### ISSUE TITLE
Help needed to run Webpack + Typescript + React with Jest

### ISSUE THREAD

**Issue by jonaslewin** [wallabyjs/public#1024]
### Issue description or question
We have issues to run the tests in wallaby. The tests are working when running npm test.

The error we get is:
```
wallaby:workers Failed to map the stack to user code, entry message: TypeError: 
Cannot read property 'cache' of undefined, stack: 
TypeError: Cannot read property 'cache' of undefined

Runtime error: TypeError: Cannot read property 'cache' of undefined
    at Object.<anonymous> (.\LongPathToFile\Button.test.js.wbp.js:1:112)
    at Runtime._execModule (C:\SourcePath\node_modules\jest-runtime\build\index.js:442:13)
```

The Button.test.js.wbp.js starts with
```
window.__moduleBundler.cache["C:\\Users\\MyUser\\AppData\\Local\\Temp\\.wallaby\\projects\\...
```

### Wallaby.js configuration file

```javascript
"use strict";

var schema = require("./schema.json");
var babelRelayPlugin = require("babel-relay-plugin");
var wallabyWebpack = require("wallaby-webpack");
var webpackPostprocessor = wallabyWebpack({
    resolve: {
        modules: ["node_modules"],
        extensions: [".webpack.js", ".web.js", ".ts", ".tsx", ".js", ".scss", ".css"]
    },
    module: {
        rules: [
            {
                test: /\.ts(x?)$/,
                use: [
                    {
                        loader: "babel-loader",
                        query: {
                            plugins: [babelRelayPlugin(schema.data)]
                        }
                    },
                    "ts-loader"
                ]
            }
        ]
    },
    externals: {
        "cheerio": "window",
        "react/addons": "react",
        "react/lib/ExecutionEnvironment": "react",
        "react/lib/ReactContext": "react"
    }
});

module.exports = function (wallaby) {
    return {
        files: [
            { pattern: "LongPathToFile/Button.tsx", load: false }
        ],
        tests: [
            { pattern: "LongPathToFile/Button.test.tsx", load: false }
        ],
        env: {
            type: "node",
            runner: "node"
        },
        testFramework: "jest",
        debug: true,
        postprocessor: webpackPostprocessor,
        bootstrap: function (wallaby) {
            wallaby.testFramework.configure({
                "transform": {
                    ".(ts|tsx)": "./dependencies/ts-jest/preprocessor.js"
                },
                "testRegex": "Button.test.tsx$",
                "moduleFileExtensions": [
                    "ts",
                    "tsx",
                    "js"
                ],
                "moduleNameMapper": {
                    "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "./dependencies/mocks/fileMock.js",
                    "\\.(css|less)$": "identity-obj-proxy"
                }
            });
            //window.__moduleBundler.loadTests();
        }
    };
};

```

### Code editor or IDE name and version

Visual Studio 2017

### OS name and version

Windows 10

**Comment by jonaslewin** [comment]
We have also tried with this configuration, producing the same error:

```javascript
"use strict";

var wallabyWebpack = require("wallaby-webpack");
var webpackPostprocessor = wallabyWebpack({
    resolve: {
        modules: ["node_modules"],
        extensions: [".webpack.js", ".web.js", ".js", ".scss", ".css"]
    },
    externals: {
        "cheerio": "window",
        "react/addons": "react",
        "react/lib/ExecutionEnvironment": "react",
        "react/lib/ReactContext": "react"
    }
});

module.exports = function (wallaby) {
    return {
        files: [
            { pattern: "LongPathToFile/Button.tsx", load: false },
            "package.json"
        ],
        tests: [
            { pattern: "LongPathToFile/Button.test.tsx", load: false }
        ],
        env: {
            type: "node",
            runner: "node"
        },
        testFramework: "jest",
        debug: true,
        postprocessor: webpackPostprocessor,
        bootstrap: function (wallaby) {
            wallaby.testFramework.configure(require("./package.json").jest);
        }
    };
};
```

**Comment by ArtemGovorov** [comment]
Jest runs in node, so you don't need to use webpack with jest (in fact wallaby doesn't even support webpack in node).

Try this config:

```javascript
module.exports = function (wallaby) {
    return {
        files: [
            "LongPathToFile/Button.tsx",
            "package.json"
        ],
        tests: [
            "LongPathToFile/Button.test.tsx"
        ],
        env: {
            type: "node",
            runner: "node"
        },
        testFramework: "jest",
        debug: true,
        bootstrap: function (wallaby) {
            wallaby.testFramework.configure(require("./package.json").jest);
        }
    };
};
```

**Comment by jonaslewin** [comment]
Thank you for the quick response.

When I try this config I get the following error:

```
​​​​​.\LongPathToFile\Button.test.js:2
import * as React from 'react';
^^^^^^
SyntaxError: Unexpected token import
    at transformAndBuildScript (C:\SourcePath\node_modules\jest-runtime\build\transform.js:320:12)
```

**Comment by ArtemGovorov** [comment]
Looks like your `tsconfig.json` is targeting ES6 (so leaves `import`s as is and node doesn't support them).

If it is the case, there're a couple of ways to make it work. You may either add a babel preprocessor, or change the `target`/`module` setting:

```javascript
var compilerOptions = require('./tsconfig.json');
compilerOptions.target = 'ES5';

module.exports = function (wallaby) {
  return {
    ...
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript(compilerOptions)
    },
    ...
  };
};
```

If it doesn't work for you, please share a small sample repo (looks like you have it isolated for one button test), I'm happy to jump in and have a look.

**Comment by jonaslewin** [comment]
As you are happy to jump in, I have added an example for you.

https://github.com/jonaslewin/typescript-webpack-react-jest-wallaby

**Comment by ArtemGovorov** [comment]
@jonaslewin Thanks for the repo.

Here are your 2 options, I have also sent you 2 pull requests:
https://github.com/jonaslewin/typescript-webpack-react-jest-wallaby/pull/1
https://github.com/jonaslewin/typescript-webpack-react-jest-wallaby/pull/2

Option 1: make wallaby compile TypeScript imports to CommonJs:

```javascript
"use strict";

var compilerOptions = require('./tsconfig.json');
compilerOptions.module = 'CommonJs';
// compilerOptions.target = 'ES5'; // may also do this if required

module.exports = function (wallaby) {
    return {
        files: [
            "site/Elements/Button/Button.tsx",
            "package.json"
        ],
        tests: [
            "site/Elements/Button/Button.test.tsx"
        ],
        env: {
            type: "node",
            runner: "node"
        },
        compilers: {
          '**/*.ts?(x)': wallaby.compilers.typeScript(compilerOptions)
        },
        testFramework: "jest",
        debug: true,
        bootstrap: function (wallaby) {
            wallaby.testFramework.configure(require("./package.json").jest);
        }
    };
};
```

Option 2: [babel preprocessor](https://wallabyjs.com/docs/config/preprocessors.html) that is using your `.babelrc` to compile TypeScript compilation result to ES5:

```javascript
"use strict";

process.env.BABEL_ENV = 'test';

module.exports = function (wallaby) {
    return {
        files: [
            "site/Elements/Button/Button.tsx",
            "package.json"
        ],
        tests: [
            "site/Elements/Button/Button.test.tsx"
        ],
        env: {
            type: "node",
            runner: "node"
        },
        preprocessors: {
          '**/*.js?(x)': file => require('babel-core')
            .transform(file.content, {babelrc: true, sourceMap: true, filename: file.path})
        },
        testFramework: "jest",
        debug: true,
        bootstrap: function (wallaby) {
            wallaby.testFramework.configure(require("./package.json").jest);
        }
    };
};
```

Both of them work for me for your repo.

**Comment by jonaslewin** [comment]
I tried option 1 and it works just fine. Thank you again very much for your help.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
