### ISSUE TITLE
Having issue with typescript compiler

### ISSUE THREAD

**Issue by rokoroku** [wallabyjs/public#1044]
### Issue description or question
I cannot find what exactly causes this issue, but I got a weird issue with wallaby's typescript compiler.
If I had a blank options to wallaby typescript compiler options like below:
```javascript
 '**/*.ts': wallaby.compilers.typeScript({})
```
This issue has gone, but without options argument like below, It causes an error.
```javascript
 '**/*.ts': wallaby.compilers.typeScript()
```

### Stacktrace
```
[Info] Started Wallaby.js Core v1.0.386
...
[Info]​​​​​ Thu, 23 Feb 2017 06:09:44 GMT wallaby:postprocessor New TypeScript language service is required
​​​​​[Info]​​​​​ Thu, 23 Feb 2017 06:09:44 GMT wallaby:postprocessor TypeScript compiler options module (before tsconfig.json): undefined
...
[Info]​​​​​ Thu, 23 Feb 2017 06:09:49 GMT wallaby:project TypeError: Cannot read property 'kind' of undefined
​​​​​[Info]​​​​​   at Object.isVariableDeclarationList (.../project/node_modules/typescript/lib/typescript.js:10192:20)
​​​​​[Info]​​​​​   at visitForStatement (.../project/node_modules/typescript/lib/typescript.js:54468:20)
​​​​​[Info]​​​​​   at visitJavaScriptInGeneratorFunctionBody (.../project/node_modules/typescript/lib/typescript.js:53559:28)
​​​​​[Info]​​​​​   at visitor (.../project/node_modules/typescript/lib/typescript.js:53511:24)
​​​​​[Info]​​​​​   at Object.visitNode (.../project/node_modules/typescript/lib/typescript.js:45551:23)
​​​​​[Info]​​​​​   at transformAndEmitForStatement (.../project/node_modules/typescript/lib/typescript.js:54460:34)
​​​​​[Info]​​​​​   at transformAndEmitStatementWorker (.../project/node_modules/typescript/lib/typescript.js:54239:28)
​​​​​[Info]​​​​​   at transformAndEmitStatement (.../project/node_modules/typescript/lib/typescript.js:54223:13)
​​​​​[Info]​​​​​   at transformAndEmitStatements (.../project/node_modules/typescript/lib/typescript.js:54207:17)
​​​​​[Info]​​​​​   at transformGeneratorFunctionBody (.../project/node_modules/typescript/lib/typescript.js:53747:13)
​​​​​[Info]​​​​​   at visitFunctionExpression (.../project/node_modules/typescript/lib/typescript.js:53677:37)
​​​​​[Info]​​​​​   at visitGenerator (.../project/node_modules/typescript/lib/typescript.js:53617:28)
​​​​​[Info]​​​​​   at visitor (.../project/node_modules/typescript/lib/typescript.js:53514:24)
​​​​​[Info]​​​​​   at visitNodes (.../project/node_modules/typescript/lib/typescript.js:45605:48)
​​​​​[Info]​​​​​   at Object.visitEachChild (.../project/node_modules/typescript/lib/typescript.js:45727:154)
​​​​​[Info]​​​​​   at visitor (.../project/node_modules/typescript/lib/typescript.js:53517:27)
​​​​​[Info]​​​​​   at visitNode (.../project/node_modules/typescript/lib/typescript.js:45551:23)
​​​​​[Info]​​​​​   at Object.visitEachChild (.../project/node_modules/typescript/lib/typescript.js:45797:46)
​​​​​[Info]​​​​​   at visitor (.../project/node_modules/typescript/lib/typescript.js:53517:27)
​​​​​[Info]​​​​​   at visitNodes (.../project/node_modules/typescript/lib/typescript.js:45605:48)
​​​​​[Info]​​​​​   at Object.visitEachChild (.../project/node_modules/typescript/lib/typescript.js:45775:45)
​​​​​[Info]​​​​​   at visitor (.../project/node_modules/typescript/lib/typescript.js:53517:27)
​​​​​[Info]​​​​​   at visitNode (.../project/node_modules/typescript/lib/typescript.js:45551:23)
​​​​​[Info]​​​​​   at visitFunctionBody (.../project/node_modules/typescript/lib/typescript.js:45659:23)
​​​​​[Info]​​​​​   at Object.visitEachChild (.../project/node_modules/typescript/lib/typescript.js:45813:397)
​​​​​[Info]​​​​​   at visitor (.../project/node_modules/typescript/lib/typescript.js:53517:27)
​​​​​[Info]​​​​​   at visitNodes (.../project/node_modules/typescript/lib/typescript.js:45605:48)
​​​​​[Info]​​​​​   at Object.visitEachChild (.../project/node_modules/typescript/lib/typescript.js:45775:45)
​​​​​[Info]​​​​​   at visitor (.../project/node_modules/typescript/lib/typescript.js:53517:27)
​​​​​[Info]​​​​​   at visitNode (.../project/node_modules/typescript/lib/typescript.js:45551:23)
​​​​​[Info]​​​​​   at visitFunctionBody (.../project/node_modules/typescript/lib/typescript.js:45659:23)
​​​​​[Info]​​​​​   at Object.visitEachChild (.../project/node_modules/typescript/lib/typescript.js:45737:342)
​​​​​[Info]​​​​​   at visitor (.../project/node_modules/typescript/lib/typescript.js:53517:27)
​​​​​[Info]​​​​​   at visitNodes (.../project/node_modules/typescript/lib/typescript.js:45605:48)
​​​​​[Info]​​​​​   at Object.visitEachChild (.../project/node_modules/typescript/lib/typescript.js:45727:154)
​​​​​[Info]​​​​​   at visitor (.../project/node_modules/typescript/lib/typescript.js:53517:27)
​​​​​[Info]​​​​​   at visitNode (.../project/node_modules/typescript/lib/typescript.js:45551:23)
​​​​​[Info]​​​​​   at Object.visitEachChild (.../project/node_modules/typescript/lib/typescript.js:45779:49)
​​​​​[Info]​​​​​   at visitor (.../project/node_modules/typescript/lib/typescript.js:53517:27)
​​​​​[Info]​​​​​   at visitNodes (.../project/node_modules/typescript/lib/typescript.js:45605:48)
​​​​​[Info]​​​​​   at visitLexicalEnvironment (.../project/node_modules/typescript/lib/typescript.js:45638:22)
​​​​​[Info]​​​​​   at Object.visitEachChild (.../project/node_modules/typescript/lib/typescript.js:45883:54)
​​​​​[Info]​​​​​   at transformSourceFile (.../project/node_modules/typescript/lib/typescript.js:53495:30)
​​​​​[Info]​​​​​   at .../project/node_modules/typescript/lib/typescript.js:2280:86
​​​​​[Info]​​​​​   at reduceLeft (.../project/node_modules/typescript/lib/typescript.js:1991:30)
​​​​​[Info]​​​​​   at .../project/node_modules/typescript/lib/typescript.js:2280:42
​​​​​[Info]​​​​​   at transformSourceFile (.../project/node_modules/typescript/lib/typescript.js:58587:20)
​​​​​[Info]​​​​​   at Object.map (.../project/node_modules/typescript/lib/typescript.js:1565:29)
​​​​​[Info]​​​​​   at Object.transformFiles (.../project/node_modules/typescript/lib/typescript.js:58568:30)
​​​​​[Info]​​​​​   at Object.emitFiles (.../project/node_modules/typescript/lib/typescript.js:61119:28)
​​​​​[Info]​​​​​   at emitWorker (.../project/node_modules/typescript/lib/typescript.js:64294:33)
​​​​​[Info]​​​​​   at .../project/node_modules/typescript/lib/typescript.js:64257:66
​​​​​[Info]​​​​​   at runWithCancellationToken (.../project/node_modules/typescript/lib/typescript.js:64347:24)
​​​​​[Info]​​​​​   at Object.emit (.../project/node_modules/typescript/lib/typescript.js:64257:20)
​​​​​[Info]​​​​​   at Object.getEmitOutput (.../project/node_modules/typescript/lib/typescript.js:81455:38)
​​​​​[Info]​​​​​   at /Users/.../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.45/wallaby/server.js:18:31673
​​​​​[Info]​​​​​   at baseFor (/Users/.../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.45/wallaby/node_modules/lodash/index.js:1971:13)
​​​​​[Info]​​​​​   at baseForOwn (/Users/.../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.45/wallaby/node_modules/lodash/index.js:2025:14)
​​​​​[Info]​​​​​   at baseEach (/Users/.../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.45/wallaby/node_modules/lodash/index.js:1814:16)
​​​​​[Info]​​​​​   at Function.forEach (/Users/.../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.45/wallaby/node_modules/lodash/index.js:5701:11)
​​​​​[Info]​​​​​   at Object.i [as postprocessor] (/Users/.../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.45/wallaby/server.js:18:31479)
​​​​​[Info]​​​​​   at /Users/.../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.45/wallaby/server.js:16:31466
​​​​​[Info]​​​​​   at Timeout._onTimeout (/Users/.../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.45/wallaby/server.js:16:31017)
​​​​​[Info]​​​​​   at ontimeout (timers.js:365:14)
​​​​​[Info]​​​​​   at tryOnTimeout (timers.js:237:5)
​​​​​[Info]​​​​​   at Timer.listOnTimeout (timers.js:207:5)
​​​​​[Info]​​​​​ From previous event:
​​​​​[Info]​​​​​   at Timeout._onTimeout (/Users/.../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.45/wallaby/server.js:16:31017)
​​​​​[Info]​​​​​   at ontimeout (timers.js:365:14)
​​​​​[Info]​​​​​   at tryOnTimeout (timers.js:237:5)
​​​​​[Info]​​​​​   at Timer.listOnTimeout (timers.js:207:5)
```
 
### Wallaby.js configuration file
```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.ts',
      '!test/**/*.spec.js'
    ],

    tests: [
      'test/**/*.spec.js'
    ],

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript()
    },

    env: {
      type: 'node'
    },

  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.9.1
Typescript 2.2.1

### OS name and version

OSX 10.12.3

**Comment by ArtemGovorov** [comment]
Could you please 
- share your `tsconfig.json`,
- try what happens without the compiler setting at all,
- try what happens if you do `npm i typescript@2.1`,
- share the file (or part of the file) that is causing the issue.
```
...
   //compilers: {
   //   '**/*.ts': wallaby.compilers.typeScript()
   // },
```

**Comment by ArtemGovorov** [comment]
Actually, I was able to reproduce the issue, so disregard my previous message. The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
