### ISSUE TITLE
Error: spawn ENOTDIR when running in webstorm

### ISSUE THREAD

**Issue by superkew** [wallabyjs/public#1058]
### Issue description or question
I get this error 6 times when running wallabyjs. Task runner doesn't run any tests.

```
Tue, 07 Mar 2017 18:37:46 GMT wallaby:project File cache requires some updates, waiting required files from IDE
Error: spawn ENOTDIR
  at exports._errnoException (util.js:874:11)
  at ChildProcess.spawn (internal/child_process.js:298:11)
  at exports.spawn (child_process.js:339:9)
  at f.spawn (/Users/.../Library/Caches/WebStorm2016.3/wallaby/wallaby/server.js:16:13090)
  at spawn (/Users/.../Library/Caches/WebStorm2016.3/wallaby/wallaby/node_modules/win-spawn/index.js:54:10)
  at startPhantomProcess (/Users/.../Library/Caches/WebStorm2016.3/wallaby/wallaby/node_modules/phantom/phantom.js:17:12)
  at Server.<anonymous> (/Users/.../Library/Caches/WebStorm2016.3/wallaby/wallaby/node_modules/phantom/phantom.js:115:14)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:166:7)
  at emitListeningNT (net.js:1260:10)
  at doNTCallback1 (node.js:430:9)
  at process._tickCallback (node.js:352:17)
```

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var wallabyPostprocessor = wallabyWebpack({
  entryPatterns: ['config/wallaby-shim.js', 'src/**/*.spec.js']
});

module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'config/wallaby-shim.ts', load: false},
      {pattern: 'src/**/*.spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*.spec.ts', load: false}
    ],

    env: {
      runner: require('phantomjs-prebuilt').path
    },
    debug: true,

    preprocessors: {
      '**/*.js': file => require('angular2-inline-template-style')(
      file.content,
      {
        base: require('path').parse(require('path').join(wallaby.localProjectDir, file.path)).dir
      })
  },


    postprocessor: wallabyPostprocessor,

    setup: function () {
    window.__moduleBundler.loadTests();
  }
};
};

```

wallaby-shim.ts
```
import 'core-js/client/shim';
import 'reflect-metadata';
import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/proxy';
import 'zone.js/dist/jasmine-patch';

import 'rxjs/Rx';

import { TestBed } from '@angular/core/testing';
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';

TestBed.initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);
```

### Code editor or IDE name and version

WebStorm 2016.3.4
Build #WS-163.13906.20, built on March 6, 2017
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
It looks like `phantomjs-prebuilt` package installation might be broken. Please try 

- stopping wallaby.js and killing all PhantomJs processes (if any are hanging),
- removing the setting (wallaby ships with the same version of PhantomJs anyway):
```
    env: {
      runner: require('phantomjs-prebuilt').path
    },
```
- if the above doesn't help, [try the Chrome/Electron runner](https://wallabyjs.com/docs/integration/electron.html) to see if it fixes the issue.

**Comment by superkew** [comment]
Removing the require fixed it.

Thank you.

Great product, and great support!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
