### ISSUE TITLE
Problems with React+Typescript+Jest Error: spawn node ENOENT

### ISSUE THREAD

**Issue by DLoT** [wallabyjs/public#1061]
### Issue description or question
Hi,

I want to check out wallaby.js with React Typescript and Jest but no luck so far...

I forked process.spawn to figure out what's missing. To me it seems that jest is executed with a wrong version and therefore `Error: spawn node ENOENT` is thrown.

I already tried the solution here https://github.com/wallabyjs/public/issues/1024
with the same result.

I'm using node 7 for wallaby but also tried the bundled version 4.2.2 with the same result.  

### process.spawn output 
```javascript
{ '0': 'node',
  '1': 
   [ '/home/dlot/.WebStorm2016.3/system/wallaby/wallaby/server.js',
     'runner',
     0,
     32925,
     'jest@0.4.3',
     '',
     '/home/dlot/work/ssi/node_modules' ],
  '2': 
   { cwd: '/home/dlot/.WebStorm2016.3/system/wallaby/projects/96cfa2219aeb5902/instrumented',
     env: 
      { PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin',
        ...
        DEBUG: 'wallaby:.*',
        DEBUG_FD: '1' } } }
``` 
 
### Wallaby.js configuration file

```javascript
"use strict";

(function() {
  var childProcess = require("child_process");
  var oldSpawn = childProcess.spawn;
  function mySpawn() {
    console.log('spawn called');
    console.log(arguments);
    var result = oldSpawn.apply(this, arguments);
    return result;
  }
  childProcess.spawn = mySpawn;
})();

const compilerOptions = require('./tsconfig.json');

module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'src/**/*.tsx', load: false}
    ],

    tests: [
      {pattern: 'src/**/*.spec.ts', load: false}
    ],

    env: {
      type: "node",
      runner: "node"
    },

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript(compilerOptions)
    },

    testFramework: "jest",
    debug: true,
    bootstrap: function (wallaby) {
      wallaby.testFramework.configure(require("./package.json").jest);
    }
  };
};

```

### tsconfig.json
```javascript
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "outDir": "./build/",
        "sourceMap": true,
        "jsx": "react"
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [
        "node_modules"
    ]
}
```
### package.json

```javascript
{
  "name": "ssi",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "jest"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },
  "devDependencies": {
    "@types/react": "^15.0.12",
    "@types/react-dom": "^0.14.23",
    "@types/jest": "^19.2.0",
    "@types/node": "^7.0.8",
    "awesome-typescript-loader": "^3.0.7",
    "babel-core": "^6.23.1",
    "babel-jest": "^19.0.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.23.0",
    "jest": "^19.0.2",
    "jest-cli": "^19.0.2",
    "react-test-renderer": "^15.4.2",
    "ts-jest": "^19.0.0",
    "typescript": "^2.2.1",
    "webpack": "^2.2.1"
  },
  "jest": {
    "transform": {
      ".(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "testRegex": "(.(test|spec))\\.(ts|tsx|js)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ]
  }
}

```

### Code editor or IDE name and version

WebStorm 2016.3.4

### OS name and version

Linux Ubuntu 16.04

**Comment by ArtemGovorov** [comment]
> `Error: spawn node ENOENT`

It looks like spawning `node` command doesn't work on your machine for some reason. If this is the case, then it shouldn't be jest/TS specific, could you try [this sample](https://github.com/wallabyjs/wallaby-node-iojs-sample) to see if the error is reproduced there as well?

Did you try removing the runner setting?
```javascript
module.exports = function (wallaby) {
  return {
    ...

    env: {
      type: "node",
      // runner: "node"
    },
```

Also try specifying an absolute path to your node executable:
```javascript
module.exports = function (wallaby) {
  return {
    ...

    env: {
      type: "node",
      runner: "/.../node" // <--- wherever it is
    },
```

**Comment by DLoT** [comment]
i got it running with `process.env.PATH=process.env.PATH+':/home/dlot/.nvm/versions/node/v7.3.0/bin'`

both of your suggestions work fine!

but no tests are found :(

```
No failing tests, 0 passing

Fri, 10 Mar 2017 14:14:22 GMT wallaby:project Wallaby config: /home/dlot/work/ssi/wallaby.js
Fri, 10 Mar 2017 14:14:22 GMT wallaby:uiService Listening port 51235
Fri, 10 Mar 2017 14:14:22 GMT wallaby:project File cache: /home/dlot/.WebStorm2016.3/system/wallaby/projects/96cfa2219aeb5902
Fri, 10 Mar 2017 14:14:22 GMT wallaby:project Config file change detected, invalidating local cache
Wallaby App available at: http://wallabyjs.com/app/#/files
Fri, 10 Mar 2017 14:14:22 GMT wallaby:workers Parallelism for initial run: 2, for regular run: 2
Fri, 10 Mar 2017 14:14:22 GMT wallaby:workers Starting run worker instance #0
Fri, 10 Mar 2017 14:14:22 GMT wallaby:workers Starting run worker instance #1
Fri, 10 Mar 2017 14:14:22 GMT wallaby:workers Web server is listening at 34391
Fri, 10 Mar 2017 14:14:22 GMT wallaby:project File cache requires some updates, waiting required files from IDE
Fri, 10 Mar 2017 14:14:22 GMT wallaby:project File package.json changes are patches only: false
Fri, 10 Mar 2017 14:14:22 GMT wallaby:project File src/index.tsx changes are patches only: false
Fri, 10 Mar 2017 14:14:22 GMT wallaby:project File src/index.spec.ts changes are patches only: false
Fri, 10 Mar 2017 14:14:22 GMT wallaby:project Preparing to process package.json
Fri, 10 Mar 2017 14:14:22 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 10 Mar 2017 14:14:22 GMT wallaby:project Preparing to process src/index.tsx
Fri, 10 Mar 2017 14:14:22 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 10 Mar 2017 14:14:22 GMT wallaby:project Preparing to process src/index.spec.ts
Fri, 10 Mar 2017 14:14:22 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 10 Mar 2017 14:14:23 GMT wallaby:workers Started run worker instance (delayed) #1
Fri, 10 Mar 2017 14:14:23 GMT wallaby:workers Started run worker instance (delayed) #0
Fri, 10 Mar 2017 14:14:23 GMT wallaby:processor No compilers found for src/index.tsx
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project File src/index.tsx is not instrumented by core
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project No preprocessors configured for src/index.tsx
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Writing to disk and caching processed file src/index.tsx
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project File src/index.tsx changes saved, store ts: 1489154799332, change ts: 1489155262928
Fri, 10 Mar 2017 14:14:23 GMT wallaby:processor No compilers found for package.json
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project File package.json is not instrumented by core
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project No preprocessors configured for package.json
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Writing to disk and caching processed file package.json
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project File package.json changes saved, store ts: 1489152451155, change ts: 1489155262920
Fri, 10 Mar 2017 14:14:23 GMT wallaby:processor No compilers found for src/index.spec.ts
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project File src/index.spec.ts is not instrumented by core
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project No preprocessors configured for src/index.spec.ts
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Writing to disk and caching processed file src/index.spec.ts
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project File src/index.spec.ts changes saved, store ts: 1489139822577, change ts: 1489155262930
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Stopping process pool
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Running postprocessor
Fri, 10 Mar 2017 14:14:23 GMT wallaby:postprocessor New TypeScript language service is required
Fri, 10 Mar 2017 14:14:23 GMT wallaby:postprocessor TypeScript compiler options module (before tsconfig.json): undefined
Fri, 10 Mar 2017 14:14:23 GMT wallaby:postprocessor TypeScript compiler options module (after tsconfig.json): 1
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Preparing to process src/index.js
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Preparing to process src/index.spec.js
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Processing compiled src/index.js
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Instrumenting src/index.js, via process pool: false
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Processing compiled src/index.spec.js
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Instrumenting src/index.spec.js, via process pool: false
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project No preprocessors configured for src/index.js
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project No preprocessors configured for src/index.spec.js
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Writing to disk and caching processed file src/index.js
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Writing to disk and caching processed file src/index.spec.js
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Postprocessor execution finished
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Test run started; run priority: 3
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Running all tests
Fri, 10 Mar 2017 14:14:23 GMT wallaby:workers Starting test run, priority: 3
Fri, 10 Mar 2017 14:14:23 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #tubvu]
Fri, 10 Mar 2017 14:14:23 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #tubvu]
Fri, 10 Mar 2017 14:14:23 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #tubvu]
Fri, 10 Mar 2017 14:14:23 GMT wallaby:workers Running tests in sandbox [worker #0, session #tubvu]
Fri, 10 Mar 2017 14:14:23 GMT wallaby:workers Loaded unknown number of test(s)
Fri, 10 Mar 2017 14:14:23 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
Fri, 10 Mar 2017 14:14:23 GMT wallaby:workers Sandbox [tubvu] is responsive, closing it
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Test run finished
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Processed console.log entries
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Processed loading sequences
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Processed executed tests
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Processed code coverage
Fri, 10 Mar 2017 14:14:23 GMT wallaby:project Test run result processed and sent to IDE
```

### jest ouput

```
➜  ssi git:(master) ✗ jest
 PASS  src/index.spec.ts
  ✓ sum (1ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.939s, estimated 1s
Ran all test suites.
```

**Comment by DLoT** [comment]
I figured out the missing tests, due to my previous attempt to use webpack I didn't load the files.

Now I'm struggling with `Error Cannot read property '_jasmineAdapter' of undefined`.
I tried https://github.com/wallabyjs/wallaby-jest-sample, with the same result...

**Comment by ArtemGovorov** [comment]
Can't reproduce the issue.  Is there any stack/file reported with the error? Also could you please paste your node modules tree structure from the  https://github.com/wallabyjs/wallaby-jest-sample sample after `npm install`.

**Comment by DLoT** [comment]
It seems this is an issue with Webstorm 2016.3.4
I've installed the WS 2017 EAP yesterday and just found out that is works there... 

Nevertheless here the output when running with WS 2016 and the tree below.  

Thank you very much for your fast support!
 
```
wallaby.js started
core v1.0.394
Runtime error: TypeError: Cannot read property '_jasmineAdapter' of undefined
    at Runtime._execModule (/home/dlot/work/wallaby-jest-sample/node_modules/jest-runtime/build/index.js:447:13)
    at Runtime.requireModule (/home/dlot/work/wallaby-jest-sample/node_modules/jest-runtime/build/index.js:295:14)
    at runTest (/home/dlot/work/wallaby-jest-sample/node_modules/jest-cli/build/runTest.js:53:10)
    at /home/dlot/work/wallaby-jest-sample/node_modules/jest-cli/build/TestRunner.js:307:14
    at process._tickCallback (node.js:368:9)
console.log:  FAIL  ../../.WebStorm2016.3/system/wallaby/projects/c45fc9a7ebfe099a/instrumented/__tests__/sum-test.js

console.log:   ● Test suite failed to run

    TypeError: Cannot read property '_jasmineAdapter' of undefined
      
      at Object.<anonymous> (../../.WebStorm2016.3/system/wallaby/wallaby/runners/node/jest@0.4.3/jasmine2Initializer.js:14:2810)
      at process._tickCallback (../../.WebStorm2016.3/system/wallaby/projects/c45fc9a7ebfe099a/instrumented/node.js:368:9)


console.log: Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.618s
```
 
```
➜  wallaby-jest-sample git:(master) ✗ npm list
/home/dlot/work/wallaby-jest-sample
└─┬ jest-cli@19.0.2
  ├── ansi-escapes@1.4.0
  ├── callsites@2.0.0
  ├─┬ chalk@1.1.3
  │ ├── ansi-styles@2.2.1
  │ ├── escape-string-regexp@1.0.5
  │ ├─┬ has-ansi@2.0.0
  │ │ └── ansi-regex@2.1.1
  │ ├── strip-ansi@3.0.1
  │ └── supports-color@2.0.0
  ├── graceful-fs@4.1.11
  ├─┬ is-ci@1.0.10
  │ └── ci-info@1.0.0
  ├─┬ istanbul-api@1.1.1
  │ ├─┬ async@2.1.5
  │ │ └── lodash@4.17.4
  │ ├─┬ fileset@2.0.3
  │ │ ├─┬ glob@7.1.1
  │ │ │ ├── fs.realpath@1.0.0
  │ │ │ ├── inflight@1.0.6
  │ │ │ └── inherits@2.0.3
  │ │ └─┬ minimatch@3.0.3
  │ │   └─┬ brace-expansion@1.1.6
  │ │     ├── balanced-match@0.4.2
  │ │     └── concat-map@0.0.1
  │ ├─┬ istanbul-lib-hook@1.0.0
  │ │ └─┬ append-transform@0.4.0
  │ │   └─┬ default-require-extensions@1.0.0
  │ │     └─┬ strip-bom@2.0.0
  │ │       └── is-utf8@0.2.1
  │ ├─┬ istanbul-lib-report@1.0.0-alpha.3
  │ │ ├── async@1.5.2
  │ │ ├── path-parse@1.0.5
  │ │ ├── rimraf@2.6.1
  │ │ └─┬ supports-color@3.2.3
  │ │   └── has-flag@1.0.0
  │ ├─┬ istanbul-lib-source-maps@1.1.0
  │ │ └── source-map@0.5.6
  │ ├─┬ istanbul-reports@1.0.1
  │ │ └─┬ handlebars@4.0.6
  │ │   ├── async@1.5.2
  │ │   ├─┬ optimist@0.6.1
  │ │   │ └── wordwrap@0.0.3
  │ │   ├─┬ source-map@0.4.4
  │ │   │ └── amdefine@1.0.1
  │ │   └─┬ uglify-js@2.8.11
  │ │     ├── uglify-to-browserify@1.0.2
  │ │     └─┬ yargs@3.10.0
  │ │       ├── camelcase@1.2.1
  │ │       ├─┬ cliui@2.1.0
  │ │       │ ├─┬ center-align@0.1.3
  │ │       │ │ ├─┬ align-text@0.1.4
  │ │       │ │ │ └── longest@1.0.1
  │ │       │ │ └── lazy-cache@1.0.4
  │ │       │ ├── right-align@0.1.3
  │ │       │ └── wordwrap@0.0.2
  │ │       └── window-size@0.1.0
  │ ├─┬ js-yaml@3.8.2
  │ │ ├─┬ argparse@1.0.9
  │ │ │ └── sprintf-js@1.0.3
  │ │ └── esprima@3.1.3
  │ ├─┬ mkdirp@0.5.1
  │ │ └── minimist@0.0.8
  │ └─┬ once@1.4.0
  │   └── wrappy@1.0.2
  ├── istanbul-lib-coverage@1.0.1
  ├─┬ istanbul-lib-instrument@1.4.2
  │ ├─┬ babel-generator@6.23.0
  │ │ ├── babel-messages@6.23.0
  │ │ ├─┬ babel-runtime@6.23.0
  │ │ │ ├── core-js@2.4.1
  │ │ │ └── regenerator-runtime@0.10.3
  │ │ ├─┬ detect-indent@4.0.0
  │ │ │ └─┬ repeating@2.0.1
  │ │ │   └── is-finite@1.0.2
  │ │ ├── jsesc@1.3.0
  │ │ └── trim-right@1.0.1
  │ ├── babel-template@6.23.0
  │ ├─┬ babel-traverse@6.23.1
  │ │ ├─┬ babel-code-frame@6.22.0
  │ │ │ └── js-tokens@3.0.1
  │ │ ├─┬ debug@2.6.1
  │ │ │ └── ms@0.7.2
  │ │ ├── globals@9.16.0
  │ │ └─┬ invariant@2.2.2
  │ │   └── loose-envify@1.3.1
  │ ├─┬ babel-types@6.23.0
  │ │ ├── esutils@2.0.2
  │ │ └── to-fast-properties@1.0.2
  │ ├── babylon@6.16.1
  │ └── semver@5.3.0
  ├── jest-changed-files@19.0.2
  ├─┬ jest-config@19.0.2
  │ ├── jest-environment-node@19.0.2
  │ ├─┬ jest-resolve@19.0.2
  │ │ ├─┬ browser-resolve@1.11.2
  │ │ │ └── resolve@1.1.7
  │ │ └── resolve@1.3.2
  │ ├── jest-validate@19.0.2
  │ └─┬ pretty-format@19.0.0
  │   └─┬ ansi-styles@3.0.0
  │     └─┬ color-convert@1.9.0
  │       └── color-name@1.1.1
  ├─┬ jest-environment-jsdom@19.0.2
  │ ├── jest-mock@19.0.0
  │ └─┬ jsdom@9.11.0
  │   ├── abab@1.0.3
  │   ├── acorn@4.0.11
  │   ├── acorn-globals@3.1.0
  │   ├── array-equal@1.0.0
  │   ├── content-type-parser@1.0.1
  │   ├── cssom@0.3.2
  │   ├── cssstyle@0.2.37
  │   ├─┬ escodegen@1.8.1
  │   │ ├── esprima@2.7.3
  │   │ ├── estraverse@1.9.3
  │   │ ├─┬ optionator@0.8.2
  │   │ │ ├── deep-is@0.1.3
  │   │ │ ├── fast-levenshtein@2.0.6
  │   │ │ ├── levn@0.3.0
  │   │ │ ├── prelude-ls@1.1.2
  │   │ │ ├── type-check@0.3.2
  │   │ │ └── wordwrap@1.0.0
  │   │ └── source-map@0.2.0
  │   ├── html-encoding-sniffer@1.0.1
  │   ├── nwmatcher@1.3.9
  │   ├── parse5@1.5.1
  │   ├─┬ request@2.81.0
  │   │ ├── aws-sign2@0.6.0
  │   │ ├── aws4@1.6.0
  │   │ ├── caseless@0.12.0
  │   │ ├─┬ combined-stream@1.0.5
  │   │ │ └── delayed-stream@1.0.0
  │   │ ├── extend@3.0.0
  │   │ ├── forever-agent@0.6.1
  │   │ ├─┬ form-data@2.1.2
  │   │ │ └── asynckit@0.4.0
  │   │ ├─┬ har-validator@4.2.1
  │   │ │ ├─┬ ajv@4.11.4
  │   │ │ │ └── co@4.6.0
  │   │ │ └── har-schema@1.0.5
  │   │ ├─┬ hawk@3.1.3
  │   │ │ ├── boom@2.10.1
  │   │ │ ├── cryptiles@2.0.5
  │   │ │ ├── hoek@2.16.3
  │   │ │ └── sntp@1.0.9
  │   │ ├─┬ http-signature@1.1.1
  │   │ │ ├── assert-plus@0.2.0
  │   │ │ ├─┬ jsprim@1.3.1
  │   │ │ │ ├── extsprintf@1.0.2
  │   │ │ │ ├── json-schema@0.2.3
  │   │ │ │ └── verror@1.3.6
  │   │ │ └─┬ sshpk@1.11.0
  │   │ │   ├── asn1@0.2.3
  │   │ │   ├── assert-plus@1.0.0
  │   │ │   ├── bcrypt-pbkdf@1.0.1
  │   │ │   ├─┬ dashdash@1.14.1
  │   │ │   │ └── assert-plus@1.0.0
  │   │ │   ├── ecc-jsbn@0.1.1
  │   │ │   ├─┬ getpass@0.1.6
  │   │ │   │ └── assert-plus@1.0.0
  │   │ │   ├── jodid25519@1.0.2
  │   │ │   ├── jsbn@0.1.1
  │   │ │   └── tweetnacl@0.14.5
  │   │ ├── is-typedarray@1.0.0
  │   │ ├── isstream@0.1.2
  │   │ ├── json-stringify-safe@5.0.1
  │   │ ├─┬ mime-types@2.1.14
  │   │ │ └── mime-db@1.26.0
  │   │ ├── oauth-sign@0.8.2
  │   │ ├── performance-now@0.2.0
  │   │ ├── qs@6.4.0
  │   │ ├── safe-buffer@5.0.1
  │   │ ├── stringstream@0.0.5
  │   │ ├── tunnel-agent@0.6.0
  │   │ └── uuid@3.0.1
  │   ├── sax@1.2.2
  │   ├── symbol-tree@3.2.2
  │   ├─┬ tough-cookie@2.3.2
  │   │ └── punycode@1.4.1
  │   ├── webidl-conversions@4.0.1
  │   ├─┬ whatwg-encoding@1.0.1
  │   │ └── iconv-lite@0.4.13
  │   ├─┬ whatwg-url@4.5.0
  │   │ ├── tr46@0.0.3
  │   │ └── webidl-conversions@3.0.1
  │   └── xml-name-validator@2.0.1
  ├─┬ jest-haste-map@19.0.0
  │ ├─┬ fb-watchman@2.0.0
  │ │ └─┬ bser@2.0.0
  │ │   └── node-int64@0.4.0
  │ └─┬ sane@1.5.0
  │   ├─┬ anymatch@1.3.0
  │   │ └── arrify@1.0.1
  │   ├─┬ exec-sh@0.2.0
  │   │ └── merge@1.2.0
  │   ├─┬ fb-watchman@1.9.2
  │   │ └── bser@1.0.2
  │   ├── minimist@1.2.0
  │   ├─┬ walker@1.0.7
  │   │ └─┬ makeerror@1.0.11
  │   │   └── tmpl@1.0.4
  │   └── watch@0.10.0
  ├─┬ jest-jasmine2@19.0.2
  │ ├── jest-matcher-utils@19.0.0
  │ └── jest-matchers@19.0.0
  ├── jest-message-util@19.0.0
  ├── jest-regex-util@19.0.0
  ├─┬ jest-resolve-dependencies@19.0.0
  │ └── jest-file-exists@19.0.0
  ├─┬ jest-runtime@19.0.2
  │ ├─┬ babel-core@6.23.1
  │ │ ├── babel-helpers@6.23.0
  │ │ ├─┬ babel-register@6.23.0
  │ │ │ ├─┬ home-or-tmp@2.0.0
  │ │ │ │ ├── os-homedir@1.0.2
  │ │ │ │ └── os-tmpdir@1.0.2
  │ │ │ └── source-map-support@0.4.11
  │ │ ├── convert-source-map@1.4.0
  │ │ ├── json5@0.5.1
  │ │ ├── path-is-absolute@1.0.1
  │ │ └── private@0.1.7
  │ ├─┬ babel-jest@19.0.0
  │ │ └─┬ babel-preset-jest@19.0.0
  │ │   └── babel-plugin-jest-hoist@19.0.0
  │ ├─┬ babel-plugin-istanbul@4.0.0
  │ │ ├─┬ find-up@2.1.0
  │ │ │ └─┬ locate-path@2.0.0
  │ │ │   ├─┬ p-locate@2.0.0
  │ │ │   │ └── p-limit@1.1.0
  │ │ │   └── path-exists@3.0.0
  │ │ └─┬ test-exclude@4.0.0
  │ │   └── object-assign@4.1.1
  │ ├─┬ json-stable-stringify@1.0.1
  │ │ └── jsonify@0.0.0
  │ └── strip-bom@3.0.0
  ├─┬ jest-snapshot@19.0.2
  │ ├─┬ jest-diff@19.0.0
  │ │ └── diff@3.2.0
  │ └── natural-compare@1.4.0
  ├─┬ jest-util@19.0.2
  │ └── leven@2.1.0
  ├─┬ micromatch@2.3.11
  │ ├─┬ arr-diff@2.0.0
  │ │ └── arr-flatten@1.0.1
  │ ├── array-unique@0.2.1
  │ ├─┬ braces@1.8.5
  │ │ ├─┬ expand-range@1.8.2
  │ │ │ └─┬ fill-range@2.2.3
  │ │ │   ├── is-number@2.1.0
  │ │ │   ├─┬ isobject@2.1.0
  │ │ │   │ └── isarray@1.0.0
  │ │ │   ├── randomatic@1.1.6
  │ │ │   └── repeat-string@1.6.1
  │ │ ├── preserve@0.2.0
  │ │ └── repeat-element@1.1.2
  │ ├─┬ expand-brackets@0.1.5
  │ │ └── is-posix-bracket@0.1.1
  │ ├── extglob@0.3.2
  │ ├── filename-regex@2.0.0
  │ ├── is-extglob@1.0.0
  │ ├── is-glob@2.0.1
  │ ├─┬ kind-of@3.1.0
  │ │ └── is-buffer@1.1.4
  │ ├── normalize-path@2.0.1
  │ ├─┬ object.omit@2.0.1
  │ │ ├─┬ for-own@0.1.5
  │ │ │ └── for-in@1.0.2
  │ │ └── is-extendable@0.1.1
  │ ├─┬ parse-glob@3.0.4
  │ │ ├─┬ glob-base@0.3.0
  │ │ │ └── glob-parent@2.0.0
  │ │ └── is-dotfile@1.0.2
  │ └─┬ regex-cache@0.4.3
  │   ├── is-equal-shallow@0.1.3
  │   └── is-primitive@2.0.0
  ├─┬ node-notifier@5.0.2
  │ ├── growly@1.3.0
  │ └── shellwords@0.1.0
  ├── slash@1.0.0
  ├── string-length@1.0.1
  ├── throat@3.0.0
  ├─┬ which@1.2.12
  │ └── isexe@1.1.2
  ├─┬ worker-farm@1.3.1
  │ ├─┬ errno@0.1.4
  │ │ └── prr@0.0.0
  │ └── xtend@4.0.1
  └─┬ yargs@6.6.0
    ├── camelcase@3.0.0
    ├─┬ cliui@3.2.0
    │ └── wrap-ansi@2.1.0
    ├── decamelize@1.2.0
    ├── get-caller-file@1.0.2
    ├─┬ os-locale@1.4.0
    │ └─┬ lcid@1.0.0
    │   └── invert-kv@1.0.0
    ├─┬ read-pkg-up@1.0.1
    │ ├─┬ find-up@1.1.2
    │ │ ├── path-exists@2.1.0
    │ │ └─┬ pinkie-promise@2.0.1
    │ │   └── pinkie@2.0.4
    │ └─┬ read-pkg@1.1.0
    │   ├─┬ load-json-file@1.1.0
    │   │ ├─┬ parse-json@2.2.0
    │   │ │ └─┬ error-ex@1.3.1
    │   │ │   └── is-arrayish@0.2.1
    │   │ └── pify@2.3.0
    │   ├─┬ normalize-package-data@2.3.6
    │   │ ├── hosted-git-info@2.2.0
    │   │ ├─┬ is-builtin-module@1.0.0
    │   │ │ └── builtin-modules@1.1.1
    │   │ └─┬ validate-npm-package-license@3.0.1
    │   │   ├─┬ spdx-correct@1.0.2
    │   │   │ └── spdx-license-ids@1.2.2
    │   │   └── spdx-expression-parse@1.0.4
    │   └── path-type@1.1.0
    ├── require-directory@2.1.1
    ├── require-main-filename@1.0.1
    ├── set-blocking@2.0.0
    ├─┬ string-width@1.0.2
    │ ├── code-point-at@1.1.0
    │ └─┬ is-fullwidth-code-point@1.0.0
    │   └── number-is-nan@1.0.1
    ├── which-module@1.0.0
    ├── y18n@3.2.1
    └─┬ yargs-parser@4.2.1
      └── camelcase@3.0.0
```

**Comment by ArtemGovorov** [comment]
This is interesting, because it shouldn't depend on the WS version. Is that the same local repo folder you're opening? Are you mostly using WS 2017 EAP now or still the previous version? Could you please try deleting the node modules folder and re-running `npm install`?

**Comment by DLoT** [comment]
Yes, it's the same folder.

I just reinstalled the node modules, invalidated the cache in WS 2016.3 and restarted, still the same result.

I'll use the 2017 EAP for now, shouldn't take too long for the final release.

Next week I'll try wallaby on a huge nodejs/typescript project with jasmine and WS 2016.3. 

I let you know if it works there.

**Comment by ArtemGovorov** [comment]
> I'll use the 2017 EAP for now, shouldn't take too long for the final release.
>  project with jasmine

Great, thanks for the update.
Jasmine shouldn't have the issue, it's definitely jest integration specific, so I'll close then issue for now, but surely let me know if something else doesn't work in the jasmine/ts/node project. 

If you need to make the current work in WS 2016.3, let me know and after the weekend I'll build a core with some additional logging to try troubleshooting the issue.
