### ISSUE TITLE
Wallaby is choking on tsconfig generated by `tcs --init`

### ISSUE THREAD

**Issue by zubivan** [wallabyjs/public#1174]
### Issue description or question

Just created a new typescript project with Wallaby and when running a first test noticed that wallaby is choking on comments in tsconfig file. Please see the repo here:

https://github.com/zubivan/wallaby-typescript-init

```javascript
​​[Error] Failed to load configuration file:  SyntaxError: c:\source\wallaby-issue\tsconfig.json: Unexpected token / in JSON at position 31​​
​​[Error]   at Object.parse (native)​​
​​[Error]   at Module.s.require (C:\Users\izu\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.50\wallaby\server.js:19:16559)​​
​​[Error]   at require (internal/module.js:20:19)​​
​​[Error]   at Object.<anonymous> (c:\source\wallaby-issue\wallaby.js:1:85)​​
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.431
```

### Wallaby.js configuration file

```javascript
var compilerOptions = require('./tsconfig.json');

module.exports = function (wallaby) {
    return {
        files: [
            { pattern: './node_modules/**/*.*', instrument: false, load: false, ignore: true },
            { pattern: './**/*.spec.ts*', instrument: false, load: false, ignore: true },
            { pattern: './**/*.test.ts*', instrument: false, load: false, ignore: true },
            { pattern: './**/*.ts*', instrument: true, load: false, ignore: false },
            'package.json',
            'tsconfig.json'
        ],
        tests: [
            '**/*.spec.ts*'
        ],
        env: {
            type: 'node',
            runner: 'node'
        },
        // compilers: {
        //     '**/*.ts?(x)': wallaby.compilers.typeScript(compilerOptions)
        // },
        testFramework: 'jest',
        setup: function (wallaby) {
            const jestConfig = require("./package.json").jest;
            delete jestConfig.transform;
            wallaby.testFramework.configure(jestConfig);
        },
        maxConsoleMessagesPerTest: 10000,
        slowTestThreshold: 10000,
        debug: true
    }
};

```

### Code editor or IDE name and version

Visual Studio Code v1.12.2

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
It doesn't look like it's wallaby itself doing anything wrong. It's the way node.js works - you are `require`-ing the `tsconfig.json` file in your wallaby config:
```javascript
var compilerOptions = require('./tsconfig.json');
```
and node.js doesn't like comments in JSON files. 

You are not using the `compilerOptions` anyway, so you may remove the line and everything should work for you.
