### ISSUE TITLE
tsx test file runtime error: Unexpected token <

### ISSUE THREAD

**Issue by joelhoward0** [wallabyjs/public#1207]
I have a simple React component test with a .tsx extension that is failing to run under wallaby with the error "Unexpected token <".

### My test file
```
import * as React from 'react'

import { AppComponent } from 'components/app'

describe("AppComponent", () => {
  it("renders", () => {
    let context = {} as any;
    let app = <AppComponent context={context} />
  });
});
```
Here is the resulting .js file in the wallaby project cache, which throws the syntax error when wallaby tries to run it:
```
'use strict';
$_$wp(1);
$_$w(1, 0), exports.__esModule = true;
var React = ($_$w(1, 1), require('react'));
var app_1 = ($_$w(1, 2), require('components/app'));
$_$w(1, 3), describe('AppComponent', function () {
    $_$wf(1);
    $_$w(1, 4), it('renders', function () {
        $_$wf(1);
        var context = ($_$w(1, 5), {});
        var app = ($_$w(1, 6), <app_1.AppComponent context={context}/>);
    });
});
$_$wpe(1);
```
As you can see the jsx syntax is inserted as-is, but of course isn't valid javascript.
### Wallaby.js configuration file
```
module.exports = function(wallaby) {
  var path = require('path');

  process.env.NODE_PATH += 
    path.delimiter + path.join(wallaby.projectCacheDir, 'client/components') +
    path.delimiter + path.join(wallaby.projectCacheDir, 'domain') +
    path.delimiter + path.join(wallaby.projectCacheDir, 'combat') +
    path.delimiter + path.join(wallaby.projectCacheDir);

  return {
    files: [
      'domain/**/*.ts',
      'client/**/*.ts*',
      'domain/*.ts',
      'test/data/*.ts',
      'test/firebase-test-config.ts'
    ],
    tests: [
      'test/app-component-tests.tsx'
    ],
    env: {
      type: 'node'
    }
  }
}
```
I also tried with 
```
compilers: { 
  "**/*.ts": wallaby.compilers.typeScript({
    module: 'commonjs',
    jsx: 'react'
}) 
```
directly in my wallaby.js, without success.
### tsconfig.json
```
{
  "compilerOptions": {
    "strictNullChecks": true,
    "module": "commonjs",
    "sourceMap": true,
    "outDir": "./compiledts",
    "target": "es6",
    "baseUrl": ".",
    "paths": {
      "routes/*": ["client/components/routes/*"],
      "components/*": ["client/components/*"],
      "hex/*": ["domain/hex/*"],
      "combat/*": ["domain/combat/*"]
    },
    "jsx": "react"
  },
  "exclude": [
    "node_modules",
    "typings/browser",
    "typings/browser.d.ts",
    "firebase"
  ],
  "compileOnSave": false
}
```
I'm using Typescript 2.2.2, Sublime Text 3 Stable Build 3126, on Windows 10. The test runs directly in mocha with ts-node.

**Comment by ArtemGovorov** [comment]
It looks like your `tsconfig.json` is not being applied for some reason. Wallaby loads it automatically if it's located in the project's root (also [adding the `debug: true` setting](https://wallabyjs.com/docs/intro/get-started-sublime.html#troubleshooting) should result in printing some messages about loading the tsconfig file or some errors/warnings about not finding it). If the file is not in the project's root then adding the `compilers` section should do the trick.

The `compilers` section you've tried only includes `.ts` files (because of the specified file pattern `**/*.ts`) and your component file is probably `.tsx` - this is why it didn't work. Try using the [example from the docs](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings) with the pattern that includes `.tsx` files:

```javascript
...
compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({
        module: 'commonjs',
        jsx: 'react'
      })
},
```

**Comment by joelhoward0** [comment]
@ArtemGovorov Unfortunately, I see the same issue when I add the aforementioned compilers setting. My wallaby.js:
```
module.exports = function(wallaby) {
  var path = require('path');

  process.env.NODE_PATH += 
    path.delimiter + path.join(wallaby.projectCacheDir, 'client/components') +
    path.delimiter + path.join(wallaby.projectCacheDir, 'domain') +
    path.delimiter + path.join(wallaby.projectCacheDir, 'combat') +
    path.delimiter + path.join(wallaby.projectCacheDir);

  return {
    files: [
      'domain/**/*.ts',
      'client/**/*.ts?(x)',
      'domain/*.ts',
      'test/data/*.ts',
      'test/firebase-test-config.ts'
    ],
    tests: [
      'test/app-component-tests.tsx'
    ],
    env: {
      type: 'node'
    },
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({
        module: 'commonjs',
        jsx: 'react'
      })
    }
  }
}
```
I messed with some other settings and can confirm this wallaby.js is the one being used. Commenting out the lines that actually contain tsx syntax causes the .tsx test files to run correctly.

**Comment by ArtemGovorov** [comment]
I have created [this sample repo](https://github.com/ArtemGovorov/wallaby-1207) with your config, file structure and your TypeScript config. It's working for me (though I had to add this line because the import is done as `components/app`, so `client` needs to be added as a root as well - however this is a different issue that should not affect TypeScript compilation). 

Please try the repo to see if it's working for you. If it is, please try to add the missing details from your project to reproduce the issue.

**Comment by joelhoward0** [comment]
@ArtemGovorov I see the same issue with provided repo. I suspected a problem with my Sublime Wallaby installation, but uninstalling and reinstalling it had no effect.

I actually tried the repo you provided on a second computer, and found the same issue. I am going to try changing typescript and react versions and see if it gets me anywhere.

**Comment by ArtemGovorov** [comment]
Could you please do this:
- close all Sublime Text instances,
- open the `C:\Users\joelh\AppData\Roaming\Sublime Text 3\Packages\Wallaby\wallaby\package.json` file and paste the `"version"` from the file,
- delete the `C:\Users\joelh\AppData\Roaming\Sublime Text 3\Packages\Wallaby\wallaby\` folder,
- open the sample project in Sublime Text, wait until wallaby core is installed (progress bar in the bottom left corner),
- open wallaby.js config and change it (even a space anywhere in the config is enough), save the config (leave the `debug: true` option there).
- start wallaby.js and paste the output from the wallaby console with `debug: true`, juts like you have already done.

**Comment by joelhoward0** [comment]
@ArtemGovorov Done - the version in package.json was 1.0.321 (same before and after deleting C:\Users\joelh\AppData\Roaming\Sublime Text 3\Packages\Wallaby\wallaby and reinstalling). Here is the output:

```
[Info]: wallaby.js started[Info]: wallaby.js started​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:52 GMT wallaby:project Wallaby config: C:\git\wallaby-test\wallaby.js​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:52 GMT wallaby:fs File added: test/app-component-tests.tsx​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:52 GMT wallaby:fs File added: client/components/app.tsx​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:53 GMT wallaby:fs File system scan has finished by timeout​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:53 GMT wallaby:project File cache: C:\Users\joelh\AppData\Roaming\Sublime Text 3\Packages\Wallaby\projects\526149addc756d8f​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:53 GMT wallaby:uiService Listening port 51235​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:53 GMT wallaby:project Config file change detected, invalidating local cache​​​​​
​​​​​[Info]: Wallaby App available at: http://wallabyjs.com/app/#/files​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:53 GMT wallaby:workers Parallelism for initial run: 1, for regular run: 1​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:53 GMT wallaby:workers Starting run worker instance #0​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:53 GMT wallaby:workers Web server is listening at 61400​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:53 GMT wallaby:project File cache requires some updates, waiting required files from IDE​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:53 GMT wallaby:project File test/app-component-tests.tsx changes are patches only: false​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:53 GMT wallaby:project File client/components/app.tsx changes are patches only: false​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:53 GMT wallaby:project Preparing to process test/app-component-tests.tsx​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:53 GMT wallaby:project Starting processor pool (if not yet started)​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:53 GMT wallaby:project Preparing to process client/components/app.tsx​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:53 GMT wallaby:project Starting processor pool (if not yet started)​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:workers Started run worker instance (delayed) #0​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:processor No compilers found for test/app-component-tests.tsx​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project File test/app-component-tests.tsx is not instrumented by core​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project No preprocessors configured for test/app-component-tests.tsx​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Writing to disk and caching processed file test/app-component-tests.tsx​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project File test/app-component-tests.tsx changes saved, store ts: 1498526568617, change ts: 1498531073267​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:processor No compilers found for client/components/app.tsx​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project File client/components/app.tsx is not instrumented by core​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project No preprocessors configured for client/components/app.tsx​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Writing to disk and caching processed file client/components/app.tsx​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project File client/components/app.tsx changes saved, store ts: 1498526551709, change ts: 1498531073269​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Stopping process pool​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Running postprocessor​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:postprocessor New TypeScript language service is required​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Preparing to process client/components/app.js​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Preparing to process test/app-component-tests.js​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Processing compiled client/components/app.js​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Instrumenting client/components/app.js, via process pool: false​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Processing compiled test/app-component-tests.js​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Instrumenting test/app-component-tests.js, via process pool: false​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project No preprocessors configured for client/components/app.js​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project No preprocessors configured for test/app-component-tests.js​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Writing to disk and caching processed file client/components/app.js​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Writing to disk and caching processed file test/app-component-tests.js​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Postprocessor execution finished​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Test run started; run priority: 3​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Running all tests​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:workers Starting test run, priority: 3​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #84h1s]​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #84h1s]​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #84h1s]​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:workers Running tests in sandbox [worker #0, session #84h1s]​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:workers Sandbox (active) [84h1s] error: C:\Users\joelh\AppData\Roaming\Sublime Text 3\Packages\Wallaby\projects\526149addc756d8f\instrumented\test\app-component-tests.js:11​​​​​
​​[Error]: Runtime error: .\test\app-component-tests.js:11​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:workers Failed to map the stack to user code, entry message: C:\Users\joelh\AppData\Roaming\Sublime Text 3\Packages\Wallaby\projects\526149addc756d8f\instrumented\test\app-component-tests.js:11, stack: C:\Users\joelh\AppData\Roaming\Sublime Text 3\Packages\Wallaby\projects\526149addc756d8f\instrumented\test\app-component-tests.js:11​​​​​
​​[Error]:         var app = ($_$w(1, 6), <app_1.AppComponent context={context}/>);​​
​​​​​[Info]:         var app = ($_$w(1, 6), <app_1.AppComponent context={context}/>);​​​​​
​​[Error]:                                ^​​
​​​​​[Info]:                                ^​​​​​
​​[Error]: SyntaxError: Unexpected token <​​
​​​​​[Info]: SyntaxError: Unexpected token <​​​​​
​​[Error]:     at Object.exports.runInThisContext (vm.js:76:16)​​
​​​​​[Info]:     at Object.exports.runInThisContext (vm.js:76:16)​​​​​
​​[Error]:     at Module._compile (module.js:542:28)​​
​​​​​[Info]:     at Module._compile (module.js:542:28)​​​​​
​​[Error]:     at Object.Module._extensions..js (module.js:579:10)​​
​​[Error]:     at Module.load (module.js:487:32)​​
​​​​​[Info]:     at Object.Module._extensions..js (module.js:579:10)​​​​​
​​[Error]:     at tryModuleLoad (module.js:446:12)​​
​​​​​[Info]:     at Module.load (module.js:487:32)​​​​​
​​[Error]:     at Function.Module._load (module.js:438:3)​​
​​​​​[Info]:     at tryModuleLoad (module.js:446:12)​​​​​
​​​​​[Info]:     at Function.Module._load (module.js:438:3)​​​​​
​​​​​[Info]:     at Module.require (module.js:497:17)​​​​​
​​[Error]:     at Module.require (module.js:497:17)​​
​​​​​[Info]:     at Module.s.require (C:\Users\joelh\AppData\Roaming\Sublime Text 3\Packages\Wallaby\wallaby\server.js:18:30828)​​​​​
​​[Error]:     at require (internal/module.js:20:19)​​
​​​​​[Info]:     at require (internal/module.js:20:19)​​​​​
​​​​​[Info]:     at C:\Users\joelh\AppData\Roaming\Sublime Text 3\Packages\Wallaby\wallaby\runners\node\mocha@2.1.0\framework\lib\mocha.js:14:2502​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:workers Sandbox [84h1s] is responsive, closing it​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Test run finished​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Processed console.log entries​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Processed loading sequences​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Processed executed tests​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Processed code coverage​​​​​
​​​​​[Info]: Tue, 27 Jun 2017 02:37:54 GMT wallaby:project Test run result processed and sent to IDE​​​​​
```

**Comment by ArtemGovorov** [comment]
It looks like your license key had expired, so the old version of wallaby core is installed. Did you [enter your new license key](https://wallabyjs.com/docs/intro/license.html#sublime-text) after you have renewed your license? If not, try pasting the new key (that you should have received when renewing the license) and [try performing the same actions](https://github.com/wallabyjs/public/issues/1207#issuecomment-311234833) (it should happen automatically, but just to force the process let's do it manually).

**Comment by joelhoward0** [comment]
@ArtemGovorov That solved it - I guess I hadn't entered the new license key on either of my machines. I wasn't seeing the expired license notification that prompted me to renew in the first place, so I didn't realize I wasn't on the latest version. Everything ran correctly first try on the latest core version.

Thanks so much for all your help! Wallaby & your support are best in class.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
