### ISSUE TITLE
Unexpected token only in index.tsx with TypeScript + Webpack

### ISSUE THREAD

**Issue by timothymclane** [wallabyjs/public#1214]
### Issue description or question
I am having issues getting TypeScript + Wallaby + Webpack working. I have tried options from the example TypeScript repos, but they don't seem to solve the module parse error I'm running into.

Tests do seem to run and pass/fail, with editor integration and all, but if I change a watched file, I get the module parse error. This eventually causes Wallaby to crash.

The issue only seems to occur in my base index.tsx. I don't get errors from any other TypeScript file, so I'm a bit baffled.

The contents of the Wallaby.js Tests output window

```
​​​​​0 failing tests, 46 passing​​​​​
​​​​​​​​​​
​​Module parse failed: c:\git\events-admin-ui\src\index.tsx Unexpected token (13:4)​​
​​You may need an appropriate loader to handle this file type.​​
​​| 
​​
​​| ReactDOM.render(
​​
​​|     <Provider store={store}>
​​
​​|         <ConnectedRouter history={history}>
​​
​​|             <Route path="/" component={App} />
ModuleParseError: Module parse failed: c:\git\events-admin-ui\src\index.tsx Unexpected token (13:4)​​
​​You may need an appropriate loader to handle this file type.​​
​​| 
​​
​​| ReactDOM.render(
​​
​​|     <Provider store={store}>
​​
​​|         <ConnectedRouter history={history}>
​​
​​|             <Route path="/" component={App} />
​​
​​  at doBuild.e (c:\git\events-admin-ui\node_modules\webpack\lib\NormalModule.js:296:19)​​
​​  at c:\git\events-admin-ui\node_modules\loader-runner\lib\LoaderRunner.js:370:3​​
​​  at iterateNormalLoaders (c:\git\events-admin-ui\node_modules\loader-runner\lib\LoaderRunner.js:211:10)​​
​​  at c:\git\events-admin-ui\node_modules\loader-runner\lib\LoaderRunner.js:202:4​​
​​  at c:\git\events-admin-ui\node_modules\graceful-fs\graceful-fs.js:78:16​​
​​  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)​​
```

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackConfig = require('./webpack.config.js');
var webpackPostprocessor = wallabyWebpack(webpackConfig);

webpackConfig.resolve.extensions = ['.js', '.json'];
webpackConfig.module.rules = []
webpackConfig.plugins = []
var wallabyPostprocessor = wallabyWebpack(webpackConfig);

module.exports = function (wallaby) {

  return {
    testFramework: 'mocha',
    files: [
      { pattern: 'src/**/*.ts?(x)', load: false },
      { pattern: 'src/**/*.unit.ts?(x)', ignore: true }
    ],

    tests: [
      { pattern: 'src/**/*.unit.ts?(x)', load: false }
    ],

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript()
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

### tsconfig.json
```javascript
{
  "compilerOptions": {
    "sourceMap": true,
    "target": "es5",
    "jsx": "react",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "declaration": false,
    "noImplicitAny": false,
    "noImplicitReturns": false,
    "removeComments": true,
    "strictNullChecks": false,
    "outDir": "build",
    "lib": [
      "es6",
      "es7",
      "dom"
    ]
  },
  "exclude": [
    "dist",
    "build",
    "node_modules"
  ]
}
```

### OS name and version
Visual Studio Code v1.13.1
Windows 10

**Comment by ArtemGovorov** [comment]
Looks like you're creating 2 postprocessors in your config, but only using the first one, while should be using the second one. Try this config:

```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackConfig = require('./webpack.config.js');
webpackConfig.resolve.extensions = ['.js', '.json'];
webpackConfig.module.rules = []
webpackConfig.plugins = []
var wallabyPostprocessor = wallabyWebpack(webpackConfig);

module.exports = function (wallaby) {

  return {
    testFramework: 'mocha',
    files: [
      { pattern: 'src/**/*.ts?(x)', load: false },
      { pattern: 'src/**/*.unit.ts?(x)', ignore: true }
    ],

    tests: [
      { pattern: 'src/**/*.unit.ts?(x)', load: false }
    ],

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript()
    },

    postprocessor: wallabyPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

If it doesn't work for you, please let me know the following:
- Where from exactly and how the `c:\git\events-admin-ui\src\index.tsx` file is imported in your code? Is it imported with the `.tsx` extension name?
- Share your `webpack.config.js` file content.

**Comment by timothymclane** [comment]
I removed the extra postprocessor, but same error message.

./src/index.tsx is the entry point of the application. The only place it is referenced is inside the Webpack config. It's not imported into any other file.

Here's the project's webpack.config.js:
```javascript
var webpack = require('webpack');
var path = require('path');

// variables
var isProduction = process.argv.indexOf('-p') >= 0;
var sourcePath = path.join(__dirname, './src');
var outPath = path.join(__dirname, './dist');

console.log('isProd: ', isProduction)

// plugins
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var CleanWebpackPlugin = require('clean-webpack-plugin');

module.exports = {
    context: sourcePath,
    devtool: 'cheap-module-source-map',
    entry: {
        main: './index.tsx',
        vendor: [
            'react',
            'react-dom',
            'react-redux',
            'react-router',
            'redux'
        ]
    },
    externals: {
        'react/addons': true,
        'react/lib/ExecutionEnvironment': true,
        'react/lib/ReactContext': true,
        'react-addons-test-utils': true,
    },
    output: {
        path: outPath,
        publicPath: '',
        filename: 'scripts/bundle.js',
    },
    target: 'web',
    resolve: {
        extensions: ['.js', '.ts', '.tsx'],
        // Fix webpack's default behavior to not load packages with jsnext:main module
        // https://github.com/Microsoft/TypeScript/issues/11677
        mainFields: ['main']
    },
    module: {
        rules: [
            // .ts, .tsx
            {
                test: /\.tsx?$/,
                enforce: 'pre',
                loader: 'tslint-loader',
                options: { failOnHint: true }
            },
            {
                test: /\.tsx?$/,
                use: isProduction
                    ? 'awesome-typescript-loader'
                    : [
                        'react-hot-loader',
                        'awesome-typescript-loader'
                    ]
            },
            // css
            {
                test: /\.less$/,
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: [
                        {
                            loader: 'css-loader',
                            query: {
                                modules: false,
                                sourceMap: !isProduction,
                                importLoaders: 1,
                            }
                        },
                        {
                            loader: 'less-loader'
                        }
                    ]
                })
            },
            // static assets
            { test: /\.html$/, use: 'html-loader' },
            { test: /\.ico$/, use: 'file-loader?name=[name].[ext]' },
            { test: /\.(png|jpg)$/, use: 'file-loader' },
            { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url-loader?limit=10000&mimetype=application/font-woff" },
            { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "file-loader" }
        ],
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            filename: 'scripts/vendor.bundle.js',
            minChunks: Infinity
        }),
        new webpack.optimize.AggressiveMergingPlugin(),
        new webpack.NamedModulesPlugin(),
        new HtmlWebpackPlugin({
            template: 'index.html'
        }),
        new webpack.DefinePlugin(
            {
                'process.env': {
                    NODE_ENV: isProduction ? JSON.stringify('production') : JSON.stringify('dev')
                }
            }
        ),
        new ExtractTextPlugin({
            filename: 'dist/style.css',
            disable: !isProduction
        }),
        new CleanWebpackPlugin('dist')
    ],
    devServer: {
        contentBase: sourcePath,
        hot: true,
        stats: {
            warnings: false
        },
    },
    node: {
        // workaround for webpack-dev-server issue
        // https://github.com/webpack/webpack-dev-server/issues/60#issuecomment-103411179
        fs: 'empty',
        net: 'empty'
    }
};
```

**Comment by ArtemGovorov** [comment]
Try removing the `context` setting:
```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackConfig = require('./webpack.config.js');
webpackConfig.resolve.extensions = ['.js', '.json'];
webpackConfig.module.rules = [];
webpackConfig.plugins = [];
delete webpackConfig.context; // <---
var wallabyPostprocessor = wallabyWebpack(webpackConfig);
...
```

If it doesn't help, try passing an empty object as webpack config (to check if there's something in your webpack config that causing the issue):

```javascript
var wallabyWebpack = require('wallaby-webpack');
var wallabyPostprocessor = wallabyWebpack({});
...
```

If nothing from the above helps, please create a sample repo reproducing the issue - I'll have look into it.

**Comment by timothymclane** [comment]
Yeah, it's something in my Webpack config. Not sure what was causing it. The empty object tripped me up a bit since we're using Enzyme and needed the externals, but it's working now.

```javascript
var wallabyWebpack = require('wallaby-webpack');

var wallabyPostprocessor = wallabyWebpack({
  externals: {
    'react/addons': true,
    'react/lib/ExecutionEnvironment': true,
    'react/lib/ReactContext': true,
    'react-addons-test-utils': true,
  }
});

module.exports = function (wallaby) {
  return {
    testFramework: 'mocha',
    files: [
      { pattern: 'src/**/*.ts?(x)', load: false },
      { pattern: 'src/**/*.unit.ts?(x)', ignore: true }
    ],

    tests: [
      { pattern: 'src/**/*.unit.ts?(x)', load: false }
    ],

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript()
    },

    postprocessor: wallabyPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

Thanks so much for your help! 😀

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
