### ISSUE TITLE
Babel error starting wallaby in atom with create-react-app

### ISSUE THREAD

**Issue by cmcnamara87** [wallabyjs/public#1238]
### Issue description or question
I am unable to start Wallaby in Atom.

Error in Wallaby Focus Panel:

```
Failed to run compilers on src/App.js, Error: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: "undefined". (While processing preset: "/Users/usersname/Sites/form/node_modules/babel-preset-react-app/index.js")
  at Object.<anonymous> (/Users/usersname/Sites/form/node_modules/babel-preset-react-app/index.js:49:9)
  at require (internal/module.js:20:19)
  at /Users/usersname/Sites/form/node_modules/babel-core/lib/transformation/file/options/option-manager.js:296:17
  at Array.map (native)
  at OptionManager.mergePresets (/Users/usersname/Sites/form/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
  at OptionManager.mergeOptions (/Users/usersname/Sites/form/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
  at OptionManager.init (/Users/usersname/Sites/form/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
  at File.initOptions (/Users/usersname/Sites/form/node_modules/babel-core/lib/transformation/file/index.js:212:65)
  at new File (/Users/usersname/Sites/form/node_modules/babel-core/lib/transformation/file/index.js:135:24)
  at Pipeline.transform (/Users/usersname/Sites/form/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Wallaby.js configuration file
```javascript
module.exports = function(wallaby) {
  // Babel, jest-cli and some other modules are located under
  // react-scripts/node_modules, so need to let node.js know about it
  var path = require('path');
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, 'node_modules') +
    path.delimiter +
    path.join(__dirname, 'node_modules/react-scripts/node_modules');
  require('module').Module._initPaths();

  // Babel needs this
  process.env.NODE_ENV = 'development';

  return {
    files: ['src/**/*.js', '!src/**/*.test.js'],

    tests: ['src/**/*.test.js'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['react-app']
      })
    },

    setup: wallaby => {
      wallaby.testFramework.configure({
        // as in node_modules/react-scripts/utils/createJestConfig.js
        testURL: 'http://localhost',
        setupFiles: [
          require('path').join(
            wallaby.localProjectDir,
            'node_modules/react-scripts/config/polyfills.js'
          )
        ],
        moduleNameMapper: {
          '^.+\\.(jpg|jpeg|png|gif|svg)$': require.resolve(
            'react-scripts/config/jest/fileTransform.js'
          ),
          '^.+\\.css$': require.resolve(
            'react-scripts/config/jest/cssTransform.js'
          ),
          '^react-native$': 'react-native-web'
        }
      });
    },

    testFramework: 'jest'
  };
};

```

### Code editor or IDE name and version
Atom v1.18.0

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Just tried to create a fresh `create-react-app` and paste your wallaby config - everything is working for me.

<img width="833" alt="screen shot 2017-07-24 at 2 30 41 pm" src="https://user-images.githubusercontent.com/979966/28508224-cd125b26-707c-11e7-908c-76709df56c52.png">

This line in your wallaby config is supposed to set what `babel-preset-react-app` needs:
```javascript
  process.env.NODE_ENV = 'development';
```

However, the error source `/Users/usersname/Sites/form/node_modules/babel-preset-react-app/index.js:49:9`, and the earlier assignment in the file:

```javascript
var env = process.env.BABEL_ENV || process.env.NODE_ENV;
``` 
and also the error message, specifically this bit: `Instead, received: "undefined".`, makes me think that something in your Atom setup is setting `process.env.BABEL_ENV` to `'undefined'` (as a string), otherwise it would work (or the error would say `Instead, received: undefined.`, because the value is written `JSON.stringify(...)` at `babel-preset-react-app/index.js:49:9`).

You may either investigate what exactly is setting process.env.BABEL_ENV to the string `"undefined"`, or just overwrite the value in wallaby config:
```javascript
//process.env.NODE_ENV = 'development';
process.env.BABEL_ENV = process.env.NODE_ENV = 'development';
```

Hope it makes sense.
