### ISSUE TITLE
Fails to find file, seems like CWD is getting altered

### ISSUE THREAD

**Issue by wldcordeiro** [wallabyjs/public#1250]
### Issue description or question

So I'm having a really bizarre failure. It just started occurring and I'm not sure what the fix here is. I haven't modified my project at all and my coworker was able to run wallaby with no issues from the same branch. Below is my config file and the error. Now it's telling me that the file in reference isn't found in `/src/file-uploading-tile/error.png` but the problem here is that the import it's failing at is a relative import `import errorImg from './error.png'` and it appears that Wallaby is trying to search from `/` and not the project which would just be `src/file-uploading-tile/error.png` above. I've tried clearing my Wallaby cache (rm -rf ~/.atom/packages/atom-wallaby/wallaby), and I've tried removing my node_modules dir and installing again with no success.

### Wallaby.js configuration file

```javascript
process.env.BABEL_ENV = 'babel'
process.env.NODE_ENV = 'test'
module.exports = function(wallaby) {
	return {
		files: [
			{ pattern: 'src/**/*.js', instrument: true, load: false },
			{ pattern: '**/*.snap', instrument: false },
			{ pattern: 'src/**/*.mock.js', instrument: false, load: false },
			{ pattern: 'src/**/*.png', instrument: false, load: false },
			{ pattern: 'src/**/*.story.js', ignore: true },
			{ pattern: 'src/**/*.test.js', ignore: true },
		],
		tests: [{ pattern: 'src/**/*.test.js' }],
		env: {
			type: 'node',
			runner: 'node',
		},
		testFramework: 'jest',
		compilers: {
			'src/**/*.js': wallaby.compilers.babel(),
		},
	}
}

```

ERROR:

```
Failed to run compilers on src/file-uploading-tile/left-space.js, Error: src/file-uploading-tile/left-space.js: Cannot find module '/src/file-uploading-tile/error.png'
  at require (internal/module.js:11:18)
  at PluginPass.CallExpression (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-plugin-transform-assets/lib/index.js:67:19)
  at newFn (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/visitors.js:276:21)
  at NodePath._call (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/path/context.js:76:18)
  at NodePath.call (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/path/context.js:48:17)
  at NodePath.visit (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/path/context.js:105:12)
  at TraversalContext.visitQueue (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/context.js:150:16)
  at TraversalContext.visitSingle (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/context.js:108:19)
  at TraversalContext.visit (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/context.js:192:19)
  at Function.traverse.node (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/index.js:114:17)
  at NodePath.visit (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/path/context.js:115:19)
  at TraversalContext.visitQueue (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/context.js:150:16)
  at TraversalContext.visitMultiple (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/context.js:103:17)
  at TraversalContext.visit (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/context.js:190:19)
  at Function.traverse.node (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/index.js:114:17)
  at NodePath.visit (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/path/context.js:115:19)
  at TraversalContext.visitQueue (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/context.js:150:16)
  at TraversalContext.visitSingle (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/context.js:108:19)
  at TraversalContext.visit (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/context.js:192:19)
  at Function.traverse.node (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/index.js:114:17)
  at traverse (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-traverse/lib/index.js:79:12)
  at File.transform (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-core/lib/transformation/file/index.js:548:35)
  at /Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-core/lib/transformation/pipeline.js:50:19
  at File.wrap (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-core/lib/transformation/file/index.js:564:16)
  at Pipeline.transform (/Users/wellingtoncordeiro/Documents/projects/matchsticks/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
  at _combinedTickCallback (internal/process/next_tick.js:95:7)
  at process._tickCallback (internal/process/next_tick.js:161:9)
  at emitTwo (events.js:125:13)
  at process.emit (events.js:213:7)
  at handleMessage (internal/child_process.js:753:14)
  at Pipe.channel.onread (internal/child_process.js:472:11)
  at _combinedTickCallback (internal/process/next_tick.js:95:7)
  at process._tickCallback (internal/process/next_tick.js:161:9)
```

### Code editor or IDE name and version

Atom v1.19beta5

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Looks like it is a babel issue, wallaby.js doesn't even get a chance the run the tests.

Could you please share your `.babelrc` and `package.json` files?

> my coworker was able to run wallaby with no issues from the same branch

Is your co-worker using the same version of Atom? 
Perhaps there are some babel related ENV vars your editor has configured? You may check Atom Dev Tools, Console: `process.env`.

**Comment by wldcordeiro** [comment]
`.babelrc`

```
{
	"env": {
		"babel": {
			"presets": [
				"es2015",
				"react"
			],
			"plugins": [
				"transform-object-rest-spread",
				"transform-class-properties",
				"transform-react-jsx-source",
				["transform-assets", {
					"extensions": ["png", "svg"],
					"name": "[name].[ext]?[sha512:hash:base64:7]",
					"limit": 10000
				}],
				"polypackage"
			]
		},
		"rollup": {
			"presets": [
				["babel-preset-es2015", { "modules": false }],
				"react"
			],
			"plugins": [
				"transform-object-rest-spread",
				"transform-class-properties",
				"external-helpers"
			]
		}
	}
}
```

`package.json`

```json
{
  "name": "---",
  "version": "---",
  "description": "---",
  "main": "dist/index.js",
  "jsnext:main": "dist-es/index.js",
  "module": "dist-es/index.js",
  "homepage": "---",
  "repository": {
    "type": "git",
    "url": "git@---"
  },
  "author": "---",
  "license": "SEE LICENSE IN LICENSE",
  "peerDependencies": {
    "glamor": "2.x",
    "prop-types": "15.x",
    "react": "15.x"
  },
  "scripts": {
    "build": "run-s clean build:* test:build",
    "build:babel": "NODE_ENV=production BABEL_ENV=babel babel src -d dist --ignore *.test.js,*.story.js,*.mock.js",
    "build:rollup": "NODE_ENV=production BABEL_ENV=rollup rollup -c config/rollup.config.js",
    "clean": "rimraf dist dist-es \"!(wallaby.conf).js\"",
    "format": "prettier-eslint --write \"src/**/*.js\" \"config/*.js\" \"dist-test/*.js\" \"*.js\"",
    "lint": "eslint src config dist-test wallaby.conf.js",
    "test": "BABEL_ENV=babel jest",
    "test:build": "BABEL_ENV=babel babel-node dist-test/index.js",
    "start": "NODE_ENV=development BABEL_ENV=babel start-storybook -p 9001 -c .storybook",
    "validate": "run-s \"test -- --coverage\" build",
    "precommit": "lint-staged",
    "prepush": "run-s validate",
    "build-storybook": "BABEL_ENV=babel build-storybook -s src -o public"
  },
  "devDependencies": {
    "@storybook/addon-actions": "3.1.9",
    "@storybook/addon-info": "3.1.9",
    "@storybook/addon-knobs": "3.1.9",
    "@storybook/react": "3.1.9",
    "babel-cli": "6.24.1",
    "babel-eslint": "7.2.3",
    "babel-plugin-external-helpers": "6.22.0",
    "babel-plugin-polypackage": "2.0.0-beta.1",
    "babel-plugin-transform-assets": "0.2.0",
    "babel-plugin-transform-class-properties": "6.24.1",
    "babel-plugin-transform-es2015-modules-commonjs": "6.24.1",
    "babel-plugin-transform-object-rest-spread": "6.23.0",
    "babel-plugin-transform-react-jsx-source": "6.22.0",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-react": "6.24.1",
    "css-wipe": "4.3.0",
    "enzyme": "2.9.1",
    "enzyme-to-json": "1.5.1",
    "eslint": "4.3.0",
    "eslint-config-inferno": "1.0.1",
    "eslint-config-inferno-react": "1.0.1",
    "glamor": "2.20.37",
    "husky": "0.14.3",
    "jest": "20.0.4",
    "jest-glamor-react": "3.1.0",
    "jsdom": "11.1.0",
    "lint-staged": "4.0.2",
    "npm-run-all": "4.0.2",
    "prettier-eslint-cli": "4.1.1",
    "prettysize": "0.1.0",
    "prop-types": "15.5.10",
    "react": "15.6.1",
    "react-addons-test-utils": "15.6.0",
    "react-dom": "15.6.1",
    "react-test-renderer": "15.6.1",
    "rimraf": "2.6.1",
    "rollup": "0.45.2",
    "rollup-plugin-babel": "2.7.1",
    "rollup-plugin-bundle-size": "1.0.1",
    "rollup-plugin-commonjs": "8.0.2",
    "rollup-plugin-img": "1.0.6",
    "rollup-plugin-json": "2.3.0",
    "rollup-plugin-node-resolve": "3.0.0",
    "rollup-plugin-uglify": "2.0.1"
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.js",
      "!**/*.story.js",
      "!**/*.mock.js",
      "!**/*.test.js"
    ],
    "setupTestFrameworkScriptFile": "<rootDir>/config/jest-setup.js",
    "transformIgnorePatterns": [
      "/node_modules/"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>/dist/",
      "<rootDir>/dist-es/",
      "<rootDir>/node_modules/"
    ],
    "snapshotSerializers": [
      "jest-glamor-react",
      "enzyme-to-json/serializer"
    ],
  },
    "parser": "babel-eslint"
  },
  "lint-staged": {
    "*.js": [
      "prettier-eslint --write",
      "git add"
    ]
  },
  "dependencies": {
    "polished": "1.3.0",
    "react-transition-group": "1.2.0",
    "recompose": "0.24.0"
  }
}
```

This same repo was working for me yesterday and we haven't had any changes in our package.json or babelrc in a week according to git.

**Comment by ArtemGovorov** [comment]
I'm not sure why it's happening, but looks like your `process.env.PWD` (that the `transform-asset` babel package is using) is incorrectly set somewhere (maybe by Atom). 

We have released a new version where we force setting it to a correct value. Please update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version, and the issue should be resolved for you.

Not related to the issue, but I'd also suggest changing your snapshot pattern to be more specific, from 
```javascript
{ pattern: '**/*.snap', instrument: false },
```
to 
```javascript
{ pattern: 'src/**/*.snap', instrument: false },
```
This should make wallaby startup faster (because it doesn't need to scan your `node_modules` for `.snap` files).

**Comment by wldcordeiro** [comment]
Thanks @ArtemGovorov everything is working again! 😄 I'm loving Wallaby :D Now Quokka for Atom would be awesome is that something we can vote on?

**Comment by ArtemGovorov** [comment]
@wldcordeiro Awesome, thanks! Yes, please vote for the Atom version for Quokka here: https://github.com/wallabyjs/quokka/issues/20
