### ISSUE TITLE
jest 21 error: error: TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by breathe** [wallabyjs/public#1293]
### Issue description or question

I see a lot of errors like this in wallaby console output after upgrading to jest 21.

The test suite appears to be mostly working though ...  I can't tell if anything new is misbehaving yet.

```
​​​​​[Info]​​​​​ Thu, 07 Sep 2017 00:49:13 GMT wallaby:workers Failed to map the stack to user code, entry message: TypeError: Path must be a string. Received undefined, stack: TypeError: Path must be a string. Received undefined
​​​​​[Info]​​​​​     at assertPath (path.js:7:11)
​​​​​[Info]​​​​​     at Object.relative (path.js:1226:5)
​​​​​[Info]​​​​​     at buffer.reduce (/Users/bcohen/software/masslight/conversational_assistants/node_modules/jest-util/build/get_console_output.js:21:46)
​​​​​[Info]​​​​​     at Array.reduce (native)
​​​​​[Info]​​​​​     at module.exports (/Users/bcohen/software/masslight/conversational_assistants/node_modules/jest-util/build/get_console_output.js:20:17)
​​​​​[Info]​​​​​     at DefaultReporter._printTestFileSummary (/Users/bcohen/software/masslight/conversational_assistants/node_modules/jest/node_modules/jest-cli/build/reporters/default_reporter.js:185:62)
​​​​​[Info]​​​​​     at DefaultReporter.onTestResult (/Users/bcohen/software/masslight/conversational_assistants/node_modules/jest/node_modules/jest-cli/build/reporters/default_reporter.js:163:10)
​​​​​[Info]​​​​​     at /Users/bcohen/software/masslight/conversational_assistants/node_modules/jest/node_modules/jest-cli/build/reporter_dispatcher.js:46:24
​​​​​[Info]​​​​​     at Generator.next (<anonymous>)
​​​​​[Info]​​​​​     at step (/Users/bcohen/software/massligh
​​[Error] Runtime error: TypeError: Path must be a string. Received undefined​​
​​[Error]     at assertPath (path.js:7:11)​​
​​[Error]     at Object.relative (path.js:1226:5)​​
​​[Error]     at buffer.reduce (/Users/bcohen/software/masslight/conversational_assistants/node_modules/jest-util/build/get_console_output.js:21:46)​​
​​[Error]     at Array.reduce (native)​​
​​[Error]     at module.exports (/Users/bcohen/software/masslight/conversational_assistants/node_modules/jest-util/build/get_console_output.js:20:17)​​
​​[Error]     at DefaultReporter._printTestFileSummary (/Users/bcohen/software/masslight/conversational_assistants/node_modules/jest/node_modules/jest-cli/build/reporters/default_reporter.js:185:62)​​
​​[Error]     at DefaultReporter.onTestResult (/Users/bcohen/software/masslight/conversational_assistants/node_modules/jest/node_modules/jest-cli/build/reporters/default_reporter.js:163:10)​​
​​[Error]     at /Users/bcohen/software/masslight/conversational_assistants/node_modules/jest/node_modules/jest-cli/build/reporter_dispatcher.js:46:24​​
​​[Error]     at Generator.next (<anonymous>)​​
​​[Error]     at step (/Users/bcohen/software/masslight/conversational_assistants/node_modules/jest/node_modules/jest-cli/build/reporter_dispatcher.js:1:260)​​
​​[Error]     at /Users/bcohen/software/masslight/conversational_assistants/node_modules/jest/node_modules/jest-cli/build/reporter_dispatcher.js:1:490​​
​​[Error]     at /Users/bcohen/software/masslight/conversational_assistants/node_modules/jest/node_modules/jest-cli/build/reporter_dispatcher.js:1:171​​
​​[Error]     at ReporterDispatcher.onTestResult (/Users/bcohen/software/masslight/conversational_assistants/node_modules/jest/node_modules/jest-cli/build/reporter_dispatcher.js:47:10)​​
​​[Error]     at /Users/bcohen/software/masslight/conversational_assistants/node_modules/jest/node_modules/jest-cli/build/test_scheduler.js:101:35​​
​​[Error]     at Generator.next (<anonymous>)​​
​​[Error]     at step (/Users/bcohen/software/masslight/conversational_assistants/node_modules/jest/node_modules/jest-cli/build/test_scheduler.js:30:405)​​
​​[Error]     at /Users/bcohen/software/masslight/conversational_assistants/node_modules/jest/node_modules/jest-cli/build/test_scheduler.js:30:635​​
​​[Error]     at /Users/bcohen/software/masslight/conversational_assistants/node_modules/jest/node_modules/jest-cli/build/test_scheduler.js:30:316​​
​​[Error]     at onResult (/Users/bcohen/software/masslight/conversational_assistants/node_modules/jest/node_modules/jest-cli/build/test_scheduler.js:103:59)​​
​​[Error]     at /Users/bcohen/software/masslight/conversational_assistants/node_modules/jest-runner/build/index.js:79:46​​
​​​​​[Info]​​​​​ Thu, 07 Sep 2017 00:49:13 GMT wallaby:workers Test executed: handler should provide expected responses when invoked
​​​​​[Info]​​​​​ console.error: PASS ../../../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/projects/d7ebb1959fdf7908/instrumented/src/Lambda/ai-help/intermediary.test.js
​​​​​[Info]​​​​​ console.error: FAIL ../../../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/projects/d7ebb1959fdf7908/instrumented/src/Lambda/ai-help/intermediary.test.js
​​​​​[Info]​​​​​ console.error:   ● Test suite failed to run
​​​​​[Info]​​​​​     TypeError: Path must be a string. Received undefined
​​​​​[Info]​​​​​       
​​​​​[Info]​​​​​       at assertPath (../../../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/projects/d7ebb1959fdf7908/instrumented/path.js:7:11)
​​​​​[Info]​​​​​       at Object.relative (../../../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/projects/d7ebb1959fdf7908/instrumented/path.js:1226:5)
​​​​​[Info]​​​​​       at Array.reduce (native)
​​​​​[Info]​​​​​           at Generator.next (<anonymous>)
​​​​​[Info]​​​​​           at Generator.next (<anonymous>)
​​​​​[Info]​​​​​ Thu, 07 Sep 2017 00:49:13 GMT wallaby:workers Run 6 test(s), skipped 0 test(s)
​​​​​[Info]​​​​​ console.error: Test Suites: 1 failed, 2 passed, 3 of 2 total
​​​​​[Info]​​​​​ Tests:       6 passed, 6 total
​​​​​[Info]​​​​​ Snapshots:   6 passed, 6 total
​​​​​[Info]​​​​​ Time:        5.158s
​​​​​[Info]​​​​​ Ran all test suites.
```

### Wallaby.js configuration file

```javascript
module.exports = function() {
  return {
    files: [
      "package.json",
      "tsconfig.json",
      ".secrets/*",
      "resources/**/*",
      "src/**/*.yml",
      "src/**/*.ts",
      "serverless-services/*",
      "serverless-services/**/*.yml",
      "!lib/**",
      "!src/**/*.test.ts"
    ],

    tests: ["src/**/*.test.ts", "!src/service-tests/**/*"],

    env: {
      type: "node",
      runner: "node"
    },

    debug: true,
    testFramework: "jest",

    setup: function(wallaby) {
      var jestConfig = require("./package.json").jest;
      jestConfig.moduleNameMapper = {
        "^.*/Configuration/(.*)-shim.js$":
          wallaby.projectCacheDir + "/src/Configuration/$1",
        "^.*/lib/ServerlessPlugins/(.*)$":
          wallaby.projectCacheDir + "/src/ServerlessPlugins/$1"
      };
      wallaby.testFramework.configure(jestConfig);
    }
  };
};
```

### Code editor or IDE name and version

Visual Studio v1.15.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Thanks for the report.

The Jest 21 integration issue is fixed in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.
