### ISSUE TITLE
jest 21 failure with '_loadConfigDependencies' of undefined

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#1302]
### Issue description or question
I'm seeing another failue with jest 21, reproducible repo at https://github.com/kwonoj/emscripten-wasm-loader. 
VS CODE / npm@5.4.1 / windows / Core v1.0.488 . stacktraces are

```
[Error] Runtime error: jest-cli node module is not found or the version is not supported, missing `npm install jest --save-dev` or `npm install jest-cli --save-dev`?​​
​​[Error] TypeError: Cannot read property '_loadConfigDependencies' of undefined​​
​​[Error]     at Module._compile (module.js:573:30)​​
​​[Error]     at Object.Module._extensions..js (module.js:584:10)​​
​​[Error]     at Module.load (module.js:507:32)​​
​​[Error]     at tryModuleLoad (module.js:470:12)​​
​​[Error]     at Function.Module._load (module.js:462:3)​​
​​[Error]     at Module.require (module.js:517:17)​​
​​[Error]     at require (internal/module.js:11:18)​​
​​[Error]     at Module._compile (module.js:573:30)​​
​​[Error]     at Object.Module._extensions..js (module.js:584:10)​​
​​[Error]     at Module.load (module.js:507:32)​​
​​[Error]     at tryModuleLoad (module.js:470:12)​​
​​[Error]     at Function.Module._load (module.js:462:3)​​
​​[Error]     at Function.Module.runMain (module.js:609:10)​​
​​[Error]     at startup (bootstrap_node.js:158:16)​​
​​[Error]     at bootstrap_node.js:598:3​​
​​​​​[Info]​​​​​ Thu, 14 Sep 2017 07:02:37 GMT wallaby:workers Failed to map the stack to user code, entry message: jest-cli node module is not found or the version is not supported, missing `npm install jest --save-dev` or `npm install jest-cli --save-dev`?
​​​​​[Info]​​​​​ TypeError: Cannot read property '_loadConfigDependencies' of undefined, stack: jest-cli node module is not found or the version is not supported, missing `npm install jest --save-dev` or `npm install jest-cli --save-dev`?
​​​​​[Info]​​​​​ TypeError: Cannot read property '_loadConfigDependencies' of undefined
​​​​​[Info]​​​​​     at Object.<anonymous> (C:\Users\kwono\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.59\wallaby\runners\node\jest@0.4.3\initializer.js:14:6050)
​​​​​[Info]​​​​​     at Module._compile (module.js:573:30)
​​​​​[Info]​​​​​     at Object.Module._extensions..js (module.js:584:10)
​​​​​[Info]​​​​​     at Module.load (module.js:507:32)
​​​​​[Info]​​​​​     at tryModuleLoad (module.js:470:12)
​​​​​[Info]​​​​​     at Function.Module._load (module.js:462:3)
​​​​​[Info]​​​​​     at Module.require (module.js:517:17)
​​​​​[Info]​​​​​     at Module.r.require (C:\Users\kwono\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.59\wallaby\server.js:19:29641)
​​​​​[Info]​​​​​     at require (internal/module.js:11:18)
​​​​​[Info]​​​​​     at r (C:\Users\kwono\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.59\wallaby\server.js:14:114)
​​​​​[Info]​​​​​     at C:\Users\kwono\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.59\wallaby\server.js:14:305
​​​​​[Info]​​​​​     at m (C:\Users\kwono\.vscode\ext
​​​​​[Info]​​​​​ Thu, 14 Sep 2017 07:02:37 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
​​
```

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

WebStorm v?
IntelliJ IDEA v?
Visual Studio v?
Atom v1.?
Visual Studio Code v1.?
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
Thanks for the report. Looks like Jest 21.0.2 is working fine, but Jest 21.1.0 (released today) had introduced some breaking changes. The compatibility issue is fixed in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.
