### ISSUE TITLE
​​ReferenceError: window is not defined​​

### ISSUE THREAD

**Issue by andyjessop** [wallabyjs/public#1314]
### Issue description or question
I'm using Jest and I'm getting the following error:
```
​​ReferenceError: window is not defined​​
​​    at emitTwo (events.js:125:13)​​
​​    at WebSocket.emit (events.js:213:7)​​
​​    at afterWrite (_stream_writable.js:430:3)​​
​​    at onwrite (_stream_writable.js:421:7)​​
​​    at afterTransform (_stream_transform.js:102:3)​​
​​    at TransformState.afterTransform (_stream_transform.js:75:12)​​
​​    at Zlib.callback (zlib.js:471:7)​​
```
When I run `jest` from the console and on CircleCI, the tests pass.

So I guess this is something to do with it running on node

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      { pattern: 'src/**/*.js', load: false },
      { pattern: '!src/**/*.spec.js', load: false }
    ],

    tests: [
      { pattern: 'src/**/*.spec.js', load: false }
    ],

    debug: true,

    testFramework: 'jest',

    env: {
      type: 'node'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    setup: function () {
      // required to trigger test loading
      window.__moduleBundler.loadTests();
    }
  };
};
```
### Jest Config in package.json
```
"jest": {
    "moduleFileExtensions": [
      "js",
      "vue",
      "json",
      "node"
    ],
    "testMatch": [
      "<rootDir>/src/**/*.test.js"
    ],
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
      ".*\\.(vue)$": "<rootDir>/node_modules/jest-vue-preprocessor"
    }
  }
```
### Code editor or IDE name and version
VSCode 1.16.0

### OS name and version
OSX Yosemite

**Comment by ArtemGovorov** [comment]
The error is coming from the `setup` function of your wallaby config where you do `window.__moduleBundler.loadTests();`.

It looks like your config is taken from webpack/browser examples of wallaby.js configs, as it contains a lot of webpack specific things, including the one causing the error. [Wallaby config for Jest](https://wallabyjs.com/docs/integration/jest.html) looks a bit different.

Here's how your config may look like:

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.js',
      '!src/**/*.spec.js'
    ],

    tests: [
       'src/**/*.spec.js'
    ],

    debug: true,

    testFramework: 'jest',

    env: {
      type: 'node'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    }
  };
};
```
