### ISSUE TITLE
Error with Wallaby VS Code loading Babel config 

### ISSUE THREAD

**Issue by RishiSpeets** [wallabyjs/public#1320]
### Issue description or question
When starting up Wallaby using the Wallaby Start command in VS Code, the following error gets thrown (including stack trace):

```
​​[Error] Failed to load configuration file:  /Users/rishi/www/GitHub/CP2-dashboard/.babelrc:2​​
​​[Error]   "presets": [​​
​​[Error]            ^​​
​​[Error] SyntaxError: Unexpected token :​​
​​[Error]   at createScript (vm.js:56:10)​​
​​[Error]   at Object.runInThisContext (vm.js:97:10)​​
​​[Error]   at Module.i._compile (/Users/rishi/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.60/wallaby/server.js:15:21530)​​
​​[Error]   at Module.r.require (/Users/rishi/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.60/wallaby/server.js:19:29672)​​
​​[Error]   at require (internal/module.js:20:19)​​
​​[Error]   at module.exports.wallaby (/Users/rishi/www/GitHub/CP2-dashboard/.wallaby.js:22:40)​​
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.494
```

Using Jest (21.1.0) as test framework. All tests pass when ran with jest-cli.

### Wallaby.js configuration file

```javascript
process.env.BABEL_ENV = "test";

module.exports = wallaby => ({
  files: [
    "src/**/*.js",
    "src/**/*.json",
    "package.json",
    "!src/**/*.test.js",
    "./__mocks__/*"
  ],

  tests: ["src/**/*.test.js"],

  env: {
    type: "node",
    runner: "node"
  },

  testFramework: "jest",

  compilers: {
    "**/*.js": wallaby.compilers.babel(require()) // eslint-disable-line global-require
  }
});
```

### Babel config
```
{
  "presets": [
    "react",
    [
      "env",
      {
        "targets": {
          "browsers": ["last 2 versions"]
        },
        "modules": false,
        "loose": true
      }
    ]
  ],
  "plugins": [
    "transform-runtime",
    "transform-object-rest-spread",
    "transform-es2015-modules-commonjs",
    "transform-decorators-legacy",
    "transform-class-properties",
    "react-hot-loader/babel"
  ],
  "env": {
    "test": {
      "plugins": [
        "transform-runtime",
        "transform-object-rest-spread",
        "transform-es2015-modules-commonjs",
        "transform-decorators-legacy",
        "transform-class-properties"
      ]
    }
  }
}
```

### Jest config
```
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}",
      "!src/**/*.test.{js,jsx}",
      "!src/*/RbGenerated*/*.{js,jsx}",
      "!src/index.js"
    ],
    "coverageThreshold": {
      "global": {
        "statements": 98,
        "branches": 91,
        "functions": 98,
        "lines": 98
      }
    },
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
    "moduleNameMapper": {
      ".*\\.(css|less|styl|scss|sass)$": "<rootDir>/__mocks__/styleMock.js",
      ".*\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js"
    }
  }
```

### Code editor or IDE name and version

Visual Studio Code v1.15.1

### OS name and version

OSX 10.12.6

**Comment by ArtemGovorov** [comment]
You are `require`-ing an empty module in your wallaby config:

```javascript
  compilers: {
    "**/*.js": wallaby.compilers.babel(require()) // eslint-disable-line global-require
  }
```

It should just be:
```javascript
    compilers: {
      '**/*.js': wallaby.compilers.babel()
    }
```
