### ISSUE TITLE
Jest 21+ doesn't work with Wallaby?

### ISSUE THREAD

**Issue by okonet** [wallabyjs/public#1330]
### Issue description or question

`core v1.0.485`

I've just upgraded Jest from 19.x to 21.x (latest) and now I see the following error in the Wallaby console:

```
jest-cli node module is not found or the version is not supported, missing `npm install jest --save-dev` or `npm install jest-cli --save-dev`?
TypeError: Cannot read property '_loadConfigDependencies' of undefined
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

### Wallaby.js configuration file

```javascript
module.exports = () => ({
  files: [
    'package.json',
    'src/**/*.js',
    'src/**/*.js.snap',
    'node_modules/highlight.js/styles/*.css',
    '!src/**/*.spec.js'
  ],

  tests: ['src/**/*.spec.js'],

  env: {
    type: 'node',
    runner: 'node'
  },

  testFramework: 'jest'
})
```

### Code editor or IDE name and version

IntelliJ IDEA v2017.2

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Wallaby supports Jest 21.x, however the support for the latest version of Jest 21.x was added after the `v1.0.485` of the core, this is why it doesn't work for you. 

The older version of core that you have installed most likely means that your free upgrades period had expired, so you may consider renewing your license in order to get the latest core updates that include the latest Jest version support.
