### ISSUE TITLE
jest version 21 not supported in trial version

### ISSUE THREAD

**Issue by pietgk** [wallabyjs/public#1359]
### Issue description or question

I get the error message:
jest-cli node module is not found or the version is not supported, missing `npm install jest --save-dev` or `npm install jest-cli --save-dev`?​​

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
// eslint-disable-next-line
console.log(wallaby);
  return {
    files: [
      // { pattern: './**/*.js*', load: false },
      // { pattern: './**/*.ts*', load: false },
      { pattern: '!__tests__/*.test.ts', load: false },
    ],

    tests: [
      { pattern: '__tests__/*.test.ts', load: false },
    ],

    env: {
      type: 'node',
      runner: 'node',
    },

    // compilers: {
    //   '**/*.js*': wallaby.compilers.typeScript(),
    //   '**/*.ts*': wallaby.compilers.typeScript(),
    // },
    testFramework: 'jest',
    debug: true,
    // for node.js tests you need to set env property as well
    // https://wallabyjs.com/docs/integration/node.html
  };
};
```
package.json jest part:

```
  "jest": {
    "preset": "react-native",
    "testRegex": "build/.+\\.(test|spec).js$",
    "verbose": true,
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|react-navigation|native-base)/"
    ],
    "moduleNameMapper": {
      "(.*)/SoundManager.js": "$1/SoundManager.js"
    }
  },
```

Visual Studio Code v1.17.2
OS/X Sierra 10.12.6

**Comment by ArtemGovorov** [comment]
> I get the error message:
> jest-cli node module is not found or the version is not supported, missing npm install jest --save-dev or npm install jest-cli --save-dev

There should be some more details in the error (the error stack), could you please paste teh full error?

Unrelated to the error, but you also need to remove `load: false` property from your `files`/`tests`.

**Comment by ArtemGovorov** [comment]
Also (even though those are commented out), don't use patterns like `./**/*.ts*`, because it'll include `node_modules` and other potentially unrelated files. Try using `src/**/*.ts*` patterns (if you have the `src` folder, or just replace it with the folder name that you have).

**Comment by pietgk** [comment]
i have a src and a build directory.
it seams that my src directory where wallaby.conf.js is located, is the current directory for wallaby.

the error trace is:
```
​​Error: Cannot find Jest test runner​​
​​    at Module._compile (module.js:569:30)​​
​​    at Object.Module._extensions..js (module.js:580:10)​​
​​    at Module.load (module.js:503:32)​​
​​    at tryModuleLoad (module.js:466:12)​​
​​    at Function.Module._load (module.js:458:3)​​
​​    at Module.require (module.js:513:17)​​
​​    at require (internal/module.js:11:18)​​
​​    at Module._compile (module.js:569:30)​​
​​    at Object.Module._extensions..js (module.js:580:10)​​
​​    at Module.load (module.js:503:32)​​
​​    at tryModuleLoad (module.js:466:12)​​
​​    at Function.Module._load (module.js:458:3)​​
​​    at Function.Module.runMain (module.js:605:10)​​
​​    at startup (bootstrap_node.js:158:16)​​
​​    at bootstrap_node.js:575:3​​
```

my tsconfig .json is:
```
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "allowJs": true,
        "checkJs": false,
        "target": "es2015",
        "module": "es2015",
        "jsx": "react-native",
        "outDir": "build",
        "rootDir": "src",
        "allowSyntheticDefaultImports": true,
        "noImplicitAny": true,
        "suppressImplicitAnyIndexErrors": true,
        "preserveConstEnums": true,
        "sourceMap": true,
        "moduleResolution": "Node"
    },
    "exclude": [
        "__tests__/**/*.test.ts",
        "src/__tests__/**/*.test.ts",
        "index.js",
        "build",
        "node_modules"
    ],
    "compileOnSave": false
}
```

my complete package.json is:
```
{
  "name": "smartsaltspreader",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest --watchAll --no-cache",
    "testDebug": "jest --watch --no-cache --debug",
    "android": "node node_modules/react-native/local-cli/cli.js run-android",
    "ios": "node node_modules/react-native/local-cli/cli.js run-ios",
    "postinstall": "rndebugger-open",
    "prebuild": "rm -rf build",
    "build": "tsc -w",
    "testBuildWithResolutionTrace": "tsc -w --traceResolution",
    "fixPropTypes1": "jscodeshift -t ../react-codemod/transforms/React-PropTypes-to-prop-types.js node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAware*.js",
    "fixPropTypes2": "jscodeshift -t ../react-codemod/transforms/React-PropTypes-to-prop-types.js node_modules/native-base/src/basic/Swipe*",
    "showPropTypesIssues": "grep -r 'import.*\\<PropTypes\\>.*react' node_modules/**/src",
    "lint": "esw --watch src/**/*.js",
    "tslint": "tslint src/**/*.ts",
    "tscVersion": "tsc --version"
  },
  "dependencies": {
    "autobind-decorator": "2.1.0",
    "buffer": "^5.0.8",
    "color": "^2.0.0",
    "json-cycle": "1.3.0",
    "mobx": "3.3.0",
    "mobx-react": "4.3.2",
    "mobx-state-tree": "^1.0.0",
    "mobx-utils": "3.2.0",
    "native-base": "2.3.2",
    "npm": "5.4.2",
    "print-message": "2.1.0",
    "react": "16.0.0-beta.5",
    "react-native": "0.49.2",
    "react-native-android-location": "pietgk/react-native-android-location#feature/get_GPS_updating_working",
    "react-native-ble-manager": "6.2.0",
    "react-native-deprecated-custom-components": "0.1.1",
    "react-native-device-info": "0.11.0",
    "react-native-fs": "2.5.1",
    "react-native-modal-dropdown": "0.5.0",
    "react-native-sensor-manager": "thebenmiller/react-native-sensor-manager",
    "react-native-slider": "0.11.0",
    "react-native-sound": "0.10.4",
    "react-native-svg": "5.4.1",
    "react-native-uuid": "^1.4.9",
    "react-native-vector-icons": "4.3.0",
    "react-navigation": "1.0.0-beta.13",
    "react-test-renderer": "16.0.0-beta.5",
    "rn-snoopy": "2.0.0",
    "ts-node": "^3.3.0",
    "uuid": "^3.1.0"
  },
  "jest": {
    "preset": "react-native",
    "testRegex": "build/.+\\.(test|spec).js$",
    "verbose": true,
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|react-navigation|native-base)/"
    ],
    "moduleNameMapper": {
      "(.*)/SoundManager.js": "$1/SoundManager.js"
    }
  },
  "quokka": {
    "node": "/Users/grop/.nvm/versions/node/v8.1.0/bin/node"
  },
  "devDependencies": {
    "@types/jest": "21.1.0",
    "@types/react": "16.0.3",
    "@types/react-native": "0.48.6",
    "@types/react-navigation": "1.0.21",
    "@types/react-test-renderer": "^16.0.0-beta.5",
    "babel-cli": "^6.26.0",
    "babel-eslint": "8.0.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-env": "^1.6.0",
    "babel-preset-react-native": "4.0.0",
    "babel-register": "^6.26.0",
    "eslint": "4.7.2",
    "eslint-config-airbnb": "^15.0.1",
    "eslint-plugin-flowtype": "^2.35.1",
    "eslint-plugin-import": "^2.3.0",
    "eslint-plugin-jsx-a11y": "5.1.1",
    "eslint-plugin-react": "^7.1.0",
    "eslint-plugin-react-native": "^3.1.0",
    "eslint-watch": "^3.1.2",
    "jest": "21.1.0",
    "react-native-debugger-open": "^0.3.11",
    "react-native-dotenv": "^0.1.0",
    "tslint": "^5.6.0",
    "typescript": "^2.5.2"
  }
}
```

**Comment by ArtemGovorov** [comment]
Thanks for providing the details.

> it seams that my src directory where wallaby.conf.js is located

This is an issue. Wallaby config is expected to be located in your project's root. Please move your wallaby config file to your project's root, it should fix the issue.

**Comment by ArtemGovorov** [comment]
Let me know it moving the file fixes the issue for you.

**Comment by pietgk** [comment]
i moved wallaby.conf.ts to the project root

./wallaby.conf.js is now:
```
module.exports = function (wallaby) {
// eslint-disable-next-line
console.log(wallaby);
  return {
    files: [
      // { pattern: 'src/**/*.js*', load: false },
      // { pattern: 'src/**/*.ts*', load: false },
      { pattern: '!src/__tests__/*.test.ts', load: false },
    ],

    tests: [
      'src/__tests__/BluethoothConnector.test.ts',
    ],

    env: {
      type: 'node',
      runner: 'node',
    },

    compilers: {
      'src/**/*.js*': wallaby.compilers.typeScript(),
      'src/**/*.ts*': wallaby.compilers.typeScript(),
    },
    testFramework: 'jest',
    debug: true,
    // for node.js tests you need to set env property as well
    // https://wallabyjs.com/docs/integration/node.html
  };
};
```
my test in ./src/__tests__/BluethoothConnector.test.ts
```
import 'jest';

describe('Bluethooth Connector', function() {
  it('can start a scan', () => {
    expect(0).toBe(0);
  });
  it('can stop a scan', () => {
    expect(0).toBe(1);
  });
  it('can connect a thing', () => {
    expect(0).toBe(1);
  });
  it('can disconnect a thing', () => {
    expect(0).toBe(1);
  });
});```

i now get
```
​​​​​0 failing tests, 0 passing​​​​​
​​​​​​​​​​
​​./src/__tests__/BluethoothConnector.test.js:2​​
​​import 'jest';​​
​​^^^^^^​​
​​​​
​​SyntaxError: Unexpected token import​​
​​    at ScriptTransformer._transformAndBuildScript (/Users/grop/dev/innotronic/smartsaltspreader/node_modules/jest-runtime/build/script_transformer.js:305:17)​​
​​    at ScriptTransformer.transform (/Users/grop/dev/innotronic/smartsaltspreader/node_modules/jest-runtime/build/script_transformer.js:332:21)​​
​​    at Runtime._execModule (/Users/grop/dev/innotronic/smartsaltspreader/node_modules/jest-runtime/build/index.js:501:53)​​
​​    at Runtime.requireModule (/Users/grop/dev/innotronic/smartsaltspreader/node_modules/jest-runtime/build/index.js:332:14)​​
​​    at /Users/grop/dev/innotronic/smartsaltspreader/node_modules/jest-jasmine2/build/index.js:101:13​​
​​    at Generator.next (<anonymous>)​​
​​    at step (/Users/grop/dev/innotronic/smartsaltspreader/node_modules/jest-jasmine2/build/index.js:106:583)​​
​​    at /Users/grop/dev/innotronic/smartsaltspreader/node_modules/jest-jasmine2/build/index.js:106:813​​
​​    at Promise (<anonymous>)​​
​​    at /Users/grop/dev/innotronic/smartsaltspreader/node_modules/jest-jasmine2/build/index.js:106:494​​
​​    at jasmine2 (/Users/grop/dev/innotronic/smartsaltspreader/node_modules/jest-jasmine2/build/index.js:106:68)​​
​​    at runTest (/Users/grop/dev/innotronic/smartsaltspreader/node_modules/jest-runner/build/run_test.js:98:10)​​
​​    at /Users/grop/dev/innotronic/smartsaltspreader/node_modules/jest-runner/build/index.js:71:68​​
​​    at Generator.next (<anonymous>)​​
​​    at step (/Users/grop/dev/innotronic/smartsaltspreader/node_modules/jest-runner/build/index.js:23:376)​​
​​    at /Users/grop/dev/innotronic/smartsaltspreader/node_modules/jest-runner/build/index.js:23:536​​
​​    at <anonymous>​​
​​    at process._tickCallback (internal/process/next_tick.js:169:7)​​
```

**Comment by ArtemGovorov** [comment]
Because your `tsconfig.json` doesn't compile ES modules to `CommonJs`, you'll need to configure wallaby use the `react-native` preset as [described here in our docs](https://wallabyjs.com/docs/integration/typescript.html#compiling-to-es6-and-using-babel):

```diff
module.exports = function (wallaby) {
// eslint-disable-next-line
console.log(wallaby);
  return {
    ...
+   preprocessors: {
+     '**/*.js': file => require('babel-core').transform(
+       file.content,
+       {sourceMap: true, compact: false, presets: ['react-native']})
+   },
  };
};
```

I have created [this sample repo](https://github.com/ArtemGovorov/wallaby-1359) with your configs and working wallaby config. If something else doesn't work for you in your real project, please feel free to fork and update the sample repo with some demo of the issue(s) that you're encountering, I'm happy to have a look.

**Comment by pietgk** [comment]
Thx, the specific test now runs.
Thumbs up for the support, the react-native typescript context was not detected/found by me.

**Comment by pietgk** [comment]
I now included files and get the following error:

```
[Error] ​​Failed to parse src/containers/SampleView.js, SyntaxError: Unexpected character '@' (6:0)​​
[Error] ​​  at _combinedTickCallback (internal/process/next_tick.js:95:7)​​
[Error] ​​  at process._tickCallback (internal/process/next_tick.js:161:9)​​
[Error] ​​  at _combinedTickCallback (internal/process/next_tick.js:95:7)​​
[Error] ​​  at process._tickCallback (internal/process/next_tick.js:161:9)​​
```

changed wallaby.conf.js is:
```

// see https://github.com/ArtemGovorov/wallaby-1359 for simple working example 
// after issue https://github.com/wallabyjs/public/issues/1359#issuecomment-338633214
// 
module.exports = function (wallaby) {
  // eslint-disable-next-line
  console.log(wallaby);
  return {
    files: [
      { pattern: 'src/containers/SampleView.js', load: false },
      // { pattern: 'src/**/*.+(t|j)s*', load: false },
      { pattern: '!src/__tests__/*.test.ts', load: false },
    ],

    tests: [
      'src/__tests__/*.test.ts',
    ],

    env: {
      type: 'node',
      runner: 'node',
    },

    compilers: {
      'src/**/*.+(t|j)s*': wallaby.compilers.typeScript(),
    },

    preprocessors: {
      // eslint-disable-next-line global-require, import/no-extraneous-dependencies
      '**/*.js': file => require('babel-core').transform(
        file.content,
        { sourceMap: true, compact: false, presets: ['react-native'] }),
    },

    testFramework: 'jest',

    debug: true,
    // for node.js tests you need to set env property as well
    // https://wallabyjs.com/docs/integration/node.html
  };
};
```

src/containers/SampleView.js
```
/* eslint-disable react/prop-types */
import React, { Component } from 'react';
import { Text } from 'react-native';
import { observer } from 'mobx-react/native';

@observer
export default class Log extends Component {
  render() {
    return (
      <Text>SampleView</Text>
    );
  }
}
```
