### ISSUE TITLE
Issue about Wallaby's TypeScript support.

### ISSUE THREAD

**Issue by Hazealign** [wallabyjs/public#1380]
### Issue description or question
I have some trouble with TypeScript and Ava Project with Wallaby. Can I get some help?

```
​​​​​[Info]​​​​​ Wed, 08 Nov 2017 07:06:38 GMT wallaby:workers Loaded unknown number of test(s)
​​​​​[Info]​​​​​ Wed, 08 Nov 2017 07:06:39 GMT wallaby:workers Failed to map the stack to user code, entry message: Rejected promise returned by test
​​​​​[Info]​​​​​ SyntaxError {
​​​​​[Info]​​​​​   message: 'Unexpected token import',
​​​​​[Info]​​​​​ }, stack: C:\Users\Realignist\.vscode-insiders\extensions\WallabyJs.wallaby-vscode-1.0.64\projects\029c53c3935d157e\instrumented\src\modules\entities\ArticleEntity.ts:1
​​​​​[Info]​​​​​ (function (exports, require, module, __filename, __dirname) { import { Column, Entity, PrimaryGeneratedColumn, OneToOne, ManyToMany, OneToMany } from 'typeorm'
​​​​​[Info]​​​​​                                                               ^^^^^^
​​​​​[Info]​​​​​ SyntaxError: Unexpected token import
​​​​​[Info]​​​​​     at createScript (vm.js:80:10)
​​​​​[Info]​​​​​     at Object.runInThisContext (vm.js:139:10)
​​​​​[Info]​​​​​     at Module._compile (module.js:576:28)
​​​​​[Info]​​​​​     at Object.Module._extensions..js (module.js:623:10)
​​​​​[Info]​​​​​     at Module.load (module.js:531:32)
​​​​​[Info]​​​​​     at tryModuleLoad (module.js:494:12)
​​​​​[Info]​​​​​     at Function.Module._load (module.js:486:3)
​​​​​[Info]​​​​​     at Module.require (module.js:556:17)
​​​​​[Info]​​​​​     at Module.r.require (C:\Users\Realignist\.vscode-insiders\extensions\WallabyJs.wallaby-vscode-1.0.64\wallaby\server.js:19:31091)
​​​​​[Info]​​​​​     at Module.modulePrototype.require (C:\Users\Realignist\.vscode-insiders\extensions\WallabyJs.wallaby-vscode-1.0.64\wa
​​​​​[Info]​​​​​ Wed, 08 Nov 2017 07:06:39 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
​​​​​[Info]​​​​​ Wed, 08 Nov 2017 07:06:39 GMT wallaby:workers Sandbox [jojmq] is responsive, closing it
​​​​​[Info]​​​​​ Wed, 08 Nov 2017 07:06:39 GMT wallaby:project Test run finished
​​​​​[Info]​​​​​ Wed, 08 Nov 2017 07:06:39 GMT wallaby:project Processed console.log entries
​​​​​[Info]​​​​​ Wed, 08 Nov 2017 07:06:39 GMT wallaby:project Processed loading sequences
​​​​​[Info]​​​​​ Wed, 08 Nov 2017 07:06:39 GMT wallaby:project Processed executed tests
​​​​​[Info]​​​​​ Wed, 08 Nov 2017 07:06:39 GMT wallaby:project Processed code coverage
​​​​​[Info]​​​​​ Wed, 08 Nov 2017 07:06:39 GMT wallaby:project Test run result processed and sent to IDE
```

### Wallaby.js configuration file

```javascript
const tsConfig = require('./tsconfig.json')

module.exports = (wallaby) => {
  return {
    name: 'Evidnet Server v2',
    files: [
      'src/**/*.ts'
    ],

    tests: [
      'test/**/*.spec.ts'
    ],
    
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript(tsConfig)
    },
    env: {
      type: 'node',
      runner: 'node'
    },
    debug: true,
    testFramework: 'ava',
    delays: {
      run: 1000
    },
    slowTestThreshold: 500,
    lowCoverageThreshold: 85,
    reportUnhandledPromises: true
  }
}
```

```json
{
  "version": "2.5.3",
  "compilerOptions": {
    "target": "es2015",
    "allowSyntheticDefaultImports": true,
    "preserveConstEnums": true,
    "sourceMap": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "lib": [
      "es6",
      "es7"
    ],
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "declaration": false,
    "noImplicitAny": false,
    "noImplicitReturns": false,
    "removeComments": true,
    "noUnusedLocals": true,
    "strictNullChecks": true,
    "types": [
      "node"
    ]
  },
  "exclude": [
    "node_modules",
    "server/**/*.spec.ts"
  ],
  "compileOnSave": false
}
```

### Code editor or IDE name and version

Visual Studio Code 1.18.0-Insider

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
Please share:
- your wallaby.js config file, 
- your package.json file,
- your tsconfig.json file.

**Comment by Hazealign** [comment]
Sorry I uploaded too early. It was mistake.
@ArtemGovorov I updated the information. Can you check this issue again? 
Thanks. :)

**Comment by ArtemGovorov** [comment]
Thanks for sharing your config files.

The issue is that you're passing the tsconfig.json root object:

```javascript
const tsConfig = require('./tsconfig.json')

module.exports = (wallaby) => {
  return {
    ...
    
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript(tsConfig) // <--
    },
```

however it is [supposed to be the `compilerOptions` property](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings).

So you may either pass the correct property:
```javascript
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript(tsConfig.compilerOptions) // <--
    },
```

Also, because [wallaby supports zero config for TypeScript](https://wallabyjs.com/docs/integration/typescript.html), and automatically reads and applies your `tsconfig.json` file, you may remove the `compilers` setting all together:

```diff
-const tsConfig = require('./tsconfig.json')

module.exports = (wallaby) => {
  return {
    name: 'Evidnet Server v2',
    files: [
      'src/**/*.ts'
    ],

    tests: [
      'test/**/*.spec.ts'
    ],
    
-   compilers: {
-     '**/*.ts?(x)': wallaby.compilers.typeScript(tsConfig)
-   },
    env: {
      type: 'node',
      runner: 'node'
    },
    debug: true,
    testFramework: 'ava',
    delays: {
      run: 1000
    },
    slowTestThreshold: 500,
    lowCoverageThreshold: 85,
    reportUnhandledPromises: true
  }
}
```

**Comment by Hazealign** [comment]
Thanks. I'll try it.
