### ISSUE TITLE
Failed to map the stack to user code

### ISSUE THREAD

**Issue by scriptsure** [wallabyjs/public#1392]
### Issue description or question
Getting weird error when trying to run a DELETE test. 

Tue, 14 Nov 2017 15:56:56 GMT wallaby:workers Sandbox (active) [nt5in] error: RangeError: Invalid status code: 0
Tue, 14 Nov 2017 15:56:56 GMT wallaby:workers Failed to map the stack to user code, entry message: RangeError: Invalid status code: 0, stack: RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:192:11)
    at ServerResponse.writeHead (E:\platform\node_modules\on-headers\index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:566:10)
    at writeend (E:\platform\node_modules\express-session\index.js:261:22)
    at Command.ontouch (E:\platform\node_modules\express-session\index.js:348:11)
    at Command.callback (E:\platform\node_modules\connect-redis\lib\connect-redis.js:252:10)
    at normal_reply (E:\platform\node_modules\redis\index.js:721:21)
    at RedisClient.return_reply (E:\platform\node_modules\redis\index.js:819:9)
    at JavascriptRedisParser.Parser.returnReply (E:\platform\node_modules\redis\index.js:192:18)
    at JavascriptRedisParser.execute (E:\platform\node_modules\redis-parser\lib\parser.js:560:12)
    at Socket.<anonymous> (E:\platform\node_modules\redis\index.js:274:27)
    at emitOne (events.js:96:13)
    at Socket.
Runtime error: RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:192:11)
    at ServerResponse.writeHead (E:\platform\node_modules\on-headers\index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:566:10)
    at writeend (E:\platform\node_modules\express-session\index.js:261:22)
    at Command.ontouch (E:\platform\node_modules\express-session\index.js:348:11)
    at Command.callback (E:\platform\node_modules\connect-redis\lib\connect-redis.js:252:10)
    at normal_reply (E:\platform\node_modules\redis\index.js:721:21)
    at RedisClient.return_reply (E:\platform\node_modules\redis\index.js:819:9)
    at JavascriptRedisParser.Parser.returnReply (E:\platform\node_modules\redis\index.js:192:18)
    at JavascriptRedisParser.execute (E:\platform\node_modules\redis-parser\lib\parser.js:560:12)
    at Socket.<anonymous> (E:\platform\node_modules\redis\index.js:274:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version
 
WebStorm v2017.2.5 
### OS name and version

Windows8

**Comment by scriptsure** [comment]
@ArtemGovorov the UI in webstorm shows error... but on the URL for status of messages it does not show that the test was run. And i get this random error as seem above...

`            agent.delete(ROUTEPATH + '/' + userID + '/' + prescriberID)
                .set('Cookie', connectSid)
                .end(function (err, res) {
                    if (err) {
                        console.log('delete the pending requests error:', res, err.message);
                        done();
                    } else {
                        if (res.status !== http_constants.STAT_200_OK) {
                            console.error('delete.001 received status:', res.status, ', ' + util.inspect(res.body));
                            fail('delete.001 received status: ' + res.status);
                            done();
                        } else {
                            expect(res.status).toBe(http_constants.STAT_200_OK);
                            expect(res.body).toBeDefined();
                            expect(res.body.hasOwnProperty('userID')).toBeGreaterThan(0);
                            logger.verbose('delete requests: ' + util.inspect(res.body, {depth: null}));
                            done();
                        }
                    }
                });
`

**Comment by ArtemGovorov** [comment]
This is a runtime error (caused by your test/or code that the test executes) and it looks like it's uncaught, so just crashes the testing sandbox and prevents other tests from running (like any other global error uncaught error outside tests would).

The error itself is not specific to wallaby and caused by the test (or code that is executes), but you need to fix/catch it so that other tests can run normally. Looks like the error is raised in an async manner and outside your test (ie. after the test execution is finished).

If you create a sample repo with the error, I'm happy to help and investigate what is causing it and how to fix/catch it.

**Comment by scriptsure** [comment]
@ArtemGovorov thanks for the reply... thanks for the help... superb support thanks. I will continue to debug and track it down. Thanks!

**Comment by azaeng04** [comment]
I am also getting this error with not much information. I recreated an exact example of the same app, except its structure, and I got the tests passing. Is there any way we could somehow pin point where the issue is coming from?

**Comment by smcenlly** [comment]
@azaeng04 - we will reply to the issue you raised: https://github.com/wallabyjs/public/issues/3445
