### ISSUE TITLE
TypeError: Cannot read property 'awaitingFiles' of undefined in 1.0.56

### ISSUE THREAD

**Issue by bruderstein** [wallabyjs/public#140]
Everytime I try to start wallaby in 1.0.56 (windows), I get an error about awaitingFiles 

env is type node, I've tried with a runner to the latest iojs.exe (2.2.1) and get the same effect.
```
Failed to execute start operation, TypeError: Cannot read property 'awaitingFiles' of undefined
  at EventEmitter._.extend._signalIfBecameLive (C:\Users\xxxxxx\.WebStorm10\system\wallaby\wallaby\server.js:10:13004)
  at C:\Users\xxxxxxx\.WebStorm10\system\wallaby\wallaby\server.js:9:29379
From previous event:
  at EventEmitter._.extend.start (C:\Users\xxxxxx\.WebStorm10\system\wallaby\wallaby\server.js:9:29463)
  at WebSocket.<anonymous> (C:\Users\xxxxxx\.WebStorm10\system\wallaby\wallaby\server.js:8:1299)
  at emitTwo (events.js:87:13)
  at WebSocket.emit (events.js:169:7)
  at Receiver.self._receiver.ontext (C:\Users\xxxxxx\.WebStorm10\system\wallaby\wallaby\node_modules\ws\lib\WebSocket.js:682:10)
  at Receiver.opcodes.1.finish (C:\Users\xxxxxx\.WebStorm10\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:391:14)
  at Receiver.expectHandler (C:\Users\xxxxx\.WebStorm10\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:372:33)
  at Receiver.add (C:\Users\xxxxxx\.WebStorm10\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:87:24)
  at Socket.firstHandler (C:\Users\xxxxxx\.WebStorm10\system\wallaby\wallaby\node_modules\ws\lib\WebSocket.js:663:22)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)

```

**Comment by ArtemGovorov** [comment]
@bruderstein Did it work before 1.0.56?

**Comment by bruderstein** [comment]
I had problems for the first time this morning, I think it was still 1.0.55, but it worked earlier this morning. As it stopped working, I restarted webstorm, and then I got the 1.0.56.

I've had issues around iojs/nodejs today, and reinstalled the newest iojs and then the node.js 0.12.4.  I only have node.js in the PATH.  I've checked using Procmon and wallaby is still using it's own iojs 1.6.4 though.

**Comment by ArtemGovorov** [comment]
Just published 1.0.57, please restart your WebStorm, start wallaby.js and let me know what happens now.

**Comment by ArtemGovorov** [comment]
In order to get wallaby.js use your node version you have to specify `env.runner` property like described here - https://github.com/wallabyjs/public#environment-setting.
So your config should look like:
``` JavaScript
env: {
      type: 'node',
      runner: 'c:\\path\\to\\the\\desired\\node.exe'
}
```

**Comment by bruderstein** [comment]
Yeah, as I said, I've tried that, and still get the same error (both iojs and nodejs).

**Comment by ArtemGovorov** [comment]
Ah, sorry, I got you wrong the first time. Did 1.0.57 update change anything? Could also you please add `debug: true` to the root wallaby config object and paste the full Wallaby Console output here?

**Comment by bruderstein** [comment]
1.0.57 works, thanks. Sorry for the delay :)

**Comment by ArtemGovorov** [comment]
Cool, thanks!
