### ISSUE TITLE
Typescript and vue-wallaby-compiler

### ISSUE THREAD

**Issue by elevatebart** [wallabyjs/public#1415]
### Issue description or question

When using vue-wallaby-compiler, I tried using typescript as the cripting language.
Problem is, I get an error at compilation.

I put together a quick repo if you want to try it out ;)
https://github.com/elevatebart/vue-wallaby-ts

```
[Error] ​​Failed to run compilers on src/components/HelloWorld.vue, TypeError: scriptCompiler is not a function​​
[Error] ​​  at /Users/ledouxb/Documents/github/wallaby-vue-ts/node_modules/wallaby-vue-compiler/index.js:16:29​​
[Error] ​​  at _combinedTickCallback (internal/process/next_tick.js:131:7)​​
[Error] ​​  at process._tickCallback (internal/process/next_tick.js:180:9)​​
[Error] ​​  at emitTwo (events.js:126:13)​​
[Error] ​​  at process.emit (events.js:214:7)​​
[Error] ​​  at emit (internal/child_process.js:772:12)​​
[Error] ​​  at _combinedTickCallback (internal/process/next_tick.js:141:11)​​
[Error] ​​  at process._tickCallback (internal/process/next_tick.js:180:9)​​
[Error] ​​  at _combinedTickCallback (internal/process/next_tick.js:131:7)​​
[Error] ​​  at process._tickCallback (internal/process/next_tick.js:180:9)​​
```

### Wallaby.js configuration file

```javascript
const wallabyWebpack = require('wallaby-webpack')
var webpackConfig = require('./build/webpack.test.conf')

module.exports = function (wallaby) {
  webpackConfig.resolve.alias = {'@': require('path').join(wallaby.projectCacheDir, 'src')}
  webpackConfig.module.rules.find(r => r.loader === 'vue-loader').options.loaders.jss = ''
  const wallabyPostprocessor = wallabyWebpack(webpackConfig)

  return {
    files: [
      {pattern: 'node_modules/chai/chai.js', instrument: false},
      {pattern: 'node_modules/sinon/lib/sinon.js', instrument: false},
      {pattern: 'src/**/*.*', load: false},
    ],

    compilers: {
      '**/*.vue': require('wallaby-vue-compiler')(wallaby.compilers.typeScript({})),
      '**/*.js': wallaby.compilers.babel(),
      '**/*.ts': wallaby.compilers.typeScript()
    },

    tests: [
      {pattern: 'test/unit/**/*.spec.ts', load: false},
    ],

    postprocessor: wallabyPostprocessor,
    testFramework: 'mocha',
    setup: function () {
      window.__moduleBundler.loadTests()
      window.expect = chai.expect
      window.sinon = sinon
      var should = chai.should()
    },
    debug: true
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.18.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Thanks for the repo. I have sent you [the pull request](https://github.com/elevatebart/vue-wallaby-ts/pull/1) to make it work:

```javascript
const wallabyWebpack = require('wallaby-webpack')
var webpackConfig = require('./build/webpack.test.conf')

module.exports = function (wallaby) {
  webpackConfig.resolve.alias = {'@': require('path').join(wallaby.projectCacheDir, 'src'), 'vue$': 'vue/dist/vue.esm.js'}
  webpackConfig.module.rules = webpackConfig.module.rules.filter(r => !'.ts'.match(r.test) && !'.js'.match(r.test));
  webpackConfig.module.rules.find(r => r.loader === 'vue-loader').options.loaders.js = '';

  const wallabyPostprocessor = wallabyWebpack(webpackConfig)

  return {
    files: [
      {pattern: 'node_modules/chai/chai.js', instrument: false},
      {pattern: 'node_modules/sinon/pkg/sinon.js', instrument: false},
      {pattern: 'src/**/*.*', load: false},
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
      '**/*.ts': wallaby.compilers.typeScript({module: 'CommonJs', target: 'ES5'})
    },

    preprocessors: {
      '**/*.vue': f => f.content.replace('lang="ts"', '').replace('.ts', '.js')
    },

    tests: [
      {pattern: 'test/unit/**/*.spec.ts', load: false},
    ],

    postprocessor: wallabyPostprocessor,
    testFramework: 'mocha',
    setup: function () {
      window.__moduleBundler.loadTests()
      window.expect = chai.expect
      window.sinon = sinon
      var should = chai.should()
    },
    debug: true
  }
}
```

The major changes are:
- removed all `.ts/.js` loaders from wallaby webpack config (because you have `.js/.ts` compilers configured),
- change TypeScript compilation target to `ES5/CommonJs` in wallaby config. Otherwise you'll need babel compilation on top of your compiled TypeScript files, that looks unnecessary. If you do need it, you may remove my change of the `ES5/CommonJs` target and add Babel preprocessor after TypeScript compilation, [as described here in our docs](https://wallabyjs.com/docs/integration/typescript.html#compiling-to-es6-and-using-babel).
- added `.vue` preprocessor to replace all `ts` references to `.js` in `.vue` files, because wallaby compiles `.ts` files to `.js` without a webpack loader,
- fixed sinon script link.
