### ISSUE TITLE
Wallaby won't start

### ISSUE THREAD

**Issue by ksnyde** [wallabyjs/public#1419]
### Issue description or question

I restarted my browser for unrelated reasons but when i came back I found that I couldn't start Wallaby anymore. I'm working on a NODEJS project written in Typescript `2.6.1` within the VS-Code editor (`1.18.1`) on **macOs**. I have noticed that in the "Wallabyjs Console" I am getting the following error which _appears_ to be coming from within Typescript modules, which is puzzling considering I have not upgraded it recently. I suspect it's a red herring but not sure where else to look.

    [Info]​​​​​ Sun, 03 Dec 2017 21:15:47 GMT wallaby:project Instrumenting src/vote-smart/shared.js, via process pool: false
    ​​​​​[Info]​​​​​ Sun, 03 Dec 2017 21:15:47 GMT wallaby:project TypeError: Cannot read property 'kind' of undefined
    ​​​​​[Info]​​​​​   at transformModuleBody (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:54978:22)
    ​​​​​[Info]​​​​​   at visitModuleDeclaration (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:54950:33)
    ​​​​​[Info]​​​​​   at visitTypeScript (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:53077:28)
    ​​​​​[Info]​​​​​   at visitorWorker (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:52798:24)
    ​​​​​[Info]​​​​​   at sourceElementVisitorWorker (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:52827:28)
    ​​​​​[Info]​​​​​   at saveStateAndInvoke (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:52742:27)
    ​​​​​[Info]​​​​​   at sourceElementVisitor (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:52812:20)
    ​​​​​[Info]​​​​​   at visitNodes (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:51104:48)
    ​​​​​[Info]​​​​​   at Object.visitLexicalEnvironment (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:51137:22)
    ​​​​​[Info]​​​​​   at visitSourceFile (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:53089:53)
    ​​​​​[Info]​​​​​   at saveStateAndInvoke (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:52742:27)
    ​​​​​[Info]​​​​​   at transformSourceFile (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:52726:27)
    ​​​​​[Info]​​​​​   at /Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:2601:86
    ​​​​​[Info]​​​​​   at reduceLeft (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:2274:30)
    ​​​​​[Info]​​​​​   at /Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:2601:42
    ​​​​​[Info]​​​​​   at transformRoot (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:65718:82)
    ​​​​​[Info]​​​​​   at Object.map (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:1725:29)
    ​​​​​[Info]​​​​​   at Object.transformNodes (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:65706:30)
    ​​​​​[Info]​​​​​   at Object.emitFiles (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:68440:28)
    ​​​​​[Info]​​​​​   at emitWorker (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:72517:33)
    ​​​​​[Info]​​​​​   at /Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:72479:66
    ​​​​​[Info]​​​​​   at runWithCancellationToken (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:72571:24)
    ​​​​​[Info]​​​​​   at Object.emit (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:72479:20)
    ​​​​​[Info]​​​​​   at Object.getFileEmitOutput (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:71137:34)
    ​​​​​[Info]​​​​​   at Object.getEmitOutput (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:96004:23)
    ​​​​​[Info]​​​​​   at /Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/server.js:19:24748
    ​​​​​[Info]​​​​​   at baseFor (/Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/node_modules/lodash/index.js:1971:13)
    ​​​​​[Info]​​​​​   at baseForOwn (/Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/node_modules/lodash/index.js:2025:14)
    ​​​​​[Info]​​​​​   at baseEach (/Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/node_modules/lodash/index.js:1814:16)
    ​​​​​[Info]​​​​​   at Function.forEach (/Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/node_modules/lodash/index.js:5701:11)
    ​​​​​[Info]​​​​​   at Object.n [as postprocessor] (/Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/server.js:19:24554)
    ​​​​​[Info]​​​​​   at /Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/server.js:17:16568
    ​​​​​[Info]​​​​​   at Timeout._onTimeout (/Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/server.js:17:16006)
    ​​​​​[Info]​​​​​   at ontimeout (timers.js:475:11)
    ​​​​​[Info]​​​​​   at tryOnTimeout (timers.js:310:5)
    ​​​​​[Info]​​​​​   at Timer.listOnTimeout (timers.js:270:5)
    ​​​​​[Info]​​​​​ From previous event:
    ​​​​​[Info]​​​​​   at Timeout._onTimeout (/Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/server.js:17:16006)
    ​​​​​[Info]​​​​​   at ontimeout (timers.js:475:11)
    ​​​​​[Info]​​​​​   at tryOnTimeout (timers.js:310:5)
    ​​​​​[Info]​​​​​   at Timer.listOnTimeout (timers.js:270:5)

### Wallaby.js configuration file

```javascript
{
  "compilerOptions": {
    "declaration": true,
    "module": "commonjs",
    "lib": ["es2015", "es2016", "es2017", "esnext.asynciterable", "dom"],
    "target": "ES6",
    "moduleResolution": "node",
    "sourceMap": true,
    "noImplicitAny": true,
    "outDir": "./lib",
    "removeComments": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "typeRoots": ["./node_modules/@types", "./types"]
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*-spec.ts"]
}
```

**Comment by ksnyde** [comment]
Closing as I can see the same error when running mocha from _cli_. Also it appears there is an issue in the Typescript repo which matches my situation.

**Comment by ksnyde** [comment]
> Note: upgrading to `typescript@next` gives a much clearer error
