### ISSUE TITLE
Failed to run compilers on node_modules/mkdirp/bin/cmd.js

### ISSUE THREAD

**Issue by vjau** [wallabyjs/public#1424]
### Issue description or question
I get following error message when running wallaby

project Error: Failed to run compilers on node_modules/mkdirp/bin/cmd.js, SyntaxError: node_modules/mkdirp/bin/cmd.js: 'return' outside of function (13:4)
  11 | if (argv.help) {
  12 |     fs.createReadStream(__dirname + '/usage.txt').pipe(process.stdout);
> 13 |     return;
     |     ^
  14 | }
  15 | 
  16 | var paths = argv._.slice();
    at Parser.pp$5.raise (/home/vincent/dev/npmLocalPackages/lclparse/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp$1.parseReturnStatement (/home/vincent/dev/npmLocalPackages/lclparse/node_modules/babylon/lib/index.js:2066:10)
    at Parser.pp$1.parseStatement (/home/vincent/dev/npmLocalPackages/lclparse/node_modules/babylon/lib/index.js:1848:19)
    at Parser.pp$1.parseBlockBody (/home/vincent/dev/npmLocalPackages/lclparse/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseBlock (/home/vincent/dev/npmLocalPackages/lclparse/node_modules/babylon/lib/index.js:2247:8)
    at Parser.pp$1.parseStatement (/home/vincent/dev/npmLocalPackages/lclparse/node_modules/babylon/lib/index.js:1868:19)
    at Parser.pp$1.parseIfStatement (/home/vincent/dev/npmLocalPackages/lclparse/node_modules/babylon/lib/index.js:2059:26)
    at Parser.pp$1.parseStatement (/home/vincent/dev/npmLocalPackages/lclparse/node_modules/babylon/lib/index.js:1846:19)
    at Parser.pp$1.parseBlockBody (/home/vincent/dev/npmLocalPackages/lclparse/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/home/vincent/dev/npmLocalPackages/lclparse/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/home/vincent/dev/npmLocalPackages/lclparse/node_modules/babylon/lib/index.js:1673:17)
    at parse (/home/vincent/dev/npmLocalPackages/lclparse/node_modules/babylon/lib/index.js:7305:37)
    at File.parse (/home/vincent/dev/npmLocalPackages/lclparse/node_modules/babel-core/lib/transformation/file/index.js:517:15)
    at File.parseCode (/home/vincent/dev/npmLocalPackages/lclparse/node_modules/babel-core/lib/transformation/file/index.js:602:20)
    at /home/vincent/dev/npmLocalPackages/lclparse/node_modules/babel-core/lib/transformation/pipeline.js:49:12
    at File.wrap (/home/vincent/dev/npmLocalPackages/lclparse/node_modules/babel-core/lib/transformation/file/index.js:564:16)
    at Pipeline.transform (/home/vincent/dev/npmLocalPackages/lclparse/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at /home/vincent/.WebStorm2017.3/system/wallaby/wallaby/server.js:18:1139
    at _rejected (/home/vincent/.WebStorm2017.3/system/wallaby/wallaby/node_modules/q/q.js:864:24)
    at /home/vincent/.WebStorm2017.3/system/wallaby/wallaby/node_modules/q/q.js:890:30
    at Promise.when (/home/vincent/.WebStorm2017.3/system/wallaby/wallaby/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/vincent/.WebStorm2017.3/system/wallaby/wallaby/node_modules/q/q.js:808:41)
    at /home/vincent/.WebStorm2017.3/system/wallaby/wallaby/node_modules/q/q.js:624:44
    at runSingle (/home/vincent/.WebStorm2017.3/system/wallaby/wallaby/node_modules/q/q.js:137:13)
    at flush (/home/vincent/.WebStorm2017.3/system/wallaby/wallaby/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      '**/*.js',
      { pattern: 'test/**/*.js', ignore: true }
    ],

    tests: [
      'test/**/*.js'
    ],
    testFramework: 'mocha',
    env: {
      type: 'node',
      runner: 'node'
    },
    compilers: {
      '**/*.js*': wallaby.compilers.babel()
    },
    debug: true
  };
};

```

.babelrc

{
  "presets" :["env", "stage-2"]
}

### Code editor or IDE name and version

WebStorm 2017.30

Ubuntu 16.04

Node 8.5

**Comment by ArtemGovorov** [comment]
Looks like your `files` pattern `'**/*.js',` is too greedy - it includes `node_modules` and not only this causes wallaby to instrument them (and causes the error), it also slows everything down because of a lot of unnecessary actions that wallaby has to perform.

We normally recommend to use a less greedy pattern, for example if you have an `src` folder, then you can do:

```
    files: [
      'src/**/*.js',
      { pattern: 'test/**/*.js', ignore: true }
    ],
```

If it's not possible, then at least exclude the `node_modules` folder (ideally all other unnecessary files in the root folder and subfolders that you don't need):

```
    files: [
      '**/*.js',
      { pattern: '**/node_modules/**', ignore: true }
      { pattern: 'test/**/*.js', ignore: true }
    ],
```
