### ISSUE TITLE
vscode: wallaby crash and not available after some time

### ISSUE THREAD

**Issue by unional** [wallabyjs/public#1447]
### Issue description or question

When I have wallaby started for a while (don't know exactly how long, likely 1-2 hours), it crashes and not available:
![image](https://user-images.githubusercontent.com/3254987/34465848-a09e6482-ee75-11e7-901f-51b8601a195d.png)

Here are some logs that may be relevant:
```sh
[Extension Host] (node:29328) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 deploy.config.reloaded listeners added. Use emitter.setMaxListeners() to increase limit
[Extension Host] TextEditor is closed/disposed
t.log @ console.ts:123
console.ts:123 
[Extension Host] Error: Error while downloading wallaby.js version file: connect ETIMEDOUT 104.24.96.87:80
    at Request.<anonymous> (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/dist/index.js:14:9648)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/node_modules/request/request.js:867:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

t.log @ console.ts:123
console.ts:123 [Extension Host] Disconnected from wallaby core: 1006
log.ts:165   ERR not opened: Error: not opened
    at WebSocket.send (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/wallaby/node_modules/ws/lib/WebSocket.js:219:16)
    at c._send (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/wallaby/client.js:14:4518)
    at c._requestWithCorrelationId (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/wallaby/client.js:14:4008)
    at c.requestError (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/wallaby/client.js:14:3874)
    at d.4.b._disposables.add.l.languages.registerHoverProvider.provideHover (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/dist/index.js:14:17504)
    at Promise (<anonymous>:null:null)
    at Object.provideHover (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/dist/index.js:14:17444)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:441:131
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:93:1004
    at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:74:234)
    at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:93:967)
    at e.provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:441:85)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:453:419
    at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:451:24)
    at e.$provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:453:381)
    at t.e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:516:87)
    at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:357:580)
    at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:357:270)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:356:206
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:358:204
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:85:988
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:87:218)
    at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:135:717)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)

console.ts:123 [Extension Host] 2018-01-01T03:05:25.142Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"/Users/hwong/github/unional/global-test-harness/src/createTestHarness.ts"}}
console.ts:123 [Extension Host] 2018-01-01T03:05:25.149Z - info: [CodeActionCreator] calculated diagnostics {"durationMs":1}
console.ts:123 [Extension Host] 2018-01-01T03:05:25.164Z - debug: [DocumentSymbolStructureExtension] activeWindowChanged, reparsing
console.ts:123 [Extension Host] 2018-01-01T03:05:25.228Z - debug: [CodeActionCreator] provide code actions for file {"meta":{"file":"/Users/hwong/github/unional/global-test-harness/src/createTestHarness.ts"}}
console.ts:123 [Extension Host] 2018-01-01T03:05:25.229Z - info: [CodeActionCreator] calculated diagnostics
console.ts:123 [Extension Host] Error: An extension called process.exit() and this was prevented.
    at process.exit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:528:7)
    at d (/Users/hwong/.vscode/extensions/WallabyJs.quokka-vscode-1.0.88/dist/index.js:5:3107)
    at process.d.1.c.activate.process.exit (/Users/hwong/.vscode/extensions/WallabyJs.quokka-vscode-1.0.88/dist/index.js:5:3161)
    at d (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/dist/index.js:14:11333)
    at process.d.1.c.activate.process.exit (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/dist/index.js:14:11387)
    at gracefulExit (/Users/hwong/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/winston/lib/winston/exception-handler.js:197:15)
    at _toString (/Users/hwong/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/async/lib/async.js:52:16)
    at done (/Users/hwong/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/async/lib/async.js:246:17)
    at /Users/hwong/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/async/lib/async.js:44:16
    at onetime (/Users/hwong/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/one-time/index.js:23:16)
    at module.exports.<anonymous> (/Users/hwong/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/winston/lib/winston/exception-handler.js:224:9)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:101:20)
    at module.exports.emit (events.js:191:7)
    at logged (/Users/hwong/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/winston/lib/winston/transports/file.js:139:10)
    at afterWrite (_stream_writable.js:383:3)
    at _combinedTickCallback (internal/process/next_tick.js:86:20)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

t.log @ console.ts:123
log.ts:165   ERR not opened: Error: not opened
    at WebSocket.send (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/wallaby/node_modules/ws/lib/WebSocket.js:219:16)
    at c._send (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/wallaby/client.js:14:4518)
    at c.fileOpenedInEditor (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/wallaby/client.js:14:3183)
    at /Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/dist/index.js:15:2202
    at /Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/dist/index.js:15:2294
    at baseFor (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/wallaby/node_modules/lodash/index.js:1971:13)
    at baseForOwn (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/wallaby/node_modules/lodash/index.js:2025:14)
    at baseEach (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/wallaby/node_modules/lodash/index.js:1814:16)
    at Function.forEach (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/wallaby/node_modules/lodash/index.js:5701:11)
    at c.value (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/dist/index.js:15:1984)
    at c.wrapper (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/wallaby/node_modules/lodash/index.js:2914:56)
    at Timeout.delayed [as _onTimeout] (/Users/hwong/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.69/wallaby/node_modules/lodash/index.js:6879:27)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    "files": [
      { pattern: 'tsconfig.*', instrument: false },
      { pattern: 'fixtures/**', instrument: false },
      "src/**/*.ts",
      "!src/**/*.spec.ts"
    ],
    "tests": [
      "src/**/*.spec.ts"
    ],
    "env": {
      "type": "node"
    },
    compilers: {
      'src/**/*.ts': wallaby.compilers.typeScript({ module: 'commonjs' }),
    },
    testFramework: 'ava'
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.19.1

### OS name and version

OSX: 10.12.6

**Comment by ArtemGovorov** [comment]
Thanks for providing the logs, it was helpful. One of your other extensions was causing the issue. 

Wallaby extension is subscribed to `process.exit` and deactivates itself on the event, and one of your extension's dependencies is calling `process.exit`, specifically `typescript-hero`'s [`winston` dependency](https://github.com/winstonjs/winston/blob/master/lib/winston/exception-handler.js#L197).
 
To avoid depending on such event, we have changed the way to handle it. So now the issue is fixed and the fix is published in the latest extension version 1.0.70.
