### ISSUE TITLE
Postprocessor run failure: Failed to parse ..., TypeError: this[type] is not a function​​

### ISSUE THREAD

**Issue by pietgk** [wallabyjs/public#1448]
### Issue description or question
[Error] ​​Postprocessor run failure: Failed to parse src/containers/SampleView.jsts, TypeError: this[type] is not a function​​
[Error] ​​    at _combinedTickCallback (internal/process/next_tick.js:131:7)​​
[Error] ​​    at process._tickCallback (internal/process/next_tick.js:180:9)​​

previous issue context used to reproduce this error:
https://github.com/wallabyjs/public/issues/1359#issuecomment-338633214

sample repository to reproduce this error is https://github.com/ArtemGovorov/wallaby-1359
just start wallaby in vscode and you get the error.

wallaby was just updated (2-jan 2018), ls ~/.vscode/extensions =>
WallabyJs.quokka-vscode-1.0.89/  WallabyJs.wallaby-vscode-1.0.70/

Please help, this is blocking my workflow.

### Wallaby.js configuration file

```javascript
// see https://github.com/ArtemGovorov/wallaby-1359 for simple working example
// after issue https://github.com/wallabyjs/public/issues/1359#issuecomment-338633214
//
module.exports = function (wallaby) {
  // eslint-disable-next-line
  console.log(wallaby);
  return {
    files: [
      { pattern: 'src/containers/SampleView.js', load: false },
      // { pattern: 'src/**/*.+(t|j)s*', load: false },
      { pattern: '!src/__tests__/*.test.ts', load: false },
    ],

    tests: [
      'src/__tests__/*.test.ts',
    ],

    env: {
      type: 'node',
      runner: 'node',
    },

    compilers: {
      'src/**/*.+(t|j)s*': wallaby.compilers.typeScript(),
    },

    preprocessors: {
      // eslint-disable-next-line global-require, import/no-extraneous-dependencies
      '**/*.+(js|jsts)': file => file.type === 'ts' ? file.content : require('babel-core').transform(
        file.changeExt('js').content,
        {sourceMap: true, compact: false, filename: file.path, presets: ['react-native']}),
    },

    testFramework: 'jest',

    debug: true,
    // for node.js tests you need to set env property as well
    // https://wallabyjs.com/docs/integration/node.html
  };
};```

Visual Studio Code v1.19.1
OSX 10.12.6

**Comment by pietgk** [comment]
Wallaby.js console logging is:

```
​​​​​[Info]​​​​​ { localProjectDir: '/Users/grop/dev/innotronic/wallaby-1359/',
​​​​​[Info]​​​​​   projectCacheDir: '/Users/grop/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/projects/b2569161424ad387/instrumented',
​​​​​[Info]​​​​​   compilers: 
​​​​​[Info]​​​​​    { coffeeScript: [Function],
​​​​​[Info]​​​​​      babel: [Function],
​​​​​[Info]​​​​​      typeScript: [Function: typeScript] },
​​​​​[Info]​​​​​   postprocessors: { typeScript: [Function] },
​​​​​[Info]​​​​​   defaults: 
​​​​​[Info]​​​​​    { files: { ignore: false, instrument: true, trigger: true, load: true },
​​​​​[Info]​​​​​      tests: { ignore: false, instrument: true, trigger: true, load: true } } }
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:23 GMT wallaby:project Wallaby config: /Users/grop/dev/innotronic/wallaby-1359/wallaby.conf.js
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:23 GMT wallaby:fs File added: src/containers/SampleView.js
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:23 GMT wallaby:fs File added: package.json
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.533
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:23 GMT wallaby:fs File added: src/__tests__/BluethoothConnector.test.ts
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:project File cache: /Users/grop/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/projects/b2569161424ad387
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:uiService Listening port 51235
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:project package.json file change detected, invalidating local cache
​​​​​[Info]​​​​​ Wallaby App (realtime reports) is available at: http://localhost:51245
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:workers Parallelism for initial run: 6, for regular run: 3
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:workers Starting run worker instance #0
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:workers Starting run worker instance #1
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:workers Starting run worker instance #2
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:workers Starting run worker instance #3
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:workers Starting run worker instance #4
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:workers Starting run worker instance #5
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:workers Web server is listening at 51289
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:project File cache requires some updates, waiting required files from IDE
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:project File src/containers/SampleView.js changes are patches only: false
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:project File package.json changes are patches only: false
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:project File src/__tests__/BluethoothConnector.test.ts changes are patches only: false
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:project Preparing to process package.json
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:project File package.json is not instrumented by core
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:project Preparing to process src/containers/SampleView.js
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:project Preparing to process src/__tests__/BluethoothConnector.test.ts
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:workers Started run worker instance (delayed) #2
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:workers Started run worker instance (delayed) #3
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:workers Started run worker instance (delayed) #1
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:workers Started run worker instance (delayed) #0
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:workers Started run worker instance (delayed) #5
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:24 GMT wallaby:workers Started run worker instance (delayed) #4
​​​​​[Info]​​​​​ { localProjectDir: '/Users/grop/dev/innotronic/wallaby-1359/',
​​​​​[Info]​​​​​   projectCacheDir: '/Users/grop/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/projects/b2569161424ad387/instrumented',
​​​​​[Info]​​​​​   compilers: 
​​​​​[Info]​​​​​    { coffeeScript: [Function],
​​​​​[Info]​​​​​      babel: [Function],
​​​​​[Info]​​​​​      typeScript: [Function: typeScript] },
​​​​​[Info]​​​​​   postprocessors: { typeScript: [Function] },
​​​​​[Info]​​​​​   defaults: 
​​​​​[Info]​​​​​    { files: { ignore: false, instrument: true, trigger: true, load: true },
​​​​​[Info]​​​​​      tests: { ignore: false, instrument: true, trigger: true, load: true } } }
​​​​​[Info]​​​​​ { localProjectDir: '/Users/grop/dev/innotronic/wallaby-1359/',
​​​​​[Info]​​​​​   projectCacheDir: '/Users/grop/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/projects/b2569161424ad387/instrumented',
​​​​​[Info]​​​​​   compilers: 
​​​​​[Info]​​​​​    { coffeeScript: [Function],
​​​​​[Info]​​​​​      babel: [Function],
​​​​​[Info]​​​​​      typeScript: [Function: typeScript] },
​​​​​[Info]​​​​​   postprocessors: { typeScript: [Function] },
​​​​​[Info]​​​​​   defaults: 
​​​​​[Info]​​​​​    { files: { ignore: false, instrument: true, trigger: true, load: true },
​​​​​[Info]​​​​​      tests: { ignore: false, instrument: true, trigger: true, load: true } } }
​​​​​[Info]​​​​​ { localProjectDir: '/Users/grop/dev/innotronic/wallaby-1359/',
​​​​​[Info]​​​​​   projectCacheDir: '/Users/grop/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/projects/b2569161424ad387/instrumented',
​​​​​[Info]​​​​​   compilers: 
​​​​​[Info]​​​​​    { coffeeScript: [Function],
​​​​​[Info]​​​​​      babel: [Function],
​​​​​[Info]​​​​​      typeScript: [Function: typeScript] },
​​​​​[Info]​​​​​   postprocessors: { typeScript: [Function] },
​​​​​[Info]​​​​​   defaults: 
​​​​​[Info]​​​​​    { files: { ignore: false, instrument: true, trigger: true, load: true },
​​​​​[Info]​​​​​      tests: { ignore: false, instrument: true, trigger: true, load: true } } }
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:processor No compilers found for src/containers/SampleView.js
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project File src/containers/SampleView.js is not instrumented by core
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:processor WARNING: could not find and load babel-preset-jest preset, it is required for correct jest.mock(...) calls hoisting
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:processor Running 1 processor(s) for src/containers/SampleView.js
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:processor Finished running one processor for src/containers/SampleView.js
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project Writing to disk and caching processed file src/containers/SampleView.js
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project File src/containers/SampleView.js changes saved, store ts: 1514911322000, change ts: 1514918304457
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:processor No compilers found for src/__tests__/BluethoothConnector.test.ts
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project File src/__tests__/BluethoothConnector.test.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:processor No preprocessors found for src/__tests__/BluethoothConnector.test.ts
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project Writing to disk and caching processed file src/__tests__/BluethoothConnector.test.ts
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project File src/__tests__/BluethoothConnector.test.ts changes saved, store ts: 1514911322000, change ts: 1514918304458
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:processor No preprocessors found for package.json
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project Writing to disk and caching processed file package.json
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project File package.json changes saved, store ts: 1514918236000, change ts: 1514918304458
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project Stopping process pool
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project Running postprocessor
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:postprocessor New TypeScript language service is required
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:postprocessor TypeScript compiler options module (before tsconfig.json): undefined
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:postprocessor TypeScript compiler options module (after tsconfig.json): 5
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project Preparing to process src/containers/SampleView.jsts
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project Preparing to process src/__tests__/BluethoothConnector.test.js
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project Processing compiled src/containers/SampleView.jsts
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project Instrumenting src/containers/SampleView.jsts, via process pool: false
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project Processing compiled src/__tests__/BluethoothConnector.test.js
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project Instrumenting src/__tests__/BluethoothConnector.test.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:processor WARNING: could not find and load babel-preset-jest preset, it is required for correct jest.mock(...) calls hoisting
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:processor Running 1 processor(s) for src/__tests__/BluethoothConnector.test.js
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:processor Finished running one processor for src/__tests__/BluethoothConnector.test.js
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project Error: Failed to parse src/containers/SampleView.jsts, TypeError: this[type] is not a function
​​​​​[Info]​​​​​     at _combinedTickCallback (internal/process/next_tick.js:131:7)
​​​​​[Info]​​​​​     at process._tickCallback (internal/process/next_tick.js:180:9)
​​​​​[Info]​​​​​     at /Users/grop/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/wallaby/server.js:18:3826
​​​​​[Info]​​​​​     at _rejected (/Users/grop/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/wallaby/node_modules/q/q.js:864:24)
​​​​​[Info]​​​​​     at /Users/grop/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/wallaby/node_modules/q/q.js:890:30
​​​​​[Info]​​​​​     at Promise.when (/Users/grop/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/wallaby/node_modules/q/q.js:1142:31)
​​​​​[Info]​​​​​     at Promise.promise.promiseDispatch (/Users/grop/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/wallaby/node_modules/q/q.js:808:41)
​​​​​[Info]​​​​​     at /Users/grop/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/wallaby/node_modules/q/q.js:624:44
​​​​​[Info]​​​​​     at runSingle (/Users/grop/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/wallaby/node_modules/q/q.js:137:13)
​​​​​[Info]​​​​​     at flush (/Users/grop/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/wallaby/node_modules/q/q.js:125:13)
​​​​​[Info]​​​​​     at _combinedTickCallback (internal/process/next_tick.js:131:7)
​​​​​[Info]​​​​​     at process._tickCallback (internal/process/next_tick.js:180:9)
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project Test run finished
​​​​​[Info]​​​​​ Tue, 02 Jan 2018 18:38:25 GMT wallaby:project Test run data re-queued

```

**Comment by pietgk** [comment]
Researching other issue did not give any clue on how to solve this.

**Comment by ArtemGovorov** [comment]
Thanks for the report. Recent parser updates (to support newer JSX spec) had broken the edge case. The bug is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by pietgk** [comment]
ok thx, works again
