### ISSUE TITLE
ngCliWebpackSample with VS Code on MacOS results in ​​Failed: No provider for TestingCompilerFactory!​​

### ISSUE THREAD

**Issue by syamanashi** [wallabyjs/public#1449]
### Issue description or question

I'm trying to set up a new Angular CLI project and get the Wallaby.js working with it using the steps specified in the README of https://github.com/wallabyjs/ngCliWebpackSample.  Each time, I'm getting errors for each .spec test that include:

`​​Failed: No provider for TestingCompilerFactory!​​`

I most recently performed a git clone of https://github.com/wallabyjs/ngCliWebpackSample, performed a `npm install`, then tried running Wallaby.js to get similar errors for each test in VS Code's Output:

```
3 failing tests, 0 passing​​​​​
  
  ​​​​AppComponent should render title in a h1 tag​​​​ ​​​[15 ms]​​​​
    ​​​​
    ​​Failed: StaticInjectorError[TestingCompilerFactory]: ​​
    ​​  NullInjectorError: No provider for TestingCompilerFactory!​​
      at t.<anonymous> ​src/app/app.component.spec.ts:5:4​
    ​​​​
    ​​Failed: StaticInjectorError[TestingCompilerFactory]: ​​
    ​​  NullInjectorError: No provider for TestingCompilerFactory!​​
      at t.<anonymous> ​src/app/app.component.spec.ts:22:4​
  
  ​​​​AppComponent should have as title 'app'​​​​ ​​​[11 ms]​​​​
    ​​​​
    ​​Failed: StaticInjectorError[TestingCompilerFactory]: ​​
    ​​  NullInjectorError: No provider for TestingCompilerFactory!​​
      at t.<anonymous> ​src/app/app.component.spec.ts:5:4​
    ​​​​
    ​​Failed: StaticInjectorError[TestingCompilerFactory]: ​​
    ​​  NullInjectorError: No provider for TestingCompilerFactory!​​
      at t.<anonymous> ​src/app/app.component.spec.ts:17:4​
  
  ​​​​AppComponent should create the app​​​​ ​​​[9 ms]​​​​
    ​​​​
    ​​Failed: StaticInjectorError[TestingCompilerFactory]: ​​
    ​​  NullInjectorError: No provider for TestingCompilerFactory!​​
      at t.<anonymous> ​src/app/app.component.spec.ts:5:4​
    ​​​​
    ​​Failed: StaticInjectorError[TestingCompilerFactory]: ​​
    ​​  NullInjectorError: No provider for TestingCompilerFactory!​​
      at t.<anonymous> ​src/app/app.component.spec.ts:12:4​
```

### Wallaby.js configuration file (copied from above mentioned sample repo)

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader', 'css-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.19.1

### OS name and version

macOS High Sierra v10.13.1

**Comment by ArtemGovorov** [comment]
Just tried to clone the sample project and everything is working as expected for me in VS Code on macOS
<img width="761" alt="screen shot 2018-01-03 at 11 38 11 am" src="https://user-images.githubusercontent.com/979966/34507093-b063f566-f07e-11e7-9ca2-db9cf932758f.png">

Possibly you have some older (globally) installed angular version and webpack (when an from wallaby gets confused). Try checking these folders to see if any of them exist (and delete if so):
```
/Users/your_username/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/projects/77ddf1e9d4664fdd/node_modules
/Users/your_username/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/projects/node_modules
/Users/your_username/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/node_modules
/Users/your_username/.vscode/extensions/node_modules
/Users/your_username/.vscode/node_modules
/Users/your_username/node_modules
/Users/node_modules
/node_modules
```

Also try the same for your local project (ie. checking all levels up from your local project folder, excluding the project's `node_modules`)

**Comment by syamanashi** [comment]
@ArtemGovorov ,

Thank you!  This was a huge help.  I removed the following node_modules directory which is probably not needed any longer as I'm currently using nvm (and was seemingly corrupting my environment):

/Users/your_username/node_modules

Everything is working now after deleting this.  Cheers!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
