### ISSUE TITLE
create-react-app configuration after webpack eject

### ISSUE THREAD

**Issue by sherm84** [wallabyjs/public#1451]
### Issue description or question
After running yarn eject, wallaby stop working

Error: Cannot find module 'react-scripts/scripts/utils/createJestConfig'​​
​​    at Function.Module._resolveFilename (module.js:536:15)​​
​​    at Function.Module._load (module.js:466:25)​​
​​    at Module.require (module.js:579:17)​​
​​    at require (internal/module.js:11:18)​​
​​    at emitTwo (events.js:126:13)​​
​​    at WebSocket.emit (events.js:214:7)​​
​​    at afterWrite (_stream_writable.js:454:3)​​
​​    at onwrite (_stream_writable.js:445:7)​​
​​    at InflateRaw.afterTransform (_stream_transform.js:90:3)​​
​​    at Zlib.callback (zlib.js:515:5)​​

### Wallaby.js configuration file

```javascript
// paste your config here
module.exports = function (wallaby) {

  // Babel, jest-cli and some other modules may be located under
  // react-scripts/node_modules, so need to let node.js know about it
  var path = require('path');
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, 'node_modules') +
    path.delimiter +
    path.join(__dirname, 'node_modules/react-scripts/node_modules');
  require('module').Module._initPaths();

  return {
    files: [
      'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!src/**/*.test.js?(x)'
    ],

    tests: ['src/**/*.test.js?(x)'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['react-app']
      })
    },

    setup: wallaby => {
      const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(p => require.resolve('react-scripts/' + p));
      delete jestConfig.transform['^.+\\.(js|jsx)$'];
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
`eject` deletes react-scripts, so the relevant bits in the config need to be replaced/removed/simplified. The only *required* change is the last one, the rest is just removing things that aren't required anymore:

```diff
// paste your config here
module.exports = function (wallaby) {

- // Babel, jest-cli and some other modules may be located under
- // react-scripts/node_modules, so need to let node.js know about it
- var path = require('path');
- process.env.NODE_PATH +=
-   path.delimiter +
-   path.join(__dirname, 'node_modules') +
-   path.delimiter +
-   path.join(__dirname, 'node_modules/react-scripts/node_modules');
- require('module').Module._initPaths();

  return {
    files: [
      'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!src/**/*.test.js?(x)'
    ],

    tests: ['src/**/*.test.js?(x)'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({
-       babel: require('babel-core'),
-       presets: ['react-app']
      })
    },

    setup: wallaby => {
-     const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(p => require.resolve('react-scripts/' + p));
+     const jestConfig = require('./package.json').jest;
      delete jestConfig.transform['^.+\\.(js|jsx)$'];
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};
```

The final config looks like:

```javascript
module.exports = function (wallaby) {

  return {
    files: [
      'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!src/**/*.test.js?(x)'
    ],

    tests: ['src/**/*.test.js?(x)'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({})
    },

    setup: wallaby => {
      const jestConfig = require('./package.json').jest;
      delete jestConfig.transform['^.+\\.(js|jsx)$'];
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};

```

**Comment by sherm84** [comment]
Thanks!

**Comment by mcasey8540** [comment]
If using React, try adding the following to `plugins/index.js `

```
const webpack = require("@cypress/webpack-preprocessor");

// This function is called when a project is opened or re-opened (e.g. due to
// the project's config changing)

const mywebpackoptions = {
  module: {
    rules: [
      {
        test: /^.+\\.(js|jsx)$/,
        loader: "babel-loader",
        enforce: "pre",
        exclude: /(node_modules)/
      }
    ]
  }
};

module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  const options = {
    // send in the options from your webpack.config.js, so it works the same
    // as your app's code
    webpackOptions: mywebpackoptions,
    watchOptions: {}
  };

  on("file:preprocessor", webpack(options));
};
```

**Comment by incognos** [comment]
Hi, I am using an ejected create-react-app and I am getting the following errors using the config above:

```
SyntaxError: Unexpected token 'const'​​
  at ​src/App.js:31:2​
​​SyntaxError: Unexpected token ')'​​
  at ​src/App.test.js:7:0​
​​SyntaxError: Use of reserved word 'class'​​
  at ​src/components/agency/add.js:12​
​​SyntaxError: Use of reserved word 'class'​​
  at ​src/components/agency/edit.js:13​
```

Obviously I am using ES6 - any suggestions on how to resolve this. I am at a bit of a loss

Cheers

**Comment by incognos** [comment]
Just realized this was dealt with: 

https://github.com/wallabyjs/public/issues/1616

**Comment by smcenlly** [comment]
Thanks for the update. Let us know if you run into any other problems.
