### ISSUE TITLE
Vue SFC with jest 

### ISSUE THREAD

**Issue by marocchino** [wallabyjs/public#1456]
### Issue description or question

I am trying to setup wallaby and got error messages like 'Cannot read property 'plugins' of null​​. '.
After this message, I checked fail to collect vue sfc coverages.

```
​​[Error] Runtime error: TypeError: Cannot read property 'plugins' of null​​
​​[Error]     at Object.transformBabel [as babel] (/Users/username/Documents/projectname/node_modules/jest-vue-preprocessor/transforms/transformBabel.js:56:22)​​
​​[Error]     at Object.process (/Users/username/Documents/projectname/node_modules/jest-vue-preprocessor/index.js:62:36)​​
​​[Error]     at ScriptTransformer.transformSource (/Users/username/Documents/projectname/node_modules/jest-runtime/build/script_transformer.js:218:35)​​
​​[Error]     at ScriptTransformer._transformAndBuildScript (/Users/username/Documents/projectname/node_modules/jest-runtime/build/script_transformer.js:291:40)​​
​​[Error]     at ScriptTransformer.transform (/Users/username/Documents/projectname/node_modules/jest-runtime/build/script_transformer.js:332:21)​​
​​[Error]     at Runtime._execModule (/Users/username/Documents/projectname/node_modules/jest-runtime/build/index.js:501:53)​​
​​[Error]     at Runtime.requireModule (/Users/username/Documents/projectname/node_modules/jest-runtime/build/index.js:332:14)​​
​​[Error]     at Runtime.requireModuleOrMock (/Users/username/Documents/projectname/node_modules/jest-runtime/build/index.js:408:19)​​
​​[Error]     at Object.<anonymous> (./src/components/__tests__/TaskListItem-test.js:4:35)​​
​​[Error]     at Runtime._execModule (/Users/username/Documents/projectname/node_modules/jest-runtime/build/index.js:520:13)​​
​​[Error]     at Runtime.requireModule (/Users/username/Documents/projectname/node_modules/jest-runtime/build/index.js:332:14)​​
​​[Error]     at /Users/username/Documents/projectname/node_modules/jest-jasmine2/build/index.js:101:13​​
​​[Error]     at Generator.next (<anonymous>)​​
​​[Error]     at step (/Users/username/Documents/projectname/node_modules/jest-jasmine2/build/index.js:106:583)​​
​​[Error]     at /Users/username/Documents/projectname/node_modules/jest-jasmine2/build/index.js:106:813​​
​​[Error]     at new Promise (<anonymous>)​​
​​[Error]     at /Users/username/Documents/projectname/node_modules/jest-jasmine2/build/index.js:106:494​​
​​[Error]     at jasmine2 (/Users/username/Documents/projectname/node_modules/jest-jasmine2/build/index.js:106:68)​​
​​[Error]     at runTest (/Users/username/Documents/projectname/node_modules/jest-runner/build/run_test.js:98:10)​​
​​[Error]     at /Users/username/Documents/projectname/node_modules/jest-runner/build/index.js:71:68​​
​​[Error]     at Generator.next (<anonymous>)​​
​​[Error]     at step (/Users/username/Documents/projectname/node_modules/jest-runner/build/index.js:23:376)​​
​​[Error]     at /Users/username/Documents/projectname/node_modules/jest-runner/build/index.js:23:536​​
​​[Error]     at <anonymous>​​
​​[Error]     at process._tickCallback (internal/process/next_tick.js:188:7)​​
​​​​​[Info]​​​​​ console.log: FAIL src/components/__tests__/TaskList-test.js
​​​​​[Info]​​​​​ console.log:   ● Test suite failed to run
​​​​​[Info]​​​​​     TypeError: Cannot read property 'plugins' of null
​​​​​[Info]​​​​​
​​​​​[Info]​​​​​       at Object.transformBabel [as babel] (node_modules/jest-vue-preprocessor/transforms/transformBabel.js:56:22)
​​​​​[Info]​​​​​       at Object.process (node_modules/jest-vue-preprocessor/index.js:62:36)
​​​​​[Info]​​​​​       at Runtime.u._wallabyReplaced.l.requireModule (../../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/wallaby/runners/node/jest@0.4.3/initializer.js:14:17457)
​​​​​[Info]​​​​​       at Object.<anonymous> (../../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/projects/8a07f34e08979d35/instrumented/src/components/__tests__/TaskList-test.js:8:31)
​​​​​[Info]​​​​​       at Runtime.u._wallabyReplaced.l.requireModule (../../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/wallaby/runners/node/jest@0.4.3/initializer.js:14:17457)
​​​​​[Info]​​​​​           at Generator.next (<anonymous>)
​​​​​[Info]​​​​​           at new Promise (<anonymous>)
​​​​​[Info]​​​​​           at Generator.next (<anonymous>)
​​​​​[Info]​​​​​           at <anonymous>
​​​​​[Info]​​​​​       at process._tickCallback (../../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/projects/8a07f34e08979d35/instrumented/internal/process/next_tick.js:188:7)
​​​​​[Info]​​​​​ Wed, 10 Jan 2018 06:41:56 GMT wallaby:workers [36ri7] Run 0 test(s), skipped 0 test(s)
​​​​​[Info]​​​​​ console.log: FAIL src/components/__tests__/TaskListItem-test.js
​​​​​[Info]​​​​​ console.log:   ● Test suite failed to run
​​​​​[Info]​​​​​     TypeError: Cannot read property 'plugins' of null
​​​​​[Info]​​​​​
​​​​​[Info]​​​​​       at Object.transformBabel [as babel] (node_modules/jest-vue-preprocessor/transforms/transformBabel.js:56:22)
​​​​​[Info]​​​​​       at Object.process (node_modules/jest-vue-preprocessor/index.js:62:36)
​​​​​[Info]​​​​​       at Runtime.u._wallabyReplaced.l.requireModule (../../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/wallaby/runners/node/jest@0.4.3/initializer.js:14:17457)
​​​​​[Info]​​​​​       at Object.<anonymous> (../../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/projects/8a07f34e08979d35/instrumented/src/components/__tests__/TaskListItem-test.js:4:35)
​​​​​[Info]​​​​​       at Runtime.u._wallabyReplaced.l.requireModule (../../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/wallaby/runners/node/jest@0.4.3/initializer.js:14:17457)
​​​​​[Info]​​​​​           at Generator.next (<anonymous>)
​​​​​[Info]​​​​​           at new Promise (<anonymous>)
​​​​​[Info]​​​​​           at Generator.next (<anonymous>)
​​​​​[Info]​​​​​           at <anonymous>
​​​​​[Info]​​​​​       at process._tickCallback (../../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/projects/8a07f34e08979d35/instrumented/internal/process/next_tick.js:188:7)
​​​​​[Info]​​​​​ console.log: Test Suites: 2 failed, 2 total
​​​​​[Info]​​​​​ Tests:       0 total
​​​​​[Info]​​​​​ Snapshots:   0 total
​​​​​[Info]​​​​​ Time:        1.792s
​​​​​[Info]​​​​​ Ran all test suites.
​​​​​[Info]​​​​​ Wed, 10 Jan 2018 06:41:56 GMT wallaby:workers [36ri7] Sandbox is responsive, closing it
​​​​​[Info]​​​​​ Wed, 10 Jan 2018 06:41:56 GMT wallaby:workers Merging parallel test run results
​​​​​[Info]​​​​​ Finished executing 13 affected test(s)
```

### Wallaby.js configuration file

<https://github.com/riseshia/gannbaruzoi-frontend/blob/wallaby/wallaby.js>

```javascript
module.exports = function (wallaby) {
  return {
    files: ['src/**/*', '!src/**/__tests__/**/*', 'package.json'],

    tests: ['src/**/__tests__/*-test.js'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
      '**/*.vue': require('wallaby-vue-compiler')(wallaby.compilers.babel({}))
    },

    setup: function (wallaby) {
      var jestConfig = require('./package.json').jest
      if (!jestConfig.globals) {
        jestConfig.globals = {}
      }
      jestConfig.moduleNameMapper = {
        '^@/(.*)$': wallaby.projectCacheDir + '/src/$1'
      }
      jestConfig.globals['__DEV__'] = true
      wallaby.testFramework.configure(jestConfig)
    },

    testFramework: 'jest',
    debug: true
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.19.1

### OS name and version

OSX 10.13.2

**Comment by ArtemGovorov** [comment]
Looks like `jest-vue-preprocessor` looks up babel config in `process.cwd()` (as opposed to the Jest `rootDir`) and it is the wallaby cache folder, so the file `.babelrc` file needs to be in the `files` list to get to the wallaby cache. I have sent you [the pull request](https://github.com/riseshia/gannbaruzoi-frontend/pull/31) with the change to make it work.

**Comment by ArtemGovorov** [comment]
Also, for correct error stack mappings in `.vue` files, the `jest-vue-preprocessor` needs to be applied as Wallaby preprocessor (and not as a jest transform). I have sent you another [pull request with the change](https://github.com/riseshia/gannbaruzoi-frontend/pull/32). 

With this change, the previous change is not required, so your final config should look like:

```diff
module.exports = function (wallaby) {
  return {
    files: ['src/**/*', '!src/**/__tests__/**/*', 'package.json'],

    tests: ['src/**/__tests__/*-test.js'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
      '**/*.vue': require('wallaby-vue-compiler')(wallaby.compilers.babel({}))
    },

+   preprocessors: {
+     '**/*.vue': file => require('jest-vue-preprocessor').process(file.content, file.path)
+   },

    setup: function (wallaby) {
      var jestConfig = require('./package.json').jest
      if (!jestConfig.globals) {
        jestConfig.globals = {}
      }
      jestConfig.moduleNameMapper = {
        '^@/(.*)$': wallaby.projectCacheDir + '/src/$1'
      }
      jestConfig.globals['__DEV__'] = true
+     delete jestConfig.transform['\\.vue$']
      wallaby.testFramework.configure(jestConfig)
    },

    testFramework: 'jest',
    debug: true
  }
}
```

**Comment by bbugh** [comment]
If you're using the default Vue `webpack` template setup with your jest config in `test/unit/jest.conf.js` instead of `package.json` like the above setup, this wallaby config will work for you:

```javascript
// Add `jest-vue-preprocessor` to your dev dependencies

module.exports = function (wallaby) {
  return {
    files: ['src/**/*', 'package.json'],

    tests: ['test/**/*.spec.js'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
      '**/*.vue': require('wallaby-vue-compiler')(wallaby.compilers.babel({}))
    },

    preprocessors: {
      '**/*.vue': file => require('jest-vue-preprocessor').process(file.content, file.path)
    },

    setup: function (wallaby) {
      const jestConfig = {}

      jestConfig.moduleNameMapper = {
        '^@/(.*)$': wallaby.projectCacheDir + '/src/$1'
      }
      wallaby.testFramework.configure(jestConfig)
    },

    testFramework: 'jest',
    debug: true
  }
}
```

**Comment by c0h1b4** [comment]
Hello bbugh,

After using your wallaby config file, I'm getting the following error:

Configuration error:​​
​​​​
​​Could not locate module @/components/HelloWorld (mapped as ./src/components/HelloWorld)​​

any hints?

**Comment by ArtemGovorov** [comment]
I have edited the config a bit (hope you don't mind @bbugh). @c0h1b4 please try the latest version, should work now.

**Comment by c0h1b4** [comment]
Hi Artem, still on error:

Configuration error:​​
​​​​
​​Could not locate module @/components/HelloWorld (mapped as ./src/components/HelloWorld)​​
​​​​
​​Please check:​​
​​​​
​​"moduleNameMapper": {​​
​​  "/^@\/(.*)$/": "C:\Users\myself\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.74\projects\816d26c58610c7aa\instrumented/src/$1"​​
​​},​​
​​"resolver": undefined​​

**Comment by ArtemGovorov** [comment]
Looks like it's the issue with paths concatenation on Windows. I modified the config again to handle it correctly, so try again. I have also created this repo branch https://github.com/ArtemGovorov/gannbaruzoi-frontend/tree/helloworld that is working for me with this config.

**Comment by bbugh** [comment]
I've never managed to get Jest coverage to work with Vue—with or without wallabyjs—so I don't think it's related.

**Comment by ArtemGovorov** [comment]
Wallaby doesn't actually need Jest coverage, it calculates its own and it's it's working out-of-box with zero config for it. 

It's easy to see how it's working in the sample repo https://github.com/ArtemGovorov/gannbaruzoi-frontend/tree/helloworld. If you just run it, it'll show 0% coverage in [Wallaby App](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html) and it's expected because the `HelloWorld.vue` [component methods don't have any code](https://github.com/ArtemGovorov/gannbaruzoi-frontend/blob/helloworld/src/components/HelloWorld.vue#L7-L20), so no coverage. If you add any code to any of the methods, then it'll start showing the code coverage:

<img width="858" alt="screen shot 2018-01-19 at 12 37 47 pm" src="https://user-images.githubusercontent.com/979966/35132209-bf9e2a30-fd15-11e7-8e2d-36b0a6df5a21.png">

**Comment by ArtemGovorov** [comment]
In case if anyone is looking for a wallaby config for `vue-cli` generated project:

```javascript
module.exports = (wallaby) => {

  const compiler = wallaby.compilers.babel({presets: [['@vue/app', {modules: 'commonjs'}]]})

  return {
    files: ['src/**/*', 'package.json'],

    tests: ['test/**/*.spec.js'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js': compiler,
      '**/*.vue': require('wallaby-vue-compiler')(compiler)
    },

    preprocessors: {
      '**/*.vue': file => require('jest-vue-preprocessor').process(file.content, file.path)
    },

    setup: function (wallaby) {
      const jestConfig = require('./package.json').jest || {}

      jestConfig.moduleNameMapper = {
        '^@/components/([^\\.]*)$': wallaby.projectCacheDir + '/src/components/$1.vue',
        '^@/(.*)$': wallaby.projectCacheDir + '/src/$1'
      }
      jestConfig.transform = {}

      wallaby.testFramework.configure(jestConfig)
    },

    testFramework: 'jest',

    debug: true
  }
}
```

**Comment by Ldoppea** [comment]
This works great, thank you!

I like to have my tests on site of their component, so tried to modify the config file and replace
`tests: ['test/**/*.spec.js']`
by
`tests: ['test/**/*.spec.js', 'src/**/*.spec.js']`
Then I sopped/started wallaby.

But only tests in the `test` folder are executed, The one in `src` folder are not covered. Is that because they are in the `files` folder?
`files: ['src/**/*', 'package.json']`

**Comment by ArtemGovorov** [comment]
> But only tests in the `test` folder are executed, The one in `src` folder are not covered. Is that because they are in the `files` folder?

Yes, and [Wallaby Console](https://wallabyjs.com/docs/intro/get-started-sublime.html#troubleshooting) as well as [Wallaby Failing Tests console](https://wallabyjs.com/docs/intro/get-started-sublime.html#failing-tests) should display the message about it (even a config snippet to fix it). You need to exclude tests from `files`:

```
files: ['src/**/*', 'package.json', '!src/**/*.spec.js']
```

**Comment by Ldoppea** [comment]
Ok, sorry I missed that console line, it was lost in the ~200 lines printed by the start process. Works better now. Thanks for all your help.

**Comment by ArtemGovorov** [comment]
> Ok, sorry I missed that console line, it was lost in the ~200 lines printed by the start process.

You may remove the `debug: true` line from your config and that'll make wallaby print only important stuff to the console.

**Comment by ArtemGovorov** [comment]
P.S. Have removed the setting from sample configs published here as well.

**Comment by bbugh** [comment]
@ArtemGovorov unfortunately in the never ending 💩 battle with JavaScript's configuration systems, [that config you posted](https://github.com/wallabyjs/public/issues/1456#issuecomment-361140961) for `vue-cli` with `webpack` doesn't work with an out of the box latest (non-pre) version of `vue-cli`. 

```
» vue -V
2.9.3

» vue init webpack wallaby-test    

? Project name wallaby-test
? Project description A Vue.js project
? Author <name>
? Vue build standalone
? Install vue-router? Yes
? Use ESLint to lint your code? Yes
? Pick an ESLint preset Standard
? Set up unit tests Yes
? Pick a test runner jest
? Setup e2e tests with Nightwatch? No
? Should we run `npm install` for you after the project has been created? (recom
mended) yarn

   vue-cli · Generated "wallaby-test"
[snip]

» yarn add --dev jest-vue-preprocessor wallaby-vue-compiler
» cat > wallaby.conf.js # paste the config you posted
```

Results in this error:

```
[Error] ​​Failed to run compilers on test/unit/specs/HelloWorld.spec.js, Error: Couldn't find preset "@vue/app" relative to directory "test/unit/specs"​​
[Error] ​​    at .../wallaby-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19​​
[Error] ​​    at Array.map (<anonymous>)​​
[Error] ​​    at OptionManager.resolvePresets (.../wallaby-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)​​
[Error] ​​    at OptionManager.mergePresets (.../wallaby-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)​​
[Error] ​​    at OptionManager.mergeOptions (.../wallaby-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)​​
[Error] ​​    at OptionManager.init (.../wallaby-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)​​
[Error] ​​    at File.initOptions (.../wallaby-test/node_modules/babel-core/lib/transformation/file/index.js:212:65)​​
[Error] ​​    at new File (.../wallaby-test/node_modules/babel-core/lib/transformation/file/index.js:135:24)​​
[Error] ​​    at Pipeline.transform (.../wallaby-test/node_modules/babel-core/lib/transformation/pipeline.js:46:16)​​
[Error] ​​    at _combinedTickCallback (internal/process/next_tick.js:131:7)​​
[Error] ​​    at process._tickCallback (internal/process/next_tick.js:180:9)​​
```

**Comment by bbugh** [comment]
Also, with the same setup except using the `wallaby.conf.js` [that I posted that you edited](https://github.com/wallabyjs/public/issues/1456#issuecomment-357470417), I get this error:

```
​​​​​0 failing tests, 0 passing​​​​​
​​​​​​​​​​
​​TypeError: Cannot convert undefined or null to object​​
​​    at emitTwo (events.js:126:13)​​
​​    at WebSocket.emit (events.js:214:7)​​
​​    at afterWrite (_stream_writable.js:454:3)​​
​​    at onwrite (_stream_writable.js:445:7)​​
​​    at InflateRaw.afterTransform (_stream_transform.js:90:3)​​
​​    at Zlib.callback (zlib.js:515:5)​​
```

**Comment by Ldoppea** [comment]
Answering your first post :
The last config he posted was working on vue-cli 3.0-alpha.4, but not sure if it worked on 2.9.

Did you edit your `package.json` file by adding `jest-vue-preprocessor` to `jest.transform` like following?

```
"jest": {
    ...
    ,
    "transform": {
      "^.+\\.vue$": "jest-vue-preprocessor",
      "^.+\\.jsx?$": "babel-jest"
    },
    ...
```

**Comment by ArtemGovorov** [comment]
@bbugh Updated the config you've posted that IO have edited to make it work. Also updated my post to specify where to find working config for vue-cli v3 and where to find one for vue-cli v2.

**Comment by ArtemGovorov** [comment]
@SimonSiefke Could you please share the template that you are using to generate your project with vue/cli and your vue/cli version? Eg. `vue init ?`

**Comment by ArtemGovorov** [comment]
It should be pretty straightforward to set up, however note that wallaby doesn't support code coverage for TypeScript in `.vue` files. Tests will still run ok, and separate/referenced TypeScript files are highlighted as expected, just not `script` sections of `.vue` written in TypeScript.

**Comment by SimonSiefke** [comment]
@ArtemGovorov I am using vue v3.0.0-alpha-13. 
1. I created a project with 'vue create myProject' and selected the features TypeScript and Unit Testing and Jest as the testing framework: </summary>
```
Vue CLI v3.0.0-alpha.13
? Please pick a preset: Manually select features
? Check the features needed for your project: TS, Unit
? Use class-style component syntax? No
? Use Babel alongside TypeScript for auto-detected polyfills? No
? Pick a unit testing solution: Jest
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In package.json
? Save this as a preset for future projects? (Y/n) n
```
2. I installed wallaby-vue-compiler and jest-vue-preprocessor
```bash
yarn add -D wallaby-vue-compiler jest-vue-preprocessor
```
3. I tried to set up wallaby based on your configuration file
```js
// wallaby.js
module.exports = wallaby => {
  const compiler = wallaby.compilers.typeScript({
    presets: [['@vue/app', { modules: 'commonjs' }]],
  })

  return {
    files: ['src/**/*', 'package.json'],

    tests: ['test/**/*.spec.ts'],

    env: {
      type: 'node',
      runner: 'node',
    },

    compilers: {
      '**/*.ts': compiler,
      '**/*.vue': require('wallaby-vue-compiler')(compiler),
    },

    preprocessors: {
      '**/*.vue': file =>
        require('jest-vue-preprocessor').process(file.content, file.path),
    },

    setup(wallaby) {
      const jestConfig = require('./package.json').jest || {}

      jestConfig.moduleNameMapper = {
        '^@/components/([^\\.]*)$':
          wallaby.projectCacheDir + '/src/components/$1.vue',
        '^@/(.*)$': wallaby.projectCacheDir + '/src/$1',
      }
      jestConfig.transform = {}

      wallaby.testFramework.configure(jestConfig)
    },

    testFramework: 'jest',
  }
}
```

```json
// package.json
{
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test": "vue-cli-service test"
  },
  "dependencies": {
    "vue": "^2.5.13"
  },
  "devDependencies": {
    "@types/jest": "^22.0.1",
    "@vue/cli-plugin-typescript": "^3.0.0-alpha.13",
    "@vue/cli-plugin-unit-jest": "^3.0.0-alpha.13",
    "@vue/cli-service": "^3.0.0-alpha.13",
    "@vue/test-utils": "^1.0.0-beta.10",
    "jest-vue-preprocessor": "^1.3.1",
    "ts-jest": "^22.0.1",
    "vue-template-compiler": "^2.5.13",
    "wallaby-vue-compiler": "^1.0.2"
  },
  "browserslist": ["> 1%", "last 2 versions", "not ie <= 8"],
  "jest": {
    "moduleFileExtensions": ["ts", "tsx", "js", "jsx", "json", "vue"],
    "transform": {
      "^.+\\.vue$": "vue-jest",
      "^.+\\.tsx?$": "ts-jest"
    },
    "moduleNameMapper": {
      "^@/(.*)$": "<rootDir>/src/$1"
    },
    "snapshotSerializers": ["jest-serializer-vue"],
    "mapCoverage": true
  }
}

```
4. I get the follwowing error:
```
[Error] ​​Failed to run compilers on src/App.vue, TypeError: scriptCompiler is not a function​​
[Error] ​​    at /home/simon/Documents/myProject/node_modules/wallaby-vue-compiler/index.js:16:29​​
[Error] ​​    at process._tickCallback (internal/process/next_tick.js:150:11)​​

```

**Comment by ArtemGovorov** [comment]
@SimonSiefke Here's the config that should work for you for **`vue-cli` v3.0.0-alpha-13 + TypeScript**:

```javascript
module.exports = wallaby => {

  return {
    files: ['src/**/*', 'package.json', 'tsconfig.json'],

    tests: ['test/**/*.spec.ts'],

    env: {
      type: 'node',
      runner: 'node',
    },


    preprocessors: {
      '**/*.js?(x)': file => require('babel-core').transform(
        file.content,
        {sourceMap: true, compact: false, filename: file.path, plugins: ['transform-es2015-modules-commonjs']})
    },

    setup(wallaby) {
      const jestConfig = require('./package.json').jest || {}

      jestConfig.moduleNameMapper = {
        '^@/components/([^\\.]*)$':
        wallaby.projectCacheDir + '/src/components/$1.vue',
        '^@/(.*)$': wallaby.projectCacheDir + '/src/$1',
      }

      delete jestConfig.transform['^.+\\.tsx?$']

      wallaby.testFramework.configure(jestConfig)
    },

    testFramework: 'jest'
  }
}
```

Note however that, as I have mentioned earlier, wallaby doesn't support code coverage for TypeScript inside `.vue` files.

**Comment by SimonSiefke** [comment]
This works great! Thanks for your effort. 😄

**Comment by tony19** [comment]
@ArtemGovorov I'm interested in trying my hand at adding code coverage support for TypeScript in `.vue` files. How can I contribute?

**Comment by ArtemGovorov** [comment]
@tony19 Thanks for offering your help! We are working on a better Jest integration at the moment, and the scenario will most likely be covered.
