### ISSUE TITLE
Create React App confijg example doesn't work with Enzyme

### ISSUE THREAD

**Issue by haluvibe** [wallabyjs/public#1525]
### Issue description or question

Create React App confijg example found here -> [https://wallabyjs.com/docs/integration/react-jsx.htm](https://wallabyjs.com/docs/integration/react-jsx.html) doesn't work with Enzyme.

repo here -> [https://github.com/haluvibe/curious](https://github.com/haluvibe/curious)

```
/Users/paulhayes/sites/curious/src/setupTests.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { configure } from "enzyme";
                                                                                         ^^^^^^

SyntaxError: Unexpected token import
    at ScriptTransformer._transformAndBuildScript (/Users/paulhayes/sites/curious/node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
    at ScriptTransformer.transform (/Users/paulhayes/sites/curious/node_modules/jest-runtime/build/ScriptTransformer.js:316:21)
    at Runtime._execModule (/Users/paulhayes/sites/curious/node_modules/jest-runtime/build/index.js:494:53)
    at Runtime.requireModule (/Users/paulhayes/sites/curious/node_modules/jest-runtime/build/index.js:329:14)
    at jasmine2 (/Users/paulhayes/sites/curious/node_modules/jest-jasmine2/build/index.js:89:13)
    at runTest (/Users/paulhayes/sites/curious/node_modules/jest-cli/build/runTest.js:85:10)
    at promise.then (/Users/paulhayes/sites/curious/node_modules/jest-cli/build/TestRunner.js:197:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Wallaby.js configuration file

```javascript

module.exports = function (wallaby) {
  // Babel, jest-cli and some other modules may be located under
  // react-scripts/node_modules, so need to let node.js know about it
  var path = require("path");
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, "node_modules") +
    path.delimiter +
    path.join(__dirname, "node_modules/react-scripts/node_modules");
  require("module").Module._initPaths();

  return {
    files: [
      "src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)",
      "!src/**/*.test.js?(x)"
    ],

    tests: ["src/**/*.test.js?(x)"],

    env: {
      type: "node",
      runner: "node"
    },

    compilers: {
      "**/*.js?(x)": wallaby.compilers.babel({
        babel: require("babel-core"),
        presets: ["react-app"]
      })
    },

    setup: wallaby => {
      const jestConfig = require("react-scripts/scripts/utils/createJestConfig")(
        p => require.resolve("react-scripts/" + p)
      );
      Object.keys(jestConfig.transform || {}).forEach(
        k => ~k.indexOf("^.+\\.(js|jsx") && void delete jestConfig.transform[k]
      );
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: "jest"
  };
};

```

### Code editor or IDE name and version

Atom v1.24.0 x64

### OS name and version

OSX 10.12.6

**Comment by ArtemGovorov** [comment]
Looks like you are not using the latest version published at  https://wallabyjs.com/docs/integration/react-jsx.htm, here's the bit you're missing:

```diff
    setup: wallaby => {
      const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(p => require.resolve('react-scripts/' + p));
      Object.keys(jestConfig.transform || {}).forEach(k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]);
      delete jestConfig.testEnvironment;
+     if (jestConfig.setupTestFrameworkScriptFile) {
+       jestConfig.setupTestFrameworkScriptFile = jestConfig.setupTestFrameworkScriptFile.replace('<rootDir>', wallaby.projectCacheDir);
+     }
      wallaby.testFramework.configure(jestConfig);
    },
```
