### ISSUE TITLE
Throwing an error with JEST, works from command line and webstorm run config

### ISSUE THREAD

**Issue by appsolutegeek** [wallabyjs/public#1531]
I have just moved over to JEST but I am getting a lot of errors.
I have ts-jest installed and it works via the command line and webstorm normal run config..

For example, my test script is the following and all works well..

`    "test": "react-scripts-ts test --env=jsdom",`

For sure I have missed something.

This is my tsconfig.test.json which I use for compiling import to require..

```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "commonjs"
  }
}
```

I have a file called setupTexts.ts which sits in my src which jest calls automatically, this is 

```
import * as Enzyme from 'enzyme';
import * as Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });
```

My package.json has nothing special and I do not have a jest config file, as I don't need it as far as I know. Same config works from command line and run config in webstorn.

My wallaby configuration file is this, I just converted ti from a working version with mocha.

```
module.exports = function(wallaby) {
  return {
    files: [
      "tsconfig.test.json",
      "src/**/*.ts",
      "src/**/*.tsx",
      { pattern: "src/**/*.test.tsx", ignore: true },
      { pattern: "src/**/*.test.ts", ignore: true }
    ],

    tests: [
      "src/**/*.test.tsx",
      "src/**/*.test.ts"
    ],

    env: {
      type: "node",
      runner: "node"
    },

    testFramework: "jest",
    debug:true
  };
};
```

The error I am getting is basically this, I will place the full debug log below.

```
SyntaxError: Unexpected token import
Runtime error: ./src/App.test.js:2
import * as React from 'react';
^^^^^^

SyntaxError: Unexpected token import
    at ScriptTransformer._transformAndBuildScript (/Users/iang/Development/Personal/my-react-ts-app/node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
    at ScriptTransformer.transform (/Users/iang/Development/Personal/my-react-ts-app/node_modules/jest-runtime/build/ScriptTransformer.js:316:21)
    at Runtime._execModule (/Users/iang/Development/Personal/my-react-ts-app/node_modules/jest-runtime/build/index.js:494:53)
    at Runtime.requireModule (/Users/iang/Development/Personal/my-react-ts-app/node_modules/jest-runtime/build/index.js:329:14)
    at jasmine2 (/Users/iang/Development/Personal/my-react-ts-app/node_modules/jest-jasmine2/build/index.js:97:11)
    at runTest (/Users/iang/Development/Personal/my-react-ts-app/node_modules/jest-cli/build/runTest.js:85:10)
    at promise.then (/Users/iang/Development/Personal/my-react-ts-app/node_modules/jest-cli/build/TestRunner.js:197:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
console.log:  FAIL  ../../../Library/Caches/WebStorm2017.3/wallaby/projects/d840ae028f50f15f/instrumented/src/App.test.js

console.log:   ● Test suite failed to run

    /Users/iang/Library/Caches/WebStorm2017.3/wallaby/projects/d840ae028f50f15f/instrumented/src/App.test.js:2
    import * as React from 'react';
    ^^^^^^
    
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Runtime.u._wallabyReplaced.l.requireModule (../../../Library/Caches/WebStorm2017.3/wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:18045)
          at <anonymous>
      at process._tickCallback (../../../Library/Caches/WebStorm2017.3/wallaby/projects/d840ae028f50f15f/instrumented/internal/process/next_tick.js:188:7)
```

I am using a MAC and the latest version of webstorm IDE 

Here is the full debug log.

```
wallaby.js started
core v1.0.555
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Wallaby config: /Users/iang/Development/Personal/my-react-ts-app/wallaby.conf.js
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project File cache: /Users/iang/Library/Caches/WebStorm2017.3/wallaby/projects/d840ae028f50f15f
Sun, 25 Feb 2018 08:41:11 GMT wallaby:uiService Listening port 51235
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Config file change detected, invalidating local cache
Wallaby App (realtime reports) is available at: http://localhost:51245
Sun, 25 Feb 2018 08:41:11 GMT wallaby:workers Parallelism for initial run: 6, for regular run: 3
Sun, 25 Feb 2018 08:41:11 GMT wallaby:workers Starting run worker instance #0
Sun, 25 Feb 2018 08:41:11 GMT wallaby:workers Starting run worker instance #1
Sun, 25 Feb 2018 08:41:11 GMT wallaby:workers Starting run worker instance #2
Sun, 25 Feb 2018 08:41:11 GMT wallaby:workers Starting run worker instance #3
Sun, 25 Feb 2018 08:41:11 GMT wallaby:workers Starting run worker instance #4
Sun, 25 Feb 2018 08:41:11 GMT wallaby:workers Starting run worker instance #5
Sun, 25 Feb 2018 08:41:11 GMT wallaby:workers Web server is listening at 62749
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project File cache requires some updates, waiting required files from IDE
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project File package.json changes are patches only: false
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project File tsconfig.test.json changes are patches only: false
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project File src/App.tsx changes are patches only: false
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project File src/index.tsx changes are patches only: false
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project File src/App.test.tsx changes are patches only: false
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project File src/setupTests.ts changes are patches only: false
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project File src/registerServiceWorker.ts changes are patches only: false
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project File src/Something/Something.tsx changes are patches only: false
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project File src/__snapshots__/App.test.tsx.snap changes are patches only: false
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Preparing to process package.json
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Starting processor pool (if not yet started)
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project File package.json is not instrumented by core
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Preparing to process tsconfig.test.json
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Starting processor pool (if not yet started)
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Preparing to process src/App.tsx
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Starting processor pool (if not yet started)
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Preparing to process src/index.tsx
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Starting processor pool (if not yet started)
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Preparing to process src/App.test.tsx
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Starting processor pool (if not yet started)
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Preparing to process src/setupTests.ts
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Starting processor pool (if not yet started)
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Preparing to process src/registerServiceWorker.ts
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Starting processor pool (if not yet started)
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Preparing to process src/Something/Something.tsx
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Starting processor pool (if not yet started)
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Preparing to process src/__snapshots__/App.test.tsx.snap
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project Starting processor pool (if not yet started)
Sun, 25 Feb 2018 08:41:11 GMT wallaby:project File src/__snapshots__/App.test.tsx.snap is not instrumented by core
Sun, 25 Feb 2018 08:41:12 GMT wallaby:workers Started run worker instance (delayed) #1
Sun, 25 Feb 2018 08:41:12 GMT wallaby:workers Started run worker instance (delayed) #0
Sun, 25 Feb 2018 08:41:12 GMT wallaby:workers Started run worker instance (delayed) #3
Sun, 25 Feb 2018 08:41:12 GMT wallaby:workers Started run worker instance (delayed) #2
Sun, 25 Feb 2018 08:41:12 GMT wallaby:workers Started run worker instance (delayed) #4
Sun, 25 Feb 2018 08:41:12 GMT wallaby:workers Started run worker instance (delayed) #5
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No compilers found for src/index.tsx
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project File src/index.tsx is not instrumented by core
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No preprocessors found for src/__snapshots__/App.test.tsx.snap
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Writing to disk and caching processed file src/__snapshots__/App.test.tsx.snap
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No compilers found for src/registerServiceWorker.ts
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project File src/registerServiceWorker.ts is not instrumented by core
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No preprocessors found for src/index.tsx
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Writing to disk and caching processed file src/index.tsx
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No preprocessors found for src/registerServiceWorker.ts
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project File src/__snapshots__/App.test.tsx.snap changes saved, store ts: 1519483028018, change ts: 1519548071309
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Writing to disk and caching processed file src/registerServiceWorker.ts
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project File src/index.tsx changes saved, store ts: 1519462625716, change ts: 1519548071308
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project File src/registerServiceWorker.ts changes saved, store ts: 1519462625794, change ts: 1519548071309
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor Running 1 processor(s) for package.json
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor Finished running one processor for package.json
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Writing to disk and caching processed file package.json
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project File package.json changes saved, store ts: 1519482987061, change ts: 1519548071307
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No compilers found for src/App.test.tsx
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project File src/App.test.tsx is not instrumented by core
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No preprocessors found for src/App.test.tsx
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Writing to disk and caching processed file src/App.test.tsx
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project File src/App.test.tsx changes saved, store ts: 1519477555509, change ts: 1519548071308
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No compilers found for src/App.tsx
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project File src/App.tsx is not instrumented by core
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No preprocessors found for src/App.tsx
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Writing to disk and caching processed file src/App.tsx
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project File src/App.tsx changes saved, store ts: 1519483134050, change ts: 1519548071308
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No compilers found for src/Something/Something.tsx
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project File src/Something/Something.tsx is not instrumented by core
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No preprocessors found for src/Something/Something.tsx
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Writing to disk and caching processed file src/Something/Something.tsx
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project File src/Something/Something.tsx changes saved, store ts: 1519483148553, change ts: 1519548071309
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No compilers found for tsconfig.test.json
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project File tsconfig.test.json is not instrumented by core
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No preprocessors found for tsconfig.test.json
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Writing to disk and caching processed file tsconfig.test.json
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project File tsconfig.test.json changes saved, store ts: 1519462625816, change ts: 1519548071308
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No compilers found for src/setupTests.ts
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project File src/setupTests.ts is not instrumented by core
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No preprocessors found for src/setupTests.ts
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Writing to disk and caching processed file src/setupTests.ts
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project File src/setupTests.ts changes saved, store ts: 1519483000829, change ts: 1519548071309
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Stopping process pool
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Running postprocessor
Sun, 25 Feb 2018 08:41:13 GMT wallaby:postprocessor New TypeScript language service is required
Sun, 25 Feb 2018 08:41:13 GMT wallaby:postprocessor TypeScript compiler options module (before tsconfig.json): undefined
Sun, 25 Feb 2018 08:41:13 GMT wallaby:postprocessor TypeScript compiler options module (after tsconfig.json): 6
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Preparing to process src/registerServiceWorker.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Preparing to process src/setupTests.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Preparing to process src/App.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Preparing to process src/Something/Something.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Preparing to process src/index.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Preparing to process src/App.test.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Processing compiled src/registerServiceWorker.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Instrumenting src/registerServiceWorker.js, via process pool: false
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Processing compiled src/setupTests.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Instrumenting src/setupTests.js, via process pool: false
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Processing compiled src/App.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Instrumenting src/App.js, via process pool: false
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Processing compiled src/Something/Something.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Instrumenting src/Something/Something.js, via process pool: false
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Processing compiled src/index.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Instrumenting src/index.js, via process pool: false
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Processing compiled src/App.test.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Instrumenting src/App.test.js, via process pool: false
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No preprocessors found for src/registerServiceWorker.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No preprocessors found for src/setupTests.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No preprocessors found for src/App.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No preprocessors found for src/Something/Something.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No preprocessors found for src/index.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:processor No preprocessors found for src/App.test.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Writing to disk and caching processed file src/registerServiceWorker.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Writing to disk and caching processed file src/setupTests.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Writing to disk and caching processed file src/App.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Writing to disk and caching processed file src/Something/Something.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Writing to disk and caching processed file src/index.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Writing to disk and caching processed file src/App.test.js
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Postprocessor execution finished
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Test run started; run priority: 3
Sun, 25 Feb 2018 08:41:13 GMT wallaby:project Running all tests
Sun, 25 Feb 2018 08:41:13 GMT wallaby:workers Starting test run, priority: 3
Sun, 25 Feb 2018 08:41:13 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #vp8s1]
Sun, 25 Feb 2018 08:41:13 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #vp8s1]
Sun, 25 Feb 2018 08:41:13 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #vp8s1]
Sun, 25 Feb 2018 08:41:13 GMT wallaby:workers [worker #0, session #vp8s1] Running tests in sandbox
Sun, 25 Feb 2018 08:41:15 GMT wallaby:workers Sandbox (active) [vp8s1] error: /Users/iang/Library/Caches/WebStorm2017.3/wallaby/projects/d840ae028f50f15f/instrumented/src/App.test.js:2
import * as React from 'react';
^^^^^^

SyntaxError: Unexpected token import
Runtime error: ./src/App.test.js:2
import * as React from 'react';
^^^^^^

SyntaxError: Unexpected token import
    at ScriptTransformer._transformAndBuildScript (/Users/iang/Development/Personal/my-react-ts-app/node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
    at ScriptTransformer.transform (/Users/iang/Development/Personal/my-react-ts-app/node_modules/jest-runtime/build/ScriptTransformer.js:316:21)
    at Runtime._execModule (/Users/iang/Development/Personal/my-react-ts-app/node_modules/jest-runtime/build/index.js:494:53)
    at Runtime.requireModule (/Users/iang/Development/Personal/my-react-ts-app/node_modules/jest-runtime/build/index.js:329:14)
    at jasmine2 (/Users/iang/Development/Personal/my-react-ts-app/node_modules/jest-jasmine2/build/index.js:97:11)
    at runTest (/Users/iang/Development/Personal/my-react-ts-app/node_modules/jest-cli/build/runTest.js:85:10)
    at promise.then (/Users/iang/Development/Personal/my-react-ts-app/node_modules/jest-cli/build/TestRunner.js:197:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
console.log:  FAIL  ../../../Library/Caches/WebStorm2017.3/wallaby/projects/d840ae028f50f15f/instrumented/src/App.test.js

console.log:   ● Test suite failed to run

    /Users/iang/Library/Caches/WebStorm2017.3/wallaby/projects/d840ae028f50f15f/instrumented/src/App.test.js:2
    import * as React from 'react';
    ^^^^^^
    
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Runtime.u._wallabyReplaced.l.requireModule (../../../Library/Caches/WebStorm2017.3/wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:18045)
          at <anonymous>
      at process._tickCallback (../../../Library/Caches/WebStorm2017.3/wallaby/projects/d840ae028f50f15f/instrumented/internal/process/next_tick.js:188:7)


Sun, 25 Feb 2018 08:41:15 GMT wallaby:workers [vp8s1] Run 0 test(s), skipped 0 test(s)
console.log: Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.622s
Ran all test suites.

Sun, 25 Feb 2018 08:41:15 GMT wallaby:workers [vp8s1] Sandbox is responsive, closing it
Sun, 25 Feb 2018 08:41:15 GMT wallaby:project Test run finished
Sun, 25 Feb 2018 08:41:15 GMT wallaby:project Processed console.log entries
Sun, 25 Feb 2018 08:41:15 GMT wallaby:project Processed loading sequences
Sun, 25 Feb 2018 08:41:15 GMT wallaby:project Processed executed tests
Sun, 25 Feb 2018 08:41:15 GMT wallaby:project Processed code coverage
Sun, 25 Feb 2018 08:41:15 GMT wallaby:project Test run result processed and sent to IDE
```

**Comment by ArtemGovorov** [comment]
Thanks for sharing the details. You may find the [working CRA-ts config sample here](https://github.com/wallabyjs/public/issues/1431). You may also find the [details describing the config here in our docs](https://wallabyjs.com/docs/integration/react-jsx.html#create-react-app) (it is for CRA, but most of it applies to CRA-ts as well).

**Comment by appsolutegeek** [comment]
Thanks!, that helped a lot, it's now working.
