### ISSUE TITLE
Vue, Jest and Typescript are messing with wallaby

### ISSUE THREAD

**Issue by elevatebart** [wallabyjs/public#1533]
### Issue description or question

I am trying to get 4 wonders work together: 
Vue, Jest, Typescript and Wallabyjs
On the [linked repo](https://github.com/elevatebart/wallaby-vue-jest-ts), when I launch wallaby,
I get the following error:

```
Failed to run compilers on src/components/HelloWorld.vue, SyntaxError: src/components/HelloWorld.vue: Unexpected token, expected , (93:12)​​
[Error] ​​  91 | export default class HelloWorld extends Vue {​​
[Error] ​​  92 |   msg = "Welcome to Your Vue.js App";​​
[Error] ​​> 93 |   setMsg(msg: string): void {​​
[Error] ​​     |             ^​​
[Error] ​​  94 |     this.msg = msg;​​
[Error] ​​  95 |   }​​
[Error] ​​  96 | }​​
[Error] ​​    at Parser.pp$5.raise (c:\Enablon\wallaby-vue-jest-ts\node_modules\babylon\lib\index.js:4454:13)​​
[Error] ​​    at Parser.pp.unexpected (c:\Enablon\wallaby-vue-jest-ts\node_modules\babylon\lib\index.js:1761:8)​​
[Error] ​​    at Parser.pp.expect (c:\Enablon\wallaby-vue-jest-ts\node_modules\babylon\lib\index.js:1749:33)​​
[Error] ​​    at Parser.pp$2.parseBindingList (c:\Enablon\wallaby-vue-jest-ts\node_modules\babylon\lib\index.js:3101:12)​​
[Error] ​​    at Parser.pp$3.parseMethod (c:\Enablon\wallaby-vue-jest-ts\node_modules\babylon\lib\index.js:4178:22)​​
[Error] ​​    at Parser.pp$1.parseClassMethod (c:\Enablon\wallaby-vue-jest-ts\node_modules\babylon\lib\index.js:2583:8)​​
[Error] ​​    at Parser.pp$1.parseClassBody (c:\Enablon\wallaby-vue-jest-ts\node_modules\babylon\lib\index.js:2510:14)​​
[Error] ​​    at Parser.pp$1.parseClass (c:\Enablon\wallaby-vue-jest-ts\node_modules\babylon\lib\index.js:2406:8)​​
[Error] ​​    at Parser.pp$1.parseExport (c:\Enablon\wallaby-vue-jest-ts\node_modules\babylon\lib\index.js:2642:19)​​
[Error] ​​    at Parser.pp$1.parseStatement (c:\Enablon\wallaby-vue-jest-ts\node_modules\babylon\lib\index.js:1884:74)​​
[Error] ​​    at Parser.pp$1.parseBlockBody (c:\Enablon\wallaby-vue-jest-ts\node_modules\babylon\lib\index.js:2268:21)​​
[Error] ​​    at Parser.pp$1.parseTopLevel (c:\Enablon\wallaby-vue-jest-ts\node_modules\babylon\lib\index.js:1778:8)​​
[Error] ​​    at Parser.parse (c:\Enablon\wallaby-vue-jest-ts\node_modules\babylon\lib\index.js:1673:17)​​
[Error] ​​    at parse (c:\Enablon\wallaby-vue-jest-ts\node_modules\babylon\lib\index.js:7305:37)​​
[Error] ​​    at File.parse (c:\Enablon\wallaby-vue-jest-ts\node_modules\babel-core\lib\transformation\file\index.js:517:15)​​
[Error] ​​    at File.parseCode (c:\Enablon\wallaby-vue-jest-ts\node_modules\babel-core\lib\transformation\file\index.js:602:20)​​
[Error] ​​    at c:\Enablon\wallaby-vue-jest-ts\node_modules\babel-core\lib\transformation\pipeline.js:49:12​​
[Error] ​​    at File.wrap (c:\Enablon\wallaby-vue-jest-ts\node_modules\babel-core\lib\transformation\file\index.js:564:16)​​
[Error] ​​    at Pipeline.transform (c:\Enablon\wallaby-vue-jest-ts\node_modules\babel-core\lib\transformation\pipeline.js:47:17)​​
[Error] ​​    at c:\Enablon\wallaby-vue-jest-ts\node_modules\wallaby-vue-compiler\index.js:16:29​​
[Error] ​​    at _combinedTickCallback (internal/process/next_tick.js:131:7)​​
[Error] ​​    at process._tickCallback (internal/process/next_tick.js:180:9)​​
```
I think `wallaby-vue-compiler` is not compiling the Vue script with TypeScript. 
Can you help me?
Thank you in advance,
Bart

### Wallaby.js configuration file

```javascript
const babelOptions = { sourceMap: true, plugins: ["transform-es2015-modules-commonjs"], presets: ['babel-preset-jest'] };

module.exports = function (wallaby) {
    return {
        files: [
            { pattern: 'tsconfig.json', instrument: false },
            { pattern: 'test/unit/jest.conf.js', instrument: false },
            { pattern: 'src/**/*.*', load: false },
        ],

        compilers: {
            '**/*.js': wallaby.compilers.babel(),
            '**/*.vue': require('wallaby-vue-compiler')(wallaby.compilers.babel({})),
            "**/*.ts?(x)": wallaby.compilers.typeScript({
                module: "commonjs"
            }),
        },

        preprocessors: {
            "**/*.js?(x)": file => require("babel-core").transform(file.content, babelOptions),
        },

        tests: [
            { pattern: 'test/unit/**/*.spec.ts', load: false }
        ],

        env: {
            type: 'node',
            runner: 'node'
        },

        testFramework: 'jest',
        setup: function () {
            const jestConfig = require('./test/unit/jest.conf');
            jestConfig.moduleNameMapper = {
                "^@/(.*)$": wallaby.projectCacheDir + "/src/$1"
            };
            wallaby.testFramework.configure(jestConfig);
        }
    }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.20.1

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Working config for Vue, Jest and TypeScript (for vue-cli) can be found here: https://github.com/wallabyjs/public/issues/1456#issuecomment-365823745. Yours is a bit different because you are not using `vue-cli`, but I have taken that config as a base to get yours working.

Note that at the moment wallaby doesn't support code coverage for TypeScript in `.vue` files. Tests will still run ok, just `script` sections of `.vue` written in TypeScript will not be highlighted.

```javascript
module.exports = () => {
  process.env.BABEL_ENV = 'test';
  return {
    files: [
      'src/**/*',
      { pattern: 'test/unit/jest.conf.js', instrument: false },
      { pattern: 'test/unit/setup.js', instrument: false },
      'tsconfig.json'
    ],

    tests: ['test/unit/**/*.spec.ts'],

    env: {
      type: 'node',
      runner: 'node',
    },

    preprocessors: {
      '**/*.js?(x)': file => require('babel-core').transform(
        file.content,
        {
          sourceMap: true, compact: false, filename: file.path,
          plugins: ['transform-es2015-modules-commonjs'], presets: ['babel-preset-jest']
        })
    },

    setup(wallaby) {
      const jestConfig = require('./test/unit/jest.conf');

      delete jestConfig.rootDir;
      delete jestConfig.mapCoverage;
      jestConfig.setupFiles[0] = jestConfig.setupFiles[0].replace('<rootDir>', wallaby.projectCacheDir);
      jestConfig.moduleNameMapper = {
        '^@/components/([^\\.]*)$': wallaby.projectCacheDir + '/src/components/$1.vue',
        '^@/(.*)$': wallaby.projectCacheDir + '/src/$1',
      };

      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest',
    debug: true
  }
};
```

**Comment by elevatebart** [comment]
Once again @ArtemGovorov have been amazing. 

Thank you again
