### ISSUE TITLE
Not resolving import from files in node_modules

### ISSUE THREAD

**Issue by rafaelmaruta** [wallabyjs/public#1549]
### Issue description or question
I have some files that are imported from dependencies in node_modules that are not transpiled, but I don't want to run tests from this `./node_modules/admin-components`, just ignore them, only consider `./src`. But when I import these files, it throws these errors:

```
​​SyntaxError: ./node_modules/admin-components/src/helpers/utils/react-utils/index.jsx: Unexpected token, expected "," (6:40)​​
​​​​
​​  4 |  * Side effect function that changes the state​​
​​  5 |  */​​
​​> 6 | export const changeState = function (arg: () => mixed | {}): Function {​​
​​    |                                         ^​​
​​  7 |   return (...args: any[]): Promise => (​​
​​  8 |     new Promise(resolve => {​​
​​  9 |       const state = typeof arg === 'function' ? () => arg(...args) : arg​​
  at Object.<anonymous> ​src/app/campaign/campaign/components/edit-row/test.jsx:5​
​​./node_modules/admin-components/src/index.jsx:3​​
​​export { default as DashedButton } from './components/button/dashed';​​
​​^^^^^^​​
​​​​
​​SyntaxError: Unexpected token export​​
  at ​node_modules/admin-components/src/index.jsx:3​
  at Object.<anonymous> ​src/app/campaign/campaign/functions/index.jsx:9​
  at Object.<anonymous> ​src/app/campaign/campaign/test.jsx:11​
​​./node_modules/admin-components/src/components/layout/country-selector/redux/reducer.js:3​​
​​import { DISABLE_COUNTRY, SET_COUNTRY } from './actionTypes';​​
​​^^^^^^​​
````

So here my jest package.json node:

```
"jest": {
    "globals": {
      "sessionStorage": true
    },
    "moduleFileExtensions": [
      "js",
      "jsx"
    ],
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/node_modules/admin-core/__mocks__/fileMock.js",
      "^.+\\.(s)?css$": "identity-obj-proxy"
    },
    "setupTestFrameworkScriptFile": "<rootDir>/node_modules/admin-core/setupTests.js",
    "transform": {
      ".*": "babel-jest"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!admin-components)"
    ]
  }
```

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      { pattern: 'src/**/*.js?(x)', load: false },
      { pattern: 'src/**/*.snap', load: false },
      { pattern: 'node_modules/admin-components/**', instrument: false },
      '!src/**/*test.js?(x)'
    ],

    tests: [
      'src/**/*test.js?(x)'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    compilers: {
      'src/**/*.js?(x)': wallaby.compilers.babel()
    },

    debug: true,

    reportConsoleErrorAsError: true
  }
}
```

My Jest is working fine. I already tried to use this setup but doesn't work:

```
setup: function (wallaby) {
      var jestConfig = require('./package.json').jest;
      wallaby.testFramework.configure(jestConfig);
    }
```

### Code editor or IDE name and version
Visual Studio Code

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
You don't need to specify the module in your `files` in this case. This should work for you:

```diff
module.exports = function (wallaby) {
  return {
    files: [
      { pattern: 'src/**/*.js?(x)', load: false },
      { pattern: 'src/**/*.snap', load: false },
-     { pattern: 'node_modules/admin-components/**', instrument: false },
      '!src/**/*test.js?(x)'
    ],

    ...
  }
}
```

I just tried on a simple repo with a similar structure with your config, and it's working for me (without including the module in the `files` list). Please try the solution above, and if it doesn't work for you, please create a sample repo demonstrating the issue (you may leave just one dummy test importing `admin_components` and replace the whole `admin_components` module with a single `admin_components/index.js` with `export default 1` for the sample repo purposes).

**Comment by rafaelmaruta** [comment]
Hi @ArtemGovorov, I created a sample branch in my repo with the issue:

https://github.com/rafaelmaruta/webpack-react-redux-sass-css-modules-jest-storybook-flow/tree/test-wallaby

The project `yarn start` and tests with Jest are working, but with Wallaby even removing that line (`{ pattern: 'node_modules/admin-components/**', instrument: false }`) it throws an error:

```
​​​​​0 failing tests, 0 passing​​​​​
​​​​​​​​​​
​​Error: Cannot find module '../../../../node_modules/my-components' from 'index.jsx'​​
​​    at Resolver.resolveModule (/Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-resolve/build/index.js:169:17)​​
​​    at Resolver._getVirtualMockPath (/Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-resolve/build/index.js:254:80)​​
​​    at Resolver._getAbsolutPath (/Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-resolve/build/index.js:245:89)​​
​​    at Resolver.getModuleID (/Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-resolve/build/index.js:228:31)​​
​​    at Runtime._shouldMock (/Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-runtime/build/index.js:512:37)​​
​​    at Runtime.requireModuleOrMock (/Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-runtime/build/index.js:334:14)​​
​​    at Object.<anonymous> (./src/js/routes/Main/index.jsx:11:58)​​
​​    at Runtime._execModule (/Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-runtime/build/index.js:448:13)​​
​​    at Runtime.requireModule (/Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-runtime/build/index.js:265:14)​​
​​    at Runtime.requireModuleOrMock (/Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-runtime/build/index.js:337:19)​​
​​    at Object.<anonymous> (./src/js/routes/Main/test.jsx:9:46)​​
​​    at Runtime._execModule (/Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-runtime/build/index.js:448:13)​​
​​    at Runtime.requireModule (/Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-runtime/build/index.js:265:14)​​
​​    at /Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-jasmine2/build/index.js:114:13​​
​​    at Generator.next (<anonymous>)​​
​​    at step (/Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-jasmine2/build/index.js:144:191)​​
​​    at /Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-jasmine2/build/index.js:144:437​​
​​    at new Promise (<anonymous>)​​
​​    at /Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-jasmine2/build/index.js:144:99​​
​​    at jasmine2 (/Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-jasmine2/build/index.js:122:17)​​
​​    at /Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-runner/build/run_test.js:73:28​​
​​    at Generator.next (<anonymous>)​​
​​    at step (/Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-runner/build/run_test.js:147:191)​​
​​    at /Users/rafael.maruta/projetos/exemplos/webpack-react-redux-sass-css-modules-jest-storybook-flow/node_modules/jest-runner/build/run_test.js:147:361​​
​​    at <anonymous>​​
​​    at process._tickCallback (internal/process/next_tick.js:160:7)​​
```

I think Wallaby can't resolve imports from node_modules files. I am using the plugin babel plugin module resolver to resolve aliases at webpack/default.js:111, and .babelrc:26

**Comment by ArtemGovorov** [comment]
Thanks for sharing the repo. 

The issue is in babel's `module-resolver` plugin that you're using. It creates a relative path, so you either need to have the module in your `files` list, or to map it using Jest's `moduleNameMapper`.

So there are 2 ways to make it work.

One solution is to include the module into `files` (but don't set the `instrument: false` flag):

```diff
module.exports = function (wallaby) {

  return {
    files: [
      {pattern: 'src/**/*.js?(x)', load: false},
      {pattern: 'src/**/*.snap', load: false},
+     'node_modules/my-components/**',
      '!src/**/test.js?(x)'
    ],

    tests: [
      'src/**/test.js?(x)'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel()
    },

    debug: true,

    reportConsoleErrorAsError: true
  }
}

```

If you need to exclude the module from code coverage calculation, you [may use this setting](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-a-file). Note that in this case, wallaby will not work (track files/display coverage) in your `src/js/my-components` folder.

Another solution is to mute the mentioned babel's plugin and use Jest's `moduleNameMapper`:

```diff
module.exports = function (wallaby) {

+ const babelConfig = JSON.parse(require('fs').readFileSync('./.babelrc'));
+ babelConfig.babelrc = false;
+ delete babelConfig.plugins.find(p => p[0] === 'module-resolver')[1].alias.MyComponent;

  return {
    files: [
      { pattern: 'src/**/*.js?(x)', load: false },
      { pattern: 'src/**/*.snap', load: false },
      '!src/**/test.js?(x)'
    ],

    tests: [
      'src/**/test.js?(x)'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    compilers: {
-     '**/*.js?(x)': wallaby.compilers.babel()
+     '**/*.js?(x)': wallaby.compilers.babel(babelConfig)
    },

    debug: true,

    reportConsoleErrorAsError: true,

+   setup: function (wallaby) {
+     const jestConfig = require('./package.json').jest;
+     jestConfig.moduleNameMapper['MyComponent'] = '<rootDir>/src/js/my-components';
+     wallaby.testFramework.configure(jestConfig);
    }
  }
}
```

In this case, wallaby will work (track files/display coverage) in your `src/js/my-components` folder as well.

Hope it helps.

**Comment by rafaelmaruta** [comment]
It worked @ArtemGovorov thanks!
