### ISSUE TITLE
ReferenceError: $_$wp is not defined

### ISSUE THREAD

**Issue by Maninacan** [wallabyjs/public#1553]
### Issue description or question
I copied the create-react-app wallaby.conf verbatim from the documentation but when I run it I am getting the stack trace that I pasted down below.  The Wallaby app runs, but as you can see in the screenshot below it says tests are 0 of 0.  Any help would be appreciated.
### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {

  // Babel, jest-cli and some other modules may be located under
  // react-scripts/node_modules, so need to let node.js know about it
  var path = require('path');
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, 'node_modules') +
    path.delimiter +
    path.join(__dirname, 'node_modules/react-scripts/node_modules');
  require('module').Module._initPaths();

  return {
    files: [
      'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!src/**/*.test.js?(x)'
    ],

    tests: ['src/**/*.test.js?(x)'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['react-app']
      })
    },

    setup: wallaby => {
      const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(p => require.resolve('react-scripts/' + p));
      Object.keys(jestConfig.transform || {}).forEach(k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]);
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};

```

### Code editor or IDE name and version
WebStorm 2108.1 EAP

### OS name and version
OSX 10.13.3

STACK TRACE:
```
wallaby.js started
core v1.0.566
Wallaby App (realtime reports) is available at: http://localhost:51245
Runtime error: ReferenceError: $_$wp is not defined
console.log:  FAIL  ../../Library/Caches/WebStorm2018.1/wallaby/projects/ebb8a25dea795fc3/instrumented/src/__tests__/App.test.js

    at Object.<anonymous> (./src/setupTests.js:2:1)
    at Runtime._execModule (/Users/jonaaron/Projects/coherence-entityreport-ui-react/node_modules/jest-runtime/build/index.js:513:13)
    at Runtime.requireModule (/Users/jonaaron/Projects/coherence-entityreport-ui-react/node_modules/jest-runtime/build/index.js:329:14)
    at jasmine2 (/Users/jonaaron/Projects/coherence-entityreport-ui-react/node_modules/jest-jasmine2/build/index.js:89:13)
    at runTest (/Users/jonaaron/Projects/coherence-entityreport-ui-react/node_modules/jest/node_modules/jest-cli/build/runTest.js:85:10)
    at promise.then (/Users/jonaaron/Projects/coherence-entityreport-ui-react/node_modules/jest/node_modules/jest-cli/build/TestRunner.js:197:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Runtime error: ReferenceError: $_$wp is not defined
    at Object.<anonymous> (./src/setupTests.js:2:1)
    at Runtime._execModule (/Users/jonaaron/Projects/coherence-entityreport-ui-react/node_modules/jest-runtime/build/index.js:513:13)
    at Runtime.requireModule (/Users/jonaaron/Projects/coherence-entityreport-ui-react/node_modules/jest-runtime/build/index.js:329:14)
    at jasmine2 (/Users/jonaaron/Projects/coherence-entityreport-ui-react/node_modules/jest-jasmine2/build/index.js:89:13)
    at runTest (/Users/jonaaron/Projects/coherence-entityreport-ui-react/node_modules/jest/node_modules/jest-cli/build/runTest.js:85:10)
    at promise.then (/Users/jonaaron/Projects/coherence-entityreport-ui-react/node_modules/jest/node_modules/jest-cli/build/TestRunner.js:197:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Runtime error: ReferenceError: $_$wp is not defined
    at Object.<anonymous> (./src/setupTests.js:2:1)
    at Runtime._execModule (/Users/jonaaron/Projects/coherence-entityreport-ui-react/node_modules/jest-runtime/build/index.js:513:13)
    at Runtime.requireModule (/Users/jonaaron/Projects/coherence-entityreport-ui-react/node_modules/jest-runtime/build/index.js:329:14)
    at jasmine2 (/Users/jonaaron/Projects/coherence-entityreport-ui-react/node_modules/jest-jasmine2/build/index.js:89:13)
    at runTest (/Users/jonaaron/Projects/coherence-entityreport-ui-react/node_modules/jest/node_modules/jest-cli/build/runTest.js:85:10)
    at promise.then (/Users/jonaaron/Projects/coherence-entityreport-ui-react/node_modules/jest/node_modules/jest-cli/build/TestRunner.js:197:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
console.log:  FAIL  ../../Library/Caches/WebStorm2018.1/wallaby/projects/ebb8a25dea795fc3/instrumented/src/__tests__/store.test.js

console.log:  FAIL  ../../Library/Caches/WebStorm2018.1/wallaby/projects/ebb8a25dea795fc3/instrumented/src/components/__tests__/utils.test.js

console.log:   ● Test suite failed to run

    ReferenceError: $_$wp is not defined
      
      at Object.<anonymous> (../../Library/Caches/WebStorm2018.1/wallaby/projects/ebb8a25dea795fc3/instrumented/src/setupTests.js:2:1)
      at Runtime.u._wallabyReplaced.l.requireModule (../../Library/Caches/WebStorm2018.1/wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:18865)
          at <anonymous>
      at process._tickCallback (../../Library/Caches/WebStorm2018.1/wallaby/projects/ebb8a25dea795fc3/instrumented/internal/process/next_tick.js:188:7)


console.log:   ● Test suite failed to run

    ReferenceError: $_$wp is not defined
      
      at Object.<anonymous> (../../Library/Caches/WebStorm2018.1/wallaby/projects/ebb8a25dea795fc3/instrumented/src/setupTests.js:2:1)
      at Runtime.u._wallabyReplaced.l.requireModule (../../Library/Caches/WebStorm2018.1/wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:18865)
          at <anonymous>
      at process._tickCallback (../../Library/Caches/WebStorm2018.1/wallaby/projects/ebb8a25dea795fc3/instrumented/internal/process/next_tick.js:188:7)


console.log:   ● Test suite failed to run

    ReferenceError: $_$wp is not defined
      
      at Object.<anonymous> (../../Library/Caches/WebStorm2018.1/wallaby/projects/ebb8a25dea795fc3/instrumented/src/setupTests.js:2:1)
      at Runtime.u._wallabyReplaced.l.requireModule (../../Library/Caches/WebStorm2018.1/wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:18865)
          at <anonymous>
      at process._tickCallback (../../Library/Caches/WebStorm2018.1/wallaby/projects/ebb8a25dea795fc3/instrumented/internal/process/next_tick.js:188:7)


console.log: Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.973s
Ran all test suites.

console.log: Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.971s
Ran all test suites.

console.log: Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.973s
Ran all test suites.
```

setupTests.js
```javascript
import 'jest-enzyme'
import jsdom from 'jsdom'
import { configure } from 'enzyme'
import Adapter from 'enzyme-adapter-react-16'

configure({ adapter: new Adapter() })

const localStorageMock = {
  getItem: jest.fn(),
  setItem: jest.fn(),
  clear: jest.fn()
}
global.localStorage = localStorageMock

const sessionStorageMock = {
  getItem: jest.fn(),
  setItem: jest.fn(),
  clear: jest.fn()
}

global.sessionStorage = sessionStorageMock


const { JSDOM } = jsdom
const documentHTML = '<!doctype html><html><body><div id="root"></div></body></html>'
global.document = new JSDOM(documentHTML)
global.window = document.parentWindow

```
<img width="1906" alt="screen shot 2018-03-12 at 1 08 14 pm" src="https://user-images.githubusercontent.com/1934083/37304225-969fdc82-25f6-11e8-8957-0b67e91438ad.png">

**Comment by ArtemGovorov** [comment]
Just tried to create a new app with the latest `create-react-app` and the config is working for me. I have a suspicion some of your project dependencies may be affecting wallaby resolution of Jest modules.

Try deleting your `yarn.lock`, clearing node modules and installing them. If it doesn't help (or is not acceptable), please share your project's `package.json` file (`dependences` and `devDependencies` sections are enough) and your `yarn.lock` file, and we'll try to reproduce the issue.

**Comment by ArtemGovorov** [comment]
Here is the [sample `create-react-app` repo](https://github.com/ArtemGovorov/wallaby-1553) that I have created (where the config is working).

**Comment by Maninacan** [comment]
@ArtemGovorov Thanks for looking into it.  I got the `$_$wp is not defined` to go away by deleting the `node_modules` folder and doing `npm install` again.  But now I'm getting another error that I've been fighting. 
```TypeError: Cannot read property '_jasmineAdapter' of undefined
    at Runtime._execModule (/Users/jonaaron/WebstormProjects/create-react-app-wallaby/node_modules/jest-runtime/build/index.js:513:13)
    at Runtime.requireModule (/Users/jonaaron/WebstormProjects/create-react-app-wallaby/node_modules/jest-runtime/build/index.js:329:14)
    at jasmine2 (/Users/jonaaron/WebstormProjects/create-react-app-wallaby/node_modules/jest-jasmine2/build/index.js:89:13)
    at runTest (/Users/jonaaron/WebstormProjects/create-react-app-wallaby/node_modules/jest/node_modules/jest-cli/build/runTest.js:85:10)
    at promise.then (/Users/jonaaron/WebstormProjects/create-react-app-wallaby/node_modules/jest/node_modules/jest-cli/build/TestRunner.js:197:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
I removed all of my work's in-house libs and I'm still getting the error after reinstalling the node_modules again.

Here is the package.json minus the in-house libs:
```json
{
  "name": "create-react-app-wallaby",
  "version": "0.1.0",
  "private": true,
  "repository": "",
  "homepage": ".",
  "keywords": [],
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "dependencies": {
    "axios": "0.18.0",
    "chardin.js": "0.1.3",
    "downloadjs": "1.4.7",
    "font-awesome": "^4.4.0",
    "history": "4.7.2",
    "immutability-helper": "^2.6.6",
    "jest-enzyme": "5.0.3",
    "jquery": "^3.2.1",
    "leaflet": "^1.3.1",
    "leaflet.awesome-markers": "^2.0.4",
    "lodash": "latest",
    "moment": "2.21.0",
    "opencollective": "1.0.3",
    "prop-types": "15.6.1",
    "query-string": "latest",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-leaflet": "1.8.2",
    "react-redux": "5.0.7",
    "react-router": "^4.2.0",
    "react-router-dom": "4.2.2",
    "react-router-redux": "^5.0.0-alpha.8",
    "react-scripts": "1.1.1",
    "react-styleguidist": "6.2.7",
    "react-test-renderer": "16.2.0",
    "redux": "3.7.2",
    "redux-logger": "^3.0.6",
    "redux-observable": "0.18.0",
    "redux-thunk": "^2.2.0",
    "reselect": "3.0.1",
    "rxjs": "5.5.6",
    "source-map-explorer": "1.5.0",
    "styled-components": "3.2.1",
    "uikit": "3.0.0-beta.40"
  },
  "devDependencies": {
    "babel-preset-react-app": "3.1.1",
    "enzyme": "3.3.0",
    "enzyme-adapter-react-16": "^1.1.0",
    "eslint-config-standard": "11.0.0",
    "eslint-plugin-node": "6.0.1",
    "eslint-plugin-promise": "3.7.0",
    "eslint-plugin-standard": "3.0.1",
    "jsdom": "11.6.2",
    "node-sass": "4.8.1",
    "node-sass-chokidar": "1.1.0",
    "redux-devtools-extension": "2.13.2",
    "wallaby-webpack": "3.9.5",
    "wdio-dot-reporter": "0.0.9",
    "wdio-mocha-framework": "0.5.13",
    "wdio-selenium-standalone-service": "0.0.10",
    "wdio-spec-reporter": "0.1.4",
    "webdriverio": "4.12.0"
  },
  "engines": {
    "node": ">= 8.0.0",
    "npm": ">= 5.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
```

**Comment by ArtemGovorov** [comment]
Just updated the [sample repo](https://github.com/ArtemGovorov/wallaby-1553) `package.json` (replaced with yours), and it's still working for me. Could you please clone the repo, run `yarn` and run wallaby to see if it's working for you? If it is, please try add the bits I'm missing to reproduce the issue.

**Comment by Maninacan** [comment]
@ArtemGovorov I found the issue (kind of).  I've been using NPM instead of Yarn.  I can't use Yarn because my work uses Sinopia for our in-house npm libs and for whatever reason it won't accept Yarn when I try to run it.  Is there no way to get this to work using NPM?

**Comment by ArtemGovorov** [comment]
Thanks for the note regarding your package manager. We have been able to reproduce and fix the issue, the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by Maninacan** [comment]
@ArtemGovorov Sorry, I know you're time is valuable, but I already tried that fix ([the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update)).  It is still an issue.  Were you able to reproduce and fix the issue using NPM?  Or does it just not work using NPM?

**Comment by Maninacan** [comment]
Cool. I'll give it a try. Thanks!

**Comment by Maninacan** [comment]
@ArtemGovorov It's working for me now. Not sure why but I really appreciate the help.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
