### ISSUE TITLE
jest.mock with Webpack 4

### ISSUE THREAD

**Issue by Almenit** [wallabyjs/public#1576]
### Issue description or question
jest.mock doesn't work when using webpack 4. 
It works when running jest
### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        files: [
            "package.json",
            "tsconfig.json",
            "Capish.Applications.Reflect.Web/Content/Scripts/**/*.ts*",
            { pattern: "Capish.Applications.Reflect.Web/Content/Scripts/cql/cql.peg.parser.js", instrument: false },
            { pattern: "Capish.Applications.Reflect.Web/Content/Scripts/cql/cql-intellisense-parser.js", instrument: false },
            "!Capish.Applications.Reflect.Web/Content/Scripts/tests/**/test.*.ts*",
            "!Capish.Applications.Reflect.Web/Content/Scripts/tests/index.ts*",
            { pattern: "Capish.Applications.Reflect.Web/Content/Scripts/tests/polyfills.ts", instrument: false },
            { pattern: "Capish.Applications.Reflect.Web/Content/Scripts/tests/jsnlogTestConfigure.ts", instrument: false },
            "Capish.Applications.Reflect.ConfigurationBuilders/**/*.ts*",
            "!Capish.Applications.Reflect.ConfigurationBuilders/tests/**/test.*.ts*"
        ],

        tests: [
            "Capish.Applications.Reflect.Web/Content/Scripts/tests/**/test.*.ts*",
            "Capish.Applications.Reflect.ConfigurationBuilders/tests/**/test.*.ts*"
        ],

        debug: true,

        preprocessors: {
            'Capish.Applications.Reflect.Web/Content/Scripts/**/*.js*': file => {
                return require("@babel/core")
                    .transform(file.content, {
                        sourceMap: true,
                        compact: false,
                        babelrc: true,
                        filename: file.path
                    });
            },
            'Capish.Applications.Reflect.ConfigurationBuilders/**/*.js*': file => {
                return require("@babel/core")
                    .transform(file.content, {
                        sourceMap: true,
                        compact: false,
                        babelrc: true,
                        filename: file.path
                    });
            }
        },
        env: {
            type: "node",
            runner: "node"
        },
        testFramework: "jest",
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.21.1

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Your wallaby config is not using Webpack 4. 
Could you please share some more details about how exactly `jest.mock` is not working, with some code example and the error message/stack?

**Comment by Almenit** [comment]
The problem I get is i.e 
​​TypeError: createCqlFromFiltersWithAndMock.mockReturnValue is not a function​​
For this:
```javascript
import { createCqlFromFiltersWithAnd } from "../../../utils/cqlFilterHelper";
jest.mock("../../../utils/cqlFilterHelper");
const createCqlFromFiltersWithAndMock: jest.MockInstance<any> = createCqlFromFiltersWithAnd as any;
...
createCqlFromFiltersWithAndMock.mockReturnValue("highlight");
```

I have another project where we run webpack 3. We use the same wallaby configuration (besides filenames). There it works as it should.
There we use:
"wallaby-webpack": "3.9.3",
"webpack": "3.6.0"

In this project we use:
"wallaby-webpack": "3.9.5",
"webpack": "4.2.0",

Same config in .babelrc for both projects
```javascript
{
  "passPerPreset": true,
  "presets": [
    "@babel/preset-typescript",
    "@babel/preset-es2016",
    "@babel/preset-react"
  ],
    "plugins": [
        "react-hot-loader/babel",
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-proposal-object-rest-spread",
        "babel-plugin-jest-hoist",
        "babel-plugin-syntax-object-rest-spread"
    ],
  "env": {
    "test": {
      "plugins": [
        "@babel/plugin-transform-modules-commonjs"
      ]
    },
    "production": {
      "presets": [
        "babili"
      ]
    }
  }
}
``

**Comment by ArtemGovorov** [comment]
Could you please share 
- your `package.json` `dependencies` and `devDependencies` sections?
- whether you are using `npm` or `yarn` to install your dependencies.

**Comment by Almenit** [comment]
We using `npm`
`package.json`
```javascript
{
  "name": "r",
  "version": "1.0.0",
  "description": "",
  "author": "",
  "license": "ISC",
  "private": true,
  "devDependencies": {
    "@babel/core": "7.0.0-beta.35",
    "@babel/plugin-proposal-class-properties": "7.0.0-beta.35",
    "@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.35",
    "@babel/plugin-transform-modules-commonjs": "7.0.0-beta.35",
    "@babel/plugin-transform-react-jsx": "7.0.0-beta.35",
    "@babel/preset-env": "7.0.0-beta.35",
    "@babel/preset-es2016": "7.0.0-beta.35",
    "@babel/preset-react": "7.0.0-beta.35",
    "@babel/preset-typescript": "7.0.0-beta.35",
    "@types/classnames": "2.2.3",
    "@types/crossroads": "0.0.30",
    "@types/d3": "3.5.40",
    "@types/element-resize-detector": "1.1.0",
    "@types/flux": "3.1.7",
    "@types/jest": "22.2.2",
    "@types/jsnlog": "^2.17.2",
    "@types/react": "15.6.14",
    "@types/react-addons-test-utils": "0.14.21",
    "@types/resumablejs": "1.0.5",
    "@types/sinon": "4.3.0",
    "@types/underscore": "1.8.8",
    "assets-webpack-plugin": "3.5.1",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "22.0.4",
    "babel-loader": "7.1.2",
    "babel-preset-babili": "1.0.0",
    "babili-webpack-plugin": "0.0.11",
    "cache-loader": "^1.2.2",
    "css-loader": "^0.28.10",
    "del": "2.2.2",
    "enzyme": "3.3.0",
    "enzyme-adapter-react-15": "1.0.5",
    "file-loader": "^1.1.11",
    "fork-ts-checker-webpack-plugin": "^0.4.1",
    "identity-obj-proxy": "3.0.0",
    "jest": "22.4.2",
    "jest-junit": "3.6.0",
    "jest-runner-tsc": "1.1.0",
    "less": "^3.0.1",
    "less-loader": "^4.1.0",
    "merge-stream": "1.0.0",
    "mock-promises": "0.8.1",
    "npm-run-all": "^4.1.2",
    "postcss": "^6.0.19",
    "postcss-cssnext": "^3.1.0",
    "postcss-import": "^11.1.0",
    "postcss-loader": "^2.1.1",
    "react-hot-loader": "^4.0.0",
    "react-test-renderer": "15.6.2",
    "replace-in-file": "^3.2.0",
    "require-dir": "0.3.1",
    "resolve": "1.1.7",
    "sinon": "4.4.8",
    "style-loader": "^0.20.3",
    "svg-sprite-loader": "^3.7.1",
    "svgo": "^1.0.5",
    "svgo-loader": "^2.1.0",
    "ts-jest": "22.4.1",
    "typed-css-modules": "0.2.0",
    "typescript": "2.6.2",
    "url-loader": "^1.0.1",
    "wallaby-webpack": "3.9.5",
    "webpack": "4.2.0",
    "webpack-cli": "^2.0.12",
    "webpack-dev-server": "2.8.2",
    "yaku": "0.16.7"
  },
  "dependencies": {
    "babel-polyfill": "6.16.0",
    "classnames": "2.2.5",
    "crossroads": "0.12.2",
    "d3": "3.5.17",
    "element-resize-detector": "1.1.14",
    "eventemitter2": "5.0.1",
    "fbjs": "0.8.5",
    "flux": "3.1.3",
    "immutable": "3.8.2",
    "javascript-natural-sort": "0.7.1",
    "jsnlog": "2.20.1",
    "lodash": "^4.17.5",
    "moment": "2.21.0",
    "react": "15.6.2",
    "react-addons-create-fragment": "15.6.2",
    "react-addons-css-transition-group": "15.6.2",
    "react-addons-perf": "15.6.0-rc.1",
    "react-addons-pure-render-mixin": "15.6.2",
    "react-dom": "15.6.2",
    "resumablejs": "1.1.0",
    "underscore": "1.8.3"
  },
  "scripts": {
    "build:dev": "webpack --env=dev --mode development --config webpack.dev.config.js",
    "build:vendor:dev": "webpack --mode development --config webpack.vendor.config.js",
    "build:vendor:prod": "webpack --mode production --env=prod -p --config webpack.vendor.config.js",
    "build:prod": "npm run relay && webpack --env=prod --mode production --config webpack.prod.config.js --define process.env.NODE_ENV='production'",
    "csstypes": "tcm ./Capish.Applications.Reflect.Web/",
    "publish": "npm-run-all -s build:vendor:prod build:prod",
    "serve": "node server.js",
    "start": "webpack --env=dev --mode development --watch --config webpack.dev.config.js",
    "test": "tsc --noEmit --allowUnreachableCode && jest --runInBand",
    "postinstall": "npm run build:vendor:dev",
    "transform": "node tasks/npm-transform.js"
  },
  "jest": {
    "transform": {
      ".(ts|tsx)": "./node_modules/ts-jest/preprocessor.js"
    },
    "testRegex": "/tests/.*/test\\..*\\.(ts|tsx|js)",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "moduleDirectories": [
      "node_modules"
    ],
    "testResultsProcessor": "./node_modules/jest-junit",
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/fileMock.js",
      "\\.(css|less)$": "identity-obj-proxy"
    },
    "globals": {
      "ts-jest": {
        "tsConfigFile": "tsconfig.json"
      }
    }
  }
}

**Comment by ArtemGovorov** [comment]
Thanks for providing the details. I have created the sample repo https://github.com/ArtemGovorov/wallaby-1576 with all your provided configs as is, and [a sample test](https://github.com/ArtemGovorov/wallaby-1576/blob/master/Capish.Applications.Reflect.Web/Content/Scripts/tests/a/b/test.a.ts) and everything is working for me as expected.

Could you please clone the repo to see if it's working for you, and if so, please add the bits I'm missing top reproduce the issue.

**Comment by Almenit** [comment]
Thanks. Yes that repo works for me to. I will try to find the issue. The log looks a bit strange. Any comment on that?
![image](https://user-images.githubusercontent.com/5937466/37874570-aee51632-3031-11e8-8888-9d0722607b2f.png)

**Comment by Almenit** [comment]
I get an error in the sample repo.

> ​​​​​[Info]​​​​​ Sun, 25 Mar 2018 11:54:40 GMT wallaby:workers Sandbox (active) [fpo3p] error: TypeError: snapshotState.getUncheckedKeys is not a function
​​[Error] Runtime error: TypeError: snapshotState.getUncheckedKeys is not a function​​
​​[Error]     at addSnapshotData (c:\Temp\test\wallaby-1576\node_modules\jest-jasmine2\build\index.js:170:39)​​
​​[Error]     at c:\Temp\test\wallaby-1576\node_modules\jest-jasmine2\build\index.js:117:14​​
​​[Error]     at <anonymous>​​
​​[Error]     at process._tickCallback (internal/process/next_tick.js:188:7)​​

**Comment by Almenit** [comment]
I found the setting causing the issue. Its the typescript configuration
`"allowSyntheticDefaultImports": true,`

**Comment by ArtemGovorov** [comment]
I have added the `"allowSyntheticDefaultImports": true,` setting to the sample repo https://github.com/ArtemGovorov/wallaby-1576, but it's still working for me without any issues. Could you please check what am I missing?

**Comment by Almenit** [comment]
I updated the repo with a failing tsconfig

**Comment by ArtemGovorov** [comment]
@Almenit Thanks, I have found [the missing bit](https://github.com/ArtemGovorov/wallaby-1576/blob/6e4b1704d7e486cc96e6c17032f06a5736391d87/wallaby.js#L1). Because `.babelrc` babel config has the `env.test` defined plugin `@babel/plugin-transform-modules-commonjs`, it wasn't applied without letting babel know about it.

**Comment by Almenit** [comment]
Ok thanks that works. I still get the 
`TypeError: snapshotState.getUncheckedKeys is not a function`
error in the repo.

**Comment by ArtemGovorov** [comment]
> `TypeError: snapshotState.getUncheckedKeys is not a function`

Hmm, I can't reproduce it locally. Are you only getting this in the sample repo, not in your real one?

**Comment by ArtemGovorov** [comment]
From the error message it looks like you may have some older version of Jest installed on your machine (in a `node_modules` folder that is on the way where wallaby Jest looks up for modules). 

Check if any of these folders exist, and if so, just delete them:
```
c:\Users\your_username\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.78\projects\node_modules
c:\Users\your_username\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.78\node_modules
c:\Users\your_username\.vscode\extensions\node_modules
c:\Users\your_username\.vscode\node_modules
c:\Users\your_username\node_modules
c:\Users\node_modules
c:\node_modules
```

**Comment by Almenit** [comment]
Yes I get it in the sample repo

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by Almenit** [comment]
Thank you much better!
