### ISSUE TITLE
create-react-app documentation issue

### ISSUE THREAD

**Issue by FDiskas** [wallabyjs/public#1600]
Reproduce:
1. `npm i -g create-react-app`
1. `create-react-app wallaby-error`
1. `cd wallaby-error`
1. `code .` (open IDE)
1. create new file **wallaby.js**
1. copy example from https://wallabyjs.com/docs/integration/react-jsx.html#create-react-app
1. Run wallaby

**Errors:**
```
wallaby.js started
core v1.0.575
Error: spawn node ENOENT
    at _errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by ArtemGovorov** [comment]
Looks like you don't have `node` path in your environment variables. In this case you may need to specify the [path to `node` executable in the `env.runner` setting](https://wallabyjs.com/docs/integration/node.html#node-version).
