### ISSUE TITLE
issue in starting node application after use of winston

### ISSUE THREAD

**Issue by rahuliet** [wallabyjs/public#1601]
```
*********/node_modules/winston/lib/winston/common.js:9
const { format } = require('util');
      ^
SyntaxError: Unexpected token {
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (*******/node_modules/winston/lib/winston.js:9:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)**
```
issue in starting node application after use of winston

**Comment by ArtemGovorov** [comment]
Without some more provided details, my best guess is that you are using [wallaby embedded version of node](https://wallabyjs.com/docs/integration/node.html#node-version), and if you specify 

```diff
module.exports = function () {
  return {
    ...
    env: {
      type: 'node',
+     runner: 'node'
    }
  }
```

then it should work for you.

If the suggested solution doesn't work, please use [our issue template](https://github.com/wallabyjs/public/blob/master/ISSUE_TEMPLATE) and specify the rest of the required details, so that we are able to help with the issue.

**Comment by rahuliet** [comment]
this is not about wallaby.js
to be specific I have recently included winston in my project by "npm i winston@next --save " for logging purpose.. the error which I am getting is on linux server machine on start of application


```
*********/node_modules/winston/lib/winston/common.js:9
const { format } = require('util');
      ^
SyntaxError: Unexpected token {
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (*******/node_modules/winston/lib/winston.js:9:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)**

```
Linux OS Version & Details
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.9 (Santiago)
Release:        6.9

**Comment by ArtemGovorov** [comment]
How is your issue related to wallaby.js?

**Comment by rahuliet** [comment]
this seems to be in wrong repository .. my mistake i should have tagged it to winston repo
