### ISSUE TITLE
[Bug] Error when using 'only' with 'mocha' on Core 1.0.576

### ISSUE THREAD

**Issue by JimiC** [wallabyjs/public#1602]
### Issue description or question
Core 1.0.576 throws an error when using `mocha` test framework and using `only` in test.

```
​​[Error] Runtime error: TypeError: Cannot read property '0' of undefined​​
​​[Error]     at Object.<anonymous> (./test/utils/utils.test.js:3:1)​​
​​[Error]     at Module._compile (module.js:571:32)​​
​​[Error]     at Object.Module._extensions..js (module.js:580:10)​​
​​[Error]     at Module.load (module.js:488:32)​​
​​[Error]     at tryModuleLoad (module.js:447:12)​​
​​[Error]     at Function.Module._load (module.js:439:3)​​
​​[Error]     at Module.require (module.js:498:17)​​
​​[Error]     at require (internal/module.js:20:19)​​
​​[Error]     at /pathTo/vscode-icons/node_modules/mocha/lib/mocha.js:231:27​​
​​[Error]     at Array.forEach (native)​​
​​[Error]     at Mocha.loadFiles (/pathTo/vscode-icons/node_modules/mocha/lib/mocha.js:228:14)​​
​​[Error]     at Mocha.run (/pathTo/vscode-icons/node_modules/mocha/lib/mocha.js:536:10)​​
​​[Error]     at emitTwo (events.js:106:13)​​
​​[Error]     at WebSocket.emit (events.js:194:7)​​
​​[Error]     at afterWrite (_stream_writable.js:383:3)​​
​​[Error]     at onwrite (_stream_writable.js:374:7)​​
​​[Error]     at afterTransform (_stream_transform.js:79:3)​​
​​[Error]     at TransformState.afterTransform (_stream_transform.js:54:12)​​
​​[Error]     at Zlib.callback (zlib.js:625:5)​​
```
### Wallaby.js configuration file

```javascript
module.exports = {
  files: [
    "src/**/*.ts",
    "test/support/*.ts",
    "locale/lang.*.json",
    "package.json",
    "package.nls.json",
    "package.nls.template.json",
    "icons/*.*"
  ],
  tests: [
    "test/**/*.test.ts"
  ],
  filesWithNoCoverageCalculated: [
  ],
  preprocessors: {
    "**/*.json": (file, done) => done(file.rename(`../${file.path}`).content),
    "icons/*.*": (file, done) => done(file.rename(`../${file.path}`).content)
  },
  hints: {
    ignoreCoverage: /\/* wallaby ignore next\/*/
  },
  testFramework: "mocha",
  env: {
    type: "node",
    runner: process.platform === "win32" ? `${process.env.APPDATA}\\nvm\\v7.9.0\\node` : `${require("os").homedir()}/.nvm/versions/node/v7.9.0/bin/node`
  },
  delays: {
    run: 500
  },
  debug: true,
  reportConsoleErrorAsError: true,
  setup: (wallaby) => wallaby.testFramework.ui("bdd")
};
```

### Code editor or IDE name and version

Visual Studio Code v1.21.1

### OS name and version

- [ ] Windows
- [ ] OSX
- [x] Linux
 - Ubuntu Mate 16.04.4

**Comment by ArtemGovorov** [comment]
We can't reproduce the issue locally when trying this repo https://github.com/vscode-icons/vscode-icons. Could you please some steps to reproduce it?

**Comment by JimiC** [comment]
@ArtemGovorov Add `only` to any test and restart `wallaby`.

**Comment by JimiC** [comment]
@ArtemGovorov I updated the `wallaby` config to the one we use in `vscode-icons`.

**Comment by borislit** [comment]
Happens with jest aswell @ArtemGovorov

**Comment by ArtemGovorov** [comment]
Thanks for the report(s). We have been able to reproduce and fix the issue. The fix is published in [Wallaby Core v1.0.577](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). 

Note that you may need to touch your wallaby config (even a space will do) to clear Wallaby cache.

**Comment by ArtemGovorov** [comment]
BTW, it was a bug in [this new feature implementation](https://twitter.com/wallabyjs/status/981420172765429761) (just in case you've missed the announcement).

**Comment by JimiC** [comment]
@ArtemGovorov Confirming issue resolved even without touching the `wallaby` config.
