### ISSUE TITLE
VS Code fs-extra/lib/copy/ncp.js error / inconsistent passing of tests

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1605]
### Issue description or question
VS Code fails two tests while Wallaby with Webstorm and Jest pass. I think the issue is related below, possibly because I'm mocking ``fs-extra`` in other tests?

VS Code is returning the following error:

```js
​​/Users/chris/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.80/node_modules/fs-extra/lib/copy/ncp.js:17​​
​​  var filter = options.filter​​
​​                       ^​​
​​​​
​​TypeError: Cannot read property 'filter' of undefined​​
​​    at ncp (/Users/chris/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.80/node_modules/fs-extra/lib/copy/ncp.js:17:24)​​
​​    at /Users/chris/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.80/node_modules/fs-extra/lib/copy/copy.js:28:29​​
​​    at FSReqWrap.cb [as oncomplete] (fs.js:312
```

Example on the Gitlab repo I gave you access to in the past.

### Wallaby.js configuration file

```javascript
'use strict';

module.exports = (wallaby) => {
    process.env.NODE_PATH = require('path').join(
        wallaby.localProjectDir,
        '../../node_modules',
    );

    return {
        files: [
            { pattern: 'src/**/__sandbox__/**/*', instrument: false },
            { pattern: 'src/**/__sandbox__/**/.*', instrument: false },
            { pattern: '.babelrc+(.js|)', instrument: false },
            'src/**/*.js',
            'jest.config.js',
            '.env',
            'src/**/*.snap',
            '!src/**/*.test.js',
        ],

        tests: [
            'src/**/*.test.js',
        ],

        compilers: {
            '**/*.js': wallaby.compilers.babel(),
        },

        hints: {
            ignoreCoverage: /ignore coverage/,
        },

        env: {
            type: 'node',
            runner: 'node',
        },

        testFramework: 'jest',

        setup: (w) => {
            /**
             * https://github.com/wallabyjs/public/issues/1268#issuecomment-323237993
             */
            if (w.projectCacheDir !== process.cwd()) {
                process.chdir(w.projectCacheDir);
            }

            require('babel-polyfill');
            process.env.NODE_ENV = 'test';
            const jestConfig = require('./jest.config');

            jestConfig.transform = { '__sandbox__.+\\.jsx?$': 'babel-jest' };
            w.testFramework.configure(jestConfig);
        },
    };
};
```

### Code editor or IDE name and version

``Visual Studio Code v1.21.1``

### OS name and version

``OSX 10.13.3``

**Comment by chrisblossom** [comment]
@ArtemGovorov That was quick (per usual), thanks! If you don't mind me asking, what was I doing to cause this error?

**Comment by ArtemGovorov** [comment]
@chrisblossom The issue was with `fs-extra` being used from an incorrect location by VS Code extension.
