### ISSUE TITLE
Exception in WebStorm.core

### ISSUE THREAD

**Issue by mbaranovski** [wallabyjs/public#1612]
### Issue description or question
For a while I noticed that WebStorm is throwing me a fatal error. I tried to reinstall wallaby but the same occurs.

### Code editor or IDE name and version
WebStorm v 181.4203.498

### OS name and version
OSX 10.12.6

### Error comments:
`[3 intention duplicates found for com.wallaby.javascript.actions.JumpToFailingTestIntentionAction@58e89271, 3 intention duplicates found for com.wallaby.javascript.actions.RunTestFileIntentionAction@600cccdd, 3 intention duplicates found for com.wallaby.javascript.actions.ShowAssertionErrorDiffIntentionAction@3a1b20d9, 3 intention duplicates found for com.wallaby.javascript.actions.ShowLastRunScreenShotIntentionAction@35d2460d, 3 intention duplicates found for com.wallaby.javascript.actions.RunAllTestsIntentionAction@29b521dc, 3 intention duplicates found for com.wallaby.javascript.actions.ShowFileUncoveredRangesIntentionAction@2fd96a13, 3 intention duplicates found for com.wallaby.javascript.actions.ShowLineUncoveredRangesIntentionAction@4c279ad9, 3 intention duplicates found for com.wallaby.javascript.actions.RunTestIntentionAction@6b624f7e, 3 intention duplicates found for com.wallaby.javascript.actions.JumpToErrorSourceIntentionAction@6b59380f, 3 intention duplicates found for com.wallaby.javascript.actions.ShowLineTestsIntentionAction@f345e85]`

### Error Details
`[3 intention duplicates found for com.wallaby.javascript.actions.JumpToFailingTestIntentionAction@58e89271, 3 intention duplicates found for com.wallaby.javascript.actions.RunTestFileIntentionAction@600cccdd, 3 intention duplicates found for com.wallaby.javascript.actions.ShowAssertionErrorDiffIntentionAction@3a1b20d9, 3 intention duplicates found for com.wallaby.javascript.actions.ShowLastRunScreenShotIntentionAction@35d2460d, 3 intention duplicates found for com.wallaby.javascript.actions.RunAllTestsIntentionAction@29b521dc, 3 intention duplicates found for com.wallaby.javascript.actions.ShowFileUncoveredRangesIntentionAction@2fd96a13, 3 intention duplicates found for com.wallaby.javascript.actions.ShowLineUncoveredRangesIntentionAction@4c279ad9, 3 intention duplicates found for com.wallaby.javascript.actions.RunTestIntentionAction@6b624f7e, 3 intention duplicates found for com.wallaby.javascript.actions.JumpToErrorSourceIntentionAction@6b59380f, 3 intention duplicates found for com.wallaby.javascript.actions.ShowLineTestsIntentionAction@f345e85]
java.lang.IllegalStateException: [3 intention duplicates found for com.wallaby.javascript.actions.JumpToFailingTestIntentionAction@58e89271, 3 intention duplicates found for com.wallaby.javascript.actions.RunTestFileIntentionAction@600cccdd, 3 intention duplicates found for com.wallaby.javascript.actions.ShowAssertionErrorDiffIntentionAction@3a1b20d9, 3 intention duplicates found for com.wallaby.javascript.actions.ShowLastRunScreenShotIntentionAction@35d2460d, 3 intention duplicates found for com.wallaby.javascript.actions.RunAllTestsIntentionAction@29b521dc, 3 intention duplicates found for com.wallaby.javascript.actions.ShowFileUncoveredRangesIntentionAction@2fd96a13, 3 intention duplicates found for com.wallaby.javascript.actions.ShowLineUncoveredRangesIntentionAction@4c279ad9, 3 intention duplicates found for com.wallaby.javascript.actions.RunTestIntentionAction@6b624f7e, 3 intention duplicates found for com.wallaby.javascript.actions.JumpToErrorSourceIntentionAction@6b59380f, 3 intention duplicates found for com.wallaby.javascript.actions.ShowLineTestsIntentionAction@f345e85]
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.checkForDuplicates(IntentionManagerImpl.java:300)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.getAvailableIntentionActions(IntentionManagerImpl.java:275)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:337)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.a(ShowIntentionsPass.java:269)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:245)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

**Comment by ArtemGovorov** [comment]
What is your Wallaby plugin version? The issue was fixed in v1.0.110.

**Comment by mbaranovski** [comment]
🍿 🌯 🍿  Updating worked, thanks.
