### ISSUE TITLE
errors in nx project

### ISSUE THREAD

**Issue by zpydee** [wallabyjs/public#1613]
error:

```
​​​​​0 failing tests, 24 passing​​​​​
​​​​​​​​​​
​​Uncaught Error: Cannot find module './wallabyTest.js'​​
​​at http://localhost:62713/wallaby-webpack.js?1523513781368:1​​
​​Uncaught Error: Cannot find module '42'​​
​​at http://localhost:62713/wallaby-webpack.js?1523513781368:1​​
​​Uncaught Error: Cannot find module '15'​​
​​at http://localhost:62713/wallaby-webpack.js?1523513781368:1​​
​​Uncaught Error: Cannot find module '19'​​
​​at http://localhost:62713/wallaby-webpack.js?1523513781368:1​​
​​Uncaught Error: Cannot find module '20'​​
​​at http://localhost:62713/wallaby-webpack.js?1523513781368:1​​
​​Uncaught Error: Cannot find module "./shell.component.css"​​
  at ​libs/core/shell/src/components/shell/shell.component.ts:23​
​​Module not found: Error: Can't resolve 'css-loader' in '/Users/zpydee/hack/nx'ModuleNotFoundError: Module not found: Error: Can't resolve 'css-loader' in '/Users/zpydee/hack/nx'​​
​​    at factoryCallback (/Users/zpydee/hack/nx/node_modules/webpack/lib/Compilation.js:276:40)​​
​​    at factory (/Users/zpydee/hack/nx/node_modules/webpack/lib/NormalModuleFactory.js:237:20)​​
​​    at resolver (/Users/zpydee/hack/nx/node_modules/webpack/lib/NormalModuleFactory.js:60:20)​​
​​    at asyncLib.parallel (/Users/zpydee/hack/nx/node_modules/webpack/lib/NormalModuleFactory.js:193:21)​​
​​    at /Users/zpydee/hack/nx/node_modules/async/dist/async.js:3874:9​​
​​    at /Users/zpydee/hack/nx/node_modules/async/dist/async.js:473:16​​
​​    at iteratorCallback (/Users/zpydee/hack/nx/node_modules/async/dist/async.js:1048:13)​​
​​    at /Users/zpydee/hack/nx/node_modules/async/dist/async.js:958:16​​
​​    at /Users/zpydee/hack/nx/node_modules/async/dist/async.js:3871:13​​
​​    at /Users/zpydee/hack/nx/node_modules/async/dist/async.js:1126:9​​
​​    at /Users/zpydee/hack/nx/node_modules/async/dist/async.js:473:16​​
​​    at iteratorCallback (/Users/zpydee/hack/nx/node_modules/async/dist/async.js:1048:13)​​
​​    at /Users/zpydee/hack/nx/node_modules/async/dist/async.js:958:16​​
​​    at /Users/zpydee/hack/nx/node_modules/async/dist/async.js:1123:13​​
​​    at resolver.resolve (/Users/zpydee/hack/nx/node_modules/webpack/lib/NormalModuleFactory.js:263:20)​​
​​    at onError (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/Resolver.js:65:10)​​
​​    at loggingCallbackWrapper (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)​​
​​    at runAfter (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/Resolver.js:158:4)​​
​​    at innerCallback (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/Resolver.js:146:3)​​
​​    at loggingCallbackWrapper (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)​​
​​    at next (/Users/zpydee/hack/nx/node_modules/tapable/lib/Tapable.js:252:11)​​
​​    at /Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4​​
​​    at loggingCallbackWrapper (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)​​
​​    at runAfter (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/Resolver.js:158:4)​​
​​    at innerCallback (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/Resolver.js:146:3)​​
​​    at loggingCallbackWrapper (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)​​
​​    at next (/Users/zpydee/hack/nx/node_modules/tapable/lib/Tapable.js:252:11)​​
​​    at innerCallback (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/Resolver.js:144:11)​​
​​    at loggingCallbackWrapper (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)​​
​​    at next (/Users/zpydee/hack/nx/node_modules/tapable/lib/Tapable.js:249:35)​​
​​    at resolver.doResolve.createInnerCallback (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)​​
​​    at loggingCallbackWrapper (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)​​
​​    at afterInnerCallback (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/Resolver.js:166:11)​​
​​    at loggingCallbackWrapper (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)​​
​​    at next (/Users/zpydee/hack/nx/node_modules/tapable/lib/Tapable.js:249:35)​​
​​    at /Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:4​​
​​    at loggingCallbackWrapper (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)​​
​​    at runAfter (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/Resolver.js:158:4)​​
​​    at innerCallback (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/Resolver.js:146:3)​​
​​    at loggingCallbackWrapper (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)​​
​​    at next (/Users/zpydee/hack/nx/node_modules/tapable/lib/Tapable.js:252:11)​​
​​    at runAfter (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/Resolver.js:158:4)​​
​​    at innerCallback (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/Resolver.js:146:3)​​
​​    at loggingCallbackWrapper (/Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)​​
​​    at next (/Users/zpydee/hack/nx/node_modules/tapable/lib/Tapable.js:252:11)​​
​​    at /Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/forEachBail.js:29:14​​
​​    at /Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/ModulesInHierachicDirectoriesPlugin.js:42:12​​
​​    at /Users/zpydee/hack/nx/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:70:14​​
​​    at process._tickCallback (internal/process/next_tick.js:150:11)​​
```

wallaby.js
``` javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./tsconfig.spec.json').compilerOptions);

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'wallabyTest.js',
      'apps/**/*spec.js',
      'libs/**/*spec.js'
    ],

    module: {
      loaders: [
        {test: /\.css$/, loader: ['raw-loader', 'css-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'apps'),
        path.join(wallaby.projectCacheDir, 'libs'),
        'node_modules'
      ],
      alias: {
          '@spawntech': path.join(wallaby.projectCacheDir, 'libs')
      }
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'wallabyTest.ts', load: false},
      {pattern: 'apps/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'apps/**/*.d.ts', ignore: true},
      {pattern: 'apps/**/*spec.ts', ignore: true},
      {pattern: 'libs/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'libs/**/*.d.ts', ignore: true},
      {pattern: 'libs/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'apps/**/*spec.ts', load: false},
      {pattern: 'libs/**/*spec.ts', load: false},
      {pattern: 'apps/**/e2e/**', ignore: true},
      {pattern: 'libs/**/e2e/**', ignore: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },
  };
};

```

wallabyTest.ts
```typescript
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';

import {getTestBed} from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);
```

@ArtemGovorov what do I have wrong?

**Comment by zpydee** [comment]
many thanks
