### ISSUE TITLE
How to use with Jest Node Environments?

### ISSUE THREAD

**Issue by vinialbano** [wallabyjs/public#1618]
### Issue description or question
I am trying to test my MongoDB repositories with this implementation [https://github.com/vladgolubev/jest-mongodb](url)

It works normally when using Jest alone, but when I try to use with Wallaby, I get the following error:

`TypeError: Cannot read property 'getConnectionString' of undefined
    at MongoEnvironment.setup (<path>/mongo-environment.js:11:56)
    at <path>/node_modules/jest-runner/build/run_test.js:71:23
    at Generator.next (<anonymous>)
    at step (<path>/node_modules/jest-runner/build/run_test.js:147:191)
    at <path>/node_modules/jest-runner/build/run_test.js:147:437
    at Promise (<anonymous>)
    at <path>/node_modules/jest-runner/build/run_test.js:147:99
    at runTestInternal (<path>/node_modules/jest-runner/build/run_test.js:103:17)
    at <path>/node_modules/jest-runner/build/run_test.js:161:23
    at Generator.next (<anonymous>)
    at step (<path>/node_modules/jest-runner/build/run_test.js:147:191)
    at <path>/node_modules/jest-runner/build/run_test.js:147:437
    at Promise (<anonymous>)
    at <path>/node_modules/jest-runner/build/run_test.js:147:99
    at runTest (<path>/node_modules/jest-runner/build/run_test.js:174:18)
    at <path>/node_modules/jest-runner/build/index.js:67:64
    at Generator.next (<anonymous>)
    at step (<path>/node_modules/jest-runner/build/index.js:29:191)
    at <path>/node_modules/jest-runner/build/index.js:29:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

How can I make it work? It seems that Wallaby can't run the Jest Setup file.

### Wallaby.js configuration file

```javascript
module.exports = function () {
  return {
    files: [
      '/app/**/*.js',
      '!/app/**/__tests__/*.js'
    ],
    tests: [
      'app/**/__tests__/*.js'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    testFramework: 'jest'
  }
}
```

### Code editor or IDE name and version

WebStorm v2017.2.2

### OS name and version

OSX 10.13.4

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. There was a bug with Jest `globalSetup` support in wallaby. The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.
