### ISSUE TITLE
Failed to find modules - Angular 2, Typescript

### ISSUE THREAD

**Issue by GPavlovic** [wallabyjs/public#1628]
### Issue description or question
So I have an Angular 2 project, built with typescript, and running tests via karma right now. I am attempting to configure Wallaby, and having some trouble which might be related to my vendor bundle?
This is an example of the error that I am seeing:
```
​​[at-loader] ..\..\..\Users\goran.pavlovic\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.83\projects\36ab87e4dd4b0243\instrumented\Client\app\modules\common\cachers\booking-category.cacher.ts:1:28 ​​
​​    TS2307: Cannot find module '@angular/core'.Error: [at-loader] ..\..\..\Users\goran.pavlovic\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.83\projects\36ab87e4dd4b0243\instrumented\Client\app\modules\common\cachers\booking-category.cacher.ts:1:28 ​​
```
The rest of the errors are the same, but for lodash, rxjs/observable, etc.

Any ideas as to what I am doing wrong?

### Wallaby.js configuration file

```javascript
const ContextReplacementPlugin = require('webpack/lib/ContextReplacementPlugin');
const LoaderOptionsPlugin = require('webpack/lib/LoaderOptionsPlugin');

var wallabyWebpack = require('wallaby-webpack');
var testWebpackConfig = require('./Client/test/webpack.config.test');
var path = require("path");

module.exports = function (wallaby) {
  testWebpackConfig.entryPatterns = [];
  testWebpackConfig.entryPatterns.push('spec-bundle-wallaby.js');
  testWebpackConfig.entryPatterns.push('Client/app/**/*spec.js');
  testWebpackConfig.module.rules.forEach(l => {
    delete l.include;
  });
  testWebpackConfig.emitModulePaths = true;

  var webpackPostprocessor = wallabyWebpack(testWebpackConfig);

  return {
    files: [{
        pattern: "wwwroot/dist/vendor.js",
        load: false,
        instrument: false
      },
      {
        pattern: "Client/**/*.ts",
        load: false,
        instrument: true
      },
      {
        pattern: "spec-bundle-wallaby.js",
        load: false,
        instrument: false
      },
      {
        pattern: "Client/**/*.d.ts",
        ignore: true
      },
      {
        pattern: "Client/**/*.css",
        load: false
      },
      {
        pattern: "Client/**/*.scss",
        load: false
      },
      {
        pattern: "Client/**/*.html",
        load: false
      },
      {
        pattern: "Client/**/*spec.ts",
        ignore: true
      }
    ],

    tests: [{
        pattern: "Client/**/*spec.ts",
        load: false,
        instrument: true
      },
      {
        pattern: "Client/**/*.spec.ts",
        load: false,
        instrument: true
      }
    ],

    testFramework: "jasmine",

    middleware: function (app, express) {
      var path = require("path");
      app.use("/assets", express.static(path.join(__dirname, "./Client/app/assets")));
    },

    env: {
      kind: "chrome"
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true,

    workers: {
      initial: 1,
      regular: 1
    }
  };
};
```

webpack config:
```
const ContextReplacementPlugin = require('webpack/lib/ContextReplacementPlugin');
const LoaderOptionsPlugin = require('webpack/lib/LoaderOptionsPlugin');

var webpack = require('webpack');
var path = require('path');
var rootPath = path.join.bind(path, path.resolve(__dirname, '../../'));

module.exports = {
  devtool: 'source-map',
  resolve: {
    extensions: ['.ts', '.js'],
    modules: [rootPath('Client'), 'node_modules'],
  },
  module: {
    rules: [{
        test: /\.ts$/,
        use: [{
            loader: 'awesome-typescript-loader-gp?silent=true',
            query: {
              sourceMap: false,
              inlineSourceMap: true,
              compilerOptions: {
                removeComments: true
              }
            },
          },
          'angular2-template-loader'
        ],
        include: rootPath('Client'),
        exclude: [/\.e2e\.ts$/]
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.(png|jpg|jpeg|gif|svg|ico)$/,
        loader: 'url-loader?limit=25000'
      },
      {
        test: /\.css$/,
        loader: ['raw-loader', 'css-loader']
      },
      {
        test: /\.scss$/,
        loader: ['raw-loader', 'sass-loader']
      },
      {
        test: /\.html$/,
        loader: 'html-loader?minimize=false'
      }

    ]
  },
  plugins: [
    new webpack.DllReferencePlugin({
      context: __dirname,
      manifest: require('../../wwwroot/dist/vendor-manifest.json')
    })
  ],
  performance: {
    hints: false
  },
  node: {
    global: true,
    process: false,
    crypto: 'empty',
    module: false,
    clearImmediate: false,
    setImmediate: false
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.22.2

### OS name and version

Windows 10.0.16299 Build 16299

**Comment by GPavlovic** [comment]
So I have managed to get it in a better state (maybe?). I now have an issue where the requires that are in my angular components (to dynamically load json files with translations in this case). are through errors like: 
```
    ​​Error: Cannot find module "."​​
      at webpackMissingModule ​Client/app/modules/common/helpers/category-label-format/category-label-format.helper.ts:30​
      at MockCategoryLabelFormatHelper.CategoryLabelFormatHelper ​Client/app/modules/common/helpers/category-label-format/category-label-format.helper.ts:30:12​
      at new MockCategoryLabelFormatHelper ​Client/test/mocks/helpers/category-label-format.helper.mock.ts:6​
      at t.<anonymous> ​Client/app/modules/cancel-booking/components/cancel-acknowledgement/cancel-acknowledgement.component.spec.ts:33:4​
```
from a line that looks like: 
```
        for (let locale of this.configurationCacher.locales)
        {
            this.localizationService.mergeTranslations(locale.cultureName, require('./compact-change-party-size.component.' + locale.cultureName + '.json'));
        }
```
