### ISSUE TITLE
Unexpected token { (and just getting Wallaby setup in general for React, Webpack, ES6/7, Jest, relative & absolute import, styled-components, snapshots)

### ISSUE THREAD

**Issue by reywright** [wallabyjs/public#1633]
#I made a repo based off of the private repo I work on, in order to give you more context. Can you assist in helping me set this up?

### Issue description or question
My current issue (though I'm sure there will be more after I resolve this one) currently throws this error:

```
/Users/rwright/dev/wallaby-nowork/config/jest/testSetup.js:1​​
​​({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { configure } from 'enzyme';​​
​​                                                                                                ^​​
​​​​
​​SyntaxError: Unexpected token {​​
at new Script (vm.js:51:7)​​
​​    at ScriptTransformer._transformAndBuildScript (/Users/rwright/dev/wallaby-nowork/node_modules/jest-runtime/build/script_transformer.js:305:17)​​
​​    at ScriptTransformer.transform (/Users/rwright/dev/wallaby-nowork/node_modules/jest-runtime/build/script_transformer.js:332:21)​​
​​    at Runtime._execModule (/Users/rwright/dev/wallaby-nowork/node_modules/jest-runtime/build/index.js:501:53)​​
​​    at Runtime.requireModule (/Users/rwright/dev/wallaby-nowork/node_modules/jest-runtime/build/index.js:332:14)​​
​​    at new Runtime (/Users/rwright/dev/wallaby-nowork/node_modules/jest-runtime/build/index.js:171:14)​​
​​    at runTest (/Users/rwright/dev/wallaby-nowork/node_modules/jest-runner/build/run_test.js:91:19)​​
​​    at /Users/rwright/dev/wallaby-nowork/node_modules/jest-runner/build/index.js:71:68​​
​​    at Generator.next (<anonymous>)​​
​​    at step (/Users/rwright/dev/wallaby-nowork/node_modules/jest-runner/build/index.js:23:376)​​
​​    at /Users/rwright/dev/wallaby-nowork/node_modules/jest-runner/build/index.js:23:536​​
​​    at <anonymous>​​
​​    at process._tickCallback (internal/process/next_tick.js:118:7)​​
```

### Wallaby.js configuration file

https://github.com/reywright/wallaby-nowork

`yarn install` then `yarn test` will run the tests, which pass.

### Code editor or IDE name and version
Visual Studio Code v1.21.1?

### OS name and version
OSX 10.12.6

**Comment by ArtemGovorov** [comment]
Had sent you [the PR](https://github.com/reywright/wallaby-nowork/pull/1) to make your config work.

Changes in the `package.json` (`<rootDir>`) were not required for wallaby + babel 6, but looks like they are required for wallaby + babel 7 (will investigate if it's possible to skip them for babel 7).
