### ISSUE TITLE
erroneously enabled strict mode

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#1634]
### Issue description or question

I'm getting this error:

```plain
SyntaxError: Binding eval in strict mode (672:24)​​
[Error] ​​    at process.emit (events.js:182:13)​​
[Error] ​​    at emit (internal/child_process.js:797:12)​​
[Error] ​​    at process._tickCallback (internal/process/next_tick.js:174:19)​​
```

Which is coming out of [this file](https://github.com/boneskull/node-red/blob/experimental/lerna/packages/core-nodes/test/logic/10-switch_spec.js).

You'll note this file does *not* have a `'use strict'` declaration.

### Wallaby.js configuration file

```javascript
'use strict';

module.exports = wallaby => {
  return {
    files: [
      'packages/core-nodes/nodes/**',
      'packages/runtime/api/**',
      'packages/runtime/runtime/**'
    ],

    tests: [
      'packages/core-nodes/test/**/*_spec.js',
      'packages/runtime/test/**/*_spec.js'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    setup() {
      wallaby.testFramework.timeout(3000);
    },
    debug:true
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.22.2

### OS name and version

OSX High Sierra

**Comment by boneskull** [comment]
Likewise [this file](https://github.com/boneskull/node-red/blob/experimental/lerna/packages/runtime/runtime/storage/localfilesystem/projects/defaultFileSet.js) errors with:

```plain
[Error] ​​Failed to parse packages/runtime/runtime/storage/localfilesystem/projects/defaultFileSet.js, SyntaxError: Binding package in strict mode (19:12)​​
[Error] ​​    at process.emit (events.js:182:13)​​
[Error] ​​    at emit (internal/child_process.js:797:12)​​
[Error] ​​    at process._tickCallback (internal/process/next_tick.js:174:19)​​
```

Again, a valid "strict" error, but no pragma.  My system `node` is v10.0.0.
