### ISSUE TITLE
Lazy loading of modules ++ (Aurelia, Require, Node_modules)

### ISSUE THREAD

**Issue by einari** [wallabyjs/public#1637]
### Issue description or question

I feel like I'm trying to bend the spoon with my mind here and it won't bend. Not sure if should bend or I should stop trying to bend it. 

Anywho, here is what I'm trying to accomplish:
I have the following structure for my files and tests.

```
+-- features
       | something.js
       +-- for_something
              | when_doing_stuff.js
              +-- given
                     | a_context.js               
```

We want to be able to `import` the system under test (`something.js`) into the (`when_doing.stuff.js`) which resides in either a folder called 'for_<name of unit>' or a folder called 'when_<some behavior>' as a sub folder of the system under test.
 
In addition to this, we want to be able to import reusable contexts that resides within the specification folder itself (`given/a_context.js`). Since it is located where it is, I'm not able to actually get this to load properly unless I explicitly configure the `tests` array to ignore given folders for instance. But the problem is also that we tend to have things on the same folder level as the specification itself that we want to import as well, which then complicates things.

On top of this, our systems import things that lives in the `node_modules` folder, but we don't want to be putting that entire folder into the `files` array. We've tried with a `middleware` without success. 

We're using this between a lot of different projects and we're trying to come up with a generic approach that will work for all these - so having specific configuration for each project is something we're trying to avoid. We want to package this up into an NPM package that we use as dev-dependency in every project.

We want to use Babel for transpiling.

### Wallaby.js configuration file

You can find a full setup [here](https://github.com/einari/WallabyIssues/tree/master/require).

Since we are using Aurelia and we need its polyfills, we've configured it with `requirejs` so that we can get the polyfills initialized before running specs. We are not wedded to this at all and basically very pragmatic to how it all fits together - as long as it does not severely impact the feedback loop and also startup time of Wallaby.

As you'll see, this does not work - it will fail trying to require things from `@dolittle/commands` which is sitting in `node_modules`. We've tried with concrete configurations of it by adding it to `files` and also manually requiring it and setting up paths for requirejs. All these feels wrong as that configuration would grow and grow and becomes also very project specific.

### Code editor or IDE name and version

Visual Studio Code v1.22.2

### OS name and version

macOS

**Comment by ArtemGovorov** [comment]
How do you build your app for production? Are you using aurelia-cli?

**Comment by einari** [comment]
We don't use aurelia-cli - we use WebPack directly. We've generalized our setup for that [here](https://github.com/dolittle-interaction/JavaScript.Build.Aurelia). 

We started off setting this all up with WebPack as well - but wasn't able to do that either with the requirements we have.

In the project referenced in this comment, you'll see a working Karma setup. The problem we have with Karma during development is that is notoriuosly unreliable on picking up changes and actually running things as things change. And with good experience in the past with Wallaby we really want to move over to your excellent tool :)

**Comment by ArtemGovorov** [comment]
>  we use WebPack directly.

Ah, this should make things easier. Webpack is the easiest way to make wallaby work with Aurelia (for tests running in browser). Take a look into [this sample project](https://github.com/stevies/aurelia-testing-sample).

> We started off setting this all up with WebPack as well - but wasn't able to do that either with the requirements we have.

What was the issue with it?

**Comment by einari** [comment]
With WebPack, I get the problem of the stuff in `node_modules` that gets imported not being handled correctly:

```shell
[Info]​​​​​ Sun, 29 Apr 2018 07:32:48 GMT wallaby:workers Sandbox (active) [oedmx] error: Uncaught Error: Module parse failed: Unexpected token (6:8)
​​​​​[Info]​​​​​ You may need an appropriate loader to handle this file type.
​​​​​[Info]​​​​​ |  *--------------------------------------------------------------------------------------------*/
​​​​​[Info]​​​​​ | export class Command {
​​​​​[Info]​​​​​ |     type='';
​​​​​[Info]​​​​​ | }
​​[Error] Runtime error: Uncaught Error: Module parse failed: Unexpected token (6:8)​​
```

If I then add a rule to the Webpack setup for doing transpilation in Webpack as well like this:

```json
{test: /\.js$/, loader: 'babel-loader' }
```

I get this: 

```shell
[Info]​​​​​ Sun, 29 Apr 2018 07:37:40 GMT wallaby:workers Sandbox (active) [x01xx] error: Uncaught Error: Module build failed: TypeError: Cannot read property 'toString' of undefined
​​​​​[Info]​​​​​     at readBabelConfig (/Users/einari/Projects/Playground/WallabyIssues/webpack/node_modules/babel-loader/lib/utils/read.js:13:43)
​​​​​[Info]​​​​​     at Object.module.exports (/Users/einari/Projects/Playground/WallabyIssues/webpack/node_modules/babel-loader/lib/index.js:126:30)
​​[Error] Runtime error: Uncaught Error: Module build failed: TypeError: Cannot read property 'toString' of undefined​​
​​[Error]     at readBabelConfig (/Users/einari/Projects/Playground/WallabyIssues/webpack/node_modules/babel-loader/lib/utils/read.js:13:43)​​
​​[Error]     at Object.module.exports (/Users/einari/Projects/Playground/WallabyIssues/webpack/node_modules/babel-loader/lib/index.js:126:30)​​
```

I've updated my reproduction with a Webpack folder with it all set up - the rule is commented out right now.

**Comment by einari** [comment]
I'm realizing that we probably would avoid a world of hurt by having it transpiled in the module that is being imported. Let me give that a shot first.

**Comment by einari** [comment]
That cleared it all. I thought I could get away with not transpiling things before publishing to NPM for now. Figured I'd save some time. Tunnelvision.  

Thanks @ArtemGovorov  - great support as always. Sorry for rubberducking you..
