### ISSUE TITLE
ConnectionException on starting wallaby

### ISSUE THREAD

**Issue by benbelow** [wallabyjs/public#1656]
### Issue description or question

When running wallaby through Webstorm, the task spins forever. In the Webstorm logs is the line: 

```WARN -                        Wallaby - Connection refused: connect 
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.Socket.connect(Socket.java:589)
	at c.b.a.b.run(Unknown Source)
	at com.wallaby.javascript.session.g.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)```

### Wallaby.js configuration file

```module.exports = function (wallaby) {

    var wallabyWebpack = require('wallaby-webpack');
    var webpack = require('webpack');
    var wallabyPostprocessor = wallabyWebpack({
        plugins:
            [
                new webpack.NormalModuleReplacementPlugin(/\.(gif|png|scss|css)$/, 'node-noop')
            ],
    });

    // Babel, jest-cli and some other modules are located under
    // react-scripts/node_modules, so need to let node.js know about it
    var path = require('path');
    process.env.NODE_PATH +=
        path.delimiter +
        path.join(__dirname, 'node_modules') +
        path.delimiter +
        path.join(__dirname, 'node_modules/react-scripts/node_modules');
    require('module').Module._initPaths();

    // Babel needs this
    process.env.NODE_ENV = 'development';

    return {
        files: [
            'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
            '!src/**/*.test.js'
        ],

        tests: ['src/**/*.test.js'],

        env: {
            type: 'node',
            runner: 'node'
        },

        compilers: {
            '**/*.js': wallaby.compilers.babel({
                babel: require('babel-core'),
                presets: ['react-app', 'es2017']
            }),
        },

        setup: (wallaby) => {
            const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(p => require.resolve('react-scripts/' + p));
            delete jestConfig.transform['^.+\\.(js|jsx)$'];
            delete jestConfig.testEnvironment;
            wallaby.testFramework.configure(jestConfig);
        },

        testFramework: 'jest',
    };
};

```

### Code editor or IDE name and version

WebStorm 2018.1.1?

### OS name and version

Windows 10

**Comment by benbelow** [comment]
Further info: 

> Wallaby was working fine last week, this week I am working from another country via a VPN.
> I have tried re-installing the latest version of wallaby
> I have tried invalidating Webstorm's cache

**Comment by benbelow** [comment]
After some experimentation this appears to have been caused by changing my Webstorm settings to connect via IPv6 rather than IPv4, as otherwise it was not connecting to my license server.

**Comment by benbelow** [comment]
@ArtemGovorov Would you expect wallaby to be able to authenticate over IPv6? As I can't connect with the Jetbrains license server on IPv4, nor wallaby on IPv6, my workflow is left in a non ideal state.

**Comment by ArtemGovorov** [comment]
@benbelow Wallaby doesn't need to authenticate at all (should be able to work offline). Looks like the error is thrown when wallaby plugin tries to connect to wallaby core (node.js process) via websocket. I think we have seen such error before, but it was related to user's machine (as opposed to IDE) firewall settings.

Could you please specifies what setting(s) are causing the issue? A screenshot of the settings tab would be great, so we can try the same in our environment.

**Comment by benbelow** [comment]
The only setting that's changed between my current configuration (wallaby working) and the one in which it didn't, is in the `C:\Program Files\JetBrains\WebStorm 2018.1\bin\webstorm64.exe.vmoptions` file.

I'd changed the line `-Djava.net.preferIPv4Stack=true`

to: `-Djava.net.preferIPv6Addresses=true`

**Comment by ArtemGovorov** [comment]
Thanks for providing the details. The issue is fixed and the fix is published in plugin v1.0.113.
