### ISSUE TITLE
Troubles setting up: jest, react, es6, custom project

### ISSUE THREAD

**Issue by denislutz** [wallabyjs/public#1668]
### Issue description or question
Hi Artem, I tried my best to setup wallaby, I could solve many issues, but I am failing
with the same issue.

```
[Info]​​​​​ Thu, 24 May 2018 13:30:36 GMT wallaby:workers [worker #0, session #o1owd] Running tests in sandbox
​​​​​[Info]​​​​​ Thu, 24 May 2018 13:30:50 GMT wallaby:workers Sandbox (active) [o1owd] error: Error: Failed to get mock metadata: /mypath/myproject/node_modules/cheerio/node_modules/parse5/lib/tokenizer/named_entity_data.js
​​​​​[Info]​​​​​ See: http://facebook.github.io/jest/docs/manual-mocks.html#content
​​[Error] Runtime error: Error: Failed to get mock metadata: /mypath/myproject/node_modules/cheerio/node_modules/parse5/lib/tokenizer/named_entity_data.js​​
​​[Error] See: http://facebook.github.io/jest/docs/manual-mocks.html#content​​
​​[Error]     at Runtime._generateMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:498:15)​​
​​[Error]     at Runtime.requireMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:327:43)​​
​​[Error]     at Runtime.requireModuleOrMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:335:19)​​
​​[Error]     at Object.<anonymous> (/mypath/myproject/node_modules/cheerio/node_modules/parse5/lib/tokenizer/index.js:5:14)​​
​​[Error]     at Runtime._execModule (/mypath/myproject/node_modules/jest-runtime/build/index.js:448:13)​​
​​[Error]     at Runtime.requireModule (/mypath/myproject/node_modules/jest-runtime/build/index.js:265:14)​​
​​[Error]     at Runtime._generateMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:490:34)​​
​​[Error]     at Runtime.requireMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:327:43)​​
​​[Error]     at Runtime.requireModuleOrMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:335:19)​​
​​[Error]     at Object.<anonymous> (/mypath/myproject/node_modules/cheerio/node_modules/parse5/lib/parser/index.js:3:17)​​
​​[Error]     at Runtime._execModule (/mypath/myproject/node_modules/jest-runtime/build/index.js:448:13)​​
​​[Error]     at Runtime.requireModule (/mypath/myproject/node_modules/jest-runtime/build/index.js:265:14)​​
​​[Error]     at Runtime._generateMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:490:34)​​
​​[Error]     at Runtime.requireMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:327:43)​​
​​[Error]     at Runtime.requireModuleOrMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:335:19)​​
​​[Error]     at Object.<anonymous> (/mypath/myproject/node_modules/cheerio/node_modules/parse5/lib/index.js:3:14)​​
​​[Error]     at Runtime._execModule (/mypath/myproject/node_modules/jest-runtime/build/index.js:448:13)​​
​​[Error]     at Runtime.requireModule (/mypath/myproject/node_modules/jest-runtime/build/index.js:265:14)​​
​​[Error]     at Runtime._generateMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:490:34)​​
​​[Error]     at Runtime.requireMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:327:43)​​
​​[Error]     at Runtime.requireModuleOrMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:335:19)​​
​​[Error]     at Object.<anonymous> (/mypath/myproject/node_modules/cheerio/lib/parse.js:5:14)​​
​​[Error]     at Runtime._execModule (/mypath/myproject/node_modules/jest-runtime/build/index.js:448:13)​​
​​[Error]     at Runtime.requireModule (/mypath/myproject/node_modules/jest-runtime/build/index.js:265:14)​​
​​[Error]     at Runtime._generateMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:490:34)​​
​​[Error]     at Runtime.requireMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:327:43)​​
​​[Error]     at Runtime.requireModuleOrMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:335:19)​​
​​[Error]     at Object.<anonymous> (/mypath/myproject/node_modules/cheerio/lib/cheerio.js:5:13)​​
​​[Error]     at Runtime._execModule (/mypath/myproject/node_modules/jest-runtime/build/index.js:448:13)​​
​​[Error]     at Runtime.requireModule (/mypath/myproject/node_modules/jest-runtime/build/index.js:265:14)​​
​​[Error]     at Runtime._generateMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:490:34)​​
​​[Error]     at Runtime.requireMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:327:43)​​
​​[Error]     at Runtime.requireModuleOrMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:335:19)​​
​​[Error]     at Object.<anonymous> (/mypath/myproject/node_modules/cheerio/index.js:5:28)​​
​​[Error]     at Runtime._execModule (/mypath/myproject/node_modules/jest-runtime/build/index.js:448:13)​​
​​[Error]     at Runtime.requireModule (/mypath/myproject/node_modules/jest-runtime/build/index.js:265:14)​​
​​[Error]     at Runtime._generateMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:490:34)​​
​​[Error]     at Runtime.requireMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:327:43)​​
​​[Error]     at Runtime.requireModuleOrMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:335:19)​​
​​[Error]     at Object.<anonymous> (/mypath/myproject/node_modules/enzyme/build/ReactWrapper.js:13:16)​​
​​[Error]     at Runtime._execModule (/mypath/myproject/node_modules/jest-runtime/build/index.js:448:13)​​
​​[Error]     at Runtime.requireModule (/mypath/myproject/node_modules/jest-runtime/build/index.js:265:14)​​
​​[Error]     at Runtime._generateMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:490:34)​​
​​​​​[Info]​​​​​ Thu, 24 May 2018 13:30:51 GMT wallaby:workers Failed to map the stack to user code, entry message: Error: Failed to get mock metadata: /mypath/myproject/node_modules/cheerio/node_modules/parse5/lib/tokenizer/named_entity_data.js
​​​​​[Info]​​​​​ See: http://facebook.github.io/jest/docs/manual-mocks.html#content, stack: Error: Failed to get mock metadata: /mypath/myproject/node_modules/cheerio/node_modules/parse5/lib/tokenizer/named_entity_data.js
​​​​​[Info]​​​​​ See: http://facebook.github.io/jest/docs/manual-mocks.html#content
​​​​​[Info]​​​​​     at Runtime._generateMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:498:15)
​​​​​[Info]​​​​​     at Runtime.requireMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:327:43)
​​​​​[Info]​​​​​     at Runtime.requireModuleOrMock (/mypath/myproject/node_modules/jest-runtime/build/index.js:335:19)
​​​​​[Info]​​​​​     at Object.<anonymous> (/mypath/myproject/node_modules/cheerio/node_modules/parse5/lib/tokenizer/index.js:5:14)
​​​​​[Info]​​​​​     at Runtime._execModule (/mypath/myproject/node_modules/jest-runtime/build/index.js:448:13)
​​​​​[Info]​​​​​     at Runtime.requireModule (/mypath/myproject/node_modules/jest-runtime/build/index.js:265:14)
​​​​​[Info]​​​​​     at Runtime.u._wallabyReplaced.l.requireModule (/Users/minimalist/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.84/wallaby/runners/node
​​​​​[Info]​​​​​ console.warn: jest-haste-map: duplicate manual mock found:
​​​​​[Info]​​​​​   Module name: fontUrls
​​​​​[Info]​​​​​   Duplicate Mock path: /Users/minimalist/git/react-frontend-commons/src/config/styles/__mocks__/fontUrls.jsx
​​​​​[Info]​​​​​ This warning is caused by two manual mock files with the same file name.
​​​​​[Info]​​​​​ Jest will use the mock file found in: 
​​​​​[Info]​​​​​ /Users/minimalist/git/react-frontend-commons/src/config/styles/__mocks__/fontUrls.jsx
​​​​​[Info]​​​​​  Please delete one of the following two files: 
​​​​​[Info]​​​​​  /Users/minimalist/git/react-frontend-commons/build/esm/config/styles/__mocks__/fontUrls.js
​​​​​[Info]​​​​​ /Users/minimalist/git/react-frontend-commons/src/config/styles/__mocks__/fontUrls.jsx
​​​​​[Info]​​​​​ console.warn: jest-haste-map: duplicate manual mock found:
​​​​​[Info]​​​​​   Module name: fileMock
​​​​​[Info]​​​​​   Duplicate Mock path: /Users/minimalist/git/checkout-ui/__mocks__/fileMock.js
​​​​​[Info]​​​​​ This warning is caused by two manual mock files with the same file name.
​​​​​[Info]​​​​​ Jest will use the mock file found in: 
​​​​​[Info]​​​​​ /Users/minimalist/git/checkout-ui/__mocks__/fileMock.js
​​​​​[Info]​​​​​  Please delete one of the following two files: 
​​​​​[Info]​​​​​  /Users/minimalist/git/articlerating-ui/__tests__/__mocks__/fileMock.js
​​​​​[Info]​​​​​ /Users/minimalist/git/checkout-ui/__mocks__/fileMock.js
​​​​​[Info]​​​​​ console.log: FAIL src/MyModule/MyModule.test.jsx
​​​​​[Info]​​​​​ console.log:   ● Test suite failed to run
​​​​​[Info]​​​​​     Failed to get mock metadata: /mypath/myproject/node_modules/cheerio/node_modules/parse5/lib/tokenizer/named_entity_data.js
​​​​​[Info]​​​​​     
​​​​​[Info]​​​​​     See: http://facebook.github.io/jest/docs/manual-mocks.html#content
​​​​​[Info]​​​​​       
​​​​​[Info]​​​​​       at Runtime._generateMock (MyModule-ui/node_modules/jest-runtime/build/index.js:498:15)
​​​​​[Info]​​​​​       at Object.<anonymous> (MyModule-ui/node_modules/cheerio/node_modules/parse5/lib/tokenizer/index.js:5:14)
​​​​​[Info]​​​​​       at Runtime.u._wallabyReplaced.l.requireModule (../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.84/wallaby/runners/node/jest@0.4.3/initializer.js:14:19992)
​​​​​[Info]​​​​​       at Object.<anonymous> (MyModule-ui/node_modules/cheerio/node_modules/parse5/lib/parser/index.js:3:17)
​​​​​[Info]​​​​​       at Runtime.u._wallabyReplaced.l.requireModule (../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.84/wallaby/runners/node/jest@0.4.3/initializer.js:14:19992)
​​​​​[Info]​​​​​       at Object.<anonymous> (MyModule-ui/node_modules/cheerio/node_modules/parse5/lib/index.js:3:14)
​​​​​[Info]​​​​​       at Runtime.u._wallabyReplaced.l.requireModule (../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.84/wallaby/runners/node/jest@0.4.3/initializer.js:14:19992)
​​​​​[Info]​​​​​       at Object.<anonymous> (MyModule-ui/node_modules/cheerio/lib/parse.js:5:14)
​​​​​[Info]​​​​​       at Runtime.u._wallabyReplaced.l.requireModule (../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.84/wallaby/runners/node/jest@0.4.3/initializer.js:14:19992)
​​​​​[Info]​​​​​       at Object.<anonymous> (MyModule-ui/node_modules/cheerio/lib/cheerio.js:5:13)
​​​​​[Info]​​​​​       at Runtime.u._wallabyReplaced.l.requireModule (../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.84/wallaby/runners/node/jest@0.4.3/initializer.js:14:19992)
​​​​​[Info]​​​​​       at Object.<anonymous> (MyModule-ui/node_modules/cheerio/index.js:5:28)
​​​​​[Info]​​​​​       at Runtime.u._wallabyReplaced.l.requireModule (../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.84/wallaby/runners/node/jest@0.4.3/initializer.js:14:19992)
​​​​​[Info]​​​​​       at Object.<anonymous> (MyModule-ui/node_modules/enzyme/build/ReactWrapper.js:13:16)
​​​​​[Info]​​​​​       at Runtime.u._wallabyReplaced.l.requireModule (../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.84/wallaby/runners/node/jest@0.4.3/initializer.js:14:19992)
```

### Wallaby.js configuration file

```javascript
'use strict';
module.exports = function(wallaby) {
	const testPathExp = 'src/**/*.test.jsx';
	return {
		files: [
			{ pattern: 'node_modules/react-frontend-commons/build/es2015/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', instrument: false, load: true, ignore: false }, 
			{ pattern: 'node_modules/cheerio/**/*.js', instrument: false, load: true, ignore: false },
			{ pattern: 'testConfig/**.js*', instrument: false, load: true, ignore: false },
			{ pattern: 'testConfig/fileMock.js', instrument: false, load: true, ignore: false },
			'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
			`!${testPathExp}`,
		],
	  tests: [testPathExp],
	  env: {
		type: 'node',
		runner: 'node',
	},
		setup(wallaby) {
			const jestConfig = require('./testConfig/jest.json')
			wallaby.testFramework.configure(jestConfig);
		},
	  compilers: {
		  '**/*.js?(x)': wallaby.compilers.babel({
			babel: require('babel-core'),
		}),
		'**/*.svg': wallaby.compilers.babel({
			babel: require('babel-core'),
		  }),
		},
		testFramework: 'jest',
		debug: true,
	};
};
```

jest.json
```
{
	"automock": true,
	"collectCoverageFrom": [
		"src/**/*.{js,jsx}",
		"!src/**/*.story.{js,jsx}"
	],
	"setupTestFrameworkScriptFile": "<rootDir>/testConfig/setup-jasmine-env.js",
	"testRegex": "./src/.*.test.jsx$",
    "rootDir": "../",
	"testPathIgnorePatterns": ["/node_modules/", "/npm-build/"],
	"coverageReporters": [
		"text",
		"html",
		"cobertura",
		"lcov"
	],
	"moduleFileExtensions": [
		"js",
		"json",
		"jsx"
	],
	"unmockedModulePathPatterns": [
		"<rootDir>/node_modules",
		"<rootDir>/testConfig"
	],
	"moduleNameMapper": {
		"^.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/testConfig/fileMock.js"
	},
	"globals": {
		"__cdn_path__": true,
		"__webpack_public_path__": true
	},
	"setupFiles": ["<rootDir>/testConfig/setup.js"]
}


```

### Code editor or IDE name and version
Visual Studio Code v1. =>   Version 1.23.1 (1.23.1)

### OS name and version
OSX

I tried to include node_modules completelly but it takes too long to load everything.

Thanks a lot in Advance.

**Comment by ArtemGovorov** [comment]
Thanks for providing the details.

Under normal circumstances, you shouldn't need to include any `node_modules` in your `files` list, such as:

```diff
-{ pattern: 'node_modules/react-frontend-commons/build/es2015/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', instrument: false, load: true, ignore: false }, 
-{ pattern: 'node_modules/cheerio/**/*.js', instrument: false, load: true, ignore: false },
```

What happens if you remove those fro your `files` list?

If it doesn't help, could you please create and share a sample repo demonstrating the issue? We are happy to take a look and help with the configuration.

**Comment by denislutz** [comment]
Artem, thanks a lot. I was interrupted, so sorry for this late response. I will retry couple of things and of course figure out why I need this patterns in the node_modules and come back to this ticket.

**Comment by denislutz** [comment]
It works!  I am  ordering the license!

I set all automock to  false in the jest config.

`{
	"automock": false,`

For the future I think its a good approach to disable it at first. 

Here is the resulting wallaby.js config.

`'use strict';

module.exports = function(wallaby) {
	const testPathExp = 'src/**/*.test.jsx';
  
	return {
	  files: [
		{ pattern: 'testConfig/**.js*', instrument: false, load: true, ignore: false },
		'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
		`!${testPathExp}`,
	  ],
  
	  tests: [testPathExp],
  
	  env: {
		type: 'node',
		runner: 'node',
	  },
  
	  compilers: {
		'**/*.js?(x)': wallaby.compilers.babel({
		  babel: require('babel-core'),
		}),
		'**/*.svg': wallaby.compilers.babel({
			babel: require('babel-core'),
		  }),
	  },
	setup(wallaby) {
		const jestConfig = require('./testConfig/jest.json')
		wallaby.testFramework.configure(jestConfig);
	},
	  testFramework: 'jest',
	  debug: true,
	};
  };`
