### ISSUE TITLE
Use es6 modules in package

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1674]
### Issue description or question

Hi, I am trying to use bpmn-moddle package which is unfortunately packages with es6 modules.
I already tried two things:

First, I have updated my node to latest version 10.2.1.
Second, I am using `esm` in my wallaby configuration as per:

```
    env: {
      type: 'node',
      runner: 'node',
      params: {
        runner: `-r ${require.resolve('esm')}`
      }
    },
```

Yet, this is the error I receive:

```
/Users/tomi/Github/apps/corporatorts/node_modules/bpmn-moddle/index.js:1​​
​​({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export {​​
​​                                                                                         ^^^^^^​​
​​​​
​​SyntaxError: Unexpected token export​​
  at Object.<anonymous> ​src/server/models/bpmn_model.ts:2​
  at Object.<anonymous> ​src/server/models/tests/bpmn_model.test.ts:1​
```

### Wallaby.js configuration file

```javascript
module.exports = function() {
  return {
    files: [
      'tsconfig.json',
      'jest.setup.js',
      'test/*.js',
      'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg|graphql)',
      '!src/**/tests/*.+(ts|tsx)',
      '!src/luis_app',
      '!src/**/index.ts'
    ],

    tests: ['!src/**/tests/index.ts', 'src/**/tests/*.+(ts|tsx)'],

    env: {
      type: 'node',
      runner: 'node',
      params: {
        runner: `-r ${require.resolve('esm')}`
      }
    },

    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.23.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
[Jest doesn't support `esm` yet](https://github.com/facebook/jest/issues/4842). 

Having said that, if your Jest config doesn't exclude the module from being compiled, it should work for you even without `esm`. How does your Jest config look like and what file is is located in?

**Comment by tomitrescak** [comment]
Hi, this is my jest config:

```
module.exports = {
  roots: ['<rootDir>/src'],
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
    '^.+\\.js$': 'babel-jest',
    '\\.(gql|graphql)$': 'jest-transform-graphql'
  },
  testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$',
  // "setupTestFrameworkScriptFile": "<rootDir>/jest.run.js",
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  testResultsProcessor: './node_modules/luis/dist/bridges/jest/reporter',
  watchPathIgnorePatterns: ['<rootDir>/src/summary.json', '<rootDir>/src/snapshots.js'],
  setupTestFrameworkScriptFile: '<rootDir>/jest.setup.js',
  moduleNameMapper: {
    '^.*[.](css|CSS)$': '<rootDir>/test/styleMock.js',
    '^.*[.](jpg|gif|png|ttf|eot|svg)$': '<rootDir>/test/fileMock.js'
  },
  //transformIgnorePatterns: ['<rootDir>/node_modules/', '/!node_modules\\/bpmn-moddle']
  transformIgnorePatterns: ['node_modules/(?!(bpmn_moddle)/)']
};
```

this is the error:

```

    /Users/tomi/Github/apps/corporatorts/node_modules/bpmn-moddle/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export {
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export

    > 1 | import BpmnModdle from 'bpmn-moddle';
        | ^
      2 | import { Access } from './accesses_model';
      3 |
      4 | var moddle = new BpmnModdle();

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:402:17)
      at Object.<anonymous> (src/server/models/bpmn_process_model.ts:1:1)
```

**Comment by ArtemGovorov** [comment]
- Is Jest CLI working, or is throwing the same error? 
- May I see your babel config?

**Comment by tomitrescak** [comment]
@ArtemGovorov you are right, jest is throwing the same error. Scheise!
I will stop bothering now and move this to Jest forum then.

BTW. This is my ".babelrc"

```
{
  "env": {
    "development": {
      "plugins": ["transform-es2015-modules-commonjs"]
    },
    "test": {
      "plugins": ["transform-es2015-modules-commonjs"]
    }
  }
}
```

**Comment by vvscode** [comment]
@tomitrescak  any updates ? couldn't find related links. Have you solved it?

**Comment by tomitrescak** [comment]
Well, you are NOT going to like my answer but what I do is that I transpile all nasty modules after every install. It saves me from heaps of troubles across many packages. Since I transpile to ES5 it kills the tree shaking capability. As a result, I advise to reinstall modules before going production if you really need that.

Here is how I've done it:

1. Add the script below your project. e.g. '${Project_ROOT}/transform.js'
2. Add the line below to your scripts in package.json
3. Done! After every install the packages will be transpiled and you will have no issues
4. **NOTE**. If babel is not used in your project you will need to install it along with required plugins.

// package.json

```json
{
  "scripts": {
    ...
    "postinstall": "node transform_moddle.js",
  },
}
```

// transform.js

```js
const fs = require('fs');
const path = require('path');

function transformFiles(workPath) {
  console.log('Transforming: ' + workPath);

  const files = fs.readdirSync(workPath);
  for (let file of files) {
    const filePath = path.join(workPath, file);

    if (file === 'test' || file === 'assets' || file === 'dist') {
      continue;
    }

    if (fs.lstatSync(filePath).isDirectory()) {
      transformFiles(filePath);
      continue;
    }
    if (path.extname(file) === '.js') {
      const content = fs.readFileSync(filePath, { encoding: 'utf-8' });
      const result = require('babel-core').transform(content, {
        plugins: ['transform-es2015-modules-commonjs', 'transform-object-rest-spread']
      });
      fs.writeFileSync(filePath, result.code, { encoding: 'utf-8' });
    }
  }
}

// below list all packages that give you headaches, these are mine
const dirs = [
  'moddle',
  'moddle-xml',
  'bpmn-moddle',
  'bpmn-js',
  'diagram-js',
  'jest-styled-components'
];

for (let dir of dirs) {
  const workPath = __dirname + '/node_modules/' + dir;
  transformFiles(workPath);
}
```

**Comment by tomitrescak** [comment]
From what I understand, the mess above should be possible to handle natively with jest using following two settings.

1. Whitelist all module you want to transpile with jest in jest.config
2. Set that you want to transpile js with babel jest

```
{
"transformIgnorePatterns": [
  "node_modules/(?!(react-native|my-project|react-native-button)/)"
],
transform: {
    '^.+\\.(js|jsx)?$': 'babel-jest'
  },
}
```

I just never made it work. But maybe I missed something
