### ISSUE TITLE
Wallaby RealTime Error (TypeError: Cannot read property 'bindings' of null)

### ISSUE THREAD

**Issue by aethiss** [wallabyjs/public#1685]
### Question (HELP WANTED)
I try to configure wallaby for a react-native app. Jest test and the app work perfectly... just wallaby seems don't work. The error i receive is : 

```javascript
Failed to run compilers on src/components/containers/debugger/Debugger.js, TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/scope/index.js:869:12)
    at convertBlockScopedToVar (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:139:13)
    at PluginPass.VariableDeclaration (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:26:9)
    at newFn (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitQueue (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/context.js:124:21)
    at TraversalContext.visitQueue (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/context.js:124:21)
    at TraversalContext.visitMultiple (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/index.js:94:17)
    at traverse (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/traverse/lib/index.js:76:12)
    at transformFile (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/core/lib/transformation/index.js:88:29)
    at runSync (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/core/lib/transformation/index.js:45:3)
    at transformSync (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/core/lib/transform.js:43:38)
    at Object.transform (/Users/aethiss/Web/react-native/NextGon/client/client202/node_modules/@babel/core/lib/transform.js:22:38)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Wallaby.js configuration file

```javascript
/* eslint-disable */
module.exports = function (wallaby) {
  return {
    files: [
      { pattern: 'src/**/*.spec.js?(x)', ignore: true },
      { pattern: 'src/**/*.js?(x)', instrument: true, load: false, ignore: false },
      'src/**/*.snap'
    ],
    tests: [
      'src/**/*.spec.js?(x)'
    ],

    env: {
      type: 'node',
      runner: 'node',
    },

    testFramework: 'jest',

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        presets: [
          'react-native'
        ],
        plugins: [
          'transform-flow-strip-types',
          'transform-object-rest-spread',
          'transform-async-to-generator',
        ],
      }),
    },

    setup: (wallaby) => {
      wallaby.testFramework.configure(require('./package.json').jest);
    },
  };
};
```

### Code editor or IDE name and version
WebStorm 2018.1

### OS name and version
OSX High Sierra 10.13.4
#

**Comment by aethiss** [comment]
Sorry i can't add TAGS 'Help Wanted'

The example of my app here : 
https://github.com/aethiss/Nexgon-2.0.1/tree/master

**Comment by ArtemGovorov** [comment]
Wallaby babel compiler is using the latest found babel version in the repo by default (that is v7 in your case). However, `react-native` requires babel 6, otherwise it throws the error (because it's trying to use babel 6 presets in babel 7).

All you need to do is to tell wallaby babel compiler to [use babel 6](https://wallabyjs.com/docs/integration/es-next.html#babel-compiler-version):

```diff
    ...
    compilers: {
      '**/*.js': wallaby.compilers.babel({
+       babel: require('babel-core')
-       ...
      })
    },
```

Note that you may skip presets/plugins, because wallaby will use your `.babelrc` anyway.

**Comment by aethiss** [comment]
@ArtemGovorov Very Tnx.
(i also forced my boss to buy a license for all the others developer, wallaby.js best friends :D )

BTW: Works perfect.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
