### ISSUE TITLE
Returning a JSON object directly from a fat-arrow function breaks wallaby

### ISSUE THREAD

**Issue by andrewryan1906** [wallabyjs/public#1688]
### Issue description or question
Everything was working fine, and all of a sudden, I couldn't get any visual feedback from Wallaby. The status indicator was spinning indefinitely. 

What was weird was that the console said:

```
Mon, 04 Jun 2018 18:34:07 GMT wallaby:project Test run result processed and sent to IDE
```

And, the Wallaby app server reports all tests passing. So I know it's running the tests. But it won't report results visually to WebStorm. And this is all of a sudden, after weeks of it working.

I tried to:

* Restart Webstorm
* Comment out the test file I've been working on

Looking at the logs, I see:

```
2018-06-04 14:34:07,349 [ 480506]   WARN -                        Wallaby - start > end: start=2739; end=2711 
java.lang.IllegalArgumentException: start > end: start=2739; end=2711
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:52)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:42)
	at com.intellij.openapi.editor.impl.DocumentImpl.createRangeMarker(DocumentImpl.java:429)
	at com.intellij.openapi.editor.Document.createRangeMarker(Document.java:241)
	at com.wallaby.javascript.session.CoverableRange.a(Unknown Source)
	at com.wallaby.javascript.d.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:902)
	at com.wallaby.javascript.a.a(Unknown Source)
	at com.wallaby.javascript.y.run(Unknown Source)
	at com.wallaby.javascript.w.a(Unknown Source)
	at com.wallaby.javascript.WallabyController.a(Unknown Source)
	at com.wallaby.javascript.WallabyController.a(Unknown Source)
	at com.wallaby.javascript.WallabyController.a(Unknown Source)
	at com.wallaby.javascript.R.a(Unknown Source)
	at com.wallaby.javascript.R.consume(Unknown Source)
	at com.wallaby.javascript.session.Session$a.a(Unknown Source)
	at com.wallaby.javascript.session.Session$a.a(Unknown Source)
	at com.wallaby.javascript.session.s.run(Unknown Source)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:273)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:270)
	at com.intellij.util.concurrency.QueueProcessor.lambda$null$0(QueueProcessor.java:78)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
	at com.intellij.util.concurrency.QueueProcessor.lambda$wrappingProcessor$1(QueueProcessor.java:78)
	at com.intellij.util.concurrency.QueueProcessor.lambda$null$3(QueueProcessor.java:211)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
	at com.intellij.util.concurrency.QueueProcessor.lambda$startProcessing$4(QueueProcessor.java:211)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### Wallaby.js configuration file

```javascript
const ngxWallabyJest = require('ngx-wallaby-jest');

module.exports = function (wallaby) {
    return {
        files: [
            //Files used for testing
            {pattern: 'tsconfig.json', load: false},
            {pattern: 'jest.config.js', load: false},
            {pattern: 'src/setupJest.ts', load: false},
            {pattern: 'src/tsconfig.spec.json', load: false},
            {pattern: 'src/app/**/*.ts', load: false},
            {pattern: 'src/app/**/*.html', load: false},
            {pattern: 'test/**/*.ts', load: false},
            {pattern: 'src/app/**/*.spec.ts', ignore: true},
            {pattern: 'src/app/**/*.d.ts', ignore: true},
        ],
        tests: ['src/app/**/*.spec.ts'],
        env: {
        //Jest tests runs on node, not on a browser!
            type: 'node',
            runner: 'node'
        },
        preprocessors: {
            // This translate templateUrl and styleUrls to the right implementation
            // For wallaby
            'src/**/*.component.ts': ngxWallabyJest,
        },
        testFramework: 'jest',

        // bootstrap: function (wallaby) {
        //     //Use the configured jest file for testing
        //     const jestConfig = require('./jest.config.js');
        //     wallaby.testFramework.configure(jestConfig);
        // },
        debug: true
    };
};

```

### Code editor or IDE name and version

WebStorm v2018.1.4

### OS name and version

Windows 10

**Comment by andrewryan1906** [comment]
OK - I was able to - through trial and error - locate the code that was causing Wallaby to freak out. It's the Javascript shortcut for returning a JSON object directly from a fat-arrow function. So my code was:

```
  this.itemsToDisplay = objList.results.map(obj => ({
          textToDisplay: this.inputFormatter(obj),
          routerLink: this.url ? [this.url, obj.objectID] : null,
          displayAnchor: this.url
        } ) );
```

and that was causing the Wallaby app to spin and freak out. By changing it to:

```
 this.itemsToDisplay = objList.results.map(obj => {

          return {
            textToDisplay: this.inputFormatter(obj),
            routerLink: this.url ? [this.url, obj.objectID] : null,
            displayAnchor: this.url
          };
        });
```

The Wallaby app returned to normal.

I guess this is a bug, don't know if there's anything else you need me to do? I have a workaround now.

Thanks,
Andrew

**Comment by ArtemGovorov** [comment]
Thanks for the detailed report!

Unfortunately we can't yet reproduce it (with the exact same code and exact same config). Could you please clone this repo branch https://github.com/wallabyjs/ngCliWebpackSample/tree/1688, run `npm i` and wallaby to see if it's working for you? There's just a single test there, calling the exact same code that you've shared: https://github.com/wallabyjs/ngCliWebpackSample/blob/1688/src/app/app.component.ts#L14-L18. 

BTW, we have created a new config for Angular + Jest, that doesn't need any additional dependencies and allows tests to run on `.html` file changes. You may [try it from our docs](https://wallabyjs.com/docs/integration/angular.html#jest).

**Comment by andrewryan1906** [comment]
I downloaded the code and actually made some changes to make it more like my use case - namely, the map occurs inside of a Promise resolution... but couldn't get it to happen in the test branch.

I confirmed it still occurs on my project, but interestingly enough, it disappears if the assignment is omitted. So this:

```
 this.itemsToDisplay = objList.results.map(obj => ({

          textToDisplay: this.inputFormatter(obj),
          routerLink: this.url ? [this.url, obj.objectID] : null,
          displayAnchor: this.url

        }) );
```

still fails, but this:

```
 objList.results.map(obj => ({

          textToDisplay: this.inputFormatter(obj),
          routerLink: this.url ? [this.url, obj.objectID] : null,
          displayAnchor: this.url

        }) );
```

Does not, I was curious if it was something with my member variable, but indeed, this fails:

```
   let newValue = objList.results.map(obj => ({

          textToDisplay: this.inputFormatter(obj),
          routerLink: this.url ? [this.url, obj.objectID] : null,
          displayAnchor: this.url

        }) );
```

Hope this helps...

**Comment by ArtemGovorov** [comment]
Could you please try [this wallaby config](https://wallabyjs.com/docs/integration/angular.html#jest) to see if the issue shows up with it as well?

**Comment by smcenlly** [comment]
Closing this issue as we need more information. We will re-open the issue if more detail is provided.
