### ISSUE TITLE
Create-react-app config file

### ISSUE THREAD

**Issue by DayBr3ak** [wallabyjs/public#1691]
### Issue description or question
I can't start wallabyjs on a create-react-app at all. Can you explain what I'm doing wrong

output when I start:
```
​​​​​0 failing tests, 0 passing​​​​​
​​​​​​​​​​
​​SyntaxError: Invalid regular expression: /[\\\\\]node_modules[\\\\\].+\.(js|jsx|mjs)$/: Unterminated character class​​
​​    at new RegExp (<anonymous>)​​
​​    at shouldTransform (C:\Users\project\node_modules\react-scripts\node_modules\jest-runtime\build\ScriptTransformer.js:392:7)​​
​​    at ScriptTransformer._transformAndBuildScript (C:\Users\project\node_modules\react-scripts\node_modules\jest-runtime\build\ScriptTransformer.js:271:5)​​
​​    at ScriptTransformer.transform (C:\Users\project\node_modules\react-scripts\node_modules\jest-runtime\build\ScriptTransformer.js:316:21)​​
​​    at Runtime._execModule (C:\Users\project\node_modules\react-scripts\node_modules\jest-runtime\build\index.js:494:53)​​
​​    at Runtime.requireModule (C:\Users\project\node_modules\react-scripts\node_modules\jest-runtime\build\index.js:329:14)​​
​​    at new Runtime (C:\Users\project\node_modules\react-scripts\node_modules\jest-runtime\build\index.js:170:14)​​
​​    at runTest (C:\Users\project\node_modules\react-scripts\node_modules\jest\node_modules\jest-cli\build\runTest.js:78:19)​​
​​    at promise.then (C:\Users\project\node_modules\react-scripts\node_modules\jest\node_modules\jest-cli\build\TestRunner.js:197:14)​​
​​    at <anonymous>​​
​​    at process._tickCallback (internal/process/next_tick.js:118:7)​​
```

### Wallaby.js configuration file
config directly pulled from https://wallabyjs.com/docs/integration/react-jsx.html

```javascript
module.exports = function(wallaby) {
  // Babel, jest-cli and some other modules may be located under
  // react-scripts/node_modules, so need to let node.js know about it
  var path = require('path')
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, 'node_modules') +
    path.delimiter +
    path.join(__dirname, 'node_modules/react-scripts/node_modules')
  require('module').Module._initPaths()

  return {
    files: [
      'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!src/**/*.test.js?(x)'
    ],

    tests: ['src/**/*.test.js?(x)'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['react-app']
      })
    },

    setup: wallaby => {
      const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(
        p => require.resolve('react-scripts/' + p)
      )
      Object.keys(jestConfig.transform || {}).forEach(
        k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]
      )
      delete jestConfig.testEnvironment
      wallaby.testFramework.configure(jestConfig)
    },

    testFramework: 'jest'
  }
}

```

### Code editor or IDE name and version

Visual Studio Code v1.2.31

### OS name and version

Windows 10

create-react-app version 1.5.2

same result on nodejs version 9.10 and 10.3

**Comment by ArtemGovorov** [comment]
Hmm, it doesn't look like wallaby specific issue. Does `npm test` work for you?

**Comment by ArtemGovorov** [comment]
I'm closing the issue because there's been no activity on it recently. If it is still a valid issue for you, please provide the info requested above.

**Comment by PhilTheAir** [comment]
Similar to this issue: https://github.com/facebook/jest/issues/6385
