### ISSUE TITLE
Wallaby config for workshop Frontend Masters - help needed

### ISSUE THREAD

**Issue by smarigowda** [wallabyjs/public#1695]
### I am trying to configure wallaby js for one on the Frontend Masters workshop. I am getting error, need help to debug.

My github repository is https://github.com/smarigowda/testing-workshop/tree/my-working-branch

### Wallaby.js configuration file

Config file is located at https://github.com/smarigowda/testing-workshop/tree/my-working-branch/client

### Code editor or IDE name and version

Visual Studio Code v1.24.0

### OS name and version
OSX Sierra 10.12.6

**Comment by smarigowda** [comment]
Console log is given below.

```
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.601
​​​​​[Info]​​​​​ Wallaby App (realtime reports) is available at: http://localhost:51245
​​[Error] No files with tests found, check your tests list patterns.​​
​​​​​[Info]​​​​​ Can't determine tests to run for the change, re-running all tests.
​​​​​[Info]​​​​​ To prevent the full test run when can not determine tests to run, use `loose: true` configuration option.
​​[Error] Runtime error: Error: Cannot find module './test/setup-test-framework.js'​​
​​[Error]     at Function.Module._resolveFilename (module.js:469:15)​​
​​[Error]     at Function.resolve (internal/module.js:27:19)​​
​​[Error]     at Object.<anonymous> (./jest.config.js:10:43)​​
​​[Error]     at Module._compile (module.js:570:32)​​
​​[Error]     at Module._extensions..js (module.js:579:10)​​
​​[Error]     at Module.load (module.js:487:32)​​
​​[Error]     at tryModuleLoad (module.js:446:12)​​
​​[Error]     at Function.Module._load (module.js:438:3)​​
​​[Error]     at Module.require (module.js:497:17)​​
​​[Error]     at require (internal/module.js:20:19)​​
​​[Error]     at emitTwo (events.js:106:13)​​
​​[Error]     at WebSocket.emit (events.js:191:7)​​
​​[Error]     at afterWrite (_stream_writable.js:385:3)​​
​​[Error]     at onwrite (_stream_writable.js:376:7)​​
​​[Error]     at WritableState.onwrite (_stream_writable.js:90:5)​​
​​[Error]     at afterTransform (_stream_transform.js:79:3)​​
​​[Error]     at TransformState.afterTransform (_stream_transform.js:54:12)​​
​​[Error]     at Zlib.callback (zlib.js:649:5)​​
​​​​​[Info]​​​​​ Can't determine tests to run for the change, re-running all tests.
​​​​​[Info]​​​​​ To prevent the full test run when can not determine tests to run, use `loose: true` configuration option.
​​[Error] Runtime error: Error: Cannot find module './test/setup-test-framework.js'​​
​​[Error]     at Function.Module._resolveFilename (module.js:469:15)​​
​​[Error]     at Function.resolve (internal/module.js:27:19)​​
​​[Error]     at Object.<anonymous> (./jest.config.js:10:43)​​
​​[Error]     at Module._compile (module.js:570:32)​​
​​[Error]     at Module._extensions..js (module.js:579:10)​​
​​[Error]     at Module.load (module.js:487:32)​​
​​[Error]     at tryModuleLoad (module.js:446:12)​​
​​[Error]     at Function.Module._load (module.js:438:3)​​
​​[Error]     at Module.require (module.js:497:17)​​
​​[Error]     at require (internal/module.js:20:19)​​
​​[Error]     at emitTwo (events.js:106:13)​​
​​[Error]     at WebSocket.emit (events.js:191:7)​​
​​[Error]     at afterWrite (_stream_writable.js:385:3)​​
​​[Error]     at onwrite (_stream_writable.js:376:7)​​
​​[Error]     at WritableState.onwrite (_stream_writable.js:90:5)​​
​​[Error]     at afterTransform (_stream_transform.js:79:3)​​
​​[Error]     at TransformState.afterTransform (_stream_transform.js:54:12)​​
​​[Error]     at Zlib.callback (zlib.js:649:5)​​
```

**Comment by ArtemGovorov** [comment]
> Runtime error: Error: Cannot find module './test/setup-test-framework.js'​​

That's because the file was not in the [`files` list](https://wallabyjs.com/docs/config/files.html).

> [Error] No files with tests found, check your tests list patterns.​​

That's because the `tests` pattern was not correct (`__test__` vs `__tests__`).

I have sent you the [pull request with the change](https://github.com/smarigowda/testing-workshop/pull/1).
