### ISSUE TITLE
Big Codebase Infinite Building without errors

### ISSUE THREAD

**Issue by trsdln** [wallabyjs/public#1712]
### Issue description or question

I'm getting infinite loading while trying to start Jest unit/integration tests at VSCode. 

### Wallaby.js configuration file

```javascript
module.exports = wallaby => {
  const path = require('path');
  return {
    debug: false,
    testFramework: 'jest',
    files: [
      'imports/**/*.js',
      '.jest/config.js',
      '.jest/mongo-environment.js',
      '.jest/common.js',
      { pattern: 'imports/**/*.spec.js', ignore: true },
    ],
    tests: ['imports/**/*.spec.js'],
    compilers: {
      'imports/**/*.js': wallaby.compilers.babel({
        presets: [
          [
            'env',
            {
              targets: {
                node: 'current',
              },
              include: ['transform-es2015-destructuring'],
            },
          ],
          'stage-0',
        ],
        plugins: [
          [
            'ramda',
            {
              useES: false,
            },
          ],
        ],
      }),
    },
    env: { type: 'node' },
    workers: { initial: 1, regular: 1, recycle: true },
    setup: () => {
      var jestConfig = require(`${wallaby.localProjectDir}/.jest/config.js`);
      wallaby.testFramework.configure(jestConfig);
    },
  };
};
```

### Code editor or IDE name and version

Visual Studio Code 1.24.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Could you please open [Wallaby.js Console](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting) output channel in VS Code after starting Wallaby and copy&paste the output from there? If there's not much info there, please add the `debug: true` flag to your config, run Wallaby and paste some last output from the Wallaby Console before it starts loading infinitely.

**Comment by trsdln** [comment]
With debug enabled that's all I'm getting at output:

```
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 08:28:58 GMT wallaby:project Wallaby config: /Users/taras/projects/poly/graph/.jest/.wallaby-config.js
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.603
```

**Comment by ArtemGovorov** [comment]
Thanks.

Could you please check if these projects are working for you (clone + `npm i` + run wallaby):
- https://github.com/wallabyjs/wallaby-jest-snapshots
- https://github.com/ArtemGovorov/wallaby-1712

> Big Codebase

- How many files are in the `imports` folder? 
- Are there any `node_modules` folders in there?
- Are there any symlinks?
- If you change `imports/**...` both in `files` and `tests` to `imports1/**...` (deliberate mistake just to check something), does it start printing more data in the Wallaby Console log when you start it?

**Comment by trsdln** [comment]
> Could you please check if these projects are working for you (clone + npm i + run wallaby):

Both projects work fine. No issues there.

> How many files are in the imports folder?

853

> Are there any node_modules folders in there?

Single node_modules folder at the same level as `imports` folder.

Directory structure:

```
* my-project
  * imports
  * .jest
    * .wallaby-config.js
    * jest.config.js
  * node_modules
```

> Are there any symlinks?

no JS file symlinks files

> If you change imports/**... both in files and tests to imports1/**... (deliberate mistake just to check something), does it start printing more data in the Wallaby Console log when you start it?

No, nothings changes. I removed also babel compiler and it didn't affected anything.

```js
module.exports = wallaby => {
  const path = require('path');
  return {
    debug: true,
    testFramework: 'jest',
    files: [
      'imports1/**/*.js',
      { pattern: 'imports1/**/*.spec.js', ignore: true },
      '.jest/config.js',
      '.jest/mongo-environment.js',
      '.jest/common.js',
    ],
    tests: ['imports1/**/*.spec.js'],
    env: { type: 'node' },
    setup: () => {
      var jestConfig = require(`${wallaby.localProjectDir}/.jest/config.js`);
      wallaby.testFramework.configure(jestConfig);
    },
  };
};
```

**Comment by ArtemGovorov** [comment]
> No, nothings changes. I removed also babel compiler and it didn't affected anything.

This is interesting. Could you please try:

- remove or comment out these lines:
```
'.jest/config.js',
'.jest/mongo-environment.js',
'.jest/common.js',
```
and run wallaby to see if Wallaby Console log contains something new.
- copy&paste your project on disk, delete the `imports` folder and run wallaby on it to see if Wallaby Console log contains something new.

**Comment by trsdln** [comment]
I removed almost everything from config:

```js
module.exports = wallaby => {
  const path = require('path');
  return {
    debug: true,
    testFramework: 'jest',
    files: [
      'imports/**/*.js',
    ],
    tests: ['imports/**/*.spec.js'],
    env: { type: 'node' },
    setup: () => {
      wallaby.testFramework.configure('/irrelevant/path/to/nonexisting/file.js');
    },
  };
};
```

and removed imports folder. Those changes didn't affected anything.

Then I moved .wallaby-config 1 level up to project's root. Only then I got some output at console:

```
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:20 GMT wallaby:project Wallaby config: /Users/taras/projects/my-proejct/.wallaby-config.js
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:20 GMT wallaby:fs File added: package.json
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.603
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:21 GMT wallaby:fs File system scan has finished by timeout
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:21 GMT wallaby:project File cache: /Users/taras/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.86/projects/282bb2b022a5464c
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:21 GMT wallaby:uiService Listening port 51235
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:21 GMT wallaby:project package.json file change detected, invalidating local cache
​​​​​[Info]​​​​​ Wallaby App (realtime reports) is available at: http://localhost:51245
​​[Error] No files with tests found, check your tests list patterns.​​
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:workers Parallelism for initial run: 2, for regular run: 2
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:workers Starting run worker instance #0
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:workers Starting run worker instance #1
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:workers Web server is listening at 50436
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:project File cache requires some updates, waiting required files from IDE
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:project File package.json changes are patches only: false
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:project Preparing to process package.json
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:project File package.json is not instrumented by core
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:workers Started run worker instance (delayed) #1
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:workers Started run worker instance (delayed) #0
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:processor Running 1 processor(s) for package.json
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:processor Finished running one processor for package.json
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:project Writing to disk and caching processed file package.json
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:project File package.json changes saved, store ts: 1529316052437, change ts: 1529316562106
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:project Stopping process pool
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:project Running postprocessor
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:postprocessor New TypeScript language service is required
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:postprocessor TypeScript postprocessor will be removed because in 1 project files none were found by patterns: **/*.ts?(x)
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:project Postprocessor execution finished
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:project Postprocessor is removed as requested by itself
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:project Test run started; run priority: 3
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:project Running all tests
​​​​​[Info]​​​​​ Can't determine tests to run for the change, re-running all tests.
​​​​​[Info]​​​​​ To prevent the full test run when can not determine tests to run, use `loose: true` configuration option.
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:project Test task priority upgraded to full run
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:workers Starting test run, priority: 3
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #xauup]
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #xauup]
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #xauup]
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:workers [worker #0, session #xauup] Running tests in sandbox
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:workers Sandbox (active) [xauup] error: TypeError: Cannot read property 'replace' of undefined
​​[Error] Runtime error: TypeError: Cannot read property 'replace' of undefined​​
​​[Error]     at emitTwo (events.js:126:13)​​
​​[Error]     at WebSocket.emit (events.js:214:7)​​
​​[Error]     at afterWrite (_stream_writable.js:464:3)​​
​​[Error]     at onwrite (_stream_writable.js:455:7)​​
​​[Error]     at InflateRaw.afterTransform (_stream_transform.js:90:3)​​
​​[Error]     at Zlib.callback (zlib.js:515:5)​​
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:22 GMT wallaby:workers Failed to map the stack to user code, entry message: TypeError: Cannot read property 'replace' of undefined, stack: TypeError: Cannot read property 'replace' of undefined
​​​​​[Info]​​​​​     at configure (/Users/taras/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.86/wallaby/runners/node/jest@0.4.3/initializer.js:14:18736)
​​​​​[Info]​​​​​     at Object.configure (/Users/taras/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.86/wallaby/runners/node/jest@0.4.3/initializer.js:14:22137)
​​​​​[Info]​​​​​     at eval (eval at module.exports (/Users/taras/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.86/wallaby/runners/node/bootstrap.js:14:44), <anonymous>:2:29)
​​​​​[Info]​​​​​     at eval (eval at module.exports (/Users/taras/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.86/wallaby/runners/node/bootstrap.js:14:44), <anonymous>:3:8)
​​​​​[Info]​​​​​     at module.exports (/Users/taras/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.86/wallaby/runners/node/bootstrap.js:14:44)
​​​​​[Info]​​​​​     at b.in:run (/Users/taras/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.86/wallaby/server.js:16:22952)
​​​​​[Info]​​​​​     at WebSocket.<anonymous> (/Users/taras/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.86/wallaby/server.js:16:21744)
​​​​​[Info]​​​​​     
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:23 GMT wallaby:workers [xauup] Run 0 test(s), skipped 0 test(s)
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:23 GMT wallaby:workers [xauup] Sandbox is responsive, closing it
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:23 GMT wallaby:project Test run finished
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:23 GMT wallaby:project Processed console.log entries
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:23 GMT wallaby:project Processed loading sequences
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:23 GMT wallaby:project Processed executed tests
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:23 GMT wallaby:project Processed code coverage
​​​​​[Info]​​​​​ Mon, 18 Jun 2018 10:09:23 GMT wallaby:project Test run result processed and sent to IDE
```

Feels like problem is configuration file location itself.

**Comment by trsdln** [comment]
Changed paths a bit:

```
{
    debug: false,
    testFramework: 'jest',
    files: [
      '../imports/**/*.js',
      '../.jest/config.js',
      '../.jest/mongo-environment.js',
      '../.jest/common.js',
      { pattern: '../imports/**/*.spec.js', ignore: true },
    ],
    tests: ['../imports/**/*.spec.js'],
    compilers: {
      '../imports/**/*.js'
```

and got this error:

```
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.603
​​​​​[Info]​​​​​ Wallaby App (realtime reports) is available at: http://localhost:51245
​​[Error] No files with tests found, check your tests list patterns.​​
​​​​​[Info]​​​​​ Can't determine tests to run for the change, re-running all tests.
​​​​​[Info]​​​​​ To prevent the full test run when can not determine tests to run, use `loose: true` configuration option.
​​[Error] Runtime error: Failed to initialize wallaby jest.​​
​​[Error] Error: Cannot find Jest test runner​​
​​[Error]     at Module._compile (module.js:652:30)​​
​​[Error]     at Object.Module._extensions..js (module.js:663:10)​​
​​[Error]     at Module.load (module.js:565:32)​​
​​[Error]     at tryModuleLoad (module.js:505:12)​​
​​[Error]     at Function.Module._load (module.js:497:3)​​
​​[Error]     at Module.require (module.js:596:17)​​
​​[Error]     at require (internal/module.js:11:18)​​
​​[Error]     at Module._compile (module.js:652:30)​​
​​[Error]     at Object.Module._extensions..js (module.js:663:10)​​
​​[Error]     at Module.load (module.js:565:32)​​
​​[Error]     at tryModuleLoad (module.js:505:12)​​
​​[Error]     at Function.Module._load (module.js:497:3)​​
​​[Error]     at Function.Module.runMain (module.js:693:10)​​
​​[Error]     at startup (bootstrap_node.js:191:16)​​
​​[Error]     at bootstrap_node.js:612:3​​
```

Should paths at `files` and `tests` be relative to wallaby-config or project's root?

**Comment by ArtemGovorov** [comment]
> Should paths at `files` and `tests` be relative to wallaby-config or project's root?

Yes, wallaby config must be in the project's root and paths in `files` and `tests` should be relative to the project's root. So it looks like if you move the config to the root, and use correct paths, it should work for you.

**Comment by ArtemGovorov** [comment]
Eg. wallaby config file must be in the same folder as your `package.json` file and `node_modules` folder.
