### ISSUE TITLE
`java.lang.reflect.InvocationTargetException` thrown on wallaby exit

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#1758]
```
IntelliJ IDEA 2018.2 EAP (Ultimate Edition)
Build #IU-182.3684.2, built on July 10, 2018
IntelliJ IDEA EAP User
Expiration date: August 9, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
```

_idea.log_

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$5.invoke(ProcessHandler.java:223)
	at com.sun.proxy.$Proxy22.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler$4.run(ProcessHandler.java:180)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:256)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:161)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:157)
	at com.intellij.execution.process.KillableProcessHandler.notifyProcessTerminated(KillableProcessHandler.java:134)
	at com.intellij.execution.process.BaseProcessHandler.onOSProcessTerminated(BaseProcessHandler.java:61)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:113)
	at com.intellij.execution.process.BaseOSProcessHandler$2$1.consume(BaseOSProcessHandler.java:120)
	at com.intellij.execution.process.BaseOSProcessHandler$2$1.consume(BaseOSProcessHandler.java:105)
	at com.intellij.execution.process.ProcessWaitFor$1$1.run(ProcessWaitFor.java:65)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.execution.process.ProcessWaitFor$1.run(ProcessWaitFor.java:45)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@5b04ee64
Current thread: Thread[node,4,Idea Thread Group] 419908867
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1453805737
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1113)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1102)
	at com.intellij.ui.mac.touchbar.TouchBarsManager.onUpdateEditorHeader(TouchBarsManager.java:263)
	at com.intellij.openapi.editor.impl.EditorImpl.setHeaderComponent(EditorImpl.java:1817)
	at com.wallaby.javascript.J.a(Unknown Source)
	at com.wallaby.javascript.J.fun(Unknown Source)
	at com.intellij.util.containers.ContainerUtilRt.map2List(ContainerUtilRt.java:393)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1899)
	at com.wallaby.javascript.w.dispose(Unknown Source)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:182)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeUnregistered(ObjectTree.java:194)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:147)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:129)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.wallaby.javascript.WallabyController.l(Unknown Source)
	at com.wallaby.javascript.aq.processTerminated(Unknown Source)
	... 22 more
```

**Comment by ArtemGovorov** [comment]
Thanks for providing the error stack.
The issue is fixed and the fix is published in Wallaby IntelliJ plugin v1.0.116.
