### ISSUE TITLE
​​[Error] TypeError: fs.readlink is not a function​​ ​​[Error]     at forEachBail.withIndex (C:\Users\gwk736\Gitlab\web-client\node_modules\enhanced-resolve\lib\SymlinkPlugin.js:26:8)​​

### ISSUE THREAD

**Issue by pearljamik** [wallabyjs/public#1778]
### Issue description or question
I am not able to run tests with webpack, node and angular 6 typescript. I get the following error when running tests:

```
[Error] TypeError: fs.readlink is not a function​​
​​[Error]     at forEachBail.withIndex (C:\Users\gwk736\Gitlab\web-client\node_modules\enhanced-resolve\lib\SymlinkPlugin.js:26:8)​​
​​[Error]     at Function.forEachBailWithIndex [as withIndex] (C:\Users\gwk736\Gitlab\web-client\node_modules\enhanced-resolve\lib\forEachBail.js:44:3)​​
​​[Error]     at resolver.getHook.tapAsync (C:\Users\gwk736\Gitlab\web-client\node_modules\enhanced-resolve\lib\SymlinkPlugin.js:25:16)​​
​​[Error]     at _fn1 (eval at create (C:\Users\gwk736\Gitlab\web-client\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:25:1)​​
​​[Error]     at resolver.getHook.tapAsync (C:\Users\gwk736\Gitlab\web-client\node_modules\enhanced-resolve\lib\AliasFieldPlugin.js:26:12)​​
​​[Error]     at _fn0 (eval at create (C:\Users\gwk736\Gitlab\web-client\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:16:1)​​
​​[Error]     at resolver.getHook.tapAsync (C:\Users\gwk736\Gitlab\web-client\node_modules\enhanced-resolve\lib\AliasPlugin.js:53:11)​​
​​[Error]     at AsyncSeriesBailHook.eval [as callAsync] (eval at create (C:\Users\gwk736\Gitlab\web-client\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)​​
​​[Error]     at AsyncSeriesBailHook.lazyCompileHook [as _callAsync] (C:\Users\gwk736\Gitlab\web-client\node_modules\tapable\lib\Hook.js:35:21)​​
​​[Error]     at Resolver.doResolve (C:\Users\gwk736\Gitlab\web-client\node_modules\enhanced-resolve\lib\Resolver.js:235:16)​​
​​[Error]     at resolver.getHook.tapAsync (C:\Users\gwk736\Gitlab\web-client\node_modules\enhanced-resolve\lib\TryNextPlugin.js:17:13)​​
​​[Error]     at AsyncSeriesBailHook.eval [as callAsync] (eval at create (C:\Users\gwk736\Gitlab\web-client\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)​​
​​[Error]     at AsyncSeriesBailHook.lazyCompileHook [as _callAsync] (C:\Users\gwk736\Gitlab\web-client\node_modules\tapable\lib\Hook.js:35:21)​​
​​[Error]     at Resolver.doResolve (C:\Users\gwk736\Gitlab\web-client\node_modules\enhanced-resolve\lib\Resolver.js:235:16)​​
​​[Error]     at resolver.getHook.tapAsync (C:\Users\gwk736\Gitlab\web-client\node_modules\enhanced-resolve\lib\FileKindPlugin.js:19:13)​​
​​[Error]     at AsyncSeriesBailHook.eval [as callAsync] (eval at create (C:\Users\gwk736\Gitlab\web-client\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)​​
​​[Error]     at AsyncSeriesBailHook.lazyCompileHook [as _callAsync] (C:\Users\gwk736\Gitlab\web-client\node_modules\tapable\lib\Hook.js:35:21)​​
​​[Error]     at Resolver.doResolve (C:\Users\gwk736\Gitlab\web-client\node_modules\enhanced-resolve\lib\Resolver.js:235:16)​​
​​[Error]     at DescriptionFileUtils.loadDescriptionFile (C:\Users\gwk736\Gitlab\web-client\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:38:14)​​
​​[Error]     at forEachBail (C:\Users\gwk736\Gitlab\web-client\node_modules\enhanced-resolve\lib\DescriptionFileUtils.js:51:12)​​
​​[Error]     at args (C:\Users\gwk736\Gitlab\web-client\node_modules\enhanced-resolve\lib\forEachBail.js:30:14)​​
​​[Error]     at onJson (C:\Users\gwk736\Gitlab\web-client\node_modules\enhanced-resolve\lib\DescriptionFileUtils.js:42:5)​​
​​[Error]     at resolver.fileSystem.readFile (C:\Users\gwk736\Gitlab\web-client\node_modules\enhanced-resolve\lib\DescriptionFileUtils.js:30:6)​​
​​[Error]     at C:\Users\gwk736\Gitlab\web-client\node_modules\graceful-fs\graceful-fs.js:78:16​​
​​[Error]     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)​​
```

### Wallaby.js configuration file

```javascript
'use strict';

let helpers = require('./e2e/src/helpers/root');
let webpack = require('webpack');
let wallabyWebpack = require('wallaby-webpack');

const ENV = 'test';
const path = require('path');
const DefinePlugin = require('webpack/lib/DefinePlugin');

let compilerOptions = Object.assign(
  {}, require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

  compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    bail: false,
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', {loader: 'less-loader', options: {paths: [__dirname]}}]},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png|svg)$/, loader: 'url-loader?limit=128000'}
      ],
    },
    node: {
      global: true,
      fs: 'empty',
      net: 'empty',
      crypto: 'empty',
      module: false,
      clearImmediate: false,
      setImmediate: false
    },
    plugins: [
      new DefinePlugin({
        'ENV': JSON.stringify(ENV),
        'HMR': false,
        'PLATFORM_SPECIFIC_VARIABLES': {},
        'globalConfig': {
          platform: {},
          metadata: {
            APP_NAME: '"AWARE"'
          }
        },
        'process.env': {
          'ENV': JSON.stringify(ENV),
          'NODE_ENV': JSON.stringify(ENV),
          'HMR': false
        }
      }),
      new webpack.NormalModuleReplacementPlugin(
        /\.(gif|png|json)$/, 'node-noop'
      ),
      new webpack.ProvidePlugin({
        i18next: 'i18next',
        i18nextBrowserLanguageDetector: 'i18next-browser-languagedetector',
        simulant: 'simulant'
      })
    ],

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src')
      ],
   
    }
  });
  return {
    reportUnhandledPromises: false,
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true},
      {pattern: 'src/locales/**/*.*', load: false},
      {pattern: 'src/assets/**/*.*', load: false},
      {pattern: 'node_modules/dragula/dist/dragula.min.css', load: false},
      {pattern: 'node_modules/flatpickr/dist/themes/dark.css', load: false},
      {pattern: 'node_modules/@commandcentral/cobalt-table/dist/styles/cobalt-main-theme.css', load: false},
      {pattern: 'node_modules/@commandcentral/cobalt-basic-controls/dist/styles/cobalt-main-theme.css', load: false},
      {pattern: 'node_modules/@commandcentral/golden-layout/src/css/goldenlayout-base.css', load: false}
    ],
    tests: [
      {pattern: 'src/app/**/*spec.ts', load: false}
    ],
    workers: {
      initial: 2,
      regular: 2
    },
    testFramework: 'jasmine',
    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },
    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/assets/icon/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },
    env: {
      kind: 'chrome'
    },
    postprocessor: webpackPostprocessor,
    setup: function () {
      window.__moduleBundler.loadTests();
    },
    debug: false
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.25.0
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Looks like you are using an outdated version of the `wallaby-webpack` package. Please update the package version to the latest (v3.9.10), and it should work for you.
