### ISSUE TITLE
wallabyjs fails to install/setup

### ISSUE THREAD

**Issue by cyberhck** [wallabyjs/public#1793]
### Issue description or question
I get the following error message when I try to start wallaby (it starts to download node, then I get this error:

Can not copy extract files to /home/cyberkiller/.PhpStorm2018.2/system/wallaby/node_v8.5.0/node.

So I try doing `chmod 777 -R ~/.PhpStorm2018.2` and try again, it still fails, so I click cancel, it does create a file called "node" which is nodejs because after chmod +x node, I can run it and I get a node shell. But after cancel, I get another error related to phantomjs, no matter how much I try I get stuck here:
![image](https://user-images.githubusercontent.com/3640284/44128918-c890f250-a06f-11e8-8272-28504c729e70.png)

Once I cancel that, it tries to download something else and tries to start, but it says process finished with exit code 0.

### Wallaby.js configuration file

```javascript
module.exports = function () {
  return {
    files: [
      // There are not only .ts files, also .tsx, .png used.
      // also config/main.js is used from one the files
      {pattern: 'translations/*.json'},
      {pattern: '__mocks__/*', ignore: true},
      {pattern: 'config/main.js'},
      {pattern: 'src/**/*.ts*'},
      {pattern: 'src/**/*.png'},
      {pattern: 'src/**/*.test.ts*', ignore: true}
    ],
    tests: [
      {pattern: 'src/**/*.test.ts*'},
      {pattern: 'src/**/*.snap', ignore: true}
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    testFramework: 'jest'
  };
};

```

### Code editor or IDE name and version

WebStorm 2018.2.2 EAP
PhpStorm 2018.2.1 same problem in both?

### OS name and version

Linux

WallabyJS version: 1.0.104

**Comment by smcenlly** [comment]
We haven't been able to duplicate this issue on our Linux desktop environments. In addition to checking the permissions on the directory, could you please check that the ownership of  _/home/cyberkiller/.PhpStorm2018.2/system/wallaby/_ is set to your user?

If the directory owner is set correctly, please troubleshoot by following our [offline installation guide](https://wallabyjs.com/docs/intro/troubleshooting.html#offline-installation).

**Comment by cyberhck** [comment]
Thanks for quick response,

yes, owner is me: here's snippet:

`drwxrwxr-x  6 cyberkiller cyberkiller 4096 Aug 15 10:00 wallaby`
I'll give offline installation a try, but I'm not sure if that'll be easy enough, because I'm using quite old version of wallaby. I'm trying: https://s3.amazonaws.com/wallaby-downloads/wallaby-v1.0.104.zip will let you know.

I'm not sure if more info will be helpful, let me know if you need any more info, also I'm using jetbrains' toolbox app to install/update webstorm, I guess that won't be a problem?

**Comment by smcenlly** [comment]
We don't expect that updating through the toolbox app will cause a problem. 

Internally we log additional information to the idea.log file when an error occurs. Could you please send us a copy of the "idea.log" file? The location should be available from the “Help - Show Log” menu of your code editor.

**Comment by cyberhck** [comment]
[idea.log](https://github.com/wallabyjs/public/files/2289153/idea.log)
here's a copy of my log file, I do get an error and it says java.lang.NoClassDefFoundError, maybe the plugin isn't packaged properly, I did see this before when I was working with plugin development, not sure what happened then.

**Comment by cyberhck** [comment]
```log
java.lang.NoClassDefFoundError: com/intellij/util/io/tar/TarInputStream
	at com.wallaby.javascript.WallabyDependencies$d.a(Unknown Source)
	at com.wallaby.javascript.WallabyDependencies$d.a(Unknown Source)
	at com.wallaby.javascript.WallabyDependencies$d.b(Unknown Source)
	at com.wallaby.javascript.WallabyDependencies$d.a(Unknown Source)
	at com.wallaby.javascript.aI.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:247)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:574)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.io.tar.TarInputStream PluginClassLoader[wallaby.js, 1.0.104] com.intellij.ide.plugins.cl.PluginClassLoader@23548b6f
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more
```
is the error I get right on IDE

**Comment by cyberhck** [comment]
I tried installing offline, but when I started wallaby, it tried to install phantomjs again, I guess I screwed it up or something.

**Comment by cyberhck** [comment]
ahh, sorry, that was stupid of me, I'll see if I can update :)
