### ISSUE TITLE
Wallaby can't require <rootDir>/jest.config.js with Vue default configuration

### ISSUE THREAD

**Issue by bbugh** [wallabyjs/public#1802]
### Issue description or question

I have worked around the issue locally but thought I'd report it in case the example configuration is incorrect.

I moved my jest configuration out of `package.json` into a root directory `jest.config.js`. Wallaby doesn't seem to be able to find it based on the [default configuration suggested here](https://wallabyjs.com/docs/integration/vue.html). If I tell the require statement to use the `wallaby.localProjectDir` instead of a relative path, it works correctly. Here is the error:

```
​​​​​0 failing tests, 0 passing​​​​​
​​​​​​​​​​
​​Error: Cannot find module './jest.config'​​
​​    at Function.Module._resolveFilename (module.js:547:15)​​
​​    at Function.Module._load (module.js:474:25)​​
​​    at Module.require (module.js:596:17)​​
​​    at require (internal/module.js:11:18)​​
​​    at emitTwo (events.js:126:13)​​
​​    at WebSocket.emit (events.js:214:7)​​
​​    at afterWrite (_stream_writable.js:464:3)​​
​​    at onwrite (_stream_writable.js:455:7)​​
​​    at InflateRaw.afterTransform (_stream_transform.js:90:3)​​
​​    at Zlib.callback (zlib.js:515:5)​​
```

The jest file is there, though:

```
project/root/dir» ls *.config.js
jest.config.js    wallaby.config.js
```

Strangely, this worked fine with `package.json` in the same folder.

### Wallaby.js configuration file

The relevant config file

```javascript
    setup (wallaby) {
      // ERROR: recommended settings from vue config page
      const jestConfig = require('./package').jest || require('./jest.config')
      // SUCCESS: using wallaby's absolute path
      const jestConfig = require('./package').jest || require(wallaby.localProjectDir + 'jest.config')
      delete jestConfig.transform['^.+\\.tsx?$']
      wallaby.testFramework.configure(jestConfig)
    },
```

<details>
<summary>The entire config file</summary>

```javascript
process.env.BABEL_ENV = 'test'

module.exports = wallaby => {
  return {
    files: [
      'app/javascript/**/*',
      '!app/javascript/**/*.spec.js',
      '!app/javascript/**/*.spec.ts',
      'package.json',
      'tsconfig.json'
    ],

    tests: ['app/javascript/**/*.spec.js', 'app/javascript/**/*.spec.ts'],

    env: {
      type: 'node',
      runner: 'node'
    },

    preprocessors: {
      '**/*.js?(x)': file =>
        require('babel-core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          babelrc: true
        })
    },

    setup (wallaby) {
      const jestConfig = require('./package').jest || require(wallaby.localProjectDir + 'jest.config')
      delete jestConfig.transform['^.+\\.tsx?$']
      wallaby.testFramework.configure(jestConfig)
    },

    testFramework: 'jest',

    debug: true
  }
}
```
</details>

<details>
<summary>Jest config, in case that matters</summary>

```javascript
module.exports = {
  roots: [
    'app/javascript/'
  ],
  moduleDirectories: [
    'node_modules',
    'app/javascript'
  ],
  moduleFileExtensions: [
    'js',
    'json',
    'ts',
    'vue'
  ],
  testRegex: '(/test/.*|\\.(test|spec))\\.(ts|tsx|js)$',
  transform: {
    '^.+\\.js$': '<rootDir>/node_modules/babel-jest',
    '^.+\\.tsx?$': 'ts-jest',
    '.*\\.(vue)$': '<rootDir>/node_modules/vue-jest'
  },
  transformIgnorePatterns: [
    '/node_modules/(?!lodash-es)'
  ],
  moduleNameMapper: {
    '^#/(.*)$': '<rootDir>/app/javascript/$1'
  },
  snapshotSerializers: [
    '<rootDir>/node_modules/jest-serializer-vue'
  ],
  setupTestFrameworkScriptFile: 'given2/setup',
  setupFiles: [
    'jest-plugin-context/setup'
  ]
}
```
</details>

### Code editor or IDE name and version

Visual Studio Code 1.26.1

### OS name and version

OSX 10.12.6

**Comment by ArtemGovorov** [comment]
The reason why it doesn't work is that the `jest.config.js` is missign in your `files` list (`package.json` in the list, so it works with it). In the samples with recommended settings from [vue config page](https://wallabyjs.com/docs/integration/vue.html) that contain this line:

```js
const jestConfig = require('./package').jest || require('./jest.config')
```

`jest.config.js` file is present in the `files` list:

```js
files: ['src/**/*', 'jest.config.js', 'package.json'],
```

So the solution in your case is:

```diff
    files: [
      'app/javascript/**/*',
      '!app/javascript/**/*.spec.js',
      '!app/javascript/**/*.spec.ts',
      'package.json',
+     'jest.config.js'
      'tsconfig.json'
    ],
```

after the change you may switch from the workaround with `wallaby.localProjectDir` to `require('./jest.config')`.

**Comment by bbugh** [comment]
CRAP! I am so bad at this. Thanks again @ArtemGovorov.
