### ISSUE TITLE
​​Error: Cannot find Jest test runner​​

### ISSUE THREAD

**Issue by celador** [wallabyjs/public#1808]
### Issue description or question

Jest runs fine, Wallaby does not.  Using  "jest": "23.4.1" and  "jest-cli": "23.4.1",

extension version: wallabyjs.wallaby-vscode-1.0.92

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: ['src/**/*.js?(x)', '!src/**/__tests__/*.js'],

    tests: ['src/**/__tests__/*.js'],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: {
      type: 'jest',
      path: 'node_modules/.bin/jest'
    },
    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['es2015', 'react'],
        plugins: ['transform-class-properties']
      })
    }
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.26.1

### OS name and version

OSX - Mojave beta

**Comment by celador** [comment]
Installing it globally fixed it, but that doesn't seem to be the right way to solve this problem...

**Comment by smcenlly** [comment]
> Jest runs fine, Wallaby does not.

Can you please provide more detail of what you mean? Is wallaby running at all? What error(s) are you receiving?

Can you also please provide your package.json configuration

Do you get the same error if you open our [working sample](https://github.com/wallabyjs/wallaby-jest-snapshots) of a jest configuration?

**Comment by smcenlly** [comment]
Please also try removing the path from the testFramework property of your config so that it looks like this:

```javascript
testFramework: {
      type: 'jest'
    },
```

**Comment by deshiknaves** [comment]
Exact same issue with jest version `v23.5.0`. Doesn't work with your example either.

```
/* eslint global-require: "off" */
module.exports = function configure() {
  return {
    files: [
      'src/**',
      '!src/**/*.spec.js',
    ],
    tests: [
      'src/**/*.spec.js',
    ],
    testFramework: 'jest',
    env: {
      type: 'node',
      runner: 'node',
    },
    setup(wallaby) {
      const jestConfig = require('./package.json').jest;

      wallaby.testFramework.configure(jestConfig);
    },
    debug: true,
  };
};
```

```
​​Failed to initialize wallaby jest.​​
​​Error: Cannot find Jest test runner​​
​​    at Module._compile (module.js:652:30)​​
​​    at Object.Module._extensions..js (module.js:663:10)​​
​​    at Module.load (module.js:565:32)​​
​​    at tryModuleLoad (module.js:505:12)​​
​​    at Function.Module._load (module.js:497:3)​​
​​    at Module.require (module.js:596:17)​​
​​    at require (internal/module.js:11:18)​​
​​    at Module._compile (module.js:652:30)​​
​​    at Object.Module._extensions..js (module.js:663:10)​​
​​    at Module.load (module.js:565:32)​​
​​    at tryModuleLoad (module.js:505:12)​​
​​    at Function.Module._load (module.js:497:3)​​
​​    at Function.Module.runMain (module.js:693:10)​​
​​    at startup (bootstrap_node.js:191:16)​​
​​    at bootstrap_node.js:612:3​​
```

**Comment by deshiknaves** [comment]
It's got to do with an older version of Wallaby. I just renewed and updated. All good now.
