### ISSUE TITLE
tsconfig-paths-webpack-plugin support

### ISSUE THREAD

**Issue by AustinMatherne** [wallabyjs/public#1811]
### Issue description or question
I'm trying to get [tsconfig-paths](https://github.com/dividab/tsconfig-paths) working with webpack using the [tsconfig-paths-webpack-plugin](https://github.com/dividab/tsconfig-paths-webpack-plugin).

Wallaby is throwing
```
​​[Error] TypeError: filesystem.readJson is not a function​​
​​[Error]     at /Users/amather/repos/workshops/wallaby-nx-workspace/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:136:20​​
​​[Error]     at findFirstExistingPath (/Users/amather/repos/workshops/wallaby-nx-workspace/node_modules/tsconfig-paths/lib/match-path-async.js:81:9)​​
​​[Error]     at /Users/amather/repos/workshops/wallaby-nx-workspace/node_modules/tsconfig-paths/lib/match-path-async.js:77:20​​
​​[Error]     at filesystem.stat (/Users/amather/repos/workshops/wallaby-nx-workspace/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:151:17)​​
​​[Error]     at /Users/amather/repos/workshops/wallaby-nx-workspace/node_modules/graceful-fs/polyfills.js:284:29​​
​​[Error]     at FSReqWrap.oncomplete (fs.js:152:21)​​
```
It appears to be because [`WallabyInputFileSystem.js`](https://github.com/jeffling/wallaby-webpack/blob/065e6cf4dd2f37054b327297c9bf30a0276fa3fd/lib/WallabyInputFileSystem.js) doesn't implement `readJson`.

[Here's a repo](https://github.com/AustinMatherne/wallaby-nx-workspace) which replicates the issue.

### Wallaby.js configuration file

```javascript
'use strict';

const path = require('path');
const wallabyWebpack = require('wallaby-webpack');
const glob = require('glob');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
const compilerOptions = Object.assign(
  { useStandardDefaults: true },
  require('./tsconfig.json').compilerOptions
);

module.exports = wallaby => {
  const webpackPostprocessor = wallabyWebpack({
    entryPatterns: ['wallabyTest.js', '@(apps|libs)/**/*.spec.js'],
    module: {
      rules: [
        { test: /\.css$/, loader: 'raw-loader' },
        { test: /\.html$/, loader: 'raw-loader' },
        {
          test: /\.ts$/,
          loader: '@ngtools/webpack',
          include: /node_modules/,
          query: { tsConfigPath: 'tsconfig.json' }
        },
        {
          test: /\.js$/,
          loader: 'angular2-template-loader',
          exclude: /node_modules/
        },
        {
          test: /\.scss$|\.sass$/,
          loaders: [
            'raw-loader',
            {
              loader: 'sass-loader',
              options: {
                includePaths: glob.sync('./apps/*/src/assets/styles')
              }
            }
          ]
        },
        { test: /\.(jpg|png|svg)$/, loader: 'url-loader?limit=128000' }
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    },
    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'apps'),
        path.join(wallaby.projectCacheDir, 'libs'),
        'node_modules'
      ],
      plugins: [new TsconfigPathsPlugin()]
    }
  });

  return {
    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },
    env: {
      kind: 'chrome'
    },
    filesWithNoCoverageCalculated: [
      'wallabyTest.ts',
      '**/mocks/**',
      '**/test/**',
      '**/*.module.ts',
      'apps/*/src/*',
      'apps/*/src/environments/*'
    ],
    files: [
      { pattern: 'wallabyTest.ts', load: false },
      {
        pattern: '@(apps|libs)/**/*.@(css|html|json|sass|scss|svg|ts)',
        load: false
      },
      { pattern: '@(apps|libs)/**/*.d.ts', ignore: true },
      { pattern: '@(apps|libs)/**/*.spec.ts', ignore: true },
      { pattern: '@(apps|libs)/**/*-e2e/**', ignore: true }
    ],
    tests: [
      { pattern: '@(apps|libs)/**/*.spec.ts', load: false },
      { pattern: '@(apps|libs)/**/*-e2e/**', ignore: true }
    ],
    postprocessor: webpackPostprocessor,
    setup: () => {
      window.__moduleBundler.loadTests();
    },
    testFramework: 'jasmine'
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.26.1

### OS name and version

OSX v10.13.6

**Comment by AustinMatherne** [comment]
Thank you! It works perfectly!

You may want to update the docs with this approach for folks using typescript with webpack.
