### ISSUE TITLE
setup wallaby for angular multiproject using jest with nrwl builder

### ISSUE THREAD

**Issue by pverhelle** [wallabyjs/public#1816]
### Issue description or question

we have a multi project/library angular project setup with jest that uses a nrwl builder

if we run ng test (see angular.json and jest.config.js ) manually, all the test pass
if we try to insert the same settings from the main jest config file into the wallaby.js to let wallaby run in the background, only basic unit test succeed. all our (for now still autogenerated) component/service tests fail

i believe the reason to be the following error 
```
Zone is needed for the async() test helper but could not be found. Please make sure that your environment includes zone.js/dist/zone.js
```

but the wallaby log gives us multiple other error like the following at the end of the log
```
​​[Error] Test without test file id, most likely the test did not run, OR the test/test body is in the file that is not in the `tests` list in the configuration file { testFileIdCanNotBeDetermined: 'should create the app',​​
​​[Error]   id: 100001,​​
​​[Error]   log: ​​
​​[Error]    [ { message: 'Error: Failed: "Zone is needed for the async() test helper but could not be found. Please make sure that your environment includes zone.js/dist/zone.js"',​​
​​[Error]        stack: [Array],​​
​​[Error]        context: [Object] },​​
​​[Error]      { message: 'Error: Failed: "Zone is needed for the async() test helper but could not be found. Please make sure that your environment includes zone.js/dist/zone.js"',​​
​​[Error]        stack: [Array],​​
​​[Error]        context: [Object] } ],​​
​​[Error]   filesInvolved: [] }​​
```
and multiple variations of this
```
console.log: FAIL libs/dal/src/lib/bundles/bundles.service.spec.js
​​​​​[Info]​​​​​ console.log:   ● BundlesService › should be created
​​​​​[Info]​​​​​     TypeError: Cannot read property 'getComponentFromError' of null
​​​​​[Info]​​​​​       at TestBed.Object.<anonymous>.TestBed._initIfNeeded (../../packages/core/testing/src/test_bed.ts:351:46)
​​​​​[Info]​​​​​       at TestBed.Object.<anonymous>.TestBed.execute (../../packages/core/testing/src/test_bed.ts:442:10)
​​​​​[Info]​​​​​       at Object.<anonymous> (../../packages/core/testing/src/test_bed.ts:627:40)
​​​​​[Info]​​​​​       at Object.call (../../../Users/pverhelle/.vscode-insiders/extensions/wallabyjs.wallaby-vscode-1.0.93/wallaby/runners/node/jest@0.4.3/jasmine2Initializer.js:14:1786)
```

i have tried the solution given in https://github.com/wallabyjs/public/issues/1768 by adding wallabyTest.ts but it won't work

tried adding multiple import combinations to this test but get the following errors:

when importing 
```    
import 'core-js/es7/reflect';
import 'zone.js/dist/zone-testing';
```

error
```
ReferenceError: Zone is not defined
```

when importing 
```    
import 'core-js/es7/reflect';
import 'zone.js/dist/zone';
```

error
```
Error: Your test suite must contain at least one test.​
```

when importing 
```    
import 'core-js/es7/reflect';
import 'zone.js/dist/zone';
import 'zone.js/dist/zone-testing';
```

error
```
Cannot read property 'prototype' of undefined
```

### Wallaby.js configuration file

```javascript
module.exports = function() {
  return {
    files: [
      'jest.config.js',
      'apps/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!apps/**/*.spec.ts',
      'libs/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!libs/**/*.spec.ts'
    ],

    tests: ['apps/**/*.spec.ts', 'libs/**/*.spec.ts', 'wallabyTest.ts'],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    setup: function(wallaby) {
      var jestConfig = require('./jest.config').jest;
      wallaby.testFramework.configure(jestConfig);
    }
  };
};


```

### jest.js configuration file

```javascript
module.exports = {
  testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
  transform: {
    '^.+\\.(ts|js|html)$': 'jest-preset-angular/preprocessor.js'
  },
  resolver: '@nrwl/builders/plugins/jest/resolver',
  moduleFileExtensions: ['ts', 'js', 'html'],
  collectCoverage: true,
  coverageReporters: ['html']
};
```
### jest.js configuration file for subprojects (they all have the same format which points to the main config file)

```javascript
module.exports = {
  name: 'pages-bundles',
  preset: '../../../jest.config.js',
  coverageDirectory: '../../../coverage/libs/pages/bundles'
};

```

### angular.json configuration file

```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "",
  "projects": {
    "polpo-classroom-web": {
      "root": "apps/polpo-classroom-web/",
      "sourceRoot": "apps/polpo-classroom-web/src",
      "projectType": "application",
      "prefix": "campus",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/apps/polpo-classroom-web",
            "index": "apps/polpo-classroom-web/src/index.html",
            "main": "apps/polpo-classroom-web/src/main.ts",
            "polyfills": "apps/polpo-classroom-web/src/polyfills.ts",
            "tsConfig": "apps/polpo-classroom-web/tsconfig.app.json",
            "assets": [
              "apps/polpo-classroom-web/src/favicon.ico",
              "apps/polpo-classroom-web/src/assets"
            ],
            "styles": [
              "apps/polpo-classroom-web/src/styles.css"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "apps/polpo-classroom-web/src/environments/environment.ts",
                  "with": "apps/polpo-classroom-web/src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "polpo-classroom-web:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "polpo-classroom-web:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "polpo-classroom-web:build"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "apps/polpo-classroom-web/tsconfig.app.json",
              "apps/polpo-classroom-web/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/builders:jest",
          "options": {
            "jestConfig": "apps/polpo-classroom-web/jest.config.js",
            "tsConfig": "apps/polpo-classroom-web/tsconfig.spec.json",
            "setupFile": "apps/polpo-classroom-web/src/test-setup.ts"
          }
        }
      }
    },
    "polpo-classroom-web-e2e": {
      "root": "apps/polpo-classroom-web-e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "apps/polpo-classroom-web-e2e/protractor.conf.js",
            "devServerTarget": "polpo-classroom-web:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "polpo-classroom-web:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "apps/polpo-classroom-web-e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "pages-bundles": {
      "root": "libs/pages/bundles",
      "sourceRoot": "libs/pages/bundles/src",
      "projectType": "library",
      "prefix": "campus",
      "architect": {
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "libs/pages/bundles/tsconfig.lib.json",
              "libs/pages/bundles/tsconfig.spec.json",
              "libs/pages/bundles/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/builders:jest",
          "options": {
            "jestConfig": "libs/pages/bundles/jest.config.js",
            "tsConfig": "libs/pages/bundles/tsconfig.spec.json",
            "setupFile": "libs/pages/bundles/src/test-setup.ts"
          }
        }
      }
    },
    "ui": {
      "root": "libs/ui",
      "sourceRoot": "libs/ui/src",
      "projectType": "library",
      "prefix": "campus",
      "architect": {
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "libs/ui/tsconfig.lib.json",
              "libs/ui/tsconfig.spec.json",
              "libs/ui/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/builders:jest",
          "options": {
            "jestConfig": "libs/ui/jest.config.js",
            "tsConfig": "libs/ui/tsconfig.spec.json",
            "setupFile": "libs/ui/src/test-setup.ts"
          }
        }
      }
    },
    "dal": {
      "root": "libs/dal",
      "sourceRoot": "libs/dal/src",
      "projectType": "library",
      "prefix": "campus",
      "architect": {
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "libs/dal/tsconfig.lib.json",
              "libs/dal/tsconfig.spec.json",
              "libs/dal/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/builders:jest",
          "options": {
            "jestConfig": "libs/dal/jest.config.js",
            "tsConfig": "libs/dal/tsconfig.spec.json",
            "setupFile": "libs/dal/src/test-setup.ts"
          }
        }
      }
    }
  },
  "cli": {
    "warnings": {
      "typescriptMismatch": false,
      "versionMismatch": false
    },
    "defaultCollection": "@nrwl/schematics"
  },
  "defaultProject": "polpo-classroom-web"
}


```

### Code editor or IDE name and version

Visual Studio Code v1.26.1
Visual Studio Code v1.27.0 insiders

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Could you please set up and share a sample GitHub repo demonstrating the issue? Please add a simple failing test (that fails in Wallaby, but is passing when running Jest CLI in the sample project). We are happy to take a look and help with the config.

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. I have sent you the pull request with Wallaby config to make it work: https://github.com/diekeure/wallaby.setup.example/pull/1.

I have taken the config from our docs at https://wallabyjs.com/docs/integration/angular.html#jest and added one of your setup files (that `@nrwl/builders:jest` in your angular config is using to configure Jest).

**Comment by pverhelle** [comment]
works like a charm, thank you!
