### ISSUE TITLE
ReferenceError: $_$wp is not defined​​

### ISSUE THREAD

**Issue by coniel** [wallabyjs/public#1839]
### Issue description or question
I've tried the solutions posted on similar issues but nothing has worked. Here is a stripped down version of my project: https://github.com/coniel/wallaby-debug

I use yarn workspaces with an app under /packages/apps created using create-react-app from which wallaby pulls the setupTests.js file.

This setup used to work fine. I started getting this error after downgrading from react-scripts@next down to v1 because I was having some issues with it. I've been trying all sorts of stuff all day (including deleting all node_modules folder and yarn.lock) but haven't had any luck so far.

Full error:
```
ReferenceError: $_$wp is not defined​​
​​    at Object.<anonymous> (./packages/apps/ibguides/src/setupTests.js:2:1)​​
​​    at Runtime._execModule (/Users/oscarconiel1/Sites/wallaby-debug/node_modules/react-scripts/node_modules/jest-runtime/build/index.js:513:13)​​
​​    at Runtime.requireModule (/Users/oscarconiel1/Sites/wallaby-debug/node_modules/react-scripts/node_modules/jest-runtime/build/index.js:329:14)​​
​​    at /Users/oscarconiel1/Sites/wallaby-debug/node_modules/jest-config/node_modules/jest-jasmine2/build/index.js:112:15​​
​​    at Generator.next (<anonymous>)​​
​​    at step (/Users/oscarconiel1/Sites/wallaby-debug/node_modules/jest-config/node_modules/jest-jasmine2/build/index.js:170:30)​​
​​    at /Users/oscarconiel1/Sites/wallaby-debug/node_modules/jest-config/node_modules/jest-jasmine2/build/index.js:189:14​​
​​    at new Promise (<anonymous>)​​
​​    at /Users/oscarconiel1/Sites/wallaby-debug/node_modules/jest-config/node_modules/jest-jasmine2/build/index.js:167:12​​
​​    at jasmine2 (/Users/oscarconiel1/Sites/wallaby-debug/node_modules/jest-config/node_modules/jest-jasmine2/build/index.js:138:17)​​
​​    at runTest (/Users/oscarconiel1/Sites/wallaby-debug/node_modules/react-scripts/node_modules/jest-cli/build/runTest.js:85:10)​​
​​    at promise.then (/Users/oscarconiel1/Sites/wallaby-debug/node_modules/react-scripts/node_modules/jest-cli/build/TestRunner.js:197:14)​​
​​    at <anonymous>​​
​​    at process._tickCallback (internal/process/next_tick.js:189:7)​​
```

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  // Babel, jest-cli and some other modules may be located under
  // react-scripts/node_modules, so need to let node.js know about it
  var path = require('path');
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, 'node_modules') +
    path.delimiter +
    path.join(__dirname, 'node_modules/react-scripts/node_modules');
  require('module').Module._initPaths();

  return {
    debug: true,
    files: [
      'packages/**/*.+(js|jsx|graphql|gql|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!packages/**/*.test.+(js|jsx|ts|tsx)',
      '!packages/**/*.stories.+(js|jsx|ts|tsx)',
      '!packages/**/node_modules/**',
    ],

    tests: [
      'packages/**/*.test.+(js|jsx|ts|tsx)',
      '!packages/**/node_modules/**',
    ],

    env: {
      type: 'node',
      runner: 'node',
    },

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['react-app'],
      }),
      '**/*.ts?(x)': wallaby.compilers.typeScript({
        module: 'commonjs',
        jsx: 'React',
      }),
    },

    setup: wallaby => {
      const path = require('path');
      const paths = require('react-scripts/config/paths');
      const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(
        p => require.resolve('react-scripts/' + p),
        path.resolve('./packages/apps/ibguides'),
        [path.resolve('./packages/apps/ibguides')],
      );

      delete jestConfig.transform['^.+\\.(js|jsx)$'];
      delete jestConfig.transform['^.+\\.(ts|tsx)$'];
      delete jestConfig.testEnvironment;

      jestConfig.setupTestFrameworkScriptFile = path.resolve('./packages/apps/ibguides/src/setupTests.js');

      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest',
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.27.2

### OS name and version

OSX 10.13.6

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. Wallaby was confused by multiple Jest versions installed in your project: you have one from `react-scripts`, but also have the [latest Jest version](https://github.com/coniel/wallaby-debug/blob/master/package.json#L44) installed in the project's root. 

The issue is fixed and the fix is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by coniel** [comment]
Thanks a lot! I can confirm that the issue is now fixed (and that I need to clean up my dependencies).

However, I'm now having another issue. I'm getting an `Unexpected token` error in some files but not others. For example, in the repo I linked (note: I've made a new commit to the repo adding a missing dependency), the tests in `packages/components/SesondaryActionButton` run just fine. However, `packages/components/InfoButton` (which imports SecondaryActionButton) throws the unexpected token error:
```
​​/Users/oscarconiel1/Sites/wallaby-debug/packages/components/InfoButton/InfoButton.js: Unexpected token (7:2)​​
​​[0m [90m  5 | [39m​​
​​ [90m  6 | [39m[36mconst[39m [33mInfoButton[39m [33m=[39m props [33m=>[39m (​​
​​[31m[1m>[22m[39m[90m  7 | [39m  [33m<[39m[33mSecondaryActionButton[39m {[33m...[39mprops}[33m>[39m​​
​​ [90m    | [39m  [31m[1m^[22m[39m​​
​​ [90m  8 | [39m    [33m<[39m[33mInfoIcon[39m [33m/[39m[33m>[39m​​
​​ [90m  9 | [39m  [33m<[39m[33m/[39m[33mSecondaryActionButton[39m[33m>[39m​​
​​ [90m 10 | [39m)[33m;[39m[0m​​
​​/Users/oscarconiel1/Sites/wallaby-debug/packages/components/SecondaryActionButton/SecondaryActionButton.js: Unexpected token (25:63)​​
​​[0m [90m 23 | [39m})[33m;[39m​​
​​ [90m 24 | [39m​​
​​[31m[1m>[22m[39m[90m 25 | [39m[36mconst[39m [33mSecondaryActionButton[39m [33m=[39m ({ classes[33m,[39m className[33m,[39m children[33m,[39m [33m...[39mprops }) [33m=>[39m (​​
​​ [90m    | [39m                                                               [31m[1m^[22m[39m​​
​​ [90m 26 | [39m  [33m<[39m[33mIconButton[39m {[33m...[39mprops} className[33m=[39m{classNames(classes[33m.[39mroot[33m,[39m className)}[33m>[39m​​
​​ [90m 27 | [39m    {[33mReact[39m[33m.[39mcloneElement(children[33m,[39m {​​
​​ [90m 28 | [39m      style[33m:[39m [33mICON_STYLE[39m[33m,[39m[0m​​
```

**Comment by ArtemGovorov** [comment]
@coniel Could you please update your sample repo https://github.com/coniel/wallaby-debug with the demo of the issue? Happy to have a look.

**Comment by coniel** [comment]
Updated. You'll need to run `yarn` from the project root as this added a new workspace.

**Comment by ArtemGovorov** [comment]
Thanks! Have [sent you the PR](https://github.com/coniel/wallaby-debug/pull/1), also updated the code at https://github.com/wallabyjs/public/issues/1374#issuecomment-342021786.

**Comment by coniel** [comment]
Thank you so much! Everything works now!

I was actually very close with my attempt. I had changed the line to:
`acc[`^${require(packageJsonPath).name}(.*)`] = `${path.dirname(packageJsonPath)}/$1`;`
instead of
`acc[`^${require(packageJsonPath).name}(.*)`] = `${path.dirname(packageJsonPath)}$1`;`
i.e. I mistakenly added `/$1` instead of `$1` at the end.

Thanks again, I really appreciate the help! I will keep the debug repo up in case anyone comes across this issue.
