### ISSUE TITLE
Question: Setup of Wallaby in VS Code on Linux

### ISSUE THREAD

**Issue by daKmoR** [wallabyjs/public#1842]
So I am trying to setup Wallaby in VS Code on Linux using the env Chrome.

To be certain I tried this repo https://github.com/wallabyjs/calculator-sample  and it works fine on my windows machine but I can not get it to work on my Debian.

If I remove the "env: chrome" it works fine but I need to use chrome because of features which are not supported for PhantomJs.

I made a symlink for google-chrome to chrome in /usr/bin but that did not help. I think It finds chrome but something with the connection does not work out?

I am pretty lost and I am not sure what to test next... any hints?

wallaby version
```
$ cat ~/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.96/package.json 
{
	"name": "wallaby-vscode",
	"displayName": "Wallaby.js",
	"description": "Integrated Continuous Testing Tool for JavaScript.",
	"version": "1.0.96", 
```

system info
```
$ code --version
1.27.2
f46c4c469d6e6d8c46f268d1553c5dc4b475840f
x64
$ node --version
v8.9.1
$ npm --version
5.5.1
$ lsb_release -da
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.2 (stretch)
Release:	9.2
Codename:	stretch
```

Wallaby Log:
```
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:53 GMT wallaby:project Wallaby config: /home/xwing/new/calculator-sample/wallaby.js
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:53 GMT wallaby:fs File added: style/calculator.css
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:53 GMT wallaby:fs File added: lib/jquery.js
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.617
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:fs File added: src/calculatorModel.js
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:fs File added: src/calculatorView.js
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:fs File added: test/calculatorSpec.js
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:fs File added: test/helper/template.js
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:project File cache: /home/xwing/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.96/projects/973ae252a5fe9204
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:uiService Listening port 51235
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:workers Parallelism for initial run: 2, for regular run: 2
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:workers Starting run worker instance #0
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:workers Starting run worker instance #1
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:workers Web server is listening at 38529
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:project Stopping process pool
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:project File cache is up-to-date, starting full test run
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:project Running postprocessor
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:postprocessor New TypeScript language service is required
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:postprocessor TypeScript postprocessor will be removed because in 6 project files none were found by patterns: **/*.ts?(x)
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:project Postprocessor execution finished
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:project Postprocessor is removed as requested by itself
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:project Test run started; run priority: 3
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:project Running all tests
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:workers Starting test run, priority: 3
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:29:54 GMT wallaby:chromeRunner Starting sandbox [worker #0, session #1f2j9]
​​[Error] Error: connect ECONNREFUSED 127.0.0.1:38479​​
​​[Error]     at Object._errnoException (util.js:1024:11)​​
​​[Error]     at _exceptionWithHostPort (util.js:1046:20)​​
​​[Error]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)​​
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:30:19 GMT wallaby:workers Started run worker instance (immediate) #0
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:30:19 GMT wallaby:workers Started run worker instance (immediate) #1
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:30:19 GMT wallaby:chromeRunner Preparing sandbox [worker #0, session #1f2j9]
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:30:19 GMT wallaby:browserRunner Total files to load in sandbox: 6
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:30:19 GMT wallaby:browserRunner Sandbox is generated [worker #0, session #1f2j9]: http://localhost:38529/wallaby_sandbox0.html
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:30:19 GMT wallaby:chromeRunner Prepared sandbox [worker #0, session #1f2j9]
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:30:19 GMT wallaby:workers [worker #0, session #1f2j9] Running tests in sandbox
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:30:19 GMT wallaby:chromeRunner Failed to evaluate code on Chrome Tab: Cannot read property 'Runtime' of undefined
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:30:20 GMT wallaby:workers [1f2j9] Sandbox is not responsive, recycling worker instance
​​​​​[Info]​​​​​ Thu, 27 Sep 2018 17:30:20 GMT wallaby:project Test run finished
```

**Comment by ArtemGovorov** [comment]
Looks like there's some (network?) issue with connecting to Chrome in your environment. Could you please try if Chrome via Electron works for you https://wallabyjs.com/docs/integration/electron.html?

**Comment by smcenlly** [comment]
Thanks for letting us know how you got this working and for the puppeteer reference. 

We did some further reading and on Linux environments, Chromium requires User Namespaces for sandboxing ([read more here](https://chromium.googlesource.com/chromium/src/+/lkgr/docs/linux_sandboxing.md)). For Debian, this feature is not enabled by default, to use user namespaces, you need to ensure that `sysctl` has `kernel.unprivileged_userns_clone=1` flag set. 

We will set these as default params for Linux environments in the next release of Wallaby.
