### ISSUE TITLE
Connection refused in Linux with google chrome headless.

### ISSUE THREAD

**Issue by JasonAsmk** [wallabyjs/public#1847]
Wallaby gets an ECONNREFUSED from chrome. Both `google-chrome` and `chromium` are in Path. Specifying a direct path to the chrome executable yields the same error. Tried passing `--headless --disable-gpu` as well. Raising this issue as you might have more insight on this.
Edit: followed the steps here [https://wallabyjs.com/docs/integration/chrome.html](https://wallabyjs.com/docs/integration/chrome.html)

```
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.617
​​​​​[Info]​​​​​ Wallaby App (realtime reports) is available at: http://localhost:51245
​​[Error] which: no chromium-browser in (/home/jasonasmk/.nvm/versions/node/v8.11.1/bin:/home/jasonasmk/Android/Sdk/platform-tools:/home/jasonasmk/bin:/home/jasonasmk/.local/bin:/usr/local/bin:/home/jasonasmk/.cargo/bin:/home/jasonasmk/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/bin)​​
​​[Error] Error: connect ECONNREFUSED 127.0.0.1:40657​​
​​[Error]     at Object._errnoException (util.js:1022:11)​​
​​[Error]     at _exceptionWithHostPort (util.js:1044:20)​​
​​[Error]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)​​
```

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/wallaby-test.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      { test: /\.css$/, loader: 'raw-loader' },
      { test: /\.html$/, loader: 'raw-loader' },
      { test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/ },
      { test: /\.json$/, loader: 'json-loader' },
      { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
      { test: /\.less$/, loaders: ['raw-loader', 'less-loader'] },
      { test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader'] },
      { test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000' }
    ]
  }
});

var compilerOptions = require('./src/tsconfig.spec.json').compilerOptions;

module.exports = function (wallaby) {

  return {
    files: [
      { pattern: 'package.json', load: false },
      { pattern: 'src/**/*.ts', load: false },
      { pattern: 'src/**/*.d.ts', ignore: true },
      { pattern: 'src/**/*.css', load: false },
      { pattern: 'src/**/*.less', load: false },
      { pattern: 'src/**/*.sass', load: false },
      { pattern: 'src/**/*.scss', load: false },
      { pattern: 'src/**/*.html', load: false },
      { pattern: 'src/**/*spec.ts', ignore: true },
    ],

    filesWithNoCoverageCalculated: ['src/**/*mock.ts'],

    tests: [
      { pattern: 'src/**/*spec.ts', load: false }
    ],

    testFramework: 'jasmine',

    env: {
      kind: 'chrome'
    },

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    postprocessor: webpackPostprocessor,

    lowCoverageThreshold: 75, // 70%

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: false,

    reportConsoleErrorAsError: true,

    workers: {
      initial: 6,
      regular: 2
    },

    delays: {
      run: 1000
    }
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.24.

### OS name and version
Linux 4.18.5-arch1-1-ARCH

### Chrome version
Version 69.0.3497.100 (Official Build) (64-bit)
(AUR package)

**Comment by smcenlly** [comment]
We saw the same issue last week in [Issue #1842](https://github.com/wallabyjs/public/issues/1842). Chrome needs `sysctl` needs to have `kernel.unprivileged_userns_clone=1` to run its sandbox for Linux environments. You can disable sandboxing for your tests by adding two additional arguments, `--no-sandbox` and `--disable-setuid-sandbox`. These will be made as defaults for Linux environments in our next Wallaby release. In the meantime, you can add these to your configuration.
