### ISSUE TITLE
Works in Visual Studio, but not in Visual Studio Code, related to node_modules? 

### ISSUE THREAD

**Issue by chauey** [wallabyjs/public#1873]
### Issue description or question
I have a project that works in Visual Studio (VS), but not Visual Studio Code (VSCode). It seems to prepare things in node_modules while the one in VS does not. Error being:

> [Error] ​​Postprocessor run failure: Failed to parse node_modules/@nativescript/schematics/src/add-ns/_ns-files/__sourceDir__/app/__entryModuleName@dasherize__.module__nsext__.js, SyntaxError: Unexpected token (12:27)​​
> [Error] ​​    at _combinedTickCallback (internal/process/next_tick.js:132:7)​​
> [Error] ​​    at process._tickCallback (internal/process/next_tick.js:181:9)​​

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require("wallaby-webpack");
var path = require("path");

var compilerOptions = Object.assign(
  require("./tsconfig.json").compilerOptions,
  require("./src/tsconfig.spec.json").compilerOptions);

compilerOptions.module = "CommonJs";

module.exports = function(wallaby) {

  const webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      "src/**/*spec.js",
      "src/wallabyTest.js"
    ],

    module: {
      rules: [
        { test: /\.css$/, loader: ["raw-loader"] },
        { test: /\.html$/, loader: "raw-loader" },
        {
          test: /\.ts$/,
          loader: "@ngtools/webpack",
          include: /node_modules/,
          query: { tsConfigPath: "tsconfig.json" }
        },
        { test: /\.js$/, loader: "angular2-template-loader", exclude: /node_modules/ },
        { test: /\.json$/, loader: "json-loader" },
        { test: /\.styl$/, loaders: ["raw-loader", "stylus-loader"] },
        { test: /\.less$/, loaders: ["raw-loader", "less-loader"] },
        { test: /\.scss$|\.sass$/, loaders: ["raw-loader", "sass-loader"] },
        { test: /\.(jpg|png)$/, loader: "url-loader?limit=128000" }
      ]
    },

    resolve: {
      extensions: [".js", ".ts"],
      modules: [
        path.join(wallaby.projectCacheDir, "src/app"),
        path.join(wallaby.projectCacheDir, "src"),
        "node_modules"
      ],
      alias: {
        '@projectName': path.join(wallaby.projectCacheDir, "src/app"),
        '@projectNamecommon': path.join(wallaby.projectCacheDir, "src/app/common/"),
        '@projectNamenative': path.join(wallaby.projectCacheDir, "src/app/native/"),
        '@projectNameweb': path.join(wallaby.projectCacheDir, "src/app/web/"),
        '@module': path.join(wallaby.projectCacheDir, "src/app/web/modules"),
        '@layout': path.join(wallaby.projectCacheDir, "src/app/web/layout"),
        '@service': path.join(wallaby.projectCacheDir, "src/app/web/services"),
        '@component': path.join(wallaby.projectCacheDir, "src/app/web/components"),
        '@mock': path.join(wallaby.projectCacheDir, "src/test/mocks")
      }
    },
    node: {
      fs: "empty",
      net: "empty",
      tls: "empty",
      dns: "empty"
    }
  });

  return {
    files: [
      { pattern: "**/*.+(ts|css|less|scss|sass|styl|html|json|svg)", load: false },
      { pattern: "**/*.d.ts", ignore: true },
      { pattern: "**/*spec.ts", ignore: true },
    { pattern: './node_modules/jquery/dist/jquery.min.js', instrument: false }
    ],

    tests: [
      { pattern: "src/**/*spec.ts", load: false },
      { pattern: "src/**/*e2e-spec.ts", ignore: true }
    ],

    testFramework: "jasmine",

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function(app, express) {
      const path = require("path");
      app.use("/favicon.ico", express.static(path.join(__dirname, "src/favicon.ico")));
      app.use("/assets", express.static(path.join(__dirname, "src/assets")));
    },

    env: {
      kind: "electron"
    },

    postprocessor: webpackPostprocessor,

    setup: function() {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.28.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Looks like your `files` patterns are including `node_modules`, so Wallaby/Webpack is trying to process them. In VS node_modules (or any files that are not part of the solution), are ignored, however in VS Code, everything that is defined in your `files` patterns is processed.

Adjusting your `files` patterns to not include node module that should help:

```diff
files: [
-      { pattern: "**/*.+(ts|css|less|scss|sass|styl|html|json|svg)", load: false },
-      { pattern: "**/*.d.ts", ignore: true },
-      { pattern: "**/*spec.ts", ignore: true },
+      { pattern: "src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)", load: false },
+      { pattern: "src/**/*.d.ts", ignore: true },
+      { pattern: "src/**/*spec.ts", ignore: true },
```

**Comment by chauey** [comment]
Seems to be working better now, Thanks! Curious, does the VS one just know to ignore it?

**Comment by ArtemGovorov** [comment]
VS simply ignores anything that is not a part of the solution/project, on the other hand VS Code doesn't have solution/project files, so everything is included by default.
