### ISSUE TITLE
'_jasmineAdapter' of undefined

### ISSUE THREAD

**Issue by baronTommy** [wallabyjs/public#1904]
Is there a mistake in setting? 😂

### Issue description or question
```
TypeError: Cannot read property '_jasmineAdapter' of undefined
    at Runtime._execModule (/Users/tommy/node_modules/jest-runtime/build/index.js:694:13)
    at Runtime.requireModule (/Users/tommy/node_modules/jest-runtime/build/index.js:376:14)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:112:15
    at Generator.next (<anonymous>)
    at step (/Users/tommy/node_modules/jest-jasmine2/build/index.js:170:30)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:189:14
    at new Promise (<anonymous>)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:167:12


TypeError: Cannot read property '_jasmineAdapter' of undefined
    at Runtime._execModule (/Users/tommy/node_modules/jest-runtime/build/index.js:694:13)
    at Runtime.requireModule (/Users/tommy/node_modules/jest-runtime/build/index.js:376:14)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:112:15
    at Generator.next (<anonymous>)
    at step (/Users/tommy/node_modules/jest-jasmine2/build/index.js:170:30)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:189:14
    at new Promise (<anonymous>)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:167:12


TypeError: Cannot read property '_jasmineAdapter' of undefined
    at Runtime._execModule (/Users/tommy/node_modules/jest-runtime/build/index.js:694:13)
    at Runtime.requireModule (/Users/tommy/node_modules/jest-runtime/build/index.js:376:14)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:112:15
    at Generator.next (<anonymous>)
    at step (/Users/tommy/node_modules/jest-jasmine2/build/index.js:170:30)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:189:14
    at new Promise (<anonymous>)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:167:12


wallaby.js started
core v1.0.633
Wallaby App (realtime reports) is available at: http://localhost:51245
Runtime error: TypeError: Cannot read property '_jasmineAdapter' of undefined
    at Runtime._execModule (/Users/tommy/node_modules/jest-runtime/build/index.js:694:13)
    at Runtime.requireModule (/Users/tommy/node_modules/jest-runtime/build/index.js:376:14)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:112:15
    at Generator.next (<anonymous>)
    at step (/Users/tommy/node_modules/jest-jasmine2/build/index.js:170:30)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:189:14
    at new Promise (<anonymous>)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:167:12
console.log: FAIL src/lib/func1.test.js

console.log:   ● Test suite failed to run

    TypeError: Cannot read property '_jasmineAdapter' of undefined
      at Object.<anonymous> (../../../Users/tommy/Library/Caches/WebStorm2018.2/wallaby/wallaby/runners/node/jest@0.4.3/jasmine2Initializer.js:14:2524)
      at Runtime.d._wallabyReplaced.c.requireModule (../../../Users/tommy/Library/Caches/WebStorm2018.2/wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:22691)


##########################

Runtime error: TypeError: Cannot read property '_jasmineAdapter' of undefined
    at Runtime._execModule (/Users/tommy/node_modules/jest-runtime/build/index.js:694:13)
    at Runtime.requireModule (/Users/tommy/node_modules/jest-runtime/build/index.js:376:14)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:112:15
    at Generator.next (<anonymous>)
    at step (/Users/tommy/node_modules/jest-jasmine2/build/index.js:170:30)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:189:14
    at new Promise (<anonymous>)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:167:12
console.log: FAIL src/lib/standard.test.js

console.log:   ● Test suite failed to run

    TypeError: Cannot read property '_jasmineAdapter' of undefined
      at Object.<anonymous> (../../../Users/tommy/Library/Caches/WebStorm2018.2/wallaby/wallaby/runners/node/jest@0.4.3/jasmine2Initializer.js:14:2524)
      at Runtime.d._wallabyReplaced.c.requireModule (../../../Users/tommy/Library/Caches/WebStorm2018.2/wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:22691)


Runtime error: TypeError: Cannot read property '_jasmineAdapter' of undefined
    at Runtime._execModule (/Users/tommy/node_modules/jest-runtime/build/index.js:694:13)
    at Runtime.requireModule (/Users/tommy/node_modules/jest-runtime/build/index.js:376:14)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:112:15
    at Generator.next (<anonymous>)
    at step (/Users/tommy/node_modules/jest-jasmine2/build/index.js:170:30)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:189:14
    at new Promise (<anonymous>)
    at /Users/tommy/node_modules/jest-jasmine2/build/index.js:167:12
console.log: FAIL src/lib/func.test.js

console.log:   ● Test suite failed to run

    TypeError: Cannot read property '_jasmineAdapter' of undefined
      at Object.<anonymous> (../../../Users/tommy/Library/Caches/WebStorm2018.2/wallaby/wallaby/runners/node/jest@0.4.3/jasmine2Initializer.js:14:2524)
      at Runtime.d._wallabyReplaced.c.requireModule (../../../Users/tommy/Library/Caches/WebStorm2018.2/wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:22691)

```

### Wallaby.js configuration file
my repository
https://github.com/baronTommy/type-script-pg2

package.json
```json
{
  "scripts": {
    "build": "webpack --mode=development",
    "fmt": "tslint --fix --project . 'src/**/*.ts'",
    "test": "jest",
    "_prettier": "prettier --write 'src/**'",
    "_test": "jest --coverage --notify --notifyMode=failure"
  },
  "name": "typescript-pg3",
  "version": "1.0.0",
  "author": "Tommy <16768208+baronTommy@users.noreply.github.com>",
  "license": "MIT",
  "devDependencies": {
    "@types/jest": "^23.3.9",
    "jest": "^23.6.0",
    "prettier": "^1.14.3",
    "ts-jest": "^23.10.4",
    "ts-loader": "^5.3.0",
    "tslint": "^5.11.0",
    "tslint-config-prettier": "^1.15.0",
    "tslint-plugin-prettier": "^2.0.1",
    "typescript": "^3.1.6",
    "webpack": "^4.24.0",
    "webpack-cli": "^3.1.2"
  }
}
```

wallaby.js
```js
module.exports = function (wallaby) {
    return {
        files: [
            'src/**/*.ts',
            '!src/**/*.test.ts'
        ],

        tests: [
            'src/**/*.test.ts',
        ],

        env: {
            type: 'node',
            runner: 'node'
        },
        testFramework: 'jest',

        // setup: wallaby => {
        //     const jestConfig = require('./jest.config.js');
        //     wallaby.testFramework.configure(jestConfig);
        // },

    };
};
```

### Code editor or IDE name and version
```
WebStorm 2018.2.5
Build #WS-182.4892.25, built on October 18, 2018
Licensed to Yuichi Imatomi
Subscription is active until January 16, 2019
JRE: 1.8.0_152-release-1248-b19 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

### OS name and version
OSX
10.13.6

**Comment by ArtemGovorov** [comment]
Thanks for providing the details!
Looks like a conflicting version of Jest is installed in the `/Users/tommy/node_modules` folder. Please delete the `/Users/tommy/node_modules` folder and it should work for you.

**Comment by baronTommy** [comment]
Thank you for your quick answer
It worked
