### ISSUE TITLE
Wallaby server.js eats all of the resources and stops responding almost immediately after start

### ISSUE THREAD

**Issue by ayatkevich** [wallabyjs/public#1909]
### Issue description or question

Hi, first of all thanks for Wallaby! I'm a license owner for VS code, I love wallaby, and would really love to keep using it!

Right now wallaby server.js eats all of the resources and stops responding almost immediately after start.
So I run manually Wallaby.js Start in VS Code. Then it runs all of my tests, shows that everything passes without any issue. But after that, even without me changing anything in the code, it starts using all of my resources all of a sudden and stops responding at all.

![image](https://user-images.githubusercontent.com/139799/48200532-80b52e80-e370-11e8-9e3f-8566fac6175b.png)

Also creates entries in snapshot that should not be there:

```
exports[`check typings 1`] = `"Cannot find type definition file for 'jest'."`;

exports[`check typings 2`] = `"Cannot find type definition file for 'node'."`;

exports[`check typings 3`] = `"File 'src/typings-tests/jsql.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'."`;

exports[`check typings: src/postgremote/jsql.ts 1`] = `"Cannot find module 'sqlstring'."`;
```

I see that there are first three items 

As you can see here the latest one is for src/postgremote/jsql.ts when this file just should not be evaluated by my `typings.sepc.ts` because it looks for files in `./src/typings-tests`

```bash
 ~ > ✔ > ps aux | grep wallaby
ayatkev+ 25335 96.8  0.7 946772 123456 ?       Rl   16:02   4:34 node --harmony /home/ayatkevich/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.99/wallaby/server.js extended-core-ws --projectCachePath=/home/ayatkevich/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.99/projects/e57f4d126c33ae61 --configPath=/home/ayatkevich/dev/bibimbap/wallaby.js --lkp=/home/ayatkevich/.vscode/extensions/.wlck --client=VSCode --phantomjs=/home/ayatkevich/.vscode/phantomjs_v2.1.1/phantomjs --port=36345
```

There is a repo in which I work: https://github.com/ayatkevich/bibimbap

### Wallaby.js configuration file

```javascript
module.exports = function() {
  return {
    files: [
      'tsconfig.json',
      'src/**/*.ts',
      '!src/**/*.spec.ts'
    ],

    tests: ['src/**/*.spec.ts'],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.28.2

### OS name and version

Linux

**Comment by smcenlly** [comment]
I've created a [pull request](https://github.com/ayatkevich/bibimbap/pull/1) to fix the jest snapshot issue. We've been unable to duplicate the high process usage on Windows and MacOS.

Can you please add `debug: 'true'` as an additional property in your wallaby.js configuration file and send us a full copy of your `Wallaby.js Console` `Output` window. This should allow us to further debug/diagnose why you have high CPU usage.

Can you also please try and isolate your tests and see which tests are causing the high CPU usage? With the TypeScript program that you're generating, it's possible that this is interfering with Wallaby's internal processing.

**Comment by ayatkevich** [comment]
@smcenlly thank you very much for the pull request!

I've tried to narrow down the issue with switched on debug for wallaby and it seems like the issue with my `typings.spec.ts`. There is a wallaby log.

First two lines are about I'm changing s/`test,skip`/`test`. After that it seems like not being able to respond and it eats all of my process resources. Yet fortunately when I change s/`test`/`test.skip` back, it starts working as usual.

```
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:54:37 GMT wallaby:fs File changed: src/typings.spec.ts
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:54:37 GMT wallaby:fs No changes detected for src/typings.spec.ts
​​[Error] Some long running code has been detected: one of your tests is taking more than 5000ms to execute.​​
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:44 GMT wallaby:fs File changed in editor: src/typings.spec.ts
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:44 GMT wallaby:workers Cancelling test run, cancel requester priority: 2, current run priority: 2
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:44 GMT wallaby:project Test run was cancelled
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:fs File changed: src/typings.spec.ts
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:fs No changes detected for src/typings.spec.ts
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:workers [xhe1g] Sandbox is not responsive, recycling worker instance
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project Test run cancelled, re-queueing run data
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project Test run finished
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project Test run data re-queued
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project File src/typings.spec.ts changes are patches only: true
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project Returning previously cached file [3] from memory
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project Preparing to process src/typings.spec.ts
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project No compilers configured for src/typings.spec.ts
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project File src/typings.spec.ts is not instrumented by core
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project No preprocessors configured for src/typings.spec.ts
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project Writing to disk and caching processed file src/typings.spec.ts
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project File src/typings.spec.ts changes saved, store ts: 1541749953015, change ts: 1541750145718
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project Running postprocessor
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project Preparing to process src/typings.spec.js
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project Processing compiled src/typings.spec.js
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project Instrumenting src/typings.spec.js, via process pool: false
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:processor No preprocessors found for src/typings.spec.js
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project Writing to disk and caching processed file src/typings.spec.js
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project Postprocessor execution finished
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:project Test run started; run priority: 2
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:workers Starting test run, priority: 2
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #rnj0y]
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #rnj0y]
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:45 GMT wallaby:workers Starting run worker instance #0
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:46 GMT wallaby:workers Started run worker instance (delayed) #0
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:46 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #rnj0y]
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:46 GMT wallaby:workers [worker #0, session #rnj0y] Running tests in sandbox
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:47 GMT wallaby:workers [rnj0y] Loaded unknown number of test(s)
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:47 GMT wallaby:fs File changed: src/__snapshots__/typings.spec.ts.snap
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:47 GMT wallaby:fs No changes detected for src/__snapshots__/typings.spec.ts.snap
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:47 GMT wallaby:workers [rnj0y] Run 0 test(s), skipped 1 test(s)
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:47 GMT wallaby:workers [rnj0y] Sandbox is responsive, closing it
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:47 GMT wallaby:project Test run finished
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:47 GMT wallaby:project Processed console.log entries
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:47 GMT wallaby:project Processed loading sequences
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:47 GMT wallaby:project Processed executed tests
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:47 GMT wallaby:project Processed code coverage
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 07:55:47 GMT wallaby:project Test run result processed and sent to IDE
```

**Comment by ayatkevich** [comment]
I've just tried to edit my `index.spec.ts`, just added /*?*/, it displayed correctly, but then went wild again with this output in console:

```
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:31 GMT wallaby:project Running postprocessor
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:31 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project Preparing to process src/postgremote/index.spec.js
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project Processing compiled src/postgremote/index.spec.js
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project Instrumenting src/postgremote/index.spec.js, via process pool: false
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project Error: Failed to parse src/postgremote/index.spec.js, SyntaxError: Unexpected token (277:16)
​​​​​[Info]​​​​​     at process.internalTickCallback (internal/process/next_tick.js:70:11)
​​​​​[Info]​​​​​     at /home/ayatkevich/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.99/wallaby/server.js:18:14057
​​​​​[Info]​​​​​     at _rejected (/home/ayatkevich/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.99/wallaby/node_modules/q/q.js:864:24)
​​​​​[Info]​​​​​     at /home/ayatkevich/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.99/wallaby/node_modules/q/q.js:890:30
​​​​​[Info]​​​​​     at Promise.when (/home/ayatkevich/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.99/wallaby/node_modules/q/q.js:1142:31)
​​​​​[Info]​​​​​     at Promise.promise.promiseDispatch (/home/ayatkevich/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.99/wallaby/node_modules/q/q.js:808:41)
​​​​​[Info]​​​​​     at /home/ayatkevich/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.99/wallaby/node_modules/q/q.js:624:44
​​​​​[Info]​​​​​     at runSingle (/home/ayatkevich/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.99/wallaby/node_modules/q/q.js:137:13)
​​​​​[Info]​​​​​     at flush (/home/ayatkevich/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.99/wallaby/node_modules/q/q.js:125:13)
​​​​​[Info]​​​​​     at process.internalTickCallback (internal/process/next_tick.js:70:11)
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project Test run finished
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project Test run data re-queued
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:fs File changed in editor: src/postgremote/index.spec.ts
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project File src/postgremote/index.spec.ts changes are patches only: true
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project Returning previously cached file [6] from memory
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project Preparing to process src/postgremote/index.spec.ts
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project No compilers configured for src/postgremote/index.spec.ts
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project File src/postgremote/index.spec.ts is not instrumented by core
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project No preprocessors configured for src/postgremote/index.spec.ts
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project Writing to disk and caching processed file src/postgremote/index.spec.ts
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project File src/postgremote/index.spec.ts changes saved, store ts: 1541749927719, change ts: 1541750492810
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project Running postprocessor
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project Preparing to process src/postgremote/index.spec.js
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project Processing compiled src/postgremote/index.spec.js
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:32 GMT wallaby:project Instrumenting src/postgremote/index.spec.js, via process pool: false
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:33 GMT wallaby:project Detected single test [should work with different schemas] change
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:33 GMT wallaby:processor No preprocessors found for src/postgremote/index.spec.js
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:33 GMT wallaby:project Writing to disk and caching processed file src/postgremote/index.spec.js
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:33 GMT wallaby:project Postprocessor execution finished
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:33 GMT wallaby:project Test run started; run priority: 2
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:33 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:33 GMT wallaby:workers Starting test run, priority: 2
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:33 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #xpte3]
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:33 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #xpte3]
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:33 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #xpte3]
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:01:33 GMT wallaby:workers [worker #0, session #xpte3] Running tests in sandbox
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:02:00 GMT wallaby:fs File changed: src/postgremote/index.spec.ts
​​​​​[Info]​​​​​ Fri, 09 Nov 2018 08:02:00 GMT wallaby:fs No changes detected for src/postgremote/index.spec.ts
```

And this in test output
```
[Error] ​​Postprocessor run failure: Failed to parse src/postgremote/index.spec.js, SyntaxError: Unexpected token (277:16)​​
[Error] ​​    at process.internalTickCallback (internal/process/next_tick.js:70:11)​​
```

Now it does not respond and keeps eating all of my resources.

**Comment by ayatkevich** [comment]
So, I've managed to get it working continuously only with unit tests in my `jsql.spec.ts`, skipping everything else.

I've already used wallaby with some heavy tests previously, but I did it with default test framework for node. I'm curious now could it be because of jest?

**Comment by smcenlly** [comment]
> just added /?/

Might just be a typo in your response, but please note that Wallaby's live comments require you to use `//?` or `/*?*/`. If you've somehow inserted a bad glob expression in your code, this may be the cause of your high CPU. I've tried using `/?/` but it doesn't result in high CPU.

> with this output in console

Is this a full copy of the console output when the CPU spiked again, or just a snippet?

--

Could you also please run Jest in `watch` mode and see if you get similar issues/behavior to when you run Wallaby?

To date, we've been testing with Windows and MacOS. Can you please tell us your exact version of Linux and we'll try to replicate your problem using the same OS dist that you're using.

**Comment by ayatkevich** [comment]
@smcenlly yeah, that was a typo, I've been using `/*?*/`

These were all snippets.

I'm using:

```
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

**Comment by zaripych** [comment]
I seem to have similar issue. After some time one of the `node` processes wents into 100% CPU usage and then there is no coverage highlights from Wallaby.js. Tests stop running as well. Here is my config:

```
module.exports = function(wallaby) {
  return {
    files: [
      //
      { pattern: '.env', instrument: false },
      { pattern: '.env.local', instrument: false },
      'package.json',
      'tsconfig.json',
      'setupTests.ts',
      'config/**/*.js',
      'src/**/*.*',
      //
      '!src/**/*.d.ts',
      'src/**/__tests__/**/*.{js,jsx}',
      'src/**/?(*.)(spec|test).{js,jsx}',
      '!src/**/__tests__/**/*.{ts,tsx}',
      '!src/**/?(*.)(spec|test).{ts,tsx}',
    ],

    tests: [
      //
      'src/**/__tests__/**/*.{js,jsx,ts,tsx}',
      'src/**/*.(spec|test).{js,jsx,ts,tsx}',
    ],

    env: {
      type: 'node',
      runner: 'node',
    },

    testFramework: 'jest',

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.babel({
        babel: require('@babel/core'),
      }),
    },

    hints: {
      ignoreCoverage: /istanbul ignore next/,
    },

    setup: function(wallaby) {
      const jestConfig = require('./package.json').jest;
      jestConfig.setupFiles = jestConfig.setupFiles.map(
        //
        file => file.replace('.ts', '.js')
      );
      wallaby.testFramework.configure(jestConfig);
    },

    debug: false,
  };
};
```

The hanging process arguments:
```
xx               53857 100.0  0.5  4651432  88912   ??  R    11:34pm   9:28.74 node --harmony /Users/xx/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.99/wallaby/server.js extended-core-ws --projectCachePath=/Users/xx/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.99/projects/f9bbe4ed37afe03f --configPath=/Users/xx/Projects/aimee-blue/ab-web/wallaby.js --lkp=/Users/xx/.vscode/extensions/.wlck --client=VSCode --phantomjs=/Users/xx/.vscode/phantomjs_v2.1.1/phantomjs --port=61657
```

**Comment by smcenlly** [comment]
@zaripych, could you please add debug: 'true' as an additional property in your wallaby.js configuration file and send us a full copy of your Wallaby.js Console Output window.

**Comment by smcenlly** [comment]
@ayatkevich, we haven't been able to duplicate the problem using the same version of ubuntu that you're using. A couple of questions:

1) Do you have the same problem on other machines/operating systems? 
2) Are you able to reproduce the issue without any use of the postgres components? (we wonder if this is somehow related to postgres resources not being released).

I'd like to suggest that you try changing wallaby's [workers configuration](https://wallabyjs.com/docs/config/workers.html) to see if that solves your problem. By default, Wallaby will create (# CPUs - 2) initial worker processes, and ((# CPUs - 2) / 2) regular processes. Both have a minimum lower bound of 2. The config below will force both of our # workers settings to 2, and will restart the workers each time a test needs to execute (typically slows tests down by 50-100ms).

If that doesn't help and you still have the issue without the postgres components, we'll provide you with a patched version of wallaby core to get more information with a CPU profile dump.

```diff
module.exports = function() {
  return {
    debug: true,

    files: [
      { pattern: 'node_modules/@types/**/*', instrument: false },
      'tsconfig.json',
      'src/**/*.ts',
      '!src/**/*.spec.ts'
    ],

    tests: ['src/**/*.spec.ts'],

+   workers: {
+     initial: 2,
+     regular: 2,
+     restart: true
+   },

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    setup: function() {
      process.env.POSTGRES_USER = 'postgremote';
      process.env.POSTGRES_DB = 'postgremote';
      process.env.POSTGRES_PASSWORD = '';
    }
  };
};
```

**Comment by ayatkevich** [comment]
@smcenlly 

> Do you have the same problem on other machines/operating systems?

Unfortunately, I have no another system to try.

> Are you able to reproduce the issue without any use of the postgres components? (we wonder if this is somehow related to postgres resources not being released).

Yep, I've reproduced it without any use of the postgres components.

> I'd like to suggest that you try changing wallaby's workers configuration

These settings seem to be working! :+1: 
I've been doing development with all the tests included for an hour now and it works well.

**Comment by zaripych** [comment]
@smcennly
I changed my config and replaced greedy ‘**’ pattern in the compiler section with ’src/**’. Since then Wallaby behave well so far, so I think it might have been related.

Thank you for great work!
