### ISSUE TITLE
CRA 2.1 with Typescript

### ISSUE THREAD

**Issue by lucax88x** [wallabyjs/public#1912]
### Issue description or question
Creating a React solution with the new version of create-react-app 2.1 which has the Typescript support does not work

The same configuration was working with a create-react-app 1.x with the Typescript version from Microsoft ([sample](https://github.com/lucax88x/react-playground))

this is the error

```
[Error] ​​Postprocessor run failure: Failed to run preprocessors on src/actions/index.js, ReferenceError: [BABEL] src/actions/index.js: Unknown option: C:\git\time-tracker\src\app\node_modules\babel-preset-react-app\index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.​​
[Error] ​​​​
[Error] ​​A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:​​
[Error] ​​​​
[Error] ​​Invalid:​​
[Error] ​​  `{ presets: [{option: value}] }`​​
[Error] ​​Valid:​​
[Error] ​​  `{ presets: [['presetName', {option: value}]] }`​​
[Error] ​​​​
[Error] ​​For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "C:\\git\\time-tracker\\src\\app\\node_modules\\babel-preset-react-app\\index.js")​​
[Error] ​​    at Logger.error (C:\git\time-tracker\src\app\node_modules\babel-core\lib\transformation\file\logger.js:41:11)​​
[Error] ​​    at OptionManager.mergeOptions (C:\git\time-tracker\src\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:226:20)​​
[Error] ​​    at C:\git\time-tracker\src\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:265:14​​
[Error] ​​    at C:\git\time-tracker\src\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:323:22​​
[Error] ​​    at Array.map (<anonymous>)​​
[Error] ​​    at OptionManager.resolvePresets (C:\git\time-tracker\src\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)​​
[Error] ​​    at OptionManager.mergePresets (C:\git\time-tracker\src\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)​​
[Error] ​​    at OptionManager.mergeOptions (C:\git\time-tracker\src\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)​​
[Error] ​​    at OptionManager.init (C:\git\time-tracker\src\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)​​
[Error] ​​    at File.initOptions (C:\git\time-tracker\src\app\node_modules\babel-core\lib\transformation\file\index.js:212:65)​​
[Error] ​​    at new File (C:\git\time-tracker\src\app\node_modules\babel-core\lib\transformation\file\index.js:135:24)​​
[Error] ​​    at Pipeline.transform (C:\git\time-tracker\src\app\node_modules\babel-core\lib\transformation\pipeline.js:46:16)​​
[Error] ​​    at **/*.js?(x) (C:\git\time-tracker\src\app\wallaby.js:29:33)​​
[Error] ​​    at _combinedTickCallback (internal/process/next_tick.js:132:7)​​
[Error] ​​    at process._tickCallback (internal/process/next_tick.js:181:9)​​

```

### Wallaby.js configuration file

```javascript
// tslint:disable

module.exports = function(wallaby) {
    const testPathExp = 'src/**/*.spec.ts?(x)';
  
    return {
      files: [
        'tsconfig.json',
        'tsconfig.test.json',
        'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
        {pattern: 'config/**/*.js', instrument: false},
        `!${testPathExp}`
      ],
  
      tests: [testPathExp],
  
      env: {
        runner: 'node',
        type: 'node'
      },
      compilers: {
        '**/*.js?(x)': wallaby.compilers.babel({
          babel: require('babel-core'),
          presets: ['react-app']
        })
      },
      preprocessors: {
        '**/*.js?(x)': file =>
          require('babel-core').transform(file.content, {
            compact: false,
            filename: file.path,
            presets: ['react-app'],
            sourceMap: true
          })
      },
  
      setup: () => {
        const jestConfig = require('./package').jest;
        Object.keys(jestConfig.transform || {}).forEach(
          k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]
        );
        delete jestConfig.testEnvironment;
        wallaby.testFramework.configure(jestConfig);
      },
  
      testFramework: 'jest'
    };
  };
  
```

### Code editor or IDE name and version

Visual Studio Code v1.?

### OS name and version

Windows

Let me know if you need a repro solution.

**Comment by ArtemGovorov** [comment]
As [mentioned in our docs](https://wallabyjs.com/docs/integration/react-jsx.html#create-react-app), you may find working Wallaby config for CRA in [this post](https://github.com/wallabyjs/public/issues/1431#issuecomment-419028592) (see `Wallaby Config for CRA >=2.1 with TypeScript support generated app (not ejected)`).
