### ISSUE TITLE
Error trying to  run wallaby for mocha test

### ISSUE THREAD

**Issue by rollymaduk** [wallabyjs/public#1914]
### Issue description or question
Please help ! I get an error like the one below trying to  run wallaby for mocha test
I am using an older version of wallaby v1.0.94
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

### Wallaby.js configuration file

```javascript
module.exports = wallaby => ({
  files: [
    'app/**/*.js',
    '!app/**/*.test.js',
  ],
  tests: [
    'app/**/*.test.js',
  ],

  env: {
    type: 'node',
    env: 'node',
  },
  compilers: { '**/*.js': wallaby.compilers.babel() },
  testFramework: 'mocha',

  debug: true,
});
```

### Code editor or IDE name and version

WebStorm v 2018.1.5

### OS name and version

Windows
OSX
Linux Ubuntu 18.04.1 LTS

**Comment by ArtemGovorov** [comment]
Please share a sample repo demonstrating the issue, we are happy to take a look and investigate.

**Comment by smcenlly** [comment]
Closing this issue as we require more information. We will reopen the issue if more detail is provided.
