### ISSUE TITLE
Problem with integrating puppeteer and jest-puppeteer 

### ISSUE THREAD

**Issue by scullabyte** [wallabyjs/public#1917]
### Issue description or question

I have installed `jest-puppeteer` and everything works in jest when I run it, however, wallaby doesn't work unless I remove the `"preset": "jest-puppeteer"` line from my jest configuration. I have upgraded all packages, uninstalled `node_modules` and re-yarned everything with no luck.

```
[Error] Runtime error: TypeError: Cannot read property '_jasmineAdapter' of undefined​​
​​[Error]     at Object.<anonymous> (/Users/admin/Development/projects/adfire/functions/node_modules/expect-puppeteer/lib/index.js:141:2524)​​
​​[Error]     at Runtime._execModule (/Users/admin/node_modules/jest-runtime/build/index.js:694:13)​​
​​[Error]     at Runtime.requireModule (/Users/admin/node_modules/jest-runtime/build/index.js:376:14)​​
​​[Error]     at /Users/admin/node_modules/jest-jasmine2/build/index.js:112:15​​
​​[Error]     at Generator.next (<anonymous>)​​
​​[Error]     at step (/Users/admin/node_modules/jest-jasmine2/build/index.js:170:30)​​
​​[Error]     at /Users/admin/node_modules/jest-jasmine2/build/index.js:189:14​​
​​[Error]     at new Promise (<anonymous>)​​
​​[Error]     at /Users/admin/node_modules/jest-jasmine2/build/index.js:167:12​​`
```

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: ["src/**/*.*", "!src/**/*spec.ts", "package.json", "!node_modules/"],
    tests: ["src/**/*spec.ts"],
    env: {
      type: "node",
      runner: "node"
    },
    testFramework: "jest",
    setup: function(wallaby) {
      var jestConfig = require("./package.json").jest;
      wallaby.testFramework.configure(jestConfig);
    },
    compilers: {
      "**/*.js": wallaby.compilers.babel()
    },
    preprocessors: {
      "**/*.(j|t)s?(x)": file =>
        require("babel-core").transform(file.content, {
          sourceMap: true,
          filename: file.path,
          presets: ["babel-preset-jest"]
        })
    },
    debug: true
  };
};
```
package.json
```javascript
{
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "serve": "npm run build && firebase serve --only functions",
    "kill": "killall node",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "snippet": "npm run shell > ./snippet.sh",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log",
    "testfiles": "npm run lint && npm run build -- --pretty",
    "test": "jest --watchAll",
    "testoffline": "npm run testfiles ./**/*.spec.ts"
  },
  "jest": {
    "transform": {
      "^.+\\.tsx?$": "ts-jest"
    },
    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "modulePaths": [
      "<rootDir>/src/",
      "<rootDir>/node_modules/",
      "<rootDir>/functions/node_modules/"
    ],
    "preset": "jest-puppeteer"
  },
  "main": "build/index.js",
  "dependencies": {
    "@types/expect-puppeteer": "^3.3.0",
    "@types/faker": "^4.1.4",
    "@types/jest-environment-puppeteer": "^2.2.1",
    "apollo-boost": "^0.1.20",
    "apollo-server-express": "^2.2.2",
    "babel-cli": "^6.26.0",
    "babel-jest": "^23.6.0",
    "babel-preset-jest": "^23.2.0",
    "babel-register": "^6.26.0",
    "body-parser": "^1.18.3",
    "cors": "^2.8.5",
    "express": "^4.16.4",
    "express-async-handler": "^1.1.4",
    "faker": "^4.1.0",
    "firebase-admin": "^6.1.0",
    "firebase-functions": "^2.1.0",
    "firebase-functions-helper": "^0.5.10",
    "graphql": "^14.0.2",
    "graphql-server-express": "^1.4.0",
    "graphql-tools": "^4.0.3",
    "lodash": "^4.17.11",
    "puppeteer": "^1.10.0",
    "puppeteer-request-mocker": "^1.0.0",
    "react-apollo": "^2.3.1",
    "request": "^2.88.0",
    "request-promise": "^4.2.2",
    "ts-node": "^7.0.1"
  },
  "devDependencies": {
    "@types/jest": "^23.3.9",
    "@types/lodash": "^4.14.118",
    "@types/puppeteer": "^1.10.0",
    "eslint": "^5.9.0",
    "firebase-functions-test": "^0.1.4",
    "jest-puppeteer": "^3.5.1",
    "ts-jest": "^23.10.4",
    "tslint": "^5.11.0",
    "typescript": "~3.1.6"
  },
  "engines": {
    "node": "8"
  },
  "private": true
}

```

tsconfig.json
```javascript

{
  "compilerOptions": {
    "target": "es2017",
    "lib": ["esnext", "dom", "esnext.asynciterable"],
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitReturns": false,
    "allowSyntheticDefaultImports": true,
    "outDir": "build",
    "sourceMap": true,
    "esModuleInterop": true,
    "isolatedModules": false,
    "experimentalDecorators": true
  },
  "compileOnSave": true,
  "include": ["src", "node_modules/@types/puppeteer/index.d.ts"],
  "exclude": ["node_modules", "src/**/*.spec.ts"]
}

```

.babelrc
```javascript
{
  "presets": ["@babel/preset-typescript"]
}
```
.eslintrc
```javascript
{
  "parserOptions": {
    // Required for certain syntax usages
    "ecmaVersion": 6
  },
  "plugins": ["promise"],
  "env": {
    "jest": true
  },
  "globals": {
    "page": true,
    "browser": true,
    "context": true,
    "jestPuppeteer": true
  },
  "extends": "eslint:recommended",
  "rules": {
    // Removed rule "disallow the use of console" from recommended eslint rules
    "no-console": "off",

    // Removed rule "disallow multiple spaces in regular expressions" from recommended eslint rules
    "no-regex-spaces": "off",

    // Removed rule "disallow the use of debugger" from recommended eslint rules
    "no-debugger": "off",

    // Removed rule "disallow unused variables" from recommended eslint rules
    "no-unused-vars": "off",

    // Removed rule "disallow mixed spaces and tabs for indentation" from recommended eslint rules
    "no-mixed-spaces-and-tabs": "off",

    // Removed rule "disallow the use of undeclared variables unless mentioned in /*global */ comments" from recommended eslint rules
    "no-undef": "off",

    // Warn against template literal placeholder syntax in regular strings
    "no-template-curly-in-string": 1,

    // Warn if return statements do not either always or never specify values
    "consistent-return": 1,

    // Warn if no return statements in callbacks of array methods
    "array-callback-return": 1,

    // Requre the use of === and !==
    "eqeqeq": 2,

    // Disallow the use of alert, confirm, and prompt
    "no-alert": 2,

    // Disallow the use of arguments.caller or arguments.callee
    "no-caller": 2,

    // Disallow null comparisons without type-checking operators
    "no-eq-null": 2,

    // Disallow the use of eval()
    "no-eval": 2,

    // Warn against extending native types
    "no-extend-native": 1,

    // Warn against unnecessary calls to .bind()
    "no-extra-bind": 1,

    // Warn against unnecessary labels
    "no-extra-label": 1,

    // Disallow leading or trailing decimal points in numeric literals
    "no-floating-decimal": 2,

    // Warn against shorthand type conversions
    "no-implicit-coercion": 1,

    // Warn against function declarations and expressions inside loop statements
    "no-loop-func": 1,

    // Disallow new operators with the Function object
    "no-new-func": 2,

    // Warn against new operators with the String, Number, and Boolean objects
    "no-new-wrappers": 1,

    // Disallow throwing literals as exceptions
    "no-throw-literal": 2,

    // Require using Error objects as Promise rejection reasons
    "prefer-promise-reject-errors": 2,

    // Enforce “for” loop update clause moving the counter in the right direction
    "for-direction": 2,

    // Enforce return statements in getters
    "getter-return": 2,

    // Disallow await inside of loops
    "no-await-in-loop": 2,

    // Disallow comparing against -0
    "no-compare-neg-zero": 2,

    // Warn against catch clause parameters from shadowing variables in the outer scope
    "no-catch-shadow": 1,

    // Disallow identifiers from shadowing restricted names
    "no-shadow-restricted-names": 2,

    // Enforce return statements in callbacks of array methods
    "callback-return": 2,

    // Require error handling in callbacks
    "handle-callback-err": 2,

    // Warn against string concatenation with __dirname and __filename
    "no-path-concat": 1,

    // Prefer using arrow functions for callbacks
    "prefer-arrow-callback": 1,

    // Return inside each then() to create readable and reusable Promise chains.
    "promise/always-return": 2,

    //Enforces the use of catch() on un-returned promises
    "promise/catch-or-return": 2,

    // Warn against nested then() or catch() statements
    "promise/no-nesting": 1
  }
}

```

### Code editor or IDE name and version

Visual Studio Code v1.29

### OS name and version

OSX 10.14

**Comment by scullabyte** [comment]
Sorry... Just figured it out. I had two VSCode windows open and one was a parent to the one with the package.json so Wallaby must not have been reading the child window's package.json... dumb error on my part. 

I am curious if anyone can tell me if there is a plan to upgrade to puppeteer on the backend of wallaby though?

**Comment by antoniputra** [comment]
Hi @scullabyte  can you run this jest-puppeteer in vsc?
