### ISSUE TITLE
Template Parse Errors when using Wallaby with Jest/Angular 7

### ISSUE THREAD

**Issue by andrewryan1906** [wallabyjs/public#1926]
### Issue description or question
I am able to use Jest to test Angular 7 components without any issue. However, when I enable Wallaby, these tests fail with template parse errors. The error output is here:

https://gist.github.com/andrewryan1906/c836aa89702cdc1877a1a080bfbd6522

Again - Jest runs without a problem. 

### Wallaby.js configuration file
https://gist.github.com/andrewryan1906/2c14550541f8b033e6980b9bbcd7eedb

```javascript

The error comes in this test code:

beforeAll((done) => (async () => {


    TestBed.resetTestingModule();


    mockContactRolesService = {} as ContactRolesService;
    mockConfigurationService = {
      CustomFields: [],
      GetDefaultPageLayout: jest.fn(),
      UpsertContactRole: jest.fn(),
      LoadContactRoles: jest.fn()
    } as RolodexConfigurationService;


    TestBed.configureTestingModule({
      declarations: [ContactRoleFormComponent, LightSwitchComponent],
      imports: [ReactiveFormsModule],
      providers: [
        FormBuilder,
        {provide: Router, useValue: {}},
        {provide: IdGeneratorService, useValue: {}},
        {provide: ToastrService, useValue: {   }},
        {provide: ActivatedRoute, useValue: mockActivatedRoute},
        {provide: SecurityService, useValue: {CurrentTenantId: 'tests'}},
        {provide: ContactRolesService, useValue: mockContactRolesService},
        {provide: RolodexConfigurationService, useValue: mockConfigurationService}

      ],
      schemas: [NO_ERRORS_SCHEMA]
    });


    await TestBed.compileComponents();

    // prevent Angular from resetting testing module
    TestBed.resetTestingModule = () => TestBed;
  })().then(done).catch(done.fail));


  let mockToastrService = {error: jest.fn()};
  beforeEach(() => {


    TestBed.overrideProvider(ToastrService, {useValue: mockToastrService});


  });


```

### Code editor or IDE name and version

WebStorm v2018.2

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
We have never seen an issue like this, so will need some more details to investigate it.
Could you please create a sample repo with a dummy test file, and a failing template (that is working ok from Jest CLI), we are happy to have a look and investigate.

**Comment by andrewryan1906** [comment]
I just started working on this repo when I encountered the error; so it's pretty small. How do I give you access to the repo so you can look at it?

Is there a direct email I can use?

**Comment by andrewryan1906** [comment]
OK, I've made you a read only collaborator on my repo; you should be able to pull it down. Via Webstorm, I can run Jest just fine, but Wallaby doesn't work.

Anything else I can provide to aid in troubleshooting?

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo access. Looks like your html files are being compiled twice (once by Wallaby compilers section, and then by Jest transform). The compilation is exactly the same, but breaks when applied twice.

To fix it, you'll either need to remove `compilers` section from Wallaby (to let Jest transform do the job), or to remove the Jest transform for HTML files (the second option is better because Wallaby will be able to rerun tests on changes in your HTML files if it compiles them):

```diff
    ...
    testFramework: 'jest',

+   setup: wallaby => {
+     const jestConfig = require('./jest.config');
+     jestConfig.transform = {
+       '^.+\\.(ts|js)$': '<rootDir>/node_modules/jest-preset-angular/preprocessor.js',
+     };
+     wallaby.testFramework.configure(jestConfig);
+   },
   ...
```

**Comment by andrewryan1906** [comment]
Artem,

Thanks for this... but how exactly do I do the second thing? How do I remove the Jest transform for HTML files?

I've given you write access to the repo if you want to make the change and check it in.

Andrew

**Comment by andrewryan1906** [comment]
BTW, I tried to add the code you included, and i get this error:

```
Error: Cannot find module './jest.config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at WebSocket.emit (events.js:182:13)
    at afterWrite (_stream_writable.js:480:3)
    at onwrite (_stream_writable.js:471:7)
    at InflateRaw.afterTransform (_stream_transform.js:94:3)
    at Zlib.processCallback (zlib.js:619:8)
```

Not sure what directory the wallaby is running in, or how to make the require target the current directory (because ./jest.config definitely exists)

**Comment by dornfeder** [comment]
@ArtemGovorov As i have a similar setup as @andrewryan1906 with the same problem, i would be very much interested in what the wallaby.js for the actual final solution looks like. Could you provide that here?

**Comment by ArtemGovorov** [comment]
@dornfeder 

Sure, here it is:

```js
module.exports = function () {

  const jestTransform = file => require('jest-preset-angular/preprocessor').process(file.content, file.path, {globals: {__TRANSFORM_HTML__: true}, rootDir: __dirname});

  return {
    files: [
      'src/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      'jest.config.js',
      '!src/**/*.spec.ts',
    ],

    tests: ['src/**/*.spec.ts'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.html': file => ({code: jestTransform(file), map: {version: 3, sources: [], names: [], mappings: []}, ranges: []})
    },

    preprocessors: {
      'src/**/*.js': [
        jestTransform,
        file => require('@babel/core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          presets: [require('babel-preset-jest')]
        })
      ]
    },

    testFramework: 'jest',

    setup: wallaby => {
      const jestConfig = require('./jest.config');
      jestConfig.transform = {
        '^.+\\.(ts|js)$': '<rootDir>/node_modules/jest-preset-angular/preprocessor.js',
      };
      wallaby.testFramework.configure(jestConfig);
    }
  };
};
```

**Comment by dornfeder** [comment]
@ArtemGovorov Great, thanks. I had some smaller mistakes in my own config, now I am at least not getting the template error any longer. BUT now wallaby fails with this error message: 

```
​​​​​0 failing tests, 38 passing​​​​​
​​​​​​​​​​
​​Jest encountered an unexpected token​​
​​​​
​​This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.​​
​​​​
​​By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".​​
​​​​
​​Here's what you can do:​​
​​ • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.​​
​​ • If you need a custom transformation specify a "transform" option in your config.​​
​​ • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.​​
​​​​
​​You'll find more details and examples of these config options in the docs:​​
​​https://jestjs.io/docs/en/configuration.html​​
​​​​
​​Details:​​
​​​​
​​C:\Users\dornfeder\dev\project\frontend\node_modules\lodash-es\lodash.js:10​​
​​export { default as add } from './add.js';​​
​​^^^^^^​​
​​​​ 
```

Seems like a similar issue as https://github.com/wallabyjs/public/issues/1853, but i still could not fix it. 
The issue seems to be that this one node module `lodash-es` NEEDS to be transformed in order to work but i can't get Wallaby to do it. The Jest Ignore Pattern does not seem to work here. 

**wallaby.js**
```js
// see https://wallabyjs.com/docs/integration/angular.html#jest
module.exports = function () {

  const jestTransform = file => require('jest-preset-angular/preprocessor').process(file.content, file.path, {
    globals: {
      __TRANSFORM_HTML__: true,
    },
    rootDir: __dirname
  });

  return {
    files: [
      'src/app/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      'jest.config.js',
      'src/setup-jest.ts',
      'src/__mocks__/jestGlobalMocks.ts',
      '!src/app/**/*.+(spec|test).ts'
    ],

    tests: [
        'src/app/**/*.+(spec|test).ts',
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    preprocessors: {
      'src/**/*.js': [
        jestTransform,
        (file) => require('@babel/core').transform(file.content, {
          sourceMap: true,
          filename: file.path,
          presets: [require('babel-preset-jest')]
        })
      ]
    },

    compilers: {
        '**/*.html': file => ({
            code: jestTransform(file),
            map: {
            version: 3,
            sources: [],
            names: [],
            mappings: []
            },
            ranges: []
        })
    },

    testFramework: 'jest',

    setup: wallaby => {
        const jestConfig = require('./jest.config');
        jestConfig.transform = {
          '^.+\\.(ts|js)$': '<rootDir>/node_modules/jest-preset-angular/preprocessor.js',
        };
        wallaby.testFramework.configure(jestConfig);
    }
  };
};

```

**jest.config.js**
```js
module.exports = {
    preset: "jest-preset-angular",
    setupTestFrameworkScriptFile: "<rootDir>/src/setup-jest.ts",
    coveragePathIgnorePatterns: [
        "/node_modules/",
        "/__mocks__/",
        "/environments/"
    ],
    collectCoverage: true,
    roots: ['src'],
    globals: {
        "ts-jest": {
            "tsConfigFile": "tsconfig.json"
        },
        "__TRANSFORM_HTML__": true
    },
    reporters: [
        "default",
        ["jest-junit", {
            output: "./output/jest/report/junit.xml",
            usePathForSuiteName: "true"
        }],
        ["jest-html-reporter", {
            pageTitle: "Test Report",
            outputPath: "./output/jest/report/index.html"
        }]
    ],    
    coverageReporters: ["html","lcovonly"],
    coverageDirectory: "./output/jest/coverage/",
    testURL: "http://localhost/",
    transformIgnorePatterns: [
        "/!node_modules\\/lodash-es/"
    ],
    transform: { "^.+\\.(js|jsx|mjs)$": "./node_modules/babel-jest"}
};
```
**.babelrc** 
```
{
    "plugins": [
        "transform-es2015-modules-commonjs"
    ]
}
```
Any ideas how to fix that?

**Comment by ArtemGovorov** [comment]
@andrewryan1906 This one should be easy to fix:

```diff
// see https://wallabyjs.com/docs/integration/angular.html#jest
module.exports = function () {

  const jestTransform = file => require('jest-preset-angular/preprocessor').process(file.content, file.path, {
    globals: {
      __TRANSFORM_HTML__: true,
    },
    rootDir: __dirname
  });

  return {
    files: [
      'src/app/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      'jest.config.js',
+     {pattern: '.babelrc', instrument: false} 
      'src/setup-jest.ts',
      'src/__mocks__/jestGlobalMocks.ts',
      '!src/app/**/*.+(spec|test).ts'
    ],
...
```

**Comment by dornfeder** [comment]
> @andrewryan1906 This one should be easy to fix:
> 
> ```diff
> ...
>       'jest.config.js',
> +     {pattern: '.babelrc', instrument: false} 
>       'src/setup-jest.ts',
> ...
> ```

Unfortunately, that did not do the trick for me, i am still getting the `unexpected token` error. 
Is it because in jest config i use `./node_modules/babel-jest` as transformer but in wallaby it is switched to `'<rootDir>/node_modules/jest-preset-angular/preprocessor.js'`?

**Comment by ArtemGovorov** [comment]
> Unfortunately, that did not do the trick for me, i am still getting the `unexpected token` error.
Is it because in jest config i use `./node_modules/babel-jest` as transformer but in wallaby it is switched to `'<rootDir>/node_modules/jest-preset-angular/preprocessor.js'`?

@dornfeder Possibly, could you please try commenting it out from your Wallaby config to see if it helps:

```
//    jestConfig.transform = {
//          '^.+\\.(ts|js)$': '<rootDir>/node_modules/jest-preset-angular/preprocessor.js',
//        };
```

If it doesn't help, could you please provide a sample repo demonstrating the issue? We are happy to investigate it further.

**Comment by dornfeder** [comment]
> If it doesn't help, could you please provide a sample repo demonstrating the issue? We are happy to investigate it further.

It did not help, so i created a basic example repo where i could reproduce the `Jest encountered an unexpected token​​` error: https://github.com/dornfeder/angular-jest-wallaby-test

**Comment by ArtemGovorov** [comment]
Thanks for the repo. I have sent you the [pull request to make it work](https://github.com/dornfeder/angular-jest-wallaby-test/pull/1):

```diff
      setup: wallaby => {
          const jestConfig = require('./jest.config');
          jestConfig.transform = {
+           '^.*node_modules.*\\.(js|jsx|mjs)$': 'babel-jest',
            '^.+\\.(ts|js)$': '<rootDir>/node_modules/jest-preset-angular/preprocessor.js',
          }; 
          wallaby.testFramework.configure(jestConfig);
      }
```

**Comment by dornfeder** [comment]
> ```diff
> (js|jsx|mjs)
> ```

Thanks for your help, that did the trick for my testrepo. 👍
