### ISSUE TITLE
Newer version of ts-jest does not work with Wallabyjs

### ISSUE THREAD

**Issue by UberMouse** [wallabyjs/public#1931]
### Issue description or question
Wallabyjs does not work with the new version of ts-jest (v23.10.5). v23.10.0 was a rewrite of ts-jest, downgrading to the previous version (v23.1.4) causes it to work fine.

I'm not actually sure if we need ts-jest if we are using Wallabyjs? We had it before Wallaby and it has been working so haven't tried to change it

### Wallaby.js configuration file

```javascript
var compilerOptions = require('./tsconfig.json');
compilerOptions.module = 'CommonJs';


module.exports = function (wallaby) {
  return {
    files: [
      { pattern: 'tsconfig.json', load: false },
      { pattern: 'Scripts/react/**/*.ts', load: false },
      { pattern: 'Scripts/react/**/*.tsx', load: false },
      { pattern: 'Scripts/react/**/*.js', load: false },
      { pattern: 'Scripts/react/**/*.spec.tsx', ignore: true },
      { pattern: 'Scripts/react/**/*.spec.ts', ignore: true },
      { pattern: 'Scripts/react/**/*.stories.tsx', ignore: true },
    ],
    tests: [
      'Scripts/react/**/*.spec.ts',
      'Scripts/react/**/*.spec.tsx',
      '!Scripts/react/sections/apm/modules/onboarding/tourtip.spec.tsx'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    testFramework: 'jest',
    filesWithNoCoverageCalculated: [
      'Scripts/react/sections/productpages/setupinstructions/instructions/languages/**/*'
    ],
    compilers: {
      '**/*.js': wallaby.compilers.babel(),
      '**/*.ts': wallaby.compilers.typeScript(),
      '**/*.tsx': wallaby.compilers.typeScript(),
    },
    hints: {
      ignoreCoverageForFile: /ignore file coverage/,
      ignoreCoverage: /ignore coverage/
    },
    setup: function (wallaby) {
      var jestConfig = require(wallaby.localProjectDir + '/jestconfig.json');

      wallaby.testFramework.configure(jestConfig);
    },
    workers: {
      initial: 3,
      regular: 2
    }
  }
};
```

### Code editor or IDE name and version

Webstorm 2018.3 

### OS name and version

OSX 10.14.1

**Comment by ArtemGovorov** [comment]
We have just tried a sample project with `ts-jest@23.10.5` and it seems to work.

- What error are you getting?
- Could you please share your `jestconfig.json` file?

> I'm not actually sure if we need ts-jest if we are using Wallabyjs?

You don't normally need it with Wallaby (Wallaby is not using it), unless there are some node module that you are using are written (and published) in TS, so they need to be compiled by `ts-jest` (again could be configured to be compiled by Wallaby instead). Looking at you jest config may help.

**Comment by UberMouse** [comment]
Here's our jestconfig.json. The error I'm getting is "TypeError: Scripts/react/tests/stateHelpers.js: Emit skipped". The file changes each time I run Wallaby. If I check the Wallaby Console for the stacktrace I get something like this

```
Runtime error: TypeError: Scripts/react/tests/stateHelpers.js: Emit skipped
    at getOutput (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/ts-jest/dist/compiler.js:160:23)
    at Object.compile (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/ts-jest/dist/compiler.js:206:25)
    at TsJestTransformer.process (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/ts-jest/dist/ts-jest-transformer.js:101:41)
    at ScriptTransformer.transformSource (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-runtime/build/script_transformer.js:314:35)
    at ScriptTransformer._transformAndBuildScript (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-runtime/build/script_transformer.js:385:40)
    at ScriptTransformer.transform (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-runtime/build/script_transformer.js:445:19)
    at Runtime._execModule (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-runtime/build/index.js:640:53)
    at Runtime.requireModule (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-runtime/build/index.js:376:14)
    at Runtime.requireModuleOrMock (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-runtime/build/index.js:463:19)
    at Object.<anonymous> (./Scripts/react/tests/sagaHelpers.js:24:1)
    at Runtime._execModule (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-runtime/build/index.js:694:13)
    at Runtime.requireModule (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-runtime/build/index.js:376:14)
    at Runtime.requireModuleOrMock (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-runtime/build/index.js:463:19)
    at Object.<anonymous> (./Scripts/react/app/sagas.spec.js:3:1)
    at Runtime._execModule (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-runtime/build/index.js:694:13)
    at Runtime.requireModule (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-runtime/build/index.js:376:14)
    at /Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-jasmine2/build/index.js:129:13
    at Generator.next (<anonymous>)
    at step (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-jasmine2/build/index.js:170:30)
    at /Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-jasmine2/build/index.js:189:14
    at new Promise (<anonymous>)
    at /Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-jasmine2/build/index.js:167:12
    at jasmine2 (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-jasmine2/build/index.js:138:17)
    at /Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-runner/build/run_test.js:187:24
    at Generator.next (<anonymous>)
    at step (/Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-runner/build/run_test.js:315:30)
    at /Users/taylor/dev/raygun/src/App/Mindscape.Raygun.Website/node_modules/jest-runner/build/run_test.js:326:15
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

```json
{
  "transform": {
    "^.+\\.(t|j)sx?$": "ts-jest"
  },
  "setupFiles": [
    "<rootDir>/Scripts/react/tests/shim.js",
    "<rootDir>/Scripts/react/tests/setup.js"
  ],
  "snapshotSerializers": ["jest-html", "<rootDir>/node_modules/snapshot-diff/serializer.js"],
  "testEnvironment": "jsdom",
  "setupTestFrameworkScriptFile": "./Scripts/react/tests/setupFramework.js",
  "roots":  [
    "<rootDir>/Scripts/react/"
  ],
  "testRegex": "(\\.|/)(test|spec)\\.(ts|tsx|js)$",
  "moduleNameMapper": {
    "^components/(.*)$":  "<rootDir>/Scripts/react/components/$1",
    "^app/(.*)$": "<rootDir>/Scripts/react/app/$1",
    "^interfaces/(.*)$":  "<rootDir>/Scripts/react/interfaces/$1",
    "^sections/(.*)$": "<rootDir>/Scripts/react/sections/$1",
    "^utils/(.*)$": "<rootDir>/Scripts/react/utils/$1",
    "^apm/(.*)$": "<rootDir>/Scripts/react/sections/apm/$1",
    "^constants/(.*)$": "<rootDir>/Scripts/react/constants/$1",
    "^modules/(.*)$": "<rootDir>/Scripts/react/modules/$1",
    "^hocs/(.*)$": "<rootDir>/Scripts/react/hocs/$1",
    "^selectors/(.*)$": "<rootDir>/Scripts/react/selectors/$1",
    "^fela-rules/(.*)$": "<rootDir>/Scripts/react/fela-rules/$1",
    "^legacy/(.*)$": "<rootDir>/Scripts/react/legacy/$1",
    "^tests/(.*)$": "<rootDir>/Scripts/react/tests/$1"
  },
  "globals": {
    "window": {}
  },
  "moduleFileExtensions": [
    "ts",
    "tsx",
    "js",
    "json"
  ]
}
```

**Comment by ArtemGovorov** [comment]
Thanks for sharing the details.

This should help:

```diff
setup: function (wallaby) {
      var jestConfig = require(wallaby.localProjectDir + '/jestconfig.json');
+     jestConfig.transform = {};
      wallaby.testFramework.configure(jestConfig);
    },
```

**Comment by asgerhallas** [comment]
@ArtemGovorov just a quick question. I've seen this removal of the transform property from the config in a few places, but I can't really find any description in the docs of why it's necessary? Can you maybe explain it to me, or direct me to where I can find some info about it? :)

**Comment by ArtemGovorov** [comment]
@asgerhallas Wallaby uses its [own TypeScript compiler](https://wallabyjs.com/docs/integration/typescript.html) to perform TS compilation and instrumentation, so `ts-jest` transform is not required. In some cases it is best to remove it because it may be trying to double compile `.js` file emitted by Wallaby with `ts-jest`.

**Comment by eyaleizenberg** [comment]
@ArtemGovorov What's the proper way to do this in the new package.json configuration? I am using the automatic-no-configuration option so I haven't defined anything. My jest.config.js file looks like this:
```javascript
// jest.config.js
module.exports = {
  clearMocks: true,
  preset: "ts-jest",
  testEnvironment: "node"
};
```

**Comment by ArtemGovorov** [comment]
@eyaleizenberg Proper way to do what exactly? Wallaby auto-config is utilising Jest transforms and doesn't need them to be removed.

**Comment by eyaleizenberg** [comment]
@ArtemGovorov I have only that jest.config.js and no other configurations. When I run wallaby in my new project I get the following error:
```
[Info]  Started Wallaby.js Core v1.0.722
[Info]  Wallaby App (realtime reports) is available at: http://localhost:51245
[Error] Runtime error: ./utilities/album-utils.spec.ts: TypeError: utilities/album-utils.spec.ts: Emit skipped 
[Error]     at getOutput (./node_modules/ts-jest/dist/compiler.js:160:23) 
[Error]     at Object.compile (./node_modules/ts-jest/dist/compiler.js:206:25) 
[Error]     at TsJestTransformer.process (./node_modules/ts-jest/dist/ts-jest-transformer.js:101:41) 
[Error]     at ScriptTransformer.transformSource (./node_modules/@jest/transform/build/ScriptTransformer.js:453:35) 
[Error]     at ScriptTransformer._transformAndBuildScript (./node_modules/@jest/transform/build/ScriptTransformer.js:523:40) 
[Error]     at ScriptTransformer.transform (./node_modules/@jest/transform/build/ScriptTransformer.js:579:25) 
[Error]     at Runtime._execModule (./node_modules/jest-runtime/build/index.js:842:53) 
[Error]     at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:577:12) 
[Error]     at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:433:10) 
[Error]     at ./node_modules/jest-jasmine2/build/index.js:202:13 
[Error]     at Generator.next (<anonymous>) 
[Error]     at asyncGeneratorStep (./node_modules/jest-jasmine2/build/index.js:27:24) 
[Error]     at _next (./node_modules/jest-jasmine2/build/index.js:47:9) 
[Error]     at ./node_modules/jest-jasmine2/build/index.js:52:7 
[Error]     at new Promise (<anonymous>) 
[Error]     at ./node_modules/jest-jasmine2/build/index.js:44:12 
[Error]     at _jasmine (./node_modules/jest-jasmine2/build/index.js:207:19) 
[Error]     at jasmine2 (./node_modules/jest-jasmine2/build/index.js:60:19) 
[Error]     at ./node_modules/jest-runner/build/runTest.js:385:24 
[Error]     at Generator.next (<anonymous>) 
[Error]     at asyncGeneratorStep (./node_modules/jest-runner/build/runTest.js:161:24) 
[Error]     at _next (./node_modules/jest-runner/build/runTest.js:181:9) 
[Error]     at process._tickCallback (internal/process/next_tick.js:68:7) 
```

**Comment by ArtemGovorov** [comment]
@eyaleizenberg Please try this:
```diff
// jest.config.js
module.exports = {
  clearMocks: true,
  preset: "ts-jest",
  testEnvironment: "node",
+ globals: {
+   'ts-jest': {
+     diagnostics: true
+   }
+ }
};
```

**Comment by eyaleizenberg** [comment]
Yup that worked! Thanks a lot @ArtemGovorov !
