### ISSUE TITLE
Wallaby with Typescript and Jest from Create-React-App 2

### ISSUE THREAD

**Issue by Yonben** [wallabyjs/public#1936]
Hi,

### Issue description or question
When trying to run my tests, while usually working fine, if I try to import the functions I'm trying to test, I get the following errors:
```
[Info]​​​​​ console.log: FAIL src/components/Tester/tester.lib.test.js
​​​​​[Info]​​​​​ console.log:   ● Test suite failed to run
​​​​​[Info]​​​​​     Jest encountered an unexpected token
​​​​​[Info]​​​​​     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
​​​​​[Info]​​​​​     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
​​​​​[Info]​​​​​     Here's what you can do:
​​​​​[Info]​​​​​      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
​​​​​[Info]​​​​​      • If you need a custom transformation specify a "transform" option in your config.
​​​​​[Info]​​​​​      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
​​​​​[Info]​​​​​     You'll find more details and examples of these config options in the docs:
​​​​​[Info]​​​​​     https://jestjs.io/docs/en/configuration.html
​​​​​[Info]​​​​​     Details:
​​​​​[Info]​​​​​     C:\Users\yonben\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.100\projects\ec01e3fc6883a663\instrumented\src\components\Tester\tester.lib.test.js:2
​​​​​[Info]​​​​​     import { process } from './tester.lib';
​​​​​[Info]​​​​​            ^
​​​​​[Info]​​​​​     SyntaxError: Unexpected token {
​​​​​[Info]​​​​​       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:400:17)
​​​​​[Info]​​​​​       at Runtime.d._wallabyReplaced.p.requireModule (C:/Users/yonben/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.100/wallaby/runners/node/jest@0.4.3/initializer.js:14:23793)
```

### Wallaby.js configuration file

```javascript
module.exports = function (w) {

  return {
    files: [
      'src/**/*.ts',
      {
        pattern: 'src/**/*.test.ts',
        ignore: true
      }
    ],

    tests: [
      'src/**/*.test.ts'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.29.2
Typescript 3.2.1
React-scripts 2.1.1

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
TypeScript Jest configuration (`ts-jest` modules to be more specific) requires access to the `tsconfig.json` file, so if you are using Jest with TypeScript, you’ll need to add the file to your files list:

```diff
module.exports = function (w) {

  return {
    files: [
+     'tsconfig.json',
      'src/**/*.ts',
      {
        pattern: 'src/**/*.test.ts',
        ignore: true
      }
    ],

    tests: [
      'src/**/*.test.ts'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest'
  };
};
```

If you are using TypeScript with Jest and your tests are making jest.mock calls, then you will need to run Babel (babel-preset-jest) transformation on top of TypeScript compilation (just like ts-jest is doing) to hoist the calls:

```javascript
module.exports = function (w) {
  return {
    files: [
      ...
    ],

    tests: [
      ...
    ],

    ...

    preprocessors: {
      '**/*.js?(x)': file => require('babel-core').transform(
        file.content,
        {sourceMap: true, filename: file.path, presets: ['babel-preset-jest']})
    }
  };
};
```

If you haven't already seen, our website includes a section on [how to configure `jest`](https://wallabyjs.com/docs/integration/jest.html).

If you still can't get it working, please send us a cut-down sample repo, we'd be happy to take a look for you.

**Comment by ArtemGovorov** [comment]
You may find an [example of CRA + TypeScript Wallaby config here](https://github.com/wallabyjs/public/issues/1431#issuecomment-419028592).

**Comment by Yonben** [comment]
@smcenlly I think it should be in the docs: https://wallabyjs.com/docs/integration/typescript.html

CRA is a really popular tool and searching for "Typescript CRA Jest Wallaby" didn't lead me straight to the linked issue which was the instant fix.

Did I miss something in the docs?

Thanks!!

**Comment by ArtemGovorov** [comment]
> yeah my first bet was to go straight to the TS section.

Done, added the link to TS docs section as well.
