### ISSUE TITLE
Tests cannot find source modules

### ISSUE THREAD

**Issue by philipmw** [wallabyjs/public#1959]
### Issue description or question

Here's the project I'm working with: https://github.com/philipmw/reactful-dice/tree/wallaby. It is in Typescript and uses Jest.

The problem is that I see this in the Wallaby Console:

    Mon, 07 Jan 2019 23:43:57 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #86x41]
    Mon, 07 Jan 2019 23:43:57 GMT wallaby:workers [worker #0, session #86x41] Running tests in sandbox
    Mon, 07 Jan 2019 23:44:00 GMT wallaby:workers Sandbox (active) [86x41] error: Error: Cannot find module './Dice' from 'Dice.test.js'
    Mon, 07 Jan 2019 23:44:00 GMT wallaby:workers Sandbox (active) [37lw0] error: Error: Cannot find module './Die' from 'Die.test.js'
    Runtime error: Error: Cannot find module './Dice' from 'Dice.test.js'
        at Resolver.resolveModule (/Users/pmw/Repos/reactful-dice/node_modules/jest-resolve/build/index.js:221:17)
        at Resolver._getVirtualMockPath (/Users/pmw/Repos/reactful-dice/node_modules/jest-resolve/build/index.js:338:16)
        at Resolver._getAbsolutePath (/Users/pmw/Repos/reactful-dice/node_modules/jest-resolve/build/index.js:324:14)
        at Resolver.getModuleID (/Users/pmw/Repos/reactful-dice/node_modules/jest-resolve/build/index.js:301:31)
        at Runtime._shouldMock (/Users/pmw/Repos/reactful-dice/node_modules/jest-runtime/build/index.js:766:37)
        at Runtime.requireModuleOrMock (/Users/pmw/Repos/reactful-dice/node_modules/jest-runtime/build/index.js:460:14)
        at Object.<anonymous> (./src/Dice.test.js:11:28)
        at Runtime._execModule (/Users/pmw/Repos/reactful-dice/node_modules/jest-runtime/build/index.js:694:13)
        at Runtime.requireModule (/Users/pmw/Repos/reactful-dice/node_modules/jest-runtime/build/index.js:376:14)
        at /Users/pmw/Repos/reactful-dice/node_modules/jest-jasmine2/build/index.js:129:13
        at Generator.next (<anonymous>)
        at step (/Users/pmw/Repos/reactful-dice/node_modules/jest-jasmine2/build/index.js:170:30)
        at /Users/pmw/Repos/reactful-dice/node_modules/jest-jasmine2/build/index.js:189:14
        at new Promise (<anonymous>)
        at /Users/pmw/Repos/reactful-dice/node_modules/jest-jasmine2/build/index.js:167:12
        at jasmine2 (/Users/pmw/Repos/reactful-dice/node_modules/jest-jasmine2/build/index.js:138:17)
        at /Users/pmw/Repos/reactful-dice/node_modules/jest-runner/build/run_test.js:187:24
        at Generator.next (<anonymous>)
        at step (/Users/pmw/Repos/reactful-dice/node_modules/jest-runner/build/run_test.js:315:30)
        at /Users/pmw/Repos/reactful-dice/node_modules/jest-runner/build/run_test.js:326:15
        at process._tickCallback (internal/process/next_tick.js:68:7)

I tried your [Wallaby Typescript Sample](https://github.com/wallabyjs/wallaby-typescript-sample) on the same environment, and that works fine.

I've brought your sample to be closer to how my project is -- I renamed your sample files from TS to TSX, and I specified the sample's `env runner` to be the same path as my project's. But your sample continues to succeed.

One difference I can think of is that I'm using jest, while your sample uses Jasmine.

I wonder if you have ideas why my project is failing to integrate with Wallaby.

### Wallaby.js configuration file

https://github.com/philipmw/reactful-dice/blob/wallaby/wallaby.js

### Code editor or IDE name and version

IntelliJ IDEA 2018.3.2 (Ultimate Edition)
Build #IU-183.4886.37, built on December 17, 2018
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### OS name and version

macOS 10.13.6

**Comment by ArtemGovorov** [comment]
Looks like your `files` list pattern doesn't include your source files. As you may see in your Wallaby Console output, only test files are being read by Wallaby:

<img width="953" alt="screen shot 2019-01-08 at 10 35 59 am" src="https://user-images.githubusercontent.com/979966/50801667-7e9c2b80-1331-11e9-864d-63b4e1ff6f35.png">

I have sent the PR to fix the config: https://github.com/philipmw/reactful-dice/pull/1

**Comment by philipmw** [comment]
Amazing support. Thank you.
