### ISSUE TITLE
Support for the experimental syntax 'classProperties' isn't currently enabled

### ISSUE THREAD

**Issue by asgerhallas** [wallabyjs/public#1965]
I'm trying to use Jest in a Expo app, I now get this error when starting Wallaby:

```
SyntaxError: C:\workspace\EnergySystems\inspector\node_modules\react-native\jest\mockComponent.js: Support for the experimental syntax 'classProperties' isn't currently enabled (20:24):​​
​​​​
​​  18 | ​​
​​  19 |   const Component = class extends SuperClass {​​
​​> 20 |     static displayName = 'Component';​​
​​     |                        ^​​
​​  21 | ​​
​​  22 |     render() {​​
​​  23 |       const name =​​
​​​​
​​Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.​​
​​    at Parser.raise (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:4051:15)​​
​​    at Parser.expectPlugin (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5387:18)​​
​​    at Parser.parseClassProperty (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8508:12)​​
​​    at Parser.pushClassProperty (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8472:30)​​
​​    at Parser.parseClassMemberWithIsStatic (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8411:14)​​
​​    at Parser.parseClassMember (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8348:10)​​
​​    at C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8302:16​​
​​    at Parser.withTopicForbiddingContext (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7429:14)​​
​​    at Parser.parseClassBody (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8277:10)​​
​​    at Parser.parseClass (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8248:10)​​
​​    at Parser.parseExprAtom (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:6498:21)​​
​​    at Parser.parseExprSubscripts (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:6104:21)​​
​​    at Parser.parseMaybeUnary (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:6083:21)​​
​​    at Parser.parseExprOps (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5968:21)​​
​​    at Parser.parseMaybeConditional (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5940:21)​​
​​    at Parser.parseMaybeAssign (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5887:21)​​
​​    at Parser.parseVar (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8150:26)​​
​​    at Parser.parseVarStatement (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7964:10)​​
​​    at Parser.parseStatementContent (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7555:21)​​
​​    at Parser.parseStatement (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7505:17)​​
​​    at Parser.parseBlockOrModuleBlockBody (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8073:23)​​
​​    at Parser.parseBlockBody (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8060:10)​​
​​    at Parser.parseBlock (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8049:10)​​
​​    at Parser.parseFunctionBody (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7157:24)​​
​​    at Parser.parseArrowExpression (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7110:10)​​
​​    at Parser.parseParenAndDistinguishExpression (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:6718:12)​​
​​    at Parser.parseExprAtom (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:6473:21)​​
​​    at Parser.parseExprSubscripts (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:6104:21)​​
​​    at Parser.parseMaybeUnary (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:6083:21)​​
​​    at Parser.parseExprOps (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5968:21)​​
​​    at Parser.parseMaybeConditional (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5940:21)​​
​​    at Parser.parseMaybeAssign (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5887:21)​​
​​    at Parser.parseMaybeAssign (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5927:27)​​
​​    at Parser.parseExpression (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5840:21)​​
​​    at Parser.parseStatementContent (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7619:21)​​
​​    at Parser.parseStatement (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7505:17)​​
​​    at Parser.parseBlockOrModuleBlockBody (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8073:23)​​
​​    at Parser.parseBlockBody (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8060:10)​​
​​    at Parser.parseTopLevel (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7470:10)​​
​​    at Parser.parse (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8915:17)​​
​​    at parse (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:10946:38)​​
​​    at parser (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\lib\transformation\normalize-file.js:170:34)​​
​​    at normalizeFile (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\lib\transformation\normalize-file.js:138:11)​​
​​    at runSync (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\lib\transformation\index.js:44:43)​​
​​    at transformSync (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\lib\transform.js:43:38)​​
​​    at transform (C:\workspace\EnergySystems\inspector\node_modules\@babel\core\lib\transform.js:22:38)​​
​​    at Object.process (C:\workspace\EnergySystems\inspector\node_modules\babel-jest\build\index.js:192:79)​​
​​    at ScriptTransformer.transformSource (C:\workspace\EnergySystems\inspector\node_modules\jest-runtime\build\script_transformer.js:314:35)​​
​​    at ScriptTransformer._transformAndBuildScript (C:\workspace\EnergySystems\inspector\node_modules\jest-runtime\build\script_transformer.js:385:40)​​
​​    at ScriptTransformer.transform (C:\workspace\EnergySystems\inspector\node_modules\jest-runtime\build\script_transformer.js:445:19)​​

```

I can not find a working way to add the "@babel/plugin-proposal-class-properties" plugin to the Wallaby config. Running jest from the command line does not fail, and I have not added this plugin to any other config files.

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
    const testPathExp = 'src/**/__tests__/*.{js,jsx}';

    return {
        files: ['tsconfig.json', 'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', `!${testPathExp}`],

        tests: [testPathExp],

        env: {
            type: 'node',
            runner: 'node'
        },

        compilers: {
            '**/*.js?(x)': wallaby.compilers.babel()
        },

        testFramework: 'jest'
    };
};
```

### babel.config.js configuration file

```javascript
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
  };
};
```

### package.json configuration file

```javascript
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "jest-expo": "^32.0.0"
  },
  "private": true,
  "jest": {
    "preset": "jest-expo"
  }
}

```

Visual Studio Code v1.30.2
Windows 10

**Comment by ArtemGovorov** [comment]
Try configuring [Wallaby babel compiler](https://wallabyjs.com/docs/integration/es-next.html#babel-compiler-options) to use the plugin:

```diff
module.exports = function(wallaby) {
    const testPathExp = 'src/**/__tests__/*.{js,jsx}';

    return {
        files: ['tsconfig.json', 'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', `!${testPathExp}`],

        tests: [testPathExp],

        env: {
            type: 'node',
            runner: 'node'
        },

        compilers: {
-            '**/*.js?(x)': wallaby.compilers.babel()
+            '**/*.js?(x)': wallaby.compilers.babel({ plugins: ['@babel/plugin-proposal-class-properties'] })
        },

        testFramework: 'jest'
    };
};
```

If it doesn't help, please lets us know and share a sample GH repo where the issue can be reproduced - we are happy to help with the config.

**Comment by asgerhallas** [comment]
@ArtemGovorov Thanks for the reply! It does not work unfortunately, so here's a very simple failing sample: https://github.com/asgerhallas/wallabyjs_failing_expo_sample

**Comment by jljorgenson18** [comment]
You probably need to also copy over your babel config. You could try adding babel.config.js to your file list.

**Comment by asgerhallas** [comment]
@jljorgenson18 :-O ... it worked! I have tried for hours getting this running. The only change needed was adding the babel.config.js to the file list. The plugin is not needed separately, it's probably already in the preset. 

Thanks a lot! :)

I have updated the repo with the change for future reference.
