### ISSUE TITLE
Failed when parsing cosmiconfig rc type file

### ISSUE THREAD

**Issue by JimiC** [wallabyjs/public#1975]
### Wallaby.js configuration file

```javascript
module.exports = {
  files: [
    "src/**/*.ts",
    "src/schemas/**/*.json",
    "test/helper.ts",
    "test/fixtures/**/*",
    "test/fixtures/**/.integrity.json",
    "test/cosmiconfig/**/*",
    "test/cosmiconfig/**/.*",
    "package.json"
  ],
  tests: [
    "test/**/*.test.ts"
  ],
  filesWithNoCoverageCalculated: [
    "src/cli.ts"
  ],
  preprocessors: {
    "package.json": (file, done) => done(file.rename(`../${file.path}`).content),
    "**/test/fixtures/**/*": (file, done) => done(file.rename(`../${file.path}`).content),
    "**/test/fixtures/**/.integrity.json": (file, done) => done(file.rename(`../${file.path}`).content),
    "**/test/cosmiconfig/**/*": (file, done) => done(file.rename(`../${file.path}`).content),
    "**/test/cosmiconfig/**/.*": (file, done) => done(file.rename(`../${file.path}`).content),
  },
  hints: {
    ignoreCoverage: /wallaby ignore next/
  },
  testFramework: "mocha",
  env: {
    type: "node",
    runner: process.platform === "win32" ? `${process.env.APPDATA}\\nvm\\v6.14.4\\node` : `${require('os').homedir()}/.nvm/versions/node/v6.14.4/bin/node`
  },
  delays: {
    run: 500
  },
  debug: true,
  reportConsoleErrorAsError: true,
  setup: (wallaby) => wallaby.testFramework.ui("bdd")
};
```

### Code editor or IDE name and version

Visual Studio Code v1.30.1

### OS name and version

Linux (Ubuntu Mate 1.20.1 (18.04.1))

---

I have a project where I'm trying to test a `cosmiconfig` rc file (let say it's `.projrc`).
As you can see from the configuration in the `preprocessors` section I'm moving the fixture files up the directory to make their path compatible when testing also via `mocha` `cli`.
While `wallaby` tries to process the `.projrc` file which content is:
```json
{
  source: '',
  verbose: false,
  exclude: []
}
```
it throws the following error:
```
[Error] ​​Failed to parse test/cosmiconfig/rc/.projrc, SyntaxError: Unexpected token (4:9)​​
[Error] ​​    at emitTwo (events.js:126:13)​​
[Error] ​​    at process.emit (events.js:214:7)​​
[Error] ​​    at emit (internal/child_process.js:772:12)​​
[Error] ​​    at _combinedTickCallback (internal/process/next_tick.js:141:11)​​
[Error] ​​    at process._tickCallback (internal/process/next_tick.js:180:9)​​
```

Suspecting that `wallaby` is trying to process the file as a plain text , if I remove the offending `,` from each line the content get changed to:
```
$_$wp(55);
{
    source: {
        $_$w(55, 0), '';
    }
    verbose: {
        $_$w(55, 1), false;
    }
    exclude: {
        $_$w(55, 2), [];
    }
}
$_$wpe(55);
```
which will obviously make my test case fail.

Any suggetions on how to fix this?

**Comment by JimiC** [comment]
@ArtemGovorov Thanks for the solution. You gave me valuable insight on how to tweak the configuration file and make it better.
Now that config section looks like:
```
files: [
    "src/**/*.ts",
    "src/schemas/**/*.json",
    "test/helper.ts",
    { pattern: "test/fixtures/**/*", instrument: false },
    { pattern: "test/fixtures/**/.integrity.json", instrument: false },
    { pattern: "test/cosmiconfig/**/*", instrument: false },
    { pattern: "test/cosmiconfig/**/.*", instrument: false },
    "package.json"
  ],
```
