### ISSUE TITLE
Module in the setupTestFrameworkScriptFile option was not found

### ISSUE THREAD

**Issue by EyalPerry** [wallabyjs/public#1977]
Despite specifying file in files section of wallaby.js, the setup module 'test/local/setup-local' is not copied to the cache (or so it seems).

### Wallaby configuration
```javascript
module.exports = function(wallaby) {
  return {
    files: [
      "src/**/*.ts?(x)",
      "src/**/*.snap",
      "!src/**/*.spec.ts?(x)",
      "test/local/**/*.js",
    ],
    tests: ["src/**/*.spec.ts?(x)"],
    env: {
      type: "node",
      runner: "node"
    },
    compilers: {
      "**/*.(jsx|js|tsx|ts)": wallaby.compilers.babel()
    },
    testFramework: "jest",
    debug: true
  };
};
```

### Jest configuration
```javascript
let testDirPrefix = "src";
let setupFilePostfix = "local";

let testEnvironment = 'jsdom';
const isE2E = process.env.TEST_MODE === 'e2e';

if (isE2E) {
    testDirPrefix = "test/e2e";

    testEnvironment = 'node';
    setupFilePostfix = 'e2e';
}

const config = {
    testEnvironment,
    testMatch: ["<rootDir>" + testDirPrefix + "/**/?(*.)+(spec).(jsx|jsx|ts|tsx)"],
    moduleFileExtensions: ["js", "jsx", "ts", "tsx", "json"],
    setupTestFrameworkScriptFile: "<rootDir>test/"+setupFilePostfix+"/setup-" + setupFilePostfix + ".js",
    moduleNameMapper: {
        "^Components$(.*)$": "<rootDir>src/components$1",
        "^Store(.*)$": "<rootDir>src/store$1",
        "^Util(.*)$": "<rootDir>/src/util$1",
        "^Types(.*)$": "<rootDir>src/types$1",
        "^Assets(.*)$": "<rootDir>assets$1",
        "\\.(css|scss)$": "identity-obj-proxy",
    },
    transform: {
        "^.+\\.(js|jsx|ts|tsx)$": "babel-jest"
    },
    bail: true,
    resetMocks: true,
    resetModules: true,
    timers: "fake"
};

module.exports = config;

```

### Folder structure:

- wallaby.js
- jest.config.js
- test
  - local
     - setup-local.js

### Code editor or IDE name and version

Visual Studio Code v1.30.2

### OS name and version
macOS Mojave 10.14.2

**Comment by ArtemGovorov** [comment]
Try normalizing `<rootDir>` usage in your Jest config as follows:

```diff
const config = {
    testEnvironment,
-   testMatch: ["<rootDir>" + testDirPrefix + "/**/?(*.)+(spec).(jsx|jsx|ts|tsx)"],
+   testMatch: ["<rootDir>/" + testDirPrefix + "/**/?(*.)+(spec).(jsx|jsx|ts|tsx)"],
    moduleFileExtensions: ["js", "jsx", "ts", "tsx", "json"],
-   setupTestFrameworkScriptFile: "<rootDir>test/"+setupFilePostfix+"/setup-" + setupFilePostfix + ".js",
+   setupTestFrameworkScriptFile: "<rootDir>/test/"+setupFilePostfix+"/setup-" + setupFilePostfix + ".js",
    moduleNameMapper: {
-       "^Components$(.*)$": "<rootDir>src/components$1",
+       "^Components$(.*)$": "<rootDir>/src/components$1",
-       "^Store(.*)$": "<rootDir>src/store$1",
+       "^Store(.*)$": "<rootDir>/src/store$1",
        "^Util(.*)$": "<rootDir>/src/util$1",
-       "^Types(.*)$": "<rootDir>src/types$1",
+       "^Types(.*)$": "<rootDir>/src/types$1",
-       "^Assets(.*)$": "<rootDir>assets$1",
+       "^Assets(.*)$": "<rootDir>/assets$1",
        "\\.(css|scss)$": "identity-obj-proxy",
    },
```

**Comment by EyalPerry** [comment]
Hi, thanks for your reply!
Your tip worked, however I now receive the following error, despite not using js - but ts instead:

​​Postprocessor run failure: Failed to parse src/components/menu-component/menu-component.js, SyntaxError: Unterminated JSX contents (14:92)​​
[Error] ​​    at _combinedTickCallback (internal/process/next_tick.js:132:7)​​
[Error] ​​    at process._tickCallback (internal/process/next_tick.js:181:9)​​

*there is a .ts file, and it has NO errors* - tests do pass in jest and everything does work.

**Comment by smcenlly** [comment]
Without a sample repo, the only thing I can think of is that perhaps the error is caused because you're using an older version of TypeScript. 

By default, wallaby.js is using your project local TypeScript compiler version (from the project `node_modules/typescript`), if there’s no local version, then wallaby falls back to the embedded TypeScript compiler version which is v2.0.7.

You can use the latest version of TypeScript by adding as a dev dependency. Alternatively, you can use a different version, by passing the TypeScript compiler via typescript options property ([read more in our docs](https://wallabyjs.com/docs/integration/typescript.html)).

--

If that's not your problem, please provide us with a sample repo, we'd be happy to take a look.

**Comment by smcenlly** [comment]
Closing this issue due to lack of activity. Will re-open if more information is provided.
