### ISSUE TITLE
version 1.0.107 doesn't start

### ISSUE THREAD

**Issue by devmao** [wallabyjs/public#1982]
### Issue description or question

I'm getting this error in console with **v1.0.107** (**v1.0.106 works**) on start:

```
[Error] internal/modules/cjs/loader.js:582
​​[Error]     throw err;
​​[Error]     ^
​​[Error] 
​​[Error] Error: Cannot find module 'C:\Users\mapu\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.107\wallaby\server.js'
​​[Error]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
​​​​[Error]     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
​​​​[Error]     at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
​​[Error]     at startup (internal/bootstrap/node.js:285:19)
​​​[Error]     at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

### Wallaby.js configuration file

```javascript
process.env.BABEL_ENV = 'test'

module.exports = wallaby => ({
  files: [
    'config/**/*.json',
    'shared/**/*.js',
    'client/**/*.js',
    'server/**/*.js',
    { pattern: 'machine-simulator/**/*.js', instrument: false },
    'package.json',
    '!shared/**/*.test.js',
    '!client/.cache/**/*',
    '!client/dist/**/*',
    '!client/**/*.test.js',
    '!server/**/*.test.js',
    '!machine-simulator/**/*.test.js'
  ],

  tests: [
    'client/**/*.test.js',
    'server/**/*.test.js',
    'machine-simulator/**/*.test.js'
  ],

  env: {
    type: 'node',
    runner: 'node'
  },

  testFramework: 'jest',

  compilers: {
    '**/*.js': wallaby.compilers.babel()
  },

  setup () {
    const jestConfig = require('./package.json').jest
    wallaby.testFramework.configure(jestConfig)
  }
})
```

### Code editor or IDE name and version

Visual Studio Code v1.30.2

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
It looks like a corrupted Wallaby installation issue. Please 
- close VS Code, 
- delete all `C:\Users\mapu\.vscode\extensions\wallabyjs.wallaby-vscode-*` files,
- start VS Code and install the latest Wallaby extension,
 and it should work for you.
