### ISSUE TITLE
Error: Debug Failure. False expression: Too many nodes written to output.

### ISSUE THREAD

**Issue by valdestrijus** [wallabyjs/public#2036]
### Issue description or question
1. Debug. Failure
wallaby:project Error: Debug Failure. False expression: Too many nodes written to output.
```
// tsconfig
{
  "compilerOptions": {
    "target": "es5",
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "lib": [
      "dom",
      "es5",
      "es6",
      "es7",
      "es2015.iterable",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src"
  ]
}

```
```
[Info]  Wed, 27 Mar 2019 08:03:06 GMT wallaby:project Instrumenting src/api/api.service.constants.js, via process pool: false
[Info]  Wed, 27 Mar 2019 08:03:06 GMT wallaby:project Error: Debug Failure. False expression: Too many nodes written to output.
[Info]      at extractSingleNode (D:\react_app\node_modules\typescript\lib\typescript.js:64297:18)
[Info]      at visitNode (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:63900:54)
[Info]      at Object.visitEachChild (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:64266:51)
[Info]      at visitCatchClause (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:70006:23)
[Info]      at visitorWorker (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69907:28)
[Info]      at visitor (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69850:20)
[Info]      at visitNode (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:63891:23)
[Info]      at Object.visitEachChild (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:64193:90)
[Info]      at visitorWorker (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69919:31)
[Info]      at visitor (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69850:20)
[Info]      at visitNodes (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:63942:48)
[Info]      at Object.visitEachChild (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:64161:45)
[Info]      at visitorWorker (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69919:31)
[Info]      at visitor (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69850:20)
[Info]      at Object.visitNode (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:63891:23)
[Info]      at transformFunctionBody (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:70277:27)
[Info]      at visitArrowFunction (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:70216:62)
[Info]      at visitorWorker (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69899:28)
[Info]      at visitor (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69850:20)
[Info]      at visitNode (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:63891:23)
[Info]      at Object.visitEachChild (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:64195:154)
[Info]      at visitVariableDeclaration (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:70032:23)
[Info]      at visitorWorker (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69879:28)
[Info]      at visitor (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69850:20)
[Info]      at visitNodes (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:63942:48)
[Info]      at Object.visitEachChild (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:64197:63)
[Info]      at visitorWorker (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69919:31)
[Info]      at visitor (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69850:20)
[Info]      at visitNode (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:63891:23)
[Info]      at Object.visitEachChild (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:64163:111)
[Info]      at visitorWorker (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69919:31)
[Info]      at visitor (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69850:20)
[Info]      at visitNodes (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:63942:48)
[Info]      at Object.visitEachChild (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:64161:45)
[Info]      at visitorWorker (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69919:31)
[Info]      at visitor (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69850:20)
[Info]      at Object.visitNode (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:63891:23)
[Info]      at transformFunctionBody (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:70277:27)
[Info]      at visitFunctionDeclaration (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:70207:19)
[Info]      at visitorWorker (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69895:28)
[Info]      at visitor (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69850:20)
[Info]      at visitNodes (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:63942:48)
[Info]      at visitLexicalEnvironment (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:63975:22)
[Info]      at Object.visitEachChild (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:64279:54)
[Info]      at transformSourceFile (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:69845:30)
[Info]      at transformSourceFileOrBundle (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:65526:57)
[Info]      at D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:1402:86
[Info]      at reduceLeft (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:1102:30)
[Info]      at D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:1402:42
[Info]      at transformRoot (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:81671:82)
[Info]      at Object.map (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:429:29)
[Info]      at Object.transformNodes (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:81658:30)
[Info]      at emitJsFileOrBundle (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:82019:32)
[Info]      at emitSourceFileOrBundle (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:81987:13)
[Info]      at forEachEmittedFile (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:81890:30)
[Info]      at Object.emitFiles (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:81976:9)
[Info]      at emitWorker (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:87463:33)
[Info]      at D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:87423:66
[Info]      at runWithCancellationToken (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:87515:24)
[Info]      at Object.emit (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:87423:20)
[Info]      at Object.getFileEmitOutput (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:88894:34)
[Info]      at Object.getEmitOutput (D:\project_namespace\react_app\node_modules\typescript\lib\typescript.js:118945:23)
[Info]      at C:\Users\R001-MazrimV\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.120\wallaby\server.js:21:10074
[Info]      at baseFor (C:\Users\R001-MazrimV\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.120\wallaby\node_modules\lodash\index.js:1971:13)
[Info]      at baseForOwn (C:\Users\R001-MazrimV\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.120\wallaby\node_modules\lodash\index.js:2025:14)
[Info]      at baseEach (C:\Users\R001-MazrimV\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.120\wallaby\node_modules\lodash\index.js:1814:16)
[Info]      at Function.forEach (C:\Users\R001-MazrimV\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.120\wallaby\node_modules\lodash\index.js:5701:11)
[Info]      at Object.n [as postprocessor] (C:\Users\R001-MazrimV\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.120\wallaby\server.js:21:9880)
[Info]      at C:\Users\R001-MazrimV\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.120\wallaby\server.js:18:8242
[Info]      at Function.promise (C:\Users\R001-MazrimV\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.120\wallaby\node_modules\q\q.js:702:9)
[Info]      at Timeout._onTimeout (C:\Users\R001-MazrimV\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.120\wallaby\server.js:18:7627)
[Info]      at ontimeout (timers.js:436:11)
[Info]      at tryOnTimeout (timers.js:300:5)
[Info]      at listOnTimeout (timers.js:263:5)
[Info]      at Timer.processTimers (timers.js:223:10)
[Info]  Wed, 27 Mar 2019 08:03:06 GMT wallaby:project Test run finished
```
### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  var path = require('path');
  process.env.NODE_ENV = 'test';
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, 'node_modules') +
    path.delimiter +
    path.join(__dirname, 'node_modules/react-scripts/node_modules');
  require('module').Module._initPaths();

  return {
    files: [
      { pattern: 'src/setupTests.js', instrument: false },
      'src/**/*.+(ts|tsx|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!src/**/*.test.ts?(x)',
      '!src/**/*.Story.ts?(x)',
      '!src/serviceWorker.ts',
      '!src/Story/*',
      '!node_modules/*',
    ],

    tests: ['src/**/*.test.ts?(x)'],
    debug: true,
    env: {
      type: 'node',
      runner: 'node',
    },

    preprocessors: {
      '**/*.js?(x)': (file) =>
        require('@babel/core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          presets: ['react-app'],
        }),
    },
    testURL: 'http://localhost/react',

    setup: (wallaby) => {
      const jestConfig = require('react-scripts/scripts/utils/createJestConfig')((p) =>
        require.resolve('react-scripts/' + p),
      );
      Object.keys(jestConfig.transform || {}).forEach(
        (k) => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k],
      );
      delete jestConfig.testEnvironment;
      jestConfig.testURL = 'http://localhost/react';
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest',
  };
};

```

### Code editor or IDE name and version

Visual Studio Code  1.32.3
WebStorm 18.3

### OS name and version
Windows 10

### Additional info
We are installing wallaby manually as our machines is deployed under company proxy.
Wallaby version: 1.0.120, Wallaby server version: 1.0.671
Typescript version in package.json 3.3.3333

Week ago we didint face any issues, now we are facing this.

**Comment by smcenlly** [comment]
This error is coming from TypeScript, there are a few closed issues that reference the same error messages:

https://github.com/Microsoft/TypeScript/issues/12961
https://github.com/Microsoft/TypeScript/issues/13664
https://github.com/Microsoft/TypeScript/issues/21098

A few questions:

1) Did you start experiencing the issue after you just upgraded? 
2) Did you upgrade any other dependencies?
3) Do you get the same error when using `jest` without Wallaby?

If the issue is only affecting Wallaby, we recommend that you roll back to your previous version for now if you need to fix this immediately.

Are you able to provide us with a sample repo that has the same problem?

**Comment by valdestrijus** [comment]
1) yes
2) There was some upgrades on React version and typecsript
3) No

**Comment by ArtemGovorov** [comment]
Unfortunately TypeScript doesn't report the name of the file causing the issue, however we will need the file to troubleshoot the issue.

Please provide the information requested below and also try the following:

1) Is your `tsconfig.json` located at your project's root (and named `tsconfig.json`)?
2) Try the following change in your config and let us know if it changes anything:

```diff
module.exports = function (wallaby) {
  return {
    ...

+   compilers: {
+     '**/*.ts?(x)': wallaby.compilers.typeScript({ useStandardDefaults: true })
+   },

    ...
  };
};
```

3) Try the following change in your Wallaby config, if the issue is reproduced with it, then please share the file that is reported last (prior to the error) in Wallaby console.
```diff
module.exports = function (wallaby) {
  return {
    ...

+   compilers: {
+     '**/*.ts?(x)': wallaby.compilers.typeScript({ isolatedModules: true })
+   },

    ...
  };
};
```
If you have difficulties to locate the file, then according to the TS stack trace, the file in question should have the following things in its code:
- a function declaration,
- a variable declared somewhere inside the function, the variable is an arrow function with some catch clause in it.

**Comment by ArtemGovorov** [comment]
Forgot to mentioned, the issue is not related to Wallaby updates. It looks like it is either related to TypeScript version update, or, more likely, an update to some file(s) that are now causing TypeScript compilation issue.

**Comment by smcenlly** [comment]
@valdestrijus - did you manage to get this working? Let us know if you need more help.

**Comment by valdestrijus** [comment]
Hello, thanks for help. We managed to solve this, indeed it was problem in our code.

We had this interesting try catch block:

```javascript
 try {
      ...
    } catch ({ response = null, ...exception }) { // babel error here, changed to catch (e)
      setError(exception);
    } finally {
...
    }

```

Strange thing was that typescript compiler did not throw anything and it was completely valid. The error happened in wallaby only.

**Comment by ArtemGovorov** [comment]
Thanks for the update. Looks like you guys have found TypeScript compiler issue. We can easily reproduce it without Wallaby in TS playground:

<img width="664" alt="Screen Shot 2019-03-28 at 5 47 36 pm" src="https://user-images.githubusercontent.com/979966/55140483-f1c07b80-5183-11e9-90ba-cf1483029d30.png">

I have created the issue in TypeScript repo: https://github.com/Microsoft/TypeScript/issues/30627.
