### ISSUE TITLE
`Error: Cannot find module 'ws/lib/Sender.fallbacks.js'`

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2042]
Happens after a restored my MBP from a CCC backup (excluding `node_modules`)

I reinstalled from zip and it didn't fix it.

IntelliJ

```
Error: Cannot find module 'ws/lib/Sender.fallbacks.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
```

**Comment by vjpr** [comment]
Solved.

```
rm -rf ~/Library/Caches/IntelliJIdea2019.1/wallaby
```
