### ISSUE TITLE
Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by acorretti** [wallabyjs/public#2046]
### Issue description or question

Running into an issue just starting up Wallaby. Already discarded having two tests or blocks with the same description, I don't know what else to look at.

### Wallaby.js configuration file

```javascript
[Error] Runtime error: TypeError: Cannot read property 'push' of undefined 
[Error]     at WebSocket.emit (events.js:182:13) 
[Error]     at afterWrite (_stream_writable.js:483:3) 
[Error]     at onwrite (_stream_writable.js:474:7) 
[Error]     at InflateRaw.afterTransform (_stream_transform.js:94:3) 
[Error]     at Zlib.processCallback (zlib.js:625:8) 
```

### Code editor or IDE name and version

Visual Studio Code v1.32.3

### OS name and version

OSX

**Comment by smcenlly** [comment]
Could you please set `debug` to `true` in your wallaby.js configuration file, run again and provide us with the output of the Wallaby console.

**See below for an example of how to set `debug` to `true`:**

```javascript
module.exports = function () {
  return {
    files: [
      ...
    ],

    tests: [
      ...
    ],

    debug: true
  };
};
```

Once you have set this and you re-run wallaby, You should additional information about the test execution progress, which can be viewed by going to the `Wallaby.js Console` Output Channel (View - Output). Please note: this is different to the `Wallaby.js Tests` Output Channel.

**Comment by acorretti** [comment]
Preprocessing goes fine and right when workers start execution the following message prints from all of them:

```
[Info]  Wed, 03 Apr 2019 06:22:28 GMT wallaby:workers [worker #5, session #nq9mp] Running tests in sandbox
[Info]  Wed, 03 Apr 2019 06:22:28 GMT wallaby:workers Sandbox (active) [c6uzp] error: Cannot read property 'push' of undefined
[Info]  Wed, 03 Apr 2019 06:22:28 GMT wallaby:workers Failed to map the stack to user code, entry message: Cannot read property 'push' of undefined, stack: TypeError: Cannot read property 'push' of undefined
[Info]      at eval (eval at module.exports (/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.122/wallaby/runners/node/bootstrap.js:14:44), <anonymous>:3:40)
[Info]      at eval (eval at module.exports (/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.122/wallaby/runners/node/bootstrap.js:14:44), <anonymous>:5:6)
[Info]      at module.exports (/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.122/wallaby/runners/node/bootstrap.js:14:44)
[Info]      at b.in:run (/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.122/wallaby/server.js:16:29893)
[Info]      at WebSocket.<anonymous> (/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.122/wallaby/server.js:16:28681)
[Info]      at WebSocket.emit (events.js:182:13)
[Info]      at Receiver.ontext (/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.122/wallaby/node_modules/ws/lib/WebSocket.js:841:10)
[Info]      at /Users/user/.vscode/ext
(x6)
[Info]  Wed, 03 Apr 2019 06:22:28 GMT wallaby:workers [c6uzp] Run 0 test(s), skipped 0 test(s)
[Info]  Wed, 03 Apr 2019 06:22:28 GMT wallaby:workers [je6m5] Run 0 test(s), skipped 0 test(s)
[Info]  Wed, 03 Apr 2019 06:22:28 GMT wallaby:workers [nq9mp] Run 0 test(s), skipped 0 test(s)
[Info]  Wed, 03 Apr 2019 06:22:28 GMT wallaby:workers [i8occ] Run 0 test(s), skipped 0 test(s)
[Info]  Wed, 03 Apr 2019 06:22:28 GMT wallaby:workers [7xo1x] Run 0 test(s), skipped 0 test(s)
[Info]  Wed, 03 Apr 2019 06:22:28 GMT wallaby:workers [snudt] Run 0 test(s), skipped 0 test(s)
[Info]  Wed, 03 Apr 2019 06:22:28 GMT wallaby:workers [i8occ] Sandbox is responsive, closing it
...
```

Help appreciated!

Thank you

**Comment by ArtemGovorov** [comment]
It looks like there's an issue with your Wallaby config file, presumably with `setup` function code. Could you please share your Wallaby config file?

**Comment by smcenlly** [comment]
@acorretti - did you manage to solve your issue?

**Comment by acorretti** [comment]
Sorry guys, I forgot to come back on this.

Not solved yet but I’ve ruled out being a problem on Wallaby, but on some change in our project. Didn’t manage to get time to delve into it, though.

I’m going to close the issue and come back once I get to the root of it.

Thanks!
