### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined 

### ISSUE THREAD

**Issue by blogwebpl** [wallabyjs/public#2062]
### Issue description or question
Wallaby stop working when I installed  "sort-class-members-codemod": "^0.5.1". 
wallaby 0 failing tests, 0 passing 
but jest work correctly  109 passed, 109 total

`TypeError: Cannot read property 'bind' of undefined 
    at Runtime._createJestObjectFor (/Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runtime/build/index.js:925:38) 
    at Runtime._execModule (/Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runtime/build/index.js:702:12) 
    at Runtime.requireModule (/Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runtime/build/index.js:376:14) 
    at new Runtime (/Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runtime/build/index.js:219:14) 
    at /Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runner/build/run_test.js:98:15 
    at Generator.next (<anonymous>) 
    at step (/Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runner/build/run_test.js:315:30) 
    at /Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runner/build/run_test.js:334:14 
    at new Promise (<anonymous>) 
    at /Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runner/build/run_test.js:312:12 
    at runTestInternal (/Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runner/build/run_test.js:239:17) 
    at /Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runner/build/run_test.js:354:23 
    at Generator.next (<anonymous>) 
    at step (/Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runner/build/run_test.js:315:30) 
    at /Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runner/build/run_test.js:334:14 
    at new Promise (<anonymous>) 
    at /Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runner/build/run_test.js:312:12 
    at runTest (/Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runner/build/run_test.js:367:18) 
    at /Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runner/build/index.js:116:28 
    at Generator.next (<anonymous>) 
    at step (/Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runner/build/index.js:37:30) 
    at /Users/Tomek/Nextcloud/Praca/przewoznik.info/root/client/node_modules/jest-runner/build/index.js:48:15 
    at process._tickCallback (internal/process/next_tick.js:68:7) 
`

When  remove sort-class-members-codemod from devDependencies - wallaby works.

'  "devDependencies": {
    "enzyme": "^3.9.0",
    "enzyme-adapter-react-16": "^1.12.1",
    "eslint-plugin-sort-class-members": "^1.4.0",
    "jsinspect": "^0.12.7",
    "sort-class-members-codemod": "^0.5.1"
  },'

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
	process.env.NODE_ENV = 'test';
	const path = require('path');
	process.env.NODE_PATH +=
		path.delimiter +
		path.join(__dirname, 'node_modules') +
		path.delimiter +
		path.join(__dirname, 'node_modules/react-scripts/node_modules');
	require('module').Module._initPaths();

	return {
		files: [
			'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
			'!src/**/*.test.js?(x)'
		],

		env: {
			runner: 'node',
			type: 'node'
		},
		filesWithNoCoverageCalculated: [ 'src/serviceWorker.js', 'src/index.js', 'src/config.js', 'src/axios.js', 'src/__mocks__/axios.js' ],
		tests: [ 'src/**/*.test.js?(x)' ],

		compilers: {
			'**/*.js?(x)': wallaby.compilers.babel({
				presets: [ 'react-app' ]
			})
		},

		testFramework: 'jest',
		setup: (wallaby) => {
			const jestConfig = require('react-scripts/scripts/utils/createJestConfig')((p) => require.resolve(`react-scripts/${p}`));
			Object.keys(jestConfig.transform || {}).forEach((k) => k.indexOf('^.+\\.(js|jsx') !== -1 && void delete jestConfig.transform[ k ]);
			delete jestConfig.testEnvironment;
			wallaby.testFramework.configure(jestConfig);
		}
	};
};

```

### Code editor or IDE name and version

Visual Studio Code v1.33.1

### OS name and version
OSX 10.14.4

**Comment by smcenlly** [comment]
Unfortunately we can't reproduce the problem. Can you please provide us with a sample repo that has the same issue?

What we did:
1) Created a new project using `create-react-app`
2) Updated our project to use the `devDependencies` you provided above
3) Run `wallaby.js` with the same configuration file you provided above

**Comment by blogwebpl** [comment]
`git clone https://github.com/blogwebpl/test.git
cd test
yarn`

1. yarn test - result 109 passed, 109 total
2. start visual studio
3. start wallaby

result: 
0 failing tests, 0 passing 
TypeError: Cannot read property 'bind' of undefined

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. We have used `npm` instead of `yarn`, that is why we couldn't reproduce it.

The issue is fixed and the fix is published in [the latest Wallaby core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
