### ISSUE TITLE
Wallaby doesn't work with Vue-enterprise-boilerplate:  SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by elektrobober** [wallabyjs/public#2087]
### Issue description or question
Hi, i'm trying integrate Wallaby with [Vue-enterprise-boilerplate](https://github.com/chrisvfritz/vue-enterprise-boilerplate), and face this issue.

```
/Desktop/test/vue-enterprise-boilerplate/tests/unit/setup.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Vue from 'vue';
             ^^^

    SyntaxError: Unexpected identifier
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:400:17)
      at Runtime.u._wallabyReplaced.c.requireModule (../../../Library/Caches/WebStorm2019.1/wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:25612)
```
And if I run test from Webstorm or from terminal it will executed as expected. **Widw**?

### Wallaby.js configuration file

```javascript
module.exports = (wallaby) => {
  process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true;

  const compiler = wallaby.compilers.babel({
    presets: [['@vue/app', { modules: 'commonjs' }]],
  });

  return {
    files: [
      'src/**/*',
      'jest.config.js',
      'package.json',
      'aliases.config.js',
      'jsconfig.template.js',
      './.prettierrc.js',
      { pattern: 'src/**/*.unit.js', ignore: true },
    ],

    tests: ['**/*.unit.js'],

    env: {
      type: 'node',
      runner: 'node',
    },

    compilers: {
      '**/*.js': compiler,
      '**/*.vue': require('wallaby-vue-compiler')(compiler),
    },

    preprocessors: {
      '**/*.vue': (file) =>
        require('vue-jest').process(file.content, file.path),
    },

    setup: function(wallaby) {
      const jestConfig = require('./package').jest || require('./jest.config');
      function replaceJestRootDir(config) {
        return Object.entries(config)
          .map(([configKey, configValue]) => {
            if (typeof configValue === 'string') {
              return [
                configKey,
                configValue.replace(
                  '<rootDir>',
                  wallaby.localProjectDir.slice(0, -1)
                ),
              ];
            }
            if (Array.isArray(configValue)) {
              return [
                configKey,
                configValue.map((el) =>
                  el.replace('<rootDir>', wallaby.localProjectDir.slice(0, -1))
                ),
              ];
            }
            if (configValue instanceof Object) {
              return [configKey, replaceJestRootDir(configValue)];
            }
            return [configKey, configValue];
          })
          .reduce((acc, [key, val]) => {
            return {
              ...acc,
              [key]: val,
            };
          }, {});
      }
      const updatedJestConfig = replaceJestRootDir(jestConfig);
      wallaby.testFramework.configure(updatedJestConfig);
    },

    testFramework: 'jest',

    debug: true,
  };
};

```

### Jest config

As is in [repo](https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/jest.config.js)

### Code editor or IDE name and version

WebStorm 2019.1

### OS name and version
OSX 10.14

**Comment by ArtemGovorov** [comment]
This sample should work for you: https://wallabyjs.com/docs/integration/vue.html#vuecli-v3x because the `Vue-enterprise-boilerplate` has a very similar structure. The only change you need to make to the sample config is to add `tests/**` folders to your `files` list because Jest initialisation files are located there.

Here is the full config that works for me on a fresh `Vue-enterprise-boilerplate`:

```js
module.exports = (wallaby) => {
    process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true;

    const compiler = wallaby.compilers.babel({
        presets: [['@vue/app', { modules: 'commonjs' }]],
    });

    return {
        files: [
            'src/**/*',
            'tests/unit/**',
            'tests/mock-api/**',
            'jest.config.js',
            'package.json',
            'aliases.config.js',
            'jsconfig.template.js',
            './.prettierrc.js',
            { pattern: 'src/**/*.unit.js', ignore: true },
        ],

        tests: ['src/**/*.unit.js'],

        env: {
            type: 'node',
            runner: 'node',
        },

        compilers: {
            '**/*.js': compiler,
            '**/*.vue': require('wallaby-vue-compiler')(compiler),
        },

        preprocessors: {
            '**/*.vue': (file) =>
                require('vue-jest').process(file.content, file.path),
        },

        setup: function(wallaby) {
            const jestConfig = require('./package').jest || require('./jest.config');
            jestConfig.transform = {};
            wallaby.testFramework.configure(jestConfig);
        },

        testFramework: 'jest',

        debug: true,
    };
};
```

<img width="905" alt="Screen Shot 2019-05-28 at 11 15 28 am" src="https://user-images.githubusercontent.com/979966/58444115-ebc22900-8139-11e9-9cb1-2c92cb1305fb.png">
