### ISSUE TITLE
Cannot find module '../index'

### ISSUE THREAD

**Issue by mdreizin** [wallabyjs/public#209]
Hello,

I have just tried `wallaby` and it didn't work for me :(

`platform`

OS X 10.10.4
WebStorm 10.0.4

`log`
```
wallaby.js started
core v1.0.82
Runtime error: Error: Cannot find module '../index'
    at Function.Module._resolveFilename (module.js:316:15)
    at Function.Module._load (module.js:258:25)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/Users/mdreizin/Library/Caches/WebStorm10/wallaby/projects/6920c693b88d1811/instrumented/test/config.spec.js:3:63)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
Runtime error: Error: Cannot find module '../index'
    at Function.Module._resolveFilename (module.js:316:15)
    at Function.Module._load (module.js:258:25)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/Users/mdreizin/Library/Caches/WebStorm10/wallaby/projects/6920c693b88d1811/instrumented/test/multiConfig.spec.js:3:66)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
Runtime error: Error: Cannot find module '../index'
    at Function.Module._resolveFilename (module.js:316:15)
    at Function.Module._load (module.js:258:25)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/Users/mdreizin/Library/Caches/WebStorm10/wallaby/projects/6920c693b88d1811/instrumented/test/index.spec.js:3:116)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
Finished executing 0 affected test(s)
```

`wallaby.json`
```json
{
  "files": [
    "lib/*.js"
  ],

  "tests": [
    "test/*spec.js"
  ],
  "testFramework": "mocha",
  "env": {
    "type": "node"
  }
}
```

`dir structure`
```
.
├── LICENSE
├── README.md
├── index.js
├── lib
│   ├── config.js
│   ├── multiConfig.js
│   └── util.js
├── test
│   ├── config.spec.js
│   ├── index.spec.js
│   └── multiConfig.spec.js
└── wallaby.json
```

`test/config.spec.js`

```
'use strict';

var expect = require('expect.js'),
    webpackConfig = require('../index');
```

For more details please look at https://github.com/mdreizin/webpack-config

**Comment by ArtemGovorov** [comment]
Hello,

the index.js file is [missing](http://wallabyjs.com/docs/intro/troubleshooting.html#39-cannot-find-module-39-or-39-file-not-found-39) in the files list:

``` json
"files": [
    "lib/*.js",
    "index.js"
  ],
```

Please let me know if it works for you.

**Comment by mdreizin** [comment]
@ArtemGovorov Thanks, I missed that.
