### ISSUE TITLE
ENOENT for Jest Mocks with create-react-app and react-scripts v3.0.1

### ISSUE THREAD

**Issue by thehig** [wallabyjs/public#2090]
## Outline

I have a project that was scaffolded with `create-react-app` and uses `jest` in testing. I have used wallaby in the past and had great success, but returning after a few months away things no longer seem to be working for me.

My tests are passing in Jest successfully from CLI. I have recreated my Wallaby-JS config based on the latest documentation. I have renewed my Wallaby licence to ensure everything was as up-to-date as possible.

I was previously using `NODE_PATH=src` to allow for absolute-path imports, but have recently switched to using the jsconfig approach as `NODE_PATH` is being deprecated.

## The Problem

The error that I am encountering is:

```
Error: ENOENT: no such file or directory, stat 'D:\...snipped...\frontend\.\src\spec\__mocks__\react.js'
at Object.<anonymous> ​src/spec/test-setup.js:1​
```

There is a file located at `\frontend\src\spec\__mocks__\react.js`, however the ENOENT path above has an extra `\.\` in it that I can't track down.

I have included my `__mocks__/react.js`, `test-setup.js` and `jsconfig.json` below:

### __mocks__/react.js

```javascript
/* eslint-disable no-undef */

const react = require('react');
// Resolution for requestAnimationFrame not supported in jest error :
// https://github.com/facebook/react/issues/9102#issuecomment-283873039
global.window = global;
window.addEventListener = () => {};
window.requestAnimationFrame = () => {
  throw new Error('requestAnimationFrame is not supported in Node');
};

module.exports = react;
```

### test-setup.js

```javascript
import Adapter from 'enzyme-adapter-react-16';
import { configure } from 'enzyme';

configure({ adapter: new Adapter() });

var localStorageMock = (function() {
  var store = {};
  return {
    getItem: function(key) {
      return store[key];
    },
    setItem: function(key, value) {
      store[key] = value && value.toString();
    },
    clear: function() {
      store = {};
    },
    removeItem: function(key) {
      delete store[key];
    }
  };
})();
Object.defineProperty(window, 'localStorage', { value: localStorageMock });
```

### jsconfig.json

```javascript
{
  "compilerOptions": {
    "target": "ES6",
    "module": "commonjs",
    "baseUrl": "src/",
    "allowSyntheticDefaultImports": true
  },
  "exclude": [
    "node_modules",
    "**/node_modules/*",
    "brands", "scripts", "status"
  ]
}
```

### Wallaby.js configuration file

```javascript
/*
Sources
https://github.com/wallabyjs/public/issues/1472
https://github.com/thehig/storyshots-css-wallaby
*/

/* eslint-disable no-undef */
module.exports = function(wallaby) {
  // Babel, jest-cli and some other modules may be located under
  // react-scripts/node_modules, so need to let node.js know about it
  var path = require('path');
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, 'node_modules') +
    path.delimiter +
    path.join(__dirname, 'node_modules/react-scripts/node_modules') +
    path.delimiter +
    path.join(wallaby.projectCacheDir, 'src');

  require('module').Module._initPaths();

  // Babel needs this
  process.env.NODE_ENV = 'development';

  const babelCompiler = wallaby.compilers.babel({
    babel: require('@babel/core'),
    presets: ['react-app']
  });

  return {
    files: [
      // Include all files required to run the app
      // Wallaby will copy these files internally to add instrumentation
      // Everything required to run Storybook is required to be able to run storyshots
      '.storybook/**/*.js',
      'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      // But don't include the tests that will be triggering
      '!src/**/*.spec.js'
    ],
    tests: [
      // '!src/spec/storyshots.spec.js', // Can be useful to disable the storyshots tests as they are long running
      '!src/spec/screenshots/**/*.*', // Don't try and run screenshots with wallaby
      'src/**/*.spec.js'
    ],
    filesWithNoCoverageCalculated: [
      'node_modules/**/*.*',
      '.storybook/**/*.js',
      'src/**/*.stories*.js',

      'src/**/*.spec*.js',
      'src/spec/**/*.*',

      'src/registerServiceWorker.js'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    compilers: {
      '**/*.js?(x)': babelCompiler,
      // 'dot' folders are not included by the above
      '.storybook/**/*.js': babelCompiler
    },

    reportConsoleErrorAsError: true,
    hints: {
      // https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-code-blocks-inside-a-file
      ignoreCoverage: /ignore coverage/ // or /istanbul ignore next/, or any RegExp
    },

    setup: wallaby => {
      const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(
        p => require.resolve('react-scripts/' + p)
      );
      Object.keys(jestConfig.transform || {}).forEach(
        k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]
      );
      delete jestConfig.testEnvironment;
      jestConfig.setupTestFrameworkScriptFile =
        '<rootDir>/src/spec/test-setup.js';

      wallaby.testFramework.configure(jestConfig);
    }
  };
};
```

### Code editor or IDE name and version

Version: 1.34.0 (system setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

### OS name and version

Windows

**Comment by smcenlly** [comment]
I reproduced your issue, by doing the following:

1) Create a new project using `create-react-app` (v3.0.1)
```
npx create-react-app issue-2090
```

2) Add the same `jsconfig.json` that you provided
3) Change generated `App.js` to use absolute reference instead of relative path for logo and css.

---

The fix to the problem is to ensure that your `jsconfig.js` is included in the `files` section of your wallaby configuration. In the wallaby `setup` function, `createJestConfig` is attempting to load the file, but can't find it, which is why the module resolution fails. 

My configuration ended up looking like this

```diff
module.exports = function (wallaby) {

  // Babel, jest-cli and some other modules may be located under
  // react-scripts/node_modules, so need to let node.js know about it
  var path = require('path');
  process.env.NODE_PATH +=
      path.delimiter +
      path.join(__dirname, 'node_modules') +
      path.delimiter +
      path.join(__dirname, 'node_modules/react-scripts/node_modules');
  require('module').Module._initPaths();

  return {
      files: [
+         'jsconfig.json',
          'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
          '!src/**/*.test.js?(x)'
      ],

      tests: ['src/**/*.test.js?(x)'],

      env: {
          type: 'node',
          runner: 'node'
      },

      compilers: {
          '**/*.js?(x)': wallaby.compilers.babel({
              presets: ['react-app']
          })
      },

      setup: wallaby => {
          const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(p => require.resolve('react-scripts/' + p));
          console.log(jestConfig);
          Object.keys(jestConfig.transform || {}).forEach(k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]);
          delete jestConfig.testEnvironment;
          wallaby.testFramework.configure(jestConfig);
      },

      testFramework: 'jest'
  };
};
```

**Comment by thehig** [comment]
Thanks for the response, however this doesn't solve the issue for me.

The 'fix' in this scenario seems to work because nothing is attempting to load the `test-setup.js` file. If you add `jestConfig.setupTestFrameworkScriptFile = '<rootDir>/src/spec/test-setup.js';` to force the `test-setup` to be loaded, the same error occurs.

**Comment by thehig** [comment]
I noticed this in the Wallaby console

```
[Info]  console.log: FAIL src/shared/api/duck.spec.js
[Info]  console.log:   ● Test suite failed to run
[Info]      ENOENT: no such file or directory, stat 'D:\...snipped....\frontend\C:\...snipped....\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.128\projects\f6c5e0f61121fcdf\instrumented\src\spec\__mocks__\react.js'
[Info]        at Object.statSync (node_modules/graceful-fs/polyfills.js:295:24)
[Info]        at getScriptCacheKey (node_modules/@jest/transform/build/ScriptTransformer.js:693:39)
[Info]        at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:504:24)
[Info]        at Runtime.u._wallabyReplaced.c.requireModule (C:/...snipped..../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.128/wallaby/runners/node/jest@0.4.3/initializer.js:14:25612)
[Info]        at Object.<anonymous> (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:2:1)
[Info]        at Runtime.u._wallabyReplaced.c.requireModule (C:/...snipped..../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.128/wallaby/runners/node/jest@0.4.3/initializer.js:14:25612)
[Info]        at Object.require (node_modules/enzyme-adapter-react-16/src/index.js:2:18)
[Info]        at Runtime.u._wallabyReplaced.c.requireModule (C:/...snipped..../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.128/wallaby/runners/node/jest@0.4.3/initializer.js:14:25612)
[Info]        at Object.<anonymous> (C:/...snipped..../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.128/projects/f6c5e0f61121fcdf/instrumented/src/spec/test-setup.js:4:64)
[Info]        at Runtime.u._wallabyReplaced.c.requireModule (C:/...snipped..../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.128/wallaby/runners/node/jest@0.4.3/initializer.js:14:25612)
[Info]            at Array.forEach (<anonymous>)
```

specifically this line

```
[Info]      ENOENT: no such file or directory, stat 'D:\...snipped....\frontend\C:\...snipped....\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.128\projects\f6c5e0f61121fcdf\instrumented\src\spec\__mocks__\react.js'
```

which may just be an 'artifact' of the Wallaby instrumentation process, but I thought it might be relevant

**Comment by thehig** [comment]
I've created a repo [here](https://github.com/thehig/wallabyjs--2090) that demonstrates the bug.

It only occurs when the wallabyjs extension folder is on a different drive letter from the codebase. I suspect there's some kind of "relative path traversal" trying to happen, but that it doesn't work in the case of a path traversal that can't be relatively performed.

**Comment by smcenlly** [comment]
Thanks for the additional information. We have found and fixed the root cause, which was a conflict between jest and wallaby. Jest expects all files to be on the same drive, while wallaby does some patching to minimize the files that are copied to its local cache directory, which was the cause of the problem.

Please update your wallaby to use wallaby core v1.0.692 to fix the problem. If wallaby does not update automatically, you can perform a [forced update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by thehig** [comment]
Fixed after a forced update. Thank you!
