### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by kennethlynne** [wallabyjs/public#2103]
### Issue description or question
Running `ts-mocha --paths lib/**/*.spec.ts` works just fine, but running wallaby just crashes with the following error:

```
[Info]  Started Wallaby.js Core v1.0.695
[Error] Runtime error: ./lib/testCase.spec.js:2 
[Error] import { assert } from 'chai'; 
[Error]        ^ 
[Error] SyntaxError: Unexpected token { 
[Error]     at new Script (vm.js:80:7) 
[Error]     at createScript (vm.js:274:10) 
[Error]     at Object.runInThisContext (vm.js:326:10) 
[Error]     at Module._compile (internal/modules/cjs/loader.js:664:28) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:600:32) 
[Error]     at tryModuleLoad (internal/modules/cjs/loader.js:539:12) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:531:3) 
[Error]     at Module.require (internal/modules/cjs/loader.js:637:17) 
[Error]     at require (internal/modules/cjs/helpers.js:22:18) 
[Error]     at test-case/node_modules/mocha/lib/mocha.js:330:36 
[Error]     at Array.forEach (<anonymous>) 
[Error]     at Mocha.loadFiles (test-case/node_modules/mocha/lib/mocha.js:327:14) 
[Error]     at Mocha.run (test-case/node_modules/mocha/lib/mocha.js:804:10) 
[Error]     at WebSocket.emit (events.js:189:13) 
[Error]     at afterWrite (_stream_writable.js:480:3) 
[Error]     at onwrite (_stream_writable.js:471:7) 
[Error]     at InflateRaw.afterTransform (_stream_transform.js:94:3) 
[Error]     at Zlib.processCallback (zlib.js:626:8) 
```
### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      'lib/**/*.ts',
      { pattern: './tsconfig.json', load: true },
      { pattern: './package.json', instrument: false, load: true, ignore: false },
      { pattern: './**/*.spec.ts', instrument: false, load: false, ignore: true },
    ],
    tests: ['lib/**/*.spec.ts'],
    env: {
      type: 'node',
    },
    testFramework: 'mocha',
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.35.0

### OS name and version
OSX 10.14.5

**Comment by kennethlynne** [comment]
Here is a minimum reproducible test case https://github.com/kennethlynne/wallaby-test-case

**Comment by smcenlly** [comment]
Thanks for the sample repo!

We can see that your problem is caused by the default behavior of `ts-node` which is used by `ts-mocha`.

When `ts-mocha` runs your project, it changes a few of your TypeScript compiler settings that wallaby does not:

**[ts-node code](https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L449)**
```
function fixConfig (ts: TSCommon, config: _ts.ParsedCommandLine) {
...
  if (config.options.module === undefined) {
    config.options.module = ts.ModuleKind.CommonJS
  }
...
}
```

You can fix wallaby by explicitly overriding the module type to be commonjs (see below):

**Updated `wallaby.js` Configuration**

```diff
module.exports = function(wallaby) {
  return {
    files: [
      'lib/**/*.ts',
      { pattern: './tsconfig.json', load: true },
      { pattern: './package.json', instrument: false, load: true, ignore: false },
      { pattern: './**/*.spec.ts', instrument: false, load: false, ignore: true },
    ],
+   compilers: {
+     '**/*.ts?(x)': wallaby.compilers.typeScript({
+       module: 'commonjs',
+     })
    },
    tests: ['lib/**/*.spec.ts'],
    env: {
      type: 'node',
    },
    testFramework: 'mocha',
  };
};
```

**Comment by kennethlynne** [comment]
Thank you so much!
