### ISSUE TITLE
Problems with ngCli project library requirements

### ISSUE THREAD

**Issue by TheTiGuR** [wallabyjs/public#2104]
### Issue description or question
*Primary* problem: 
Trying to run wallaby against the base app of an Angular CLI 7 generated app results in a variety of errors.
1. With a default wallaby config  (minus less/sass loaders), I get the following:
` 
Uncaught SyntaxError: Unexpected token ! 
  at ​src/app/components/users/add-edit.component.ts:62​
Uncaught Error: Cannot find module '.\src\wallabyTest.js' 
Uncaught Error: Cannot find module '12' 
Uncaught Error: Cannot find module '35' 
Module not found: Error: Can't resolve 'myLib' in '.\src\app'ModuleNotFoundError: Module not found: Error: Can't resolve 'myLib' in '.\src\app' 
`
The unexpected token appears to be a red herring as the code referenced is correct. The wallabyTest.ts exists. The library myLib exists both compiled in the dist folder and in projects/myLib
------
2. If I change the entryPatterns to this: 
`entryPatterns: ['src/wallabyTest.ts', 'src/**/*spec.ts', 'projects/myLib/src/lib/**/*spec.js'],` 
and add the library to the resolve.modules:
`path.join(wallaby.projectCacheDir, 'projects/myLib/src'),
        path.join(wallaby.projectCacheDir, 'projects/myLib/src/lib'),`
I get some semblance of tests running:
`
Specified entry pattern "src/wallabyTest.ts" does not match any file. 
Specified entry pattern "src/**/*spec.ts" does not match any file. 
  
  ​​​​BadgeComponent should create​​​​ ​​​[11 ms]​​​​
     
    Zone is needed for the async() test helper but could not be found. Please make sure that your environment includes zone.js/dist/zone.js 
`

I'm not sure where to go from here to get a working config, but the errors don't seem to be leading me to what I need, so any help would be appreciated. I am unable to provide a sample repo, but hopefully the information that helps resolve the secondary problem may prove useful to what I am trying to achieve. Thanks!

*Secondary* problem:
In trying to  diagnose the above problem, I pulled down the ngCli sample repo to start with a clean base and see what I could figure out. As-is, tests run as expected. I then create a new library ('ng generate library foo'), added a method on the sample service (getSomething() { return 'something'} ), import the library into the base app.module, make a call to that method, and it fails with this error:
`Uncaught Error: Cannot set base providers because it has already been called 
at http://localhost:57652/____wallaby-bundle.js?1559851917288&wallabyFileId=bundle:3586 `
The only change to the wallaby config was to remove sass/less loaders because they weren't installed in the package.json

### Code editor or IDE name and version
Visual Studio Code v1.35

### OS name and version
Windows 10 - current

**Comment by ArtemGovorov** [comment]
> Primary problem:

> With a default wallaby config (minus less/sass loaders),

Your `projects` folder (or `projects/myLib`) needs to be added to the `files` list. Also the following change is required in your Wallaby webpack part of the config:

```diff
    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
+       path.join(wallaby.projectCacheDir, 'projects'),
        'node_modules'
      ]
    },
```

> 2. If I change the entryPatterns to this:

Entry patterns are suppose to have `.js` extension, no need to change it.

> Secondary problem

We'll look into this separately.

**Comment by NikGovorov** [comment]
Hi @TheTiGuR,

Please try the following config:

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js',
      'projects/myLib/src/lib/**/*spec.js' // ADDED
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.(jpg|png|svg)$/, loader: 'raw-loader'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ],
      alias: {
        'myLib': path.join(wallaby.projectCacheDir, 'projects/myLib/src/public-api') // ADDED
      }
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.+(ts|css|html|json|svg)', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true},
      {pattern: 'projects/myLib/src/**/*.+(ts|css|html|json|svg)', load: false}, // ADDED
      {pattern: 'projects/myLib/src/**/*.d.ts', ignore: true}, // ADDED
      {pattern: 'projects/myLib/src/**/*spec.ts', ignore: true} // ADDED
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true},
      {pattern: 'projects/myLib/src/**/*spec.ts', load: false} // ADDED
    ],

    testFramework: 'jasmine',

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

**Comment by TheTiGuR** [comment]
Still the same error. Here is my complete config, just in case I did something wrong
`
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./tsconfig.spec.json').compilerOptions
);

module.exports = function(wallaby) {
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: ['src/wallabyTest.js', 'src/**/*spec.js', 'projects/myLib/src/lib/**/*spec.js'],
    module: {
      rules: [
        { test: /\.css$/, loader: ['raw-loader'] },
        { test: /\.html$/, loader: 'raw-loader' },
        {
          test: /\.ts$/,
          loader: '@ngtools/webpack',
          include: /node_modules/,
          query: { tsConfigPath: 'tsconfig.json' }
        },
        { test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/ },
        { test: /\.(jpg|png|svg)$/, loader: 'raw-loader' }
      ]
    },
    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ],
      alias: {
        myLib: path.join(wallaby.projectCacheDir, 'projects/myLib/src/public-api')
      }
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      { pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false },
      { pattern: 'src/**/*.d.ts', ignore: true },
      { pattern: 'src/**/*spec.ts', ignore: true },
      { pattern: './projects/Objectsrc/lib/**/*.+(ts|css||html)', load: false },
      { pattern: './projects/myLib/src/lib/**/*.d.ts', ignore: true },
      { pattern: './projects/myLib/src/lib/**/*spec.ts', ignore: true }
    ],

    tests: [
      { pattern: 'src/**/*spec.ts', load: false },
      { pattern: 'src/**/*e2e-spec.ts', ignore: true },
      { pattern: './projects/myLib/src/**/*spec.ts', load: false }
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function(app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function() {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
`

Error:
`
0 failing tests, 2 passing 
 
Uncaught Error: Cannot find module 'myLib' 
Module not found: Error: Can't resolve 'myLib' in '.\src\app'ModuleNotFoundError: Module not found: Error: Can't resolve 'myLib' in '.\src\app' 
    at factory.create (C:\Users\me\code\ngCliWebpackSample\node_modules\webpack\lib\Compilation.js:823:10) 
    at factory (C:\Users\me\code\ngCliWebpackSample\node_modules\webpack\lib\NormalModuleFactory.js:397:22) 
    at resolver (C:\Users\me\code\ngCliWebpackSample\node_modules\webpack\lib\NormalModuleFactory.js:130:21) 
    at asyncLib.parallel (C:\Users\me\code\ngCliWebpackSample\node_modules\webpack\lib\NormalModuleFactory.js:224:22) 
    at C:\Users\me\code\ngCliWebpackSample\node_modules\neo-async\async.js:2830:7 
    at C:\Users\me\code\ngCliWebpackSample\node_modules\neo-async\async.js:6877:13 
    at normalResolver.resolve (C:\Users\me\code\ngCliWebpackSample\node_modules\webpack\lib\NormalModuleFactory.js:214:25) 
    at doResolve (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\Resolver.js:184:12) 
    at hook.callAsync (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\Resolver.js:238:5) 
    at _fn0 (eval at create (C:\Users\me\code\ngCliWebpackSample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1) 
    at resolver.doResolve (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5) 
    at hook.callAsync (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\Resolver.js:238:5) 
    at _fn0 (eval at create (C:\Users\me\code\ngCliWebpackSample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1) 
    at hook.callAsync (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\Resolver.js:238:5) 
    at _fn0 (eval at create (C:\Users\me\code\ngCliWebpackSample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1) 
    at resolver.doResolve (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38) 
    at hook.callAsync (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\Resolver.js:238:5) 
    at _fn0 (eval at create (C:\Users\me\code\ngCliWebpackSample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:657:1) 
    at resolver.doResolve (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\AliasPlugin.js:47:40) 
    at hook.callAsync (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\Resolver.js:238:5) 
    at _fn0 (eval at create (C:\Users\me\code\ngCliWebpackSample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1) 
    at resolver.doResolve (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5) 
    at hook.callAsync (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\Resolver.js:238:5) 
    at _fn0 (eval at create (C:\Users\me\code\ngCliWebpackSample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1) 
    at hook.callAsync (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\Resolver.js:238:5) 
    at _fn0 (eval at create (C:\Users\me\code\ngCliWebpackSample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1) 
    at resolver.doResolve (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38) 
    at hook.callAsync (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\Resolver.js:238:5) 
    at _fn43 (eval at create (C:\Users\me\code\ngCliWebpackSample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1) 
    at hook.callAsync (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\Resolver.js:238:5) 
    at _fn0 (eval at create (C:\Users\me\code\ngCliWebpackSample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1) 
    at resolver.doResolve (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38) 
    at hook.callAsync (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\Resolver.js:238:5) 
    at _fn1 (eval at create (C:\Users\me\code\ngCliWebpackSample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1) 
    at hook.callAsync (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\Resolver.js:238:5) 
    at _fn0 (eval at create (C:\Users\me\code\ngCliWebpackSample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1) 
    at fs.stat (C:\Users\me\code\ngCliWebpackSample\node_modules\enhanced-resolve\lib\DirectoryExistsPlugin.js:22:13) 
    at C:\Users\me\code\ngCliWebpackSample\node_modules\graceful-fs\polyfills.js:282:31 
    at FSReqWrap.oncomplete (fs.js:153:21) 
`
....


Thanks for any additional insight you can provide!

**Comment by NikGovorov** [comment]
This looks wrong:

```{ pattern: './projects/Objectsrc/lib//.+(ts|css||html)', load: false }```

Could you please fix it it try again?

**Comment by TheTiGuR** [comment]
`var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./tsconfig.spec.json').compilerOptions
);

module.exports = function(wallaby) {
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: ['src/wallabyTest.js', 'src/**/*spec.js', 'projects/myLib/src/lib/**/*spec.js'],
    module: {
      rules: [
        { test: /\.css$/, loader: ['raw-loader'] },
        { test: /\.html$/, loader: 'raw-loader' },
        {
          test: /\.ts$/,
          loader: '@ngtools/webpack',
          include: /node_modules/,
          query: { tsConfigPath: 'tsconfig.json' }
        },
        { test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/ },
        { test: /\.(jpg|png|svg)$/, loader: 'raw-loader' }
      ]
    },
    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ],
      alias: {
        myLib: path.join(wallaby.projectCacheDir, 'projects/myLib/src/public-api')
      }
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      { pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false },
      { pattern: 'src/**/*.d.ts', ignore: true },
      { pattern: 'src/**/*spec.ts', ignore: true },
      { pattern: './projects/myLib/src/lib/**/*.+(ts|css||html)', load: false },
      { pattern: './projects/myLib/src/lib/**/*.d.ts', ignore: true },
      { pattern: './projects/myLib/src/lib/**/*spec.ts', ignore: true }
    ],

    tests: [
      { pattern: 'src/**/*spec.ts', load: false },
      { pattern: 'src/**/*e2e-spec.ts', ignore: true },
      { pattern: './projects/myLib/src/**/*spec.ts', load: false }
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function(app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function() {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
`

Still getting the same error as my last comment with that line corrected. This is in the ngCli sample project as described in my initial question.

**Comment by NikGovorov** [comment]
Could you please try the exact configuration I provided you with earlier? The configuration that you're posting does not match, `projects/myLib/src/public-api/public-api.ts` is not covered by files patterns for example.

**Comment by TheTiGuR** [comment]
Well, in the test project it is correct, so that's good, in my live project it still can't resolve the missing module (myLib), even after copying the exact working one in the test project and updating the name to be correct. I will look further on Monday and see if I can find anything further.

**Comment by smcenlly** [comment]
If you still can't get it working after taking a further look, could you put together a sample repo with the same problem? We're happy to take a look.
