### ISSUE TITLE
Ava 2.0.0 support

### ISSUE THREAD

**Issue by jiku** [wallabyjs/public#2106]
### Issue description or question

From `Wallaby.js Console`

```shell
[Info]  Mon, 10 Jun 2019 16:35:24 GMT wallaby:project Wallaby Node version: v12.3.0
[Info]  Mon, 10 Jun 2019 16:35:24 GMT wallaby:project Wallaby config: /Users/test/Documents/dev/Lab/wallaby/ava-sample/wallaby.js
[Info]  Started Wallaby.js Core v1.0.695
[Info]  Mon, 10 Jun 2019 16:35:24 GMT wallaby:fs File added: app/index.js
[Info]  Mon, 10 Jun 2019 16:35:24 GMT wallaby:fs File added: app/index.spec.js
[Info]  Mon, 10 Jun 2019 16:35:25 GMT wallaby:project File cache: /Users/test/.vscode-insiders/extensions/wallabyjs.wallaby-vscode-1.0.128/projects/6fb606a564dc7938
[Info]  Mon, 10 Jun 2019 16:35:25 GMT wallaby:uiService Listening port 51236
[Info]  Mon, 10 Jun 2019 16:35:25 GMT wallaby:project package.json file change detected, invalidating local cache
[Info]  Wallaby App (realtime reports) is available at: http://localhost:51245
[Info]  Mon, 10 Jun 2019 16:35:25 GMT wallaby:workers Parallelism for initial run: 2, for regular run: 2
[Info]  Mon, 10 Jun 2019 16:35:25 GMT wallaby:workers Starting run worker instance #0
[Info]  Mon, 10 Jun 2019 16:35:25 GMT wallaby:workers Starting run worker instance #1
[Info]  Mon, 10 Jun 2019 16:35:25 GMT wallaby:workers Web server is listening at 62530
[Info]  Mon, 10 Jun 2019 16:35:25 GMT wallaby:project File cache requires some updates, waiting required files from IDE
[Info]  Mon, 10 Jun 2019 16:35:25 GMT wallaby:project File app/index.js changes are patches only: false
[Info]  Mon, 10 Jun 2019 16:35:25 GMT wallaby:project File app/index.spec.js changes are patches only: false
[Info]  Mon, 10 Jun 2019 16:35:25 GMT wallaby:project Preparing to process app/index.js
[Info]  Mon, 10 Jun 2019 16:35:25 GMT wallaby:project Starting processor pool (if not yet started)
[Info]  Mon, 10 Jun 2019 16:35:25 GMT wallaby:project Preparing to process app/index.spec.js
[Info]  Mon, 10 Jun 2019 16:35:25 GMT wallaby:project Starting processor pool (if not yet started)
[Info]  Mon, 10 Jun 2019 16:35:27 GMT wallaby:workers Started run worker instance (delayed) #0
[Info]  Mon, 10 Jun 2019 16:35:27 GMT wallaby:workers Started run worker instance (delayed) #1
[Info]  Mon, 10 Jun 2019 16:35:27 GMT wallaby:processor Running 1 processor(s) for app/index.js
[Info]  Mon, 10 Jun 2019 16:35:27 GMT wallaby:processor Running 1 processor(s) for app/index.spec.js
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:processor Finished running one processor for app/index.js
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:project Processing compiled app/index.js
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:project Instrumenting app/index.js, via process pool: true
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:processor Finished running one processor for app/index.spec.js
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:project Processing compiled app/index.spec.js
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:project Instrumenting app/index.spec.js, via process pool: true
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:project No preprocessors configured for app/index.js
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:project Writing to disk and caching processed file app/index.js
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:project No preprocessors configured for app/index.spec.js
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:project Writing to disk and caching processed file app/index.spec.js
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:project File app/index.js changes saved, store ts: 1547741413406, change ts: 1560184525407
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:project File app/index.spec.js changes saved, store ts: 1547713808007, change ts: 1560184525408
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:project Stopping process pool
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:project Running postprocessor
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:postprocessor New TypeScript language service is required
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:postprocessor TypeScript postprocessor will be removed because in 2 project files none were found by patterns: [ '**/*.ts?(x)' ]
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:project Postprocessor execution finished
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:project Postprocessor is removed as requested by itself
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:project Test run started; run priority: 3
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:project Running all tests
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:workers Starting test run, priority: 3
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #02zlq]
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #02zlq]
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #02zlq]
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:workers [worker #0, session #02zlq] Running tests in sandbox
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:workers Sandbox (active) [02zlq] error: ava node module is not found or the version is not supported, missing `npm install ava --save-dev`?
[Info]  TypeError: Cannot read property 'source' of undefined
[Error] Runtime error: ava node module is not found or the version is not supported, missing `npm install ava --save-dev`? 
[Error] TypeError: Cannot read property 'source' of undefined 
[Error]     at Object.formatter (/Users/test/Documents/dev/Lab/wallaby/ava-sample/node_modules/ava/lib/enhance-assert.js:11:33) 
[Error]     at Module._compile (internal/modules/cjs/loader.js:774:30) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:641:32) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:556:12) 
[Error]     at Module.require (internal/modules/cjs/loader.js:681:19) 
[Error]     at require (internal/modules/cjs/helpers.js:16:16) 
[Error]     at Module._compile (internal/modules/cjs/loader.js:774:30) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:641:32) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:556:12) 
[Error]     at Function.Module.runMain (internal/modules/cjs/loader.js:837:10) 
[Error]     at internal/main/run_main_module.js:17:11 
[Info]  Mon, 10 Jun 2019 16:35:28 GMT wallaby:workers Failed to map the stack to user code, entry message: ava node module is not found or the version is not supported, missing `npm install ava --save-dev`?
[Info]  TypeError: Cannot read property 'source' of undefined, stack: ava node module is not found or the version is not supported, missing `npm install ava --save-dev`?
[Info]  TypeError: Cannot read property 'source' of undefined
[Info]      at Object.formatter (/Users/test/Documents/dev/Lab/wallaby/ava-sample/node_modules/ava/lib/enhance-assert.js:11:33)
[Info]      at Object.<anonymous> (/Users/test/.vscode-insiders/extensions/wallabyjs.wallaby-vscode-1.0.128/wallaby/runners/node/ava@0.3.0/initializer.js:14:2976)
[Info]      at Module._compile (internal/modules/cjs/loader.js:774:30)
[Info]      at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
[Info]      at Module.load (internal/modules/cjs/loader.js:641:32)
[Info]      at Function.Module._load (internal/modules/cjs/loader.js:556:12)
[Info]      at Module.require (internal/modules/cjs/loader.js:681:19)
[Info]      at Module.r.require (/Users/test/.vscode-insiders/extensions/wallabyjs.wallaby-vscode-1.0.128/wallaby/server.js:21:23923)
[Info]      at require (internal/modules/cjs/helpers.js:16:16)
[Info]      at r (/Users/test/.vscode-insiders/extensions/wallabyjs.wallaby-vscode-1.0.128/w
[Info]  Mon, 10 Jun 2019 16:35:29 GMT wallaby:workers [02zlq] Run 0 test(s), skipped 0 test(s)
[Info]  Mon, 10 Jun 2019 16:35:29 GMT wallaby:workers [02zlq] Sandbox is responsive, closing it
[Info]  Mon, 10 Jun 2019 16:35:29 GMT wallaby:project Test run finished
[Info]  Mon, 10 Jun 2019 16:35:29 GMT wallaby:project Processed console.log entries
[Info]  Mon, 10 Jun 2019 16:35:29 GMT wallaby:project Processed loading sequences
[Info]  Mon, 10 Jun 2019 16:35:29 GMT wallaby:project Processed executed tests
[Info]  Mon, 10 Jun 2019 16:35:29 GMT wallaby:project Processed code coverage
[Info]  Mon, 10 Jun 2019 16:35:29 GMT wallaby:project Test run result processed and sent to IDE
```

### Wallaby.js configuration file

[2.0.0](https://github.com/jiku/ava-sample/tree/2.0.0)
[1.4.1](https://github.com/jiku/ava-sample/tree/1.4.1)

### Code editor or IDE name and version

Visual Studio Code v1.36.0

### OS name and version

macOS 10.14.5

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This has been fixed in the latest version of wallaby core, v1.0.696. Wallaby should automatically update for you within the next ~20 minutes, or else when you next restart Visual Studio Code. If it does not, you may [force a core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
