### ISSUE TITLE
EADDRINUSE Node Web Socket w/ Mocha

### ISSUE THREAD

**Issue by damionvega** [wallabyjs/public#2110]
### Issue description or question
I receive the following error after Wallaby re-runs the first time and on. I should note that I am receiving output below the error today, whereas yesterday it was only showing the error. I believe editing my config (read on another issue) was the difference, but am still receiving the error.

When the error is present, there is no Wallaby output in the Editor pane(s)–only in the Output window.

```console
Error: listen EADDRINUSE 127.0.0.1:8888 
    at Object._errnoException (util.js:1022:11) 
    at _exceptionWithHostPort (util.js:1044:20) 
    at Server.setupListenHandle [as _listen2] (net.js:1367:14) 
    at listenInCluster (net.js:1408:12) 
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1517:7) 
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10) 
/Users/djv/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.128/wallaby/runners/node/mocha@2.1.0/initializer.js:14 
var Mocha;if(global.wallaby._testFrameworkPath)Mocha=require(global.wallaby._testFrameworkPath);else try{Mocha=require("mocha")}catch(e){Mocha=require("./framework/index.js")}var mocha,tracer=global.$_$tracer;tracer.start(function(){var e,t=tracer.initialSpecId(),n=[],i=global.$_$session,r=function(){return i!==global.$_$session};mocha.reporter(function(i){var o=i._grep||/.*/,a=i._invert,s=!1;if(i._invert=!1,i.runTest=function(e){if(!r()){var t=this.test,n=this;this.asyncOnly&&(t.asyncOnly=!0);try{t.on("error",function(e){n.fail(t,e)}),tracer.specSyncStart();try{t.run(e)}finally{tracer.specSyncEnd()}}catch(i){e(i)}}},i.grep=function(e,t){o=e,a=t,i._invert=!1},i.grepTotal=function(e){var t=0;return e.eachTest(function(e){var n=o.test(e.fullTitle());a&&(n=!n),n&&t++}),t},i._grep={test:function(e){var t=o.test(e);if(a&&(t=!t),!t)return!1;if(!tracer.hasSpecFilter())return!0;var i=n.slice(1);return i 
 
TypeError: Cannot read property 'push' of undefined 
    at emitTwo (events.js:126:13) 
    at Runner.emit (events.js:214:7) 
    at Runner.fail (/Users/djv/work/api/node_modules/mocha/lib/runner.js:244:8) 
    at Runner.uncaught (/Users/djv/work/api/node_modules/mocha/lib/runner.js:699:12) 
    at process.uncaught (/Users/djv/work/api/node_modules/mocha/lib/runner.js:804:10) 
    at emitOne (events.js:121:20) 
    at process.emit (events.js:211:7) 
    at process._fatalException (bootstrap_node.js:375:26) 
```

### Wallaby.js configuration file

```javascript
module.exports = () => {
  return {
    files: [
      'server.js',
      'config/**/*.js',
      'config/**/*.env',
      'models/**/*.js',
      'public/**/*.js',
      'test/config/*.js',
      'test/factories/*.js',
    ],
    tests: ['test/*spec.js'],
    testFramework: 'mocha',
    env: {
      type: 'node',
    },
    debug: true,
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.35.1

### OS name and version

macOS Mojave 10.14.3

**Comment by damionvega** [comment]
**Update**: It seems the error only appears when using a `console.log()` or `/*?*/`.

**Comment by smcenlly** [comment]
Wallaby has a `restart` flag that should fix this for you. If it doesn't, please let us know and we will reopen this issue.

From [our docs](https://wallabyjs.com/docs/integration/node.html#node-process-reuse):

---

When running your node.js tests, wallaby by default tries to re-use previously created node.js process(es) to make the runs faster. **If you are relying on the test node process re-start for each run, because your tests are not cleaning after themselves** (for example, they are not closing opened database connections, not stopping started web services, or are registering some callbacks that may be invoked after your test run finishes and interfere with your next test run), then you may use `workers.restart` setting **set to `true`** to make wallaby.js re-start node process for each run.

```javascript
module.exports = function () {
  return {
    files: [
      'lib/**/*.js'
    ],

    tests: [
      'test/**/*Spec.js'
    ],

    env: {
      type: 'node'
    },

    workers: {
      restart: true
    }
  };
};
```

**Comment by damionvega** [comment]
After finding [this link](https://wallabyjs.com/docs/config/workers.html) I've updated my config to the following which seems to be working fine:

```js
module.exports = () => {
  return {
    files: [
      'server.js',
      'config/**/*.js',
      'config/**/*.env',
      'models/**/*.js',
      'public/**/*.js',
      'test/config/*.js',
      'test/factories/*.js',
    ],
    tests: ['test/*spec.js'],
    testFramework: 'mocha',
    env: {
      type: 'node',
    },
    debug: true,
    workers: {
      restart: true,
    },
  }
}
```

**Comment by damionvega** [comment]
Yep, thanks @smcenlly
