### ISSUE TITLE
NullPointerException when running against an Angular project in WebStorm

### ISSUE THREAD

**Issue by jmb-qhr** [wallabyjs/public#2133]
### Issue description or question
It seems to have only started in the past couple months though I may be off, WebStorm keeps complaining about wallaby throwing a null pointer exception. It seems to happen most often shortly after I stop or restart the wallaby process.

### Error

java.lang.NullPointerException
	at com.wallaby.javascript.WallabyController.a(Unknown Source)
	at com.wallaby.javascript.b.a(Unknown Source)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:368)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:224)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

### Wallaby.js configuration file

```javascript
const wallabyWebpack = require('wallaby-webpack');
const path = require('path');

const compilerOptions = Object.assign(
    require('./tsconfig.json').compilerOptions,
    require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'es2015';

module.exports = function (wallaby) {

  let webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js',
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', {loader: 'less-loader', options: {paths: [__dirname]}}]},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png|svg)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts', '.json'],
      modules: [
        path.join(wallaby.projectCacheDir, 'config'),
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src/testing'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules',
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  // noinspection JSUnresolvedFunction
  return {
    files: [
      {pattern: 'config/**/*.+(ts|json)', load: false},
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true},
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],

    filesWithNoCoverageCalculated: [
      'src/*.ts',
      'src/**/*.module.ts',
      'src/testing/*.ts',
      'src/environments/*.ts',
      'src/app/in-memory-data.service.ts'
    ],

    workers: {
      initial: 6,
      regular: 2
    },

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      const path = require('path');
      // noinspection JSUnresolvedFunction
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      // noinspection JSUnresolvedFunction
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      // kind: 'electron',
      kind: 'chrome',
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      // noinspection JSUnresolvedFunction
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```

### Code editor or IDE name and version

WebStorm v2019.1.3
![image](https://user-images.githubusercontent.com/35278666/60986880-b181a500-a2fd-11e9-865c-f04c5eb4b506.png)

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
Thanks for reporting the problem. Unfortunately, we're unable to determine the cause and can't reproduce the problem. We've created a customized Wallaby for Intellij installation kit for you that will provide us with additional documentation. Could you please download and install the build from [here](https://wallaby-downloads.s3.amazonaws.com/issue-2133/wallaby-intellij-v1.0.135.zip). When you next experience the problem, please provide us with the updated log.

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. If you have the problem again and can provide us with logs, please let us know and we'll re-open.
