### ISSUE TITLE
ngCliWebpackSample breaks on Angular 8. "Can't resolve all parameters for AppComponent(?)" when injecting any service to a component.

### ISSUE THREAD

**Issue by joshiraez** [wallabyjs/public#2144]
### Issue description or question
Wallaby breaks and can't run any test when running on latest angular version whenever a component injects a service (or there are any services built).

It happened on a new project we are building where suddenly wallaby stopped working. After trying to pinpoint the issue, I found that it's caused by services building and injection (like Wallaby can't find the services) on runtime.

Tests run fine using ng test.

For reproduction, 
* Clone ngCliWebpackSample (which config we were using for our other projects, the older version for angular 7 and the recently updated one for angular 8). 
* Run npm install. Try to start wallaby in visual studio code.
* It will run fine with the default tests.
* Add any service injection to AppComponent (The Title service for example)
* Add the provider for Title on the test
* Run ng test: it should pass.
* Run Wallaby, it will get an error with a log like this:
```
  ​​​​AppComponent should render title in a h1 tag​​​​ ​​​[23 ms]​​​​
     
    Failed: Can't resolve all parameters for AppComponent: (?). 
     
    Error: Can't resolve all parameters for AppComponent: (?). 
  
  ​​​​AppComponent should create the app​​​​ ​​​[20 ms]​​​​
     
    Failed: Can't resolve all parameters for AppComponent: (?). 
     
    Error: Can't resolve all parameters for AppComponent: (?). 
  
  ​​​​AppComponent should have as title 'Wallaby Angular CLI Project'​​​​ ​​​[20 ms]​​​​
     
    Failed: Can't resolve all parameters for AppComponent: (?). 
     
    Error: Can't resolve all parameters for AppComponent: (?). 
```

In our other project, sometimes another different error appears instead when all tests would pass. This project has services also implemented so I don't know if the problem is that webpack can't  compile services correctly.

The stack trace in that case is:

```
Uncaught Error: Module parse failed: Unexpected character '@' (14:0) 
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders 
| import { Observable } from 'rxjs'; 
|  
> @Injectable({ 
|   providedIn: 'root', 
| }) 
at http://localhost:35563/__modules/359.js?1563534018795:1 
Module parse failed: Unexpected character '@' (14:0) 
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders 
| import { Observable } from 'rxjs'; 
|  
> @Injectable({ 
|   providedIn: 'root', 
| })ModuleParseError: Module parse failed: Unexpected character '@' (14:0) 
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders 
| import { Observable } from 'rxjs'; 
|  
> @Injectable({ 
|   providedIn: 'root', 
| }) 
    at handleParseError (/home/jose/dev/repositories/j.raez/ext-bo/node_modules/webpack/lib/NormalModule.js:450:19) 
    at /home/jose/dev/repositories/j.raez/ext-bo/node_modules/webpack/lib/NormalModule.js:484:5 
    at /home/jose/dev/repositories/j.raez/ext-bo/node_modules/webpack/lib/NormalModule.js:343:12 
    at /home/jose/dev/repositories/j.raez/ext-bo/node_modules/loader-runner/lib/LoaderRunner.js:373:3 
    at iterateNormalLoaders (/home/jose/dev/repositories/j.raez/ext-bo/node_modules/loader-runner/lib/LoaderRunner.js:214:10) 
    at /home/jose/dev/repositories/j.raez/ext-bo/node_modules/loader-runner/lib/LoaderRunner.js:205:4 
    at /home/jose/dev/repositories/j.raez/ext-bo/node_modules/graceful-fs/graceful-fs.js:90:16 
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3) 
```
I can't paste you this project because it has private stuff. I also tried to reproduce it in the other project, but with no luck. I don't know if it bugs in another flow or something like that, because as I said, whenever all tests would pass (with ng test), any of the above stack traces could appear when running wallaby, and I was just unlucky.

Thank you for your help

##Code to reproduce former stack:
* After cloning ngCliWebpackSample
```typescript
//App.component.ts
import { Component } from '@angular/core';
import { Title } from '@angular/platform-browser';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(private _title : Title) {}
  title = 'Wallaby Angular CLI Project';
}
```
```typescript
//app.component.spec.ts
import { TestBed, async } from '@angular/core/testing';
import { AppComponent } from './app.component';
import { Title } from '@angular/platform-browser';

describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      providers: [Title]
    }).compileComponents();
  }));

  it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  });

  it(`should have as title 'Wallaby Angular CLI Project'`, () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app.title).toEqual('Wallaby Angular CLI Project');
  });

  it('should render title in a h1 tag', () => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelector('h1').textContent).toContain('Welcome to Wallaby Angular CLI Project!');
  });
});
```

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  const wallabyWebpack = require('wallaby-webpack');
  const path = require('path');
  const fs = require('fs');

  const specPattern = '/**/*spec.ts';
  const angularConfig = require('./angular.json');

  const projects = Object.keys(angularConfig.projects).map(key => {
    return { name: key, ...angularConfig.projects[key] };
  }).filter(project => project.sourceRoot)
    .filter(project => project.projectType !== 'application' || 
                       (project.architect &&
                        project.architect.test &&
                        project.architect.test.builder === '@angular-devkit/build-angular:karma'));

  const applications = projects.filter(project => project.projectType === 'application');
  const libraries = projects.filter(project => project.projectType === 'library');

  const tsConfigFile = projects
    .map(project => path.join(__dirname, project.root, 'tsconfig.spec.json'))
    .find(tsConfig => fs.existsSync(tsConfig));

  const tsConfigSpec = tsConfigFile ? JSON.parse(fs.readFileSync(tsConfigFile)) : {};

  const compilerOptions = Object.assign(require('./tsconfig.json').compilerOptions, tsConfigSpec.compilerOptions);

  return {
    files: [
      { pattern: path.basename(__filename), load: false, instrument: false },
      ...projects.map(project => ({
        pattern: project.sourceRoot + '/**/*.+(ts|js|css|less|scss|sass|styl|html|json|svg)',
        load: false
      })),
      ...projects.map(project => ({
        pattern: project.sourceRoot + specPattern,
        ignore: true
      })),
      ...projects.map(project => ({
        pattern: project.sourceRoot + '/**/*.d.ts',
        ignore: true
      }))
    ],

    tests: [
      ...applications.map(project => ({
        pattern: project.sourceRoot + specPattern,
        load: false
      }))
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({
        ...compilerOptions,
        getCustomTransformers: program => {
          return {
            before: [
              require('@ngtools/webpack/src/transformers/replace_resources').replaceResources(
                path => true,
                () => program.getTypeChecker(),
                false
              )
            ]
          };
        }
      })
    },

    preprocessors: {
      /* Initialize Test Environment for Wallaby */
      [path.basename(__filename)]: file => `
 import '@angular-devkit/build-angular/src/angular-cli-files/models/jit-polyfills';
 import 'zone.js/dist/zone-testing';
 import { getTestBed } from '@angular/core/testing';
 import { BrowserDynamicTestingModule,  platformBrowserDynamicTesting} from '@angular/platform-browser-dynamic/testing';

 getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());`
    },

    middleware: function(app, express) {
      const path = require('path');

      applications.forEach(application => {
        if (
          !application.architect ||
          !application.architect.test ||
          !application.architect.test.options ||
          !application.architect.test.options.assets
        ) {
          return;
        }

        application.architect.test.options.assets.forEach(asset => {
          app.use(asset.slice(application.sourceRoot.length), express.static(path.join(__dirname, asset)));
        });
      });
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: wallabyWebpack({
      entryPatterns: [
        ...applications
          .map(project => project.sourceRoot + '/polyfills.js')
          .filter(polyfills => fs.existsSync(path.join(__dirname, polyfills.replace(/js$/, 'ts')))),
        path.basename(__filename),
        ...projects.map(project => project.sourceRoot + specPattern.replace(/ts$/, 'js'))
      ],

      module: {
        rules: [
          { test: /\.css$/, loader: ['raw-loader'] },
          { test: /\.html$/, loader: 'raw-loader' },
          {
            test: /\.ts$/,
            loader: '@ngtools/webpack',
            include: /node_modules/,
            query: { tsConfigPath: 'tsconfig.json' }
          },
          { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
          { test: /\.less$/, loaders: ['raw-loader', { loader: 'less-loader' }] },
          {
            test: /\.scss$|\.sass$/,
            loaders: [{ loader: 'raw-loader' }, { loader: 'sass-loader', options: { implementation: require('sass') } }]
          },
          { test: /\.(jpg|png|svg)$/, loader: 'raw-loader' }
        ]
      },

      resolve: {
        extensions: ['.js', '.ts'],
        modules: [
          __dirname,
          'node_modules',
          ...(projects.length ? projects.filter(project => project.root).map(project => project.root) : []),
          ...(projects.length ? projects.filter(project => project.sourceRoot).map(project => project.sourceRoot) : [])
        ],
        alias: libraries.reduce((result, project) => {
          result[project.name] = path.join(wallaby.projectCacheDir, project.sourceRoot, 'public-api');
          return result;
        }, {})
      }
    }),

    setup: function() {
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.36.1

### OS name and version

Linux: Ubuntu 18.04.2 LTS

Thank you for your help

Edit:
Some extra info. ngCliWebpackSample is in Angular 8.1.0. Our project ext-bo is in Angular 8.1.1

**Comment by ArtemGovorov** [comment]
Thanks for providing the details. @smcenlly was able to identify the issue's cause.

This issue
> ngCliWebpackSample breaks on Angular 8. "Can't resolve all parameters for AppComponent(?)" when injecting any service to a component.

was caused by the latest Angular CLI removing `"emitDecoratorMetadata": true,` param from tsconfigs, causing incorrect TypeScript build when Wallaby is doing it (Angular CLI must be setting the parameter automatically internally).

We have updated docs to include the setting, you may copy this line: https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js#L27 to get it working.

Regarding the other error:

> Uncaught Error: Module parse failed: Unexpected character '@' (14:0) 

it looks like not compiled/instrumented file is being imported/bundled by Webpack. It can happen when this file in your project:

```
import { Observable } from 'rxjs'; 
  
@Injectable({ 
   providedIn: 'root', 
 })
```

is being imported with `.ts` extension - please check that it is not the case. If it's not (and the error is still reproduced after teh suggested config fix), please share how that file is being imported, and that project's wallaby config.

**Comment by joshiraez** [comment]
Thank you, you were right.

The above line solved the issue with the example case and our project for the "Can't resolve all parameters for AppComponent: (?).".

The other problem was an issue with TS importing, as well. After changing every route to its relative route, it worked well.
