### ISSUE TITLE
Wallaby stopped unexpectedly. Exit code: 7, Error Message: null

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2154]
Has something changed with source maps recently?

Do you use `source-map-support` or is that in my code somehow?

Maybe it is because I am using `@babel/register` in my `wallaby.js` which has `source-map-support` as a dependency.

### Issue description or question

```
wallaby.js started
undefined:1
var _0x4744=['onConnected','LDacl','hTKvy','PIRnO','debugLog','console.','pGjPG','JDjUL','JRjgE','networkInterfaces','Sandbox\x20(%s)\x20[%s]\x20error:\x20%s','inactive','_reportableError','Runtime\x20error:\x20','scheduleCompleteIfNotActiveFor','Cannot\x20find\x20module','_executingTest','addToTestLog','TwWOJ','[%s]\x20Running\x20tests\x20in\x20sandbox','sessionId','workerId','cSVma','jMMKq','EnDUs','../../..','Sandbox\x20load\x20failed,\x20status:\x20','_handleError','dLKEd','lnNrO','WOgoR','xiePO','XKRJF','UycDf','XPdji','hasAnsi','awMyC','LUGBr','UgBWd','EblAT','mxOQR','Cancelling\x20test\x20run,\x20cancel\x20requester\x20priority:\x20%s,\x20current\x20run\x20priority:\x20%s','enRnO','SRyuI','yCtKQ','closing','LjxbM','[%s]\x20Loaded\x20%s\x20test(s)','total','_total','loadingSequence','qsXNj','complete','_areLogEntryMessagesEqual','pkWLF','lKMgJ','RGQFU','VUQPj','_executingFiles','_setTimeoutForLongRunningOperation','lNILv','\x5c$&','qgTYU','wallaby.js','_load','testRunnerTransformedFile','k

SyntaxError: Unexpected token v in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.parseSourceMapInput (/xxx/node_modules/.registry.npmjs.org/source-map/0.6.1/node_modules/source-map/lib/util.js:433:15)
    at new SourceMapConsumer (/xxx/node_modules/.registry.npmjs.org/source-map/0.6.1/node_modules/source-map/lib/source-map-consumer.js:17:22)
    at mapSourcePosition (/xxx/node_modules/.registry.npmjs.org/source-map-support/0.5.12/node_modules/source-map-support/source-map-support.js:190:14)
    at wrapCallSite (/xxx/node_modules/.registry.npmjs.org/source-map-support/0.5.12/node_modules/source-map-support/source-map-support.js:358:20)
    at /xxx/node_modules/.registry.npmjs.org/source-map-support/0.5.12/node_modules/source-map-support/source-map-support.js:399:26
    at Array.map (<anonymous>)
    at Function.prepareStackTrace (/xxx/node_modules/.registry.npmjs.org/source-map-support/0.5.12/node_modules/source-map-support/source-map-support.js:398:30)
    at prepareStackTrace (internal/errors.js:30:29)
    at process.<anonymous> (/Users/Vaughan/Library/Caches/IntelliJIdea2019.2/wallaby/wallaby/server.js:14:7229)
    at process.emit (events.js:200:13)
    at process._fatalException (internal/process/execution.js:146:25)
```

### Wallaby.js configuration file

It's complicated.

### Code editor or IDE name and version

IntelliJ IDEA v2019.2

### OS name and version

Windows
**OSX**
Linux

**Comment by vjpr** [comment]
Seems something is generating source maps for `/Users/Vaughan/Library/Caches/IntelliJIdea2019.2/wallaby/wallaby/server.js`...

**Comment by vjpr** [comment]
I was using `@babel/register` in my wallaby config. Adding `sourceMaps: false` fixes the error.

It seems that `wallaby/server.js` runs my config file in the same execution environment as it does. So that if I used `@babel/register`, `source-map-support` is being enabled in this execution env. (`@babel/runtime` is not compiling `wallaby/server.js` though).

**Comment by ArtemGovorov** [comment]
Thanks for the update. Another solution is to ignore wallaby/server.js using `@babel/register` options.

If you share an example of your config, we are also happy to investigate other solutions/workarounds.
