### ISSUE TITLE
Internal Wallaby error "TypeError: _.truncate is not a function"

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/public#2178]
### Issue description or question

On an attempt to show a Live Comments with `//?. $` the Wallaby is crashing with error
```
Error: Failed to instrument tests/unit/errors/***.test.js
TypeError: _.truncate is not a function
```

### Wallaby.js configuration file

No config file - I'm using Jest 24.8

### Code editor or IDE name and version

WebStorm v2019.2

### OS name and version

Windows 10 Pro

This is the code to reproduce:
`_.js` - file under test
```
module.exports = () => 'bla'
```
test file
```
const underTest = require('./_')

test('test', () => {
  underTest() //?. $
})

```

This is the full console output (without my names):
```Runtime error: Error: Failed to instrument tests/unit/errors/[FILE].test.js
TypeError: _.truncate is not a function
    at ScriptTransformer.transformSource (.\node_modules\@jest\transform\build\ScriptTransformer.js:387:35)
    at ScriptTransformer._transformAndBuildScript (.\node_modules\@jest\transform\build\ScriptTransformer.js:457:40)
    at ScriptTransformer.transform (.\node_modules\@jest\transform\build\ScriptTransformer.js:513:25)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:842:53)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:577:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:433:10)
    at .\node_modules\jest-jasmine2\build\index.js:201:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (.\node_modules\jest-jasmine2\build\index.js:27:24)
    at _next (.\node_modules\jest-jasmine2\build\index.js:47:9)
    at .\node_modules\jest-jasmine2\build\index.js:52:7
    at new Promise (<anonymous>)
    at .\node_modules\jest-jasmine2\build\index.js:44:12
    at jasmine2 (.\node_modules\jest-jasmine2\build\index.js:60:19)
    at .\node_modules\jest-runner\build\runTest.js:385:24
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (.\node_modules\jest-runner\build\runTest.js:161:24)
    at _next (.\node_modules\jest-runner\build\runTest.js:181:9)
    at ScriptTransformer.transformSource (.\node_modules\@jest\transform\build\ScriptTransformer.js:387:35)
    at ScriptTransformer._transformAndBuildScript (.\node_modules\@jest\transform\build\ScriptTransformer.js:457:40)
    at ScriptTransformer.transform (.\node_modules\@jest\transform\build\ScriptTransformer.js:513:25)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:842:53)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:577:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:433:10)
    at .\node_modules\jest-jasmine2\build\index.js:201:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (.\node_modules\jest-jasmine2\build\index.js:27:24)
    at _next (.\node_modules\jest-jasmine2\build\index.js:47:9)
    at .\node_modules\jest-jasmine2\build\index.js:52:7
    at new Promise (<anonymous>)
    at .\node_modules\jest-jasmine2\build\index.js:44:12
    at jasmine2 (.\node_modules\jest-jasmine2\build\index.js:60:19)
    at .\node_modules\jest-runner\build\runTest.js:385:24
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (.\node_modules\jest-runner\build\runTest.js:161:24)
    at _next (.\node_modules\jest-runner\build\runTest.js:181:9)
console.log: Jest: FAIL tests/unit/errors/[FILE].test.js

console.log: Jest:   ● Test suite failed to run

    Failed to instrument tests/unit/errors/[FILE].test.js
    TypeError: _.truncate is not a function
        at c._wrapIntoVisitor (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:17:982)
        at c._wrapIfCommentedForAutoLog (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:16:27552)
        at c._instructionValueSequence (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:16:27218)
        at Array.<anonymous> (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:16:17311)
        at Object.t.<computed> [as ExpressionStatement] (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:16:23808)
        at c._change (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:16:24242)
        at c._change (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:16:24614)
        at c._change (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:16:24614)
        at c._change (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:16:24614)
        at c._change (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:16:24614)
        at c._change (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:16:24614)
        at c._change (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:16:24614)
        at c._change (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:16:24614)
        at c._change (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:16:24614)
        at c._change (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:16:24614)
        at c._change (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:16:24614)
        at c.instrument (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:16:20855)
        at Object.t.exports [as instrument] (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\server.js:17:3046)
        at Object.e.process (C:\Users\[USER]\.WebStorm2019.2\system\wallaby\wallaby\runners\node\jest@24.8.0\initializer.js:14:15835)
        at ScriptTransformer.transformSource (F:\[PROJECT]\node_modules\@jest\transform\build\ScriptTransformer.js:387:35)
        at ScriptTransformer._transformAndBuildScript (F:\[PROJECT]\node_modules\@jest\transform\build\ScriptTransformer.js:457:40)
        at ScriptTransformer.transform (F:\[PROJECT]\node_modules\@jest\transform\build\ScriptTransformer.js:513:25)
        at Runtime._execModule (F:\[PROJECT]\node_modules\jest-runtime\build\index.js:842:53)
        at Runtime._loadModule (F:\[PROJECT]\node_modules\jest-runtime\build\index.js:577:12)
        at Runtime.requireModule (F:\[PROJECT]\node_modules\jest-runtime\build\index.js:433:10)
        at F:\[PROJECT]\node_modules\jest-jasmine2\build\index.js:201:13
        at Generator.next (<anonymous>)
        at asyncGeneratorStep (F:\[PROJECT]\node_modules\jest-jasmine2\build\index.js:27:24)
        at _next (F:\[PROJECT]\node_modules\jest-jasmine2\build\index.js:47:9)
        at F:\[PROJECT]\node_modules\jest-jasmine2\build\index.js:52:7
        at new Promise (<anonymous>)
        at F:\[PROJECT]\node_modules\jest-jasmine2\build\index.js:44:12
        at jasmine2 (F:\[PROJECT]\node_modules\jest-jasmine2\build\index.js:60:19)
        at F:\[PROJECT]\node_modules\jest-runner\build\runTest.js:385:24
        at Generator.next (<anonymous>)
        at asyncGeneratorStep (F:\[PROJECT]\node_modules\jest-runner\build\runTest.js:161:24)
        at _next (F:\[PROJECT]\node_modules\jest-runner\build\runTest.js:181:9)
      at c._wrapIntoVisitor (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:17:982)
      at c._wrapIfCommentedForAutoLog (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:16:27552)
      at c._instructionValueSequence (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:16:27218)
      at Array.<anonymous> (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:16:17311)
      at Object.t.<computed> [as ExpressionStatement] (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:16:23808)
      at c._change (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:16:24242)
      at c._change (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:16:24614)
      at c._change (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:16:24614)
      at c._change (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:16:24614)
      at c._change (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:16:24614)
      at c._change (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:16:24614)
      at c._change (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:16:24614)
      at c._change (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:16:24614)
      at c._change (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:16:24614)
      at c._change (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:16:24614)
      at c._change (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:16:24614)
      at c.instrument (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:16:20855)
      at Object.t.exports [as instrument] (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:17:3046)
      at Object.e.process (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/runners/node/jest@24.8.0/initializer.js:14:15835)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:387:35)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:457:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at Object.formatInstrumentationError (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:23:7312)
      at Object.e.process (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/runners/node/jest@24.8.0/initializer.js:14:16049)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:387:35)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:457:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
```

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in [the latest Wallaby core v1.0.720](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
