### ISSUE TITLE
Error on attempty to rename file in WebStorm

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/public#2179]
### Issue description or question

1. Create file `testfile.js` with code
```
module.exports = () => 'bla'
```
2. Create `testfile.test.js` with test
```
const underTest = require('../testfile')

test('test', () => {
  expect(underTest()).toEqual('bla')
})
```
3. In Project view (left panel with files) right click on `testfile.js` (or Shift + F6) and in popup set all checkboxes and set new name `testFile.js`

EB: Everything should continue to work
CB: Even thought in `testfile.test.js` the `require('../testfile')` has been changed to `require('../testFile')` there is an error in Wallaby Failing Tests tab:
```
ENOENT: no such file or directory, unlink 'C:\Users\[USER]\.WebStorm2019.2\system\wallaby\projects\8ff66b766eb71af7\original\errors\testFile.js'
  at Object.<anonymous> tests/testfile.test.js:1:1
```

### Wallaby.js configuration file

Autoconfig with Jest 24.8

### Code editor or IDE name and version

WebStorm v2019.2

### OS name and version

Windows 10 Pro

### Full stacktrace from Wallaby console
```
Runtime error: Error: ENOENT: no such file or directory, open 'C:\Users\[USER]\.WebStorm2019.2\system\wallaby\projects\8ff66b766eb71af7\original\errors\testFile.js'
    at Object.openSync (fs.js:447:3)
    at Object.readFileSync (fs.js:349:35)
    at ScriptTransformer._transformAndBuildScript (.\node_modules\@jest\transform\build\ScriptTransformer.js:443:43)
    at ScriptTransformer.transform (.\node_modules\@jest\transform\build\ScriptTransformer.js:513:25)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:842:53)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:577:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:433:10)
    at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:598:21)
    at Object.<anonymous> (.\tests\testfile.test.js:2:34)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:888:13)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:577:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:433:10)
    at .\node_modules\jest-jasmine2\build\index.js:201:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (.\node_modules\jest-jasmine2\build\index.js:27:24)
    at _next (.\node_modules\jest-jasmine2\build\index.js:47:9)
    at .\node_modules\jest-jasmine2\build\index.js:52:7
    at new Promise (<anonymous>)
    at .\node_modules\jest-jasmine2\build\index.js:44:12
    at jasmine2 (.\node_modules\jest-jasmine2\build\index.js:60:19)
    at .\node_modules\jest-runner\build\runTest.js:385:24
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (.\node_modules\jest-runner\build\runTest.js:161:24)
    at _next (.\node_modules\jest-runner\build\runTest.js:181:9)
console.log: Jest: FAIL tests/testfile.test.js

console.log: Jest:   ● Test suite failed to run

    ENOENT: no such file or directory, open 'C:\Users\[USER]\.WebStorm2019.2\system\wallaby\projects\8ff66b766eb71af7\original\errors\testFile.js'
      at Object.o.readFileSync (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/server.js:23:8847)
      at Object.fs.readFileSync (C:/Users/[USER]/.WebStorm2019.2/system/wallaby/wallaby/runners/node/jest@24.8.0/initializer.js:14:14308)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:443:43)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at Object.<anonymous> (tests/testfile.test.js:2:34)
```

UPD: I can not reproduce it in a small file like from example (although I didn't try much), but in my project file the Wallaby is not updating its internal files even after changes in the test file. Maybe it's because I have changed the names of both test file and file under test. To solve the problem I have to restart the Wallaby

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This has been fixed in the latest version of Wallaby core, v1.0.721.

Wallaby will update next time you restart it. If you don't receive an update, you may [force a core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
