### ISSUE TITLE
Cannot start Wallaby in WebStorm on an Angular project

### ISSUE THREAD

**Issue by ianjamieson** [wallabyjs/public#2192]
### Cannot start Wallaby in WebStorm on an Angular project
I am using WebStorm and Angular 8.2.3. Am including the first two fixes in case others encounter these issues too.

I started with the default [configuration file](https://wallabyjs.com/docs/integration/angular.html).

**FIrst error**
```
Runtime error: Uncaught Error: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import 'layout';
       ^
      Can't find stylesheet to import.
  ╷
1 │ @import 'layout';
  │         ^^^^^^^^
```

I fixed this by adding the `includePaths`, as suggested [here](https://github.com/wallabyjs/public/issues/1245#issuecomment-318970473):

```javascript
{
        test: /\.scss$|\.sass$/,
        loaders: [{ loader: 'raw-loader' }, { loader: 'sass-loader', options: { implementation: require('sass'), includePaths: ['./src/styles'] } }]
      },
```

**Second Error**
In my Angular environment files, I use `package.json` to get the current app version number like this:

```typescript
export const environment: Environment = {
  ...
  version: require('../../package.json').version
};
```

So the next error was 
```
Uncaught Error: Cannot find module '../../package.json'
	at src/environments/environment.ts:33

Module not found: Error: Can't resolve '../../package.json' in './src/environments'ModuleNotFoundError: Module not found: Error: Can't resolve '../../package.json' in './src/environments'
    at factory.create (./node_modules/webpack/lib/Compilation.js:888:10)
```

I fixed this by adding `package.json` to the `files:` list in `wallaby.js`:

```javascript
return {
    files: [
      'package.json',
      { pattern: path.basename(__filename), load: false, instrument: false },
      ...projects.map(project => ({
      pattern: project.sourceRoot + '/**/*.+(ts|js|css|less|scss|sass|styl|html|json|svg)',
      load: false
    })),
...projects.map(project => ({
    pattern: project.sourceRoot + specPattern,
    ignore: true
  })),
...projects.map(project => ({
    pattern: project.sourceRoot + '/**/*.d.ts',
    ignore: true
  }))
],
```

**Unfixed: Third error**
```
Uncaught TypeError: Cannot read property 'Minimal' of undefined
	at src/app/shared/shared.module.ts:136
```

Referring to this code:

```typescript
StoreRouterConnectingModule.forRoot({
      stateKey: 'router',
      serializer: MinimalRouterStateSerializer,
      routerState: RouterState.Minimal
    }),
```
`Minimal` does exist as part of `@ngrx/router-store`. 

**Unfixed: Fouth Error**
To resolve the issue above, I changed the reference to the enum to just a value so I could get past this stage so far. eg.

```typescript
StoreRouterConnectingModule.forRoot({
      stateKey: 'router',
      serializer: MinimalRouterStateSerializer,
      routerState: 1
    }),
```

Now the next error I get is:

```
Uncaught Error: Cannot set base providers because it has already been called
at http://localhost:63245/____wallaby-bundle.js?1566920673734&wallabyFileId=bundle:31803
```

Trying to open this file crashes my IDE, but I will try to provide more detail when I can.

### Wallaby.js configuration file
```
return {
    files: [
      'package.json',
      { pattern: path.basename(__filename), load: false, instrument: false },
      ...projects.map(project => ({
      pattern: project.sourceRoot + '/**/*.+(ts|js|css|less|scss|sass|styl|html|json|svg)',
      load: false
    })),
...projects.map(project => ({
    pattern: project.sourceRoot + specPattern,
    ignore: true
  })),
...projects.map(project => ({
    pattern: project.sourceRoot + '/**/*.d.ts',
    ignore: true
  }))
```

```javascript
module.exports = function(wallaby) {
  const wallabyWebpack = require('wallaby-webpack');
  const path = require('path');
  const fs = require('fs');

  const specPattern = '/**/*spec.ts';
  const angularConfig = require('./angular.json');

  const projects = Object.keys(angularConfig.projects).map(key => {
    return { name: key, ...angularConfig.projects[key] };
}).filter(project => project.sourceRoot)
.filter(project => project.projectType !== 'application' ||
  (project.architect &&
    project.architect.test &&
    project.architect.test.builder === '@angular-devkit/build-angular:karma'));

  const applications = projects.filter(project => project.projectType === 'application');
  const libraries = projects.filter(project => project.projectType === 'library');

  const tsConfigFile = projects
    .map(project => path.join(__dirname, project.root, 'tsconfig.spec.json'))
.find(tsConfig => fs.existsSync(tsConfig));

  const tsConfigSpec = tsConfigFile ? JSON.parse(fs.readFileSync(tsConfigFile)) : {};

  const compilerOptions = Object.assign(require('./tsconfig.json').compilerOptions, tsConfigSpec.compilerOptions);
  compilerOptions.emitDecoratorMetadata = true;

  return {
    files: [
      'package.json',
      { pattern: path.basename(__filename), load: false, instrument: false },
      ...projects.map(project => ({
      pattern: project.sourceRoot + '/**/*.+(ts|js|css|less|scss|sass|styl|html|json|svg)',
      load: false
    })),
...projects.map(project => ({
    pattern: project.sourceRoot + specPattern,
    ignore: true
  })),
...projects.map(project => ({
    pattern: project.sourceRoot + '/**/*.d.ts',
    ignore: true
  }))
],

  tests: [
    ...projects.map(project => ({
    pattern: project.sourceRoot + specPattern,
    load: false
  }))
],

  testFramework: 'jasmine',

    compilers: {
    '**/*.ts': wallaby.compilers.typeScript({
        ...compilerOptions,
      getCustomTransformers: program => {
      return {
        before: [
          require('@ngtools/webpack/src/transformers/replace_resources').replaceResources(
            path => true,
          () => program.getTypeChecker(),
        false
    )
    ]
    };
    }
  })
  },

  preprocessors: {
    /* Initialize Test Environment for Wallaby */
    [path.basename(__filename)]: file => `
 import '@angular-devkit/build-angular/src/angular-cli-files/models/jit-polyfills';
 import 'zone.js/dist/zone-testing';
 import { getTestBed } from '@angular/core/testing';
 import { BrowserDynamicTestingModule,  platformBrowserDynamicTesting} from '@angular/platform-browser-dynamic/testing';

 getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());`
  },

  middleware: function(app, express) {
    const path = require('path');

    applications.forEach(application => {
      if (
    !application.architect ||
    !application.architect.test ||
    !application.architect.test.options ||
    !application.architect.test.options.assets
  ) {
      return;
    }

    application.architect.test.options.assets.forEach(asset => {
      if (asset && !asset.glob) {
      // Only works for file assets (not globs)
      // (https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/asset-configuration.md#project-assets)
      app.use(asset.slice(application.sourceRoot.length), express.static(path.join(__dirname, asset)));
    }
  });
  });
  },

  env: {
    kind: 'chrome'
  },

  postprocessor: wallabyWebpack({
    entryPatterns: [
      ...applications
      .map(project => project.sourceRoot + '/polyfills.js')
    .filter(polyfills => fs.existsSync(path.join(__dirname, polyfills.replace(/js$/, 'ts')))),
  path.basename(__filename),
...projects.map(project => project.sourceRoot + specPattern.replace(/ts$/, 'js'))
],

  module: {
    rules: [
      { test: /\.css$/, loader: ['raw-loader'] },
      { test: /\.html$/, loader: 'raw-loader' },
      {
        test: /\.ts$/,
        loader: '@ngtools/webpack',
        include: /node_modules/,
        query: { tsConfigPath: 'tsconfig.json' }
      },
      { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
      { test: /\.less$/, loaders: ['raw-loader', { loader: 'less-loader' }] },
      {
        test: /\.scss$|\.sass$/,
        loaders: [{ loader: 'raw-loader' }, { loader: 'sass-loader', options: { implementation: require('sass'), includePaths: ['./src/styles'] } }]
      },
      { test: /\.(jpg|png|svg)$/, loader: 'raw-loader' }
    ]
  },

  resolve: {
    extensions: ['.js', '.ts'],
      modules: [
      wallaby.projectCacheDir,
      ...(projects.length ? projects.filter(project => project.root)
      .map(project => path.join(wallaby.projectCacheDir, project.root)) : []),
  ...(projects.length ? projects.filter(project => project.sourceRoot)
      .map(project => path.join(wallaby.projectCacheDir,project.sourceRoot)) : []),
    'node_modules'
  ],
    alias: libraries.reduce((result, project) => {
      result[project.name] = path.join(wallaby.projectCacheDir, project.sourceRoot, 'public-api');
    return result;
  }, {})
  }
}),

  setup: function() {
    window.__moduleBundler.loadTests();
  }
};
};


```

### Code editor or IDE name and version
WebStorm v2018.2.3

### OS name and version

OSX Catalina 10.15 Beta

**Comment by NikGovorov** [comment]
@ianjamieson,

To fix your third error, please update your configuration file:

```diff
module.exports = function(wallaby) {
  const wallabyWebpack = require('wallaby-webpack');
  const path = require('path');
  const fs = require('fs');

  const specPattern = '/**/*spec.ts';
  const angularConfig = require('./angular.json');

  const projects = Object.keys(angularConfig.projects).map(key => {
    return { name: key, ...angularConfig.projects[key] };
}).filter(project => project.sourceRoot)
.filter(project => project.projectType !== 'application' ||
  (project.architect &&
    project.architect.test &&
    project.architect.test.builder === '@angular-devkit/build-angular:karma'));

  const applications = projects.filter(project => project.projectType === 'application');
  const libraries = projects.filter(project => project.projectType === 'library');

  const tsConfigFile = projects
    .map(project => path.join(__dirname, project.root, 'tsconfig.spec.json'))
.find(tsConfig => fs.existsSync(tsConfig));

  const tsConfigSpec = tsConfigFile ? JSON.parse(fs.readFileSync(tsConfigFile)) : {};

  const compilerOptions = Object.assign(require('./tsconfig.json').compilerOptions, tsConfigSpec.compilerOptions);
  compilerOptions.emitDecoratorMetadata = true;
++compilerOptions.useStandardDefaults = true;

  return {
    files: [
      'package.json',
      { pattern: path.basename(__filename), load: false, instrument: false },
      ...projects.map(project => ({
      pattern: project.sourceRoot + '/**/*.+(ts|js|css|less|scss|sass|styl|html|json|svg)',
      load: false
    })),
...projects.map(project => ({
    pattern: project.sourceRoot + specPattern,
    ignore: true
  })),
...projects.map(project => ({
    pattern: project.sourceRoot + '/**/*.d.ts',
    ignore: true
  }))
],

  tests: [
    ...projects.map(project => ({
    pattern: project.sourceRoot + specPattern,
    load: false
  }))
],

  testFramework: 'jasmine',

    compilers: {
    '**/*.ts': wallaby.compilers.typeScript({
        ...compilerOptions,
      getCustomTransformers: program => {
      return {
        before: [
          require('@ngtools/webpack/src/transformers/replace_resources').replaceResources(
            path => true,
          () => program.getTypeChecker(),
        false
    )
    ]
    };
    }
  })
  },

  preprocessors: {
    /* Initialize Test Environment for Wallaby */
    [path.basename(__filename)]: file => `
 import '@angular-devkit/build-angular/src/angular-cli-files/models/jit-polyfills';
 import 'zone.js/dist/zone-testing';
 import { getTestBed } from '@angular/core/testing';
 import { BrowserDynamicTestingModule,  platformBrowserDynamicTesting} from '@angular/platform-browser-dynamic/testing';

 getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());`
  },

  middleware: function(app, express) {
    const path = require('path');

    applications.forEach(application => {
      if (
    !application.architect ||
    !application.architect.test ||
    !application.architect.test.options ||
    !application.architect.test.options.assets
  ) {
      return;
    }

    application.architect.test.options.assets.forEach(asset => {
      if (asset && !asset.glob) {
      // Only works for file assets (not globs)
      // (https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/asset-configuration.md#project-assets)
      app.use(asset.slice(application.sourceRoot.length), express.static(path.join(__dirname, asset)));
    }
  });
  });
  },

  env: {
    kind: 'chrome'
  },

  postprocessor: wallabyWebpack({
    entryPatterns: [
      ...applications
      .map(project => project.sourceRoot + '/polyfills.js')
    .filter(polyfills => fs.existsSync(path.join(__dirname, polyfills.replace(/js$/, 'ts')))),
  path.basename(__filename),
...projects.map(project => project.sourceRoot + specPattern.replace(/ts$/, 'js'))
],

  module: {
    rules: [
      { test: /\.css$/, loader: ['raw-loader'] },
      { test: /\.html$/, loader: 'raw-loader' },
      {
        test: /\.ts$/,
        loader: '@ngtools/webpack',
        include: /node_modules/,
        query: { tsConfigPath: 'tsconfig.json' }
      },
      { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
      { test: /\.less$/, loaders: ['raw-loader', { loader: 'less-loader' }] },
      {
        test: /\.scss$|\.sass$/,
        loaders: [{ loader: 'raw-loader' }, { loader: 'sass-loader', options: { implementation: require('sass'), includePaths: ['./src/styles'] } }]
      },
      { test: /\.(jpg|png|svg)$/, loader: 'raw-loader' }
    ]
  },

  resolve: {
    extensions: ['.js', '.ts'],
      modules: [
      wallaby.projectCacheDir,
      ...(projects.length ? projects.filter(project => project.root)
      .map(project => path.join(wallaby.projectCacheDir, project.root)) : []),
  ...(projects.length ? projects.filter(project => project.sourceRoot)
      .map(project => path.join(wallaby.projectCacheDir,project.sourceRoot)) : []),
    'node_modules'
  ],
    alias: libraries.reduce((result, project) => {
      result[project.name] = path.join(wallaby.projectCacheDir, project.sourceRoot, 'public-api');
    return result;
  }, {})
  }
}),

  setup: function() {
    window.__moduleBundler.loadTests();
  }
};
};
```
Regarding to fourth error, usually it's caused by calling `initTestEnvironment` method multiple times. Could you please check if it is the case for you? 
Wallaby calls it [once](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js#L80) during initialization and there is also standard `test.ts` that [calls it](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/test.ts#L13) file but this file should be completely ignored by wallaby, please check that you don't import the file from anywhere else.

**Comment by NikGovorov** [comment]
You could also try to use [ Automatic Configuration](https:/wallabyjs.com / docs / intro / config.html#jetbrains-ides) feature, Angular CLI support is still work in progress, but should work for single application workspaces.

**Comment by ianjamieson** [comment]
> To fix your third error, please update your configuration file:

I have updated but get:

```
./wallaby.js:28
  ++compilerOptions.useStandardDefaults = true;
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ReferenceError: Invalid left-hand side in assignment
    at new Script (vm.js:73:7)
```

So have changed that line to just:

```javascript
++compilerOptions.useStandardDefaults;
```

Now when running I get this error:

```
Postprocessor run failure: Cannot find module '@ngtools/webpack/src/transformers/replace_resources'
```

> You could also try to use Automatic Configuration feature, Angular CLI support is still work in progress, but should work for single application workspaces.

I get:

```
Failed to load configuration file: Automatic Angular CLI configuration error: Cannot detect @angular/cli package version, is the package installed?

We've also tried to automatically configure Wallaby.js for other frameworks
```

`package.json` has:

```
"devDependencies": {
    "@angular-devkit/build-angular": "0.802.1",
    "@angular/cli": "8.2.2",
    "@angular/compiler": "8.1.2",
    "@angular/compiler-cli": "8.1.2",
    "@angular/language-service": "8.2.3",
    "@ngrx/schematics": "8.2.0",
    ...
}
```

I think I will possibly wait at this point until the automatic configuration is set up for Angular CLI

**Comment by NikGovorov** [comment]
>I have updated but get:

The line I added actually should be just `compilerOptions.useStandardDefaults = true;`, `++` in diff/patch syntax means a new line in the file, so you can easily spot what's changed.

>Now when running I get this error:

Could you please check if the package is installed to `@angular-devkit/build-angular/node_modules` folder in your `node_modules` ? If so please change your config in the following way:

```diff
module.exports = function(wallaby) {
  const wallabyWebpack = require('wallaby-webpack');
  const path = require('path');
  const fs = require('fs');

  const specPattern = '/**/*spec.ts';
  const angularConfig = require('./angular.json');

  const projects = Object.keys(angularConfig.projects).map(key => {
    return { name: key, ...angularConfig.projects[key] };
}).filter(project => project.sourceRoot)
.filter(project => project.projectType !== 'application' ||
  (project.architect &&
    project.architect.test &&
    project.architect.test.builder === '@angular-devkit/build-angular:karma'));

  const applications = projects.filter(project => project.projectType === 'application');
  const libraries = projects.filter(project => project.projectType === 'library');

  const tsConfigFile = projects
    .map(project => path.join(__dirname, project.root, 'tsconfig.spec.json'))
.find(tsConfig => fs.existsSync(tsConfig));

  const tsConfigSpec = tsConfigFile ? JSON.parse(fs.readFileSync(tsConfigFile)) : {};

  const compilerOptions = Object.assign(require('./tsconfig.json').compilerOptions, tsConfigSpec.compilerOptions);
  compilerOptions.emitDecoratorMetadata = true;
  compilerOptions.useStandardDefaults = true;

  return {
    files: [
      'package.json',
      { pattern: path.basename(__filename), load: false, instrument: false },
      ...projects.map(project => ({
      pattern: project.sourceRoot + '/**/*.+(ts|js|css|less|scss|sass|styl|html|json|svg)',
      load: false
    })),
...projects.map(project => ({
    pattern: project.sourceRoot + specPattern,
    ignore: true
  })),
...projects.map(project => ({
    pattern: project.sourceRoot + '/**/*.d.ts',
    ignore: true
  }))
],

  tests: [
    ...projects.map(project => ({
    pattern: project.sourceRoot + specPattern,
    load: false
  }))
],

  testFramework: 'jasmine',

    compilers: {
    '**/*.ts': wallaby.compilers.typeScript({
        ...compilerOptions,
      getCustomTransformers: program => {
      return {
        before: [
--        require('@ngtools/webpack/src/transformers/replace_resources').replaceResources(
++        require('@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/transformers/replace_resources').replaceResources(
            path => true,
          () => program.getTypeChecker(),
        false
    )
    ]
    };
    }
  })
  },

  preprocessors: {
    /* Initialize Test Environment for Wallaby */
    [path.basename(__filename)]: file => `
 import '@angular-devkit/build-angular/src/angular-cli-files/models/jit-polyfills';
 import 'zone.js/dist/zone-testing';
 import { getTestBed } from '@angular/core/testing';
 import { BrowserDynamicTestingModule,  platformBrowserDynamicTesting} from '@angular/platform-browser-dynamic/testing';

 getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());`
  },

  middleware: function(app, express) {
    const path = require('path');

    applications.forEach(application => {
      if (
    !application.architect ||
    !application.architect.test ||
    !application.architect.test.options ||
    !application.architect.test.options.assets
  ) {
      return;
    }

    application.architect.test.options.assets.forEach(asset => {
      if (asset && !asset.glob) {
      // Only works for file assets (not globs)
      // (https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/asset-configuration.md#project-assets)
      app.use(asset.slice(application.sourceRoot.length), express.static(path.join(__dirname, asset)));
    }
  });
  });
  },

  env: {
    kind: 'chrome'
  },

  postprocessor: wallabyWebpack({
    entryPatterns: [
      ...applications
      .map(project => project.sourceRoot + '/polyfills.js')
    .filter(polyfills => fs.existsSync(path.join(__dirname, polyfills.replace(/js$/, 'ts')))),
  path.basename(__filename),
...projects.map(project => project.sourceRoot + specPattern.replace(/ts$/, 'js'))
],

  module: {
    rules: [
      { test: /\.css$/, loader: ['raw-loader'] },
      { test: /\.html$/, loader: 'raw-loader' },
      {
        test: /\.ts$/,
        loader: '@ngtools/webpack',
        include: /node_modules/,
        query: { tsConfigPath: 'tsconfig.json' }
      },
      { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
      { test: /\.less$/, loaders: ['raw-loader', { loader: 'less-loader' }] },
      {
        test: /\.scss$|\.sass$/,
        loaders: [{ loader: 'raw-loader' }, { loader: 'sass-loader', options: { implementation: require('sass'), includePaths: ['./src/styles'] } }]
      },
      { test: /\.(jpg|png|svg)$/, loader: 'raw-loader' }
    ]
  },

  resolve: {
    extensions: ['.js', '.ts'],
      modules: [
      wallaby.projectCacheDir,
      ...(projects.length ? projects.filter(project => project.root)
      .map(project => path.join(wallaby.projectCacheDir, project.root)) : []),
  ...(projects.length ? projects.filter(project => project.sourceRoot)
      .map(project => path.join(wallaby.projectCacheDir,project.sourceRoot)) : []),
    'node_modules'
  ],
    alias: libraries.reduce((result, project) => {
      result[project.name] = path.join(wallaby.projectCacheDir, project.sourceRoot, 'public-api');
    return result;
  }, {})
  }
}),

  setup: function() {
    window.__moduleBundler.loadTests();
  }
};
};
```

>I get:

Does `../../test` export TestUtils? Does `ng test` work for the project?

**Comment by smcenlly** [comment]
@ianjamieson - since we didn't hear back from you, I'm going to assume this fixed your problem. If not, please let us know and we will re-open this issue and assist you.
