### ISSUE TITLE
Wallaby not transforming HTML any more

### ISSUE THREAD

**Issue by adover** [wallabyjs/public#2197]
### Issue description or question
It seems that something updated causing Wallaby to fail transforming HTML. I've tried all of the usual tricks to get it running but for some reason it is not successful.

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
    return {
        files: [
            'tsconfig.json',
            'tsconfig.spec.json',
            'jest.config.js',
            'apps/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
            '!apps/**/*.spec.ts',
            '!apps/**/*.stories.ts',
            '!apps/**/main.ts',
            'libs/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
            '!libs/**/*.spec.ts',
            '!libs/**/*.stories.ts',
            '!libs/**/environment.*.ts',
            '!libs/**/environment.ts',
            '!apps/legacy-restyle/**/*.*',
        ],

        tests: [
            './apps/**/*.spec.ts',
            './libs/**/*.spec.ts',
            '!apps/pluto-e2e/**/*.spec.ts',
            '!apps/product-stamp-e2e/**/*.spec.ts',
        ],

        env: {
            type: 'node',
            runner: 'node',
            params: {
                runner: '--max-old-space-size=12288',
            },
        },

        debug: true,

        testFramework: 'jest',

        compilers: {
            '**/*.ts?(x)': wallaby.compilers.typeScript({
                module: 'commonjs',
                getCustomTransformers: () => {
                    return {
                        before: [
                            require('jest-preset-angular/InlineHtmlStripStylesTransformer').factory(
                                { compilerModule: require('typescript') }
                            ),
                        ],
                    };
                },
            }),
            '**/*.html': file => ({
                code: require('ts-jest').process(file.content, file.path, {
                    globals: {
                        'ts-jest': {
                            stringifyContentPathRegex: '\\.html$',
                        },
                    },
                }),
                map: { version: 3, sources: [], names: [], mappings: [] },
                ranges: [],
            }),
        },

        preprocessors: {
            '**/*.js': file =>
                require('@babel/core').transform(file.content, {
                    sourceMap: true,
                    compact: false,
                    filename: file.path,
                    presets: [require('babel-preset-jest')],
                }),
        },

        setup: function(wallaby) {
            let jestConfig = require('./jest.config');
            delete jestConfig.preset;
            jestConfig = Object.assign(
                require('jest-preset-angular/jest-preset'),
                jestConfig
            );
            jestConfig.transformIgnorePatterns.push('instrumented.*.(jsx?|html)$');
            jestConfig.rootDir = './';
            jestConfig.setupFilesAfterEnv = ['./apps/pluto/src/test-setup.ts'];

            jestConfig.transform = { '^.+\\.(ts)$': 'ts-jest' };

            wallaby.testFramework.configure(jestConfig);
        },
    };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.37

### OS name and version

Windows 10

Error Trace
```
[Error] Runtime error: Jest encountered an unexpected token 
[Error] This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript. 
[Error] By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules". 
[Error] Here's what you can do: 
[Error]  • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config. 
[Error]  • If you need a custom transformation specify a "transform" option in your config. 
[Error]  • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper
[package.json.txt](https://github.com/wallabyjs/public/files/3572296/package.json.txt)
[package-lock.json.txt](https://github.com/wallabyjs/public/files/3572297/package-lock.json.txt)

" config option. 
[Error] You'll find more details and examples of these config options in the docs: 
[Error] https://jestjs.io/docs/en/configuration.html 
[Error] Details: 
[Error] .\libs\styleguide\src\lib\4_atoms\components\input\input.component.html:1 
[Error] ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){<ng-container *ngIf="isCharInput; then characterInput; else clickableInput"> 
[Error]                                                                                          ^ 
[Error] SyntaxError: Unexpected token < 
[Error]     at new Script (vm.js:83:7) 
[Error]     at ScriptTransformer._transformAndBuildScript (.\node_modules\@jest\transform\build\ScriptTransformer.js:537:17) 
[Error]     at ScriptTransformer.transform (.\node_modules\@jest\transform\build\ScriptTransformer.js:579:25) 
[Error]     at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:842:53) 
[Error]     at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:577:12) 
[Error]     at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:433:10) 
[Error]     at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:598:21) 
[Error]     at Object.<anonymous> (.\libs\styleguide\src\lib\4_atoms\components\input\input.component.js:131:13) 
[Error]     at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:867:68) 
[Error]     at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:577:12) 
[Error]     at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:433:10) 
[Error]     at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:598:21) 
[Error]     at Object.<anonymous> (.\libs\styleguide\src\lib\4_atoms\components\input\input.component.spec.js:11:42) 
[Error]     at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:867:68) 
[Error]     at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:577:12) 
[Error]     at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:433:10) 
[Error]     at .\node_modules\jest-jasmine2\build\index.js:202:13 
[Error]     at Generator.next (<anonymous>) 
[Error]     at asyncGeneratorStep (.\node_modules\jest-jasmine2\build\index.js:27:24) 
[Error]     at _next (.\node_modules\jest-jasmine2\build\index.js:47:9) 
[Error]     at .\node_modules\jest-jasmine2\build\index.js:52:7 
[Error]     at new Promise (<anonymous>) 
[Error]     at .\node_modules\jest-jasmine2\build\index.js:44:12 
[Error]     at jasmine2 (.\node_modules\jest-jasmine2\build\index.js:60:19) 
[Error]     at .\node_modules\jest-runner\build\runTest.js:385:24 
[Error]     at Generator.next (<anonymous>) 
[Error]     at asyncGeneratorStep (.\node_modules\jest-runner\build\runTest.js:161:24) 
[Error]     at _next (.\node_modules\jest-runner\build\runTest.js:181:9) 
```

I also tried in a previous issue repo https://github.com/ArtemGovorov/wallaby-2187 by adding HTML files in the lib and installing using the package lock and json supplied but it is throwing the same error

**Comment by ArtemGovorov** [comment]
While we are investigating the issue, could you please try [automatic Jest configuration feature](https://wallabyjs.com/docs/intro/config.html#vs-code)? If it works for you, you will not need any config.

**Comment by adover** [comment]
> While we are investigating the issue, could you please try [automatic Jest configuration feature](https://wallabyjs.com/docs/intro/config.html#vs-code)? If it works for you, you will not need any config.

I'm using Nrwl Nx (so not importing jest-preset-angular) in the jest.config. Therefore it throws a `Runtime error: ReferenceError: Zone is not defined `

**Comment by ArtemGovorov** [comment]
The issue was caused by our recent breaking changed in Wallaby defaults. The issue is fixed and the fix is published [in the latest Wallaby core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
