### ISSUE TITLE
[WebStorm] Plugin crash

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/public#2223]
### Issue description or question

WebStorm plugin crashes

WebStorm version: 2019.3 EAP#3
Wallaby version: 1.0.140
OS: Windows 10 Pro

![crach](https://user-images.githubusercontent.com/6392013/65803223-a9ac0100-e186-11e9-8761-4440957e99c8.png)

Stacktrace:
```
java.lang.NullPointerException
	at com.wallaby.javascript.WallabyController.a(Unknown Source)
	at com.wallaby.javascript.b.a(Unknown Source)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:368)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:217)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:705)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by smcenlly** [comment]
We were unable to reproduce the issue in both the latest EAP and earlier versions of WebStorm. We did receive a number of WebStorm errors before even installing Wallaby with the latest EAP so it may not be entirely stable.

Were you able to reproduce the error in an earlier version of WebStorm?

**We have released a new version of the Wallaby for IntelliJ plugin (v1.0.141) that may fix your problem.** If it does not, could you please detail the steps that you're taking before the error occurs? e.g. is it when you change projects? When you first launch? etc.

**Comment by Alexsey** [comment]
Unfortunately, I didn't catch the exact moment when the error occurred, so I'm not sure what was I doing specifically before the throw

After updating Wallaby to version 1.0.141 I didn't catch this error anymore, so maybe it has been resolved. I think the issue may be closed now and reopened in case if the error would happen again, or it can remain open for a few days - maybe someone else would catch it as well, and if not - to be closed after
