### ISSUE TITLE
cannot find module error

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#223]
Using PyCharm 4.5.3.

Wallaby console:

```
wallaby.js started
core v1.0.84
Runtime error: Error: Cannot find module '/Users/boneskull/Library/Caches/PyCharm40/wallaby/projects/16aa0d4113d44a47/instrumented/app/'
    at Function.Module._resolveFilename (module.js:316:15)
    at Function.require.resolve (module.js:368:19)
    at Environment.resolveModulePath (/Volumes/alien/projects/boneskull/generator-boneskull/node_modules/yeoman-generator/node_modules/yeoman-environment/lib/environment.js:422:18)
    at Environment.register (/Volumes/alien/projects/boneskull/generator-boneskull/node_modules/yeoman-generator/node_modules/yeoman-environment/lib/environment.js:160:25)
    at /Volumes/alien/projects/boneskull/generator-boneskull/node_modules/yeoman-generator/lib/test/helpers.js:187:11
    at Array.forEach (native)
    at Object.exports.registerDependencies (/Volumes/alien/projects/boneskull/generator-boneskull/node_modules/yeoman-generator/lib/test/helpers.js:183:16)
    at Object.exports.createGenerator (/Volumes/alien/projects/boneskull/generator-boneskull/node_modules/yeoman-generator/lib/test/helpers.js:170:8)
    at Context.<anonymous> (/Users/boneskull/Library/Caches/PyCharm40/wallaby/projects/16aa0d4113d44a47/instrumented/test/index.spec.js:18:46)
    at /Volumes/alien/projects/boneskull/generator-boneskull/node_modules/yeoman-generator/lib/test/helpers.js:96:5
Finished executing 0 affected test(s)
```

Failing test console:

![failing test console](http://content.screencast.com/users/chiller/folders/Jing/media/0cab39d7-2a73-47fe-9bbc-d07cc6d6bf8b/00000219.png)

Inline error:

![inline error](http://content.screencast.com/users/chiller/folders/Jing/media/83d80191-8d82-4a6b-9436-a57e0c86567f/00000218.png)

**Comment by boneskull** [comment]
MacOS 10.10.4, io.js v2.4.0

**Comment by ArtemGovorov** [comment]
Could you please share your wallaby config file?

Maybe something inside `createGenerator` requires `app/index.js` and the file is [not listed](http://wallabyjs.com/docs/intro/troubleshooting.html#39-cannot-find-module-39-or-39-file-not-found-39) in the `files` list?

**Comment by boneskull** [comment]
```json
{
  "files": [
    "lib/**/*.js"
  ],
  "tests": [
    "test/**/*.js"
  ],
  "testFramework": "mocha",
  "env": {
    "type": "node"
  }
}
```

**Comment by boneskull** [comment]
but to your question, yeah that's probably what is happening

**Comment by boneskull** [comment]
actually I see the problem

**Comment by ArtemGovorov** [comment]
Does including the `index.js` to the `files` list fix the issue?

**Comment by boneskull** [comment]
yes, but my problem now is that I have files with extension `.js` which should *not* be instrumented, but *should* be copied to the instrumented dir.  any suggestions?

**Comment by ArtemGovorov** [comment]
Try setting [`instrument: false`](http://wallabyjs.com/docs/config/files.html#file-object) to those files/patterns.

**Comment by ArtemGovorov** [comment]
BTW, if those files are node modules in subfolders, it's better not to copy (and not to list them at all), but rather use [this solution](https://github.com/wallabyjs/public/issues/210).

**Comment by ArtemGovorov** [comment]
Closing this for now, please let me know if there's still an issue with instrumenting files.
