### ISSUE TITLE
wallaby.js and CRA typescript project with ts-nameof.macro package

### ISSUE THREAD

**Issue by PhilippK13** [wallabyjs/public#2231]
### Issue description or question
Hi,
I'm trying to setup wallaby.js on the project created with CRA typescript and [react-app-rewired](https://github.com/timarney/react-app-rewired). I'm also using[ ts-nameof.macro](https://github.com/dsherret/ts-nameof/tree/master/packages/ts-nameof.macro).

The project itself starts without an issue, however, when starting wallaby in VS Code, I get the following error:

`Postprocessor run failure: Failed to run preprocessors on src/App.js, Error: ts-nameof.macro: [ts-nameof]: Unhandled node type (SequenceExpression) in text:...`

### Wallaby diagnostics report

```
{ editorVersion: '1.38.1',
  pluginVersion: '1.0.146',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.17763',
  nodeVersion: 'v10.15.3',
  coreVersion: '1.0.761',
  config:
   { files:
      [ { pattern: 'src/setupTests.ts', instrument: false, ignore: false, trigger: true, load: true, order: 1 },
        { pattern: 'src/**/*.+(ts|js|tsx|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
        { pattern: 'src/**/*.test.ts?(x)', ignore: true, trigger: true, load: true, instrument: true },
        { pattern: 'src/**/*.test.ts?(x).snap', ignore: false, instrument: false, trigger: true, load: true, order: 3 },
        { pattern: 'package.json', ignore: false, instrument: false, trigger: true, load: true, order: 4 } ],
     tests: [ { pattern: 'src/**/*.test.ts?(x)', ignore: false, trigger: true, load: true, test: true, order: 5 } ],
     env: { type: 'node', params: {}, runner: 'C:\\Program Files\\nodejs\\node.exe', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
     compilers: { '**/*.js': [Function], '**/*.?(lit)coffee?(.md)': [Function] },
     preprocessors: { '**/*.js?(x)': [Function: **/*.js?(x)], 'package.json': [Function] },
     testFramework: { version: 'jest@0.4.3', configurator: 'jest@0.4.3', reporter: 'jest@0.4.3', starter: 'jest@0.4.3' },
     diagnostics: {},
     filesWithNoCoverageCalculated: [],
     runAllTestsInAffectedTestFile: false,
     maxConsoleMessagesPerTest: 100,
     autoConsoleLog: true,
     delays: { run: 0, edit: 100, update: 0 },
     workers: { initial: 0, regular: 0, recycle: false },
     teardown: undefined,
     hints:
      { ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
        ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
        commentAutoLog: '?',
        testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' } },
     automaticTestFileSelection: true,
     runSelectedTestsOnly: false,
     extensions: {},
     reportUnhandledPromises: true,
     slowTestThreshold: 75,
     lowCoverageThreshold: 80,
     loose: true,
     configCode:
      'module.exports = function(wallaby) {\r\n  var path = require("path");\r\n  process.env.BABEL_ENV = "test";\r\n  process.env.NODE_ENV = "test";\r\n  process.env.NODE_PATH +=\r\n    path.delimiter +\r\n    path.join(__dirname, "node_modules") +\r\n    path.delimiter +\r\n    path.join(__dirname, "node_modules/react-scripts/node_modules") +\r\n    path.delimiter +\r\n    path.join(wallaby.projectCacheDir, "src");\r\n  require("module").Module._initPaths();\r\n\r\n  return {\r\n    files: [\r\n      { pattern: "src/setupTests.ts", instrument: false },\r\n      "src/**/*.+(ts|js|tsx|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)",\r\n      "!src/**/*.test.ts?(x)"\r\n    ],\r\n    tests: ["src/**/*.test.ts?(x)"],\r\n    env: {\r\n      type: "node"\r\n    },\r\n    compilers: {\r\n      "**/*.js": wallaby.compilers.babel()\r\n    },\r\n    preprocessors: {\r\n      "**/*.js?(x)": file =>\r\n        require("@babel/core").transform(file.content, {\r\n          sourceMap: true,\r\n          compact: false,\r\n          filename: file.path,\r\n          presets: [require("babel-preset-jest"), "react-app"]\r\n        })\r\n    },\r\n    setup: wallaby => {\r\n      const jestConfig = require("react-scripts/scripts/utils/createJestConfig")(\r\n        p => require.resolve("react-scripts/" + p)\r\n      );\r\n      Object.keys(jestConfig.transform || {}).forEach(\r\n        k => ~k.indexOf("^.+\\\\.(js|jsx") && void delete jestConfig.transform[k]\r\n      );\r\n\r\n      delete jestConfig.testEnvironment;\r\n      wallaby.testFramework.configure(jestConfig);\r\n    },\r\n    testFramework: "jest"\r\n  };\r\n};\r\n' },
  packageJSON:
   { dependencies: { react: '^16.10.1', 'react-dom': '^16.10.1', 'react-scripts': '3.1.2' },
     devDependencies:
      { '@testing-library/jest-dom': '^4.1.0',
        '@testing-library/react': '^9.3.0',
        '@types/jest': '^24.0.18',
        '@types/node': '^12.7.5',
        '@types/react': '^16.9.5',
        '@types/react-dom': '^16.9.1',
        '@types/react-test-renderer': '^16.9.0',
        '@typescript-eslint/eslint-plugin': '^2.3.0',
        '@typescript-eslint/parser': '^2.3.0',
        'jest-environment-jsdom-fifteen': '^1.0.0',
        'jest-junit': '^8.0.0',
        'jest-watch-typeahead': '^0.4.0',
        react: '^16.9.5',
        'react-app-rewired': '^2.1.3',
        'react-dom': '^16.9.1',
        'react-scripts': '^3.1.1',
        'react-test-renderer': '^16.9.0',
        'ts-nameof.macro': '^4.0.3',
        typescript: '^3.6.3' } },
  fs: { numberOfFiles: 9 },
  debug:
   [ '2019-10-06T08:22:13.371Z project Wallaby Node version: v10.15.3\n',
     '2019-10-06T08:22:13.372Z project Wallaby config: ...\\CRA\\wallaby-ts-nameof-macro-issue\\wallaby.js\n',
     '2019-10-06T08:22:13.915Z project File cache: ...\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.146\\projects\\f9a7566d7c33ca1c\n',
     '2019-10-06T08:22:13.983Z uiService Listening port 51236\n',
     '2019-10-06T08:22:14.001Z project package.json file change detected, invalidating local cache\n',
     '2019-10-06T08:22:14.007Z workers Parallelism for initial run: 10, for regular run: 5\n',
     '2019-10-06T08:22:14.007Z workers Starting run worker instance #0\n',
     '2019-10-06T08:22:14.007Z workers Starting run worker instance #1\n',
     '2019-10-06T08:22:14.007Z workers Starting run worker instance #2\n',
     '2019-10-06T08:22:14.007Z workers Starting run worker instance #3\n',
     '2019-10-06T08:22:14.007Z workers Starting run worker instance #4\n',
     '2019-10-06T08:22:14.007Z workers Starting run worker instance #5\n',
     '2019-10-06T08:22:14.007Z workers Starting run worker instance #6\n',
     '2019-10-06T08:22:14.007Z workers Starting run worker instance #7\n',
     '2019-10-06T08:22:14.007Z workers Starting run worker instance #8\n',
     '2019-10-06T08:22:14.007Z workers Starting run worker instance #9\n',
     '2019-10-06T08:22:14.008Z workers Web server is listening at 50795\n',
     '2019-10-06T08:22:14.009Z project File cache requires some updates, waiting required files from IDE\n',
     '2019-10-06T08:22:14.889Z workers Started run worker instance (delayed) #0\n',
     '2019-10-06T08:22:14.897Z workers Started run worker instance (delayed) #8\n',
     '2019-10-06T08:22:14.929Z workers Started run worker instance (delayed) #3\n',
     '2019-10-06T08:22:14.932Z workers Started run worker instance (delayed) #2\n',
     '2019-10-06T08:22:14.937Z workers Started run worker instance (delayed) #5\n',
     '2019-10-06T08:22:14.941Z workers Started run worker instance (delayed) #9\n',
     '2019-10-06T08:22:14.941Z workers Started run worker instance (delayed) #4\n',
     '2019-10-06T08:22:14.950Z workers Started run worker instance (delayed) #1\n',
     '2019-10-06T08:22:14.954Z workers Started run worker instance (delayed) #6\n',
     '2019-10-06T08:22:15.024Z workers Started run worker instance (delayed) #7\n',
     '2019-10-06T08:22:16.399Z project Stopping process pool\n',
     '2019-10-06T08:22:16.400Z project Running postprocessor\n',
     '2019-10-06T08:22:16.403Z postprocessor New TypeScript language service is required\n',
     '2019-10-06T08:22:17.112Z project Error: Failed to run preprocessors on src/App.js, Error: ts-nameof.macro: [ts-nameof]: Unhandled node type (SequenceExpression) in text: $_$w(5, 1), o.bar.prop1 (Please open an issue if you believe this should be supported.) Learn more: https://www.npmjs.com/package/ts-nameof.macro\n    at Object.throwError (.\\node_modules\\@ts-nameof\\common\\dist\\errors.js:4:11)\n    at parseCommonNode (.\\node_modules\\@ts-nameof\\transforms-babel\\dist\\parse.js:84:25)\n    at parseFunctionReturnExpression (.\\node_modules\\@ts-nameof\\transforms-babel\\dist\\parse.js:129:42)\n    at parseCommonNode (.\\node_modules\\@ts-nameof\\transforms-babel\\dist\\parse.js:51:20)\n    at .\\node_modules\\@ts-nameof\\transforms-babel\\dist\\parse.js:45:63\n    at Array.map (<anonymous>)\n    at parseArguments (.\\node_modules\\@ts-nameof\\transforms-babel\\dist\\parse.js:45:35)\n    at parseNameof (.\\node_modules\\@ts-nameof\\transforms-babel\\dist\\parse.js:29:24)\n    at Object.parse (.\\node_modules\\@ts-nameof\\transforms-babel\\dist\\parse.js:24:12)\n    at Object.transformNode (.\\node_modules\\@ts-nameof\\transforms-babel\\dist\\index.js:20:31)\n    at .\\node_modules\\ts-nameof.macro\\dist\\index.js:11:28\n    at Array.forEach (<anonymous>)\n    at nameofMacro (.\\node_modules\\ts-nameof.macro\\dist\\index.js:9:20)\n    at macroWrapper (.\\node_modules\\babel-plugin-macros\\dist\\index.js:61:12)\n    at applyMacros (.\\node_modules\\babel-plugin-macros\\dist\\index.js:224:14)\n    at ImportDeclaration (.\\node_modules\\babel-plugin-macros\\dist\\index.js:108:28)\n    at NodePath._call (.\\node_modules\\@babel\\traverse\\lib\\path\\context.js:53:20)\n    at NodePath.call (.\\node_modules\\@babel\\traverse\\lib\\path\\context.js:40:17)\n    at NodePath.visit (.\\node_modules\\@babel\\traverse\\lib\\path\\context.js:88:12)\n    at TraversalContext.visitQueue (.\\node_modules\\@babel\\traverse\\lib\\context.js:120:16)\n    at TraversalContext.visitMultiple (.\\node_modules\\@babel\\traverse\\lib\\context.js:87:17)\n    at TraversalContext.visit (.\\node_modules\\@babel\\traverse\\lib\\context.js:146:19)\n    at Function.traverse.node (.\\node_modules\\@babel\\traverse\\lib\\index.js:96:17)\n    at traverse (.\\node_modules\\@babel\\traverse\\lib\\index.js:78:12)\n    at NodePath.traverse (.\\node_modules\\@babel\\traverse\\lib\\path\\index.js:163:24)\n    at PluginPass.Program (.\\node_modules\\babel-plugin-macros\\dist\\index.js:89:18)\n    at newFn (.\\node_modules\\@babel\\traverse\\lib\\visitors.js:195:21)\n    at NodePath._call (.\\node_modules\\@babel\\traverse\\lib\\path\\context.js:53:20)\n    at NodePath.call (.\\node_modules\\@babel\\traverse\\lib\\path\\context.js:40:17)\n    at NodePath.visit (.\\node_modules\\@babel\\traverse\\lib\\path\\context.js:88:12)\n    at TraversalContext.visitQueue (.\\node_modules\\@babel\\traverse\\lib\\context.js:120:16)\n    at TraversalContext.visitSingle (.\\node_modules\\@babel\\traverse\\lib\\context.js:92:19)\n    at TraversalContext.visit (.\\node_modules\\@babel\\traverse\\lib\\context.js:148:19)\n    at Function.traverse.node (.\\node_modules\\@babel\\traverse\\lib\\index.js:96:17)\n    at traverse (.\\node_modules\\@babel\\traverse\\lib\\index.js:78:12)\n    at transformFile (.\\node_modules\\@babel\\core\\lib\\transformation\\index.js:88:29)\n    at runSync (.\\node_modules\\@babel\\core\\lib\\transformation\\index.js:45:3)\n    at transformSync (.\\node_modules\\@babel\\core\\lib\\transform.js:43:38)\n    at Object.transform (.\\node_modules\\@babel\\core\\lib\\transform.js:22:38)\n    at **/*.js?(x) (.\\wallaby.js:29:32)\n    at process._tickCallback (internal/process/next_tick.js:61:11)\n    at ...\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.146\\wallaby\\server.js:22:254\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n',
     '2019-10-06T08:22:17.113Z project Test run finished\n',
     '2019-10-06T08:22:17.113Z project Test run data re-queued\n' ] }
```
### Sample repo

You can find a sample project where issue is reproduced [here](https://github.com/PhilippK13/wallaby-ts-nameof-macro).

**Comment by smcenlly** [comment]
Sorry for the slow reply on this issue. We normally manage tickets via email and for some reason nobody received an email related for this issue. We're looking at your repo now.

**Comment by smcenlly** [comment]
Hi @PhilippK13 - your issue went missing almost immediately after our response and we didn't get a chance to investigate at all. In fact, we couldn't figure out what had happened (we thought maybe you deleted the issue). If your account gets suspended again, please send us an email and we can help you that way (hello@wallabyjs.com). We have now cloned your repository and are taking a look.

**Comment by smcenlly** [comment]
Good news, we have taken a look at your project and have a quick fix for you. Since your project is using Jest v24+, you are able to use our [Automatic Configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) feature.

Since you are using VS Code, to start Wallaby without a configuration file run the `Wallaby.js: Select Configuration` command and then select Automatic Configuration <project directory> option once. After that you may keep using Wallaby Start command as usual and it will start Wallaby with automatic configuration.

![image](https://user-images.githubusercontent.com/2074089/66966646-519b5700-f0c1-11e9-8455-c4de075897ad.png)

If you want to use a configuration file (not recommended), this will work for you:

```diff
module.exports = function(wallaby) {
  var path = require("path");
  process.env.BABEL_ENV = "test";
  process.env.NODE_ENV = "test";
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, "node_modules") +
    path.delimiter +
    path.join(__dirname, "node_modules/react-scripts/node_modules") +
    path.delimiter +
    path.join(wallaby.projectCacheDir, "src");
  require("module").Module._initPaths();

  return {
    files: [
      { pattern: "src/setupTests.ts", instrument: false },
      "src/**/*.+(ts|js|tsx|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)",
      "!src/**/*.test.ts?(x)"
    ],
    tests: ["src/**/*.test.ts?(x)"],
    env: {
      type: "node"
    },
    compilers: {
-     "**/*.js": wallaby.compilers.babel()
+     "**/*.js": wallaby.compilers.babel({presets: ["react-app"]})
    },
-   preprocessors: {
-     "**/*.js?(x)": file =>
-       require("@babel/core").transform(file.content, {
-         sourceMap: true,
-         compact: false,
-         filename: file.path,
-         presets: [require("babel-preset-jest"), "react-app"]
-       })
-   },
    setup: wallaby => {
      const jestConfig = require("react-scripts/scripts/utils/createJestConfig")(
        p => require.resolve("react-scripts/" + p)
      );
      Object.keys(jestConfig.transform || {}).forEach(
        k => ~k.indexOf("^.+\\.(js|jsx") && void delete jestConfig.transform[k]
      );

      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },
    testFramework: "jest"
  };
};
```
