### ISSUE TITLE
Configuring wallaby with vue/jest to transform folder in node_modules

### ISSUE THREAD

**Issue by brianbender** [wallabyjs/public#2236]
### Issue description or question

I'm having an issue configuring wallaby to transform some Javascript in node_modules. I could use some assistance with determining the correct way to configure Wallaby for this scenario.

[Here](https://github.com/brianbender/test-app) is a simple repository demonstrating the issue. The structure of the project is a vue-cli app with jest, where a package in node_modules needs to be transformed according to the `transformIgnorePatterns` in the jest configuration.

Unit tests ran through `vue-cli-service test:unit` will pass, while Wallaby will fail with the following error:

```[Error] Runtime error: Jest encountered an unexpected token 
[Error] This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript. 
[Error] By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules". 
[Error] Here's what you can do: 
[Error]  • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config. 
[Error]  • If you need a custom transformation specify a "transform" option in your config. 
[Error]  • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option. 
[Error] You'll find more details and examples of these config options in the docs: 
[Error] https://jestjs.io/docs/en/configuration.html 
[Error] Details: 
[Error] .\node_modules\@enlearn\warehouse\src\index.js:1 
[Error] ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { createInMemoryStorage } from "./in-memory-storage"; 
[Error]                                                                                          ^^^^^^ 
[Error] SyntaxError: Unexpected token export 
[Error]     at new Script (vm.js:83:7) 
[Error]     at ScriptTransformer._transformAndBuildScript (.\node_modules\jest-runtime\build\script_transformer.js:400:17) 
[Error]     at ScriptTransformer.transform (.\node_modules\jest-runtime\build\script_transformer.js:445:19) 
[Error]     at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:640:53) 
[Error]     at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:376:14) 
[Error]     at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:463:19) 
[Error]     at .\src\components\HelloWorld.vue:5:1 
[Error]     at Object.<anonymous> (.\src\components\HelloWorld.vue:21:3) 
[Error]     at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:694:13) 
[Error]     at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:376:14) 
[Error]     at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:463:19) 
[Error]     at Object.<anonymous> (.\tests\unit\example.spec.js:5:55) 
[Error]     at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:694:13) 
[Error]     at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:376:14) 
[Error]     at .\node_modules\jest-jasmine2\build\index.js:129:13 
[Error]     at Generator.next (<anonymous>) 
[Error]     at step (.\node_modules\jest-jasmine2\build\index.js:170:30) 
[Error]     at .\node_modules\jest-jasmine2\build\index.js:189:14 
[Error]     at new Promise (<anonymous>) 
[Error]     at .\node_modules\jest-jasmine2\build\index.js:167:12 
[Error]     at jasmine2 (.\node_modules\jest-jasmine2\build\index.js:138:17) 
[Error]     at .\node_modules\jest-runner\build\run_test.js:187:24 
[Error]     at Generator.next (<anonymous>) 
[Error]     at step (.\node_modules\jest-runner\build\run_test.js:315:30) 
[Error]     at .\node_modules\jest-runner\build\run_test.js:326:15 
[Error]     at process._tickCallback (internal/process/next_tick.js:68:7) 
```

### Wallaby diagnostics report

```
{ editorVersion: '1.38.1',
  pluginVersion: '1.0.146',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.18362',
  nodeVersion: 'v10.16.3',
  coreVersion: '1.0.766',
  config:
   { files:
      [ { pattern: 'src/**/*', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
        { pattern: 'jest.config.js', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
        { pattern: 'package.json', ignore: false, trigger: true, load: true, instrument: true, order: 3 },
        { pattern: 'tests/**/*.spec.js.snap', ignore: false, instrument: false, trigger: true, load: true, order: 4 } ],
     tests: [ { pattern: 'tests/**/*.spec.js', ignore: false, trigger: true, load: true, test: true, order: 5 } ],
     env: { type: 'node', params: {}, runner: 'C:\\Program Files\\nodejs\\node.exe', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
     compilers: { '**/*.js': [Function], '**/*.vue': [Function], '**/*.?(lit)coffee?(.md)': [Function] },
     preprocessors: { '**/*.vue': [Function: **/*.vue], 'package.json': [Function] },
     testFramework: { version: 'jest@0.4.3', configurator: 'jest@0.4.3', reporter: 'jest@0.4.3', starter: 'jest@0.4.3' },
     diagnostics: {},
     filesWithNoCoverageCalculated: [],
     runAllTestsInAffectedTestFile: false,
     maxConsoleMessagesPerTest: 100,
     autoConsoleLog: true,
     delays: { run: 0, edit: 100, update: 0 },
     workers: { initial: 0, regular: 0, recycle: false },
     teardown: undefined,
     hints:
      { ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
        ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
        commentAutoLog: '?',
        testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' } },
     automaticTestFileSelection: true,
     runSelectedTestsOnly: false,
     extensions: {},
     reportUnhandledPromises: true,
     slowTestThreshold: 75,
     lowCoverageThreshold: 80,
     loose: true,
     configCode:
      'module.exports = (wallaby) => {\r\n\r\n    process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true;\r\n  \r\n    const compiler = wallaby.compilers.babel({presets: [[\'@vue/app\', {modules: \'commonjs\'}]]})\r\n  \r\n    return {\r\n      files: [\'src/**/*\', \'jest.config.js\', \'package.json\'],\r\n      tests: [\'tests/**/*.spec.js\'],\r\n      env: {\r\n        type: \'node\'\r\n      },\r\n  \r\n      compilers: {\r\n        \'**/*.js\': compiler,\r\n        \'**/*.vue\': require(\'wallaby-vue-compiler\')(compiler)\r\n      },\r\n  \r\n      preprocessors: {\r\n        \'**/*.vue\': file => require(\'vue-jest\').process(file.content, file.path, require(\'./jest.config\'))\r\n      },\r\n  \r\n      setup: function (wallaby) {\r\n        const jestConfig = require(\'./package\').jest || require(\'./jest.config\')\r\n        jestConfig.transform = {}\r\n        wallaby.testFramework.configure(jestConfig)\r\n      },\r\n  \r\n      testFramework: \'jest\'\r\n    }\r\n  }\r\n  \r\n  \r\n' },
  packageJSON:
   { dependencies: { '@enlearn/warehouse': '^0.5.0', 'core-js': '^2.6.5', vue: '^2.6.10' },
     devDependencies:
      { '@vue/cli-plugin-babel': '^3.11.0',
        '@vue/cli-plugin-eslint': '^3.11.0',
        '@vue/cli-plugin-unit-jest': '^3.11.0',
        '@vue/cli-service': '^3.11.0',
        '@vue/test-utils': '1.0.0-beta.29',
        'babel-core': '7.0.0-bridge.0',
        'babel-eslint': '^10.0.1',
        'babel-jest': '^23.6.0',
        eslint: '^5.16.0',
        'eslint-plugin-vue': '^5.0.0',
        'node-sass': '^4.12.0',
        'sass-loader': '^8.0.0',
        'vue-template-compiler': '^2.6.10',
        'wallaby-vue-compiler': '^1.0.6' } },
  fs: { numberOfFiles: 8 },
  debug:
   [ '2019-10-10T17:41:06.601Z project Wallaby Node version: v10.16.3\n',
     '2019-10-10T17:41:06.601Z project Wallaby config: C:\\dev\\test-app\\wallaby.conf.js\n',
     '2019-10-10T17:41:07.222Z project File cache: C:\\Users\\Brian\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.146\\projects\\985c99a239b663bf\n',
     '2019-10-10T17:41:07.265Z uiService Listening port 51236\n',
     '2019-10-10T17:41:07.292Z workers Parallelism for initial run: 6, for regular run: 3\n',
     '2019-10-10T17:41:07.292Z workers Starting run worker instance #0\n',
     '2019-10-10T17:41:07.292Z workers Starting run worker instance #1\n',
     '2019-10-10T17:41:07.292Z workers Starting run worker instance #2\n',
     '2019-10-10T17:41:07.292Z workers Starting run worker instance #3\n',
     '2019-10-10T17:41:07.292Z workers Starting run worker instance #4\n',
     '2019-10-10T17:41:07.292Z workers Starting run worker instance #5\n',
     '2019-10-10T17:41:07.293Z workers Web server is listening at 59790\n',
     '2019-10-10T17:41:07.335Z project File cache requires some updates, waiting required files from IDE\n',
     '2019-10-10T17:41:08.091Z workers Started run worker instance (delayed) #1\n',
     '2019-10-10T17:41:08.092Z workers Started run worker instance (delayed) #0\n',
     '2019-10-10T17:41:08.122Z workers Started run worker instance (delayed) #3\n',
     '2019-10-10T17:41:08.160Z workers Started run worker instance (delayed) #4\n',
     '2019-10-10T17:41:08.167Z workers Started run worker instance (delayed) #2\n',
     '2019-10-10T17:41:08.175Z workers Started run worker instance (delayed) #5\n',
     '2019-10-10T17:41:09.438Z project Compiler did not set ranges for file [src/App.vue]\n',
     '2019-10-10T17:41:09.459Z project Compiler did not set ranges for file [src/components/HelloWorld.vue]\n',
     '2019-10-10T17:41:10.549Z project Stopping process pool\n',
     '2019-10-10T17:41:10.551Z project Running postprocessor\n',
     '2019-10-10T17:41:10.553Z postprocessor New TypeScript language service is required\n',
     '2019-10-10T17:41:10.554Z postprocessor TypeScript postprocessor will be removed because in 8 project files none were found by patterns: **/*.ts?(x)\n',
     '2019-10-10T17:41:10.554Z project Postprocessor execution finished\n',
     '2019-10-10T17:41:10.554Z project Postprocessor is removed as requested by itself\n',
     '2019-10-10T17:41:10.554Z project Test run started; run priority: 3\n',
     '2019-10-10T17:41:10.554Z project Running all tests\n',
     '2019-10-10T17:41:10.555Z workers Starting test run, priority: 3\n',
     '2019-10-10T17:41:10.555Z nodeRunner Starting sandbox [worker #0, session #rkk7m]\n',
     '2019-10-10T17:41:10.555Z nodeRunner Preparing sandbox [worker #0, session #rkk7m]\n',
     '2019-10-10T17:41:10.556Z nodeRunner Prepared sandbox [worker #0, session #rkk7m]\n',
     '2019-10-10T17:41:10.556Z workers [worker #0, session #rkk7m] Running tests in sandbox\n',
     '2019-10-10T17:41:12.242Z workers Sandbox (active) [rkk7m] error: Jest encountered an unexpected token\n\nThis usually means that you are trying to import a file which Jest cannot parse, e.g. it\'s not plain JavaScript.\n\nBy default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".\n\nHere\'s what you can do:\n • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.\n • If you need a custom transformation specify a "transform" option in your config.\n • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.\n\nYou\'ll find more details and examples of these config options in the docs:\nhttps://jestjs.io/docs/en/configuration.html\n\nDetails:\n\nC:\\dev\\test-app\\node_modules\\@enlearn\\warehouse\\src\\index.js:1\n({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { createInMemoryStorage } from "./in-memory-storage";\n                                                                                         ^^^^^^\n\nSyntaxError: Unexpected token export\n',
     '2019-10-10T17:41:12.246Z workers [rkk7m] Run 0 test(s), skipped 0 test(s)\n',
     '2019-10-10T17:41:12.247Z workers [rkk7m] Sandbox is responsive, closing it\n',
     '2019-10-10T17:41:12.247Z project Test run finished\n',
     '2019-10-10T17:41:12.248Z project Processed console.log entries\n',
     '2019-10-10T17:41:12.248Z project Processed loading sequences\n',
     '2019-10-10T17:41:12.248Z project Processed executed tests\n',
     '2019-10-10T17:41:12.248Z project Processed code coverage\n',
     '2019-10-10T17:41:12.252Z project Test run result processed and sent to IDE\n' ] }
```

**Comment by smcenlly** [comment]
Similar to jest's `transformIgnorePatterns`, Wallaby needs to be told to process the node_module(s) that need to be transformed. The way that you are referencing the package, you need to tell wallaby to include the `@enlearn` ".js" and "package.json" files by updating the `files` section of your `wallaby.conf.js`. I have provided an example below:

```diff
module.exports = (wallaby) => {
...
    return {
      files: [
        'src/**/*', 
        'jest.config.js', 
        'package.json', 
+      'node_modules/@enlearn/**/+(*.js|package.json)'
      ],
...
  }
```
