### ISSUE TITLE
Status Indicator not visible in Visual studio 2019

### ISSUE THREAD

**Issue by spapaseit** [wallabyjs/public#2240]
### Issue description or question

When I use Wallaby with Visual Studio 2019 (v16.3.5), the red/green status indicator on the status bar is not visible/shown.
Wallaby works as expected other than that; tests are run and coverage indicators are displayed correctly.

I have tried removing and reinstalling the extension, but to no avail.

For reference, I have Resharper and NCrunch as main installed extensions (full list of extensions below)

### Wallaby diagnostics report

```
{ editor: 'Visual Studio',
  editorVersion: '16.0',
  pluginVersion: '1.0.49.0',
  editorType: 'Visual Studio',
  osVersion: 'win32 10.0.18362',
  nodeVersion: 'v8.15.1',
  coreVersion: '1.0.767',
  config: 
   { files: [ [Object], [Object], [Object], [Object], [Object] ],
     tests: [ [Object] ],
     env: 
      { type: 'node',
        params: {},
        runner: 'c:\\Program Files\\nodejs\\node.exe',
        viewportSize: [Object],
        options: [Object],
        bundle: true },
     preprocessors: 
      { '**/*.js?(x)': [Function: **/*.js?(x)],
        'package.json': [Function] },
     testFramework: 
      { version: 'jest@0.4.3',
        configurator: 'jest@0.4.3',
        reporter: 'jest@0.4.3',
        starter: 'jest@0.4.3' },
     debug: true,
     diagnostics: {},
     filesWithNoCoverageCalculated: [],
     runAllTestsInAffectedTestFile: false,
     compilers: { '**/*.?(lit)coffee?(.md)': [Function] },
     maxConsoleMessagesPerTest: 100,
     autoConsoleLog: true,
     delays: { run: 0, edit: 100, update: 0 },
     workers: { initial: 0, regular: 0, recycle: false },
     teardown: undefined,
     hints: 
      { ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
        ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
        commentAutoLog: '?',
        testFileSelection: [Object] },
     automaticTestFileSelection: true,
     runSelectedTestsOnly: false,
     extensions: {},
     reportUnhandledPromises: true,
     slowTestThreshold: 75,
     lowCoverageThreshold: 80,
     loose: true,
     configCode: '﻿module.exports = wallaby => {\r\n    process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true;\r\n\r\n    return {\r\n        files: ["src/**/*", "jest.config.js", "package.json", "tsconfig.json"],\r\n\r\n        tests: ["tests/**/*.spec.ts"],\r\n\r\n        env: {\r\n            type: "node"\r\n        },\r\n\r\n        preprocessors: {\r\n            "**/*.js?(x)": file => require("@babel/core").transform(\r\n                file.content,\r\n                {sourceMap: true, compact: false, filename: file.path, plugins: ["babel-plugin-jest-hoist"]})\r\n        },\r\n\r\n        setup(wallaby) {\r\n            const jestConfig = require("./package").jest || require("./jest.config")\r\n            delete jestConfig.transform["^.+\\\\.tsx?$"]\r\n            wallaby.testFramework.configure(jestConfig)\r\n        },\r\n\r\n        testFramework: "jest",\r\n\r\n        debug: true\r\n    }\r\n}' },
  packageJSON: 
   { dependencies: 
      { '@fortawesome/fontawesome-svg-core': '^1.2.20',
        '@fortawesome/free-solid-svg-icons': '^5.10.0',
        '@fortawesome/vue-fontawesome': '^0.1.6',
        audit: '0.0.6',
        axios: '^0.19.0',
        bootstrap: '^4.3.1',
        'bootstrap-vue': '^2.0.0-rc.28',
        'core-js': '^2.6.5',
        fix: '0.0.6',
        jquery: '^3.4.1',
        'jwt-decode': '^2.2.0',
        moment: '^2.24.0',
        nprogress: '^0.2.0',
        numeral: '^2.0.6',
        'popper.js': '^1.15.0',
        'reflect-metadata': '^0.1.13',
        vue: '^2.6.10',
        'vue-class-component': '^7.0.2',
        'vue-form-wizard': '^0.8.4',
        'vue-property-decorator': '^8.1.0',
        'vue-router': '^3.0.3',
        'vue-signature-pad': '^1.1.14',
        vuex: '^3.0.1' },
     devDependencies: 
      { '@types/jest': '^24.0.17',
        '@types/jquery': '^3.3.30',
        '@types/jwt-decode': '^2.2.1',
        '@types/nprogress': '^0.2.0',
        '@types/numeral': '0.0.25',
        '@types/reflect-metadata': '^0.1.0',
        '@vue/cli-plugin-babel': '^3.9.0',
        '@vue/cli-plugin-typescript': '^3.9.0',
        '@vue/cli-plugin-unit-jest': '^3.10.0',
        '@vue/cli-service': '^3.9.0',
        '@vue/test-utils': '1.0.0-beta.29',
        'aspnet-webpack': '^3.0.0',
        'babel-core': '7.0.0-bridge.0',
        'node-sass': '^4.9.0',
        'sass-loader': '^7.1.0',
        'ts-jest': '^24.0.2',
        typescript: '^3.6.4',
        'vue-template-compiler': '^2.6.10',
        'vuex-module-decorators': '^0.9.9',
        'wallaby-vue-compiler': '^1.0.6',
        'webpack-hot-middleware': '^2.25.0' } },
  fs: { numberOfFiles: 59 },
  debug: 
   [ '2019-10-17T07:20:28.287Z project Wallaby Node version: v8.15.1\n',
     '2019-10-17T07:20:28.288Z project Wallaby config: C:\\Software Development\\Projects\\Gigantisch\\digital-delivery-form\\DigitalDeliveryForm.Web\\wallaby.js\n',
     '2019-10-17T07:20:28.916Z project File cache: C:\\Users\\sergi\\AppData\\Local\\Temp\\.wallaby\\projects\\eOialCu+JYkc8us2ruKWQIpWXCU=\\cache\n',
     '2019-10-17T07:20:28.982Z uiService Listening port 51235\n',
     '2019-10-17T07:20:29.008Z project package.json file change detected, invalidating local cache\n',
     '2019-10-17T07:20:29.024Z workers Parallelism for initial run: 2, for regular run: 2\n',
     '2019-10-17T07:20:29.024Z workers Starting run worker instance #0\n',
     '2019-10-17T07:20:29.024Z workers Starting run worker instance #1\n',
     '2019-10-17T07:20:29.024Z workers Web server is listening at 56378\n',
     '2019-10-17T07:20:29.024Z project File cache requires some updates, waiting required files from IDE\n',
     '2019-10-17T07:20:29.071Z extended-core New document or complex document change\n',
     '2019-10-17T07:20:30.048Z workers Started run worker instance (delayed) #0\n',
     '2019-10-17T07:20:30.064Z workers Started run worker instance (delayed) #1\n',
     '2019-10-17T07:20:31.637Z project Stopping process pool\n',
     '2019-10-17T07:20:31.637Z project Running postprocessor\n',
     '2019-10-17T07:20:31.652Z postprocessor New TypeScript language service is required\n',
     '2019-10-17T07:20:34.393Z project Postprocessor execution finished\n',
     '2019-10-17T07:20:34.393Z project Test run started; run priority: 3\n',
     '2019-10-17T07:20:34.394Z project Running all tests\n',
     '2019-10-17T07:20:34.398Z workers Starting test run, priority: 3\n',
     '2019-10-17T07:20:34.399Z workers Distributing tests between 2 workers\n',
     '2019-10-17T07:20:34.399Z workers Running tests in parallel\n',
     '2019-10-17T07:20:34.400Z nodeRunner Starting sandbox [worker #0, session #o2vn0]\n',
     '2019-10-17T07:20:34.400Z nodeRunner Starting sandbox [worker #1, session #26zmc]\n',
     '2019-10-17T07:20:34.400Z nodeRunner Preparing sandbox [worker #0, session #o2vn0]\n',
     '2019-10-17T07:20:34.400Z nodeRunner Preparing sandbox [worker #1, session #26zmc]\n',
     '2019-10-17T07:20:34.400Z nodeRunner Prepared sandbox [worker #0, session #o2vn0]\n',
     '2019-10-17T07:20:34.401Z nodeRunner Prepared sandbox [worker #1, session #26zmc]\n',
     '2019-10-17T07:20:34.401Z workers [worker #0, session #o2vn0] Running tests in sandbox\n',
     '2019-10-17T07:20:34.403Z workers [worker #1, session #26zmc] Running tests in sandbox\n',
     '2019-10-17T07:20:37.860Z workers Sandbox (active) [26zmc] error: Error: Your test suite must contain at least one test.\n',
     '2019-10-17T07:20:37.862Z workers Failed to map the stack to user code, entry message: Error: Your test suite must contain at least one test., stack: Error: Your test suite must contain at least one test.\n    at C:\\Software Development\\Projects\\Gigantisch\\digital-delivery-form\\DigitalDeliveryForm.Web\\node_modules\\jest\\node_modules\\jest-cli\\build\\TestScheduler.js:256:22\n    at Generator.next (<anonymous>)\n    at step (C:\\Software Development\\Projects\\Gigantisch\\digital-delivery-form\\DigitalDeliveryForm.Web\\node_modules\\jest\\node_modules\\jest-cli\\build\\TestScheduler.js:147:30)\n    at C:\\Software Development\\Projects\\Gigantisch\\digital-delivery-form\\DigitalDeliveryForm.Web\\node_modules\\jest\\node_modules\\jest-cli\\build\\TestScheduler.js:166:14\n    at new Promise (<anonymous>)\n    at C:\\Software Development\\Projects\\Gigantisch\\digital-delivery-form\\DigitalDeliveryForm.Web\\node_modules\\jest\\node_modules\\jest-cli\\build\\TestScheduler.js:144:12\n    at onResult (C:\\Software Development\\Projects\\Gigantisch\\digital-delivery-form\\DigitalDeliveryForm.Web\\node_modules\\jest\\node_modules\\jest-cli\\build\\TestScheduler.js:291:23)\n    at C:\\Software Development\\Projects\\Giganti\n',
     '2019-10-17T07:20:37.926Z workers [26zmc] Loaded unknown number of test(s)\n',
     '2019-10-17T07:20:37.933Z workers [26zmc] Run 0 test(s), skipped 0 test(s)\n',
     '2019-10-17T07:20:37.934Z workers [26zmc] Sandbox is responsive, closing it\n',
     '2019-10-17T07:20:38.038Z workers Sandbox (active) [o2vn0] error: Error: Configuration error:\n\nCould not locate module @/components/OrderDetails.vue mapped as:\nC:\\Users\\sergi\\AppData\\Local\\Temp\\.wallaby\\projects\\eOialCu+JYkc8us2ruKWQIpWXCU=\\cache\\instrumented/src/components/OrderDetails.vue.\n\nPlease check your configuration for these entries:\n{\n  "moduleNameMapper": {\n    "/^@\\/(.*)$/": "C:\\Users\\sergi\\AppData\\Local\\Temp\\.wallaby\\projects\\eOialCu+JYkc8us2ruKWQIpWXCU=\\cache\\instrumented/src/$1"\n  },\n  "resolver": null\n}\n',
     '2019-10-17T07:20:38.140Z workers [o2vn0] Run 0 test(s), skipped 0 test(s)\n',
     '2019-10-17T07:20:38.167Z workers [o2vn0] Sandbox is responsive, closing it\n',
     '2019-10-17T07:20:38.168Z workers Merging parallel test run results\n',
     '2019-10-17T07:20:38.168Z project Test run finished\n',
     '2019-10-17T07:20:38.169Z project Processed console.log entries\n',
     '2019-10-17T07:20:38.169Z project Processed loading sequences\n',
     '2019-10-17T07:20:38.169Z project Processed executed tests\n',
     '2019-10-17T07:20:38.171Z project Processed code coverage\n',
     '2019-10-17T07:20:38.183Z project Test run result processed and sent to IDE\n' ] }
```

### Visual Studio 2019 Installed Extensions

 - Add New File   3.5.134  
 - ADL Tools Service Provider   1.0  
 - ASP.NET and Web Tools 2019   16.3.285.24939  
 - ASP.NET Web Frameworks and Tools 2019   16.3.285.24939
 - Azure App Service Tools v3.0.0   16.3.285.24939   
 - Azure Data Lake Node   1.0
 - Azure Data Lake Tools for Visual Studio   2.4.2000.0   
 - Azure Functions and Web Jobs Tools   16.3.285.24939
 - Azure Stream Analytics Tools for Visual Studio   2.4.2000.0
 - Bundler & Minifier   2.8.396
 - C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
 - Common Azure Tools   1.10
 - CSS Tools 2019   1.1.2
 - EditorConfig Language Service   1.17.260
 - EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs.
 - Fabric.DiagnosticEvents   1.0
 - File Icons   2.7
 - File Nesting   2.6.85
 - Image Optimizer   4.0.132
 - Image Sprites   1.4.58
 - IntelliCode Extension   1.0
 - JetBrains ReSharper Ultimate 2019.2.2   Build 192.0.20190828.114715
 - Markdown Editor   1.12.236
 - Microsoft Azure HDInsight Azure Node   2.4.2000.0
 - Microsoft Azure Hive Query Language Service   2.4.2000.0
 - Microsoft Azure Service Fabric Tools for Visual Studio   16.0
 - Microsoft Azure Stream Analytics Language Service   2.4.2000.0
 - Microsoft Azure Stream Analytics Node   1.0
 - Microsoft Azure Tools   2.9
 - Microsoft Continuous Delivery Tools for Visual Studio   0.4
 - Microsoft JVM Debugger   1.0
 - Microsoft Library Manager   2.0.83+gbc8a4b23ec
 - Microsoft MI-Based Debugger   1.0
 - Microsoft Visual Studio Tools for Containers   1.1
 - NCrunch
 - NuGet Package Manager   5.3.0
 - Open Command Line   2.4.226
 - Package Installer   2.0.103
 - Package Security Alerts   1.0.22
 - ProjectServicesPackage Extension   1.0
 - SQL Server Data Tools   16.0.61908.27190
 - Microsoft SQL Server Data Tools
 - SVG Viewer   1.0.8
 - ToolWindowHostedEditor   1.0
 - TypeScript Tools   16.0.10821.2002
 - Viasfora   4.2.188
 - Visual Basic Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
 - Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
 - Microsoft Visual F# Tools 10.4 for F# 4.6
 - Visual Studio Code Debug Adapter Host Package   1.0
 - Visual Studio Tools for Containers   1.0
 - Visual Studio Tools for Kubernetes   1.0
 - Web Accessibility Checker   1.5.58
 - Web Compiler   1.12.394
 - Web Essentials 2019   0.5.7
 - ZenCoding   1.2.12

**Comment by smcenlly** [comment]
Thanks for reporting the problem and for the detail in your issue. We've fixed the problem, available in the latest extension for Visual Studio 2019 (v1.0.50). Please update your extension to get the fix.

**Comment by spapaseit** [comment]
Thanks for the quick action on this, you guys are awesome.
