### ISSUE TITLE
Wallaby with cypress

### ISSUE THREAD

**Issue by felikf** [wallabyjs/public#2245]
### Issue description or question
I have a project Angular8 with jest + wallaby + Webstorm.  Wallaby works with automatic configuration perfectly OK.

I have added cypress which generated `<my-project>/cypress` directory. Now when I start wallaby I get an error:

```
wallaby.js started
core v1.0.769
Wallaby App (realtime reports) is available at: http://localhost:51245
Runtime error: ReferenceError: context is not defined
    at Object.<anonymous> (.\cypress\integration\examples\actions.spec.js:2:1)
    at Runtime._execModule (.\node_modules\@jest\core\node_modules\jest-runtime\build\index.js:888:13)
    at Runtime._loadModule (.\node_modules\@jest\core\node_modules\jest-runtime\build\index.js:577:12)
    at Runtime.requireModule (.\node_modules\@jest\core\node_modules\jest-runtime\build\index.js:433:10)
```

The automatic configuration loads the cypress files - I would like to ignore them.

I have tried to follow https://wallabyjs.com/docs/intro/config.html#overriding-automatic-defaults

to exclude cypress:

```
module.exports = () => ({
  autoDetect: true,
  files: [
    './src/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
    'jest.setup.ts',
    '!src/**/*.spec.ts',
    '!cypress/**/*.js',
  ],
});
```

but without success - still same error. How can I easily tell wallaby to ignore the cypress files?

(Running `jest` to run jest and test works OK - all tests are passing.)

![image](https://user-images.githubusercontent.com/13978154/67281715-58b2d280-f4d0-11e9-92fc-4761eab42083.png)

### Wallaby diagnostics report

```
{
  editorVersion: 'WebStorm 2019.3 EAP',
  pluginVersion: '1.0.143',
  editorType: 'IntelliJ',
  osVersion: 'win32 10.0.18362',
  nodeVersion: 'v12.11.1',
  coreVersion: '1.0.769',
  config: {
    files: [
      { pattern: 'src/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'jest.setup.ts', ignore: false, trigger: true, load: true, order: 2 },
      { pattern: 'src/**/*.spec.ts', ignore: true, trigger: true, load: true },
      { pattern: 'cypress/**/*.js', ignore: true, trigger: true, load: true },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true }
    ],
    diagnostics: {},
    filesWithCoverageCalculated: [],
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    micromatch: true,
    tests: [
      { pattern: '\\\\node_modules\\\\', regexp: /\\node_modules\\/, ignore: true, trigger: true, load: true, test: true },
      {
        pattern: 'dist\\\\|build\\\\|coverage\\\\|\\\\\\.idea\\\\|\\\\\\.vscode\\\\|\\\\\\.git\\\\|\\\\\\.gitlab\\\\',
        regexp: /dist\\|build\\|coverage\\|\\\.idea\\|\\\.vscode\\|\\\.git\\|\\\.gitlab\\/,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 4 }
    ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: 'F:\\app\\nodejs\\node.exe', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: '// module.exports = function () {\r\n' +
      '//\r\n' +
      "//   const jestTransform = file => require('jest-preset-angular/preprocessor').process(file.content, file.path, {globals: {__TRANSFORM_HTML__: true}, rootDir: __dirname});\r\n" +
      '//\r\n' +
      '//   return {\r\n' +
      '//     files: [\r\n' +
      "//       './src/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',\r\n" +
      "//       'jest.setup.ts',\r\n" +
      "//       '!src/**/*.spec.ts'\r\n" +
      '//     ],\r\n' +
      '//\r\n' +
      "//     tests: ['./src/**/*.spec.ts'],\r\n" +
      '//\r\n' +
      '//     env: {\r\n' +
      "//       type: 'node',\r\n" +
      "//       runner: 'node'\r\n" +
      '//     },\r\n' +
      '//\r\n' +
      '//     compilers: {\r\n' +
      "//       '**/*.html': file => ({code: jestTransform(file), map: {version: 3, sources: [], names: [], mappings: []}, ranges: []})\r\n" +
      '//     },\r\n' +
      '//\r\n' +
      '//     preprocessors: {\r\n' +
      "//       './src/**/*.js': [\r\n" +
      '//         jestTransform,\r\n' +
      "//         (file) => require('babel-core').transform(file.content, { sourceMap: true, filename: file.path, presets: ['babel-preset-jest'] })\r\n" +
      '//       ]\r\n' +
      '//     },\r\n' +
      '//\r\n' +
      "//     testFramework: 'jest'\r\n" +
      '//   };\r\n' +
      '// };\r\n' +
      '\r\n' +
      '\r\n' +
      'module.exports = () => ({\r\n' +
      '  autoDetect: true,\r\n' +
      '  files: [\r\n' +
      "    './src/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',\r\n" +
      "    'jest.setup.ts',\r\n" +
      "    '!src/**/*.spec.ts',\r\n" +
      "    '!cypress/**/*.js',\r\n" +
      '  ],\r\n' +
      '});\r\n'
  },
  packageJSON: {
    dependencies: {
      '@angular/animations': '8.2.6',
      '@angular/cdk': '8.2.0',
      '@angular/common': '8.2.6',
      '@angular/compiler': '8.2.6',
      '@angular/core': '8.2.6',
      '@angular/flex-layout': '8.0.0-beta.27',
      '@angular/forms': '8.2.6',
      '@angular/material': '8.2.0',
      '@angular/material-moment-adapter': '8.2.0',
      '@angular/platform-browser': '8.2.6',
      '@angular/platform-browser-dynamic': '8.2.6',
      '@angular/router': '8.2.6',
      '@ngrx/effects': '8.3.0',
      '@ngrx/router-store': '8.3.0',
      '@ngrx/store': '8.3.0',
      '@ngrx/store-devtools': '8.3.0',
      '@ngx-translate/core': '11.0.1',
      '@ngx-translate/http-loader': '4.0.0',
      'core-js': '3.2.1',
      'error-stack-parser': '2.0.3',
      hammerjs: '2.0.8',
      lodash: '4.17.15',
      moment: '2.24.0',
      'ngx-take-until-destroy': '5.4.0',
      rxjs: '6.5.3',
      tslib: '^1.10.0',
      'ts-md5': '1.2.4',
      'web-animations-js': '2.3.2',
      'zone.js': '~0.9.1'
    },
    devDependencies: {
      '@angular-builders/jest': '8.2.0',
      '@angular-devkit/build-angular': '0.803.6',
      '@angular/cli': '8.3.4',
      '@angular/compiler-cli': '8.2.6',
      '@angular/language-service': '8.2.6',
      '@ngrx/schematics': '8.3.0',
      '@types/jest': '23.3.14',
      '@types/lodash': '4.14.125',
      '@types/node': '8.10.36',
      'browser-sync': '2.26.7',
      codelyzer: '5.1.2',
      cypress: '^3.4.1',
      'istanbul-reports': '2.2.5',
      'jasmine-marbles': '0.4.1',
      jest: '24.8.0',
      'jest-cli': '24.1.0',
      'jest-preset-angular': '7.1.1',
      'jest-sonar-reporter': '2.0.0',
      'jest-teamcity-reporter': '0.9.0',
      'json-loader': '0.5.7',
      'ngx-wallaby-jest': '0.0.2',
      prettier: '1.18.2',
      protractor: '5.4.1',
      'rxjs-tslint-rules': '4.25.0',
      'ts-node': '7.0.1',
      tslint: '5.16.0',
      'tslint-eslint-rules': '5.4.0',
      'tslint-microsoft-contrib': '6.1.1',
      'tslint-teamcity-reporter': '3.2.2',
      typescript: '3.5.3',
      'wallaby-webpack': '3.9.15'
    }
  },
  fs: { numberOfFiles: 1840 },
  debug: [
    '2019-10-22T11:01:16.122Z config Detected Jest.\n',
    '2019-10-22T11:01:16.124Z config Configured Jest.\n',
    '2019-10-22T11:01:16.141Z project Wallaby Node version: v12.11.1\n',
    '2019-10-22T11:01:16.141Z project Wallaby config: F:\\work\\cps\\dashboardsfe\\wallaby.js\n',
    '2019-10-22T11:01:35.739Z fs File system scan has finished by timeout\n',
    '2019-10-22T11:01:35.786Z project File cache: C:\\Users\\Felix Fatka\\.WebStorm2019.3\\system\\wallaby\\projects\\6a613323597e1d23\n',
    '2019-10-22T11:01:35.933Z uiService Listening port 51235\n',
    '2019-10-22T11:01:38.165Z project Config file change detected, invalidating local cache\n',
    '2019-10-22T11:01:42.597Z uiService UI client connected\n',
    '2019-10-22T11:01:42.598Z uiService Outgoing message ui:handshake\n',
    '2019-10-22T11:01:42.685Z uiService Outgoing message ui:busy\n',
    '2019-10-22T11:01:42.686Z uiService UI client disconnected\n',
    '2019-10-22T11:01:45.440Z workers Parallelism for initial run: 2, for regular run: 2\n',
    '2019-10-22T11:01:45.441Z workers Starting run worker instance #0\n',
    '2019-10-22T11:01:45.441Z workers Starting run worker instance #1\n',
    '2019-10-22T11:01:45.444Z workers Web server is listening at 27981\n',
    '2019-10-22T11:01:45.444Z project File cache requires some updates, waiting required files from IDE\n',
    '2019-10-22T11:01:47.043Z workers Started run worker instance (delayed) #0\n',
    '2019-10-22T11:01:47.044Z workers Started run worker instance (delayed) #1\n',
    '2019-10-22T11:01:48.743Z project Stopping process pool\n',
    '2019-10-22T11:01:48.749Z project Test run started; run priority: 3\n',
    '2019-10-22T11:01:48.750Z project Running all tests\n',
    '2019-10-22T11:01:48.809Z workers Starting test run, priority: 3\n',
    '2019-10-22T11:01:48.809Z workers Distributing tests between 2 workers\n',
    '2019-10-22T11:01:48.816Z workers Running tests in parallel\n',
    '2019-10-22T11:01:48.817Z nodeRunner Starting sandbox [worker #0, session #nvsd4]\n',
    '2019-10-22T11:01:48.817Z nodeRunner Starting sandbox [worker #1, session #54ip9]\n',
    '2019-10-22T11:01:48.817Z nodeRunner Preparing sandbox [worker #0, session #nvsd4]\n',
    '2019-10-22T11:01:48.817Z nodeRunner Preparing sandbox [worker #1, session #54ip9]\n',
    '2019-10-22T11:01:48.817Z nodeRunner Prepared sandbox [worker #0, session #nvsd4]\n',
    '2019-10-22T11:01:48.817Z nodeRunner Prepared sandbox [worker #1, session #54ip9]\n',
    '2019-10-22T11:01:48.818Z workers [worker #0, session #nvsd4] Running tests in sandbox\n',
    '2019-10-22T11:01:48.826Z workers [worker #1, session #54ip9] Running tests in sandbox\n',
    '2019-10-22T11:01:50.689Z uiService UI client connected\n',
    '2019-10-22T11:01:50.689Z uiService Outgoing message ui:handshake\n',
    '2019-10-22T11:01:50.697Z uiService Incoming message ui:start\n',
    '2019-10-22T11:01:50.698Z uiService Outgoing message ui:summary\n',
    '2019-10-22T11:01:50.722Z uiService Outgoing message ui:files\n',
    '2019-10-22T11:01:50.897Z uiService Incoming message ui:closedInEditor\n',
    '2019-10-22T11:01:56.474Z workers Sandbox (active) [nvsd4] error: ReferenceError: context is not defined\n',
    '2019-10-22T11:01:56.575Z workers [nvsd4] Run 0 test(s), skipped 0 test(s)\n',
    '2019-10-22T11:01:56.586Z workers Sandbox (active) [54ip9] error: ReferenceError: context is not defined\n',
    '2019-10-22T11:01:56.687Z workers [54ip9] Run 0 test(s), skipped 0 test(s)\n',
    '2019-10-22T11:01:56.852Z workers Sandbox (inactive) [nvsd4] error: ReferenceError: context is not defined\n',
    '2019-10-22T11:01:57.010Z workers Sandbox (inactive) [54ip9] error: ReferenceError: context is not defined\n',
    '2019-10-22T11:01:57.294Z workers Sandbox (inactive) [nvsd4] error: ReferenceError: context is not defined\n',
    '2019-10-22T11:01:57.472Z workers Sandbox (inactive) [54ip9] error: ReferenceError: context is not defined\n',
    '2019-10-22T11:01:57.576Z workers [nvsd4] Sandbox is not responsive, recycling worker instance\n',
    '2019-10-22T11:01:57.688Z workers [54ip9] Sandbox is not responsive, recycling worker instance\n',
    '2019-10-22T11:01:57.689Z workers Merging parallel test run results\n',
    '2019-10-22T11:01:57.690Z project Test run finished\n',
    '2019-10-22T11:01:57.690Z project Processed console.log entries\n',
    '2019-10-22T11:01:57.690Z project Processed loading sequences\n',
    '2019-10-22T11:01:57.690Z project Processed executed tests\n',
    '2019-10-22T11:01:57.698Z project Processed code coverage\n',
    '2019-10-22T11:01:57.706Z project Test run result processed and sent to IDE\n',
    '2019-10-22T11:01:57.706Z uiService Outgoing message ui:summary\n'
  ]
}
```

And jest config:

```
  "jest": {
    "preset": "jest-preset-angular",
    "globals": {
      "ts-jest": {
        "tsConfig": "<rootDir>/src/tsconfig.spec.json",
        "stringifyContentPathRegex": "\\.html$",
        "astTransformers": [
          "jest-preset-angular/InlineHtmlStripStylesTransformer"
        ],
        "diagnostics": {
          "warnOnly": true
        }
      }
    },
    "moduleNameMapper": {
      "environments/(.*)": "<rootDir>/src/environments/$1"
    },
    "setupFilesAfterEnv": [
      "<rootDir>/src/setupJest.ts"
    ],
    "testResultsProcessor": "jest-teamcity-reporter",
    "transformIgnorePatterns": [
      "node_modules/(?!@ngrx|angular2-ui-switch|ng-dynamic)"
    ]
  }

```

**Comment by smcenlly** [comment]
> (Running jest to run jest and test works OK - all tests are passing.)

Is this running `npx jest` from the command line, or are you are using a WebStorm Jest Run Configuration?

--

We set up a similar project with Cypress.io tests and using `npx jest`, and both the `src` and `cypress` tests were run (with an error on the Cypress tests).

The best way to fix this problem is to update your Jest configuration so that the `cypress` folder is added to `testPathIgnorePatterns` (see below).

```diff
"jest": {
  "preset": "jest-preset-angular",
  "globals": {
    "ts-jest": {
      "tsConfig": "<rootDir>/src/tsconfig.json",
      "stringifyContentPathRegex": "\\.html$",
      "astTransformers": [
        "jest-preset-angular/InlineHtmlStripStylesTransformer"
      ],
      "diagnostics": {
        "warnOnly": true
      }
    }
  },
  "moduleNameMapper": {
    "environments/(.*)": "<rootDir>/src/environments/$1"
  },
  "setupFilesAfterEnv": [
    "<rootDir>/src/setupJest.ts"
  ],
  "testResultsProcessor": "jest-teamcity-reporter",
  "transformIgnorePatterns": [
    "node_modules/(?!@ngrx|angular2-ui-switch|ng-dynamic)"
  ],
+ "testPathIgnorePatterns": [
+   "<rootDir>/cypress/"
+ ]
}
```

**Comment by felikf** [comment]
Thanks that worked. I have lost some time trying same with `modulePathIgnorePatterns`.
Why is this needed? I see there is this setting: 

```
 { pattern: 'cypress/**/*.js', ignore: true, trigger: true, load: true },
```

in the automatic config for wallaby.

**Comment by smcenlly** [comment]
> Why is this needed?

I'm not sure why `./node_modules/.bin/jest` worked for you but Wallaby did not. Using Wallaby, you should get the same behavior as using jest from the command line. If you can provide us with a sample, we'd really appreciate it so we can diagnose why it didn't work.
