### ISSUE TITLE
Wallaby throws error with Vue CLI 4, typescript + babel + jest

### ISSUE THREAD

**Issue by chessydk** [wallabyjs/public#2246]
### Issue description or question

With a brand new scaffolded Vue Cli 4 project, Wallaby fails to run the default included test (example.spec.test) as soon as I start Wallaby.

Wallaby throws this error:

```
wallaby.js started
core v1.0.769
Runtime error: TypeError: Cannot convert undefined or null to object
    at WebSocket.emit (events.js:198:13)
    at afterWrite (_stream_writable.js:485:3)
    at onwrite (_stream_writable.js:476:7)
    at InflateRaw.afterTransform (_stream_transform.js:94:3)
    at Zlib.processCallback (zlib.js:548:8)
```

### Using
Webstorm 2019.2.3
@Vue/cli 4.0.5
Vue-cli options: Typescript and babel for auto polyfilling. Jest for unittest.

### Wallaby diagnostics report

Using webstorm. The `Help | Wallaby.js | Copy Diagnostics Report` is grayed out, so can't provide that.

### Project included

I have included the whole project as a zip file so you can see my wallaby.js and package.json. All you need to reproduce is running npm install.
[wallaby-fails-ts-jest.zip](https://github.com/wallabyjs/public/files/3761947/wallaby-fails-ts-jest.zip)

**Comment by smcenlly** [comment]
Thanks for the sample repo. Vue 4.x with Jest no longer requires a configuration file. You may delete your Wallaby.js file and update your WebStorm run configuration from `Configuration File` to `Automatic`. You may read more about automatic configuration in [our docs](https://wallabyjs.com/docs/intro/config.html#jetbrains-ides).

**Comment by chessydk** [comment]
Hi Simon, thx for feedback, but if I remove wallaby.js and start wallaby I get another error:

```
0 failing tests, 0 passing  Launch Coverage/Test Explorer

Error: Cannot find module 'core-js/modules/es.symbol.description' from 'jasmineInitializer.js'
```

Maybe because vue-cli 4 uses core-js v. 3 ?

**Comment by smcenlly** [comment]
I'll reopen the issue. We tested yesterday with the latest version of Vue CLI and everything was working with the default template using jest for unit tests. We also tested `wallaby-fails-ts-jest.zip` and worked fine. 

Today we have tested `wallaby-fails-ts-jest.zip` on another machine and it's also working. Could you please try downloading the `wallaby-fails-ts-jest.zip` to a fresh directory, running `npm install` and confirm whether that's working for you? 

On your existing project(s), can you also please try deleting your `package.lock.json` or `yarn.lock`, `node_modules` and reinstalling all of your packages?

If that doesn't fix your problem, can you please provide us with your Wallaby Diagnostics report? To share the report:

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- run `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

**Comment by chessydk** [comment]
Thats very weird - unzipped in fresh directory and npm installed. Same error. Tried on a colleques machine and it works there. His and mine package-lock.json's are equal (to rule out npm version problem). I have the latest node v. 12.13.0. 

## Error from "Wallaby console"
```
wallaby.js started
core v1.0.771
Runtime error: Error: Cannot find module 'core-js/modules/es.symbol.description' from 'jasmineInitializer.js'
    at Resolver.resolveModule (.\node_modules\jest-resolve\build\index.js:259:17)
    at Resolver._getVirtualMockPath (.\node_modules\jest-resolve\build\index.js:390:14)
    at Resolver._getAbsolutePath (.\node_modules\jest-resolve\build\index.js:376:14)
    at Resolver.getModuleID (.\node_modules\jest-resolve\build\index.js:348:31)
    at Runtime._shouldMock (.\node_modules\jest-runtime\build\index.js:942:37)
    at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:595:16)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:867:68)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:577:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:433:10)
    at .\node_modules\jest-jasmine2\build\index.js:187:55
    at Array.forEach (<anonymous>)
    at .\node_modules\jest-jasmine2\build\index.js:187:31
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (.\node_modules\jest-jasmine2\build\index.js:27:24)
    at _next (.\node_modules\jest-jasmine2\build\index.js:47:9)
    at .\node_modules\jest-jasmine2\build\index.js:52:7
    at new Promise (<anonymous>)
    at .\node_modules\jest-jasmine2\build\index.js:44:12
    at _jasmine (.\node_modules\jest-jasmine2\build\index.js:207:19)
    at jasmine2 (.\node_modules\jest-jasmine2\build\index.js:60:19)
    at .\node_modules\jest-runner\build\runTest.js:385:24
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (.\node_modules\jest-runner\build\runTest.js:161:24)
    at _next (.\node_modules\jest-runner\build\runTest.js:181:9)
console.log: Jest: FAIL tests/unit/example.spec.ts

console.log: Jest:   ● Test suite failed to run

    Cannot find module 'core-js/modules/es.symbol.description' from 'jasmineInitializer.js'
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (../../../../Users/che/.WebStorm2019.2/system/wallaby/wallaby/runners/node/jest@24.8.0/jasmineInitializer.js:3:1)
          at Array.forEach (<anonymous>)
```

## Wallaby diagnostics report:
```
{
  editorVersion: 'WebStorm 2019.2.3',
  pluginVersion: '1.0.143',
  editorType: 'IntelliJ',
  osVersion: 'win32 10.0.17134',
  nodeVersion: 'v12.13.0',
  coreVersion: '1.0.771',
  config: {
    diagnostics: {},
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    micromatch: true,
    files: [
      { pattern: '\\\\node_modules\\\\', regexp: /\\node_modules\\/, ignore: true, trigger: true, load: true },
      {
        pattern: 'dist\\\\|build\\\\|coverage\\\\|\\\\\\.idea\\\\|\\\\\\.vscode\\\\|\\\\\\.git\\\\|\\\\\\.gitlab\\\\',
        regexp: /dist\\|build\\|coverage\\|\\\.idea\\|\\\.vscode\\|\\\.git\\|\\\.gitlab\\/,
        ignore: true,
        trigger: true,
        load: true
      },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '**/tests/unit/**/*.spec.[jt]s?(x)', ignore: true, trigger: true, load: true },
      { pattern: '**/__tests__/*.[jt]s?(x)', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '\\\\node_modules\\\\', regexp: /\\node_modules\\/, ignore: true, trigger: true, load: true, test: true },
      {
        pattern: 'dist\\\\|build\\\\|coverage\\\\|\\\\\\.idea\\\\|\\\\\\.vscode\\\\|\\\\\\.git\\\\|\\\\\\.gitlab\\\\',
        regexp: /dist\\|build\\|coverage\\|\\\.idea\\|\\\.vscode\\|\\\.git\\|\\\.gitlab\\/,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      { pattern: '**/tests/unit/**/*.spec.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: '**/__tests__/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 }
    ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: 'C:\\Program Files\\nodejs\\node.exe', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#302369812'
  },
  packageJSON: {
    dependencies: { 'core-js': '^3.3.2', vue: '^2.6.10', 'vue-class-component': '^7.0.2', 'vue-property-decorator': '^8.3.0' },
    devDependencies: {
      '@types/jest': '^24.0.11',
      '@vue/cli-plugin-babel': '^4.0.0',
      '@vue/cli-plugin-typescript': '^4.0.0',
      '@vue/cli-plugin-unit-jest': '^4.0.0',
      '@vue/cli-service': '^4.0.0',
      '@vue/test-utils': '1.0.0-beta.29',
      typescript: '~3.5.3',
      'vue-template-compiler': '^2.6.10',
      'wallaby-vue-compiler': '^1.0.6'
    }
  },
  fs: { numberOfFiles: 18 },
  debug: [
    '2019-10-25T11:28:52.391Z config Detected Jest.\n',
    '2019-10-25T11:28:52.393Z config Configured Jest.\n',
    '2019-10-25T11:28:52.399Z project Wallaby Node version: v12.13.0\n',
    '2019-10-25T11:28:52.399Z project Wallaby config: C:\\projects\\Private\\vue-cli4\\wallaby-works\\auto.detect\n',
    '2019-10-25T11:28:53.949Z project File cache: C:\\Users\\che\\.WebStorm2019.2\\system\\wallaby\\projects\\e4ccb62f90891e0c\n',
    '2019-10-25T11:28:54.124Z uiService Listening port 51235\n',
    '2019-10-25T11:28:54.201Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2019-10-25T11:28:54.201Z workers Starting run worker instance #0\n',
    '2019-10-25T11:28:54.202Z workers Starting run worker instance #1\n',
    '2019-10-25T11:28:54.202Z workers Starting run worker instance #2\n',
    '2019-10-25T11:28:54.202Z workers Starting run worker instance #3\n',
    '2019-10-25T11:28:54.202Z workers Starting run worker instance #4\n',
    '2019-10-25T11:28:54.202Z workers Starting run worker instance #5\n',
    '2019-10-25T11:28:54.205Z workers Web server is listening at 50513\n',
    '2019-10-25T11:28:54.342Z project Stopping process pool\n',
    '2019-10-25T11:28:54.342Z project File cache is up-to-date, starting full test run\n',
    '2019-10-25T11:28:54.345Z project Test run started; run priority: 3\n',
    '2019-10-25T11:28:54.346Z project Running all tests\n',
    '2019-10-25T11:28:54.352Z workers Starting test run, priority: 3\n',
    '2019-10-25T11:28:54.353Z nodeRunner Starting sandbox [worker #0, session #pko0x]\n',
    '2019-10-25T11:28:54.353Z nodeRunner Preparing sandbox [worker #0, session #pko0x]\n',
    '2019-10-25T11:28:55.252Z workers Started run worker instance (delayed) #1\n',
    '2019-10-25T11:28:55.259Z workers Started run worker instance (delayed) #0\n',
    '2019-10-25T11:28:55.259Z nodeRunner Prepared sandbox [worker #0, session #pko0x]\n',
    '2019-10-25T11:28:55.260Z workers [worker #0, session #pko0x] Running tests in sandbox\n',
    '2019-10-25T11:28:55.295Z workers Started run worker instance (delayed) #2\n',
    '2019-10-25T11:28:55.296Z workers Started run worker instance (delayed) #3\n',
    '2019-10-25T11:28:55.344Z workers Started run worker instance (delayed) #4\n',
    '2019-10-25T11:28:55.345Z workers Started run worker instance (delayed) #5\n',
    "2019-10-25T11:29:05.129Z workers Sandbox (active) [pko0x] error: Error: Cannot find module 'core-js/modules/es.symbol.description' from 'jasmineInitializer.js'\n",
    '2019-10-25T11:29:05.143Z workers [pko0x] Run 0 test(s), skipped 0 test(s)\n',
    '2019-10-25T11:29:05.146Z workers [pko0x] Sandbox is responsive, closing it\n',
    "2019-10-25T11:29:05.148Z workers Failed to map the stack to user code, entry message: Error: Cannot find module 'core-js/modules/es.symbol.description' from 'jasmineInitializer.js', stack: Error: Cannot find module 'core-js/modules/es.symbol.description' from 'jasmineInitializer.js'\n" +
      '    at Resolver.resolveModule (C:\\projects\\Private\\vue-cli4\\wallaby-works\\node_modules\\jest-resolve\\build\\index.js:259:17)\n' +
      '    at Resolver._getVirtualMockPath (C:\\projects\\Private\\vue-cli4\\wallaby-works\\node_modules\\jest-resolve\\build\\index.js:390:14)\n' +
      '    at Resolver._getAbsolutePath (C:\\projects\\Private\\vue-cli4\\wallaby-works\\node_modules\\jest-resolve\\build\\index.js:376:14)\n' +
      '    at Resolver.getModuleID (C:\\projects\\Private\\vue-cli4\\wallaby-works\\node_modules\\jest-resolve\\build\\index.js:348:31)\n' +
      '    at Runtime._shouldMock (C:\\projects\\Private\\vue-cli4\\wallaby-works\\node_modules\\jest-runtime\\build\\index.js:942:37)\n' +
      '    at Runtime.requireModuleOrMock (C:\\projects\\Private\\vue-cli4\\wallaby-works\\node_modules\\jest-runtime\\build\\index.js:595:16)\n' +
      '    at Object.<anonymous> (C:\\Users\\che\\.WebStorm2019.2\\system\\wallaby\\wallaby\\runners\\node\\jest@24.8.0\\jasmineInitializer.js:3:1)\n' +
      '    at Runtime._execModule (C:\\projects\\Private\\vue\n',
    '2019-10-25T11:29:05.149Z project Test run finished\n',
    '2019-10-25T11:29:05.149Z project Processed console.log entries\n',
    '2019-10-25T11:29:05.149Z project Processed loading sequences\n',
    '2019-10-25T11:29:05.149Z project Processed executed tests\n',
    '2019-10-25T11:29:05.150Z project Processed code coverage\n',
    '2019-10-25T11:29:05.158Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
Can you try deleting package lock file, deleting node_modules, and installing them from the scratch? If it doesn't help, try checking if there are some (obsolete) `node_modules` in the `C:\\projects\\Private\\vue-cli4\\` folder (and all folders up to `C:\\`), same for `C:\\Users\\che\\` folder.

**Comment by chessydk** [comment]
Solved it! - by upgrading to Webstorm 2019.3EAP ...

Thx for working with me.

**Comment by felikf** [comment]
Same for me in webstorm:

![image](https://user-images.githubusercontent.com/13978154/71978766-6f89db00-321c-11ea-91dd-39801ee68278.png)

**Comment by smcenlly** [comment]
@felikf - I have moved your comment to a new issue (#2307) as it appears to be unrelated to the original thread.
