### ISSUE TITLE
Navigating to error details

### ISSUE THREAD

**Issue by oliversturm** [wallabyjs/public#2268]
### Issue description or question

I'm looking at a failed test just now that appears like this in VS Code:

![wallaby-error-info-missing](https://user-images.githubusercontent.com/4730969/68684801-fdb94c00-0560-11ea-9401-523bb4784249.png)

The popup shows a part of the error output - the format isn't great, but for many errors it's just fine. However, in this case there is much more - by activating the "Wallaby.js Tests" output window and searching for it manually (I have numerous tests failing right now, so this isn't easy), I can find all this detail:

```
  ​​​​getAggregateStore correct state with one event​​​​ ​​​[15 ms]​​​​
     
    TypeError: Type-variable constraint violation 
     
    maybe_ :: (() -> b) -> (a -> b) -> Maybe a -> b 
                     ^ 
                     1 
     
    1)  reject ("Can't get initial state for aggregate customer") :: (no types) 
     
    Since there is no type of which all the above values are members, the type-variable constraint has been violated. 
     
      at contAggregateId ​packages/command-processor/aggregateStore.js:33:6​
      at Object.test ​packages/command-processor/test/aggregateStore.test.js:139:6​
     
    Error: expect.assertions(1) 
     
    Expected one assertion to be called but received zero assertion calls. 
        at Object.test (/home/user/git/lazyapps/packages/command-processor/test/aggregateStore.test.js:258:30) 
        at Object.e.length.arguments.(anonymous function) (/home/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.156/wallaby/runners/node/jest@24.8.0/jasmineInitializer.js:14:1786) 
        at Object.asyncJestTest (/home/user/git/lazyapps/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37) 
        at resolve (/home/user/git/lazyapps/node_modules/jest-jasmine2/build/queueRunner.js:43:12) 
        at new Promise (<anonymous>) 
        at mapper (/home/user/git/lazyapps/node_modules/jest-jasmine2/build/queueRunner.js:26:19) 
        at promise.then (/home/user/git/lazyapps/node_modules/jest-jasmine2/build/queueRunner.js:73:41) 
```

If there is a way of navigating directly from the failed test to the detailed error message, I haven't found it yet. Please tell me! Or otherwise, perhaps this is a feature request?

### Wallaby diagnostics report

```
{ editorVersion: '1.40.0',
  pluginVersion: '1.0.156',
  editorType: 'VSCode',
  osVersion: 'linux 4.19.80-1.pvops.qubes.x86_64',
  nodeVersion: 'v10.16.3',
  coreVersion: '1.0.784',
  config:
   { diagnostics: {},
     testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
     filesWithCoverageCalculated: [],
     micromatch: true,
     files:
      [ { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
        { pattern: 'dist/|build/|coverage/|/\\.idea/|/\\.vscode/|/\\.git/|/\\.gitlab/', regexp: /dist\/|build\/|coverage\/|\/\.idea\/|\/\.vscode\/|\/\.git\/|\/\.gitlab\//, ignore: true, trigger: true, load: true },
        { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
        { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true },
        { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true } ],
     tests:
      [ { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
        { pattern: 'dist/|build/|coverage/|/\\.idea/|/\\.vscode/|/\\.git/|/\\.gitlab/',
          regexp: /dist\/|build\/|coverage\/|\/\.idea\/|\/\.vscode\/|\/\.git\/|\/\.gitlab\//,
          ignore: true,
          trigger: true,
          load: true,
          test: true },
        { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
        { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 } ],
     filesWithNoCoverageCalculated: [],
     runAllTestsInAffectedTestFile: false,
     compilers: {},
     preprocessors: {},
     maxConsoleMessagesPerTest: 100,
     autoConsoleLog: true,
     delays: { run: 0, edit: 100, update: 0 },
     workers: { initial: 0, regular: 0, recycle: false },
     teardown: undefined,
     hints:
      { ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
        ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
        commentAutoLog: '?',
        testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' } },
     automaticTestFileSelection: true,
     runSelectedTestsOnly: false,
     extensions: {},
     env: { type: 'node', params: {}, runner: '<homeDir>/.nvm/versions/node/v10.16.3/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
     reportUnhandledPromises: true,
     slowTestThreshold: 75,
     lowCoverageThreshold: 80,
     loose: true,
     configCode: 'auto.detect#596826066' },
  packageJSON: { dependencies: undefined, devDependencies: { lerna: '^3.18.3' } },
  fs: { numberOfFiles: 22 },
  debug:
   [ '2019-11-12T15:24:19.156Z config Detected Jest.\n',
     '2019-11-12T15:24:19.157Z config Configured Jest.\n',
     '2019-11-12T15:24:19.161Z project Wallaby Node version: v10.16.3\n',
     '2019-11-12T15:24:19.161Z project Wallaby config: <homeDir>/git/lazyapps/auto.detect\n',
     '2019-11-12T15:24:19.940Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.156/projects/ca0f456b54552ec0\n',
     '2019-11-12T15:24:19.954Z uiService Listening port 51235\n',
     '2019-11-12T15:24:19.976Z workers Parallelism for initial run: 4, for regular run: 2\n',
     '2019-11-12T15:24:19.976Z workers Starting run worker instance #0\n',
     '2019-11-12T15:24:19.977Z workers Starting run worker instance #1\n',
     '2019-11-12T15:24:19.977Z workers Starting run worker instance #2\n',
     '2019-11-12T15:24:19.977Z workers Starting run worker instance #3\n',
     '2019-11-12T15:24:19.977Z workers Web server is listening at 32867\n',
     '2019-11-12T15:24:20.020Z project Stopping process pool\n',
     '2019-11-12T15:24:20.020Z project File cache is up-to-date, starting full test run\n',
     '2019-11-12T15:24:20.026Z project Test run started; run priority: 3\n',
     '2019-11-12T15:24:20.026Z project Running all tests\n',
     '2019-11-12T15:24:20.039Z workers Starting test run, priority: 3\n',
     '2019-11-12T15:24:20.039Z workers Distributing tests between 4 workers\n',
     '2019-11-12T15:24:20.041Z workers Running tests in parallel\n',
     '2019-11-12T15:24:20.041Z nodeRunner Starting sandbox [worker #0, session #le81b]\n',
     '2019-11-12T15:24:20.041Z nodeRunner Starting sandbox [worker #1, session #oi4v9]\n',
     '2019-11-12T15:24:20.041Z nodeRunner Starting sandbox [worker #2, session #pobrh]\n',
     '2019-11-12T15:24:20.041Z nodeRunner Starting sandbox [worker #3, session #vpfe2]\n',
     '2019-11-12T15:24:20.041Z nodeRunner Preparing sandbox [worker #0, session #le81b]\n',
     '2019-11-12T15:24:20.041Z nodeRunner Preparing sandbox [worker #1, session #oi4v9]\n',
     '2019-11-12T15:24:20.041Z nodeRunner Preparing sandbox [worker #2, session #pobrh]\n',
     '2019-11-12T15:24:20.041Z nodeRunner Preparing sandbox [worker #3, session #vpfe2]\n',
     '2019-11-12T15:24:20.593Z workers Started run worker instance (delayed) #1\n',
     '2019-11-12T15:24:20.593Z nodeRunner Prepared sandbox [worker #1, session #oi4v9]\n',
     '2019-11-12T15:24:20.593Z workers [worker #1, session #oi4v9] Running tests in sandbox\n',
     '2019-11-12T15:24:20.630Z workers Started run worker instance (delayed) #0\n',
     '2019-11-12T15:24:20.630Z nodeRunner Prepared sandbox [worker #0, session #le81b]\n',
     '2019-11-12T15:24:20.631Z workers [worker #0, session #le81b] Running tests in sandbox\n',
     '2019-11-12T15:24:20.636Z workers Started run worker instance (delayed) #3\n',
     '2019-11-12T15:24:20.636Z nodeRunner Prepared sandbox [worker #3, session #vpfe2]\n',
     '2019-11-12T15:24:20.636Z workers [worker #3, session #vpfe2] Running tests in sandbox\n',
     '2019-11-12T15:24:20.686Z workers Started run worker instance (delayed) #2\n',
     '2019-11-12T15:24:20.686Z nodeRunner Prepared sandbox [worker #2, session #pobrh]\n',
     '2019-11-12T15:24:20.686Z workers [worker #2, session #pobrh] Running tests in sandbox\n',
     '2019-11-12T15:24:23.719Z workers Sandbox (active) [oi4v9] error: Error: Your test suite must contain at least one test.\n',
     '2019-11-12T15:24:23.724Z workers [oi4v9] Loaded unknown number of test(s)\n',
     '2019-11-12T15:24:23.730Z workers [oi4v9] Run 0 test(s), skipped 0 test(s)\n',
     '2019-11-12T15:24:23.732Z workers [oi4v9] Sandbox is responsive, closing it\n',
     '2019-11-12T15:24:24.147Z workers [vpfe2] Loaded unknown number of test(s)\n',
     '2019-11-12T15:24:24.159Z workers [vpfe2] Test executed: returns error1\n',
     '2019-11-12T15:24:24.160Z workers [pobrh] Loaded unknown number of test(s)\n',
     '2019-11-12T15:24:24.161Z workers [vpfe2] Test executed: returns error2\n',
     '2019-11-12T15:24:24.161Z workers [pobrh] Test executed: add event\n',
     '2019-11-12T15:24:24.163Z workers [vpfe2] Test executed: returns Nothing for valid object\n',
     '2019-11-12T15:24:24.163Z workers [pobrh] Test executed: get events\n',
     '2019-11-12T15:24:24.164Z workers [vpfe2] Test executed: log for error\n',
     '2019-11-12T15:24:24.164Z workers [pobrh] Test executed: context add event\n',
     '2019-11-12T15:24:24.165Z workers [vpfe2] Test executed: don\'t log for valid object\n',
     '2019-11-12T15:24:24.165Z workers [pobrh] Test executed: context get events\n',
     '2019-11-12T15:24:24.173Z workers [vpfe2] Run 5 test(s), skipped 0 test(s)\n',
     '2019-11-12T15:24:24.174Z workers [pobrh] Run 4 test(s), skipped 0 test(s)\n',
     '2019-11-12T15:24:24.175Z workers [vpfe2] Sandbox is responsive, closing it\n',
     '2019-11-12T15:24:24.195Z workers [pobrh] Sandbox is responsive, closing it\n',
     '2019-11-12T15:24:24.295Z workers [le81b] Loaded unknown number of test(s)\n',
     '2019-11-12T15:24:24.297Z workers [le81b] Test executed: projects correctly\n',
     '2019-11-12T15:24:24.298Z workers [le81b] Test executed: promise returns data\n',
     '2019-11-12T15:24:24.300Z workers [le81b] Test executed: promise rejects\n',
     '2019-11-12T15:24:24.303Z workers [le81b] Test executed: aggregate with initial\n',
     '2019-11-12T15:24:24.304Z workers [le81b] Test executed: aggregate without initial\n',
     '2019-11-12T15:24:24.312Z workers [le81b] Test executed: correct state with one event\n',
     '2019-11-12T15:24:24.317Z workers [le81b] Test executed: Nothing for non-existent aggregate name\n',
     '2019-11-12T15:24:24.323Z workers [le81b] Test executed: Nothing for aggregate without initial\n',
     '2019-11-12T15:24:24.326Z workers [le81b] Test executed: Initial for aggregate without events\n',
     '2019-11-12T15:24:24.328Z workers [le81b] Test executed: Initial for aggregate without projections\n',
     '2019-11-12T15:24:24.332Z workers [le81b] Test executed: correct state with an ignored event\n',
     '2019-11-12T15:24:24.343Z workers [le81b] Run 11 test(s), skipped 0 test(s)\n',
     '2019-11-12T15:24:24.358Z workers [le81b] Sandbox is responsive, closing it\n',
     '2019-11-12T15:24:24.358Z workers Merging parallel test run results\n',
     '2019-11-12T15:24:24.360Z project Test run finished\n',
     '2019-11-12T15:24:24.360Z project Processed console.log entries\n',
     '2019-11-12T15:24:24.360Z project Processed loading sequences\n',
     '2019-11-12T15:24:24.361Z project Processed executed tests\n',
     '2019-11-12T15:24:24.363Z project Processed code coverage\n',
     '2019-11-12T15:24:24.392Z project Test run result processed and sent to IDE\n' ] }
```

**Comment by smcenlly** [comment]
We don't have a feature that will allow you to quickly get to the detailed error message. Will add as a feature request.

**Comment by ArtemGovorov** [comment]
> If there is a way of navigating directly from the failed test to the detailed error message, I haven't found it yet. 

Yes, it is supported. When you have your cursor on the line with the error (or on any line of the test, or code that the test is covering), you may use the `Wallaby.js: Show Line Test(s)` command (`Ctrl+Shift+R L`) that will display the details of this test only in the "Wallaby.js Tests" output window.

**Comment by oliversturm** [comment]
You're right, this works. Thank you!
