### ISSUE TITLE
Wallaby does not support dynamic imports

### ISSUE THREAD

**Issue by timbru31** [wallabyjs/public#2269]
### Issue description or question

Using the new automated configuration results in no test execution, because dynamic imports are not resolved correctly. Please see the following error message:

```
[Error] Failed to instrument src/app/core/util/product-helper.spec.ts 
[Error]    98 |     // test order version parsing 
[Error]    99 |     it('Nothing is selected. Should return the default order version', () => tslib_1.__awaiter(this, void 0, void 0, function* () { 
[Error] > 100 |         const products = (yield import('../../../testing/product-json/2play-mobile-nothing-selected.json')); 
[Error]       |                                 ^ SyntaxError: Unexpected token (100:32) 
[Error]   101 |         const version = parseOrderVersion(products); 
[Error]   102 |         expect(version).toBeDefined(); 
[Error]   103 |         expect(version).toEqual(DEFAULT_ORDER_VERSION); 
```

On the other hand, `ng test` works fine.

### Wallaby diagnostics report

```
{
  editorVersion: '1.41.0-insider',
  pluginVersion: '1.0.156',
  editorType: 'VSCode',
  osVersion: 'darwin 18.7.0',
  nodeVersion: 'v12.12.0',
  coreVersion: '1.0.784',
  config: {
    diagnostics: {
      angular: {
        workspace: {
          '$schema': './node_modules/@angular/cli/lib/config/schema.json',
          version: 1,
          newProjectRoot: 'projects',
          projects: {
            D2D: {
              root: '',
              sourceRoot: 'src',
              projectType: 'application',
              architect: {
                build: {
                  builder: '@angular-devkit/build-angular:browser',
                  options: {
                    outputPath: 'www',
                    index: 'src/index.html',
                    main: 'src/main.ts',
                    tsConfig: 'tsconfig.app.json',
                    polyfills: 'src/polyfills.ts',
                    assets: [ 'src/assets', 'src/static', 'src/robots.txt', 'src/cordova.js' ],
                    styles: [ 'node_modules/ol/ol.css', 'src/styles.less', 'src/css/app.css' ],
                    scripts: [ './node_modules/hammerjs/hammer.min.js', './src/static/js/ext/AppMeasurement.js' ],
                    aot: true,
                    webWorkerTsConfig: 'tsconfig.worker.json',
                    optimization: true,
                    outputHashing: 'all',
                    vendorChunk: false,
                    buildOptimizer: true,
                    extractCss: true,
                    budgets: [ { type: 'initial', maximumWarning: '2mb', maximumError: '5mb' }, { type: 'anyComponentStyle', maximumWarning: '6kb', maximumError: '10kb' } ]
                  },
                  configurations: {
                    staging: {
                      fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.staging.ts' } ],
                      sourceMap: false,
                      namedChunks: false,
                      extractLicenses: true
                    },
                    production: {
                      fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.production.ts' } ],
                      sourceMap: false,
                      namedChunks: false,
                      extractLicenses: true
                    },
                    playground: { fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.playground.ts' } ] },
                    kindergarten: { fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.kindergarten.ts' } ] },
                    testground: { fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.testground.ts' } ] },
                    e2e: { fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.e2e.ts' } ], outputPath: 'www_e2e' },
                    'e2e-staging': {
                      fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.e2e.ts' } ],
                      extractCss: true,
                      buildOptimizer: true,
                      outputHashing: 'all',
                      sourceMap: false,
                      namedChunks: false,
                      extractLicenses: true,
                      outputPath: 'www_e2e'
                    },
                    serve: { aot: true, optimization: false, outputHashing: 'none', vendorChunk: false, buildOptimizer: false, extractCss: false }
                  }
                },
                serve: {
                  builder: '@angular-devkit/build-angular:dev-server',
                  options: { browserTarget: 'D2D:build:serve' },
                  configurations: {
                    staging: { browserTarget: 'D2D:build:staging' },
                    production: { browserTarget: 'D2D:build:production' },
                    playground: { browserTarget: 'D2D:build:playground' },
                    testground: { browserTarget: 'D2D:build:testground' },
                    kindergarten: { browserTarget: 'D2D:build:kindergarten' },
                    e2e: { browserTarget: 'D2D:build:e2e' },
                    'e2e-staging': { browserTarget: 'D2D:build:e2e-staging' }
                  }
                },
                'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: 'D2D:build' } },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    watch: true,
                    main: 'src/test.ts',
                    karmaConfig: 'src/karma.conf.js',
                    polyfills: 'src/polyfills.ts',
                    tsConfig: 'tsconfig.spec.json',
                    scripts: [ 'node_modules/hammerjs/hammer.min.js', 'src/static/js/ext/AppMeasurement.js' ],
                    styles: [ 'node_modules/ol/ol.css', 'src/styles.less' ],
                    assets: [ 'src/assets', 'src/static', 'src/robots.txt', 'src/cordova.js' ]
                  }
                },
                lint: { builder: '@angular-devkit/build-angular:tslint', options: { tsConfig: [ 'tsconfig.app.json', 'tsconfig.spec.json', 'tsconfig.worker.json' ], exclude: [] } },
                'ionic-cordova-build': {
                  builder: '@ionic/angular-toolkit:cordova-build',
                  options: { browserTarget: 'D2D:build' },
                  configurations: {
                    staging: { browserTarget: 'D2D:build:staging' },
                    prod: { browserTarget: 'D2D:build:prod' },
                    playground: { browserTarget: 'D2D:build:playground' },
                    testground: { browserTarget: 'D2D:build:testground' },
                    kindergarten: { browserTarget: 'D2D:build:kindergarten' }
                  }
                },
                'ionic-cordova-serve': {
                  builder: '@ionic/angular-toolkit:cordova-serve',
                  options: { cordovaBuildTarget: 'D2D:ionic-cordova-build', devServerTarget: 'D2D:serve' },
                  configurations: {
                    staging: { cordovaBuildTarget: 'D2D:ionic-cordova-build:staging', devServerTarget: 'D2D:serve:staging' },
                    prod: { cordovaBuildTarget: 'D2D:ionic-cordova-build:prod', devServerTarget: 'D2D:serve:prod' },
                    playground: { cordovaBuildTarget: 'D2D:ionic-cordova-build:playground', devServerTarget: 'D2D:serve:playground' },
                    testground: { cordovaBuildTarget: 'D2D:ionic-cordova-build:testground', devServerTarget: 'D2D:serve:testground' },
                    kindergarten: { cordovaBuildTarget: 'D2D:ionic-cordova-build:kindergarten', devServerTarget: 'D2D:serve:kindergarten' }
                  }
                }
              }
            },
            'D2D-e2e': {
              root: '',
              sourceRoot: '',
              projectType: 'application',
              architect: {
                e2e: { builder: '@angular-devkit/build-angular:protractor', options: { protractorConfig: 'e2e/protractor.conf.js', devServerTarget: 'D2D:serve:e2e' } },
                lint: { builder: '@angular-devkit/build-angular:tslint', options: { tsConfig: [ 'e2e/tsconfig.e2e.json' ], exclude: [] } }
              }
            }
          },
          defaultProject: 'D2D',
          cli: { warnings: { typescriptMismatch: false } },
          schematics: {
            '@schematics/angular:component': { spec: true, inlineTemplate: false, prefix: 'ume', styleext: 'less' },
            '@schematics/angular:directive': { prefix: 'ume' },
            '@ionic/angular-toolkit:component': { prefix: 'ume', styleext: 'less' },
            '@ionic/angular-toolkit:page': { prefix: 'ume', styleext: 'less' }
          }
        },
        main: '// tslint:disable:no-import-side-effect\n' +
          '// tslint:disable:ordered-imports\n' +
          '\n' +
          '// This file is required by karma.conf.js and loads recursively all the .spec and framework files\n' +
          '\n' +
          "import 'zone.js/dist/zone-testing';\n" +
          "import { getTestBed } from '@angular/core/testing';\n" +
          "import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';\n" +
          '\n' +
          '// tslint:disable:no-any ban-ts-ignore\n' +
          '// @ts-ignore\n' +
          'declare const require: any;\n' +
          '// tslint:enable:no-any ban-ts-ignore\n' +
          '\n' +
          '// First, initialize the Angular testing environment.\n' +
          'getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());\n' +
          '// Then we find all the tests.\n' +
          '\n' +
          '// And load the modules.\n' +
          '\n'
      }
    },
    testFramework: { version: 'jasmine@3.4.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3', autoDetected: true },
    env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    files: [
      { pattern: 'src/**/*.spec.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/polyfills.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/main.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/index.html', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.base.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.wallaby.ts', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'node_modules/hammerjs/hammer.min.js', instrument: false, load: true, ignore: false, trigger: true, order: 2 },
      { pattern: 'src/static/js/ext/AppMeasurement.js', instrument: false, load: true, ignore: false, trigger: true, order: 3 },
      { pattern: 'src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 4 },
      { pattern: 'src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 5 }
    ],
    tests: [ { pattern: 'src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 6 } ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#1269540'
  },
  packageJSON: {
    dependencies: {
      '@angular/cdk': '^8.2.3',
      '@angular/common': '^8.2.11',
      '@angular/compiler': '^8.2.11',
      '@angular/core': '^8.2.11',
      '@angular/flex-layout': '^8.0.0-beta.27',
      '@angular/forms': '^8.2.11',
      '@angular/platform-browser': '^8.2.11',
      '@angular/platform-browser-dynamic': '^8.2.11',
      '@angular/router': '^8.2.11',
      '@d2d/cordova-plugin-inappbrowser': '^3.0.2',
      '@d2d/cordova-plugin-ionic-webview': '^4.2.0',
      '@d2d/cordova-plugin-zip': '^5.0.0',
      '@ionic-native/app-version': '^5.16.0',
      '@ionic-native/badge': '^5.16.0',
      '@ionic-native/calendar': '^5.16.0',
      '@ionic-native/core': '^5.16.0',
      '@ionic-native/device': '^5.16.0',
      '@ionic-native/dialogs': '^5.16.0',
      '@ionic-native/file': '^5.16.0',
      '@ionic-native/file-opener': '^5.16.0',
      '@ionic-native/file-transfer': '^5.16.0',
      '@ionic-native/in-app-browser': '^5.16.0',
      '@ionic-native/ionic-webview': '^5.16.0',
      '@ionic-native/local-notifications': '^5.16.0',
      '@ionic-native/native-page-transitions': '^5.16.0',
      '@ionic-native/network': '^5.16.0',
      '@ionic-native/open-native-settings': '^5.16.0',
      '@ionic-native/pin-check': '^5.16.0',
      '@ionic-native/screen-orientation': '^5.16.0',
      '@ionic-native/secure-storage': '^5.16.0',
      '@ionic-native/status-bar': '^5.16.0',
      '@ionic-native/toast': '^5.16.0',
      '@ionic-native/zip': '^5.16.0',
      '@ionic/pro': '^2.0.4',
      '@ngrx/effects': '^8.4.0',
      '@ngrx/router-store': '^8.4.0',
      '@ngrx/store': '^8.4.0',
      '@ngx-translate/core': '^11.0.1',
      'angular2-text-mask': '^9.0.0',
      'com.telerik.plugins.nativepagetransitions': '^0.6.5',
      'cordova-android': '^8.0.0',
      'cordova-android-support-gradle-release': '^3.0.1',
      'cordova-ios': '^5.0.1',
      'cordova-open-native-settings': '^1.5.2',
      'cordova-pdf-generator': '^2.0.8',
      'cordova-plugin-androidx': '^1.0.2',
      'cordova-plugin-androidx-adapter': '^1.1.0',
      'cordova-plugin-app-version': '^0.1.9',
      'cordova-plugin-badge': '^0.8.8',
      'cordova-plugin-calendar': '^5.1.5',
      'cordova-plugin-customurlscheme': '^4.4.0',
      'cordova-plugin-device': '^2.0.3',
      'cordova-plugin-dialogs': '^2.0.2',
      'cordova-plugin-file': '^6.0.2',
      'cordova-plugin-file-opener2': '^2.2.1',
      'cordova-plugin-file-transfer': '^1.7.1',
      'cordova-plugin-geolocation': '^4.0.2',
      'cordova-plugin-ionic': '^5.4.4',
      'cordova-plugin-local-notification': 'git+https://github.com/katzer/cordova-plugin-local-notifications.git',
      'cordova-plugin-lottie-splashscreen': '^0.7.1',
      'cordova-plugin-network-information': '^2.0.2',
      'cordova-plugin-pincheck': '^0.0.6',
      'cordova-plugin-screen-orientation': '^3.0.2',
      'cordova-plugin-secure-storage': '^3.0.2',
      'cordova-plugin-splashscreen': '^5.0.3',
      'cordova-plugin-statusbar': '^2.4.3',
      'cordova-plugin-whitelist': '^1.3.4',
      'cordova-plugin-x-toast': '^2.7.2',
      'date-fns': '^2.7.0',
      dexie: '^2.0.4',
      'es6-promise-plugin': '^4.2.2',
      hammerjs: '^2.0.8',
      ibantools: '^2.2.0',
      lunr: '^2.3.8',
      ol: '^5.3.3',
      rxjs: '^6.5.3',
      signature_pad: '^2.3.2',
      tslib: '^1.10.0',
      'zone.js': '^0.10.2'
    },
    devDependencies: {
      '@angular-devkit/architect': '^0.803.18',
      '@angular-devkit/build-angular': '^0.803.18',
      '@angular-devkit/build-optimizer': '^0.803.18',
      '@angular-devkit/core': '^8.3.18',
      '@angular-devkit/schematics': '^8.3.18',
      '@angular/cli': '^8.3.18',
      '@angular/compiler-cli': '^8.2.11',
      '@angular/language-service': '^8.2.13',
      '@commitlint/cli': '^8.2.0',
      '@commitlint/config-conventional': '^8.2.0',
      '@ionic/angular-toolkit': '^2.1.1',
      '@ngrx/store-devtools': '^8.4.0',
      '@ngtools/webpack': '^8.3.18',
      '@types/cordova': '^0.0.34',
      '@types/ejs': '^2.6.3',
      '@types/jasmine': '^3.4.6',
      '@types/jasminewd2': '^2.0.8',
      '@types/lunr': '^2.3.2',
      '@types/node': '^12.12.7',
      '@types/ol': '^5.3.6',
      '@types/signature_pad': '^2.3.0',
      '@types/testingbot-api': '^1.0.0',
      autoprefixer: '^9.7.1',
      'clean-css-cli': '^4.3.0',
      codelyzer: '^5.2.0',
      cordova: '^9.0.0',
      ejs: '^2.7.1',
      ionic: '^5.4.6',
      'jasmine-core': '^3.5.0',
      'jasmine-spec-reporter': '^4.2.1',
      karma: '^4.4.1',
      'karma-chrome-launcher': '^3.1.0',
      'karma-coverage-istanbul-reporter': '^2.1.0',
      'karma-firefox-launcher': '^1.2.0',
      'karma-jasmine': '^2.0.1',
      'karma-jasmine-html-reporter': '^1.4.2',
      'karma-safari-launcher': '^1.0.0',
      'karma-testingbot-launcher': '^1.0.3',
      less: '^3.10.3',
      'ngrx-store-logger': '^0.2.4',
      'postcss-cli': '^6.1.3',
      protractor: '^5.4.2',
      'rxjs-tslint-rules': '^4.26.1',
      serve: '^11.2.0',
      stylelint: '^11.1.1',
      'stylelint-config-prettier': '^6.0.0',
      'stylelint-config-standard': '^19.0.0',
      'testingbot-api': '^1.0.7',
      'ts-node': '^8.5.0',
      tslint: '^5.20.1',
      typescript: '~3.5.3',
      'webdriver-manager': '^12.1.7'
    }
  },
  fs: { numberOfFiles: 1001 },
  debug: [
    '2019-11-13T17:12:13.565Z config Detected Angular CLI.\n',
    '2019-11-13T17:12:15.056Z angular/cli project config Using virtual <homeDir>/Coding/ume/d2d-webapp/src/test.ts.\n',
    '2019-11-13T17:12:15.068Z config Configured Angular CLI.\n',
    '2019-11-13T17:12:15.069Z project Wallaby Node version: v12.12.0\n',
    '2019-11-13T17:12:15.069Z project Wallaby config: <homeDir>/Coding/ume/d2d-webapp/auto.detect\n',
    '2019-11-13T17:12:15.976Z project File cache: <homeDir>/.vscode-insiders/extensions/wallabyjs.wallaby-vscode-1.0.156/projects/1ddafceaa4c0b784\n',
    '2019-11-13T17:12:15.988Z uiService Listening port 51235\n',
    '2019-11-13T17:12:16.295Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2019-11-13T17:12:16.295Z workers Starting run worker instance #0\n',
    '2019-11-13T17:12:16.295Z workers Starting run worker instance #1\n',
    '2019-11-13T17:12:16.295Z workers Starting run worker instance #2\n',
    '2019-11-13T17:12:16.295Z workers Starting run worker instance #3\n',
    '2019-11-13T17:12:16.295Z workers Starting run worker instance #4\n',
    '2019-11-13T17:12:16.295Z workers Starting run worker instance #5\n',
    '2019-11-13T17:12:16.317Z workers Web server is listening at 53033\n',
    '2019-11-13T17:12:16.380Z project Stopping process pool\n',
    '2019-11-13T17:12:16.380Z project File cache is up-to-date, starting full test run\n',
    '2019-11-13T17:12:16.382Z project Running postprocessor\n',
    '2019-11-13T17:12:16.391Z postprocessor Processing started.\n',
    '2019-11-13T17:12:16.391Z postprocessor Initializing.\n',
    '2019-11-13T17:12:16.392Z postprocessor Initializing entry.\n',
    '2019-11-13T17:12:16.392Z postprocessor Sanitizing configuration.\n',
    '2019-11-13T17:12:16.392Z postprocessor Adjusting configuration.\n',
    '2019-11-13T17:12:16.392Z postprocessor Creating compiler.\n',
    '2019-11-13T17:12:16.465Z postprocessor Customizing compiler.\n',
    '2019-11-13T17:12:16.465Z postprocessor Compilation started.\n',
    '2019-11-13T17:12:26.035Z workers Started run worker instance (immediate) #0\n',
    '2019-11-13T17:12:26.035Z workers Started run worker instance (immediate) #1\n',
    '2019-11-13T17:12:26.035Z workers Started run worker instance (immediate) #2\n',
    '2019-11-13T17:12:26.035Z workers Started run worker instance (immediate) #3\n',
    '2019-11-13T17:12:26.035Z workers Started run worker instance (immediate) #4\n',
    '2019-11-13T17:12:26.035Z workers Started run worker instance (immediate) #5\n',
    '2019-11-13T17:12:41.450Z project Error: Failed to instrument src/app/core/util/product-helper.spec.ts\n' +
      '   98 |     // test order version parsing\n' +
      "   99 |     it('Nothing is selected. Should return the default order version', () => tslib_1.__awaiter(this, void 0, void 0, function* () {\n" +
      "> 100 |         const products = (yield import('../../../testing/product-json/2play-mobile-nothing-selected.json'));\n" +
      '      |                                 ^ SyntaxError: Unexpected token (100:32)\n' +
      '  101 |         const version = parseOrderVersion(products);\n' +
      '  102 |         expect(version).toBeDefined();\n' +
      '  103 |         expect(version).toEqual(DEFAULT_ORDER_VERSION);\n' +
      '    at Object.formatInstrumentationError (<homeDir>/.vscode-insiders/extensions/wallabyjs.wallaby-vscode-1.0.156/wallaby/server.js:25:3931)\n' +
      '    at Object.r (<homeDir>/.vscode-insiders/extensions/wallabyjs.wallaby-vscode-1.0.156/wallaby/server.js:19:24496)\n' +
      '    at Object.t.exports.post (<homeDir>/.vscode-insiders/extensions/wallabyjs.wallaby-vscode-1.0.156/wallaby/server.js:19:25172)\n' +
      '    at LOADER_EXECUTION (<homeDir>/Coding/ume/d2d-webapp/node_modules/loader-runner/lib/LoaderRunner.js:119:14)\n' +
      '    at runSyncOrAsync (<homeDir>/Coding/ume/d2d-webapp/node_modules/loader-runner/lib/LoaderRunner.js:120:4)\n' +
      '    at iterateNormalLoaders (<homeDir>/Coding/ume/d2d-webapp/node_modules/loader-runner/lib/LoaderRunner.js:232:2)\n' +
      '    at iterateNormalLoaders (<homeDir>/Coding/ume/d2d-webapp/node_modules/loader-runner/lib/LoaderRunner.js:221:10)\n' +
      '    at <homeDir>/Coding/ume/d2d-webapp/node_modules/loader-runner/lib/LoaderRunner.js:236:3\n' +
      '    at context.callback (<homeDir>/Coding/ume/d2d-webapp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)\n' +
      '    at <homeDir>/Coding/ume/d2d-webapp/node_modules/@ngtools/webpack/src/loader.js:90:9\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n',
    '2019-11-13T17:12:41.451Z project Test run finished\n',
    '2019-11-13T17:12:41.451Z project Test run data re-queued\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
Thanks for providing the diagnostics report. The issue is fixed and the fix is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by timbru31** [comment]
Thanks for the quick fix!
