### ISSUE TITLE
Unexpected token… when running for node/mocha with mixed TS & JS 

### ISSUE THREAD

**Issue by pavsaund** [wallabyjs/public#2281]
### Issue description or question

We have a largish project that's been converted to TypeScript, but still contains some JavaScript files, and are encountering an issue with wallaby runner not transpiling the javascript files, and throwing an `Unexpected token...` in the console. I've re-created a test-project, which is a lot smaller, but has the same behaviour: https://github.com/pavsaund/wallaby-dolittle-aurelia-mixed-js-ts

There's some tooling instrumentation happening behind the scenes, but I've provided a few different configurations in that example, and a descriptive Readme. I tried looking at solutions for others with the same issue, but couldn't successfully apply a functional fix.

Appreciate any help you can provide (really want to get wallaby enabled again 😁 )

<details><summary>Console Output:</summary>

```sh
[Info]  Started Wallaby.js Core v1.0.789
[Error] Runtime error: ./Features/external-dependency.js:1 
[Error] export const stringish = (x) => x.toString(); 
[Error] ^^^^^^ 
[Error] SyntaxError: Unexpected token export 
[Error]     at Module._compile (internal/modules/cjs/loader.js:718:23) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:641:32) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:556:12) 
[Error]     at Module.require (internal/modules/cjs/loader.js:681:19) 
[Error]     at require (internal/modules/cjs/helpers.js:16:16) 
[Error]     at Object.<anonymous> (./Features/something.js:4:45) 
[Error]     at Module._compile (internal/modules/cjs/loader.js:774:30) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:641:32) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:556:12) 
[Error]     at Module.require (internal/modules/cjs/loader.js:681:19) 
[Error]     at require (internal/modules/cjs/helpers.js:16:16) 
[Error]     at Object.<anonymous> (./Features/for_something/given/a_context.js:3:21) 
[Error]     at Module._compile (internal/modules/cjs/loader.js:774:30) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:641:32) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:556:12) 
[Error]     at Module.require (internal/modules/cjs/loader.js:681:19) 
[Error]     at require (internal/modules/cjs/helpers.js:16:16) 
[Error]     at Object.<anonymous> (./Features/for_something/when_doing_something.js:4:35) 
[Error]     at Module._compile (internal/modules/cjs/loader.js:774:30) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:641:32) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:556:12) 
[Error]     at Module.require (internal/modules/cjs/loader.js:681:19) 
[Error]     at require (internal/modules/cjs/helpers.js:16:16) 
[Error]     at ./node_modules/mocha/lib/mocha.js:334:36 
[Error]     at Array.forEach (<anonymous>) 
[Error]     at Mocha.loadFiles (./node_modules/mocha/lib/mocha.js:331:14) 
[Error]     at Mocha.run (./node_modules/mocha/lib/mocha.js:809:10) 
[Error]     at WebSocket.emit (events.js:200:13) 
```

</details>

### Wallaby diagnostics report
<details><summary>Diagnostics report</summary>

```
{
  editorVersion: '1.40.2',
  pluginVersion: '1.0.157',
  editorType: 'VSCode',
  osVersion: 'darwin 19.0.0',
  nodeVersion: 'v12.4.0',
  coreVersion: '1.0.789',
  config: {
    files: [
      { pattern: 'wwwroot/**/*', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: 'Configurations/**/*', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: 'Scripts/**/*', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: 'node_modules/!(chai|chai-as-promised|sinon|sinon-chai)', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: 'node_modules/@dolittle/!(typescript.build)', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: 'package.json', instrument: false, ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'node_modules/chai', instrument: false, ignore: false, trigger: true, load: true, order: 2 },
      { pattern: 'node_modules/chai-as-promised', instrument: false, ignore: false, trigger: true, load: true, order: 3 },
      { pattern: 'node_modules/sinon', instrument: false, ignore: false, trigger: true, load: true, order: 4 },
      { pattern: 'node_modules/sinon-chai', instrument: false, ignore: false, trigger: true, load: true, order: 5 },
      { pattern: 'node_modules/@dolittle/typescript.build', instrument: false, ignore: false, trigger: true, load: true, order: 6 },
      { pattern: 'Distribution/**/*', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: '**/for_*/**/!(given)/*.@(ts|js)', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: '**/for_*/*.@(ts|js)', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: '**/for_*/**/given/*.@(ts|js)', instrument: false, ignore: false, trigger: true, load: true, order: 7 },
      { pattern: '**/*.@(ts|js)', ignore: false, trigger: true, load: true, instrument: true, order: 8 }
    ],
    tests: [
      { pattern: 'wwwroot/**/*', ignore: true, trigger: true, load: true, test: true },
      { pattern: 'Configurations/**/*', ignore: true, trigger: true, load: true, test: true },
      { pattern: 'Scripts/**/*', ignore: true, trigger: true, load: true, test: true },
      { pattern: 'node_modules/!(chai|chai-as-promised|sinon|sinon-chai)', ignore: true, trigger: true, load: true, test: true },
      { pattern: 'node_modules/@dolittle/!(typescript.build)', ignore: true, trigger: true, load: true, test: true },
      { pattern: 'Distribution/**/*', ignore: true, trigger: true, load: true, test: true },
      { pattern: '**/for_*/**/given/*.@(ts|js)', ignore: true, trigger: true, load: true, test: true },
      { pattern: '**/for_*/*.@(ts|js)', ignore: false, trigger: true, load: true, test: true, order: 9 },
      { pattern: '**/for_*/**/!(given)/*.@(ts|js)', ignore: false, trigger: true, load: true, test: true, order: 10 }
    ],
    compilers: { '**/*.?(lit)coffee?(.md)': [Function] },
    testFramework: { version: 'mocha@2.1.0', configurator: 'mocha@2.1.0', reporter: 'mocha@2.1.0', starter: 'mocha@2.1.0' },
    env: { type: 'node', runner: 'node', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: undefined,
    configCode: `\nmodule.exports = function (wallaby) {\n    process.env.WALLABY = "true";\n    return {\n        files: [\n            { pattern: 'wwwroot/**/*', ignore: true },\n            { pattern: ` +
      "'Configurations/**/*', ignore: true },\n            { pattern: 'Scripts/**/*', ignore: true },\n            { pattern: 'node_modules/!(chai|chai-as-promised|sinon|sinon-chai)', ignore: " +
      "true },\n            { pattern: 'node_modules/@dolittle/!(typescript.build)', ignore: true },\n            { pattern: 'package.json', instrument: false },\n            { pattern: " +
      "'node_modules/chai', instrument: false },\n            { pattern: 'node_modules/chai-as-promised', instrument: false },\n            { pattern: 'node_modules/sinon', instrument: false " +
      "},\n            { pattern: 'node_modules/sinon-chai', instrument: false },\n            { pattern: 'node_modules/@dolittle/typescript.build', instrument: false },\n            { " +
      "pattern: 'Distribution/**/*', ignore: true },\n            { pattern: '/**/for_*/**/!(given)/*.@(ts|js)', ignore: true },\n            { pattern: '/**/for_*/*.@(ts|js)', ignore: true " +
      "},\n            { pattern: '/**/for_*/**/given/*.@(ts|js)', instrument: false },\n            { pattern: '/**/*.@(ts|js)' }\n        ],\n        tests: [\n            { pattern: " +
      "'wwwroot/**/*', ignore: true },\n            { pattern: 'Configurations/**/*', ignore: true },\n            { pattern: 'Scripts/**/*', ignore: true },\n            { pattern: " +
      "'node_modules/!(chai|chai-as-promised|sinon|sinon-chai)', ignore: true },\n            { pattern: 'node_modules/@dolittle/!(typescript.build)', ignore: true },\n            { pattern: " +
      "'Distribution/**/*', ignore: true },\n            { pattern: '/**/for_*/**/given/*.@(ts|js)', ignore: true },\n            { pattern: '/**/for_*/*.@(ts|js)' },\n            { pattern: " +
      "'/**/for_*/**/!(given)/*.@(ts|js)' }\n        ],\n        compilers: {\n            '**/*.@(js|ts)': wallaby.compilers.typeScript({\n                module: 'commonjs',\n                " +
      "downlevelIteration: true,\n                allowJs: true,\n                experimentalDecorators: true,\n                esModuleInterop: true,\n                target: 'es6'\n           " +
      ' })\n        },\n        setup: (wallaby) => {\n            process.env.IS_TESTING = "true";\n            global.expect = chai.expect;\n            let should = chai.should();\n            ' +
      "global.sinon = require('sinon');\n            let sinonChai = require('sinon-chai');\n            let chaiAsPromised = require('chai-as-promised');\n            chai.use(sinonChai);\n    " +
      "        chai.use(chaiAsPromised);\n        \n            global.mock = require('@fluffy-spoon/substitute').Substitute;\n        },\n        testFramework: 'mocha',\n        env: { type: " +
      "'node', runner: 'node' }\n    }\n}"
  },
  packageJSON: {
    dependencies: { '@dolittle/aurelia': '^2.0.0', eslint: '^6.6.0', 'eslint-config-prettier': '^6.6.0', 'eslint-plugin-prettier': '^3.1.1', prettier: '^1.19.1' },
    devDependencies: { '@babel/core': '^7.7.4', '@dolittle/build': '^6.3.4', '@dolittle/typescript.build': '^5.1.1', '@dolittle/typescript.webpack.aurelia': '^1.1.0', dotenv: '^6.1.0' }
  },
  fs: { numberOfFiles: 284 },
  debug: [
    '2019-11-26T20:50:58.486Z project Wallaby Node version: v12.4.0\n',
    '2019-11-26T20:50:58.486Z project Wallaby config: <homeDir>/code/Playground/wallaby-dolittle-aurelia-mixed-js-ts/wallaby.config.plain.js\n',
    '2019-11-26T20:50:59.465Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.157/projects/a773436c54e9d5da\n',
    '2019-11-26T20:50:59.472Z uiService Listening port 51235\n',
    '2019-11-26T20:50:59.511Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2019-11-26T20:50:59.511Z workers Starting run worker instance #0\n',
    '2019-11-26T20:50:59.511Z workers Starting run worker instance #1\n',
    '2019-11-26T20:50:59.511Z workers Starting run worker instance #2\n',
    '2019-11-26T20:50:59.512Z workers Starting run worker instance #3\n',
    '2019-11-26T20:50:59.512Z workers Starting run worker instance #4\n',
    '2019-11-26T20:50:59.512Z workers Starting run worker instance #5\n',
    '2019-11-26T20:50:59.517Z workers Web server is listening at 55177\n',
    '2019-11-26T20:50:59.693Z project File cache requires some updates, waiting required files from IDE\n',
    '2019-11-26T20:50:59.928Z workers Started run worker instance (delayed) #1\n',
    '2019-11-26T20:50:59.929Z workers Started run worker instance (delayed) #0\n',
    '2019-11-26T20:50:59.933Z workers Started run worker instance (delayed) #2\n',
    '2019-11-26T20:50:59.958Z workers Started run worker instance (delayed) #3\n',
    '2019-11-26T20:51:00.000Z workers Started run worker instance (delayed) #5\n',
    '2019-11-26T20:51:00.034Z workers Started run worker instance (delayed) #4\n',
    '2019-11-26T20:51:00.284Z project Stopping process pool\n',
    '2019-11-26T20:51:00.285Z project Running postprocessor\n',
    '2019-11-26T20:51:00.300Z postprocessor New TypeScript language service is required\n',
    '2019-11-26T20:51:10.161Z project Postprocessor execution finished\n',
    '2019-11-26T20:51:10.161Z project Test run started; run priority: 3\n',
    '2019-11-26T20:51:10.161Z project Running all tests\n',
    '2019-11-26T20:51:10.166Z workers Starting test run, priority: 3\n',
    '2019-11-26T20:51:10.166Z nodeRunner Starting sandbox [worker #0, session #04yip]\n',
    '2019-11-26T20:51:10.166Z nodeRunner Preparing sandbox [worker #0, session #04yip]\n',
    '2019-11-26T20:51:10.167Z nodeRunner Prepared sandbox [worker #0, session #04yip]\n',
    '2019-11-26T20:51:10.167Z workers [worker #0, session #04yip] Running tests in sandbox\n',
    '2019-11-26T20:51:10.379Z workers Sandbox (active) [04yip] error: Unexpected token export\n',
    '2019-11-26T20:51:10.483Z workers [04yip] Run 0 test(s), skipped 0 test(s)\n',
    '2019-11-26T20:51:10.485Z workers [04yip] Sandbox is responsive, closing it\n',
    '2019-11-26T20:51:10.487Z project Test run finished\n',
    '2019-11-26T20:51:10.487Z project Processed console.log entries\n',
    '2019-11-26T20:51:10.487Z project Processed loading sequences\n',
    '2019-11-26T20:51:10.487Z project Processed executed tests\n',
    '2019-11-26T20:51:10.489Z project Processed code coverage\n',
    '2019-11-26T20:51:10.506Z project Test run result processed and sent to IDE\n'
  ]
}
```

</details>

**Comment by smcenlly** [comment]
There are a couple of minor tweaks that you will need to make to your configuration to get this working ([referenced in this issue](https://github.com/wallabyjs/public/issues/2049)). 

The issue is that your TypeScript configuration doesn't specify an `outDir`. With `allowJs`: `true` setting, the TS compiler can not overwrite existing JS files and skips emit. You will also need to rename the transpiled JavaScript files using a preprocessor.

Here's the change you need to make in your Wallaby config to make it work:

```diff
...
        compilers: {
            '**/*.@(js|ts)': wallaby.compilers.typeScript({
                module: 'commonjs',
                downlevelIteration: true,
                allowJs: true,
                experimentalDecorators: true,
                esModuleInterop: true,
+               outDir: './any',
                target: 'es6'
            })
        },
+       preprocessors: {
+           '**/*.jsts': file => file.changeExt('js').content
+       },
        setup: (wallaby) => {
...
```

**Comment by pavsaund** [comment]
Thanks! I hadn't considered combined the outDir and preprocessor options together. :)

I hope you can help me understand what's going on a bit regarding the preprocessor step. I read that as changing the extension from all the files matching `*.jsts` and changing their extension to `js`. Does the wallaby-typescript compiler change the filenames in its local cache to jsts first?
