### ISSUE TITLE
Testing Angular Library with Jest + Wallaby

### ISSUE THREAD

**Issue by kplates** [wallabyjs/public#2288]
### Issue description or question

Having issues getting wallaby running with my angular library created using the angular cli. Have tried multiple solutions only to find they are out of date. I believe I will need to manually create my wallaby.js configuration but am unsure how to achieve this. I can seem to run jest on its own via the package.json npm scripts just fine.

```
SyntaxError: .\projects\my-awesome-lib\src\lib\my-awesome-lib.component.spec.ts: Unexpected token, expected ";" (6:15) 
 
  4 |  
  5 | describe('MyAwesomeLibComponent', () => { 
> 6 |   let component: MyAwesomeLibComponent; 
    |                ^ 
  7 |   let fixture: ComponentFixture<MyAwesomeLibComponent>; 
  8 |  
  9 |   beforeEach(async(() => { 
Jest encountered an unexpected token 

```

### Wallaby diagnostics report

```
{ editorVersion: '1.40.2',
  pluginVersion: '1.0.158',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.17134',
  nodeVersion: 'v10.16.3',
  coreVersion: '1.0.793',
  config:
   { diagnostics: {},
     testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
     filesWithCoverageCalculated: [],
     micromatch: true,
     files:
      [ { pattern: '\\\\node_modules\\\\', regexp: /\\node_modules\\/, ignore: true, trigger: true, load: true },
        { pattern: 'dist\\\\|build\\\\|coverage\\\\|\\\\\\.idea\\\\|\\\\\\.vscode\\\\|\\\\\\.git\\\\|\\\\\\.gitlab\\\\',
          regexp: /dist\\|build\\|coverage\\|\\\.idea\\|\\\.vscode\\|\\\.git\\|\\\.gitlab\\/,
          ignore: true,
          trigger: true,
          load: true },
        { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
        { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true },
        { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true } ],
     tests:
      [ { pattern: '\\\\node_modules\\\\', regexp: /\\node_modules\\/, ignore: true, trigger: true, load: true, test: true },
        { pattern: 'dist\\\\|build\\\\|coverage\\\\|\\\\\\.idea\\\\|\\\\\\.vscode\\\\|\\\\\\.git\\\\|\\\\\\.gitlab\\\\',
          regexp: /dist\\|build\\|coverage\\|\\\.idea\\|\\\.vscode\\|\\\.git\\|\\\.gitlab\\/,
          ignore: true,
          trigger: true,
          load: true,
          test: true },
        { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
        { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 } ],
     filesWithNoCoverageCalculated: [],
     runAllTestsInAffectedTestFile: false,
     compilers: {},
     preprocessors: {},
     maxConsoleMessagesPerTest: 100,
     autoConsoleLog: true,
     delays: { run: 0, edit: 100, update: 0 },
     workers: { initial: 0, regular: 0, recycle: false },
     teardown: undefined,
     hints:
      { ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
        ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
        commentAutoLog: '?',
        testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' } },
     automaticTestFileSelection: true,
     runSelectedTestsOnly: false,
     extensions: {},
     env: { type: 'node', params: {}, runner: 'C:\\Program Files\\nodejs\\node.exe', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
     reportUnhandledPromises: true,
     slowTestThreshold: 75,
     lowCoverageThreshold: 80,
     loose: true,
     configCode: 'auto.detect#195988946' },
  packageJSON:
   { dependencies:
      { '@angular/animations': '~8.2.9',
        '@angular/common': '~8.2.9',
        '@angular/compiler': '~8.2.9',
        '@angular/core': '~8.2.9',
        '@angular/forms': '~8.2.9',
        '@angular/platform-browser': '~8.2.9',
        '@angular/platform-browser-dynamic': '~8.2.9',
        '@angular/router': '~8.2.9',
        rxjs: '~6.4.0',
        tslib: '^1.10.0',
        'zone.js': '~0.9.1' },
     devDependencies:
      { '@angular-devkit/build-angular': '~0.803.7',
        '@angular-devkit/build-ng-packagr': '~0.803.20',
        '@angular/cli': '~8.3.7',
        '@angular/compiler-cli': '~8.2.9',
        '@angular/language-service': '~8.2.9',
        '@types/jasmine': '~3.3.8',
        '@types/jasminewd2': '~2.0.3',
        '@types/node': '~8.9.4',
        codelyzer: '^5.0.0',
        'jasmine-core': '~3.4.0',
        'jasmine-spec-reporter': '~4.2.1',
        jest: '^24.9.0',
        'jest-preset-angular': '^8.0.0',
        'ng-packagr': '^5.4.0',
        protractor: '~5.4.0',
        'ts-node': '~7.0.0',
        tsickle: '^0.37.0',
        tslint: '~5.15.0',
        typescript: '~3.5.3' } },
  fs: { numberOfFiles: 45 },
  debug:
   [ '2019-12-09T04:13:07.685Z config Detected Jest.\n',
     '2019-12-09T04:13:07.685Z config Configured Jest.\n',
     '2019-12-09T04:13:07.689Z project Wallaby Node version: v10.16.3\n',
     '2019-12-09T04:13:07.689Z project Wallaby config: C:\\Users\\kplates\\Desktop\\my-awesome-app\\auto.detect\n',
     '2019-12-09T04:13:08.466Z project File cache: C:\\Users\\kplates\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.158\\projects\\75b744ae4c948dca\n',
     '2019-12-09T04:13:08.514Z uiService Listening port 51235\n',
     '2019-12-09T04:13:08.536Z workers Parallelism for initial run: 10, for regular run: 5\n',
     '2019-12-09T04:13:08.537Z workers Starting run worker instance #0\n',
     '2019-12-09T04:13:08.537Z workers Starting run worker instance #1\n',
     '2019-12-09T04:13:08.537Z workers Starting run worker instance #2\n',
     '2019-12-09T04:13:08.537Z workers Starting run worker instance #3\n',
     '2019-12-09T04:13:08.537Z workers Starting run worker instance #4\n',
     '2019-12-09T04:13:08.537Z workers Starting run worker instance #5\n',
     '2019-12-09T04:13:08.537Z workers Starting run worker instance #6\n',
     '2019-12-09T04:13:08.537Z workers Starting run worker instance #7\n',
     '2019-12-09T04:13:08.537Z workers Starting run worker instance #8\n',
     '2019-12-09T04:13:08.537Z workers Starting run worker instance #9\n',
     '2019-12-09T04:13:08.538Z workers Web server is listening at 54836\n',
     '2019-12-09T04:13:08.582Z project Stopping process pool\n',
     '2019-12-09T04:13:08.582Z project File cache is up-to-date, starting full test run\n',
     '2019-12-09T04:13:08.585Z project Test run started; run priority: 3\n',
     '2019-12-09T04:13:08.586Z project Running all tests\n',
     '2019-12-09T04:13:08.588Z workers Starting test run, priority: 3\n',
     '2019-12-09T04:13:08.588Z workers Distributing tests between 10 workers\n',
     '2019-12-09T04:13:08.590Z workers Running tests in parallel\n',
     '2019-12-09T04:13:08.590Z nodeRunner Starting sandbox [worker #0, session #mo8qs]\n',
     '2019-12-09T04:13:08.590Z nodeRunner Starting sandbox [worker #1, session #l9s4z]\n',
     '2019-12-09T04:13:08.590Z nodeRunner Starting sandbox [worker #2, session #g5bef]\n',
     '2019-12-09T04:13:08.591Z nodeRunner Preparing sandbox [worker #0, session #mo8qs]\n',
     '2019-12-09T04:13:08.591Z nodeRunner Preparing sandbox [worker #1, session #l9s4z]\n',
     '2019-12-09T04:13:08.591Z nodeRunner Preparing sandbox [worker #2, session #g5bef]\n',
     '2019-12-09T04:13:09.052Z workers Started run worker instance (delayed) #0\n',
     '2019-12-09T04:13:09.052Z nodeRunner Prepared sandbox [worker #0, session #mo8qs]\n',
     '2019-12-09T04:13:09.053Z workers [worker #0, session #mo8qs] Running tests in sandbox\n',
     '2019-12-09T04:13:09.055Z workers Started run worker instance (delayed) #1\n',
     '2019-12-09T04:13:09.055Z nodeRunner Prepared sandbox [worker #1, session #l9s4z]\n',
     '2019-12-09T04:13:09.055Z workers [worker #1, session #l9s4z] Running tests in sandbox\n',
     '2019-12-09T04:13:09.056Z workers Started run worker instance (delayed) #2\n',
     '2019-12-09T04:13:09.056Z nodeRunner Prepared sandbox [worker #2, session #g5bef]\n',
     '2019-12-09T04:13:09.056Z workers [worker #2, session #g5bef] Running tests in sandbox\n',
     '2019-12-09T04:13:09.059Z workers Started run worker instance (delayed) #3\n',
     '2019-12-09T04:13:09.059Z workers Started run worker instance (delayed) #5\n',
     '2019-12-09T04:13:09.062Z workers Started run worker instance (delayed) #4\n',
     '2019-12-09T04:13:09.073Z workers Started run worker instance (delayed) #6\n',
     '2019-12-09T04:13:09.077Z workers Started run worker instance (delayed) #8\n',
     '2019-12-09T04:13:09.081Z workers Started run worker instance (delayed) #7\n',
     '2019-12-09T04:13:09.082Z workers Started run worker instance (delayed) #9\n',
     '2019-12-09T04:13:11.093Z workers Sandbox (active) [g5bef] error: Jest encountered an unexpected token\n\nThis usually means that you are trying to import a file which Jest cannot parse, e.g. it\'s not plain JavaScript.\n\nBy default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".\n\nHere\'s what you can do:\n • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.\n • If you need a custom transformation specify a "transform" option in your config.\n • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.\n\nYou\'ll find more details and examples of these config options in the docs:\nhttps://jestjs.io/docs/en/configuration.html\n\nDetails:\n\nC:\\Users\\kplates\\Desktop\\my-awesome-app\\src\\app\\app.component.spec.ts:2\nimport {\n       ^\n\nSyntaxError: Unexpected token {\n',
     '2019-12-09T04:13:11.097Z workers [g5bef] Run 0 test(s), skipped 0 test(s)\n',
     '2019-12-09T04:13:11.098Z workers [g5bef] Sandbox is responsive, closing it\n',
     '2019-12-09T04:13:11.321Z workers Sandbox (active) [l9s4z] error: Jest encountered an unexpected token\n\nThis usually means that you are trying to import a file which Jest cannot parse, e.g. it\'s not plain JavaScript.\n\nBy default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".\n\nHere\'s what you can do:\n • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.\n • If you need a custom transformation specify a "transform" option in your config.\n • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.\n\nYou\'ll find more details and examples of these config options in the docs:\nhttps://jestjs.io/docs/en/configuration.html\n\nDetails:\n\nSyntaxError: C:\\Users\\kplates\\Desktop\\my-awesome-app\\projects\\my-awesome-lib\\src\\lib\\my-awesome-lib.service.spec.ts: Unexpected token (9:17)\n\n   7 | \n   8 |   it(\'should be created\', () => {\n>  9 |     const service: MyAwesomeLibService = TestBed.get(MyAwesomeLibService);\n     |                  ^\n  10 |     expect(service).toBeTruthy();\n  11 |   });\n  12 | });\n',
     '2019-12-09T04:13:11.328Z workers [l9s4z] Run 0 test(s), skipped 0 test(s)\n',
     '2019-12-09T04:13:11.331Z workers Sandbox (active) [mo8qs] error: SyntaxError: C:\\Users\\kplates\\Desktop\\my-awesome-app\\projects\\my-awesome-lib\\src\\lib\\my-awesome-lib.component.spec.ts: Unexpected token, expected ";" (6:15)\n\n  4 | \n  5 | describe(\'MyAwesomeLibComponent\', () => {\n> 6 |   let component: MyAwesomeLibComponent;\n    |                ^\n  7 |   let fixture: ComponentFixture<MyAwesomeLibComponent>;\n  8 | \n  9 |   beforeEach(async(() => {\n',
     '2019-12-09T04:13:11.335Z workers [l9s4z] Sandbox is responsive, closing it\n',
     '2019-12-09T04:13:11.335Z workers Failed to map the stack to user code, entry message: Jest encountered an unexpected token\n\nThis usually means that you are trying to import a file which Jest cannot parse, e.g. it\'s not plain JavaScript.\n\nBy default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".\n\nHere\'s what you can do:\n • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.\n • If you need a custom transformation specify a "transform" option in your config.\n • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.\n\nYou\'ll find more details and examples of these config options in the docs:\nhttps://jestjs.io/docs/en/configuration.html\n\nDetails:\n\nSyntaxError: C:\\Users\\kplates\\Desktop\\my-awesome-app\\projects\\my-awesome-lib\\src\\lib\\my-awesome-lib.service.spec.ts: Unexpected token (9:17)\n\n   7 | \n   8 |   it(\'should be created\', () => {\n>  9 |     const service: MyAwesomeLibService = TestBed.get(MyAweso, stack: Jest encountered an unexpected token\n\nThis usually means that you are trying to import a file which Jest cannot parse, e.g. it\'s not plain JavaScript.\n\nBy default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".\n\nHere\'s what you can do:\n • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.\n • If you need a custom transformation specify a "transform" option in your config.\n • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.\n\nYou\'ll find more details and examples of these config options in the docs:\nhttps://jestjs.io/docs/en/configuration.html\n\nDetails:\n\nSyntaxError: C:\\Users\\kplates\\Desktop\\my-awesome-app\\projects\\my-awesome-lib\\src\\lib\\my-awesome-lib.service.spec.ts: Unexpected token (9:17)\n\n   7 | \n   8 |   it(\'should be created\', () => {\n>  9 |     const service: MyAwesomeLibService = TestBed.get(MyAweso\n',
     '2019-12-09T04:13:11.345Z workers [mo8qs] Run 0 test(s), skipped 0 test(s)\n',
     '2019-12-09T04:13:11.351Z workers [mo8qs] Sandbox is responsive, closing it\n',
     '2019-12-09T04:13:11.352Z workers Failed to map the stack to user code, entry message: SyntaxError: C:\\Users\\kplates\\Desktop\\my-awesome-app\\projects\\my-awesome-lib\\src\\lib\\my-awesome-lib.component.spec.ts: Unexpected token, expected ";" (6:15)\n\n  4 | \n  5 | describe(\'MyAwesomeLibComponent\', () => {\n> 6 |   let component: MyAwesomeLibComponent;\n    |                ^\n  7 |   let fixture: ComponentFixture<MyAwesomeLibComponent>;\n  8 | \n  9 |   beforeEach(async(() => {, stack: SyntaxError: C:\\Users\\kplates\\Desktop\\my-awesome-app\\projects\\my-awesome-lib\\src\\lib\\my-awesome-lib.component.spec.ts: Unexpected token, expected ";" (6:15)\n\n  4 | \n  5 | describe(\'MyAwesomeLibComponent\', () => {\n> 6 |   let component: MyAwesomeLibComponent;\n    |                ^\n  7 |   let fixture: ComponentFixture<MyAwesomeLibComponent>;\n  8 | \n  9 |   beforeEach(async(() => {\n    at Parser.raise (C:\\Users\\kplates\\Desktop\\my-awesome-app\\node_modules\\@babel\\parser\\src\\parser\\location.js:41:63)\n    at Parser.raise [as unexpected] (C:\\Users\\kplates\\Desktop\\my-awesome-app\\node_modules\\@babel\\parser\\src\\parser\\util.js:160:16)\n    at Parser.unexpected [as semicolon] (C:\\Users\\kplates\\Desktop\\my-awesome-app\\node_modules\\@babel\\parser\\src\\parser\\util.js:133:40)\n    at Parser.semicolon [as parseVarStatement] (C:\\Users\\kplates\\Desktop\\my-awesome-app\\node_modules\\@babel\\parser\\src\\parser\\statement.js:698:10)\n    at Parser.parseVarStatement [as parseStatementContent] (C:\\Users\\kplates\\Desktop\\\n',
     '2019-12-09T04:13:11.352Z workers Merging parallel test run results\n',
     '2019-12-09T04:13:11.352Z project Test run finished\n',
     '2019-12-09T04:13:11.352Z project Processed console.log entries\n',
     '2019-12-09T04:13:11.352Z project Processed loading sequences\n',
     '2019-12-09T04:13:11.352Z project Processed executed tests\n',
     '2019-12-09T04:13:11.353Z project Processed code coverage\n',
     '2019-12-09T04:13:11.357Z project Test run result processed and sent to IDE\n' ] }
```
```

**Comment by ArtemGovorov** [comment]
It looks like Jest transforms are not applied for some reason for the library code when running from Wallaby. We have tested Wallaby with Jest for Angular Libs  when Jest is configured like [described in this article](https://timdeschryver.dev/posts/integrate-jest-into-an-angular-application-and-library). Please take a look to see how your setup is different. 

> I can seem to run jest on its own via the package.json npm scripts just fine.

Can you please the command you are using to run your lib tests and also share your Jest config?

**Comment by kplates** [comment]
Ah I forgot to link. https://github.com/kplates/jest-wallaby

This looks very familiar to the tutorial I followed. I will double check everything.

**Comment by kplates** [comment]
`"jest": {
     "preset": "jest-preset-angular",
     "setupTestFrameworkScriptFile": "<rootDir>/setupJest.ts"
},`

Issue resolved by adding the above into the package.json.

**Comment by NikGovorov** [comment]
Awesome, thanks for the update.

**Comment by NikGovorov** [comment]
You could also rename `jest.base.config.js` to `jest.config.js`.
