### ISSUE TITLE
Error with vue-cli 4 (typescript, babel, jest)

### ISSUE THREAD

**Issue by sp33dlink** [wallabyjs/public#2289]
Notice: Might be a very similar issue to #2246
I created a new project with vue cli 4.1.1 and checked the options typescript, babel, jest.
Wallaby fails to run the default test with following message:
`[Error] Runtime error: Error: Cannot find module 'core-js/modules/es.symbol.description' from 'jasmineInitializer.js' `

I am using the automatic configuration and had no issues on a cli-generated project with v3.

Really appreciate tool and support from the devs here. Keep up the great work 👍 ❤️ 

### Project folder without node_modules
[vue-ts-201912.zip](https://github.com/wallabyjs/public/files/3940628/vue-ts-201912.zip)

### Wallaby diagnostics report

```
{ editorVersion: '1.40.2',
  pluginVersion: '1.0.158',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.16299',
  nodeVersion: 'v10.15.3',
  coreVersion: '1.0.787',
  config:
   { diagnostics: {},
     testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
     filesWithCoverageCalculated: [],
     micromatch: true,
     files:
      [ { pattern: '\\\\node_modules\\\\', regexp: /\\node_modules\\/, ignore: true, trigger: true, load: true },
        { pattern: 'dist\\\\|build\\\\|coverage\\\\|\\\\\\.idea\\\\|\\\\\\.vscode\\\\|\\\\\\.git\\\\|\\\\\\.gitlab\\\\',
          regexp: /dist\\|build\\|coverage\\|\\\.idea\\|\\\.vscode\\|\\\.git\\|\\\.gitlab\\/,
          ignore: true,
          trigger: true,
          load: true },
        { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
        { pattern: '**/tests/unit/**/*.spec.[jt]s?(x)', ignore: true, trigger: true, load: true },
        { pattern: '**/__tests__/*.[jt]s?(x)', ignore: true, trigger: true, load: true } ],
     tests:
      [ { pattern: '\\\\node_modules\\\\', regexp: /\\node_modules\\/, ignore: true, trigger: true, load: true, test: true },
        { pattern: 'dist\\\\|build\\\\|coverage\\\\|\\\\\\.idea\\\\|\\\\\\.vscode\\\\|\\\\\\.git\\\\|\\\\\\.gitlab\\\\',
          regexp: /dist\\|build\\|coverage\\|\\\.idea\\|\\\.vscode\\|\\\.git\\|\\\.gitlab\\/,
          ignore: true,
          trigger: true,
          load: true,
          test: true },
        { pattern: '**/tests/unit/**/*.spec.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
        { pattern: '**/__tests__/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 } ],
     filesWithNoCoverageCalculated: [],
     runAllTestsInAffectedTestFile: false,
     compilers: {},
     preprocessors: {},
     maxConsoleMessagesPerTest: 100,
     autoConsoleLog: true,
     delays: { run: 0, edit: 100, update: 0 },
     workers: { initial: 0, regular: 0, recycle: false },
     teardown: undefined,
     hints:
      { ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
        ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
        commentAutoLog: '?',
        testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' } },
     automaticTestFileSelection: true,
     runSelectedTestsOnly: false,
     extensions: {},
     env:
      { type: 'node',
        params: {},
        runner: 'C:\\Users\\REPLACED\\AppData\\Local\\Programs\\node-v10.15.3-win-x64\\node.exe',
        viewportSize: { width: 800, height: 600 },
        options: { width: 800, height: 600 },
        bundle: true },
     reportUnhandledPromises: true,
     slowTestThreshold: 75,
     lowCoverageThreshold: 80,
     loose: true,
     configCode: 'auto.detect#302369812' },
  packageJSON:
   { dependencies: { 'core-js': '^3.4.3', vue: '^2.6.10', 'vue-class-component': '^7.0.2', 'vue-property-decorator': '^8.3.0', 'vue-router': '^3.1.3', vuex: '^3.1.2' },
     devDependencies:
      { '@types/jest': '^24.0.19',
        '@vue/cli-plugin-babel': '^4.1.0',
        '@vue/cli-plugin-eslint': '^4.1.0',
        '@vue/cli-plugin-router': '^4.1.0',
        '@vue/cli-plugin-typescript': '^4.1.0',
        '@vue/cli-plugin-unit-jest': '^4.1.0',
        '@vue/cli-plugin-vuex': '^4.1.0',
        '@vue/cli-service': '^4.1.0',
        '@vue/eslint-config-standard': '^4.0.0',
        '@vue/eslint-config-typescript': '^4.0.0',
        '@vue/test-utils': '1.0.0-beta.29',
        eslint: '^5.16.0',
        'eslint-plugin-vue': '^5.0.0',
        typescript: '~3.5.3',
        'vue-template-compiler': '^2.6.10' } },
  fs: { numberOfFiles: 23 },
  debug:
   [ '2019-12-09T15:59:42.575Z config Detected Jest.\n',
     '2019-12-09T15:59:42.576Z config Configured Jest.\n',
     '2019-12-09T15:59:42.579Z project Wallaby Node version: v10.15.3\n',
     '2019-12-09T15:59:42.579Z project Wallaby config: C:\\Users\\REPLACED\\Documents\\vue-ts-201912\\auto.detect\n',
     '2019-12-09T15:59:43.894Z project File cache: C:\\Users\\REPLACED\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.158\\projects\\220dfca1f6aeaecc\n',
     '2019-12-09T15:59:43.981Z uiService Listening port 51236\n',
     '2019-12-09T15:59:44.010Z project package.json file change detected, invalidating local cache\n',
     '2019-12-09T15:59:44.027Z workers Parallelism for initial run: 2, for regular run: 2\n',
     '2019-12-09T15:59:44.027Z workers Starting run worker instance #0\n',
     '2019-12-09T15:59:44.027Z workers Starting run worker instance #1\n',
     '2019-12-09T15:59:44.029Z workers Web server is listening at 63704\n',
     '2019-12-09T15:59:44.029Z project File cache requires some updates, waiting required files from IDE\n',
     '2019-12-09T15:59:44.072Z project Stopping process pool\n',
     '2019-12-09T15:59:44.075Z project Test run started; run priority: 3\n',
     '2019-12-09T15:59:44.076Z project Running all tests\n',
     '2019-12-09T15:59:44.078Z workers Starting test run, priority: 3\n',
     '2019-12-09T15:59:44.078Z nodeRunner Starting sandbox [worker #0, session #8v3qp]\n',
     '2019-12-09T15:59:44.078Z nodeRunner Preparing sandbox [worker #0, session #8v3qp]\n',
     '2019-12-09T15:59:45.046Z workers Started run worker instance (delayed) #0\n',
     '2019-12-09T15:59:45.047Z nodeRunner Prepared sandbox [worker #0, session #8v3qp]\n',
     '2019-12-09T15:59:45.047Z workers [worker #0, session #8v3qp] Running tests in sandbox\n',
     '2019-12-09T15:59:45.054Z workers Started run worker instance (delayed) #1\n',
     '2019-12-09T15:59:51.171Z workers Sandbox (active) [8v3qp] error: Error: Cannot find module \'core-js/modules/es.symbol.description\' from \'jasmineInitializer.js\'\n',
     '2019-12-09T15:59:51.201Z workers [8v3qp] Run 0 test(s), skipped 0 test(s)\n',
     '2019-12-09T15:59:51.208Z workers [8v3qp] Sandbox is responsive, closing it\n',
     '2019-12-09T15:59:51.210Z workers Failed to map the stack to user code, entry message: Error: Cannot find module \'core-js/modules/es.symbol.description\' from \'jasmineInitializer.js\', stack: Error: Cannot find module \'core-js/modules/es.symbol.description\' from \'jasmineInitializer.js\'\n    at Resolver.resolveModule (C:\\Users\\REPLACED\\Documents\\vue-ts-201912\\node_modules\\jest-resolve\\build\\index.js:259:17)\n    at Resolver._getVirtualMockPath (C:\\Users\\REPLACED\\Documents\\vue-ts-201912\\node_modules\\jest-resolve\\build\\index.js:390:14)\n    at Resolver._getAbsolutePath (C:\\Users\\REPLACED\\Documents\\vue-ts-201912\\node_modules\\jest-resolve\\build\\index.js:376:14)\n    at Resolver.getModuleID (C:\\Users\\REPLACED\\Documents\\vue-ts-201912\\node_modules\\jest-resolve\\build\\index.js:348:31)\n    at Runtime._shouldMock (C:\\Users\\REPLACED\\Documents\\vue-ts-201912\\node_modules\\jest-runtime\\build\\index.js:942:37)\n    at Runtime.requireModuleOrMock (C:\\Users\\REPLACED\\Documents\\vue-ts-201912\\node_modules\\jest-runtime\\build\\index.js:595:16)\n    at Object.<anonymous> (c:\\Users\\REPLACED\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.158\\wallaby\\runners\\node\\jest@24.8.0\\jasmineInitializer.js:1:28)\n    at Runtime._execModule (C:\\Users\\\n',
     '2019-12-09T15:59:51.210Z project Test run finished\n',
     '2019-12-09T15:59:51.211Z project Processed console.log entries\n',
     '2019-12-09T15:59:51.211Z project Processed loading sequences\n',
     '2019-12-09T15:59:51.211Z project Processed executed tests\n',
     '2019-12-09T15:59:51.211Z project Processed code coverage\n',
     '2019-12-09T15:59:51.215Z project Test run result processed and sent to IDE\n' ] }
```

**Comment by smcenlly** [comment]
Thanks for the sample repo. We installed npm modules using `npm install` and everything worked for us. 

![image](https://user-images.githubusercontent.com/2074089/70481299-dc328c80-1b2d-11ea-9892-ad7011cf9706.png)

Could you please try stopping Wallaby, running `npx jest --clearCache` in your project directory and then starting Wallaby again?

The only difference was that we were running on a slightly later version of core, `v1.0.793`. It looks like the version of Wallaby core that you are using is ~1 month out of date. If clearing the jest cache does not work for you, could you please try updating to the latest version of core to see if that fixes your problem? If your license has expired, you may request a [temporary trial license from our website](https://wallabyjs.com/download/#try-it-free) and revert back to your old license after you finish testing.

**Comment by sp33dlink** [comment]
`npx jest --clearCache` after deleting and reinstalling modules didn't help.

I requested the trial and tried with the new version of core with the same results:
```[Info]  Started Wallaby.js Core v1.0.796
[Error] Runtime error: Error: Cannot find module 'core-js/modules/es.symbol.description' from 'jasmineInitializer.js' ```

**Comment by smcenlly** [comment]
Can you please try cloning your repo to another directory or another computer and seeing if that works for you? We will do the same today (try on different computers).

**Comment by smcenlly** [comment]
We were unable to reproduce the problem. Outside of your project folder, can you please see if there are any `node_modules` directories between your project directory and the root of your `C:` drive? If so, it's possible that is causing a problem.

**Comment by smcenlly** [comment]
Closing this issue due to lack of response. Will re-open if/when we hear back.

**Comment by sp33dlink** [comment]
I sorted it out! It was node 10's fault. After updating to node 12 it ran beautifully.  

Now I just need to find out how to downgrade wallabyjs to the version covered by my license.

**Comment by sp33dlink** [comment]
Got it by manually downloading replacing wallaby core in the vscode wallaby extension. Firewalls suck! :D
