### ISSUE TITLE
TypeError: Cannot read property '_jasmineAdapter' of undefined 

### ISSUE THREAD

**Issue by manish-jain-1** [wallabyjs/public#2292]
Hello,

We have been having wallaby issues after we upgraded React Native from 57 to 59 and jest from 23 to 24. Here's high level package.json and wallaby errors. Automatic or manual configuration not working for [Info]  Started Wallaby.js Core v1.0.711

Any ideas?

Thank you!!

Packages.json:

 ```
  "react": "16.8.3",
        "react-native": "0.59.10",
 "devDependencies": {
        "@babel/core": "^7.4.5",
        "@babel/runtime": "^7.4.5",
        "babel-eslint": "10.0.1",
        "babel-jest": "24.9.0",
        "jest": "24.9.0",
```

 ```
"jest": {
        "setupFilesAfterEnv": [
            "<rootDir>/jest/setup.js"
        ],
        "preset": "react-native",
        "collectCoverage": true,
        "transform": {
            "\\.js$": "<rootDir>/jest/preprocessor.js"
        },
        "moduleDirectories": [
            "node_modules",
            "bower_components",
            "shared"
        ],
        "testPathIgnorePatterns": [
            "/node_modules/",
            "<rootDir>/lib/",
            "/__tests__/utils.js"
        ],
        "setupFiles": [
            "<rootDir>/jest/setup.js"
        ],
```
   

0 failing tests, 0 passing  ​Launch Coverage & Test Explorer​

```
TypeError: Cannot read property '_jasmineAdapter' of undefined 

[Error] Runtime error: TypeError: Cannot read property '_jasmineAdapter' of undefined 
[Error]     at Runtime._execModule (/Users/user/app/node_modules/jest-runtime/build/index.js:867:68) 
[Error]     at Runtime._loadModule (/Users/user/app/node_modules/jest-runtime/build/index.js:577:12) 
[Error]     at Runtime.requireModule (/Users/user/app/node_modules/jest-runtime/build/index.js:433:10) 
[Error]     at config.setupFilesAfterEnv.forEach.path (/Users/user/app/node_modules/jest/node_modules/jest-jasmine2/build/index.js:187:55) 
[Error]     at Array.forEach (<anonymous>) 
[Error]     at /Users/user/app/node_modules/jest/node_modules/jest-jasmine2/build/index.js:187:31 
[Error]     at Generator.next (<anonymous>) 
[Error]     at asyncGeneratorStep (/Users/user/app/node_modules/jest/node_modules/jest-jasmine2/build/index.js:27:24) 
[Error]     at _next (/Users/user/app/node_modules/jest/node_modules/jest-jasmine2/build/index.js:47:9) 
[Error] Runtime error: TypeError: Cannot read property '_jasmineAdapter' of undefined 
[Error]     at Runtime._execModule (/Users/user/app/node_modules/jest-runtime/build/index.js:867:68) 
[Error]     at Runtime._loadModule (/Users/user/app/node_modules/jest-runtime/build/index.js:577:12) 
[Error]     at Runtime.requireModule (/Users/user/app/node_modules/jest-runtime/build/index.js:433:10) 
[Error]     at config.setupFilesAfterEnv.forEach.path (/Users/user/app/node_modules/jest/node_modules/jest-jasmine2/build/index.js:187:55) 
[Error]     at Array.forEach (<anonymous>) 
[Error]     at /Users/user/app/node_modules/jest/node_modules/jest-jasmine2/build/index.js:187:31 
[Error]     at Generator.next (<anonymous>) 
[Error]     at asyncGeneratorStep (/Users/user/app/node_modules/jest/node_modules/jest-jasmine2/build/index.js:27:24) 
[Error]     at _next (/Users/user/app/node_modules/jest/node_modules/jest-jasmine2/build/index.js:47:9) 
```

**Comment by smcenlly** [comment]
It looks like the version of Wallaby core that you are using is ~6 months out of date. Could you please try updating to the latest version of core to see if that fixes your problem? If your license has expired, you may request a [temporary trial license from our website](https://wallabyjs.com/download/#try-it-free) and revert back to your old license after you finish testing.

**Comment by manishjain-hrbl** [comment]
Yeah, that fixed it using evaluation. I believe I have to buy a new license.

**Comment by manish-jain-1** [comment]
Yeah, that fixed it. I believe I have to buy a new license as my license is 6 months old.

**Comment by smcenlly** [comment]
We are constantly adding support for the latest version of testing libraries and frameworks. If you would like to renew and need assistance, please let us know (hello@wallabyjs.com).
