### ISSUE TITLE
Error: Cannot find module 'acorn-walk' while trying the new debugger 

### ISSUE THREAD

**Issue by vjau** [wallabyjs/public#2298]
### Issue description or question

When trying to debug a test, i get this error :
```
[Error] Failed to instrument server/processing/fecExport/actionsComptaLineExport.js 
[Error] Error: Cannot find module 'acorn-walk' 
[Error]     at Function.Module._resolveFilename (module.js:548:15) 
[Error]     at Function.Module._load (module.js:475:25) 
[Error]     at Module.require (module.js:597:17) 
[Error]     at require (internal/module.js:11:18) 
[Error]     at _combinedTickCallback (internal/process/next_tick.js:132:7) 
[Error]     at process._tickCallback (internal/process/next_tick.js:181:9) 
```

While trying to copy the wallaby diagnostic with vscode copy diagnostic report command, i don't get anything new in the clipboard.

**Comment by ArtemGovorov** [comment]
Looks like your Wallaby Core version is not up-to-date. Please run `Wallaby.js Force Core Update` command in your VS Code, and the issue should be fixed.
