### ISSUE TITLE
Can not use with eggjs framework.

### ISSUE THREAD

**Issue by duncup** [wallabyjs/public#2299]
In eggjs framework use the baseDir to load file somewhere, and wallaby use the sandbox path run the project, so eggjs can not load some file.
Any help? And i don't think change egg loader logic is a good idea.

**Comment by ArtemGovorov** [comment]
Very likely it should be possible to configure Wallaby to include the required files. However, to provide the solution we need Wallaby diagnostics report to better understand the issue. To share the report:

- start Wallaby in your project;
- wait until it reports some results or errors (finishes running tests);
- run `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

**Comment by duncup** [comment]
This is my config
```
'use strict';

module.exports = function() {
  return {
    files: [
      '+(app|config|lib|logs|mist|run|scripts)/**/*.+(js|json)',
      '*',
    ],

    tests: [
      'test/binance/**/*.test.js', // adjust if required
    ],

    require: [
      'co-mocha',
    ],

    env: {
      type: 'node',
      params: {
        env: 'NODE_ENV=test;',
      },
    },

    workers: {
      restart: true,
    },

    setup(w) {
      const mocha = w.testFramework;
      mocha.timeout(60000);
    },

    trace: true,
  };
};
```
One of the error list.
```
Runtime error: Error: egg is not found in ./node_modules
    at assertAndReturn (./node_modules/egg-utils/lib/framework.js:67:9)
    at Object.getFrameworkPath (./node_modules/egg-utils/lib/framework.js:49:10)
    at formatOptions (./node_modules/egg-mock/lib/format_options.js:38:23)
    at Function.module.exports [as app] (./node_modules/egg-mock/lib/app.js:173:13)
    at Object.<anonymous> (./node_modules/egg-mock/bootstrap.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (./test/binance/service/binance.test.js:3:43)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at ./node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (./node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (./node_modules/mocha/lib/mocha.js:809:10)
    at WebSocket.emit (events.js:210:5)
    at afterWrite (_stream_writable.js:501:3)
    at onwrite (_stream_writable.js:488:7)
    at InflateRaw.afterTransform (_stream_transform.js:96:3)
    at Zlib.processCallback (zlib.js:571:8)
```

**Comment by duncup** [comment]
Or you guys just create one eggjs project maybe quickly.

**Comment by smcenlly** [comment]
We followed [the quickstart guide on the egg.js.org website](https://eggjs.org/en/intro/quickstart.html#the-quick-way) using `npm init egg --type=simple`. A working configuration file is shown below. Besides the changes to `files` / `tests` sections of the configuration, the important part to get egg.js working was adding `process.env.EGG_BASE_DIR = w.localProjectDir;` in the setup function.

**wallaby.js**
```javascript
'use strict';

module.exports = function() {
  
  return {
    files: [
      'package.json',
      'app/**/*.js',
      'config/**/*.js'
    ],

    tests: [
      'test/**/*.test.js',
    ],

    require: [
      'co-mocha',
    ],

    env: {
      type: 'node'
    },

    workers: {
      restart: true,
    },

    setup(w) {
      process.env.EGG_BASE_DIR = w.localProjectDir;
      const mocha = w.testFramework;
      mocha.timeout(60000);
    },

    trace: true,
  };
};
```

**Comment by duncup** [comment]
Very thanks.

**Comment by duncup** [comment]
@smcenlly I try this config, it work. But no test coverage. Any help?

**Comment by duncup** [comment]
```
{
  editorVersion: 'WebStorm 2019.3.1',
  pluginVersion: '1.0.146',
  editorType: 'IntelliJ',
  osVersion: 'darwin 19.2.0',
  nodeVersion: 'v12.13.0',
  coreVersion: '1.0.806',
  config: {
    files: [
      { pattern: 'package.json', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: 'app/**/*.js', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: 'config/**/*.js', ignore: false, trigger: true, load: true, instrument: true, order: 3 }
    ],
    tests: [ { pattern: 'test/**/*.test.js', ignore: false, trigger: true, load: true, test: true, order: 4 } ],
    require: [ 'co-mocha' ],
    env: { type: 'node', params: {}, runner: '/usr/local/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    workers: { restart: true, initial: 0, regular: 0, recycle: true },
    trace: true,
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    compilers: { '**/*.?(lit)coffee?(.md)': [Function] },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: true,
    testFramework: { version: 'mocha@2.1.0', configurator: 'mocha@2.1.0', reporter: 'mocha@2.1.0', starter: 'mocha@2.1.0' },
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: undefined,
    configCode: "'use strict';\n" +
      '\n' +
      'module.exports = function() {\n' +
      '\n' +
      '  return {\n' +
      '    files: [\n' +
      "      'package.json',\n" +
      "      'app/**/*.js',\n" +
      "      'config/**/*.js',\n" +
      '    ],\n' +
      '\n' +
      '    tests: [\n' +
      "      'test/**/*.test.js',\n" +
      '    ],\n' +
      '\n' +
      '    require: [\n' +
      "      'co-mocha',\n" +
      '    ],\n' +
      '\n' +
      '    env: {\n' +
      "      type: 'node',\n" +
      '    },\n' +
      '\n' +
      '    workers: {\n' +
      '      restart: true,\n' +
      '    },\n' +
      '\n' +
      '    setup(w) {\n' +
      '      process.env.EGG_BASE_DIR = w.localProjectDir;\n' +
      '      const mocha = w.testFramework;\n' +
      '      mocha.timeout(60000);\n' +
      '    },\n' +
      '\n' +
      '    trace: true,\n' +
      '  };\n' +
      '};\n'
  },
  packageJSON: {
    dependencies: { egg: '^2.15.1', 'egg-scripts': '^2.11.0' },
    devDependencies: { autod: '^3.0.1', 'autod-egg': '^1.1.0', 'egg-bin': '^4.11.0', 'egg-ci': '^1.11.0', 'egg-mock': '^3.21.0', eslint: '^5.13.0', 'eslint-config-egg': '^7.1.0' }
  },
  fs: { numberOfFiles: 6 },
  debug: [
    '2019-12-26T07:25:03.078Z project Wallaby Node version: v12.13.0\n',
    '2019-12-26T07:25:03.093Z project Wallaby config: <homeDir>/****/wallaby.js\n',
    '2019-12-26T07:25:03.869Z project File cache: <homeDir>/Library/Caches/WebStorm2019.3/wallaby/projects/7bd81f1e0ad633a2\n',
    '2019-12-26T07:25:03.891Z uiService Listening port 51235\n',
    '2019-12-26T07:25:03.896Z project Config file change detected, invalidating local cache\n',
    '2019-12-26T07:25:03.924Z workers Parallelism for initial run: 2, for regular run: 2\n',
    '2019-12-26T07:25:03.925Z workers Starting run worker instance #0\n',
    '2019-12-26T07:25:03.926Z workers Starting run worker instance #1\n',
    '2019-12-26T07:25:03.927Z workers Web server is listening at 63052\n',
    '2019-12-26T07:25:03.927Z project File cache requires some updates, waiting required files from IDE\n',
    '2019-12-26T07:25:06.442Z project Stopping process pool\n',
    '2019-12-26T07:25:06.448Z project Running postprocessor\n',
    '2019-12-26T07:25:06.452Z postprocessor New TypeScript language service is required\n',
    "2019-12-26T07:25:06.452Z postprocessor TypeScript postprocessor will be removed because in 6 project files none were found by patterns: [ '**/*.ts?(x)' ]\n",
    '2019-12-26T07:25:06.455Z project Postprocessor execution finished\n',
    '2019-12-26T07:25:06.455Z project Postprocessor is removed as requested by itself\n',
    '2019-12-26T07:25:06.456Z project Test run started; run priority: 3\n',
    '2019-12-26T07:25:06.456Z project Running all tests\n',
    '2019-12-26T07:25:06.457Z workers Starting test run, priority: 3\n',
    '2019-12-26T07:25:06.457Z nodeRunner Starting sandbox [worker #0, session #4v9hw]\n',
    '2019-12-26T07:25:06.457Z nodeRunner Preparing sandbox [worker #0, session #4v9hw]\n',
    '2019-12-26T07:25:06.599Z workers Started run worker instance (delayed) #0\n',
    '2019-12-26T07:25:06.600Z nodeRunner Prepared sandbox [worker #0, session #4v9hw]\n',
    '2019-12-26T07:25:06.601Z workers [worker #0, session #4v9hw] Running tests in sandbox\n',
    '2019-12-26T07:25:06.991Z workers Started run worker instance (delayed) #1\n',
    '2019-12-26T07:25:08.641Z workers [4v9hw] Loaded 2 test(s)\n',
    '2019-12-26T07:25:10.447Z workers [4v9hw] Test executed: should assert\n',
    '2019-12-26T07:25:10.519Z workers [4v9hw] Test executed: should GET /\n',
    '2019-12-26T07:25:10.614Z workers [4v9hw] Run 2 test(s), skipped 0 test(s)\n',
    '2019-12-26T07:25:10.656Z workers [4v9hw] Sandbox is responsive, closing it\n',
    '2019-12-26T07:25:10.657Z workers Starting run worker instance #0\n',
    '2019-12-26T07:25:10.662Z project Test run finished\n',
    '2019-12-26T07:25:10.663Z project Processed console.log entries\n',
    '2019-12-26T07:25:10.663Z project Processed loading sequences\n',
    '2019-12-26T07:25:10.671Z project Processed executed tests\n',
    '2019-12-26T07:25:10.674Z project Processed code coverage\n',
    '2019-12-26T07:25:10.696Z project Test run result processed and sent to IDE\n',
    '2019-12-26T07:25:11.578Z uiService UI client connected\n',
    '2019-12-26T07:25:11.578Z uiService Outgoing message ui:handshake\n',
    '2019-12-26T07:25:11.593Z uiService Incoming message ui:start\n',
    '2019-12-26T07:25:11.594Z uiService Outgoing message ui:summary\n',
    '2019-12-26T07:25:11.594Z uiService Outgoing message ui:files\n',
    '2019-12-26T07:25:11.602Z uiService Incoming message ui:closedInEditor\n',
    '2019-12-26T07:25:11.603Z uiService Incoming message ui:codeRequested\n',
    '2019-12-26T07:25:11.604Z uiService Outgoing message ui:code\n',
    '2019-12-26T07:25:11.615Z workers Started run worker instance (delayed) #0\n',
    '2019-12-26T07:25:11.682Z uiService Incoming message ui:openedInEditor\n',
    '2019-12-26T07:26:23.359Z uiService UI client disconnected\n',
    '2019-12-26T07:26:28.769Z uiService UI client connected\n',
    '2019-12-26T07:26:28.769Z uiService Outgoing message ui:handshake\n',
    '2019-12-26T07:26:28.868Z uiService Incoming message ui:start\n',
    '2019-12-26T07:26:28.868Z uiService Outgoing message ui:summary\n',
    '2019-12-26T07:26:28.869Z uiService Outgoing message ui:files\n',
    '2019-12-26T07:26:28.872Z uiService Incoming message ui:tests:resultsRequested\n',
    '2019-12-26T07:26:28.874Z uiService Outgoing message ui:tests:allResultsUpdated\n',
    '2019-12-26T07:26:31.584Z uiService Incoming message ui:tests:resultsAbandoned\n',
    '2019-12-26T07:26:31.650Z uiService Incoming message ui:codeRequested\n',
    '2019-12-26T07:26:31.651Z uiService Outgoing message ui:code\n',
    '2019-12-26T07:26:31.976Z uiService Incoming message ui:openedInEditor\n',
    '2019-12-26T07:26:33.352Z uiService Incoming message ui:closedInEditor\n',
    '2019-12-26T07:26:36.242Z uiService Incoming message ui:codeRequested\n',
    '2019-12-26T07:26:36.242Z uiService Outgoing message ui:code\n',
    '2019-12-26T07:26:36.248Z uiService Incoming message ui:openedInEditor\n',
    '2019-12-26T07:26:38.062Z uiService Incoming message ui:closedInEditor\n',
    '2019-12-26T07:26:39.336Z uiService Incoming message ui:codeRequested\n',
    '2019-12-26T07:26:39.337Z uiService Outgoing message ui:code\n',
    '2019-12-26T07:26:39.407Z uiService Incoming message ui:openedInEditor\n',
    '2019-12-26T07:26:40.708Z uiService Incoming message ui:closedInEditor\n'
  ]
}
```

**Comment by duncup** [comment]
I think maybe all use the `localProjectDir` even the unit test file.

**Comment by duncup** [comment]
value-explorer has not work too
