### ISSUE TITLE
Unable to get ts-jest working: Cannot read property '_jasmineAdapter' of undefined

### ISSUE THREAD

**Issue by ssured** [wallabyjs/public#2308]
### Issue description or question

Today I bought a new license but I cannot get a sample repo working with TS + Jest
My almost empty repo is located at https://github.com/ssured/test-wallaby

I tried automatic mode as well, but it fails with the same error

Please help me out, thank you

```
[Info]  Started Wallaby.js Core v1.0.811
[Info]  Wallaby App (realtime reports) is available at: http://localhost:51245
[Error] Runtime error: TypeError: Cannot read property '_jasmineAdapter' of undefined 
[Error]     at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:867:68) 
[Error]     at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:577:12) 
[Error]     at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:433:10) 
[Error]     at .\node_modules\jest-jasmine2\build\index.js:187:55 
[Error]     at Array.forEach (<anonymous>) 
[Error]     at .\node_modules\jest-jasmine2\build\index.js:187:31 
[Error]     at Generator.next (<anonymous>) 
[Error]     at asyncGeneratorStep (.\node_modules\jest-jasmine2\build\index.js:27:24) 
[Info]  console.log: FAIL test/sample-usage.test.js
[Info]  console.log:   ● Test suite failed to run
[Info]      TypeError: Cannot read property '_jasmineAdapter' of undefined
```

Running `npm test` works properly.

### Wallaby diagnostics report

```
{
  editorVersion: '1.39.2',
  pluginVersion: '1.0.163',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.18362',
  nodeVersion: 'v12.13.0',
  coreVersion: '1.0.811',
  config: {
    files: [
      { pattern: 'jest.config.js', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: 'tsconfig.json', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: 'src/**/*.ts', ignore: false, trigger: true, load: true, instrument: true, order: 3 },
      { pattern: 'test/**/*.test.ts.snap', ignore: false, instrument: false, trigger: true, load: true, order: 4 },
      { pattern: 'package.json', ignore: false, instrument: false, trigger: true, load: true, order: 5 }
    ],
    tests: [ { pattern: 'test/**/*.test.ts', ignore: false, trigger: true, load: true, test: true, order: 6 } ],
    env: { type: 'node', params: {}, runner: 'C:\\Program Files\\nodejs\\node.exe', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    compilers: { '**/*.ts': [Function], '**/*.?(lit)coffee?(.md)': [Function] },
    testFramework: { version: 'jest@0.4.3', configurator: 'jest@0.4.3', reporter: 'jest@0.4.3', starter: 'jest@0.4.3' },
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    preprocessors: { 'package.json': [Function] },
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'module.exports = function(w) {\r\n' +
      '  return {\r\n' +
      "    files: ['jest.config.js', 'tsconfig.json', 'src/**/*.ts'],\r\n" +
      '\r\n' +
      "    tests: ['test/**/*.test.ts'],\r\n" +
      '\r\n' +
      '    env: {\r\n' +
      "      type: 'node',\r\n" +
      '    },\r\n' +
      '\r\n' +
      '    compilers: {\r\n' +
      "      '**/*.ts': w.compilers.typeScript({\r\n" +
      '        isolatedModules: true,\r\n' +
      "        // module: 'commonjs',\r\n" +
      '      }),\r\n' +
      '    },\r\n' +
      '\r\n' +
      "    testFramework: 'jest',\r\n" +
      '    // setup: function(wallaby) {\r\n' +
      "    //   var jestConfig = require('./jest.config.js');\r\n" +
      '    //   /* for example:\r\n' +
      '    //    * jestConfig.globals = { "__DEV__": true }; */\r\n' +
      '    //   wallaby.testFramework.configure(jestConfig);\r\n' +
      '    // },\r\n' +
      '  };\r\n' +
      '};\r\n'
  },
  packageJSON: {
    dependencies: { mobx: '^5.15.1' },
    devDependencies: { '@types/jest': '^24.0.23', eslint: '^6.8.0', 'eslint-plugin-jest': '^23.3.0', jest: '^24.9.0', prettier: '^1.19.1', 'ts-jest': '^24.3.0', typescript: '^3.7.3' }
  },
  fs: { numberOfFiles: 5 },
  debug: [
    '2020-01-09T11:22:39.729Z project Wallaby Node version: v12.13.0\n',
    '2020-01-09T11:22:39.729Z project Wallaby config: C:\\code\\mesh-graph-raw\\wallaby.js\n',
    '2020-01-09T11:22:40.426Z project File cache: C:\\Users\\sjoerdj.BOUWGROEP\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.163\\projects\\d23d8de2fdf2a791\n',
    '2020-01-09T11:22:40.495Z uiService Listening port 51236\n',
    '2020-01-09T11:22:40.522Z project Config file change detected, invalidating local cache\n',
    '2020-01-09T11:22:40.531Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2020-01-09T11:22:40.533Z workers Starting run worker instance #0\n',
    '2020-01-09T11:22:40.534Z workers Starting run worker instance #1\n',
    '2020-01-09T11:22:40.535Z workers Starting run worker instance #2\n',
    '2020-01-09T11:22:40.535Z workers Starting run worker instance #3\n',
    '2020-01-09T11:22:40.535Z workers Starting run worker instance #4\n',
    '2020-01-09T11:22:40.535Z workers Starting run worker instance #5\n',
    '2020-01-09T11:22:40.536Z workers Web server is listening at 62955\n',
    '2020-01-09T11:22:40.536Z project File cache requires some updates, waiting required files from IDE\n',
    '2020-01-09T11:22:41.879Z workers Started run worker instance (delayed) #3\n',
    '2020-01-09T11:22:41.932Z workers Started run worker instance (delayed) #1\n',
    '2020-01-09T11:22:41.940Z workers Started run worker instance (delayed) #4\n',
    '2020-01-09T11:22:41.974Z workers Started run worker instance (delayed) #5\n',
    '2020-01-09T11:22:42.003Z workers Started run worker instance (delayed) #0\n',
    '2020-01-09T11:22:42.007Z workers Started run worker instance (delayed) #2\n',
    '2020-01-09T11:22:42.343Z project Compiler did not set ranges for file [src/value.ts]\n',
    '2020-01-09T11:22:42.361Z project Stopping process pool\n',
    '2020-01-09T11:22:42.363Z project Test run started; run priority: 3\n',
    '2020-01-09T11:22:42.364Z project Running all tests\n',
    '2020-01-09T11:22:42.366Z workers Starting test run, priority: 3\n',
    '2020-01-09T11:22:42.367Z nodeRunner Starting sandbox [worker #0, session #c8x9b]\n',
    '2020-01-09T11:22:42.367Z nodeRunner Preparing sandbox [worker #0, session #c8x9b]\n',
    '2020-01-09T11:22:42.367Z nodeRunner Prepared sandbox [worker #0, session #c8x9b]\n',
    '2020-01-09T11:22:42.367Z workers [worker #0, session #c8x9b] Running tests in sandbox\n',
    "2020-01-09T11:22:44.467Z workers Sandbox (active) [c8x9b] error: TypeError: Cannot read property '_jasmineAdapter' of undefined\n",
    "2020-01-09T11:22:44.468Z workers Failed to map the stack to user code, entry message: TypeError: Cannot read property '_jasmineAdapter' of undefined, stack: TypeError: Cannot read property '_jasmineAdapter' of undefined\n" +
      '    at Object.<anonymous> (c:\\Users\\sjoerdj.BOUWGROEP\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.163\\wallaby\\runners\\node\\jest@0.4.3\\jasmine2Initializer.js:14:2737)\n' +
      '    at Runtime._execModule (C:\\code\\mesh-graph-raw\\node_modules\\jest-runtime\\build\\index.js:867:68)\n' +
      '    at Runtime._loadModule (C:\\code\\mesh-graph-raw\\node_modules\\jest-runtime\\build\\index.js:577:12)\n' +
      '    at Runtime.requireModule (C:\\code\\mesh-graph-raw\\node_modules\\jest-runtime\\build\\index.js:433:10)\n' +
      '    at Runtime.d._wallabyReplaced.c.requireModule (c:\\Users\\sjoerdj.BOUWGROEP\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.163\\wallaby\\runners\\node\\jest@0.4.3\\initializer.js:14:26121)\n' +
      '    at C:\\code\\mesh-graph-raw\\node_modules\\jest-jasmine2\\build\\index.js:187:55\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at C:\\code\\mesh-graph-raw\\node_modules\\jest-jasmine2\\build\\index.js:187:31\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at asyncGeneratorStep (C:\\code\\mesh-graph-raw\\node_modules\\jest-jasmi\n',
    '2020-01-09T11:22:44.473Z workers [c8x9b] Run 0 test(s), skipped 0 test(s)\n',
    '2020-01-09T11:22:44.476Z workers [c8x9b] Sandbox is responsive, closing it\n',
    '2020-01-09T11:22:44.477Z project Test run finished\n',
    '2020-01-09T11:22:44.477Z project Processed console.log entries\n',
    '2020-01-09T11:22:44.477Z project Processed loading sequences\n',
    '2020-01-09T11:22:44.477Z project Processed executed tests\n',
    '2020-01-09T11:22:44.477Z project Processed code coverage\n',
    '2020-01-09T11:22:44.482Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by smcenlly** [comment]
The sample repo that you provided is working for us (both with automatic configuration, and the configuration file that you provided). 

We have seen a similar problem in the past, often caused by caching issues (either for the local project, or wallaby's internal cache). Could you please perform the following steps:

1. Uninstall the Wallaby extension from VS Code
2. Close all instances of VS Code
3. Start VS Code
4. Check that all wallaby folders have been removed (`%USERPROFILE%\.vscode\extensions\wallabyjs.wallaby-vscode-*`); if not, delete them.
5. Install the Wallaby extension for VS Code
6. Clone the repo that you provided to a fresh directory
7. Start Wallaby on the fresh directory using automatic configuration (not the configuration file).

If that does not work, could you also please provide us with the Wallaby Diagnostic report for when you're using automatic configuration?

**Comment by ssured** [comment]
Well thanks for the support, it works now. Wasting 4 hours+ on a caching issue makes me pretty sad though.... Is there any way to better inform users? I searched previous issues but they all mention to update to the recent version, nothing on uninstalling - and installing the vscode plugin. Anyways thanks
