### ISSUE TITLE
Bug - Problem when using typescript ESNext + babel and optional chaining and nullish coalescing operator in the same statement

### ISSUE THREAD

**Issue by fdeslandes-wk** [wallabyjs/public#2312]
### Issue description or question

When using typescript configured with ESNext and babel as a preprocessor, the optional chaining and nullish coalescing operator features works well individually.  However, when we use both in the same expression, wallaby fails to instrument the file:

ex:
`
const val = { test2: { a: 2}};
val.test2 = undefined;

val?.test2?.a; // No error
const other = undefined ?? 2; // No error
const val1 = val?.test2?.a || 'Yep'; // No error
const val2 = val?.test2?.a ?? 'Nope'; // Syntax error

You can test with the following minimal-ish example:
[wallaby-typescript-babel.zip](https://github.com/wallabyjs/public/files/4072938/wallaby-typescript-babel.zip)

it fails with the following error:
[Error] Postprocessor run failure: Failed to instrument src/file.js 
[Error]   4 | const other = undefined ?? 2; 
[Error]   5 | const val1 = val?.test2?.a || 'Yep'; 
[Error] > 6 | const val2 = val?.test2?.a ?? 'Nope'; 
[Error]     |              ^ SyntaxError: Assigning to rvalue (6:13) 
[Error]   7 | //# sourceMappingURL=file.js.map 

`
### Wallaby diagnostics report

```
{ editorVersion: '1.41.1',
  pluginVersion: '1.0.165',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.17763',
  nodeVersion: 'v10.16.0',
  coreVersion: '1.0.816',
  config:
   { files: [ { pattern: 'src/**/*.ts', ignore: false, trigger: true, load: true, instrument: true, order: 1 } ],
     filesWithNoCoverageCalculated: [ 'node_modules/**/*' ],
     tests: [ { pattern: 'src/**/*spec.ts', ignore: false, trigger: true, load: true, test: true, order: 2 } ],
     testFramework: { version: 'mocha@3.2.0', configurator: 'mocha@2.0.1', reporter: 'mocha@2.0.1', starter: 'mocha@2.0.1' },
     compilers: { '**/*.?(lit)coffee?(.md)': [Function] },
     preprocessors: { 'src/**/*.js': [Function: src/**/*.js] },
     debug: true,
     workers: { initial: 1, regular: 1, recycle: false },
     hints:
      { ignoreCoverage: '__REGEXP /ignore coverage/',
        ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
        commentAutoLog: '?',
        testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' } },
     env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
     diagnostics: {},
     runAllTestsInAffectedTestFile: false,
     maxConsoleMessagesPerTest: 100,
     autoConsoleLog: true,
     delays: { run: 0, edit: 100, update: 0 },
     teardown: undefined,
     automaticTestFileSelection: true,
     runSelectedTestsOnly: false,
     extensions: {},
     reportUnhandledPromises: false,
     throwOnBeforeUnload: true,
     slowTestThreshold: 75,
     lowCoverageThreshold: 80,
     loose: undefined,
     configCode:
      'const babel = require(\'@babel/core\');\r\n\r\nmodule.exports = (w) => {\r\n  const babelCfg = {\r\n    sourceMap: true,\r\n    presets: [\r\n      [\'@babel/preset-env\', {\r\n        targets: {\r\n          browsers: [\'last 1 Chrome versions\'],\r\n        },\r\n        forceAllTransforms: true,\r\n        // Allow the use of native async await despite forceAllTransforms\r\n        exclude: [\'transform-regenerator\', \'transform-async-to-generator\'],\r\n      }],\r\n    ],\r\n    plugins: [\r\n      \'@babel/plugin-proposal-nullish-coalescing-operator\',\r\n      \'@babel/plugin-proposal-optional-chaining\',\r\n      \'@babel/plugin-proposal-object-rest-spread\',\r\n    ],\r\n  };\r\n\r\n\r\n  return {\r\n    files: [\r\n      \'src/**/*.ts\',\r\n    ],\r\n\r\n    filesWithNoCoverageCalculated: [\r\n      \'node_modules/**/*\',\r\n    ],\r\n\r\n    tests: [\r\n      \'src/**/*spec.ts\',\r\n    ],\r\n\r\n    testFramework: \'mocha\',\r\n\r\n    compilers: {\r\n      \'src/**/*.ts\': w.compilers.typeScript({ orderFilesByReferenceComments: true, noImplicitAny: false }),\r\n    },\r\n\r\n    preprocessors: {\r\n      /* Pre-processor is to late, since wallaby fails in instrumentalization phase*/\r\n      \'src/**/*.js\': file => babel.transform(file.content, babelCfg),\r\n    },\r\n    debug: true,\r\n    workers: {\r\n      initial: 1,\r\n      regular: 1,\r\n    },\r\n\r\n    hints: {\r\n      ignoreCoverage: /ignore coverage/,\r\n    },\r\n\r\n    env: {\r\n      kind: \'chrome\',\r\n    },\r\n  };\r\n};\r\n' },
  packageJSON:
   { dependencies:
      { '@babel/core': '^7.7.0',
        '@babel/plugin-proposal-nullish-coalescing-operator': '^7.7.0',
        '@babel/plugin-proposal-object-rest-spread': '^7.7.0',
        '@babel/plugin-proposal-optional-chaining': '^7.7.0',
        '@babel/polyfill': '^7.7.0',
        '@babel/preset-env': '^7.7.0',
        'babel-eslint': '~10.0.2',
        eslint: '~6.8.0',
        'eslint-config-airbnb-base': '~14.0.0',
        'eslint-plugin-import': '^2.14.0',
        tslint: '^5.18.0',
        'tslint-config-airbnb': '^5.11.1',
        typescript: '^3.7.4',
        typings: '^2.1.1' },
     devDependencies: undefined },
  fs: { numberOfFiles: 1 },
  debug:
   [ '2020-01-16T18:04:39.259Z project Wallaby Node version: v10.16.0\n',
     '2020-01-16T18:04:39.260Z project Wallaby config: C:\\projects\\wallaby-typescript-babel\\wallaby.js\n',
     '2020-01-16T18:04:40.094Z project File cache: C:\\Users\\frederick.deslandes\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.165\\projects\\95a399e740585e41\n',
     '2020-01-16T18:04:40.212Z uiService Listening port 51235\n',
     '2020-01-16T18:04:40.263Z project package.json file change detected, invalidating local cache\n',
     '2020-01-16T18:04:40.485Z workers Parallelism for initial run: 1, for regular run: 1\n',
     '2020-01-16T18:04:40.486Z workers Starting run worker instance #0\n',
     '2020-01-16T18:04:40.490Z workers Web server is listening at 55814\n',
     '2020-01-16T18:04:40.521Z project File cache requires some updates, waiting required files from IDE\n',
     '2020-01-16T18:04:41.795Z workers Started run worker instance (immediate) #0\n',
     '2020-01-16T18:04:43.073Z project Stopping process pool\n',
     '2020-01-16T18:04:43.079Z project Running postprocessor\n',
     '2020-01-16T18:04:43.082Z postprocessor New TypeScript language service is required\n',
     '2020-01-16T18:04:43.241Z project Error: Failed to instrument src/file.js\n  4 | const other = undefined ?? 2;\n  5 | const val1 = val?.test2?.a || \'Yep\';\n> 6 | const val2 = val?.test2?.a ?? \'Nope\';\n    |              ^ SyntaxError: Assigning to rvalue (6:13)\n  7 | //# sourceMappingURL=file.js.map\n    at Object.formatInstrumentationError (c:\\Users\\frederick.deslandes\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.165\\wallaby\\server.js:25:18962)\n    at c:\\Users\\frederick.deslandes\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.165\\wallaby\\server.js:22:18317\n    at _rejected (c:\\Users\\frederick.deslandes\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.165\\wallaby\\node_modules\\q\\q.js:864:24)\n    at c:\\Users\\frederick.deslandes\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.165\\wallaby\\node_modules\\q\\q.js:890:30\n    at Promise.when (c:\\Users\\frederick.deslandes\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.165\\wallaby\\node_modules\\q\\q.js:1142:31)\n    at Promise.promise.promiseDispatch (c:\\Users\\frederick.deslandes\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.165\\wallaby\\node_modules\\q\\q.js:808:41)\n    at c:\\Users\\frederick.deslandes\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.165\\wallaby\\node_modules\\q\\q.js:624:44\n    at runSingle (c:\\Users\\frederick.deslandes\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.165\\wallaby\\node_modules\\q\\q.js:137:13)\n    at flush (c:\\Users\\frederick.deslandes\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.165\\wallaby\\node_modules\\q\\q.js:125:13)\n    at process._tickCallback (internal/process/next_tick.js:61:11)\n',
     '2020-01-16T18:04:43.242Z project Test run finished\n',
     '2020-01-16T18:04:43.242Z project Test run data re-queued\n' ] }
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This has been fixed in the latest version of Wallaby core, v1.0.817. Wallaby will automatically update to this version for you. If you do not wish to wait for the update, you may launch the Command Palette using `Ctrl/Cmd + Shift + P`, then run the command `Wallaby.js: Force Core Update` to update immediately.
