### ISSUE TITLE
jest.mock is not being hoisted with a create-react-app TypeScript project

### ISSUE THREAD

**Issue by wescopeland** [wallabyjs/public#2317]
### Issue description or question

`jest.mock()` is not working with the official provided wallaby.js configuration for a CRA TypeScript project. It looks like it isn't being hoisted properly.

We just bought a handful of company licenses and are super excited to use Wallaby. Automated configuration was previously working, but seems to have broken... possibly due to a dependency change.

```
[Error] Postprocessor run failure: Failed to run preprocessors on src/components/App/NavBar/NavBar.test.js, ReferenceError: ./src/components/App/NavBar/NavBar.test.js: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables. 
```

### wallaby.js file
```js
module.exports = function(wallaby) {
    var path = require("path");
    process.env.NODE_ENV = "test";
    process.env.NODE_PATH +=
        path.delimiter +
        path.join(__dirname, "node_modules") +
        path.delimiter +
        path.join(__dirname, "node_modules/react-scripts/node_modules");
    require("module").Module._initPaths();

    return {
        files: [
            { pattern: "src/setupTests.ts", instrument: false },
            "src/**/*.+(ts|tsx|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)",
            "!src/**/*.test.ts?(x)"
        ],

        tests: ["src/**/*.test.ts?(x)"],

        env: {
            type: "node",
            runner: "node"
        },

        preprocessors: {
            "**/*.js?(x)": (file) =>
                require("@babel/core").transform(file.content, {
                    sourceMap: true,
                    compact: false,
                    filename: file.path,
                    presets: [require("babel-preset-jest"), "react-app"]
                })
        },

        setup: (wallaby) => {
            const jestConfig = require("react-scripts/scripts/utils/createJestConfig")((p) =>
                require.resolve("react-scripts/" + p)
            );
            Object.keys(jestConfig.transform || {}).forEach(
                (k) => ~k.indexOf("^.+\\.(js|jsx") && void delete jestConfig.transform[k]
            );
            delete jestConfig.testEnvironment;
            wallaby.testFramework.configure(jestConfig);
        },

        testFramework: "jest"
    };
};
```

### Wallaby diagnostics report

```
{
  editorVersion: '1.41.1',
  pluginVersion: '1.0.166',
  editorType: 'VSCode',
  osVersion: 'darwin 19.2.0',
  nodeVersion: 'v12.14.1',
  coreVersion: '1.0.825',
  config: {
    files: [
      { pattern: 'src/setupTests.ts', instrument: false, ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**/*.+(ts|tsx|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: 'src/**/*.test.ts?(x)', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: 'src/**/*.test.ts?(x).snap', ignore: false, instrument: false, trigger: true, load: true, order: 3 },
      { pattern: 'package.json', ignore: false, instrument: false, trigger: true, load: true, order: 4 }
    ],
    tests: [ { pattern: 'src/**/*.test.ts?(x)', ignore: false, trigger: true, load: true, test: true, order: 5 } ],
    env: { type: 'node', runner: 'node', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    preprocessors: { '**/*.js?(x)': [Function: **/*.js?(x)], 'package.json': [Function] },
    testFramework: { version: 'jest@0.4.3', configurator: 'jest@0.4.3', reporter: 'jest@0.4.3', starter: 'jest@0.4.3' },
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    compilers: { '**/*.?(lit)coffee?(.md)': [Function] },
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'module.exports = function(wallaby) {\n' +
      '    var path = require("path");\n' +
      '    process.env.NODE_ENV = "test";\n' +
      '    process.env.NODE_PATH +=\n' +
      '        path.delimiter +\n' +
      '        path.join(__dirname, "node_modules") +\n' +
      '        path.delimiter +\n' +
      '        path.join(__dirname, "node_modules/react-scripts/node_modules");\n' +
      '    require("module").Module._initPaths();\n' +
      '\n' +
      '    return {\n' +
      '        files: [\n' +
      '            { pattern: "src/setupTests.ts", instrument: false },\n' +
      '            "src/**/*.+(ts|tsx|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)",\n' +
      '            "!src/**/*.test.ts?(x)"\n' +
      '        ],\n' +
      '\n' +
      '        tests: ["src/**/*.test.ts?(x)"],\n' +
      '\n' +
      '        env: {\n' +
      '            type: "node",\n' +
      '            runner: "node"\n' +
      '        },\n' +
      '\n' +
      '        preprocessors: {\n' +
      '            "**/*.js?(x)": (file) =>\n' +
      '                require("@babel/core").transform(file.content, {\n' +
      '                    sourceMap: true,\n' +
      '                    compact: false,\n' +
      '                    filename: file.path,\n' +
      '                    presets: [require("babel-preset-jest"), "react-app"]\n' +
      '                })\n' +
      '        },\n' +
      '\n' +
      '        setup: (wallaby) => {\n' +
      '            const jestConfig = require("react-scripts/scripts/utils/createJestConfig")((p) =>\n' +
      '                require.resolve("react-scripts/" + p)\n' +
      '            );\n' +
      '            Object.keys(jestConfig.transform || {}).forEach(\n' +
      '                (k) => ~k.indexOf("^.+\\\\.(js|jsx") && void delete jestConfig.transform[k]\n' +
      '            );\n' +
      '            delete jestConfig.testEnvironment;\n' +
      '            wallaby.testFramework.configure(jestConfig);\n' +
      '        },\n' +
      '\n' +
      '        testFramework: "jest"\n' +
      '    };\n' +
      '};\n'
  },
  packageJSON: {
    dependencies: {
      '@craco/craco': '5.6.1',
      '@types/enzyme': '^3.9.3',
      '@types/enzyme-adapter-react-16': '^1.0.5',
      '@types/html-entities': '^1.2.16',
      '@types/jest': '23.3.12',
      '@types/js-cookie': '^2.2.1',
      '@types/lodash': '^4.14.123',
      '@types/node': '10.12.18',
      '@types/react': '16.9.17',
      '@types/react-dom': '16.9.4',
      '@types/react-redux': '^7.0.0',
      '@types/redux-first-router': '^2.1.3',
      '@types/redux-first-router-link': '^1.4.4',
      '@types/redux-form': '^7.5.2',
      '@types/redux-saga': '^0.10.5',
      '@types/redux-thunk': '^2.1.0',
      'gql-query-builder': '^3.1.3',
      'html-entities': '^1.2.1',
      'jest-extended': '^0.11.2',
      'js-cookie': '^2.2.0',
      'query-string': '^6.8.2',
      react: '^16.12.0',
      'react-dom': '^16.12.0',
      'react-helmet-async': '^1.0.4',
      'react-redux': '^6.0.0',
      'react-scripts': '3.0.1',
      redux: '^4.0.1',
      'redux-first-router': '^2.1.2',
      'redux-first-router-link': '^2.1.1',
      'redux-form': '^8.1.0',
      'redux-saga': '^1.0.2',
      'redux-saga-test-plan': '^4.0.0-beta.2',
      reselect: '^4.0.0',
      typescript: '3.2.2',
      'ui-design-components': '0.0.26'
    },
    devDependencies: {
      '@graphql-codegen/cli': '^1.9.1',
      '@graphql-codegen/typescript': '^1.9.1',
      'babel-preset-jest': '^25.1.0',
      'babel-preset-react-app': '^9.1.0',
      'craco-alias': '^1.0.4',
      enzyme: '^3.10.0',
      'enzyme-adapter-react-16': '^1.14.0',
      'jest-dom': '^3.1.2',
      'jest-fetch-mock': '^2.1.2',
      prettier: '1.19.1',
      'redux-devtools-extension': '^2.13.8',
      tslint: '^5.14.0',
      'tslint-config-prettier': '^1.18.0',
      'tslint-react': '^4.0.0'
    }
  },
  fs: { numberOfFiles: 267 },
  debug: [
    '2020-01-31T18:15:03.620Z project Wallaby Node version: v12.14.1\n',
    '2020-01-31T18:15:03.621Z project Wallaby config: <homeDir>/Documents/GitHub/ui-app/wallaby.js\n',
    '2020-01-31T18:15:04.416Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.166/projects/d8a12c032191e998\n',
    '2020-01-31T18:15:04.427Z uiService Listening port 51235\n',
    '2020-01-31T18:15:04.429Z project package.json file change detected, invalidating local cache\n',
    '2020-01-31T18:15:04.499Z workers Parallelism for initial run: 14, for regular run: 7\n',
    '2020-01-31T18:15:04.499Z workers Starting run worker instance #0\n',
    '2020-01-31T18:15:04.499Z workers Starting run worker instance #1\n',
    '2020-01-31T18:15:04.499Z workers Starting run worker instance #2\n',
    '2020-01-31T18:15:04.499Z workers Starting run worker instance #3\n',
    '2020-01-31T18:15:04.499Z workers Starting run worker instance #4\n',
    '2020-01-31T18:15:04.499Z workers Starting run worker instance #5\n',
    '2020-01-31T18:15:04.499Z workers Starting run worker instance #6\n',
    '2020-01-31T18:15:04.499Z workers Starting run worker instance #7\n',
    '2020-01-31T18:15:04.499Z workers Starting run worker instance #8\n',
    '2020-01-31T18:15:04.499Z workers Starting run worker instance #9\n',
    '2020-01-31T18:15:04.499Z workers Starting run worker instance #10\n',
    '2020-01-31T18:15:04.499Z workers Starting run worker instance #11\n',
    '2020-01-31T18:15:04.499Z workers Starting run worker instance #12\n',
    '2020-01-31T18:15:04.499Z workers Starting run worker instance #13\n',
    '2020-01-31T18:15:04.499Z workers Web server is listening at 52577\n',
    '2020-01-31T18:15:04.500Z project File cache requires some updates, waiting required files from IDE\n',
    '2020-01-31T18:15:05.155Z workers Started run worker instance (delayed) #2\n',
    '2020-01-31T18:15:05.166Z workers Started run worker instance (delayed) #1\n',
    '2020-01-31T18:15:05.169Z workers Started run worker instance (delayed) #0\n',
    '2020-01-31T18:15:05.170Z workers Started run worker instance (delayed) #3\n',
    '2020-01-31T18:15:05.170Z workers Started run worker instance (delayed) #4\n',
    '2020-01-31T18:15:05.170Z workers Started run worker instance (delayed) #6\n',
    '2020-01-31T18:15:05.171Z workers Started run worker instance (delayed) #5\n',
    '2020-01-31T18:15:05.171Z workers Started run worker instance (delayed) #7\n',
    '2020-01-31T18:15:05.171Z workers Started run worker instance (delayed) #8\n',
    '2020-01-31T18:15:05.171Z workers Started run worker instance (delayed) #9\n',
    '2020-01-31T18:15:05.172Z workers Started run worker instance (delayed) #10\n',
    '2020-01-31T18:15:05.172Z workers Started run worker instance (delayed) #12\n',
    '2020-01-31T18:15:05.172Z workers Started run worker instance (delayed) #11\n',
    '2020-01-31T18:15:05.186Z workers Started run worker instance (delayed) #13\n',
    '2020-01-31T18:15:05.677Z project Stopping process pool\n',
    '2020-01-31T18:15:05.713Z project Running postprocessor\n',
    '2020-01-31T18:15:05.727Z postprocessor New TypeScript language service is required\n',
    '2020-01-31T18:15:10.066Z project Re-attaching document block comment\n',
    '2020-01-31T18:15:10.068Z project Re-attaching document block comment\n',
    '2020-01-31T18:15:10.300Z project Re-attaching document block comment\n',
    '2020-01-31T18:15:17.822Z project Error: Failed to run preprocessors on src/components/App/NavBar/NavBar.test.js, ReferenceError: ./src/components/App/NavBar/NavBar.test.js: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.\n' +
      'Invalid variable access: __assign\n' +
      'Whitelisted objects: $_$tracer, $_$w, $_$w_, $_$wf, $_$wv, Array, ArrayBuffer, Atomics, BigInt, BigInt64Array, BigUint64Array, Boolean, Buffer, DataView, Date, Error, EvalError, EventEmitter, Float32Array, Float64Array, Function, GLOBAL, Generator, GeneratorFunction, Infinity, Int16Array, Int32Array, Int8Array, InternalError, Intl, JSON, Map, Math, NaN, Number, Object, Promise, Proxy, Q, RangeError, ReferenceError, Reflect, RegExp, Set, SharedArrayBuffer, String, Symbol, SyntaxError, TextDecoder, TextEncoder, TypeError, URIError, URL, URLSearchParams, Uint16Array, Uint32Array, Uint8Array, Uint8ClampedArray, WeakMap, WeakSet, WebAssembly, WorkerState, _, arguments, clearImmediate, clearInterval, clearTimeout, console, decodeURI, decodeURIComponent, encodeURI, encodeURIComponent, escape, eval, expect, global, globalThis, isFinite, isNaN, jest, logger, parseFloat, parseInt, process, queueMicrotask, require, root, setImmediate, setInterval, setTimeout, undefined, unescape.\n' +
      'Note: This is a precaution to guard against uninitialized mock variables. If it is ensured that the mock is required lazily, variable names prefixed with `mock` (case insensitive) are permitted.\n' +
      '\n' +
      "  64 | $_$w(104, 26, $_$c), jest.mock('ui-design-components', function () {\n" +
      '  65 |     var $_$c = $_$wf(104);\n' +
      "> 66 |     return $_$w(104, 27, $_$c), __assign({}, jest.requireActual('ui-design-components'), {\n" +
      '     |                                 ^\n' +
      '  67 |         AppHeader: function (props) {\n' +
      '  68 |             var $_$c = $_$wf(104);\n' +
      '  69 |             var AppLogoComponent = ($_$w(104, 28, $_$c), props.AppLogo), MainNavComponent = props.MainNavigation, SystemHubComponent = props.SystemHub;\n' +
      '    at File.buildCodeFrameError (./node_modules/@babel/core/lib/transformation/file/file.js:261:12)\n' +
      '    at NodePath.buildCodeFrameError (./node_modules/@babel/traverse/lib/path/index.js:157:21)\n' +
      '    at Object.FUNCTIONS.mock (./node_modules/babel-plugin-jest-hoist/build/index.js:135:20)\n' +
      '    at shouldHoistExpression (./node_modules/babel-plugin-jest-hoist/build/index.js:182:36)\n' +
      '    at PluginPass.ExpressionStatement (./node_modules/babel-plugin-jest-hoist/build/index.js:188:11)\n' +
      '    at newFn (./node_modules/@babel/traverse/lib/visitors.js:193:21)\n' +
      '    at NodePath._call (./node_modules/@babel/traverse/lib/path/context.js:53:20)\n' +
      '    at NodePath.call (./node_modules/@babel/traverse/lib/path/context.js:40:17)\n' +
      '    at NodePath.visit (./node_modules/@babel/traverse/lib/path/context.js:88:12)\n' +
      '    at TraversalContext.visitQueue (./node_modules/@babel/traverse/lib/context.js:118:16)\n' +
      '    at TraversalContext.visitMultiple (./node_modules/@babel/traverse/lib/context.js:85:17)\n' +
      '    at TraversalContext.visit (./node_modules/@babel/traverse/lib/context.js:144:19)\n' +
      '    at Function.traverse.node (./node_modules/@babel/traverse/lib/index.js:94:17)\n' +
      '    at NodePath.visit (./node_modules/@babel/traverse/lib/path/context.js:95:18)\n' +
      '    at TraversalContext.visitQueue (./node_modules/@babel/traverse/lib/context.js:118:16)\n' +
      '    at TraversalContext.visitSingle (./node_modules/@babel/traverse/lib/context.js:90:19)\n' +
      '    at TraversalContext.visit (./node_modules/@babel/traverse/lib/context.js:146:19)\n' +
      '    at Function.traverse.node (./node_modules/@babel/traverse/lib/index.js:94:17)\n' +
      '    at traverse (./node_modules/@babel/traverse/lib/index.js:76:12)\n' +
      '    at transformFile (./node_modules/@babel/core/lib/transformation/index.js:88:29)\n' +
      '    at runSync (./node_modules/@babel/core/lib/transformation/index.js:45:3)\n' +
      '    at transformSync (./node_modules/@babel/core/lib/transform.js:43:38)\n' +
      '    at Object.transform (./node_modules/@babel/core/lib/transform.js:22:38)\n' +
      '    at **/*.js?(x) (./wallaby.js:27:40)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:76:11)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.166/wallaby/server.js:22:20249\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:94:5)\n',
    '2020-01-31T18:15:17.823Z project Test run finished\n',
    '2020-01-31T18:15:17.823Z project Test run data re-queued\n'
  ]
}
```

**Comment by smcenlly** [comment]
**RE: Using Automatic Configuration**
On 2020-01-30, we made a change to support react-native that changed how create-react-app jest configuration is loaded, which may have been why your automatic configuration stopped working. As of today, we have further enhanced the configuration loading logic and released a new version of Wallaby core (v1.0.826) that may fix the problem for you. If Wallaby doesn't update automatically for you, you may force an update in VS Code by launching the Command Palette using Ctrl/Cmd + Shift + P, then running the command `Wallaby.js: Force Core Update`.

If you're still having problems with automatic configuration using v1.0.826, could you please provide us with your Wallaby Diagnostics Report when using automatic configuration?

**RE: Problem when using Wallaby.js Configuration File**
We were able to duplicate the problem using a create-react-app TypeScript project with the snippet below:

```typescript
import * as fs from 'fs';

jest.mock('fs', function() { 
  return {... jest.requireActual('fs') };
});
```

When Wallaby runs the TypeScript compiler targeting `es5`, TypeScript changes your code to:

```javascript
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
jest.mock('fs', function () {
    //return Object.assign({}, jest.requireActual('fs'));
    return __assign({}, jest.requireActual('fs'));
});
```

The `__assign` function name is not whitelisted for use in jest mocks, which is why your test run is failing. 

If you want to continue using a configuration file, there are two ways to fix this:
1) Use Object.assign() instead (e.g. `return Object.assign({}, jest.requireActual('fs'));`, or
2) Add a [`compilers` section](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings) to your Wallaby configuration to target `es6` instead of `es5`:

```javascript
...
      compilers: {
        '**/*.ts?(x)': wallaby.compilers.typeScript({ target: "es6" })
      },
...
```
