### ISSUE TITLE
PLS support ava 3.3.0

### ISSUE THREAD

**Issue by olegdovger** [wallabyjs/public#2336]
Please, help with this issue. I tried to run tests with runner ava@3.3.0

[ava_3_3_0-sample](https://github.com/olegdovger/ava_3_3_0-sample)

```
wallaby.js started
core v1.0.838
2020-02-11T23:17:45.373Z project Wallaby Node version: v13.8.0
2020-02-11T23:17:45.373Z project Wallaby config: C:\Users\olega\Projects\ava-sample\wallaby.js
2020-02-11T23:17:46.027Z project File cache: C:\Users\olega\.WebStorm2019.3\system\wallaby\projects\e0c9a8093ab41ca7
2020-02-11T23:17:46.086Z uiService Listening port 51236
2020-02-11T23:17:46.105Z project Config file change detected, invalidating local cache
Wallaby App (realtime reports) is available at: http://localhost:51245
2020-02-11T23:17:46.110Z workers Parallelism for initial run: 10, for regular run: 5
2020-02-11T23:17:46.111Z workers Starting run worker instance #0
2020-02-11T23:17:46.111Z workers Starting run worker instance wallabyjs/ava-sample#1
2020-02-11T23:17:46.111Z workers Starting run worker instance wallabyjs/ava-sample#2
2020-02-11T23:17:46.111Z workers Starting run worker instance wallabyjs/ava-sample#3
2020-02-11T23:17:46.111Z workers Starting run worker instance #4
2020-02-11T23:17:46.111Z workers Starting run worker instance #5
2020-02-11T23:17:46.111Z workers Starting run worker instance #6
2020-02-11T23:17:46.111Z workers Starting run worker instance #7
2020-02-11T23:17:46.111Z workers Starting run worker instance #8
2020-02-11T23:17:46.111Z workers Starting run worker instance #9
2020-02-11T23:17:46.112Z workers Web server is listening at 55180
2020-02-11T23:17:46.112Z project File cache requires some updates, waiting required files from IDE
2020-02-11T23:17:46.960Z workers Started run worker instance (delayed) #4
2020-02-11T23:17:46.961Z workers Started run worker instance (delayed) #0
2020-02-11T23:17:46.990Z workers Started run worker instance (delayed) wallabyjs/ava-sample#1
2020-02-11T23:17:47.013Z workers Started run worker instance (delayed) #5
2020-02-11T23:17:47.021Z workers Started run worker instance (delayed) wallabyjs/ava-sample#2
2020-02-11T23:17:47.024Z workers Started run worker instance (delayed) #6
2020-02-11T23:17:47.032Z workers Started run worker instance (delayed) wallabyjs/ava-sample#3
2020-02-11T23:17:47.093Z workers Started run worker instance (delayed) #7
2020-02-11T23:17:47.146Z workers Started run worker instance (delayed) #9
2020-02-11T23:17:47.147Z workers Started run worker instance (delayed) #8
2020-02-11T23:17:47.391Z project Stopping process pool
2020-02-11T23:17:47.395Z project Running postprocessor
2020-02-11T23:17:47.397Z postprocessor New TypeScript language service is required
2020-02-11T23:17:47.397Z postprocessor TypeScript postprocessor will be removed because in 2 project files none were found by patterns: [ '**/*.ts?(x)' ]
2020-02-11T23:17:47.399Z project Postprocessor execution finished
2020-02-11T23:17:47.399Z project Postprocessor is removed as requested by itself
2020-02-11T23:17:47.399Z project Test run started; run priority: 3
2020-02-11T23:17:47.399Z project Running all tests
2020-02-11T23:17:47.400Z workers Starting test run, priority: 3
2020-02-11T23:17:47.400Z nodeRunner Starting sandbox [worker #0, session #opqjf]
2020-02-11T23:17:47.400Z nodeRunner Preparing sandbox [worker #0, session #opqjf]
2020-02-11T23:17:47.400Z nodeRunner Prepared sandbox [worker #0, session #opqjf]
2020-02-11T23:17:47.400Z workers [worker #0, session #opqjf] Running tests in sandbox
2020-02-11T23:17:47.410Z workers Sandbox (active) [opqjf] error: ava node module is not found or the version is not supported, missing `npm install ava --save-dev`?
Error: Cannot find module 'ava/lib/enhance-assert'
Require stack:
- C:\Users\olega\.WebStorm2019.3\system\wallaby\wallaby\runners\node\ava@0.3.0\initializer.js
- C:\Users\olega\.WebStorm2019.3\system\wallaby\wallaby\server.js
Runtime error: ava node module is not found or the version is not supported, missing `npm install ava --save-dev`?
Error: Cannot find module 'ava/lib/enhance-assert'
Require stack:
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
2020-02-11T23:17:47.412Z workers Failed to map the stack to user code, entry message: ava node module is not found or the version is not supported, missing `npm install ava --save-dev`?
Error: Cannot find module 'ava/lib/enhance-assert'
Require stack:
- C:\Users\olega\.WebStorm2019.3\system\wallaby\wallaby\runners\node\ava@0.3.0\initializer.js
- C:\Users\olega\.WebStorm2019.3\system\wallaby\wallaby\server.js, stack: ava node module is not found or the version is not supported, missing `npm install ava --save-dev`?
Error: Cannot find module 'ava/lib/enhance-assert'
Require stack:
- C:\Users\olega\.WebStorm2019.3\system\wallaby\wallaby\runners\node\ava@0.3.0\initializer.js
- C:\Users\olega\.WebStorm2019.3\system\wallaby\wallaby\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at Module.i.require (C:\Users\olega\.WebStorm2019.3\system\wallaby\wallaby\server.js:25:29989)
    at Module.modulePrototype.require (C:\Users\olega\.WebStorm2019.3\system\wallaby\wallaby\runners\node\ava@0.3.0\initializer.js:14:1509)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\olega\.WebStorm2019.3\system\wallaby\wallaby\runners\node\ava@0.3.0\initializer.js:14:3150)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)

2020-02-11T23:17:47.512Z workers [opqjf] Run 0 test(s), skipped 0 test(s)
2020-02-11T23:17:47.514Z workers [opqjf] Sandbox is responsive, closing it
2020-02-11T23:17:47.515Z project Test run finished
2020-02-11T23:17:47.515Z project Processed console.log entries
2020-02-11T23:17:47.515Z project Processed loading sequences
2020-02-11T23:17:47.515Z project Processed executed tests
2020-02-11T23:17:47.515Z project Processed code coverage
2020-02-11T23:17:47.518Z project Test run result processed and sent to IDE
```

**Comment by smcenlly** [comment]
Thanks for reporting this issue and for creating the sample for us.

We did need to make some changes to support Ava v3.3.0. These changes are available in the latest version of Wallaby core, v1.0.839. We also updated our [ava-sample repo](https://github.com/wallabyjs/ava-sample) so that you can refer to a working example.

We took a look at your sample repo but were unable to not run your tests outside of Wallaby; it looks like there may be a few things you need to fix outside of Wallaby before Wallaby can run your tests. Please note that as per our sample, you will need to configure Wallaby to use babel as a compiler for your files. 

If you get stuck after updating and referring to our sample, please update your repo with your tests working outside of Wallaby and we'll take another look for you.
