### ISSUE TITLE
TypeScript automatic configuration not working

### ISSUE THREAD

**Issue by aarongeorge** [wallabyjs/public#2340]
It seems to be that regardless of how I configure Wallaby with this minimal test that it just won't handle the TypeScript Syntax. As soon as it hits argument types or optional chaining, I get a syntax error.

I'm sure this is due to a configuration issue on my end, but I've tried using the Automatic Configuration and configuring the wallaby.conf.js too.

Any help would be appreciated :)

Here is the zip [router.zip](https://github.com/wallabyjs/public/files/4201887/router.zip)

### Wallaby diagnostics report

```
{
  editorVersion: '1.42.1',
  pluginVersion: '1.0.172',
  editorType: 'VSCode',
  osVersion: 'darwin 19.2.0',
  nodeVersion: 'v13.8.0',
  coreVersion: '1.0.841',
  config: {
    diagnostics: {},
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    micromatch: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
      {
        pattern: 'dist/|build/|coverage/|/\\.idea/|/\\.vscode/|/\\.git/|/\\.gitlab/',
        regexp: /dist\/|build\/|coverage\/|\/\.idea\/|\/\.vscode\/|\/\.git\/|\/\.gitlab\//,
        ignore: true,
        trigger: true,
        load: true
      },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
      {
        pattern: 'dist/|build/|coverage/|/\\.idea/|/\\.vscode/|/\\.git/|/\\.gitlab/',
        regexp: /dist\/|build\/|coverage\/|\/\.idea\/|\/\.vscode\/|\/\.git\/|\/\.gitlab\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 }
    ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    env: {
      type: 'node',
      params: {},
      runner: '<homeDir>/.nvm/versions/node/v13.8.0/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#596826066'
  },
  packageJSON: { dependencies: undefined, devDependencies: { '@types/jest': '^25.1.2', jest: '^25.1.0' } },
  fs: { numberOfFiles: 8 },
  debug: [
    '2020-02-13T23:07:43.870Z config Detected Jest.\n',
    '2020-02-13T23:07:43.871Z config Configured Jest.\n',
    '2020-02-13T23:07:43.872Z project Wallaby Node version: v13.8.0\n',
    '2020-02-13T23:07:43.872Z project Wallaby config: <homeDir>/Development/router/auto.detect\n',
    '2020-02-13T23:07:44.542Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.172/projects/b73455f4f4bcb0ac\n',
    '2020-02-13T23:07:44.554Z uiService Listening port 51235\n',
    '2020-02-13T23:07:44.558Z workers Parallelism for initial run: 10, for regular run: 5\n',
    '2020-02-13T23:07:44.559Z workers Starting run worker instance #0\n',
    '2020-02-13T23:07:44.559Z workers Starting run worker instance #1\n',
    '2020-02-13T23:07:44.559Z workers Starting run worker instance #2\n',
    '2020-02-13T23:07:44.559Z workers Starting run worker instance #3\n',
    '2020-02-13T23:07:44.559Z workers Starting run worker instance #4\n',
    '2020-02-13T23:07:44.559Z workers Starting run worker instance #5\n',
    '2020-02-13T23:07:44.559Z workers Starting run worker instance #6\n',
    '2020-02-13T23:07:44.559Z workers Starting run worker instance #7\n',
    '2020-02-13T23:07:44.559Z workers Starting run worker instance #8\n',
    '2020-02-13T23:07:44.559Z workers Starting run worker instance #9\n',
    '2020-02-13T23:07:44.559Z workers Web server is listening at 51412\n',
    '2020-02-13T23:07:44.559Z project File cache requires some updates, waiting required files from IDE\n',
    '2020-02-13T23:07:44.693Z project Stopping process pool\n',
    '2020-02-13T23:07:44.695Z project Test run started; run priority: 3\n',
    '2020-02-13T23:07:44.695Z project Running all tests\n',
    '2020-02-13T23:07:44.697Z workers Starting test run, priority: 3\n',
    '2020-02-13T23:07:44.697Z nodeRunner Starting sandbox [worker #0, session #s8gjg]\n',
    '2020-02-13T23:07:44.697Z nodeRunner Preparing sandbox [worker #0, session #s8gjg]\n',
    '2020-02-13T23:07:44.733Z workers Started run worker instance (delayed) #0\n',
    '2020-02-13T23:07:44.733Z nodeRunner Prepared sandbox [worker #0, session #s8gjg]\n',
    '2020-02-13T23:07:44.733Z workers [worker #0, session #s8gjg] Running tests in sandbox\n',
    '2020-02-13T23:07:44.738Z workers Started run worker instance (delayed) #1\n',
    '2020-02-13T23:07:44.744Z workers Started run worker instance (delayed) #3\n',
    '2020-02-13T23:07:44.748Z workers Started run worker instance (delayed) #4\n',
    '2020-02-13T23:07:44.753Z workers Started run worker instance (delayed) #2\n',
    '2020-02-13T23:07:44.754Z workers Started run worker instance (delayed) #5\n',
    '2020-02-13T23:07:44.758Z workers Started run worker instance (delayed) #7\n',
    '2020-02-13T23:07:44.760Z workers Started run worker instance (delayed) #6\n',
    '2020-02-13T23:07:44.782Z workers Started run worker instance (delayed) #8\n',
    '2020-02-13T23:07:44.786Z workers Started run worker instance (delayed) #9\n',
    '2020-02-13T23:07:45.984Z workers Sandbox (active) [s8gjg] error: SyntaxError: <homeDir>/Development/router/test/router.spec.ts: Unexpected token, expected "," (3:15)\n' +
      '\n' +
      "  1 | import Router, {IRoute} from '../src/index'\n" +
      '  2 | \n' +
      '> 3 | const wait = (t: number = 1000, e: string, reject: boolean = false) => new Promise((res, rej) => setTimeout(reject ? rej : res, t, e))\n' +
      '    |                ^\n' +
      "  4 | const rootRoute = { uri: '/' }\n" +
      "  5 | const aboutRoute = { uri: '/about' }\n" +
      "  6 | const contactRoute = { uri: '/contact' }\n",
    '2020-02-13T23:07:45.988Z workers [s8gjg] Run 0 test(s), skipped 0 test(s)\n',
    '2020-02-13T23:07:45.989Z workers [s8gjg] Sandbox is responsive, closing it\n',
    '2020-02-13T23:07:45.990Z workers Failed to map the stack to user code, entry message: SyntaxError: <homeDir>/Development/router/test/router.spec.ts: Unexpected token, expected "," (3:15)\n' +
      '\n' +
      "  1 | import Router, {IRoute} from '../src/index'\n" +
      '  2 | \n' +
      '> 3 | const wait = (t: number = 1000, e: string, reject: boolean = false) => new Promise((res, rej) => setTimeout(reject ? rej : res, t, e))\n' +
      '    |                ^\n' +
      "  4 | const rootRoute = { uri: '/' }\n" +
      "  5 | const aboutRoute = { uri: '/about' }\n" +
      `  6 | const contactRoute = { uri: '/contact' }, stack: SyntaxError: <homeDir>/Development/router/test/router.spec.ts: Unexpected token, expected "," (3:15)\n` +
      '\n' +
      "  1 | import Router, {IRoute} from '../src/index'\n" +
      '  2 | \n' +
      '> 3 | const wait = (t: number = 1000, e: string, reject: boolean = false) => new Promise((res, rej) => setTimeout(reject ? rej : res, t, e))\n' +
      '    |                ^\n' +
      "  4 | const rootRoute = { uri: '/' }\n" +
      "  5 | const aboutRoute = { uri: '/about' }\n" +
      "  6 | const contactRoute = { uri: '/contact' }\n" +
      '    at Parser.raise (<homeDir>/Development/router/node_modules/@babel/parser/src/parser/location.js:41:63)\n' +
      '    at Parser.unexpected (<homeDir>/Development/router/node_modules/@babel/parser/src/parser/util.js:150:16)\n' +
      '    at Parser.expect (<homeDir>/Development/router/node_modules/@babel/parser/src/parser/util.js:130:28)\n' +
      '    at Parser.parseParenAndDistinguishExpression (<homeDir>/Development/router/node_modules/@babel/parser/src/parser/expression.js:1269:14)\n' +
      '    at Parser.parseExprAtom (<homeDir>/Development/router/n\n',
    '2020-02-13T23:07:45.990Z project Test run finished\n',
    '2020-02-13T23:07:45.991Z project Processed console.log entries\n',
    '2020-02-13T23:07:45.991Z project Processed loading sequences\n',
    '2020-02-13T23:07:45.991Z project Processed executed tests\n',
    '2020-02-13T23:07:45.991Z project Processed code coverage\n',
    '2020-02-13T23:07:45.993Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by smcenlly** [comment]
Your project has `jest` v25 installed as a dependency, so I assume that you are using jest for your testing framework?

Using `jest` v24+, you can Wallaby's [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration).

Using your project outside of Wallaby with `npx jest`, you get the same syntax errors. What you need to do is [configure jest to run your project with typescript](https://jestjs.io/docs/en/getting-started#using-typescript).

We performed the steps described in the jest configuration docs and everything is working for us in your router project.

**Steps:**
1. Delete `wallaby.conf.js`
2. Add babel dependencies: `yarn add --dev babel-jest @babel/core @babel/preset-env @babel/preset-typescript` or `npm install babel-jest @babel/core @babel/preset-env @babel/preset-typescript --save-dev`.
3. Create your babel configuration:
```javascript
// babel.config.js
module.exports = {
  presets: [
    ['@babel/preset-env', {targets: {node: 'current'}}],
     '@babel/preset-typescript',
  ],
};
```
4. In VS Code, run the command `Wallaby.js: Select Configuration` and select `Automatic Configuration: <project directory>`

Everything should now work for you.

**Comment by aarongeorge** [comment]
Absolutely the best support I've seen on a project. Thanks so much @smcenlly, that worked perfectly.

I wasn't aware that I needed to configure Babel and Jest.

If it's not already, maybe put this information in the TypeScript section of the Docs?

**Comment by smcenlly** [comment]
@aarongeorge - generally speaking, the expectation is that if you are using a testing framework, it must first be configured in order for Wallaby to run. We'll update the configuration section docs to detail this expectation to assist others in the future.
