### ISSUE TITLE
Command 'wallaby.start' not found with activaion failure on install

### ISSUE THREAD

**Issue by evilmarketer** [wallabyjs/public#2381]
### Issue description or question
Wallby just stoped working today in VS Code, but a day ago worked fine. Now when starting, I get an error `Command 'wallaby.start' not found`.

OS: Windows
Node: v12

Found the same error here: https://github.com/wallabyjs/public/issues/1123. But the solution is not suitable for me (I guess) because I don't use any proxy. 

Tried to:
- Install/uninstall extension
- Install/uninstall VScode
- Install previous version of Wallaby
- Install a different version of VScode

Then I looked at Extension install log and found next

### Log
[2020-03-31 19:45:57.082] [exthost] [error] Activating extension WallabyJs.wallaby-vscode failed due to an error:
[2020-03-31 19:45:57.083] [exthost] [error] ReferenceError: regeneratorRuntime is not defined
	at c.value (c:\Users\mail\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.187\dist\index.js:15:1149)
	at Object.t.activate (c:\Users\mail\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.187\dist\index.js:15:13001)
	at Object.t.activate (c:\Users\mail\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.187\dist\index.js:15:13501)
	at exports.activate (c:\Users\mail\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.187\index.js:12:71)
	at Function._callActivateOptional (c:\Users\mail\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:722:204)
	at Function._callActivate (c:\Users\mail\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:721:862)
	at c:\Users\mail\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:720:960
	at async Promise.all (index 0)
	at async d.$activate (c:\Users\mail\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:727:297)

Any ideas?

**Comment by NikGovorov** [comment]
Thanks for reporting the issue, version 1.0.188 fixes it.

**Comment by evilmarketer** [comment]
@NikGovorov Where can I find it? Or it will appear later?

**Comment by NikGovorov** [comment]
Try to reload VS Code if 1.0.188 does not appear in updates, please wait another 5 minutes. Thanks.
