### ISSUE TITLE
Not sure if PaperJS issue or wallaby config issue...

### ISSUE THREAD

**Issue by whyld4900** [wallabyjs/public#2383]
Howdy!

### Issue description or question
I created issue over here = https://github.com/paperjs/paper.js/issues/1792
If the PaperJS people add that check then wallaby works fine.
Or is there something I could do different with WallabyJS config/setup to make it work with no changes to PaperJS?

Thanks!

### Wallaby diagnostics report

```
{
  editorVersion: '1.43.2',
  pluginVersion: '1.0.190',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.17763',
  nodeVersion: 'v12.16.1',
  coreVersion: '1.0.874',
  config: {
    files: [
      { pattern: 'test/utils/index.js', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: 'test/**/*.svg', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: 'lib/**/*.js', ignore: false, trigger: true, load: true, instrument: true, order: 3 }
    ],
    tests: [ { pattern: 'test/**/*test.js', ignore: false, trigger: true, load: true, test: true, order: 4 } ],
    testFramework: { version: 'mocha@2.1.0', configurator: 'mocha@2.1.0', reporter: 'mocha@2.1.0', starter: 'mocha@2.1.0' },
    debug: true,
    compilers: { '**/*.js': [Function], '**/*.?(lit)coffee?(.md)': [Function] },
    env: { type: 'node', params: {}, runner: 'C:\\Program Files\\nodejs\\node.exe', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: undefined,
    configCode: '\n' +
      'module.exports = function(wallaby0) {\n' +
      '\n' +
      '    const compiler = wallaby0.compilers.babel();\n' +
      '\n' +
      '    return {\n' +
      '        files: [\n' +
      "            'test/utils/index.js',\n" +
      "            'test/**/*.svg',\n" +
      "            'lib/**/*.js',\n" +
      '        ],\n' +
      '\n' +
      "        tests: ['test/**/*test.js'],\n" +
      '\n' +
      "        testFramework: 'mocha',\n" +
      '\n' +
      '        debug: true,\n' +
      '\n' +
      '        compilers: {\n' +
      "            '**/*.js': compiler,\n" +
      '        },\n' +
      '\n' +
      '        env: {\n' +
      "            type: 'node',\n" +
      '        },\n' +
      '\n' +
      '        setup: function() {\n' +
      "            const paper = require('paper/dist/paper-core');\n" +
      "            const chai = require('chai');\n" +
      "            chai.use(require('sinon-chai'));\n" +
      '           \n' +
      "            global.expect = require('chai').expect;\n" +
      "            global.sinon = require('sinon');     \n" +
      '\n' +
      '            paper.setup([100, 100]);            \n' +
      '\n' +
      '        },\n' +
      '    };\n' +
      '};\n'
  },
  packageJSON: {
    dependencies: { '@hapi/joi': '^16.1.8', lodash: '^4.17.15', paper: '^0.12.4', quadrekt: '^1.0.0', 'xml-formatter': '^1.2.0', xml2js: '^0.4.22' },
    devDependencies: {
      '@babel/core': '^7.7.7',
      '@babel/preset-env': '^7.7.7',
      '@babel/register': '^7.7.7',
      '@rollup/plugin-alias': '^3.0.0',
      '@rollup/plugin-commonjs': '^11.0.1',
      '@rollup/plugin-json': '^4.0.1',
      '@rollup/plugin-node-resolve': '^7.0.0',
      'babel-plugin-module-resolver': '^4.0.0',
      canvas: '^2.6.1',
      chai: '^4.2.0',
      chalk: '^3.0.0',
      del: '^5.1.0',
      eslint: '^6.7.1',
      'eslint-config-airbnb-base': '^14.0.0',
      'eslint-plugin-import': '^2.18.2',
      'eslint-plugin-mocha': '^6.2.2',
      'fs-extra': '^8.1.0',
      jsdom: '^15.2.1',
      mocha: '^7.0.0',
      'mocha-junit-reporter': '^1.23.3',
      nodemon: '^2.0.1',
      nyc: '^15.0.0',
      rollup: '^1.29.0',
      sinon: '^8.0.4',
      'sinon-chai': '^3.4.0'
    }
  },
  fs: { numberOfFiles: 39 },
  debug: [
    '2020-04-01T15:16:46.193Z project Wallaby Node version: v12.16.1\n',
    '2020-04-01T15:16:46.194Z project Wallaby config: C:\\_PROJECTS\\StopWatch\\private-npm-repos\\pattern-utils\\wallaby.js\n',
    '2020-04-01T15:16:47.005Z project File cache: C:\\Users\\U779006\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.190\\projects\\85e0963250b7e68d\n',
    '2020-04-01T15:16:47.139Z uiService Listening port 51235\n',
    '2020-04-01T15:16:47.188Z workers Parallelism for initial run: 2, for regular run: 2\n',
    '2020-04-01T15:16:47.188Z workers Starting run worker instance #0\n',
    '2020-04-01T15:16:47.188Z workers Starting run worker instance #1\n',
    '2020-04-01T15:16:47.196Z workers Web server is listening at 64849\n',
    '2020-04-01T15:16:47.238Z project Stopping process pool\n',
    '2020-04-01T15:16:47.239Z project File cache is up-to-date, starting full test run\n',
    '2020-04-01T15:16:47.243Z project Running postprocessor\n',
    '2020-04-01T15:16:47.251Z postprocessor New TypeScript language service is required\n',
    "2020-04-01T15:16:47.254Z postprocessor TypeScript postprocessor will be removed because in 39 project files none were found by patterns: [ '**/*.ts?(x)' ]\n",
    '2020-04-01T15:16:47.265Z project Postprocessor execution finished\n',
    '2020-04-01T15:16:47.265Z project Postprocessor is removed as requested by itself\n',
    '2020-04-01T15:16:47.266Z project Test run started; run priority: 3\n',
    '2020-04-01T15:16:47.266Z project Running all tests\n',
    '2020-04-01T15:16:47.269Z workers Starting test run, priority: 3\n',
    '2020-04-01T15:16:47.269Z workers Distributing tests between 2 workers\n',
    '2020-04-01T15:16:47.276Z workers Running tests in parallel\n',
    '2020-04-01T15:16:47.277Z nodeRunner Starting sandbox [worker #0, session #o2ovy]\n',
    '2020-04-01T15:16:47.277Z nodeRunner Starting sandbox [worker #1, session #i451x]\n',
    '2020-04-01T15:16:47.277Z nodeRunner Preparing sandbox [worker #0, session #o2ovy]\n',
    '2020-04-01T15:16:47.278Z nodeRunner Preparing sandbox [worker #1, session #i451x]\n',
    '2020-04-01T15:16:47.811Z workers Started run worker instance (delayed) #0\n',
    '2020-04-01T15:16:47.812Z nodeRunner Prepared sandbox [worker #0, session #o2ovy]\n',
    '2020-04-01T15:16:47.812Z workers [worker #0, session #o2ovy] Running tests in sandbox\n',
    '2020-04-01T15:16:47.834Z workers Started run worker instance (delayed) #1\n',
    '2020-04-01T15:16:47.835Z nodeRunner Prepared sandbox [worker #1, session #i451x]\n',
    '2020-04-01T15:16:47.835Z workers [worker #1, session #i451x] Running tests in sandbox\n',
    '2020-04-01T15:16:48.150Z workers Sandbox (active) [i451x] error: The "path" argument must be of type string. Received undefined\n',
    '2020-04-01T15:16:48.153Z workers Failed to map the stack to user code, entry message: The "path" argument must be of type string. Received undefined, stack: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined\n' +
      '    at validateString (internal/validators.js:117:11)\n' +
      '    at Object.dirname (path.js:583:5)\n' +
      '    at Object.<anonymous> (C:\\_PROJECTS\\StopWatch\\private-npm-repos\\pattern-utils\\node_modules\\paper\\dist\\node\\self.js:21:48)\n' +
      '    at Module._compile (internal/modules/cjs/loader.js:1158:30)\n' +
      '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)\n' +
      '    at Module.load (internal/modules/cjs/loader.js:1002:32)\n' +
      '    at Function.Module._load (internal/modules/cjs/loader.js:901:14)\n' +
      '    at Module.require (internal/modules/cjs/loader.js:1044:19)\n' +
      '    at Module.i.require (c:\\Users\\U779006\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.190\\wallaby\\server.js:26:4062)\n' +
      '    at Module.r.require (c:\\Users\\U779006\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.190\\wallaby\\server.js:26:2726)\n' +
      '    at Module.r.require (c:\\Users\\U779006\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.190\\wallaby\\server.js:26:2726)\n' +
      '    at requi\n',
    '2020-04-01T15:16:48.157Z workers Sandbox (active) [o2ovy] error: The "path" argument must be of type string. Received undefined\n',
    '2020-04-01T15:16:48.158Z workers Failed to map the stack to user code, entry message: The "path" argument must be of type string. Received undefined, stack: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined\n' +
      '    at validateString (internal/validators.js:117:11)\n' +
      '    at Object.dirname (path.js:583:5)\n' +
      '    at Object.<anonymous> (C:\\_PROJECTS\\StopWatch\\private-npm-repos\\pattern-utils\\node_modules\\paper\\dist\\node\\self.js:21:48)\n' +
      '    at Module._compile (internal/modules/cjs/loader.js:1158:30)\n' +
      '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)\n' +
      '    at Module.load (internal/modules/cjs/loader.js:1002:32)\n' +
      '    at Function.Module._load (internal/modules/cjs/loader.js:901:14)\n' +
      '    at Module.require (internal/modules/cjs/loader.js:1044:19)\n' +
      '    at Module.i.require (c:\\Users\\U779006\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.190\\wallaby\\server.js:26:4062)\n' +
      '    at Module.r.require (c:\\Users\\U779006\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.190\\wallaby\\server.js:26:2726)\n' +
      '    at Module.r.require (c:\\Users\\U779006\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.190\\wallaby\\server.js:26:2726)\n' +
      '    at requi\n',
    '2020-04-01T15:16:48.254Z workers [i451x] Run 0 test(s), skipped 0 test(s)\n',
    '2020-04-01T15:16:48.258Z workers [i451x] Sandbox is responsive, closing it\n',
    '2020-04-01T15:16:48.259Z workers [o2ovy] Run 0 test(s), skipped 0 test(s)\n',
    '2020-04-01T15:16:48.264Z workers [o2ovy] Sandbox is responsive, closing it\n',
    '2020-04-01T15:16:48.265Z workers Merging parallel test run results\n',
    '2020-04-01T15:16:48.265Z project Test run finished\n',
    '2020-04-01T15:16:48.266Z project Processed console.log entries\n',
    '2020-04-01T15:16:48.266Z project Processed loading sequences\n',
    '2020-04-01T15:16:48.266Z project Processed executed tests\n',
    '2020-04-01T15:16:48.277Z project Processed code coverage\n',
    '2020-04-01T15:16:48.341Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by smcenlly** [comment]
We are not familiar with `paper.js` but took a look at your configuration and the file that is throwing the error, `node_modules\paper\dist\node\self.js`.

From the paper.js [readme.md](https://github.com/paperjs/paper.js) and after reading the `self.js` code and `paper-jsdom` code, it looks like if you're using `node.js` instead of a browser environment then you need to require paper using either the `paper-jsdom` or `paper-jsdom-canvas` or package. We got everything working by installing `paper-jsdom` as a dev dependency and changing your Wallaby paper require statement to:

```javascript
...
  const paper = require('paper-jsdom');
...
```

If that's not OK for you, then it looks like you'll need to wait for the paper.js team to change their code.
