### ISSUE TITLE
Jest test not working on standard Nuxt install with vue-jest (incompatible?)

### ISSUE THREAD

**Issue by ckreutz** [wallabyjs/public#2391]
### Issue description or question
My tests work fine with Jest without Wallaby. I get the console error below when running the same test with Wallaby using the automatic configuration. I have added my package.json, Wallaby console output and Wallaby diagnostics report.  Is it maybe that the vue-jest version is incompatible? 

### package.json
```
{
  "name": "Test",
  "version": "1.0.0",
  "description": "Test App",
  "author": "me",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "test": "jest"
  },
  "dependencies": {
    "@nuxtjs/apollo": "^4.0.0-rc19",
    "graphql-tag": "^2.10.3",
    "nuxt": "^2.0.0",
    "nuxt-buefy": "^0.3.2"
  },
  "devDependencies": {
    "@vue/test-utils": "^1.0.0-beta.27",
    "babel-jest": "^24.1.0",
    "jest": "^24.1.0",
    "vue-jest": "^4.0.0-0"
  }
}
```

### Console output
```
[Info]  Started Wallaby.js Core v1.0.875
[Info]  Wallaby App (realtime reports) is available at: http://localhost:51245
[Info]  console.warn: Possibly incompatible/unsupported Jest version (vue-jest/lib/process.js)
[Info]  console.warn: Possibly incompatible/unsupported Jest version (vue-jest/lib/process.js)
[Info]  console.log: Jest: FAIL test/unit/sanity-test.spec.js
[Info]  console.log: Jest:   ● Test suite failed to run
[Info]      "version" is a required argument.
[Info]        at Object.getArg (../../../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.193/wallaby/node_modules/source-map/lib/source-map/util.js:28:13)
[Info]        at new BasicSourceMapConsumer (../../../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.193/wallaby/node_modules/source-map/lib/source-map/source-map-consumer.js:292:24)
[Info]        at new SourceMapConsumer (../../../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.193/wallaby/node_modules/source-map/lib/source-map/source-map-consumer.js:26:9)
[Info]        at ../../../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.193/wallaby/server.js:26:438
[Info]        at arrayEach (../../../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.193/wallaby/node_modules/lodash/index.js:1286:13)
[Info]        at Function.forEach (../../../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.193/wallaby/node_modules/lodash/index.js:5700:11)
[Info]        at Object.updateFileMap (../../../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.193/wallaby/server.js:26:413)
[Info]        at Object.e.process (../../../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.193/wallaby/runners/node/jest@24.8.0/initializer.js:14:19948)
[Info]        at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:453:35)
[Info]        at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:523:40)
[Info]        at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
[Info]        at Object.<anonymous> (test/unit/sanity-test.spec.js:3:58)
[Error] Runtime error: undefined 
[Info]  Diagnostics report has been successfully copied to clipboard.
```

### Wallaby diagnostics report
```
{ editorVersion: '1.44.0',
  pluginVersion: '1.0.193',
  editorType: 'VSCode',
  osVersion: 'darwin 19.3.0',
  nodeVersion: 'v10.0.0',
  coreVersion: '1.0.875',
  config: 
   { diagnostics: {},
     testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
     filesWithCoverageCalculated: [ 'components/**/*.vue', 'pages/**/*.vue' ],
     micromatch: true,
     files: 
      [ { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
        { pattern: 'dist/|build/|coverage/|/\\.cache/|/\\.idea/|/\\.vscode/|/\\.git/|/\\.gitlab/',
          regexp: /dist\/|build\/|coverage\/|\/\.cache\/|\/\.idea\/|\/\.vscode\/|\/\.git\/|\/\.gitlab\//,
          ignore: true,
          trigger: true,
          load: true },
        { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
        { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true },
        { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true } ],
     tests: 
      [ { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
        { pattern: 'dist/|build/|coverage/|/\\.cache/|/\\.idea/|/\\.vscode/|/\\.git/|/\\.gitlab/',
          regexp: /dist\/|build\/|coverage\/|\/\.cache\/|\/\.idea\/|\/\.vscode\/|\/\.git\/|\/\.gitlab\//,
          ignore: true,
          trigger: true,
          load: true,
          test: true },
        { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
        { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 } ],
     filesWithNoCoverageCalculated: [],
     runAllTestsInAffectedTestFile: false,
     compilers: {},
     preprocessors: {},
     maxConsoleMessagesPerTest: 100,
     autoConsoleLog: true,
     delays: { run: 0, edit: 100, update: 0 },
     workers: { initial: 0, regular: 0, recycle: false },
     teardown: undefined,
     hints: 
      { ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
        ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
        commentAutoLog: '?',
        testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' } },
     automaticTestFileSelection: true,
     runSelectedTestsOnly: false,
     extensions: {},
     env: { type: 'node', params: {}, runner: '<homeDir>/.nvm/versions/node/v10.0.0/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
     reportUnhandledPromises: true,
     slowTestThreshold: 75,
     lowCoverageThreshold: 80,
     loose: true,
     configCode: 'auto.detect#1026773938' },
  packageJSON: 
   { dependencies: { '@nuxtjs/apollo': '^4.0.0-rc19', 'graphql-tag': '^2.10.3', nuxt: '^2.0.0', 'nuxt-buefy': '^0.3.2' },
     devDependencies: { '@vue/test-utils': '^1.0.0-beta.27', 'babel-jest': '^24.1.0', jest: '^24.1.0', 'vue-jest': '^4.0.0-0' } },
  fs: { numberOfFiles: 66 },
  debug: 
   [ '2020-04-11T14:56:10.125Z config Detected Jest.\n',
     '2020-04-11T14:56:10.127Z config Configured Jest.\n',
     '2020-04-11T14:56:10.130Z project Wallaby Node version: v10.0.0\n',
     '2020-04-11T14:56:10.130Z project Wallaby config: <homeDir>/web/nuxt/twitter-events/auto.detect\n',
     '2020-04-11T14:56:11.277Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.193/projects/66533c9eb26318d5\n',
     '2020-04-11T14:56:11.300Z uiService Listening port 51235\n',
     '2020-04-11T14:56:11.302Z project package.json file change detected, invalidating local cache\n',
     '2020-04-11T14:56:11.314Z workers Parallelism for initial run: 2, for regular run: 2\n',
     '2020-04-11T14:56:11.314Z workers Starting run worker instance #0\n',
     '2020-04-11T14:56:11.314Z workers Starting run worker instance #1\n',
     '2020-04-11T14:56:11.317Z workers Web server is listening at 54612\n',
     '2020-04-11T14:56:11.317Z project File cache requires some updates, waiting required files from IDE\n',
     '2020-04-11T14:56:11.343Z project Stopping process pool\n',
     '2020-04-11T14:56:11.345Z project Test run started; run priority: 3\n',
     '2020-04-11T14:56:11.348Z project Running all tests\n',
     '2020-04-11T14:56:11.350Z workers Starting test run, priority: 3\n',
     '2020-04-11T14:56:11.350Z nodeRunner Starting sandbox [worker #0, session #v7wuc]\n',
     '2020-04-11T14:56:11.350Z nodeRunner Preparing sandbox [worker #0, session #v7wuc]\n',
     '2020-04-11T14:56:11.612Z workers Started run worker instance (delayed) #0\n',
     '2020-04-11T14:56:11.613Z nodeRunner Prepared sandbox [worker #0, session #v7wuc]\n',
     '2020-04-11T14:56:11.613Z workers [worker #0, session #v7wuc] Running tests in sandbox\n',
     '2020-04-11T14:56:11.619Z workers Started run worker instance (delayed) #1\n',
     '2020-04-11T14:56:17.018Z workers Sandbox (active) [v7wuc] error: undefined\n',
     '2020-04-11T14:56:17.020Z workers [v7wuc] Sandbox is responsive, closing it\n',
     '2020-04-11T14:56:17.022Z project Test run finished\n' ] }
```

**Comment by ArtemGovorov** [comment]
Thanks for sharing the details. 
What would be the best way for us to generate a repo similar to yours so we could reproduce the issue? Have you [used `create-nuxt-app`](https://nuxtjs.org/guide/installation/) or something similar?

**Comment by ckreutz** [comment]
Thanks for your quick reply. 
Yes, I used the standard way: https://nuxtjs.org/guide/installation 
`` yarn create nuxt-app ``
You should come up pretty much with the same installation I have.

**Comment by ArtemGovorov** [comment]
Thanks. Looks like NuxtJS is using vue-jest v4.0.0-beta.2, we have added support for the beta version in [the latest Wallaby core v1.0.876](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
