### ISSUE TITLE
Jest + angular + manual configuration = error

### ISSUE THREAD

**Issue by Forkiy** [wallabyjs/public#2405]
### Jest + angular + manual configuration = error

I received an error when tried to manually configure wallaby with jest and angular. In my case automatic configuration didn't work correctly (works in a few times slower and tried to start wrong tests).

Repository to reproduce: https://github.com/Forkiy/jest-angular-wallaby

Error:
```
TypeError: ..\..\..\wallaby\runners\node\jest@0.4.3\jasmine2Initializer.js: Emit skipped for language service
    at compileFn (.\node_modules\ts-jest\dist\compiler\language-service.js:109:23)
    at Object.compile (.\node_modules\ts-jest\dist\compiler\instance.js:90:25)
    at TsJestTransformer.process (.\node_modules\ts-jest\dist\ts-jest-transformer.js:85:41)
    at ScriptTransformer.transformSource (.\node_modules\@jest\transform\build\ScriptTransformer.js:479:35)
    at ScriptTransformer._transformAndBuildScript (.\node_modules\@jest\transform\build\ScriptTransformer.js:569:40)
    at ScriptTransformer.transform (.\node_modules\@jest\transform\build\ScriptTransformer.js:609:25)
    at Runtime.transformFile (.\node_modules\jest-runtime\build\index.js:1149:53)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:1065:34)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:775:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:631:10)
    at jasmine2 (.\node_modules\jest-jasmine2\build\index.js:193:15)
    at runTestInternal (.\node_modules\jest-runner\build\runTest.js:373:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
``` 

### Wallaby diagnostics report

```
{ editorVersion: 'WebStorm 2020.1',
  pluginVersion: '1.0.173',
  editorType: 'IntelliJ',
  osVersion: 'win32 10.0.19041',
  nodeVersion: 'v10.16.3',
  coreVersion: '1.0.886',
  config:
   { files:
      [ { pattern: 'packages/**/*.+(js|ts|html|json|css|peg)', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
        { pattern: 'tsconfig.spec.json', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
        { pattern: 'jest.config.js', ignore: false, trigger: true, load: true, instrument: true, order: 3 },
        { pattern: 'styleMock.js', ignore: false, trigger: true, load: true, instrument: true, order: 4 },
        { pattern: 'setupJest.ts', ignore: false, trigger: true, load: true, instrument: true, order: 5 },
        { pattern: '**/*.spec.ts', ignore: true, trigger: true, load: true, instrument: true },
        { pattern: 'packages/**/*.spec.ts.snap', ignore: false, instrument: false, trigger: true, load: true, order: 6 },
        { pattern: 'package.json', ignore: false, instrument: false, trigger: true, load: true, order: 7 } ],
     tests: [ { pattern: 'packages/**/*.spec.ts', ignore: false, trigger: true, load: true, test: true, order: 8 } ],
     env: { type: 'node', runner: 'node', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
     testFramework: { version: 'jest@0.4.3', configurator: 'jest@0.4.3', reporter: 'jest@0.4.3', starter: 'jest@0.4.3' },
     preprocessors: { '**/*.js': [Function: **/*.js], 'package.json': [Function] },
     diagnostics: {},
     filesWithNoCoverageCalculated: [],
     runAllTestsInAffectedTestFile: false,
     updateNoMoreThanOneSnapshotPerTestFileRun: false,
     compilers: { '**/*.?(lit)coffee?(.md)': [Function] },
     maxConsoleMessagesPerTest: 100,
     autoConsoleLog: true,
     delays: { run: 0, edit: 100, update: 0 },
     workers: { initial: 0, regular: 0, recycle: false },
     teardown: undefined,
     hints:
      { ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
        ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
        commentAutoLog: '?',
        testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' } },
     automaticTestFileSelection: true,
     runSelectedTestsOnly: false,
     extensions: {},
     reportUnhandledPromises: true,
     slowTestThreshold: 75,
     lowCoverageThreshold: 80,
     loose: true,
     configCode:
      'module.exports = function (wallaby) {\n    return {\n        files: [\n            \'packages/**/*.+(js|ts|html|json|css|peg)\',\n            \'tsconfig.spec.json\',\n            \'jest.config.js\',\n            \'styleMock.js\',\n            \'setupJest.ts\',\n            \'!**/*.spec.ts\'\n        ],\n\n        tests: [\'packages/**/*.spec.ts\'],\n\n        env: {\n            type: \'node\',\n            runner: \'node\',\n        },\n        testFramework: \'jest\',\n\n        preprocessors: {\n            \'**/*.js\': file => require(\'@babel/core\').transform(\n                file.content,\n                {sourceMap: true, filename: file.path, presets: [require(\'babel-preset-jest\')]})\n        }\n    };\n};\n' },
  packageJSON:
   { dependencies:
      { '@angular/animations': '7.2.15',
        '@angular/cdk': '7.3.7',
        '@angular/common': '7.2.15',
        '@angular/compiler': '7.2.15',
        '@angular/core': '7.2.15',
        '@angular/forms': '7.2.15',
        '@angular/http': '7.2.15',
        '@angular/material': '7.3.7',
        '@angular/material-moment-adapter': '8.2.3',
        '@angular/platform-browser': '7.2.15',
        '@angular/platform-browser-dynamic': '7.2.15',
        '@angular/router': '7.2.15',
        '@angular/upgrade': '7.2.15',
        rxjs: '6.5.5',
        'zone.js': '0.10.3',
        lodash: '4.17.15',
        'reflect-metadata': '0.1.13' },
     devDependencies: { '@types/jest': '25.2.1', '@types/lodash': '4.14.150', '@types/node': '13.13.2', jest: '25.4.0', 'jest-preset-angular': '8.1.3', typescript: '3.8.3' } },
  fs: { numberOfFiles: 9 },
  debug:
   [ '2020-04-24T11:30:42.991Z project Wallaby Node version: v10.16.3\n',
     '2020-04-24T11:30:42.992Z project Wallaby config: D:\\Work\\wallaby-jest-example\\wallaby.js\n',
     '2020-04-24T11:30:43.765Z project File cache: C:\\Users\\kopan\\AppData\\Local\\JetBrains\\WebStorm2020.1\\wallaby\\projects\\ef90b9da9b2a050a\n',
     '2020-04-24T11:30:43.869Z uiService Listening port 51236\n',
     '2020-04-24T11:30:43.912Z workers Parallelism for initial run: 10, for regular run: 5\n',
     '2020-04-24T11:30:43.912Z workers Starting run worker instance #0\n',
     '2020-04-24T11:30:43.912Z workers Starting run worker instance #1\n',
     '2020-04-24T11:30:43.913Z workers Starting run worker instance #2\n',
     '2020-04-24T11:30:43.913Z workers Starting run worker instance #3\n',
     '2020-04-24T11:30:43.913Z workers Starting run worker instance #4\n',
     '2020-04-24T11:30:43.913Z workers Starting run worker instance #5\n',
     '2020-04-24T11:30:43.913Z workers Starting run worker instance #6\n',
     '2020-04-24T11:30:43.913Z workers Starting run worker instance #7\n',
     '2020-04-24T11:30:43.913Z workers Starting run worker instance #8\n',
     '2020-04-24T11:30:43.913Z workers Starting run worker instance #9\n',
     '2020-04-24T11:30:43.915Z workers Web server is listening at 58193\n',
     '2020-04-24T11:30:44.014Z project File cache requires some updates, waiting required files from IDE\n',
     '2020-04-24T11:30:46.366Z workers Started run worker instance (delayed) #7\n',
     '2020-04-24T11:30:46.391Z workers Started run worker instance (delayed) #2\n',
     '2020-04-24T11:30:46.396Z workers Started run worker instance (delayed) #1\n',
     '2020-04-24T11:30:46.423Z workers Started run worker instance (delayed) #6\n',
     '2020-04-24T11:30:46.428Z workers Started run worker instance (delayed) #0\n',
     '2020-04-24T11:30:46.456Z workers Started run worker instance (delayed) #8\n',
     '2020-04-24T11:30:46.521Z workers Started run worker instance (delayed) #4\n',
     '2020-04-24T11:30:46.527Z workers Started run worker instance (delayed) #5\n',
     '2020-04-24T11:30:46.547Z workers Started run worker instance (delayed) #9\n',
     '2020-04-24T11:30:46.558Z workers Started run worker instance (delayed) #3\n',
     '2020-04-24T11:30:47.695Z project Stopping process pool\n',
     '2020-04-24T11:30:47.698Z project Running postprocessor\n',
     '2020-04-24T11:30:47.712Z postprocessor New TypeScript language service is required\n',
     '2020-04-24T11:30:47.714Z postprocessor Error parsing tsconfig file D:\\Work\\wallaby-jest-example\\tsconfig.json\n(ENOENT: no such file or directory, open \'D:\\Work\\wallaby-jest-example\\tsconfig.json\')\n',
     '2020-04-24T11:30:47.714Z postprocessor Error reading tsconfig file from D:\\Work\\wallaby-jest-example\\tsconfig.json\n(Cannot find module \'D:\\Work\\wallaby-jest-example\\tsconfig.json\')\n',
     '2020-04-24T11:30:49.297Z project Postprocessor execution finished\n',
     '2020-04-24T11:30:49.297Z project Test run started; run priority: 3\n',
     '2020-04-24T11:30:49.299Z project Running all tests\n',
     '2020-04-24T11:30:49.301Z workers Starting test run, priority: 3\n',
     '2020-04-24T11:30:49.301Z workers Distributing tests between 10 workers\n',
     '2020-04-24T11:30:49.302Z workers Running tests in parallel\n',
     '2020-04-24T11:30:49.303Z nodeRunner Starting sandbox [worker #0, session #xzsn3]\n',
     '2020-04-24T11:30:49.303Z nodeRunner Starting sandbox [worker #1, session #mvu0c]\n',
     '2020-04-24T11:30:49.303Z nodeRunner Preparing sandbox [worker #0, session #xzsn3]\n',
     '2020-04-24T11:30:49.303Z nodeRunner Preparing sandbox [worker #1, session #mvu0c]\n',
     '2020-04-24T11:30:49.304Z nodeRunner Prepared sandbox [worker #0, session #xzsn3]\n',
     '2020-04-24T11:30:49.304Z nodeRunner Prepared sandbox [worker #1, session #mvu0c]\n',
     '2020-04-24T11:30:49.304Z workers [worker #0, session #xzsn3] Running tests in sandbox\n',
     '2020-04-24T11:30:49.305Z workers [worker #1, session #mvu0c] Running tests in sandbox\n',
     '2020-04-24T11:31:03.919Z workers Sandbox (active) [xzsn3] error: TypeError: ..\\..\\..\\wallaby\\runners\\node\\jest@0.4.3\\jasmine2Initializer.js: Emit skipped for language service\n',
     '2020-04-24T11:31:03.924Z workers Failed to map the stack to user code, entry message: TypeError: ..\\..\\..\\wallaby\\runners\\node\\jest@0.4.3\\jasmine2Initializer.js: Emit skipped for language service, stack: TypeError: ..\\..\\..\\wallaby\\runners\\node\\jest@0.4.3\\jasmine2Initializer.js: Emit skipped for language service\n    at compileFn (D:\\Work\\wallaby-jest-example\\node_modules\\ts-jest\\dist\\compiler\\language-service.js:109:23)\n    at Object.compile (D:\\Work\\wallaby-jest-example\\node_modules\\ts-jest\\dist\\compiler\\instance.js:90:25)\n    at TsJestTransformer.process (D:\\Work\\wallaby-jest-example\\node_modules\\ts-jest\\dist\\ts-jest-transformer.js:85:41)\n    at ScriptTransformer.transformSource (D:\\Work\\wallaby-jest-example\\node_modules\\@jest\\transform\\build\\ScriptTransformer.js:479:35)\n    at ScriptTransformer._transformAndBuildScript (D:\\Work\\wallaby-jest-example\\node_modules\\@jest\\transform\\build\\ScriptTransformer.js:569:40)\n    at ScriptTransformer.transform (D:\\Work\\wallaby-jest-example\\node_modules\\@jest\\transform\\build\\ScriptTransformer.js:609:25)\n    at Runtime.transformFile (D:\\Work\\wallaby-jest-example\\node_modules\\jest-runtime\\build\\index.js:1149:53)\n    at Runtime._execModule (D:\\Work\\wallaby-jest-example\\node_\n',
     '2020-04-24T11:31:03.936Z workers Sandbox (active) [mvu0c] error: TypeError: ..\\..\\..\\wallaby\\runners\\node\\jest@0.4.3\\jasmine2Initializer.js: Emit skipped for language service\n',
     '2020-04-24T11:31:03.937Z workers Failed to map the stack to user code, entry message: TypeError: ..\\..\\..\\wallaby\\runners\\node\\jest@0.4.3\\jasmine2Initializer.js: Emit skipped for language service, stack: TypeError: ..\\..\\..\\wallaby\\runners\\node\\jest@0.4.3\\jasmine2Initializer.js: Emit skipped for language service\n    at compileFn (D:\\Work\\wallaby-jest-example\\node_modules\\ts-jest\\dist\\compiler\\language-service.js:109:23)\n    at Object.compile (D:\\Work\\wallaby-jest-example\\node_modules\\ts-jest\\dist\\compiler\\instance.js:90:25)\n    at TsJestTransformer.process (D:\\Work\\wallaby-jest-example\\node_modules\\ts-jest\\dist\\ts-jest-transformer.js:85:41)\n    at ScriptTransformer.transformSource (D:\\Work\\wallaby-jest-example\\node_modules\\@jest\\transform\\build\\ScriptTransformer.js:479:35)\n    at ScriptTransformer._transformAndBuildScript (D:\\Work\\wallaby-jest-example\\node_modules\\@jest\\transform\\build\\ScriptTransformer.js:569:40)\n    at ScriptTransformer.transform (D:\\Work\\wallaby-jest-example\\node_modules\\@jest\\transform\\build\\ScriptTransformer.js:609:25)\n    at Runtime.transformFile (D:\\Work\\wallaby-jest-example\\node_modules\\jest-runtime\\build\\index.js:1149:53)\n    at Runtime._execModule (D:\\Work\\wallaby-jest-example\\node_\n',
     '2020-04-24T11:31:03.943Z workers [xzsn3] Run 0 test(s), skipped 0 test(s)\n',
     '2020-04-24T11:31:03.946Z workers [xzsn3] Sandbox is responsive, closing it\n',
     '2020-04-24T11:31:03.957Z workers [mvu0c] Run 0 test(s), skipped 0 test(s)\n',
     '2020-04-24T11:31:03.961Z workers [mvu0c] Sandbox is responsive, closing it\n',
     '2020-04-24T11:31:03.961Z workers Merging parallel test run results\n',
     '2020-04-24T11:31:03.963Z project Test run finished\n',
     '2020-04-24T11:31:03.964Z project Processed console.log entries\n',
     '2020-04-24T11:31:03.964Z project Processed loading sequences\n',
     '2020-04-24T11:31:03.964Z project Processed executed tests\n',
     '2020-04-24T11:31:03.967Z project Processed code coverage\n',
     '2020-04-24T11:31:03.992Z project Test run result processed and sent to IDE\n' ] }
```

**Comment by Forkiy** [comment]
It looks like a problem in my configuration and not in Wallaby. Closing.
