### ISSUE TITLE
Angular CLI + Auto config not working

### ISSUE THREAD

**Issue by ryandegruyter** [wallabyjs/public#2422]
### Issue description or question

WallabyJS won't run with automatic configuration. Basic app scaffolded a few days ago with Angular CLI. 

It recognises Jest instead of Karma. Not using Jest at all.

### Wallaby diagnostics report

```
{
  editorVersion: 'IntelliJ IDEA 2020.1.1',
  pluginVersion: '1.0.176',
  editorType: 'IntelliJ',
  osVersion: 'darwin 18.7.0',
  nodeVersion: 'v12.16.1',
  coreVersion: '1.0.896',
  config: {
    diagnostics: {},
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    globalSetup: false,
    micromatch: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
      {
        pattern: 'dist/|build/|coverage/|/\\.cache/|/\\.idea/|/\\.vscode/|/\\.git/|/\\.gitlab/',
        regexp: /dist\/|build\/|coverage\/|\/\.cache\/|\/\.idea\/|\/\.vscode\/|\/\.git\/|\/\.gitlab\//,
        ignore: true,
        trigger: true,
        load: true
      },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
      {
        pattern: 'dist/|build/|coverage/|/\\.cache/|/\\.idea/|/\\.vscode/|/\\.git/|/\\.gitlab/',
        regexp: /dist\/|build\/|coverage\/|\/\.cache\/|\/\.idea\/|\/\.vscode\/|\/\.git\/|\/\.gitlab\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 }
    ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '<homeDir>/.nvm/versions/node/v12.16.1/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#1026773938'
  },
  packageJSON: {
    dependencies: {
      '@angular/animations': '~9.1.9',
      '@angular/common': '~9.1.9',
      '@angular/compiler': '~9.1.9',
      '@angular/core': '~9.1.9',
      '@angular/forms': '~9.1.9',
      '@angular/platform-browser': '~9.1.9',
      '@angular/platform-browser-dynamic': '~9.1.9',
      '@angular/router': '~9.1.9',
      rxjs: '~6.5.4',
      tslib: '^1.10.0',
      'zone.js': '~0.10.2'
    },
    devDependencies: {
      '@angular-devkit/build-angular': '~0.901.7',
      '@angular/cli': '~9.1.7',
      '@angular/compiler-cli': '~9.1.9',
      '@babel/core': '^7.9.6',
      '@storybook/addon-actions': '^5.3.18',
      '@storybook/addon-links': '^5.3.18',
      '@storybook/addon-notes': '^5.3.18',
      '@storybook/addons': '^5.3.18',
      '@storybook/angular': '^5.3.18',
      '@types/jasmine': '~3.5.0',
      '@types/jasminewd2': '~2.0.3',
      '@types/node': '^12.11.1',
      'babel-loader': '^8.1.0',
      chromatic: '^4.0.3',
      codelyzer: '^5.1.2',
      'jasmine-core': '~3.5.0',
      'jasmine-spec-reporter': '~4.2.1',
      karma: '~5.0.0',
      'karma-chrome-launcher': '~3.1.0',
      'karma-coverage-istanbul-reporter': '~2.1.0',
      'karma-jasmine': '~3.0.1',
      'karma-jasmine-html-reporter': '^1.4.2',
      protractor: '~7.0.0',
      'ts-node': '~8.3.0',
      tslint: '~6.1.0',
      typescript: '~3.8.3'
    }
  },
  fs: { numberOfFiles: 36 },
  debug: [
    '2020-05-22T22:20:42.854Z config Detected Jest.\n',
    '2020-05-22T22:20:42.854Z config Configured Jest.\n',
    '2020-05-22T22:20:42.856Z project Wallaby Node version: v12.16.1\n',
    '2020-05-22T22:20:42.856Z project Wallaby config: <homeDir>/ryco/auto.detect\n',
    '2020-05-22T22:20:43.743Z project File cache: <homeDir>/Library/Caches/JetBrains/IntelliJIdea2020.1/wallaby/projects/38c9422a78f5c73f\n',
    '2020-05-22T22:20:43.753Z uiService Listening port 51235\n',
    '2020-05-22T22:20:43.755Z project package.json file change detected, invalidating local cache\n',
    '2020-05-22T22:20:43.764Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2020-05-22T22:20:43.764Z workers Starting run worker instance #0\n',
    '2020-05-22T22:20:43.765Z workers Starting run worker instance #1\n',
    '2020-05-22T22:20:43.765Z workers Starting run worker instance #2\n',
    '2020-05-22T22:20:43.765Z workers Starting run worker instance #3\n',
    '2020-05-22T22:20:43.765Z workers Starting run worker instance #4\n',
    '2020-05-22T22:20:43.765Z workers Starting run worker instance #5\n',
    '2020-05-22T22:20:43.765Z workers Web server is listening at 62083\n',
    '2020-05-22T22:20:43.765Z project File cache requires some updates, waiting required files from IDE\n',
    '2020-05-22T22:20:43.939Z workers Started run worker instance (delayed) #0\n',
    '2020-05-22T22:20:43.940Z workers Started run worker instance (delayed) #1\n',
    '2020-05-22T22:20:43.942Z project Stopping process pool\n',
    '2020-05-22T22:20:43.943Z project Test run started; run priority: 3\n',
    '2020-05-22T22:20:43.944Z project Running all tests\n',
    '2020-05-22T22:20:43.947Z workers Starting test run, priority: 3\n',
    '2020-05-22T22:20:43.947Z workers Distributing tests between 6 workers\n',
    '2020-05-22T22:20:43.948Z workers Running tests in parallel\n',
    '2020-05-22T22:20:43.948Z nodeRunner Starting sandbox [worker #0, session #300g9]\n',
    '2020-05-22T22:20:43.948Z nodeRunner Starting sandbox [worker #1, session #3a00v]\n',
    '2020-05-22T22:20:43.948Z nodeRunner Preparing sandbox [worker #0, session #300g9]\n',
    '2020-05-22T22:20:43.948Z nodeRunner Preparing sandbox [worker #1, session #3a00v]\n',
    '2020-05-22T22:20:43.948Z nodeRunner Prepared sandbox [worker #0, session #300g9]\n',
    '2020-05-22T22:20:43.948Z nodeRunner Prepared sandbox [worker #1, session #3a00v]\n',
    '2020-05-22T22:20:43.948Z workers [worker #0, session #300g9] Running tests in sandbox\n',
    '2020-05-22T22:20:43.949Z workers [worker #1, session #3a00v] Running tests in sandbox\n',
    '2020-05-22T22:20:43.958Z workers Started run worker instance (delayed) #2\n',
    '2020-05-22T22:20:43.959Z workers Started run worker instance (delayed) #3\n',
    '2020-05-22T22:20:44.011Z workers Started run worker instance (delayed) #4\n',
    '2020-05-22T22:20:44.066Z workers Started run worker instance (delayed) #5\n',
    '2020-05-22T22:20:48.651Z workers Sandbox (active) [300g9] error: Cannot use import statement outside a module\n',
    '2020-05-22T22:20:48.653Z workers [300g9] Run 1 test(s), skipped 0 test(s)\n',
    '2020-05-22T22:20:48.657Z workers [300g9] Sandbox is responsive, closing it\n',
    '2020-05-22T22:20:48.717Z workers Sandbox (active) [3a00v] error: <homeDir>/ryco/src/test.ts: Unexpected token, expected ";" (10:8)\n' +
      '\n' +
      "   8 | } from '@angular/platform-browser-dynamic/testing';\n" +
      '   9 | \n' +
      '> 10 | declare const require: {\n' +
      '     |         ^\n' +
      '  11 |   context(path: string, deep?: boolean, filter?: RegExp): {\n' +
      '  12 |     keys(): string[];\n' +
      '  13 |     <T>(id: string): T;\n',
    '2020-05-22T22:20:48.717Z workers [3a00v] Run 1 test(s), skipped 0 test(s)\n',
    '2020-05-22T22:20:48.719Z workers [3a00v] Sandbox is responsive, closing it\n',
    '2020-05-22T22:20:48.720Z workers Failed to map the stack to user code, entry message: <homeDir>/ryco/src/test.ts: Unexpected token, expected ";" (10:8)\n' +
      '\n' +
      "   8 | } from '@angular/platform-browser-dynamic/testing';\n" +
      '   9 | \n' +
      '> 10 | declare const require: {\n' +
      '     |         ^\n' +
      '  11 |   context(path: string, deep?: boolean, filter?: RegExp): {\n' +
      '  12 |     keys(): string[];\n' +
      '  13 |     <T>(id: string): T;, stack: SyntaxError: <homeDir>/ryco/src/test.ts: Unexpected token, expected ";" (10:8)\n' +
      '\n' +
      "   8 | } from '@angular/platform-browser-dynamic/testing';\n" +
      '   9 | \n' +
      '> 10 | declare const require: {\n' +
      '     |         ^\n' +
      '  11 |   context(path: string, deep?: boolean, filter?: RegExp): {\n' +
      '  12 |     keys(): string[];\n' +
      '  13 |     <T>(id: string): T;\n' +
      '    at Parser._raise (<homeDir>/ryco/node_modules/@babel/parser/src/parser/location.js:241:45)\n' +
      '    at Parser.raiseWithData (<homeDir>/ryco/node_modules/@babel/parser/src/parser/location.js:236:17)\n' +
      '    at Parser.raise (<homeDir>/ryco/node_modules/@babel/parser/src/parser/location.js:220:17)\n' +
      '    at Parser.unexpected (<homeDir>/ryco/node_modules/@babel/parser/src/parser/util.js:149:16)\n' +
      '    at Parser.semicolon (<homeDir>/ryco/node_modules/@babel/parser/src/parser/util.js:122:40)\n' +
      '    at Parser.parseExpressionStatement (<homeDir>/ryco/node_modules/@babel/parser/src/parser/statement.js:787:10)\n' +
      '    at Parser.parseStatementContent (<homeDir>/ryco/node_modules/@babel/parser/src/parser/s\n',
    '2020-05-22T22:20:48.720Z workers Merging parallel test run results\n',
    '2020-05-22T22:20:48.720Z project Test run finished\n',
    '2020-05-22T22:20:48.721Z project Processed console.log entries\n',
    '2020-05-22T22:20:48.721Z project Processed loading sequences\n',
    '2020-05-22T22:20:48.721Z project Processed executed tests\n',
    '2020-05-22T22:20:48.721Z project Processed code coverage\n',
    '2020-05-22T22:20:48.728Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by smcenlly** [comment]
The reason that Wallaby is attempting to use `jest` is that it is finding `jest` in your node_modules and assuming that your project is using jest. This is because the [`chromatic` package](https://www.npmjs.com/package/chromatic) in your dependencies depends on jest.

Next week, we will make some changes to how Wallaby is detecting Angular projects to ignore the jest dependency in this case.

In the meantime, you should be able to get Wallaby working for you by creating and using a Wallaby.js configuration file.

**wallaby.js**
```javascript
module.exports = () => ({
  autoDetect: true,
  testFramework: {
    configFile: 'angular'
  },
});
```

**Comment by ryandegruyter** [comment]
Ok temporary workaround works fine, thanks!

**Comment by NikGovorov** [comment]
Thanks for reporting the issue. It is fixed and the fix is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
