### ISSUE TITLE
Unable to run test when i start wallaby.js throwing NoopAnimationDriver cannot be invoked with new

### ISSUE THREAD

**Issue by gangadharvuyyuru** [wallabyjs/public#2439]
### Uncaught TypeError: Class constructor NoopAnimationDriver cannot be invoked without 'new' 
at http://localhost:56580/____wallaby-bundle.js?1591423683700&wallabyFileId=bundle:135252:15 

### Wallaby diagnostics report

Copy : Cannot find path 'D:\MyProject\Diagnostics' because it does not exist.
At line:1 char:1
+ Copy Diagnostics Report
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\MyProject\Diagnostics:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

**Comment by ArtemGovorov** [comment]
>Copy : Cannot find path 'D:\MyProject\Diagnostics' because it does not exist.

It looks like you are trying to run the command from your CLI, please follow the instructions for your editor (depending on your you must either use your editor command palette or `Help` menu item):

- to run `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command from your editor command palette; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

**Comment by gangadharvuyyuru** [comment]
```
{
  editorVersion: '1.45.1',
  pluginVersion: '1.0.207',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.18363',
  nodeVersion: 'v12.14.0',
  coreVersion: '1.0.906',
  config: {
    diagnostics: {
      angular: {
        workspace: {
          '$schema': './node_modules/@angular/cli/lib/config/schema.json',
          version: 1,
          newProjectRoot: 'projects',
          projects: {
            POS: {
              root: '',
              sourceRoot: 'src',
              projectType: 'application',
              prefix: 'app',
              schematics: { '@schematics/angular:component': { style: 'scss' } },
              architect: {
                build: {
                  builder: '@angular-devkit/build-angular:browser',
                  options: {
                    outputPath: 'dist/POS',
                    commonChunk: false,
                    index: 'src/index.html',
                    main: 'src/main.ts',
                    polyfills: 'src/polyfills.ts',
                    tsConfig: 'src/tsconfig.app.json',
                    assets: [ 'src/favicon.ico', 'src/assets' ],
                    styles: [
                      './node_modules/bootstrap/dist/css/bootstrap.min.css',
                      './node_modules/ngx-bootstrap/datepicker/bs-datepicker.css',
                      './node_modules/ngx-toastr/toastr.css',
                      './node_modules/swiper/dist/css/swiper.min.css',
                      './node_modules/theme-builder/dist/assets/styles/themes/bootstrap-theme-blue.css',
                      'src/scss/media-queries.scss',
                      'src/styles.scss'
                    ],
                    scripts: [
                      './node_modules/jquery/dist/jquery.slim.js',
                      './node_modules/popper.js/dist/umd/popper.js',
                      './node_modules/bootstrap/dist/js/bootstrap.min.js',
                      './node_modules/swiper/dist/js/swiper.min.js',
                      './node_modules/theme-builder/dist/assets/scripts/main.js',
                      './node_modules/drift-zoom/dist/Drift.min.js'
                    ],
                    es5BrowserSupport: true
                  },
                  configurations: {
                    dev: { fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.dev.ts' } ] },
                    qa: { fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.qa.ts' } ] },
                    production: {
                      fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.prod.ts' } ],
                      optimization: true,
                      outputHashing: 'all',
                      sourceMap: false,
                      extractCss: true,
                      namedChunks: false,
                      aot: true,
                      extractLicenses: true,
                      vendorChunk: true,
                      buildOptimizer: true,
                      budgets: [ { type: 'initial', maximumWarning: '10mb', maximumError: '10mb' } ]
                    }
                  }
                },
                serve: { builder: '@angular-devkit/build-angular:dev-server', options: { browserTarget: 'POS:build' }, configurations: { production: { browserTarget: 'POS:build:production' } } },
                'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: 'POS:build' } },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    codeCoverage: true,
                    main: 'src/test.ts',
                    polyfills: 'src/polyfills.ts',
                    tsConfig: 'src/tsconfig.spec.json',
                    karmaConfig: 'src/karma.conf.js',
                    styles: [ './node_modules/bootstrap/dist/css/bootstrap.min.css', './node_modules/ngx-bootstrap/datepicker/bs-datepicker.css', 'src/styles.scss' ],
                    scripts: [],
                    assets: [ 'src/favicon.ico', 'src/assets' ]
                  }
                },
                lint: { builder: '@angular-devkit/build-angular:tslint', options: { tsConfig: [ 'src/tsconfig.app.json', 'src/tsconfig.spec.json' ], exclude: [ '**/node_modules/**' ] } }
              }
            },
            'POS-e2e': {
              root: 'e2e/',
              projectType: 'application',
              prefix: '',
              architect: {
                e2e: {
                  builder: '@angular-devkit/build-angular:protractor',
                  options: { protractorConfig: 'e2e/protractor.conf.js', devServerTarget: 'POS:serve' },
                  configurations: { production: { devServerTarget: 'POS:serve:production' } }
                },
                lint: { builder: '@angular-devkit/build-angular:tslint', options: { tsConfig: 'e2e/tsconfig.e2e.json', exclude: [ '**/node_modules/**' ] } }
              }
            }
          },
          defaultProject: 'POS',
          cli: { analytics: 'ab19e6c6-4c99-43c2-ae4c-6f49a9bfa54c' }
        },
        main: '// This file is required by karma.conf.js and loads recursively all the .spec and framework files\r\n' +
          '\r\n' +
          '// uncomment below to check complete code coverage\r\n' +
          'import "./app/app.module";// This file is required by karma.conf.js and loads recursively all the .spec and framework files\r\n' +
          '\r\n' +
          "import 'zone.js/dist/zone-testing';\r\n" +
          "import { getTestBed } from '@angular/core/testing';\r\n" +
          'import {\r\n' +
          '  BrowserDynamicTestingModule,\r\n' +
          '  platformBrowserDynamicTesting\r\n' +
          "} from '@angular/platform-browser-dynamic/testing';\r\n" +
          '\r\n' +
          'declare const require: {\r\n' +
          '  context(path: string, deep?: boolean, filter?: RegExp): {\r\n' +
          '    keys(): string[];\r\n' +
          '    <T>(id: string): T;\r\n' +
          '  };\r\n' +
          '};\r\n' +
          '\r\n' +
          '// First, initialize the Angular testing environment.\r\n' +
          'getTestBed().initTestEnvironment(\r\n' +
          '  BrowserDynamicTestingModule,\r\n' +
          '  platformBrowserDynamicTesting()\r\n' +
          ');\r\n' +
          '// Then we find all the tests.\r\n' +
          '\r\n' +
          '// And load the modules.\r\n'
      }
    },
    testFramework: { version: 'jasmine@3.5.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3', autoDetected: true },
    env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    files: [
      { pattern: 'src/**/*.spec.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/polyfills.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/main.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/index.html', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.base.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.wallaby.ts', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 2 },
      { pattern: 'src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 3 }
    ],
    tests: [ { pattern: 'src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 4 } ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: true,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    testLocations: [ 'src/app/components/request/home/home.component.spec.ts' ],
    configCode: 'auto.detect#1313788472'
  },
  packageJSON: {
    dependencies: {
      '@angular/animations': '^10.0.0-next.7',
      '@angular/common': '10.0.0-next.7',
      '@angular/compiler': '10.0.0-next.7',
      '@angular/core': '10.0.0-next.7',
      '@angular/forms': '10.0.0-next.7',
      '@angular/platform-browser': '10.0.0-next.7',
      '@angular/platform-browser-dynamic': '10.0.0-next.7',
      '@angular/platform-server': '^10.0.0-next.7',
      '@angular/router': '10.0.0-next.7',
       compression: '1.7.4',
      '@microsoft/microsoft-graph-client': '^1.7.0',
      '@ng-select/ng-select': '~2.20.5',
      '@swimlane/ngx-datatable': '^15.0.0',
      '@types/express-serve-static-core': '^4.16.4',
      '@types/moment-timezone': '^0.5.12',
      axios: '^0.18.0',
      bootstrap: '^4.3.1',
      'core-js': '2.5.4',
      'drift-zoom': '^1.4.0',
      ejs: '^2.6.1',
      express: '^4.16.4',
      'express-actuator': '^1.3.0',
      'file-saver': '^2.0.0',
      'flat-cache': '^2.0.1',
      jquery: '^3.4.1',
      logger: '0.0.1',
      moment: '^2.24.0',
      'moment-timezone': '^0.5.27',
      'ng-sidebar': '8.0.0',
      'ngx-bootstrap': '^4.2.0',
      'ngx-clipboard': '^12.2.0',
      'ngx-confirm-box': '0.0.3',
      'ngx-filesaver': '^2.2.1',
      'ngx-infinite-scroll': '^8.0.1',
      'ngx-toastr': '^10.0.4',
      'node-cache': '^4.2.0',
      'node-cloudfoundry-actuator-cli': '^2.2.0',
      'node-fetch': '^2.6.0',
      'node-git-info': '^1.1.0',
      'npm-watch': '^0.6.0',
      'popper.js': '^1.15.0',
      'pretty-checkbox': '^3.0.3',
      rxjs: '6.5.5',
      'rxjs-compat': '^6.5.1',
      stubby: '^4.1.0',
      swiper: '^4.5.0',
      'textarea-caret': '^3.1.0',
      'to-px': '^1.1.0',
      tslib: '^1.13.0',
      'zone.js': '0.10.3'
    },
    devDependencies: {
      '@angular-devkit/build-angular': '^0.1000.0-next.5',
      '@angular/cli': '^10.0.0-next.5',
      '@angular/compiler-cli': '10.0.0-next.7',
      '@angular/language-service': '10.0.0-next.7',
      '@ng-select/ng-option-highlight': '0.0.4',
      '@types/chai-as-promised': '7.1.0',
      '@types/chai-string': '1.4.1',
      '@types/jasmine': '2.8.8',
      '@types/jasminewd2': '2.0.3',
      '@types/mocha': '5.2.6',
      '@types/node': '8.9.4',
      '@types/swiper': '^5.2.0',
      chai: '4.2.0',
      'chai-as-promised': '7.1.1',
      'chai-spies': '^1.0.0',
      codelyzer: '4.5.0',
      eslint: '^5.16.0',
      'eslint-config-standard': '^12.0.0',
      'eslint-plugin-import': '^2.17.3',
      'eslint-plugin-node': '^9.1.0',
      'eslint-plugin-promise': '^4.1.1',
      'eslint-plugin-standard': '^4.0.0',
      'jasmine-core': '2.99.1',
      'jasmine-spec-reporter': '4.2.1',
      karma: '4.1.0',
      'karma-chai': '0.1.0',
      'karma-chrome-launcher': '2.1.1',
      'karma-cli': '1.0.1',
      'karma-coverage-istanbul-reporter': '1.2.1',
      'karma-istanbul-threshold': '^1.2.3',
      'karma-jasmine': '1.1.2',
      'karma-jasmine-html-reporter': '0.2.2',
      'karma-mocha': '1.3.0',
      'karma-mocha-reporter': '2.2.5',
      'karma-parallel': '^0.3.1',
      'karma-phantomjs-launcher': '1.0.4',
      'karma-sinon': '1.0.5',
      'karma-sinon-chai': '2.0.2',
      livereload: '^0.9.1',
      mocha: '6.1.4',
      nodemon: '^2.0.3',
      protractor: '5.4.0',
      reify: '^0.20.12',
      sass: '^1.26.5',
      sinon: '7.3.2',
      'sinon-chai': '3.3.0',
      'ts-node': '^7.0.0',
      tslint: '5.11.0',
      typescript: '^3.8.3',
      'wallaby-webpack': '^3.9.15'
    }
  },
  fs: { numberOfFiles: 740 },
  debug: [
    '2020-06-06T10:22:06.994Z config Detected Angular CLI.\n',
    '2020-06-06T10:22:12.674Z angular/cli project config Using virtual D:/myproject/src/test.ts.\n',
    '2020-06-06T10:22:12.704Z config Configured Angular CLI.\n',
    '2020-06-06T10:22:12.705Z project Wallaby Node version: v12.14.0\n',
    '2020-06-06T10:22:12.705Z project Wallaby config: D:\\myproject\\auto.detect\n',
    '2020-06-06T10:22:14.201Z project File cache: C:\\Users\\pos\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.207\\projects\\605e3860401209f3\n',
    '2020-06-06T10:22:15.924Z uiService Listening port 51235\n',
    '2020-06-06T10:22:15.958Z project package.json file change detected, invalidating local cache\n',
    '2020-06-06T10:22:16.135Z workers Parallelism for initial run: 2, for regular run: 2\n',
    '2020-06-06T10:22:16.135Z workers Starting run worker instance #0\n',
    '2020-06-06T10:22:16.135Z workers Starting run worker instance #1\n',
    '2020-06-06T10:22:16.151Z workers Web server is listening at 49388\n',
    '2020-06-06T10:22:16.174Z project Stopping process pool\n',
    '2020-06-06T10:22:16.174Z project File cache is up-to-date, starting full test run\n',
    '2020-06-06T10:22:16.176Z project Running postprocessor\n',
    '2020-06-06T10:22:16.192Z postprocessor Processing started.\n',
    '2020-06-06T10:22:16.192Z postprocessor Initializing.\n',
    '2020-06-06T10:22:16.193Z postprocessor Initializing entry.\n',
    '2020-06-06T10:22:16.193Z postprocessor Sanitizing configuration.\n',
    '2020-06-06T10:22:16.193Z postprocessor Adjusting configuration.\n',
    '2020-06-06T10:22:16.193Z postprocessor Creating compiler.\n',
    '2020-06-06T10:22:17.947Z postprocessor Customizing compiler.\n',
    '2020-06-06T10:22:17.947Z postprocessor Compilation started.\n',
    '2020-06-06T10:22:46.758Z workers Started run worker instance (immediate) #0\n',
    '2020-06-06T10:22:46.758Z workers Started run worker instance (immediate) #1\n',
    '2020-06-06T10:23:11.144Z postprocessor Compilation finished.\n',
    '2020-06-06T10:23:18.202Z postprocessor Emitting 1117 files.\n',
    '2020-06-06T10:23:18.333Z postprocessor Processing finished.\n',
    '2020-06-06T10:23:18.921Z project Postprocessor execution finished\n',
    '2020-06-06T10:23:18.921Z project Test run started; run priority: 3\n',
    '2020-06-06T10:23:18.930Z project Running all tests\n',
    '2020-06-06T10:23:18.957Z workers Starting test run, priority: 3\n',
    '2020-06-06T10:23:18.958Z chromeRunner Starting sandbox [worker #0, session #1ltfh]\n',
    '2020-06-06T10:23:18.959Z chromeRunner Preparing sandbox [worker #0, session #1ltfh]\n',
    '2020-06-06T10:23:18.961Z browserRunner Total files to load in sandbox: 5\n',
    '2020-06-06T10:23:18.964Z browserRunner Sandbox is generated [worker #0, session #1ltfh]: http://localhost:49388/wallaby_sandbox0.html\n',
    '2020-06-06T10:23:18.964Z chromeRunner Prepared sandbox [worker #0, session #1ltfh]\n',
    '2020-06-06T10:23:18.964Z workers [worker #0, session #1ltfh] Running tests in sandbox\n',
    "2020-06-06T10:23:22.143Z workers Sandbox (active) [1ltfh] error: Uncaught TypeError: Class constructor NoopAnimationDriver cannot be invoked without 'new'\n",
    "2020-06-06T10:23:22.145Z workers Failed to map the stack to user code, entry message: Uncaught TypeError: Class constructor NoopAnimationDriver cannot be invoked without 'new', stack: Uncaught TypeError: Class constructor NoopAnimationDriver cannot be invoked without 'new'\n" +
      'at http://localhost:49388/____wallaby-bundle.js?1591438998796&wallabyFileId=bundle:135252:15\n',
    '2020-06-06T10:23:22.245Z workers [1ltfh] Run 0 test(s), skipped 0 test(s)\n',
    '2020-06-06T10:23:22.280Z workers [1ltfh] Sandbox is responsive, closing it\n',
    '2020-06-06T10:23:22.282Z project Test run finished\n',
    '2020-06-06T10:23:22.284Z project Processed console.log entries\n',
    '2020-06-06T10:23:22.284Z project Processed loading sequences\n',
    '2020-06-06T10:23:22.284Z project Processed executed tests\n',
    '2020-06-06T10:23:22.377Z project Processed code coverage\n',
    '2020-06-06T10:23:22.864Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by gangadharvuyyuru** [comment]
@ArtemGovorov  I have pasted the Diagnostic Report.

**Comment by ArtemGovorov** [comment]
What does running `ng test` in your project's root print?

**Comment by gangadharvuyyuru** [comment]
It prints the test coverage for each file that i have written unit tests

**Comment by ArtemGovorov** [comment]
> TOTAL: 1 FAILED,

Can you please paste the error details for the failed test?

**Comment by gangadharvuyyuru** [comment]
FAILED TESTS:
  getSearch
    [X] make expected calls
      HeadlessChrome 83.0.4103 (Windows 10.0.0)
    TypeError: searchKeys.includes is not a function
        at includes (_karma_webpack_/webpack:/src/app/components/request/home/home.component.ts:135:28)
        at Array.forEach (<anonymous>)
        at HomeComponent.forEach [as getSearch] (_karma_webpack_/webpack:/src/app/components/request/home/home.component.ts:133:15)
        at Context.<anonymous> (_karma_webpack_/webpack:/src/app/components/request/home/home.component.spec.ts:5198:17)
        at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:388:1)
        at ProxyZoneSpec.onInvoke (_karma_webpack_/webpack:/node_modules/zone.js/dist/proxy.js:128:1)
        at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:387:1)
        at Zone../node_modules/zone.js/dist/zone.js.Zone.run (_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:138:1)
        at Context.<anonymous> (_karma_webpack_/webpack:/node_modules/zone.js/dist/mocha-patch.js:88:1)

**Comment by ArtemGovorov** [comment]
Is the `NoopAnimationDriver cannot be invoked with new` issue still reproducible if you comment out all test file but `src/app/components/request/home/home.component.ts` and only leave one empty test like
```
it('works', () => {
});
```
in the file and restart Wallaby?

**Comment by gangadharvuyyuru** [comment]
Warning: Entry point '@azure/msal-angular' contains deep imports into 'D:/MyProject/node_modules/rxjs/add/operator/filter', 'D:/MyProject/node_modules/rxjs/add/operator/map', 'D:/MyProject/node_modules/rxjs/BehaviorSubject', 'D:/MyProject/node_modules/rxjs/add/observable/of', 'D:/MyProject/node_modules/rxjs/add/operator/do', 'D:/MyProject/node_modules/rxjs/add/operator/delay', 'D:/MyProject/node_modules/rxjs/add/operator/pairwise', 'D:/MyProject/node_modules/rxjs/Observable', 'D:/MyProject/node_modules/rxjs/add/observable/fromPromise', 'D:/MyProject/node_modules/rxjs/add/operator/mergeMap', 'D:/MyProject/node_modules/msal/lib-commonjs/Logger', 'D:/MyProject/node_modules/rxjs/Subscription'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Warning: Entry point 'ngx-toastr' contains deep imports into 'D:/MyProject/node_modules/@angular/compiler/src/core'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

START:

Finished in 0 secs / 0 secs @ 16:22:03 GMT+0530 (India Standard Time)


ERROR in node_modules/@types/node/index.d.ts:73:11 - error TS2300: Duplicate identifier 'IteratorResult'.

73 interface IteratorResult<T> { }
             ~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6
    41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
            ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.
node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6 - error TS2300: Duplicate identifier 'IteratorResult'.

41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
        ~~~~~~~~~~~~~~

  node_modules/@types/node/index.d.ts:73:11
    73 interface IteratorResult<T> { }
                 ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.
src/app/components/config/storeGroup/create-store-group/create-store-group.component.ts:562:25 - error TS2339: Property 'setElementClass' does not exist on type 'Renderer2'.

562           this.renderer.setElementClass(this.el.nativeElement.querySelector(`#custom-check-${divisions}`), "partiallyFilledCB", false);
                            ~~~~~~~~~~~~~~~
src/app/components/myfolder/create-POS/triggers.component.ts:7:25 - error TS2307: Cannot find module '@angular/core/src/render3' or its corresponding type declarations.

7 import { element } from "@angular/core/src/render3";
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/components/myfolder/create-Pos/benefits.component.ts:5:3m53 - error TS2307: Cannot find module '@angular/core/src/view/pure_expression' or its corresponding type declarations.

5 import { checkAndUpdatePureExpressionDynamic } from '@angular/core/src/view/pure_expression';
                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/components/request/request-form/general/tag-process.component.ts:6:23 - error TS2307: Cannot find module '@angular/core/src/render3' or its corresponding type declarations.

6 import { store } from "@angular/core/src/render3";
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/components/request/request-form/mycoup/test-opt.comp.spec.ts:20:45 - error TS2307: Cannot find module '@angular/core/src/render3/interfaces/styling' or its corresponding type declarations.

20 import { SinglePropOffsetValuesIndex } from '@angular/core/src/render3/interfaces/styling';
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/services/request-form.service.ts:570:22 - error TS2339: Property 'url' does not exist on type 'unknown'.

570             if (file.url && file.url.length > 0) {
                         ~~~
src/app/services/request-form.service.ts:570:34 - error TS2339: Property 'url' does not exist on type 'unknown'.

570             if (file.url && file.url.length > 0) {
                                     ~~~
src/app/shared/filter/filter.component.spec.ts:26:48 - error TS2307: Cannot find module '@angular/core/src/render3' or its corresponding type declarations.

26 import { componentHostSyntheticProperty } from '@angular/core/src/render3';

**Comment by gangadharvuyyuru** [comment]
I see the above error when i run "ng test" previously i was running in another project.

**Comment by ArtemGovorov** [comment]
Can you please share a sample repo where the originally reported issue can be reproduced? The real source code is not required, just a simple test should suffice.

**Comment by gangadharvuyyuru** [comment]
It would be difficult for me to get the repo as i only have my project in place

**Comment by ArtemGovorov** [comment]
We can't reproduce the issue on a freshly generated `@angular/cli@10.0.0-rc.2` app. Everything is working as expected:
<img width="727" alt="Screen Shot 2020-06-06 at 9 06 33 pm" src="https://user-images.githubusercontent.com/979966/83942728-a26ee400-a839-11ea-8c8b-48addcc7e891.png">

So because the issue seems to be specific to your setup/config, we need a sample to be able to reproduce it. We don't need the full source code, you may just leave one test file with a dummy test and delete all business sensitive code. As long as the issue is still reproducible in the stripped down version of your project - it's enough for us. Once you have the sample ready, please publish it as GitHub repo or email it to us hello@wallabyjs.com.

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. If you can provide us with a reproducible sample, we will re-open the issue.
