### ISSUE TITLE
Using jasmine-given plugin

### ISSUE THREAD

**Issue by EtienneGhiringhelli** [wallabyjs/public#2464]
### Issue description or question

In my Angular 10 application, I'm trying to use jasmine-given which is a karma's plugin (more info here: https://github.com/searls/jasmine-given).

I implemented it into karma.conf.ts:
```ts
module.exports = function(config) {
    config.set({
        basePath: '',
        frameworks: ['jasmine-given', 'jasmine', '@angular-devkit/build-angular'],
        plugins: [
            require('karma-jasmine'),
            require('karma-jasmine-given'),
        ...
```

And my tsconfig.spec.ts:
```ts
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    "outDir": "./out-tsc/spec",
    "types": [
      "jasmine-given",
      "jasmine",
    ]
    ...
```

It works fine using ng test command.

### The problem

I used automatic configuration from WallabyJS and it doesn't recognize the Given / Then / When functions as shown in the test console:
```bash
[Error] Runtime error: ReferenceError: Given is not defined 
[Error]     at t.<anonymous> (http://localhost:4580/src/app/app.component.spec.ts.wbp.js?1593379316276&wallabyFileId=4:10:5) 
[Error]     at ZoneDelegate.invoke (http://localhost:4580/____wallaby-bundle.js?1593379316301&wallabyFileId=bundle:432:30) 
[Error]     at Zone.run (http://localhost:4580/____wallaby-bundle.js?1593379316301&wallabyFileId=bundle:191:47) 
[Error]     at t.<anonymous> (http://localhost:4580/____wallaby-bundle.js?1593379316301&wallabyFileId=bundle:6193:33) 
[Error]     at r (http://localhost:4580/__wallaby__/jasmine@3.5.0/framework.js:14:10924) 
[Error]     at t.describe (http://localhost:4580/__wallaby__/jasmine@3.5.0/framework.js:14:21077) 
[Error]     at t.s.describe (http://localhost:4580/__wallaby__/jasmine@2.1.3/configurator.js:14:2811) 
[Error]     at t.jasmineEnv.<computed> [as describe] (http://localhost:4580/____wallaby-bundle.js?1593379316301&wallabyFileId=bundle:6123:42) 
[Error]     at describe (http://localhost:4580/__wallaby__/jasmine@3.5.0/framework.js:16:6838) 
[Error]     at Module.window.__moduleBundler.modules.<computed> (http://localhost:4580/src/app/app.component.spec.ts.wbp.js?1593379316276&wallabyFileId=4:7:19) 
[Error]     at Object.window.__moduleBundler.require (http://localhost:4580/____wallaby-webpack.js?1593379316286:28:16) 
[Error]     at http://localhost:4580/____wallaby-webpack-bootstrapper.js?1593379316287:18:36 
[Error]     at http://localhost:4580/__wallaby__/tracer.js:15:11064 
[Error]     at a._doWhenReceiverIsReady (http://localhost:4580/__wallaby__/tracer.js:14:9931) 
[Error]     at Object._startWhenReceiverIsReady (http://localhost:4580/__wallaby__/tracer.js:15:11030) 
[Error]     at Object.window.__moduleBundler.loadTests (http://localhost:4580/____wallaby-webpack-bootstrapper.js?1593379316287:13:22) 
[Error]     at http://localhost:4580/wallaby_sandbox0.html:9:23002 
[Error]     at http://localhost:4580/wallaby_sandbox0.html:9:23016 
```

So I believe, the plugin is not recognized by wallabyJS.

I tried to put a manual config file from this URL: https://wallabyjs.com/docs/integration/angular.html#manual-configuration-wallabyjs-file
To see if I can add something there but this configuration is not working at all:

```bash
[Error] Failed to load configuration file: Cannot find module 'wallaby-webpack' 
[Error] Require stack: 
[Error] - .\wallabyjs.conf.ts 
[Error] - [wallaby core]\server.js 
[Error]     at module.exports (.\wallabyjs.conf.ts:2:28) 
```

### Conclusion

To resume, I have one question & one issue:
- If possible, could you provide a guideline to how to make wallabyJS understand that jasmine-given exists
- The manual configuration you provide doesn't work. Maybe I did something wrong or maybe this is outdated ?

### Sidenote

Thank you for this amazing plugin, money well spent !

### Wallaby diagnostics report

```
{
  editorVersion: '1.46.1',
  pluginVersion: '1.0.212',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.18363',
  nodeVersion: 'v12.18.1',
  coreVersion: '1.0.920',
  config: {
    diagnostics: {
      angular: {
        workspace: {
          '$schema': './node_modules/@angular/cli/lib/config/schema.json',
          version: 1,
          newProjectRoot: 'projects',
          projects: {
            'ng-test': {
              projectType: 'application',
              schematics: { '@schematics/angular:component': { style: 'sass' } },
              root: '',
              sourceRoot: 'src',
              prefix: 'app',
              architect: {
                build: {
                  builder: '@angular-devkit/build-angular:browser',
                  options: {
                    outputPath: 'dist/ng-test',
                    index: 'src/index.html',
                    main: 'src/main.ts',
                    polyfills: 'src/polyfills.ts',
                    tsConfig: 'tsconfig.app.json',
                    aot: true,
                    assets: [ 'src/favicon.ico', 'src/assets' ],
                    styles: [ 'src/styles.sass' ],
                    scripts: []
                  },
                  configurations: {
                    production: {
                      fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.prod.ts' } ],
                      optimization: true,
                      outputHashing: 'all',
                      sourceMap: false,
                      extractCss: true,
                      namedChunks: false,
                      extractLicenses: true,
                      vendorChunk: false,
                      buildOptimizer: true,
                      budgets: [ { type: 'initial', maximumWarning: '2mb', maximumError: '5mb' }, { type: 'anyComponentStyle', maximumWarning: '6kb', maximumError: '10kb' } ]
                    }
                  }
                },
                serve: {
                  builder: '@angular-devkit/build-angular:dev-server',
                  options: { browserTarget: 'ng-test:build' },
                  configurations: { production: { browserTarget: 'ng-test:build:production' } }
                },
                'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: 'ng-test:build' } },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    main: 'src/test.ts',
                    polyfills: 'src/polyfills.ts',
                    tsConfig: 'tsconfig.spec.json',
                    karmaConfig: 'karma.conf.js',
                    assets: [ 'src/favicon.ico', 'src/assets' ],
                    styles: [ 'src/styles.sass' ],
                    scripts: []
                  }
                },
                lint: {
                  builder: '@angular-devkit/build-angular:tslint',
                  options: { tsConfig: [ 'tsconfig.app.json', 'tsconfig.spec.json', 'e2e/tsconfig.json' ], exclude: [ '**/node_modules/**' ] }
                },
                e2e: {
                  builder: '@angular-devkit/build-angular:protractor',
                  options: { protractorConfig: 'e2e/protractor.conf.js', devServerTarget: 'ng-test:serve' },
                  configurations: { production: { devServerTarget: 'ng-test:serve:production' } }
                }
              }
            }
          },
          defaultProject: 'ng-test'
        },
        main: '// This file is required by karma.conf.js and loads recursively all the .spec and framework files\n' +
          '\n' +
          "import 'zone.js/dist/zone-testing';\n" +
          "import { getTestBed } from '@angular/core/testing';\n" +
          'import {\n' +
          '  BrowserDynamicTestingModule,\n' +
          '  platformBrowserDynamicTesting\n' +
          "} from '@angular/platform-browser-dynamic/testing';\n" +
          '\n' +
          'declare const require: {\n' +
          '  context(path: string, deep?: boolean, filter?: RegExp): {\n' +
          '    keys(): string[];\n' +
          '    <T>(id: string): T;\n' +
          '  };\n' +
          '};\n' +
          '\n' +
          '// First, initialize the Angular testing environment.\n' +
          'getTestBed().initTestEnvironment(\n' +
          '  BrowserDynamicTestingModule,\n' +
          '  platformBrowserDynamicTesting()\n' +
          ');\n' +
          '// Then we find all the tests.\n' +
          '\n' +
          '// And load the modules.\n' +
          '\n'
      }
    },
    testFramework: { version: 'jasmine@3.5.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3', autoDetected: true },
    env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    files: [
      { pattern: 'src/**/*.spec.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/polyfills.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/main.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/index.html', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.base.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.wallaby.ts', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 2 },
      { pattern: 'src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 3 }
    ],
    tests: [ { pattern: 'src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 4 } ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#1313788472'
  },
  packageJSON: {
    dependencies: {
      '@angular/animations': '~10.0.0',
      '@angular/common': '~10.0.0',
      '@angular/compiler': '~10.0.0',
      '@angular/core': '~10.0.0',
      '@angular/forms': '~10.0.0',
      '@angular/platform-browser': '~10.0.0',
      '@angular/platform-browser-dynamic': '~10.0.0',
      '@angular/router': '~10.0.0',
      rxjs: '~6.5.5',
      tslib: '^2.0.0',
      'zone.js': '~0.10.3'
    },
    devDependencies: {
      '@angular-devkit/build-angular': '~0.1000.0',
      '@angular/cli': '~10.0.0',
      '@angular/compiler-cli': '~10.0.0',
      '@types/jasmine': '~3.5.0',
      '@types/jasmine-given': '^2.6.4',
      '@types/jasminewd2': '~2.0.3',
      '@types/node': '^12.11.1',
      codelyzer: '^6.0.0-next.1',
      'jasmine-core': '~3.5.0',
      'jasmine-given': '^2.6.4',
      'jasmine-spec-reporter': '~5.0.0',
      karma: '~5.0.0',
      'karma-chrome-launcher': '~3.1.0',
      'karma-coverage-istanbul-reporter': '~3.0.2',
      'karma-jasmine': '~3.3.0',
      'karma-jasmine-given': '^0.1.1',
      'karma-jasmine-html-reporter': '^1.5.0',
      protractor: '~7.0.0',
      'ts-node': '~8.3.0',
      tslint: '~6.1.0',
      typescript: '~3.9.5'
    }
  },
  fs: { numberOfFiles: 8 },
  debug: [
    '2020-06-28T21:21:47.739Z angular/cli config Detected Angular CLI.\n',
    '2020-06-28T21:21:49.739Z angular/cli karma project config Using virtual C:/Angular/ng-test/src/test.ts.\n',
    '2020-06-28T21:21:49.761Z project Wallaby Node version: v12.18.1\n',
    '2020-06-28T21:21:49.761Z project Wallaby config: C:\\Angular\\ng-test\\auto.detect\n',
    '2020-06-28T21:21:50.392Z project File cache: C:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.212\\projects\\d624378bbdd2ae13\n',
    '2020-06-28T21:21:50.448Z uiService Listening port 51235\n',
    '2020-06-28T21:21:50.512Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2020-06-28T21:21:50.512Z workers Starting run worker instance #0\n',
    '2020-06-28T21:21:50.513Z workers Starting run worker instance #1\n',
    '2020-06-28T21:21:50.513Z workers Starting run worker instance #2\n',
    '2020-06-28T21:21:50.513Z workers Starting run worker instance #3\n',
    '2020-06-28T21:21:50.513Z workers Starting run worker instance #4\n',
    '2020-06-28T21:21:50.513Z workers Starting run worker instance #5\n',
    '2020-06-28T21:21:50.515Z workers Web server is listening at 4580\n',
    '2020-06-28T21:21:50.521Z project Stopping process pool\n',
    '2020-06-28T21:21:50.521Z project File cache is up-to-date, starting full test run\n',
    '2020-06-28T21:21:50.525Z project Running postprocessor\n',
    '2020-06-28T21:21:50.527Z postprocessor Processing started.\n',
    '2020-06-28T21:21:50.527Z postprocessor Initializing.\n',
    '2020-06-28T21:21:50.527Z postprocessor Initializing entry.\n',
    '2020-06-28T21:21:50.527Z postprocessor Sanitizing configuration.\n',
    '2020-06-28T21:21:50.527Z postprocessor Adjusting configuration.\n',
    '2020-06-28T21:21:50.527Z postprocessor Creating compiler.\n',
    '2020-06-28T21:21:51.460Z postprocessor Customizing compiler.\n',
    '2020-06-28T21:21:51.460Z postprocessor Compilation started.\n',
    '2020-06-28T21:21:53.622Z workers Started run worker instance (immediate) #0\n',
    '2020-06-28T21:21:53.622Z workers Started run worker instance (immediate) #1\n',
    '2020-06-28T21:21:53.622Z workers Started run worker instance (immediate) #2\n',
    '2020-06-28T21:21:53.622Z workers Started run worker instance (immediate) #3\n',
    '2020-06-28T21:21:53.622Z workers Started run worker instance (immediate) #4\n',
    '2020-06-28T21:21:53.622Z workers Started run worker instance (immediate) #5\n',
    '2020-06-28T21:21:55.841Z postprocessor Compilation finished.\n',
    '2020-06-28T21:21:56.287Z postprocessor Emitting 325 files.\n',
    '2020-06-28T21:21:56.289Z postprocessor Processing finished.\n',
    '2020-06-28T21:21:56.316Z project Postprocessor execution finished\n',
    '2020-06-28T21:21:56.316Z project Test run started; run priority: 3\n',
    '2020-06-28T21:21:56.317Z project Running all tests\n',
    '2020-06-28T21:21:56.325Z workers Starting test run, priority: 3\n',
    '2020-06-28T21:21:56.325Z chromeRunner Starting sandbox [worker #0, session #fyl8m]\n',
    '2020-06-28T21:21:56.325Z chromeRunner Preparing sandbox [worker #0, session #fyl8m]\n',
    '2020-06-28T21:21:56.325Z browserRunner Total files to load in sandbox: 5\n',
    '2020-06-28T21:21:56.326Z browserRunner Sandbox is generated [worker #0, session #fyl8m]: http://localhost:4580/wallaby_sandbox0.html\n',
    '2020-06-28T21:21:56.326Z chromeRunner Prepared sandbox [worker #0, session #fyl8m]\n',
    '2020-06-28T21:21:56.326Z workers [worker #0, session #fyl8m] Running tests in sandbox\n',
    '2020-06-28T21:21:56.638Z workers [fyl8m] Loaded 0 test(s)\n',
    '2020-06-28T21:21:56.644Z workers Sandbox (active) [fyl8m] error: ReferenceError: Given is not defined\n',
    '2020-06-28T21:21:56.652Z workers [fyl8m] Run 0 test(s), skipped 0 test(s)\n',
    '2020-06-28T21:21:56.653Z workers [fyl8m] Sandbox is responsive, closing it\n',
    '2020-06-28T21:21:56.655Z project Test run finished\n',
    '2020-06-28T21:21:56.655Z project Processed console.log entries\n',
    '2020-06-28T21:21:56.655Z project Processed loading sequences\n',
    '2020-06-28T21:21:56.655Z project Processed executed tests\n',
    '2020-06-28T21:21:56.655Z project Processed code coverage\n',
    '2020-06-28T21:21:56.661Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by NikGovorov** [comment]
Hi @EtienneGhiringhelli,

To get `jasmine-given` working with Wallaby, please update your `./src/test.ts` in the following way:

```diff

// This file is required by karma.conf.js and loads recursively all the .spec and framework files

import 'zone.js/dist/zone-testing';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

declare const require: {
++(path: string): void;
  context(path: string, deep?: boolean, filter?: RegExp): {
    keys(): string[];
    <T>(id: string): T;
  };
};

++if (!((window as any).__karma__)) {
++  require('jasmine-given/dist/jasmine-given.js');
++}


// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);

```
