### ISSUE TITLE
Webstorm Plugin crashed on startup

### ISSUE THREAD

**Issue by dbartholomae** [wallabyjs/public#2467]
### Issue description or question

Just now when starting WebStorm, the Wallaby plugin crashed and was disabled by Webstorm. I could activate it again and it seems to run without problems, so this isn't urgent from my perspective, but just wanted to make sure you know about the error in case it is relevant to you.

### Java error
```
java.util.ConcurrentModificationException
    at gnu.trove.THashIterator.nextIndex(THashIterator.java:83)
    at gnu.trove.TIterator.hasNext(TIterator.java:57)
    at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
    at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
    at com.intellij.openapi.actionSystem.impl.AbbreviationManagerImpl.getAbbreviations(AbbreviationManagerImpl.java:88)
    at com.wallaby.javascript.WallabyController.Q(Unknown Source)
    at com.wallaby.javascript.WallabyController.initComponent(Unknown Source)
    at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:44)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62)
    at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:261)
    at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:269)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:321)
    at com.intellij.platform.PlatformProjectOpenProcessorKt.convertAndLoadProject(PlatformProjectOpenProcessor.kt:404)
    at com.intellij.platform.PlatformProjectOpenProcessorKt.prepareProject(PlatformProjectOpenProcessor.kt:299)
    at com.intellij.platform.PlatformProjectOpenProcessorKt.access$prepareProject(PlatformProjectOpenProcessor.kt:1)
    at com.intellij.platform.PlatformProjectOpenProcessor$Companion$openExistingProject$$inlined$runInAutoSaveDisabledMode$lambda$1.invoke(PlatformProjectOpenProcessor.kt:186)
    at com.intellij.platform.PlatformProjectOpenProcessor$Companion$openExistingProject$$inlined$runInAutoSaveDisabledMode$lambda$1.invoke(PlatformProjectOpenProcessor.kt:57)
    at com.intellij.platform.ProjectUiFrameAllocator$run$1$progressTask$1.run(ProjectFrameAllocator.kt:85)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932)
    at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:482)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:77)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

### Wallaby diagnostics report

From running Wallaby again after it crashed, not from the crash itself.

```
{
  editorVersion: 'WebStorm 2020.1.2',
  pluginVersion: '1.0.178',
  editorType: 'IntelliJ',
  osVersion: 'win32 10.0.18363',
  nodeVersion: 'v12.16.0',
  coreVersion: '1.0.920',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              browser: false,
              cache: true,
              cacheDirectory: 'C:\\Users\\danie\\AppData\\Local\\Temp\\jest',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '\\\\node_modules\\\\' ],
              cwd: 'D:\\repos\\kata-bootstraps\\ts\\typescript-jest-fast-check',
              dependencyExtractor: null,
              detectLeaks: undefined,
              detectOpenHandles: undefined,
              displayName: undefined,
              errorOnDeprecated: false,
              extraGlobals: undefined,
              filter: null,
              forceCoverageMatch: [],
              globalSetup: null,
              globalTeardown: null,
              globals: {},
              haste: { computeSha1: false, providesModuleNodeModules: [], throwOnModuleCollision: false },
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [ 'ts', 'js', 'json', 'node' ],
              moduleLoader: undefined,
              moduleNameMapper: {},
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              name: '9c530eeb8521f1cefa78c4a0114e7af3',
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: null,
              restoreMocks: false,
              rootDir: 'D:\\repos\\kata-bootstraps\\ts\\typescript-jest-fast-check',
              roots: [ 'D:\\repos\\kata-bootstraps\\ts\\typescript-jest-fast-check\\src' ],
              runner: 'jest-runner',
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: 'D:\\repos\\kata-bootstraps\\ts\\typescript-jest-fast-check\\node_modules\\jest-environment-node\\build\\index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [],
              testPathIgnorePatterns: [ '\\\\node_modules\\\\' ],
              testRegex: [ '(\\.|\\\\)(test)\\.(js|tsx?)$' ],
              testRunner: 'D:\\repos\\kata-bootstraps\\ts\\typescript-jest-fast-check\\node_modules\\jest-jasmine2\\build\\index.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [ [ '^.+\\.ts?$', 'D:\\repos\\kata-bootstraps\\ts\\typescript-jest-fast-check\\node_modules\\ts-jest\\dist\\index.js' ] ],
              transformIgnorePatterns: [ '\\\\node_modules\\\\' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: null,
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: 'D:\\repos\\kata-bootstraps\\ts\\typescript-jest-fast-check\\coverage',
            coverageReporters: [ 'json', 'lcov', 'text', 'html' ],
            coverageThreshold: null,
            detectLeaks: undefined,
            detectOpenHandles: undefined,
            enabledTestsMap: undefined,
            errorOnDeprecated: false,
            expand: false,
            extraGlobals: undefined,
            filter: null,
            findRelatedTests: undefined,
            forceExit: undefined,
            globalSetup: null,
            globalTeardown: null,
            json: false,
            lastCommit: undefined,
            listTests: undefined,
            logHeapUsage: undefined,
            maxConcurrency: 5,
            maxWorkers: 7,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: undefined,
            onlyFailures: undefined,
            outputFile: undefined,
            passWithNoTests: undefined,
            projects: null,
            replname: undefined,
            reporters: undefined,
            rootDir: 'D:\\repos\\kata-bootstraps\\ts\\typescript-jest-fast-check',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: null,
            testSequencer: 'D:\\repos\\kata-bootstraps\\ts\\typescript-jest-fast-check\\node_modules\\@jest\\test-sequencer\\build\\index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: null,
            watch: false,
            watchAll: undefined,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [ 'src' ],
            watchPathIgnorePatterns: [ '\\\\node_modules\\\\', '\\.\\\\dist\\\\|\\.\\\\build\\\\|\\.\\\\coverage\\\\|\\\\\\.cache\\\\|\\\\\\.idea\\\\|\\\\\\.vscode\\\\|\\\\\\.git\\\\|\\\\\\.gitlab\\\\' ],
            testPathIgnorePatterns: [ '\\\\node_modules\\\\', '\\.\\\\dist\\\\|\\.\\\\build\\\\|\\.\\\\coverage\\\\|\\\\\\.cache\\\\|\\\\\\.idea\\\\|\\\\\\.vscode\\\\|\\\\\\.git\\\\|\\\\\\.gitlab\\\\' ],
            testMatch: [],
            testRegex: [ '(\\.|\\\\)(test)\\.(js|tsx?)$' ]
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    globalSetup: false,
    micromatch: true,
    files: [
      { pattern: '\\\\node_modules\\\\', regexp: /\\node_modules\\/, ignore: true, trigger: true, load: true },
      {
        pattern: '\\.\\\\dist\\\\|\\.\\\\build\\\\|\\.\\\\coverage\\\\|\\\\\\.cache\\\\|\\\\\\.idea\\\\|\\\\\\.vscode\\\\|\\\\\\.git\\\\|\\\\\\.gitlab\\\\',
        regexp: /\.\\dist\\|\.\\build\\|\.\\coverage\\|\\\.cache\\|\\\.idea\\|\\\.vscode\\|\\\.git\\|\\\.gitlab\\/,
        ignore: true,
        trigger: true,
        load: true
      },
      { pattern: 'src/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '(\\.|\\\\)(test)\\.(js|tsx?)$', regexp: /(\.|\\)(test)\.(js|tsx?)$/, ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '\\\\node_modules\\\\', regexp: /\\node_modules\\/, ignore: true, trigger: true, load: true, test: true },
      {
        pattern: '\\.\\\\dist\\\\|\\.\\\\build\\\\|\\.\\\\coverage\\\\|\\\\\\.cache\\\\|\\\\\\.idea\\\\|\\\\\\.vscode\\\\|\\\\\\.git\\\\|\\\\\\.gitlab\\\\',
        regexp: /\.\\dist\\|\.\\build\\|\.\\coverage\\|\\\.cache\\|\\\.idea\\|\\\.vscode\\|\\\.git\\|\\\.gitlab\\/,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      { pattern: '(\\.|\\\\)(test)\\.(js|tsx?)$', regexp: /(\.|\\)(test)\.(js|tsx?)$/, ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: 'C:\\Program Files\\nodejs\\node.exe', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#2036667759'
  },
  packageJSON: {
    dependencies: {},
    devDependencies: {
      '@types/jest': '24.0.23',
      '@types/node': '12.12.8',
      'babel-core': '6.26.3',
      'babel-jest': '24.9.0',
      'cross-env': '6.0.3',
      'fast-check': '1.18.1',
      jest: '24.9.0',
      'ts-jest': '24.1.0',
      tslint: '5.20.1',
      'tslint-config-prettier': '1.18.0',
      typescript: '3.7.2'
    }
  },
  fs: { numberOfFiles: 3 },
  debug: [
    '2020-06-30T07:51:08.292Z angular/cli config Angular CLI not found.\n',
    '2020-06-30T07:51:08.664Z jest/config Detected Jest.\n',
    '2020-06-30T07:51:08.666Z jest/config Configured Jest.\n',
    '2020-06-30T07:51:08.671Z project Wallaby Node version: v12.16.0\n',
    '2020-06-30T07:51:08.671Z project Wallaby config: D:\\repos\\kata-bootstraps\\ts\\typescript-jest-fast-check\\auto.detect\n',
    '2020-06-30T07:51:10.507Z project File cache: C:\\Users\\danie\\AppData\\Local\\JetBrains\\WebStorm2020.1\\wallaby\\projects\\229cd9eaafcf260d\n',
    '2020-06-30T07:51:10.610Z uiService Listening port 51235\n',
    '2020-06-30T07:51:10.632Z project package.json file change detected, invalidating local cache\n',
    '2020-06-30T07:51:10.660Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2020-06-30T07:51:10.660Z workers Starting run worker instance #0\n',
    '2020-06-30T07:51:10.661Z workers Starting run worker instance #1\n',
    '2020-06-30T07:51:10.661Z workers Starting run worker instance #2\n',
    '2020-06-30T07:51:10.661Z workers Starting run worker instance #3\n',
    '2020-06-30T07:51:10.661Z workers Starting run worker instance #4\n',
    '2020-06-30T07:51:10.661Z workers Starting run worker instance #5\n',
    '2020-06-30T07:51:10.663Z workers Web server is listening at 51905\n',
    '2020-06-30T07:51:10.663Z project File cache requires some updates, waiting required files from IDE\n',
    '2020-06-30T07:51:10.708Z project Stopping process pool\n',
    '2020-06-30T07:51:10.712Z project Test run started; run priority: 3\n',
    '2020-06-30T07:51:10.713Z project Running all tests\n',
    '2020-06-30T07:51:10.716Z workers Starting test run, priority: 3\n',
    '2020-06-30T07:51:10.716Z nodeRunner Starting sandbox [worker #0, session #9xgzd]\n',
    '2020-06-30T07:51:10.716Z nodeRunner Preparing sandbox [worker #0, session #9xgzd]\n',
    '2020-06-30T07:51:10.949Z workers Started run worker instance (delayed) #2\n',
    '2020-06-30T07:51:10.950Z workers Started run worker instance (delayed) #1\n',
    '2020-06-30T07:51:10.952Z workers Started run worker instance (delayed) #4\n',
    '2020-06-30T07:51:10.954Z workers Started run worker instance (delayed) #5\n',
    '2020-06-30T07:51:10.957Z workers Started run worker instance (delayed) #0\n',
    '2020-06-30T07:51:10.957Z nodeRunner Prepared sandbox [worker #0, session #9xgzd]\n',
    '2020-06-30T07:51:10.957Z workers [worker #0, session #9xgzd] Running tests in sandbox\n',
    '2020-06-30T07:51:10.963Z workers Started run worker instance (delayed) #3\n',
    '2020-06-30T07:51:15.582Z workers [9xgzd] Loaded unknown number of test(s)\n',
    '2020-06-30T07:51:15.583Z workers [9xgzd] Test executed: helps to find a typo\n',
    '2020-06-30T07:51:15.585Z workers [9xgzd] Test executed: should log everything using the remote logger\n',
    '2020-06-30T07:51:15.586Z workers [9xgzd] Test executed: should log something using the remote logger\n',
    '2020-06-30T07:51:15.587Z workers [9xgzd] Test executed: should log something using the remote logger\n',
    '2020-06-30T07:51:15.589Z workers [9xgzd] Run 4 test(s), skipped 0 test(s)\n',
    '2020-06-30T07:51:15.591Z workers [9xgzd] Sandbox is responsive, closing it\n',
    '2020-06-30T07:51:15.593Z project Test run finished\n',
    '2020-06-30T07:51:15.593Z project Processed console.log entries\n',
    '2020-06-30T07:51:15.593Z project Processed loading sequences\n',
    '2020-06-30T07:51:15.594Z project Processed executed tests\n',
    '2020-06-30T07:51:15.595Z project Processed code coverage\n',
    '2020-06-30T07:51:15.613Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by smcenlly** [comment]
Thanks for sharing your report. We'll take a look and see if we can work out what happened. In the meantime, if this happens again, please let us know.

**Comment by smcenlly** [comment]
We've taken a look at the code in question and it looks like this may be an IntelliJ issue. Can you please let us know what editor and version you are/were using?

**Comment by smcenlly** [comment]
We've updated our Plugin for JetBrains editors so that it at least should not crash in this scenario. As per my previous comment, please let us know if this happens again. If the problem recurs, you should now get a warning on startup with additional details in your IntelliJ log file.
