### ISSUE TITLE
Support for the experimental syntax 'jsx' isn't currently enabled (7:51):

### ISSUE THREAD

**Issue by lemondsun** [wallabyjs/public#2468]
### Issue description or question
How to use jsx with wallaby?

### Wallaby diagnostics report

```
{
  editorVersion: '1.46.0',
  pluginVersion: '1.0.212',
  editorType: 'VSCode',
  osVersion: 'darwin 19.4.0',
  nodeVersion: 'v12.9.1',
  coreVersion: '1.0.920',
  config: {
    testFramework: { version: 'jest@0.4.3', configurator: 'jest@0.4.3', reporter: 'jest@0.4.3', starter: 'jest@0.4.3' },
    env: {
      type: 'node',
      params: {},
      runner: '<homeDir>/.nvm/versions/node/v12.9.1/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    tests: [ { pattern: 'src/tests/**/*.test.js', ignore: false, trigger: true, load: true, test: true, order: 4 } ],
    files: [
      { pattern: 'src/**/*.js', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: '**/*.test.js', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: '**/.*', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: 'src/tests/**/*.test.js.snap', ignore: false, instrument: false, trigger: true, load: true, order: 2 },
      { pattern: 'package.json', ignore: false, instrument: false, trigger: true, load: true, order: 3 }
    ],
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: { '**/*.?(lit)coffee?(.md)': [Function] },
    preprocessors: { 'package.json': [Function] },
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'module.exports = function () {\n' +
      '  return {\n' +
      "    testFramework: 'jest',\n" +
      '    env: {\n' +
      "    type: 'node',\n" +
      '    },\n' +
      "    tests: ['src/tests/**/*.test.js'],\n" +
      "    files: ['src/**/*.js', '!**/*.test.js', '!**/.*'],\n" +
      '\n' +
      '    \n' +
      '  };\n' +
      '};\n'
  },
  packageJSON: {
    dependencies: {
      '@testing-library/jest-dom': '^4.2.4',
      '@testing-library/react': '^9.5.0',
      '@testing-library/user-event': '^7.2.1',
      react: '^16.13.1',
      'react-dom': '^16.13.1',
      'react-scripts': '3.4.1',
      'react-test-renderer': '^16.13.1'
    },
    devDependencies: undefined
  },
  fs: { numberOfFiles: 6 },
  debug: [
    '2020-06-30T21:26:19.775Z project Wallaby Node version: v12.9.1\n',
    '2020-06-30T21:26:19.775Z project Wallaby config: <homeDir>/Desktop/dark-room-love-api/client/wallaby.conf.js\n',
    '2020-06-30T21:26:20.530Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.212/projects/dc59ee2e496d46ce\n',
    '2020-06-30T21:26:20.545Z uiService Listening port 51235\n',
    '2020-06-30T21:26:20.547Z project Config file change detected, invalidating local cache\n',
    '2020-06-30T21:26:20.561Z workers Parallelism for initial run: 2, for regular run: 2\n',
    '2020-06-30T21:26:20.561Z workers Starting run worker instance #0\n',
    '2020-06-30T21:26:20.561Z workers Starting run worker instance #1\n',
    '2020-06-30T21:26:20.562Z workers Web server is listening at 64208\n',
    '2020-06-30T21:26:20.562Z project File cache requires some updates, waiting required files from IDE\n',
    '2020-06-30T21:26:21.516Z workers Started run worker instance (delayed) #0\n',
    '2020-06-30T21:26:21.602Z workers Started run worker instance (delayed) #1\n',
    '2020-06-30T21:26:22.149Z project Stopping process pool\n',
    '2020-06-30T21:26:22.150Z project Running postprocessor\n',
    '2020-06-30T21:26:22.152Z postprocessor New TypeScript language service is required\n',
    "2020-06-30T21:26:22.152Z postprocessor TypeScript postprocessor will be removed because in 5 project files none were found by patterns: [ '**/*.ts?(x)' ]\n",
    '2020-06-30T21:26:22.154Z project Postprocessor execution finished\n',
    '2020-06-30T21:26:22.154Z project Postprocessor is removed as requested by itself\n',
    '2020-06-30T21:26:22.154Z project Test run started; run priority: 3\n',
    '2020-06-30T21:26:22.155Z project Running all tests\n',
    '2020-06-30T21:26:22.156Z project Test run finished\n',
    '2020-06-30T21:26:22.156Z project Test run data re-queued\n',
    '2020-06-30T21:28:35.685Z fs File changed in editor: src/App.js\n',
    '2020-06-30T21:28:35.788Z project Test run started; run priority: 3\n',
    '2020-06-30T21:28:35.788Z project Running all tests\n',
    '2020-06-30T21:28:35.794Z project Test run finished\n',
    '2020-06-30T21:28:35.794Z project Test run data re-queued\n',
    '2020-06-30T21:28:36.620Z fs File changed: src/App.js\n',
    '2020-06-30T21:28:36.621Z fs No changes detected for src/App.js\n',
    '2020-06-30T21:28:36.622Z extended-core File was not changed, but file markers may need to be synced\n',
    '2020-06-30T21:28:40.126Z fs File changed in editor: src/App.js\n',
    '2020-06-30T21:28:40.140Z project Test run started; run priority: 3\n',
    '2020-06-30T21:28:40.140Z project Running all tests\n',
    '2020-06-30T21:28:40.140Z project Test run finished\n',
    '2020-06-30T21:28:40.141Z project Test run data re-queued\n',
    '2020-06-30T21:28:41.030Z fs File changed: src/App.js\n',
    '2020-06-30T21:28:41.031Z fs No changes detected for src/App.js\n',
    '2020-06-30T21:28:41.031Z extended-core File was not changed, but file markers may need to be synced\n',
    '2020-06-30T21:29:50.976Z fs File changed in editor: src/App.js\n',
    '2020-06-30T21:29:50.989Z project Test run started; run priority: 3\n',
    '2020-06-30T21:29:50.989Z project Running all tests\n',
    '2020-06-30T21:29:50.989Z project Test run finished\n',
    '2020-06-30T21:29:50.989Z project Test run data re-queued\n',
    '2020-06-30T21:29:51.932Z fs File changed: src/App.js\n',
    '2020-06-30T21:29:51.933Z fs No changes detected for src/App.js\n',
    '2020-06-30T21:29:51.933Z extended-core File was not changed, but file markers may need to be synced\n',
    '2020-06-30T21:31:00.409Z fs File changed in editor: src/App.js\n',
    '2020-06-30T21:31:00.425Z project Test run started; run priority: 3\n',
    '2020-06-30T21:31:00.425Z project Running all tests\n',
    '2020-06-30T21:31:00.426Z project Test run finished\n',
    '2020-06-30T21:31:00.426Z project Test run data re-queued\n',
    '2020-06-30T21:31:01.356Z fs File changed: src/App.js\n',
    '2020-06-30T21:31:01.380Z fs No changes detected for src/App.js\n',
    '2020-06-30T21:31:01.380Z extended-core File was not changed, but file markers may need to be synced\n',
    '2020-06-30T21:36:33.807Z fs File changed in editor: src/App.js\n',
    '2020-06-30T21:36:33.833Z project Test run started; run priority: 3\n',
    '2020-06-30T21:36:33.833Z project Running all tests\n',
    '2020-06-30T21:36:33.836Z project Test run finished\n',
    '2020-06-30T21:36:33.836Z project Test run data re-queued\n',
    '2020-06-30T21:36:34.730Z fs File changed: src/App.js\n',
    '2020-06-30T21:36:34.732Z fs No changes detected for src/App.js\n',
    '2020-06-30T21:36:34.732Z extended-core File was not changed, but file markers may need to be synced\n',
    '2020-06-30T21:36:55.578Z fs File changed in editor: src/App.js\n',
    '2020-06-30T21:36:55.604Z project Test run started; run priority: 3\n',
    '2020-06-30T21:36:55.604Z project Running all tests\n',
    '2020-06-30T21:36:55.604Z project Test run finished\n',
    '2020-06-30T21:36:55.604Z project Test run data re-queued\n',
    '2020-06-30T21:36:56.491Z fs File changed: src/App.js\n',
    '2020-06-30T21:36:56.492Z fs No changes detected for src/App.js\n',
    '2020-06-30T21:36:56.492Z extended-core File was not changed, but file markers may need to be synced\n',
    '2020-06-30T21:36:58.158Z fs File changed in editor: src/App.js\n',
    '2020-06-30T21:36:58.183Z project Test run started; run priority: 3\n',
    '2020-06-30T21:36:58.183Z project Running all tests\n',
    '2020-06-30T21:36:58.183Z project Test run finished\n',
    '2020-06-30T21:36:58.183Z project Test run data re-queued\n',
    '2020-06-30T21:36:59.181Z fs File changed: src/App.js\n',
    '2020-06-30T21:36:59.190Z fs No changes detected for src/App.js\n',
    '2020-06-30T21:36:59.190Z extended-core File was not changed, but file markers may need to be synced\n',
    '2020-06-30T21:36:59.196Z fs File changed in editor: src/App.js\n',
    '2020-06-30T21:36:59.221Z project Test run started; run priority: 3\n',
    '2020-06-30T21:36:59.221Z project Running all tests\n',
    '2020-06-30T21:36:59.222Z project Test run finished\n',
    '2020-06-30T21:36:59.222Z project Test run data re-queued\n',
    '2020-06-30T21:36:59.770Z fs File changed in editor: src/App.js\n',
    '2020-06-30T21:36:59.784Z project Test run started; run priority: 3\n',
    '2020-06-30T21:36:59.784Z project Running all tests\n',
    '2020-06-30T21:36:59.784Z project Test run finished\n',
    '2020-06-30T21:36:59.784Z project Test run data re-queued\n',
    '2020-06-30T21:37:00.695Z fs File changed: src/App.js\n',
    '2020-06-30T21:37:00.696Z fs No changes detected for src/App.js\n',
    '2020-06-30T21:37:00.696Z extended-core File was not changed, but file markers may need to be synced\n',
    '2020-06-30T21:41:32.019Z fs File changed in editor: src/App.js\n',
    '2020-06-30T21:41:32.078Z project Test run started; run priority: 3\n',
    '2020-06-30T21:41:32.078Z project Running all tests\n',
    '2020-06-30T21:41:32.078Z project Test run finished\n',
    '2020-06-30T21:41:32.078Z project Test run data re-queued\n',
    '2020-06-30T21:41:32.914Z fs File changed: src/App.js\n',
    '2020-06-30T21:41:32.917Z fs No changes detected for src/App.js\n',
    '2020-06-30T21:41:32.917Z extended-core File was not changed, but file markers may need to be synced\n',
    '2020-06-30T21:42:32.250Z project Test run started; run priority: 3\n',
    '2020-06-30T21:42:32.250Z project Running all tests\n',
    '2020-06-30T21:42:32.252Z workers Starting test run, priority: 3\n',
    '2020-06-30T21:42:32.252Z nodeRunner Starting sandbox [worker #0, session #fu1qe]\n',
    '2020-06-30T21:42:32.252Z nodeRunner Preparing sandbox [worker #0, session #fu1qe]\n',
    '2020-06-30T21:42:32.252Z nodeRunner Prepared sandbox [worker #0, session #fu1qe]\n',
    '2020-06-30T21:42:32.253Z workers [worker #0, session #fu1qe] Running tests in sandbox\n',
    "2020-06-30T21:42:38.233Z workers Sandbox (active) [fu1qe] error: SyntaxError: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.212/projects/dc59ee2e496d46ce/instrumented/src/tests/App.test.js: Support for the experimental syntax 'jsx' isn't currently enabled (7:51):\n" +
      '\n' +
      "   5 | $_$w(6, 0, $_$c), test('renders learn react link', () => {\n" +
      '   6 |     var $_$c = $_$wf(6);\n' +
      '>  7 |     const {getByText} = ($_$w(6, 1, $_$c), render(<App/>));\n' +
      '     |                                                   ^\n' +
      '   8 |     const linkElement = ($_$w(6, 2, $_$c), getByText(/learn react/i));\n' +
      '   9 |     $_$w(6, 3, $_$c), expect(linkElement).toBeInTheDocument();\n' +
      '  10 | });\n' +
      '\n' +
      "Add @babel/plugin-transform-react-jsx (https://git.io/vb4yd) to the 'plugins' section of your Babel config to enable transformation.\n",
    "2020-06-30T21:42:38.235Z workers Failed to map the stack to user code, entry message: SyntaxError: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.212/projects/dc59ee2e496d46ce/instrumented/src/tests/App.test.js: Support for the experimental syntax 'jsx' isn't currently enabled (7:51):\n" +
      '\n' +
      "   5 | $_$w(6, 0, $_$c), test('renders learn react link', () => {\n" +
      '   6 |     var $_$c = $_$wf(6);\n' +
      '>  7 |     const {getByText} = ($_$w(6, 1, $_$c), render(<App/>));\n' +
      '     |                                                   ^\n' +
      '   8 |     const linkElement = ($_$w(6, 2, $_$c), getByText(/learn react/i));\n' +
      '   9 |     $_$w(6, 3, $_$c), expect(linkElement).toBeInTheDocument();\n' +
      '  10 | });\n' +
      '\n' +
      "Add @babel/plugin-transform-react-jsx (https://git.io/vb4yd) to the 'plugins' section of your Babel config to enable transformation., stack: SyntaxError: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.212/projects/dc59ee2e496d46ce/instrumented/src/tests/App.test.js: Support for the experimental syntax 'jsx' isn't currently enabled (7:51):\n" +
      '\n' +
      "   5 | $_$w(6, 0, $_$c), test('renders learn react link', () => {\n" +
      '   6 |     var $_$c = $_$wf(6);\n' +
      '>  7 |     const {getByText} = ($_$w(6, 1, $_$c), render(<App/>));\n' +
      '     |                                                   ^\n' +
      '   8 |     const linkElement = ($_$w(6, 2, $_$c), getByText(/learn react/i));\n' +
      '   9 |     $_$w(6, 3, $_$c), expect(linkElement).toBeInTheDocument();\n' +
      '  10 | });\n' +
      '\n' +
      "Add @babel/plugin-transform-react-jsx (https://git.io/vb4yd) to the 'plugins' section of your Babel config to enable transformation.\n" +
      '    at Parser._raise (<homeDir>/Desktop/dark-room-love-api/client/node_modules/@babel/parser/src/parser/error.js:60:45)\n' +
      '    at Parser.raiseWithData (<homeDir>/Desktop/dark-room-love-api/client/node_modules/@babel/parser/src/parser/error.js:55:17)\n' +
      '    at Parser.e\n',
    '2020-06-30T21:42:38.239Z workers Sandbox (active) [fu1qe] error: oom-love-api/client/node_modules/@babel/parser/src/parser/expression.js:174:36)\n',
    '2020-06-30T21:42:38.240Z workers Failed to map the stack to user code, entry message: oom-love-api/client/node_modules/@babel/parser/src/parser/expression.js:174:36), stack: oom-love-api/client/node_modules/@babel/parser/src/parser/expression.js:174:36)\n' +
      '    at Parser.parseStatementContent (<homeDir>/Desktop/dark-room-love-api/client/node_modules/@babel/parser/src/parser/statement.js:284:23)\n' +
      '    at Parser.parseStatement (<homeDir>/Desktop/dark-room-love-api/client/node_modules/@babel/parser/src/parser/statement.js:149:17)\n' +
      '    at Parser.parseBlockOrModuleBlockBody (<homeDir>/Desktop/dark-room-love-api/client/node_modules/@babel/parser/src/parser/statement.js:861:25)\n' +
      '    at Parser.parseBlockBody (<homeDir>/Desktop/dark-room-love-api/client/node_modules/@babel/parser/src/parser/statement.js:833:10)\n' +
      '    at Parser.parseTopLevel (<homeDir>/Desktop/dark-room-love-api/client/node_modules/@babel/parser/src/parser/statement.js:55:10)\n' +
      '    at Parser.parse (<homeDir>/Desktop/dark-room-love-api/client/node_modules/@babel/parser/src/parser/index.js:57:10)\n' +
      '    at parse (<homeDir>/Desktop/dark-room-love-api/client/node_mo\n',
    '2020-06-30T21:42:38.259Z workers [fu1qe] Run 0 test(s), skipped 0 test(s)\n',
    '2020-06-30T21:42:38.260Z workers [fu1qe] Sandbox is responsive, closing it\n',
    '2020-06-30T21:42:38.261Z project Test run finished\n',
    '2020-06-30T21:42:38.262Z project Processed console.log entries\n',
    '2020-06-30T21:42:38.262Z project Processed loading sequences\n',
    '2020-06-30T21:42:38.262Z project Processed executed tests\n',
    '2020-06-30T21:42:38.263Z project Processed code coverage\n',
    '2020-06-30T21:42:38.270Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by smcenlly** [comment]
Your project dependencies indicate that you are working with a fresh `create-react-app` project and your diagnostics report indicates that you are using a Wallaby.js configuration file.

You may delete your Wallaby configuration file and run the VS Code command `Wallaby.js: Select Configuration`  and then select the `Automatic Configuration <project directory>` option.

Our [Create React App tutorial](https://wallabyjs.com/docs/tutorial/react.html) from our website provides a step-by-step guide for using Wallaby with `create-react-app` (JSX/TSX) files.

If you continue to have problems, please let us know.
