### ISSUE TITLE
How to setup lerna for Angular / NestJS with wallaby

### ISSUE THREAD

**Issue by EtienneGhiringhelli** [wallabyjs/public#2477]
### Issue description or question

I have a lerna mono-repo including, at the moment, two projets (https://github.com/EtienneGhiringhelli/lerna-wallaby-angular-nest):
- NestJS "server side" application
- Angular "client side" application

My purpose is to be able to use WallabyJS, with or without automatic configuration, while developping without having to switch configuration between packages.

I switched the test runner form Karma to Jest for the Angular application to match with NestJS but it didn't work either.

My questions are:
- Is that even possible ?
- If yes, I read multiple time that the automatic configuration should be able to work in yarn/lerna monorepo but it doesn't, so am I doing something wrong here ?
- If no, what should I do in term of configuration ? Could you please provide help ? I believe I have to install Jest at lerna level but i'm not too sure.
- I'm wishing to add more projects in this mono (shared package, ionic app for mobile, another nestjs application for webservices). Will this be working with WallabyJS ?

Thanks a lot for your help ! You product is awesome.

### Wallaby diagnostics report

**If I don't install Jest on lerna package.json:**
```
{
  editorVersion: '1.46.0',
  pluginVersion: '1.0.216',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.18363',
  nodeVersion: 'v12.18.1',
  coreVersion: '1.0.924',
  config: {},
  packageJSON: { dependencies: undefined, devDependencies: { lerna: '^3.22.0' } },
  fs: { numberOfFiles: 0 },
  debug: [
    '2020-07-10T11:05:16.269Z angular/cli config Angular CLI not found.\n',
    "2020-07-10T11:05:16.272Z jest/config Error: Module jest-cli is not found in 'E:\\Veille\\nest-auth'.\n" +
      '    at Object.<anonymous> (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:27:30081)\n' +
      '    at r (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:27:14616)\n' +
      '    at Object.next (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:27:13911)\n' +
      '    at c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:27:13820\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at i (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:27:13614)\n' +
      '    at Object.loadJest (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:27:28094)\n' +
      '    at c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:18:541\n' +
      '    at r (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:18:4567)\n' +
      '    at Object.next (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:18:3862)\n' +
      '    at c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:18:3771\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at o (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:18:3565)\n' +
      '    at r (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:18:229)\n' +
      '    at c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:18:3242\n' +
      '    at r (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:18:4567)\n' +
      '    at Object.next (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:18:3862)\n' +
      '    at c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:18:3771\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at o (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:18:3565)\n' +
      '    at i (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:18:3123)\n' +
      '    at Config.<anonymous> (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:15:15573)\n' +
      '    at r (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:15:9063)\n' +
      '    at Object.next (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:15:8358)\n' +
      '    at s (c:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\wallaby\\server.js:15:8107)\n'
  ]
}
```

**If I do install Jest on lerna package.json:**
```
{
  editorVersion: '1.46.0',
  pluginVersion: '1.0.216',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.18363',
  nodeVersion: 'v12.18.1',
  coreVersion: '1.0.924',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: 'C:\\Users\\Etienne\\AppData\\Local\\Temp\\jest',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '\\\\node_modules\\\\' ],
              cwd: 'E:\\Veille\\nest-auth',
              dependencyExtractor: undefined,
              detectLeaks: undefined,
              detectOpenHandles: undefined,
              displayName: undefined,
              errorOnDeprecated: false,
              extraGlobals: [],
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, throwOnModuleCollision: false },
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [ 'js', 'json', 'jsx', 'ts', 'tsx', 'node' ],
              moduleLoader: undefined,
              moduleNameMapper: [],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              name: 'e76dbb77578416be268898e5719077b8',
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: 'E:\\Veille\\nest-auth',
              roots: [ 'E:\\Veille\\nest-auth' ],
              runner: 'jest-runner',
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: 'E:\\Veille\\nest-auth\\node_modules\\jest-environment-jsdom\\build\\index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
              testPathIgnorePatterns: [ '\\\\node_modules\\\\' ],
              testRegex: [],
              testRunner: 'E:\\Veille\\nest-auth\\node_modules\\jest-jasmine2\\build\\index.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [ [ '^.+\\.[jt]sx?$', 'E:\\Veille\\nest-auth\\node_modules\\babel-jest\\build\\index.js', {} ] ],
              transformIgnorePatterns: [ '\\\\node_modules\\\\' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: [],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: 'E:\\Veille\\nest-auth\\coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: undefined,
            detectOpenHandles: undefined,
            enabledTestsMap: undefined,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: undefined,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 7,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: undefined,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: 'E:\\Veille\\nest-auth',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: 'E:\\Veille\\nest-auth\\node_modules\\@jest\\test-sequencer\\build\\index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '\\\\node_modules\\\\', '\\.\\\\dist\\\\|\\.\\\\build\\\\|\\.\\\\coverage\\\\|\\\\\\.cache\\\\|\\\\\\.idea\\\\|\\\\\\.vscode\\\\|\\\\\\.git\\\\|\\\\\\.gitlab\\\\' ],
            testPathIgnorePatterns: [ '\\\\node_modules\\\\', '\\.\\\\dist\\\\|\\.\\\\build\\\\|\\.\\\\coverage\\\\|\\\\\\.cache\\\\|\\\\\\.idea\\\\|\\\\\\.vscode\\\\|\\\\\\.git\\\\|\\\\\\.gitlab\\\\' ],
            testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    globalSetup: false,
    micromatch: true,
    files: [
      { pattern: '\\\\node_modules\\\\', regexp: /\\node_modules\\/, ignore: true, trigger: true, load: true },
      {
        pattern: '\\.\\\\dist\\\\|\\.\\\\build\\\\|\\.\\\\coverage\\\\|\\\\\\.cache\\\\|\\\\\\.idea\\\\|\\\\\\.vscode\\\\|\\\\\\.git\\\\|\\\\\\.gitlab\\\\',
        regexp: /\.\\dist\\|\.\\build\\|\.\\coverage\\|\\\.cache\\|\\\.idea\\|\\\.vscode\\|\\\.git\\|\\\.gitlab\\/,
        ignore: true,
        trigger: true,
        load: true
      },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '\\\\node_modules\\\\', regexp: /\\node_modules\\/, ignore: true, trigger: true, load: true, test: true },
      {
        pattern: '\\.\\\\dist\\\\|\\.\\\\build\\\\|\\.\\\\coverage\\\\|\\\\\\.cache\\\\|\\\\\\.idea\\\\|\\\\\\.vscode\\\\|\\\\\\.git\\\\|\\\\\\.gitlab\\\\',
        regexp: /\.\\dist\\|\.\\build\\|\.\\coverage\\|\\\.cache\\|\\\.idea\\|\\\.vscode\\|\\\.git\\|\\\.gitlab\\/,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 }
    ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: 'C:\\Program Files\\nodejs\\node.exe', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#2129121490'
  },
  packageJSON: { dependencies: undefined, devDependencies: { lerna: '^3.22.0' } },
  fs: { numberOfFiles: 64 },
  debug: [
    '2020-07-10T11:01:33.868Z angular/cli config Angular CLI not found.\n',
    '2020-07-10T11:01:33.938Z jest/config Detected Jest.\n',
    '2020-07-10T11:01:33.938Z jest/config Configured Jest.\n',
    '2020-07-10T11:01:33.939Z project Wallaby Node version: v12.18.1\n',
    '2020-07-10T11:01:33.939Z project Wallaby config: E:\\Veille\\nest-auth\\auto.detect\n',
    '2020-07-10T11:01:34.786Z project File cache: C:\\Users\\Etienne\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.216\\projects\\eec1c6a73425c455\n',
    '2020-07-10T11:01:34.839Z uiService Listening port 51236\n',
    '2020-07-10T11:01:34.863Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2020-07-10T11:01:34.863Z workers Starting run worker instance #0\n',
    '2020-07-10T11:01:34.864Z workers Starting run worker instance #1\n',
    '2020-07-10T11:01:34.864Z workers Starting run worker instance #2\n',
    '2020-07-10T11:01:34.864Z workers Starting run worker instance #3\n',
    '2020-07-10T11:01:34.864Z workers Starting run worker instance #4\n',
    '2020-07-10T11:01:34.864Z workers Starting run worker instance #5\n',
    '2020-07-10T11:01:34.865Z workers Web server is listening at 1647\n',
    '2020-07-10T11:01:34.888Z project Stopping process pool\n',
    '2020-07-10T11:01:34.888Z project File cache is up-to-date, starting full test run\n',
    '2020-07-10T11:01:34.889Z project Test run started; run priority: 3\n',
    '2020-07-10T11:01:34.891Z project Running all tests\n',
    '2020-07-10T11:01:34.895Z workers Starting test run, priority: 3\n',
    '2020-07-10T11:01:34.895Z workers Distributing tests between 6 workers\n',
    '2020-07-10T11:01:34.896Z workers Running tests in parallel\n',
    '2020-07-10T11:01:34.896Z nodeRunner Starting sandbox [worker #0, session #ugeyo]\n',
    '2020-07-10T11:01:34.896Z nodeRunner Starting sandbox [worker #1, session #mwdon]\n',
    '2020-07-10T11:01:34.897Z nodeRunner Preparing sandbox [worker #0, session #ugeyo]\n',
    '2020-07-10T11:01:34.897Z nodeRunner Preparing sandbox [worker #1, session #mwdon]\n',
    '2020-07-10T11:01:35.100Z workers Started run worker instance (delayed) #0\n',
    '2020-07-10T11:01:35.100Z nodeRunner Prepared sandbox [worker #0, session #ugeyo]\n',
    '2020-07-10T11:01:35.100Z workers [worker #0, session #ugeyo] Running tests in sandbox\n',
    '2020-07-10T11:01:35.102Z workers Started run worker instance (delayed) #1\n',
    '2020-07-10T11:01:35.103Z nodeRunner Prepared sandbox [worker #1, session #mwdon]\n',
    '2020-07-10T11:01:35.103Z workers [worker #1, session #mwdon] Running tests in sandbox\n',
    '2020-07-10T11:01:35.139Z workers Started run worker instance (delayed) #4\n',
    '2020-07-10T11:01:35.139Z workers Started run worker instance (delayed) #2\n',
    '2020-07-10T11:01:35.142Z workers Started run worker instance (delayed) #3\n',
    '2020-07-10T11:01:35.143Z workers Started run worker instance (delayed) #5\n',
    '2020-07-10T11:01:37.397Z workers Sandbox (active) [ugeyo] error: Cannot use import statement outside a module\n',
    '2020-07-10T11:01:37.400Z workers [ugeyo] Run 0 test(s), skipped 0 test(s)\n',
    '2020-07-10T11:01:37.401Z workers [ugeyo] Sandbox is responsive, closing it\n',
    '2020-07-10T11:01:37.466Z workers Sandbox (active) [mwdon] error: E:\\Veille\\nest-auth\\packages\\server\\src\\app.controller.spec.ts: Unexpected token, expected ";" (6:19)\n' +
      '\n' +
      '  4 | \n' +
      "  5 | describe('AppController', () => {\n" +
      '> 6 |   let appController: AppController;\n' +
      '    |                    ^\n' +
      '  7 | \n' +
      '  8 |   beforeEach(async () => {\n' +
      '  9 |     const app: TestingModule = await Test.createTestingModule({\n',
    '2020-07-10T11:01:37.467Z workers [mwdon] Run 0 test(s), skipped 0 test(s)\n',
    '2020-07-10T11:01:37.469Z workers [mwdon] Sandbox is responsive, closing it\n',
    '2020-07-10T11:01:37.471Z workers Failed to map the stack to user code, entry message: E:\\Veille\\nest-auth\\packages\\server\\src\\app.controller.spec.ts: Unexpected token, expected ";" (6:19)\n' +
      '\n' +
      '  4 | \n' +
      "  5 | describe('AppController', () => {\n" +
      '> 6 |   let appController: AppController;\n' +
      '    |                    ^\n' +
      '  7 | \n' +
      '  8 |   beforeEach(async () => {\n' +
      '  9 |     const app: TestingModule = await Test.createTestingModule({, stack: SyntaxError: E:\\Veille\\nest-auth\\packages\\server\\src\\app.controller.spec.ts: Unexpected token, expected ";" (6:19)\n' +
      '\n' +
      '  4 | \n' +
      "  5 | describe('AppController', () => {\n" +
      '> 6 |   let appController: AppController;\n' +
      '    |                    ^\n' +
      '  7 | \n' +
      '  8 |   beforeEach(async () => {\n' +
      '  9 |     const app: TestingModule = await Test.createTestingModule({\n' +
      '    at Parser._raise (E:\\Veille\\nest-auth\\node_modules\\@babel\\parser\\src\\parser\\error.js:60:45)\n' +
      '    at Parser.raiseWithData (E:\\Veille\\nest-auth\\node_modules\\@babel\\parser\\src\\parser\\error.js:55:17)\n' +
      '    at Parser.raise (E:\\Veille\\nest-auth\\node_modules\\@babel\\parser\\src\\parser\\error.js:39:17)\n' +
      '    at Parser.unexpected (E:\\Veille\\nest-auth\\node_modules\\@babel\\parser\\src\\parser\\util.js:152:16)\n' +
      '    at Parser.semicolon (E:\\Veille\\nest-auth\\node_modules\\@babel\\parser\\src\\parser\\util.js:122:40)\n' +
      '    at Parser.parseVarStatement (E:\\Veille\\nest-auth\\node_modules\\@babel\\parser\\src\\parser\\statement.js:687:10)\n' +
      '    at Parser.parseStatementContent (E:\\Veille\\nest-auth\\node_modules\\@babel\\\n',
    '2020-07-10T11:01:37.471Z workers Merging parallel test run results\n',
    '2020-07-10T11:01:37.472Z project Test run finished\n',
    '2020-07-10T11:01:37.472Z project Processed console.log entries\n',
    '2020-07-10T11:01:37.472Z project Processed loading sequences\n',
    '2020-07-10T11:01:37.472Z project Processed executed tests\n',
    '2020-07-10T11:01:37.473Z project Processed code coverage\n',
    '2020-07-10T11:01:37.480Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by smcenlly** [comment]
Thanks for the sample repo!

To answer your questions

> Is it possible to use Wallaby on your mono-repo without having to switch configuration between packages.

Yes - with one caveat. All of your projects need to use the same testing framework and runtime (e.g. jest/node, karma/browser/webpack). Jest will definitely be easiest for you.

> I read multiple time that the automatic configuration should be able to work in yarn/lerna monorepo but it doesn't, so am I doing something wrong here ?

Wallaby provides first class support for Nx/Nrwl mono-repos but not for lerna. Having said that we can get this working without too much trouble.

For your sample repo, to get Wallaby working, Jest must be installed in the project root (at the lerna level) as you suggested. You must also configure jest to run from your mono-repo root. To do this:
1. Install `jest` at the lerna level
2. Configure `jest` to run for your entire mono-repo using `npx jest` from the CLI at the mono-repo root. 
  a. Move all jest configuration from `package.json` into `jest.config.js` files.
  b. Configure jest to run from the mono-repo root:

```javascript
module.exports = { 
  projects: [
    '<rootDir>/packages/ng-jest/jest.config.js', 
    '<rootDir>/packages/server/jest.config.js',
  ] 
};
```  

We've created a [pull request](https://github.com/EtienneGhiringhelli/lerna-wallaby-angular-nest/pull/1) for you to take these changes into the sample repo you provided to us.

**Comment by EtienneGhiringhelli** [comment]
Thank you very much, it works perfectly !

Nice support you provide here 👍
