### ISSUE TITLE
Failed run test by customizing react-script for create-react-app

### ISSUE THREAD

**Issue by anna-luyufeng** [wallabyjs/public#2489]
### Issue description or question

I customized the configuration by following [this article](https://auth0.com/blog/how-to-configure-create-react-app/) and configured the wallaby.js in manual mode.
I replaced the `react-scripts` into my customized script package name (e.g.`myname-react-scripts`).
But it still can't run the testing with the error as below:

```
[Error] Runtime error: ./node_modules/jest-resolve/build/index.js:290 
[Error]       } catch {} 
[Error]               ^ 
[Error] SyntaxError: Unexpected token { 
[Error]     at createScript (vm.js:80:10) 
[Error]     at Object.runInThisContext (vm.js:152:10) 
[Error]     at Module._compile (module.js:624:28) 
[Error]     at Module._extensions..js (module.js:671:10) 
[Error]     at Module.load (module.js:573:32) 
[Error]     at tryModuleLoad (module.js:513:12) 
[Error]     at Function.Module._load (module.js:505:3) 
[Error]     at Module.require (module.js:604:17) 
[Error]     at require (internal/module.js:11:18) 
[Error]     at _jestResolve (./node_modules/jest-config/build/utils.js:29:39) 
[Error]     at resolveWithPrefix (./node_modules/jest-config/build/utils.js:201:16) 
[Error]     at getTestEnvironment (./node_modules/jest-config/build/utils.js:247:3) 
[Error]     at Object.normalize (./node_modules/jest-config/build/normalize.js:667:59) 
[Error]     at WebSocket.emit (events.js:159:13) 
[Error]     at afterWrite (_stream_writable.js:466:3) 
[Error]     at onwrite (_stream_writable.js:457:7) 
[Error]     at InflateRaw.afterTransform (_stream_transform.js:89:3) 
[Error]     at Zlib.processCallback (zlib.js:576:8) 
```

### Wallaby diagnostics report

```
{ editorVersion: '1.46.1',
  pluginVersion: '1.0.222',
  editorType: 'VSCode',
  osVersion: 'darwin 19.5.0',
  nodeVersion: 'v9.3.0',
  coreVersion: '1.0.939',
  config: 
   { files: [ [Object], [Object], [Object], [Object], [Object] ],
     tests: [ [Object] ],
     env: 
      { type: 'node',
        params: {},
        runner: '<homeDir>/.nvm/versions/node/v9.3.0/bin/node',
        viewportSize: [Object],
        options: [Object],
        bundle: true },
     compilers: 
      { '**/*.js?(x)': [Function],
        '**/*.?(lit)coffee?(.md)': [Function] },
     testFramework: 
      { version: 'jest@0.4.3',
        configurator: 'jest@0.4.3',
        reporter: 'jest@0.4.3',
        starter: 'jest@0.4.3' },
     diagnostics: {},
     filesWithNoCoverageCalculated: [],
     runAllTestsInAffectedTestFile: false,
     updateNoMoreThanOneSnapshotPerTestFileRun: false,
     preprocessors: { 'package.json': [Function] },
     maxConsoleMessagesPerTest: 100,
     autoConsoleLog: true,
     delays: { run: 0, edit: 100, update: 0 },
     workers: { initial: 0, regular: 0, recycle: false },
     teardown: undefined,
     hints: 
      { ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
        ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
        commentAutoLog: '?',
        testFileSelection: [Object] },
     automaticTestFileSelection: true,
     runSelectedTestsOnly: false,
     extensions: {},
     reportUnhandledPromises: true,
     slowTestThreshold: 75,
     lowCoverageThreshold: 80,
     loose: true,
     configCode: 'module.exports = function (wallaby) {\n  // Babel, jest-cli and some other modules may be located under\n  // react-scripts/node_modules, so need to let node.js know about it\n  var path = require(\'path\');\n  process.env.NODE_PATH +=\n    path.delimiter +\n    path.join(__dirname, \'node_modules\') +\n    path.delimiter +\n    path.join(__dirname, \'node_modules/snapask-react-scripts/node_modules\');\n  require(\'module\').Module._initPaths();\n\n  return {\n    files: [\n      \'jsconfig.json\',\n      \'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)\',\n      \'!src/**/*.test.js?(x)\',\n    ],\n\n    tests: [\'src/**/*.test.js?(x)\'],\n\n    env: {\n      type: \'node\',\n    },\n\n    compilers: {\n      \'**/*.js?(x)\': wallaby.compilers.babel({\n        presets: [\'react-app\'],\n      }),\n    },\n\n    setup: (wallaby) => {\n      const createJestConfigUtil = require(\'snapask-react-scripts/scripts/utils/createJestConfig\');\n      const jestConfig = createJestConfigUtil((p) =>\n        require.resolve(\'snapask-react-scripts/\' + p)\n      );\n      Object.keys(jestConfig.transform || {}).forEach(\n        (k) =>\n          ~k.indexOf(\'^.+\\\\.(js|jsx\') && void delete jestConfig.transform[k]\n      );\n      delete jestConfig.testEnvironment;\n      wallaby.testFramework.configure(jestConfig);\n    },\n\n    testFramework: \'jest\',\n  };\n};\n' },
  packageJSON: 
   { dependencies: 
      { '@material-ui/core': '^4.11.0',
        '@testing-library/jest-dom': '^4.2.4',
        '@testing-library/react': '^9.3.2',
        '@testing-library/user-event': '^7.1.2',
        axios: '^0.19.2',
        classnames: '^2.2.6',
        fingerprintjs2: '^2.1.0',
        'node-sass': '^4.14.1',
        'prop-types': '^15.7.2',
        react: '^16.13.1',
        'react-css-themr': '^2.1.2',
        'react-dom': '^16.13.1',
        'react-redux': '^7.1.3',
        'react-router-dom': '^5.2.0',
        'redux-devtools-extension': '^2.13.8',
        'redux-saga': '^1.1.3',
        'snapask-react-scripts': '^3.4.2' },
     devDependencies: 
      { 'eslint-config-prettier': '^6.11.0',
        'eslint-plugin-prettier': '^3.1.3',
        husky: '^4.2.5',
        'lint-staged': '^10.2.11',
        prettier: '^2.0.5',
        stylelint: '^13.6.0',
        'stylelint-config-prettier': '^8.0.1',
        'stylelint-config-recommended-scss': '^4.2.0',
        'stylelint-config-standard': '^20.0.0',
        'stylelint-order': '^4.1.0',
        'stylelint-prettier': '^1.1.2',
        'stylelint-scss': '^3.17.2' } },
  fs: { numberOfFiles: 46 },
  debug: 
   [ '2020-08-02T02:24:44.850Z project Wallaby Node version: v9.3.0\n',
     '2020-08-02T02:24:44.850Z project Wallaby config: <homeDir>/Documents/Snapask/Study-Planet-Admin/wallaby.js\n',
     '2020-08-02T02:24:45.470Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.222/projects/d9030168f18d4994\n',
     '2020-08-02T02:24:45.478Z uiService Listening port 51235\n',
     '2020-08-02T02:24:45.481Z project Config file change detected, invalidating local cache\n',
     '2020-08-02T02:24:45.497Z workers Parallelism for initial run: 6, for regular run: 3\n',
     '2020-08-02T02:24:45.498Z workers Starting run worker instance #0\n',
     '2020-08-02T02:24:45.498Z workers Starting run worker instance #1\n',
     '2020-08-02T02:24:45.498Z workers Starting run worker instance #2\n',
     '2020-08-02T02:24:45.498Z workers Starting run worker instance #3\n',
     '2020-08-02T02:24:45.498Z workers Starting run worker instance #4\n',
     '2020-08-02T02:24:45.498Z workers Starting run worker instance #5\n',
     '2020-08-02T02:24:45.498Z workers Web server is listening at 64534\n',
     '2020-08-02T02:24:45.499Z project File cache requires some updates, waiting required files from IDE\n',
     '2020-08-02T02:24:46.224Z workers Started run worker instance (delayed) #1\n',
     '2020-08-02T02:24:46.225Z workers Started run worker instance (delayed) #2\n',
     '2020-08-02T02:24:46.233Z workers Started run worker instance (delayed) #0\n',
     '2020-08-02T02:24:46.235Z workers Started run worker instance (delayed) #3\n',
     '2020-08-02T02:24:46.250Z workers Started run worker instance (delayed) #5\n',
     '2020-08-02T02:24:46.252Z workers Started run worker instance (delayed) #4\n',
     '2020-08-02T02:24:47.795Z project Compiler did not set ranges for file [src/setupTests.js]\n',
     '2020-08-02T02:24:47.883Z project Compiler did not set ranges for file [src/hooks/createContext.js]\n',
     '2020-08-02T02:24:48.011Z project Compiler did not set ranges for file [src/pages/Login/index.js]\n',
     '2020-08-02T02:24:48.024Z project Compiler did not set ranges for file [src/redux/reducers.js]\n',
     '2020-08-02T02:24:48.034Z project Compiler did not set ranges for file [src/components/PageLoading/index.js]\n',
     '2020-08-02T02:24:48.045Z project Compiler did not set ranges for file [src/components/BaseLayout/index.js]\n',
     '2020-08-02T02:24:48.054Z project Compiler did not set ranges for file [src/components/AuthGuard/index.js]\n',
     '2020-08-02T02:24:48.118Z project Re-attaching document block comment\n',
     '2020-08-02T02:24:48.225Z project Stopping process pool\n',
     '2020-08-02T02:24:48.228Z project Running postprocessor\n',
     '2020-08-02T02:24:48.243Z postprocessor New TypeScript language service is required\n',
     '2020-08-02T02:24:48.244Z postprocessor TypeScript postprocessor will be removed because in 46 project files none were found by patterns: **/*.ts?(x)\n',
     '2020-08-02T02:24:48.244Z project Postprocessor execution finished\n',
     '2020-08-02T02:24:48.244Z project Postprocessor is removed as requested by itself\n',
     '2020-08-02T02:24:48.244Z project Test run started; run priority: 3\n',
     '2020-08-02T02:24:48.244Z project Running all tests\n',
     '2020-08-02T02:24:48.247Z workers Starting test run, priority: 3\n',
     '2020-08-02T02:24:48.247Z workers Distributing tests between 6 workers\n',
     '2020-08-02T02:24:48.249Z workers Running tests in parallel\n',
     '2020-08-02T02:24:48.249Z nodeRunner Starting sandbox [worker #0, session #eatq9]\n',
     '2020-08-02T02:24:48.249Z nodeRunner Starting sandbox [worker #1, session #ni44m]\n',
     '2020-08-02T02:24:48.249Z nodeRunner Preparing sandbox [worker #0, session #eatq9]\n',
     '2020-08-02T02:24:48.249Z nodeRunner Preparing sandbox [worker #1, session #ni44m]\n',
     '2020-08-02T02:24:48.249Z nodeRunner Prepared sandbox [worker #0, session #eatq9]\n',
     '2020-08-02T02:24:48.249Z nodeRunner Prepared sandbox [worker #1, session #ni44m]\n',
     '2020-08-02T02:24:48.250Z workers [worker #0, session #eatq9] Running tests in sandbox\n',
     '2020-08-02T02:24:48.252Z workers [worker #1, session #ni44m] Running tests in sandbox\n',
     '2020-08-02T02:24:48.292Z workers Sandbox (active) [eatq9] error: Unexpected token {\n',
     '2020-08-02T02:24:48.294Z workers Failed to map the stack to user code, entry message: Unexpected token {, stack: <homeDir>/Documents/Snapask/Study-Planet-Admin/node_modules/jest-resolve/build/index.js:290\n      } catch {}\n              ^\n\nSyntaxError: Unexpected token {\n    at createScript (vm.js:80:10)\n    at Object.runInThisContext (vm.js:152:10)\n    at Module._compile (module.js:624:28)\n    at Module._0x4e5437._compile (eval at <anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.222/wallaby/node_modules/q/q.js:2075:6), <anonymous>:1:999744)\n    at Module._extensions..js (module.js:671:10)\n    at Object.require.extensions..js (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.222/wallaby/runners/node/jest@0.4.3/initializer.js:14:7046)\n    at Module.load (module.js:573:32)\n    at tryModuleLoad (module.js:513:12)\n    at Function.Module._load (module.js:505:3)\n    at Module.require (module.js:604:17)\n    at Module.i.require (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.222/wallaby/server.js:27:28308)\n    at Module.r.require (/Users/anna-l\n',
     '2020-08-02T02:24:48.294Z workers Sandbox (active) [ni44m] error: Unexpected token {\n',
     '2020-08-02T02:24:48.295Z workers Failed to map the stack to user code, entry message: Unexpected token {, stack: <homeDir>/Documents/Snapask/Study-Planet-Admin/node_modules/jest-resolve/build/index.js:290\n      } catch {}\n              ^\n\nSyntaxError: Unexpected token {\n    at createScript (vm.js:80:10)\n    at Object.runInThisContext (vm.js:152:10)\n    at Module._compile (module.js:624:28)\n    at Module._0x4e5437._compile (eval at <anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.222/wallaby/node_modules/q/q.js:2075:6), <anonymous>:1:999744)\n    at Module._extensions..js (module.js:671:10)\n    at Object.require.extensions..js (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.222/wallaby/runners/node/jest@0.4.3/initializer.js:14:7046)\n    at Module.load (module.js:573:32)\n    at tryModuleLoad (module.js:513:12)\n    at Function.Module._load (module.js:505:3)\n    at Module.require (module.js:604:17)\n    at Module.i.require (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.222/wallaby/server.js:27:28308)\n    at Module.r.require (/Users/anna-l\n',
     '2020-08-02T02:24:48.399Z workers [eatq9] Run 0 test(s), skipped 0 test(s)\n',
     '2020-08-02T02:24:48.399Z workers [ni44m] Run 0 test(s), skipped 0 test(s)\n',
     '2020-08-02T02:24:48.400Z workers [eatq9] Sandbox is responsive, closing it\n',
     '2020-08-02T02:24:48.400Z workers [ni44m] Sandbox is responsive, closing it\n',
     '2020-08-02T02:24:48.401Z workers Merging parallel test run results\n',
     '2020-08-02T02:24:48.401Z project Test run finished\n',
     '2020-08-02T02:24:48.402Z project Processed console.log entries\n',
     '2020-08-02T02:24:48.402Z project Processed loading sequences\n',
     '2020-08-02T02:24:48.402Z project Processed executed tests\n',
     '2020-08-02T02:24:48.403Z project Processed code coverage\n',
     '2020-08-02T02:24:48.413Z project Test run result processed and sent to IDE\n' ] }
```

**Comment by ArtemGovorov** [comment]
Jest resolve package that is being reported as a source of the error, is [using `catch` block without exception identifier](https://github.com/facebook/jest/blob/918636142791a3dd4ddfe9367149a90437bd6da9/packages/jest-resolve/src/index.ts#L220) (also reported in the error's message). 

According to your Wallaby Diagnostics Report, you are using node.js version: `v9.3.0`, and this version of node doesn't support `catch` block without exception identifier. Also the issue is not Wallaby specific, and you should be able to reproduce it by running your tests from CLI using `npm test` so the solution is to update your node version.

**Comment by anna-luyufeng** [comment]
Hi @ArtemGovorov, thank you for your replying.
I tried to update my node version but it still has the error. 
(`npm test` can run correctly)

Here is the Wallaby Diagnostics Report:
```
{
  editorVersion: '1.46.1',
  pluginVersion: '1.0.222',
  editorType: 'VSCode',
  osVersion: 'darwin 19.5.0',
  nodeVersion: 'v12.6.0',
  coreVersion: '1.0.939',
  config: {
    files: [
      { pattern: 'jsconfig.json', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: 'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: 'src/**/*.test.js?(x)', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: 'src/**/*.test.js?(x).snap', ignore: false, instrument: false, trigger: true, load: true, order: 3 },
      { pattern: 'package.json', ignore: false, instrument: false, trigger: true, load: true, order: 4 }
    ],
    tests: [ { pattern: 'src/**/*.test.js?(x)', ignore: false, trigger: true, load: true, test: true, order: 5 } ],
    env: {
      type: 'node',
      params: {},
      runner: '<homeDir>/.nvm/versions/node/v12.6.0/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    compilers: { '**/*.js?(x)': [Function], '**/*.?(lit)coffee?(.md)': [Function] },
    testFramework: { version: 'jest@0.4.3', configurator: 'jest@0.4.3', reporter: 'jest@0.4.3', starter: 'jest@0.4.3' },
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    preprocessors: { 'package.json': [Function] },
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'module.exports = function (wallaby) {\n' +
      '  // Babel, jest-cli and some other modules may be located under\n' +
      '  // react-scripts/node_modules, so need to let node.js know about it\n' +
      "  var path = require('path');\n" +
      '  process.env.NODE_PATH +=\n' +
      '    path.delimiter +\n' +
      "    path.join(__dirname, 'node_modules') +\n" +
      '    path.delimiter +\n' +
      "    path.join(__dirname, 'node_modules/snapask-react-scripts/node_modules');\n" +
      "  require('module').Module._initPaths();\n" +
      '\n' +
      '  return {\n' +
      '    files: [\n' +
      "      'jsconfig.json',\n" +
      "      'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',\n" +
      "      '!src/**/*.test.js?(x)',\n" +
      '    ],\n' +
      '\n' +
      "    tests: ['src/**/*.test.js?(x)'],\n" +
      '\n' +
      '    env: {\n' +
      "      type: 'node',\n" +
      '    },\n' +
      '\n' +
      '    compilers: {\n' +
      "      '**/*.js?(x)': wallaby.compilers.babel({\n" +
      "        presets: ['react-app'],\n" +
      '      }),\n' +
      '    },\n' +
      '\n' +
      '    setup: (wallaby) => {\n' +
      "      const createJestConfigUtil = require('snapask-react-scripts/scripts/utils/createJestConfig');\n" +
      '      const jestConfig = createJestConfigUtil((p) =>\n' +
      "        require.resolve('snapask-react-scripts/' + p)\n" +
      '      );\n' +
      '      Object.keys(jestConfig.transform || {}).forEach(\n' +
      '        (k) =>\n' +
      "          ~k.indexOf('^.+\\\\.(js|jsx') && void delete jestConfig.transform[k]\n" +
      '      );\n' +
      '      delete jestConfig.testEnvironment;\n' +
      '      wallaby.testFramework.configure(jestConfig);\n' +
      '    },\n' +
      '\n' +
      "    testFramework: 'jest',\n" +
      '  };\n' +
      '};\n'
  },
  packageJSON: {
    dependencies: {
      '@material-ui/core': '^4.11.0',
      '@testing-library/jest-dom': '^4.2.4',
      '@testing-library/react': '^9.3.2',
      '@testing-library/user-event': '^7.1.2',
      axios: '^0.19.2',
      classnames: '^2.2.6',
      fingerprintjs2: '^2.1.0',
      'node-sass': '^4.14.1',
      'prop-types': '^15.7.2',
      react: '^16.13.1',
      'react-css-themr': '^2.1.2',
      'react-dom': '^16.13.1',
      'react-redux': '^7.1.3',
      'react-router-dom': '^5.2.0',
      'redux-devtools-extension': '^2.13.8',
      'redux-saga': '^1.1.3',
      'snapask-react-scripts': '^3.4.2'
    },
    devDependencies: {
      'eslint-config-prettier': '^6.11.0',
      'eslint-plugin-prettier': '^3.1.3',
      husky: '^4.2.5',
      'lint-staged': '^10.2.11',
      prettier: '^2.0.5',
      stylelint: '^13.6.0',
      'stylelint-config-prettier': '^8.0.1',
      'stylelint-config-recommended-scss': '^4.2.0',
      'stylelint-config-standard': '^20.0.0',
      'stylelint-order': '^4.1.0',
      'stylelint-prettier': '^1.1.2',
      'stylelint-scss': '^3.17.2'
    }
  },
  fs: { numberOfFiles: 46 },
  debug: [
    '2020-08-02T03:16:58.798Z project Wallaby Node version: v12.6.0\n',
    '2020-08-02T03:16:58.798Z project Wallaby config: <homeDir>/Documents/Snapask/Study-Planet-Admin/wallaby.js\n',
    '2020-08-02T03:16:59.416Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.222/projects/d9030168f18d4994\n',
    '2020-08-02T03:16:59.424Z uiService Listening port 51235\n',
    '2020-08-02T03:16:59.427Z project package.json file change detected, invalidating local cache\n',
    '2020-08-02T03:16:59.448Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2020-08-02T03:16:59.448Z workers Starting run worker instance #0\n',
    '2020-08-02T03:16:59.448Z workers Starting run worker instance #1\n',
    '2020-08-02T03:16:59.448Z workers Starting run worker instance #2\n',
    '2020-08-02T03:16:59.448Z workers Starting run worker instance #3\n',
    '2020-08-02T03:16:59.448Z workers Starting run worker instance #4\n',
    '2020-08-02T03:16:59.448Z workers Starting run worker instance #5\n',
    '2020-08-02T03:16:59.449Z workers Web server is listening at 65378\n',
    '2020-08-02T03:16:59.449Z project File cache requires some updates, waiting required files from IDE\n',
    '2020-08-02T03:16:59.994Z workers Started run worker instance (delayed) #0\n',
    '2020-08-02T03:16:59.996Z workers Started run worker instance (delayed) #2\n',
    '2020-08-02T03:17:00.001Z workers Started run worker instance (delayed) #1\n',
    '2020-08-02T03:17:00.014Z workers Started run worker instance (delayed) #3\n',
    '2020-08-02T03:17:00.016Z workers Started run worker instance (delayed) #4\n',
    '2020-08-02T03:17:00.026Z workers Started run worker instance (delayed) #5\n',
    '2020-08-02T03:17:01.573Z project Compiler did not set ranges for file [src/setupTests.js]\n',
    '2020-08-02T03:17:01.687Z project Compiler did not set ranges for file [src/hooks/createContext.js]\n',
    '2020-08-02T03:17:01.813Z project Compiler did not set ranges for file [src/redux/reducers.js]\n',
    '2020-08-02T03:17:01.834Z project Compiler did not set ranges for file [src/pages/Login/index.js]\n',
    '2020-08-02T03:17:01.876Z project Compiler did not set ranges for file [src/components/BaseLayout/index.js]\n',
    '2020-08-02T03:17:01.895Z project Compiler did not set ranges for file [src/components/PageLoading/index.js]\n',
    '2020-08-02T03:17:01.899Z project Compiler did not set ranges for file [src/components/AuthGuard/index.js]\n',
    '2020-08-02T03:17:01.934Z project Re-attaching document block comment\n',
    '2020-08-02T03:17:02.067Z project Stopping process pool\n',
    '2020-08-02T03:17:02.068Z project Running postprocessor\n',
    '2020-08-02T03:17:02.072Z postprocessor New TypeScript language service is required\n',
    "2020-08-02T03:17:02.074Z postprocessor TypeScript postprocessor will be removed because in 46 project files none were found by patterns: [ '**/*.ts?(x)' ]\n",
    '2020-08-02T03:17:02.076Z project Postprocessor execution finished\n',
    '2020-08-02T03:17:02.076Z project Postprocessor is removed as requested by itself\n',
    '2020-08-02T03:17:02.076Z project Test run started; run priority: 3\n',
    '2020-08-02T03:17:02.076Z project Running all tests\n',
    '2020-08-02T03:17:02.083Z workers Starting test run, priority: 3\n',
    '2020-08-02T03:17:02.084Z workers Distributing tests between 6 workers\n',
    '2020-08-02T03:17:02.084Z workers Running tests in parallel\n',
    '2020-08-02T03:17:02.084Z nodeRunner Starting sandbox [worker #0, session #9a7x1]\n',
    '2020-08-02T03:17:02.084Z nodeRunner Starting sandbox [worker #1, session #1gcnm]\n',
    '2020-08-02T03:17:02.085Z nodeRunner Preparing sandbox [worker #0, session #9a7x1]\n',
    '2020-08-02T03:17:02.085Z nodeRunner Preparing sandbox [worker #1, session #1gcnm]\n',
    '2020-08-02T03:17:02.085Z nodeRunner Prepared sandbox [worker #0, session #9a7x1]\n',
    '2020-08-02T03:17:02.085Z nodeRunner Prepared sandbox [worker #1, session #1gcnm]\n',
    '2020-08-02T03:17:02.085Z workers [worker #0, session #9a7x1] Running tests in sandbox\n',
    '2020-08-02T03:17:02.086Z workers [worker #1, session #1gcnm] Running tests in sandbox\n',
    '2020-08-02T03:17:03.570Z workers Sandbox (active) [9a7x1] error: ReferenceError: jasmine is not defined\n',
    '2020-08-02T03:17:03.571Z workers Failed to map the stack to user code, entry message: ReferenceError: jasmine is not defined, stack: ReferenceError: jasmine is not defined\n' +
      '    at Object.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.222/wallaby/runners/node/jest@0.4.3/jasmineInitializer.js:14:33)\n' +
      '    at Runtime._execModule (<homeDir>/Documents/Snapask/Study-Planet-Admin/node_modules/jest-runtime/build/index.js:1217:24)\n' +
      '    at Runtime._loadModule (<homeDir>/Documents/Snapask/Study-Planet-Admin/node_modules/jest-runtime/build/index.js:828:12)\n' +
      '    at Runtime.requireModule (<homeDir>/Documents/Snapask/Study-Planet-Admin/node_modules/jest-runtime/build/index.js:679:10)\n' +
      '    at Runtime.d._wallabyReplaced.c.requireModule (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.222/wallaby/runners/node/jest@0.4.3/initializer.js:14:29085)\n' +
      '    at jestAdapter (<homeDir>/Documents/Snapask/Study-Planet-Admin/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:134:15)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:85:5)\n' +
      '    at\n',
    '2020-08-02T03:17:03.572Z workers Sandbox (active) [1gcnm] error: ReferenceError: jasmine is not defined\n',
    '2020-08-02T03:17:03.573Z workers Failed to map the stack to user code, entry message: ReferenceError: jasmine is not defined, stack: ReferenceError: jasmine is not defined\n' +
      '    at Object.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.222/wallaby/runners/node/jest@0.4.3/jasmineInitializer.js:14:33)\n' +
      '    at Runtime._execModule (<homeDir>/Documents/Snapask/Study-Planet-Admin/node_modules/jest-runtime/build/index.js:1217:24)\n' +
      '    at Runtime._loadModule (<homeDir>/Documents/Snapask/Study-Planet-Admin/node_modules/jest-runtime/build/index.js:828:12)\n' +
      '    at Runtime.requireModule (<homeDir>/Documents/Snapask/Study-Planet-Admin/node_modules/jest-runtime/build/index.js:679:10)\n' +
      '    at Runtime.d._wallabyReplaced.c.requireModule (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.222/wallaby/runners/node/jest@0.4.3/initializer.js:14:29085)\n' +
      '    at jestAdapter (<homeDir>/Documents/Snapask/Study-Planet-Admin/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:134:15)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:85:5)\n' +
      '    at\n',
    '2020-08-02T03:17:03.587Z workers [9a7x1] Run 0 test(s), skipped 0 test(s)\n',
    '2020-08-02T03:17:03.588Z workers [9a7x1] Sandbox is responsive, closing it\n',
    '2020-08-02T03:17:03.590Z workers [1gcnm] Run 0 test(s), skipped 0 test(s)\n',
    '2020-08-02T03:17:03.591Z workers [1gcnm] Sandbox is responsive, closing it\n',
    '2020-08-02T03:17:03.591Z workers Merging parallel test run results\n',
    '2020-08-02T03:17:03.592Z project Test run finished\n',
    '2020-08-02T03:17:03.592Z project Processed console.log entries\n',
    '2020-08-02T03:17:03.592Z project Processed loading sequences\n',
    '2020-08-02T03:17:03.592Z project Processed executed tests\n',
    '2020-08-02T03:17:03.594Z project Processed code coverage\n',
    '2020-08-02T03:17:03.604Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by smcenlly** [comment]
Thanks for sharing the updated diagnostics report. We can see that the issue stems from the `snapask-react-scripts` setting jest test runner to `jest-circus`. To fix the problem, please update your configuration file as shown below:

```diff
module.exports = function (wallaby) { 
  // Babel, jest-cli and some other modules may be located under 
  // react-scripts/node_modules, so need to let node.js know about it 
  var path = require('path'); 
  process.env.NODE_PATH += 
    path.delimiter + 
    path.join(__dirname, 'node_modules') + 
    path.delimiter + 
    path.join(__dirname, 'node_modules/snapask-react-scripts/node_modules'); 
  require('module').Module._initPaths(); 
 
  return { 
    files: [ 
      'jsconfig.json', 
      'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', 
      '!src/**/*.test.js?(x)', 
    ], 
 
    tests: ['src/**/*.test.js?(x)'], 
 
    env: { 
      type: 'node', 
    }, 
 
    compilers: { 
      '**/*.js?(x)': wallaby.compilers.babel({ 
        presets: ['react-app'], 
      }), 
    }, 
 
    setup: (wallaby) => { 
      const createJestConfigUtil = require('snapask-react-scripts/scripts/utils/createJestConfig'); 
      const jestConfig = createJestConfigUtil((p) => 
        require.resolve('snapask-react-scripts/' + p) 
      ); 
      Object.keys(jestConfig.transform || {}).forEach( 
        (k) => 
          ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k] 
      ); 
+     delete jestConfig.testRunner;
      delete jestConfig.testEnvironment; 
      wallaby.testFramework.configure(jestConfig); 
    }, 
 
    testFramework: 'jest', 
  }; 
};
```
