### ISSUE TITLE
How to cofigure custom typescript transformes like ts-nameof, with ttypescript.

### ISSUE THREAD

**Issue by JozefBiros** [wallabyjs/public#2490]
### Issue description or question

Heelo, I managed succesfully run wallaby in our project. I am just unable to figure out last thing a that is how to correctly configure custom typescript transformers.

We are using custom transformer. For transformer we are using ttypescript compiler instead of typesript:
```
   "ttypescript": "1.5.10",
   "ts-nameof": "4.2.2",
```

In webpack config we have rule for .ts and .tsx files: 
```
 ....
 module: {
      rules: [
         ...,
         {
            test: /\.([tj])sx?$/,
            exclude: /node_modules/,
            use: [
               {
                  loader: 'ts-loader',
                  options: { transpileOnly: true, compiler: 'ttypescript' }
               }
            ]
         },
        ....
      ]
   }
  ....
```

Our tsconfig.json:
```
"compilerOptions": {
      "baseUrl": ".",
      "outDir": "./dist",
      "allowSyntheticDefaultImports": true,
      "esModuleInterop": true,
      "allowJs": true,
      "sourceMap": true,
      "noImplicitAny": false,
      "skipLibCheck": true,
      "target": "es5",
      "jsx": "react",
      "locale": "cs",
      "lib": ["es2018", "dom"],
      "module": "commonjs",
      "moduleResolution": "node",
      "resolveJsonModule": true,
      "downlevelIteration": true,
      "plugins": [{ "transform": "ts-nameof", "type": "raw" }]
   },
```

My wallaby config:
```
module.exports = function (wallaby) {
   return {
      files: [
         'setupTests.js',
         '__generated__/**/*',
         'tsconfig.json',
         'mocks/**/*',
         'package.json',
         'src/**/*.{ts,tsx,js,graphql,gql}',
         {
            pattern: 'src/**/*.test.{ts,tsx}',
            ignore: true
         },
         {
            pattern: 'src/**/*.json',
            load: false
         },
         {
            pattern: 'src/**/*.scss'
         }
      ],
      tests: ['src/**/*.test.{ts,tsx}'],
      setup() {
         require('jsdom-global/register');

         // React 16 Enzyme adapter
         const { configure } = require('enzyme');
         const Adapter = require('enzyme-adapter-react-16');
         configure({ adapter: new Adapter() });

         // Excluding custom extensions
         const { addHook } = require('pirates');
         const IGNORE_EXTENSIONS = ['.graphql', '.gql'];
         addHook(() => '', { exts: IGNORE_EXTENSIONS });

         require('ignore-styles');

         // alias resolution
         if (global._tsconfigPathsRegistered) return;
         const tsConfigPaths = require('tsconfig-paths');
         const tsconfig = require('./tsconfig.json');
         tsConfigPaths.register({
            baseUrl: tsconfig.compilerOptions.baseUrl,
            paths: tsconfig.compilerOptions.paths
         });

         global._tsconfigPathsRegistered = true;
      },
      testFramework: 'mocha',
      env: {
         type: 'node'
      }
   };
};

```

The result is of cource wallaby cannot transform nameof, and some test are failing.
From failed test tab:

```
	nameof is not defined
		at Object.exports.isProductSelectMarketTradedFragment src/pages/PortfolioOld/Table/TradingButton/ProductSelect/helpers.ts:9:4
		at Context.<anonymous> src/pages/PortfolioOld/Table/TradingButton/ProductSelect/helpers.test.ts:15:7
```

**Comment by smcenlly** [comment]
By default, Wallaby uses the TypeScript compiler, which does not support plugins. You will need to tell Wallaby to use `ttypescript` as the TypeScript compiler, instead of `typescript`. You may do this by [overriding the TypeScript compiler version](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-version):

```diff
module.exports = function (wallaby) {
   return {
      files: [
         'setupTests.js',
         '__generated__/**/*',
         'tsconfig.json',
         'mocks/**/*',
         'package.json',
         'src/**/*.{ts,tsx,js,graphql,gql}',
         {
            pattern: 'src/**/*.test.{ts,tsx}',
            ignore: true
         },
         {
            pattern: 'src/**/*.json',
            load: false
         },
         {
            pattern: 'src/**/*.scss'
         }
      ],
      tests: ['src/**/*.test.{ts,tsx}'],
+     compilers: {
+       '**/*.ts?(x)': w.compilers.typeScript({
+         typescript: require('ttypescript')
+       })
+     },
      setup() {
         require('jsdom-global/register');

         // React 16 Enzyme adapter
         const { configure } = require('enzyme');
         const Adapter = require('enzyme-adapter-react-16');
         configure({ adapter: new Adapter() });

         // Excluding custom extensions
         const { addHook } = require('pirates');
         const IGNORE_EXTENSIONS = ['.graphql', '.gql'];
         addHook(() => '', { exts: IGNORE_EXTENSIONS });

         require('ignore-styles');

         // alias resolution
         if (global._tsconfigPathsRegistered) return;
         const tsConfigPaths = require('tsconfig-paths');
         const tsconfig = require('./tsconfig.json');
         tsConfigPaths.register({
            baseUrl: tsconfig.compilerOptions.baseUrl,
            paths: tsconfig.compilerOptions.paths
         });

         global._tsconfigPathsRegistered = true;
      },
      testFramework: 'mocha',
      env: {
         type: 'node'
      }
   };
};
```

From our initial testing, this works for us, but we are not super familiar with `ttypescript` and it is possible that this approach may break in an unexpected way if `ttypescript` wrappers somehow break the `typescript` compiler/API.

If you run into problems, you may alternatively [configure Babel](https://wallabyjs.com/docs/integration/es-next.html) to transpile your TypeScript use the [@babel/preset-typescript](https://babeljs.io/docs/en/babel-preset-typescript) preset and [babel-plugin-ts-nameof](https://github.com/dsherret/ts-nameof/tree/master/packages/babel-plugin-ts-nameof).
