### ISSUE TITLE
Wallaby crashes after update

### ISSUE THREAD

**Issue by vjau** [wallabyjs/public#2522]
### Issue description or question
Since today's update of Wallaby plugin, i get many crashes of the plugin. 

This is the diagnostics report before the crash, since i can't get a diagnostic report when it has crashed.
### Wallaby diagnostics report
```
{
  editorVersion: 'WebStorm 2020.2.2',
  pluginVersion: '1.0.197',
  editorType: 'IntelliJ',
  osVersion: 'linux 5.4.0-47-generic',
  nodeVersion: 'v12.18.4',
  coreVersion: '1.0.966',
  checksum: 'ZmMzODk1M2NlMDU1YmRlMmQxZTI1OTA3M2Q2YmY5NTgsMTYxODI3MjAwMDAwMCww',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              browser: false,
              cache: true,
              cacheDirectory: '/tmp/jest_rs',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/dev/rummik',
              dependencyExtractor: null,
              detectLeaks: undefined,
              detectOpenHandles: undefined,
              displayName: undefined,
              errorOnDeprecated: false,
              extraGlobals: undefined,
              filter: null,
              forceCoverageMatch: [],
              globalSetup: null,
              globalTeardown: null,
              globals: {},
              haste: { computeSha1: false, providesModuleNodeModules: [], throwOnModuleCollision: false },
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [
                'web.js',  'js',
                'web.ts',  'ts',
                'web.tsx', 'tsx',
                'json',    'web.jsx',
                'jsx',     'node'
              ],
              moduleLoader: undefined,
              moduleNameMapper: [ [ '^react-native$', 'react-native-web' ], [ '^.+\\.module\\.(css|sass|scss)$', 'identity-obj-proxy' ] ],
              modulePathIgnorePatterns: [],
              modulePaths: [],
              name: 'c1247be9c2fba880610f95ba09747a43',
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: null,
              restoreMocks: false,
              rootDir: '<homeDir>/dev/rummik',
              roots: [ '<homeDir>/dev/rummik/src' ],
              runner: 'jest-runner',
              setupFiles: [ '<homeDir>/dev/rummik/node_modules/react-app-polyfill/jsdom.js' ],
              setupFilesAfterEnv: [ '<homeDir>/dev/rummik/src/setupTests.ts' ],
              skipFilter: false,
              skipNodeResolution: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/dev/rummik/node_modules/jest-environment-jsdom-fourteen/lib/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '<homeDir>/dev/rummik/src/**/__tests__/**/*.{js,jsx,ts,tsx}', '<homeDir>/dev/rummik/src/**/*.{spec,test}.{js,jsx,ts,tsx}' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<homeDir>/dev/rummik/node_modules/jest-jasmine2/build/index.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [
                [ '^.+\\.(js|jsx|ts|tsx)$', '<homeDir>/dev/rummik/node_modules/react-scripts/config/jest/babelTransform.js' ],
                [ '^.+\\.css$', '<homeDir>/dev/rummik/node_modules/react-scripts/config/jest/cssTransform.js' ],
                [ '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)', '<homeDir>/dev/rummik/node_modules/react-scripts/config/jest/fileTransform.js' ]
              ],
              transformIgnorePatterns: [ '[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$', '^.+\\.module\\.(css|sass|scss)$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: [ 'src/**/*.{js,jsx,ts,tsx}', '!src/**/*.d.ts' ],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<homeDir>/dev/rummik/coverage',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: null,
            detectLeaks: undefined,
            detectOpenHandles: undefined,
            enabledTestsMap: undefined,
            errorOnDeprecated: false,
            expand: false,
            extraGlobals: undefined,
            filter: null,
            findRelatedTests: undefined,
            forceExit: undefined,
            globalSetup: null,
            globalTeardown: null,
            json: false,
            lastCommit: undefined,
            listTests: undefined,
            logHeapUsage: undefined,
            maxConcurrency: 5,
            maxWorkers: 7,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: undefined,
            onlyFailures: undefined,
            outputFile: undefined,
            passWithNoTests: undefined,
            projects: null,
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/dev/rummik',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: null,
            testSequencer: '<homeDir>/dev/rummik/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: null,
            watch: false,
            watchAll: undefined,
            watchPlugins: [
              { config: {}, path: '<homeDir>/dev/rummik/node_modules/jest-watch-typeahead/filename.js' },
              { config: {}, path: '<homeDir>/dev/rummik/node_modules/jest-watch-typeahead/testname.js' }
            ],
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [ 'src' ],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|/\\..+/' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|/\\..+/' ],
            testMatch: [ 'src/**/__tests__/**/*.{js,jsx,ts,tsx}', 'src/**/*.{spec,test}.{js,jsx,ts,tsx}' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [ 'src/**/*.{js,jsx,ts,tsx}', '!src/**/*.d.ts' ],
    globalSetup: false,
    micromatch: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
      { pattern: '\\./dist/|\\./build/|\\./coverage/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\/\..+\//, ignore: true, trigger: true, load: true },
      { pattern: 'src/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**/__tests__/**/*.{js,jsx,ts,tsx}', ignore: true, trigger: true, load: true },
      { pattern: 'src/**/*.{spec,test}.{js,jsx,ts,tsx}', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
      { pattern: '\\./dist/|\\./build/|\\./coverage/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\/\..+\//, ignore: true, trigger: true, load: true, test: true },
      { pattern: 'src/**/__tests__/**/*.{js,jsx,ts,tsx}', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: 'src/**/*.{spec,test}.{js,jsx,ts,tsx}', ignore: false, trigger: true, load: true, test: true, order: 3 }
    ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '/usr/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#995820836'
  },
  packageJSON: {
    dependencies: {
      '@testing-library/jest-dom': '^4.2.4',
      '@testing-library/react': '^9.3.2',
      '@testing-library/user-event': '^7.1.2',
      '@types/jest': '^24.0.0',
      '@types/node': '^12.0.0',
      '@types/react': '^16.9.0',
      '@types/react-dom': '^16.9.0',
      immer: '^7.0.9',
      react: '^16.13.1',
      'react-dnd': '^11.1.3',
      'react-dnd-html5-backend': '^11.1.3',
      'react-dom': '^16.13.1',
      'react-scripts': '3.4.3',
      typescript: '^3.9.7',
      uuid: '^8.3.0'
    },
    devDependencies: { '@types/uuid': '^8.3.0', prettier: '^2.1.2' }
  },
  fs: { numberOfFiles: 21 },
  debug: [
    '2020-09-26T10:30:39.213Z angular/cli config Angular CLI not found.\n',
    '2020-09-26T10:30:39.494Z jest/config Detected Jest.\n',
    '2020-09-26T10:30:39.496Z jest/config Configured Jest.\n',
    '2020-09-26T10:30:39.499Z project Wallaby Node version: v12.18.4\n',
    '2020-09-26T10:30:39.499Z project Wallaby config: <homeDir>/dev/rummik/auto.detect\n',
    '2020-09-26T10:30:40.223Z project File cache: <homeDir>/.cache/JetBrains/WebStorm2020.2/wallaby/projects/3b9f762598da8aa6\n',
    '2020-09-26T10:30:40.234Z uiService Listening port 51235\n',
    '2020-09-26T10:30:40.245Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2020-09-26T10:30:40.245Z workers Starting run worker instance #0\n',
    '2020-09-26T10:30:40.246Z workers Starting run worker instance #1\n',
    '2020-09-26T10:30:40.246Z workers Starting run worker instance #2\n',
    '2020-09-26T10:30:40.246Z workers Starting run worker instance #3\n',
    '2020-09-26T10:30:40.246Z workers Starting run worker instance #4\n',
    '2020-09-26T10:30:40.246Z workers Starting run worker instance #5\n',
    '2020-09-26T10:30:40.246Z workers Web server is listening at 42223\n',
    '2020-09-26T10:30:40.246Z project File cache requires some updates, waiting required files from IDE\n',
    '2020-09-26T10:30:40.299Z project Stopping process pool\n',
    '2020-09-26T10:30:40.302Z project Test run started; run priority: 3\n',
    '2020-09-26T10:30:40.304Z project Running all tests\n',
    '2020-09-26T10:30:40.307Z workers Starting test run, priority: 3\n',
    '2020-09-26T10:30:40.307Z nodeRunner Starting sandbox [worker #0, session #59h74]\n',
    '2020-09-26T10:30:40.307Z nodeRunner Preparing sandbox [worker #0, session #59h74]\n',
    '2020-09-26T10:30:40.447Z workers Started run worker instance (delayed) #0\n',
    '2020-09-26T10:30:40.448Z nodeRunner Prepared sandbox [worker #0, session #59h74]\n',
    '2020-09-26T10:30:40.448Z workers [worker #0, session #59h74] Running tests in sandbox\n',
    '2020-09-26T10:30:40.454Z workers Started run worker instance (delayed) #4\n',
    '2020-09-26T10:30:40.454Z workers Started run worker instance (delayed) #2\n',
    '2020-09-26T10:30:40.456Z workers Started run worker instance (delayed) #1\n',
    '2020-09-26T10:30:40.460Z workers Started run worker instance (delayed) #3\n',
    '2020-09-26T10:30:40.488Z workers Started run worker instance (delayed) #5\n',
    '2020-09-26T10:30:43.814Z workers [59h74] Loaded unknown number of test(s)\n',
    '2020-09-26T10:30:43.814Z workers [59h74] Test executed: suite accept or reject number\n',
    '2020-09-26T10:30:43.814Z workers [59h74] Test executed: suite accept joker\n',
    '2020-09-26T10:30:43.815Z workers [59h74] Test executed: same number combi accept or reject number\n',
    '2020-09-26T10:30:43.815Z workers [59h74] Test executed: same number combi accept joker\n',
    '2020-09-26T10:30:43.815Z workers [59h74] Test executed: calculate score\n',
    '2020-09-26T10:30:43.816Z workers [59h74] Test executed: findAllNewCombinaisonsFromDeck sameCombinaison\n',
    '2020-09-26T10:30:43.816Z workers [59h74] Test executed: findAllNewCombinaisonsFromDeck suite\n',
    '2020-09-26T10:30:43.816Z workers [59h74] Test executed: findAllNewCombinaisonsFromDeck 4 tiles suites\n',
    '2020-09-26T10:30:43.816Z workers [59h74] Test executed: getTwoCombinaisons from deck\n',
    '2020-09-26T10:30:43.817Z workers [59h74] Test executed: findAllNewCombinaisonsFromDeck with duplicated tile\n',
    '2020-09-26T10:30:43.817Z workers [59h74] Test executed: findAllNewCombinaisonsFromDeck with suite overlapping duplicated tile\n',
    '2020-09-26T10:30:43.817Z workers [59h74] Test executed: findAllNewCombinaisonsFromDeck with suite at the end\n',
    '2020-09-26T10:30:43.817Z workers [59h74] Test executed: getAllCombinaisonsOfCombinaisons two overlapping combinaisons\n',
    '2020-09-26T10:30:43.818Z workers [59h74] Test executed: getAllCombinaisonsOfCombinaisons one vs two combinaisons\n',
    '2020-09-26T10:30:43.818Z workers [59h74] Test executed: findAllNewCombinaisonsFromDeck with suite at the end 2\n',
    '2020-09-26T10:30:43.818Z workers [59h74] Test executed: find simple suite with Joker\n',
    '2020-09-26T10:30:43.818Z workers [59h74] Test executed: find simple brelan with Joker\n',
    '2020-09-26T10:30:43.819Z workers [59h74] Test executed: find carré with two jokers\n',
    "2020-09-26T10:30:43.819Z workers [59h74] Test executed: findBestCofCForScore doesn't include joker when it doesn't enable more points\n",
    "2020-09-26T10:30:43.819Z workers [59h74] Test executed: findBestCofCForScore only include one joker when a second doesn't give more points\n",
    '2020-09-26T10:30:43.821Z workers [59h74] Test executed: findBestCofCForScore includes joker when it enable more points\n',
    "2020-09-26T10:30:43.821Z workers [59h74] Test executed: findBestCofCForScore don't choose long suite when it blocks a better sameCombi\n",
    '2020-09-26T10:30:43.821Z workers [59h74] Test executed: isValidSuite simple suite\n',
    '2020-09-26T10:30:43.821Z workers [59h74] Test executed: isValidSuite simple wrong suite numbers\n',
    '2020-09-26T10:30:43.821Z workers [59h74] Test executed: isValidSuite simple wrong suite colors\n',
    '2020-09-26T10:30:43.822Z workers [59h74] Test executed: isValidSuite simple wrong tile number\n',
    '2020-09-26T10:30:43.822Z workers [59h74] Test executed: isValidSuite wrong suite with joker at 0\n',
    '2020-09-26T10:30:43.822Z workers [59h74] Test executed: isValidSuite wrong suite with joker between two succeeding numbers\n',
    '2020-09-26T10:30:43.822Z workers [59h74] Test executed: isValidSameCombi valid\n',
    '2020-09-26T10:30:43.822Z workers [59h74] Test executed: isValidSameCombi invalid two times the same color\n',
    '2020-09-26T10:30:43.823Z workers [59h74] Test executed: isValidSameCombi invalid different numbers\n',
    '2020-09-26T10:30:43.823Z workers [59h74] Test executed: replaceJokerWithCorrespondingTile, one joker in between\n',
    '2020-09-26T10:30:43.823Z workers [59h74] Test executed: replaceJokerWithCorrespondingTile, one joker at end\n',
    '2020-09-26T10:30:43.823Z workers [59h74] Test executed: replaceJokerWithCorrespondingTile, one joker at begin\n',
    '2020-09-26T10:30:43.823Z workers [59h74] Test executed: replaceJokerWithCorrespondingTile, two jokers in between\n',
    '2020-09-26T10:30:43.824Z workers [59h74] Test executed: replaceJokerWithCorrespondingTile, two jokers in three tiles, jokers at the end\n',
    '2020-09-26T10:30:43.824Z workers [59h74] Test executed: replaceJokerWithCorrespondingTile, two jokers in three tiles, jokers around\n',
    '2020-09-26T10:30:43.826Z workers [59h74] Run 37 test(s), skipped 0 test(s)\n',
    '2020-09-26T10:30:43.828Z workers [59h74] Sandbox is responsive, closing it\n',
    '2020-09-26T10:30:43.828Z project Test run finished\n',
    '2020-09-26T10:30:43.829Z project Processed console.log entries\n',
    '2020-09-26T10:30:43.829Z project Processed loading sequences\n',
    '2020-09-26T10:30:43.829Z project Processed executed tests\n',
    '2020-09-26T10:30:43.832Z project Processed code coverage\n',
    '2020-09-26T10:30:43.881Z project Test run result processed and sent to IDE\n'
  ]
}
```

The error message i see in the wallaby console is this :
```
ReferenceError: project is not defined²
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
ReferenceError: project is not defined
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

The crash happens when i'm using the debugger.

**Comment by ArtemGovorov** [comment]
Thanks for reporting the issue. It is fixed in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
