### ISSUE TITLE
autoconfig for angular 10.1.3 is not working

### ISSUE THREAD

**Issue by LPCmedia** [wallabyjs/public#2523]
### Issue description or question

Wallaby with autoconfig and angular cli 

‌[Error] Entry module not found: TypeError: Cannot read property 'name' of undefined

The issue can be traced back to the angular/cli dedupe plugin

![image](https://user-images.githubusercontent.com/5975736/94340879-388a6e00-ffd3-11ea-81d5-df5fd158bd90.png)

### Wallaby diagnostics report

```
{
  editorVersion: '1.49.1',
  pluginVersion: '1.0.244',
  editorType: 'VSCode',
  osVersion: 'darwin 19.6.0',
  nodeVersion: 'v12.17.0',
  coreVersion: '1.0.900',
  config: {
    diagnostics: {
      angular: {
        workspace: {
          '$schema': './node_modules/@angular/cli/lib/config/schema.json',
          version: 1,
          projects: {
            playground: {
              projectType: 'application',
              schematics: { '@nrwl/angular:component': { style: 'scss' } },
              root: 'apps/playground',
              sourceRoot: 'apps/playground/src',
              prefix: 'pg',
              architect: {
                build: {
                  builder: '@angular-devkit/build-angular:browser',
                  options: {
                    outputPath: 'dist/apps/playground',
                    index: 'apps/playground/src/index.html',
                    main: 'apps/playground/src/main.ts',
                    polyfills: 'apps/playground/src/polyfills.ts',
                    tsConfig: 'apps/playground/tsconfig.app.json',
                    assets: [ 'apps/playground/src/favicon.ico', 'apps/playground/src/assets' ],
                    styles: [
                      'libs/styles/styles.css',
                      'libs/theming/fa.css',
                      'libs/theming/material.css',
                      'libs/theming/fjalla-lato.css',
                      'libs/theming/montserrat.css',
                      'libs/theming/roboto.css',
                      'apps/playground/src/styles.scss'
                    ],
                    scripts: [],
                    stylePreprocessorOptions: { includePaths: [ 'libs/theming' ] }
                  },
                  configurations: {
                    production: {
                      fileReplacements: [ { replace: 'apps/playground/src/environments/environment.ts', with: 'apps/playground/src/environments/environment.prod.ts' } ],
                      optimization: true,
                      outputHashing: 'all',
                      sourceMap: false,
                      extractCss: true,
                      namedChunks: false,
                      extractLicenses: true,
                      vendorChunk: false,
                      buildOptimizer: true,
                      budgets: [ { type: 'initial', maximumWarning: '2mb', maximumError: '5mb' } ]
                    }
                  }
                },
                serve: {
                  builder: '@angular-devkit/build-angular:dev-server',
                  options: { browserTarget: 'playground:build' },
                  configurations: { production: { browserTarget: 'playground:build:production' } }
                },
                lint: { builder: '@angular-devkit/build-angular:tslint', options: { tsConfig: [ 'apps/playground/tsconfig.app.json' ], exclude: [ '**/node_modules/**', '!apps/playground/**' ] } }
              }
            },
            dataviz: {
              root: 'libs/dataviz',
              sourceRoot: 'libs/dataviz/src',
              projectType: 'library',
              prefix: 'avn',
              architect: {
                build: {
                  builder: '@nrwl/angular:package',
                  options: { tsConfig: 'libs/dataviz/tsconfig.json', project: 'libs/dataviz/ng-package.json' },
                  stylePreprocessorOptions: { includePaths: [ 'libs/ngx-components' ] },
                  configurations: { lpack: { tsConfig: 'libs/dataviz/tsconfig.lib.json' } }
                },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    sourceMap: false,
                    browsers: 'ChromeWithoutSecurity',
                    codeCoverage: true,
                    watch: false,
                    main: 'libs/dataviz/src/test.ts',
                    tsConfig: 'libs/dataviz/tsconfig.spec.json',
                    karmaConfig: 'libs/dataviz/karma.conf.js'
                  },
                  codeCoverageExclude: [ '/**/testing/**/*.ts' ]
                },
                lint: { builder: '@angular-devkit/build-angular:tslint', options: { tsConfig: [ 'libs/dataviz/tsconfig.spec.json' ], exclude: [ '**/node_modules/**' ] } }
              }
            },
            'ngx-charts': {
              root: 'libs/ngx-charts',
              sourceRoot: 'libs/ngx-charts/src',
              projectType: 'library',
              prefix: 'avn',
              architect: {
                build: {
                  builder: '@nrwl/angular:package',
                  options: { tsConfig: 'libs/ngx-charts/tsconfig.dev.json', project: 'libs/ngx-charts/ng-package.json' },
                  configurations: { lpack: { tsConfig: 'libs/ngx-charts/tsconfig.lib.json' } },
                  stylePreprocessorOptions: { includePaths: [ 'libs/theming' ] }
                },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    sourceMap: false,
                    browsers: 'ChromeWithoutSecurity',
                    codeCoverage: true,
                    watch: false,
                    main: 'libs/ngx-charts/src/test.ts',
                    tsConfig: 'libs/ngx-charts/tsconfig.spec.json',
                    karmaConfig: 'libs/ngx-charts/karma.conf.js'
                  },
                  codeCoverageExclude: [ '/**/testing/**/*.ts' ]
                },
                lint: { builder: '@angular-devkit/build-angular:tslint', options: { tsConfig: [ 'libs/ngx-charts/tsconfig.spec.json' ], exclude: [ '**/node_modules/**', '!libs/ngx-charts/**' ] } }
              }
            },
            'ngx-components': {
              root: 'libs/ngx-components',
              sourceRoot: 'libs/ngx-components/src',
              projectType: 'library',
              prefix: 'avn',
              architect: {
                build: {
                  builder: '@nrwl/angular:package',
                  options: { tsConfig: 'libs/ngx-components/tsconfig.dev.json', project: 'libs/ngx-components/ng-package.json' },
                  configurations: { lpack: { tsConfig: 'libs/ngx-components/tsconfig.lib.json' } },
                  stylePreprocessorOptions: { includePaths: [ 'libs/theming/src/scss' ] }
                },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    main: 'libs/ngx-components/src/test.ts',
                    sourceMap: false,
                    browsers: 'ChromeWithoutSecurity',
                    codeCoverage: true,
                    watch: false,
                    tsConfig: 'libs/ngx-components/tsconfig.spec.json',
                    karmaConfig: 'libs/ngx-components/karma.conf.js',
                    codeCoverageExclude: [ 'libs/ngx-components/src/testing/**/*', 'libs/ngx-components/src/**/*.mock.ts', 'libs/ngx-components/src/**/*.module.ts' ]
                  }
                },
                lint: {
                  builder: '@angular-devkit/build-angular:tslint',
                  options: { tsConfig: [ 'libs/ngx-components/tsconfig.spec.json', 'libs/ngx-components/tsconfig.worker.json' ], exclude: [ '**/node_modules/**', '!libs/ngx-components/**' ] }
                }
              }
            },
            styles: { root: 'libs/styles', sourceRoot: 'libs/styles/src', projectType: 'library' },
            'tooling-i18n': { root: 'libs/tooling-i18n', projectType: 'library' },
            geo: {
              root: 'libs/geo',
              sourceRoot: 'libs/geo/src',
              projectType: 'library',
              schematics: {},
              architect: {
                build: {
                  builder: '@nrwl/angular:package',
                  options: { tsConfig: 'libs/geo/tsconfig.dev.json', project: 'libs/geo/ng-package.json' },
                  configurations: { lpack: { tsConfig: 'libs/geo/tsconfig.lib.json' } },
                  stylePreprocessorOptions: { includePaths: [ 'libs/theming/' ] }
                },
                lint: { builder: '@angular-devkit/build-angular:tslint', options: { tsConfig: [ 'libs/geo/tsconfig.spec.json' ], exclude: [ '**/node_modules/**', '!libs/geo/**' ] } },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    sourceMap: false,
                    browsers: 'ChromeWithoutSecurity',
                    codeCoverage: true,
                    watch: false,
                    main: 'libs/geo/src/test.ts',
                    tsConfig: 'libs/geo/tsconfig.spec.json',
                    karmaConfig: 'libs/geo/karma.conf.js'
                  }
                }
              }
            },
            theming: {
              root: 'libs/theming',
              sourceRoot: 'libs/theming/src',
              projectType: 'library',
              schematics: {},
              architect: {
                build: {
                  builder: '@nrwl/workspace:run-commands',
                  options: {
                    commands: [
                      { command: 'node libs/theming/build/themify.build.js' },
                      { command: 'yarn run tsc --project libs/theming/tsconfig.themify.json' },
                      { command: 'yarn run lerna run build --scope @activia/theming --stream' },
                      { command: 'yarn run scss-bundle -p scss-bundle.config.json' }
                    ]
                  }
                }
              }
            }
          },
          cli: { warnings: { versionMismatch: true }, packageManager: 'yarn', analytics: false },
          schematics: { '@schematics/angular:component': { style: 'scss', displayBlock: true, changeDetection: 'OnPush' } },
          defaultProject: 'playground'
        },
        tsConfig: '{"compileOnSave":false,"compilerOptions":{"rootDir":".","sourceMap":true,"declaration":false,"moduleResolution":"node","emitDecoratorMetadata":false,"experimentalDecorators":true,"importHelpers":true,"target":"es2015","module":"esnext","typeRoots":["node_modules/@types"],"lib":["es2017","dom"],"skipLibCheck":true,"skipDefaultLibCheck":true,"baseUrl":".","paths":{"@activia/*":["./libs/*"],"core-js/es7/reflect":["node_modules/core-js/proposals/reflect-metadata"]},"types":["jasmine","node","googlemaps"]},"angularCompilerOptions":{"enableIvy":true},"exclude":["node_modules","tmp"],"files":["libs/dataviz/src/test.ts","libs/ngx-charts/src/test.ts","libs/ngx-components/src/test.ts","libs/geo/src/test.ts"],"include":["libs/dataviz/**/*.spec.ts","libs/dataviz/**/*.d.ts","libs/ngx-charts/**/*.spec.ts","libs/ngx-charts/**/*.d.ts","libs/ngx-components/**/*.spec.ts","libs/ngx-components/**/*.d.ts","libs/geo/**/*.spec.ts","libs/geo/**/*.d.ts"]}',
        polyfill: {
          path: '<homeDir>/dev/components/wallaby-polyfills.js',
          code: "require('<homeDir>/dev/components/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/jit-polyfills.js');"
        },
        main: [
          {
            path: '<homeDir>/dev/components/libs/dataviz/src/test.ts',
            code: '// This file is required by karma.conf.js and loads recursively all the .spec and framework files\n' +
              '\n' +
              "import 'core-js/es7/reflect';\n" +
              "import 'zone.js/dist/zone';\n" +
              "import 'zone.js/dist/zone-testing';\n" +
              "import { getTestBed } from '@angular/core/testing';\n" +
              "import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';\n" +
              '\n' +
              'declare const require: any;\n' +
              '\n' +
              '// First, initialize the Angular testing environment.\n' +
              'getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());\n' +
              '// Then we find all the tests.\n' +
              '\n' +
              '// And load the modules.\n' +
              '\n'
          },
          {
            path: '<homeDir>/dev/components/libs/ngx-charts/src/test.ts',
            code: '// This file is required by karma.conf.js and loads recursively all the .spec and framework files\n' +
              '\n' +
              "import 'core-js/es7/reflect';\n" +
              '\n' +
              '\n' +
              '\n' +
              '\n' +
              '\n' +
              '\n' +
              '\n' +
              '// First, initialize the Angular testing environment.\n' +
              '\n' +
              '// Then we find all the tests.\n' +
              '\n' +
              '// And load the modules.\n' +
              '\n'
          },
          {
            path: '<homeDir>/dev/components/libs/ngx-components/src/test.ts',
            code: '// This file is required by karma.conf.js and loads recursively all the .spec and framework files\n' +
              '\n' +
              "import 'core-js/es7/reflect';\n" +
              '\n' +
              '\n' +
              '\n' +
              '\n' +
              '\n' +
              '\n' +
              '\n' +
              '// First, initialize the Angular testing environment.\n' +
              '\n' +
              '// Then we find all the tests.\n' +
              '\n' +
              '// And load the modules.\n' +
              '\n'
          },
          {
            path: '<homeDir>/dev/components/libs/geo/src/test.ts',
            code: '// This file is required by karma.conf.js and loads recursively all the .spec and framework files\n' +
              '\n' +
              "import 'core-js/es7/reflect';\n" +
              '\n' +
              '\n' +
              '\n' +
              '\n' +
              '\n' +
              '\n' +
              '\n' +
              '\n' +
              '// First, initialize the Angular testing environment.\n' +
              '\n' +
              '// Then we find all the tests.\n' +
              '\n' +
              '// And load the modules.\n' +
              '\n'
          }
        ]
      }
    },
    testFramework: { version: 'jasmine@3.5.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3', autoDetected: true },
    env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    files: [
      { pattern: 'libs/dataviz/src/test.ts', ignore: true, trigger: true, load: true },
      { pattern: 'libs/dataviz/src/test.base.ts', ignore: true, trigger: true, load: true },
      { pattern: 'libs/dataviz/src/test.wallaby.ts', ignore: true, trigger: true, load: true },
      { pattern: 'libs/dataviz/src/**/*.spec.ts', ignore: true, trigger: true, load: true },
      { pattern: 'libs/dataviz/src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 1 },
      { pattern: 'libs/dataviz/src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 2 },
      { pattern: 'libs/ngx-charts/src/test.ts', ignore: true, trigger: true, load: true },
      { pattern: 'libs/ngx-charts/src/test.base.ts', ignore: true, trigger: true, load: true },
      { pattern: 'libs/ngx-charts/src/test.wallaby.ts', ignore: true, trigger: true, load: true },
      { pattern: 'libs/ngx-charts/src/**/*.spec.ts', ignore: true, trigger: true, load: true },
      { pattern: 'libs/ngx-charts/src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 3 },
      { pattern: 'libs/ngx-charts/src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 4 },
      { pattern: 'libs/ngx-components/src/test.ts', ignore: true, trigger: true, load: true },
      { pattern: 'libs/ngx-components/src/test.base.ts', ignore: true, trigger: true, load: true },
      { pattern: 'libs/ngx-components/src/test.wallaby.ts', ignore: true, trigger: true, load: true },
      { pattern: 'libs/ngx-components/src/**/*.spec.ts', ignore: true, trigger: true, load: true },
      { pattern: 'libs/ngx-components/src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 5 },
      { pattern: 'libs/ngx-components/src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 6 },
      { pattern: 'libs/geo/src/test.ts', ignore: true, trigger: true, load: true },
      { pattern: 'libs/geo/src/test.base.ts', ignore: true, trigger: true, load: true },
      { pattern: 'libs/geo/src/test.wallaby.ts', ignore: true, trigger: true, load: true },
      { pattern: 'libs/geo/src/**/*.spec.ts', ignore: true, trigger: true, load: true },
      { pattern: 'libs/geo/src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 7 },
      { pattern: 'libs/geo/src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 8 }
    ],
    tests: [
      { pattern: 'libs/dataviz/src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 9 },
      { pattern: 'libs/ngx-charts/src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 10 },
      { pattern: 'libs/ngx-components/src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 11 },
      { pattern: 'libs/geo/src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 12 }
    ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#1365687385'
  },
  packageJSON: {
    dependencies: {
      '@angular/animations': '10.1.3',
      '@angular/cdk': '10.2.2',
      '@angular/common': '10.1.3',
      '@angular/compiler': '10.1.3',
      '@angular/core': '10.1.3',
      '@angular/forms': '10.1.3',
      '@angular/google-maps': '10.1.1',
      '@angular/platform-browser': '10.1.3',
      '@angular/platform-browser-dynamic': '10.1.3',
      '@angular/router': '10.1.3',
      '@swimlane/ngx-charts': '16.0.0',
      chevrotain: '7.0.1',
      color: '3.1.2',
      'core-js': '3.6.5',
      highcharts: '8.2.0',
      'lodash-es': '4.17.15',
      mime: '2.4.6',
      'mime-db': '1.44.0',
      'mime-types': '2.1.27',
      moment: '2.27.0',
      'moment-timezone': '0.5.31',
      'resize-observer-polyfill': '1.5.1',
      rxjs: '6.6.3',
      uuid: '8.3.0',
      'zone.js': '0.10.3'
    },
    devDependencies: {
      '@angular-builders/custom-webpack': '10.0.0',
      '@angular-devkit/build-angular': '0.1001.3',
      '@angular-devkit/build-ng-packagr': '0.1001.3',
      '@angular/cli': '10.1.3',
      '@angular/compiler-cli': '10.1.3',
      '@angular/language-service': '10.1.3',
      '@commitlint/cli': '9.1.1',
      '@commitlint/config-conventional': '9.1.1',
      '@commitlint/prompt': '9.1.1',
      '@compodoc/compodoc': '1.1.11',
      '@nrwl/angular': '10.2.1',
      '@nrwl/workspace': '10.2.1',
      '@types/jasmine': '3.5.11',
      '@types/node': '13.13.5',
      '@types/uuid': '8.3.0',
      'angular-pipes': '10.0.0',
      'angular2-template-loader': '0.6.2',
      codelyzer: '6.0.0',
      commitizen: '4.2.1',
      'file-loader': '6.0.0',
      husky: '4.2.5',
      'jasmine-core': '~3.5.0',
      'jasmine-spec-reporter': '~5.0.0',
      karma: '~5.0.0',
      'karma-chrome-launcher': '~3.1.0',
      'karma-coverage-istanbul-reporter': '~3.0.2',
      'karma-jasmine': '~3.3.0',
      'karma-mocha-reporter': '2.2.5',
      'karma-teamcity-reporter': '1.1.0',
      lerna: '3.22.1',
      'lint-staged': '10.2.13',
      'lpcmedia-angular-testing-library': '0.0.1',
      'moment-random': '1.0.5',
      'ng-packagr': '10.1.0',
      'ng2-mock-component': '0.2.0',
      'node-sass': '4.14.1',
      prettier: '2.1.1',
      puppeteer: '3.3.0',
      'raw-loader': '4.0.1',
      rimraf: '3.0.2',
      'rxjs-tslint-rules': '4.34.1',
      'sass-loader': '8.0.2',
      'scss-bundle': '3.1.2',
      'ts-node': '8.10.2',
      tsickle: '0.39.1',
      tslib: '^2.0.0',
      tslint: '6.1.3',
      'tslint-etc': '1.13.1',
      typescript: '4.0.2',
      'uglifyjs-webpack-plugin': '2.2.0',
      'url-loader': '4.1.0',
      'wallaby-webpack': '3.9.15',
      webpack: '4.43.0',
      'webpack-bundle-analyzer': '3.7.0',
      'webpack-cli': '3.3.11'
    }
  },
  fs: { numberOfFiles: 882 },
  debug: [
    '2020-09-26T12:32:15.020Z config Detected Angular CLI.\n',
    '2020-09-26T12:32:17.605Z angular/cli workspace config Using virtual <homeDir>/dev/components/libs/dataviz/src/test.ts.\n',
    '2020-09-26T12:32:17.606Z angular/cli workspace config Using virtual <homeDir>/dev/components/libs/ngx-charts/src/test.ts.\n',
    '2020-09-26T12:32:17.607Z angular/cli workspace config Using virtual <homeDir>/dev/components/libs/ngx-components/src/test.ts.\n',
    '2020-09-26T12:32:17.608Z angular/cli workspace config Using virtual <homeDir>/dev/components/libs/geo/src/test.ts.\n',
    '2020-09-26T12:32:17.608Z angular/cli workspace config Using virtual <homeDir>/dev/components/tsconfig.wallaby.spec.json.\n',
    '2020-09-26T12:32:17.816Z config Configured Angular CLI.\n',
    '2020-09-26T12:32:17.817Z project Wallaby Node version: v12.17.0\n',
    '2020-09-26T12:32:17.817Z project Wallaby config: <homeDir>/dev/components/auto.detect\n',
    '2020-09-26T12:32:18.972Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.244/projects/785e6753a99f679f\n',
    '2020-09-26T12:32:18.990Z uiService Listening port 51235\n',
    '2020-09-26T12:32:22.364Z workers Parallelism for initial run: 10, for regular run: 5\n',
    '2020-09-26T12:32:22.364Z workers Starting run worker instance #0\n',
    '2020-09-26T12:32:22.364Z workers Starting run worker instance #1\n',
    '2020-09-26T12:32:22.364Z workers Starting run worker instance #2\n',
    '2020-09-26T12:32:22.364Z workers Starting run worker instance #3\n',
    '2020-09-26T12:32:22.364Z workers Starting run worker instance #4\n',
    '2020-09-26T12:32:22.364Z workers Starting run worker instance #5\n',
    '2020-09-26T12:32:22.364Z workers Starting run worker instance #6\n',
    '2020-09-26T12:32:22.364Z workers Starting run worker instance #7\n',
    '2020-09-26T12:32:22.364Z workers Starting run worker instance #8\n',
    '2020-09-26T12:32:22.364Z workers Starting run worker instance #9\n',
    '2020-09-26T12:32:22.366Z workers Web server is listening at 61492\n',
    '2020-09-26T12:32:22.371Z project Stopping process pool\n',
    '2020-09-26T12:32:22.371Z project File cache is up-to-date, starting full test run\n',
    '2020-09-26T12:32:22.375Z project Running postprocessor\n',
    '2020-09-26T12:32:22.390Z postprocessor Processing started.\n',
    '2020-09-26T12:32:22.390Z postprocessor Initializing.\n',
    '2020-09-26T12:32:22.391Z postprocessor Initializing entry.\n',
    '2020-09-26T12:32:22.391Z postprocessor Sanitizing configuration.\n',
    '2020-09-26T12:32:22.391Z postprocessor Adjusting configuration.\n',
    '2020-09-26T12:32:22.391Z postprocessor Creating compiler.\n',
    '2020-09-26T12:32:23.217Z postprocessor Customizing compiler.\n',
    '2020-09-26T12:32:23.217Z postprocessor Compilation started.\n',
    '2020-09-26T12:32:35.258Z workers Started run worker instance (immediate) #0\n',
    '2020-09-26T12:32:35.258Z workers Started run worker instance (immediate) #1\n',
    '2020-09-26T12:32:35.258Z workers Started run worker instance (immediate) #2\n',
    '2020-09-26T12:32:35.258Z workers Started run worker instance (immediate) #3\n',
    '2020-09-26T12:32:35.258Z workers Started run worker instance (immediate) #4\n',
    '2020-09-26T12:32:35.258Z workers Started run worker instance (immediate) #5\n',
    '2020-09-26T12:32:35.258Z workers Started run worker instance (immediate) #6\n',
    '2020-09-26T12:32:35.258Z workers Started run worker instance (immediate) #7\n',
    '2020-09-26T12:32:35.258Z workers Started run worker instance (immediate) #8\n',
    '2020-09-26T12:32:35.258Z workers Started run worker instance (immediate) #9\n',
    "2020-09-26T12:32:35.276Z project Error: Entry module not found: TypeError: Cannot read property 'name' of undefined\n" +
      '    at t.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.244/wallaby209324/server.js:9853:39)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.244/wallaby209324/server.js:9673:33)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.244/wallaby209324/server.js:9621:32)\n' +
      '    at o (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.244/wallaby209324/server.js:9597:31)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n',
    '2020-09-26T12:32:35.277Z project Test run finished\n',
    '2020-09-26T12:32:35.277Z project Test run data re-queued\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
Support for Angular 10.1.3 has been added in core v1.0.949, however your version of core is 1.0.900 (must be because your license has expired). Please use our [trial license](https://wallabyjs.com/download/) to update to the latest core version to check if it's working for you.

**Comment by LPCmedia** [comment]
Thanks.
