### ISSUE TITLE
Incorrect "Failing Tests" output

### ISSUE THREAD

**Issue by DenisGorbachev** [wallabyjs/public#253]
* https://github.com/fixin-platform/3dcart-workflows/commit/9e9484417ae400b0e9bdcfe6f0a8ade704d27711
* git submodule update --init --recursive --remote
* git submodule foreach --recursive 'npm install'
* npm install

Output:

```
Cannot call method 'extend' of undefined
	at core/lib/Strategy.coffee:15
	at core/lib/Strategy/DBStrategy.coffee:7
	at core/lib/Strategy/DBStrategy/Save.coffee:7
	at core/lib/Strategy/DBStrategy/Save/TemporaryTable.coffee:11
	at lib/Strategy/DBStrategy/Save/TemporaryTable/_3DCartSaveOrders.coffee:15
	at test/lib/Strategy/DBStrategy/Save/TemporaryTable/_3DCartSaveOrdersSpec.coffee:33

2 failing tests, 6 passing

test/lib/Task/DecisionTask/_3DCartWriteOrderInternalCommentSpec.coffee _3DCartWriteOrderInternalComment decision task should run `WorkflowExecutionStarted -> DecisionTaskScheduled -> DecisionTaskStarted` history @fast [6 ms]

	Cannot call method 'extend' of undefined
		at core/lib/Strategy.coffee:15
		at core/lib/Strategy/APIStrategy.coffee:15
		at core/lib/Strategy/APIStrategy/Read.coffee:11
		at core/lib/Strategy/APIStrategy/Read/LimitOffset.coffee:8
		at lib/Strategy/APIStrategy/Read/LimitOffset/_3DCartReadOrders.coffee:8
		at test/lib/Strategy/APIStrategy/Read/LimitOffset/_3DCartReadOrdersSpec.coffee:23

test/lib/_3DCartBindingSpec.coffee _3DCartBinding binding.getOrders() :: GET /Orders @fast [19 ms]

	Cannot call method 'extend' of undefined
		at core/lib/Strategy.coffee:15
		at core/lib/Strategy/APIStrategy.coffee:15
		at core/lib/Strategy/APIStrategy/Write.coffee:11
		at lib/Strategy/APIStrategy/Write/_3DCartWriteOrderInternalComment.coffee:19
		at test/lib/Strategy/APIStrategy/Write/_3DCartWriteOrderInternalCommentSpec.coffee:25
```

Incorrect things:

* An error is displayed before "2 failing tests, 6 passing" line.
* Errors don't correspond to tests.

Mocha reports that errors are in "before each" hooks:

```
  8 passing (1s)
  3 failing

  1) _3DCartReadOrders "before each" hook:
     TypeError: Cannot read property 'extend' of undefined
    at _3DCartReadOrders.Strategy (/home/starfall/workspace/3dcart-workflows/core/lib/Strategy.coffee:15:12)
    at _3DCartReadOrders.APIStrategy (/home/starfall/workspace/3dcart-workflows/core/lib/Strategy/APIStrategy.coffee:15:5)
    at _3DCartReadOrders.Read (/home/starfall/workspace/3dcart-workflows/core/lib/Strategy/APIStrategy/Read.coffee:3:7)
    at _3DCartReadOrders.LimitOffset (/home/starfall/workspace/3dcart-workflows/core/lib/Strategy/APIStrategy/Read/LimitOffset.coffee:11:5)
    at new _3DCartReadOrders (/home/starfall/workspace/3dcart-workflows/lib/Strategy/APIStrategy/Read/LimitOffset/_3DCartReadOrders.coffee:10:5)
    at Context.<anonymous> (/home/starfall/workspace/3dcart-workflows/test/lib/Strategy/APIStrategy/Read/LimitOffset/_3DCartReadOrdersSpec.coffee:23:16)
    at callFn (/home/starfall/workspace/3dcart-workflows/node_modules/mocha/lib/runnable.js:251:21)
    at Hook.Runnable.run (/home/starfall/workspace/3dcart-workflows/node_modules/mocha/lib/runnable.js:244:7)
    at next (/home/starfall/workspace/3dcart-workflows/node_modules/mocha/lib/runner.js:259:10)
    at Immediate._onImmediate (/home/starfall/workspace/3dcart-workflows/node_modules/mocha/lib/runner.js:276:5)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
  

  2) _3DCartWriteOrderInternalComment "before each" hook:
     TypeError: Cannot read property 'extend' of undefined
    at _3DCartWriteOrderInternalComment.Strategy (/home/starfall/workspace/3dcart-workflows/core/lib/Strategy.coffee:15:12)
    at _3DCartWriteOrderInternalComment.APIStrategy (/home/starfall/workspace/3dcart-workflows/core/lib/Strategy/APIStrategy.coffee:15:5)
    at _3DCartWriteOrderInternalComment.Write (/home/starfall/workspace/3dcart-workflows/core/lib/Strategy/APIStrategy/Write.coffee:3:7)
    at new _3DCartWriteOrderInternalComment (/home/starfall/workspace/3dcart-workflows/lib/Strategy/APIStrategy/Write/_3DCartWriteOrderInternalComment.coffee:7:7)
    at Context.<anonymous> (/home/starfall/workspace/3dcart-workflows/test/lib/Strategy/APIStrategy/Write/_3DCartWriteOrderInternalCommentSpec.coffee:25:16)
    at callFn (/home/starfall/workspace/3dcart-workflows/node_modules/mocha/lib/runnable.js:251:21)
    at Hook.Runnable.run (/home/starfall/workspace/3dcart-workflows/node_modules/mocha/lib/runnable.js:244:7)
    at next (/home/starfall/workspace/3dcart-workflows/node_modules/mocha/lib/runner.js:259:10)
    at Immediate._onImmediate (/home/starfall/workspace/3dcart-workflows/node_modules/mocha/lib/runner.js:276:5)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
  

  3) _3DCartSaveOrders "before each" hook:
     TypeError: Cannot read property 'extend' of undefined
    at _3DCartSaveOrders.Strategy (/home/starfall/workspace/3dcart-workflows/core/lib/Strategy.coffee:15:12)
    at _3DCartSaveOrders.DBStrategy (/home/starfall/workspace/3dcart-workflows/core/lib/Strategy/DBStrategy.coffee:7:5)
    at _3DCartSaveOrders.Save (/home/starfall/workspace/3dcart-workflows/core/lib/Strategy/DBStrategy/Save.coffee:9:5)
    at _3DCartSaveOrders.TemporaryTable (/home/starfall/workspace/3dcart-workflows/core/lib/Strategy/DBStrategy/Save/TemporaryTable.coffee:14:5)
    at new _3DCartSaveOrders (/home/starfall/workspace/3dcart-workflows/lib/Strategy/DBStrategy/Save/TemporaryTable/_3DCartSaveOrders.coffee:5:7)
    at Context.<anonymous> (/home/starfall/workspace/3dcart-workflows/test/lib/Strategy/DBStrategy/Save/TemporaryTable/_3DCartSaveOrdersSpec.coffee:33:16)
    at callFn (/home/starfall/workspace/3dcart-workflows/node_modules/mocha/lib/runnable.js:251:21)
    at Hook.Runnable.run (/home/starfall/workspace/3dcart-workflows/node_modules/mocha/lib/runnable.js:244:7)
    at next (/home/starfall/workspace/3dcart-workflows/node_modules/mocha/lib/runner.js:259:10)
    at Immediate._onImmediate (/home/starfall/workspace/3dcart-workflows/node_modules/mocha/lib/runner.js:276:5)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

* Ubuntu 14.04
* Webstorm 10.0.4
* Wallaby 1.0.27

**Comment by ArtemGovorov** [comment]
Fixed incorrectly reported tests issue, added info about failing hooks to be displayed. The fix is in core v.1.0.101.

**Comment by DenisGorbachev** [comment]
Thanks!
