### ISSUE TITLE
TypeError: 'get' on proxy: property 'prototype' is a read-only and non-configurable data property

### ISSUE THREAD

**Issue by jferg-newcontext** [wallabyjs/public#2532]
I have a set of tests that run fine from the command-line (just by running `jest`) but they fail when I try to run them through wallaby with the error:  	

TypeError: 'get' on proxy: property 'prototype' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '[object Array]' but got '[object Object]')
		at Function.getIssueTypeForStory src/services/integrations/jira.utilities.ts:236:5
		at Object.<anonymous> test/integration/jira.utilities.spec.ts:114:9

This happens with both automatic and file-based configuration (though since I need to set environment variables I have to use a config file).  

The line in question is:  

```js
const createItemProjectData = ciMetadata?.projects.filter((f) => f.id === projectId);
```

and I've tried breaking it down to:

```js
   const projectMetadata = ciMetadata?.projects;
    const createItemProjectData = projectMetadata.filter((f) => {
      return projectId === f.id;
    });
```

with no success.  

Diagnostics report below.  

### Wallaby diagnostics report

```
{
  editorVersion: 'IntelliJ IDEA 2020.2.2',
  pluginVersion: '1.0.198',
  editorType: 'IntelliJ',
  osVersion: 'darwin 19.6.0',
  nodeVersion: 'v14.5.0',
  coreVersion: '1.0.970',
  checksum: 'ODljNzVjMWRjODE3NTEwZmQyNzIwYmYxZjJmZjZlZDIsMTYzMTY2NDAwMDAwMCww',
  config: {
    hints: {
      ignoreCoverage: '__REGEXP /istanbul ignore next/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    env: {
      params: { env: "MONGO_URL='https://****:****@localhost:27018/test/';APP_ENV='test';NODE_ENV='test'" },
      type: 'node',
      runner: '/usr/local/Cellar/node/14.5.0/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/private/var/folders/tk/sq4ysdls6wl_d9w2nl811sq80000gp/T/jest_dy',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/app/v2',
              dependencyExtractor: undefined,
              detectLeaks: undefined,
              detectOpenHandles: undefined,
              displayName: undefined,
              errorOnDeprecated: false,
              extraGlobals: [],
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, throwOnModuleCollision: false },
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [ 'js', 'json', 'jsx', 'ts', 'tsx', 'node' ],
              moduleLoader: undefined,
              moduleNameMapper: [],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              name: '697350d506d24e356796783c92fd2aa6',
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/app/v2',
              roots: [ '<homeDir>/app/v2' ],
              runner: 'jest-runner',
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/app/v2/node_modules/jest-environment-node/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
              testPathIgnorePatterns: [ '/node_modules/', '/frontend/', '/archive/', '/cms/' ],
              testRegex: [],
              testRunner: '<homeDir>/v2/node_modules/jest-jasmine2/build/index.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [ [ '^.+\\.tsx?$', '<homeDir>/app/v2/node_modules/ts-jest/dist/index.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: [],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<homeDir>/app/v2/coverage',
            coverageProvider: 'v8',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: undefined,
            detectOpenHandles: undefined,
            enabledTestsMap: undefined,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: undefined,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 5,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: undefined,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/app/v2',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/app/v2/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|/\\..+/', '/frontend/', '/archive/', '/cms/' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|/\\..+/', '/frontend/', '/archive/', '/cms/' ],
            testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    filesWithCoverageCalculated: [],
    globalSetup: false,
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    micromatch: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
      { pattern: '\\./dist/|\\./build/|\\./coverage/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\/\..+\//, ignore: true, trigger: true, load: true },
      { pattern: '/frontend/', regexp: /\/frontend\//, ignore: true, trigger: true, load: true },
      { pattern: '/archive/', regexp: /\/archive\//, ignore: true, trigger: true, load: true },
      { pattern: '/cms/', regexp: /\/cms\//, ignore: true, trigger: true, load: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
      { pattern: '\\./dist/|\\./build/|\\./coverage/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\/\..+\//, ignore: true, trigger: true, load: true, test: true },
      { pattern: '/frontend/', regexp: /\/frontend\//, ignore: true, trigger: true, load: true, test: true },
      { pattern: '/archive/', regexp: /\/archive\//, ignore: true, trigger: true, load: true, test: true },
      { pattern: '/cms/', regexp: /\/cms\//, ignore: true, trigger: true, load: true, test: true },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 }
    ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'module.exports = function () {\n' +
      '  return {\n' +
      '    autoDetect: true,\n' +
      '    hints: {\n' +
      '      ignoreCoverage: /istanbul ignore next/,\n' +
      '    },\n' +
      '    env: {\n' +
      '      params: {\n' +
      `        env: "MONGO_URL='https://****:****@localhost:27018/test/';APP_ENV='test';NODE_ENV='test'",\n` +
      '      },\n' +
      '    },\n' +
      '  };\n' +
      '};\n'
  },
  packageJSON: {
    dependencies: {
      '@koa/cors': '^3.1.0',
      '@koa/multer': '^3.0.0',
      '@koa/router': '^9.3.1',
      '@sentry/node': '^5.23.0',
      '@types/cron': '^1.7.2',
      '@types/koa-static-server': '^1.3.0',
      '@types/lodash': '^4.14.161',
      '@types/source-map-support': '^0.5.3',
      ajv: '^6.12.3',
      'async-busboy': '^1.0.1',
      'atlassian-jwt': '^1.0.3',
      axios: '^0.19.2',
      'axios-cookiejar-support': '^1.0.0',
      conscript: '^0.2.0',
      convict: '^6.0.0',
      'convict-format-with-validator': '^6.0.0',
      cron: '^1.8.2',
      'deep-object-diff': '^1.1.0',
      'jira-client': '^6.18.0',
      'js-yaml': '^3.14.0',
      jsonwebtoken: '^8.5.1',
      koa: '^2.13.0',
      'koa-body': '^4.2.0',
      'koa-bunyan-logger': '^2.1.0',
      'koa-helmet': '^5.2.0',
      'koa-jwt': '^4.0.0',
      'koa-jwt2': '^1.0.3',
      'koa-logger': '^3.2.1',
      'koa-mount': '^4.0.0',
      'koa-multer': '^1.0.2',
      'koa-socket-2': '^1.2.0',
      'koa-static': '^5.0.0',
      'koa-static-server': '^1.5.2',
      'koa-swagger-decorator': '^1.7.0',
      'koa-unless': '^1.0.7',
      lodash: '^4.17.20',
      merge: '^1.2.1',
      mongodb: '^3.6.0',
      mongoose: '^5.10.7',
      'object-scan': '^13.1.6',
      'path-to-regexp': '^1.1.1',
      pg: '^8.3.0',
      'pg-hstore': '^2.3.3',
      'reflect-metadata': '^0.1.13',
      'socket.io': '^2.3.0',
      'source-map-support': '^0.5.19',
      'tough-cookie': '^4.0.0',
      'ts-node': '^8.10.2',
      typeorm: '^0.2.25',
      typescript: '^4.0.3',
      uuid: '^8.3.0'
    },
    devDependencies: {
      '@deboxsoft/cpx': '^1.5.0',
      '@types/chai': '^4.2.12',
      '@types/config': '0.0.36',
      '@types/convict': '^5.2.1',
      '@types/convict-format-with-validator': '^6.0.1',
      '@types/jest': '^26.0.8',
      '@types/js-yaml': '^3.12.5',
      '@types/jsonwebtoken': '^8.5.0',
      '@types/koa': '^2.11.3',
      '@types/koa-bodyparser': '^4.3.0',
      '@types/koa-bunyan-logger': '^2.1.2',
      '@types/koa-helmet': '^5.2.0',
      '@types/koa__router': '^8.0.2',
      '@types/mongoose': '^5.7.34',
      '@types/sinon': '^9.0.4',
      '@types/supertest': '^2.0.10',
      '@types/tough-cookie': '^4.0.0',
      '@types/uuid': '^8.0.0',
      babel: '^6.23.0',
      chai: '^4.2.0',
      jest: '^26.2.2',
      'jest-preset-typescript': '^1.2.0',
      jsdoc: '^3.6.5',
      'koa-create-context': '^1.0.2',
      nodemon: '^2.0.4',
      prettier: '^2.0.5',
      shx: '^0.3.2',
      sinon: '^9.0.2',
      supertest: '^5.0.0',
      'ts-jest': '^26.1.4',
      'ts-node-dev': '^1.0.0-pre.56',
      'ts-sinon': '^1.2.0',
      'tsc-watch': '^4.2.9',
      'tsconfig-paths': '^3.9.0',
      typedoc: '^0.18.0',
      'typedoc-plugin-localization': '^2.2.1'
    }
  },
  fs: { numberOfFiles: 316 },
  debug: [
    '2020-10-06T00:05:20.689Z angular/cli config Angular CLI not found.\n',
    '2020-10-06T00:05:20.784Z jest/config Detected Jest.\n',
    '2020-10-06T00:05:20.785Z jest/config Configured Jest.\n',
    '2020-10-06T00:05:20.786Z project Wallaby Node version: v14.5.0\n',
    '2020-10-06T00:05:20.786Z project Wallaby config: <homeDir>/app/v2/wallaby.js\n',
    '2020-10-06T00:05:21.912Z project File cache: <homeDir>/Library/Caches/JetBrains/IntelliJIdea2020.2/wallaby/projects/67cb5581638f1e40\n',
    '2020-10-06T00:05:21.926Z uiService Listening port 51235\n',
    '2020-10-06T00:05:21.938Z project Config file change detected, invalidating local cache\n',
    '2020-10-06T00:05:21.965Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2020-10-06T00:05:21.965Z workers Starting run worker instance #0\n',
    '2020-10-06T00:05:21.966Z workers Starting run worker instance #1\n',
    '2020-10-06T00:05:21.966Z workers Starting run worker instance #2\n',
    '2020-10-06T00:05:21.966Z workers Starting run worker instance #3\n',
    '2020-10-06T00:05:21.966Z workers Starting run worker instance #4\n',
    '2020-10-06T00:05:21.966Z workers Starting run worker instance #5\n',
    '2020-10-06T00:05:21.966Z workers Web server is listening at 53728\n',
    '2020-10-06T00:05:21.966Z project File cache requires some updates, waiting required files from IDE\n',
    '2020-10-06T00:05:22.066Z project Stopping process pool\n',
    '2020-10-06T00:05:22.070Z project Test run started; run priority: 3\n',
    '2020-10-06T00:05:22.073Z project Running all tests\n',
    '2020-10-06T00:05:22.090Z workers Starting test run, priority: 3\n',
    '2020-10-06T00:05:22.090Z workers Distributing tests between 6 workers\n',
    '2020-10-06T00:05:22.091Z workers Running tests in parallel\n',
    '2020-10-06T00:05:22.092Z nodeRunner Starting sandbox [worker #0, session #kdme7]\n',
    '2020-10-06T00:05:22.092Z nodeRunner Starting sandbox [worker #1, session #wqd7k]\n',
    '2020-10-06T00:05:22.092Z nodeRunner Starting sandbox [worker #2, session #n27rb]\n',
    '2020-10-06T00:05:22.092Z nodeRunner Starting sandbox [worker #3, session #fyo8v]\n',
    '2020-10-06T00:05:22.092Z nodeRunner Starting sandbox [worker #4, session #xnxsk]\n',
    '2020-10-06T00:05:22.092Z nodeRunner Starting sandbox [worker #5, session #hql3t]\n',
    '2020-10-06T00:05:22.093Z nodeRunner Preparing sandbox [worker #0, session #kdme7]\n',
    '2020-10-06T00:05:22.093Z nodeRunner Preparing sandbox [worker #1, session #wqd7k]\n',
    '2020-10-06T00:05:22.093Z nodeRunner Preparing sandbox [worker #2, session #n27rb]\n',
    '2020-10-06T00:05:22.093Z nodeRunner Preparing sandbox [worker #3, session #fyo8v]\n',
    '2020-10-06T00:05:22.093Z nodeRunner Preparing sandbox [worker #4, session #xnxsk]\n',
    '2020-10-06T00:05:22.093Z nodeRunner Preparing sandbox [worker #5, session #hql3t]\n',
    '2020-10-06T00:05:22.237Z workers Started run worker instance (delayed) #0\n',
    '2020-10-06T00:05:22.238Z nodeRunner Prepared sandbox [worker #0, session #kdme7]\n',
    '2020-10-06T00:05:22.238Z workers [worker #0, session #kdme7] Running tests in sandbox\n',
    '2020-10-06T00:05:22.242Z workers Started run worker instance (delayed) #3\n',
    '2020-10-06T00:05:22.243Z nodeRunner Prepared sandbox [worker #3, session #fyo8v]\n',
    '2020-10-06T00:05:22.243Z workers [worker #3, session #fyo8v] Running tests in sandbox\n',
    '2020-10-06T00:05:22.246Z workers Started run worker instance (delayed) #1\n',
    '2020-10-06T00:05:22.246Z nodeRunner Prepared sandbox [worker #1, session #wqd7k]\n',
    '2020-10-06T00:05:22.246Z workers [worker #1, session #wqd7k] Running tests in sandbox\n',
    '2020-10-06T00:05:22.249Z workers Started run worker instance (delayed) #2\n',
    '2020-10-06T00:05:22.249Z nodeRunner Prepared sandbox [worker #2, session #n27rb]\n',
    '2020-10-06T00:05:22.249Z workers [worker #2, session #n27rb] Running tests in sandbox\n',
    '2020-10-06T00:05:22.252Z workers Started run worker instance (delayed) #4\n',
    '2020-10-06T00:05:22.252Z nodeRunner Prepared sandbox [worker #4, session #xnxsk]\n',
    '2020-10-06T00:05:22.252Z workers [worker #4, session #xnxsk] Running tests in sandbox\n',
    '2020-10-06T00:05:22.257Z workers Started run worker instance (delayed) #5\n',
    '2020-10-06T00:05:22.258Z nodeRunner Prepared sandbox [worker #5, session #hql3t]\n',
    '2020-10-06T00:05:22.258Z workers [worker #5, session #hql3t] Running tests in sandbox\n',
    '2020-10-06T00:06:03.730Z workers [fyo8v] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:04.349Z workers [hql3t] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:05.665Z workers [xnxsk] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:06.065Z workers [hql3t] Test executed: correctly fetches a record by id\n',
    '2020-10-06T00:06:06.067Z workers Failed to map the stack to user code, entry message: Error: Timeout - Async callback was not invoked within the 10000 ms timeout specified by jest.setTimeout., stack: Timeout - Async callback was not invoked within the 10000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 10000 ms timeout specified by jest.setTimeout.\n' +
      '    at mapper (<homeDir>/app/v2/node_modules/jest-jasmine2/build/queueRunner.js:27:45)\n' +
      '    at <homeDir>/app/v2/node_modules/jest-jasmine2/build/queueRunner.js:75:41\n',
    '2020-10-06T00:06:06.088Z workers [hql3t] Test executed: fetches a record and updates the sync status\n',
    '2020-10-06T00:06:06.089Z workers Failed to map the stack to user code, entry message: Error: Timeout - Async callback was not invoked within the 10000 ms timeout specified by jest.setTimeout., stack: Timeout - Async callback was not invoked within the 10000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 10000 ms timeout specified by jest.setTimeout.\n' +
      '    at mapper (<homeDir>/app/v2/node_modules/jest-jasmine2/build/queueRunner.js:27:45)\n' +
      '    at <homeDir>/app/v2/node_modules/jest-jasmine2/build/queueRunner.js:75:41\n',
    '2020-10-06T00:06:07.476Z workers [xnxsk] Test executed: correctly validates the atlassian jwt when we have a clientkey\n',
    "2020-10-06T00:06:07.477Z workers [xnxsk] Test executed: correctly decodes the atlassian jwt when we don't have a clientkey\n",
    '2020-10-06T00:06:07.571Z workers [xnxsk] Test executed: correctly creates a jira issue from a story\n',
    '2020-10-06T00:06:13.657Z workers Sandbox (active) [fyo8v] error: Caught error after test environment was torn down\n\nNo metadata for "IntegrationConfiguration" was found.\n',
    '2020-10-06T00:06:13.759Z workers [fyo8v] Run 0 test(s), skipped 0 test(s)\n',
    '2020-10-06T00:06:13.820Z workers [hql3t] Test executed: only finds new records correctly\n',
    '2020-10-06T00:06:13.820Z workers Failed to map the stack to user code, entry message: Error: Timeout - Async callback was not invoked within the 10000 ms timeout specified by jest.setTimeout., stack: Timeout - Async callback was not invoked within the 10000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 10000 ms timeout specified by jest.setTimeout.\n' +
      '    at mapper (<homeDir>/app/v2/node_modules/jest-jasmine2/build/queueRunner.js:27:45)\n' +
      '    at <homeDir>/app/v2/node_modules/jest-jasmine2/build/queueRunner.js:75:41\n',
    '2020-10-06T00:06:16.652Z workers [fyo8v] Sandbox is responsive, closing it\n',
    '2020-10-06T00:06:16.654Z workers Failed to map the stack to user code, entry message: Caught error after test environment was torn down\n' +
      '\n' +
      'No metadata for "IntegrationConfiguration" was found., stack: EntityMetadataNotFound: Caught error after test environment was torn down\n' +
      '\n' +
      'No metadata for "IntegrationConfiguration" was found.\n' +
      '    at new EntityMetadataNotFoundError (<homeDir>/app/v2/src/error/EntityMetadataNotFoundError.ts:9:9)\n' +
      '    at Connection.getMetadata (<homeDir>/app/v2/src/connection/Connection.ts:333:19)\n' +
      '    at <homeDir>/app/v2/src/persistence/EntityPersistExecutor.ts:77:55\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at EntityPersistExecutor.<anonymous> (<homeDir>/app/v2/src/persistence/EntityPersistExecutor.ts:71:30)\n' +
      '    at step (<homeDir>/app/v2/node_modules/tslib/tslib.js:141:27)\n' +
      '    at Object.next (<homeDir>/app/v2/node_modules/tslib/tslib.js:122:57)\n' +
      '    at <homeDir>/app/v2/node_modules/tslib/tslib.js:115:75\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at Object.__awaiter (<homeDir>/app/v2/node_modules/tslib/ts\n',
    '2020-10-06T00:06:17.045Z workers [hql3t] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:17.045Z workers [hql3t] Test executed: instantiates correctly\n',
    '2020-10-06T00:06:17.047Z workers [hql3t] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:17.048Z workers [hql3t] Test executed: instantiates correctly\n',
    '2020-10-06T00:06:17.050Z workers [hql3t] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:17.050Z workers [hql3t] Test executed: instantiates correctly\n',
    '2020-10-06T00:06:17.128Z workers [hql3t] Run 6 test(s), skipped 0 test(s)\n',
    '2020-10-06T00:06:17.131Z workers [hql3t] Sandbox is responsive, closing it\n',
    '2020-10-06T00:06:17.782Z workers [kdme7] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:17.782Z workers [kdme7] Test executed: instantiates correctly\n',
    '2020-10-06T00:06:17.783Z workers [kdme7] Test executed: calls _updateStories, _updateAssessments, and _updateEpics private methods\n',
    '2020-10-06T00:06:17.786Z workers [kdme7] Test executed: updates labelModifiers for all stories\n',
    '2020-10-06T00:06:17.787Z workers [kdme7] Test executed: _saveStoryLabelModifiers uses QueryRunner for transaction to update entry\n',
    '2020-10-06T00:06:17.793Z workers [kdme7] Test executed: updates ratings for all assessments\n',
    '2020-10-06T00:06:17.794Z workers [kdme7] Test executed: _saveAssessmentRatings uses QueryRunner for transaction to update entry\n',
    '2020-10-06T00:06:17.796Z workers [kdme7] Test executed: updates impacts for all epics\n',
    '2020-10-06T00:06:17.797Z workers [kdme7] Test executed: _saveEpicImpacts uses QueryRunner for transaction to update entry\n',
    '2020-10-06T00:06:17.800Z workers [kdme7] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:17.802Z workers [kdme7] Test executed: properly instantiates and assigns default values\n',
    '2020-10-06T00:06:17.804Z workers [kdme7] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:17.804Z workers [kdme7] Test executed: instantiates correctly\n',
    '2020-10-06T00:06:17.806Z workers [kdme7] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:17.807Z workers [kdme7] Test executed: instantiates correctly\n',
    '2020-10-06T00:06:17.842Z workers [kdme7] Run 11 test(s), skipped 0 test(s)\n',
    '2020-10-06T00:06:17.845Z workers [kdme7] Sandbox is responsive, closing it\n',
    '2020-10-06T00:06:19.046Z workers [n27rb] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:19.047Z workers [n27rb] Test executed: should POST worksheet `fixture/example-ws1`\n',
    '2020-10-06T00:06:19.049Z workers [n27rb] Test executed: should GET our just created worksheet\n',
    '2020-10-06T00:06:19.153Z workers [n27rb] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:19.154Z workers [n27rb] Test executed: properly instantiates and assigns default values\n',
    '2020-10-06T00:06:19.155Z workers [n27rb] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:19.156Z workers [n27rb] Test executed: instantiates correctly\n',
    '2020-10-06T00:06:19.159Z workers [n27rb] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:19.160Z workers [n27rb] Test executed: instantiates correctly\n',
    '2020-10-06T00:06:19.200Z workers [n27rb] Run 5 test(s), skipped 0 test(s)\n',
    '2020-10-06T00:06:19.202Z workers [n27rb] Sandbox is responsive, closing it\n',
    '2020-10-06T00:06:19.867Z workers [wqd7k] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:19.867Z workers [wqd7k] Test executed: should always pass\n',
    '2020-10-06T00:06:19.868Z workers [wqd7k] Test executed: should GET /v2/healthcheck\n',
    '2020-10-06T00:06:19.875Z workers [wqd7k] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:19.876Z workers [wqd7k] Test executed: successfully constructs an instance of itself\n',
    '2020-10-06T00:06:19.877Z workers [wqd7k] Test executed: filters out all attributes from an object which start with underscore\n',
    '2020-10-06T00:06:19.966Z workers [wqd7k] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:19.967Z workers [wqd7k] Test executed: instantiates correctly\n',
    '2020-10-06T00:06:19.968Z workers [wqd7k] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:19.969Z workers [wqd7k] Test executed: instantiates correctly\n',
    '2020-10-06T00:06:19.996Z workers [wqd7k] Run 6 test(s), skipped 0 test(s)\n',
    '2020-10-06T00:06:19.998Z workers [wqd7k] Sandbox is responsive, closing it\n',
    '2020-10-06T00:06:20.991Z workers [xnxsk] Test executed: correctly determines the issueType from a story\n',
    '2020-10-06T00:06:20.994Z workers [xnxsk] Test executed: correctly determines the issueType from an epic\n',
    '2020-10-06T00:06:21.014Z workers [xnxsk] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:21.015Z workers [xnxsk] Test executed: instantiates correctly\n',
    '2020-10-06T00:06:21.015Z workers [xnxsk] Test executed: validates correctly-formed enrollment request\n',
    '2020-10-06T00:06:21.015Z workers [xnxsk] Test executed: correctly requests and extracts the UPM token\n',
    '2020-10-06T00:06:21.016Z workers [xnxsk] Test executed: correctly verifies the JSON schema of an enrollment request\n',
    '2020-10-06T00:06:21.017Z workers [xnxsk] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:21.019Z workers [xnxsk] Test executed: instantiates correctly\n',
    '2020-10-06T00:06:21.022Z workers [xnxsk] Loaded unknown number of test(s)\n',
    '2020-10-06T00:06:21.023Z workers [xnxsk] Test executed: should correctly add baseUrl to metadata for HttpService decorator\n',
    '2020-10-06T00:06:21.024Z workers [xnxsk] Test executed: should correctly add decorated HttpActions to the object metadata\n',
    "2020-10-06T00:06:21.024Z workers [xnxsk] Test executed: should handle @[METHOD]('/foo') as @HttpAction('[METHOD]', '/foo')\n",
    '2020-10-06T00:06:21.059Z workers [xnxsk] Run 13 test(s), skipped 0 test(s)\n',
    '2020-10-06T00:06:21.062Z workers [xnxsk] Sandbox is responsive, closing it\n',
    '2020-10-06T00:06:21.062Z workers Merging parallel test run results\n',
    '2020-10-06T00:06:21.070Z project Test run finished\n',
    '2020-10-06T00:06:21.071Z project Processed console.log entries\n',
    '2020-10-06T00:06:21.072Z project Processed loading sequences\n',
    '2020-10-06T00:06:21.073Z project Processed executed tests\n',
    '2020-10-06T00:06:21.095Z project Processed code coverage\n',
    '2020-10-06T00:06:21.218Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
- Are you using ES proxies anywhere in your code (or are aware of/suspect any modules that you are using may be using ES proxies)?
- Can you please search for `??` in the `src/services/integrations/jira.utilities.ts` and `test/integration/jira.utilities.spec.ts` files? The `//??` (or `/*??*/`) comment [makes Wallaby wrap the target into a proxy](https://wallabyjs.com/docs/intro/advanced-logging.html#object-proxy), and not everything can be wrapped and still work correctly?

**Comment by jferg-newcontext** [comment]
Depending on several things, ciMetadata is either going to be an object property of a `typeorm` Model, or an object property of an `axios` response.  (I believe in this case it's `typeorm`.). There _was_ a //?? in the file, but I removed it and am seeing the same behavior.

**Comment by ArtemGovorov** [comment]
> There was a `//??` in the file, but I removed it and am seeing the same behavior.

- Was the comment next to the code in question (or next to the part of code that is related to the code in question)?
- Have you tried to restart Wallaby after the change? 

The error can only occur when using ES proxies, and Wallaby doesn't have any code that works with proxies other than the `//??` proxy wrapper comment. If removing the comment and restarting Wallaby doesn't help, we'll need some more context to be able to reproduce the issue. Can you please try to copy/paste the problematic test in your test file, try to minimize what it's doing, and share the the example with us? We'll then set up a sample repo with your dependencies and will try to reproduce it.

**Comment by jferg-newcontext** [comment]
* It was not exactly in the code in question but could have been upstream, I didn't trace through to be sure.   
* Yes, I did restart.  

It'll take me a bit to extract it out into a share-able code sample, but I will see what I can do later today.

**Comment by smcenlly** [comment]
@jferg-newcontext - I'm going to close this issue as we haven't heard back. If you create a reproduceable sample, please share and reply to this issue and we'll re-open.
