### ISSUE TITLE
Question: Is there a way to get the name of children components with specific error?

### ISSUE THREAD

**Issue by blopez2010** [wallabyjs/public#2549]
### Issue description or question

I've been working on a project which turned on a big one since a year ago, we have many tests in pace and recently I've been seeing an error in the Wallaby Console which I know what the error is but I can't get to the correct component to fix it. We are using jest with Enzyme; the test wrapper is being built using a `mount` so probably a children is the one having the issue. Is there any way to get within the console log error the source component throwing it?

### Wallaby diagnostics report

```console.log: Jest:   ● Console
[Info]      console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
[Info]        Error: Error: connect ECONNREFUSED 127.0.0.1:80
[Info]            at Object.dispatchError (C:\Code\Web\next-js\node_modules\jsdom\lib\jsdom\living\xhr-utils.js:65:19)
[Info]            at Request.<anonymous> (C:\Code\Web\next-js\node_modules\jsdom\lib\jsdom\living\xmlhttprequest.js:676:20)
[Info]            at Request.emit (events.js:228:7)
[Info]            at Request.onRequestError (C:\Code\Web\next-js\node_modules\request\request.js:881:8)
[Info]            at ClientRequest.emit (events.js:223:5)
[Info]            at Socket.socketErrorListener (_http_client.js:406:9)
[Info]            at Socket.emit (events.js:223:5)
[Info]            at emitErrorNT (internal/streams/destroy.js:92:8)
[Info]            at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
[Info]            at processTicksAndRejections (internal/process/task_queues.js:81:21) undefined
[Info]      console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
[Info]        Error: Error: connect ECONNREFUSED 127.0.0.1:80
[Info]            at Object.dispatchError (C:\Code\Web\next-js\node_modules\jsdom\lib\jsdom\living\xhr-utils.js:65:19)
[Info]            at Request.<anonymous> (C:\Code\Web\next-js\node_modules\jsdom\lib\jsdom\living\xmlhttprequest.js:676:20)
[Info]            at Request.emit (events.js:228:7)
[Info]            at Request.onRequestError (C:\Code\Web\next-js\node_modules\request\request.js:881:8)
[Info]            at ClientRequest.emit (events.js:223:5)
[Info]            at Socket.socketErrorListener (_http_client.js:406:9)
[Info]            at Socket.emit (events.js:223:5)
[Info]            at emitErrorNT (internal/streams/destroy.js:92:8)
[Info]            at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
[Info]            at processTicksAndRejections (internal/process/task_queues.js:81:21) undefined
[Info]      console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
[Info]        Error: Error: connect ECONNREFUSED 127.0.0.1:80
[Info]            at Object.dispatchError (C:\Code\Web\next-js\node_modules\jsdom\lib\jsdom\living\xhr-utils.js:65:19)
[Info]            at Request.<anonymous> (C:\Code\Web\next-js\node_modules\jsdom\lib\jsdom\living\xmlhttprequest.js:676:20)
[Info]            at Request.emit (events.js:228:7)
[Info]            at Request.onRequestError (C:\Code\Web\next-js\node_modules\request\request.js:881:8)
[Info]            at ClientRequest.emit (events.js:223:5)
[Info]            at Socket.socketErrorListener (_http_client.js:406:9)
[Info]            at Socket.emit (events.js:223:5)
[Info]            at emitErrorNT (internal/streams/destroy.js:92:8)
[Info]            at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
[Info]            at processTicksAndRejections (internal/process/task_queues.js:81:21) undefined
[Error] The sandbox is not responsive. Check for possibly recently introduced infinite loops. ```

**Comment by smcenlly** [comment]
If the console.log error stack doesn't contain details of the component that is throwing the error then unfortunately Wallaby cannot report on it.

If you run your tests outside of Wallaby, do you get any more detail?

Is your project open source? If so, we'd be happy to take a look and provide you with guidance on how to isolate the cause of the error.
