### ISSUE TITLE
Sandbox load failed, status: failed: Chrome is not running

### ISSUE THREAD

**Issue by hsantesteban** [wallabyjs/public#2581]
### Issue description or question

Hello.

I recently bought Wallaby and am trying hard to integrate it with the existing project. The development efforts are being made on Windows leveraging technologies such as: VueJS 2.6, VueCLI 4+ and Mocha.

I copied the configuration file from the wallaby docs for Mocha and VueCLI 4+ and setup a wallaby.js file. During the startup of Wallaby I noticed that initially there was an exception while running the function `mapResourceToPath`:

```
undefined
TypeError: Cannot read property 'indexOf' of undefined
    at t.mapResourceToPath [as _mapResourceToPath] (C:\dev\cygnus-analytics\front-end\wallaby.js:34:21)
    at t.<anonymous> (C:\Users\herna\AppData\Local\JetBrains\WebStorm2020.3\wallaby\wallaby\server.js:21:760)
    at n (C:\Users\herna\AppData\Local\JetBrains\WebStorm2020.3\wallaby\wallaby\server.js:20:28910)
    at Object.next (C:\Users\herna\AppData\Local\JetBrains\WebStorm2020.3\wallaby\wallaby\server.js:20:28205)
    at o (C:\Users\herna\AppData\Local\JetBrains\WebStorm2020.3\wallaby\wallaby\server.js:20:27964)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

So I tried to catch the error in order to, at least, allow wallaby to finish the initialisation:

```js
const mapResourceToPath = (context) => {
    try {
    const resource = context.resource;

    if (context.version) {
        // loading phase
        if (resource.endsWith("vue")) {
            return `${resource}?ignore`;
        }
        console.log(resource);
        return resource.indexOf("type=script") > 0
            ? context.resourcePath
            : resource;
    }
    console.log(resource);
    // processing phase
    return resource.indexOf("type=script") > 0 && context.wallaby
        ? resource.substring(0, resource.indexOf("?"))
        : resource.endsWith("vue")
            ? `${resource}?ignore`
            : resource;
    }
    catch(e) {
        console.log(e)
    }
};
```

As you can see, I added a couple of console.logs to see what was going on, but overall the `catch` did the trick and allowed Wallaby to finish the initialisation (?). However, to my surprise this was not enough as I get another error that this time is related to Chrome.

```
connect ECONNREFUSED 127.0.0.1:25136
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16)
Test run failure: Sandbox load failed, status: failed: Chrome is not running
```

I read a couple of issues and I can confirm that the environment variable CHROME_PATH is set: both for the user and the system.

`CHROME_PATH = C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`

I am not bound to using Mocha, I tried Jest but the lack of support (early stages support) for ES6 Modules was a pain to setup. However, if this error is fixed faster by configuring Jest correctly to pickup ES6 Modules, I can make the move.

Thanks for your help.

### Wallaby diagnostics report

```
{
  editorVersion: 'WebStorm 2020.3',
  pluginVersion: '1.0.203',
  editorType: 'IntelliJ',
  osVersion: 'win32 10.0.19042',
  nodeVersion: 'v15.3.0',
  coreVersion: '1.0.991',
  checksum: 'NDhmZTQ1MDBmNjQyYzhjM2IwNTRhN2NkNDE1MjIyMDMsMTYzODE0NDAwMDAwMCww',
  config: {
    files: [ { pattern: 'src/**/*.*', load: false, ignore: false, trigger: true, order: 1 } ],
    tests: [ { pattern: 'tests/**/*.*', load: false, ignore: false, trigger: true, test: true, order: 2 } ],
    env: {
      kind: 'chrome',
      params: { runner: '--headless --disable-gpu --remote-debugging-port=9222' },
      type: 'browser',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    testFramework: { version: 'jasmine@3.5.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3' },
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'const config = require("@vue/cli-service/webpack.config.js");\r\n' +
      '\r\n' +
      'const redundantPlugins = {\r\n' +
      '    ForkTsCheckerWebpackPlugin: true,\r\n' +
      '    PreloadPlugin: true,\r\n' +
      '    HtmlWebpackPlugin: true,\r\n' +
      '    CopyPlugin: true,\r\n' +
      '    CaseSensitivePathsPlugin: true,\r\n' +
      '    FriendlyErrorsWebpackPlugin: true,\r\n' +
      '};\r\n' +
      '\r\n' +
      'config.plugins = config.plugins.filter(\r\n' +
      '    (plugin) => !(plugin.constructor && redundantPlugins[plugin.constructor.name])\r\n' +
      ');\r\n' +
      '\r\n' +
      '// vue files are split into multiple webpack modules,\r\n' +
      '// we need to choose and map script webpack resource (i.e. module) to one absolute file path\r\n' +
      'const mapResourceToPath = (context) => {\r\n' +
      '    try {\r\n' +
      '    const resource = context.resource;\r\n' +
      '\r\n' +
      '    if (context.version) {\r\n' +
      '        // loading phase\r\n' +
      '        if (resource.endsWith("vue")) {\r\n' +
      '            return `${resource}?ignore`;\r\n' +
      '        }\r\n' +
      '        console.log(resource);\r\n' +
      '        return resource.indexOf("type=script") > 0\r\n' +
      '            ? context.resourcePath\r\n' +
      '            : resource;\r\n' +
      '    }\r\n' +
      '    console.log(resource);\r\n' +
      '    // processing phase\r\n' +
      '    return resource.indexOf("type=script") > 0 && context.wallaby\r\n' +
      '        ? resource.substring(0, resource.indexOf("?"))\r\n' +
      '        : resource.endsWith("vue")\r\n' +
      '            ? `${resource}?ignore`\r\n' +
      '            : resource;\r\n' +
      '    }\r\n' +
      '    catch(e) {\r\n' +
      '        console.log(e)\r\n' +
      '    }\r\n' +
      '};\r\n' +
      '\r\n' +
      'module.exports = function(wallaby) {\r\n' +
      '    return {\r\n' +
      '        files: [{ pattern: "src/**/*.*", load: false }],\r\n' +
      '\r\n' +
      '        tests: [{ pattern: "tests/**/*.*", load: false }],\r\n' +
      '\r\n' +
      '        postprocessor: wallaby.postprocessors.webpack(config, {\r\n' +
      '            setupFiles: [require.resolve("@vue/cli-plugin-unit-mocha/setup")],\r\n' +
      '            mapResourceToPath: mapResourceToPath,\r\n' +
      '        }),\r\n' +
      '\r\n' +
      '        env: {\r\n' +
      '            kind: "chrome",\r\n' +
      '            params: {\r\n' +
      "                runner: '--headless --disable-gpu --remote-debugging-port=9222'\r\n" +
      '            }\r\n' +
      '        },\r\n' +
      '\r\n' +
      '        setup: function() {\r\n' +
      '            // required to trigger test loading\r\n' +
      '            window.__moduleBundler.loadTests();\r\n' +
      '        }\r\n' +
      '    };\r\n' +
      '};\r\n'
  },
  packageJSON: {
    dependencies: {
      '@d3fc/d3fc-annotation': '^3.0.6',
      '@d3fc/d3fc-extent': '^4.0.1',
      '@d3fc/d3fc-series': '^5.1.3',
      '@d3fc/d3fc-shape': '^6.0.1',
      axios: '^0.19.2',
      bootstrap: '^4.5.0',
      'bootstrap-vue': '^2.17.3',
      'core-js': '^3.6.5',
      d3: '^5.16.0',
      'd3-array': '^2.4.0',
      'd3-path': '^1.0.9',
      'd3-scale': '^3.2.1',
      'd3-selection': '^1.4.1',
      'd3-shape': '^1.3.7',
      firebase: '^7.20.0',
      'html-to-image': '^0.1.1',
      install: '^0.13.0',
      jquery: '^3.5.1',
      'lodash.clonedeep': '^4.5.0',
      mitt: '^2.1.0',
      moment: '^2.27.0',
      'moment-timezone': '^0.5.31',
      npm: '^6.14.8',
      nprogress: '^0.2.0',
      'popper.js': '^1.16.1',
      'string.prototype.replaceall': '^1.0.3',
      uuid: '^8.3.0',
      vue: '^2.6.11',
      'vue-color': '^2.7.1',
      'vue-infinite-scroll': '^2.0.2',
      'vue-moment': '^4.1.0',
      'vue-router': '^3.2.0',
      'vue-shortkey': '^3.1.7',
      'vue-text-highlight': '^2.0.10',
      vuelidate: '^0.7.5',
      vuex: '^3.5.1'
    },
    devDependencies: {
      '@vue/cli-plugin-babel': '^4.4.6',
      '@vue/cli-plugin-eslint': '^4.4.6',
      '@vue/cli-plugin-router': '^4.5.6',
      '@vue/cli-plugin-unit-mocha': '^4.5.9',
      '@vue/cli-service': '^4.4.6',
      '@vue/test-utils': '^1.0.3',
      'babel-eslint': '^10.1.0',
      chai: '^4.1.2',
      eslint: '^7.5.0',
      'eslint-plugin-vue': '^6.2.2',
      mocha: '^8.2.1',
      'vue-template-compiler': '^2.6.11',
      'wallaby-vue-compiler': '^1.0.6'
    }
  },
  fs: { numberOfFiles: 979 },
  debug: [
    '2020-12-03T12:09:59.085Z project Wallaby Node version: v15.3.0\n',
    '2020-12-03T12:09:59.085Z project Wallaby config: C:\\dev\\cygnus-analytics\\front-end\\wallaby.js\n',
    '2020-12-03T12:10:00.962Z project File cache: C:\\Users\\herna\\AppData\\Local\\JetBrains\\WebStorm2020.3\\wallaby\\projects\\9b3b62b1fe1bf936\n',
    '2020-12-03T12:10:01.016Z uiService Listening port 51235\n',
    '2020-12-03T12:10:01.331Z workers Parallelism for initial run: 10, for regular run: 5\n',
    '2020-12-03T12:10:01.331Z workers Starting run worker instance #0\n',
    '2020-12-03T12:10:01.331Z workers Starting run worker instance #1\n',
    '2020-12-03T12:10:01.331Z workers Starting run worker instance #2\n',
    '2020-12-03T12:10:01.331Z workers Starting run worker instance #3\n',
    '2020-12-03T12:10:01.331Z workers Starting run worker instance #4\n',
    '2020-12-03T12:10:01.331Z workers Starting run worker instance #5\n',
    '2020-12-03T12:10:01.331Z workers Starting run worker instance #6\n',
    '2020-12-03T12:10:01.331Z workers Starting run worker instance #7\n',
    '2020-12-03T12:10:01.331Z workers Starting run worker instance #8\n',
    '2020-12-03T12:10:01.331Z workers Starting run worker instance #9\n',
    '2020-12-03T12:10:01.334Z workers Web server is listening at 24707\n',
    '2020-12-03T12:10:01.345Z project Stopping process pool\n',
    '2020-12-03T12:10:01.345Z project File cache is up-to-date, starting full test run\n',
    '2020-12-03T12:10:01.347Z project Running postprocessor\n',
    '2020-12-03T12:10:01.354Z postprocessor Processing started.\n',
    '2020-12-03T12:10:01.354Z postprocessor Initializing.\n',
    '2020-12-03T12:10:01.355Z postprocessor Initializing entry.\n',
    '2020-12-03T12:10:01.355Z postprocessor Sanitizing configuration.\n',
    '2020-12-03T12:10:01.355Z postprocessor Adjusting configuration.\n',
    '2020-12-03T12:10:01.355Z postprocessor Creating compiler.\n',
    '2020-12-03T12:10:01.668Z postprocessor Customizing compiler.\n',
    '2020-12-03T12:10:01.668Z postprocessor Compilation started.\n',
    '2020-12-03T12:10:08.179Z postprocessor Compilation finished.\n',
    '2020-12-03T12:10:08.403Z postprocessor Emitting 234 files.\n',
    '2020-12-03T12:10:08.412Z postprocessor Processing finished.\n',
    '2020-12-03T12:10:08.456Z project Postprocessor execution finished\n',
    '2020-12-03T12:10:08.456Z project Test run started; run priority: 3\n',
    '2020-12-03T12:10:08.460Z project Running all tests\n',
    '2020-12-03T12:10:08.476Z workers Starting test run, priority: 3\n',
    '2020-12-03T12:10:08.476Z workers Distributing tests between 10 workers\n',
    '2020-12-03T12:10:08.476Z workers Running tests in parallel\n',
    '2020-12-03T12:10:08.476Z chromeRunner Starting sandbox [worker #0, session #g1zt9]\n',
    '2020-12-03T12:10:08.476Z chromeRunner Starting sandbox [worker #1, session #25jsu]\n',
    '2020-12-03T12:10:08.476Z chromeRunner Starting sandbox [worker #2, session #zp5e1]\n',
    '2020-12-03T12:10:30.969Z workers Started run worker instance (immediate) #0\n',
    '2020-12-03T12:10:30.970Z workers Started run worker instance (immediate) #1\n',
    '2020-12-03T12:10:30.970Z workers Started run worker instance (immediate) #2\n',
    '2020-12-03T12:10:30.970Z workers Started run worker instance (immediate) #3\n',
    '2020-12-03T12:10:30.970Z workers Started run worker instance (immediate) #4\n',
    '2020-12-03T12:10:30.970Z workers Started run worker instance (immediate) #5\n',
    '2020-12-03T12:10:30.970Z workers Started run worker instance (immediate) #6\n',
    '2020-12-03T12:10:30.970Z workers Started run worker instance (immediate) #7\n',
    '2020-12-03T12:10:30.970Z workers Started run worker instance (immediate) #8\n',
    '2020-12-03T12:10:30.970Z workers Started run worker instance (immediate) #9\n',
    '2020-12-03T12:10:30.970Z chromeRunner Preparing sandbox [worker #0, session #g1zt9]\n',
    '2020-12-03T12:10:30.971Z browserRunner Total files to load in sandbox: 5\n',
    '2020-12-03T12:10:30.972Z browserRunner Sandbox is generated [worker #0, session #g1zt9]: http://localhost:24707/wallaby_sandbox0.html\n',
    '2020-12-03T12:10:30.973Z chromeRunner Preparing sandbox [worker #1, session #25jsu]\n',
    '2020-12-03T12:10:30.974Z browserRunner Total files to load in sandbox: 5\n',
    '2020-12-03T12:10:30.975Z browserRunner Sandbox is generated [worker #1, session #25jsu]: http://localhost:24707/wallaby_sandbox1.html\n',
    '2020-12-03T12:10:30.975Z chromeRunner Preparing sandbox [worker #2, session #zp5e1]\n',
    '2020-12-03T12:10:30.977Z browserRunner Total files to load in sandbox: 5\n',
    '2020-12-03T12:10:30.978Z browserRunner Sandbox is generated [worker #2, session #zp5e1]: http://localhost:24707/wallaby_sandbox2.html\n',
    '2020-12-03T12:10:30.978Z chromeRunner Prepared sandbox [worker #0, session #g1zt9]\n',
    '2020-12-03T12:10:30.978Z chromeRunner Prepared sandbox [worker #1, session #25jsu]\n',
    '2020-12-03T12:10:30.978Z chromeRunner Prepared sandbox [worker #2, session #zp5e1]\n',
    '2020-12-03T12:10:30.978Z workers [worker #0, session #g1zt9] Running tests in sandbox\n',
    "2020-12-03T12:10:30.979Z chromeRunner Failed to evaluate code on Chrome Tab: Cannot read property 'Runtime' of undefined\n",
    '2020-12-03T12:10:30.979Z workers [worker #1, session #25jsu] Running tests in sandbox\n',
    "2020-12-03T12:10:30.979Z chromeRunner Failed to evaluate code on Chrome Tab: Cannot read property 'Runtime' of undefined\n",
    '2020-12-03T12:10:30.979Z workers [worker #2, session #zp5e1] Running tests in sandbox\n',
    "2020-12-03T12:10:30.981Z chromeRunner Failed to evaluate code on Chrome Tab: Cannot read property 'Runtime' of undefined\n",
    '2020-12-03T12:10:37.991Z workers [g1zt9] Sandbox is not responsive, recycling worker instance\n',
    '2020-12-03T12:10:37.993Z project Test run finished\n',
    '2020-12-03T12:10:37.993Z workers [25jsu] Sandbox is not responsive, recycling worker instance\n',
    '2020-12-03T12:10:37.993Z workers [zp5e1] Sandbox is not responsive, recycling worker instance\n'
  ]
}
```

**Comment by hsantesteban** [comment]
Update: I gave Jest + Automatic Configuration another shot and I guess that I finallly have it running. Please, disregard this issue.
