### ISSUE TITLE
Wallaby test-runner fails executing CLI-based Mocha tests that Succeed via the Webstorm Mocha test-runner

### ISSUE THREAD

**Issue by b2csolutionarchitect** [wallabyjs/public#2592]
### Issue Description
Hi there!  I'm a first-time user of wallaby.js, and running into an issue where [two mocha tests designed to exercise and validate the behavior of a CLI command](https://gist.github.com/b2csolutionarchitect/ac9af3d7573eb3791401d928eaa6a56e) execute without any issue in Webstorm but fail via the wallaby test-runner.  My tests perform the following actions:

- Execute a CLI Command
- Capture the stdout results
- Assert test outcomes against the parsed results

Both tests that fail via the wallaby test-runner return the following error:

```@bash
the string "internal/modules/cjs/loader.js:984
   throw err;
   
^Error: Cannot find module '/Users/abraham.Lloyd/Library/Caches/JetBrains/WebStorm2020.3/wallaby/projects/1c47e8a21015772b/instrumented/index'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
    at Function.Module._load (internal/modules/cjs/loader.js:863:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
         code: 'MODULE_NOT_FOUND',
         requireStack: []
    }" was thrown, throw an Error :)
```

I'm using a childProcess-wrapper function to pass-in the CLI command that I want to exercise -- and have added gists that point to the [wrapper](https://gist.github.com/b2csolutionarchitect/824ce01c45d748e7b9706019f88fa935) and [execute](https://gist.github.com/b2csolutionarchitect/40a90accbea2d4d34cd86eb3c6db70ad) functions used to exercise the CLI via my[ mocha unit tests](https://gist.github.com/b2csolutionarchitect/ac9af3d7573eb3791401d928eaa6a56e).  

Any insight you can provide explaining either 1) how to adjust my mocha test or 2) how to adjust the wallaby.js configuration would be appreciated.  Thank you in advance for your time, efforts, and support.  Hope and health to you, your teams, and your families. :)

### Wallaby diagnostics report
As requested, I've included a copy of the diagnostic report.  Please feel free to follow-up with any questions you have.  I have to say I'm excited to leverage wallaby.js in this project.  Thank you for your time, help, and support -- and I look forward to hearing from you.

```
{
  editorVersion: 'WebStorm 2020.3',
  pluginVersion: '1.0.203',
  editorType: 'IntelliJ',
  osVersion: 'darwin 18.7.0',
  nodeVersion: 'v12.16.0',
  coreVersion: '1.0.999',
  checksum: 'NzQ5MjM1YmNlNTIzMzRlOGI2MTYwM2ZhMDBjMWE0N2MsMTY0MDA0NDgwMDAwMCww',
  config: {
    debug: true,
    trace: false,
    lowCoverageThreshold: 90,
    files: [
      { pattern: 'package.json', instrument: false, load: true, ignore: false, trigger: true, order: 1 },
      { pattern: 'wallaby.js', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: 'lib/qa/**/*.test.js', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: 'test/**/*.test.js', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: 'config/**', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: 'lib/**/*.js', ignore: false, trigger: true, load: true, instrument: true, order: 3 }
    ],
    tests: [
      { pattern: 'test/_common/*.test.js', ignore: false, trigger: true, load: true, test: true, order: 4 },
      { pattern: 'test/cli-interface/*.test.js', ignore: false, trigger: true, load: true, test: true, order: 5 }
    ],
    filesWithNoCoverageCalculated: [ 'qa/**/*.js' ],
    testFramework: { version: 'mocha@2.1.0', configurator: 'mocha@2.1.0', reporter: 'mocha@2.1.0', starter: 'mocha@2.1.0' },
    env: { type: 'node', runner: 'node', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    workers: { initial: 1, regular: 1, restart: true, recycle: true },
    diagnostics: {},
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: { '**/*.?(lit)coffee?(.md)': [Function] },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    loose: undefined,
    configCode: "'use strict';\n" +
      '\n' +
      '// Initialize the Wallaby configuration\n' +
      'module.exports = function() {\n' +
      '\n' +
      '    return {\n' +
      '\n' +
      '        // Manage runtime execution\n' +
      '        debug: true,\n' +
      '        trace: false,\n' +
      '\n' +
      '        // Default the desired code-coverage level\n' +
      '        lowCoverageThreshold: 90,\n' +
      '\n' +
      '        // Define the files processed by Wallaby\n' +
      '        files: [\n' +
      '            { "pattern": "package.json", "instrument": false, "load": true },\n' +
      "            '!wallaby.js',\n" +
      "            '!lib/qa/**/*.test.js',\n" +
      "            '!test/**/*.test.js',\n" +
      "            'config/**',\n" +
      "            'lib/**/*.js'\n" +
      '        ],\n' +
      '\n' +
      '        // Define the tests to process\n' +
      '        tests: [\n' +
      "            'test/_common/*.test.js',\n" +
      "            'test/cli-interface/*.test.js'\n" +
      '        ],\n' +
      '\n' +
      "        // Define the files that shouldn't be used to calculate test coverage\n" +
      '        filesWithNoCoverageCalculated: [\n' +
      "            'qa/**/*.js'\n" +
      '        ],\n' +
      '\n' +
      '        // Identify the test-framework to leverage\n' +
      "        testFramework: { type: 'mocha' },\n" +
      '\n' +
      '        // Define the node environment\n' +
      '        env: {\n' +
      "            type: 'node',\n" +
      "            runner: 'node'\n" +
      '        },\n' +
      '\n' +
      '        // Restart test workers with each test-run\n' +
      '        workers: {\n' +
      '            initial: 1,\n' +
      '            regular: 1,\n' +
      '            restart: true\n' +
      '        }\n' +
      '\n' +
      '    }\n' +
      '\n' +
      '}\n'
  },
  packageJSON: {
    dependencies: {
      async: '^3.2.0',
      'async-polling': '^0.2.1',
      'child-process-promise': '^1.0.2',
      commander: '^6.2.0',
      config: '^3.3.2',
      dotenv: '^8.2.0',
      'fs-extra': '^9.0.1',
      lodash: '^4.17.20',
      moment: '^2.29.1',
      'recursive-readdir': '^2.2.2',
      'sfcc-ci': '^2.6.0',
      'zip-folder': '^1.0.0'
    },
    devDependencies: {
      '@types/async': '^3.2.5',
      '@types/async-polling': '^0.0.4',
      '@types/child-process-promise': '^2.2.1',
      '@types/config': '^0.0.37',
      '@types/fs-extra': '^9.0.5',
      '@types/lodash': '^4.14.165',
      '@types/recursive-readdir': '^2.2.0',
      '@types/eslint': '^7.2.6',
      '@types/mocha': '^8.2.0',
      '@types/chai': '^4.2.14',
      '@types/sinon': '^9.0.9',
      '@types/sinon-chai': '^3.2.5',
      '@types/concat-stream': '^1.6.0',
      eslint: '^7.14.0',
      'eslint-config-airbnb-base': '^14.2.1',
      'eslint-plugin-import': '^2.22.1',
      'eslint-plugin-sitegenesis': '^1.0.0',
      mocha: '^8.2.1',
      chai: '^4.2.0',
      sinon: '^9.2.2',
      'sinon-chai': '^3.5.0',
      'concat-stream': '^2.0.0',
      os: '^0.1.1'
    }
  },
  fs: { numberOfFiles: 37 },
  debug: [
    '2020-12-22T14:07:47.487Z project Wallaby Node version: v12.16.0\n',
    '2020-12-22T14:07:47.487Z project Wallaby config: <rootDir>/wallaby.js\n',
    '2020-12-22T14:07:48.161Z project File cache: <homeDir>/Library/Caches/JetBrains/WebStorm2020.3/wallaby/projects/1c47e8a21015772b\n',
    '2020-12-22T14:07:48.172Z uiService Listening port 51235\n',
    '2020-12-22T14:07:48.184Z workers Parallelism for initial run: 1, for regular run: 1\n',
    '2020-12-22T14:07:48.185Z workers Starting run worker instance #0\n',
    '2020-12-22T14:07:48.186Z workers Web server is listening at 49377\n',
    '2020-12-22T14:07:48.199Z project File cache requires some updates, waiting required files from IDE\n',
    '2020-12-22T14:07:48.468Z workers Started run worker instance (delayed) #0\n',
    '2020-12-22T14:07:48.811Z project Stopping process pool\n',
    '2020-12-22T14:07:48.813Z project Running postprocessor\n',
    '2020-12-22T14:07:48.816Z postprocessor New TypeScript language service is required\n',
    "2020-12-22T14:07:48.817Z postprocessor TypeScript postprocessor will be removed because in 37 project files none were found by patterns: [ '**/*.ts?(x)' ]\n",
    '2020-12-22T14:07:48.819Z project Postprocessor execution finished\n',
    '2020-12-22T14:07:48.819Z project Postprocessor is removed as requested by itself\n',
    '2020-12-22T14:07:48.819Z project Test run started; run priority: 3\n',
    '2020-12-22T14:07:48.819Z project Running all tests\n',
    '2020-12-22T14:07:48.825Z workers Starting test run, priority: 3\n',
    '2020-12-22T14:07:48.826Z nodeRunner Starting sandbox [worker #0, session #yiuu7]\n',
    '2020-12-22T14:07:48.826Z nodeRunner Preparing sandbox [worker #0, session #yiuu7]\n',
    '2020-12-22T14:07:48.826Z nodeRunner Prepared sandbox [worker #0, session #yiuu7]\n',
    '2020-12-22T14:07:48.826Z workers [worker #0, session #yiuu7] Running tests in sandbox\n',
    '2020-12-22T14:07:48.975Z workers [yiuu7] Loaded 7 test(s)\n',
    "2020-12-22T14:07:48.978Z workers [yiuu7] Test executed: returns the default operation-mode if one isn't specified\n",
    '2020-12-22T14:07:48.978Z workers [yiuu7] Test executed: returns the default operation-mode if an unrecognized one is specified\n',
    '2020-12-22T14:07:48.979Z workers [yiuu7] Test executed: accepts all valid operation modes as defined in the app-configuration\n',
    '2020-12-22T14:07:48.980Z workers [yiuu7] Test executed: returns a valid runtimeEnvironment object definition\n',
    '2020-12-22T14:07:48.980Z workers [yiuu7] Test executed: contains the expected collection of environment properties\n',
    '2020-12-22T14:07:49.362Z workers [yiuu7] Test executed: should provide a JSON string representing the environment\n',
    `2020-12-22T14:07:49.362Z workers Failed to map the stack to user code, entry message: the string "internal/modules/cjs/loader.js:984\\n  throw err;\\n  ^\\n\\nError: Cannot find module '/Users/this.user/Library/Caches/JetBrains/WebStorm2020.3/wallaby/projects/1c47e8a21015772b/instrumented/index'\\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)\\n    at Function.Module._load (internal/modules/cjs/loader.js:863:27)\\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)\\n    at internal/main/run_main_module.js:18:47 {\\n  code: 'MODULE_NOT_FOUND',\\n  requireStack: []\\n}\\n" was thrown, throw an Error :), stack: Error: the string "internal/modules/cjs/loader.js:984\\n  throw err;\\n  ^\\n\\nError: Cannot find module '/Users/this.user/Library/Caches/JetBrains/WebStorm2020.3/wallaby/projects/1c47e8a21015772b/instrumented/index'\\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)\\n    at Function.Module._load (internal/modules/cjs/loader.js:863:27)\\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)\\n    at internal/main/run_main_module.js:18:47 {\\n  code: 'MODULE_NOT_FOUND',\\n  requireStack: []\\n}\\n" was thrown, throw an Error :)\n` +
      '    at thrown2Error (<rootDir>/node_modules/mocha/lib/runner.js:1249:10)\n' +
      '    at Runner.fail (<rootDir>/node_modules/mocha/lib/runner.js:457:11)\n' +
      '    at <rootDir>/node_modules/mocha/lib/runner.js:826:18\n' +
      '    at done (/Users/a\n',
    '2020-12-22T14:07:49.732Z workers [yiuu7] Test executed: returns an Environment Definition with all the expected attributes\n',
    `2020-12-22T14:07:49.732Z workers Failed to map the stack to user code, entry message: the string "internal/modules/cjs/loader.js:984\\n  throw err;\\n  ^\\n\\nError: Cannot find module '/Users/this.user/Library/Caches/JetBrains/WebStorm2020.3/wallaby/projects/1c47e8a21015772b/instrumented/index'\\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)\\n    at Function.Module._load (internal/modules/cjs/loader.js:863:27)\\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)\\n    at internal/main/run_main_module.js:18:47 {\\n  code: 'MODULE_NOT_FOUND',\\n  requireStack: []\\n}\\n" was thrown, throw an Error :), stack: Error: the string "internal/modules/cjs/loader.js:984\\n  throw err;\\n  ^\\n\\nError: Cannot find module '/Users/this.user/Library/Caches/JetBrains/WebStorm2020.3/wallaby/projects/1c47e8a21015772b/instrumented/index'\\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)\\n    at Function.Module._load (internal/modules/cjs/loader.js:863:27)\\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)\\n    at internal/main/run_main_module.js:18:47 {\\n  code: 'MODULE_NOT_FOUND',\\n  requireStack: []\\n}\\n" was thrown, throw an Error :)\n` +
      '    at thrown2Error (<rootDir>/node_modules/mocha/lib/runner.js:1249:10)\n' +
      '    at Runner.fail (<rootDir>/node_modules/mocha/lib/runner.js:457:11)\n' +
      '    at <rootDir>/node_modules/mocha/lib/runner.js:826:18\n' +
      '    at done (/Users/a\n',
    '2020-12-22T14:07:49.746Z workers [yiuu7] Run 7 test(s), skipped 0 test(s)\n',
    '2020-12-22T14:07:49.747Z workers [yiuu7] Sandbox is responsive, closing it\n',
    '2020-12-22T14:07:49.747Z workers Starting run worker instance #0\n',
    '2020-12-22T14:07:49.748Z project Test run finished\n',
    '2020-12-22T14:07:49.748Z project Processed console.log entries\n',
    '2020-12-22T14:07:49.749Z project Processed loading sequences\n',
    '2020-12-22T14:07:49.749Z project Processed executed tests\n',
    '2020-12-22T14:07:49.753Z project Processed code coverage\n',
    '2020-12-22T14:07:49.771Z project Test run result processed and sent to IDE\n',
    '2020-12-22T14:07:49.922Z workers Started run worker instance (delayed) #0\n',
    '2020-12-22T14:07:54.855Z uiService UI client connected\n',
    '2020-12-22T14:07:54.856Z uiService Outgoing message ui:handshake\n',
    '2020-12-22T14:07:54.858Z uiService Incoming message ui:tests:resultsRequested\n',
    '2020-12-22T14:07:54.860Z uiService Outgoing message ui:tests:allResultsUpdated\n',
    '2020-12-22T14:07:54.860Z uiService Incoming message ui:start\n',
    '2020-12-22T14:07:54.861Z uiService Outgoing message ui:summary\n',
    '2020-12-22T14:07:54.862Z uiService Outgoing message ui:files\n',
    '2020-12-22T14:07:56.843Z uiService UI client connected\n',
    '2020-12-22T14:07:56.843Z uiService Outgoing message ui:handshake\n',
    '2020-12-22T14:07:56.845Z uiService Incoming message ui:tests:resultsRequested\n',
    '2020-12-22T14:07:56.846Z uiService Outgoing message ui:tests:allResultsUpdated\n',
    '2020-12-22T14:07:56.846Z uiService Incoming message ui:start\n',
    '2020-12-22T14:07:56.847Z uiService Outgoing message ui:summary\n',
    '2020-12-22T14:07:56.847Z uiService Outgoing message ui:files\n'
  ]
}
```

**Comment by b2csolutionarchitect** [comment]
... so, if I remove the following line from my wallaby.js file:

```
{ "pattern": "package.json", "instrument": false, "load": true },
```

... the error generated changes to:

```
0 info it worked if it ends with ok
    1 verbose cli [
    1 verbose cli   '/Users/this.user/.nvm/versions/node/v12.16.0/bin/node',
    1 verbose cli   '/Users/this.user/.nvm/versions/node/v12.16.0/bin/npm',
    1 verbose cli   'run',
    1 verbose cli   'scc:env:get',
    1 verbose cli   '--',
    1 verbose cli   '-om',
    1 verbose cli   'json'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.0
4 verbose stack Error: ENOENT: no such file or directory, open '/Users/this.user/Library/Caches/JetBrains/WebStorm2020.3/wallaby/projects/1c47e8a21015772b/instrumented/package.json'
5 verbose cwd /Users/this.user/Library/Caches/JetBrains/WebStorm2020.3/wallaby/projects/1c47e8a21015772b/instrumented
6 verbose Darwin 18.7.0
7 verbose argv "/Users/this.user/.nvm/versions/node/v12.16.0/bin/node" "/Users/this.user/.nvm/versions/node/v12.16.0/bin/npm" "run" "scc:env:get" "--" "-om" "json"
8 verbose node v12.16.0
9 verbose npm  v6.13.4
10 error code ENOENT
11 error syscall open
12 error path /Users/this.user/Library/Caches/JetBrains/WebStorm2020.3/wallaby/projects/1c47e8a21015772b/instrumented/package.json
13 error errno -2
14 error enoent ENOENT: no such file or directory, open '/Users/this.user/Library/Caches/JetBrains/WebStorm2020.3/wallaby/projects/1c47e8a21015772b/instrumented/package.json'
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ -2, true ]
```

... hope this is helpful, and looking forward to hearing from you. :)

**Comment by smcenlly** [comment]
Using Wallaby to start a child process can sometimes lead to issues. It's probably best that I explain how Wallaby is running your code and what it's doing as this will allow you to work out how you might configure Wallaby to run your test.

When Wallaby runs your code, it first applies any transforms (e.g. TypeScript/Babel compiler, etc.) before then instrumenting your code and adding its own instructions, which is what allows code-coverage, inline value display and many of the other Wallaby features to become available when you run your tests with Wallaby. Wallaby then runs your project files from an instrumented project directory (e.g. `/Users/abraham.Lloyd/Library/Caches/JetBrains/WebStorm2020.3/wallaby/projects/1c47e8a21015772b/instrumented/`). There's a lot more that Wallaby does under the covers at that point (e.g. patches module loading to resolve your `node_modules` from your project directory) but in your case, I believe running from the instrumented folder this is the cause of your problem.

When your CLI spawn script is running, it appears to be running from the instrumented directory, relying on both `package.json` file (which existed in your first comment) and your `index.js` file from your project root that was not part of your Wallaby configuration files.

Depending on what your `index.js` does, and what other project files it imports, you may be able to update your Wallaby configuration `files` section to include `index.js` and other required files but you will need to mark all of these files (and their imports/requires) as `instrument`: `false`. This means that you won't get any Wallaby coverage or features on these files. The reason for this is Wallaby needs its runtime functions to be available when it runs the instrumented code but when you spawn a sub-process, Wallaby's runtime is no longer available and you will start to get failures when running on Wallaby's instrumented code outside of the Wallaby runtime process.

An alternative for you would be to update your tests to know about your original project directory when spawning a child process and run your code there instead of the Wallaby instrumented folder. You still won't get coverage or Wallaby features from the context of the spawned process, but everything should work for you.

To do this, update your Wallaby.js configuration file to set a `process.env` variable that you can later use in your tests to refer to your real project directory (instead of Wallaby's project directory):

**wallaby.js**
```javascript
'use strict';

module.exports = () => {
  return {
    ...
    setup(wallaby) {
+     process.env.PROJECT_ROOT_DIR = wallaby.localProjectDir;
      ...
    },
    ...
  };
  ...
};
```

Then in your code where you spawn the child process, switch on whether the environment variable is set/available to correctly launch your child process:

**childProcessLauncher.js**
```javascript
const executableToLaunch = process.env.PROJECT_ROOT_DIR ? path.join(process.env.PROJECT_ROOT_DIR, 'index') : require.resolve('../../index');
```

**Comment by b2csolutionarchitect** [comment]
... hi there; I just want to say thank you for your very thoughtful and detailed explanation.  What you shared makes sense, and what I landed on was just excluding the CLI unit-tests via the wallaby.js config file.  I'll use web storms test runner for those tests and can use Wallaby for in-flight development to manage the CLI under-pinnings.  I think that makes more sense than bending my tests into a pretzel.  Thanks again for your help, and hope and health to you, your teams, and your families.
