### ISSUE TITLE
Problem compiling typescript

### ISSUE THREAD

**Issue by dht** [wallabyjs/public#2598]
```
./test/api/web-app.spec.ts: Unexpected token, expected ";" (38:23)
```

for:
```
describe('web app', () => {
> 38 |   let permissionsDriver: PermissionsDriver;
```

```
{
  editorVersion: 'WebStorm 2020.3',
  pluginVersion: '1.0.203',
  editorType: 'IntelliJ',
  osVersion: 'darwin 19.6.0',
  nodeVersion: 'v12.18.3',
  coreVersion: '1.0.1001',
  checksum: 'MjFjYTc1Y2NlZjgyNDdlNDM1M2Q3ZTcyZmNmZTZiMTMsMTYwOTQ1OTIwMDAwMCww',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              browser: false,
              cache: true,
              cacheDirectory: '/private/var/folders/xs/tkcf3t055dn8hxtp6fy5c_sw0000gp/T/jest_dy',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/projects/business-manager/business-manager-web',
              dependencyExtractor: null,
              detectLeaks: undefined,
              detectOpenHandles: undefined,
              displayName: undefined,
              errorOnDeprecated: false,
              extraGlobals: undefined,
              filter: null,
              forceCoverageMatch: [],
              globalSetup: null,
              globalTeardown: null,
              globals: {},
              haste: { computeSha1: false, providesModuleNodeModules: [], throwOnModuleCollision: false },
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [ 'js', 'json', 'jsx', 'ts', 'tsx', 'node' ],
              moduleLoader: undefined,
              moduleNameMapper: {},
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              name: '21b8cf8dbd5fdd1467b33a271e1f14f0',
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: null,
              restoreMocks: false,
              rootDir: '<homeDir>/projects/business-manager/business-manager-web',
              roots: [ '<homeDir>/projects/business-manager/business-manager-web' ],
              runner: 'jest-runner',
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/projects/business-manager/business-manager-web/node_modules/jest-environment-jsdom/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<homeDir>/projects/business-manager/business-manager-web/node_modules/jest-jasmine2/build/index.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [ [ '^.+\\.[jt]sx?$', '<homeDir>/projects/business-manager/business-manager-web/node_modules/babel-jest/build/index.js' ] ],
              transformIgnorePatterns: [ '/node_modules/' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: null,
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<homeDir>/projects/business-manager/business-manager-web/coverage',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: null,
            detectLeaks: undefined,
            detectOpenHandles: undefined,
            enabledTestsMap: undefined,
            errorOnDeprecated: false,
            expand: false,
            extraGlobals: undefined,
            filter: null,
            findRelatedTests: undefined,
            forceExit: undefined,
            globalSetup: null,
            globalTeardown: null,
            json: false,
            lastCommit: undefined,
            listTests: undefined,
            logHeapUsage: undefined,
            maxConcurrency: 5,
            maxWorkers: 15,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: undefined,
            onlyFailures: undefined,
            outputFile: undefined,
            passWithNoTests: undefined,
            projects: null,
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/projects/business-manager/business-manager-web',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: null,
            testSequencer: '<homeDir>/projects/business-manager/business-manager-web/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: null,
            watch: false,
            watchAll: undefined,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|/\\..+/' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|/\\..+/' ],
            testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    micromatch: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
      { pattern: '\\./dist/|\\./build/|\\./coverage/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\/\..+\//, ignore: true, trigger: true, load: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
      { pattern: '\\./dist/|\\./build/|\\./coverage/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\/\..+\//, ignore: true, trigger: true, load: true, test: true },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '<homeDir>/.nvm/versions/node/v12.18.3/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#-1295911054'
  },
  packageJSON: {
    dependencies: {
      '@sentry/browser': '5.15.5',
      'ab-translate': '^1.1.27',
      atob: '^2.0.3',
      axios: '^0.16.2',
      'body-parser': '^1.15.2',
      chance: '^1.0.16',
      classnames: '^2.2.5',
      'cookie-parser': '^1.4.3',
      'data-capsule': '^1.0.95',
      'deep-freeze': '0.0.1',
      express: '^4.17.0',
      'fs-extra': '^9.0.0',
      'http-proxy-middleware': '^0.17.2',
      'http-status-codes': '^1.2.0',
      i18next: '^12.0.0',
      'i18next-node-fs-backend': '^1.0.0',
      'i18next-xhr-backend': '^1.5.1',
      lodash: '4.17.4',
      'prop-types': '^15.5.10',
      'react-i18next': '^7.10.1',
      'react-module-container': '^1.0.84',
      'react-redux': '^4.4.5',
      'react-router': '^3.0.2',
      'react-transition-group': '^2.2.1',
      redux: '^3.5.2',
      'redux-devtools-extension': '2.13.2',
      'redux-logger': '^3.0.6',
      'redux-thunk': '2.2.0',
      'serialize-javascript': '^1.3.0',
      'string-template': '^1.0.0',
      tslib: '^1.5.0',
      'ua-parser-js': '^0.7.19',
      urijs: '1.18.10',
      uuid: '3.2.1',
    },
    devDependencies: {
      '@types/chai': '^4.2.0',
      '@types/chai-as-promised': '^7.1.0',
      '@types/chai-enzyme': '^0.6.5',
      '@types/chance': '^1.0.1',
      '@types/cheerio': '^0.22.18',
      '@types/enzyme': '^3.1.10',
      '@types/express': '^4.17.0',
      '@types/history': '^3.0.0',
      '@types/i18next': '^12.1.0',
      '@types/jsdom': '^2.0.29',
      '@types/lodash': '^4.14.53',
      '@types/mocha': '^2.2.41',
      '@types/node': '^12.0.0',
      '@types/puppeteer': '^5.4.0',
      '@types/qs': '^6.5.0',
      '@types/react': '16.9.43',
      '@types/react-i18next': '^7.1.0',
      '@types/react-router': '^3.0.20',
      '@types/sinon': '^9.0.0',
      '@types/sinon-chai': '^3.2.0',
      '@types/ua-parser-js': '^0.7.32',
      '@types/urijs': '^1.15.33',      
      'babel-polyfill': '^6.26.0',
      btoa: '^1.1.2',
      chai: '^4.2.0',
      'chai-as-promised': '^7.1.1',
      'chai-enzyme': '^1.0.0-beta.1',
      'chai-subset': '^1.6.0',
      cheerio: '^1.0.0-rc.3',
      cookie: '^0.4.1',
      'cross-env': '^3.1.3',
      enzyme: '^3.11.0',
      'enzyme-adapter-react-16': '^1.15.2',
      'factory.ts': '^0.2.2',
      'get-port': '^5.1.1',
      history: '^3.3.0',
      husky: '4.3.0',
      'intercept-stdout': '^0.1.2',
      'isomorphic-fetch': '^2.2.1',
      jsdom: '^9.4.1',
      'jsdom-global': '^2.1.0',
      nock: '^12.0.3',
      protractor: '^5.4.1',
      qs: '^6.5.0',
      react: '16.13.1',
      'react-dom': '16.13.1',
      sinon: '^9.2.0',
      'sinon-chai': '^3.1.0',
      'sled-test-runner': '^1.0.652',
      typescript: '3.9.5',
      'with-eyes': '^3.0.0',
      yoshi: '^4.0.0',
      'yoshi-style-dependencies': '^4.0.0'
    }
  },
  fs: { numberOfFiles: 589 },
  debug: [
    '2020-12-29T15:30:47.207Z angular/cli config Angular CLI not found.\n',
    '2020-12-29T15:30:47.410Z jest/config Detected Jest.\n',
    '2020-12-29T15:30:47.411Z jest/config Configured Jest.\n',
    '2020-12-29T15:30:47.412Z project Wallaby Node version: v12.18.3\n',
    '2020-12-29T15:30:47.412Z project Wallaby config: <homeDir>/projects/business-manager/business-manager-web/auto.detect\n',
    '2020-12-29T15:30:48.582Z project File cache: <homeDir>/Library/Caches/JetBrains/WebStorm2020.3/wallaby/projects/fae539c467ac62b3\n',
    '2020-12-29T15:30:48.600Z uiService Listening port 51235\n',
    '2020-12-29T15:30:48.637Z workers Parallelism for initial run: 14, for regular run: 7\n',
    '2020-12-29T15:30:48.637Z workers Starting run worker instance #0\n',
    '2020-12-29T15:30:48.638Z workers Starting run worker instance #1\n',
    '2020-12-29T15:30:48.638Z workers Starting run worker instance #2\n',
    '2020-12-29T15:30:48.638Z workers Starting run worker instance #3\n',
    '2020-12-29T15:30:48.638Z workers Starting run worker instance #4\n',
    '2020-12-29T15:30:48.638Z workers Starting run worker instance #5\n',
    '2020-12-29T15:30:48.638Z workers Starting run worker instance #6\n',
    '2020-12-29T15:30:48.638Z workers Starting run worker instance #7\n',
    '2020-12-29T15:30:48.638Z workers Starting run worker instance #8\n',
    '2020-12-29T15:30:48.638Z workers Starting run worker instance #9\n',
    '2020-12-29T15:30:48.638Z workers Starting run worker instance #10\n',
    '2020-12-29T15:30:48.638Z workers Starting run worker instance #11\n',
    '2020-12-29T15:30:48.638Z workers Starting run worker instance #12\n',
    '2020-12-29T15:30:48.638Z workers Starting run worker instance #13\n',
    '2020-12-29T15:30:48.638Z workers Web server is listening at 54052\n',
    '2020-12-29T15:30:48.639Z project File cache requires some updates, waiting required files from IDE\n',
    '2020-12-29T15:30:48.974Z project Stopping process pool\n',
    '2020-12-29T15:30:48.977Z project Test run started; run priority: 3\n',
    '2020-12-29T15:30:48.979Z project Running all tests\n',
    '2020-12-29T15:30:48.987Z workers Starting test run, priority: 3\n',
    '2020-12-29T15:30:48.988Z nodeRunner Starting sandbox [worker #0, session #iajd1]\n',
    '2020-12-29T15:30:48.988Z nodeRunner Preparing sandbox [worker #0, session #iajd1]\n',
    '2020-12-29T15:30:48.993Z workers Started run worker instance (delayed) #0\n',
    '2020-12-29T15:30:48.994Z nodeRunner Prepared sandbox [worker #0, session #iajd1]\n',
    '2020-12-29T15:30:48.994Z workers [worker #0, session #iajd1] Running tests in sandbox\n',
    '2020-12-29T15:30:48.996Z workers Started run worker instance (delayed) #2\n',
    '2020-12-29T15:30:48.996Z workers Started run worker instance (delayed) #1\n',
    '2020-12-29T15:30:48.996Z workers Started run worker instance (delayed) #3\n',
    '2020-12-29T15:30:48.998Z workers Started run worker instance (delayed) #6\n',
    '2020-12-29T15:30:48.999Z workers Started run worker instance (delayed) #5\n',
    '2020-12-29T15:30:48.999Z workers Started run worker instance (delayed) #4\n',
    '2020-12-29T15:30:49.001Z workers Started run worker instance (delayed) #9\n',
    '2020-12-29T15:30:49.001Z workers Started run worker instance (delayed) #8\n',
    '2020-12-29T15:30:49.002Z workers Started run worker instance (delayed) #7\n',
    '2020-12-29T15:30:49.004Z workers Started run worker instance (delayed) #10\n',
    '2020-12-29T15:30:49.004Z workers Started run worker instance (delayed) #11\n',
    '2020-12-29T15:30:49.006Z workers Started run worker instance (delayed) #13\n',
    '2020-12-29T15:30:49.006Z workers Started run worker instance (delayed) #12\n',
    '2020-12-29T15:30:51.560Z workers Sandbox (active) [iajd1] error: <homeDir>/projects/business-manager/business-manager-web/test/api/web-app.spec.ts: Unexpected token, expected ";" (38:23)\n' +
      '\n' +
      '  36 | \n' +
      "  37 | describe('web app', () => {\n" +
      '> 38 |   let permissionsDriver: PermissionsDriver;\n' +
      '     |                        ^\n' +
      '  39 |   let webAppDriver: WebAppDriver;\n' +
      '  40 |   let coBrandingAuthorizationCheck: sinon.SinonStub;\n' +
      '  41 |   let sitePropertiesAuthorizationCheck: sinon.SinonStub;\n',
    '2020-12-29T15:30:51.562Z workers [iajd1] Run 0 test(s), skipped 0 test(s)\n',
    '2020-12-29T15:30:51.563Z workers [iajd1] Sandbox is responsive, closing it\n',
    '2020-12-29T15:30:51.565Z workers Failed to map the stack to user code, entry message: <homeDir>/projects/business-manager/business-manager-web/test/api/web-app.spec.ts: Unexpected token, expected ";" (38:23)\n' +
      '\n' +
      '  36 | \n' +
      "  37 | describe('web app', () => {\n" +
      '> 38 |   let permissionsDriver: PermissionsDriver;\n' +
      '     |                        ^\n' +
      '  39 |   let webAppDriver: WebAppDriver;\n' +
      '  40 |   let coBrandingAuthorizationCheck: sinon.SinonStub;\n' +
      '  41 |   let sitePropertiesAuthorizationCheck: sinon.SinonStub;, stack: SyntaxError: <homeDir>/projects/business-manager/business-manager-web/test/api/web-app.spec.ts: Unexpected token, expected ";" (38:23)\n' +
      '\n' +
      '  36 | \n' +
      "  37 | describe('web app', () => {\n" +
      '> 38 |   let permissionsDriver: PermissionsDriver;\n' +
      '     |                        ^\n' +
      '  39 |   let webAppDriver: WebAppDriver;\n' +
      '  40 |   let coBrandingAuthorizationCheck: sinon.SinonStub;\n' +
      '  41 |   let sitePropertiesAuthorizationCheck: sinon.SinonStub;\n' +
      '    at Parser._raise (<homeDir>/projects/business-manager/business-manager-web/node_modules/@babel/parser/src/parser/error.js:60:45)\n' +
      '    at Parser.raiseWithData (<homeDir>/projects/business-manager/business-manager-web/node_modules/@babel/parser/src/parser/error.js:55:17)\n' +
      '    at Parser.raise (<homeDir>/projects/business-manager/business-manager-web/node_modules/@babel/parser/src/parser/error.js:39:17)\n' +
      '    at Parser.unexpected (<homeDir>/projects/business-manager/business-manager-web/node_modules/@babel/parser/src/parser/util.js:139:16)\n' +
      '    at Parser.semicolon (<homeDir>/projects\n',
    '2020-12-29T15:30:51.565Z project Test run finished\n',
    '2020-12-29T15:30:51.565Z project Processed console.log entries\n',
    '2020-12-29T15:30:51.565Z project Processed loading sequences\n',
    '2020-12-29T15:30:51.565Z project Processed executed tests\n',
    '2020-12-29T15:30:51.569Z project Processed code coverage\n',
    '2020-12-29T15:30:51.583Z project Test run result processed and sent to IDE\n',
    '2020-12-29T15:31:08.644Z fs File changed: target/configs/business-manager.json\n',
    '2020-12-29T15:31:08.650Z fs File deleted: target/logs/wnp_app.dev.log\n',
    '2020-12-29T15:31:08.654Z project Test run started; run priority: 2\n',
    '2020-12-29T15:31:08.656Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2020-12-29T15:31:08.656Z testTask Running only selected or not excluded tests\n',
    '2020-12-29T15:31:08.666Z workers Starting test run, priority: 2\n',
    '2020-12-29T15:31:08.666Z nodeRunner Starting sandbox [worker #0, session #tynt7]\n',
    '2020-12-29T15:31:08.666Z nodeRunner Preparing sandbox [worker #0, session #tynt7]\n',
    '2020-12-29T15:31:08.666Z nodeRunner Prepared sandbox [worker #0, session #tynt7]\n',
    '2020-12-29T15:31:08.666Z workers [worker #0, session #tynt7] Running tests in sandbox\n',
    '2020-12-29T15:31:08.667Z workers Cancelling test run, cancel requester priority: 2, current run priority: 2\n',
    '2020-12-29T15:31:08.668Z project Test run was cancelled\n',
    '2020-12-29T15:31:08.767Z workers [tynt7] Sandbox is responsive, closing it\n',
    '2020-12-29T15:31:08.767Z project Test run cancelled, re-queueing run data\n',
    '2020-12-29T15:31:08.767Z project Test run finished\n',
    '2020-12-29T15:31:08.768Z project Test run data re-queued\n',
    '2020-12-29T15:31:08.773Z project Test run started; run priority: 2\n',
    '2020-12-29T15:31:08.774Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2020-12-29T15:31:08.774Z testTask Running only selected or not excluded tests\n',
    '2020-12-29T15:31:08.779Z workers Starting test run, priority: 2\n',
    '2020-12-29T15:31:08.779Z nodeRunner Starting sandbox [worker #0, session #2qz1i]\n',
    '2020-12-29T15:31:08.779Z nodeRunner Preparing sandbox [worker #0, session #2qz1i]\n',
    '2020-12-29T15:31:08.779Z nodeRunner Prepared sandbox [worker #0, session #2qz1i]\n',
    '2020-12-29T15:31:08.779Z workers [worker #0, session #2qz1i] Running tests in sandbox\n',
    '2020-12-29T15:31:08.851Z workers Sandbox (active) [2qz1i] error: <homeDir>/projects/business-manager/business-manager-web/test/api/web-app.spec.ts: Unexpected token, expected ";" (38:23)\n' +
      '\n' +
      '  36 | \n' +
      "  37 | describe('web app', () => {\n" +
      '> 38 |   let permissionsDriver: PermissionsDriver;\n' +
      '     |                        ^\n' +
      '  39 |   let webAppDriver: WebAppDriver;\n' +
      '  40 |   let coBrandingAuthorizationCheck: sinon.SinonStub;\n' +
      '  41 |   let sitePropertiesAuthorizationCheck: sinon.SinonStub;\n',
    '2020-12-29T15:31:08.852Z workers [2qz1i] Run 0 test(s), skipped 0 test(s)\n',
    '2020-12-29T15:31:08.853Z workers [2qz1i] Sandbox is responsive, closing it\n',
    '2020-12-29T15:31:08.854Z workers Failed to map the stack to user code, entry message: <homeDir>/projects/business-manager/business-manager-web/test/api/web-app.spec.ts: Unexpected token, expected ";" (38:23)\n' +
      '\n' +
      '  36 | \n' +
      "  37 | describe('web app', () => {\n" +
      '> 38 |   let permissionsDriver: PermissionsDriver;\n' +
      '     |                        ^\n' +
      '  39 |   let webAppDriver: WebAppDriver;\n' +
      '  40 |   let coBrandingAuthorizationCheck: sinon.SinonStub;\n' +
      '  41 |   let sitePropertiesAuthorizationCheck: sinon.SinonStub;, stack: SyntaxError: <homeDir>/projects/business-manager/business-manager-web/test/api/web-app.spec.ts: Unexpected token, expected ";" (38:23)\n' +
      '\n' +
      '  36 | \n' +
      "  37 | describe('web app', () => {\n" +
      '> 38 |   let permissionsDriver: PermissionsDriver;\n' +
      '     |                        ^\n' +
      '  39 |   let webAppDriver: WebAppDriver;\n' +
      '  40 |   let coBrandingAuthorizationCheck: sinon.SinonStub;\n' +
      '  41 |   let sitePropertiesAuthorizationCheck: sinon.SinonStub;\n' +
      '    at Parser._raise (<homeDir>/projects/business-manager/business-manager-web/node_modules/@babel/parser/src/parser/error.js:60:45)\n' +
      '    at Parser.raiseWithData (<homeDir>/projects/business-manager/business-manager-web/node_modules/@babel/parser/src/parser/error.js:55:17)\n' +
      '    at Parser.raise (<homeDir>/projects/business-manager/business-manager-web/node_modules/@babel/parser/src/parser/error.js:39:17)\n' +
      '    at Parser.unexpected (<homeDir>/projects/business-manager/business-manager-web/node_modules/@babel/parser/src/parser/util.js:139:16)\n' +
      '    at Parser.semicolon (<homeDir>/projects\n',
    '2020-12-29T15:31:08.854Z project Test run finished\n',
    '2020-12-29T15:31:08.854Z project Processed console.log entries\n',
    '2020-12-29T15:31:08.854Z project Processed loading sequences\n',
    '2020-12-29T15:31:08.854Z project Processed executed tests\n',
    '2020-12-29T15:31:08.854Z project Processed code coverage\n',
    '2020-12-29T15:31:08.855Z project Test run result processed and sent to IDE\n',
    '2020-12-29T15:31:11.118Z project Test run started; run priority: 2\n',
    '2020-12-29T15:31:11.119Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2020-12-29T15:31:11.119Z testTask Running only selected or not excluded tests\n',
    '2020-12-29T15:31:11.128Z workers Starting test run, priority: 2\n',
    '2020-12-29T15:31:11.128Z nodeRunner Starting sandbox [worker #0, session #7obho]\n',
    '2020-12-29T15:31:11.128Z nodeRunner Preparing sandbox [worker #0, session #7obho]\n',
    '2020-12-29T15:31:11.128Z nodeRunner Prepared sandbox [worker #0, session #7obho]\n',
    '2020-12-29T15:31:11.128Z workers [worker #0, session #7obho] Running tests in sandbox\n',
    '2020-12-29T15:31:11.222Z workers Sandbox (active) [7obho] error: <homeDir>/projects/business-manager/business-manager-web/test/api/web-app.spec.ts: Unexpected token, expected ";" (38:23)\n' +
      '\n' +
      '  36 | \n' +
      "  37 | describe('web app', () => {\n" +
      '> 38 |   let permissionsDriver: PermissionsDriver;\n' +
      '     |                        ^\n' +
      '  39 |   let webAppDriver: WebAppDriver;\n' +
      '  40 |   let coBrandingAuthorizationCheck: sinon.SinonStub;\n' +
      '  41 |   let sitePropertiesAuthorizationCheck: sinon.SinonStub;\n',
    '2020-12-29T15:31:11.223Z workers [7obho] Run 0 test(s), skipped 0 test(s)\n',
    '2020-12-29T15:31:11.225Z workers [7obho] Sandbox is responsive, closing it\n',
    '2020-12-29T15:31:11.225Z workers Failed to map the stack to user code, entry message: <homeDir>/projects/business-manager/business-manager-web/test/api/web-app.spec.ts: Unexpected token, expected ";" (38:23)\n' +
      '\n' +
      '  36 | \n' +
      "  37 | describe('web app', () => {\n" +
      '> 38 |   let permissionsDriver: PermissionsDriver;\n' +
      '     |                        ^\n' +
      '  39 |   let webAppDriver: WebAppDriver;\n' +
      '  40 |   let coBrandingAuthorizationCheck: sinon.SinonStub;\n' +
      '  41 |   let sitePropertiesAuthorizationCheck: sinon.SinonStub;, stack: SyntaxError: <homeDir>/projects/business-manager/business-manager-web/test/api/web-app.spec.ts: Unexpected token, expected ";" (38:23)\n' +
      '\n' +
      '  36 | \n' +
      "  37 | describe('web app', () => {\n" +
      '> 38 |   let permissionsDriver: PermissionsDriver;\n' +
      '     |                        ^\n' +
      '  39 |   let webAppDriver: WebAppDriver;\n' +
      '  40 |   let coBrandingAuthorizationCheck: sinon.SinonStub;\n' +
      '  41 |   let sitePropertiesAuthorizationCheck: sinon.SinonStub;\n' +
      '    at Parser._raise (<homeDir>/projects/business-manager/business-manager-web/node_modules/@babel/parser/src/parser/error.js:60:45)\n' +
      '    at Parser.raiseWithData (<homeDir>/projects/business-manager/business-manager-web/node_modules/@babel/parser/src/parser/error.js:55:17)\n' +
      '    at Parser.raise (<homeDir>/projects/business-manager/business-manager-web/node_modules/@babel/parser/src/parser/error.js:39:17)\n' +
      '    at Parser.unexpected (<homeDir>/projects/business-manager/business-manager-web/node_modules/@babel/parser/src/parser/util.js:139:16)\n' +
      '    at Parser.semicolon (<homeDir>/projects\n',
    '2020-12-29T15:31:11.226Z project Test run finished\n',
    '2020-12-29T15:31:11.226Z project Processed console.log entries\n',
    '2020-12-29T15:31:11.226Z project Processed loading sequences\n',
    '2020-12-29T15:31:11.226Z project Processed executed tests\n',
    '2020-12-29T15:31:11.226Z project Processed code coverage\n',
    '2020-12-29T15:31:11.227Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by smcenlly** [comment]
Your error indicates that `jest`'s `babel` settings are not transpiling your TypeScript to JavaScript code when Wallaby is executing your tests.

This problem is often caused when using Wallaby's [`automatic configuration`](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) (which your diagnostic report shows you are using) with a custom `jest.config.js` location. If `jest.config.js` is not located in your project root directory then you will have to manually provide the location by [overriding Wallaby's automatic configuration](https://wallabyjs.com/docs/integration/jest.html#overriding-automatic-configuration) detection:


```javascript
module.exports = () => {
  return {
    // tell wallaby to use automatic configuration
    autoDetect: true,

    testFramework: {
      // the jest configuration file path
      // (relative to project root)
      configFile: './jest.config.wallaby.js'
    }
  }
};
```

Please note: you *should* also get the same problem if you run `npx jest` from your WebStorm terminal for the same project.

---

If the above does not help, please tell us where your `jest` and `babel` configuration are located as well as the configuration files/contents.

**Comment by smcenlly** [comment]
I'm going to assume that our suggestion solved your problem. If not, please let us know and we'll re-open this issue.

**Comment by dht** [comment]
Tnx, getting back to the issue. We've managed to pass this hurdle, I don't remember exactly how.
