### ISSUE TITLE
Error starting with pnpm + workspaces

### ISSUE THREAD

**Issue by aussiegeek** [wallabyjs/public#2606]
### Issue description or question

Wallaby not working with pnpm + workspaces

When I start Wallaby, I very quickly get the error `‌[Error] Automatic Jest configuration error: Cannot find compatible jest-cli module`

I've published a repo where this can be reproduced at https://github.com/aussiegeek/wallaby-pnpm-workspaces-test-case

### Wallaby diagnostics report

```
{
  editorVersion: '1.52.1',
  pluginVersion: '1.0.257',
  editorType: 'VSCode',
  osVersion: 'darwin 20.2.0',
  nodeVersion: 'v14.15.0',
  coreVersion: '1.0.995',
  checksum: 'OTFlMTIwYzZkNTlkYTFiYTg5YjZjZDRhMzI0YzQxMTMsMTYyNTAxMTIwMDAwMCww',
  config: {},
  packageJSON: { dependencies: undefined, devDependencies: { 'jest-cli': '^26.6.3' } },
  fs: { numberOfFiles: 0 },
  debug: [
    '2021-01-14T01:13:04.281Z angular/cli config Angular CLI not found.\n',
    '2021-01-14T01:13:04.289Z jest/config Error: Cannot find compatible jest-cli module.\n' +
      '    at Object.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:28:8024)\n' +
      '    at n (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:27:26826)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:27:26121)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:27:26030\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:27:25824)\n' +
      '    at Object.loadJest (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:28:7163)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:18:2528\n' +
      '    at n (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:18:6404)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:18:5699)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:18:5608\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at s (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:18:5402)\n' +
      '    at n (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:18:2216)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:18:5079\n' +
      '    at n (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:18:6404)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:18:5699)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:18:5608\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at s (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:18:5402)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:18:4960)\n' +
      '    at Config.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:15:15609)\n' +
      '    at n (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:15:9099)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:15:8394)\n' +
      '    at o (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby0e6aa6/server.js:15:8143)\n'
  ]
}
```

**Comment by smcenlly** [comment]
Unfortunately the way pnpm installs modules by default is not supported by Wallaby. Having said that, the following command will install modules in a way that is supported:

```
pnpm install --shamefully-flatten
```

Last month we had a similar issue reported (https://github.com/wallabyjs/public/issues/2593), depending on your project, perhaps the same steps will help in your case:

> in my case it was enough to add public-hoist-pattern[] = "jest-runtime" to .npmrc in project root
