### ISSUE TITLE
[angular] VS Code extension fails when using Angular CLI 11.1 with automatic configuration

### ISSUE THREAD

**Issue by LayZeeDK** [wallabyjs/public#2608]
### Issue description or question

In a freshly generated Angular CLI 11.1 workspace, automatic configuration fails. I'm using VS Code.

No issues with Angular CLI 11.0.

When downgrading `package.json` to these dependencies, Wallaby works:
```json
  "dependencies": {
    "@angular/animations": "~11.0.5",
    "@angular/common": "~11.0.5",
    "@angular/compiler": "~11.0.5",
    "@angular/core": "~11.0.5",
    "@angular/forms": "~11.0.5",
    "@angular/platform-browser": "~11.0.5",
    "@angular/platform-browser-dynamic": "~11.0.5",
    "@angular/router": "~11.0.5",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.5",
    "@angular/cli": "~11.0.5",
    "@angular/compiler-cli": "~11.0.5",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
```

### Wallaby diagnostics report

```
{
  editorVersion: '1.52.1',
  pluginVersion: '1.0.260',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.19042',
  nodeVersion: 'v12.20.1',
  coreVersion: '1.0.1007',
  checksum: 'ZTc2ZTdhN2E5MjM4YWY0Yzc1ZTUzMzc5YTI2Yzk3N2YsMTYxNDI5NzYwMDAwMCww',
  config: {},
  packageJSON: {
    dependencies: {
      '@angular/animations': '~11.1.0',
      '@angular/common': '~11.1.0',
      '@angular/compiler': '~11.1.0',
      '@angular/core': '~11.1.0',
      '@angular/forms': '~11.1.0',
      '@angular/platform-browser': '~11.1.0',
      '@angular/platform-browser-dynamic': '~11.1.0',
      '@angular/router': '~11.1.0',
      rxjs: '~6.6.0',
      tslib: '^2.0.0',
      'zone.js': '~0.11.3'
    },
    devDependencies: {
      '@angular-devkit/build-angular': '~0.1101.0',
      '@angular/cli': '~11.1.0',
      '@angular/compiler-cli': '~11.1.0',
      '@types/jasmine': '~3.6.0',
      '@types/node': '^12.11.1',
      codelyzer: '^6.0.0',
      'jasmine-core': '~3.6.0',
      'jasmine-spec-reporter': '~5.0.0',
      karma: '~5.2.0',
      'karma-chrome-launcher': '~3.1.0',
      'karma-coverage': '~2.0.3',
      'karma-jasmine': '~4.0.0',
      'karma-jasmine-html-reporter': '^1.5.0',
      protractor: '~7.0.0',
      'ts-node': '~8.3.0',
      tslint: '~6.1.0',
      typescript: '~4.1.2'
    }
  },
  fs: { numberOfFiles: 0 },
  debug: [
    '2021-01-23T01:22:30.310Z angular/cli config Detected Angular CLI.\n',
    '2021-01-23T01:22:37.351Z angular/cli karma project config Using virtual C:/projects/sandbox/ngx-cli111-app/src/test.ts.\n',
    '2021-01-23T01:22:37.354Z angular/cli config Error: Unable to load webpack module.\n' +
      '    at Object.load (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:21:23291)\n' +
      '    at c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:21:19678\n' +
      '    at t.<anonymous> (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:16:24190)\n' +
      '    at n (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:16:16990)\n' +
      '    at Object.next (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:16:16285)\n' +
      '    at o (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:16:16044)\n',
    '2021-01-23T01:22:37.356Z angular/cli config Angular.json: \n' +
      ' {\n' +
      "  '$schema': './node_modules/@angular/cli/lib/config/schema.json',\n" +
      '  version: 1,\n' +
      "  cli: { packageManager: 'pnpm' },\n" +
      "  newProjectRoot: 'projects',\n" +
      '  projects: {\n' +
      "    'ngx-cli111-app': {\n" +
      "      projectType: 'application',\n" +
      "      schematics: { '@schematics/angular:application': { strict: true } },\n" +
      "      root: '',\n" +
      "      sourceRoot: 'src',\n" +
      "      prefix: 'app',\n" +
      '      architect: {\n' +
      '        build: {\n' +
      "          builder: '@angular-devkit/build-angular:browser',\n" +
      '          options: {\n' +
      "            outputPath: 'dist/ngx-cli111-app',\n" +
      "            index: 'src/index.html',\n" +
      "            main: 'src/main.ts',\n" +
      "            polyfills: 'src/polyfills.ts',\n" +
      "            tsConfig: 'tsconfig.app.json',\n" +
      '            aot: true,\n' +
      "            assets: [ 'src/favicon.ico', 'src/assets' ],\n" +
      "            styles: [ 'src/styles.css' ],\n" +
      '            scripts: []\n' +
      '          },\n' +
      '          configurations: {\n' +
      '            production: {\n' +
      "              fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.prod.ts' } ],\n" +
      '              optimization: true,\n' +
      "              outputHashing: 'all',\n" +
      '              sourceMap: false,\n' +
      '              namedChunks: false,\n' +
      '              extractLicenses: true,\n' +
      '              vendorChunk: false,\n' +
      '              buildOptimizer: true,\n' +
      "              budgets: [ { type: 'initial', maximumWarning: '500kb', maximumError: '1mb' }, { type: 'anyComponentStyle', maximumWarning: '2kb', maximumError: '4kb' } ]\n" +
      '            }\n' +
      '          }\n' +
      '        },\n' +
      '        serve: {\n' +
      "          builder: '@angular-devkit/build-angular:dev-server',\n" +
      "          options: { browserTarget: 'ngx-cli111-app:build' },\n" +
      "          configurations: { production: { browserTarget: 'ngx-cli111-app:build:production' } }\n" +
      '        },\n' +
      "        'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: 'ngx-cli111-app:build' } },\n" +
      '        test: {\n' +
      "          builder: '@angular-devkit/build-angular:karma',\n" +
      '          options: {\n' +
      "            main: 'src/test.ts',\n" +
      "            polyfills: 'src/polyfills.ts',\n" +
      "            tsConfig: 'tsconfig.spec.json',\n" +
      "            karmaConfig: 'karma.conf.js',\n" +
      "            assets: [ 'src/favicon.ico', 'src/assets' ],\n" +
      "            styles: [ 'src/styles.css' ],\n" +
      '            scripts: []\n' +
      '          }\n' +
      '        },\n' +
      "        lint: { builder: '@angular-devkit/build-angular:tslint', options: { tsConfig: [ 'tsconfig.app.json', 'tsconfig.spec.json', 'e2e/tsconfig.json' ], exclude: [ '**/node_modules/**' ] } },\n" +
      '        e2e: {\n' +
      "          builder: '@angular-devkit/build-angular:protractor',\n" +
      "          options: { protractorConfig: 'e2e/protractor.conf.js', devServerTarget: 'ngx-cli111-app:serve' },\n" +
      "          configurations: { production: { devServerTarget: 'ngx-cli111-app:serve:production' } }\n" +
      '        }\n' +
      '      }\n' +
      '    }\n' +
      '  },\n' +
      "  defaultProject: 'ngx-cli111-app'\n" +
      '}\n',
    '2021-01-23T01:22:37.356Z angular/cli config Error: Unable to load webpack module.\n' +
      '    at Object.load (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:21:23291)\n' +
      '    at c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:21:19678\n' +
      '    at t.<anonymous> (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:16:24190)\n' +
      '    at n (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:16:16990)\n' +
      '    at Object.next (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:16:16285)\n' +
      '    at o (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:16:16044)\n',
    "2021-01-23T01:22:37.361Z jest/config Error: Module jest-cli is not found in 'C:\\projects\\sandbox\\ngx-cli111-app'.\n" +
      '    at Object.<anonymous> (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:28:27428)\n' +
      '    at n (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:28:12148)\n' +
      '    at Object.next (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:28:11443)\n' +
      '    at c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:28:11352\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at r (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:28:11146)\n' +
      '    at Object.loadJest (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:28:25267)\n' +
      '    at c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:18:11074\n' +
      '    at n (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:18:15523)\n' +
      '    at Object.next (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:18:14818)\n' +
      '    at c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:18:14727\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at s (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:18:14521)\n' +
      '    at n (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:18:10762)\n' +
      '    at c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:18:14198\n' +
      '    at n (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:18:15523)\n' +
      '    at Object.next (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:18:14818)\n' +
      '    at c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:18:14727\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at s (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:18:14521)\n' +
      '    at r (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:18:14079)\n' +
      '    at Config.<anonymous> (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:15:24094)\n' +
      '    at n (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:15:17488)\n' +
      '    at Object.next (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:15:16783)\n' +
      '    at o (c:\\Users\\lgbn\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.260\\wallaby0e37ad\\server.js:15:16532)\n'
  ]
}
```

**Comment by NikGovorov** [comment]
Hi @LayZeeDK,

We tried to generate new Angular CLI 11.1 workspace and couldn't reproduce the issue. Could you please try to delete `node_modules`/`package-lock.json`, execute `npm install` and start Wallaby again?

**Comment by NachoVazquez** [comment]
Hi @NikGovorov,

I'm having the same issue as @LayZeeDK .

I will try what you suggested, but could you please share the `package.json` of the project where you tried?

Thanks!

**Comment by LayZeeDK** [comment]
> Could you please try to delete node_modules/package-lock.json, execute npm install and start Wallaby again?

I tried that several times. I tried using NPM CLI, Yarn CLI, and PNPM CLI.

**Comment by NikGovorov** [comment]
That's what I get when I generate new Angular CLI project:
```
{
  "name": "test2",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.1.0",
    "@angular/common": "~11.1.0",
    "@angular/compiler": "~11.1.0",
    "@angular/core": "~11.1.0",
    "@angular/forms": "~11.1.0",
    "@angular/platform-browser": "~11.1.0",
    "@angular/platform-browser-dynamic": "~11.1.0",
    "@angular/router": "~11.1.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1101.1",
    "@angular/cli": "~11.1.1",
    "@angular/compiler-cli": "~11.1.0",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.2.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.2"
  }
} 
```

**Comment by LayZeeDK** [comment]
I'll try again tonight night and publish the repo if it still doesn't work. What's the latest version of Wallaby core and the VS Code extension?

**Comment by NikGovorov** [comment]
Please try this repo: https://github.com/wallabyjs/wallaby-2608.

**Comment by NachoVazquez** [comment]
Yes, I can confirm that in a freshly created Angular workspace, application-ready or empty it is working.

**Comment by LayZeeDK** [comment]
Hi @NikGovorov,

I tried that repo and it works with NPM and Yarn as package manager, but it fails when using PNPM.

See https://github.com/wallabyjs/wallaby-2608/pull/1.

**Comment by ArtemGovorov** [comment]
Unfortunately the way pnpm installs modules by default is not supported by Wallaby. Having said that, this may help https://github.com/wallabyjs/public/issues/2606#issuecomment-759862780.

**Comment by LayZeeDK** [comment]
```
pnpm install --shamefully-hoist
```

fixes the issue in a freshly created Angular CLI workspace. Thanks!
