### ISSUE TITLE
Fails on OSS project with mocha + Vue CLI 4.X

### ISSUE THREAD

**Issue by undergroundwires** [wallabyjs/public#2629]
### Issue description or question

Project: [privacy.sexy](https://github.com/undergroundwires/privacy.sexy)

Using manual configuration + Vue CLI 4.x - Mocha.

Reproduce:

1. Install wallaby extension on vscode
2. Activate license with OS e-mail as license key
3. Clone `git clone https://github.com/undergroundwires/privacy.sexy`
4. `npm install wallaby-vue-compiler --save-dev`
2. Copy paste ~/wallaby.js for "Vue CLI 4.x - Mocha"
5. Run "ctrl + shift + p" + "Wallaby.js: Start"

### Wallaby diagnostics report

```
{
  editorVersion: '1.53.2',
  pluginVersion: '1.0.268',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.19042',
  nodeVersion: 'v14.7.0',
  coreVersion: '1.0.1030',
  checksum: 'YzViMTZlNTc2ZTZhYWEzNjVmMjE3ODMwZjE3Yjg3MjEsMTYxNDAzODQwMDAwMCww',
  config: {
    files: [ { pattern: 'src/**/*.*', load: false, ignore: false, trigger: true, order: 1 } ],
    tests: [ { pattern: 'tests/**/*.*', load: false, ignore: false, trigger: true, test: true, order: 2 } ],
    env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    testFramework: { version: 'jasmine@3.6.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3' },
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'const config = require("@vue/cli-service/webpack.config.js");\r\n' +
      '\r\n' +
      'const redundantPlugins = {\r\n' +
      '  ForkTsCheckerWebpackPlugin: true,\r\n' +
      '  PreloadPlugin: true,\r\n' +
      '  HtmlWebpackPlugin: true,\r\n' +
      '  CopyPlugin: true,\r\n' +
      '  CaseSensitivePathsPlugin: true,\r\n' +
      '  FriendlyErrorsWebpackPlugin: true,\r\n' +
      '};\r\n' +
      '\r\n' +
      'config.plugins = config.plugins.filter(\r\n' +
      '  (plugin) => !(plugin.constructor && redundantPlugins[plugin.constructor.name])\r\n' +
      ');\r\n' +
      '\r\n' +
      '// vue files are split into multiple webpack modules,\r\n' +
      '// we need to choose and map script webpack resource (i.e. module) to one absolute file path\r\n' +
      'const mapResourceToPath = (context) => {\r\n' +
      '  const resource = context.resource;\r\n' +
      '  \r\n' +
      '  if (context.version) {\r\n' +
      '    // loading phase\r\n' +
      "    if (resource.endsWith('vue')) {\r\n" +
      '      return `${resource}?ignore`;\r\n' +
      '    }\r\n' +
      '\r\n' +
      "    return resource.indexOf('type=script') > 0\r\n" +
      '      ? context.resourcePath\r\n' +
      '      : resource;\r\n' +
      '  }\r\n' +
      '\r\n' +
      '  // processing phase\r\n' +
      "  return resource.indexOf('type=script') > 0 && context.wallaby\r\n" +
      '    ? resource.substring(0, resource.indexOf("?"))\r\n' +
      '    : resource.endsWith("vue")\r\n' +
      '    ? `${resource}?ignore`\r\n' +
      '    : resource;\r\n' +
      '};\r\n' +
      '\r\n' +
      'module.exports = function(wallaby) {\r\n' +
      '  return {\r\n' +
      '    files: [{ pattern: "src/**/*.*", load: false }],\r\n' +
      '\r\n' +
      '    tests: [{ pattern: "tests/**/*.*", load: false }],\r\n' +
      '\r\n' +
      '    postprocessor: wallaby.postprocessors.webpack(config, {\r\n' +
      '      setupFiles: [require.resolve("@vue/cli-plugin-unit-mocha/setup")],\r\n' +
      '      mapResourceToPath: mapResourceToPath,\r\n' +
      '    }),\r\n' +
      '\r\n' +
      '    env: {\r\n' +
      '      kind: "chrome",\r\n' +
      '    },\r\n' +
      '\r\n' +
      '    setup: function() {\r\n' +
      '      // required to trigger test loading\r\n' +
      '      window.__moduleBundler.loadTests();\r\n' +
      '    }\r\n' +
      '  };\r\n' +
      '};\r\n'
  },
  packageJSON: {
    dependencies: {
      '@fortawesome/fontawesome-svg-core': '^1.2.32',
      '@fortawesome/free-brands-svg-icons': '^5.15.1',
      '@fortawesome/free-regular-svg-icons': '^5.15.1',
      '@fortawesome/free-solid-svg-icons': '^5.15.1',
      '@fortawesome/vue-fontawesome': '^2.0.2',
      'ace-builds': '^1.4.12',
      'core-js': '^3.6.5',
      'file-saver': '^2.0.5',
      inversify: '^5.0.5',
      'liquor-tree': '^0.2.70',
      'v-tooltip': '2.0.2',
      vue: '^2.6.12',
      'vue-class-component': '^7.2.6',
      'vue-js-modal': '^2.0.0-rc.6',
      'vue-property-decorator': '^9.1.2'
    },
    devDependencies: {
      '@types/ace': '0.0.44',
      '@types/chai': '^4.2.14',
      '@types/file-saver': '^2.0.1',
      '@types/mocha': '^8.2.0',
      '@vue/cli-plugin-babel': '^4.5.10',
      '@vue/cli-plugin-typescript': '^4.5.9',
      '@vue/cli-plugin-unit-mocha': '^4.5.9',
      '@vue/cli-service': '^4.5.9',
      '@vue/test-utils': '1.1.2',
      chai: '^4.2.0',
      electron: '^11.1.0',
      'electron-devtools-installer': '^3.1.1',
      'electron-log': '^4.3.1',
      'electron-updater': '^4.3.5',
      'js-yaml-loader': '^1.2.2',
      'markdownlint-cli': '^0.26.0',
      'remark-cli': '^9.0.0',
      'remark-lint-no-dead-urls': '^1.1.0',
      'remark-preset-lint-consistent': '^4.0.0',
      'remark-validate-links': '^10.0.2',
      sass: '^1.30.0',
      'sass-loader': '^10.1.0',
      typescript: '^4.1.3',
      'vue-cli-plugin-electron-builder': '^2.0.0-rc.5',
      'vue-template-compiler': '^2.6.12',
      'wallaby-vue-compiler': '^1.0.6',
      'yaml-lint': '^1.2.4'
    }
  },
  fs: { numberOfFiles: 463 },
  debug: [
    '2021-02-18T08:57:49.720Z extended-core Validating Open Source License\n',
    "2021-02-18T08:57:49.722Z extended-core Remotes:  [ 'https://github.com/undergroundwires/privacy.sexy' ]\n",
    '2021-02-18T08:57:52.781Z project Wallaby Node version: v14.7.0\n',
    '2021-02-18T08:57:52.781Z project Wallaby config: {{repository-dir}}\\privacy.sexy\\wallaby.js\n',
    '2021-02-18T08:57:53.502Z project File cache: {{system-drive}}:\\Users\\{{user-name}}\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.268\\projects\\e92115a91b11dc15\n',
    '2021-02-18T08:57:53.725Z uiService Listening port 51235\n',
    '2021-02-18T08:57:53.832Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2021-02-18T08:57:53.833Z workers Starting run worker instance #0\n',
    '2021-02-18T08:57:53.833Z workers Starting run worker instance #1\n',
    '2021-02-18T08:57:53.833Z workers Starting run worker instance #2\n',
    '2021-02-18T08:57:53.833Z workers Starting run worker instance #3\n',
    '2021-02-18T08:57:53.833Z workers Starting run worker instance #4\n',
    '2021-02-18T08:57:53.833Z workers Starting run worker instance #5\n',
    '2021-02-18T08:57:53.836Z workers Web server is listening at 51278\n',
    '2021-02-18T08:57:53.842Z project Stopping process pool\n',
    '2021-02-18T08:57:53.842Z project File cache is up-to-date, starting full test run\n',
    '2021-02-18T08:57:53.847Z project Running postprocessor\n',
    '2021-02-18T08:57:53.855Z postprocessor Processing started.\n',
    '2021-02-18T08:57:53.855Z postprocessor Initializing.\n',
    '2021-02-18T08:57:53.856Z postprocessor Initializing entry.\n',
    '2021-02-18T08:57:53.856Z postprocessor Sanitizing configuration.\n',
    '2021-02-18T08:57:53.857Z postprocessor Adjusting configuration.\n',
    '2021-02-18T08:57:53.857Z postprocessor Creating compiler.\n',
    '2021-02-18T08:57:54.042Z postprocessor Customizing compiler.\n',
    '2021-02-18T08:57:54.042Z postprocessor Compilation started.\n',
    '2021-02-18T08:57:54.955Z workers Started run worker instance (immediate) #0\n',
    '2021-02-18T08:57:54.955Z workers Started run worker instance (immediate) #1\n',
    '2021-02-18T08:57:54.955Z workers Started run worker instance (immediate) #2\n',
    '2021-02-18T08:57:54.955Z workers Started run worker instance (immediate) #3\n',
    '2021-02-18T08:57:54.955Z workers Started run worker instance (immediate) #4\n',
    '2021-02-18T08:57:54.955Z workers Started run worker instance (immediate) #5\n',
    '2021-02-18T08:58:03.397Z uiService UI client connected\n',
    '2021-02-18T08:58:03.398Z uiService Outgoing message ui:handshake\n',
    '2021-02-18T08:58:03.406Z uiService UI client disconnected\n',
    '2021-02-18T08:58:11.538Z uiService UI client connected\n',
    '2021-02-18T08:58:11.538Z uiService Outgoing message ui:handshake\n',
    '2021-02-18T08:58:11.687Z uiService Incoming message ui:tests:resultsRequested\n',
    '2021-02-18T08:58:11.689Z uiService Outgoing message ui:tests:allResultsUpdated\n',
    '2021-02-18T08:58:11.711Z uiService Incoming message ui:start\n',
    '2021-02-18T08:58:11.712Z uiService Outgoing message ui:summary\n',
    '2021-02-18T08:58:11.716Z uiService Outgoing message ui:files\n',
    '2021-02-18T08:58:11.933Z project Error: ./tests/unit/application/Context/State/Filter/dist/FilterResult.spec.js\n' +
      "Module not found: Error: Can't resolve '../../../../stubs/CategoryStub' in '{{repository-dir}}\\privacy.sexy\\tests\\unit\\application\\Context\\State\\Filter\\dist'\n" +
      ' @ ./tests/unit/application/Context/State/Filter/dist/FilterResult.spec.js 4:42-83\n' +
      ' @ ./wallaby-webpack-entry.js\n' +
      '    at t.<anonymous> ({{system-drive}}:\\Users\\{{user-name}}\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.268\\wallabyf72b13\\server.js:21:17671)\n' +
      '    at n ({{system-drive}}:\\Users\\{{user-name}}\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.268\\wallabyf72b13\\server.js:21:14062)\n' +
      '    at Object.next ({{system-drive}}:\\Users\\{{user-name}}\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.268\\wallabyf72b13\\server.js:21:13357)\n' +
      '    at o ({{system-drive}}:\\Users\\{{user-name}}\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.268\\wallabyf72b13\\server.js:21:13116)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n',
    '2021-02-18T08:58:11.935Z project Test run finished\n',
    '2021-02-18T08:58:11.935Z project Test run data re-queued\n',
    '2021-02-18T08:58:11.935Z uiService Outgoing message ui:summary\n'
  ]
}
```

**Comment by smcenlly** [comment]
There were a couple of problems with your project and our default `Vue CLI 4.x - Mocha` configuration.

1. The `files` and `tests` sections of your configuration need to be changed slightly for your project.
2. There was a bug in our default configuration for Vue CLI 4.x that we had not encountered before but exists for your project (it's fixed now). See changes below:

**Wallaby.js**
```diff
const config = require("@vue/cli-service/webpack.config.js");

const redundantPlugins = {
  ForkTsCheckerWebpackPlugin: true,
  PreloadPlugin: true,
  HtmlWebpackPlugin: true,
  CopyPlugin: true,
  CaseSensitivePathsPlugin: true,
  FriendlyErrorsWebpackPlugin: true,
};

config.plugins = config.plugins.filter(
  (plugin) => !(plugin.constructor && redundantPlugins[plugin.constructor.name])
);

// vue files are split into multiple webpack modules,
// we need to choose and map script webpack resource (i.e. module) to one absolute file path
const mapResourceToPath = (context) => {
  const resource = context.resource;

+ if (!resource) return resource;

  if (context.version) {
    // loading phase
    if (resource.endsWith("vue")) {
      return `${resource}?ignore`;
    }

    return resource.indexOf("type=script") > 0
      ? context.resourcePath
      : resource;
  }

  // processing phase
  return resource.indexOf("type=script") > 0 && context.wallaby
    ? resource.substring(0, resource.indexOf("?"))
    : resource.endsWith("vue")
    ? `${resource}?ignore`
    : resource;
};

module.exports = function(wallaby) {
  return {
    files: [
      { pattern: "src/**/*.*", load: false },
+     { pattern: "tests/**/*.*", load: false },
+     { pattern: "tests/**/*.spec.*", load: false, ignore: true }
    ],

    tests: [
-     { pattern: "tests/**/*.*", load: false },
+     { pattern: "tests/**/*.spec.*", load: false }
    ],

    postprocessor: wallaby.postprocessors.webpack(config, {
      setupFiles: [require.resolve("@vue/cli-plugin-unit-mocha/setup")],
      mapResourceToPath: mapResourceToPath,
    }),

    env: {
      kind: "chrome",
    },

    setup: function() {
      // required to trigger test loading
      window.__moduleBundler.loadTests();
    },
  };
};
```

---

To configure your project, the following should work for you:

1. Clone `git clone https://github.com/undergroundwires/privacy.sexy`
2. `npm install` (just for project dependencies, no need for any Wallaby dependencies)
3. Use the configuration below:

```javascript
const config = require("@vue/cli-service/webpack.config.js");

const redundantPlugins = {
  ForkTsCheckerWebpackPlugin: true,
  PreloadPlugin: true,
  HtmlWebpackPlugin: true,
  CopyPlugin: true,
  CaseSensitivePathsPlugin: true,
  FriendlyErrorsWebpackPlugin: true,
};

config.plugins = config.plugins.filter(
  (plugin) => !(plugin.constructor && redundantPlugins[plugin.constructor.name])
);

// vue files are split into multiple webpack modules,
// we need to choose and map script webpack resource (i.e. module) to one absolute file path
const mapResourceToPath = (context) => {
  const resource = context.resource;

  if (!resource) return resource;

  if (context.version) {
    // loading phase
    if (resource.endsWith("vue")) {
      return `${resource}?ignore`;
    }

    return resource.indexOf("type=script") > 0
      ? context.resourcePath
      : resource;
  }

  // processing phase
  return resource.indexOf("type=script") > 0 && context.wallaby
    ? resource.substring(0, resource.indexOf("?"))
    : resource.endsWith("vue")
    ? `${resource}?ignore`
    : resource;
};

module.exports = function(wallaby) {
  return {
    files: [
      { pattern: "src/**/*.*", load: false },
      { pattern: "tests/**/*.*", load: false },
      { pattern: "tests/**/*.spec.*", load: false, ignore: true }
    ],

    tests: [
      { pattern: "tests/**/*.spec.*", load: false }
    ],

    postprocessor: wallaby.postprocessors.webpack(config, {
      setupFiles: [require.resolve("@vue/cli-plugin-unit-mocha/setup")],
      mapResourceToPath: mapResourceToPath,
    }),

    env: {
      kind: "chrome",
    },

    setup: function() {
      // required to trigger test loading
      window.__moduleBundler.loadTests();
    },

    debug: true,
    trace: true
  };
};
```

4. Start Wallaby

At this point, you will have an error in Wallaby that doesn't appear when your run your tests from the CLI:

```
Error: 'it' should only be used in 'describe' function 
      at _loop_1 ​tests/unit/application/Parser/Script/Syntax/SyntaxFactory.spec.ts:18:20​
      at t.<anonymous> ​tests/unit/application/Parser/Script/Syntax/SyntaxFactory.spec.ts:17:21
```

It looks like you need to change the parent `it` block to a `describe` and that will fix your problem.
