### ISSUE TITLE
Wallaby Webpack render error: expecting chunks.size of 1, instead of 4

### ISSUE THREAD

**Issue by provegard** [wallabyjs/public#2652]
### Issue description or question

I have a project that imports amcharts core + charts. When I run Wallaby on this project, I get:

```
2021-03-06T23:25:29.431Z project Error: Wallaby Webpack render error: expecting chunks.size of 1, instead of 4
    at t._renderModule (C:\Users\perro\AppData\Local\JetBrains\IntelliJIdea2020.3\wallaby\wallaby\server.js:22:9574)
    at t.<anonymous> (C:\Users\perro\AppData\Local\JetBrains\IntelliJIdea2020.3\wallaby\wallaby\server.js:21:18886)
    at n (C:\Users\perro\AppData\Local\JetBrains\IntelliJIdea2020.3\wallaby\wallaby\server.js:21:14788)
    at Object.next (C:\Users\perro\AppData\Local\JetBrains\IntelliJIdea2020.3\wallaby\wallaby\server.js:21:14083)
    at o (C:\Users\perro\AppData\Local\JetBrains\IntelliJIdea2020.3\wallaby\wallaby\server.js:21:13842)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

To reproduce, run Wallaby from https://github.com/provegard/wallaby-webpack-sample/tree/amcharts-error. **Please note that the repro is on the amcharts-error branch.**

I have tried to add the following to `files` without luck:

    { pattern: 'node_modules/@amcharts/**/*.js', instrument: false, load: false },

### Wallaby diagnostics report

```
{
  editorVersion: 'IntelliJ IDEA 2020.3.2',
  pluginVersion: '1.0.213',
  editorType: 'IntelliJ',
  osVersion: 'win32 10.0.19042',
  nodeVersion: 'v14.16.0',
  coreVersion: '1.0.1042',
  config: {
    files: [
      { pattern: 'node_modules/chai/chai.js', instrument: false, ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**/*.js', load: false, ignore: false, trigger: true, order: 2 }
    ],
    tests: [ { pattern: 'test/**/*Spec.js', load: false, ignore: false, trigger: true, test: true, order: 3 } ],
    trace: true,
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    addModifiedTestFileToExclusiveTestRun: true,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    env: { type: 'browser', kind: 'chrome', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    testFramework: { version: 'jasmine@3.6.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3' },
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'module.exports = function (wallaby) {\r\n' +
      '\r\n' +
      '  return {\r\n' +
      '    files: [\r\n' +
      '      // loading chai globally\r\n' +
      "      { pattern: 'node_modules/chai/chai.js', instrument: false },\r\n" +
      "      { pattern: 'src/**/*.js', load: false }\r\n" +
      '    ],\r\n' +
      '\r\n' +
      '    tests: [\r\n' +
      "      { pattern: 'test/**/*Spec.js', load: false }\r\n" +
      '    ],\r\n' +
      '\r\n' +
      '    // compilers: {\r\n' +
      "    //   '**/*.js': wallaby.compilers.babel()\r\n" +
      '    // },\r\n' +
      '\r\n' +
      '    postprocessor: wallaby.postprocessors.webpack({}),\r\n' +
      '\r\n' +
      '    setup: function () {\r\n' +
      '      window.expect = chai.expect;\r\n' +
      '      window.__moduleBundler.loadTests();\r\n' +
      '    },\r\n' +
      '\r\n' +
      '    trace: true\r\n' +
      '  };\r\n' +
      '};\r\n'
  },
  packageJSON: {
    dependencies: { '@amcharts/amcharts4': '^4.10.16' },
    devDependencies: { 'babel-core': '^6.26.0', 'babel-preset-es2015': '^6.24.1', chai: '^4.1.2', 'wallaby-webpack': '^3.9.16', webpack: '^5.24.3' }
  },
  fs: { numberOfFiles: 3 },
  debug: [
    '2021-03-06T23:25:22.708Z project Wallaby Node version: v14.16.0\n',
    '2021-03-06T23:25:22.708Z project Wallaby config: C:\\kod\\projects\\wallaby-webpack-sample\\wallaby.js\n',
    '2021-03-06T23:25:22.779Z project File cache: C:\\Users\\perro\\AppData\\Local\\JetBrains\\IntelliJIdea2020.3\\wallaby\\projects\\66782bc09218eff1\n',
    '2021-03-06T23:25:23.065Z uiService Listening port 51235\n',
    '2021-03-06T23:25:23.101Z project Config file change detected, invalidating local cache\n',
    '2021-03-06T23:25:23.152Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2021-03-06T23:25:23.152Z workers Starting run worker instance #0\n',
    '2021-03-06T23:25:23.153Z workers Starting run worker instance #1\n',
    '2021-03-06T23:25:23.153Z workers Starting run worker instance #2\n',
    '2021-03-06T23:25:23.153Z workers Starting run worker instance #3\n',
    '2021-03-06T23:25:23.153Z workers Starting run worker instance #4\n',
    '2021-03-06T23:25:23.153Z workers Starting run worker instance #5\n',
    '2021-03-06T23:25:23.155Z workers Web server is listening at 61751\n',
    '2021-03-06T23:25:23.163Z project Stopping process pool\n',
    '2021-03-06T23:25:23.163Z project File cache is up-to-date, starting full test run\n',
    '2021-03-06T23:25:23.164Z project Running postprocessor\n',
    '2021-03-06T23:25:23.167Z postprocessor Processing started.\n',
    '2021-03-06T23:25:23.167Z postprocessor Initializing.\n',
    '2021-03-06T23:25:23.167Z postprocessor Initializing entry.\n',
    '2021-03-06T23:25:23.167Z postprocessor Sanitizing configuration.\n',
    '2021-03-06T23:25:23.167Z postprocessor Adjusting configuration.\n',
    '2021-03-06T23:25:23.167Z postprocessor Creating compiler.\n',
    '2021-03-06T23:25:23.895Z postprocessor Customizing compiler.\n',
    '2021-03-06T23:25:23.895Z postprocessor Compilation started.\n',
    '2021-03-06T23:25:23.935Z workers Started run worker instance (immediate) #0\n',
    '2021-03-06T23:25:23.935Z workers Started run worker instance (immediate) #1\n',
    '2021-03-06T23:25:23.935Z workers Started run worker instance (immediate) #2\n',
    '2021-03-06T23:25:23.935Z workers Started run worker instance (immediate) #3\n',
    '2021-03-06T23:25:23.935Z workers Started run worker instance (immediate) #4\n',
    '2021-03-06T23:25:23.935Z workers Started run worker instance (immediate) #5\n',
    '2021-03-06T23:25:29.429Z postprocessor Compilation finished.\n',
    '2021-03-06T23:25:29.431Z project Error: Wallaby Webpack render error: expecting chunks.size of 1, instead of 4\n' +
      '    at t._renderModule (C:\\Users\\perro\\AppData\\Local\\JetBrains\\IntelliJIdea2020.3\\wallaby\\wallaby\\server.js:22:9574)\n' +
      '    at t.<anonymous> (C:\\Users\\perro\\AppData\\Local\\JetBrains\\IntelliJIdea2020.3\\wallaby\\wallaby\\server.js:21:18886)\n' +
      '    at n (C:\\Users\\perro\\AppData\\Local\\JetBrains\\IntelliJIdea2020.3\\wallaby\\wallaby\\server.js:21:14788)\n' +
      '    at Object.next (C:\\Users\\perro\\AppData\\Local\\JetBrains\\IntelliJIdea2020.3\\wallaby\\wallaby\\server.js:21:14083)\n' +
      '    at o (C:\\Users\\perro\\AppData\\Local\\JetBrains\\IntelliJIdea2020.3\\wallaby\\wallaby\\server.js:21:13842)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n',
    '2021-03-06T23:25:29.435Z project Test run finished\n',
    '2021-03-06T23:25:29.435Z project Test run data re-queued\n'
  ]
}
```

**Comment by smcenlly** [comment]
Please try the suggestions mentioned [here](https://github.com/wallabyjs/public/issues/2651). The same comments/suggestions apply.

**Comment by provegard** [comment]
Ok, makes sense. Might I suggest referring to a relevant documentation page in the error message?
