### ISSUE TITLE
Upgrading to Webpack v5 (from v4) results in wallabyjs failing to start test execution

### ISSUE THREAD

**Issue by greyepoxy** [wallabyjs/public#2659]
### Issue description or question

When upgrading from Webpack v4 to Webpack v5 wallaby fails to start executing tests.
Using a fork of the TypeScript + Webpack + Wallaby sample I created a reproduction of the issue.

**With webpack v4 - works as expected**
First I setup the scenario that breaks with webpack v5 but in order to show that it works, didn't upgrade yet.
https://github.com/greyepoxy/wallaby-webpack-ts-loader/tree/with-webpack-v4
Check out the difference against the sample https://github.com/greyepoxy/wallaby-webpack-ts-loader/compare/master...greyepoxy:with-webpack-v4 (looks like LF to CRLF is causing github to not show the file diffs correctly 😞 )

This works as expected, starting wallaby succeeds in executing the tests

**With webpack v5 - Doesn't work**
Here is the branch that is just an upgrade to webpack v5 
https://github.com/greyepoxy/wallaby-webpack-ts-loader/tree/with-webpack-v5
Check out the difference from the previous branch https://github.com/greyepoxy/wallaby-webpack-ts-loader/compare/with-webpack-v4...greyepoxy:with-webpack-v5

Note: make sure to run `npm install` before starting wallaby

Starting wallaby results in a failure to start the tests with the following three errors.

1. `ReferenceError: process is not defined`
1. `TypeError: __webpack_require__.nmd is not a function`
1. `TypeError: Cannot read property 'Symbol' of undefined`

The two `TypeErrors` appear to be new code substitutions webpack v5 is doing during bundling. Looks like wallaby re-implements the webpack runtime so I am guessing these just need to be handled.

Not sure what is directly causing it but the `ReferenceError` appears to be wallaby specific.
The root cause is that the bundled `React/index.js` has the following code
```
if (process.env.NODE_ENV === 'production') {
  module.exports = __webpack_require__("./node_modules/react/cjs/react.production.min.js");
} else {
  module.exports = __webpack_require__("./node_modules/react/cjs/react.development.js");
}
```
The [default behavior of webpack](https://webpack.js.org/configuration/mode/) is to substitute `process.env.NODE_ENV` with the string `'development'` when mode is set to `'development'` (like it is in [this reproduction](https://github.com/greyepoxy/wallaby-webpack-ts-loader/blob/with-webpack-v5/webpack.config.base.js#L2)).

So in order to make sure this was wallaby specific (and not a bug with webpack) I made a commit to the code above to webpack the test file using react
https://github.com/greyepoxy/wallaby-webpack-ts-loader/tree/comparing-wallaby-webpack-to-just-weback
Check out the diff from the previous branch https://github.com/greyepoxy/wallaby-webpack-ts-loader/compare/with-webpack-v5...greyepoxy:comparing-wallaby-webpack-to-just-weback

Looking at the resulting bundled file I do see the expected substitution of `process.env.NODE_ENV` and the resulting dead code elimination https://github.com/greyepoxy/wallaby-webpack-ts-loader/blob/comparing-wallaby-webpack-to-just-weback/dist/main.js#L2158.

### Wallaby diagnostics report

This report was generated using the problematic `with-webpack-v5` branch above

```
{
  editorVersion: '1.54.2',
  pluginVersion: '1.0.274',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.18363',
  nodeVersion: 'v12.18.3',
  coreVersion: '1.0.1044',
  checksum: 'MThjOWUzOGNhZWEwODFkOTdmZDE5ZDQ5NzA3ZjdkNjIsMTY0NzU2MTYwMDAwMCww',
  config: {
    files: [ { pattern: 'src/**/*.ts', load: false, ignore: false, trigger: true, order: 1 } ],
    tests: [ { pattern: 'test/**/*Spec.ts', load: false, ignore: false, trigger: true, test: true, order: 2 } ],
    env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    debug: true,
    trace: true,
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    addModifiedTestFileToExclusiveTestRun: true,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    testFramework: { version: 'jasmine@3.6.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3' },
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: "const webpackConfig = require('./webpack.config.base');\r\n" +
      '\r\n' +
      'module.exports = function(wallaby) {\r\n' +
      '  return {\r\n' +
      "    files: [{ pattern: 'src/**/*.ts', load: false }],\r\n" +
      '\r\n' +
      "    tests: [{ pattern: 'test/**/*Spec.ts', load: false }],\r\n" +
      '\r\n' +
      '    postprocessor: wallaby.postprocessors.webpack(webpackConfig),\r\n' +
      '\r\n' +
      '    env: {\r\n' +
      "      kind: 'chrome'\r\n" +
      '    },\r\n' +
      '\r\n' +
      '    setup: function() {\r\n' +
      '      window.__moduleBundler.loadTests();\r\n' +
      '    },\r\n' +
      '\r\n' +
      '    debug: true,\r\n' +
      '    trace: true\r\n' +
      '  };\r\n' +
      '};\r\n'
  },
  packageJSON: {
    dependencies: { 'has-symbols': '^1.0.1', lodash: '^4.17.15', react: '^16.8.6', tslib: '^1.10.0' },
    devDependencies: { '@types/jasmine': '^3.4.0', 'awesome-typescript-loader': '^5.2.1', prettier: '^1.18.2', 'ts-loader': '^6.0.4', typescript: '^3.5.3', webpack: '^5.25.0', 'webpack-cli': '^4.5.0' }
  },
  fs: { numberOfFiles: 4 },
  debug: [
    '2021-03-12T23:25:42.953Z project Wallaby Node version: v12.18.3\n',
    '2021-03-12T23:25:42.953Z project Wallaby config: D:\\github\\greyepoxy\\wallaby-webpack-ts-loader\\wallaby.js\n',
    '2021-03-12T23:25:43.315Z uiService Listening port 51235\n',
    '2021-03-12T23:25:43.368Z project package.json file change detected, invalidating local cache\n',
    '2021-03-12T23:25:43.464Z workers Parallelism for initial run: 38, for regular run: 19\n',
    '2021-03-12T23:25:43.465Z workers Starting run worker instance #0\n',
    '2021-03-12T23:25:43.465Z workers Starting run worker instance #1\n',
    '2021-03-12T23:25:43.465Z workers Starting run worker instance #2\n',
    '2021-03-12T23:25:43.465Z workers Starting run worker instance #3\n',
    '2021-03-12T23:25:43.465Z workers Starting run worker instance #4\n',
    '2021-03-12T23:25:43.465Z workers Starting run worker instance #5\n',
    '2021-03-12T23:25:43.465Z workers Starting run worker instance #6\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #7\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #8\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #9\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #10\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #11\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #12\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #13\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #14\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #15\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #16\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #17\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #18\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #19\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #20\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #21\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #22\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #23\n',
    '2021-03-12T23:25:43.466Z workers Starting run worker instance #24\n',
    '2021-03-12T23:25:43.467Z workers Starting run worker instance #25\n',
    '2021-03-12T23:25:43.467Z workers Starting run worker instance #26\n',
    '2021-03-12T23:25:43.467Z workers Starting run worker instance #27\n',
    '2021-03-12T23:25:43.467Z workers Starting run worker instance #28\n',
    '2021-03-12T23:25:43.467Z workers Starting run worker instance #29\n',
    '2021-03-12T23:25:43.467Z workers Starting run worker instance #30\n',
    '2021-03-12T23:25:43.467Z workers Starting run worker instance #31\n',
    '2021-03-12T23:25:43.467Z workers Starting run worker instance #32\n',
    '2021-03-12T23:25:43.467Z workers Starting run worker instance #33\n',
    '2021-03-12T23:25:43.467Z workers Starting run worker instance #34\n',
    '2021-03-12T23:25:43.467Z workers Starting run worker instance #35\n',
    '2021-03-12T23:25:43.467Z workers Starting run worker instance #36\n',
    '2021-03-12T23:25:43.467Z workers Starting run worker instance #37\n',
    '2021-03-12T23:25:43.471Z workers Web server is listening at 59068\n',
    '2021-03-12T23:25:43.489Z project Stopping process pool\n',
    '2021-03-12T23:25:43.489Z project File cache is up-to-date, starting full test run\n',
    '2021-03-12T23:25:43.491Z project Running postprocessor\n',
    '2021-03-12T23:25:43.494Z postprocessor Processing started.\n',
    '2021-03-12T23:25:43.494Z postprocessor Initializing.\n',
    '2021-03-12T23:25:43.495Z postprocessor Initializing entry.\n',
    '2021-03-12T23:25:43.495Z postprocessor Sanitizing configuration.\n',
    '2021-03-12T23:25:43.495Z postprocessor Adjusting configuration.\n',
    '2021-03-12T23:25:43.495Z postprocessor Creating compiler.\n',
    '2021-03-12T23:25:44.431Z postprocessor Customizing compiler.\n',
    '2021-03-12T23:25:44.431Z postprocessor Compilation started.\n',
    '2021-03-12T23:25:44.464Z workers Started run worker instance (immediate) #0\n',
    '2021-03-12T23:25:44.464Z workers Started run worker instance (immediate) #1\n',
    '2021-03-12T23:25:44.464Z workers Started run worker instance (immediate) #2\n',
    '2021-03-12T23:25:44.464Z workers Started run worker instance (immediate) #3\n',
    '2021-03-12T23:25:44.464Z workers Started run worker instance (immediate) #4\n',
    '2021-03-12T23:25:44.464Z workers Started run worker instance (immediate) #5\n',
    '2021-03-12T23:25:44.464Z workers Started run worker instance (immediate) #6\n',
    '2021-03-12T23:25:44.464Z workers Started run worker instance (immediate) #7\n',
    '2021-03-12T23:25:44.464Z workers Started run worker instance (immediate) #8\n',
    '2021-03-12T23:25:44.464Z workers Started run worker instance (immediate) #9\n',
    '2021-03-12T23:25:44.464Z workers Started run worker instance (immediate) #10\n',
    '2021-03-12T23:25:44.464Z workers Started run worker instance (immediate) #11\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #12\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #13\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #14\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #15\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #16\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #17\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #18\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #19\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #20\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #21\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #22\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #23\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #24\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #25\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #26\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #27\n',
    '2021-03-12T23:25:44.465Z workers Started run worker instance (immediate) #28\n',
    '2021-03-12T23:25:44.466Z workers Started run worker instance (immediate) #29\n',
    '2021-03-12T23:25:44.466Z workers Started run worker instance (immediate) #30\n',
    '2021-03-12T23:25:44.466Z workers Started run worker instance (immediate) #31\n',
    '2021-03-12T23:25:44.466Z workers Started run worker instance (immediate) #32\n',
    '2021-03-12T23:25:44.466Z workers Started run worker instance (immediate) #33\n',
    '2021-03-12T23:25:44.466Z workers Started run worker instance (immediate) #34\n',
    '2021-03-12T23:25:44.466Z workers Started run worker instance (immediate) #35\n',
    '2021-03-12T23:25:44.466Z workers Started run worker instance (immediate) #36\n',
    '2021-03-12T23:25:44.466Z workers Started run worker instance (immediate) #37\n',
    '2021-03-12T23:25:45.718Z postprocessor Compilation finished.\n',
    '2021-03-12T23:25:45.892Z postprocessor Emitting 104 files.\n',
    '2021-03-12T23:25:45.897Z postprocessor Processing finished.\n',
    '2021-03-12T23:25:45.902Z project Postprocessor execution finished\n',
    '2021-03-12T23:25:45.902Z project Test run started; run priority: 3\n',
    '2021-03-12T23:25:45.903Z project Running all tests\n',
    '2021-03-12T23:25:45.907Z workers Starting test run, priority: 3\n',
    '2021-03-12T23:25:45.908Z workers Distributing tests between 38 workers\n',
    '2021-03-12T23:25:45.909Z workers Running tests in parallel\n',
    '2021-03-12T23:25:45.909Z chromeRunner Starting sandbox [worker #0, session #97s3d]\n',
    '2021-03-12T23:25:45.909Z chromeRunner Starting sandbox [worker #1, session #cfahp]\n',
    '2021-03-12T23:25:45.909Z chromeRunner Starting sandbox [worker #2, session #18oi4]\n',
    '2021-03-12T23:25:45.910Z chromeRunner Preparing sandbox [worker #0, session #97s3d]\n',
    '2021-03-12T23:25:45.910Z browserRunner Total files to load in sandbox: 4\n',
    '2021-03-12T23:25:45.911Z browserRunner Sandbox is generated [worker #0, session #97s3d]: http://localhost:59068/wallaby_sandbox0.html\n',
    '2021-03-12T23:25:45.911Z chromeRunner Preparing sandbox [worker #1, session #cfahp]\n',
    '2021-03-12T23:25:45.912Z browserRunner Total files to load in sandbox: 4\n',
    '2021-03-12T23:25:45.912Z browserRunner Sandbox is generated [worker #1, session #cfahp]: http://localhost:59068/wallaby_sandbox1.html\n',
    '2021-03-12T23:25:45.912Z chromeRunner Preparing sandbox [worker #2, session #18oi4]\n',
    '2021-03-12T23:25:45.912Z browserRunner Total files to load in sandbox: 4\n',
    '2021-03-12T23:25:45.912Z browserRunner Sandbox is generated [worker #2, session #18oi4]: http://localhost:59068/wallaby_sandbox2.html\n',
    '2021-03-12T23:25:45.913Z chromeRunner Prepared sandbox [worker #0, session #97s3d]\n',
    '2021-03-12T23:25:45.913Z chromeRunner Prepared sandbox [worker #1, session #cfahp]\n',
    '2021-03-12T23:25:45.913Z chromeRunner Prepared sandbox [worker #2, session #18oi4]\n',
    '2021-03-12T23:25:45.913Z workers [worker #0, session #97s3d] Running tests in sandbox\n',
    '2021-03-12T23:25:45.915Z workers [worker #1, session #cfahp] Running tests in sandbox\n',
    '2021-03-12T23:25:45.915Z workers [worker #2, session #18oi4] Running tests in sandbox\n',
    '2021-03-12T23:25:46.164Z workers Sandbox (active) [97s3d] error: process is not defined\n',
    '2021-03-12T23:25:46.167Z workers Failed to map the stack to user code, entry message: process is not defined, stack: ReferenceError: process is not defined\n' +
      '    at Object.window.__moduleBundler.modules../node_modules/react/index.js (http://localhost:59068/____wallaby-bundle.js?1615591545899&wallabyFileId=bundle:484:1)\n' +
      '    at window.__moduleBundler.require (http://localhost:59068/____wallaby-webpack.js?1615591545891:24:16)\n' +
      '    at Module.window.__moduleBundler.modules../src/calculator.ts (http://localhost:59068/____wallaby-bundle.js?1615591545899&wallabyFileId=bundle:7:63)\n' +
      '    at window.__moduleBundler.require (http://localhost:59068/____wallaby-webpack.js?1615591545891:24:16)\n' +
      '    at Module.window.__moduleBundler.modules../test/calculatorSpec.ts (http://localhost:59068/test/calculatorSpec.ts.wbp.js?1615591545740&wallabyFileId=2:3:73)\n' +
      '    at Object.window.__moduleBundler.require (http://localhost:59068/____wallaby-webpack.js?1615591545891:24:16)\n' +
      '    at http://localhost:59068/____wallaby-webpack-bootstrapper.js?1615591545891:18:36\n' +
      '    at http://localhost:59068/__wallaby__/tracer.js:15:12377\n' +
      '    at Array.<anonymous> (http://local\n',
    '2021-03-12T23:25:46.168Z workers [97s3d] Loaded 0 test(s)\n',
    '2021-03-12T23:25:46.173Z workers [97s3d] Run 0 test(s), skipped 0 test(s)\n',
    '2021-03-12T23:25:46.176Z workers [97s3d] Sandbox is responsive, closing it\n',
    '2021-03-12T23:25:46.182Z workers Sandbox (active) [cfahp] error: Uncaught TypeError: __webpack_require__.nmd is not a function\n',
    '2021-03-12T23:25:46.183Z workers Failed to map the stack to user code, entry message: Uncaught TypeError: __webpack_require__.nmd is not a function, stack: TypeError: __webpack_require__.nmd is not a function\n' +
      '    at Object.window.__moduleBundler.modules../node_modules/lodash/isBuffer.js (http://localhost:59068/____wallaby-bundle.js?1615591545899&wallabyFileId=bundle:2944:192)\n' +
      '    at window.__moduleBundler.require (http://localhost:59068/____wallaby-webpack.js?1615591545891:24:16)\n' +
      '    at Object.window.__moduleBundler.modules../node_modules/lodash/_arrayLikeKeys.js (http://localhost:59068/____wallaby-bundle.js?1615591545899&wallabyFileId=bundle:4396:16)\n' +
      '    at window.__moduleBundler.require (http://localhost:59068/____wallaby-webpack.js?1615591545891:24:16)\n' +
      '    at Object.window.__moduleBundler.modules../node_modules/lodash/keys.js (http://localhost:59068/____wallaby-bundle.js?1615591545899&wallabyFileId=bundle:4020:156)\n' +
      '    at window.__moduleBundler.require (http://localhost:59068/____wallaby-webpack.js?1615591545891:24:16)\n' +
      '    at Object.window.__moduleBundler.modules../node_modules/lodash/_getAllKeys.js (http://localhost:59068/____wallaby-bundle.js?1615591545899&\n',
    '2021-03-12T23:25:46.184Z workers [cfahp] Loaded 0 test(s)\n',
    '2021-03-12T23:25:46.190Z workers [cfahp] Run 0 test(s), skipped 0 test(s)\n',
    '2021-03-12T23:25:46.195Z workers [cfahp] Sandbox is responsive, closing it\n',
    "2021-03-12T23:25:46.196Z workers Sandbox (active) [18oi4] error: Uncaught TypeError: Cannot read property 'Symbol' of undefined\n",
    "2021-03-12T23:25:46.197Z workers Failed to map the stack to user code, entry message: Uncaught TypeError: Cannot read property 'Symbol' of undefined, stack: TypeError: Cannot read property 'Symbol' of undefined\n" +
      '    at Object.window.__moduleBundler.modules../node_modules/has-symbols/index.js (http://localhost:59068/____wallaby-bundle.js?1615591545899&wallabyFileId=bundle:395:40)\n' +
      '    at window.__moduleBundler.require (http://localhost:59068/____wallaby-webpack.js?1615591545891:24:16)\n' +
      '    at Module.window.__moduleBundler.modules../test/symbolNotDefinedErrorSpec.ts (http://localhost:59068/test/symbolNotDefinedErrorSpec.ts.wbp.js?1615591545758&wallabyFileId=4:2:69)\n' +
      '    at Object.window.__moduleBundler.require (http://localhost:59068/____wallaby-webpack.js?1615591545891:24:16)\n' +
      '    at http://localhost:59068/____wallaby-webpack-bootstrapper.js?1615591545891:18:36\n' +
      '    at http://localhost:59068/__wallaby__/tracer.js:15:12377\n' +
      '    at Array.<anonymous> (http://localhost:59068/__wallaby__/tracer.js:14:10312)\n' +
      '    at WebSocket.t._receiver.onopen (http://localhost:59068/__wallaby__/tracer.js:14:3101)\n',
    '2021-03-12T23:25:46.200Z workers [18oi4] Loaded 0 test(s)\n',
    '2021-03-12T23:25:46.208Z workers [18oi4] Run 0 test(s), skipped 0 test(s)\n',
    '2021-03-12T23:25:46.210Z workers [18oi4] Sandbox is responsive, closing it\n',
    '2021-03-12T23:25:46.211Z workers Merging parallel test run results\n',
    '2021-03-12T23:25:46.212Z project Test run finished\n',
    '2021-03-12T23:25:46.213Z project Processed console.log entries\n',
    '2021-03-12T23:25:46.213Z project Processed loading sequences\n',
    '2021-03-12T23:25:46.213Z project Processed executed tests\n',
    '2021-03-12T23:25:46.214Z project Processed code coverage\n',
    '2021-03-12T23:25:46.223Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by NikGovorov** [comment]
Hi @greyepoxy,

First of all thanks for the detailed bug report. Issues related to `nmdNotDefinedErrorSpec.ts` and `symbolNotDefinedErrorSpec.ts` are fixed and the fix is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

RE: `process.env.NODE_ENV === 'production'`, Wallaby runs Webpack with `none` [mode](https://webpack.js.org/configuration/mode) hence you need to add `DefinePlugin` to your config manually:
```javascript
const webpack = require('webpack');

module.exports = config = {
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': '"development"'
    })
  ],
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: /node_modules/,
        use: {
          loader: 'ts-loader',
          options: {
            transpileOnly: true
          }
        }
      }
    ]
  },
  resolve: {
    extensions: ['.ts', '.js']
  },
};
```

**Comment by greyepoxy** [comment]
😮 thanks so much for the fast turn around! I tested it and the new version of core seems to be working.

**Comment by NikGovorov** [comment]
Starting from [1.0.1097](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). we inject `DefinePlugin` to configuration automatically so we could support many npm packages that use `process.env.NODE_ENV === 'production'` condition out of box.
