### ISSUE TITLE
Error: Wallaby Webpack render error: expecting chunks.size of 1, instead of 8

### ISSUE THREAD

**Issue by jljorgenson18** [wallabyjs/public#2674]
### Issue description or question

I just updated to Webpack v5 (as well as upgrading associated loaders and plugins) and I just started getting this error.

`Error: Wallaby Webpack render error: expecting chunks.size of 1, instead of 8`

### Wallaby diagnostics report

Note: I deleted the package.json section to keep certain aspects of the project private. I can list versions as necessary, but the big version that is relevant is that I just updated to Webpack v5.

```js
{
  editorVersion: '1.54.3',
  pluginVersion: '1.0.275',
  editorType: 'VSCode',
  osVersion: 'darwin 20.3.0',
  nodeVersion: 'v12.10.0',
  coreVersion: '1.0.1053',
  checksum: 'ZDJlYzFiNTE4YzgwMTNiMGY3MWJjNDRjNDdlNWQwYjEsMTY0NDg4MzIwMDAwMCww',
  config: {
    files: [
      { pattern: 'node_modules/react/umd/react.development.js', instrument: false, ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'node_modules/react-dom/umd/react-dom.development.js', instrument: false, ignore: false, trigger: true, load: true, order: 2 },
      { pattern: 'node_modules/yjs/y.js', instrument: false, ignore: false, trigger: true, load: true, order: 3 },
      { pattern: 'node_modules/chai/chai.js', instrument: false, ignore: false, trigger: true, load: true, order: 4 },
      { pattern: 'node_modules/sinon/pkg/sinon-no-sourcemaps.js', instrument: false, ignore: false, trigger: true, load: true, order: 5 },
      { pattern: 'images/**/*', instrument: false, load: false, binary: true, ignore: false, trigger: true, order: 6 },
      { pattern: 'tests/**/*.+(css|less|scss|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 7 },
      { pattern: 'tests/auxiliary/**/*', instrument: true, load: false, ignore: false, trigger: true, order: 8 },
      { pattern: 'tests/resources/**/*', instrument: false, load: false, ignore: false, trigger: true, order: 9 },
      { pattern: 'tests/qa/resources/**/*', instrument: false, load: false, binary: true, ignore: false, trigger: true, order: 10 },
      { pattern: 'tests/images/**/*', instrument: false, load: false, binary: true, ignore: false, trigger: true, order: 11 },
      { pattern: 'tests/setup.ts', instrument: true, load: false, ignore: false, trigger: true, order: 12 },
      { pattern: 'tests/wallabySetup.js', instrument: true, load: false, ignore: false, trigger: true, order: 13 },
      { pattern: 'src/**/*.+(css|less|scss|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 14 },
      { pattern: 'src/apps/uno/**/*', instrument: false, load: false, ignore: false, trigger: true, order: 15 },
      { pattern: 'src/**/*', instrument: true, load: false, ignore: false, trigger: true, order: 16 }
    ],
    tests: [
      { pattern: 'tests/unit/**/*', load: false, ignore: false, trigger: true, test: true, order: 17 },
      { pattern: 'tests/sys/peso/**/*', load: false, ignore: false, trigger: true, test: true, order: 18 },
      { pattern: 'tests/qa/peso/**/*', load: false, ignore: false, trigger: true, test: true, order: 19 }
    ],
    testFramework: { version: 'mocha@3.2.0', configurator: 'mocha@2.0.1', reporter: 'mocha@2.0.1', starter: 'mocha@2.0.1' },
    env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    debug: true,
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    addModifiedTestFileToExclusiveTestRun: true,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: '/* eslint-disable import/no-extraneous-dependencies */\n' +
      "process.env.NODE_ENV = 'wallaby';\n" +
      'process.env.SKIP_SLOW_TESTS = true;\n' +
      "const path = require('path');\n" +
      "const webpack = require('webpack');\n" +
      "const webpackConfig = require('./webpack.config.js');\n" +
      '// // For helping svg-sprite-loader out (https://github.com/wallabyjs/public/issues/2061)\n' +
      'require.main.paths.push(__dirname);\n' +
      "require.main.paths.push(path.join(__dirname, 'node_modules'));\n" +
      'require.main._wallabyPathsAdded = true;\n' +
      '\n' +
      'const getWallabyWebpackConfig = () => {\n' +
      '    const wallabyWebpackConfig = {\n' +
      '        ...webpackConfig[0],\n' +
      '        devtool: undefined,\n' +
      "        // This helps speed up the build so we don't add these files to the bundle each time\n" +
      '        externals: {\n' +
      '            // Use external version of React and ReactDOM\n' +
      "            react: 'React',\n" +
      "            'react-dom': 'ReactDOM',\n" +
      "            yjs: 'Y',\n" +
      "            chai: 'chai',\n" +
      "            sinon: 'sinon'\n" +
      '        }\n' +
      '    };\n' +
      '    delete wallabyWebpackConfig.entry;\n' +
      '    delete wallabyWebpackConfig.watchOptions;\n' +
      '    delete wallabyWebpackConfig.output;\n' +
      '    delete wallabyWebpackConfig.optimization;\n' +
      '    const allowedPlugins = {\n' +
      '        ProvidePlugin: true,\n' +
      '        DefinePlugin: true,\n' +
      '        IgnorePlugin: true,\n' +
      '        CopyPlugin: true\n' +
      '    };\n' +
      '    wallabyWebpackConfig.plugins = wallabyWebpackConfig.plugins.filter(\n' +
      '        plugin => allowedPlugins[plugin.constructor.name]\n' +
      '    );\n' +
      "    wallabyWebpackConfig.plugins.push(new webpack.NormalModuleReplacementPlugin(/\\.less$/, 'node-noop'));\n" +
      "    wallabyWebpackConfig.resolve.alias.tests = path.join(__dirname, 'tests');\n" +
      '    return wallabyWebpackConfig;\n' +
      '};\n' +
      '\n' +
      '/**\n' +
      ' * NOTES:\n' +
      ' *\n' +
      ' * If you get an OOM error, try executing this `launchctl setenv NODE_OPTIONS --max_old_space_size=8192`\n' +
      ' * in your console, then restart your text editor (https://github.com/wallabyjs/public/issues/2618 for reference)\n' +
      ' */\n' +
      '\n' +
      'module.exports = wallaby => {\n' +
      '    // // For helping svg-sprite-loader out (https://github.com/wallabyjs/public/issues/2061)\n' +
      '    if (!require.main._wallabyPathsAdded) {\n' +
      '        require.main.paths.push(wallaby.localProjectDir);\n' +
      "        require.main.paths.push(path.join(wallaby.localProjectDir, 'node_modules'));\n" +
      '        require.main._wallabyPathsAdded = true;\n' +
      '    }\n' +
      '    return {\n' +
      '        files: [\n' +
      '            // Files we want loaded via script tag for performance reasons\n' +
      "            { pattern: 'node_modules/react/umd/react.development.js', instrument: false },\n" +
      "            { pattern: 'node_modules/react-dom/umd/react-dom.development.js', instrument: false },\n" +
      "            { pattern: 'node_modules/yjs/y.js', instrument: false },\n" +
      "            { pattern: 'node_modules/chai/chai.js', instrument: false },\n" +
      "            { pattern: 'node_modules/sinon/pkg/sinon-no-sourcemaps.js', instrument: false },\n" +
      '            // Extra stuff\n' +
      "            { pattern: 'images/**/*', instrument: false, load: false, binary: true },\n" +
      '            // Test Files\n' +
      "            { pattern: 'tests/**/*.+(css|less|scss|svg)', instrument: false, load: false },\n" +
      "            { pattern: 'tests/auxiliary/**/*', instrument: true, load: false },\n" +
      "            { pattern: 'tests/resources/**/*', instrument: false, load: false },\n" +
      "            { pattern: 'tests/qa/resources/**/*', instrument: false, load: false, binary: true },\n" +
      "            { pattern: 'tests/images/**/*', instrument: false, load: false, binary: true },\n" +
      "            { pattern: 'tests/setup.ts', instrument: true, load: false },\n" +
      "            { pattern: 'tests/wallabySetup.js', instrument: true, load: false },\n" +
      '            // Primary Code\n' +
      "            { pattern: 'src/**/*.+(css|less|scss|svg)', instrument: false, load: false },\n" +
      "            { pattern: 'src/apps/uno/**/*', instrument: false, load: false }, // Speed up the build by not instrumenting uno code\n" +
      "            { pattern: 'src/**/*', instrument: true, load: false }\n" +
      '        ],\n' +
      '\n' +
      '        tests: [\n' +
      "            { pattern: 'tests/unit/**/*', load: false },\n" +
      "            { pattern: 'tests/sys/peso/**/*', load: false },\n" +
      "            { pattern: 'tests/qa/peso/**/*', load: false }\n" +
      '        ],\n' +
      '\n' +
      "        testFramework: 'mocha',\n" +
      '\n' +
      '        env: {\n' +
      "            kind: 'chrome'\n" +
      '            /** Uncomment these params to debug weird Wallaby issues in a browser instance */\n' +
      '            // params: {\n' +
      "            //     runner: '--disable-gpu'\n" +
      '            // },\n' +
      '            // keepTabsOpened: true\n' +
      '        },\n' +
      '\n' +
      '        postprocessor: wallaby.postprocessors.webpack(getWallabyWebpackConfig(), {\n' +
      "            setupFiles: ['tests/wallabySetup.js']\n" +
      '        }),\n' +
      '\n' +
      '        debug: true,\n' +
      '\n' +
      '        setup() {\n' +
      '            mocha.setup({ timeout: 20000 });\n' +
      "            EN.listenTo('ready', () => window.__moduleBundler.loadTests());\n" +
      '        }\n' +
      '    };\n' +
      '};\n'
  },
  fs: { numberOfFiles: 1848 },
  debug: [
    '2021-03-29T16:55:59.875Z project Wallaby Node version: v12.10.0\n',
    '2021-03-29T16:55:59.876Z project Wallaby config: <homeDir>/projects/uno/wallaby.js\n',
    '2021-03-29T16:56:01.374Z fs File system scan has finished by timeout\n',
    '2021-03-29T16:56:01.395Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.275/projects/7634f57fffed454d\n',
    '2021-03-29T16:56:01.470Z uiService Listening port 51235\n',
    '2021-03-29T16:56:01.480Z project Config file change detected, invalidating local cache\n',
    '2021-03-29T16:56:01.588Z workers Parallelism for initial run: 10, for regular run: 5\n',
    '2021-03-29T16:56:01.589Z workers Starting run worker instance #0\n',
    '2021-03-29T16:56:01.589Z workers Starting run worker instance #1\n',
    '2021-03-29T16:56:01.589Z workers Starting run worker instance #2\n',
    '2021-03-29T16:56:01.589Z workers Starting run worker instance #3\n',
    '2021-03-29T16:56:01.589Z workers Starting run worker instance #4\n',
    '2021-03-29T16:56:01.589Z workers Starting run worker instance #5\n',
    '2021-03-29T16:56:01.589Z workers Starting run worker instance #6\n',
    '2021-03-29T16:56:01.589Z workers Starting run worker instance #7\n',
    '2021-03-29T16:56:01.589Z workers Starting run worker instance #8\n',
    '2021-03-29T16:56:01.589Z workers Starting run worker instance #9\n',
    '2021-03-29T16:56:01.591Z workers Web server is listening at 51488\n',
    '2021-03-29T16:56:01.595Z project Stopping process pool\n',
    '2021-03-29T16:56:01.595Z project File cache is up-to-date, starting full test run\n',
    '2021-03-29T16:56:01.597Z project Running postprocessor\n',
    '2021-03-29T16:56:01.613Z postprocessor Processing started.\n',
    '2021-03-29T16:56:01.614Z postprocessor Initializing.\n',
    '2021-03-29T16:56:01.615Z postprocessor Initializing entry.\n',
    '2021-03-29T16:56:01.615Z postprocessor Sanitizing configuration.\n',
    '2021-03-29T16:56:01.616Z postprocessor Adjusting configuration.\n',
    '2021-03-29T16:56:01.616Z postprocessor Creating compiler.\n',
    '2021-03-29T16:56:01.969Z postprocessor Customizing compiler.\n',
    '2021-03-29T16:56:01.969Z postprocessor Compilation started.\n',
    '2021-03-29T16:56:03.521Z workers Started run worker instance (immediate) #0\n',
    '2021-03-29T16:56:03.522Z workers Started run worker instance (immediate) #1\n',
    '2021-03-29T16:56:03.522Z workers Started run worker instance (immediate) #2\n',
    '2021-03-29T16:56:03.522Z workers Started run worker instance (immediate) #3\n',
    '2021-03-29T16:56:03.522Z workers Started run worker instance (immediate) #4\n',
    '2021-03-29T16:56:03.522Z workers Started run worker instance (immediate) #5\n',
    '2021-03-29T16:56:03.522Z workers Started run worker instance (immediate) #6\n',
    '2021-03-29T16:56:03.522Z workers Started run worker instance (immediate) #7\n',
    '2021-03-29T16:56:03.522Z workers Started run worker instance (immediate) #8\n',
    '2021-03-29T16:56:03.522Z workers Started run worker instance (immediate) #9\n',
    '2021-03-29T16:56:44.562Z postprocessor Compilation finished.\n',
    '2021-03-29T16:56:44.564Z project Error: Wallaby Webpack render error: expecting chunks.size of 1, instead of 8\n' +
      '    at t._renderModule (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.275/wallabyd826ec/server.js:22:10456)\n' +
      '    at t.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.275/wallabyd826ec/server.js:21:19776)\n' +
      '    at n (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.275/wallabyd826ec/server.js:21:15678)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.275/wallabyd826ec/server.js:21:14973)\n' +
      '    at o (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.275/wallabyd826ec/server.js:21:14732)\n',
    '2021-03-29T16:56:44.566Z project Test run finished\n',
    '2021-03-29T16:56:44.566Z project Test run data re-queued\n'
  ]
}
```

**Comment by smcenlly** [comment]
Could you please provide us with your webpack configuration (`webpack.config.js`)?

**Comment by jljorgenson18** [comment]
@smcenlly Not sure if I can. Is there a specific piece I can give you? This seems like it could be related to the output and optimization configs.

**Comment by jljorgenson18** [comment]
Actually I realized I completely delete the optimization and output sections when integrating with Wallaby 🤦🏻

```
const getWallabyWebpackConfig = () => {
    const wallabyWebpackConfig = {
        ...webpackConfig[0],
        devtool: undefined,
        // This helps speed up the build so we don't add these files to the bundle each time
        externals: {
            // Use external version of React and ReactDOM
            react: 'React',
            'react-dom': 'ReactDOM',
            yjs: 'Y',
            chai: 'chai',
            sinon: 'sinon'
        }
    };
    delete wallabyWebpackConfig.entry;
    delete wallabyWebpackConfig.watchOptions;
    delete wallabyWebpackConfig.output;
    delete wallabyWebpackConfig.optimization;
    const allowedPlugins = {
        ProvidePlugin: true,
        DefinePlugin: true,
        IgnorePlugin: true,
        CopyPlugin: true
    };
    wallabyWebpackConfig.plugins = wallabyWebpackConfig.plugins.filter(
        plugin => allowedPlugins[plugin.constructor.name]
    );
    wallabyWebpackConfig.plugins.push(new webpack.NormalModuleReplacementPlugin(/\.less$/, 'node-noop'));
    wallabyWebpackConfig.resolve.alias.tests = path.join(__dirname, 'tests');
    return wallabyWebpackConfig;
};
```

**Comment by smcenlly** [comment]
Is it working for you now?

**Comment by jljorgenson18** [comment]
As of v1.0.1053, I'm still seeing the same error.

**Comment by smcenlly** [comment]
OK - thanks, we were not sure given your comment above:

> Actually I realized I completely delete the optimization and output sections when integrating with Wallaby 🤦🏻

---

For us to try and work out what's going on we're going to need a bit more information. Can you please provide us with:

1. the sanitized version of your package.json dependencies (just remove any non-public package you are using).
2. as much of your webpack config as you can provide

If that isn't enough information to reproduce your issue, we're going to have to ask you to create a sample repo for us that has the same problem but none of your proprietary code. Let's see how we go with what you give us with (1) and (2) first.

**Comment by smcenlly** [comment]
We have made a few changes that we think may fix your problem. These changes are available in Wallaby core v1.0.1054. Please update to the latest version and try our changes. If it doesn't work, please provide the details that we requested above.

**Comment by jljorgenson18** [comment]
That seems to have fixed this issue! That being said, I'm seeing numerous test failures that now don't make a ton of sense. I can dig into those and file separate issues if needed. Thank you!

**Comment by smcenlly** [comment]
Yes, please file separate issues. We will likely need a bit more detail re: your webpack configuration to understand what's going on.
