### ISSUE TITLE
File instrumented even if prohibited

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#2714]
### Issue description or question

Hi, I have an `extendExpect` file, where I define my own matchers. I do not want to instrument this file as I do not wan that stact trace to appear in the test output. Is this possible? Currently I see this in my output window:

```
      at check ​src/lib/extendExpect.ts:42:4​
      at Object.toCompileTo ​src/lib/extendExpect.ts:59:4​
      at Context.<anonymous> ​src/compiler/tests/expressions.errors.test.ts:17:2
``` 

### Wallaby diagnostics report

```
{
  editorVersion: '1.56.2',
  pluginVersion: '1.0.292',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.19041',
  nodeVersion: 'v14.16.1',
  coreVersion: '1.0.1076',
  checksum: 'NjkzYWE3YWU0NTRjODYwOWZkYzAwMTBjMjdiNmIxOTIsMTYzODkyMTYwMDAwMCww',
  config: {
    files: [
      { pattern: 'tsconfig.json', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: 'src/**/*.ts', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: 'src/**/*.test.ts', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: 'src/lib/extendExpect.ts', instrument: false, load: true, ignore: false, trigger: true, order: 3 }
    ],
    tests: [ { pattern: 'src/**/*.test.ts', ignore: false, trigger: true, load: true, test: true, order: 4 } ],
    env: {
      type: 'node',
      NODE_ENV: 'test',
      params: {},
      runner: 'C:\\Program Files\\nodejs\\node.exe',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    testFramework: { version: 'mocha@2.1.0', configurator: 'mocha@2.1.0', reporter: 'mocha@2.1.0', starter: 'mocha@2.1.0' },
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    addModifiedTestFileToExclusiveTestRun: true,
    compilers: { '**/*.?(lit)coffee?(.md)': [Function (anonymous)] },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: undefined,
    symlinkNodeModules: undefined,
    configCode: '// @ts-nocheck\r\n' +
      '// eslint-disable-next-line @typescript-eslint/no-var-requires\r\n' +
      '\r\n' +
      'module.exports = function (wallaby) {\r\n' +
      '  return {\r\n' +
      '    files: [\r\n' +
      "      'tsconfig.json',\r\n" +
      "      'src/**/*.ts',\r\n" +
      "      '!src/**/*.test.ts',\r\n" +
      '      {\r\n' +
      "        pattern: 'src/lib/extendExpect.ts',\r\n" +
      '        instrument: false,\r\n' +
      '        load: true\r\n' +
      '      }\r\n' +
      '    ],\r\n' +
      "    tests: ['src/**/*.test.ts'],\r\n" +
      '    env: {\r\n' +
      "      type: 'node',\r\n" +
      "      NODE_ENV: 'test'\r\n" +
      '    },\r\n' +
      "    testFramework: 'mocha',\r\n" +
      '    setup() {\r\n' +
      '      const mocha = wallaby.testFramework;\r\n' +
      "      mocha.suite.on('pre-require', function () {\r\n" +
      '        // use tsconfig paths\r\n' +
      '        if (!global._tsconfigPathsRegistered) {\r\n' +
      "          require('tsconfig-paths').register();\r\n" +
      '          global._tsconfigPathsRegistered = true;\r\n' +
      '        }\r\n' +
      '        // extend expect\r\n' +
      "        require(wallaby.projectCacheDir + '/src/lib/extendExpect');\r\n" +
      '      });\r\n' +
      '    }\r\n' +
      '  };\r\n' +
      '};\r\n'
  },
  packageJSON: {
    dependencies: {
      '@types/mocha': '^8.2.1',
      assert: '^2.0.0',
      esbuild: '^0.12.1',
      expect: '^26.6.2',
      'java-ast': '^0.3.0',
      mocha: '^8.3.0',
      'ts-node': '^9.1.1',
      'tsconfig-paths': '^3.9.0',
      typescript: '^4.2.3',
      vega: '^5.20.2'
    },
    devDependencies: {}
  },
  fs: { numberOfFiles: 95 },
  debug: [
    '2021-05-26T00:00:25.879Z project Wallaby Node version: v14.16.1\n',
    '2021-05-26T00:00:25.879Z project Wallaby config: C:\\Users\\tomi\\Projects\\Github\\javatojs\\wallaby.js\n',
    '2021-05-26T00:00:26.061Z project File cache: C:\\Users\\tomi\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.292\\projects\\0f09904702d9fbea\n',
    '2021-05-26T00:00:26.315Z uiService Listening port 51235\n',
    '2021-05-26T00:00:26.359Z workers Parallelism for initial run: 10, for regular run: 5\n',
    '2021-05-26T00:00:26.359Z workers Starting run worker instance #0\n',
    '2021-05-26T00:00:26.360Z workers Starting run worker instance #1\n',
    '2021-05-26T00:00:26.360Z workers Starting run worker instance #2\n',
    '2021-05-26T00:00:26.360Z workers Starting run worker instance #3\n',
    '2021-05-26T00:00:26.360Z workers Starting run worker instance #4\n',
    '2021-05-26T00:00:26.360Z workers Starting run worker instance #5\n',
    '2021-05-26T00:00:26.360Z workers Starting run worker instance #6\n',
    '2021-05-26T00:00:26.360Z workers Starting run worker instance #7\n',
    '2021-05-26T00:00:26.360Z workers Starting run worker instance #8\n',
    '2021-05-26T00:00:26.360Z workers Starting run worker instance #9\n',
    '2021-05-26T00:00:26.366Z workers Web server is listening at 58158\n',
    '2021-05-26T00:00:26.449Z project Stopping process pool\n',
    '2021-05-26T00:00:26.449Z project File cache is up-to-date, starting full test run\n',
    '2021-05-26T00:00:26.452Z project Running postprocessor\n',
    '2021-05-26T00:00:26.467Z postprocessor New TypeScript language service is required\n',
    '2021-05-26T00:00:29.094Z project Postprocessor execution finished\n',
    '2021-05-26T00:00:29.094Z project Test run started; run priority: 3\n',
    '2021-05-26T00:00:29.095Z project Running all tests\n',
    '2021-05-26T00:00:29.099Z workers Starting test run, priority: 3\n',
    '2021-05-26T00:00:29.099Z workers Distributing tests between 10 workers\n',
    '2021-05-26T00:00:29.100Z workers Running tests in parallel\n',
    '2021-05-26T00:00:29.100Z nodeRunner Starting sandbox [worker #0, session #v0i2e]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Starting sandbox [worker #1, session #4hmml]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Starting sandbox [worker #2, session #c9rb1]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Starting sandbox [worker #3, session #5v675]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Starting sandbox [worker #4, session #ichbu]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Starting sandbox [worker #5, session #dt0au]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Starting sandbox [worker #6, session #ivnk5]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Starting sandbox [worker #7, session #lekeg]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Starting sandbox [worker #8, session #2gzdo]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Starting sandbox [worker #9, session #2enbr]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Preparing sandbox [worker #0, session #v0i2e]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Preparing sandbox [worker #1, session #4hmml]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Preparing sandbox [worker #2, session #c9rb1]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Preparing sandbox [worker #3, session #5v675]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Preparing sandbox [worker #4, session #ichbu]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Preparing sandbox [worker #5, session #dt0au]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Preparing sandbox [worker #6, session #ivnk5]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Preparing sandbox [worker #7, session #lekeg]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Preparing sandbox [worker #8, session #2gzdo]\n',
    '2021-05-26T00:00:29.101Z nodeRunner Preparing sandbox [worker #9, session #2enbr]\n',
    '2021-05-26T00:00:29.102Z workers Started run worker instance (delayed) #1\n',
    '2021-05-26T00:00:29.102Z nodeRunner Prepared sandbox [worker #1, session #4hmml]\n',
    '2021-05-26T00:00:29.103Z workers [worker #1, session #4hmml] Running tests in sandbox\n',
    '2021-05-26T00:00:29.104Z workers Started run worker instance (delayed) #2\n',
    '2021-05-26T00:00:29.105Z nodeRunner Prepared sandbox [worker #2, session #c9rb1]\n',
    '2021-05-26T00:00:29.105Z workers [worker #2, session #c9rb1] Running tests in sandbox\n',
    '2021-05-26T00:00:29.105Z workers Started run worker instance (delayed) #7\n',
    '2021-05-26T00:00:29.105Z nodeRunner Prepared sandbox [worker #7, session #lekeg]\n',
    '2021-05-26T00:00:29.105Z workers [worker #7, session #lekeg] Running tests in sandbox\n',
    '2021-05-26T00:00:29.106Z workers Started run worker instance (delayed) #4\n',
    '2021-05-26T00:00:29.106Z nodeRunner Prepared sandbox [worker #4, session #ichbu]\n',
    '2021-05-26T00:00:29.106Z workers [worker #4, session #ichbu] Running tests in sandbox\n',
    '2021-05-26T00:00:29.106Z workers Started run worker instance (delayed) #0\n',
    '2021-05-26T00:00:29.106Z nodeRunner Prepared sandbox [worker #0, session #v0i2e]\n',
    '2021-05-26T00:00:29.106Z workers [worker #0, session #v0i2e] Running tests in sandbox\n',
    '2021-05-26T00:00:29.107Z workers Started run worker instance (delayed) #3\n',
    '2021-05-26T00:00:29.107Z nodeRunner Prepared sandbox [worker #3, session #5v675]\n',
    '2021-05-26T00:00:29.107Z workers [worker #3, session #5v675] Running tests in sandbox\n',
    '2021-05-26T00:00:29.107Z workers Started run worker instance (delayed) #5\n',
    '2021-05-26T00:00:29.107Z nodeRunner Prepared sandbox [worker #5, session #dt0au]\n',
    '2021-05-26T00:00:29.107Z workers [worker #5, session #dt0au] Running tests in sandbox\n',
    '2021-05-26T00:00:29.107Z workers Started run worker instance (delayed) #9\n',
    '2021-05-26T00:00:29.108Z nodeRunner Prepared sandbox [worker #9, session #2enbr]\n',
    '2021-05-26T00:00:29.108Z workers [worker #9, session #2enbr] Running tests in sandbox\n',
    '2021-05-26T00:00:29.108Z workers Started run worker instance (delayed) #6\n',
    '2021-05-26T00:00:29.108Z nodeRunner Prepared sandbox [worker #6, session #ivnk5]\n',
    '2021-05-26T00:00:29.108Z workers [worker #6, session #ivnk5] Running tests in sandbox\n',
    '2021-05-26T00:00:29.108Z workers Started run worker instance (delayed) #8\n',
    '2021-05-26T00:00:29.109Z nodeRunner Prepared sandbox [worker #8, session #2gzdo]\n',
    '2021-05-26T00:00:29.109Z workers [worker #8, session #2gzdo] Running tests in sandbox\n',
    '2021-05-26T00:00:32.640Z workers [4hmml] Loaded 5 test(s)\n',
    '2021-05-26T00:00:32.751Z workers [ivnk5] Loaded 4 test(s)\n',
    '2021-05-26T00:00:32.768Z workers [2enbr] Loaded 2 test(s)\n',
    '2021-05-26T00:00:32.810Z workers [2enbr] Test executed: packages are not implemented\n',
    '2021-05-26T00:00:32.811Z workers [2enbr] Test executed: imports are not implemented\n',
    '2021-05-26T00:00:32.866Z workers [v0i2e] Loaded 3 test(s)\n',
    '2021-05-26T00:00:32.921Z workers [4hmml] Test executed: fails on syntax errors\n',
    '2021-05-26T00:00:32.933Z workers [2enbr] Run 2 test(s), skipped 0 test(s)\n',
    '2021-05-26T00:00:32.935Z workers [5v675] Loaded 3 test(s)\n',
    '2021-05-26T00:00:32.938Z workers [2enbr] Sandbox is responsive, closing it\n',
    '2021-05-26T00:00:32.939Z workers [5v675] Test executed: parses simple expression\n',
    '2021-05-26T00:00:32.940Z workers [5v675] Test executed: parses unary expressions\n',
    '2021-05-26T00:00:32.945Z workers [5v675] Test executed: parses binary expressions\n',
    '2021-05-26T00:00:32.948Z workers [2gzdo] Loaded 4 test(s)\n',
    '2021-05-26T00:00:32.985Z workers [ichbu] Loaded 3 test(s)\n',
    '2021-05-26T00:00:32.990Z workers [v0i2e] Test executed: transpiles a class\n',
    '2021-05-26T00:00:32.999Z workers [dt0au] Loaded 6 test(s)\n',
    '2021-05-26T00:00:33.014Z workers [4hmml] Test executed: class / interface modifiers are not implemented\n',
    '2021-05-26T00:00:33.074Z workers [4hmml] Test executed: class can have only one constructor\n',
    '2021-05-26T00:00:33.075Z workers [ichbu] Test executed: error on wrong parameter type assignment\n',
    '2021-05-26T00:00:33.075Z workers [4hmml] Test executed: class can extend only a known type\n',
    '2021-05-26T00:00:33.078Z workers [4hmml] Test executed: generic classes are not supported\n',
    '2021-05-26T00:00:33.090Z workers [ivnk5] Test executed: transpiles an interface\n',
    '2021-05-26T00:00:33.095Z workers [lekeg] Loaded 3 test(s)\n',
    '2021-05-26T00:00:33.104Z workers [5v675] Run 3 test(s), skipped 0 test(s)\n',
    '2021-05-26T00:00:33.115Z workers [5v675] Sandbox is responsive, closing it\n',
    '2021-05-26T00:00:33.154Z workers [lekeg] Test executed: error on non existing method properties\n',
    '2021-05-26T00:00:33.189Z workers [4hmml] Run 5 test(s), skipped 0 test(s)\n',
    '2021-05-26T00:00:33.192Z workers [4hmml] Sandbox is responsive, closing it\n',
    '2021-05-26T00:00:33.199Z workers [dt0au] Test executed: detects integer division in literals\n',
    '2021-05-26T00:00:33.204Z workers [c9rb1] Loaded 2 test(s)\n',
    '2021-05-26T00:00:33.221Z workers [lekeg] Test executed: method must return a value\n',
    '2021-05-26T00:00:33.227Z workers [lekeg] Test executed: method must return a correct value\n',
    '2021-05-26T00:00:33.240Z workers [2gzdo] Test executed: transpiles a method declaration with no properties\n',
    '2021-05-26T00:00:33.269Z workers [v0i2e] Test executed: transpiles inherited class\n',
    '2021-05-26T00:00:33.282Z workers [v0i2e] Test executed: can assign values\n',
    '2021-05-26T00:00:33.285Z workers [ichbu] Test executed: does not allow to assign incorrect type to incorrect type\n',
    '2021-05-26T00:00:33.291Z workers [ichbu] Test executed: check for unknown types\n',
    '2021-05-26T00:00:33.350Z workers [2gzdo] Test executed: test method properties\n',
    '2021-05-26T00:00:33.368Z workers [ivnk5] Test executed: error on wrong parameter type assignment\n',
    '2021-05-26T00:00:33.374Z workers [ivnk5] Test executed: error on wrong parameter type assignment\n',
    '2021-05-26T00:00:33.376Z workers [ivnk5] Test executed: error on wrong parameter type assignment\n',
    '2021-05-26T00:00:33.382Z workers [c9rb1] Test executed: transpiles a class with fields\n',
    '2021-05-26T00:00:33.393Z workers [c9rb1] Test executed: transpiles a class field declaration\n',
    '2021-05-26T00:00:33.424Z workers [lekeg] Run 3 test(s), skipped 0 test(s)\n',
    '2021-05-26T00:00:33.434Z workers [lekeg] Sandbox is responsive, closing it\n',
    '2021-05-26T00:00:33.440Z workers [2gzdo] Test executed: method return type\n',
    '2021-05-26T00:00:33.445Z workers [2gzdo] Test executed: test method body\n',
    '2021-05-26T00:00:33.489Z workers [dt0au] Test executed: ignores integer division when cast to non integer\n',
    '2021-05-26T00:00:33.508Z workers [v0i2e] Run 3 test(s), skipped 0 test(s)\n',
    '2021-05-26T00:00:33.512Z workers [v0i2e] Sandbox is responsive, closing it\n',
    '2021-05-26T00:00:33.512Z workers [ichbu] Run 3 test(s), skipped 0 test(s)\n',
    '2021-05-26T00:00:33.516Z workers [ichbu] Sandbox is responsive, closing it\n',
    '2021-05-26T00:00:33.538Z workers [ivnk5] Run 4 test(s), skipped 0 test(s)\n',
    '2021-05-26T00:00:33.541Z workers [ivnk5] Sandbox is responsive, closing it\n',
    '2021-05-26T00:00:33.544Z workers [c9rb1] Run 2 test(s), skipped 0 test(s)\n',
    '2021-05-26T00:00:33.548Z workers [c9rb1] Sandbox is responsive, closing it\n',
    '2021-05-26T00:00:33.550Z workers [2gzdo] Run 4 test(s), skipped 0 test(s)\n',
    '2021-05-26T00:00:33.552Z workers [2gzdo] Sandbox is responsive, closing it\n',
    '2021-05-26T00:00:33.573Z workers [dt0au] Test executed: detects integer division in variables\n',
    '2021-05-26T00:00:33.625Z workers [dt0au] Test executed: detects integer division in variables with class access\n',
    '2021-05-26T00:00:33.631Z workers [dt0au] Test executed: adds this. automatically to fields and methods\n',
    '2021-05-26T00:00:33.633Z workers [dt0au] Test executed: detects integer division in methods\n',
    '2021-05-26T00:00:33.675Z workers [dt0au] Run 6 test(s), skipped 0 test(s)\n',
    '2021-05-26T00:00:33.677Z workers [dt0au] Sandbox is responsive, closing it\n',
    '2021-05-26T00:00:33.677Z workers Merging parallel test run results\n',
    '2021-05-26T00:00:33.694Z project Test run finished\n',
    '2021-05-26T00:00:33.695Z project Processed console.log entries\n',
    '2021-05-26T00:00:33.695Z project Processed loading sequences\n',
    '2021-05-26T00:00:33.696Z project Test name duplicate: error on wrong parameter type assignment\n',
    '2021-05-26T00:00:33.696Z project Test name duplicate: error on wrong parameter type assignment\n',
    '2021-05-26T00:00:33.696Z project Processed executed tests\n',
    '2021-05-26T00:00:33.710Z project Processed code coverage\n',
    '2021-05-26T00:00:33.806Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
There're 2 separate issues:
- the file is being instrumented because another file pattern above its definition takes precedence (`'src/**/*.ts'`). if you move the `{ pattern: 'src/lib/extendExpect.ts', instrument: false, load: true }` pattern to be above the `'src/**/*.ts'` pattern, then the `src/lib/extendExpect.ts` will not be instrumented.
- even when the file is not instrumented, it doesn't necessarily mean that it will not be displayed in error stack traces. We have recently introduced a new file pattern property (`hideFromErrorStackTrace`) to control this behaviour:

```
{ pattern: 'src/lib/extendExpect.ts', instrument: false, hideFromErrorStackTrace: true }
```

**Comment by tomitrescak** [comment]
Hello, thanks! No luck though. This is my config:

```
// @ts-nocheck
// eslint-disable-next-line @typescript-eslint/no-var-requires

module.exports = function (wallaby) {
  return {
    files: [
      {
        pattern: 'src/lib/extendExpect.ts',
        instrument: false,
        hideFromErrorStackTrace: true
      },
      'tsconfig.json',
      'src/**/*.ts',
      '!src/**/*.test.ts'
    ],
    tests: ['src/**/*.test.ts'],
    env: {
      type: 'node',
      NODE_ENV: 'test'
    },
    testFramework: 'mocha',
    setup() {
      const mocha = wallaby.testFramework;
      mocha.suite.on('pre-require', function () {
        // use tsconfig paths
        if (!global._tsconfigPathsRegistered) {
          require('tsconfig-paths').register();
          global._tsconfigPathsRegistered = true;
        }
        // extend expect
        require(wallaby.projectCacheDir + '/src/lib/extendExpect');
      });
    }
  };
};
```

And this is still in the console:

```
      at check ​src/lib/extendExpect.ts:48​
      at Object.toCompileCommandsTo ​src/lib/extendExpect.ts:92​
      at Context.<anonymous> ​src/compiler/tests/integerDivision.test.ts:12:2
```

**Comment by tomitrescak** [comment]
I think it has got something to do with the fact that I require it from the cache directory:

```
setup() {
      const mocha = wallaby.testFramework;
      mocha.suite.on('pre-require', function () {
        // use tsconfig paths
        if (!global._tsconfigPathsRegistered) {
          require('tsconfig-paths').register();
          global._tsconfigPathsRegistered = true;
        }
        // extend expect
        require(wallaby.projectCacheDir + '/src/lib/extendExpect');
      });
    }
```

I was not sure how can I call an init file that is in typescript.

**Comment by ArtemGovorov** [comment]
Oh, I have forgotten to mention, please update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), and after the update touch your Wallaby config, or package.json to bust the cache.

**Comment by tomitrescak** [comment]
👍 worked like charm!
