### ISSUE TITLE
Automatic configuration [Error] Automatic Jest configuration error: Cannot find compatible jest-cli module.

### ISSUE THREAD

**Issue by 0x00000002** [wallabyjs/public#2725]
### Issue description or question

I've tried Automatic configuration <project directory> and got `‌[Error] Automatic Jest configuration error: Cannot find compatible jest-cli module.`

I have TS project with Jest.

**babel.config.js:**
```
module.exports = {
    presets: [['@babel/preset-env', { targets: { node: 'current' } }], '@babel/preset-typescript', "babel-preset-jest"],
};
```

**jest.config.js**
```
module.exports = {
    testEnvironment: 'node',
    transformIgnorePatterns: ['node_modules/(?!decoder/.*)'],
    testPathIgnorePatterns: ['deps/'],
    // testPathIgnorePatterns: ['deps/', './*/*.spec.i.*'],
    testMatch: ['./**/*.spec.*'],
};
```

**tsconfig.json":
```
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "declaration": true,
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "baseUrl": "src",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "lib": ["ES6"],
    "isolatedModules": true,
    "noEmit": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "moduleResolution": "node"
  },
  "include": ["./**/*.ts"],
  "exclude": [
    "node_modules",
    "scripts",
    "lambda",
    "dist",
    "deps",
    "serverless.ts"
  ]
}
```

If I try **wallaby.js**
```
process.env.NODE_ENV = 'wallaby';

const babelConfig = JSON.parse(require('fs').readFileSync(require('path').join(__dirname, 'babel.config.js'))).env.test;
babelConfig.presets.push('babel-preset-jest');

module.exports = wallaby => ({
  files: [
    'src/**/*.ts',
    'src/**/*.json',
    '!src/**/*.spec.ts',
    '!src/**/*.spec.i.js'
  ],

  tests: [
    'src/**/*.spec.ts',
    'src/**/*.spec.i.js',
  ],

  // do not cover third-party library
  filesWithNoCoverageCalculated: [
    'src/lib/api/*/routes.ts',
  ],

  hints: {
    ignoreCoverage: /ignore file coverage/
  },

  compilers: {
    '**/*.js*': wallaby.compilers.babel(babelConfig),
    '**/*.ts*': wallaby.compilers.babel(babelConfig) //{ babelrc: true, presets: ['babel-preset-jest'] }
  },

  env: {
    type: 'node'
  },

  trace: true,

  coverageThreshold: {
    global: {
      branches: 50,
      functions: 50,
      lines: 50,
      statements: 50
    }
  },

  testFramework: {
    // the jest configuration file path
    // (relative to project root)
    configFile: './jest.config.wallaby.js'
  },

  runMode: 'onsave'
})
```
I receive error:
```
‌[Error]  
[Error] ----------------------------- 
[Error] CommonJs config loading error 
[Error] ----------------------------- 
[Error]     at Object.<anonymous> (./wallaby.js_o:3:26) 
[Error] ------------------------------ 
[Error] ES module config loading error 
[Error] ------------------------------ 

```

### Wallaby diagnostics report

```
{
  editorVersion: '1.56.2',
  pluginVersion: '1.0.296',
  editorType: 'VSCode',
  osVersion: 'darwin 20.5.0',
  nodeVersion: 'v12.18.3',
  coreVersion: '1.0.1090',
  checksum: 'ZmRlZGNhN2FmY2M1N2RjYWEwZjM5N2ZiMDY3OWU4NDUsMTY1NDU2MDAwMDAwMCww',
  config: {},
  packageJSON: {
    dependencies: {
      '@imtbl/imlogging': '^1.0.33',
      'abi-decoder': '^2.4.0',
      'aws-sdk': '^2.904.0',
      axios: '^0.21.1',
      dotenv: '^9.0.1',
      'fp-ts': '^2.10.5',
      'io-ts': '^2.2.16',
      'reflect-metadata': '^0.1.13',
      shelljs: '^0.8.4',
      'wait-for-event': '^2.0.1',
      web3: '^1.3.5',
      'web3-core': '^1.3.5',
      'web3-core-subscriptions': '^1.3.6',
      'web3-eth-contract': '^1.3.5',
      'web3-utils': '^1.3.5'
    },
    devDependencies: {
      '@babel/core': '^7.14.3',
      '@babel/preset-env': '^7.14.2',
      '@babel/preset-typescript': '^7.13.0',
      '@serverless/typescript': '^2.41.2',
      '@types/aws-lambda': '^8.10.76',
      '@types/jest': '^26.0.23',
      '@types/node': '^15.0.2',
      '@typescript-eslint/eslint-plugin': '^4.24.0',
      '@typescript-eslint/parser': '^4.25.0',
      'babel-jest': '^26.6.3',
      'babel-loader': '^8.2.2',
      'babel-preset-jest': '^27.0.1',
      'cache-loader': '^4.1.0',
      eslint: '^7.27.0',
      'eslint-config-prettier': '^8.3.0',
      'eslint-plugin-fp-ts': '^0.2.1',
      'eslint-plugin-prettier': '^3.4.0',
      'eslint-plugin-simple-import-sort': '^7.0.0',
      'fork-ts-checker-webpack-plugin': '^6.2.10',
      fs: '^0.0.1-security',
      'jest-cli': '^27.0.4',
      path: '^0.12.7',
      prettier: '^2.3.0',
      serverless: '^2.41.2',
      'serverless-dynamodb-local': '^0.2.39',
      'serverless-offline': '^7.0.0',
      'serverless-webpack': '^5.5.0',
      'ts-jest': '^26.5.6',
      'ts-node': '^9.1.1',
      typescript: '^4.2.4',
      webpack: '^5.37.1',
      'webpack-node-externals': '^3.0.0'
    }
  },
  fs: { numberOfFiles: 0 },
  debug: [
    '2021-06-07T01:03:31.390Z angular/cli config Angular CLI not found.\n',
    '2021-06-07T01:03:31.395Z jest/config Error: Cannot find compatible jest-cli module.\n' +
      '    at Object.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:29:22884)\n' +
      '    at n (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:29:8335)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:29:7630)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:29:7539\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:29:7333)\n' +
      '    at Object.loadJest (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:29:21685)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:18:25077\n' +
      '    at n (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:18:29621)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:18:28916)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:18:28825\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at s (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:18:28619)\n' +
      '    at n (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:18:24765)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:18:28296\n' +
      '    at n (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:18:29621)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:18:28916)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:18:28825\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at s (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:18:28619)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:18:28177)\n' +
      '    at Config.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:15:25704)\n' +
      '    at n (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:15:19091)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:15:18386)\n' +
      '    at o (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.296/wallabyeb8bef/server.js:15:18135)\n'
  ]
}
```

**Comment by smcenlly** [comment]
Since you are using `Jest v27`, you will need to use Wallaby's Automatic Configuration instead of the `testFramework: 'jest'` setting.

The reason Wallaby is not working for you is that Jest is not installed as a dependency for your project, instead it is only available as a transitive dependency. You can fix this by running:

```
npm install jest --save-dev
```

**Comment by 0x00000002** [comment]
Yup, it worked!
