### ISSUE TITLE
ERR_REQUIRE_ESM with Node, Mocha, and native ES Modules

### ISSUE THREAD

**Issue by nlindley** [wallabyjs/public#2729]
### Issue description or question

I am trying to run Wallaby with Node.js 14.17.0 and native ES modules. I am receiving the following error in the console.

```
[Error] Runtime error: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ./test/index.test.js 
[Error] require() of ES modules is not supported. 
[Error] require() of ./test/index.test.js from ./node_modules/mocha/lib/esm-utils.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. 
[Error] Instead rename index.test.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ./package.json. 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1085:13) 
[Error]     at Module.load (internal/modules/cjs/loader.js:933:32) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:774:14) 
[Error]     at Module.require (internal/modules/cjs/loader.js:957:19) 
[Error]     at require (internal/modules/cjs/helpers.js:88:18) 
[Error]     at Object.exports.requireOrImport (./node_modules/mocha/lib/esm-utils.js:52:18) 
[Error]     at async Object.exports.loadFilesAsync (./node_modules/mocha/lib/esm-utils.js:71:20)
```

I have created a minimal repo to demonstrate the issue at https://github.com/nlindley/mocha-wallaby-test.

### Wallaby diagnostics report

```
{
  editorVersion: '1.57.0',
  pluginVersion: '1.0.297',
  editorType: 'VSCode',
  osVersion: 'darwin 20.5.0',
  nodeVersion: 'v14.17.0',
  coreVersion: '1.0.1095',
  checksum: 'ODQxMmZjNzFmM2U3Zjc4OTg1MmM1NzljZTg3Zjk1MjcsMTYzOTc4NTYwMDAwMCww',
  config: {
    files: [
      { pattern: 'package.json', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: 'src/**/*.js', ignore: false, trigger: true, load: true, instrument: true, order: 2 }
    ],
    tests: [ { pattern: 'test/**/*.test.js', ignore: false, trigger: true, load: true, test: true, order: 3 } ],
    env: { type: 'node', params: {}, runner: '<homeDir>/.nvm/versions/node/v14.17.0/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    workers: { restart: true, initial: 0, regular: 0, recycle: true },
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    addModifiedTestFileToExclusiveTestRun: true,
    compilers: { '**/*.?(lit)coffee?(.md)': [Function (anonymous)] },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: true,
    testFramework: { version: 'mocha@2.1.0', configurator: 'mocha@2.1.0', reporter: 'mocha@2.1.0', starter: 'mocha@2.1.0' },
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: undefined,
    symlinkNodeModules: true,
    configCode: 'export default () => {\n' +
      '  return {\n' +
      '    files: ["package.json", "src/**/*.js"],\n' +
      '\n' +
      '    tests: ["test/**/*.test.js"],\n' +
      '\n' +
      '    env: {\n' +
      '      type: "node",\n' +
      '    },\n' +
      '\n' +
      '    workers: { restart: true },\n' +
      '  };\n' +
      '};\n'
  },
  packageJSON: { dependencies: {}, devDependencies: { chai: '^4.3.4', mocha: '^9.0.0' } },
  fs: { numberOfFiles: 3 },
  debug: [
    '2021-06-11T16:17:47.254Z project Wallaby Node version: v14.17.0\n',
    '2021-06-11T16:17:47.254Z project Wallaby config: <homeDir>/Code/mocha-wallaby-test/wallaby.js\n',
    '2021-06-11T16:17:48.279Z fs File system scan has finished by timeout\n',
    '2021-06-11T16:17:48.286Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.297/projects/446cc6ec0a4a590e\n',
    '2021-06-11T16:17:48.293Z uiService Listening port 51236\n',
    '2021-06-11T16:17:48.297Z workers Parallelism for initial run: 14, for regular run: 7\n',
    '2021-06-11T16:17:48.298Z workers Starting run worker instance #0\n',
    '2021-06-11T16:17:48.298Z workers Starting run worker instance #1\n',
    '2021-06-11T16:17:48.298Z workers Starting run worker instance #2\n',
    '2021-06-11T16:17:48.298Z workers Starting run worker instance #3\n',
    '2021-06-11T16:17:48.298Z workers Starting run worker instance #4\n',
    '2021-06-11T16:17:48.298Z workers Starting run worker instance #5\n',
    '2021-06-11T16:17:48.298Z workers Starting run worker instance #6\n',
    '2021-06-11T16:17:48.298Z workers Starting run worker instance #7\n',
    '2021-06-11T16:17:48.298Z workers Starting run worker instance #8\n',
    '2021-06-11T16:17:48.298Z workers Starting run worker instance #9\n',
    '2021-06-11T16:17:48.298Z workers Starting run worker instance #10\n',
    '2021-06-11T16:17:48.298Z workers Starting run worker instance #11\n',
    '2021-06-11T16:17:48.298Z workers Starting run worker instance #12\n',
    '2021-06-11T16:17:48.298Z workers Starting run worker instance #13\n',
    '2021-06-11T16:17:48.298Z workers Web server is listening at 60599\n',
    '2021-06-11T16:17:48.354Z project Stopping process pool\n',
    '2021-06-11T16:17:48.354Z project File cache is up-to-date, starting full test run\n',
    '2021-06-11T16:17:48.356Z project Running postprocessor\n',
    '2021-06-11T16:17:48.359Z postprocessor New TypeScript language service is required\n',
    "2021-06-11T16:17:48.359Z postprocessor TypeScript postprocessor will be removed because in 3 project files none were found by patterns: [ '**/*.ts?(x)' ]\n",
    '2021-06-11T16:17:48.362Z project Postprocessor execution finished\n',
    '2021-06-11T16:17:48.362Z project Postprocessor is removed as requested by itself\n',
    '2021-06-11T16:17:48.362Z project Test run started; run priority: 3\n',
    '2021-06-11T16:17:48.362Z project Running all tests\n',
    '2021-06-11T16:17:48.364Z workers Starting test run, priority: 3\n',
    '2021-06-11T16:17:48.364Z nodeRunner Starting sandbox [worker #0, session #yqveu]\n',
    '2021-06-11T16:17:48.365Z nodeRunner Preparing sandbox [worker #0, session #yqveu]\n',
    '2021-06-11T16:17:48.489Z workers Started run worker instance (delayed) #0\n',
    '2021-06-11T16:17:48.490Z nodeRunner Prepared sandbox [worker #0, session #yqveu]\n',
    '2021-06-11T16:17:48.490Z workers [worker #0, session #yqveu] Running tests in sandbox\n',
    '2021-06-11T16:17:48.493Z workers Started run worker instance (delayed) #1\n',
    '2021-06-11T16:17:48.497Z workers Started run worker instance (delayed) #2\n',
    '2021-06-11T16:17:48.504Z workers Started run worker instance (delayed) #3\n',
    '2021-06-11T16:17:48.504Z workers Started run worker instance (delayed) #4\n',
    '2021-06-11T16:17:48.511Z workers Started run worker instance (delayed) #5\n',
    '2021-06-11T16:17:48.514Z workers Started run worker instance (delayed) #6\n',
    '2021-06-11T16:17:48.521Z workers Started run worker instance (delayed) #7\n',
    '2021-06-11T16:17:48.524Z workers Started run worker instance (delayed) #8\n',
    '2021-06-11T16:17:48.529Z workers Started run worker instance (delayed) #9\n',
    '2021-06-11T16:17:48.532Z workers Sandbox (active) [yqveu] error: Must use import to load ES Module: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.297/projects/446cc6ec0a4a590e/instrumented/test/index.test.js\n' +
      'require() of ES modules is not supported.\n' +
      'require() of <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.297/projects/446cc6ec0a4a590e/instrumented/test/index.test.js from <homeDir>/Code/mocha-wallaby-test/node_modules/mocha/lib/esm-utils.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.\n' +
      'Instead rename index.test.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.297/projects/446cc6ec0a4a590e/instrumented/package.json.\n' +
      '\n',
    '2021-06-11T16:17:48.533Z workers Failed to map the stack to user code, entry message: Must use import to load ES Module: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.297/projects/446cc6ec0a4a590e/instrumented/test/index.test.js\n' +
      'require() of ES modules is not supported.\n' +
      'require() of <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.297/projects/446cc6ec0a4a590e/instrumented/test/index.test.js from <homeDir>/Code/mocha-wallaby-test/node_modules/mocha/lib/esm-utils.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.\n' +
      'Instead rename index.test.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.297/projects/446cc6ec0a4a590e/instrumented/package.json.\n' +
      ', stack: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.297/projects/446cc6ec0a4a590e/instrumented/test/index.test.js\n' +
      'require() of ES modules is not supported.\n' +
      'require() of <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.297/projects/446cc6ec0a4a590e/instrumented/test/index.test.js from <homeDir>/Code/mocha-wallaby-test/node_modules/mocha/lib/esm-utils.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.\n' +
      'Instead rename index.test.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.297/projects/446cc6ec0a4a590e/instrumented/package.json.\n' +
      '\n' +
      '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1085:13)\n' +
      '    at Module.load (internal/modules/cjs/loader.js:933:32)\n' +
      '    at Function.Module._load (i\n',
    '2021-06-11T16:17:48.534Z workers Started run worker instance (delayed) #11\n',
    '2021-06-11T16:17:48.535Z workers Started run worker instance (delayed) #10\n',
    '2021-06-11T16:17:48.541Z workers Started run worker instance (delayed) #12\n',
    '2021-06-11T16:17:48.542Z workers Started run worker instance (delayed) #13\n',
    '2021-06-11T16:17:48.639Z workers [yqveu] Run 0 test(s), skipped 0 test(s)\n',
    '2021-06-11T16:17:48.641Z workers [yqveu] Sandbox is responsive, closing it\n',
    '2021-06-11T16:17:48.642Z workers Starting run worker instance #0\n',
    '2021-06-11T16:17:48.643Z project Test run finished\n',
    '2021-06-11T16:17:48.643Z project Processed console.log entries\n',
    '2021-06-11T16:17:48.643Z project Processed loading sequences\n',
    '2021-06-11T16:17:48.643Z project Processed executed tests\n',
    '2021-06-11T16:17:48.644Z project Processed code coverage\n',
    '2021-06-11T16:17:48.651Z project Test run result processed and sent to IDE\n',
    '2021-06-11T16:17:48.775Z workers Started run worker instance (delayed) #0\n'
  ]
}
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem; there was an issue with the latest version of mocha v9 when running on projects using ES6 imports.

This is fixed in the latest version of Wallaby core, `v1.0.1096`. Wallaby should automatically update for you to the version with the fix, but if it does not, please run the VS Code command: `Wallaby.js: Force Core Update`
