### ISSUE TITLE
Failed to initialize wallaby jest with yarn workspaces + nestjs

### ISSUE THREAD

**Issue by ArtemShapovalov** [wallabyjs/public#2731]
### Issue description or question
I am using `yarn workspaces` and have a problem while start Wallaby. I don't have jest-cli in the project node_modules there is only .bin/jest but I have it in the root node_modules

#### Wallaby.js configuration file

```js
const path = require('path');

module.exports = function (wallaby) {
  process.env.NODE_PATH +=
    path.delimiter + path.join(__dirname, 'node_modules') + path.delimiter + path.join(wallaby.projectCacheDir, 'src');

  console.log(process.env.NODE_PATH);

  return {
    // autoDetect: true,

    files: [
      'src/**/*.ts?(x)',
      '!src/**/*.spec.ts?(x)',
    ],

    tests: [
        'src/**/*.spec.ts?(x)',
    ],

    env: {
      type: 'node',
    },

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({
        module: 'commonjs',
      }),
    },

    testFramework: 'jest',

    debug: true,

    setup(wallaby) {},
  };
};

```

#### package.json jest section

```json
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
```

```bash
Failed to initialize wallaby jest.
Error: Cannot find Jest test runner
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by ArtemGovorov** [comment]
Can you please try changing your Wallaby config file to:

```js
module.exports = function (wallaby) {
  return {
    autoDetect: true
  };
};
```
and restarting Wallaby?

**Comment by ArtemShapovalov** [comment]
Thanks, it works

**Comment by ArtemGovorov** [comment]
Awesome, thanks for checking. You may actually delete the wallaby config file, and it should still work for you.
