### ISSUE TITLE
globalThis is not defined in CRA 4.0.3

### ISSUE THREAD

**Issue by nathanvale** [wallabyjs/public#2754]
When using an automatic configuration with Wallaby and CRA 4.0.3 I am hitting this error

```
 ReferenceError: globalThis is not defined 
```

Please see my repo if you need to investigate

https://github.com/nathanvale/jazz-chord-app

### Wallaby diagnostics report

```
{ editorVersion: '1.58.0',
  pluginVersion: '1.0.298',
  editorType: 'VSCode',
  osVersion: 'darwin 20.4.0',
  nodeVersion: 'v10.24.0',
  coreVersion: '1.0.1115',
  checksum: 'OWM2Yzc5NjA5YjE2ZWU2ZWE4OTc2MWFlNjRiZjU1NzMsMTY1ODE4ODgwMDAwMCww',
  config:
   { diagnostics:
      { jest:
         { config:
            { configs:
               [ { automock: false,
                   cache: true,
                   cacheDirectory: '/private/var/folders/mj/zc1nb5pn0bjgkjbjlqyzp2rm0000gn/T/jest_dx',
                   clearMocks: false,
                   coveragePathIgnorePatterns: [ '/node_modules/' ],
                   cwd: '<homeDir>/code/jazz-chord-app',
                   dependencyExtractor: undefined,
                   detectLeaks: undefined,
                   detectOpenHandles: undefined,
                   displayName: undefined,
                   errorOnDeprecated: false,
                   extraGlobals: [],
                   filter: undefined,
                   forceCoverageMatch: [],
                   globalSetup: undefined,
                   globalTeardown: undefined,
                   globals: {},
                   haste: { computeSha1: false, throwOnModuleCollision: false },
                   injectGlobals: true,
                   moduleDirectories: [ 'node_modules' ],
                   moduleFileExtensions: [ 'web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node' ],
                   moduleLoader: undefined,
                   moduleNameMapper: [ [ '^react-native$', 'react-native-web' ], [ '^.+\\.module\\.(css|sass|scss)$', 'identity-obj-proxy' ] ],
                   modulePathIgnorePatterns: [],
                   modulePaths: [],
                   name: '99bdc8f41013d44ad5687f43d8e77a67',
                   prettierPath: 'prettier',
                   resetMocks: true,
                   resetModules: false,
                   resolver: undefined,
                   restoreMocks: false,
                   rootDir: '<homeDir>/code/jazz-chord-app',
                   roots: [ '<homeDir>/code/jazz-chord-app/src' ],
                   runner: 'jest-runner',
                   setupFiles: [ '<homeDir>/code/jazz-chord-app/node_modules/react-app-polyfill/jsdom.js' ],
                   setupFilesAfterEnv: [ '<homeDir>/code/jazz-chord-app/src/setupTests.js' ],
                   skipFilter: false,
                   skipNodeResolution: undefined,
                   slowTestThreshold: 5,
                   snapshotResolver: undefined,
                   snapshotSerializers: [],
                   testEnvironment: '<homeDir>/code/jazz-chord-app/node_modules/jest-environment-jsdom/build/index.js',
                   testEnvironmentOptions: {},
                   testLocationInResults: false,
                   testMatch: [ '<homeDir>/code/jazz-chord-app/src/**/__tests__/**/*.{js,jsx,ts,tsx}', '<homeDir>/code/jazz-chord-app/src/**/*.{spec,test}.{js,jsx,ts,tsx}' ],
                   testPathIgnorePatterns: [ '/node_modules/' ],
                   testRegex: [],
                   testRunner: '<homeDir>/code/jazz-chord-app/node_modules/jest-circus/runner.js',
                   testURL: 'http://localhost',
                   timers: 'real',
                   transform:
                    [ [ '^.+\\.(js|jsx|mjs|cjs|ts|tsx)$', '<homeDir>/code/jazz-chord-app/node_modules/react-scripts/config/jest/babelTransform.js', {} ],
                      [ '^.+\\.css$', '<homeDir>/code/jazz-chord-app/node_modules/react-scripts/config/jest/cssTransform.js', {} ],
                      [ '^(?!.*\\.(js|jsx|mjs|cjs|ts|tsx|css|json)$)', '<homeDir>/code/jazz-chord-app/node_modules/react-scripts/config/jest/fileTransform.js', {} ] ],
                   transformIgnorePatterns: [ '[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs|cjs|ts|tsx)$', '^.+\\.module\\.(css|sass|scss)$' ],
                   unmockedModulePathPatterns: undefined,
                   watchPathIgnorePatterns: [] } ],
              globalConfig:
               { bail: 0,
                 changedFilesWithAncestor: false,
                 changedSince: undefined,
                 collectCoverage: false,
                 collectCoverageFrom: [ 'src/**/*.{js,jsx,ts,tsx}', '!src/**/*.d.ts' ],
                 collectCoverageOnlyFrom: undefined,
                 coverageDirectory: '<homeDir>/code/jazz-chord-app/coverage',
                 coverageProvider: 'babel',
                 coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
                 coverageThreshold: undefined,
                 detectLeaks: undefined,
                 detectOpenHandles: undefined,
                 enabledTestsMap: undefined,
                 errorOnDeprecated: false,
                 expand: false,
                 filter: undefined,
                 findRelatedTests: false,
                 forceExit: false,
                 globalSetup: undefined,
                 globalTeardown: undefined,
                 json: false,
                 lastCommit: false,
                 listTests: undefined,
                 logHeapUsage: false,
                 maxConcurrency: 5,
                 maxWorkers: 7,
                 noSCM: undefined,
                 noStackTrace: false,
                 nonFlagArgs: undefined,
                 notify: false,
                 notifyMode: 'failure-change',
                 onlyChanged: false,
                 onlyFailures: false,
                 outputFile: undefined,
                 passWithNoTests: undefined,
                 projects: [],
                 replname: undefined,
                 reporters: undefined,
                 rootDir: '<homeDir>/code/jazz-chord-app',
                 runTestsByPath: false,
                 silent: undefined,
                 skipFilter: false,
                 testFailureExitCode: 1,
                 testNamePattern: undefined,
                 testPathPattern: '',
                 testResultsProcessor: undefined,
                 testSequencer: '<homeDir>/code/jazz-chord-app/node_modules/@jest/test-sequencer/build/index.js',
                 testTimeout: undefined,
                 updateSnapshot: 'new',
                 useStderr: false,
                 verbose: undefined,
                 watch: false,
                 watchAll: false,
                 watchPlugins:
                  [ { config: {}, path: '<homeDir>/code/jazz-chord-app/node_modules/jest-watch-typeahead/filename.js' },
                    { config: {}, path: '<homeDir>/code/jazz-chord-app/node_modules/jest-watch-typeahead/testname.js' } ],
                 watchman: true },
              hasDeprecationWarnings: false,
              wallaby:
               { roots: [ 'src' ],
                 watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/' ],
                 testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/' ],
                 testMatch: [ 'src/**/__tests__/**/*.{js,jsx,ts,tsx}', 'src/**/*.{spec,test}.{js,jsx,ts,tsx}' ],
                 testRegex: [] } } } },
     testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
     filesWithCoverageCalculated: [ 'src/**/*.{js,jsx,ts,tsx}', '!src/**/*.d.ts' ],
     filesWithNoCoverageCalculated: [],
     globalSetup: false,
     micromatch: true,
     files:
      [ { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
        { pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//, ignore: true, trigger: true, load: true },
        { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
        { pattern: 'src/**', ignore: false, trigger: true, load: true, order: 2 },
        { pattern: 'src/**/__tests__/**/*.{js,jsx,ts,tsx}', ignore: true, trigger: true, load: true },
        { pattern: 'src/**/*.{spec,test}.{js,jsx,ts,tsx}', ignore: true, trigger: true, load: true } ],
     tests:
      [ { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
        { pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//, ignore: true, trigger: true, load: true, test: true },
        { pattern: 'src/**/__tests__/**/*.{js,jsx,ts,tsx}', ignore: false, trigger: true, load: true, test: true, order: 3 },
        { pattern: 'src/**/*.{spec,test}.{js,jsx,ts,tsx}', ignore: false, trigger: true, load: true, test: true, order: 4 } ],
     runAllTestsInAffectedTestFile: false,
     updateNoMoreThanOneSnapshotPerTestFileRun: false,
     addModifiedTestFileToExclusiveTestRun: true,
     compilers: {},
     preprocessors: {},
     maxConsoleMessagesPerTest: 100,
     autoConsoleLog: true,
     delays: { run: 0, edit: 100, update: 0 },
     workers: { initial: 0, regular: 0, recycle: false },
     teardown: undefined,
     hints:
      { ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
        ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
        commentAutoLog: '?',
        testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' } },
     automaticTestFileSelection: true,
     runSelectedTestsOnly: false,
     mapConsoleMessagesStackTrace: false,
     extensions: {},
     env: { type: 'node', params: {}, runner: '<homeDir>/.nvm/versions/node/v10.24.0/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
     reportUnhandledPromises: true,
     slowTestThreshold: 75,
     lowCoverageThreshold: 80,
     loose: true,
     configCode: 'auto.detect#-117548334' },
  packageJSON:
   { dependencies:
      { '@emotion/react': '11.4.0',
        '@emotion/styled': '11.3.0',
        '@material-ui/core': '5.0.0-beta.0',
        '@testing-library/jest-dom': '5.14.1',
        '@testing-library/react': '12.0.0',
        react: '17.0.2',
        'react-dom': '17.0.2',
        'react-scripts': '4.0.3',
        teoria: '^2.5.0' },
     devDependencies: { '@babel/runtime': '7.13.8', '@types/react-dom': '^17.0.9', typescript: '4.1.3', '@testing-library/react': '^12.0.0', '@testing-library/jest-dom': '^5.14.1', 'eslint-plugin-jest-dom': '^3.9.0' } },
  fs: { numberOfFiles: 27 },
  debug:
   [ '2021-07-19T05:07:44.441Z angular/cli config Angular CLI not found.\n',
     '2021-07-19T05:07:44.792Z jest/config Detected Jest.\n',
     '2021-07-19T05:07:44.793Z jest/config Configured Jest.\n',
     '2021-07-19T05:07:44.795Z project Wallaby Node version: v10.24.0\n',
     '2021-07-19T05:07:44.795Z project Wallaby config: <homeDir>/code/jazz-chord-app/auto.detect\n',
     '2021-07-19T05:07:44.898Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.298/projects/d787f42898f692f5\n',
     '2021-07-19T05:07:44.978Z uiService Listening port 51235\n',
     '2021-07-19T05:07:44.998Z workers Parallelism for initial run: 6, for regular run: 3\n',
     '2021-07-19T05:07:44.999Z workers Starting run worker instance #0\n',
     '2021-07-19T05:07:44.999Z workers Starting run worker instance #1\n',
     '2021-07-19T05:07:44.999Z workers Starting run worker instance #2\n',
     '2021-07-19T05:07:44.999Z workers Starting run worker instance #3\n',
     '2021-07-19T05:07:44.999Z workers Starting run worker instance #4\n',
     '2021-07-19T05:07:44.999Z workers Starting run worker instance #5\n',
     '2021-07-19T05:07:45.000Z workers Web server is listening at 54522\n',
     '2021-07-19T05:07:45.000Z project File cache requires some updates, waiting required files from IDE\n',
     '2021-07-19T05:07:45.066Z project Stopping process pool\n',
     '2021-07-19T05:07:45.068Z project Test run started; run priority: 3\n',
     '2021-07-19T05:07:45.071Z project Running all tests\n',
     '2021-07-19T05:07:45.074Z workers Starting test run, priority: 3\n',
     '2021-07-19T05:07:45.074Z workers Distributing tests between 6 workers\n',
     '2021-07-19T05:07:45.077Z workers Running tests in parallel\n',
     '2021-07-19T05:07:45.077Z nodeRunner Starting sandbox [worker #0, session #90ugs]\n',
     '2021-07-19T05:07:45.077Z nodeRunner Starting sandbox [worker #1, session #5a7fd]\n',
     '2021-07-19T05:07:45.077Z nodeRunner Starting sandbox [worker #2, session #ww15c]\n',
     '2021-07-19T05:07:45.077Z nodeRunner Starting sandbox [worker #3, session #oo5vt]\n',
     '2021-07-19T05:07:45.077Z nodeRunner Starting sandbox [worker #4, session #iz5t5]\n',
     '2021-07-19T05:07:45.078Z nodeRunner Preparing sandbox [worker #0, session #90ugs]\n',
     '2021-07-19T05:07:45.078Z nodeRunner Preparing sandbox [worker #1, session #5a7fd]\n',
     '2021-07-19T05:07:45.078Z nodeRunner Preparing sandbox [worker #2, session #ww15c]\n',
     '2021-07-19T05:07:45.078Z nodeRunner Preparing sandbox [worker #3, session #oo5vt]\n',
     '2021-07-19T05:07:45.078Z nodeRunner Preparing sandbox [worker #4, session #iz5t5]\n',
     '2021-07-19T05:07:45.356Z workers Started run worker instance (delayed) #0\n',
     '2021-07-19T05:07:45.356Z nodeRunner Prepared sandbox [worker #0, session #90ugs]\n',
     '2021-07-19T05:07:45.357Z workers [worker #0, session #90ugs] Running tests in sandbox\n',
     '2021-07-19T05:07:45.381Z workers Started run worker instance (delayed) #4\n',
     '2021-07-19T05:07:45.382Z nodeRunner Prepared sandbox [worker #4, session #iz5t5]\n',
     '2021-07-19T05:07:45.382Z workers [worker #4, session #iz5t5] Running tests in sandbox\n',
     '2021-07-19T05:07:45.389Z workers Started run worker instance (delayed) #1\n',
     '2021-07-19T05:07:45.389Z nodeRunner Prepared sandbox [worker #1, session #5a7fd]\n',
     '2021-07-19T05:07:45.389Z workers [worker #1, session #5a7fd] Running tests in sandbox\n',
     '2021-07-19T05:07:45.391Z workers Started run worker instance (delayed) #3\n',
     '2021-07-19T05:07:45.391Z nodeRunner Prepared sandbox [worker #3, session #oo5vt]\n',
     '2021-07-19T05:07:45.391Z workers [worker #3, session #oo5vt] Running tests in sandbox\n',
     '2021-07-19T05:07:45.399Z workers Started run worker instance (delayed) #2\n',
     '2021-07-19T05:07:45.399Z nodeRunner Prepared sandbox [worker #2, session #ww15c]\n',
     '2021-07-19T05:07:45.399Z workers [worker #2, session #ww15c] Running tests in sandbox\n',
     '2021-07-19T05:07:45.410Z workers Started run worker instance (delayed) #5\n',
     '2021-07-19T05:07:48.159Z workers Scheduling Jest Test Run (oo5vt): 2021-07-19T05:07:46.731Z\n',
     '2021-07-19T05:07:48.164Z workers Sandbox (active) [oo5vt] error: globalThis is not defined\n',
     '2021-07-19T05:07:48.167Z workers [oo5vt] Run 0 test(s), skipped 0 test(s)\n',
     '2021-07-19T05:07:48.168Z workers Jest Test Run Complete (oo5vt): 2021-07-19T05:07:48.156Z\n',
     '2021-07-19T05:07:48.170Z workers [oo5vt] Sandbox is responsive, closing it\n',
     '2021-07-19T05:07:48.173Z workers Failed to map the stack to user code, entry message: globalThis is not defined, stack: evalmachine.<anonymous>:1\nglobalThis\n^\n\nReferenceError: globalThis is not defined\n    at evalmachine.<anonymous>:1:1\n    at Script.runInContext (vm.js:133:20)\n    at Object.runInContext (vm.js:311:6)\n    at setupWindow (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/jsdom/browser/Window.js:111:55)\n    at new Window (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/jsdom/browser/Window.js:223:3)\n    at exports.createWindow (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/jsdom/browser/Window.js:95:10)\n    at new JSDOM (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/api.js:36:20)\n    at new JSDOMEnvironment (<homeDir>/code/jazz-chord-app/node_modules/jest-environment-jsdom/build/index.js:71:16)\n    at runTestInternal (<homeDir>/code/jazz-chord-app/node_modules/jest-runner/build/runTest.js:262:23)\n    at runTest (<homeDir>/code/jazz-chord-app/node_modules/jest-runner/build/runTest.js:472:40)\n',
     '2021-07-19T05:07:48.184Z workers Scheduling Jest Test Run (iz5t5): 2021-07-19T05:07:46.737Z\n',
     '2021-07-19T05:07:48.187Z workers Sandbox (active) [iz5t5] error: globalThis is not defined\n',
     '2021-07-19T05:07:48.192Z workers [iz5t5] Run 0 test(s), skipped 0 test(s)\n',
     '2021-07-19T05:07:48.193Z workers Jest Test Run Complete (iz5t5): 2021-07-19T05:07:48.181Z\n',
     '2021-07-19T05:07:48.195Z workers Scheduling Jest Test Run (5a7fd): 2021-07-19T05:07:46.733Z\n',
     '2021-07-19T05:07:48.195Z workers [iz5t5] Sandbox is responsive, closing it\n',
     '2021-07-19T05:07:48.196Z workers Failed to map the stack to user code, entry message: globalThis is not defined, stack: evalmachine.<anonymous>:1\nglobalThis\n^\n\nReferenceError: globalThis is not defined\n    at evalmachine.<anonymous>:1:1\n    at Script.runInContext (vm.js:133:20)\n    at Object.runInContext (vm.js:311:6)\n    at setupWindow (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/jsdom/browser/Window.js:111:55)\n    at new Window (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/jsdom/browser/Window.js:223:3)\n    at exports.createWindow (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/jsdom/browser/Window.js:95:10)\n    at new JSDOM (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/api.js:36:20)\n    at new JSDOMEnvironment (<homeDir>/code/jazz-chord-app/node_modules/jest-environment-jsdom/build/index.js:71:16)\n    at runTestInternal (<homeDir>/code/jazz-chord-app/node_modules/jest-runner/build/runTest.js:262:23)\n    at runTest (<homeDir>/code/jazz-chord-app/node_modules/jest-runner/build/runTest.js:472:40)\n',
     '2021-07-19T05:07:48.198Z workers Sandbox (active) [5a7fd] error: globalThis is not defined\n',
     '2021-07-19T05:07:48.199Z workers [5a7fd] Run 0 test(s), skipped 0 test(s)\n',
     '2021-07-19T05:07:48.200Z workers Jest Test Run Complete (5a7fd): 2021-07-19T05:07:48.192Z\n',
     '2021-07-19T05:07:48.202Z workers [5a7fd] Sandbox is responsive, closing it\n',
     '2021-07-19T05:07:48.203Z workers Failed to map the stack to user code, entry message: globalThis is not defined, stack: evalmachine.<anonymous>:1\nglobalThis\n^\n\nReferenceError: globalThis is not defined\n    at evalmachine.<anonymous>:1:1\n    at Script.runInContext (vm.js:133:20)\n    at Object.runInContext (vm.js:311:6)\n    at setupWindow (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/jsdom/browser/Window.js:111:55)\n    at new Window (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/jsdom/browser/Window.js:223:3)\n    at exports.createWindow (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/jsdom/browser/Window.js:95:10)\n    at new JSDOM (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/api.js:36:20)\n    at new JSDOMEnvironment (<homeDir>/code/jazz-chord-app/node_modules/jest-environment-jsdom/build/index.js:71:16)\n    at runTestInternal (<homeDir>/code/jazz-chord-app/node_modules/jest-runner/build/runTest.js:262:23)\n    at runTest (<homeDir>/code/jazz-chord-app/node_modules/jest-runner/build/runTest.js:472:40)\n',
     '2021-07-19T05:07:48.211Z workers Scheduling Jest Test Run (90ugs): 2021-07-19T05:07:46.721Z\n',
     '2021-07-19T05:07:48.213Z workers Sandbox (active) [90ugs] error: globalThis is not defined\n',
     '2021-07-19T05:07:48.214Z workers [90ugs] Run 0 test(s), skipped 0 test(s)\n',
     '2021-07-19T05:07:48.215Z workers Jest Test Run Complete (90ugs): 2021-07-19T05:07:48.208Z\n',
     '2021-07-19T05:07:48.217Z workers [90ugs] Sandbox is responsive, closing it\n',
     '2021-07-19T05:07:48.218Z workers Failed to map the stack to user code, entry message: globalThis is not defined, stack: evalmachine.<anonymous>:1\nglobalThis\n^\n\nReferenceError: globalThis is not defined\n    at evalmachine.<anonymous>:1:1\n    at Script.runInContext (vm.js:133:20)\n    at Object.runInContext (vm.js:311:6)\n    at setupWindow (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/jsdom/browser/Window.js:111:55)\n    at new Window (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/jsdom/browser/Window.js:223:3)\n    at exports.createWindow (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/jsdom/browser/Window.js:95:10)\n    at new JSDOM (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/api.js:36:20)\n    at new JSDOMEnvironment (<homeDir>/code/jazz-chord-app/node_modules/jest-environment-jsdom/build/index.js:71:16)\n    at runTestInternal (<homeDir>/code/jazz-chord-app/node_modules/jest-runner/build/runTest.js:262:23)\n    at runTest (<homeDir>/code/jazz-chord-app/node_modules/jest-runner/build/runTest.js:472:40)\n',
     '2021-07-19T05:07:48.219Z workers Scheduling Jest Test Run (ww15c): 2021-07-19T05:07:46.749Z\n',
     '2021-07-19T05:07:48.222Z workers Sandbox (active) [ww15c] error: globalThis is not defined\n',
     '2021-07-19T05:07:48.223Z workers [ww15c] Run 0 test(s), skipped 0 test(s)\n',
     '2021-07-19T05:07:48.224Z workers Jest Test Run Complete (ww15c): 2021-07-19T05:07:48.215Z\n',
     '2021-07-19T05:07:48.226Z workers [ww15c] Sandbox is responsive, closing it\n',
     '2021-07-19T05:07:48.226Z workers Failed to map the stack to user code, entry message: globalThis is not defined, stack: evalmachine.<anonymous>:1\nglobalThis\n^\n\nReferenceError: globalThis is not defined\n    at evalmachine.<anonymous>:1:1\n    at Script.runInContext (vm.js:133:20)\n    at Object.runInContext (vm.js:311:6)\n    at setupWindow (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/jsdom/browser/Window.js:111:55)\n    at new Window (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/jsdom/browser/Window.js:223:3)\n    at exports.createWindow (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/jsdom/browser/Window.js:95:10)\n    at new JSDOM (<homeDir>/code/jazz-chord-app/node_modules/jsdom/lib/api.js:36:20)\n    at new JSDOMEnvironment (<homeDir>/code/jazz-chord-app/node_modules/jest-environment-jsdom/build/index.js:71:16)\n    at runTestInternal (<homeDir>/code/jazz-chord-app/node_modules/jest-runner/build/runTest.js:262:23)\n    at runTest (<homeDir>/code/jazz-chord-app/node_modules/jest-runner/build/runTest.js:472:40)\n',
     '2021-07-19T05:07:48.227Z workers Merging parallel test run results\n',
     '2021-07-19T05:07:48.228Z project Test run finished\n',
     '2021-07-19T05:07:48.229Z project Processed console.log entries\n',
     '2021-07-19T05:07:48.229Z project Processed loading sequences\n',
     '2021-07-19T05:07:48.229Z project Processed executed tests\n',
     '2021-07-19T05:07:48.229Z project Processed code coverage\n',
     '2021-07-19T05:07:48.257Z project Test run result processed and sent to IDE\n',
     '2021-07-19T05:07:56.907Z fs No metadata for added file found: .git/FETCH_HEAD\n',
     '2021-07-19T05:07:57.684Z fs File changed: .git/FETCH_HEAD\n',
     '2021-07-19T05:07:57.684Z fs No metadata for changed file found: .git/FETCH_HEAD\n',
     '2021-07-19T05:11:25.974Z fs File changed: .git/FETCH_HEAD\n',
     '2021-07-19T05:11:25.974Z fs No metadata for changed file found: .git/FETCH_HEAD\n',
     '2021-07-19T05:11:26.657Z fs File changed: .git/FETCH_HEAD\n',
     '2021-07-19T05:11:26.657Z fs No metadata for changed file found: .git/FETCH_HEAD\n' ] }
```

**Comment by ArtemGovorov** [comment]
Thanks for sharing the repo and the diagnostics report. From the report:

> nodeVersion: 'v10.24.0',

it looks like you're using node v10 to run Wallaby and [`globalThis` support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) has been added on node v12. By default Wallaby is using your system default node version to run, so updating your node version should help, but if you have multiple node versions installed side-by-side (for example with `nvm`), you may point [configure Wallaby VS Code extension to use any other node version](https://wallabyjs.com/docs/intro/install.html#visual-studio-code).

**Comment by AlonaLaskar** [comment]
hello friend ,
i got the same problem , i development an applicaetion in react using ionic freamwork.
when i try to connect capaciton in android  studio i got this error's :"{"message":"Uncaught ReferenceError: globalThis is not defined",
"Msg: ReferenceError: globalThis is not defined",
 "Msg: Uncaught ReferenceError: globalThis is not defined".
npm version :"9.2.0",node version :"v16.14.0",ionic version :"6.20.8"

**Comment by ArtemGovorov** [comment]
@AlonaLaskar Your issue doesn't seem to be related to Wallaby.js, so I'd suggest to ask your question in Ionic specific Q&A resources.
