### ISSUE TITLE
Testing Angular 12 results in "No code generation entry for..." 

### ISSUE THREAD

**Issue by kdiehl** [wallabyjs/public#2775]
### Issue description or question

In our Angular 12 project running Wallaby with automatic configuration leads to the following error.
I assume this is a dependency or configuration issue regarding our project.

Tests using Karma are working fine.

### Wallaby diagnostics report

```
{
  editorVersion: 'WebStorm 2021.2',
  pluginVersion: '1.0.221',
  editorType: 'IntelliJ',
  osVersion: 'win32 10.0.18363',
  nodeVersion: 'v14.16.0',
  coreVersion: '1.0.1128',
  checksum: 'ZTRiOWJlZWFkY2FlNjAyNjAyNjcxOGUxNzE4ZmNlOWYsMTY2MDYwODAwMDAwMCww',
  config: {
    diagnostics: {
      angular: {
        workspace: {
          '$schema': './node_modules/@angular/cli/lib/config/schema.json',
          version: 1,
          newProjectRoot: 'projects',
          projects: {
            'my-app': {
              root: '',
              sourceRoot: 'src',
              projectType: 'application',
              architect: {
                build: {
                  builder: '@angular-devkit/build-angular:browser',
                  options: {
                    allowedCommonJsDependencies: [ 'date-holidays' ],
                    outputPath: 'dist',
                    index: 'src/index.html',
                    main: 'src/main.ts',
                    tsConfig: 'src/tsconfig.app.json',
                    polyfills: 'src/polyfills.ts',
                    stylePreprocessorOptions: { includePaths: [ 'node_modules' ] },
                    assets: [
                      'src/assets',
                      'src/favicon.ico',
                      'src/robots.txt',
                      { glob: '**/*', input: './node_modules/dsa/assets/', output: './assets/' },
                      'src/manifest.webmanifest'
                    ],
                    styles: [ './node_modules/dsa/dsa.css', 'src/custom-material-theme.scss', 'src/styles.scss' ],
                    scripts: [],
                    vendorChunk: true,
                    extractLicenses: false,
                    buildOptimizer: false,
                    sourceMap: true,
                    optimization: false,
                    namedChunks: true
                  },
                  configurations: {
                    production: {
                      budgets: [ { type: 'anyComponentStyle', maximumWarning: '6kb' } ],
                      optimization: true,
                      outputHashing: 'all',
                      sourceMap: false,
                      namedChunks: false,
                      extractLicenses: true,
                      vendorChunk: false,
                      buildOptimizer: true,
                      fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.prod.ts' } ],
                      serviceWorker: true,
                      ngswConfigPath: 'ngsw-config.json'
                    }
                  },
                  defaultConfiguration: ''
                },
                serve: {
                  builder: '@angular-devkit/build-angular:dev-server',
                  options: { browserTarget: 'my-app:build', port: 4030 },
                  configurations: { production: { browserTarget: 'my-app:build:production' } }
                },
                'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: 'my-app:build' } },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    main: 'src/test.ts',
                    karmaConfig: 'src/karma.conf.js',
                    polyfills: 'src/polyfills.ts',
                    tsConfig: 'src/tsconfig.spec.json',
                    codeCoverage: true,
                    scripts: [],
                    styles: [ './node_modules/dsa/dsa.css', 'src/styles.scss' ],
                    assets: [
                      'src/assets',
                      'src/favicon.ico',
                      'src/robots.txt',
                      { glob: '**/*', input: './node_modules/dsa/assets/', output: './assets/' },
                      'src/manifest.webmanifest'
                    ]
                  }
                },
                lint: { builder: '@angular-eslint/builder:lint', options: { lintFilePatterns: [ 'src/**/*.ts', 'src/**/*.html' ] } }
              }
            },
            'my-app-e2e': {
              root: 'e2e/',
              projectType: 'application',
              prefix: '',
              architect: {
                e2e: {
                  builder: '@angular-devkit/build-angular:protractor',
                  options: { protractorConfig: 'e2e/protractor.conf.js', devServerTarget: 'my-app:serve' },
                  configurations: { production: { devServerTarget: 'my-app:serve:production' } }
                },
                lint: { builder: '@angular-devkit/build-angular:tslint', options: { tsConfig: 'e2e/tsconfig.e2e.json', exclude: [ '**/node_modules/**' ] } }
              }
            }
          },
          defaultProject: 'my-app',
          schematics: { '@schematics/angular:component': { prefix: 'app', style: 'scss' }, '@schematics/angular:directive': { prefix: 'app' } }
        },
        main: '// This file is required by karma.conf.js and loads recursively all the .spec and framework files\r\n' +
          '\r\n' +
          "import 'zone.js/testing';\r\n" +
          "import { getTestBed } from '@angular/core/testing';\r\n" +
          'import {\r\n' +
          '  BrowserDynamicTestingModule,\r\n' +
          '  platformBrowserDynamicTesting,\r\n' +
          "} from '@angular/platform-browser-dynamic/testing';\r\n" +
          '\r\n' +
          'declare const require: any;\r\n' +
          '\r\n' +
          '// First, initialize the Angular testing environment.\r\n' +
          'getTestBed().initTestEnvironment(\r\n' +
          '  BrowserDynamicTestingModule,\r\n' +
          '  platformBrowserDynamicTesting()\r\n' +
          ');\r\n' +
          '// Then we find all the tests.\r\n' +
          '\r\n' +
          '// And load the modules.\r\n' +
          '\r\n'
      }
    },
    testFramework: { version: 'jasmine@3.6.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3', autoDetected: true },
    env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    files: [
      { pattern: 'src/**/*.spec.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/polyfills.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/main.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/index.html', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.base.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.wallaby.ts', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 2 },
      { pattern: 'src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 3 }
    ],
    tests: [ { pattern: 'src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 4 } ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    addModifiedTestFileToExclusiveTestRun: true,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#1313788472'
  },
  packageJSON: {
    dependencies: {
      '@angular/animations': '12.0.3',
      '@angular/cdk': '12.0.4',
      '@angular/common': '12.0.3',
      '@angular/compiler': '12.0.3',
      '@angular/core': '12.0.3',
      '@angular/flex-layout': '^12.0.0-beta.34',
      '@angular/forms': '12.0.3',
      '@angular/localize': '12.0.3',
      '@angular/material': '12.0.4',
      '@angular/platform-browser': '12.0.3',
      '@angular/platform-browser-dynamic': '12.0.3',
      '@angular/router': '12.0.3',
      '@angular/service-worker': '12.0.3',
      '@babel/core': '^7.15.0',
      'dsa': '^13.0.0',
      '@uiowa/digit-only': '1.2.1',
      'angular-oauth2-oidc': '10.0.3',
      'date-holidays': '1.6.1',
      moment: '2.26.0',
      'ngx-skeleton-loader': '2.9.1',
      rxjs: '6.5.5',
      tslib: '2.0.0',
      'zone.js': '~0.11.4'
    },
    devDependencies: {
      '@angular-devkit/build-angular': '^12.0.3',
      '@angular-eslint/builder': '12.1.0',
      '@angular-eslint/eslint-plugin': '12.1.0',
      '@angular-eslint/eslint-plugin-template': '12.1.0',
      '@angular-eslint/schematics': '12.1.0',
      '@angular-eslint/template-parser': '12.1.0',
      '@angular/cli': '^12.2.1',
      '@angular/compiler-cli': '12.0.3',
      '@angular/language-service': '12.0.3',
      '@types/jasmine': '~3.6.0',
      '@types/jasminewd2': '2.0.6',
      '@types/node': '^12.11.1',
      '@typescript-eslint/eslint-plugin': '4.23.0',
      '@typescript-eslint/parser': '4.23.0',
      codelyzer: '^6.0.0',
      eslint: '^7.28.0',
      'eslint-config-prettier': '^8.3.0',
      'eslint-plugin-import': 'latest',
      'eslint-plugin-jsdoc': 'latest',
      'eslint-plugin-prefer-arrow': 'latest',
      'eslint-plugin-prettier': '^3.4.0',
      husky: '^3.0.9',
      'jasmine-core': '~3.6.0',
      'jasmine-spec-reporter': '~5.0.0',
      karma: '^6.3.3',
      'karma-chrome-launcher': '~3.1.0',
      'karma-coverage': '^2.0.3',
      'karma-coverage-istanbul-reporter': '~3.0.2',
      'karma-jasmine': '~4.0.0',
      'karma-jasmine-html-reporter': '^1.5.0',
      'karma-spec-reporter': '0.0.32',
      'lint-staged': '^9.4.3',
      'ng-mocks': '^12.1.0',
      prettier: '2.1.1',
      protractor: '~7.0.0',
      'ts-node': '8.3.0',
      tslint: '~6.1.0',
      'tslint-config-prettier': '1.18.0',
      'tslint-plugin-prettier': '2.3.0',
      typescript: '4.2.4'
    }
  },
  fs: { numberOfFiles: 641 },
  debug: [
    '2021-08-17T06:17:39.672Z angular/cli config Detected Angular CLI.\n',
    '2021-08-17T06:17:50.596Z angular/cli karma project config Using virtual C:/Users/User/Projects/my-app/src/test.ts.\n',
    '2021-08-17T06:17:50.719Z project Wallaby Node version: v14.16.0\n',
    '2021-08-17T06:17:50.719Z project Wallaby config: C:\\Users\\User\\Projects\\my-app\\auto.detect\n',
    '2021-08-17T06:17:52.404Z project File cache: C:\\Users\\User\\AppData\\Local\\JetBrains\\WebStorm2021.2\\wallaby\\projects\\b551fe643195b21c\n',
    '2021-08-17T06:17:52.888Z uiService Listening port 51235\n',
    '2021-08-17T06:17:52.974Z project package.json file change detected, invalidating local cache\n',
    '2021-08-17T06:17:53.329Z workers Parallelism for initial run: 10, for regular run: 5\n',
    '2021-08-17T06:17:53.330Z workers Starting run worker instance #0\n',
    '2021-08-17T06:17:53.330Z workers Starting run worker instance #1\n',
    '2021-08-17T06:17:53.330Z workers Starting run worker instance #2\n',
    '2021-08-17T06:17:53.330Z workers Starting run worker instance #3\n',
    '2021-08-17T06:17:53.330Z workers Starting run worker instance #4\n',
    '2021-08-17T06:17:53.330Z workers Starting run worker instance #5\n',
    '2021-08-17T06:17:53.330Z workers Starting run worker instance #6\n',
    '2021-08-17T06:17:53.330Z workers Starting run worker instance #7\n',
    '2021-08-17T06:17:53.330Z workers Starting run worker instance #8\n',
    '2021-08-17T06:17:53.330Z workers Starting run worker instance #9\n',
    '2021-08-17T06:17:53.335Z workers Web server is listening at 50172\n',
    '2021-08-17T06:17:53.365Z project Stopping process pool\n',
    '2021-08-17T06:17:53.365Z project File cache is up-to-date, starting full test run\n',
    '2021-08-17T06:17:53.367Z project Running postprocessor\n',
    '2021-08-17T06:17:53.378Z postprocessor Processing started.\n',
    '2021-08-17T06:17:53.378Z postprocessor Initializing.\n',
    '2021-08-17T06:17:53.379Z postprocessor Initializing entry.\n',
    '2021-08-17T06:17:53.380Z postprocessor Sanitizing configuration.\n',
    '2021-08-17T06:17:53.380Z postprocessor Adjusting configuration.\n',
    '2021-08-17T06:17:53.390Z postprocessor Creating compiler.\n',
    '2021-08-17T06:17:53.886Z postprocessor Customizing compiler.\n',
    '2021-08-17T06:17:53.886Z postprocessor Compilation started.\n',
    '2021-08-17T06:18:12.563Z workers Started run worker instance (immediate) #0\n',
    '2021-08-17T06:18:12.563Z workers Started run worker instance (immediate) #1\n',
    '2021-08-17T06:18:12.563Z workers Started run worker instance (immediate) #2\n',
    '2021-08-17T06:18:12.564Z workers Started run worker instance (immediate) #3\n',
    '2021-08-17T06:18:12.564Z workers Started run worker instance (immediate) #4\n',
    '2021-08-17T06:18:12.564Z workers Started run worker instance (immediate) #5\n',
    '2021-08-17T06:18:12.564Z workers Started run worker instance (immediate) #6\n',
    '2021-08-17T06:18:12.564Z workers Started run worker instance (immediate) #7\n',
    '2021-08-17T06:18:12.564Z workers Started run worker instance (immediate) #8\n',
    '2021-08-17T06:18:12.564Z workers Started run worker instance (immediate) #9\n',
    '2021-08-17T06:18:30.307Z postprocessor Compilation finished.\n',
    '2021-08-17T06:18:34.376Z project Error: No code generation entry for C:\\Users\\User\\Projects\\my-app\\node_modules\\@angular-devkit\\build-angular\\src\\babel\\webpack-loader.js??ruleSet[1].rules[2].use[0]!C:\\Users\\User\\Projects\\my-app\\node_modules\\@ngtools\\webpack\\src\\ivy\\index.js!C:\\Users\\User\\Projects\\my-app\\node_modules\\perf-marks\\dist\\es2015\\user-timing-api-resolver.js (existing entries: C:\\Users\\User\\Projects\\my-app\\node_modules\\@angular-devkit\\build-angular\\src\\babel\\webpack-loader.js??ruleSet[1].rules[2].use[0]!...!!!!<<<AND SO ON>>>!!!!.' +
      '    at CodeGenerationResults.get (C:\\Users\\User\\Projects\\my-app\\node_modules\\webpack\\lib\\CodeGenerationResults.js:32:10)\n' +
      '    at CodeGenerationResults.getSource (C:\\Users\\User\\Projects\\my-app\\node_modules\\webpack\\lib\\CodeGenerationResults.js:96:15)\n' +
      '    at JavascriptModulesPlugin.renderModule (C:\\Users\\User\\Projects\\my-app\\node_modules\\webpack\\lib\\javascript\\JavascriptModulesPlugin.js:474:47)\n' +
      '    at t._renderModule (C:\\Users\\User\\AppData\\Local\\JetBrains\\WebStorm2021.2\\wallaby\\wallaby\\server.js:22:27250)\n' +
      '    at t.<anonymous> (C:\\Users\\User\\AppData\\Local\\JetBrains\\WebStorm2021.2\\wallaby\\wallaby\\server.js:22:2196)\n' +
      '    at n (C:\\Users\\User\\AppData\\Local\\JetBrains\\WebStorm2021.2\\wallaby\\wallaby\\server.js:21:30116)\n' +
      '    at Object.next (C:\\Users\\User\\AppData\\Local\\JetBrains\\WebStorm2021.2\\wallaby\\wallaby\\server.js:21:29411)\n' +
      '    at o (C:\\Users\\User\\AppData\\Local\\JetBrains\\WebStorm2021.2\\wallaby\\wallaby\\server.js:21:29170)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n',
    '2021-08-17T06:19:24.226Z project Test run finished\n',
    '2021-08-17T06:19:24.227Z project Test run data re-queued\n'
  ]
}
```

**Comment by kdiehl** [comment]
For some reason the "Start Exclusive Test Run" on a file works perfectly

**Comment by NikGovorov** [comment]
Thanks for reporting the issue. It is fixed and the fix is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
