### ISSUE TITLE
Wallaby.js starting, but not working (nothing happens)

### ISSUE THREAD

**Issue by Jabher** [wallabyjs/public#28]
End of the log file:
```
2015-03-03 12:18:22,252 [2432264]  ERROR - ecution.process.ProcessHandler - WebStorm 9.0.3  Build #WS-139.1112 
2015-03-03 12:18:22,252 [2432264]  ERROR - ecution.process.ProcessHandler - JDK: 1.6.0_65 
2015-03-03 12:18:22,252 [2432264]  ERROR - ecution.process.ProcessHandler - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-03-03 12:18:22,252 [2432264]  ERROR - ecution.process.ProcessHandler - Vendor: Apple Inc. 
2015-03-03 12:18:22,252 [2432264]  ERROR - ecution.process.ProcessHandler - OS: Mac OS X 
2015-03-03 12:18:22,252 [2432264]  ERROR - ecution.process.ProcessHandler - Last Action: Rerun 
2015-03-03 12:19:41,887 [2511899]  ERROR - ecution.process.ProcessHandler - null 
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:214)
	at com.sun.proxy.$Proxy15.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:188)
	at com.intellij.execution.process.ColoredProcessHandler.textAvailable(ColoredProcessHandler.java:91)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:66)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:147)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:76)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:53)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:241)
	at com.intellij.util.io.BaseOutputReader.processLine(BaseOutputReader.java:59)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:85)
	at com.intellij.util.io.BaseOutputReader.readAvailable(BaseOutputReader.java:126)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:99)
	at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:46)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: java.lang.NoClassDefFoundError: com/wallaby/javascript/session/b
	at com.wallaby.javascript.session.Session.a(Unknown Source)
	at com.wallaby.javascript.J.onTextAvailable(Unknown Source)
	... 25 more
2015-03-03 12:19:41,888 [2511900]  ERROR - ecution.process.ProcessHandler - WebStorm 9.0.3  Build #WS-139.1112 
2015-03-03 12:19:41,888 [2511900]  ERROR - ecution.process.ProcessHandler - JDK: 1.6.0_65 
2015-03-03 12:19:41,889 [2511901]  ERROR - ecution.process.ProcessHandler - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-03-03 12:19:41,889 [2511901]  ERROR - ecution.process.ProcessHandler - Vendor: Apple Inc. 
2015-03-03 12:19:41,889 [2511901]  ERROR - ecution.process.ProcessHandler - OS: Mac OS X 
2015-03-03 12:19:41,889 [2511901]  ERROR - ecution.process.ProcessHandler - Last Action: Rerun 
```

**Comment by ArtemGovorov** [comment]
Interesting, I can't reproduce the issue on OSX with the same WebStorm build. 

Could you please try uninstalling the plugin and installing it again to see if the issue persists?

**Comment by ArtemGovorov** [comment]
And BTW, what version of the plugin are you using? You can see the version on the Plugins settings page list.

**Comment by Jabher** [comment]
Version 1.0.1, WebStorm 9.0.3#WS-139.1112
os x 10.10.2 (default mac jvm) and 10.9 (jvm 1.8).

**Comment by ArtemGovorov** [comment]
Interesting, I have the exact same environment but can't reproduce the issues. Anyway, let's try something. I have uploaded a new version, please try it, and if it doesn't work, please attach the end of the log file.

**Comment by ArtemGovorov** [comment]
Ok, seems like you have the same issue like this one: https://github.com/wallabyjs/public/issues/32. Please make sure to install from the downloaded zip, and don't unzip it. If it doesn't help, please let me know.

**Comment by Jabher** [comment]
Aaand it works. Great, tnx, just stupid habit to unzip everything.
