### ISSUE TITLE
Async `setup` config function

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2812]
### Issue description or question

Can we use `async` in the setup functions? Does it support ESM? It appears this doesn't work.

_wallaby.conf.js_

```
setup: async wallaby => {
	await import('./tools/wallaby/register')
}
```

```
Runtime error: SyntaxError: await is only valid in async functions and the top level bodies of modules
    at WebSocket.emit (node:events:394:28)
    at afterWrite (node:internal/streams/writable:497:5)
    at onwrite (node:internal/streams/writable:477:7)
    at Zlib.cb (node:internal/streams/transform:201:7)
    at Zlib.processCallback (node:zlib:612:8)


2021-09-27T13:55:27.835Z workers Failed to map the stack to user code, entry message: await is only valid in async functions and the top level bodies of modules, stack: SyntaxError: await is only valid in async functions and the top level bodies of modules
    at module.exports (/Users/Vaughan/Library/Application Support/JetBrains/IntelliJIdeaVaughan/system/wallaby/wallaby/runners/node/bootstrap.js:14:1679)
    at x.in:run (/Users/Vaughan/Library/Application Support/JetBrains/IntelliJIdeaVaughan/system/wallaby/wallaby/server.js:21:24563)
    at WebSocket.<anonymous> (/Users/Vaughan/Library/Application Support/JetBrains/IntelliJIdeaVaughan/system/wallaby/wallaby/server.js:21:21706)
    at WebSocket.emit (node:events:394:28)
    at Receiver.ontext (/Users/Vaughan/Library/Application Support/JetBrains/IntelliJIdeaVaughan/system/wallaby/wallaby/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/Vaughan/Library/Application Support/JetBrains/IntelliJIdeaVaughan/system/wallaby/wallaby/node_modules/ws/lib/Receiver.js:536:18
    at /Users/Vaughan/Library/Application Support/JetBrains/IntelliJIdeaVaughan/system/wallaby/wallaby/node_modules/ws/lib/Receiver.js:368:7
    at /Users/Va
```

**Comment by smcenlly** [comment]
Thanks for letting us know that this wasn't working for you. Previously we did not support the use of `async` functions in the setup/teardown methods but we have now added support for this. 

Wallaby core `v1.0.1152`+ now support use of `async` `setup` and `teardown` functions.
