### ISSUE TITLE
`workers Failed to map the stack to user code` in ESM + Ava

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2827]
### Issue description or question

In this repro: https://github.com/vjpr/issue-wallaby-ava, I am seeing the following:

```
2021-10-04T14:28:17.476Z workers Failed to map the stack to user code, entry message: false, stack: AssertionError
    at ExecutionContext.assert (/Users/Vaughan/dev/code/issue-wallaby-ava/node_modules/.pnpm/ava@4.0.0-alpha.2/node_modules/ava/lib/assert.js:959:11)
    at file:///Users/Vaughan/Library/Application%20Support/JetBrains/IntelliJIdeaVaughan/system/wallaby/projects/b6febda6b403d55c/instrumented/packages/stress/tests/test0.test.ava.js?update=1633357697461&wallaby=true:6:25
    at Test.callFn (/Users/Vaughan/dev/code/issue-wallaby-ava/node_modules/.pnpm/ava@4.0.0-alpha.2/node_modules/ava/lib/test.js:578:21)
    at Test.run (/Users/Vaughan/dev/code/issue-wallaby-ava/node_modules/.pnpm/ava@4.0.0-alpha.2/node_modules/ava/lib/test.js:591:23)
    at Test.run (/Users/Vaughan/Library/Application Support/JetBrains/IntelliJIdeaVaughan/system/wallaby/wallaby/runners/node/ava@1.0.0/initializer.js:256:31)
    at Runner.runSingle (/Users/Vaughan/dev/code/issue-wallaby-ava/node_modules/.pnpm/ava@4.0.0-alpha.2/node_modules/ava/lib/runner.js:270:33)
```

The issue is in this line:

```
var j = i._fileRoot ? e.lastIndexOf(i._fileRoot) : -1;
```

```diff
i._fileRoot = /Users/Vaughan/Library/Application Support/JetBrains/IntelliJIdeaVaughan/system/wallaby/projects/b6febda6b403d55c/instrumented
- e = file:///Users/Vaughan/Library/Application%20Support/JetBrains/IntelliJIdeaVaughan/system/wallaby/projects/b6febda6b403d55c/instrumented/packages/stress/tests/test0.test.ava.js?update=1633357697461&wallaby=true:6:25
+ e = file:///Users/Vaughan/Library/Application Support/JetBrains/IntelliJIdeaVaughan/system/wallaby/projects/b6febda6b403d55c/instrumented/packages/stress/tests/test0.test.ava.js?update=1633357697461&wallaby=true:6:25
```

Note: `Application%20Support` vs `Application Support`.

URL's need to be unescaped.

**Comment by smcenlly** [comment]
This is fixed in the latest version of Wallaby core, `v1.0.1161`.
