### ISSUE TITLE
Module Not Found Error: Webpack + Angularjs + Typescript

### ISSUE THREAD

**Issue by alitez76** [wallabyjs/public#2832]
### Issue description or question
Wallaby fails to extract tests by 'Module not found' Error

When I run the wallaby start using the configuration file created by following the step in [this guide](https://wallabyjs.com/docs/integration/webpack-built-in.html), I'm getting this module not found errors and the tests discovery in wallaby stuck and fails with this error:

```
‌[Error] ./client-src/apps/_common/index.spec.ts 
[Error] Module not found: Error: Can't resolve 'test-helpers/mocks/state.mock' in './client-src/apps/_common' 
[Error]  @ ./client-src/apps/_common/index.spec.ts 4:21-68 
[Error]  @ ./wallaby-webpack-entry.js 

```

This is my config file:
```
module.exports = function (wallaby) {
  return {
    files: [
      { pattern: "client-src/**/*.ts", load: false },
      { pattern: "client-src/**/*.spec.ts", ignore: true },
      "!node_modules/**",
    ],

    tests: [
      { pattern: "client-src/**/*.spec.ts", load: false },
      "!node_modules/**",
    ],

    postprocessor: wallaby.postprocessors.webpack({
      module: {
        rules: [
          {
            test: /\.ts$/,
            use: [
              { loader: "ng-annotate-loader" },
              {
                loader: "ts-loader",
                options: { transpileOnly: true, onlyCompileBundledFiles: true },
              },
            ],
          },
        ],
      },
      resolve: {
        extensions: [".ts"],
      },
    }),
  };
};
```
 
### Wallaby diagnostics report

```
{
  editorVersion: '1.60.2',
  pluginVersion: '1.0.314',
  editorType: 'VSCode',
  osVersion: 'darwin 20.6.0',
  nodeVersion: 'v14.17.0',
  coreVersion: '1.0.1162',
  checksum: 'ZmY0NWRkYTcxYWFmMDI0MjhjZTFkMzcwZjYxNjY4YzgsMTYzNDM0MjQwMDAwMCwx',
  config: {
    files: [
      { pattern: 'client-src/**/*.ts', load: false, ignore: false, trigger: true, order: 1 },
      { pattern: 'client-src/**/*.spec.ts', ignore: true, trigger: true, load: true },
      { pattern: 'node_modules/**', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: 'client-src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 2 },
      { pattern: 'node_modules/**', ignore: true, trigger: true, load: true, test: true }
    ],
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    addModifiedTestFileToExclusiveTestRun: true,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'browser', kind: 'chrome', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    testFramework: { version: 'jasmine@3.6.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3' },
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'module.exports = function (wallaby) {\n' +
      '  return {\n' +
      '    files: [\n' +
      '      { pattern: "client-src/**/*.ts", load: false },\n' +
      '      { pattern: "client-src/**/*.spec.ts", ignore: true },\n' +
      '      "!node_modules/**",\n' +
      '    ],\n' +
      '\n' +
      '    tests: [\n' +
      '      { pattern: "client-src/**/*.spec.ts", load: false },\n' +
      '      "!node_modules/**",\n' +
      '    ],\n' +
      '\n' +
      '    postprocessor: wallaby.postprocessors.webpack({\n' +
      '      module: {\n' +
      '        rules: [\n' +
      '          {\n' +
      '            test: /\\.ts$/,\n' +
      '            use: [\n' +
      '              { loader: "ng-annotate-loader" },\n' +
      '              {\n' +
      '                loader: "ts-loader",\n' +
      '                options: { transpileOnly: true, onlyCompileBundledFiles: true },\n' +
      '              },\n' +
      '            ],\n' +
      '          },\n' +
      '        ],\n' +
      '      },\n' +
      '      resolve: {\n' +
      '        extensions: [".ts"],\n' +
      '      },\n' +
      '    }),\n' +
      '  };\n' +
      '};\n'
  },
  packageJSON: {
    dependencies: {
      '@xxx/frontend-logging': '4.0.2',
      '@progress/kendo-theme-default': '2.57.1',
      '@progress/kendo-ui': '2018.1.117',
      '@uirouter/angularjs': '1.0.22',
      angular: '1.5.9',
      'angular-animate': '1.5.9',
      'angular-aria': '1.5.9',
      'angular-cookies': '1.5.9',
      'angular-local-storage': '0.6.0',
      'angular-messages': '1.5.9',
      'angular-moment': '1.0.1',
      'angular-permission': '6.0.0',
      'angular-resource': '1.5.9',
      'angular-route': '1.5.9',
      'angular-sanitize': '1.5.9',
      'angular-translate': '2.15.1',
      'angular-translate-interpolation-messageformat': '2.15.2',
      'angular-translate-loader-partial': '2.15.1',
      'angular-translate-loader-static-files': '2.15.1',
      'angular-utils-pagination': '0.8.2',
      axios: '0.18.1',
      'blueimp-file-upload': '10.2.0',
      bootstrap: '4.0.0-alpha.6',
      'browser-cookies': '1.0.8',
      chardet: '1.3.0',
      'chart.js': '2.9.4',
      clipboard: '1.5.16',
      dompurify: '2.2.7',
      'es6-promise': '4.2.8',
      'es6-symbol': '3.1.3',
      'hellosign-embedded': '2.9.0',
      jquery: '3.5.1',
      'js-yaml': '3.13.1',
      keycode: '2.1.8',
      keypather: '1.10.2',
      linkifyjs: '2.0.5',
      'lodash.debounce': '4.0.8',
      'lodash.isequal': '4.5.0',
      'lodash.merge': '4.6.2',
      messageformat: '1.0.2',
      'moment-timezone': '0.5.33',
      'ng-redux': '4.4.1',
      'path-complete-extname': '0.1.0',
      pluralize: '3.1.0',
      qs: '6.8.0',
      redux: '3.7.2',
      'redux-saga': '0.16.0',
      rrule: '2.2.0',
      semver: '7.3.2',
      'tc-angular-chartjs': '2.1.4',
      'tslint-config-prettier': '1.18.0',
      'ui-select': '0.18.1',
      uuid: '2.0.3'
    },
    devDependencies: {
      '@xxx/karma-parallel': '1.22.5',
      '@cypress/webpack-preprocessor': '4.1.0',
      '@octokit/types': '6.21.1',
      '@rails/webpacker': '4.3.0',
      '@types/angular': '1.6.56',
      '@types/angular-local-storage': '0.6.1',
      '@types/angular-mocks': '1.7.0',
      '@types/angular-permission': '2.3.22',
      '@types/angular-resource': '1.5.15',
      '@types/angular-sanitize': '1.7.0',
      '@types/angular-translate': '2.16.0',
      '@types/browser-sync': '0.0.34',
      '@types/chai': '4.0.10',
      '@types/chart.js': '2.9.34',
      '@types/clipboard': '1.5.34',
      '@types/cypress-axe': '0.4.0',
      '@types/cypress-image-snapshot': '3.1.2',
      '@types/dompurify': '2.2.1',
      '@types/faker': '4.1.0',
      '@types/fetch-mock': '6.0.1',
      '@types/inquirer': '6.0.2',
      '@types/jasmine': '3.5.11',
      '@types/jquery': '3.5',
      '@types/kendo-ui': '2018.1.0',
      '@types/lodash': '4.14.64',
      '@types/lodash.debounce': '4.0.3',
      '@types/lodash.isequal': '4.5.5',
      '@types/lodash.merge': '4.6.4',
      '@types/minimist': '1.2.0',
      '@types/node': '14.17.0',
      '@types/prismjs': '1.4.18',
      '@types/semver': '7.3.4',
      '@types/showdown': '1.9.3',
      '@types/uuid': '3.4.3',
      '@types/webpack': '4.4.31',
      '@types/webpack-env': '1.13.6',
      'angular-mocks': '1.5.9',
      autoprefixer: '7.1.1',
      'axe-core': '3.3.2',
      'axios-mock-adapter': '1.15.0',
      chalk: '1.1.3',
      'clean-webpack-plugin': '0.1.15',
      'copy-webpack-plugin': '6.1.0',
      cypress: '4.12.1',
      'cypress-axe': '0.5.1',
      danger: '10.3.1',
      faker: '4.1.0',
      'fetch-mock': '6.5.2',
      'file-loader': '1.1.11',
      'fork-ts-checker-webpack-plugin': '6.2.0',
      glob: '7.1.2',
      'hard-source-webpack-plugin': '0.13.1',
      'html-webpack-plugin': '3.2.0',
      htmlhint: '0.14.2',
      'ignore-loader': '0.1.2',
      istanbul: '0.4.5',
      'istanbul-instrumenter-loader': '3.0.1',
      'jasmine-ajax': '3.3.1',
      'jasmine-core': '3.5.0',
      karma: '6.3.2',
      'karma-chrome-launcher': '3.1.0',
      'karma-commonjs': '1.0.0',
      'karma-coverage': '2.0.3',
      'karma-coverage-istanbul-reporter': '3.0.3',
      'karma-jasmine': '3.0.1',
      'karma-jasmine-html-reporter': '1.5.3',
      'karma-json-reporter': '1.2.1',
      'karma-ng-html2js-preprocessor': '1.0.0',
      'karma-notify-reporter': '1.0.1',
      'karma-sourcemap-loader': '0.3.7',
      'karma-webpack': '4.0.0-beta.0',
      'markdown-loader': '2.0.1',
      mochawesome: '4.1.0',
      'ng-annotate-loader': '0.6.0',
      precss: '1.4.0',
      prettier: '2.2.1',
      prismjs: '1.24.0',
      puppeteer: '5.5.0',
      'raw-loader': '0.5.1',
      'redoc-cli': '0.9.12',
      retire: '2.1.2',
      'sass-variable-loader': '0.1.2',
      sassdoc: '2.7.3',
      showdown: '1.9.1',
      'ts-loader': '8.0.3',
      'ts-node': '4.1.0',
      tslint: '6.1.3',
      'tslint-defocus': '2.0.6',
      typescript: '4.0.2',
      'webpack-bundle-analyzer': '4.4.1',
      'webpack-dev-server': '3.11.0',
      xhook: '1.4.0',
      'yaml-loader': '0.5.0'
    }
  },
  fs: { numberOfFiles: 4656 },
  debug: [
    '2021-10-07T22:51:55.833Z project Wallaby Node version: v14.17.0\n',
    '2021-10-07T22:51:55.833Z project Wallaby config: <homeDir>/src/yyy/components/manage/wallaby.config.js\n',
    '2021-10-07T22:51:56.738Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.314/projects/52a49a1fe611a958\n',
    '2021-10-07T22:51:56.880Z uiService Listening port 51235\n',
    '2021-10-07T22:51:57.074Z workers Parallelism for initial run: 10, for regular run: 5\n',
    '2021-10-07T22:51:57.075Z workers Starting run worker instance #0\n',
    '2021-10-07T22:51:57.075Z workers Starting run worker instance #1\n',
    '2021-10-07T22:51:57.075Z workers Starting run worker instance #2\n',
    '2021-10-07T22:51:57.075Z workers Starting run worker instance #3\n',
    '2021-10-07T22:51:57.075Z workers Starting run worker instance #4\n',
    '2021-10-07T22:51:57.075Z workers Starting run worker instance #5\n',
    '2021-10-07T22:51:57.075Z workers Starting run worker instance #6\n',
    '2021-10-07T22:51:57.075Z workers Starting run worker instance #7\n',
    '2021-10-07T22:51:57.075Z workers Starting run worker instance #8\n',
    '2021-10-07T22:51:57.075Z workers Starting run worker instance #9\n',
    '2021-10-07T22:51:57.078Z workers Web server is listening at 56189\n',
    '2021-10-07T22:51:57.089Z project Stopping process pool\n',
    '2021-10-07T22:51:57.089Z project File cache is up-to-date, starting full test run\n',
    '2021-10-07T22:51:57.093Z project Running postprocessor\n',
    '2021-10-07T22:51:57.121Z postprocessor Processing started.\n',
    '2021-10-07T22:51:57.121Z postprocessor Initializing.\n',
    '2021-10-07T22:51:57.125Z postprocessor Initializing entry.\n',
    '2021-10-07T22:51:57.125Z postprocessor Sanitizing configuration.\n',
    '2021-10-07T22:51:57.125Z postprocessor Adjusting configuration.\n',
    '2021-10-07T22:51:57.127Z postprocessor Creating compiler.\n',
    '2021-10-07T22:51:57.238Z postprocessor Customizing compiler.\n',
    '2021-10-07T22:51:57.238Z postprocessor Compilation started.\n',
    '2021-10-07T22:51:57.980Z workers Started run worker instance (immediate) #0\n',
    '2021-10-07T22:51:57.980Z workers Started run worker instance (immediate) #1\n',
    '2021-10-07T22:51:57.981Z workers Started run worker instance (immediate) #2\n',
    '2021-10-07T22:51:57.981Z workers Started run worker instance (immediate) #3\n',
    '2021-10-07T22:51:57.981Z workers Started run worker instance (immediate) #4\n',
    '2021-10-07T22:51:57.981Z workers Started run worker instance (immediate) #5\n',
    '2021-10-07T22:51:57.981Z workers Started run worker instance (immediate) #6\n',
    '2021-10-07T22:51:57.981Z workers Started run worker instance (immediate) #7\n',
    '2021-10-07T22:51:57.981Z workers Started run worker instance (immediate) #8\n',
    '2021-10-07T22:51:57.981Z workers Started run worker instance (immediate) #9\n',
    '2021-10-07T22:53:35.742Z project Error: ./client-src/apps/main/common/modules/services/email-confirmation-modal-service/email-confirmation-modal.service.spec.ts\n' +
      "Module not found: Error: Can't resolve 'test-helpers/mocks/http-mocking.service' in '<homeDir>/src/yyy/components/manage/client-src/apps/main/common/modules/services/email-confirmation-modal-service'\n" +
      ' @ ./client-src/apps/main/common/modules/services/email-confirmation-modal-service/email-confirmation-modal.service.spec.ts 189:53-103\n' +
      ' @ ./wallaby-webpack-entry.js\n' +
      '    at t.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.314/wallaby3b275b/server.js:22:6899)\n' +
      '    at n (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.314/wallaby3b275b/server.js:22:3290)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.314/wallaby3b275b/server.js:22:2585)\n' +
      '    at o (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.314/wallaby3b275b/server.js:22:2344)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n',
    '2021-10-07T22:53:35.744Z project Test run finished\n',
    '2021-10-07T22:53:35.744Z project Test run data re-queued\n',
    '2021-10-07T22:53:37.165Z project Running postprocessor\n',
    '2021-10-07T22:53:37.217Z postprocessor Processing started.\n',
    '2021-10-07T22:53:37.217Z postprocessor Initializing entry.\n',
    '2021-10-07T22:54:09.509Z postprocessor Compilation started (incremental).\n',
    '2021-10-07T22:56:20.120Z project Error: ./client-src/apps/_common/ui/src/lib/thError/thError.directive.spec.ts\n' +
      "Module not found: Error: Can't resolve 'test-helpers/spec.helpers' in '<homeDir>/src/yyy/components/manage/client-src/apps/_common/ui/src/lib/thError'\n" +
      ' @ ./client-src/apps/_common/ui/src/lib/thError/thError.directive.spec.ts 6:43-79\n' +
      ' @ ./wallaby-webpack-entry.js\n' +
      '    at t.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.314/wallaby3b275b/server.js:22:6899)\n' +
      '    at n (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.314/wallaby3b275b/server.js:22:3290)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.314/wallaby3b275b/server.js:22:2585)\n' +
      '    at o (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.314/wallaby3b275b/server.js:22:2344)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n',
    '2021-10-07T22:56:20.122Z project Test run finished\n',
    '2021-10-07T22:56:20.122Z project Test run data re-queued\n',
    '2021-10-07T22:56:20.223Z project Running postprocessor\n',
    '2021-10-07T22:56:20.263Z postprocessor Processing started.\n',
    '2021-10-07T22:56:20.264Z postprocessor Initializing entry.\n',
    '2021-10-07T22:56:28.886Z postprocessor Compilation started (incremental).\n',
    '2021-10-07T22:58:38.150Z project Error: ./client-src/apps/_common/index.spec.ts\n' +
      "Module not found: Error: Can't resolve 'test-helpers/mocks/yyy-state.mock' in '<homeDir>/src/yyy/components/manage/client-src/apps/_common'\n" +
      ' @ ./client-src/apps/_common/index.spec.ts 4:21-68\n' +
      ' @ ./wallaby-webpack-entry.js\n' +
      '    at t.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.314/wallaby3b275b/server.js:22:6899)\n' +
      '    at n (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.314/wallaby3b275b/server.js:22:3290)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.314/wallaby3b275b/server.js:22:2585)\n' +
      '    at o (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.314/wallaby3b275b/server.js:22:2344)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n',
    '2021-10-07T22:58:38.150Z project Test run finished\n',
    '2021-10-07T22:58:38.150Z project Test run data re-queued\n'
  ]
}
```

**Comment by alitez76** [comment]
test-helpers folder is under the client-src folder, so I assumed it should be loaded using the first pattern in files. 

question: are the paths relative to where the wallaby configuration file is located or relative to the root of the project loaded in vscode?

**Comment by smcenlly** [comment]
> question: are the paths relative to where the wallaby configuration file is located or relative to the root of the project loaded in vscode?

The paths are relative to where the wallaby configuration file is loaded.

> test-helpers folder is under the client-src folder, so I assumed it should be loaded using the first pattern in files.

Do you have any aliases for these? You would also need to ensure that they're correctly packaged as part of your webpack configuration.

---

Something for you to check, and some background...

With your Wallaby configuration, on startup, Wallaby will copy your project files (and tests) to a cached folder and will instrument and run your tests from there. If you have unmodified changes in your editor, the cached directory will also be updated on those (which is what allows Wallaby to run without saving your files).

Could you please check that the `test-helpers` files are being copied to Wallaby's cache? They should be located in a folder like:

```
/Users/%USER_NAME%/.vscode/extensions/wallabyjs.wallaby-%EXTENSION_VERSION%/projects/%RANDOM_ID%
```

if you have started Wallaby on a number of projects, you may have to look through the folders to find your current project. You should see `original` and `instrumented` folders with your source contents inside them.

**Comment by NikGovorov** [comment]
In your karma config you ignore all `scss` files, however in your wallaby config you don't, is there any specific reason for it? Looks like that's why karma works and wallaby does not.

**Comment by smcenlly** [comment]
> However, the issue is that no tests are discovered. All the files seems properly discovered and loaded by wallaby, but no test.

The reason that no tests are running is because you have used `load: false` (which is correct when using webpack to import your files for browser tests) but then you need to explicitly start the test run. So what you're missing is a setup function:

**Wallaby Configuration**
```diff
// const webpack = require("webpack");

const wallabyWebpack = require("wallaby-webpack");
const webpackConfig = require("./config/webpack/test");

const wallabyPostprocessor = wallabyWebpack(webpackConfig);

module.exports = function (wallaby) {
  return {
    trace: true,
    files: [
      { pattern: "client-src/apps/**/*.ts", load: false },
      { pattern: "config/locales/ngApp/en.yml", load: false },
      { pattern: "client-src/apps/**/*.yml", load: false },
      { pattern: "client-src/apps/main/common/javascripts/*.js", load: false },
      { pattern: "client-src/apps/**/*.html", load: false },
      { pattern: "client-src/apps/**/*.scss", load: false },
      { pattern: "client-src/apps/**/*.json", load: false },
      {pattern: "client-src/apps/**/*.spec.ts", ignore: true},
      "!node_modules/**",
    ],

    tests: [
      { pattern: "client-src/apps/**/*.spec.ts", load: false },
      "!node_modules/**",
    ],
    postprocessor: wallabyPostprocessor,
+   setup: function() {
+     window.__moduleBundler.loadTests();
+   }
  };
};

```

I can see that your configuration above is now no longer using the recommend Wallaby built-in postprocessor webpack integration and is using the open-source `wallaby-webpack` integration. If it works for you, that is great but since none of your tests were running, I would not be surprised if you start getting errors after adding the `setup` function as none of your code was executing before.

**Comment by NikGovorov** [comment]
Hi @alitez76,

If you still have any issues running your tests with Wallaby.js could you please create a sample github repo demonstrating the issues? We're happy to help fixing them.

**Comment by alitez76** [comment]
Sorry I got so busy with other works that I couldn't get back to this wallaby setup issues.

On my latest settings:
```
const webpackConfig = require("./config/webpack/test");


module.exports = function (wallaby) {
  return {
    trace: true,
    files: [
      { pattern: "client-src/apps/**/*.ts", load: true },
      { pattern: "config/locales/ngApp/en.yml", load: false },
      { pattern: "client-src/apps/**/*.yml", load: false },
      { pattern: "client-src/apps/main/common/javascripts/*.js", load: false },
      { pattern: "client-src/apps/**/*.html", load: false },
      { pattern: "client-src/apps/**/*.scss", load: false },
      { pattern: "client-src/apps/**/*.json", load: false },
      {pattern: "client-src/apps/**/*.spec.ts", ignore: true},
      "!node_modules/**",
    ],

    tests: [
      { pattern: "client-src/apps/main/**/*.spec.ts", load: false },
      "!node_modules/**",
    ],
    postprocessor: wallaby.postprocessors.webpack(webpackConfig),
    setup: function() {
        window.__moduleBundler.loadTests();
    }
  };
};
```

The test discovery seems working fine, however lot of tests fail. These are couple of errors I see:
```
Uncaught ReferenceError: jQuery is not defined 
  ​​​​​at Object.window.__moduleBundler.modules.<computed> ​​​​​​client-src/apps/_common/ui/src/lib/index.ts:2:0​
  ​​​​​at Object.window.__moduleBundler.modules.<computed> ​​​​​​client-src/apps/main/bills/bills-table/bills-table-columns.service.ts:6:0​
  ​​​​​at Object.window.__moduleBundler.modules.<computed> ​​​​​​client-src/apps/main/bills/bills-table/bills-table-columns.service.spec.ts:5:0
```

**Comment by smcenlly** [comment]
As per NikGovorov's last comment

> could you please create a sample github repo demonstrating the issues?

It seems that you are using some quite old dependencies with what we assume is a bit of a mix of technologies (not necessarily standard/latest) so trying to understand what's going on and help you will be hard without this.

One way of doing this is to take a copy of your project and then remove all source code except the code necessary to run your tests from the command line. Leave a single (dummy) test that has the same problem. At that point, you should have a sample that has none of your production code, and some non-proprietary code that sets up your testing framework so that we can see how things are configured and what's going on.

You also don't need to share this publicly, you may email us if you prefer: hello@wallabyjs.com

**Comment by alitez76** [comment]
@smcenlly  Thanks Simon, It's a super big repo, but I try to do as you mentioned and share with you asap.

just couple of questions that may help me:

1. What should I do with node_modules in regards to the `files` and `tests` in wallaby config?
2. How about the `index.ts` file that kind of the root module importer that imports all the angularjs modules? 
Please check my wallaby config file to see if there is anything specifically wrong with it?

**Comment by smcenlly** [comment]
> What should I do with node_modules in regards to the files and tests in wallaby config?

Generally speaking, there is no need to include node_modules _**unless**_ for some reason they need to be transformed. In your case, using webpack, I assume that your webpack configuration will bundle them as required.

> How about the index.ts file that kind of the root module importer that imports all the angularjs modules?

All of the files and tests that match your patterns are being imported automatically by Wallaby when it uses your webpack configuration. Your latest error, `Uncaught ReferenceError: jQuery is not defined` seems to indicate that you need to add jQuery to the list of `file` patterns so that the jQuery library is included. For example:

```javascript
module.exports = function (wallaby) {
  return {
...
    files: [
        // update pattern to point to correct jQuery source file location
        {pattern: 'lib/jquery.js', instrument: false},
...
    ]
```

> Please check my wallaby config file to see if there is anything specifically wrong with it?

Besides the jQuery suggestion, the configuration file looks OK (without knowing your project structure, webpack configuration, etc.).

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. If you provide a reproducible sample to further investigate your problems, we will re-open the issue.
