### ISSUE TITLE
wallaby.js config file not loading

### ISSUE THREAD

**Issue by mcjohnalds** [wallabyjs/public#2922]
### Issue description or question

I can't get the wallaby.js or wallaby.conf.js files to work. The "wallaby" field in the package.json works but that alternative isn't appropriate for my situation.

Steps to reproduce:

1. Install wallaby.js and quokka.js extensions in vscode
2. Create a folder with a package.json, some jest tests, and a wallaby.js file (clone https://github.com/mcjohnalds/wallaby-test for a premade example)
3. Disable all vscode extensions except for wallaby and quokka (just in case they are interfering)
4. Reload vscode
5. Run the `Wallaby.js: Start` command
6. Wallaby.js runs but it does not use the configuration in the wallaby.js configuration file, it just uses the defaults

Renaming to wallaby.conf.js does not help.

Moving the config from wallaby.js to package.json does work.

### Wallaby diagnostics report

```
{
  editorVersion: '1.63.2',
  pluginVersion: '1.0.325',
  editorType: 'VSCode',
  osVersion: 'darwin 20.6.0',
  nodeVersion: 'v14.17.6',
  coreVersion: '1.0.1218',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/private/var/folders/nn/thj1qdcs0695zfc2sgrkn6f80000gn/T/jest_dx',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/wallaby-test',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: undefined,
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              extraGlobals: [],
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: false, throwOnModuleCollision: false },
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [ 'js', 'jsx', 'ts', 'tsx', 'json', 'node' ],
              moduleLoader: undefined,
              moduleNameMapper: [],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              name: 'f7f1ad531aa619cf04b634d93a7a0e81',
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/wallaby-test',
              roots: [ '<homeDir>/wallaby-test' ],
              runner: '<homeDir>/wallaby-test/node_modules/jest-runner/build/index.js',
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/wallaby-test/node_modules/jest-environment-node/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<homeDir>/wallaby-test/node_modules/jest-circus/runner.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [ [ '\\.[jt]sx?$', '<homeDir>/wallaby-test/node_modules/babel-jest/build/index.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: [],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<homeDir>/wallaby-test/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 7,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/wallaby-test',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: undefined,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/wallaby-test/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/nn/thj1qdcs0695zfc2sgrkn6f80000gn/T/jest_dx', '\\./coverage' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/nn/thj1qdcs0695zfc2sgrkn6f80000gn/T/jest_dx', '\\./coverage' ],
            testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    micromatch: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
      { pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//, ignore: true, trigger: true, load: true },
      {
        pattern: '/private/var/folders/nn/thj1qdcs0695zfc2sgrkn6f80000gn/T/jest_dx',
        regexp: /\/private\/var\/folders\/nn\/thj1qdcs0695zfc2sgrkn6f80000gn\/T\/jest_dx/,
        ignore: true,
        trigger: true,
        load: true
      },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      {
        pattern: '/private/var/folders/nn/thj1qdcs0695zfc2sgrkn6f80000gn/T/jest_dx',
        regexp: /\/private\/var\/folders\/nn\/thj1qdcs0695zfc2sgrkn6f80000gn\/T\/jest_dx/,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, test: true },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    addModifiedTestFileToExclusiveTestRun: true,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '<homeDir>/.nvm/versions/node/v14.17.6/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#-2057835932'
  },
  packageJSON: { dependencies: { jest: '^27.4.7' }, devDependencies: undefined },
  fs: { numberOfFiles: 7 },
  debug: [
    '2022-02-02T07:15:54.509Z angular/cli config Angular CLI not found.\n',
    '2022-02-02T07:15:54.549Z jest/config Detected Jest.\n',
    '2022-02-02T07:15:54.549Z jest/config Configured Jest.\n',
    '2022-02-02T07:15:54.550Z project Wallaby Node version: v14.17.6\n',
    '2022-02-02T07:15:54.550Z project Wallaby config: <homeDir>/wallaby-test/auto.detect\n',
    '2022-02-02T07:15:54.576Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.325/projects/15b029bed807c321\n',
    '2022-02-02T07:15:54.631Z uiService Listening port 51235\n',
    '2022-02-02T07:15:54.639Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2022-02-02T07:15:54.639Z workers Starting run worker instance #0\n',
    '2022-02-02T07:15:54.639Z workers Starting run worker instance #1\n',
    '2022-02-02T07:15:54.639Z workers Starting run worker instance #2\n',
    '2022-02-02T07:15:54.639Z workers Starting run worker instance #3\n',
    '2022-02-02T07:15:54.639Z workers Starting run worker instance #4\n',
    '2022-02-02T07:15:54.639Z workers Starting run worker instance #5\n',
    '2022-02-02T07:15:54.639Z workers Web server is listening at 56871\n',
    '2022-02-02T07:15:54.639Z project File cache requires some updates, waiting required files from IDE\n',
    '2022-02-02T07:15:54.669Z project Stopping process pool\n',
    '2022-02-02T07:15:54.671Z project Test run started; run priority: 3\n',
    '2022-02-02T07:15:54.672Z project Running all tests\n',
    '2022-02-02T07:15:54.674Z workers Starting test run, priority: 3\n',
    '2022-02-02T07:15:54.674Z workers Distributing tests between 6 workers\n',
    '2022-02-02T07:15:54.675Z workers Running tests in parallel\n',
    '2022-02-02T07:15:54.675Z nodeRunner Starting sandbox [worker #0, session #ll4y4]\n',
    '2022-02-02T07:15:54.675Z nodeRunner Starting sandbox [worker #1, session #gu4au]\n',
    '2022-02-02T07:15:54.676Z nodeRunner Preparing sandbox [worker #0, session #ll4y4]\n',
    '2022-02-02T07:15:54.676Z nodeRunner Preparing sandbox [worker #1, session #gu4au]\n',
    '2022-02-02T07:15:54.742Z workers Started run worker instance (delayed) #3\n',
    '2022-02-02T07:15:54.744Z workers Started run worker instance (delayed) #0\n',
    '2022-02-02T07:15:54.744Z nodeRunner Prepared sandbox [worker #0, session #ll4y4]\n',
    '2022-02-02T07:15:54.744Z workers [worker #0, session #ll4y4] Running tests in sandbox\n',
    '2022-02-02T07:15:54.745Z workers Started run worker instance (delayed) #4\n',
    '2022-02-02T07:15:54.748Z workers Started run worker instance (delayed) #1\n',
    '2022-02-02T07:15:54.748Z nodeRunner Prepared sandbox [worker #1, session #gu4au]\n',
    '2022-02-02T07:15:54.748Z workers [worker #1, session #gu4au] Running tests in sandbox\n',
    '2022-02-02T07:15:54.749Z workers Started run worker instance (delayed) #2\n',
    '2022-02-02T07:15:54.751Z workers Started run worker instance (delayed) #5\n',
    '2022-02-02T07:15:55.134Z workers Sandbox (active) [ll4y4] error: process.exit called with 1\n',
    '2022-02-02T07:15:55.142Z workers Scheduling Jest Test Run (ll4y4): 2022-02-02T07:15:54.902Z\n',
    '2022-02-02T07:15:55.144Z workers [ll4y4] Loaded unknown number of test(s)\n',
    '2022-02-02T07:15:55.145Z workers Sandbox (active) [ll4y4] error: Your test suite must contain at least one test.\n',
    '2022-02-02T07:15:55.146Z workers [ll4y4] Run 0 test(s), skipped 0 test(s)\n',
    '2022-02-02T07:15:55.146Z workers Jest Test Run Complete (ll4y4): 2022-02-02T07:15:55.139Z\n',
    '2022-02-02T07:15:55.147Z workers [ll4y4] Sandbox is responsive, closing it\n',
    '2022-02-02T07:15:55.148Z workers Failed to map the stack to user code, entry message: Your test suite must contain at least one test., stack: Error: Your test suite must contain at least one test.\n' +
      '    at onResult (<homeDir>/wallaby-test/node_modules/@jest/core/build/TestScheduler.js:175:18)\n' +
      '    at <homeDir>/wallaby-test/node_modules/@jest/core/build/TestScheduler.js:316:17\n' +
      '    at <homeDir>/wallaby-test/node_modules/emittery/index.js:260:13\n' +
      '    at Array.map (<anonymous>)\n' +
      '    at Emittery.emit (<homeDir>/wallaby-test/node_modules/emittery/index.js:258:23)\n',
    '2022-02-02T07:15:55.158Z workers Scheduling Jest Test Run (gu4au): 2022-02-02T07:15:54.912Z\n',
    '2022-02-02T07:15:55.159Z workers [gu4au] Loaded unknown number of test(s)\n',
    '2022-02-02T07:15:55.160Z workers [gu4au] Test executed: should sum two numbers\n',
    '2022-02-02T07:15:55.160Z workers [gu4au] Run 1 test(s), skipped 0 test(s)\n',
    '2022-02-02T07:15:55.160Z workers Jest Test Run Complete (gu4au): 2022-02-02T07:15:55.157Z\n',
    '2022-02-02T07:15:55.161Z workers [gu4au] Sandbox is responsive, closing it\n',
    '2022-02-02T07:15:55.161Z workers Merging parallel test run results\n',
    '2022-02-02T07:15:55.161Z project Test run finished\n',
    '2022-02-02T07:15:55.161Z project Processed console.log entries\n',
    '2022-02-02T07:15:55.161Z project Processed loading sequences\n',
    '2022-02-02T07:15:55.161Z project Processed executed tests\n',
    '2022-02-02T07:15:55.162Z project Processed code coverage\n',
    '2022-02-02T07:15:55.165Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
You may [run `Wallaby.js Select Configuration` command](https://wallabyjs.com/docs/integration/jest.html#starting-wallaby-on-a-project-with-configured-jest) and your config file should be in the list for selection.
