### ISSUE TITLE
Wallaby.js is updating and will be started automatically when the update is complete.

### ISSUE THREAD

**Issue by colorways** [wallabyjs/public#2929]
Hi there. I'm getting the above error when I try to start Wallaby.

1. I've tried the suggestions in #2584 and #2773. Namely, uninstalling/deleting dir/reinstalling didn't work.
2. I have a valid license through May 2022 but when entering my license it shows this message in peach in the Manage License page in the Activate License box: "Wallaby.js is updating, you will be notified when the update is complete."
3. I've tried a few older extension versions going back to 1.0.300. All give the same response.
4. The `~/.wallaby/` folder only contains a single file `startPage.json` with a value of `{"version":5}` inside it
5. I'm using automatic configuration in this project
6. The VS Code Developer Tools console doesn't have any relevant messages related to Wallaby
7. I've tried starting and activating using a VPN and without VPN
8. The `Wallaby.js Console` Output window doesn't have any info in it
9. Quokka works perfectly

Any other ideas to try or diagnostic info I can provide to troubleshoot?

**Comment by smcenlly** [comment]
Could you please check the VS Code Developer Tools console to see if there are any errors reported? (Use the `Developer: Toggle Developer Tools` to show the console).

Did you also check/try to set the VS Code proxy as described in [one of the previous issues](https://github.com/wallabyjs/public/issues/2773#issuecomment-900697013)?

I would also try the following:
1. Close all instances of VS Code
2. Disable your Firewall and Virus Scanner
3. Re-open VS Code and see if it works for you. 

Can you also please provide details of your operating system? I assume that you are using VS Code/Wallaby on a project hosted on your operating system and not in a docker/remote environment?

---

While we work through the issue with you, you may perform an offline installation ([instructions here](https://wallabyjs.com/docs/intro/offline.html)) to continue to use Wallaby.

**Comment by colorways** [comment]
Thanks for such a quick response, Simon. Working on a Mac (Catalina 10.15.7) on the metal, not Docker/remote. I tried uninstalling everything again and this time, I *did* get an error (below). The server it thinks is down is not - I can download that zip file no problem in a browser. I have no proxy running. Disabling firewall didn't change things either. Tried rebooting, no dice. Tried re-installing VS Code and that didn't help. The odd thing is that re-registering Quokka through its Manage License page works perfect. Any other thoughts?

```text
FetchError: request to https://github.com/wallabyjs/github-releases/releases/download/v1.0.1223/wallaby-v1.0.1223.zip failed, reason: connect EHOSTDOWN 140.82.114.4:443 - Local (0.0.0.0:0)
	at ClientRequest.<anonymous> (/Users/yyyyyyyyyy/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.326/node_modules/node-fetch/lib/index.js:1461:11)
	at ClientRequest.emit (events.js:327:22)
	at ClientRequest.EventEmitter.emit (domain.js:467:12)
	at TLSSocket.socketErrorListener (_http_client.js:469:9)
	at TLSSocket.emit (events.js:315:20)
	at TLSSocket.EventEmitter.emit (domain.js:467:12)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by colorways** [comment]
This is resolved. There *was* a firewall rule at another layer of the network preventing the request to `github.com` from going through. Thank you, Simon, for your time. My apologies for essentially wasting it when the problem was fully on this side! :)
