### ISSUE TITLE
error:0308010C:digital envelope routines::unsupported​​

### ISSUE THREAD

**Issue by gh0st** [wallabyjs/public#2931]
### Issue description or question

Starting wallaby yields the following error

```
‍​[Info]​ Started Wallaby.js Core v1.0.1226
​​[Error] Error: error:0308010C:digital envelope routines::unsupported​​
​​[Error]     at new Hash (node:internal/crypto/hash:67:19)​​
​​[Error]     at Object.createHash (node:crypto:130:10)​​
​​[Error]     at module.exports (/Users/currentUser/Developer/myProject/client/node_modules/webpack/lib/util/createHash.js:135:53)​​
​​[Error]     at NormalModule._initBuildHash (/Users/currentUser/Developer/myProject/client/node_modules/webpack/lib/NormalModule.js:417:16)​​
​​[Error]     at handleParseError (/Users/currentUser/Developer/myProject/client/node_modules/webpack/lib/NormalModule.js:471:10)​​
​​[Error]     at /Users/currentUser/Developer/myProject/client/node_modules/webpack/lib/NormalModule.js:503:5​​
​​[Error]     at /Users/currentUser/Developer/myProject/client/node_modules/webpack/lib/NormalModule.js:358:12​​
​​[Error]     at /Users/currentUser/Developer/myProject/client/node_modules/loader-runner/lib/LoaderRunner.js:373:3​​
​​[Error]     at iterateNormalLoaders (/Users/currentUser/Developer/myProject/client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)​​
​​[Error]     at iterateNormalLoaders (/Users/currentUser/Developer/myProject/client/node_modules/loader-runner/lib/LoaderRunner.js:221:10)​​
​​[Error]     at /Users/currentUser/Developer/myProject/client/node_modules/loader-runner/lib/LoaderRunner.js:236:3​​
​​[Error]     at Object.context.callback (/Users/currentUser/Developer/myProject/client/node_modules/loader-runner/lib/LoaderRunner.js:111:13)​​
​​[Error]     at LOADER_EXECUTION (/Users/currentUser/Developer/myProject/client/node_modules/loader-runner/lib/LoaderRunner.js:119:14)​​
​​[Error]     at runSyncOrAsync (/Users/currentUser/Developer/myProject/client/node_modules/loader-runner/lib/LoaderRunner.js:120:4)​​
​​[Error]     at iterateNormalLoaders (/Users/currentUser/Developer/myProject/client/node_modules/loader-runner/lib/LoaderRunner.js:232:2)​​
​​[Error]     at iterateNormalLoaders (/Users/currentUser/Developer/myProject/client/node_modules/loader-runner/lib/LoaderRunner.js:221:10)​​
​​[Error]     at /Users/currentUser/Developer/myProject/client/node_modules/loader-runner/lib/LoaderRunner.js:236:3​​
​​[Error]     at context.callback (/Users/currentUser/Developer/myProject/client/node_modules/loader-runner/lib/LoaderRunner.js:111:13)​​
​​[Error]     at /Users/currentUser/Developer/myProject/client/node_modules/babel-loader/lib/index.js:59:71​​
​​[Error]     at processTicksAndRejections (node:internal/process/task_queues:96:5)​​
```

### Wallaby diagnostics report

```
{
  editorVersion: '1.64.2',
  pluginVersion: '1.0.327',
  editorType: 'VSCode',
  osVersion: 'darwin 21.3.0',
  nodeVersion: 'v17.0.1',
  coreVersion: '1.0.1226',
  checksum: 'ZTEwMjBlNWQ1NTBlZDAzNjViNGUzZTdhYmJhMzBhMWYsMTY3Njc2NDgwMDAwMCww',
  config: {
    diagnostics: {
      angular: {
        workspace: {
          '$schema': './node_modules/@angular/cli/lib/config/schema.json',
          version: 1,
          newProjectRoot: 'projects',
          projects: {
            'myProject': {
              projectType: 'application',
              schematics: {},
              root: '',
              sourceRoot: 'src',
              prefix: 'app',
              architect: {
                build: {
                  builder: '@angular-devkit/build-angular:browser',
                  options: {
                    outputPath: 'dist/myProject',
                    index: 'src/index.html',
                    main: 'src/main.ts',
                    polyfills: 'src/polyfills.ts',
                    tsConfig: 'tsconfig.app.json',
                    aot: true,
                    assets: [ 'src/favicon.ico', 'src/assets', { glob: '**/*', input: 'node_modules/ngx-auth-firebaseui/assets/', output: './assets' } ],
                    styles: [ './node_modules/@angular/material/prebuilt-themes/indigo-pink.css', 'src/styles.scss' ],
                    scripts: []
                  },
                  configurations: {
                    production: {
                      fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.prod.ts' } ],
                      optimization: true,
                      outputHashing: 'all',
                      sourceMap: false,
                      namedChunks: false,
                      extractLicenses: true,
                      vendorChunk: false,
                      buildOptimizer: true,
                      budgets: [ { type: 'initial', maximumWarning: '2mb', maximumError: '5mb' }, { type: 'anyComponentStyle', maximumWarning: '6kb' } ]
                    }
                  }
                },
                serve: {
                  builder: '@angular-devkit/build-angular:dev-server',
                  options: { browserTarget: 'myProject:build' },
                  configurations: { production: { browserTarget: 'myProject:build:production' } }
                },
                'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: 'myProject:build' } },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    main: 'src/test.ts',
                    polyfills: 'src/polyfills.ts',
                    tsConfig: 'tsconfig.spec.json',
                    karmaConfig: 'karma.conf.js',
                    assets: [ 'src/favicon.ico', 'src/assets' ],
                    styles: [ './node_modules/@angular/material/prebuilt-themes/indigo-pink.css', 'src/styles.scss' ],
                    scripts: []
                  }
                },
                lint: {
                  builder: '@angular-devkit/build-angular:tslint',
                  options: { tsConfig: [ 'tsconfig.app.json', 'tsconfig.spec.json', 'e2e/tsconfig.json' ], exclude: [ '**/node_modules/**' ] }
                },
                e2e: {
                  builder: '@angular-devkit/build-angular:protractor',
                  options: { protractorConfig: 'e2e/protractor.conf.js', devServerTarget: 'myProject:serve' },
                  configurations: { production: { devServerTarget: 'myProject:serve:production' } }
                },
                deploy: { builder: '@angular/fire:deploy', options: {} }
              }
            }
          },
          defaultProject: 'myProject'
        },
        main: '// This file is required by karma.conf.js and loads recursively all the .spec and framework files\n' +
          '\n' +
          "import 'zone.js/dist/zone-testing';\n" +
          "import { getTestBed } from '@angular/core/testing';\n" +
          'import {\n' +
          '  BrowserDynamicTestingModule,\n' +
          '  platformBrowserDynamicTesting\n' +
          "} from '@angular/platform-browser-dynamic/testing';\n" +
          '\n' +
          'declare const require: any;\n' +
          '\n' +
          '// First, initialize the Angular testing environment.\n' +
          'getTestBed().initTestEnvironment(\n' +
          '  BrowserDynamicTestingModule,\n' +
          '  platformBrowserDynamicTesting()\n' +
          ');\n' +
          '// Then we find all the tests.\n' +
          '\n' +
          '// And load the modules.\n' +
          '\n'
      }
    },
    testFramework: { version: 'jasmine@3.10.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3', autoDetected: true },
    env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    files: [
      { pattern: 'src/**/*.spec.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/polyfills.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/main.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/index.html', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.base.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.wallaby.ts', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 2 },
      { pattern: 'src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 3 }
    ],
    tests: [ { pattern: 'src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 4 } ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    addModifiedTestFileToExclusiveTestRun: true,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#1313788472'
  },
  packageJSON: {
    dependencies: {
      '@angular-material-extensions/password-strength': '^8.2.1',
      '@angular/animations': '^11.2.14',
      '@angular/cdk': '^11.2.13',
      '@angular/common': '^11.2.14',
      '@angular/compiler': '^11.2.14',
      '@angular/core': '^11.2.14',
      '@angular/fire': '^6.1.5',
      '@angular/flex-layout': '^11.0.0-beta.33',
      '@angular/forms': '^11.2.14',
      '@angular/material': '^11.2.13',
      '@angular/platform-browser': '^11.2.14',
      '@angular/platform-browser-dynamic': '^11.2.14',
      '@angular/router': '^11.2.14',
      firebase: '^8.7.1',
      'ngx-auth-firebaseui': '^5.3.0',
      'ngx-material-timepicker': '^5.5.3',
      rxjs: '^6.6.7',
      'standard-version': '^9.3.1',
      tslib: '^2.3.0',
      'zone.js': '^0.11.4'
    },
    devDependencies: {
      '@angular-devkit/architect': '^0.1101.4',
      '@angular-devkit/build-angular': '~0.1101.4',
      '@angular/cli': '^11.2.17',
      '@angular/compiler-cli': '^11.2.14',
      '@angular/language-service': '^11.2.14',
      '@types/jasmine': '^3.8.1',
      '@types/jasminewd2': '^2.0.10',
      '@types/node': '^14.18.2',
      codelyzer: '^6.0.2',
      'firebase-tools': '^9.23.3',
      fuzzy: '^0.1.3',
      inquirer: '^7.3.3',
      'inquirer-autocomplete-prompt': '^1.4.0',
      'jasmine-core': '~3.6.0',
      'jasmine-spec-reporter': '^6.0.0',
      karma: '^6.3.14',
      'karma-chrome-launcher': '~3.1.0',
      'karma-coverage-istanbul-reporter': '~3.0.2',
      'karma-jasmine': '~4.0.0',
      'karma-jasmine-html-reporter': '^1.7.0',
      protractor: '~7.0.0',
      'ts-node': '^9.1.1',
      tslint: '~6.1.0',
      typescript: '4.1.5'
    }
  },
  fs: { numberOfFiles: 96 },
  debug: [
    '2022-02-19T10:58:51.515Z angular/cli config Detected Angular CLI.\n',
    '2022-02-19T10:58:51.516Z angular/cli config Angular currentDirPath: "<homeDir>/Developer/myProject/client", workspaceDirPath: "<homeDir>/Developer/myProject/client"\n',
    '2022-02-19T10:58:52.481Z angular/cli karma project config Using virtual <homeDir>/Developer/myProject/client/src/test.ts.\n',
    '2022-02-19T10:58:52.487Z project Wallaby Node version: v17.0.1\n',
    '2022-02-19T10:58:52.487Z project Wallaby config: <homeDir>/Developer/myProject/client/auto.detect\n',
    '2022-02-19T10:58:52.526Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.327/projects/7801050248262466\n',
    '2022-02-19T10:58:52.553Z uiService Listening port 51235\n',
    '2022-02-19T10:58:52.575Z workers Parallelism for initial run: 8, for regular run: 4\n',
    '2022-02-19T10:58:52.575Z workers Starting run worker instance #0\n',
    '2022-02-19T10:58:52.575Z workers Starting run worker instance #1\n',
    '2022-02-19T10:58:52.575Z workers Starting run worker instance #2\n',
    '2022-02-19T10:58:52.575Z workers Starting run worker instance #3\n',
    '2022-02-19T10:58:52.575Z workers Starting run worker instance #4\n',
    '2022-02-19T10:58:52.575Z workers Starting run worker instance #5\n',
    '2022-02-19T10:58:52.575Z workers Starting run worker instance #6\n',
    '2022-02-19T10:58:52.575Z workers Starting run worker instance #7\n',
    '2022-02-19T10:58:52.576Z workers Web server is listening at 49999\n',
    '2022-02-19T10:58:52.580Z project Stopping process pool\n',
    '2022-02-19T10:58:52.580Z project File cache is up-to-date, starting full test run\n',
    '2022-02-19T10:58:52.581Z project Running postprocessor\n',
    '2022-02-19T10:58:52.583Z postprocessor Processing started.\n',
    '2022-02-19T10:58:52.583Z postprocessor Initializing.\n',
    '2022-02-19T10:58:52.583Z postprocessor Initializing entry.\n',
    '2022-02-19T10:58:52.583Z postprocessor Sanitizing configuration.\n',
    '2022-02-19T10:58:52.583Z postprocessor Adjusting configuration.\n',
    '2022-02-19T10:58:52.583Z postprocessor Creating compiler.\n',
    '2022-02-19T10:58:52.618Z postprocessor Customizing compiler.\n',
    '2022-02-19T10:58:52.618Z postprocessor Compilation started.\n',
    '2022-02-19T10:58:55.297Z workers Started run worker instance (immediate) #0\n',
    '2022-02-19T10:58:55.297Z workers Started run worker instance (immediate) #1\n',
    '2022-02-19T10:58:55.297Z workers Started run worker instance (immediate) #2\n',
    '2022-02-19T10:58:55.297Z workers Started run worker instance (immediate) #3\n',
    '2022-02-19T10:58:55.297Z workers Started run worker instance (immediate) #4\n',
    '2022-02-19T10:58:55.297Z workers Started run worker instance (immediate) #5\n',
    '2022-02-19T10:58:55.297Z workers Started run worker instance (immediate) #6\n',
    '2022-02-19T10:58:55.297Z workers Started run worker instance (immediate) #7\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
It looks like it is node 17 related issue. You may find some more [details/solutions here](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported). If you want to keep node 17 as your default node version, you may configure Wallaby to use other installed version as [described here](https://wallabyjs.com/docs/intro/install.html#visual-studio-code).

**Comment by gh0st** [comment]
That was the issue. Thank you!
