### ISSUE TITLE
Unable to launch WallabyJS on Webstorm

### ISSUE THREAD

**Issue by ItIsHamza** [wallabyjs/public#2932]
### Issue description or question

I'm not able to make WallabyJS work properly anymore on Webstorm. The first time I used a trial version, everything went fine. 1 month after I renewed my trial license just to try it one last time before buying the license. But Wallaby seems to start with no problem but when going through my spec files, the same error is occuring, preventing me from testing anything.

### Wallaby diagnostics report

```
console.log: Jest:   ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'runnerExistingCache')
      at NgJestTransformer.e.process (../../../../../AppData/Local/JetBrains/WebStorm2021.3/wallaby/wallaby/runners/node/jest@24.8.0/initializer.js:15:4817)
      at ScriptTransformer.transformSource (../../node_modules/@jest/transform/build/ScriptTransformer.js:620:31)
      at ScriptTransformer._transformAndBuildScript (../../node_modules/@jest/transform/build/ScriptTransformer.js:766:40)
      at ScriptTransformer.transform (../../node_modules/@jest/transform/build/ScriptTransformer.js:823:19)
      at Object.<anonymous> (src/app/shared/shared.module.ts:15:41)
      at Object.<anonymous> (src/app/administration/components/pre-ord-administration/blocks/maintenance-pack-configuration/maintenance-pack-configuration.component.spec.ts:8:46)
```
This error is occuring in almost every file. 

What I tried:
- Clear Wallaby cache
- Clear Jest cache
- Uninstall & reinstall Wallaby plug in
- Edit the configuration from automatic to manual and point it to my wallaby.js file
- Uninstall & reinstall my IDE

Result is still the same. Any idea what might be causing this issue?

**Comment by smcenlly** [comment]
The issue is fixed in the latest version of Wallaby core, v1.0.1229 (released about 1 hour ago). Wallaby should automatically update for you, but if it does not, you may [force a core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

> In JetBrains IDEs or Visual Studio: just restart your IDE and start wallaby.js to force the core update.
