### ISSUE TITLE
Wallaby.js needs restarting after clearing the Jest cache with some TypeScript projects

### ISSUE THREAD

**Issue by dnicolson** [wallabyjs/public#2942]
### Issue description or question

For some TypeScript projects clearing the Jest cache requires restarting Wallaby.js due to a "no such file or directory" error. Changing the Jest config file can also require a restart, I don't have the steps to reproduce through.

To reproduce:
1. Clone https://github.com/bschlenk/node-typescript-jest-boilerplate
2. Run `npm i`
3. Open Visual Studio Code and start Wallaby.js
4. Run `npx jest --cacheClean`
5. Edit the test in `utils.test.ts`

### Wallaby diagnostics report

```
{
  editorVersion: '1.64.2',
  pluginVersion: '1.0.327',
  editorType: 'VSCode',
  osVersion: 'darwin 21.3.0',
  nodeVersion: 'v14.17.0',
  coreVersion: '1.0.1237',
  checksum: 'OTkxODgwZDA0YWMwNWI1ZGExN2E1YjkxMTMxMDIxM2MsMTY3NDE3MjgwMDAwMCww',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/private/var/folders/1c/877fdzzj05v1vyy_h41r8cqw0000gn/T/jest_dx',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/x',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: undefined,
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              extraGlobals: [],
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: false, throwOnModuleCollision: false },
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [ 'js', 'jsx', 'ts', 'tsx', 'json', 'node' ],
              moduleLoader: undefined,
              moduleNameMapper: [],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              name: '3d7c2a893d26f94f5ebe0c312d607034',
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/x',
              roots: [ '<homeDir>/x' ],
              runner: '<homeDir>/x/node_modules/jest-runner/build/index.js',
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/x/node_modules/jest-environment-node/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
              testPathIgnorePatterns: [ '<homeDir>/x/node_modules/', '<homeDir>/x/dist/' ],
              testRegex: [],
              testRunner: '<homeDir>/x/node_modules/jest-circus/runner.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [ [ '^.+\\.tsx?$', '<homeDir>/x/node_modules/ts-jest/dist/index.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: true,
            collectCoverageFrom: [ 'src/**/*.ts', '!**/*.d.ts' ],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<homeDir>/x/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 15,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/x',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: undefined,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/x/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [
              '/node_modules/',
              '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
              '/private/var/folders/1c/877fdzzj05v1vyy_h41r8cqw0000gn/T/jest_dx',
              '\\./node_modules/',
              '\\./dist/',
              '\\./coverage'
            ],
            testPathIgnorePatterns: [
              '/node_modules/',
              '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
              '/private/var/folders/1c/877fdzzj05v1vyy_h41r8cqw0000gn/T/jest_dx',
              '\\./node_modules/',
              '\\./dist/',
              '\\./coverage'
            ],
            testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [ 'src/**/*.ts', '!**/*.d.ts' ],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    micromatch: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
      { pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//, ignore: true, trigger: true, load: true },
      {
        pattern: '/private/var/folders/1c/877fdzzj05v1vyy_h41r8cqw0000gn/T/jest_dx',
        regexp: /\/private\/var\/folders\/1c\/877fdzzj05v1vyy_h41r8cqw0000gn\/T\/jest_dx/,
        ignore: true,
        trigger: true,
        load: true
      },
      { pattern: '\\./node_modules/', regexp: /\.\/node_modules\//, ignore: true, trigger: true, load: true },
      { pattern: '\\./dist/', regexp: /\.\/dist\//, ignore: true, trigger: true, load: true },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      {
        pattern: '/private/var/folders/1c/877fdzzj05v1vyy_h41r8cqw0000gn/T/jest_dx',
        regexp: /\/private\/var\/folders\/1c\/877fdzzj05v1vyy_h41r8cqw0000gn\/T\/jest_dx/,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      { pattern: '\\./node_modules/', regexp: /\.\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
      { pattern: '\\./dist/', regexp: /\.\/dist\//, ignore: true, trigger: true, load: true, test: true },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, test: true },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    addModifiedTestFileToExclusiveTestRun: true,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '<homeDir>/.asdf/installs/nodejs/14.17.0/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#2009922554'
  },
  packageJSON: {
    dependencies: undefined,
    devDependencies: {
      '@commitlint/cli': '^12.1.4',
      '@commitlint/config-conventional': '^12.1.4',
      '@types/jest': '^26.0.23',
      '@types/node': '^16.0.0',
      '@typescript-eslint/eslint-plugin': '^4.28.1',
      '@typescript-eslint/parser': '^4.28.1',
      eslint: '^7.30.0',
      'eslint-config-prettier': '^8.3.0',
      'eslint-plugin-import': '^2.23.4',
      husky: '^7.0.0',
      jest: '^27.0.6',
      'lint-staged': '^11.0.0',
      nodemon: '^2.0.9',
      prettier: '^2.3.2',
      'ts-jest': '^27.0.3',
      'ts-node': '^10.0.0',
      typescript: '^4.3.5'
    }
  },
  fs: { numberOfFiles: 16 },
  debug: [
    '2022-03-07T20:56:57.140Z angular/cli config Angular CLI not found.\n',
    '2022-03-07T20:56:57.284Z jest/config Detected Jest.\n',
    '2022-03-07T20:56:57.284Z jest/config Configured Jest.\n',
    '2022-03-07T20:56:57.286Z project Wallaby Node version: v14.17.0\n',
    '2022-03-07T20:56:57.286Z project Wallaby config: <homeDir>/x/auto.detect\n',
    '2022-03-07T20:56:57.337Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.327/projects/a2f49081c997b46d\n',
    '2022-03-07T20:56:57.345Z uiService Listening port 51237\n',
    '2022-03-07T20:56:57.348Z project package.json file change detected, invalidating local cache\n',
    '2022-03-07T20:56:57.357Z workers Parallelism for initial run: 14, for regular run: 7\n',
    '2022-03-07T20:56:57.357Z workers Starting run worker instance #0\n',
    '2022-03-07T20:56:57.358Z workers Starting run worker instance #1\n',
    '2022-03-07T20:56:57.358Z workers Starting run worker instance #2\n',
    '2022-03-07T20:56:57.358Z workers Starting run worker instance #3\n',
    '2022-03-07T20:56:57.358Z workers Starting run worker instance #4\n',
    '2022-03-07T20:56:57.358Z workers Starting run worker instance #5\n',
    '2022-03-07T20:56:57.358Z workers Starting run worker instance #6\n',
    '2022-03-07T20:56:57.358Z workers Starting run worker instance #7\n',
    '2022-03-07T20:56:57.358Z workers Starting run worker instance #8\n',
    '2022-03-07T20:56:57.358Z workers Starting run worker instance #9\n',
    '2022-03-07T20:56:57.358Z workers Starting run worker instance #10\n',
    '2022-03-07T20:56:57.358Z workers Starting run worker instance #11\n',
    '2022-03-07T20:56:57.358Z workers Starting run worker instance #12\n',
    '2022-03-07T20:56:57.358Z workers Starting run worker instance #13\n',
    '2022-03-07T20:56:57.358Z workers Web server is listening at 52554\n',
    '2022-03-07T20:56:57.358Z project File cache requires some updates, waiting required files from IDE\n',
    '2022-03-07T20:56:57.434Z project Stopping process pool\n',
    '2022-03-07T20:56:57.436Z project Test run started; run priority: 3\n',
    '2022-03-07T20:56:57.437Z project Running all tests\n',
    '2022-03-07T20:56:57.440Z workers Starting test run, priority: 3\n',
    '2022-03-07T20:56:57.440Z nodeRunner Starting sandbox [worker #0, session #00gn5]\n',
    '2022-03-07T20:56:57.440Z nodeRunner Preparing sandbox [worker #0, session #00gn5]\n',
    '2022-03-07T20:56:57.546Z workers Started run worker instance (delayed) #0\n',
    '2022-03-07T20:56:57.546Z nodeRunner Prepared sandbox [worker #0, session #00gn5]\n',
    '2022-03-07T20:56:57.547Z workers [worker #0, session #00gn5] Running tests in sandbox\n',
    '2022-03-07T20:56:57.551Z workers Started run worker instance (delayed) #1\n',
    '2022-03-07T20:56:57.557Z workers Started run worker instance (delayed) #2\n',
    '2022-03-07T20:56:57.563Z workers Started run worker instance (delayed) #3\n',
    '2022-03-07T20:56:57.564Z workers Started run worker instance (delayed) #4\n',
    '2022-03-07T20:56:57.568Z workers Started run worker instance (delayed) #5\n',
    '2022-03-07T20:56:57.572Z workers Started run worker instance (delayed) #6\n',
    '2022-03-07T20:56:57.581Z workers Started run worker instance (delayed) #7\n',
    '2022-03-07T20:56:57.582Z workers Started run worker instance (delayed) #8\n',
    '2022-03-07T20:56:57.588Z workers Started run worker instance (delayed) #9\n',
    '2022-03-07T20:56:57.591Z workers Started run worker instance (delayed) #10\n',
    '2022-03-07T20:56:57.598Z workers Started run worker instance (delayed) #11\n',
    '2022-03-07T20:56:57.601Z workers Started run worker instance (delayed) #12\n',
    '2022-03-07T20:56:57.605Z workers Started run worker instance (delayed) #13\n',
    '2022-03-07T20:57:00.280Z workers Scheduling Jest Test Run (00gn5): 2022-03-07T20:56:58.161Z\n',
    '2022-03-07T20:57:00.284Z workers [00gn5] Loaded unknown number of test(s)\n',
    '2022-03-07T20:57:00.284Z workers [00gn5] Test executed: should return a message\n',
    '2022-03-07T20:57:00.286Z workers [00gn5] Run 1 test(s), skipped 0 test(s)\n',
    '2022-03-07T20:57:00.286Z workers Jest Test Run Complete (00gn5): 2022-03-07T20:57:00.279Z\n',
    '2022-03-07T20:57:00.287Z workers [00gn5] Sandbox is responsive, closing it\n',
    '2022-03-07T20:57:00.288Z project Test run finished\n',
    '2022-03-07T20:57:00.288Z project Processed console.log entries\n',
    '2022-03-07T20:57:00.288Z project Processed loading sequences\n',
    '2022-03-07T20:57:00.288Z project Processed executed tests\n',
    '2022-03-07T20:57:00.289Z project Processed code coverage\n',
    '2022-03-07T20:57:00.302Z project Test run result processed and sent to IDE\n',
    '2022-03-07T20:57:18.335Z fs File changed in editor: src/__tests__/utils.test.ts\n',
    '2022-03-07T20:57:18.345Z project Test run started; run priority: 2\n',
    '2022-03-07T20:57:18.345Z testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2022-03-07T20:57:18.346Z workers Starting test run, priority: 2\n',
    '2022-03-07T20:57:18.346Z nodeRunner Starting sandbox [worker #0, session #425c7]\n',
    '2022-03-07T20:57:18.346Z nodeRunner Preparing sandbox [worker #0, session #425c7]\n',
    '2022-03-07T20:57:18.346Z nodeRunner Prepared sandbox [worker #0, session #425c7]\n',
    '2022-03-07T20:57:18.346Z workers [worker #0, session #425c7] Running tests in sandbox\n',
    '2022-03-07T20:57:18.482Z workers Scheduling Jest Test Run (425c7): 2022-03-07T20:57:18.349Z\n',
    "2022-03-07T20:57:18.483Z workers Sandbox (active) [425c7] error: ENOENT: no such file or directory, open '/private/var/folders/1c/877fdzzj05v1vyy_h41r8cqw0000gn/T/jest_dx/ts-jest/59/50e1ce89804c93162ae88817e039dd3bcb0213/e9a8ee471bc676fe755c57379268f21a1390a7a4'\n",
    '2022-03-07T20:57:18.485Z workers [425c7] Run 0 test(s), skipped 0 test(s)\n',
    '2022-03-07T20:57:18.485Z workers Jest Test Run Complete (425c7): 2022-03-07T20:57:18.481Z\n',
    '2022-03-07T20:57:18.486Z workers [425c7] Sandbox is responsive, closing it\n',
    "2022-03-07T20:57:18.487Z workers Failed to map the stack to user code, entry message: ENOENT: no such file or directory, open '/private/var/folders/1c/877fdzzj05v1vyy_h41r8cqw0000gn/T/jest_dx/ts-jest/59/50e1ce89804c93162ae88817e039dd3bcb0213/e9a8ee471bc676fe755c57379268f21a1390a7a4', stack: Error: ENOENT: no such file or directory, open '/private/var/folders/1c/877fdzzj05v1vyy_h41r8cqw0000gn/T/jest_dx/ts-jest/59/50e1ce89804c93162ae88817e039dd3bcb0213/e9a8ee471bc676fe755c57379268f21a1390a7a4'\n" +
      '    at Object.openSync (fs.js:498:3)\n' +
      '    at writeFileSync (fs.js:1524:35)\n' +
      '    at fs.writeFileSync (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.327/wallaby2dd020/runners/node/jest@24.8.0/initializer.js:14:31261)\n' +
      '    at TsJestTransformer.getCacheKey (<homeDir>/x/node_modules/ts-jest/dist/ts-jest-transformer.js:245:40)\n' +
      '    at TsJestTransformer.e.getCacheKey (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.327/wallaby2dd020/runners/node/jest@24.8.0/initializer.js:15:1015)\n' +
      '    at ScriptTransformer._getCacheKey (<homeDir>/x/node_modules/@jest/transform/build/ScriptTransformer.js:281:41)\n' +
      '    at ScriptTransformer._getFileCachePath (<homeDir>/x/node_modules/@jest/transform/build/ScriptTransformer.js:352:27)\n' +
      '    at ScriptTransformer.transformSource (<homeDir>/x/node_modules/@jest/tr\n',
    '2022-03-07T20:57:18.487Z project Test run finished\n',
    '2022-03-07T20:57:18.488Z project Processed console.log entries\n',
    '2022-03-07T20:57:18.488Z project Processed loading sequences\n',
    '2022-03-07T20:57:18.488Z project Processed executed tests\n',
    '2022-03-07T20:57:18.488Z project Processed code coverage\n',
    '2022-03-07T20:57:18.491Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by smcenlly** [comment]
This is expected behavior and not something that we can reasonably handle in Wallaby. 

When you run Wallaby with Jest, Wallaby executes your tests with Jest (and `ts-jest`) and by clearing the cache, you're effectively removing files from a running application that is relying on them.

In your case, [this line of code](https://github.com/kulshekhar/ts-jest/blob/dced8c9661352d00d5b8576e662697e564c5d50d/src/ts-jest-transformer.ts#L266) from `ts-jest` is causing a problem because the parent directory (that is expected to exist) no longer exists.

There's no global event we can hook into to easily know that the jest cache has been reset.

You will find that you get the same error if running jest from the command line (e.g. in watch mode) and clearing the cache in a different terminal session.

![image](https://user-images.githubusercontent.com/2074089/157131670-08b2514e-9971-42c6-b6e1-0fc55f5facfd.png)

---

Even if `ts-jest` were to check for the directory's existence (and created it if required) to fix this issue, I would not be surprised if there are other issues that happen if jest is already running when you clear the cache. If jest/ts-jest are updated to support clearing the cache while tests are running in watch mode, then Wallaby should work for you too.
