### ISSUE TITLE
Inline snapshot updates wrong part of line

### ISSUE THREAD

**Issue by puddii** [wallabyjs/public#2963]
### Issue description or question

When I use Wallaby with Testing Library and Jest inline snapshots, Wallaby sometimes inserts the snapshot into the wrong part of the line. I was able to reproduce this issue with my own function.

Starting with this file:

```js
const example = {
  function: (value) => value,
};

test("inline snapshot", () => {
  expect(example.function("example value")).toMatchInlineSnapshot();
});
```

Jest produces this output:

```js
const example = {
  function: (value) => value,
};

test("inline snapshot", () => {
  expect(example.function("example value")).toMatchInlineSnapshot(`"example value"`);
});
```

Wallaby produces this output:

```js
const example = {
  function: (value) => value,
};

test("inline snapshot", () => {
  expect(example.function("example value", `"example value"`)).toMatchInlineSnapshot();
});
```

### Wallaby diagnostics report

```
{
  editorVersion: '1.66.0',
  pluginVersion: '1.0.334',
  editorType: 'VSCode',
  osVersion: 'darwin 21.4.0',
  nodeVersion: 'v16.14.2',
  coreVersion: '1.0.1252',
  checksum: 'ODE0ZDdjYTFmNGNiMmZlM2MxMDcwMzYzM2ZmZDVmYmQsMTY4MDY1MjgwMDAwMCww',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/private/var/folders/g_/ktlmsm391ms597jd3xy9_58w0000gn/T/jest_dx',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/Desktop/wallaby-inline-snapshot',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: undefined,
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              extraGlobals: [],
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: false, throwOnModuleCollision: false },
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [ 'js', 'jsx', 'ts', 'tsx', 'json', 'node' ],
              moduleLoader: undefined,
              moduleNameMapper: [],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              name: '780775bda64b30356ea65b95f80e0685',
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/Desktop/wallaby-inline-snapshot',
              roots: [ '<homeDir>/Desktop/wallaby-inline-snapshot' ],
              runner: '<homeDir>/Desktop/wallaby-inline-snapshot/node_modules/jest-runner/build/index.js',
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/Desktop/wallaby-inline-snapshot/node_modules/jest-environment-node/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<homeDir>/Desktop/wallaby-inline-snapshot/node_modules/jest-circus/runner.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [ [ '\\.[jt]sx?$', '<homeDir>/Desktop/wallaby-inline-snapshot/node_modules/babel-jest/build/index.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: [],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<homeDir>/Desktop/wallaby-inline-snapshot/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 15,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/Desktop/wallaby-inline-snapshot',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: undefined,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/Desktop/wallaby-inline-snapshot/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/g_/ktlmsm391ms597jd3xy9_58w0000gn/T/jest_dx', '\\./coverage' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/g_/ktlmsm391ms597jd3xy9_58w0000gn/T/jest_dx', '\\./coverage' ],
            testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    micromatch: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
      { pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//, ignore: true, trigger: true, load: true },
      {
        pattern: '/private/var/folders/g_/ktlmsm391ms597jd3xy9_58w0000gn/T/jest_dx',
        regexp: /\/private\/var\/folders\/g_\/ktlmsm391ms597jd3xy9_58w0000gn\/T\/jest_dx/,
        ignore: true,
        trigger: true,
        load: true
      },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      {
        pattern: '/private/var/folders/g_/ktlmsm391ms597jd3xy9_58w0000gn/T/jest_dx',
        regexp: /\/private\/var\/folders\/g_\/ktlmsm391ms597jd3xy9_58w0000gn\/T\/jest_dx/,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, test: true },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '/usr/local/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#667818852'
  },
  packageJSON: { dependencies: undefined, devDependencies: { jest: '^27.5.1' } },
  fs: { numberOfFiles: 3 },
  debug: [
    '2022-04-05T02:22:27.867Z angular/cli config Angular CLI not found.\n',
    '2022-04-05T02:22:28.006Z jest/config Detected Jest.\n',
    '2022-04-05T02:22:28.006Z jest/config Configured Jest.\n',
    '2022-04-05T02:22:28.008Z project Wallaby Node version: v16.14.2\n',
    '2022-04-05T02:22:28.008Z project Wallaby config: <homeDir>/Desktop/wallaby-inline-snapshot/auto.detect\n',
    '2022-04-05T02:22:28.046Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.334/projects/1c017c36b1da7f2e\n',
    '2022-04-05T02:22:28.136Z uiService Listening port 51235\n',
    '2022-04-05T02:22:28.146Z workers Parallelism for initial run: 14, for regular run: 7\n',
    '2022-04-05T02:22:28.146Z workers Starting run worker instance #0\n',
    '2022-04-05T02:22:28.146Z workers Starting run worker instance #1\n',
    '2022-04-05T02:22:28.146Z workers Starting run worker instance #2\n',
    '2022-04-05T02:22:28.147Z workers Starting run worker instance #3\n',
    '2022-04-05T02:22:28.147Z workers Starting run worker instance #4\n',
    '2022-04-05T02:22:28.147Z workers Starting run worker instance #5\n',
    '2022-04-05T02:22:28.147Z workers Starting run worker instance #6\n',
    '2022-04-05T02:22:28.147Z workers Starting run worker instance #7\n',
    '2022-04-05T02:22:28.147Z workers Starting run worker instance #8\n',
    '2022-04-05T02:22:28.147Z workers Starting run worker instance #9\n',
    '2022-04-05T02:22:28.147Z workers Starting run worker instance #10\n',
    '2022-04-05T02:22:28.147Z workers Starting run worker instance #11\n',
    '2022-04-05T02:22:28.147Z workers Starting run worker instance #12\n',
    '2022-04-05T02:22:28.147Z workers Starting run worker instance #13\n',
    '2022-04-05T02:22:28.147Z workers Web server is listening at 56520\n',
    '2022-04-05T02:22:28.147Z project File cache requires some updates, waiting required files from IDE\n',
    '2022-04-05T02:22:28.235Z project Stopping process pool\n',
    '2022-04-05T02:22:28.236Z project Test run started; run priority: 3\n',
    '2022-04-05T02:22:28.238Z project Running all tests\n',
    '2022-04-05T02:22:28.241Z workers Starting test run, priority: 3\n',
    '2022-04-05T02:22:28.241Z nodeRunner Starting sandbox [worker #0, session #dj21p]\n',
    '2022-04-05T02:22:28.241Z nodeRunner Preparing sandbox [worker #0, session #dj21p]\n',
    '2022-04-05T02:22:28.398Z workers Started run worker instance (delayed) #0\n',
    '2022-04-05T02:22:28.398Z nodeRunner Prepared sandbox [worker #0, session #dj21p]\n',
    '2022-04-05T02:22:28.399Z workers [worker #0, session #dj21p] Running tests in sandbox\n',
    '2022-04-05T02:22:28.403Z workers Started run worker instance (delayed) #1\n',
    '2022-04-05T02:22:28.404Z workers Started run worker instance (delayed) #2\n',
    '2022-04-05T02:22:28.409Z workers Started run worker instance (delayed) #3\n',
    '2022-04-05T02:22:28.413Z workers Started run worker instance (delayed) #4\n',
    '2022-04-05T02:22:28.416Z workers Started run worker instance (delayed) #5\n',
    '2022-04-05T02:22:28.416Z workers Started run worker instance (delayed) #6\n',
    '2022-04-05T02:22:28.416Z workers Started run worker instance (delayed) #7\n',
    '2022-04-05T02:22:28.421Z workers Started run worker instance (delayed) #8\n',
    '2022-04-05T02:22:28.422Z workers Started run worker instance (delayed) #9\n',
    '2022-04-05T02:22:28.425Z workers Started run worker instance (delayed) #10\n',
    '2022-04-05T02:22:28.430Z workers Started run worker instance (delayed) #11\n',
    '2022-04-05T02:22:28.438Z workers Started run worker instance (delayed) #12\n',
    '2022-04-05T02:22:28.459Z workers Started run worker instance (delayed) #13\n',
    '2022-04-05T02:22:29.380Z workers Scheduling Jest Test Run (dj21p): 2022-04-05T02:22:28.788Z\n',
    '2022-04-05T02:22:29.384Z workers [dj21p] Loaded unknown number of test(s)\n',
    '2022-04-05T02:22:29.384Z workers [dj21p] Test executed: inline snapshot\n',
    '2022-04-05T02:22:29.385Z workers [dj21p] Run 1 test(s), skipped 0 test(s)\n',
    '2022-04-05T02:22:29.386Z workers Jest Test Run Complete (dj21p): 2022-04-05T02:22:29.379Z\n',
    '2022-04-05T02:22:29.387Z workers [dj21p] Sandbox is responsive, closing it\n',
    '2022-04-05T02:22:29.388Z project Test run finished\n',
    '2022-04-05T02:22:29.388Z project Processed console.log entries\n',
    '2022-04-05T02:22:29.388Z project Processed loading sequences\n',
    '2022-04-05T02:22:29.388Z project Processed executed tests\n',
    '2022-04-05T02:22:29.389Z project Processed code coverage\n',
    '2022-04-05T02:22:29.397Z project Test run result processed and sent to IDE\n',
    '2022-04-05T02:22:29.517Z fs File changed in editor: snapshot.test.js\n',
    '2022-04-05T02:22:29.524Z project Test run started; run priority: 2\n',
    '2022-04-05T02:22:29.525Z testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2022-04-05T02:22:29.525Z workers Starting test run, priority: 2\n',
    '2022-04-05T02:22:29.525Z nodeRunner Starting sandbox [worker #0, session #ozyv0]\n',
    '2022-04-05T02:22:29.525Z nodeRunner Preparing sandbox [worker #0, session #ozyv0]\n',
    '2022-04-05T02:22:29.525Z nodeRunner Prepared sandbox [worker #0, session #ozyv0]\n',
    '2022-04-05T02:22:29.526Z workers [worker #0, session #ozyv0] Running tests in sandbox\n',
    '2022-04-05T02:22:29.647Z workers Scheduling Jest Test Run (ozyv0): 2022-04-05T02:22:29.527Z\n',
    '2022-04-05T02:22:29.648Z workers [ozyv0] Loaded unknown number of test(s)\n',
    '2022-04-05T02:22:29.649Z workers [ozyv0] Test executed: inline snapshot\n',
    '2022-04-05T02:22:29.651Z workers [ozyv0] Run 1 test(s), skipped 0 test(s)\n',
    '2022-04-05T02:22:29.652Z workers Jest Test Run Complete (ozyv0): 2022-04-05T02:22:29.641Z\n',
    '2022-04-05T02:22:29.656Z workers [ozyv0] Sandbox is responsive, closing it\n',
    '2022-04-05T02:22:29.656Z project Test run finished\n',
    '2022-04-05T02:22:29.656Z project Processed console.log entries\n',
    '2022-04-05T02:22:29.656Z project Processed loading sequences\n',
    '2022-04-05T02:22:29.656Z project Processed executed tests\n',
    '2022-04-05T02:22:29.656Z project Processed code coverage\n',
    '2022-04-05T02:22:29.658Z project Test run result processed and sent to IDE\n',
    '2022-04-05T02:22:37.085Z fs File changed: snapshot.test.js\n',
    '2022-04-05T02:22:37.092Z project Test run started; run priority: 2\n',
    '2022-04-05T02:22:37.092Z testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2022-04-05T02:22:37.093Z workers Starting test run, priority: 2\n',
    '2022-04-05T02:22:37.093Z nodeRunner Starting sandbox [worker #0, session #ccl74]\n',
    '2022-04-05T02:22:37.093Z nodeRunner Preparing sandbox [worker #0, session #ccl74]\n',
    '2022-04-05T02:22:37.093Z nodeRunner Prepared sandbox [worker #0, session #ccl74]\n',
    '2022-04-05T02:22:37.093Z workers [worker #0, session #ccl74] Running tests in sandbox\n',
    '2022-04-05T02:22:37.132Z fs File changed in editor: snapshot.test.js\n',
    '2022-04-05T02:22:37.132Z fs No changes detected for snapshot.test.js\n',
    '2022-04-05T02:22:37.216Z workers Scheduling Jest Test Run (ccl74): 2022-04-05T02:22:37.094Z\n',
    '2022-04-05T02:22:37.217Z workers [ccl74] Loaded unknown number of test(s)\n',
    '2022-04-05T02:22:37.217Z workers [ccl74] Test executed: inline snapshot\n',
    "2022-04-05T02:22:37.218Z workers Sandbox (active) [ccl74] error: Jest: Couldn't locate all inline snapshots.\n",
    '2022-04-05T02:22:37.220Z workers [ccl74] Run 1 test(s), skipped 0 test(s)\n',
    '2022-04-05T02:22:37.220Z workers Jest Test Run Complete (ccl74): 2022-04-05T02:22:37.215Z\n',
    '2022-04-05T02:22:37.221Z workers [ccl74] Sandbox is responsive, closing it\n',
    "2022-04-05T02:22:37.223Z workers Failed to map the stack to user code, entry message: Jest: Couldn't locate all inline snapshots., stack: Error: Jest: Couldn't locate all inline snapshots.\n" +
      '    at traverseAst (<homeDir>/Desktop/wallaby-inline-snapshot/node_modules/jest-snapshot/build/InlineSnapshots.js:377:11)\n' +
      '    at saveSnapshotsForFile (<homeDir>/Desktop/wallaby-inline-snapshot/node_modules/jest-snapshot/build/InlineSnapshots.js:229:3)\n' +
      '    at saveInlineSnapshots (<homeDir>/Desktop/wallaby-inline-snapshot/node_modules/jest-snapshot/build/InlineSnapshots.js:190:5)\n' +
      '    at SnapshotState.save (<homeDir>/Desktop/wallaby-inline-snapshot/node_modules/jest-snapshot/build/State.js:236:52)\n' +
      '    at _addSnapshotData (<homeDir>/Desktop/wallaby-inline-snapshot/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:112:32)\n' +
      '    at jestAdapter (<homeDir>/Desktop/wallaby-inline-snapshot/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:88:3)\n' +
      '    at runTestInternal (<homeDir>/Desktop/wallaby-inline-snapshot/node_modules/jest-runner/build/runTest.js:389:16)\n' +
      '    at runTest (<homeDir>/Deskto\n',
    '2022-04-05T02:22:37.223Z project Test run finished\n',
    '2022-04-05T02:22:37.223Z project Processed console.log entries\n',
    '2022-04-05T02:22:37.223Z project Processed loading sequences\n',
    '2022-04-05T02:22:37.223Z project Processed executed tests\n',
    '2022-04-05T02:22:37.223Z project Processed code coverage\n',
    '2022-04-05T02:22:37.227Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
Thanks for submitting the report. The issue is fixed and the fix is published in the [latest Wallaby Core v1.0.1253](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
