### ISSUE TITLE
Chrome runner error: ReferenceError: process is not defined

### ISSUE THREAD

**Issue by MeltedYeti** [wallabyjs/public#2974]
### Unable to launch chrome... I think

I am hoping someone here is able to help, I have recently begun work with a new company on new projects and I am attempting to get Wallaby up and running. The application under test is an Angular CLI application though there are differences in file locations for some things. I have tried to do a manual configuration but it was having issues loading the tsconfig for some reason that I cannot understand, at least that is what it looked like. If I do a no configuration setup it almost works but it cannot launch chrome.

### Wallaby diagnostics report

```
{
  editorVersion: 'WebStorm 2022.1',
  pluginVersion: '1.0.238',
  editorType: 'IntelliJ',
  osVersion: 'darwin 19.6.0',
  nodeVersion: 'v12.21.0',
  coreVersion: '1.0.1256',
  checksum: 'MjNmMjg1ZTQwZjM4OGFiYTdlZjc1YmRlM2QyYjFhYjAsMTY1NDkwNTYwMDAwMCww',
  config: {
    diagnostics: {
      angular: {
        workspace: {
          '$schema': './node_modules/@angular/cli/lib/config/schema.json',
          version: 1,
          newProjectRoot: 'projects',
          projects: {
            'se-partner-activation-ui': {
              projectType: 'application',
              schematics: { '@schematics/angular:component': { style: 'scss' } },
              root: 'projects/se-partner-activation-ui',
              sourceRoot: 'projects/se-partner-activation-ui/src',
              prefix: 'app',
              architect: {
                build: {
                  builder: '@angular-devkit/build-angular:browser',
                  options: {
                    outputPath: 'dist/se-partner-activation-ui',
                    index: 'projects/se-partner-activation-ui/src/index.html',
                    main: 'projects/se-partner-activation-ui/src/main.ts',
                    polyfills: 'projects/se-partner-activation-ui/src/polyfills.ts',
                    tsConfig: 'projects/se-partner-activation-ui/tsconfig.app.json',
                    aot: true,
                    assets: [ 'projects/se-partner-activation-ui/src/favicon.ico', 'projects/se-partner-activation-ui/src/assets' ],
                    styles: [ 'projects/se-partner-activation-ui/src/styles.scss' ],
                    scripts: []
                  },
                  configurations: {
                    production: {
                      fileReplacements: [ { replace: 'projects/se-partner-activation-ui/src/environments/environment.ts', with: 'projects/se-partner-activation-ui/src/environments/environment.prod.ts' } ],
                      optimization: true,
                      outputHashing: 'all',
                      sourceMap: false,
                      namedChunks: false,
                      extractLicenses: true,
                      vendorChunk: false,
                      buildOptimizer: true,
                      budgets: [ { type: 'initial', maximumWarning: '2mb', maximumError: '5mb' }, { type: 'anyComponentStyle', maximumWarning: '6kb', maximumError: '10kb' } ]
                    },
                    staging: {
                      fileReplacements: [ { replace: 'projects/se-partner-activation-ui/src/environments/environment.ts', with: 'projects/se-partner-activation-ui/src/environments/environment.staging.ts' } ],
                      optimization: true,
                      outputHashing: 'all',
                      sourceMap: false,
                      namedChunks: false,
                      extractLicenses: true,
                      vendorChunk: false,
                      buildOptimizer: true,
                      budgets: [ { type: 'initial', maximumWarning: '2mb', maximumError: '5mb' }, { type: 'anyComponentStyle', maximumWarning: '6kb', maximumError: '10kb' } ]
                    },
                    'dev-staging': {
                      fileReplacements: [
                        { replace: 'projects/se-partner-activation-ui/src/environments/environment.ts', with: 'projects/se-partner-activation-ui/src/environments/environment.dev-staging.ts' }
                      ],
                      preserveSymlinks: true
                    }
                  }
                },
                serve: {
                  builder: '@angular-builders/custom-webpack:dev-server',
                  options: {
                    browserTarget: 'se-partner-activation-ui:build',
                    host: 'sales-channel-activation.sportsengine.com.dev',
                    port: 5050,
                    publicHost: 'https://sales-channel-activation.sportsengine.com.dev'
                  },
                  configurations: {
                    production: { browserTarget: 'se-partner-activation-ui:build:production' },
                    staging: { browserTarget: 'se-partner-activation-ui:build:staging' },
                    'dev-staging': { browserTarget: 'se-partner-activation-ui:build:dev-staging' }
                  }
                },
                'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: 'se-partner-activation-ui:build' } },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    main: 'projects/se-partner-activation-ui/src/test.ts',
                    polyfills: 'projects/se-partner-activation-ui/src/polyfills.ts',
                    tsConfig: 'projects/se-partner-activation-ui/tsconfig.spec.json',
                    karmaConfig: 'projects/se-partner-activation-ui/karma.conf.js',
                    assets: [ 'projects/se-partner-activation-ui/src/favicon.ico', 'projects/se-partner-activation-ui/src/assets' ],
                    styles: [ 'projects/se-partner-activation-ui/src/styles.scss' ],
                    scripts: [],
                    codeCoverageExclude: [ 'projects/se-partner-activation-ui/src/testing/**/*' ]
                  }
                },
                lint: { builder: '@angular-eslint/builder:lint', options: { lintFilePatterns: [ 'projects/se-partner-activation-ui/**/*.ts', 'projects/se-partner-activation-ui/**/*.html' ] } },
                e2e: {
                  builder: '@angular-devkit/build-angular:protractor',
                  options: { protractorConfig: 'projects/se-partner-activation-ui/e2e/protractor.conf.js', devServerTarget: 'se-partner-activation-ui:serve' },
                  configurations: { production: { devServerTarget: 'se-partner-activation-ui:serve:production' } }
                }
              }
            }
          },
          defaultProject: 'se-partner-activation-ui',
          cli: { defaultCollection: '@angular-eslint/schematics' }
        },
        main: "import 'zone.js/dist/zone-testing';\n" +
          "import { getTestBed } from '@angular/core/testing';\n" +
          'import {\n' +
          '  BrowserDynamicTestingModule,\n' +
          '  platformBrowserDynamicTesting\n' +
          "} from '@angular/platform-browser-dynamic/testing';\n" +
          '\n' +
          '// shared imports for all your projects\n' +
          '// imports for app-a, lib-b, lib-c, app-d etc.\n' +
          '\n' +
          '// shared code for all your projects\n' +
          '// code for app-a, lib-b, lib-c, app-d etc.\n' +
          '\n' +
          '// First, initialize the Angular testing environment.\n' +
          'getTestBed().initTestEnvironment(\n' +
          '  BrowserDynamicTestingModule,\n' +
          '  platformBrowserDynamicTesting()\n' +
          ');\n' +
          '\n' +
          '// shared code for all your projects\n' +
          '// code for app-a, lib-b, lib-c, app-d etc.\n'
      }
    },
    testFramework: { version: 'jasmine@3.10.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3', autoDetected: true },
    env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    files: [
      { pattern: 'projects/se-partner-activation-ui/src/**/*.spec.ts', ignore: true, trigger: true, load: true },
      { pattern: 'projects/se-partner-activation-ui/src/polyfills.ts', ignore: true, trigger: true, load: true },
      { pattern: 'projects/se-partner-activation-ui/src/test.ts', ignore: true, trigger: true, load: true },
      { pattern: 'projects/se-partner-activation-ui/src/main.ts', ignore: true, trigger: true, load: true },
      { pattern: 'projects/se-partner-activation-ui/src/index.html', ignore: true, trigger: true, load: true },
      { pattern: 'projects/se-partner-activation-ui/src/test.base.ts', ignore: true, trigger: true, load: true },
      { pattern: 'projects/se-partner-activation-ui/src/test.wallaby.ts', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'projects/se-partner-activation-ui/src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 2 },
      { pattern: 'projects/se-partner-activation-ui/src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 3 }
    ],
    tests: [ { pattern: 'projects/se-partner-activation-ui/src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 4 } ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#-1310445100'
  },
  packageJSON: {
    dependencies: {
      '@angular/animations': '~11.2.14',
      '@angular/common': '~11.2.14',
      '@angular/compiler': '~11.2.14',
      '@angular/core': '~11.2.14',
      '@angular/forms': '~11.2.14',
      '@angular/platform-browser': '~11.2.14',
      '@angular/platform-browser-dynamic': '~11.2.14',
      '@angular/router': '~11.2.14',
      luxon: '^2.3.1',
      rxjs: '~6.6.0',
      sass: '^1.49.9',
      'sass-loader': '^12.6.0',
      'se-fe-accordion': '^1.0.1',
      'se-fe-alert': '^1.0.0',
      'se-fe-attachment-service': '1.0.0',
      'se-fe-auth-support': '^2.3.0',
      'se-fe-button': '^1.1.0',
      'se-fe-card': '^2.0.0 ',
      'se-fe-core': '^1.0.4',
      'se-fe-frame-router': '^1.4.0',
      'se-fe-grid': '^2.0.0',
      'se-fe-guide': '^1.2.0',
      'se-fe-header': '^2.0.0',
      'se-fe-icon': '^1.8.1',
      'se-fe-image-uploader': '1.1.0',
      'se-fe-inline-list': '^1.0.0',
      'se-fe-modal': '^2.0.0',
      'se-fe-progress-bar': '^2.0.1',
      'se-fe-scroll': '^1.0.3',
      'se-fe-spinner': '^1.0.1',
      'se-form-components': '^1.4.2',
      tslib: '^2.0.0',
      'zone.js': '~0.10.2'
    },
    devDependencies: {
      '@angular-builders/custom-webpack': '^11.1.1',
      '@angular-devkit/build-angular': '~0.1102.18',
      '@angular-eslint/builder': '4.3.1',
      '@angular-eslint/eslint-plugin': '4.3.1',
      '@angular-eslint/eslint-plugin-template': '4.3.1',
      '@angular-eslint/schematics': '4.3.1',
      '@angular-eslint/template-parser': '4.3.1',
      '@angular/cli': '~11.2.18',
      '@angular/compiler-cli': '~11.2.14',
      '@types/jasmine': '~3.6.0',
      '@types/jasminewd2': '~2.0.3',
      '@types/node': '^12.20.47',
      '@typescript-eslint/eslint-plugin': '4.16.1',
      '@typescript-eslint/parser': '4.16.1',
      eslint: '^7.6.0',
      'jasmine-core': '~3.6.0',
      'jasmine-spec-reporter': '~5.0.0',
      karma: '~6.3.17',
      'karma-chrome-launcher': '~3.1.1',
      'karma-coverage': '~2.2.0',
      'karma-jasmine': '~4.0.2',
      'karma-jasmine-html-reporter': '^1.5.0',
      'ng-packagr': '^11.2.4',
      prettier: '^2.6.1',
      protractor: '~7.0.0',
      'sass-loader': '^12.6.0',
      'ts-node': '~8.3.0',
      typescript: '~4.0.8',
      'wallaby-webpack': '^3.9.16'
    }
  },
  fs: { numberOfFiles: 163 },
  debug: [
    '2022-04-20T14:33:26.052Z angular/cli config Detected Angular CLI.\n',
    '2022-04-20T14:33:26.053Z angular/cli config Angular currentDirPath: "<homeDir>/sportsengine/se-partner-activation-ui", workspaceDirPath: "<homeDir>/sportsengine/se-partner-activation-ui"\n',
    '2022-04-20T14:33:28.448Z angular/cli karma project config Using physical <homeDir>/sportsengine/se-partner-activation-ui/projects/se-partner-activation-ui/src/test.wallaby.ts.\n',
    '2022-04-20T14:33:28.466Z project Wallaby Node version: v12.21.0\n',
    '2022-04-20T14:33:28.466Z project Wallaby config: <homeDir>/sportsengine/se-partner-activation-ui/auto.detect\n',
    '2022-04-20T14:33:28.593Z project File cache: <homeDir>/Library/Caches/JetBrains/WebStorm2022.1/wallaby/projects/bebcb3081a6593fe\n',
    '2022-04-20T14:33:28.657Z uiService Listening port 51235\n',
    '2022-04-20T14:33:28.704Z workers Parallelism for initial run: 14, for regular run: 7\n',
    '2022-04-20T14:33:28.704Z workers Starting run worker instance #0\n',
    '2022-04-20T14:33:28.704Z workers Starting run worker instance #1\n',
    '2022-04-20T14:33:28.704Z workers Starting run worker instance #2\n',
    '2022-04-20T14:33:28.704Z workers Starting run worker instance #3\n',
    '2022-04-20T14:33:28.704Z workers Starting run worker instance #4\n',
    '2022-04-20T14:33:28.704Z workers Starting run worker instance #5\n',
    '2022-04-20T14:33:28.704Z workers Starting run worker instance #6\n',
    '2022-04-20T14:33:28.704Z workers Starting run worker instance #7\n',
    '2022-04-20T14:33:28.704Z workers Starting run worker instance #8\n',
    '2022-04-20T14:33:28.704Z workers Starting run worker instance #9\n',
    '2022-04-20T14:33:28.704Z workers Starting run worker instance #10\n',
    '2022-04-20T14:33:28.704Z workers Starting run worker instance #11\n',
    '2022-04-20T14:33:28.704Z workers Starting run worker instance #12\n',
    '2022-04-20T14:33:28.704Z workers Starting run worker instance #13\n',
    '2022-04-20T14:33:28.706Z workers Web server is listening at 62913\n',
    '2022-04-20T14:33:28.711Z project Stopping process pool\n',
    '2022-04-20T14:33:28.712Z project File cache is up-to-date, starting full test run\n',
    '2022-04-20T14:33:28.719Z project Running postprocessor\n',
    '2022-04-20T14:33:28.723Z postprocessor Processing started.\n',
    '2022-04-20T14:33:28.723Z postprocessor Initializing.\n',
    '2022-04-20T14:33:28.726Z postprocessor Initializing entry.\n',
    '2022-04-20T14:33:28.727Z postprocessor Sanitizing configuration.\n',
    '2022-04-20T14:33:28.727Z postprocessor Adjusting configuration.\n',
    '2022-04-20T14:33:28.729Z postprocessor Creating compiler.\n',
    '2022-04-20T14:33:28.869Z postprocessor Customizing compiler.\n',
    '2022-04-20T14:33:28.870Z postprocessor Compilation started.\n',
    '2022-04-20T14:33:33.017Z workers Started run worker instance (immediate) #0\n',
    '2022-04-20T14:33:33.017Z workers Started run worker instance (immediate) #1\n',
    '2022-04-20T14:33:33.017Z workers Started run worker instance (immediate) #2\n',
    '2022-04-20T14:33:33.017Z workers Started run worker instance (immediate) #3\n',
    '2022-04-20T14:33:33.017Z workers Started run worker instance (immediate) #4\n',
    '2022-04-20T14:33:33.017Z workers Started run worker instance (immediate) #5\n',
    '2022-04-20T14:33:33.017Z workers Started run worker instance (immediate) #6\n',
    '2022-04-20T14:33:33.017Z workers Started run worker instance (immediate) #7\n',
    '2022-04-20T14:33:33.017Z workers Started run worker instance (immediate) #8\n',
    '2022-04-20T14:33:33.017Z workers Started run worker instance (immediate) #9\n',
    '2022-04-20T14:33:33.017Z workers Started run worker instance (immediate) #10\n',
    '2022-04-20T14:33:33.017Z workers Started run worker instance (immediate) #11\n',
    '2022-04-20T14:33:33.017Z workers Started run worker instance (immediate) #12\n',
    '2022-04-20T14:33:33.017Z workers Started run worker instance (immediate) #13\n',
    '2022-04-20T14:33:35.125Z postprocessor Compilation finished.\n',
    '2022-04-20T14:33:35.282Z postprocessor Emitting 401 files.\n',
    '2022-04-20T14:33:35.289Z postprocessor Processing finished.\n',
    '2022-04-20T14:33:35.331Z project Postprocessor execution finished\n',
    '2022-04-20T14:33:35.331Z project Test run started; run priority: 3\n',
    '2022-04-20T14:33:35.333Z project Running all tests\n',
    '2022-04-20T14:33:35.338Z workers Starting test run, priority: 3\n',
    '2022-04-20T14:33:35.338Z chromeRunner Starting sandbox [worker #0, session #b882f]\n',
    '2022-04-20T14:33:35.338Z chromeRunner Preparing sandbox [worker #0, session #b882f]\n',
    '2022-04-20T14:33:35.339Z browserRunner Total files to load in sandbox: 6\n',
    '2022-04-20T14:33:35.340Z browserRunner Sandbox is generated [worker #0, session #b882f]: http://localhost:62913/wallaby_sandbox0.html\n',
    '2022-04-20T14:33:35.340Z chromeRunner Prepared sandbox [worker #0, session #b882f]\n',
    '2022-04-20T14:33:35.340Z workers [worker #0, session #b882f] Running tests in sandbox\n',
    '2022-04-20T14:33:35.694Z chromeRunner Failed to evaluate code on Chrome Tab: {"exceptionId":1,"text":"Uncaught","lineNumber":3897,"columnNumber":51,"scriptId":"16","exception":{"type":"object","subtype":"error","className":"ReferenceError","description":"ReferenceError: process is not defined\\n    at t.instance.install (http://localhost:62913/____wallaby-bundle.js?1650465215309&wallabyFileId=bundle:3898:52)\\n    at S (http://localhost:62913/__wallaby__/jasmine@3.10.0/framework.js:14:14148)\\n    at t.execute (http://localhost:62913/__wallaby__/jasmine@3.10.0/framework.js:14:22883)\\n    at p._onStart (http://localhost:62913/__wallaby__/jasmine@2.1.3/starter.js:14:72)\\n    at n (http://localhost:62913/__wallaby__/tracer.js:14:5752)\\n    at p.start (http://localhost:62913/__wallaby__/tracer.js:14:6110)\\n    at <anonymous>:1:23\\n    at <anonymous>:1:32","objectId":"-5418214394913756687.2.2"}}\n'
  ]
}
```

**Comment by smcenlly** [comment]
Do your tests run from the command-line outside of Wallaby?

From the error, it looks like you have some `node.js` code that uses `process` (**at t.instance.install**) that for some reason is running in chrome and causing your tests to fail.

If the tests are working from the command-line, is it possible for you to provide us with your repo (or a cut down version) so we can try and see what file/dependency is being bundled when it shouldn't be? If you prefer, you mail email us: hello@wallabyjs.com

**Comment by MeltedYeti** [comment]
What do you mean "are the tests working from the command line"? If you mean can I run them through Angular using `ng test` then yes, the tests work fine when ran through karma/jasmine. I don't know that I am able to email much as the code is the company's and not my own. I can't reproduce this error through normal means.

I looked into what is calling `instance.install` and it appears that it is coming from zonejs and not something manually called. Does that shed any light on the situation?

**Comment by NikGovorov** [comment]
@MeltedYeti What `webpack` version do you use on the project? Do you have the following section on your `package.json`?

```
{
  "resolutions": {
    "webpack": "^5.0.0"
  },
}
```

**Comment by smcenlly** [comment]
@MeltedYeti - we were able to identify the cause of your problem.

Your project has explicitly installed `sass-loader@^12.6.0` which ends up overriding the webpack version for your Angular 11 project to `webpack@^5.x` (instead of `webpack@^4.x` that ships with Angular 11). Because Webpack 5 for Angular 11 is marked as experimental and not suggested for production, Wallaby has never supported using webpack 5 with Angular 11 projects.

If you want to use webpack 5, then the Angular team recommendation (and our own) is to use Angular CLI v12 or v13.

Did you know that your dependencies were swapping your webpack version? Is this intentional? If it is not intentional, you may find that there are some other things that break.

You should also be able to fix your issue by downgrading `sass-loader` to previous version that uses webpack 4 (e.g. `10.0.3`).

While we don't have any plans right now to support using Webpack 5 with Angular 11, please let us know if you're doing this intentionally and we will evaluate adding support as a feature request.

**Comment by MeltedYeti** [comment]
@smcenlly @NikGovorov - thank you for the help in figuring out what is going wrong. I am with a new company on a new team so I can't really explain the choices that were made. I guess for this project I am just SOL until we update our Angular version.

**Comment by smcenlly** [comment]
You could also try explicitly installing `webpack` version 4 in your `package.json` to see if that fixes your problem.

```
npm install webpack@4 --save-dev
```
