### ISSUE TITLE
Optional Chaining broken in newest Wallaby version

### ISSUE THREAD

**Issue by andrewryan1906** [wallabyjs/public#2975]
### Issue description or question

I downloaded the newest version of Wallaby, and I get an error when using the optional chaining (?.) operator, even though I'm using Node 14.

I've set up a repo to demonstrate it here:

https://github.com/rhythmsoftware/wallaby-test

I'm using Mocha, so I have a configuration file, and when I run it, I get:

```
Failed to instrument src/logic.js
  5 |     };
  6 | 
> 7 |     console.log( item?.value );
    |                       ^ SyntaxError: Unexpected token (7:22)
  8 | }
  9 | 


```

### Wallaby diagnostics report

```
{
  editorVersion: 'WebStorm 2022.1',
  pluginVersion: '1.0.238',
  editorType: 'IntelliJ',
  osVersion: 'darwin 20.6.0',
  nodeVersion: 'v14.16.0',
  coreVersion: '1.0.802',
  config: {
    files: [
      { pattern: 'config.js', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: 'src/**/*.js', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: 'tests/json/**/*', ignore: false, trigger: true, load: true, instrument: true, order: 3 }
    ],
    tests: [ { pattern: 'tests/unit/**/*spec.js', ignore: false, trigger: true, load: true, test: true, order: 4 } ],
    testFramework: { version: 'mocha@2.1.0', configurator: 'mocha@2.1.0', reporter: 'mocha@2.1.0', starter: 'mocha@2.1.0' },
    env: { type: 'node', runner: 'node', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    compilers: { '**/*.?(lit)coffee?(.md)': [Function (anonymous)] },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: undefined,
    configCode: 'module.exports = function () {\n' +
      '    return {\n' +
      '        files: [\n' +
      "            'config.js',\n" +
      "            'src/**/*.js',\n" +
      "            'tests/json/**/*',\n" +
      '        ],\n' +
      '\n' +
      '        tests: [\n' +
      "            'tests/unit/**/*spec.js'\n" +
      '        ],\n' +
      "        testFramework: 'mocha',\n" +
      '        setup: function () {\n' +
      "            global.expect = require('chai').expect;\n" +
      '        },\n' +
      '        env: {\n' +
      "            type: 'node',\n" +
      "            runner: 'node'\n" +
      '        }\n' +
      '    };\n' +
      '\n' +
      '};'
  },
  packageJSON: { dependencies: { mocha: '^9.2.2' }, devDependencies: undefined },
  fs: { numberOfFiles: 2 },
  debug: [
    '2022-04-20T17:14:02.156Z project Wallaby Node version: v14.16.0\n',
    '2022-04-20T17:14:02.156Z project Wallaby config: <homeDir>/rhythm/wallaby-test/wallaby.js\n',
    '2022-04-20T17:14:02.744Z project File cache: <homeDir>/Library/Caches/JetBrains/WebStorm2022.1/wallaby/projects/f4e0dd1ccad884c9\n',
    '2022-04-20T17:14:02.750Z uiService Listening port 51236\n',
    '2022-04-20T17:14:02.751Z project package.json file change detected, invalidating local cache\n',
    '2022-04-20T17:14:02.755Z workers Parallelism for initial run: 10, for regular run: 5\n',
    '2022-04-20T17:14:02.755Z workers Starting run worker instance #0\n',
    '2022-04-20T17:14:02.755Z workers Starting run worker instance #1\n',
    '2022-04-20T17:14:02.755Z workers Starting run worker instance #2\n',
    '2022-04-20T17:14:02.755Z workers Starting run worker instance #3\n',
    '2022-04-20T17:14:02.755Z workers Starting run worker instance #4\n',
    '2022-04-20T17:14:02.755Z workers Starting run worker instance #5\n',
    '2022-04-20T17:14:02.755Z workers Starting run worker instance #6\n',
    '2022-04-20T17:14:02.755Z workers Starting run worker instance #7\n',
    '2022-04-20T17:14:02.755Z workers Starting run worker instance #8\n',
    '2022-04-20T17:14:02.755Z workers Starting run worker instance #9\n',
    '2022-04-20T17:14:02.756Z workers Web server is listening at 64535\n',
    '2022-04-20T17:14:02.756Z project File cache requires some updates, waiting required files from IDE\n',
    '2022-04-20T17:14:03.123Z workers Started run worker instance (delayed) #2\n',
    '2022-04-20T17:14:03.140Z workers Started run worker instance (delayed) #1\n',
    '2022-04-20T17:14:03.186Z workers Started run worker instance (delayed) #3\n',
    '2022-04-20T17:14:03.188Z workers Started run worker instance (delayed) #4\n',
    '2022-04-20T17:14:03.190Z workers Started run worker instance (delayed) #0\n',
    '2022-04-20T17:14:03.194Z workers Started run worker instance (delayed) #5\n',
    '2022-04-20T17:14:03.247Z workers Started run worker instance (delayed) #6\n',
    '2022-04-20T17:14:03.320Z workers Started run worker instance (delayed) #7\n',
    '2022-04-20T17:14:03.346Z workers Started run worker instance (delayed) #8\n',
    '2022-04-20T17:14:03.584Z workers Started run worker instance (delayed) #9\n',
    '2022-04-20T17:14:03.832Z project Error: Failed to instrument src/logic.js\n' +
      '  5 |     };\n' +
      '  6 | \n' +
      '> 7 |     console.log( item?.value );\n' +
      '    |                       ^ SyntaxError: Unexpected token (7:22)\n' +
      '  8 | }\n' +
      '  9 | \n' +
      '    at Object.formatInstrumentationError (<homeDir>/Library/Caches/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:25:14064)\n' +
      '    at <homeDir>/Library/Caches/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:22:13415\n' +
      '    at _rejected (<homeDir>/Library/Caches/JetBrains/WebStorm2022.1/wallaby/wallaby/node_modules/q/q.js:864:24)\n' +
      '    at <homeDir>/Library/Caches/JetBrains/WebStorm2022.1/wallaby/wallaby/node_modules/q/q.js:890:30\n' +
      '    at Promise.when (<homeDir>/Library/Caches/JetBrains/WebStorm2022.1/wallaby/wallaby/node_modules/q/q.js:1142:31)\n' +
      '    at Promise.promise.promiseDispatch (<homeDir>/Library/Caches/JetBrains/WebStorm2022.1/wallaby/wallaby/node_modules/q/q.js:808:41)\n' +
      '    at <homeDir>/Library/Caches/JetBrains/WebStorm2022.1/wallaby/wallaby/node_modules/q/q.js:624:44\n' +
      '    at runSingle (<homeDir>/Library/Caches/JetBrains/WebStorm2022.1/wallaby/wallaby/node_modules/q/q.js:137:13)\n' +
      '    at flush (<homeDir>/Library/Caches/JetBrains/WebStorm2022.1/wallaby/wallaby/node_modules/q/q.js:125:13)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:75:11)\n',
    '2022-04-20T17:14:03.832Z project Stopping process pool\n',
    '2022-04-20T17:14:03.833Z project Changes did not trigger any tests\n'
  ]
}
```

**Comment by smcenlly** [comment]
The version of Wallaby that you are using `v1.0.802` was released on **16 Dec 2019**. Optional chaining support in Wallaby was not added to Wallaby until **10 Jan 2020**. You can read about all changes since your version in our [changelog](https://github.com/wallabyjs/public/blob/master/CHANGELOG.md).

Please update to the latest version of Wallaby, it will fix your problem. If your license has expired and you would like to use the latest version, you may [request a 15-day trial](https://wallabyjs.com/download/#try-it-free) to confirm the issue is fixed for you. You may renew your license via [our website](https://wallabyjs.com/purchase/#select-wallaby) (select to Claim your existing user discount), or else email us: hello@wallabyjs.com

**Comment by andrewryan1906** [comment]
Hello,

I'm using the latest version, 1.0.238. To confirm, I just reinstalled and redownloaded Wallaby from here:

https://plugins.jetbrains.com/plugin/15742-wallaby

Same error. Diagnostics report says plugin version 1.0.238, core version 1.0.802. Not sure what the difference is between those, or how I can get a newer "core" version.

Thanks,
Andrew
