### ISSUE TITLE
Cannot read properties of undefined (reading 'testEnvironmentOptions') 

### ISSUE THREAD

**Issue by heinolindstrom** [wallabyjs/public#2997]
### Issue description or question

My tests run with jest:

```
npx jest
 PASS  src/App.test.tsx
 PASS  src/service/Api.test.ts

Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        3.2 s, estimated 4 s
Ran all test suites.
```

But fails with Wallabyjs:

```
‌0 failing tests, 0 passing  ​Launch Coverage & Test Explorer​ | ​Search Tests​

Cannot read properties of undefined (reading 'testEnvironmentOptions') 
  ​​​​​at ​​​​​​src/App.test.tsx:1​

Cannot read properties of undefined (reading 'testEnvironmentOptions') 
  ​​​​​at ​​​​​​src/service/Api.test.ts:1
```

What could cause this or could I configure something differently?

Test project is here [wallaby-tmp](https://github.com/heinolindstrom/wallaby-tmp).

### Wallaby diagnostics report

```
{
  editorVersion: '1.67.2',
  pluginVersion: '1.0.337',
  editorType: 'VSCode',
  osVersion: 'linux 5.10.102.1-microsoft-standard-WSL2',
  nodeVersion: 'v16.15.0',
  coreVersion: '1.0.1270',
  checksum: 'ZWM2MWE4NTk5ZjU1YjJmZDYyODEzNzM3OTUxZmY3NGUsMTY3OTA5NzYwMDAwMCww',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/tmp/jest_rs',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/Projects/wallaby-tmp',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: undefined,
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              extraGlobals: [],
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: false, throwOnModuleCollision: false },
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [
                'web.js',  'js',
                'web.ts',  'ts',
                'web.tsx', 'tsx',
                'json',    'web.jsx',
                'jsx',     'node'
              ],
              moduleLoader: undefined,
              moduleNameMapper: [ [ '^react-native$', 'react-native-web' ], [ '^.+\\.module\\.(css|sass|scss)$', 'identity-obj-proxy' ] ],
              modulePathIgnorePatterns: [],
              modulePaths: [],
              name: '351b8a4bf188d82d5a070a61d994be94',
              prettierPath: 'prettier',
              resetMocks: true,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/Projects/wallaby-tmp',
              roots: [ '<homeDir>/Projects/wallaby-tmp/src' ],
              runner: '<homeDir>/Projects/wallaby-tmp/node_modules/react-scripts/node_modules/jest-runner/build/index.js',
              setupFiles: [ '<homeDir>/Projects/wallaby-tmp/node_modules/react-app-polyfill/jsdom.js' ],
              setupFilesAfterEnv: [ '<homeDir>/Projects/wallaby-tmp/src/setupTests.ts' ],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/Projects/wallaby-tmp/node_modules/jest-environment-jsdom/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '<homeDir>/Projects/wallaby-tmp/src/**/__tests__/**/*.{js,jsx,ts,tsx}', '<homeDir>/Projects/wallaby-tmp/src/**/*.{spec,test}.{js,jsx,ts,tsx}' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<homeDir>/Projects/wallaby-tmp/node_modules/react-scripts/node_modules/jest-circus/runner.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [
                [ '^.+\\.(js|jsx|mjs|cjs|ts|tsx)$', '<homeDir>/Projects/wallaby-tmp/node_modules/react-scripts/config/jest/babelTransform.js', {} ],
                [ '^.+\\.css$', '<homeDir>/Projects/wallaby-tmp/node_modules/react-scripts/config/jest/cssTransform.js', {} ],
                [ '^(?!.*\\.(js|jsx|mjs|cjs|ts|tsx|css|json)$)', '<homeDir>/Projects/wallaby-tmp/node_modules/react-scripts/config/jest/fileTransform.js', {} ]
              ],
              transformIgnorePatterns: [ '[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs|cjs|ts|tsx)$', '^.+\\.module\\.(css|sass|scss)$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: [ 'src/**/*.{js,jsx,ts,tsx}', '!src/**/*.d.ts' ],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<homeDir>/Projects/wallaby-tmp/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 15,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/Projects/wallaby-tmp',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: undefined,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/Projects/wallaby-tmp/node_modules/react-scripts/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: [
              { config: {}, path: '<homeDir>/Projects/wallaby-tmp/node_modules/jest-watch-typeahead/filename.js' },
              { config: {}, path: '<homeDir>/Projects/wallaby-tmp/node_modules/jest-watch-typeahead/testname.js' }
            ],
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [ 'src' ],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/tmp/jest_rs', '\\./coverage' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/tmp/jest_rs', '\\./coverage' ],
            testMatch: [ 'src/**/__tests__/**/*.{js,jsx,ts,tsx}', 'src/**/*.{spec,test}.{js,jsx,ts,tsx}' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [ 'src/**/*.{js,jsx,ts,tsx}', '!src/**/*.d.ts' ],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    micromatch: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
      { pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//, ignore: true, trigger: true, load: true },
      { pattern: '/tmp/jest_rs', regexp: /\/tmp\/jest_rs/, ignore: true, trigger: true, load: true },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**', ignore: false, trigger: true, load: true, order: 2 },
      { pattern: 'src/**/__tests__/**/*.{js,jsx,ts,tsx}', ignore: true, trigger: true, load: true },
      { pattern: 'src/**/*.{spec,test}.{js,jsx,ts,tsx}', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      { pattern: '/tmp/jest_rs', regexp: /\/tmp\/jest_rs/, ignore: true, trigger: true, load: true, test: true },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, test: true },
      { pattern: 'src/**/__tests__/**/*.{js,jsx,ts,tsx}', ignore: false, trigger: true, load: true, test: true, order: 3 },
      { pattern: 'src/**/*.{spec,test}.{js,jsx,ts,tsx}', ignore: false, trigger: true, load: true, test: true, order: 4 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '<homeDir>/.nvm/versions/node/v16.15.0/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#-1577851950'
  },
  packageJSON: {
    dependencies: {
      '@testing-library/jest-dom': '^5.16.4',
      '@testing-library/react': '^13.2.0',
      '@testing-library/user-event': '^13.5.0',
      '@types/node': '^16.11.36',
      '@types/react': '^18.0.9',
      '@types/react-dom': '^18.0.4',
      axios: '^0.27.2',
      dotenv: '^16.0.1',
      'jest-css-modules-transform': '^4.4.2',
      'jest-environment-jsdom': '^28.1.0',
      react: '^18.1.0',
      'react-dom': '^18.1.0',
      'react-scripts': '5.0.1',
      'web-vitals': '^2.1.4'
    },
    devDependencies: { '@types/jest': '^27.5.1', jest: '^28.1.0', 'ts-jest': '^28.0.2', typescript: '^4.6.4' }
  },
  fs: { numberOfFiles: 25 },
  debug: [
    '2022-05-23T13:03:09.360Z angular/cli config Angular CLI not found.\n',
    '2022-05-23T13:03:09.566Z jest/config Detected Jest.\n',
    '2022-05-23T13:03:09.566Z jest/config Configured Jest.\n',
    '2022-05-23T13:03:09.567Z project Wallaby Node version: v16.15.0\n',
    '2022-05-23T13:03:09.567Z project Wallaby config: <homeDir>/Projects/wallaby-tmp/auto.detect\n',
    '2022-05-23T13:03:09.617Z project File cache: <homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.337/projects/b4726fa2e678e2bb\n',
    '2022-05-23T13:03:09.621Z uiService Listening port 51237\n',
    '2022-05-23T13:03:09.630Z workers Parallelism for initial run: 14, for regular run: 7\n',
    '2022-05-23T13:03:09.630Z workers Starting run worker instance #0\n',
    '2022-05-23T13:03:09.630Z workers Starting run worker instance #1\n',
    '2022-05-23T13:03:09.630Z workers Starting run worker instance #2\n',
    '2022-05-23T13:03:09.630Z workers Starting run worker instance #3\n',
    '2022-05-23T13:03:09.630Z workers Starting run worker instance #4\n',
    '2022-05-23T13:03:09.630Z workers Starting run worker instance #5\n',
    '2022-05-23T13:03:09.630Z workers Starting run worker instance #6\n',
    '2022-05-23T13:03:09.630Z workers Starting run worker instance #7\n',
    '2022-05-23T13:03:09.630Z workers Starting run worker instance #8\n',
    '2022-05-23T13:03:09.630Z workers Starting run worker instance #9\n',
    '2022-05-23T13:03:09.630Z workers Starting run worker instance #10\n',
    '2022-05-23T13:03:09.630Z workers Starting run worker instance #11\n',
    '2022-05-23T13:03:09.630Z workers Starting run worker instance #12\n',
    '2022-05-23T13:03:09.630Z workers Starting run worker instance #13\n',
    '2022-05-23T13:03:09.631Z workers Web server is listening at 45665\n',
    '2022-05-23T13:03:09.798Z project Stopping process pool\n',
    '2022-05-23T13:03:09.799Z project File cache is up-to-date, starting full test run\n',
    '2022-05-23T13:03:09.802Z project Test run started; run priority: 3\n',
    '2022-05-23T13:03:09.803Z project Running all tests\n',
    '2022-05-23T13:03:09.806Z workers Starting test run, priority: 3\n',
    '2022-05-23T13:03:09.806Z workers Distributing tests between 14 workers\n',
    '2022-05-23T13:03:09.807Z workers Running tests in parallel\n',
    '2022-05-23T13:03:09.807Z nodeRunner Starting sandbox [worker #0, session #jhpyg]\n',
    '2022-05-23T13:03:09.807Z nodeRunner Starting sandbox [worker #1, session #94ziq]\n',
    '2022-05-23T13:03:09.807Z nodeRunner Preparing sandbox [worker #0, session #jhpyg]\n',
    '2022-05-23T13:03:09.807Z nodeRunner Preparing sandbox [worker #1, session #94ziq]\n',
    '2022-05-23T13:03:09.818Z workers Started run worker instance (delayed) #2\n',
    '2022-05-23T13:03:09.822Z workers Started run worker instance (delayed) #1\n',
    '2022-05-23T13:03:09.822Z nodeRunner Prepared sandbox [worker #1, session #94ziq]\n',
    '2022-05-23T13:03:09.823Z workers [worker #1, session #94ziq] Running tests in sandbox\n',
    '2022-05-23T13:03:09.824Z workers Started run worker instance (delayed) #3\n',
    '2022-05-23T13:03:09.825Z workers Started run worker instance (delayed) #0\n',
    '2022-05-23T13:03:09.826Z nodeRunner Prepared sandbox [worker #0, session #jhpyg]\n',
    '2022-05-23T13:03:09.826Z workers [worker #0, session #jhpyg] Running tests in sandbox\n',
    '2022-05-23T13:03:09.827Z workers Started run worker instance (delayed) #4\n',
    '2022-05-23T13:03:09.827Z workers Started run worker instance (delayed) #5\n',
    '2022-05-23T13:03:09.828Z workers Started run worker instance (delayed) #7\n',
    '2022-05-23T13:03:09.828Z workers Started run worker instance (delayed) #6\n',
    '2022-05-23T13:03:09.912Z workers Started run worker instance (delayed) #8\n',
    '2022-05-23T13:03:09.913Z workers Started run worker instance (delayed) #9\n',
    '2022-05-23T13:03:09.920Z workers Started run worker instance (delayed) #10\n',
    '2022-05-23T13:03:09.939Z workers Started run worker instance (delayed) #11\n',
    '2022-05-23T13:03:09.950Z workers Started run worker instance (delayed) #12\n',
    '2022-05-23T13:03:09.951Z workers Started run worker instance (delayed) #13\n',
    '2022-05-23T13:03:10.568Z workers Scheduling Jest Test Run (jhpyg): 2022-05-23T13:03:10.263Z\n',
    "2022-05-23T13:03:10.571Z workers Sandbox (active) [jhpyg] error: TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')\n" +
      '    at new JSDOMEnvironment (./node_modules/jest-environment-jsdom/build/index.js:73:28)\n' +
      '    at runTestInternal (./node_modules/react-scripts/node_modules/jest-runner/build/runTest.js:267:23)\n' +
      '    at async runTest (./node_modules/react-scripts/node_modules/jest-runner/build/runTest.js:475:34)\n' +
      '    at async TestRunner.runTests (./node_modules/react-scripts/node_modules/jest-runner/build/index.js:101:12)\n' +
      '    at async TestScheduler.scheduleTests (./node_modules/react-scripts/node_modules/@jest/core/build/TestScheduler.js:333:13)\n',
    '2022-05-23T13:03:10.573Z workers [jhpyg] Run 0 test(s), skipped 0 test(s)\n',
    '2022-05-23T13:03:10.573Z workers Jest Test Run Complete (jhpyg): 2022-05-23T13:03:10.565Z\n',
    '2022-05-23T13:03:10.579Z workers [jhpyg] Sandbox is responsive, closing it\n',
    "2022-05-23T13:03:10.580Z workers Failed to map the stack to user code, entry message: Cannot read properties of undefined (reading 'testEnvironmentOptions'), stack: TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')\n" +
      '    at new JSDOMEnvironment (<homeDir>/Projects/wallaby-tmp/node_modules/jest-environment-jsdom/build/index.js:73:28)\n' +
      '    at runTestInternal (<homeDir>/Projects/wallaby-tmp/node_modules/react-scripts/node_modules/jest-runner/build/runTest.js:267:23)\n' +
      '    at async runTest (<homeDir>/Projects/wallaby-tmp/node_modules/react-scripts/node_modules/jest-runner/build/runTest.js:475:34)\n' +
      '    at async TestRunner.runTests (<homeDir>/Projects/wallaby-tmp/node_modules/react-scripts/node_modules/jest-runner/build/index.js:101:12)\n' +
      '    at async TestScheduler.scheduleTests (<homeDir>/Projects/wallaby-tmp/node_modules/react-scripts/node_modules/@jest/core/build/TestScheduler.js:333:13)\n',
    '2022-05-23T13:03:10.581Z workers Scheduling Jest Test Run (94ziq): 2022-05-23T13:03:10.273Z\n',
    "2022-05-23T13:03:10.582Z workers Sandbox (active) [94ziq] error: TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')\n" +
      '    at new JSDOMEnvironment (./node_modules/jest-environment-jsdom/build/index.js:73:28)\n' +
      '    at runTestInternal (./node_modules/react-scripts/node_modules/jest-runner/build/runTest.js:267:23)\n' +
      '    at async runTest (./node_modules/react-scripts/node_modules/jest-runner/build/runTest.js:475:34)\n' +
      '    at async TestRunner.runTests (./node_modules/react-scripts/node_modules/jest-runner/build/index.js:101:12)\n' +
      '    at async TestScheduler.scheduleTests (./node_modules/react-scripts/node_modules/@jest/core/build/TestScheduler.js:333:13)\n',
    '2022-05-23T13:03:10.582Z workers [94ziq] Run 0 test(s), skipped 0 test(s)\n',
    '2022-05-23T13:03:10.583Z workers Jest Test Run Complete (94ziq): 2022-05-23T13:03:10.577Z\n',
    '2022-05-23T13:03:10.584Z workers [94ziq] Sandbox is responsive, closing it\n',
    "2022-05-23T13:03:10.584Z workers Failed to map the stack to user code, entry message: Cannot read properties of undefined (reading 'testEnvironmentOptions'), stack: TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')\n" +
      '    at new JSDOMEnvironment (<homeDir>/Projects/wallaby-tmp/node_modules/jest-environment-jsdom/build/index.js:73:28)\n' +
      '    at runTestInternal (<homeDir>/Projects/wallaby-tmp/node_modules/react-scripts/node_modules/jest-runner/build/runTest.js:267:23)\n' +
      '    at async runTest (<homeDir>/Projects/wallaby-tmp/node_modules/react-scripts/node_modules/jest-runner/build/runTest.js:475:34)\n' +
      '    at async TestRunner.runTests (<homeDir>/Projects/wallaby-tmp/node_modules/react-scripts/node_modules/jest-runner/build/index.js:101:12)\n' +
      '    at async TestScheduler.scheduleTests (<homeDir>/Projects/wallaby-tmp/node_modules/react-scripts/node_modules/@jest/core/build/TestScheduler.js:333:13)\n',
    '2022-05-23T13:03:10.584Z workers Merging parallel test run results\n',
    '2022-05-23T13:03:10.584Z project Test run finished\n',
    '2022-05-23T13:03:10.585Z project Processed console.log entries\n',
    '2022-05-23T13:03:10.585Z project Processed loading sequences\n',
    '2022-05-23T13:03:10.585Z project Processed executed tests\n',
    '2022-05-23T13:03:10.585Z project Processed code coverage\n',
    '2022-05-23T13:03:10.590Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by smcenlly** [comment]
From your diagnostics report, it looks like your project is a temporary sample`wallaby-tmp` - are you able to share it with us?

If not, could you please provide us with your `jest` configuration (configuration may be in `package.json` or `jest.config.js` depending on how you created your project).

**Comment by smcenlly** [comment]
Please disregard my question - I had missed the link to your sample repo.

**Comment by smcenlly** [comment]
Thanks for the sample repo.

You get the same behavior if your execute `npm run test` from the command-line. Because your project is configured to use `react-scripts` to run your tests (in `package.json`), Wallaby is using react and reports the same problem as the CLI.

You can fix this by changing your `package.json` to run your tests with `jest` as per CLI:

**package.json**
```javascript
...
  "scripts": {
...
    "test": "jest",
...
  },
...
```

**Comment by heinolindstrom** [comment]
> You can fix this by changing your `package.json` to run your tests with `jest` as per CLI:

Thanks a lot! 👍
