### ISSUE TITLE
Carrot in path causes "Error when reading file"

### ISSUE THREAD

**Issue by rspringAya** [wallabyjs/public#3001]
### Issue description or question

When the path to a test file contains a carrot character, Wallaby throws an error that it cannot read the file. My test is with a new Angular 13 project. The first run was without any carrot characters. Then I added a folder beginning with a carrot and added a spec file, resulting in the error.

Also note, this does not show in the diagnostics report. I needed to enable trace to copy from that output.

### Wallaby diagnostics report

```
{
  editorVersion: '1.67.2',
  pluginVersion: '1.0.337',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.19043',
  nodeVersion: 'v16.14.0',
  coreVersion: '1.0.1270',
  config: {
    trace: true,
    diagnostics: {
      angular: {
        workspace: {
          '$schema': './node_modules/@angular/cli/lib/config/schema.json',
          version: 1,
          newProjectRoot: 'projects',
          projects: {
            wallabytest: {
              projectType: 'application',
              schematics: { '@schematics/angular:application': { strict: true } },
              root: '',
              sourceRoot: 'src',
              prefix: 'app',
              architect: {
                build: {
                  builder: '@angular-devkit/build-angular:browser',
                  options: {
                    outputPath: 'dist/wallabytest',
                    index: 'src/index.html',
                    main: 'src/main.ts',
                    polyfills: 'src/polyfills.ts',
                    tsConfig: 'tsconfig.app.json',
                    assets: [ 'src/favicon.ico', 'src/assets' ],
                    styles: [ 'src/styles.css' ],
                    scripts: []
                  },
                  configurations: {
                    production: {
                      budgets: [ { type: 'initial', maximumWarning: '500kb', maximumError: '1mb' }, { type: 'anyComponentStyle', maximumWarning: '2kb', maximumError: '4kb' } ],
                      fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.prod.ts' } ],
                      outputHashing: 'all'
                    },
                    development: { buildOptimizer: false, optimization: false, vendorChunk: true, extractLicenses: false, sourceMap: true, namedChunks: true }
                  },
                  defaultConfiguration: 'production'
                },
                serve: {
                  builder: '@angular-devkit/build-angular:dev-server',
                  configurations: { production: { browserTarget: 'wallabytest:build:production' }, development: { browserTarget: 'wallabytest:build:development' } },
                  defaultConfiguration: 'development'
                },
                'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: 'wallabytest:build' } },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    main: 'src/test.ts',
                    polyfills: 'src/polyfills.ts',
                    tsConfig: 'tsconfig.spec.json',
                    karmaConfig: 'karma.conf.js',
                    assets: [ 'src/favicon.ico', 'src/assets' ],
                    styles: [ 'src/styles.css' ],
                    scripts: []
                  }
                }
              }
            }
          },
          defaultProject: 'wallabytest'
        },
        main: '// This file is required by karma.conf.js and loads recursively all the .spec and framework files\n' +
          '\n' +
          "import 'zone.js/testing';\n" +
          "import { getTestBed } from '@angular/core/testing';\n" +
          'import {\n' +
          '  BrowserDynamicTestingModule,\n' +
          '  platformBrowserDynamicTesting\n' +
          "} from '@angular/platform-browser-dynamic/testing';\n" +
          '\n' +
          'declare const require: {\n' +
          '  context(path: string, deep?: boolean, filter?: RegExp): {\n' +
          '    <T>(id: string): T;\n' +
          '    keys(): string[];\n' +
          '  };\n' +
          '};\n' +
          '\n' +
          '// First, initialize the Angular testing environment.\n' +
          'getTestBed().initTestEnvironment(\n' +
          '  BrowserDynamicTestingModule,\n' +
          '  platformBrowserDynamicTesting(),\n' +
          ');\n' +
          '\n' +
          '// Then we find all the tests.\n' +
          '\n' +
          '// And load the modules.\n' +
          '\n'
      }
    },
    testFramework: { version: 'jasmine@3.10.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3', autoDetected: true },
    env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    files: [
      { pattern: 'src/**/*.spec.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/polyfills.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/main.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/index.html', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.base.ts', ignore: true, trigger: true, load: true },
      { pattern: 'src/test.wallaby.ts', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 2 },
      { pattern: 'src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 3 }
    ],
    tests: [ { pattern: 'src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 4 } ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#1313788472'
  },
  packageJSON: {
    dependencies: {
      '@angular/animations': '~13.3.0',
      '@angular/common': '~13.3.0',
      '@angular/compiler': '~13.3.0',
      '@angular/core': '~13.3.0',
      '@angular/forms': '~13.3.0',
      '@angular/platform-browser': '~13.3.0',
      '@angular/platform-browser-dynamic': '~13.3.0',
      '@angular/router': '~13.3.0',
      rxjs: '~7.5.0',
      tslib: '^2.3.0',
      'zone.js': '~0.11.4'
    },
    devDependencies: {
      '@angular-devkit/build-angular': '~13.3.1',
      '@angular/cli': '~13.3.1',
      '@angular/compiler-cli': '~13.3.0',
      '@types/jasmine': '~3.10.0',
      '@types/node': '^12.11.1',
      'jasmine-core': '~4.0.0',
      karma: '~6.3.0',
      'karma-chrome-launcher': '~3.1.0',
      'karma-coverage': '~2.1.0',
      'karma-jasmine': '~4.0.0',
      'karma-jasmine-html-reporter': '~1.7.0',
      typescript: '~4.6.2'
    }
  },
  fs: { numberOfFiles: 9 },
  debug: [
    '2022-05-27T18:41:41.087Z angular/cli config Detected Angular CLI.\n',
    '2022-05-27T18:41:41.098Z angular/cli config Angular currentDirPath: "C:\\Dev\\CodeSamples\\wallabytest", workspaceDirPath: "C:\\Dev\\CodeSamples\\wallabytest"\n',
    '2022-05-27T18:42:19.325Z angular/cli karma project config Using virtual C:/Dev/CodeSamples/wallabytest/src/test.ts.\n',
    '2022-05-27T18:42:19.978Z project Wallaby Node version: v16.14.0\n',
    '2022-05-27T18:42:19.978Z project Wallaby config: C:\\Dev\\CodeSamples\\wallabytest\\auto.detect\n',
    '2022-05-27T18:42:20.115Z project File cache: C:\\Users\\RogerSpring\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.337\\projects\\31236fd00871600f\n',
    '2022-05-27T18:42:22.016Z uiService Listening port 51235\n',
    '2022-05-27T18:42:22.042Z project package.json file change detected, invalidating local cache\n',
    '2022-05-27T18:42:22.561Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2022-05-27T18:42:22.562Z workers Starting run worker instance #0\n',
    '2022-05-27T18:42:22.562Z workers Starting run worker instance #1\n',
    '2022-05-27T18:42:22.562Z workers Starting run worker instance #2\n',
    '2022-05-27T18:42:22.562Z workers Starting run worker instance #3\n',
    '2022-05-27T18:42:22.562Z workers Starting run worker instance #4\n',
    '2022-05-27T18:42:22.562Z workers Starting run worker instance #5\n',
    '2022-05-27T18:42:22.567Z workers Web server is listening at 60224\n',
    '2022-05-27T18:42:22.577Z project Stopping process pool\n',
    '2022-05-27T18:42:22.577Z project File cache is up-to-date, starting full test run\n',
    '2022-05-27T18:42:22.583Z project Running postprocessor\n',
    '2022-05-27T18:42:22.588Z postprocessor Processing started.\n',
    '2022-05-27T18:42:22.588Z postprocessor Initializing.\n',
    '2022-05-27T18:42:22.589Z postprocessor Initializing entry.\n',
    '2022-05-27T18:42:22.589Z postprocessor Sanitizing configuration.\n',
    '2022-05-27T18:42:22.589Z postprocessor Adjusting configuration.\n',
    '2022-05-27T18:42:22.664Z postprocessor Creating compiler.\n',
    '2022-05-27T18:42:26.377Z postprocessor Customizing compiler.\n',
    '2022-05-27T18:42:26.377Z postprocessor Compilation started.\n',
    '2022-05-27T18:42:32.866Z workers Started run worker instance (immediate) #0\n',
    '2022-05-27T18:42:32.866Z workers Started run worker instance (immediate) #1\n',
    '2022-05-27T18:42:32.866Z workers Started run worker instance (immediate) #2\n',
    '2022-05-27T18:42:32.866Z workers Started run worker instance (immediate) #3\n',
    '2022-05-27T18:42:32.866Z workers Started run worker instance (immediate) #4\n',
    '2022-05-27T18:42:32.866Z workers Started run worker instance (immediate) #5\n',
    '2022-05-27T18:42:42.212Z postprocessor Compilation finished.\n',
    '2022-05-27T18:42:42.555Z postprocessor Emitting 377 files.\n',
    '2022-05-27T18:42:42.566Z postprocessor Processing finished.\n',
    '2022-05-27T18:42:42.612Z project Postprocessor execution finished\n',
    '2022-05-27T18:42:42.612Z project Test run started; run priority: 3\n',
    '2022-05-27T18:42:42.614Z project Running all tests\n',
    '2022-05-27T18:42:42.621Z workers Starting test run, priority: 3\n',
    '2022-05-27T18:42:42.621Z workers Distributing tests between 6 workers\n',
    '2022-05-27T18:42:42.621Z workers Running tests in parallel\n',
    '2022-05-27T18:42:42.622Z chromeRunner Starting sandbox [worker #0, session #s1n5m]\n',
    '2022-05-27T18:42:42.622Z chromeRunner Starting sandbox [worker #1, session #pvrtp]\n',
    '2022-05-27T18:42:42.623Z chromeRunner Preparing sandbox [worker #0, session #s1n5m]\n',
    '2022-05-27T18:42:42.624Z browserRunner Total files to load in sandbox: 5\n',
    '2022-05-27T18:42:42.626Z browserRunner Sandbox is generated [worker #0, session #s1n5m]: http://localhost:60224/wallaby_sandbox0.html\n',
    '2022-05-27T18:42:42.626Z chromeRunner Preparing sandbox [worker #1, session #pvrtp]\n',
    '2022-05-27T18:42:42.626Z browserRunner Total files to load in sandbox: 5\n',
    '2022-05-27T18:42:42.627Z browserRunner Sandbox is generated [worker #1, session #pvrtp]: http://localhost:60224/wallaby_sandbox1.html\n',
    '2022-05-27T18:42:42.627Z chromeRunner Prepared sandbox [worker #0, session #s1n5m]\n',
    '2022-05-27T18:42:42.628Z chromeRunner Prepared sandbox [worker #1, session #pvrtp]\n',
    '2022-05-27T18:42:42.628Z workers [worker #0, session #s1n5m] Running tests in sandbox\n',
    '2022-05-27T18:42:42.630Z workers [worker #1, session #pvrtp] Running tests in sandbox\n',
    '2022-05-27T18:42:43.318Z workers Sandbox (active) [s1n5m] error: Cannot find module 369.\n' +
      '    at Object.window.__moduleBundler.require (http://localhost:60224/____wallaby-webpack.js?1653676962554:23:15)\n' +
      '    at http://localhost:60224/____wallaby-webpack-bootstrapper.js?1653676962555:19:36\n' +
      '    at http://localhost:60224/__wallaby__/tracer.js:15:16020\n' +
      '    at d._doWhenReceiverIsReady (http://localhost:60224/__wallaby__/tracer.js:14:11899)\n' +
      '    at Object._startWhenReceiverIsReady (http://localhost:60224/__wallaby__/tracer.js:15:15986)\n' +
      '    at Object.window.__moduleBundler.loadTests (http://localhost:60224/____wallaby-webpack-bootstrapper.js?1653676962555:14:22)\n' +
      '    at http://localhost:60224/wallaby_sandbox0.html:9:26633\n' +
      '    at http://localhost:60224/wallaby_sandbox0.html:9:26647\n',
    '2022-05-27T18:42:43.320Z workers Failed to map the stack to user code, entry message: Uncaught Error: Cannot find module 369., stack: Error: Cannot find module 369.\n' +
      '    at Object.window.__moduleBundler.require (http://localhost:60224/____wallaby-webpack.js?1653676962554:23:15)\n' +
      '    at http://localhost:60224/____wallaby-webpack-bootstrapper.js?1653676962555:19:36\n' +
      '    at http://localhost:60224/__wallaby__/tracer.js:15:16020\n' +
      '    at d._doWhenReceiverIsReady (http://localhost:60224/__wallaby__/tracer.js:14:11899)\n' +
      '    at Object._startWhenReceiverIsReady (http://localhost:60224/__wallaby__/tracer.js:15:15986)\n' +
      '    at Object.window.__moduleBundler.loadTests (http://localhost:60224/____wallaby-webpack-bootstrapper.js?1653676962555:14:22)\n' +
      '    at http://localhost:60224/wallaby_sandbox0.html:9:26633\n' +
      '    at http://localhost:60224/wallaby_sandbox0.html:9:26647\n',
    '2022-05-27T18:42:43.329Z workers [s1n5m] Loaded 0 test(s)\n',
    '2022-05-27T18:42:43.331Z workers [pvrtp] Loaded 3 test(s)\n',
    '2022-05-27T18:42:43.336Z workers [s1n5m] Run 0 test(s), skipped 0 test(s)\n',
    '2022-05-27T18:42:43.339Z workers [s1n5m] Sandbox is responsive, closing it\n',
    '2022-05-27T18:42:43.490Z workers [pvrtp] Test executed: should create the app\n',
    '2022-05-27T18:42:43.521Z workers [pvrtp] Test executed: should render title\n',
    "2022-05-27T18:42:43.545Z workers [pvrtp] Test executed: should have as title 'wallabytest'\n",
    '2022-05-27T18:42:43.570Z workers [pvrtp] Run 3 test(s), skipped 0 test(s)\n',
    '2022-05-27T18:42:43.572Z workers [pvrtp] Sandbox is responsive, closing it\n',
    '2022-05-27T18:42:43.573Z workers Merging parallel test run results\n',
    '2022-05-27T18:42:43.574Z project Test run finished\n',
    '2022-05-27T18:42:43.575Z project Processed console.log entries\n',
    '2022-05-27T18:42:43.575Z project Processed loading sequences\n',
    '2022-05-27T18:42:43.576Z project Processed executed tests\n',
    '2022-05-27T18:42:43.578Z project Processed code coverage\n',
    '2022-05-27T18:42:43.598Z project Test run result processed and sent to IDE\n'
  ]
}
```
```
​[Info]​ 2022-05-27T18:45:08.229Z postprocessor Processing finished.
​[Info]​ 2022-05-27T18:45:08.437Z project Postprocessor execution finished
​[Info]​ 2022-05-27T18:45:08.437Z project Test run started; run priority: 2
​[Info]​ 2022-05-27T18:45:08.439Z testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
​[Info]​ 2022-05-27T18:45:08.444Z workers Starting test run, priority: 2
​[Info]​ 2022-05-27T18:45:08.444Z chromeRunner Starting sandbox [worker #0, session #pddjd]
​[Info]​ 2022-05-27T18:45:08.444Z chromeRunner Preparing sandbox [worker #0, session #pddjd]
​[Info]​ 2022-05-27T18:45:08.444Z browserRunner Total files to load in sandbox: 5
​[Info]​ 2022-05-27T18:45:08.445Z browserRunner Sandbox is generated [worker #0, session #pddjd]: http://localhost:60224/wallaby_sandbox0.html
​[Info]​ 2022-05-27T18:45:08.445Z chromeRunner Prepared sandbox [worker #0, session #pddjd]
​[Info]​ 2022-05-27T18:45:08.445Z workers [worker #0, session #pddjd] Running tests in sandbox
​[Info]​ 2022-05-27T18:45:08.565Z middleware Preparing to serve /____wallaby-webpack.js
​[Info]​ 2022-05-27T18:45:08.565Z middleware Serving /____wallaby-webpack.js from cache
​[Info]​ 2022-05-27T18:45:08.566Z middleware Preparing to serve /____wallaby-webpack-bootstrapper.js
​[Info]​ 2022-05-27T18:45:08.566Z middleware Serving /____wallaby-webpack-bootstrapper.js from cache
​[Info]​ 2022-05-27T18:45:08.568Z middleware Preparing to serve /____wallaby-bundle.js
​[Info]​ 2022-05-27T18:45:08.568Z middleware Serving /____wallaby-bundle.js from cache
​[Info]​ 2022-05-27T18:45:08.603Z middleware Preparing to serve /____wallaby-webpack-setup.js
​[Info]​ 2022-05-27T18:45:08.603Z middleware Serving /____wallaby-webpack-setup.js from cache
​[Info]​ 2022-05-27T18:45:08.604Z middleware Preparing to serve /src/%5Etest/my-test.spec.ts.wbp.js
​[Info]​ 2022-05-27T18:45:08.604Z middleware Serving /src/%5Etest/my-test.spec.ts.wbp.js from disk
​[Info]​ 2022-05-27T18:45:08.609Z middleware Serving /src/%5Etest/my-test.spec.ts.wbp.js from disk (alt. location)
​[Info]​ 2022-05-27T18:45:08.609Z middleware Error when reading file C:\Dev\CodeSamples\wallabytest\src\%5Etest\my-test.spec.ts.wbp.js, File 'src/%5Etest/my-test.spec.ts.wbp.js' is not registered.
​[Info]​ 2022-05-27T18:45:08.623Z middleware Preparing to serve /____wallaby-bundle.js
​[Info]​ 2022-05-27T18:45:08.623Z middleware Serving /____wallaby-bundle.js from cache
​[Info]​ 2022-05-27T18:45:08.657Z middleware Preparing to serve /src/%5Etest/my-test.spec.ts.wbp.js
​[Info]​ 2022-05-27T18:45:08.657Z middleware Serving /src/%5Etest/my-test.spec.ts.wbp.js from disk
​[Info]​ 2022-05-27T18:45:08.658Z middleware Serving /src/%5Etest/my-test.spec.ts.wbp.js from disk (alt. location)
​[Info]​ 2022-05-27T18:45:08.658Z middleware Error when reading file C:\Dev\CodeSamples\wallabytest\src\%5Etest\my-test.spec.ts.wbp.js, File 'src/%5Etest/my-test.spec.ts.wbp.js' is not registered.
​[Info]​ 2022-05-27T18:45:08.988Z workers Sandbox (active) [pddjd] error: Cannot find module 369.
​[Info]​     at Object.window.__moduleBundler.require (http://localhost:60224/____wallaby-webpack.js?1653677108225:23:15)
​[Info]​     at http://localhost:60224/____wallaby-webpack-bootstrapper.js?1653677108225:19:36
​[Info]​     at http://localhost:60224/__wallaby__/tracer.js:15:16020
​[Info]​     at d._doWhenReceiverIsReady (http://localhost:60224/__wallaby__/tracer.js:14:11899)
​[Info]​     at Object._startWhenReceiverIsReady (http://localhost:60224/__wallaby__/tracer.js:15:15986)
​[Info]​     at Object.window.__moduleBundler.loadTests (http://localhost:60224/____wallaby-webpack-bootstrapper.js?1653677108225:14:22)
​[Info]​     at http://localhost:60224/wallaby_sandbox0.html:9:26358
​[Info]​     at http://localhost:60224/wallaby_sandbox0.html:9:26372
​​[Error] Runtime error: Cannot find module 369.​​
​​[Error]     at Object.window.__moduleBundler.require (http://localhost:60224/____wallaby-webpack.js?1653677108225:23:15)​​
​​[Error]     at http://localhost:60224/____wallaby-webpack-bootstrapper.js?1653677108225:19:36​​
​​[Error]     at http://localhost:60224/__wallaby__/tracer.js:15:16020​​
​​[Error]     at d._doWhenReceiverIsReady (http://localhost:60224/__wallaby__/tracer.js:14:11899)​​
​​[Error]     at Object._startWhenReceiverIsReady (http://localhost:60224/__wallaby__/tracer.js:15:15986)​​
​​[Error]     at Object.window.__moduleBundler.loadTests (http://localhost:60224/____wallaby-webpack-bootstrapper.js?1653677108225:14:22)​​
​​[Error]     at http://localhost:60224/wallaby_sandbox0.html:9:26358​​
​​[Error]     at http://localhost:60224/wallaby_sandbox0.html:9:26372​​
​[Info]​ 2022-05-27T18:45:08.991Z workers Failed to map the stack to user code, entry message: Uncaught Error: Cannot find module 369., stack: Error: Cannot find module 369.
​[Info]​     at Object.window.__moduleBundler.require (http://localhost:60224/____wallaby-webpack.js?1653677108225:23:15)
​[Info]​     at http://localhost:60224/____wallaby-webpack-bootstrapper.js?1653677108225:19:36
​[Info]​     at http://localhost:60224/__wallaby__/tracer.js:15:16020
​[Info]​     at d._doWhenReceiverIsReady (http://localhost:60224/__wallaby__/tracer.js:14:11899)
​[Info]​     at Object._startWhenReceiverIsReady (http://localhost:60224/__wallaby__/tracer.js:15:15986)
​[Info]​     at Object.window.__moduleBundler.loadTests (http://localhost:60224/____wallaby-webpack-bootstrapper.js?1653677108225:14:22)
​[Info]​     at http://localhost:60224/wallaby_sandbox0.html:9:26358
​[Info]​     at http://localhost:60224/wallaby_sandbox0.html:9:26372
​[Info]​ 2022-05-27T18:45:08.997Z workers [pddjd] Loaded 0 test(s)
​[Info]​ 2022-05-27T18:45:09.001Z workers [pddjd] Run 0 test(s), skipped 0 test(s)
​[Info]​ 2022-05-27T18:45:09.002Z workers [pddjd] Sandbox is responsive, closing it
​[Info]​ 2022-05-27T18:45:09.004Z project Test run finished
​[Info]​ 2022-05-27T18:45:09.004Z project Processed console.log entries
​[Info]​ 2022-05-27T18:45:09.004Z project Processed loading sequences
​[Info]​ 2022-05-27T18:45:09.004Z project Processed executed tests
​[Info]​ 2022-05-27T18:45:09.004Z project Processed code coverage
​[Info]​ 2022-05-27T18:45:09.006Z project Test run result processed and sent to IDE
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This has been fixed in the latest version of Wallaby core, `v1.0.1271`.

**Comment by rspringAya** [comment]
Thank you for the quick turn around!
