### ISSUE TITLE
Cannot read property 'inline' of undefined

### ISSUE THREAD

**Issue by ervinMagic** [wallabyjs/public#3014]
### Issue description or question

I am no longer able to run our tests using wallaby. 
Let me preface this by saying the configuration file has been stable for almost a year...

On startup it immediately fails with the following output.

```
wallaby.js started
core v1.0.1286
Wallaby App (realtime reports) is available at: http://localhost:51245
{"message":"Cannot read property 'inline' of undefined","stack":"TypeError: Cannot read property 'inline' of undefined\n    at d._format (/Users/ervin/Library/Caches/JetBrains/WebStorm2021.3/wallaby/wallaby/server.js:29:3858)\n    at d._warn (/Users/ervin/Library/Caches/JetBrains/WebStorm2021.3/wallaby/wallaby/server.js:28:31320)\n    at /Users/ervin/Library/Caches/JetBrains/WebStorm2021.3/wallaby/wallaby/server.js:28:22754\n    at Array.<anonymous> (/Users/ervin/Library/Caches/JetBrains/WebStorm2021.3/wallaby/wallaby/server.js:28:31188)\n    at WebSocket.t._receiver.onopen (/Users/ervin/Library/Caches/JetBrains/WebStorm2021.3/wallaby/wallaby/server.js:28:23423)\n    at WebSocket.onOpen (/Users/ervin/Library/Caches/JetBrains/WebStorm2021.3/wallaby/wallaby/node_modules/ws/lib/WebSocket.js:456:14)\n    at WebSocket.emit (events.js:322:22)\n    at WebSocket.establishConnection (/Users/ervin/Library/Caches/JetBrains/WebStorm2021.3/wallaby/wallaby/node_modules/ws/lib/WebSocket.js:887:8)\n    at ClientRequest.upgrade (/Users/ervin/Library/Caches/JetBrains/WebStorm2021.3/wallaby/wallaby/node_modules/ws/lib/WebSocket.js:778:25)\n    at Object.onceWrapper (events.js:417:26)\n    at ClientRequest.emit (events.js:310:20)\n    at Socket.socketOnData (_http_client.js:503:11)\n    at Socket.emit (events.js:310:20)\n    at addChunk (_stream_readable.js:286:12)\n    at readableAddChunk (_stream_readable.js:268:9)\n    at Socket.Readable.push (_stream_readable.js:209:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)","_p":"###wpm###"}
... 
(repeat forever) 
...

```

### Wallaby diagnostics report

```
{
  editorVersion: 'WebStorm 2021.3.1',
  pluginVersion: '1.0.242',
  editorType: 'IntelliJ',
  osVersion: 'darwin 21.5.0',
  nodeVersion: 'v12.16.3',
  coreVersion: '1.0.1286',
  checksum: 'MDNiYjQ4NjVlY2ZmMjI4YzRmYWYxMDI1MjViZWVkMjAsMTY1NTMzNzYwMDAwMCww',
  config: {
    name: 'foo-consumer-api',
    files: [
      { pattern: 'controllers/**/*.js', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: 'helpers/**/*.js', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: 'models/**/*.js', ignore: false, trigger: true, load: true, instrument: true, order: 3 },
      { pattern: 'mailers/**/*.*', ignore: false, trigger: true, load: true, instrument: true, order: 4 },
      { pattern: 'index.js', ignore: false, trigger: true, load: true, instrument: true, order: 5 },
      { pattern: 'spec/**/*-helpers.js', ignore: false, trigger: true, load: true, instrument: true, order: 6 },
      { pattern: 'spec/**/*-spec.js', ignore: true, trigger: true, load: true, instrument: true }
    ],
    tests: [ { pattern: 'spec/**/*-spec.js', ignore: false, trigger: true, load: true, test: true, order: 7 } ],
    debug: false,
    testFramework: { version: 'jasmine@2.3.4', configurator: 'jasmine@2.3.4', reporter: 'jasmine@2.3.4', starter: 'jasmine@2.3.4' },
    reportConsoleErrorAsError: true,
    reportUnhandledPromises: true,
    maxConsoleMessagesPerTest: 3000,
    env: {
      type: 'node',
      runner: '<homeDir>/.nvm/versions/node/v12.16.3/bin/node',
      params: {},
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    workers: { initial: 1, regular: 1, restart: true, recycle: true },
    teardown: "function teardown(wallaby) {\n      console.log('Teardown');\n      console.log(`Current worker id: ${wallaby.workerId}`);\n      console.log(`Current session id: ${wallaby.sessionId}`);\n    }",
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: { '**/*.?(lit)coffee?(.md)': [Function] },
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: undefined,
    symlinkNodeModules: undefined,
    configCode: "const os = require('os');\n" +
      '\n' +
      'module.exports = function (wallaby) {\n' +
      "  process.env.AWS_PROFILE = 'foo';\n" +
      "  process.env.AWS_SDK_LOAD_CONFIG = 'true';\n" +
      '\n' +
      '  return {\n' +
      "    name: 'foo-consumer-api',\n" +
      '    files: [\n' +
      "      'controllers/**/*.js',\n" +
      "      'helpers/**/*.js',\n" +
      "      'models/**/*.js',\n" +
      "      'mailers/**/*.*',\n" +
      "      'index.js',\n" +
      "      'spec/**/*-helpers.js',\n" +
      "      '!spec/**/*-spec.js',\n" +
      '    ],\n' +
      "    tests: ['spec/**/*-spec.js'],\n" +
      '    debug: false,\n' +
      "    testFramework: 'jasmine',\n" +
      "    // filesWithNoCoverageCalculated: ['**/*.*'],\n" +
      '    reportConsoleErrorAsError: true,\n' +
      '    reportUnhandledPromises: true,\n' +
      '    maxConsoleMessagesPerTest: 3000,\n' +
      '    env: {\n' +
      "      type: 'node',\n" +
      '      runner: `${os.homedir()}/.nvm/versions/node/v12.16.3/bin/node`,\n' +
      '    },\n' +
      '    // force tests run in order to prevent PG errors\n' +
      '    workers: {\n' +
      '      initial: 1,\n' +
      '      regular: 1,\n' +
      '      restart: true,\n' +
      '      recycle: false,\n' +
      '    },\n' +
      '    setup(wallaby) {\n' +
      '      console.log(`Node Version: ${process.version}`);\n' +
      "      console.log('Setup');\n" +
      '      console.log(`Current worker id: ${wallaby.workerId}`);\n' +
      '      console.log(`Current session id: ${wallaby.sessionId}`);\n' +
      '      wallaby.delayStart();\n' +
      '      wallaby.testFramework.DEFAULT_TIMEOUT_INTERVAL = 10000;\n' +
      '\n' +
      "      const root = require('rootrequire');\n" +
      '      const helper = require(`${root}/controllers/helper`);\n' +
      '      const specGlobalHelpers = require(`${root}/spec/helpers/global-helpers`);\n' +
      '      const specFixtureHelpers = require(`${root}/spec/helpers/fixture-helpers`);\n' +
      '      const config = require(`${root}/config.json`)[specGlobalHelpers.testEnv];\n' +
      "      const request = require('request');\n" +
      '      request.env = specGlobalHelpers.testEnv;\n' +
      '      request.config = config;\n' +
      '      return helper.models(request).then(function (db) {\n' +
      '        console.log(\n' +
      "          'specFixtureHelpers.buildEnterpriseTemplate()',\n" +
      '          specFixtureHelpers.buildEnterpriseTemplate()\n' +
      '        );\n' +
      '        if (wallaby.workerId === 0) {\n' +
      '          return db.enterprise_template\n' +
      '            .destroy({ truncate: true, individualHooks: false, hooks: false })\n' +
      '            .then(function () {\n' +
      '              return db.enterprise_template\n' +
      '                .create(specFixtureHelpers.buildEnterpriseTemplate(), {\n' +
      '                  individualHooks: false,\n' +
      '                  hooks: false,\n' +
      '                })\n' +
      '                .then(function (test) {\n' +
      '                  return wallaby.start();\n' +
      '                });\n' +
      '            });\n' +
      '        }\n' +
      '        return wallaby.start();\n' +
      '      });\n' +
      '    },\n' +
      '    // teardown only invoked if setup is invoked\n' +
      '    teardown(wallaby) {\n' +
      "      console.log('Teardown');\n" +
      '      console.log(`Current worker id: ${wallaby.workerId}`);\n' +
      '      console.log(`Current session id: ${wallaby.sessionId}`);\n' +
      '    },\n' +
      '  };\n' +
      '};\n'
  },
  packageJSON: {
    dependencies: {
      '@aws-sdk/client-s3': '^3.75.0',
      '@aws-sdk/client-ses': '^3.75.0',
      '@aws-sdk/client-sesv2': '^3.75.0',
      '@aws-sdk/client-sns': '^3.75.0',
      '@aws-sdk/s3-request-presigner': '^3.75.0',
      '@google/maps': '^1.1.3',
      auth0: '^2.20.0',
      axios: '^0.21.1',
      'base-64': '^1.0.0',
      bluebird: '3.7.2',
      cancan: '3.1.0',
      'claudia-api-builder': '4.1.0',
      'cls-hooked': '^4.2.2',
      'cron-parser': '2.13.0',
      dotenv: '^6.0.0',
      'email-templates': '^2.5.4',
      express: '^4.14.1',
      faker: '^4.1.0',
      'fast-csv': '^4.3.5',
      fuzzysort: '^1.1.4',
      'generate-password': '^1.4.2',
      hashids: '^1.1.1',
      jsforce: '1.9.3',
      jsonwebtoken: '7.1.x',
      'jwks-rsa': '^1.3.0',
      'lambda-log': '^3.0.0',
      less: '^3.10.3',
      lodash: '^4.17.21',
      luxon: '^1.22.0',
      moment: '^2.29.3',
      'moment-business-days': '^1.1.3',
      'moment-range': '^4.0.1',
      'node-uuid': '^1.4.8',
      npm: '^6.9.0',
      'number-to-words': '^1.2.3',
      nunjucks: '^3.2.3',
      pg: '^8.7.3',
      'pg-hstore': '2.3.x',
      plaid: '^4.1.0',
      'promise-retry': '1.1.1',
      randomstring: '^1.1.5',
      request: '2.88.0',
      'request-promise': '4.2.5',
      rootrequire: '^1.0.0',
      sequelize: '5.21.2',
      'sequelize-cli': '5.5.1',
      'slack-notify': '^0.1.7',
      stripe: '8.4.1',
      styleme: '^2.5.4',
      twilio: '^3.77.1',
      underscore: '^1.13.3',
      utf8: '^3.0.0',
      util: '0.12.1',
      'util.promisify': '^1.0.0',
      validator: '^10.2.0'
    },
    devDependencies: {
      'body-parser': '^1.16.0',
      chalk: '^2.1.0',
      claudia: '^5.11.0',
      csv: '^1.1.1',
      eslint: '^6.8.0',
      'eslint-config-airbnb': '^18.1.0',
      'eslint-config-prettier': '^6.11.0',
      'eslint-plugin-import': '^2.20.2',
      'eslint-plugin-jsx-a11y': '^6.2.3',
      'eslint-plugin-prettier': '^3.1.3',
      'eslint-plugin-react': '^7.19.0',
      'eslint-plugin-react-hooks': '^2.5.0',
      esm: '^3.2.25',
      fs: '0.0.1-security',
      jasmine: '2.99.0',
      'jasmine-core': '2.99.0',
      'jasmine-reporters': '^2.5.0',
      'lambda-local': '^1.6.2',
      multer: '^1.3.0',
      ngrok: '^2.2.6',
      'opn-cli': '3.1.x',
      prettier: '2.0.5',
      'sequelize-erd': '^1.3.0',
      'serverless-newrelic-lambda-layers': '^0.3.0',
      'serverless-prune-plugin': '^1.4.3',
      supervisor: '^0.12.0',
      yargs: '^6.6.0'
    }
  },
  fs: { numberOfFiles: 662 },
  debug: [
    '2022-06-21T13:14:52.480Z project Wallaby Node version: v12.16.3\n',
    '2022-06-21T13:14:52.480Z project Wallaby config: <homeDir>/Projects/ibeat-consumer-api/wallaby.js\n',
    '2022-06-21T13:14:53.662Z fs File system scan has finished by timeout\n',
    '2022-06-21T13:14:53.678Z project File cache: <homeDir>/Library/Caches/JetBrains/WebStorm2021.3/wallaby/projects/a88f0ad537c0d630\n',
    '2022-06-21T13:14:53.741Z uiService Listening port 51235\n',
    '2022-06-21T13:14:53.757Z project Config file change detected, invalidating local cache\n',
    '2022-06-21T13:14:53.802Z workers Parallelism for initial run: 1, for regular run: 1\n',
    '2022-06-21T13:14:53.802Z workers Starting run worker instance #0\n',
    '2022-06-21T13:14:53.802Z workers Web server is listening at 52116\n',
    '2022-06-21T13:14:53.802Z project File cache requires some updates, waiting required files from IDE\n',
    `2022-06-21T13:14:54.038Z nodeRunner Error in worker: {"message":"Cannot read property 'inline' of undefined","stack":"TypeError: Cannot read property 'inline' of undefined\\n    at d._format (<homeDir>/Library/Caches/JetBrains/WebStorm2021.3/wallaby/wallaby/server.js:29:3858)\\n    at d._warn (<homeDir>/Library/Caches/JetBrains/WebStorm2021.3/wallaby/wallaby/server.js:28:31320)\\n    at <homeDir>/Library/Caches/JetBrains/WebStorm2021.3/wallaby/wallaby/server.js:28:22754\\n    at Array.<anonymous> (<homeDir>/Library/Caches/JetBrains/WebStorm2021.3/wallaby/wallaby/server.js:28:31188)\\n    at WebSocket.t._receiver.onopen (<homeDir>/Library/Caches/JetBrains/WebStorm2021.3/wallaby/wallaby/server.js:28:23423)\\n    at WebSocket.onOpen (<homeDir>/Library/Caches/JetBrains/WebStorm2021.3/wallaby/wallaby/node_modules/ws/lib/WebSocket.js:456:14)\\n    at WebSocket.emit (events.js:322:22)\\n    at WebSocket.establishConnection (<homeDir>/Library/Caches/JetBrains/WebStorm2021.3/wallaby/wallaby/node_modules/ws/lib/WebSocket.js:887:8)\\n    at ClientRequest.upgrade (<homeDir>/Library/Caches/JetBrains/WebStorm2021.3/wallaby/wallaby/node_modules/ws/lib/WebSocket.js:778:25)\\n    at Object.onceWrapper (events.js:417:26)\\n    at ClientRequest.emit (events.js:310:20)\\n    at Socket.socketOnData (_http_client.js:503:11)\\n    at Socket.emit (events.js:310:20)\\n    at addChunk (_stream_readable.js:286:12)\\n    at readableAddChunk (_stream_readable.js:268:9)\\n    at Socket.Readable.push (_stream_readable.js:209:10)\\n    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)","_p":"###wpm###"}\n`,
    '2022-06-21T13:14:56.020Z project Stopping process pool\n',
    '2022-06-21T13:14:56.026Z project Running postprocessor\n',
    '2022-06-21T13:14:56.050Z postprocessor New TypeScript language service is required\n',
    "2022-06-21T13:14:56.058Z postprocessor TypeScript postprocessor will be removed because in 662 project files none were found by patterns: [ '**/*.ts?(x)' ]\n",
    '2022-06-21T13:14:56.063Z project Postprocessor execution finished\n',
    '2022-06-21T13:14:56.063Z project Postprocessor is removed as requested by itself\n',
    '2022-06-21T13:14:56.063Z project Promoting test run to full run because of test selection changes\n',
    '2022-06-21T13:14:56.063Z project Test run started; run priority: 3\n',
    '2022-06-21T13:14:56.064Z project Running all tests\n',
    '2022-06-21T13:14:56.070Z workers Starting test run, priority: 3\n',
    '2022-06-21T13:14:56.070Z nodeRunner Starting sandbox [worker #0, session #q7wlr]\n',
    '2022-06-21T13:14:56.072Z nodeRunner Preparing sandbox [worker #0, session #q7wlr]\n'
  ]
}
```

**Comment by danieljnewsome732** [comment]
Also having the same issue.  Have tried changing config, upgrading node, clearing npx cache, using previous versions of Wallaby.js, upgrading WebStorm, using autoconfig. No luck

**Comment by smcenlly** [comment]
Thanks for reporting the problem. Please update to Wallaby core `v1.0.1288`, it should work for you.
