### ISSUE TITLE
Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by PavelA85** [wallabyjs/public#3031]
### Issue description or question
After a recent Wallaby update, I started to see this exception.
Restarting wallaby runner helps.

```
console.log: Jest:   ● Test suite failed to run

    TypeError: Cannot set property '0' of undefined
      at d.statement (../../Users/myuser/AppData/Local/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:28:27608)
      at f.$_$w.f.$_$w_.e.$_$w.e.$_$w_ (../../Users/myuser/AppData/Local/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:30:3958)
      at Object.<anonymous> (src/components/actions/sections/SectionBody/Components/EntityAttribute/index.tsx:55:1)
      at Object.<anonymous> (src/components/review/sections/SectionBody/Components/EntityAttribute/index.tsx:16:47)
      at Object.<anonymous> (src/components/review/sections/SectionBody/Items/Component.tsx:14:70)
      at Object.<anonymous> (src/components/review/sections/SectionBody/Items/Line.tsx:7:40)
      at Object.<anonymous> (src/components/review/sections/SectionBody/Items/Orderable.tsx:8:35)
      at Object.<anonymous> (src/components/review/sections/SectionBody/index.tsx:6:62)
      at Object.<anonymous> (src/components/review/sections/ReviewSections.tsx:8:64)
      at Object.<anonymous> (src/components/review/sections/index.ts:12:68)
      at Object.<anonymous> (src/features/mozart/components/MozartContent/components/MozartUserInput.tsx:10:62)
      at Object.<anonymous> (src/features/mozart/components/MozartContent/components/index.ts:4:46)
      at Object.<anonymous> (src/features/mozart/components/MozartContent/MozartContent.tsx:10:41)
      at Object.<anonymous> (src/features/mozart/components/MozartPrintLayout/MozartPrintLayout.tsx:10:44)
      at Object.<anonymous> (src/features/mozart/components/MozartFooter/MozartFinishFooter.tsx:19:72)
      at Object.<anonymous> (src/features/mozart/components/MozartFooter/MozartFinishFooter.test.tsx:8:49)


Runtime error: TypeError: Cannot set property '0' of undefined
    at Object.<anonymous> (.\src\components\actions\sections\SectionBody\Components\EntityAttribute\index.tsx:55:1)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:1299:24)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:898:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:746:10)
    at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:919:21)
    at Object.<anonymous> (.\src\components\review\sections\SectionBody\Components\EntityAttribute\index.tsx:16:47)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:1299:24)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:898:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:746:10)
    at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:919:21)
    at Object.<anonymous> (.\src\components\review\sections\SectionBody\Items\Component.tsx:14:70)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:1299:24)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:898:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:746:10)
    at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:919:21)
    at Object.<anonymous> (.\src\components\review\sections\SectionBody\Items\Line.tsx:7:40)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:1299:24)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:898:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:746:10)
    at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:919:21)
    at Object.<anonymous> (.\src\components\review\sections\SectionBody\Items\Orderable.tsx:8:35)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:1299:24)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:898:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:746:10)
    at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:919:21)
    at Object.<anonymous> (.\src\components\review\sections\SectionBody\index.tsx:6:62)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:1299:24)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:898:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:746:10)
    at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:919:21)
    at Object.<anonymous> (.\src\components\review\sections\ReviewSections.tsx:8:64)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:1299:24)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:898:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:746:10)
    at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:919:21)
    at Object.<anonymous> (.\src\components\review\sections\index.ts:12:68)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:1299:24)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:898:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:746:10)
    at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:919:21)
    at Object.<anonymous> (.\src\features\mozart\components\MozartContent\components\MozartUserInput.tsx:10:62)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:1299:24)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:898:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:746:10)
    at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:919:21)
    at Object.<anonymous> (.\src\features\mozart\components\MozartContent\components\index.ts:4:46)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:1299:24)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:898:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:746:10)
    at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:919:21)
    at Object.<anonymous> (.\src\features\mozart\components\MozartContent\MozartContent.tsx:10:41)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:1299:24)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:898:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:746:10)
    at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:919:21)
    at Object.<anonymous> (.\src\features\mozart\components\MozartPrintLayout\MozartPrintLayout.tsx:10:44)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:1299:24)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:898:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:746:10)
    at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:919:21)
    at Object.<anonymous> (.\src\features\mozart\components\MozartFooter\MozartFinishFooter.tsx:19:72)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:1299:24)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:898:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:746:10)
    at Runtime.requireModuleOrMock (.\node_modules\jest-runtime\build\index.js:919:21)
    at Object.<anonymous> (.\src\features\mozart\components\MozartFooter\MozartFinishFooter.test.tsx:8:49)
    at Runtime._execModule (.\node_modules\jest-runtime\build\index.js:1299:24)
    at Runtime._loadModule (.\node_modules\jest-runtime\build\index.js:898:12)
    at Runtime.requireModule (.\node_modules\jest-runtime\build\index.js:746:10)
    at jestAdapter (.\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapter.js:106:13)
    at runTestInternal (.\node_modules\jest-runner\build\runTest.js:380:16)
    at runTest (.\node_modules\jest-runner\build\runTest.js:472:34)
```

**Comment by PavelA85** [comment]
Not sure if it is connected issue, but also I started to this kind of errors:
```
Test file 'src/components/footer/Footer.test.tsx' is importing or is causing import of another test file 'src/features/mozart/components/MozartFooter/MozartFinishFooter.test.tsx'.
This may cause tests in the 'src/features/mozart/components/MozartFooter/MozartFinishFooter.test.tsx' file to be executed more than once (when the test file runs and every time it gets imported).
If the 'src/features/mozart/components/MozartFooter/MozartFinishFooter.test.tsx' test file contains some test helper code, try refactoring the reused code into a file of its own and use it by importing the new file into 'src/components/footer/Footer.test.tsx' and 'src/features/mozart/components/MozartFooter/MozartFinishFooter.test.tsx' test files.
```

I could not find the references test to test mentioned in this log.

**Comment by smcenlly** [comment]
Could you please try running:

```
npx jest --clearCache
```

That should clear your jest cache for all projects. After doing that, please let us know if you see the error again. If you do, please also tell us if you remember any specific steps your were taking prior to seeing the error that you think may be helpful in reproducing the problem.

---

RE: 

> Not sure if it is a connected issue, but also I started to this kind of error:
> ```
> Test file 'src/components/footer/Footer.test.tsx' is importing or is causing import of another test file 'src/features/mozart/components/MozartFooter/MozartFinishFooter.test.tsx'.
> This may cause tests in the 'src/features/mozart/components/MozartFooter/MozartFinishFooter.test.tsx' file to be executed more than once (when the test file runs and every time it gets imported).
> If the 'src/features/mozart/components/MozartFooter/MozartFinishFooter.test.tsx' test file contains some test helper code, try refactoring the reused code into a file of its own and use it by importing the new file into 'src/components/footer/Footer.test.tsx' and 'src/features/mozart/components/MozartFooter/MozartFinishFooter.test.tsx' test files.
> ```

I think we would need to see your project source code in order understand your file/project structure and how/why this might be occurring.

--

If you're still having problems, could you please provide us with your:

* package.json
* jest configuration
* typescript configuration
* instructions for how you run your tests from the command-line
* react-rewired configuration (assuming it's relevant)

**Comment by smcenlly** [comment]
Assuming our suggestion worked for you. If not, please provide us with the details requested and we will re-open the issue and continue investigating.

**Comment by PavelA85** [comment]
Yes, it worked.
Thank you!
