### ISSUE TITLE
Can't debug source (only unit test code) and can't see coverage/status on source code (only unit tests)

### ISSUE THREAD

**Issue by tohagan** [wallabyjs/public#3039]
### Issue description or question

Used Wallaby's automatic configuration and selected the subproject folder that is a VSCode workspace folder (`functions/`). 

Fairly simple vanilla folders: 
- `functions/src/**/*.ts`
- `functions/test/**/*.spec.ts`

Jest unit tests run, however ... 

- (a) When running a unit test with Wallby debugger, the debugger won't step into the source code calls (only steps over unit test code).  Adding breakpoints OR adding `debugger` statements to the source code also won't stop the Wallby debugger.

- (b) Code coverage indicators (coloured squares) only display on `test/**/*.spec.ts` unit test code not in source code `src/**/*.ts` unlike other projects I use Wallaby with.

Attempted to fix:
- Done many **Reset Wallaby Cache** and **Wallaby Start** . 
- Check coverage settings

## jest-config.js
```js
module.exports = {
  preset: 'ts-jest',
  // testEnvironment: 'jsdom',
  testEnvironment: 'node',
  // runInBand: true,
  // testPathIgnorePatterns: ['/fixtures/', '/utils/'],

  /// Have attempted with these coverage settings both ON and DISABLED
  // collectCoverage: true,
  // coverageDirectory: 'coverage',
  // coverageReporters: ['html', 'lcov', 'text'],
  // collectCoverageFrom: ['/src/**/*.ts'],
  // coveragePathIgnorePatterns: ['/node_modules/', 'src/index.ts', '\\.d\\.ts$'],
  testMatch: ['<rootDir>/test/**/*.spec.ts'],
  rootDir: __dirname,
  globals: {
    __DEV__: true,
    __TEST__: true,
    __BROWSER__: true,
  },
}
```

Also Wallany Console is reporting this error which does not make any sense since there are Jest unit tests and they are running
```
​​[Error] Runtime error: Your test suite must contain at least one test.​​
​​[Error]     at onResult (.\node_modules\@jest\core\build\TestScheduler.js:172:18)​​
​​[Error]     at .\node_modules\@jest\core\build\TestScheduler.js:300:17​​
​​[Error]     at .\node_modules\emittery\index.js:311:13​​
​​[Error]     at Array.map (<anonymous>)​​
​​[Error]     at Emittery.emit (.\node_modules\emittery\index.js:309:23)​​
```

### Wallaby diagnostics report

```
{
  editorVersion: '1.69.2',
  pluginVersion: '1.0.346',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.19044',
  nodeVersion: 'v14.19.0',
  coreVersion: '1.0.1310',
  checksum: 'YmYwZWJjMmM3YTU5ZDdkODkzN2RhMGQwZjA2ZDY0ZjgsMTY2OTUwNzIwMDAwMCww',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: 'C:\\Users\\tony\\AppData\\Local\\Temp\\jest',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '\\\\node_modules\\\\' ],
              cwd: 'C:\\Users\\tony\\Projects\\Fundable\\PTC-PAYMENTS\\functions',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: undefined,
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              fakeTimers: { enableGlobally: false },
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: { __DEV__: true, __TEST__: true, __BROWSER__: true },
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: true, throwOnModuleCollision: false },
              id: 'ed3340df6aa12cacdcf3387ddf53dfbc',
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [
                'js',   'mjs',
                'cjs',  'jsx',
                'ts',   'tsx',
                'json', 'node'
              ],
              moduleNameMapper: [],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: 'C:\\Users\\tony\\Projects\\Fundable\\PTC-PAYMENTS\\functions',
              roots: [ 'C:\\Users\\tony\\Projects\\Fundable\\PTC-PAYMENTS\\functions' ],
              runner: 'C:\\Users\\tony\\Projects\\Fundable\\PTC-PAYMENTS\\functions\\node_modules\\jest-runner\\build\\index.js',
              runtime: undefined,
              sandboxInjectedGlobals: [],
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: 'C:\\Users\\tony\\Projects\\Fundable\\PTC-PAYMENTS\\functions\\node_modules\\jest-environment-node\\build\\index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ 'C:/Users/tony/Projects/Fundable/PTC-PAYMENTS/functions/test/**/*.spec.ts' ],
              testPathIgnorePatterns: [ '\\\\node_modules\\\\' ],
              testRegex: [],
              testRunner: 'C:\\Users\\tony\\Projects\\Fundable\\PTC-PAYMENTS\\functions\\node_modules\\jest-circus\\runner.js',
              transform: [ [ '^.+\\.tsx?$', 'C:\\Users\\tony\\Projects\\Fundable\\PTC-PAYMENTS\\functions\\node_modules\\ts-jest\\dist\\index.js', {} ] ],
              transformIgnorePatterns: [ '\\\\node_modules\\\\', '\\.pnp\\.[^\\\\]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            ci: false,
            collectCoverage: false,
            collectCoverageFrom: [],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: 'C:\\Users\\tony\\Projects\\Fundable\\PTC-PAYMENTS\\functions\\coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 7,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: 'C:\\Users\\tony\\Projects\\Fundable\\PTC-PAYMENTS\\functions',
            runTestsByPath: false,
            shard: undefined,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: undefined,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: 'C:\\Users\\tony\\Projects\\Fundable\\PTC-PAYMENTS\\functions\\node_modules\\@jest\\test-sequencer\\build\\index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '\\\\node_modules\\\\', '\\.\\\\dist\\\\|\\.\\\\build\\\\|\\.\\\\coverage\\\\|\\.\\\\git\\\\|\\\\\\..+\\\\', 'C:\\Users\\tony\\AppData\\Local\\Temp\\jest', '\\.\\coverage' ],
            testPathIgnorePatterns: [ '\\\\node_modules\\\\', '\\.\\\\dist\\\\|\\.\\\\build\\\\|\\.\\\\coverage\\\\|\\.\\\\git\\\\|\\\\\\..+\\\\', 'C:\\Users\\tony\\AppData\\Local\\Temp\\jest', '\\.\\coverage' ],
            testMatch: [ 'test/**/*.spec.ts' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    micromatch: true,
    files: [
      { pattern: '\\\\node_modules\\\\', regexp: /\\node_modules\\/, ignore: true, trigger: true, load: true },
      {
        pattern: '\\.\\\\dist\\\\|\\.\\\\build\\\\|\\.\\\\coverage\\\\|\\.\\\\git\\\\|\\\\\\..+\\\\',
        regexp: /\.\\dist\\|\.\\build\\|\.\\coverage\\|\.\\git\\|\\\..+\\/,
        ignore: true,
        trigger: true,
        load: true
      },
      { pattern: 'C:\\Users\\tony\\AppData\\Local\\Temp\\jest', regexp: /<homeDir>\AppData\Local\Temp\jest/, ignore: true, trigger: true, load: true },
      { pattern: '\\.\\coverage', regexp: /\.\coverage/, ignore: true, trigger: true, load: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'test/**/*.spec.ts', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '\\\\node_modules\\\\', regexp: /\\node_modules\\/, ignore: true, trigger: true, load: true, test: true },
      {
        pattern: '\\.\\\\dist\\\\|\\.\\\\build\\\\|\\.\\\\coverage\\\\|\\.\\\\git\\\\|\\\\\\..+\\\\',
        regexp: /\.\\dist\\|\.\\build\\|\.\\coverage\\|\.\\git\\|\\\..+\\/,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      { pattern: 'C:\\Users\\tony\\AppData\\Local\\Temp\\jest', regexp: /<homeDir>\AppData\Local\Temp\jest/, ignore: true, trigger: true, load: true, test: true },
      { pattern: '\\.\\coverage', regexp: /\.\coverage/, ignore: true, trigger: true, load: true, test: true },
      { pattern: 'test/**/*.spec.ts', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: 'C:\\nodejs\\node.exe', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#2028779941'
  },
  packageJSON: {
    dependencies: { axios: '^0.27.2', 'firebase-admin': '^10.0.2', 'firebase-functions': '^3.18.0', xml2js: '^0.4.23' },
    devDependencies: {
      '@ngneat/falso': '^6.1.0',
      '@types/jest': '^28.1.4',
      '@types/xml2js': '^0.4.11',
      '@typescript-eslint/eslint-plugin': '^5.12.0',
      '@typescript-eslint/parser': '^5.12.0',
      eslint: '^8.9.0',
      'eslint-config-google': '^0.14.0',
      'eslint-plugin-import': '^2.25.4',
      'eslint-plugin-jest': '^26.7.0',
      'firebase-functions-test': '^0.2.0',
      jest: '^28.1.2',
      'ts-jest': '^28.0.5',
      typescript: '^4.5.4'
    }
  },
  fs: { numberOfFiles: 34 },
  debug: [
    '2022-08-04T06:50:02.966Z config Attempting automatic configuration for angular\n',
    '2022-08-04T06:50:02.978Z angular/cli config Angular CLI not found.\n',
    '2022-08-04T06:50:02.978Z config Finished attempting automatic configuration for angular (12ms)\n',
    '2022-08-04T06:50:02.978Z config Attempting automatic configuration for jest\n',
    '2022-08-04T06:50:03.233Z jest/config Detected Jest.\n',
    '2022-08-04T06:50:03.233Z jest/config Configured Jest.\n',
    '2022-08-04T06:50:03.233Z config Finished attempting automatic configuration for jest (255ms)\n',
    '2022-08-04T06:50:03.235Z project Wallaby Node version: v14.19.0\n',
    '2022-08-04T06:50:03.235Z project Wallaby config: C:\\Users\\tony\\Projects\\Fundable\\PTC-PAYMENTS\\functions\\auto.detect\n',
    '2022-08-04T06:50:03.380Z project File cache: C:\\Users\\tony\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.346\\projects\\58c871c3ef196ca0\n',
    '2022-08-04T06:50:03.659Z uiService Listening port 51235\n',
    '2022-08-04T06:50:03.690Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2022-08-04T06:50:03.690Z workers Starting run worker instance #0\n',
    '2022-08-04T06:50:03.690Z workers Starting run worker instance #1\n',
    '2022-08-04T06:50:03.690Z workers Starting run worker instance #2\n',
    '2022-08-04T06:50:03.690Z workers Starting run worker instance #3\n',
    '2022-08-04T06:50:03.691Z workers Starting run worker instance #4\n',
    '2022-08-04T06:50:03.691Z workers Starting run worker instance #5\n',
    '2022-08-04T06:50:03.693Z workers Web server is listening at 56785\n',
    '2022-08-04T06:50:03.749Z project File cache requires some updates, waiting required files from IDE\n',
    '2022-08-04T06:50:03.795Z project Stopping process pool\n',
    '2022-08-04T06:50:03.797Z project Test run started; run priority: 3\n',
    '2022-08-04T06:50:03.799Z project Running all tests\n',
    '2022-08-04T06:50:03.802Z workers Starting test run, priority: 3\n',
    '2022-08-04T06:50:03.802Z workers Distributing tests between 6 workers\n',
    '2022-08-04T06:50:03.803Z workers Running tests in parallel\n',
    '2022-08-04T06:50:03.803Z nodeRunner Starting sandbox [worker #0, session #o5f9o]\n',
    '2022-08-04T06:50:03.804Z nodeRunner Starting sandbox [worker #1, session #msbjd]\n',
    '2022-08-04T06:50:03.804Z nodeRunner Starting sandbox [worker #2, session #9ms2k]\n',
    '2022-08-04T06:50:03.804Z nodeRunner Preparing sandbox [worker #0, session #o5f9o]\n',
    '2022-08-04T06:50:03.804Z nodeRunner Preparing sandbox [worker #1, session #msbjd]\n',
    '2022-08-04T06:50:03.804Z nodeRunner Preparing sandbox [worker #2, session #9ms2k]\n',
    '2022-08-04T06:50:04.133Z workers Started run worker instance (delayed) #1\n',
    '2022-08-04T06:50:04.133Z nodeRunner Prepared sandbox [worker #1, session #msbjd]\n',
    '2022-08-04T06:50:04.134Z workers [worker #1, session #msbjd] Running tests in sandbox\n',
    '2022-08-04T06:50:04.137Z workers Started run worker instance (delayed) #2\n',
    '2022-08-04T06:50:04.138Z nodeRunner Prepared sandbox [worker #2, session #9ms2k]\n',
    '2022-08-04T06:50:04.138Z workers [worker #2, session #9ms2k] Running tests in sandbox\n',
    '2022-08-04T06:50:04.158Z workers Started run worker instance (delayed) #3\n',
    '2022-08-04T06:50:04.161Z workers Started run worker instance (delayed) #0\n',
    '2022-08-04T06:50:04.161Z nodeRunner Prepared sandbox [worker #0, session #o5f9o]\n',
    '2022-08-04T06:50:04.161Z workers [worker #0, session #o5f9o] Running tests in sandbox\n',
    '2022-08-04T06:50:04.172Z workers Started run worker instance (delayed) #4\n',
    '2022-08-04T06:50:04.200Z workers Started run worker instance (delayed) #5\n',
    '2022-08-04T06:50:09.973Z workers Scheduling Jest Test Run (msbjd): 2022-08-04T06:50:04.857Z\n',
    '2022-08-04T06:50:09.974Z workers [msbjd] Loaded unknown number of test(s)\n',
    '2022-08-04T06:50:09.977Z workers Sandbox (active) [msbjd] error: Your test suite must contain at least one test.\n' +
      '    at onResult (.\\node_modules\\@jest\\core\\build\\TestScheduler.js:172:18)\n' +
      '    at .\\node_modules\\@jest\\core\\build\\TestScheduler.js:300:17\n' +
      '    at .\\node_modules\\emittery\\index.js:311:13\n' +
      '    at Array.map (<anonymous>)\n' +
      '    at Emittery.emit (.\\node_modules\\emittery\\index.js:309:23)\n',
    '2022-08-04T06:50:09.984Z workers [msbjd] Run 0 test(s), skipped 0 test(s)\n',
    '2022-08-04T06:50:09.984Z workers Jest Test Run Complete (msbjd): 2022-08-04T06:50:09.969Z\n',
    '2022-08-04T06:50:09.986Z workers [msbjd] Sandbox is responsive, closing it\n',
    '2022-08-04T06:50:09.988Z workers Failed to map the stack to user code, entry message: Your test suite must contain at least one test., stack: Error: Your test suite must contain at least one test.\n' +
      '    at onResult (C:\\Users\\tony\\Projects\\Fundable\\PTC-PAYMENTS\\functions\\node_modules\\@jest\\core\\build\\TestScheduler.js:172:18)\n' +
      '    at C:\\Users\\tony\\Projects\\Fundable\\PTC-PAYMENTS\\functions\\node_modules\\@jest\\core\\build\\TestScheduler.js:300:17\n' +
      '    at C:\\Users\\tony\\Projects\\Fundable\\PTC-PAYMENTS\\functions\\node_modules\\emittery\\index.js:311:13\n' +
      '    at Array.map (<anonymous>)\n' +
      '    at Emittery.emit (C:\\Users\\tony\\Projects\\Fundable\\PTC-PAYMENTS\\functions\\node_modules\\emittery\\index.js:309:23)\n',
    '2022-08-04T06:50:10.027Z workers Scheduling Jest Test Run (o5f9o): 2022-08-04T06:50:04.879Z\n',
    '2022-08-04T06:50:10.028Z workers [o5f9o] Loaded unknown number of test(s)\n',
    '2022-08-04T06:50:10.029Z workers [o5f9o] Test executed: should return a token\n',
    '2022-08-04T06:50:10.102Z workers Scheduling Jest Test Run (9ms2k): 2022-08-04T06:50:04.852Z\n',
    '2022-08-04T06:50:10.103Z workers [9ms2k] Loaded unknown number of test(s)\n',
    '2022-08-04T06:50:10.106Z workers [9ms2k] Test executed: returns valid codes\n',
    '2022-08-04T06:50:10.188Z workers [o5f9o] Test executed: should return a token\n',
    '2022-08-04T06:50:10.349Z workers [o5f9o] Test executed: should return a valid axios client\n',
    '2022-08-04T06:50:10.360Z workers [o5f9o] Run 3 test(s), skipped 0 test(s)\n',
    '2022-08-04T06:50:10.361Z workers Jest Test Run Complete (o5f9o): 2022-08-04T06:50:10.347Z\n',
    '2022-08-04T06:50:10.363Z workers [o5f9o] Sandbox is responsive, closing it\n',
    '2022-08-04T06:50:10.419Z workers [9ms2k] Test executed: should succeed\n',
    '2022-08-04T06:50:10.419Z workers Failed to map the stack to user code, entry message: Error: read ECONNRESET, stack: Error: read ECONNRESET\n' +
      '    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)\n',
    '2022-08-04T06:50:10.428Z workers [9ms2k] Run 2 test(s), skipped 0 test(s)\n',
    '2022-08-04T06:50:10.429Z workers Jest Test Run Complete (9ms2k): 2022-08-04T06:50:10.409Z\n',
    '2022-08-04T06:50:10.430Z workers [9ms2k] Sandbox is responsive, closing it\n',
    '2022-08-04T06:50:10.431Z workers Merging parallel test run results\n',
    '2022-08-04T06:50:10.432Z project Test run finished\n',
    '2022-08-04T06:50:10.433Z project Processed console.log entries\n',
    '2022-08-04T06:50:10.433Z project Processed loading sequences\n',
    '2022-08-04T06:50:10.434Z project Processed executed tests\n',
    '2022-08-04T06:50:10.436Z project Processed code coverage\n',
    '2022-08-04T06:50:10.459Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
Thanks for sharing the report. Unfortunately we can't reproduce the issue. We have created a sample repo here https://github.com/wallabyjs/wallaby-3039 with your config/dependencies and a simple test + a source file, and everything seems to be working as expected:

![3039](https://user-images.githubusercontent.com/979966/182794409-8ac30a1a-e5c2-4f23-b0ba-4080ab3d7091.gif)

I'm guessing we are missing some of the details specific to your project, can you please clone the https://github.com/wallabyjs/wallaby-3039 sample repo, run `npm install` in the `functions` folder and run Wallaby on it? If the sample repo is working for you, can you please compare it to your project to see what is missing (alternatively it may be easier if you create a repro from your real project by removing all of the source/tests and leaving a simple test/module like in the sample repo)?

**Comment by tohagan** [comment]
I've now solved this issue. 

1. I had `describe()` containing NO it() calls that caused this jest error (not from WallabyJS) ... 
 - `​​[Error] Runtime error: Your test suite must contain at least one test.​​`
 
 2. I added the `.vscode/launch.json`  file below to the VSCode project and for some reason that caused WallbyJS  to perform the code coverage and the debugger also now worked properly.  I'm not sure why, but one theory I have is that WallbyJS's auto configuration needed this to configure itself correctly (e.g. it now knew to use the node debugger)
 
 ```json
{
  "configurations": [
    {
      "type": "node",
      "name": "Jest Tests",
      "request": "launch",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "npm",
      "args": [
        "jest",
        "--env=node",
        "--watch",
        "--runInBand",
        "--watchAll=false",
        "--collectCoverage=false"
      ]
    }
  ]
}
```

**Comment by smcenlly** [comment]
> 2. I added the `.vscode/launch.json`  file below to the VSCode project and for some reason that caused WallbyJS  to perform the code coverage and the debugger also now worked properly.  I'm not sure why, but one theory I have is that WallbyJS's auto configuration needed this to configure itself correctly (e.g. it now knew to use the node debugger)
> 
> 3. I also disabled and re-enabled WallabyJS in VSCode. Not sure if that contributed to fixing it. 

Wallaby doesn't use or reference your launch configuration. With your other error, perhaps it just needed to be restarted if you didn't change anything else.

If it happens again and you can provide more detail, please let us know.
