### ISSUE TITLE
Cannot read properties of undefined (reading 'describe') (mocha, typescript) inside npm/yarn workspaces

### ISSUE THREAD

**Issue by lamartire** [wallabyjs/public#3040]
### Issue description or question

When I try to run wallaby inside a npm workspace's package it always shows this error. Plain tests execution via npm-script works perfectly.

By the way, wallaby works brilliantly with pnpm-workspaces, but they have another module linking strategy, I would say – they don't link all the packages, like npm or yarn do that.

What's wrong? How I can solve the problem?

```
// npm test script
"test": "npx nyc ts-node --project ./test/tsconfig.json ./test/runner.ts"
```

```js
// wallaby.js
module.exports = (wallaby) => ({
  files: [
    './package.json',
    './src/**/*.ts',
    '!./src/**/*.spec.ts',
  ],
  tests: [
    './src/**/*.spec.ts'
  ],
  env: {
    type: 'node',
  },
  workers: { restart: true },
  compilers: {
    './**/*.ts': wallaby.compilers.typeScript({
      module: 'commonjs',
    })
  },
})
```

```ts
// test/runner.ts
import path from "path";
import fg from "fast-glob";
import Mocha from "mocha";
import "source-map-support/register";

const mocha = new Mocha();

fg.sync([path.resolve(__dirname, "../src/**/*.spec.ts")]).forEach((file) =>
  mocha.addFile(file)
);

mocha.run((failures) => process.exit(failures === 0 ? 0 : 1));
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "strict": true,
    "target": "ES2020",
    "module": "CommonJS",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "isolatedModules": true
  }
}
```

### Wallaby diagnostics report

```
{
  editorVersion: 'IntelliJ IDEA 2022.2',
  pluginVersion: '1.0.250',
  editorType: 'IntelliJ',
  osVersion: 'darwin 21.4.0',
  nodeVersion: 'v16.13.0',
  coreVersion: '1.0.1310',
  checksum: 'ZmNlNjQ1OGRiZDcwNzEwZjkzYmZkZTdmZDdhODhlMTQsMTY5MjIzMDQwMDAwMCww',
  config: {
    files: [
      { pattern: 'package.json', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: 'src/**/*.ts', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: 'src/**/*.spec.ts', ignore: true, trigger: true, load: true, instrument: true }
    ],
    tests: [ { pattern: 'src/**/*.spec.ts', ignore: false, trigger: true, load: true, test: true, order: 3 } ],
    env: { type: 'node', params: {}, runner: '/usr/local/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    workers: { restart: true, initial: 0, regular: 0, recycle: true },
    compilers: { '**/*.?(lit)coffee?(.md)': [Function (anonymous)] },
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    smartStart: [ { test: true, source: false, pattern: '**/*', startMode: 'open' }, { test: false, source: true, pattern: '**/*', startMode: 'edit' } ],
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: true,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: true,
    testFramework: { version: 'mocha@2.1.0', configurator: 'mocha@2.1.0', reporter: 'mocha@2.1.0', starter: 'mocha@2.1.0' },
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: undefined,
    symlinkNodeModules: undefined,
    configCode: 'module.exports = (wallaby) => ({\n' +
      '  files: [\n' +
      "    './package.json',\n" +
      "    './src/**/*.ts',\n" +
      "    '!./src/**/*.spec.ts',\n" +
      '  ],\n' +
      '  tests: [\n' +
      "    './src/**/*.spec.ts'\n" +
      '  ],\n' +
      '  env: {\n' +
      "    type: 'node',\n" +
      '  },\n' +
      '  workers: { restart: true },\n' +
      '  compilers: {\n' +
      "    './**/*.ts': wallaby.compilers.typeScript({\n" +
      "      module: 'commonjs',\n" +
      '    })\n' +
      '  },\n' +
      '})',
    testLocations: [ 'src/test/cli.spec.ts' ]
  },
  packageJSON: {
    dependencies: { enquirer: '^2.3.6', 'commons': '../commons', minimist: '^1.2.6', nanospinner: '^1.1.0' },
    devDependencies: {
      '@types/chai': '^4.3.1',
      '@types/minimist': '^1.2.2',
      '@types/mocha': '^9.1.1',
      '@types/node': '^18.0.3',
      '@types/sinon': '^10.0.12',
      chai: '^4.3.6',
      'fast-glob': '^3.2.11',
      memfs: '^3.4.7',
      mocha: '^10.0.0',
      nyc: '^15.1.0',
      rimraf: '^3.0.2',
      sinon: '^14.0.0',
      'ts-node': '^10.9.1',
      typescript: '^4.7.4'
    }
  },
  fs: { numberOfFiles: 3 },
  debug: [
    '2022-08-04T07:45:30.692Z project Wallaby Node version: v16.13.0\n',
    '2022-08-04T07:45:30.693Z project Wallaby config: <homeDir>/myproject/packages/cli/wallaby.js\n',
    '2022-08-04T07:45:30.724Z project File cache: <homeDir>/Library/Caches/JetBrains/IntelliJIdea2022.2/wallaby/projects/172edc2c934a3426\n',
    '2022-08-04T07:45:30.853Z uiService Listening port 51235\n',
    '2022-08-04T07:45:30.863Z workers Parallelism for initial run: 10, for regular run: 5\n',
    '2022-08-04T07:45:30.864Z workers Starting run worker instance #0\n',
    '2022-08-04T07:45:30.864Z workers Starting run worker instance #1\n',
    '2022-08-04T07:45:30.864Z workers Starting run worker instance #2\n',
    '2022-08-04T07:45:30.864Z workers Starting run worker instance #3\n',
    '2022-08-04T07:45:30.864Z workers Starting run worker instance #4\n',
    '2022-08-04T07:45:30.864Z workers Starting run worker instance #5\n',
    '2022-08-04T07:45:30.864Z workers Starting run worker instance #6\n',
    '2022-08-04T07:45:30.864Z workers Starting run worker instance #7\n',
    '2022-08-04T07:45:30.864Z workers Starting run worker instance #8\n',
    '2022-08-04T07:45:30.864Z workers Starting run worker instance #9\n',
    '2022-08-04T07:45:30.864Z workers Web server is listening at 60166\n',
    '2022-08-04T07:45:31.017Z project File cache requires some updates, waiting required files from IDE\n',
    '2022-08-04T07:45:31.300Z workers Started run worker instance (delayed) #1\n',
    '2022-08-04T07:45:31.300Z workers Started run worker instance (delayed) #0\n',
    '2022-08-04T07:45:31.305Z workers Started run worker instance (delayed) #2\n',
    '2022-08-04T07:45:31.357Z workers Started run worker instance (delayed) #4\n',
    '2022-08-04T07:45:31.360Z workers Started run worker instance (delayed) #3\n',
    '2022-08-04T07:45:31.364Z workers Started run worker instance (delayed) #5\n',
    '2022-08-04T07:45:31.431Z workers Started run worker instance (delayed) #6\n',
    '2022-08-04T07:45:31.444Z workers Started run worker instance (delayed) #7\n',
    '2022-08-04T07:45:31.454Z workers Started run worker instance (delayed) #8\n',
    '2022-08-04T07:45:31.483Z workers Started run worker instance (delayed) #9\n',
    '2022-08-04T07:45:31.670Z project Stopping process pool\n',
    '2022-08-04T07:45:31.675Z project Running postprocessor\n',
    '2022-08-04T07:45:31.678Z postprocessor New TypeScript language service is required\n',
    '2022-08-04T07:45:31.905Z project Requested to run all tests\n',
    '2022-08-04T07:45:31.909Z project Postprocessor execution finished\n',
    '2022-08-04T07:45:31.909Z project Test run started; run priority: 3\n',
    '2022-08-04T07:45:31.910Z project Running all tests\n',
    '2022-08-04T07:45:31.910Z workers Starting test run, priority: 3\n',
    '2022-08-04T07:45:31.911Z nodeRunner Starting sandbox [worker #0, session #udj5w]\n',
    '2022-08-04T07:45:31.911Z nodeRunner Preparing sandbox [worker #0, session #udj5w]\n',
    '2022-08-04T07:45:31.911Z nodeRunner Prepared sandbox [worker #0, session #udj5w]\n',
    '2022-08-04T07:45:31.911Z workers [worker #0, session #udj5w] Running tests in sandbox\n',
    '2022-08-04T07:45:31.918Z workers [udj5w] Loaded 0 test(s)\n',
    '2022-08-04T07:45:31.919Z workers [udj5w] Run 0 test(s), skipped 0 test(s)\n',
    '2022-08-04T07:45:31.920Z workers [udj5w] Sandbox is responsive, closing it\n',
    '2022-08-04T07:45:31.921Z workers Recyling run worker instance #0\n',
    '2022-08-04T07:45:31.921Z workers Starting run worker instance #0\n',
    '2022-08-04T07:45:31.921Z project Test run finished\n',
    '2022-08-04T07:45:31.922Z project Processed console.log entries\n',
    '2022-08-04T07:45:31.922Z project Processed loading sequences\n',
    '2022-08-04T07:45:31.922Z project Processed executed tests\n',
    '2022-08-04T07:45:31.922Z project Processed code coverage\n',
    '2022-08-04T07:45:31.933Z project Test run result processed and sent to IDE\n',
    '2022-08-04T07:45:32.035Z project Running postprocessor\n',
    '2022-08-04T07:45:32.207Z project Postprocessor execution finished\n',
    '2022-08-04T07:45:32.207Z project Test run started; run priority: 3\n',
    '2022-08-04T07:45:32.207Z project Running all tests\n',
    '2022-08-04T07:45:32.208Z workers Starting test run, priority: 3\n',
    '2022-08-04T07:45:32.208Z nodeRunner Starting sandbox [worker #0, session #ey9lo]\n',
    '2022-08-04T07:45:32.208Z nodeRunner Preparing sandbox [worker #0, session #ey9lo]\n',
    '2022-08-04T07:45:32.212Z workers Started run worker instance (delayed) #0\n',
    '2022-08-04T07:45:32.212Z nodeRunner Prepared sandbox [worker #0, session #ey9lo]\n',
    '2022-08-04T07:45:32.212Z workers [worker #0, session #ey9lo] Running tests in sandbox\n',
    "2022-08-04T07:45:32.386Z workers Sandbox (active) [ey9lo] error: TypeError: Cannot read properties of undefined (reading 'describe')\n" +
      '    at exports.describe (<homeDir>/myproject/node_modules/mocha/lib/mocha.js:111:26)\n' +
      '    at Object.<anonymous> (./src/test/cli.spec.js:63:41)\n' +
      '    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n' +
      '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n' +
      '    at Module.load (node:internal/modules/cjs/loader:981:32)\n' +
      '    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n' +
      '    at Module.require (node:internal/modules/cjs/loader:1005:19)\n' +
      '    at require (node:internal/modules/cjs/helpers:102:18)\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at WebSocket.emit (node:events:390:28)\n' +
      '    at afterWrite (node:internal/streams/writable:497:5)\n' +
      '    at onwrite (node:internal/streams/writable:477:7)\n' +
      '    at Zlib.cb (node:internal/streams/transform:201:7)\n' +
      '    at Zlib.processCallback (node:zlib:612:8)\n',
    '2022-08-04T07:45:32.488Z workers [ey9lo] Run 0 test(s), skipped 0 test(s)\n',
    '2022-08-04T07:45:32.489Z workers [ey9lo] Sandbox is responsive, closing it\n',
    '2022-08-04T07:45:32.489Z workers Recyling run worker instance #0\n',
    '2022-08-04T07:45:32.489Z workers Starting run worker instance #0\n',
    '2022-08-04T07:45:32.490Z project Test run finished\n',
    '2022-08-04T07:45:32.490Z project Processed console.log entries\n',
    '2022-08-04T07:45:32.490Z project Processed loading sequences\n',
    '2022-08-04T07:45:32.490Z project Processed executed tests\n',
    '2022-08-04T07:45:32.490Z project Processed code coverage\n',
    '2022-08-04T07:45:32.498Z project Test run result processed and sent to IDE\n',
    '2022-08-04T07:45:32.687Z workers Started run worker instance (delayed) #0\n'
  ]
}
```

**Comment by smcenlly** [comment]
Can you please provide us with a sample of a npm workspace with a single sample test configured the same way as you have with your project (same linking setup, packages, etc.) so that we can understand how your project is configured?

**Comment by lamartire** [comment]
Sure, https://github.com/lamartire/wallaby-npm-workspace-bug-example

**Comment by lamartire** [comment]
You need to run: `npm install --workspaces` in the project root before you start

**Comment by ArtemGovorov** [comment]
Thanks for providing the sample repo. In this case because Wallaby config file is located inside the package subfolder, Wallaby mocha integration can't find the mocha module in the package (because it's hoisted up to the root `node_modules`), and starts using Wallaby embedded version of mocha (with no support for imported `describe`). All you need to do to make it work is to specify the path to mocha location via the [`testFramework.path` setting](https://github.com/lamartire/wallaby-npm-workspace-bug-example/pull/1).

**Comment by lamartire** [comment]
It works! Thank you! :)
