### ISSUE TITLE
Vitest error

### ISSUE THREAD

**Issue by chlbri** [wallabyjs/public#3066]
Output of the console: 

```
​[Info]​ 2022-09-02T11:43:46.947Z config Attempting automatic configuration for angular
​[Info]​ 2022-09-02T11:43:46.948Z angular/cli config Detecting Angular CLI.
​[Info]​ 2022-09-02T11:43:46.950Z angular/cli config Angular CLI not found.
​[Info]​ 2022-09-02T11:43:46.950Z config Finished attempting automatic configuration for angular (3ms)
​[Info]​ 2022-09-02T11:43:46.951Z config Attempting automatic configuration for jest
​[Info]​ 2022-09-02T11:43:46.952Z jest/config Detecting Jest.
​[Info]​ Started Wallaby.js Core v1.0.1326
​[Info]​ 2022-09-02T11:43:46.954Z jest/config Error: Module jest-cli is not found in '/workspace/core'.
​[Info]​     at Object.<anonymous> (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:31:17499)
​[Info]​     at r (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:31:746)
​[Info]​     at Object.next (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:31:41)
​[Info]​     at /home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:30:31992
​[Info]​     at new Promise (<anonymous>)
​[Info]​     at n (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:30:31786)
​[Info]​     at Object.loadJest (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:31:15097)
​[Info]​     at /home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:17909
​[Info]​     at r (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:22642)
​[Info]​     at Object.next (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:21937)
​[Info]​     at /home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:21846
​[Info]​     at new Promise (<anonymous>)
​[Info]​     at s (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:21640)
​[Info]​     at r (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:17597)
​[Info]​     at Object.<anonymous> (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:21317)
​[Info]​     at r (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:22642)
​[Info]​     at Object.next (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:21937)
​[Info]​     at /home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:21846
​[Info]​     at new Promise (<anonymous>)
​[Info]​     at s (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:21640)
​[Info]​     at Object.n [as configure] (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:21198)
​[Info]​     at Config.<anonymous> (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:15:20840)
​[Info]​     at r (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:15:12061)
​[Info]​     at Object.next (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:15:11356)
​[Info]​     at o (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:15:11105)
​[Info]​ 2022-09-02T11:43:46.954Z config Finished attempting automatic configuration for jest (3ms)
​[Info]​ 2022-09-02T11:43:46.954Z config Attempting automatic configuration for vitest
​[Info]​ 2022-09-02T11:43:46.955Z vitest/config Detecting Vitest.
​[Info]​ 2022-09-02T11:43:46.957Z vitest/config Detected Vitest.
​[Info]​ 2022-09-02T11:43:47.237Z vitest/config Error: (node:28960) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
​[Info]​ (Use `node --trace-warnings ...` to show where the warning was created)
​[Info]​ startVitest is not a function
​[Info]​     at Object.<anonymous> (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:24955)
​[Info]​     at r (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:27402)
​[Info]​     at Object.next (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:26697)
​[Info]​     at /home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:26606
​[Info]​     at new Promise (<anonymous>)
​[Info]​     at n (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:26400)
​[Info]​     at Object.r [as configure] (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:19:23933)
​[Info]​     at Config.<anonymous> (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:15:20840)
​[Info]​     at r (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:15:12061)
​[Info]​     at Object.next (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:15:11356)
​[Info]​     at o (/home/gitpod/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/wallaby13dc36/server.js:15:11105)
​[Info]​ 2022-09-02T11:43:47.237Z config Finished attempting automatic configuration for vitest (283ms)
​​[Error] Failed to load configuration file: Automatic Jest configuration error: Module jest-cli is not found in '.'.​​
​​[Error] We've also tried to automatically configure Wallaby.js for other frameworks​​
​​[Error] Automatic Vitest configuration error: (node:28960) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time​​
​​[Error] (Use `node --trace-warnings ...` to show where the warning was created)​​
​​[Error] startVitest is not a function​​
​​[Error] Please refer to our docs: https://wallabyjs.com/docs/config/overview.html ​​
​[Info]​ 2022-09-02T11:43:47.243Z extended-core Setting preferences
​[Info]​ 2022-09-02T11:51:08.813Z extended-core Setting preferences
​[Info]​ 2022-09-02T11:51:11.969Z extended-core Setting preferences
```

**Comment by smcenlly** [comment]
Could you please update to the latest version of Wallaby, `v1.0.1327`. We've added some additional diagnostics to help us why it's not working for you.

After updating, could you please provide us with an updated diagnostics report / console output? You should also now receive a message in your `Wallaby Test` console:

```
[Error] Error extracting vitest configuration 
[Error] Please contact Wallaby support and provide the contents of this file './filename.mjs' 
```

Can you also please provide the contents of the filename referenced in the error message.

**Comment by chlbri** [comment]
Ok i will check

**Comment by chlbri** [comment]
Yes everything work fine. I used with gitpod, I think it’s because of that. On local it identify the vitest configuration

**Comment by chlbri** [comment]
But it still need vite dependency despite the fact that vitest doesn’t need vite dependency to be installed side by side.

**Comment by smcenlly** [comment]
Glad it is working for you now. We tried a project with only `vitest` installed (and not `vite`) and it was working for us. It may be related to something special that gitpod is doing for you?

If you're able to provide us with a sample repo that has the same problem, we'd appreciate it so that we can see if we can fix this within Wallaby rather than asking people to install `vite`.

Since it's now working for you, I'll resolve this issue.
