### ISSUE TITLE
Unexpected Token 'export' Error: Auto Configured w/ create-react-app

### ISSUE THREAD

**Issue by JosefSaltz** [wallabyjs/public#3081]
### Issue description or question
I'm receiving an error from jest encountering an unexpected token of 'export' in my create-react-app frontend application. I am using the automatic configuration option. I looked at some of the previous issues that might be relevant but they are from several years back and from the current Docs it seems this should run fine out of the box?
### Wallaby diagnostics report
```
{
  editorVersion: '1.71.2',
  pluginVersion: '1.0.347',
  editorType: 'VSCode',
  osVersion: 'linux 4.19.104-microsoft-standard',
  nodeVersion: 'v16.13.2',
  coreVersion: '1.0.1331',
  checksum: 'MDZhZjAzOTE4MDNkNzhmYzA5ZmE1NjBmNTA3ZmY4NGMsMTY5NTE2ODAwMDAwMCww',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/tmp/jest_rs',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/projects/work/jdt/sms-chat/frontend',
              dependencyExtractor: undefined,
              detectLeaks: undefined,
              detectOpenHandles: undefined,
              displayName: undefined,
              errorOnDeprecated: false,
              extraGlobals: [],
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, throwOnModuleCollision: false },
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [
                'web.js',  'js',
                'web.ts',  'ts',
                'web.tsx', 'tsx',
                'json',    'web.jsx',
                'jsx',     'node'
              ],
              moduleLoader: undefined,
              moduleNameMapper: [ [ '^react-native$', 'react-native-web' ], [ '^.+\\.module\\.(css|sass|scss)$', 'identity-obj-proxy' ] ],
              modulePathIgnorePatterns: [],
              modulePaths: [ '<homeDir>/projects/work/jdt/sms-chat/frontend/src' ],
              name: '1095c4bbcb5fcec751604bb8b2319ffa',
              prettierPath: 'prettier',
              resetMocks: true,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/projects/work/jdt/sms-chat/frontend',
              roots: [ '<homeDir>/projects/work/jdt/sms-chat/frontend/src' ],
              runner: 'jest-runner',
              setupFiles: [ '<homeDir>/projects/work/jdt/sms-chat/frontend/node_modules/react-app-polyfill/jsdom.js' ],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/projects/work/jdt/sms-chat/frontend/node_modules/jest-environment-jsdom/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [
                '<homeDir>/projects/work/jdt/sms-chat/frontend/src/**/__tests__/**/*.{js,jsx,ts,tsx}',
                '<homeDir>/projects/work/jdt/sms-chat/frontend/src/**/*.{spec,test}.{js,jsx,ts,tsx}'
              ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<homeDir>/projects/work/jdt/sms-chat/frontend/node_modules/jest-circus/runner.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [
                [ '^.+\\.(js|jsx|mjs|cjs|ts|tsx)$', '<homeDir>/projects/work/jdt/sms-chat/frontend/node_modules/react-scripts/config/jest/babelTransform.js', {} ],
                [ '^.+\\.css$', '<homeDir>/projects/work/jdt/sms-chat/frontend/node_modules/react-scripts/config/jest/cssTransform.js', {} ],
                [ '^(?!.*\\.(js|jsx|mjs|cjs|ts|tsx|css|json)$)', '<homeDir>/projects/work/jdt/sms-chat/frontend/node_modules/react-scripts/config/jest/fileTransform.js', {} ]
              ],
              transformIgnorePatterns: [ '[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs|cjs|ts|tsx)$', '^.+\\.module\\.(css|sass|scss)$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: [ 'src/**/*.{js,jsx,ts,tsx}', '!src/**/*.d.ts' ],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<homeDir>/projects/work/jdt/sms-chat/frontend/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: undefined,
            detectOpenHandles: undefined,
            enabledTestsMap: undefined,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: undefined,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 11,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: undefined,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/projects/work/jdt/sms-chat/frontend',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/projects/work/jdt/sms-chat/frontend/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: [
              { config: {}, path: '<homeDir>/projects/work/jdt/sms-chat/frontend/node_modules/jest-watch-typeahead/filename.js' },
              { config: {}, path: '<homeDir>/projects/work/jdt/sms-chat/frontend/node_modules/jest-watch-typeahead/testname.js' }
            ],
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [ 'src' ],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/tmp/jest_rs', '\\./coverage' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/tmp/jest_rs', '\\./coverage' ],
            testMatch: [ 'src/**/__tests__/**/*.{js,jsx,ts,tsx}', 'src/**/*.{spec,test}.{js,jsx,ts,tsx}' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [ 'src/**/*.{js,jsx,ts,tsx}', '!src/**/*.d.ts' ],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    dot: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, file: true, test: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        file: true,
        test: true
      },
      { pattern: '/tmp/jest_rs', regexp: /\/tmp\/jest_rs/, ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**', ignore: false, trigger: true, load: true, order: 2 },
      { pattern: 'src/**/__tests__/**/*.{js,jsx,ts,tsx}', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/**/*.{spec,test}.{js,jsx,ts,tsx}', ignore: true, trigger: true, load: true, file: true }
    ],
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true, file: false },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true,
        file: false
      },
      { pattern: '/tmp/jest_rs', regexp: /\/tmp\/jest_rs/, ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'src/**/__tests__/**/*.{js,jsx,ts,tsx}', ignore: false, trigger: true, load: true, test: true, order: 3 },
      { pattern: 'src/**/*.{spec,test}.{js,jsx,ts,tsx}', ignore: false, trigger: true, load: true, test: true, order: 4 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '<homeDir>/.nvm/versions/node/v16.13.2/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#-1577851950'
  },
  packageJSON: {
    dependencies: {
      '@fortawesome/fontawesome-svg-core': '^1.2.36',
      '@fortawesome/free-solid-svg-icons': '^6.1.1',
      '@fortawesome/react-fontawesome': '^0.1.16',
      '@marker.io/browser': '^0.12.0',
      '@testing-library/jest-dom': '^5.15.0',
      '@testing-library/react': '^12.1.5',
      '@testing-library/user-event': '^12.1.10',
      'awesome-phonenumber': '^2.64.0',
      bootstrap: '5.1.3',
      bufferutil: '^4.0.5',
      'caniuse-lite': '^1.0.30001280',
      dotenv: '^10.0.0',
      firebase: '^8.9.1',
      firebaseui: '^5.0.0',
      'google-libphonenumber': '^3.2.25',
      'libphonenumber-js': '^1.9.52',
      react: '^17.0.2',
      'react-bootstrap': '^2.0.2',
      'react-dom': '^17.0.2',
      'react-router-bootstrap': '^0.25.0',
      'react-router-dom': '^5.2.0',
      'react-scripts': '4.0.3',
      'react-textarea-autosize': '^8.3.3',
      'react-transition-group': '^4.4.2',
      rfs: '^9.0.6',
      seedrandom: '^3.0.5',
      'serialize-error': '^11.0.0',
      'socket.io': '^4.3.2',
      'socket.io-client': '^4.5.0',
      'utf-8-validate': '^5.0.7',
      uuid: '^8.3.2',
      'web-vitals': '^1.0.1',
      websocket: '^1.0.34'
    },
    devDependencies: { concurrently: '^6.4.0', 'react-test-renderer': '^17.0.2', sass: '^1.43.4' }
  },
  fs: { numberOfFiles: 223 },
  debug: [
    '2022-09-23T09:24:28.664Z config Attempting automatic configuration for angular\n',
    '2022-09-23T09:24:28.668Z angular/cli config Angular CLI not found.\n',
    '2022-09-23T09:24:28.668Z config Finished attempting automatic configuration for angular (4ms)\n',
    '2022-09-23T09:24:28.668Z config Attempting automatic configuration for jest\n',
    '2022-09-23T09:24:28.733Z jest/config Detected Jest.\n',
    '2022-09-23T09:24:28.733Z jest/config Configured Jest.\n',
    '2022-09-23T09:24:28.733Z config Finished attempting automatic configuration for jest (65ms)\n',
    '2022-09-23T09:24:28.735Z project Wallaby Node version: v16.13.2\n',
    '2022-09-23T09:24:28.735Z project Wallaby config: <homeDir>/projects/work/jdt/sms-chat/frontend/auto.detect\n',
    '2022-09-23T09:24:28.751Z fs File system starting\n',
    '2022-09-23T09:24:28.907Z fs File system scan completed\n',
    '2022-09-23T09:24:28.931Z project File cache: <homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.347/projects/c1c1b631a0c2146f\n',
    '2022-09-23T09:24:28.979Z uiService Listening port 51235\n',
    '2022-09-23T09:24:29.007Z workers Parallelism for initial run: 10, for regular run: 5\n',
    '2022-09-23T09:24:29.007Z workers Starting run worker instance #0\n',
    '2022-09-23T09:24:29.007Z workers Starting run worker instance #1\n',
    '2022-09-23T09:24:29.007Z workers Starting run worker instance #2\n',
    '2022-09-23T09:24:29.007Z workers Starting run worker instance #3\n',
    '2022-09-23T09:24:29.007Z workers Starting run worker instance #4\n',
    '2022-09-23T09:24:29.007Z workers Starting run worker instance #5\n',
    '2022-09-23T09:24:29.007Z workers Starting run worker instance #6\n',
    '2022-09-23T09:24:29.007Z workers Starting run worker instance #7\n',
    '2022-09-23T09:24:29.007Z workers Starting run worker instance #8\n',
    '2022-09-23T09:24:29.007Z workers Starting run worker instance #9\n',
    '2022-09-23T09:24:29.008Z workers Web server is listening at 46165\n',
    '2022-09-23T09:24:29.060Z project Stopping process pool\n',
    '2022-09-23T09:24:29.060Z project File cache is up-to-date, starting full test run\n',
    '2022-09-23T09:24:29.066Z project Test run started; run priority: 3\n',
    '2022-09-23T09:24:29.069Z project Running all tests\n',
    '2022-09-23T09:24:29.082Z workers Starting test run, priority: 3\n',
    '2022-09-23T09:24:29.082Z workers Distributing tests between 10 workers\n',
    '2022-09-23T09:24:29.085Z workers Running tests in parallel\n',
    '2022-09-23T09:24:29.085Z nodeRunner Starting sandbox [worker #0, session #mf1qr]\n',
    '2022-09-23T09:24:29.086Z nodeRunner Starting sandbox [worker #1, session #ot8q7]\n',
    '2022-09-23T09:24:29.086Z nodeRunner Starting sandbox [worker #2, session #hsyb5]\n',
    '2022-09-23T09:24:29.086Z nodeRunner Starting sandbox [worker #3, session #1yi7e]\n',
    '2022-09-23T09:24:29.086Z nodeRunner Starting sandbox [worker #4, session #de0zf]\n',
    '2022-09-23T09:24:29.086Z nodeRunner Starting sandbox [worker #5, session #o2rek]\n',
    '2022-09-23T09:24:29.086Z nodeRunner Preparing sandbox [worker #0, session #mf1qr]\n',
    '2022-09-23T09:24:29.086Z nodeRunner Preparing sandbox [worker #1, session #ot8q7]\n',
    '2022-09-23T09:24:29.086Z nodeRunner Preparing sandbox [worker #2, session #hsyb5]\n',
    '2022-09-23T09:24:29.087Z nodeRunner Preparing sandbox [worker #3, session #1yi7e]\n',
    '2022-09-23T09:24:29.087Z nodeRunner Preparing sandbox [worker #4, session #de0zf]\n',
    '2022-09-23T09:24:29.087Z nodeRunner Preparing sandbox [worker #5, session #o2rek]\n',
    '2022-09-23T09:24:29.204Z workers Started run worker instance (delayed) #1\n',
    '2022-09-23T09:24:29.204Z nodeRunner Prepared sandbox [worker #1, session #ot8q7]\n',
    '2022-09-23T09:24:29.204Z workers [worker #1, session #ot8q7] Running tests in sandbox\n',
    '2022-09-23T09:24:29.208Z workers Started run worker instance (delayed) #0\n',
    '2022-09-23T09:24:29.208Z nodeRunner Prepared sandbox [worker #0, session #mf1qr]\n',
    '2022-09-23T09:24:29.208Z workers [worker #0, session #mf1qr] Running tests in sandbox\n',
    '2022-09-23T09:24:29.213Z workers Started run worker instance (delayed) #3\n',
    '2022-09-23T09:24:29.213Z nodeRunner Prepared sandbox [worker #3, session #1yi7e]\n',
    '2022-09-23T09:24:29.213Z workers [worker #3, session #1yi7e] Running tests in sandbox\n',
    '2022-09-23T09:24:29.215Z workers Started run worker instance (delayed) #2\n',
    '2022-09-23T09:24:29.216Z nodeRunner Prepared sandbox [worker #2, session #hsyb5]\n',
    '2022-09-23T09:24:29.216Z workers [worker #2, session #hsyb5] Running tests in sandbox\n',
    '2022-09-23T09:24:29.229Z workers Started run worker instance (delayed) #4\n',
    '2022-09-23T09:24:29.229Z nodeRunner Prepared sandbox [worker #4, session #de0zf]\n',
    '2022-09-23T09:24:29.229Z workers [worker #4, session #de0zf] Running tests in sandbox\n',
    '2022-09-23T09:24:29.231Z workers Started run worker instance (delayed) #5\n',
    '2022-09-23T09:24:29.231Z nodeRunner Prepared sandbox [worker #5, session #o2rek]\n',
    '2022-09-23T09:24:29.232Z workers [worker #5, session #o2rek] Running tests in sandbox\n',
    '2022-09-23T09:24:29.238Z workers Started run worker instance (delayed) #6\n',
    '2022-09-23T09:24:29.243Z workers Started run worker instance (delayed) #8\n',
    '2022-09-23T09:24:29.245Z workers Started run worker instance (delayed) #7\n',
    '2022-09-23T09:24:29.255Z workers Started run worker instance (delayed) #9\n',
    '2022-09-23T09:24:30.471Z workers Scheduling Jest Test Run (ot8q7): 2022-09-23T09:24:29.567Z\n',
    '2022-09-23T09:24:30.472Z workers [ot8q7] Loaded unknown number of test(s)\n',
    '2022-09-23T09:24:30.472Z workers [ot8q7] Test executed: It contains the MessageContainer component\n',
    '2022-09-23T09:24:30.519Z workers Scheduling Jest Test Run (1yi7e): 2022-09-23T09:24:29.609Z\n',
    '2022-09-23T09:24:30.520Z workers [1yi7e] Loaded unknown number of test(s)\n',
    '2022-09-23T09:24:30.520Z workers [1yi7e] Test executed: It renders the InputForm component\n',
    '2022-09-23T09:24:30.524Z workers Scheduling Jest Test Run (hsyb5): 2022-09-23T09:24:29.608Z\n',
    '2022-09-23T09:24:30.526Z workers [hsyb5] Loaded unknown number of test(s)\n',
    '2022-09-23T09:24:30.527Z workers [hsyb5] Test executed: It renders an image\n',
    '2022-09-23T09:24:30.551Z workers Scheduling Jest Test Run (o2rek): 2022-09-23T09:24:29.643Z\n',
    '2022-09-23T09:24:30.551Z workers Scheduling Jest Test Run (de0zf): 2022-09-23T09:24:29.649Z\n',
    '2022-09-23T09:24:30.558Z workers [o2rek] Loaded unknown number of test(s)\n',
    '2022-09-23T09:24:30.558Z workers [de0zf] Loaded unknown number of test(s)\n',
    '2022-09-23T09:24:30.567Z workers [o2rek] Test executed: It Renders the TextMessage bubble\n',
    '2022-09-23T09:24:30.568Z workers [de0zf] Test executed: It contains the InputForm component\n',
    '2022-09-23T09:24:30.596Z workers [ot8q7] Run 1 test(s), skipped 0 test(s)\n',
    '2022-09-23T09:24:30.597Z workers Jest Test Run Complete (ot8q7): 2022-09-23T09:24:30.470Z\n',
    '2022-09-23T09:24:30.599Z workers [ot8q7] Sandbox is responsive, closing it\n',
    '2022-09-23T09:24:30.658Z workers [1yi7e] Run 1 test(s), skipped 0 test(s)\n',
    '2022-09-23T09:24:30.659Z workers Jest Test Run Complete (1yi7e): 2022-09-23T09:24:30.518Z\n',
    '2022-09-23T09:24:30.661Z workers [1yi7e] Sandbox is responsive, closing it\n',
    '2022-09-23T09:24:30.662Z workers [hsyb5] Run 1 test(s), skipped 0 test(s)\n',
    '2022-09-23T09:24:30.663Z workers Jest Test Run Complete (hsyb5): 2022-09-23T09:24:30.521Z\n',
    '2022-09-23T09:24:30.665Z workers [hsyb5] Sandbox is responsive, closing it\n',
    '2022-09-23T09:24:30.668Z workers [o2rek] Run 1 test(s), skipped 0 test(s)\n',
    '2022-09-23T09:24:30.668Z workers [de0zf] Run 1 test(s), skipped 0 test(s)\n',
    '2022-09-23T09:24:30.668Z workers Jest Test Run Complete (o2rek): 2022-09-23T09:24:30.544Z\n',
    '2022-09-23T09:24:30.668Z workers Jest Test Run Complete (de0zf): 2022-09-23T09:24:30.544Z\n',
    '2022-09-23T09:24:30.669Z workers [o2rek] Sandbox is responsive, closing it\n',
    '2022-09-23T09:24:30.669Z workers [de0zf] Sandbox is responsive, closing it\n',
    '2022-09-23T09:24:31.906Z workers Scheduling Jest Test Run (mf1qr): 2022-09-23T09:24:29.572Z\n',
    '2022-09-23T09:24:31.908Z workers Sandbox (active) [mf1qr] error: Jest encountered an unexpected token\n' +
      '\n' +
      "This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.\n" +
      '\n' +
      'By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".\n' +
      '\n' +
      "Here's what you can do:\n" +
      ' • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.\n' +
      ' • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.\n' +
      ' • If you need a custom transformation specify a "transform" option in your config.\n' +
      ' • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.\n' +
      '\n' +
      "You'll find more details and examples of these config options in the docs:\n" +
      'https://jestjs.io/docs/en/configuration.html\n' +
      '\n' +
      'Details:\n' +
      '\n' +
      './node_modules/@marker.io/browser/src/index.js:5\n' +
      'export default {\n' +
      '^^^^^^\n' +
      '\n' +
      "SyntaxError: Unexpected token 'export'\n" +
      '    at new Script (node:vm:100:7)\n' +
      '    at Runtime.createScriptFromCode (./node_modules/jest-runtime/build/index.js:1350:14)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1245:25)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:898:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:746:10)\n' +
      '    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:919:21)\n' +
      '    at Object.<anonymous> (./src/App.js:10:59)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1299:24)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:898:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:746:10)\n' +
      '    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:919:21)\n' +
      '    at Object.<anonymous> (./src/test/App.test.js:6:56)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1299:24)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:898:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:746:10)\n' +
      '    at jestAdapter (./node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:106:13)\n' +
      '    at runTestInternal (./node_modules/jest-runner/build/runTest.js:380:16)\n' +
      '    at runTest (./node_modules/jest-runner/build/runTest.js:472:34)\n',
    '2022-09-23T09:24:31.948Z workers [mf1qr] Run 0 test(s), skipped 0 test(s)\n',
    '2022-09-23T09:24:31.948Z workers Jest Test Run Complete (mf1qr): 2022-09-23T09:24:31.905Z\n',
    '2022-09-23T09:24:31.949Z workers [mf1qr] Sandbox is responsive, closing it\n',
    '2022-09-23T09:24:31.950Z workers Merging parallel test run results\n',
    '2022-09-23T09:24:31.958Z project Test run finished\n',
    '2022-09-23T09:24:31.958Z project Processed console.log entries\n',
    '2022-09-23T09:24:31.958Z project Processed loading sequences\n',
    '2022-09-23T09:24:31.958Z project Processed executed tests\n',
    '2022-09-23T09:24:31.976Z project Processed code coverage\n',
    '2022-09-23T09:24:32.075Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
Yes, it should work without any additional config. From the error message, it looks like `@marker.io` node module that you are using is an ES module, so [Jest needs to be configured to transpile it](https://stackoverflow.com/questions/60714101/how-to-setup-jest-with-node-modules-that-use-es6) (by default it doesn't transpile node modules). Having said that, we expect the issue not be specific to Wallaby and the same error should show up if you run Jest CLI (via `npm/yarn test` command in your project). Can you please confirm whether or now running Jest from CLI works for you?

**Comment by JosefSaltz** [comment]
I can confirm that I receive the same error when running jest from CLI. However, I'm unsure where to inject the Jest ES module support flags in my current package.json given it's using react-scripts.

#### Current package.json
```js
{
  "name": "smschat-frontend",
  "Author": "Derek M. Robertson, Josef P. Saltz",
  "version": "0.7.0",
  "homepage": "https://smscola.vippbx.com",
  "private": true,
  "proxy": "http://localhost:8015",
  "type": "module",
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.36",
    "@fortawesome/free-solid-svg-icons": "^6.1.1",
    "@fortawesome/react-fontawesome": "^0.1.16",
    "@marker.io/browser": "^0.12.0",
    "@testing-library/jest-dom": "^5.15.0",
    "@testing-library/react": "^12.1.5",
    "@testing-library/user-event": "^12.1.10",
    "awesome-phonenumber": "^2.64.0",
    "bootstrap": "5.1.3",
    "bufferutil": "^4.0.5",
    "caniuse-lite": "^1.0.30001280",
    "dotenv": "^10.0.0",
    "firebase": "^8.9.1",
    "firebaseui": "^5.0.0",
    "google-libphonenumber": "^3.2.25",
    "libphonenumber-js": "^1.9.52",
    "react": "^17.0.2",
    "react-bootstrap": "^2.0.2",
    "react-dom": "^17.0.2",
    "react-router-bootstrap": "^0.25.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "react-textarea-autosize": "^8.3.3",
    "react-transition-group": "^4.4.2",
    "rfs": "^9.0.6",
    "seedrandom": "^3.0.5",
    "serialize-error": "^11.0.0",
    "socket.io": "^4.3.2",
    "socket.io-client": "^4.5.0",
    "utf-8-validate": "^5.0.7",
    "uuid": "^8.3.2",
    "web-vitals": "^1.0.1",
    "websocket": "^1.0.34"
  },
  "scripts": {
    "start": "react-scripts start",
    "fireup": "firebase emulators:start --import=./emulator-data --export-on-exit=./emulator-data/",
    "allsystemsgo": "concurrently 'yarn start' 'yarn fireup' ",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "concurrently": "^6.4.0",
    "react-test-renderer": "^17.0.2",
    "sass": "^1.43.4"
  },
  "jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!(@ui5|lit-html)).*\\.js$"
    ]
  }
}
```

**Comment by JosefSaltz** [comment]
I also tried setting `"test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!ui-core)/\" --env=jsdom"` and that did not work either.

**Comment by smcenlly** [comment]
Wallaby's integration with `create-react-app` uses `react-scripts test` without any parameters (Wallaby does not read or process your `package.json` `scripts.test` setting for additional parameters.

In your case, there are a few options available to you:

1. Override the automatic configuration files/tests to change the ignore patterns. See [our docs](https://wallabyjs.com/docs/config/files.html#overriding-automatic-configuration) for more information.
2. Use [`react-app-rewired`](https://www.npmjs.com/package/react-app-rewired) to change your jest configuration.
3. Eject your app from using `react-scripts` and change the transform ignore patterns in the ejected configuration.

**Comment by smcenlly** [comment]
Previous commented updated, removed first option. Please check the issue for latest advice.

**Comment by ArtemGovorov** [comment]
Looks like you already have the required Jest setting override in your `package.json`:

```
  "jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!(@ui5|lit-html)).*\\.js$"
    ]
  }
```

In order to get rid of the error and make both Jest CLI and Wallaby work you just need to adjust it to include the problematic package (`@marker.io`):

```
  "jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!(@marker\\.io|@ui5|lit-html)).*\\.js$"
    ]
  }
```

(please check if I got the name/regexp for the module name right).

**Comment by JosefSaltz** [comment]
Think that did it, I'm having a promise error with `ReactDOM.unmountComponentAtNode()` but I believe that is nothing to do with Wallaby so I'm going to go ahead and close this. Thank you!

**Comment by JosefSaltz** [comment]
Actually one last question, should Wallaby be running on my imports? This isn't something it does in my backend tests.

![image](https://user-images.githubusercontent.com/11865958/192136467-bbb6acc5-75e1-48b3-8050-925d62312a5d.png)

**Comment by smcenlly** [comment]
This is expected in this case. 

With `create-react-app`, babel changes your `import` statements to `require` statements. Wallaby can capture when `require` statements are executed but cannot do the same when native `esm` `import` statements are used.

**Comment by JosefSaltz** [comment]
Thanks for confirming!
