### ISSUE TITLE
Wallaby runs out of memory

### ISSUE THREAD

**Issue by skanev** [wallabyjs/public#3099]
### Issue description or question

So, wallaby runs out of memory for me.

I've narrowed it down to the fact that I have a few huge JSONs in the repo. They are not really in the repo, they are `.gitignore`-d, but I still need them in my project root for various reasons. They are 3.7GB in total. If I remove them, wallaby works just fine. If I add them, however, it spells trouble.

If there is a way I can tell wallaby to ignore them, that would be just perfect and make me a happy customer ;) . Now I have to keep moving them in/out depending on whether I'm running tests or not, which is annoying.

### Wallaby diagnostics report

There is no diagnostic report to paste here, as wallaby gives me an error when I request it, but here's what I get in the console, for posterity:

```
‍​[Info]​ Wallaby App (realtime reports) is available at: http://localhost:51245
​[Info]​ Started Wallaby.js Core v1.0.1342
​​[Error] No files with tests found, check your tests list patterns.​​
​[Info]​ Can't determine tests to run for the change.
​[Info]​ To run all tests when can not determine tests to run, use `runAllTestsWhenNoAffectedTests: true` configuration option.
​[Info]​ console.error: ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
​[Info]​ transform: {
​[Info]​     <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
​[Info]​ },
​[Info]​ console.log: Jest: PASS src/utilities/app.test.ts
​[Info]​ console.log: Jest:   ● Console
​[Info]​     console.log
​[Info]​       Received interrupt, exiting...
​[Info]​       at console.t.<computed> (../../../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby4f0f4a/runners/node/jest@24.8.0/initializer.js:14:21364)
​[Info]​     console.log
​[Info]​       Received interrupt, exiting...
​[Info]​       at console.t.<computed> (../../../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby4f0f4a/runners/node/jest@24.8.0/initializer.js:14:21364)
​[Info]​ console.error: ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
​[Info]​ transform: {
​[Info]​     <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
​[Info]​ },
​[Info]​ console.error: ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
​[Info]​ transform: {
​[Info]​     <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
​[Info]​ },
​[Info]​ console.error: ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
​[Info]​ transform: {
​[Info]​     <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
​[Info]​ },
​[Info]​ console.error: ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
​[Info]​ transform: {
​[Info]​     <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
​[Info]​ },
​[Info]​ console.error: ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
​[Info]​ transform: {
​[Info]​     <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
​[Info]​ },
​[Info]​ console.error: ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
​[Info]​ transform: {
​[Info]​     <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
​[Info]​ },
​[Info]​ console.log: Jest: PASS src/utilities/data.test.ts
​[Info]​ console.log: Jest: PASS src/utilities/date.test.ts
​[Info]​ console.log: Jest: PASS src/utilities/stream.test.ts
​[Info]​ console.log: Jest: PASS src/tests/insights.test.ts
​[Info]​ console.log: Jest: PASS src/utilities/deep-links.test.ts
​[Info]​ console.log: Jest: PASS src/utilities/sqs.test.ts
​[Info]​ console.error: ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
​[Info]​ transform: {
​[Info]​     <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
​[Info]​ },
​[Info]​ console.error: ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
​[Info]​ transform: {
​[Info]​     <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
​[Info]​ },
​​[Error] <--- Last few GCs --->​​
​​[Error] [45478:0x128040000]     5910 ms: Mark-sweep 4013.4 (4050.9) -> 4012.0 (4050.4) MB, 8.6 / 0.0 ms  (average mu = 0.978, current mu = 0.976) allocation failure; scavenge might not succeed​​
​​[Error] [45478:0x128040000]     6311 ms: Mark-sweep 4522.6 (4559.1) -> 4520.8 (4558.6) MB, 12.3 / 0.0 ms  (average mu = 0.974, current mu = 0.969) allocation failure; scavenge might not succeed​​
​​[Error] <--- JS stacktrace --->​​
​​[Error] FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory​​
​​[Error]  1: 0x1047de200 node::Abort() [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error]  2: 0x1047de3f0 node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error]  3: 0x104924880 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error]  4: 0x104acf5e8 v8::internal::EmbedderStackStateScope::EmbedderStackStateScope(v8::internal::Heap*, v8::internal::EmbedderStackStateScope::Origin, cppgc::EmbedderStackState) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error]  5: 0x104ace0cc v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error]  6: 0x104ac2374 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error]  7: 0x104ac2ba4 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error]  8: 0x104aa82bc v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error]  9: 0x104aa1e44 v8::internal::MaybeHandle<v8::internal::SeqOneByteString> v8::internal::FactoryBase<v8::internal::Factory>::NewRawStringWithMap<v8::internal::SeqOneByteString>(int, v8::internal::Map, v8::internal::AllocationType) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 10: 0x104aaa878 v8::internal::Factory::NewStringFromUtf8(v8::base::Vector<char const> const&, v8::internal::AllocationType) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 11: 0x104946a88 v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 12: 0x10488dfc0 node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 13: 0x1047bdf44 void node::Buffer::(anonymous namespace)::StringSlice<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 14: 0x1049951a0 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 15: 0x104994c9c v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 16: 0x1049944c8 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 17: 0x10518518c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 18: 0x109a2a9e8 ​​
​​[Error] 19: 0x109b48948 ​​
​​[Error] 20: 0x1051d06f8 Builtins_PromiseFulfillReactionJob [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 21: 0x105133c4c Builtins_RunMicrotasks [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 22: 0x10510e3a4 Builtins_JSRunMicrotasksEntry [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 23: 0x104a50e10 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 24: 0x104a51300 v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 25: 0x104a514dc v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 26: 0x104a77bac v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 27: 0x104a78444 v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 28: 0x1049951a0 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 29: 0x104994c9c v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 30: 0x1049944c8 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 31: 0x10518518c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 32: 0x109ad4048 ​​
​​[Error] 33: 0x10510e4d0 Builtins_JSEntryTrampoline [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 34: 0x10510e164 Builtins_JSEntry [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 35: 0x104a50e40 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 36: 0x104a50374 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 37: 0x1049408a8 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 38: 0x104728d00 node::InternalCallbackScope::Close() [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 39: 0x104728fc8 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 40: 0x10473d8ec node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 41: 0x1047e2b34 node::fs::FSReqCallback::Resolve(v8::Local<v8::Value>) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 42: 0x1047e30ec node::fs::AfterNoArgs(uv_fs_s*) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 43: 0x1047da7b0 node::MakeLibuvRequestCallback<uv_fs_s, void (*)(uv_fs_s*)>::Wrapper(uv_fs_s*) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 44: 0x1050eccbc uv__work_done [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 45: 0x1050f0458 uv__async_io [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 46: 0x1051021a4 uv__io_poll [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 47: 0x1050f08e8 uv_run [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 48: 0x1047296d4 node::SpinEventLoop(node::Environment*) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 49: 0x104819128 node::NodeMainInstance::Run() [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 50: 0x1047acec8 node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResult const*) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 51: 0x1047ad190 node::Start(int, char**) [/Users/aquarius/.volta/tools/image/node/18.12.0/bin/node]​​
​​[Error] 52: 0x1098d908c ​​
```

**Comment by smcenlly** [comment]
It sounds like your project is using Wallaby's automatic configuration. You should be able to create a Wallaby configuration file and [override the `files` setting](https://wallabyjs.com/docs/config/files.html#overriding-automatic-configuration) to exclude your JSON files:

**wallaby.js** (configuration file)
```javascript
module.exports = () => ({
  // modify `files` automatic configuration settings
  files: {
    override: (filePatterns) => {
      // TODO: modify `filePatterns` array as required
      filePatterns.push('!**/*.json');
      return filePatterns;
    }
  },
});
```

---

If that doesn't work and you're still having problems, can you please provide us with a cut-down sample (with the same structure as your project) with a single `JSON` file? This will allow us to understand your project structure and how/why the JSON file is being loaded by Wallaby.

**Comment by skanev** [comment]
This works for me, thanks!

I'm not sure where to put `wallaby.js`. I've so far put it as top-level in the project, but it doesn't get picked automatically. I can select it manually through Cmd+Shift+P, which at the very least solves my problem.

Given that not everybody in the team is using wallaby, where would you recommend to put this?

**Comment by smcenlly** [comment]
> I'm not sure where to put wallaby.js. I've so far put it as top-level in the project

This is the correct place to put your configuration; it must be in the top-level of your project.

> it doesn't get picked automatically. I can select it manually through Cmd+Shift+P

This is correct. If your project supports automatic configuration and you have a configuration file then you must explicitly select to use it.

> Given that not everybody in the team is using wallaby, where would you recommend to put this?

You will need to put your configuration file here. Perhaps you can include the wallaby pattern in your `.gitignore` if you're concerned about accidentally commiting it?
