### ISSUE TITLE
webstorm exception for node.js test

### ISSUE THREAD

**Issue by szarouski** [wallabyjs/public#31]
```
Attempt to load text for binary file which doesn't have a decompiler plugged in: D:\sz\websites\http-master\tests\.work\test.png
java.lang.IllegalArgumentException: Attempt to load text for binary file which doesn't have a decompiler plugged in: D:\sz\websites\http-master\tests\.work\test.png
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:410)
	at com.wallaby.javascript.u.a(Unknown Source)
	at com.wallaby.javascript.u.compute(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:894)
	at com.wallaby.javascript.p.B(Unknown Source)
	at com.wallaby.javascript.p.x(Unknown Source)
	at com.wallaby.javascript.session.Session$File.<init>(Unknown Source)
	at com.wallaby.javascript.session.Session$File.<init>(Unknown Source)
	at com.wallaby.javascript.session.Session$FileChangeCommand.<init>(Unknown Source)
	at com.wallaby.javascript.session.Session$FileChangeCommand.<init>(Unknown Source)
	at com.wallaby.javascript.session.Session$FileChangeCommand.<init>(Unknown Source)
	at com.wallaby.javascript.session.c.run(Unknown Source)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
	at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
	at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

```

Hi Artem, the issue is happening if one of the files within files array in config section is an image (in this case png). For the test which is failing I don't really need an image, so I can exclude it. If I understand correctly files are copied over to `C:\Users\$username$\.WebStorm10\system\wallaby\projects\$projectname$_wallaby\instrumented\...` I think there might be a case when user will want to do some manipulations with images and that is when exception will be raised (unless there is a way to workaround that). Thank you.

**Comment by ArtemGovorov** [comment]
Nice find, thanks. Will be looking into it shortly.

**Comment by ArtemGovorov** [comment]
Just a quick update - the issue is fixed and will be out tomorrow (or on Monday).

**Comment by szarouski** [comment]
Great news, thanks Artem. I'll do a quick test and close the issue when fix is published.

**Comment by ArtemGovorov** [comment]
Done.

**Comment by szarouski** [comment]
Hi Artem, currently, I'm getting following in tests panel: `Failed to parse tests/.work/test.png, SyntaxError: Unexpected token (1:8)`. My config contains following:
```js
module.exports = function () {
	return {
		files: [
			'src/*.js',
			'tests/**', //png is within tests folder
			'modules/**'
		],

		tests: [
			'tests/proxy.js'
		],

		env: {
			type: 'node',
			// if runner property is not set, then wallaby.js embedded node/io.js version is used
			// you can specifically set the node version by specifying 'node' (or any other command)
			// that resolves your default node version or just specify the path your node installation, like
			runner: 'node',
			// or
			// runner: 'path to the desired node version'
			params: {
				runner: '--harmony --harmony_arrow_functions'
			}
		}
	};
};
```

I just want to confirm if this is expected. Thank you.

**Comment by ArtemGovorov** [comment]
Hi Sergey,

It's not really expected. Seems like a wallaby cache issue. Could you try to change your config and restart wallaby.js? It can be any change, even just a space somewhere in it.

Another thing I have noticed is that your files and tests lists are intersecting. It can cause some other issues, have a look here https://github.com/wallabyjs/public#troubleshooting how to make them right.
You can use `'tests/**/*.js'`pattern if your tests folder contains some files that are not tests, but then you have to exclude tests by following the previously specified pattern with ` { pattern: 'tests/proxy.js', ignore: true } `. I'm not sure what's the pattern for your tests from your example, doesn't seem like there is, but then maybe you don't have any js files that are not tests in tests folder and may just not add `'tests/**/*.js'` to your files list, but only to tests list.

I'm working on providing some warning if the lists intersect.

```javascript
module.exports = function () {
    return {
        files: [
            'src/*.js',
            'tests/**/*.png', //png is within tests folder
            // if you have some files that are not tests (not in tests list) in tests folder
            // you can use:
            // 'tests/**/*.js', 
            // { pattern: 'tests/proxy.js', ignore: true } // exclude your tests like this or using some pattern
            'modules/**/*.js' // just in case
        ],

        tests: [
            'tests/proxy.js'
        ],

        env: {
            type: 'node',
            params: {
                runner: '--harmony --harmony_arrow_functions'
            }
        }
    };
};
```

**Comment by szarouski** [comment]
Hey, yes you're right it was a caching issue. As for tests and files pattern overlap, I was just trying to test a case with png and blindly included whole test directory in files, thanks for warning.
