### ISSUE TITLE
Gatsby + Jest Automatic Jest configuration error: Module jest-cli is not found in

### ISSUE THREAD

**Issue by chrisj-skinner** [wallabyjs/public#3100]
### Issue description or question

Gatsby 4.23.0 + Jest 29.2.2
Following the jest docs at: https://www.gatsbyjs.com/docs/how-to/testing/unit-testing/

Getting the following error when starting Wallaby:

```
‌[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'. 
[Error]  
[Error] We've also tried to automatically configure Wallaby.js for other frameworks 
[Error] Automatic Vitest configuration error: Vitest dependency not found. 
```

When comparing to:https://www.gatsbyjs.com/docs/how-to/testing/unit-testing/ (which works fine)  I don't see any differences in my setup. I've tried selecting the auto config as well as specifying the project folder

### Wallaby diagnostics report

Unable to copy the report which can be seen in the log below from the Walaby.js Console in VSCODE.

```
​[Info]​ Started Wallaby.js Core v1.0.1342
​​[Error] Failed to load configuration file: Automatic Jest configuration error: Module jest-cli is not found in '.'.​​
​​[Error] We've also tried to automatically configure Wallaby.js for other frameworks​​
​​[Error] Automatic Vitest configuration error: Vitest dependency not found.​​
​​[Error] Please refer to our docs: https://wallabyjs.com/docs/config/overview.html ​​
​​[Error] Failed to start copyDiagnosticsReportToClipboard operation, TypeError: Cannot read property 'map' of undefined​​
​​[Error]     at _0x17e365 (/Users/xxxxxxxxx/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby1ef227/node_modules/ws/lib/Sender.fallbacks.js:1:171805)​​
​​[Error]     at _0x30dade.<computed>.copyDiagnosticsReportToClipboard (/Users/xxxxxxxxx/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby1ef227/node_modules/ws/lib/Sender.fallbacks.js:1:172796)​​
​​[Error]     at Object.i.receive (/Users/xxxxxxxxx/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby1ef227/server.js:14:11638)​​
​​[Error]     at WebSocket.<anonymous> (/Users/xxxxxxxxx/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby1ef227/server.js:32:3317)​​
​​[Error]     at WebSocket.emit (events.js:314:20)​​
​​[Error]     at Receiver.ontext (/Users/xxxxxxxxx/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby1ef227/node_modules/ws/lib/WebSocket.js:841:10)​​
​​[Error]     at /Users/xxxxxxxxx/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby1ef227/node_modules/ws/lib/Receiver.js:536:18​​
​​[Error]     at /Users/xxxxxxxxx/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby1ef227/node_modules/ws/lib/Receiver.js:368:7​​
​​[Error]     at /Users/xxxxxxxxx/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby1ef227/node_modules/ws/lib/PerMessageDeflate.js:249:5​​
​​[Error]     at afterWrite (_stream_writable.js:490:5)​​
​​[Error]     at onwrite (_stream_writable.js:470:7)​​
​​[Error]     at InflateRaw.afterTransform (_stream_transform.js:98:3)​​
​​[Error]     at Zlib.processCallback (zlib.js:585:8)​​

```

**Comment by smcenlly** [comment]
We tried to reproduce your problem but it works for us when we follow the instructions. We uploaded the repo that we created [here](https://github.com/wallabyjs/gatsby-jest).

Can you please try our repo and let us know if it works for you?

If Wallaby is still not working for your project, are you able to share it with us so we can try and reproduce the problem ourselves? If that's not possible, please share your `package.json` with us so that we can inspect your dependencies.

**Comment by smcenlly** [comment]
@chrisj-skinner - did our sample repo work for you?

**Comment by smcenlly** [comment]
Closing this issue since we haven't heard back.
