### ISSUE TITLE
Wallaby + Mocha hooks file + import in hooks file does not work

### ISSUE THREAD

**Issue by wilgert** [wallabyjs/public#3102]
### Issue description or question

We need to do some cleanup in an after each hook which is located in a separate `hooks.js` file. This `hooks.js` subsequently needs to import some info from another file. When running the tests using mocha itself this is configured through a `.mocharc.yaml` file which wallaby does not seem to use.
So we add the afterEach hook in the setup function in `wallaby.js`. Unfortunately when running wallaby it gives us:
```
./test/hooks.js:1
import { SOME_INFO } from './some-info';
```

You can reproduce this issue by cloning the following repo: https://github.com/wilgert/wallaby-mocha-import-example

### Wallaby diagnostics report
```
{
  editorVersion: 'WebStorm 2022.2.3',
  pluginVersion: '1.0.253',
  editorType: 'IntelliJ',
  osVersion: 'darwin 21.5.0',
  nodeVersion: 'v14.17.0',
  coreVersion: '1.0.1345',
  checksum: 'ZTIxNDY1ZTgwOGRhYjg2YTE1NDc2OGZjMjAzZDQ3MjEsMTY2OTI0ODAwMDAwMCww',
  config: {
    env: { type: 'node', params: {}, runner: '<homeDir>/.nvm/versions/node/v14.17.0/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    files: [ { pattern: 'src/**/*.ts', ignore: false, trigger: true, load: true, instrument: true, order: 1 } ],
    tests: [ { pattern: 'test/**/*.spec.ts', ignore: false, trigger: true, load: true, test: true, order: 2 } ],
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: { '**/*.?(lit)coffee?(.md)': [Function (anonymous)] },
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: true,
    testFramework: { version: 'mocha@2.1.0', configurator: 'mocha@2.1.0', reporter: 'mocha@2.1.0', starter: 'mocha@2.1.0' },
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: true,
    symlinkNodeModules: undefined,
    configCode: 'module.exports = wallaby => ({\n' +
      "  env: { type: 'node' },\n" +
      "  files: ['src/**/*.ts'],\n" +
      "  tests: ['test/**/*.spec.ts'],\n" +
      '  setup: async function (w) {\n' +
      '    const mocha = w.testFramework;\n' +
      '    const rootHooksFile = w.localProjectDir + `/test/hooks.js`;\n' +
      '    const rootHook = await import(rootHooksFile);\n' +
      '    mocha.suite.afterEach = rootHook.mochaHooks.afterEach;\n' +
      '  },\n' +
      '});\n'
  },
  packageJSON: {
    dependencies: {},
    devDependencies: {
      '@types/chai': '^4.2.14',
      '@types/mocha': '^8.0.4',
      '@types/node': '^14.18.12',
      '@typescript-eslint/eslint-plugin': '^4.7.0',
      '@typescript-eslint/parser': '^4.7.0',
      chai: '^4.2.0',
      eslint: '^7.13.0',
      'eslint-config-prettier': '^8.5.0',
      'eslint-plugin-prettier': '^4.0.0',
      'eslint-plugin-unused-imports': '^1.0.0',
      husky: '^4.3.0',
      mocha: '^8.2.1',
      nanoid: '^3.3.1',
      nodemon: '^2.0.15',
      prettier: '^2.6.0',
      'ts-node': '^9.0.0',
      typescript: '^4.6.2'
    }
  },
  fs: { numberOfFiles: 2 },
  debug: [
    '2022-11-16T10:06:05.369Z project Wallaby Node version: v14.17.0\n',
    '2022-11-16T10:06:05.370Z project Wallaby config: <homeDir>/Projects/twallaby-mocha-import-example/wallaby.js\n',
    '2022-11-16T10:06:05.385Z fs File system starting\n',
    '2022-11-16T10:06:05.413Z fs File system scan completed\n',
    '2022-11-16T10:06:05.420Z project File cache: <homeDir>/Library/Caches/JetBrains/WebStorm2022.2/wallaby/projects/55963b1fb133d315\n',
    '2022-11-16T10:06:05.627Z uiService Listening port 51235\n',
    '2022-11-16T10:06:05.648Z workers Parallelism for initial run: 10, for regular run: 5\n',
    '2022-11-16T10:06:05.648Z workers Starting run worker instance #0\n',
    '2022-11-16T10:06:05.649Z workers Starting run worker instance #1\n',
    '2022-11-16T10:06:05.649Z workers Starting run worker instance #2\n',
    '2022-11-16T10:06:05.649Z workers Starting run worker instance #3\n',
    '2022-11-16T10:06:05.649Z workers Starting run worker instance #4\n',
    '2022-11-16T10:06:05.649Z workers Starting run worker instance #5\n',
    '2022-11-16T10:06:05.649Z workers Starting run worker instance #6\n',
    '2022-11-16T10:06:05.649Z workers Starting run worker instance #7\n',
    '2022-11-16T10:06:05.649Z workers Starting run worker instance #8\n',
    '2022-11-16T10:06:05.649Z workers Starting run worker instance #9\n',
    '2022-11-16T10:06:05.650Z workers Web server is listening at 55057\n',
    '2022-11-16T10:06:05.798Z project Stopping process pool\n',
    '2022-11-16T10:06:05.799Z project File cache is up-to-date, starting full test run\n',
    '2022-11-16T10:06:05.801Z project Running postprocessor\n',
    '2022-11-16T10:06:05.808Z postprocessor New TypeScript language service is required\n',
    '2022-11-16T10:06:06.590Z project Postprocessor execution finished\n',
    '2022-11-16T10:06:06.590Z project Test run started; run priority: 3\n',
    '2022-11-16T10:06:06.591Z project Running all tests\n',
    '2022-11-16T10:06:06.596Z workers Starting test run, priority: 3\n',
    '2022-11-16T10:06:06.597Z nodeRunner Starting sandbox [worker #0, session #1lpt5]\n',
    '2022-11-16T10:06:06.671Z nodeRunner Preparing sandbox [worker #0, session #1lpt5]\n',
    '2022-11-16T10:06:06.686Z workers Started run worker instance (delayed) #0\n',
    '2022-11-16T10:06:06.688Z nodeRunner Prepared sandbox [worker #0, session #1lpt5]\n',
    '2022-11-16T10:06:06.689Z workers [worker #0, session #1lpt5] Running tests in sandbox\n',
    '2022-11-16T10:06:06.697Z workers Started run worker instance (delayed) #2\n',
    '2022-11-16T10:06:06.702Z workers Started run worker instance (delayed) #1\n',
    '2022-11-16T10:06:06.724Z workers Started run worker instance (delayed) #3\n',
    '2022-11-16T10:06:06.726Z workers Started run worker instance (delayed) #4\n',
    '2022-11-16T10:06:06.770Z workers Started run worker instance (delayed) #7\n',
    '2022-11-16T10:06:06.873Z workers Started run worker instance (delayed) #5\n',
    '2022-11-16T10:06:06.892Z workers Started run worker instance (delayed) #6\n',
    '2022-11-16T10:06:06.904Z workers Started run worker instance (delayed) #9\n',
    '2022-11-16T10:06:06.909Z workers Sandbox (active) [1lpt5] error: ./test/hooks.js:1\n' +
      "import { SOME_INFO } from './some-info';\n" +
      '^^^^^^\n' +
      '\n' +
      'SyntaxError: Cannot use import statement outside a module\n' +
      '    at wrapSafe (internal/modules/cjs/loader.js:984:16)\n' +
      '    at Module._compile (internal/modules/cjs/loader.js:1032:27)\n' +
      '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)\n' +
      '    at Module.load (internal/modules/cjs/loader.js:933:32)\n' +
      '    at Function.Module._load (internal/modules/cjs/loader.js:774:14)\n' +
      '    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)\n' +
      '    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)\n' +
      '    at async Loader.import (internal/modules/esm/loader.js:177:24)\n',
    '2022-11-16T10:06:06.913Z workers Failed to map the stack to user code, entry message: Uncaught Error in Wallaby `setup` function: Cannot use import statement outside a module, stack: <homeDir>/Projects/wallaby-mocha-import-example/test/hooks.js:1\n' +
      "import { SOME_INFO } from './some-info';\n" +
      '^^^^^^\n' +
      '\n' +
      'SyntaxError: Cannot use import statement outside a module\n' +
      '    at wrapSafe (internal/modules/cjs/loader.js:984:16)\n' +
      '    at Module._compile (internal/modules/cjs/loader.js:1032:27)\n' +
      '    at Module._0xce904.<computed> [as _compile] (eval at <anonymous> (<homeDir>/Library/Caches/JetBrains/WebStorm2022.2/wallaby/wallaby/node_modules/q/q.js:2075:6), <anonymous>:1:1119849)\n' +
      '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)\n' +
      '    at Module.load (internal/modules/cjs/loader.js:933:32)\n' +
      '    at Function.Module._load (internal/modules/cjs/loader.js:774:14)\n' +
      '    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)\n' +
      '    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)\n' +
      '    at async Loader.import (internal/modules/esm/loader.js:177:24)\n' +
      '    at async eval (eval at module.exports (<homeDir>/Library/Caches/JetBrains/WebStorm2022.2/wallaby/wallaby/ru\n',
    '2022-11-16T10:06:06.934Z workers Started run worker instance (delayed) #8\n',
    '2022-11-16T10:06:07.011Z workers [1lpt5] Run 0 test(s), skipped 0 test(s)\n',
    '2022-11-16T10:06:07.016Z workers [1lpt5] Sandbox is responsive, closing it\n',
    '2022-11-16T10:06:07.017Z project Test run finished\n',
    '2022-11-16T10:06:07.018Z project Processed console.log entries\n',
    '2022-11-16T10:06:07.018Z project Processed loading sequences\n',
    '2022-11-16T10:06:07.018Z project Processed executed tests\n',
    '2022-11-16T10:06:07.018Z project Processed code coverage\n',
    '2022-11-16T10:06:07.036Z project Test run result processed and sent to IDE\n',
    '2022-11-16T10:06:09.900Z uiService UI client connected\n',
    '2022-11-16T10:06:09.900Z uiService Outgoing message ui:handshake\n',
    '2022-11-16T10:06:09.909Z uiService Incoming message ui:start\n',
    '2022-11-16T10:06:09.909Z uiService Outgoing message ui:summary\n',
    '2022-11-16T10:06:09.910Z uiService Outgoing message ui:files\n',
    '2022-11-16T10:06:09.920Z uiService Incoming message ui:closedInEditor\n',
    '2022-11-16T10:06:10.493Z uiService UI client connected\n',
    '2022-11-16T10:06:10.493Z uiService Outgoing message ui:handshake\n',
    '2022-11-16T10:06:10.505Z uiService Incoming message ui:start\n',
    '2022-11-16T10:06:10.506Z uiService Outgoing message ui:summary\n',
    '2022-11-16T10:06:10.506Z uiService Outgoing message ui:files\n'
  ]
}
```

**Comment by smcenlly** [comment]
Thanks for the sample repo.

The reason the `mocha` is working and Wallaby is not is that you are using `ts-node/register/transpile-only` in your mocha configuration to transpile all files at runtime (both `.ts` and `.js`) but Wallaby configuration is loading the uncompiled JavaScript file.

There are two ways to fix your problem (see below). The comments in the configuration explain the changes.

Personally, I'd go for option one if possible as it seems a little cleaner. 

**Option 1: Change your JavaScript Files to TypeScript files and include them in your configuration**

- rename `hooks.js` to `hooks.ts`
- rename `some-info.js` to `some-info.ts`
- change `.mocharc.yaml` from `require: test/hooks.js` to `require: test/hooks.ts`

```javascript
module.exports = wallaby => ({
  env: { type: 'node' },
  files: [
    'src/**/*.ts',

    // Update patterns to include non-spec files in test but do NOT instrument them
    { pattern: 'test/**/*.ts', instrument: false },

    // Explicilty exclude any `spec.ts` files under `test` folder
    '!test/**/*.spec.ts',
  ],
  tests: ['test/**/*.spec.ts'],
  setup: async function (w) {
    const mocha = w.testFramework;

    // Change to use compiled version of hooks, not uncompiled version
    const rootHooksFile = w.projectCacheDir + `/test/hooks.js`;
    const rootHook = await import(rootHooksFile);
    mocha.suite.afterEach = rootHook.mochaHooks.afterEach;
  },
});
```

**Option 2: Update Wallaby Configuration to Compile JavaScript Files**
```javascript
module.exports = wallaby => ({
  env: { type: 'node' },
  files: [
    'src/**/*.ts',

    // tell Wallaby to copy all JavaScript files from test folder and do NOT instrument them
    { pattern: 'test/**/*.js', instrument: false },
  ],
  tests: ['test/**/*.spec.ts'],

  // When copying JavaScript files, change the extension to `jsts`
  // this is required to allow TypeScript to compile JavaScript files
  preprocessors: {
    '**/*.jsts': file => file.changeExt('js').content
  },
  compilers: {
    '**/*.js': wallaby.compilers.typeScript({
      // Add `outDir` property to compiler options. This is required for TypeScript
      // compiler to emit the file to disk
      outDir: './any'
    }),
  },
  setup: async function (w) {
    const mocha = w.testFramework;

    // Change to use compiled version of hooks, not uncompiled version
    const rootHooksFile = w.projectCacheDir + `/test/hooks.js`;
    const rootHook = await import(rootHooksFile);
    mocha.suite.afterEach = rootHook.mochaHooks.afterEach;
  },
});
```
