### ISSUE TITLE
Failed to load configuration file: Automatic Angular CLI configuration error: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by mot4** [wallabyjs/public#3111]
### Issue description or question

I'm trying to run Wallaby in an angular project which has a library project.
After updating to angular 15 I'm getting this error:
**Failed to load configuration file: Automatic Angular CLI configuration error: The "path" argument must be of type string. Received undefined**

The same problem was solved once here: https://github.com/wallabyjs/public/issues/2305 

### Wallaby diagnostics report

Not available

### Trace log

````
wallaby.js started
core v1.0.1346
2022-11-25T18:29:17.155Z config Attempting automatic configuration for angular
2022-11-25T18:29:17.156Z angular/cli config Detecting Angular CLI.
2022-11-25T18:29:17.161Z angular/cli config Detected Angular CLI.
2022-11-25T18:29:17.164Z angular/cli config Angular currentDirPath: "C:\Users\<user>\WebstormProjects\<project-name>", workspaceDirPath: "C:\Users\<user>\WebstormProjects\<project-name>"
2022-11-25T18:29:17.175Z angular/cli karma workspace config Configuring.
2022-11-25T18:29:20.066Z angular/cli config TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:393:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:433:7)
    at t.<anonymous> (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:18:9390)
    at r (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:17:29781)
    at Object.next (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:17:29076)
    at o (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:17:28835)
2022-11-25T18:29:20.070Z angular/cli config Angular.json: 
 {
  '$schema': './node_modules/@angular/cli/lib/config/schema.json',
  schematics: {
    '@schematics/angular': { component: { changeDetection: 'OnPush' } },
    '@angular-eslint/schematics:application': { setParserOptionsProject: true },
    '@angular-eslint/schematics:library': { setParserOptionsProject: true }
  },
  version: 1,
  newProjectRoot: 'projects',
  projects: {
    '<project-name>': {
      projectType: 'application',
      schematics: { '@schematics/angular:component': { style: 'scss' }, '@schematics/angular:application': { strict: true } },
      root: '',
      sourceRoot: 'src',
      prefix: 'app',
      architect: {
        build: {
          builder: '@angular-devkit/build-angular:browser',
          options: {
            outputPath: 'dist/<project-name>',
            index: 'src/index.html',
            main: 'src/main.ts',
            polyfills: [ 'zone.js' ],
            tsConfig: 'tsconfig.app.json',
            inlineStyleLanguage: 'scss',
            assets: [
              'src/robots.txt',
              'src/assets',
              { glob: '**/*', input: './dist/<project-library-name>/assets/', output: './assets/' },
              { glob: 'CHANGELOG.md', input: '.', output: './assets/' },
              { glob: 'CHANGELOG_LATEST.md', input: '.', output: './assets/' }
            ],
            styles: [ 'dist/<project-library-name>/<project-name>.css', 'src/styles.scss' ],
            scripts: []
          },
          configurations: {
            production: {
              fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.prod.ts' } ],
              tsConfig: 'tsconfig.app.prod.json',
              index: 'src/index/prod/index.html',
              outputHashing: 'all'
            },
            development: { buildOptimizer: false, optimization: false, vendorChunk: true, extractLicenses: false, sourceMap: true, namedChunks: true }
          },
          defaultConfiguration: 'production'
        },
        serve: {
          builder: '@angular-devkit/build-angular:dev-server',
          configurations: { production: { browserTarget: '<project-name>:build:production' }, development: { browserTarget: '<project-name>:build:development' } },
          defaultConfiguration: 'development'
        },
        'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: '<project-name>:build' } },
        test: {
          builder: '@angular-devkit/build-angular:karma',
          options: {
            polyfills: [ 'zone.js', 'zone.js/testing' ],
            tsConfig: 'tsconfig.spec.json',
            karmaConfig: 'karma.conf.js',
            inlineStyleLanguage: 'scss',
            assets: [
              'src/robots.txt',
              'src/assets',
              { glob: '**/*', input: './dist/<project-library-name>/assets/', output: './assets/' },
              { glob: 'CHANGELOG.md', input: '.', output: './assets/' },
              { glob: 'CHANGELOG_LATEST.md', input: '.', output: './assets/' }
            ],
            styles: [ 'dist/<project-library-name>/<project-name>.css', 'src/styles.scss' ],
            scripts: []
          }
        },
        lint: {
          builder: '@krema/angular-eslint-stylelint-builder:lint',
          options: {
            eslintFilePatterns: [ 'src/**/*.ts', 'src/**/*.html', 'src/**/*.js', '*.ts', '*.js' ],
            eslintCache: true,
            eslintCacheLocation: '.eslintcache',
            stylelintFilePatterns: [ 'src/**/*.scss' ],
            stylelintCache: true,
            stylelintCacheLocation: '.stylelintcache',
            maxWarnings: 0
          }
        }
      }
    },
    '<project-library-name>': {
      projectType: 'library',
      root: 'projects/<project-library-name>',
      sourceRoot: 'projects/<project-library-name>',
      prefix: '<project-name>',
      architect: {
        build: {
          builder: '@angular-devkit/build-angular:ng-packagr',
          options: { project: 'projects/<project-library-name>/ng-package.json' },
          configurations: { production: { tsConfig: 'projects/<project-library-name>/tsconfig.lib.prod.json' }, development: { tsConfig: 'projects/<project-library-name>/tsconfig.lib.json' } },
          defaultConfiguration: 'production'
        },
        test: {
          builder: '@angular-devkit/build-angular:karma',
          options: {
            tsConfig: 'projects/<project-library-name>/tsconfig.spec.json',
            polyfills: [ 'zone.js', 'zone.js/testing' ],
            karmaConfig: 'projects/<project-library-name>/karma.conf.js',
            codeCoverageExclude: [ 'projects/<project-library-name>/src/lib/eem/client-information.ts' ],
            assets: [ { glob: '**/*', input: './dist/<project-library-name>/assets/', output: './assets/' } ]
          }
        },
        lint: {
          builder: '@krema/angular-eslint-stylelint-builder:lint',
          options: {
            eslintFilePatterns: [ 'projects/<project-library-name>/**/*.ts', 'projects/<project-library-name>/**/*.html', 'projects/<project-library-name>/**/*.js' ],
            eslintCache: true,
            eslintCacheLocation: 'projects/<project-library-name>/.eslintcache',
            stylelintFilePatterns: [ 'projects/<project-library-name>/**/*.scss' ],
            stylelintCache: true,
            stylelintCacheLocation: 'projects/<project-library-name>/.stylelintcache',
            maxWarnings: 0
          }
        }
      }
    },
    cypress: {
      projectType: 'library',
      root: 'cypress',
      sourceRoot: 'cypress',
      prefix: 'cypress',
      architect: {
        lint: {
          builder: '@krema/angular-eslint-stylelint-builder:lint',
          options: {
            eslintConfig: 'cypress/.eslintrc.js',
            eslintFilePatterns: [ 'cypress/**/*.ts', 'cypress/**/*.js' ],
            eslintCache: true,
            eslintCacheLocation: 'cypress/.eslintcache',
            stylelintFilePatterns: [],
            stylelintCache: true,
            stylelintCacheLocation: 'cypress/.stylelintcache',
            maxWarnings: 0
          }
        }
      }
    }
  },
  cli: { analytics: false }
}
2022-11-25T18:29:20.070Z angular/cli config TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:393:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:433:7)
    at t.<anonymous> (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:18:9390)
    at r (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:17:29781)
    at Object.next (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:17:29076)
    at o (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:17:28835)
2022-11-25T18:29:20.070Z config Finished attempting automatic configuration for angular (2916ms)
2022-11-25T18:29:20.070Z config Attempting automatic configuration for jest
2022-11-25T18:29:20.071Z jest/config Detecting Jest.
2022-11-25T18:29:20.078Z jest/config Error: Module jest-cli is not found in 'C:\Users\<user>\WebstormProjects\<project-name>'.
    at Object.<anonymous> (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:31:21447)
    at r (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:31:4685)
    at Object.next (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:31:3980)
    at C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:31:3889
    at new Promise (<anonymous>)
    at s (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:31:3683)
    at Object.loadJest (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:31:19045)
    at C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:18149
    at r (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:22882)
    at Object.next (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:22177)
    at C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:22086
    at new Promise (<anonymous>)
    at s (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:21880)
    at r (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:17837)
    at Object.<anonymous> (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:21557)
    at r (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:22882)
    at Object.next (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:22177)
    at C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:22086
    at new Promise (<anonymous>)
    at s (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:21880)
    at Object.n [as configure] (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:21438)
    at Config.<anonymous> (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:15:20840)
    at r (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:15:12061)
    at Object.next (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:15:11356)
    at o (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:15:11105)
2022-11-25T18:29:20.078Z config Finished attempting automatic configuration for jest (8ms)
2022-11-25T18:29:20.078Z config Attempting automatic configuration for vitest
2022-11-25T18:29:20.079Z vitest/config Detecting Vitest.
2022-11-25T18:29:20.081Z vitest/config Error: Vitest dependency not found.
    at Object.<anonymous> (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:24789)
    at r (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:28035)
    at Object.next (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:27330)
    at C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:27239
    at new Promise (<anonymous>)
    at n (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:27033)
    at Object.r [as configure] (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:19:24173)
    at Config.<anonymous> (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:15:20840)
    at r (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:15:12061)
    at Object.next (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:15:11356)
    at o (C:\Users\<user>\AppData\Local\JetBrains\WebStorm2022.2\wallaby\wallaby\server.js:15:11105)
2022-11-25T18:29:20.081Z config Finished attempting automatic configuration for vitest (3ms)
Failed to load configuration file: Automatic Angular CLI configuration error: The "path" argument must be of type string. Received undefined

We've also tried to automatically configure Wallaby.js for other frameworks
Automatic Jest configuration error: Module jest-cli is not found in '.'.
Automatic Vitest configuration error: Vitest dependency not found.
Please refer to our docs: https://wallabyjs.com/docs/config/overview.html

**Comment by NikGovorov** [comment]
Thanks for creating the issue, Angular CLI 15 support will be released on Monday.

**Comment by NikGovorov** [comment]
Angular CLI 15 support is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
