### ISSUE TITLE
Set tsconfig file path or modify config

### ISSUE THREAD

**Issue by mot4** [wallabyjs/public#3113]
### Issue description or question

I'm not able to let Wallaby know my tsconfig file.
I have tried this way:
```````````````
module.exports = (wallaby) => {
  const { compilerOptions } = require('./myOtherTsconfig.json');
  return {
    compilers: wallaby.compilers.typeScript(compilerOptions),
  };
};
```````````````
And also with:
`````````````
compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions),
    },
`````````````
But I get the following error:
``````````
Compilers cannot be set if built in webpack postprocessor is used.
``````````

If I set the postprocessor to wallaby-webpack with:
```````````````
module.exports = (wallaby) => {
  const { compilerOptions } = require('./myOtherTsconfig.json');
  const wallabyWebpack = require('wallaby-webpack');
  return {
    postprocessor: wallabyWebpack(),
    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions),
    },
  };
};
```````````````
I get:
`````````````````````
Unsupported webpack version. The 'wallaby-webpack' package does not support your project's version of webpack (5.75.0). Use Wallaby's built-in webpack integration instead: https://wallabyjs.com/docs/integration/webpack-built-in.html
    at module.exports (.\wallaby.js:5:20)
`````````````````````

I just want to modify the strict mode and a couple more of ts configs.

### Wallaby diagnostics report

````````````````````
Unsupported webpack version. The 'wallaby-webpack' package does not support your project's version of webpack (5.75.0). Use Wallaby's built-in webpack integration instead: https://wallabyjs.com/docs/integration/webpack-built-in.html
    at module.exports (.\wallaby.js:5:20)
``````````````````````

**Comment by smcenlly** [comment]
Can you please describe how you run your tests outside of Wallaby and provide your `package.json`?

Your configuration looks like it is missing the required sections for `files` and `tests`. If you are using webpack to bundle your files, then you will need to use `ts-loader` to compile your TypeScript code during bundling.

As per the error message, the `wallaby-webpack` package does not support your project's version of webpack (`5.75.0`). You will need to use our built-in webpack integration instead.

Please refer to [our docs](https://wallabyjs.com/docs/integration/webpack-built-in.html) for guidance. There is a [TypeScript sample project](https://github.com/wallabyjs/wallaby-webpack-ts-loader) listed at the bottom of the page.

**Comment by smcenlly** [comment]
One other question: 

I assume you have an Angular application? Do your tests run from the command-line using Angular? If so, is there any reason you're not using Wallaby's [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) vs. creating a configuration file?

**Comment by mot4** [comment]
I have an Angular application and I run my tests outside of Wallaby with 'ng test'. 
The problem with the automatic configuration is that in my project are two tsconfig files 'tsconfig.json' and 'tsconfig.app.json' where 'tsconfig.json' is extended. All I want is to say Wallaby to take the tsconfig.app.json instead of the tsconfig.json. Or in case it's not possible, provide Wallaby with the config of tsconfig.app.json (what I was trying to do in the snippets).

For example, in tsconfig.json strict is set to true, while in tsconfig.app.json is set to false.

**Comment by NikGovorov** [comment]
If you have only one project in your workspace then Wallaby should act like `ng test` and use `tsconfig.spec.json`.

**Comment by mot4** [comment]
> Assuming that you have multiple projects in your Angular CLI workspace, you may consider using custom workspace `tsconfig` exclusively for Wallaby. https://wallabyjs.com/docs/integration/angular.html#automatic-configuration-workspace-overrides

This was it! It's working with the `tsconfig.wallaby.spec.json`. Thank u!
