### ISSUE TITLE
error TS2304: Cannot find name 'getTestBed'.  20 getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting()

### ISSUE THREAD

**Issue by manudss** [wallabyjs/public#3114]
### Issue description or question

Hello,

We have this problem, when we launch Wallabyjs :

```
apps/idaas-portal/src/test.ts:20:1 - error TS2304: Cannot find name 'getTestBed'.

20 getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting(), {
   ~~~~~~~~~~

    at t.<anonymous> (C:\Users\A740550\AppData\Local\JetBrains\IntelliJIdea2022.3\wallaby\wallaby\server.js:23:11296)
    at r (C:\Users\A740550\AppData\Local\JetBrains\IntelliJIdea2022.3\wallaby\wallaby\server.js:23:7523)
    at Object.next (C:\Users\A740550\AppData\Local\JetBrains\IntelliJIdea2022.3\wallaby\wallaby\server.js:23:6818)
    at o (C:\Users\A740550\AppData\Local\JetBrains\IntelliJIdea2022.3\wallaby\wallaby\server.js:23:6577)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```
Do you have any idea why? But what makes, that we can't launch the tests via Wallabyjs.

### Wallaby diagnostics report

https://gist.github.com/manudss/aa28524922b52c92b6716f05bac79aa5

**Comment by manudss** [comment]
In the disagnostics reports, you get the test.ts like this : 
```json
{
            path: 'C:/dev/idaas_front_end/src/apps/idaas-portal/src/test.ts',
            code: '// This file is required by karma.conf.js and loads recursively all the .spec and framework files\r\n' +
              '// /!\\ Do not order the import for this files.  Zone and Zone-testing must be on always on top\r\n' +
              '// Do not apply prettier to this files, (deactivate git hooks when commit)\r\n' +
              '// prettier-ignore\r\n' +
              '\r\n' +
              '\r\n' +
              '\r\n' +
              '\r\n' +
              '\r\n' +
              '\r\n' +
              "import { autoUnsubscribe } from '@hirez_io/observer-spy';\r\n" +
              '\r\n' +
              '// add auto Unsubscribe when use @hirez_io/observer-spy to test rxjs subscription.\r\n' +
              'autoUnsubscribe();\r\n' +
              '\r\n' +
              '// eslint-disable-next-line @typescript-eslint/no-explicit-any\r\n' +
              '\r\n' +
              '\r\n' +
              '// First, initialize the Angular testing environment.\r\n' +
              'getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting(), {\r\n' +
              '    teardown: { destroyAfterEach: false }\r\n' +
              '});\r\n' +
              '// Then we find all the tests.\r\n' +
              '\r\n' +
              '// And load the modules.\r\n' +
              '\r\n'
          },
```


But the real file was : 
```typescript
// This file is required by karma.conf.js and loads recursively all the .spec and framework files
// /!\ Do not order the import for this files.  Zone and Zone-testing must be on always on top
// Do not apply prettier to this files, (deactivate git hooks when commit)
// prettier-ignore
import 'zone.js';
import 'zone.js/testing';

import { getTestBed } from '@angular/core/testing';
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';

import { autoUnsubscribe } from '@hirez_io/observer-spy';

// add auto Unsubscribe when use @hirez_io/observer-spy to test rxjs subscription.
autoUnsubscribe();

// eslint-disable-next-line @typescript-eslint/no-explicit-any
declare const require: any;

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting(), {
    teardown: { destroyAfterEach: false }
});
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);
```

We saw that all imports were removed ! (excepts autoUnsubscribe). Do you have something that clean the code of index.ts before ?

**Comment by NikGovorov** [comment]
Could you please try to update to [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update)?

**Comment by NikGovorov** [comment]
Try to delete `.angular` folder if the update does not help.

**Comment by manudss** [comment]
Many thanks. This was corrected the error. 

And now all imports are correctly displayed into the diagnostic report. 

I have just needed to clear Walaby cache in order to make all tests workings.
