### ISSUE TITLE
WallabyJS fails all of a sudden

### ISSUE THREAD

**Issue by lhmbe** [wallabyjs/public#3117]
### Issue description or question

Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: ./apps/xx/src/test.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at ./node_modules/@ngtools/webpack/src/ivy/loader.js:59:26
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:442:9)
@ ./apps/francis-shared/src/test.ts

### Wallaby diagnostics report

```
{
  editorVersion: 'IntelliJ IDEA 2022.1',
  pluginVersion: '1.0.238',
  editorType: 'IntelliJ',
  osVersion: 'darwin 21.6.0',
  nodeVersion: 'v18.9.0',
  coreVersion: '1.0.1351',
  checksum: 'ZmJlMTY4NmQzYTk4ZTMzZTg1MjFhNTlhNmM1ZTA2ZGMsMTY3MzU2ODAwMDAwMCww',
  config: {
    trace: false,
    env: {
      kind: 'chrome',
      params: { runner: '--headless --disable-gpu --disable-web-security --deterministic-fetch' },
      type: 'browser',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    diagnostics: {
      angular: {
        workspace: {
          '$schema': './node_modules/@angular/cli/lib/config/schema.json',
          version: 1,
          newProjectRoot: 'apps',
          projects: {
            'xxxxx-web': {
              root: 'apps/xxxxx-web',
              sourceRoot: 'apps/xxxxx-web/src',
              projectType: 'application',
              prefix: 'x',
              schematics: { '@schematics/angular:component': { style: 'scss' } },
              architect: {
                build: {
                  builder: '@angular-devkit/build-angular:browser',
                  options: {
                    allowedCommonJsDependencies: [ 'lodash', 'chart.js', 'flat', 'rxjs-compat', 'big.js', 'uuid' ],
                    outputPath: 'dist/',
                    index: 'apps/xxxxx-web/src/index.html',
                    main: 'apps/xxxxx-web/src/main.ts',
                    polyfills: 'polyfills.ts',
                    tsConfig: 'apps/xxxxx-web/src/tsconfig.app.json',
                    assets: [ 'apps/xxxxx-web/src/favicon.ico', 'apps/xxxxx-web/src/assets' ],
                    styles: [ 'apps/xxxxx-web/src/styles.scss' ],
                    scripts: [ 'node_modules/detect-zoom/detect-zoom.min.js' ],
                    stylePreprocessorOptions: { includePaths: [ 'apps/xxxxx-web/src/assets/typography/', 'apps/xxxxx-shared/src/sass/' ] },
                    outputHashing: 'all',
                    statsJson: true,
                    extractLicenses: false,
                    sourceMap: true,
                    namedChunks: true
                  },
                  configurations: {
                    apigw: {
                      aot: false,
                      vendorChunk: true,
                      buildOptimizer: false,
                      optimization: false,
                      fileReplacements: [ { replace: 'apps/xxxxx-web/src/environments/environment.ts', with: 'apps/xxxxx-web/src/environments/environment.apigw.ts' } ]
                    },
                    'pro-no-optimization': { optimization: false },
                    pro: { sourceMap: false, namedChunks: false, outputPath: 'target/dist' },
                    local: { aot: false, vendorChunk: true, namedChunks: false, buildOptimizer: true },
                    e2e: {
                      namedChunks: false,
                      aot: true,
                      buildOptimizer: true,
                      fileReplacements: [ { replace: 'apps/xxxxx-web/src/environments/environment.ts', with: 'apps/xxxxx-web/src/environments/environment.e2e.ts' } ]
                    }
                  },
                  defaultConfiguration: ''
                },
                serve: {
                  builder: '@angular-devkit/build-angular:dev-server',
                  options: { browserTarget: 'xxxxx-web:build', disableHostCheck: true },
                  configurations: {
                    dev: { browserTarget: 'xxxxx-web:build:dev' },
                    e2e: { browserTarget: 'xxxxx-web:build:e2e' },
                    apigw: { browserTarget: 'xxxxx-web:build:apigw' },
                    acc: { browserTarget: 'xxxxx-web:build:acc' },
                    pro: { browserTarget: 'xxxxx-web:build:pro' },
                    production: { browserTarget: 'xxxxx-web:build:pro' }
                  }
                },
                'serve-e2e': {
                  builder: '@angular-devkit/build-angular:dev-server',
                  options: { browserTarget: 'xxxxx-web:build', disableHostCheck: true },
                  configurations: {
                    dev: { browserTarget: 'xxxxx-web:build:dev' },
                    e2e: { browserTarget: 'xxxxx-web:build:e2e' },
                    apigw: { browserTarget: 'xxxxx-web:build:apigw' },
                    acc: { browserTarget: 'xxxxx-web:build:acc' },
                    pro: { browserTarget: 'xxxxx-web:build:pro' },
                    production: { browserTarget: 'xxxxx-web:build:pro' }
                  }
                },
                'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: 'xxxxx-web:build' } },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    codeCoverage: true,
                    main: 'apps/xxxxx-web/src/test.ts',
                    polyfills: 'polyfills.ts',
                    tsConfig: 'apps/xxxxx-web/src/tsconfig.spec.json',
                    karmaConfig: 'karma.conf.js',
                    styles: [ 'apps/xxxxx-web/src/styles.scss' ],
                    scripts: [ 'node_modules/detect-zoom/detect-zoom.min.js' ],
                    assets: [ 'apps/xxxxx-web/src/favicon.ico', 'apps/xxxxx-web/src/assets' ],
                    stylePreprocessorOptions: { includePaths: [ 'apps/xxxxx-web/src/assets/typography/', 'apps/xxxxx-shared/src/sass/' ] }
                  }
                },
                lint: { builder: '@angular-eslint/builder:lint', options: { lintFilePatterns: [ 'apps/xxxxx-web/**/*.ts', 'apps/xxxxx-web/**/*.html' ] } }
              }
            },
            'xxxxx-mobile': {
              root: 'apps/xxxxx-mobile',
              sourceRoot: 'apps/xxxxx-mobile/src',
              projectType: 'application',
              prefix: 'fcsm',
              schematics: { '@schematics/angular:component': { style: 'scss' } },
              architect: {
                build: {
                  builder: '@angular-devkit/build-angular:browser',
                  options: {
                    allowedCommonJsDependencies: [],
                    outputPath: 'apps/xxxxx-mobile/www',
                    index: 'apps/xxxxx-mobile/src/index.html',
                    main: 'apps/xxxxx-mobile/src/main.ts',
                    polyfills: 'polyfills.ts',
                    tsConfig: 'apps/xxxxx-mobile/src/tsconfig.app.json',
                    assets: [ 'apps/xxxxx-mobile/src/favicon.ico', 'apps/xxxxx-mobile/src/assets' ],
                    styles: [ 'apps/xxxxx-mobile/src/styles.scss', 'apps/xxxxx-mobile/src/overrides.scss' ],
                    scripts: [],
                    stylePreprocessorOptions: { includePaths: [ 'apps/xxxxx-mobile/src/assets/typography/', 'apps/xxxxx-shared/src/sass/' ] },
                    aot: false,
                    vendorChunk: true,
                    extractLicenses: false,
                    buildOptimizer: false,
                    sourceMap: true,
                    optimization: false,
                    namedChunks: true
                  },
                  configurations: {
                    local: { namedChunks: false },
                    dev: {
                      namedChunks: false,
                      fileReplacements: [ { replace: 'apps/xxxxx-mobile/src/environments/environment.ts', with: 'apps/xxxxx-mobile/src/environments/environment.dev.ts' } ]
                    },
                    acc: {
                      namedChunks: false,
                      fileReplacements: [ { replace: 'apps/xxxxx-mobile/src/environments/environment.ts', with: 'apps/xxxxx-mobile/src/environments/environment.acc.ts' } ]
                    },
                    prod: {
                      sourceMap: false,
                      fileReplacements: [ { replace: 'apps/xxxxx-mobile/src/environments/environment.ts', with: 'apps/xxxxx-mobile/src/environments/environment.prod.ts' } ]
                    }
                  },
                  defaultConfiguration: ''
                },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    codeCoverage: true,
                    main: 'apps/xxxxx-mobile/src/test.ts',
                    polyfills: 'polyfills.ts',
                    tsConfig: 'apps/xxxxx-mobile/src/tsconfig.spec.json',
                    karmaConfig: 'karma.conf.js',
                    stylePreprocessorOptions: { includePaths: [ 'apps/xxxxx-web/src/assets/typography/', 'apps/xxxxx-shared/src/sass/' ] }
                  }
                },
                serve: {
                  builder: '@angular-devkit/build-angular:dev-server',
                  options: { browserTarget: 'xxxxx-mobile:build', disableHostCheck: true },
                  configurations: { dev: { browserTarget: 'xxxxx-mobile:build:dev' }, acc: { browserTarget: 'xxxxx-mobile:build:acc' }, defaultConfiguration: 'dev' }
                },
                'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: 'xxxxx-mobile:build' } },
                lint: { builder: '@angular-eslint/builder:lint', options: { lintFilePatterns: [ 'apps/xxxxx-mobile/**/*.ts', 'apps/xxxxx-mobile/**/*.html' ] } }
              }
            },
            'xxxxx-web-e2e': {
              root: 'apps/xxxxx-web',
              sourceRoot: 'apps/xxxxx-web/e2e',
              projectType: 'library',
              prefix: '',
              architect: {
                lint: { builder: '@angular-eslint/builder:lint', options: { lintFilePatterns: [ 'apps/xxxxx-web/e2e/**/*.ts', 'apps/xxxxx-web/e2e/**/*.html' ] } }
              }
            },
            'xxxxx-shared': {
              projectType: 'library',
              root: 'apps/xxxxx-shared',
              sourceRoot: 'apps/xxxxx-shared/src',
              prefix: 'fcs',
              architect: {
                build: {
                  builder: '@angular-devkit/build-ng-packagr:build',
                  options: {
                    tsConfig: 'apps/xxxxx-shared/tsconfig.lib.json',
                    project: 'apps/xxxxx-shared/ng-package.json',
                    stylePreprocessorOptions: { includePaths: [ 'apps/xxxxx-shared/src/typography', 'apps/xxxxx-shared/src/sass' ] }
                  },
                  configurations: { production: { tsConfig: 'apps/xxxxx-shared/tsconfig.lib.prod.json' } }
                },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    codeCoverage: true,
                    codeCoverageExclude: [ '**/*.mock-impl.ts' ],
                    main: 'apps/xxxxx-shared/test.ts',
                    polyfills: 'polyfills.ts',
                    tsConfig: 'apps/xxxxx-shared/tsconfig.spec.json',
                    karmaConfig: 'karma.conf.js',
                    stylePreprocessorOptions: { includePaths: [ 'apps/xxxxx-shared/src/typography', 'apps/xxxxx-shared/src/sass' ] }
                  }
                },
                lint: { builder: '@angular-eslint/builder:lint', options: { lintFilePatterns: [ 'apps/xxxxx-shared/**/*.ts', 'apps/xxxxx-shared/**/*.html' ] } }
              }
            }
          },
          cli: { packageManager: 'yarn' }
        },
        polyfill: {
          path: '<homeDir>/git/x/wallaby-polyfills.js',
          code: "require('<homeDir>/git/x/node_modules/@angular-devkit/build-angular/src/webpack/jit-polyfills.js');\nrequire('<homeDir>/git/x/polyfills.ts');"
        },
        main: [
          {
            path: '<homeDir>/git/x/apps/xxxxx-web/src/test.ts',
            code: '\n' +
              '              \n' +
              "              import 'zone.js/testing';  \n" +
              "              import { getTestBed } from '@angular/core/testing';\n" +
              '      \n' +
              '              import {\n' +
              '                BrowserDynamicTestingModule,\n' +
              '                platformBrowserDynamicTesting\n' +
              "              } from '@angular/platform-browser-dynamic/testing'; \n" +
              '          \n' +
              '              getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting(), { teardown: { destroyAfterEach: true }});\n' +
              '              '
          },
          {
            path: '<homeDir>/git/x/apps/xxxxx-mobile/src/test.ts',
            code: '\n              \n                \n              \n      \n               \n          \n              \n              '
          },
          {
            path: '<homeDir>/git/x/apps/xxxxx-shared/src/test.ts',
            code: '\n              \n                \n              \n      \n               \n          \n              \n              '
          }
        ]
      }
    },
    testFramework: { version: 'jasmine@3.10.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3', autoDetected: true },
    files: [
      { pattern: 'node_modules/detect-zoom/detect-zoom.min.js', instrument: false, load: true, ignore: false, trigger: true, order: 1 },
      { pattern: 'polyfills.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-web/src/test.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-web/src/main.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-web/src/index.html', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-web/src/test.base.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-web/src/test.wallaby.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-web/src/**/*.spec.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-web/src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 2 },
      { pattern: 'apps/xxxxx-web/src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 3 },
      { pattern: 'polyfills.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-mobile/src/test.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-mobile/src/main.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-mobile/src/index.html', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-mobile/src/test.base.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-mobile/src/test.wallaby.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-mobile/src/**/*.spec.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-mobile/src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 4 },
      { pattern: 'apps/xxxxx-mobile/src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 5 },
      { pattern: 'polyfills.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-shared/test.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-shared/src/test.base.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-shared/src/test.wallaby.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-shared/src/**/*.spec.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/xxxxx-shared/src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 6 },
      { pattern: 'apps/xxxxx-shared/src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 7 }
    ],
    tests: [
      { pattern: 'apps/xxxxx-web/src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 8 },
      { pattern: 'apps/xxxxx-mobile/src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 9 },
      { pattern: 'apps/xxxxx-shared/src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 10 }
    ],
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: false,
    configCode: 'auto.detect#1982606356'
  },
  packageJSON: {
    dependencies: {
      '@angular-slider/ngx-slider': '^2.0.4',
      '@angular/animations': '12.2.16',
      '@angular/cdk': '12.2.13',
      '@angular/common': '12.2.16',
      '@angular/compiler': '12.2.16',
      '@angular/core': '12.2.16',
      '@angular/forms': '12.2.16',
      '@angular/localize': '12.2.16',
      '@angular/platform-browser': '12.2.16',
      '@angular/platform-browser-dynamic': '12.2.16',
      '@angular/router': '12.2.16',
      '@atlas-angular/businesstypes': '5.2.0',
      '@atlas-angular/cdk': '5.2.0',
      '@atlas-angular/l10n': '5.2.0',
      '@atlas-angular/logger': '5.2.0',
      '@atlas-angular/rxjs': '5.2.0',
      '@atlas/businesstypes': '5.2.0',
      '@atlas/logger': '5.2.0',
      '@azure/msal-angular': '2.4.4',
      '@azure/msal-browser': '2.29.0',
      '@compodoc/compodoc': '1.1.11',
      '@ionic/eslint-config': '0.3.0',
      '@maia/accordion-lists': '5.9.0',
      '@maia/action-tile': '5.6.0',
      '@maia/actions': '5.9.0',
      '@maia/additional-information': '5.6.0',
      '@maia/avatars': '5.6.0',
      '@maia/badge': '5.6.0',
      '@maia/buttons': '5.6.0',
      '@maia/charts': '5.9.0',
      '@maia/collapsibles': '5.6.0',
      '@maia/core': '5.6.0',
      '@maia/datepickers': '5.6.0',
      '@maia/divider': '5.9.0',
      '@maia/dropdowns': '5.6.0',
      '@maia/ecommerce': '5.6.0',
      '@maia/empty-state': '5.6.0',
      '@maia/forms': '5.6.0',
      '@maia/general-information': '5.9.0',
      '@maia/icons': '5.6.0',
      '@maia/input-autocomplete': '5.6.0',
      '@maia/input-masks': '5.6.0',
      '@maia/input-select': '5.6.0',
      '@maia/layout': '5.6.0',
      '@maia/lists': '5.6.0',
      '@maia/mini-buttons': '5.6.0',
      '@maia/modals': '5.6.0',
      '@maia/name-value-collections': '5.6.0',
      '@maia/panels': '5.6.0',
      '@maia/pop-ups': '5.9.0',
      '@maia/radio-buttons': '5.6.0',
      '@maia/ranges': '5.6.0',
      '@maia/rich-text': '5.6.0',
      '@maia/search-autocomplete': '5.6.0',
      '@maia/search-bar': '5.6.0',
      '@maia/select': '5.6.0',
      '@maia/select-tile': '^5.9.0',
      '@maia/slide-ins': '5.9.0',
      '@maia/spinners': '5.6.0',
      '@maia/squares': '5.6.0',
      '@maia/stamps': '5.6.0',
      '@maia/styles': '5.9.0',
      '@maia/switches': '5.6.0',
      '@maia/system-messages': '5.9.0',
      '@maia/tables': '5.9.0',
      '@maia/tabs': '5.6.0',
      '@maia/tags': '5.6.0',
      '@maia/text-area': '5.6.0',
      '@maia/text-lists': '5.9.0',
      '@maia/themes': '5.9.0',
      '@maia/tiles': '5.6.0',
      '@maia/timepickers': '5.6.0',
      '@ng-stack/contenteditable': '1.1.1',
      '@ngneat/hot-toast': '2.0.2',
      '@ngneat/overview': '1',
      '@ngneat/transloco': '2.21.0',
      '@ngneat/transloco-persist-lang': '1.0.4',
      '@ngneat/transloco-persist-translations': '1.0.5',
      '@ngneat/transloco-preload-langs': '2.0.4',
      '@s-libs/js-core': '12.0.0',
      '@s-libs/micro-dash': '12.0.0',
      '@s-libs/ng-core': '12.0.0',
      '@s-libs/rxjs-core': '12.0.0',
      'angular-svg-icon': '12.0.0',
      'angular-svg-icon-preloader': '1.0.0',
      'chart.js': '2.9.4',
      'classlist.js': '1.1.20150312',
      'date-fns': '2.22.1',
      debug: '4.1.1',
      'detect-zoom': '1.0.2',
      hammerjs: '2.0.8',
      'jwt-decode': '3.1.2',
      'lodash-es': '4.17.15',
      'ng2-charts': '2.4.3',
      'ngx-autosize': '1.7.2',
      'ngx-dropzone': '3.0.0',
      'ngx-long-press2': '1.0.0',
      'ngx-mask': '8.0.0',
      'ngx-pipes': '2.7.5',
      'ngx-ui-scroll': '2.3.1',
      'node-ts': '5.1.2',
      'normalize.css': '8.0.1',
      plist: '3.0.4',
      postcss: '8.4.16',
      'postcss-scss': '4.0.4',
      rxjs: '6.6.7',
      'rxjs-compat': '6.6.7',
      'ts-data.stack': '1.0.6',
      tslib: '2.0.0',
      uuid: '8.3.2',
      yargs: '16.2.0',
      'zone.js': '0.11.4'
    },
    devDependencies: {
      '@angular-devkit/build-angular': '12.2.17',
      '@angular-devkit/build-ng-packagr': '0.1002.0',
      '@angular-eslint/builder': '12.1.0',
      '@angular-eslint/eslint-plugin': '12.1.0',
      '@angular-eslint/eslint-plugin-template': '12.1.0',
      '@angular-eslint/schematics': '12.1.0',
      '@angular-eslint/template-parser': '12.1.0',
      '@angular/cli': '12.2.17',
      '@angular/compiler-cli': '12.2.16',
      '@angular/language-service': '12.2.16',
      '@capacitor-community/barcode-scanner': '2.1.1',
      '@capacitor/android': '4.3.0',
      '@capacitor/app': '4.0.1',
      '@capacitor/browser': '4.0.1',
      '@capacitor/camera': '4.1.1',
      '@capacitor/cli': '4.3.0',
      '@capacitor/core': '4.3.0',
      '@capacitor/device': '4.0.1',
      '@capacitor/dialog': '4.0.1',
      '@capacitor/ios': '4.3.0',
      '@capacitor/keyboard': '4.0.1',
      '@capacitor/network': '4.0.1',
      '@capacitor/status-bar': '4.0.1',
      '@types/chrome': '0.0.126',
      '@types/jasmine': '3.5.10',
      '@types/jasminewd2': '2.0.8',
      '@types/lodash-es': '4.17.3',
      '@types/node': '12.12.50',
      '@types/selenium-webdriver': '4.0.6',
      '@typescript-eslint/eslint-plugin': '4.23.0',
      '@typescript-eslint/parser': '4.23.0',
      'backoff-rxjs': '6.5.7',
      'capacitor-native-settings': '4.0.1',
      'chrome-webstore-upload-cli': '1.2.0',
      concurrently: '4.1.0',
      crx: '5.0.1',
      cypress: '9.3.1',
      'edit-json-file': '1.6.0',
      eslint: '^7.26.0',
      'eslint-config-prettier': '8.5.0',
      'eslint-plugin-import': 'latest',
      'eslint-plugin-jsdoc': 'latest',
      'eslint-plugin-prefer-arrow': 'latest',
      'eslint-plugin-sonarjs': '0.8.0-125',
      'http-server': '0.12.3',
      'jasmine-core': '3.6.0',
      'jasmine-expect': '4.0.3',
      'jasmine-spec-reporter': '5.0.2',
      karma: '6.3.3',
      'karma-chrome-launcher': '3.1.0',
      'karma-coverage-istanbul-reporter': '3.0.3',
      'karma-jasmine': '4.0.1',
      'karma-jasmine-html-reporter': '1.5.4',
      'karma-jasmine-matchers': '4.0.2',
      'karma-jasmine-seed-reporter': '0.2.0',
      'karma-mocha-reporter': '2.2.5',
      mocha: '8.1.3',
      mochawesome: '6.1.1',
      'mochawesome-merge': '4.2.0',
      'mochawesome-report-generator': '5.1.0',
      'ng-packagr': '12.0.5',
      'node-fetch': '2.6.0',
      'postinstall-postinstall': '2.0.0',
      prettier: '2.7.1',
      'raw-loader': '4.0.2',
      'sass-loader': '12.1.0',
      'selenium-webdriver': '4.0.0-alpha.5',
      shave: '2.5.9',
      'source-map-explorer': '2.2.2',
      'start-server-and-test': '1.14.0',
      stylelint: '14.10.0',
      'stylelint-config-prettier': '9.0.3',
      'stylelint-config-standard-scss': '3.0.0',
      'stylelint-order': '4.1.0',
      'stylelint-scss': '3.19.0',
      'ts-mockito': '2.6.1',
      'ts-node': '10.0.0',
      typescript: '4.2.4',
      'wallaby-webpack': '3.9.16',
      watch: '1.0.2',
      'webdriver-manager': '13'
    }
  },
  fs: { numberOfFiles: 3138 },
  debug: [
    '2022-12-01T14:41:30.071Z config Attempting automatic configuration for angular\n',
    '2022-12-01T14:41:30.073Z angular/cli config Detected Angular CLI.\n',
    '2022-12-01T14:41:30.074Z angular/cli config Angular currentDirPath: "<homeDir>/git/x", workspaceDirPath: "<homeDir>/git/x"\n',
    '2022-12-01T14:41:32.115Z angular/cli karma workspace config Using default <homeDir>/git/x/apps/xxxxx-web/src/test.ts.\n',
    '2022-12-01T14:41:32.117Z angular/cli karma workspace config Using default <homeDir>/git/x/apps/xxxxx-mobile/src/test.ts.\n',
    '2022-12-01T14:41:32.119Z angular/cli karma workspace config Using default <homeDir>/git/x/apps/xxxxx-shared/src/test.ts.\n',
    '2022-12-01T14:41:32.119Z angular/cli karma workspace config Using physical <homeDir>/git/x/tsconfig.wallaby.spec.json.\n',
    '2022-12-01T14:41:34.935Z config Finished attempting automatic configuration for angular (4864ms)\n',
    '2022-12-01T14:41:34.936Z project Wallaby Node version: v18.9.0\n',
    '2022-12-01T14:41:34.936Z project Wallaby config: <homeDir>/git/x/auto.detect\n',
    '2022-12-01T14:41:34.942Z fs File system starting\n',
    '2022-12-01T14:41:36.207Z fs File system scan has finished by timeout\n',
    '2022-12-01T14:41:36.247Z project File cache: <homeDir>/Library/Caches/JetBrains/IntelliJIdea2022.1/wallaby/projects/f662018d01c351ab\n',
    '2022-12-01T14:41:37.215Z uiService Listening port 51235\n',
    '2022-12-01T14:41:37.222Z project package.json file change detected, invalidating local cache\n',
    '2022-12-01T14:41:37.397Z workers Parallelism for initial run: 8, for regular run: 4\n',
    '2022-12-01T14:41:37.397Z workers Starting run worker instance #0\n',
    '2022-12-01T14:41:37.397Z workers Starting run worker instance #1\n',
    '2022-12-01T14:41:37.397Z workers Starting run worker instance #2\n',
    '2022-12-01T14:41:37.397Z workers Starting run worker instance #3\n',
    '2022-12-01T14:41:37.397Z workers Starting run worker instance #4\n',
    '2022-12-01T14:41:37.397Z workers Starting run worker instance #5\n',
    '2022-12-01T14:41:37.397Z workers Starting run worker instance #6\n',
    '2022-12-01T14:41:37.397Z workers Starting run worker instance #7\n',
    '2022-12-01T14:41:37.402Z workers Web server is listening at 51874\n',
    '2022-12-01T14:41:37.408Z project Stopping process pool\n',
    '2022-12-01T14:41:37.408Z project File cache is up-to-date, starting full test run\n',
    '2022-12-01T14:41:37.409Z project Running postprocessor\n',
    '2022-12-01T14:41:37.428Z postprocessor Processing started.\n',
    '2022-12-01T14:41:37.428Z postprocessor Initializing.\n',
    '2022-12-01T14:41:37.430Z postprocessor Initializing entry.\n',
    '2022-12-01T14:41:37.430Z postprocessor Sanitizing configuration.\n',
    '2022-12-01T14:41:37.430Z postprocessor Adjusting configuration.\n',
    '2022-12-01T14:41:37.433Z postprocessor Creating compiler.\n',
    '2022-12-01T14:41:37.588Z postprocessor Customizing compiler.\n',
    '2022-12-01T14:41:37.588Z postprocessor Compilation started.\n',
    '2022-12-01T14:41:51.735Z workers Started run worker instance (immediate) #0\n',
    '2022-12-01T14:41:51.735Z workers Started run worker instance (immediate) #1\n',
    '2022-12-01T14:41:51.735Z workers Started run worker instance (immediate) #2\n',
    '2022-12-01T14:41:51.735Z workers Started run worker instance (immediate) #3\n',
    '2022-12-01T14:41:51.735Z workers Started run worker instance (immediate) #4\n',
    '2022-12-01T14:41:51.735Z workers Started run worker instance (immediate) #5\n',
    '2022-12-01T14:41:51.735Z workers Started run worker instance (immediate) #6\n',
    '2022-12-01T14:41:51.735Z workers Started run worker instance (immediate) #7\n',
    '2022-12-01T14:42:15.017Z project Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):\n' +
      "Error: <homeDir>/git/x/apps/xxxxx-shared/src/test.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.\n" +
      '    at <homeDir>/git/x/node_modules/@ngtools/webpack/src/ivy/loader.js:59:26\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at runNextTicks (node:internal/process/task_queues:64:3)\n' +
      '    at process.processImmediate (node:internal/timers:442:9)\n' +
      '@ ./apps/xxxxx-shared/src/test.ts\n' +
      '    at t.<anonymous> (<homeDir>/Library/Caches/JetBrains/IntelliJIdea2022.1/wallaby/wallaby/server.js:23:11753)\n' +
      '    at r (<homeDir>/Library/Caches/JetBrains/IntelliJIdea2022.1/wallaby/wallaby/server.js:23:7980)\n' +
      '    at Object.next (<homeDir>/Library/Caches/JetBrains/IntelliJIdea2022.1/wallaby/wallaby/server.js:23:7275)\n' +
      '    at o (<homeDir>/Library/Caches/JetBrains/IntelliJIdea2022.1/wallaby/wallaby/server.js:23:7034)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n',
    '2022-12-01T14:42:15.018Z project Test run finished\n',
    '2022-12-01T14:42:15.018Z project Test run data re-queued\n'
  ]
}
```

**Comment by NikGovorov** [comment]
Could you please share `tsconfig.wallaby.spec.json`?

**Comment by NikGovorov** [comment]
The only way I can reproduce your issue is not having `apps/xxxxx-shared/src/test.ts` in `files` of `tsconfig.wallaby.spec.json`. Could you please check that it is there?

**Comment by LoreVdl** [comment]
This is the tsconfig.wallaby.spec.json file: 
`{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "types": ["jasmine", "node"]
  },
  "files": [
    "apps/francis-web/src/test.ts",
    "apps/francis-mobile/src/test.ts",
    "apps/francis-shared/test.ts",
    "polyfills.ts"
  ],
  "include": ["**/*.spec.ts", "**/*.mock.ts", "**/*.mock-impl.ts", "**/*.d.ts"],
  "exclude": ["apps/francis-web/e2e/**/*"]
}`

**Comment by NikGovorov** [comment]
Thanks for reporting the issue. It is fixed and the fix is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
