### ISSUE TITLE
Causes IndexOutOfBoundsException: Wrong line: 135. Available lines count:120 error in Webstorm.

### ISSUE THREAD

**Issue by denizoguz** [wallabyjs/public#3124]
### Issue description or question

Wallabyjs is causing problem notifications to be displayed frequently. Webstorm is recommending to disable the add-on. 

```
java.lang.IndexOutOfBoundsException: Wrong line: 135. Available lines count: 120
	at com.intellij.openapi.editor.impl.LineSet.checkLineIndex(LineSet.java:200)
	at com.intellij.openapi.editor.impl.LineSet.getLineStart(LineSet.java:181)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineStartOffset(DocumentImpl.java:1027)
	at com.wallaby.javascript.b.b(Unknown Source)
	at com.wallaby.javascript.WallabyController.a(Unknown Source)
	at com.wallaby.javascript.WallabyController.a(Unknown Source)
	at com.wallaby.javascript.v.selectionChanged(Unknown Source)
	at com.intellij.openapi.editor.impl.SelectionModelImpl.broadcastSelectionEvent(SelectionModelImpl.java:78)
	at com.intellij.openapi.editor.impl.SelectionModelImpl.fireSelectionChanged(SelectionModelImpl.java:72)
	at com.intellij.openapi.editor.impl.CaretImpl.lambda$doSetSelection$6(CaretImpl.java:1177)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:414)
	at com.intellij.openapi.editor.impl.CaretImpl.doSetSelection(CaretImpl.java:1087)
	at com.intellij.openapi.editor.impl.CaretImpl.setSelection(CaretImpl.java:1077)
	at com.intellij.openapi.editor.impl.CaretImpl.setSelection(CaretImpl.java:1069)
	at com.intellij.openapi.editor.impl.CaretImpl.setSelection(CaretImpl.java:1064)
	at com.intellij.openapi.editor.SelectionModel.setSelection(SelectionModel.java:169)
```

### Wallaby diagnostics report

```
editorVersion: 'WebStorm 2022.3',
  pluginVersion: '1.0.253',
  editorType: 'IntelliJ',
  osVersion: 'darwin 22.1.0',
  nodeVersion: 'v16.13.1',
  coreVersion: '1.0.1357',
```
Can't copy/paste the diagnostic report because it causes "Comment is too long" error. I can send it to you by mail if you want.

**Comment by smcenlly** [comment]
This has been fixed in the latest version of the Wallaby plugin for IntelliJ editors, `v1.0.255`.
