### ISSUE TITLE
Not seeing the green lighting on some files even though explicitly included

### ISSUE THREAD

**Issue by azaeng04-stitch** [wallabyjs/public#3135]
### Issue description or question

What could cause a file not to show the green hi-lighting in VSCode?
![Screenshot 2022-12-23 at 11 54 27](https://user-images.githubusercontent.com/106675683/209314473-9295d501-1c06-40ea-b18b-6ea33caf9653.png)
![Screenshot 2022-12-23 at 11 54 53](https://user-images.githubusercontent.com/106675683/209314506-06425244-3963-48b4-9546-e79341f1e812.png)

### Wallaby diagnostics report
```
{
  editorVersion: '1.74.1',
  pluginVersion: '1.0.348',
  editorType: 'VSCode',
  osVersion: 'darwin 22.2.0',
  nodeVersion: 'v18.12.1',
  coreVersion: '1.0.1363',
  checksum: 'NDg2ZGU1MzUyMTNiZTU2MDczN2MxZGUyOTEzNWM0NDIsMTcxMTY3MDQwMDAwMCww',
  config: {
    tests: [
      { pattern: '**/**/*.test.ts', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: 'node_modules/**/*.test.ts', ignore: true, trigger: true, load: true, test: true, file: false }
    ],
    files: [ { pattern: '**/**/**/*.test.ts', ignore: true, trigger: true, load: true, file: true }, { pattern: '**/**/**/*.ts', ignore: false, trigger: true, load: true, order: 1 } ],
    diagnostics: {
      vitest: {
        file: {
          config: "import tsConfigPaths from 'vite-tsconfig-paths';\n" +
            "import { defineConfig } from 'vitest/config';\n" +
            '\n' +
            'export default defineConfig({\n' +
            "    root: '.',\n" +
            '    plugins: [tsConfigPaths()],\n' +
            '    test: {\n' +
            '        globals: true,\n' +
            "        setupFiles: ['./__tests__/setup/mock-app-config.ts', './__tests__/setup/msw.ts'],\n" +
            "        include: ['./__tests__/**/*.test.{ts,tsx}'],\n" +
            "        environment: 'happy-dom',\n" +
            '        coverage: {\n' +
            "            exclude: ['**/__mocks__/**', '**/__tests__/**'],\n" +
            '        },\n' +
            '    },\n' +
            '});\n'
        },
        config: {
          allowOnly: true,
          watch: true,
          globals: true,
          environment: 'happy-dom',
          threads: true,
          clearMocks: false,
          restoreMocks: false,
          mockReset: false,
          include: [ './__tests__/**/*.test.{ts,tsx}' ],
          exclude: [ '**/node_modules/**', '**/dist/**', '**/cypress/**', '**/.{idea,git,cache,output,temp}/**' ],
          testTimeout: 5000,
          hookTimeout: 10000,
          isolate: true,
          watchExclude: [ '**/node_modules/**', '**/dist/**' ],
          forceRerunTriggers: [],
          update: false,
          reporters: [ 'default' ],
          silent: false,
          ui: false,
          uiBase: '/__vitest__/',
          open: true,
          coverage: {
            enabled: false,
            clean: true,
            cleanOnRerun: false,
            reportsDirectory: '<homeDir>/projects/stitch/src/Reuben/coverage',
            excludeNodeModules: true,
            exclude: [ '**/__mocks__/**', '**/__tests__/**' ],
            reporter: [ 'text', 'html' ],
            allowExternal: false,
            extension: [
              '.js',  '.cjs',
              '.mjs', '.ts',
              '.tsx', '.jsx',
              '.vue', '.svelte'
            ],
            tempDirectory: '<homeDir>/projects/stitch/src/Reuben/coverage/tmp'
          },
          fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
          setupFiles: [ '<homeDir>/projects/stitch/src/Reuben/__tests__/setup/mock-app-config.ts', '<homeDir>/projects/stitch/src/Reuben/__tests__/setup/msw.ts' ],
          defines: {},
          root: '<homeDir>/projects/stitch/src/Reuben',
          deps: { inline: [ {}, {}, {}, {}, {}, '@nuxt/test-utils' ] },
          snapshotOptions: { snapshotFormat: {}, updateSnapshot: 'new' },
          package: {
            version: '0.14.2',
            urls: { hooks: 'file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/runners/node/hooks.mjs' },
            paths: {
              root: '<homeDir>/projects/stitch/node_modules/.pnpm/vitest@0.14.2_c8@7.11.3+happy-dom@5.2.0/node_modules/vitest',
              dist: '<homeDir>/projects/stitch/node_modules/.pnpm/vitest@0.14.2_c8@7.11.3+happy-dom@5.2.0/node_modules/vitest/dist'
            }
          }
        }
      }
    },
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0', autoDetected: true },
    preserveComments: false,
    extractComments: true,
    workers: { initial: 1, regular: 1, recycle: false },
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: {
      type: 'node',
      params: { runner: '--experimental-loader=file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/runners/node/hooks.mjs' },
      runner: '<homeDir>/.nvm/versions/node/v18.12.1/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: true,
    symlinkNodeModules: undefined,
    configCode: 'module.exports = () => ({\n' +
      '    autoDetect: true,\n' +
      "    tests: ['**/**/*.test.ts', '!./node_modules/**/*.test.ts'],\n" +
      "    files: [{ pattern: '**/**/**/*.test.ts', ignore: true }, '**/**/**/*.ts'],\n" +
      '});\n'
  },
  packageJSON: {
    dependencies: {
      '@algolia/client-search': '>=4.9.1 <5.0.0',
      '@datadog/browser-rum': '^4.17.2',
      '@next/bundle-analyzer': '^12.1.6',
      '@shared/capitec-pay': 'workspace:^0.0.0',
      '@shared/dd-tracer': 'workspace:^0.0.0',
      '@shared/domain-types': 'workspace:^0.0.0',
      '@shared/feature-flags': 'workspace:^0.0.0',
      '@shared/graphql-id': 'workspace:^0.0.0',
      '@shared/logging': 'workspace:^0.0.0',
      '@shared/operations-api-client': 'workspace:^0.0.0',
      '@shared/operations-relay-types': 'workspace:^0.0.0',
      '@shared/payouts-protocol': 'workspace:^0.0.0',
      '@shared/puppetmaster-protocol': 'workspace:^0.0.0',
      '@shared/serialization': 'workspace:^0.0.0',
      '@types/node-fetch': '^2.6.2',
      '@xstate/inspect': '^0.5.0',
      '@xstate/react': '^1.6.3',
      'aggregate-error': '^4.0.1',
      clsx: '^1.1.1',
      color2k: '^1.2.5',
      decoders: '^2.0.1',
      graphql: '^15.8.0',
      'graphql-request': '^3.5.0',
      jsonwebtoken: '^8.5.1',
      'jwks-rsa': '^2.0.4',
      'libphonenumber-js': '^1.10.14',
      lodash: '^4.17.21',
      'lottie-react': '^2.2.1',
      luxon: '^2.3.1',
      next: '^12.2.2',
      react: '17.0.2',
      'react-dom': '17.0.2',
      'react-error-boundary': '^3.1.4',
      'react-hook-form': '^7.33.1',
      'short-unique-id': '^4.4.4',
      'ts-toolbelt': '^9.6.0',
      'unix-dgram': '^2.0.4',
      webpack: '>=4.0.0 <5.0.0 || >=5.0.0 <6.0.0',
      winston: '^3.8.1',
      'winston-transport': '^4.5.0',
      ws: '^7.3.1',
      xstate: '4.29.0'
    },
    devDependencies: {
      '@datadog/datadog-ci': '^0.17.12',
      '@rollup/plugin-typescript': '^8.2.5',
      '@types/jsonwebtoken': '8.5.9',
      '@types/lodash': '^4.14.182',
      '@types/luxon': '^2.3.0',
      '@types/node': '^18.11.9',
      '@types/react': '^17',
      '@types/tailwindcss': '^2.2.1',
      '@types/uuid': '^8.3.1',
      autoprefixer: '^10.4.7',
      c8: '^7.11.3',
      'cross-fetch': '^3.1.5',
      eslint: '8.19.0',
      'eslint-config-next': '12.1.6',
      'happy-dom': '^5.2.0',
      'http-server': '^0.12.3',
      msw: '^0.49.0',
      'node-mocks-http': '^1.11.0',
      postcss: '^8.4.14',
      'postcss-preset-env': '^7.3.1',
      rollup: '^2.56.3',
      'rollup-plugin-terser': '^7.0.2',
      tailwindcss: '^3.0.24',
      tslib: '2.3.1',
      typescript: '^4.9.3',
      vite: '^2.6.4',
      'vite-tsconfig-paths': '^3.5.0',
      vitest: '^0.14.2'
    }
  },
  fs: { numberOfFiles: 14703 },
  debug: [
    '2022-12-23T09:51:26.395Z config Attempting automatic configuration for angular\n',
    '2022-12-23T09:51:26.396Z angular/cli config Angular CLI not found.\n',
    '2022-12-23T09:51:26.396Z config Finished attempting automatic configuration for angular (2ms)\n',
    '2022-12-23T09:51:26.397Z config Attempting automatic configuration for jest\n',
    "2022-12-23T09:51:26.398Z jest/config Error: Module jest-cli is not found in '<homeDir>/projects/stitch/src/Reuben'.\n" +
      '    at Object.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:31:25202)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:31:8268)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:31:7563)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:31:7472\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at s (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:31:7266)\n' +
      '    at Object.loadJest (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:31:22800)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:19:22845\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:19:27578)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:19:26873)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:19:26782\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at s (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:19:26576)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:19:22533)\n' +
      '    at Object.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:19:26253)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:19:27578)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:19:26873)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:19:26782\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at s (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:19:26576)\n' +
      '    at Object.n [as configure] (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:19:26134)\n' +
      '    at Config.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:15:20840)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:15:12061)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:15:11356)\n' +
      '    at o (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallabyc27856/server.js:15:11105)\n',
    '2022-12-23T09:51:26.398Z config Finished attempting automatic configuration for jest (1ms)\n',
    '2022-12-23T09:51:26.398Z config Attempting automatic configuration for vitest\n',
    '2022-12-23T09:51:26.401Z vitest/config Detected Vitest (0.14.2).\n',
    '2022-12-23T09:51:26.765Z config Finished attempting automatic configuration for vitest (366ms)\n',
    '2022-12-23T09:51:26.766Z project Wallaby Node version: v18.12.1\n',
    '2022-12-23T09:51:26.766Z project Wallaby config: <homeDir>/projects/stitch/src/Reuben/wallaby.js\n',
    '2022-12-23T09:51:26.805Z fs File system starting\n',
    '2022-12-23T09:51:27.221Z fs File system scan completed\n',
    '2022-12-23T09:51:27.231Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/projects/7f71207b04490716\n',
    '2022-12-23T09:51:27.263Z uiService Listening port 51235\n',
    '2022-12-23T09:51:27.338Z workers Parallelism for initial run: 1, for regular run: 1\n',
    '2022-12-23T09:51:27.338Z workers Starting run worker instance #0\n',
    '2022-12-23T09:51:27.339Z workers Web server is listening at 50045\n',
    '2022-12-23T09:51:27.339Z project Stopping process pool\n',
    '2022-12-23T09:51:27.339Z project File cache is up-to-date, starting full test run\n',
    '2022-12-23T09:51:27.345Z project Test run started; run priority: 3\n',
    '2022-12-23T09:51:27.348Z project Running all tests\n',
    '2022-12-23T09:51:27.359Z project Test task priority upgraded to full run\n',
    '2022-12-23T09:51:27.360Z workers Starting test run, priority: 3\n',
    '2022-12-23T09:51:27.360Z nodeRunner Starting sandbox [worker #0, session #si7fy]\n',
    '2022-12-23T09:51:27.360Z nodeRunner Preparing sandbox [worker #0, session #si7fy]\n',
    '2022-12-23T09:51:27.465Z workers Started run worker instance (delayed) #0\n',
    '2022-12-23T09:51:27.466Z nodeRunner Prepared sandbox [worker #0, session #si7fy]\n',
    '2022-12-23T09:51:27.466Z workers [worker #0, session #si7fy] Running tests in sandbox\n',
    '2022-12-23T09:51:27.545Z project Test run is not cancelled because cancel requester does not have enough priority to cancel the run\n',
    '2022-12-23T09:51:27.545Z project Test run is not cancelled because cancel requester does not have enough priority to cancel the run\n',

**Comment by smcenlly** [comment]
Generally speaking, a file won't have indicators if Wallaby did not process it. For `vitest` and `jest` projects, this may be a result of none of your tests executing that file. 

Your `files` pattern from your config file looks a little suspicious and may be causing problems:

```
...
  files: [
    { pattern: '**/**/**/*.test.ts', ignore: true }, 
    '**/**/**/*.ts'
  ]
...
```

Could you please try changing `**/**/**/*.ts` to `**/*.ts`?

I'm wondering what was the reason for overriding the `files` and `tests` configuration instead of using the default provided by our `vitest` integration? You have a large number of files in your project `14,703` and I suspect you need to update the files and tests patterns to ignore all node_modules (unless you want to run tests from there).

From your screenshots, I can see that you have code-coverage indicated in your `.test.ts` file but not in your code file. Do you have coverage indicators in any of your code files (not `.test.ts` files)?

You're also running an older version of `vitest`, it may be worth upgrading that also to try and fix your problem.

If you're still having issues, could you please create a cut-down sample repo that has the same problem?

**Comment by azaeng04-stitch** [comment]
Thank you @smcenlly for your response.

I checked if the file was being processed in the diagnostics above and it does show that they are being processed.
I am noticing other files also not showing the hilighting.
If the file isn't being executed it usually shows the white block instead of green, red or orange.

I did the smart setup as well and I am getting the same result.
Could it be my vitest configuration file?

**Comment by azaeng04-stitch** [comment]
@smcenlly I also noticed that there are not code coverage indicators in the other files under `pages`. This is a monorepo and I have wallaby running in just the one app.

**Comment by azaeng04-stitch** [comment]
@smcenlly I realized why it wasn't showing the green indicators. When a function in the given file is being mocked then it doesn't seem to show the indicators. Isn't that a bug?

**Comment by smcenlly** [comment]
@azaeng04-stitch - I am not sure that understand your question entirely but if you mock a function and call it from a test, then the file containing that function won't show indicators because that code never executed.

If that's not what you're asking, could you please provide a code example of your test, function, and the coverage indicators you are seeing (or not seeing)?

**Comment by smcenlly** [comment]
Assuming that my last comment clarified why this wasn't working for you and that the behavior is expected. If not, please reply and we'll re-open the issue.

**Comment by azaeng04-stitch** [comment]
I see @smcenlly that makes sense so then it won't show indicators if the function is being mocked because it is not being called. All good then thank you. You can keep this ticket closed.

**Comment by azaeng04-stitch** [comment]
Just out of curiosity. Shouldn't wallaby be showing the white indicators if the code has not been executed?

**Comment by smcenlly** [comment]
For `jest`, Wallaby will process your files to determine coverage indicators as they're executed. If your file never executes (because it's mocked) then it will never have coverage indicators calculated.

The behavior actually differs a little depending on your test runner. For more recent test runners (e.g. `jest`, `vitest`), coverage is calculated on demand as files are executed. For older test runners that are not as smart in their execution, coverage indicators are calculated before the test run starts (this can be a lot slower for larger projects).
