### ISSUE TITLE
Node: pg.Pool.connect() hangs

### ISSUE THREAD

**Issue by tslocke** [wallabyjs/public#3139]
I'm having a problem with `pool.connect` not completing...

```
  const pool = new pg.Pool({connectionString: process.env.DATABASE_URL})
  await pool.connect()
```

...and discovered that it works fine outside Wallaby. I am sure stuff about where to correctly connect to pg has come up before but couldn't find it. I think maybe the db pool should be created in my wallaby setup function? Any advice? Thanks.

**Comment by tslocke** [comment]
Update: I'm trying to test this in the context of the setup function, but I can't require `pg`. From the docs I thought this was supported and would pick up the stuff in my package.json but:

```js
  setup: function() {
    const pg = require('pg')
    const pool = new pg.Pool({connectionString: process.env.DATABASE_URL})
    console.log(pool)
    const f = async () => {
      await pool.connect()
      console.log('done')
    }
    return f()
  }
  // Cannot find module 'pg'
```

Diagnostics:

```
{
  editorVersion: '1.73.0',
  pluginVersion: '1.0.348',
  editorType: 'VSCode',
  osVersion: 'darwin 22.2.0',
  nodeVersion: 'v16.15.1',
  coreVersion: '1.0.1363',
  checksum: 'MDY1YTZlY2QyZTAzNjNiNDliMmViMDE1ODI2MDE1NjMsMTY4MjcyNjQwMDAwMCww',
  config: {
    workers: { initial: 1, regular: 1, restart: true, recycle: true },
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/private/var/folders/1g/4ply6jh94jjfg90j5ts90n_w0000gn/T/jest_dx',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/Projects/Inio/inio/api',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: undefined,
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              extraGlobals: [],
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: false, throwOnModuleCollision: false },
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [ 'js', 'jsx', 'ts', 'tsx', 'json', 'node' ],
              moduleLoader: undefined,
              moduleNameMapper: [ [ '@/(.*)', [ '<homeDir>/Projects/Inio/inio/api/src/$1' ] ] ],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              name: '37063767abf0dcc1ce90c1d152b9136f',
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/Projects/Inio/inio/api',
              roots: [ '<homeDir>/Projects/Inio/inio/api' ],
              runner: '<homeDir>/Projects/Inio/inio/api/node_modules/jest-runner/build/index.js',
              setupFiles: [],
              setupFilesAfterEnv: [ '<homeDir>/Projects/Inio/inio/api/tests/setup.ts' ],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/Projects/Inio/inio/api/node_modules/jest-environment-node/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [ '(/tests/.*\\.(test|spec))\\.(jsx?|tsx?)$' ],
              testRunner: '<homeDir>/Projects/Inio/inio/api/node_modules/jest-circus/runner.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [ [ '^.+\\.tsx?$', '<homeDir>/Projects/Inio/inio/api/node_modules/ts-jest/dist/index.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: [],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<homeDir>/Projects/Inio/inio/api/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 7,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/Projects/Inio/inio/api',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: undefined,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/Projects/Inio/inio/api/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/1g/4ply6jh94jjfg90j5ts90n_w0000gn/T/jest_dx', '\\./coverage' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/1g/4ply6jh94jjfg90j5ts90n_w0000gn/T/jest_dx', '\\./coverage' ],
            testMatch: [],
            testRegex: [ '(/tests/.*\\.(test|spec))\\.(jsx?|tsx?)$' ]
          }
        }
      }
    },
    filesWithCoverageCalculated: [],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    dot: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, file: true, test: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        file: true,
        test: true
      },
      {
        pattern: '/private/var/folders/1g/4ply6jh94jjfg90j5ts90n_w0000gn/T/jest_dx',
        regexp: /\/private\/var\/folders\/1g\/4ply6jh94jjfg90j5ts90n_w0000gn\/T\/jest_dx/,
        ignore: true,
        trigger: true,
        load: true,
        file: true,
        test: true
      },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '(/tests/.*\\.(test|spec))\\.(jsx?|tsx?)$', regexp: /(\/tests\/.*\.(test|spec))\.(jsx?|tsx?)$/, ignore: true, trigger: true, load: true, file: true }
    ],
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true, file: false },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true,
        file: false
      },
      {
        pattern: '/private/var/folders/1g/4ply6jh94jjfg90j5ts90n_w0000gn/T/jest_dx',
        regexp: /\/private\/var\/folders\/1g\/4ply6jh94jjfg90j5ts90n_w0000gn\/T\/jest_dx/,
        ignore: true,
        trigger: true,
        load: true,
        test: true,
        file: false
      },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '(/tests/.*\\.(test|spec))\\.(jsx?|tsx?)$', regexp: /(\/tests\/.*\.(test|spec))\.(jsx?|tsx?)$/, ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: {
      type: 'node',
      params: {},
      runner: '<homeDir>/.fnm/node-versions/v16.15.1/installation/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: false,
    configCode: 'module.exports = () => ({\n' +
      '  autoDetect: true,\n' +
      '  workers: {\n' +
      '    initial: 1,\n' +
      '    regular: 1,\n' +
      '    restart: true,\n' +
      '  },\n' +
      '\n' +
      '  setup: function() {\n' +
      "    const pg = require('pg')\n" +
      '    const pool = new pg.Pool({connectionString: process.env.DATABASE_URL})\n' +
      '    console.log(pool)\n' +
      '    const f = async () => {\n' +
      '      await pool.connect()\n' +
      "      console.log('done')\n" +
      '    }\n' +
      '    return f()\n' +
      '  }\n' +
      '});\n'
  },
  packageJSON: {
    dependencies: {
      '@aws-sdk/client-s3': '^3.141.0',
      '@aws-sdk/s3-request-presigner': '^3.141.0',
      '@fastify/accepts': '^4.1.0',
      '@fastify/auth': '^4.2.0',
      '@fastify/autoload': '^5.6.0',
      '@fastify/cors': '^8.2.0',
      '@fastify/formbody': '^7.4.0',
      '@fastify/secure-session': '^4.1.1',
      '@fastify/sensible': '^5.2.0',
      '@fastify/static': '^6.6.0',
      '@prisma/client': '^4.1',
      bcrypt: '^5.0.1',
      debug: '^4.3.3',
      dotenv: '^10.0.0',
      ejs: '^3.1.6',
      fastify: '^4.10.2',
      'fastify-sentry': '^1.4.0',
      'fastify-zod': '^1.2.0',
      inflection: '^1.13.2',
      nanoid: '^3.3.4',
      nodemailer: '^6.7.2',
      pg: '>=8.8.0',
      'pg-mem': '>=2.5.0',
      'point-of-view': '^4.16.0',
      prisma: '^4.1',
      pusher: '^5.0.1',
      ramda: '^0.27.1',
      replicache: '>=12.0.1',
      'replicache-transaction': '^0.2.1',
      ws: '^8.8.1',
      zod: '>=3.17.3'
    },
    devDependencies: {
      '@tailwindcss/forms': '^0.4.0',
      '@tailwindcss/typography': '^0.5.0',
      '@types/bcrypt': '^5.0.0',
      '@types/chai': '^4.3.0',
      '@types/debug': '^4.1.7',
      '@types/ejs': '^3.1.0',
      '@types/express': '^4.17.13',
      '@types/inflection': '^1.13.0',
      '@types/jest': '^27.4.1',
      '@types/mocha': '^9.1.0',
      '@types/node': '^16.10.2',
      '@types/nodemailer': '^6.4.4',
      '@types/pg': '^8.6.6',
      '@types/ramda': '^0.27.61',
      '@types/ws': '^8.5.3',
      chai: '^4.3.6',
      eslint: '^8.2.0',
      jest: '^27.5.1',
      mocha: '^9.2.1',
      'pino-pretty': '^7.3.0',
      prettier: '^2.2.1',
      'tailwindcss-cli': '^0.1.2',
      'ts-jest': '^27.1.2',
      'ts-node': '^10.7.0',
      'ts-node-dev': '^2.0.0',
      'tsconfig-paths': '^3.12.0',
      'type-fest': '^2.12.1',
      typescript: '4.7.4'
    }
  },
  fs: { numberOfFiles: 143 },
  debug: [
    '2023-01-02T11:22:36.526Z config Attempting automatic configuration for angular\n',
    '2023-01-02T11:22:36.528Z angular/cli config Angular CLI not found.\n',
    '2023-01-02T11:22:36.528Z config Finished attempting automatic configuration for angular (2ms)\n',
    '2023-01-02T11:22:36.528Z config Attempting automatic configuration for jest\n',
    '2023-01-02T11:22:36.585Z jest/config Detected Jest.\n',
    '2023-01-02T11:22:36.585Z jest/config Configured Jest.\n',
    '2023-01-02T11:22:36.585Z config Finished attempting automatic configuration for jest (57ms)\n',
    '2023-01-02T11:22:36.586Z project Wallaby Node version: v16.15.1\n',
    '2023-01-02T11:22:36.586Z project Wallaby config: <homeDir>/Projects/Inio/inio/api/wallaby.js\n',
    '2023-01-02T11:22:36.592Z fs File system starting\n',
    '2023-01-02T11:22:36.613Z fs File system scan completed\n',
    '2023-01-02T11:22:36.616Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/projects/b5ece163a3f6e316\n',
    '2023-01-02T11:22:36.654Z uiService Listening port 51235\n',
    '2023-01-02T11:22:36.671Z project Config file change detected, invalidating local cache\n',
    '2023-01-02T11:22:36.679Z workers Parallelism for initial run: 1, for regular run: 1\n',
    '2023-01-02T11:22:36.679Z workers Starting run worker instance #0\n',
    '2023-01-02T11:22:36.679Z workers Web server is listening at 64611\n',
    '2023-01-02T11:22:36.679Z project File cache requires some updates, waiting required files from IDE\n',
    '2023-01-02T11:22:36.705Z project Stopping process pool\n',
    '2023-01-02T11:22:36.706Z project Test run started; run priority: 3\n',
    '2023-01-02T11:22:36.707Z project Running all tests\n',
    '2023-01-02T11:22:36.708Z workers Starting test run, priority: 3\n',
    '2023-01-02T11:22:36.708Z nodeRunner Starting sandbox [worker #0, session #rw2jh]\n',
    '2023-01-02T11:22:36.709Z nodeRunner Preparing sandbox [worker #0, session #rw2jh]\n',
    '2023-01-02T11:22:36.782Z workers Started run worker instance (delayed) #0\n',
    '2023-01-02T11:22:36.782Z nodeRunner Prepared sandbox [worker #0, session #rw2jh]\n',
    '2023-01-02T11:22:36.782Z workers [worker #0, session #rw2jh] Running tests in sandbox\n',
    "2023-01-02T11:22:36.786Z workers Sandbox (active) [rw2jh] error: Cannot find module 'pg'\n" +
      'Require stack:\n' +
      '- [wallaby core]/runners/node/bootstrap.js\n' +
      '- [wallaby core]/server.js\n' +
      '    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)\n' +
      '    at Function.Module._load (node:internal/modules/cjs/loader:778:27)\n' +
      '    at Module.require (node:internal/modules/cjs/loader:1005:19)\n' +
      '    at require (node:internal/modules/cjs/helpers:102:18)\n' +
      '    at WebSocket.emit (node:events:527:28)\n' +
      '    at afterWrite (node:internal/streams/writable:497:5)\n' +
      '    at onwrite (node:internal/streams/writable:477:7)\n' +
      '    at Zlib.cb (node:internal/streams/transform:202:7)\n' +
      '    at Zlib.processCallback (node:zlib:611:8)\n',
    '2023-01-02T11:22:36.887Z workers [rw2jh] Run 0 test(s), skipped 0 test(s)\n',
    '2023-01-02T11:22:36.889Z workers [rw2jh] Sandbox is responsive, closing it\n',
    '2023-01-02T11:22:36.889Z workers Recyling run worker instance #0\n',
    '2023-01-02T11:22:36.889Z workers Starting run worker instance #0\n',
    "2023-01-02T11:22:36.890Z workers Failed to map the stack to user code, entry message: Cannot find module 'pg'\n" +
      'Require stack:\n' +
      '- <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby0e9230/runners/node/bootstrap.js\n' +
      "- <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby0e9230/server.js, stack: Error: Cannot find module 'pg'\n" +
      'Require stack:\n' +
      '- <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby0e9230/runners/node/bootstrap.js\n' +
      '- <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby0e9230/server.js\n' +
      '    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)\n' +
      '    at Function.Module._load (node:internal/modules/cjs/loader:778:27)\n' +
      '    at Module.require (node:internal/modules/cjs/loader:1005:19)\n' +
      '    at Module.r.require (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby0e9230/server.js:31:18958)\n' +
      '    at Module.r.require (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby0e9230/server.js:31:18958)\n' +
      '    at require (node:internal/modules/cjs/helpers:102:18)\n' +
      '    at eval (eval at module.exports (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby0e9230/runners/node/bootstrap.js:14:44), <anonymous>:2:16)\n' +
      '    at eval (eval at module.exports (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.34\n',
    '2023-01-02T11:22:36.890Z project Test run finished\n',
    '2023-01-02T11:22:36.891Z project Processed console.log entries\n',
    '2023-01-02T11:22:36.891Z project Processed loading sequences\n',
    '2023-01-02T11:22:36.891Z project Processed executed tests\n',
    '2023-01-02T11:22:36.891Z project Processed code coverage\n',
    '2023-01-02T11:22:36.895Z project Test run result processed and sent to IDE\n',
    '2023-01-02T11:22:36.996Z workers Started run worker instance (delayed) #0\n'
  ]
}
```

**Comment by smcenlly** [comment]
You mentioned that this was working outside of Wallaby, can you describe where you're initializing Postgres? If you can (and you should be able to), I'd try configure Wallaby and Jest to run the same way instead of using Wallaby's global setup function.

Since you're using Jest, you should be able to use a [Jest async `globalSetup` function](https://jestjs.io/docs/configuration/#globalsetup-string) to initialize Postgres and Wallaby should work with that. If you use the setup function, you need to control concurrency and ensure that setup is only executed once. You may also need to implement a teardown function to ensure everything is cleaned up afterwards.

> I'm trying to test this in the context of the setup function, but I can't require pg. From the docs I thought this was supported

It should be working for you. I'm not sure why it's not but we'll investigate.

**Comment by tslocke** [comment]
To add a bit more information, I seem to have the problem irrespective of test setup issues. The app is set up to connect to the pool right away as soon as the relevant module loads. I put some trace code before/after `pool.connect()` and if I restart Wallaby, I see the before in the Wallaby console output, but not the after.

If I start the app up normally, just using Node (this is a backend project), I see both the before and after.

Does this shed any more light? Any suggestions for how to further debug the issue? 

Thanks v much

**Comment by smcenlly** [comment]
Sorry, I'm not really sure what you're trying to say... are you able to provide a code sample or a sample repo that has the problem?

**Comment by smcenlly** [comment]
@tslocke - are you able to provide us with a code sample or a sample repo so we can understand your project configuration and see the problem?

**Comment by tslocke** [comment]
Sorry, yes - I’ll get on that.

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. If you still need help, please provide a code sample or a sample repo so we can understand your project configuration and see the problem. We can then re-open the issue.
