### ISSUE TITLE
Sequelize / Node Error

### ISSUE THREAD

**Issue by daw451-duplicate** [wallabyjs/public#314]
has anyone seen these errors with sequelize and wallaby?

console.error: (node) warning: possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit.

console.error: Trace
    at process.addListener (events.js:239:17)
    at ConnectionManager (E:\ScriptSureV2\ScriptSure 10\trunk\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:43:11)
    at new ConnectionManager (E:\ScriptSureV2\ScriptSure 10\trunk\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:10:29)
    at new MysqlDialect (E:\ScriptSureV2\ScriptSure 10\trunk\node_modules\sequelize\lib\dialects\mysql\index.js:12:28)
    at new Sequelize (E:\ScriptSureV2\ScriptSure 10\trunk\node_modules\sequelize\lib\sequelize.js:203:20)
    at Object.<anonymous> (C:\Users\aaron\.WebStorm10\system\wallaby\projects\b64252923298e1e5\instrumented\models\index.js:10:31)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at Module.s.require (C:\Users\aaron\.WebStorm10\system\wallaby\wallaby\server.js:18:6887)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\aaron\.WebStorm10\system\wallaby\projects\b64252923298e1e5\instrumented\routes\v1.0\user.js:7:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

**Comment by ArtemGovorov** [comment]
This is most likely [node process re-using issue](http://wallabyjs.com/docs/intro/troubleshooting.html#transient-issues-when-running-node-js-tests). Try setting workers count to 1 and recycle node processes:
``` JavaScript
module.exports = function () {
  return {
    files: [
      'lib/*.js'
    ],

    tests: [
      'test/*Spec.js'
    ],

    env: {
      type: 'node'
    },

    workers: {
      recycle: true, 
      initial: 1,
      regular: 1
    }
  };
};
```
