### ISSUE TITLE
VItest +  Webstorm issue

### ISSUE THREAD

**Issue by AurelienWebnation** [wallabyjs/public#3145]
Hi!

I tried to use Wallaby.js with my webstorm ide + vitest.
I'm using nvm to manage my node versions.

Vite version: `4.0.0`

The error I get :
>Automatic Jest configuration error: Module jest-cli is not found in '.'.
>
>We've also tried to automatically configure Wallaby.js for other frameworks
Automatic Vitest configuration error: Error: spawnSync node ENOENT

This is what I did:

1.  Edit a configuration in webstorm settings with:
     - Configuration type: Automatic
     - Root path: path to my project folder (default)
     - Node.js: path to node.js executable (/home/aurelien/.nvm/versions/node/v16.12.0/bin/node), I tried with node v19/18/16
2. Downgrade vitest from  `0.27.0` to `0.14.0`
3. Trying installing vite-cli
4. Trying installing jest-cli

My actual package.json:
```json
{
  "name": "vitest",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "@testing-library/dom": "^8.19.0",
    "@testing-library/jest-dom": "^5.16.5",
    "jsdom": "^20.0.3",
    "vite": "^4.0.0",
    "vitest": "^0.27.0"
  }
}
```

**Comment by smcenlly** [comment]
Could you please provide your Wallaby Diagnostics Report. The repot is a simple JSON text report that contains some basic information about your Wallaby config and project that is required to start troubleshooting most of Wallaby issues.

To share the report:

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- run `Copy Diagnostics Report` command:
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

If the report is not being generated, can you please provide us with the output of your `Wallaby Console` in Wallaby's run output window.

**Comment by AurelienWebnation** [comment]
@smcenlly I can't get a Diagnostics Report !
Wallaby don't pass any test.
I have an error directly when I launch it.
![image](https://i.imgur.com/8qPEtoF.png)

**Comment by smcenlly** [comment]
There have been a number of changes to vitest latest versions that have broken Wallaby's integration.

We have found and fixed some additional problems today with the latest version of vites.

Can you please update to Wallaby core v1.0.1369 and let us know if you're still having problems. Wallaby should update automatically for you, but if it does not, you may [force a core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

If you are still having problems, can you please provide us with the output of your `Wallaby Console` in Wallaby's run output window (the tab in your screenshot with the purple console icon).

**Comment by AurelienWebnation** [comment]
Webstorm updated wallaby core to the last `v1.0.1369` but I still have the same error.
Here is a screen of the `Wallaby Console` :
![image](https://i.imgur.com/PM83Tqi.png)

**Comment by smcenlly** [comment]
We have a similar issue for `vitest` (https://github.com/wallabyjs/public/issues/3146) where they were using `pnpm`. It looks like you're also using `pnpm`.

Wallaby needs to patch `vite-node`, which as of `vitest@0.26.x` is now a peer dependency and is not being resolved when modules are installed using `pnpm`.

Please install vite-node as a project dependency and let us know if that fixes your problem.

**Comment by briangwaltney** [comment]
I just updated my mac to Ventura 13.1 and this problem started for me. It was working fine before the update. I was using vitest 27.1 without vite-node and had no problems. After updating to Ventura 13.1, it stopped working. vite-node did not help and neither did downgrading vitest. I tried 26.x and 25.x.

Best I can tell, it has something to do with the Mac update. 

After a second restart after the update, the error went away and Wallaby is working as expected. YMMV

**Comment by smcenlly** [comment]
@briangwaltney - thanks for sharing!

**Comment by AurelienWebnation** [comment]
I installed `vite-node` but I get the same error.

`package.json` :
```json
{
  "name": "vitest",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "test": "vitest"
  },
  "devDependencies": {
    "@testing-library/dom": "^8.20.0",
    "@testing-library/jest-dom": "^5.16.5",
    "jsdom": "^20.0.3",
    "vite": "^4.0.4",
    "vitest": "^0.27.2"
  },
  "dependencies": {
    "vite-node": "^0.27.2"
  }
}
```
Wallaby core : `v1.0.1371`

![image](https://i.imgur.com/rBO5WOJ.png)

The simple test i'm trying to pass:
```js
describe('Math test suite', () => {
  it('should return true', () => {
    expect(true).toBe(true);
  })
})
```

**Comment by AurelienWebnation** [comment]
Hey! Thanks for your help.
So I created a `wallaby.js` at the root path with your configuration, but I still have an error (with commonjs and esm) :

```
wallaby.js started
core v1.0.1371
Failed to load configuration file: 
We have tried both CommonJs require and ESM import to load the config, you may find errors for each attempt below.
-----------------------------
CommonJs config loading error
-----------------------------
Error [ERR_REQUIRE_ESM]: require() of ES Module ./wallaby.js from [wallaby core]/server.js not supported.
wallaby.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename wallaby.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in ./package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

------------------------------
ES module config loading error
------------------------------
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and './package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file://./wallaby.js:1:1
Please refer to our docs: https://wallabyjs.com/docs/config/overview.html 
```

I push this test project to a fresh repository: https://github.com/AurelienWebnation/vItest-webstorm-issue-3145

**Comment by smcenlly** [comment]
If you rename `wallaby.js` to `wallaby.cjs`, it should allow you to start Wallaby.

**Comment by smcenlly** [comment]
Can you also please try deleting and reinstalling your node modules? Your project worked for me, so I'm wondering if there's a dependency issue (or something similar).

**Comment by AurelienWebnation** [comment]
Hey!
The project worked for you? That's very strange..
So I just deleting and reinstalling my node modules + rename `wallaby.js` to `wallaby.cjs`.

That's the error I get now from the wallaby console:

>wallaby.js started
core v1.0.1372
2023-01-20T07:16:26.749Z config Attempting automatic configuration for angular
2023-01-20T07:16:26.751Z angular/cli config Detecting Angular CLI.
2023-01-20T07:16:26.754Z angular/cli config Angular CLI not found.
2023-01-20T07:16:26.754Z config Finished attempting automatic configuration for angular (6ms)
2023-01-20T07:16:26.755Z config Attempting automatic configuration for jest
2023-01-20T07:16:26.756Z jest/config Detecting Jest.
2023-01-20T07:16:26.760Z jest/config Error: Module jest-cli is not found in '/home/aurelien/lab/test/vitest'.
    at Object.<anonymous> (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:31:25202)
    at r (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:31:8268)
    at Object.next (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:31:7563)
    at /home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:31:7472
    at new Promise (<anonymous>)
    at s (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:31:7266)
    at Object.loadJest (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:31:22800)
    at /home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:22872
    at r (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:27605)
    at Object.next (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:26900)
    at /home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:26809
    at new Promise (<anonymous>)
    at s (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:26603)
    at r (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:22560)
    at Object.<anonymous> (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:26280)
    at r (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:27605)
    at Object.next (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:26900)
    at /home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:26809
    at new Promise (<anonymous>)
    at s (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:26603)
    at Object.n [as configure] (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:26161)
    at Config.<anonymous> (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:15:20840)
    at r (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:15:12061)
    at Object.next (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:15:11356)
    at o (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:15:11105)
2023-01-20T07:16:26.760Z config Finished attempting automatic configuration for jest (5ms)
2023-01-20T07:16:26.760Z config Attempting automatic configuration for vitest
2023-01-20T07:16:26.762Z vitest/config Detecting Vitest.
2023-01-20T07:16:26.766Z vitest/config Detected Vitest (0.27.2).
2023-01-20T07:16:26.773Z vitest/config Error: Error: spawnSync node ENOENT
    at Object.<anonymous> (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:30272)
    at r (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:20:746)
    at Object.next (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:20:41)
    at /home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:31962
    at new Promise (<anonymous>)
    at n (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:31756)
    at Object.r [as configure] (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:28896)
    at Config.<anonymous> (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:15:20840)
    at r (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:15:12061)
    at Object.next (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:15:11356)
    at o (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:15:11105)
2023-01-20T07:16:26.773Z config Finished attempting automatic configuration for vitest (13ms)
Failed to load configuration file: Automatic Jest configuration error: Module jest-cli is not found in '.'.

>We've also tried to automatically configure Wallaby.js for other frameworks
Automatic Vitest configuration error: Error: spawnSync node ENOENT
Please refer to our docs: https://wallabyjs.com/docs/config/overview.html

**Comment by smcenlly** [comment]
Can you please let us know what version of node you are using?

Could you also please try explicitly setting your node version in your Wallaby `Run Configuration` instead of `{SYSTEM DEFAULT}` and then try starting Wallaby again?

**Comment by AurelienWebnation** [comment]
Like I said, I tried with node Node.js: path to node.js executable (/home/aurelien/.nvm/versions/node/v16.12.0/bin/node), I tried with node v16.12.0 / v18.13.0 / v19.4.0.
So I already explicitly setting my node version in my Wallaby Run Configuration instead of {SYSTEM DEFAULT}.
![image](https://i.imgur.com/Lnxs2tA.png)

**Comment by smcenlly** [comment]
> Like I said, I tried with node v16.12.0 / v18.13.0 / v19.4.0.

Sorry, I forget you said this in your initial response.

---

One thing I just noticed is that your project folder is called `vitest`.

Normally `npm` complains if you have a project folder with the same name as a dependency. Can you please try cloning your repo to a fresh directory with:

```
git clone https://github.com/AurelienWebnation/vItest-webstorm-issue-3145
```

and then try reinstalling dependencies and see if it works?

**Comment by AurelienWebnation** [comment]
I cloned the repo into a new fresh folder called `vItest-webstorm-issue-3145`.
But I have the same error...
```
wallaby.js started
core v1.0.1373
2023-01-23T14:05:54.888Z config Attempting automatic configuration for angular
2023-01-23T14:05:54.889Z angular/cli config Detecting Angular CLI.
Failed to load configuration file: Automatic Jest configuration error: Module jest-cli is not found in '.'.

2023-01-23T14:05:54.895Z angular/cli config Angular CLI not found.
We've also tried to automatically configure Wallaby.js for other frameworks
2023-01-23T14:05:54.895Z config Finished attempting automatic configuration for angular (8ms)
Automatic Vitest configuration error: Error: spawnSync node ENOENT
2023-01-23T14:05:54.896Z config Attempting automatic configuration for jest
Please refer to our docs: https://wallabyjs.com/docs/config/overview.html 
2023-01-23T14:05:54.897Z jest/config Detecting Jest.
2023-01-23T14:05:54.899Z jest/config Error: Module jest-cli is not found in '/home/aurelien/lab/test/vItest-webstorm-issue-3145'.
    at Object.<anonymous> (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:31:25202)
    at r (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:31:8268)
    at Object.next (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:31:7563)
    at /home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:31:7472
    at new Promise (<anonymous>)
    at s (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:31:7266)
    at Object.loadJest (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:31:22800)
    at /home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:22872
    at r (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:27605)
    at Object.next (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:26900)
    at /home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:26809
    at new Promise (<anonymous>)
    at s (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:26603)
    at r (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:22560)
    at Object.<anonymous> (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:26280)
    at r (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:27605)
    at Object.next (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:26900)
    at /home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:26809
    at new Promise (<anonymous>)
    at s (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:26603)
    at Object.n [as configure] (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:26161)
    at Config.<anonymous> (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:15:20840)
    at r (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:15:12061)
    at Object.next (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:15:11356)
    at o (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:15:11105)
2023-01-23T14:05:54.900Z config Finished attempting automatic configuration for jest (3ms)
2023-01-23T14:05:54.900Z config Attempting automatic configuration for vitest
2023-01-23T14:05:54.901Z vitest/config Detecting Vitest.
2023-01-23T14:05:54.904Z vitest/config Detected Vitest (0.27.3).
2023-01-23T14:05:54.924Z vitest/config Error: Error: spawnSync node ENOENT
    at Object.<anonymous> (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:30272)
    at r (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:20:746)
    at Object.next (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:20:41)
    at /home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:31962
    at new Promise (<anonymous>)
    at n (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:31756)
    at Object.r [as configure] (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:19:28896)
    at Config.<anonymous> (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:15:20840)
    at r (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:15:12061)
    at Object.next (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:15:11356)
    at o (/home/aurelien/.cache/JetBrains/WebStorm2022.1/wallaby/wallaby/server.js:15:11105)
2023-01-23T14:05:54.924Z config Finished attempting automatic configuration for vitest (24ms)
```

We can see the vitest config have been found :
```
2023-01-23T14:05:54.900Z config Attempting automatic configuration for vitest
2023-01-23T14:05:54.901Z vitest/config Detecting Vitest.
2023-01-23T14:05:54.904Z vitest/config Detected Vitest (0.27.3).
2023-01-23T14:05:54.924Z vitest/config Error: Error: spawnSync node ENOENT
```

It's very strange because you don't have this issue..

Can you tell me exact the steps/commands etc you're doing after cloning the repo?

**Comment by smcenlly** [comment]
We think we have found and fixed the problem that was affecting you. It seems that `node` is not part of your system path when you are launching with WebStorm for some reason (we don't have the same problem), so spawning `node` isn't working when Wallaby is trying to extract `vitest` configuration. We have updated Wallaby's logic to use the same `node` path as when you launched Wallaby, which should fix the issue.

Please update to Wallaby core `v1.0.1374`. Wallaby should automatically update for you. If it does not, you may [follow these steps](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to force an update.

**Comment by AurelienWebnation** [comment]
I just upadted to Wallaby core `v1.0.1374` and it's working!
Thanks you a lot @smcenlly.
