### ISSUE TITLE
crashing if test file match in wallaby.config but doesn't in jest.config

### ISSUE THREAD

**Issue by ShadowBelmolve** [wallabyjs/public#3149]
### Wallaby always crash if a test file match in wallaby.config but does not match in jest.config

I'm currently working in a project that have `.spec.ts` files for pure unit testing, and `.test.ts` files for any test that need external services(database, redis, etc).

When I was working I found that if I changed a file name from `.spec.ts` to `.test.ts` wallaby would instantly crash.

While I was writing this issue I made some tests and found that it always crash with any `.test.ts` file in a specific directory(and sub), even if the file is empty.
That directory was new so I looked at the `jest.config.ts` file and noticed the directory didn't had a match for `.test.ts` files.
Simply adding it resolved the issue.

### Wallaby diagnostics report

```
{
  editorVersion: '1.74.3',
  pluginVersion: '1.0.348',
  editorType: 'VSCode',
  osVersion: 'linux 5.15.85-1-MANJARO',
  nodeVersion: 'v18.12.1',
  coreVersion: '1.0.1370',
  checksum: 'NTk4M2FlMTE5ZmJmNzcxMDQyMzExZDQ2OGE1YjQyOTEsMTY3ODkyNDgwMDAwMCww',
  config: {
    name: 'ONStores Backend',
    tests: [
      { pattern: 'src/**/*.spec.ts', ignore: false, trigger: true, load: true, test: true, order: 3 },
      { pattern: 'src/**/*.test.ts', ignore: false, trigger: true, load: true, test: true, order: 4 }
    ],
    workers: { initial: 1, regular: 1, restart: false, recycle: false },
    filesWithNoCoverageCalculated: [ 'src/**/testing/**.ts', /testing/, /testing/, /testing/, /testing/ ],
    runAllTestsWhenNoAffectedTests: true,
    trace: true,
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/tmp/jest_rs',
              clearMocks: false,
              coveragePathIgnorePatterns: [ 'testing' ],
              cwd: '<rootDir>',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: { color: 'white', name: 'Use Cases' },
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              fakeTimers: { enableGlobally: false },
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: true, throwOnModuleCollision: false },
              id: '4a403c37b29423ad9e4d7d87877fd3b5',
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [
                'js',   'mjs',
                'cjs',  'jsx',
                'ts',   'tsx',
                'json', 'node'
              ],
              moduleNameMapper: [
                [ '^use\\-cases/(.*)$', '<rootDir>/src/use-cases/$1' ],
                [ '^app/(.*)$', '<rootDir>/src/app/$1' ],
                [ '^vtex/(.*)$', '<rootDir>/src/vtex/$1' ],
                [ '^root/(.*)$', '<rootDir>/$1' ]
              ],
              modulePathIgnorePatterns: [],
              modulePaths: [ '<rootDir>/src/src' ],
              prettierPath: 'prettier',
              resetMocks: true,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<rootDir>/src',
              roots: [ '<rootDir>/src' ],
              runner: '<rootDir>/node_modules/jest-runner/build/index.js',
              runtime: undefined,
              sandboxInjectedGlobals: [],
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<rootDir>/node_modules/jest-environment-node/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/use-cases/**/*.spec.ts' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<rootDir>/node_modules/jest-circus/runner.js',
              transform: [ [ '^.+\\.(t|j)s$', '<rootDir>/node_modules/ts-jest/dist/index.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            },
            {
              automock: false,
              cache: true,
              cacheDirectory: '/tmp/jest_rs',
              clearMocks: false,
              coveragePathIgnorePatterns: [ 'testing' ],
              cwd: '<rootDir>',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: { color: 'white', name: 'App' },
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              fakeTimers: { enableGlobally: false },
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: true, throwOnModuleCollision: false },
              id: '45b6232f6868faad8c6a3d66f92c4702',
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [
                'js',   'mjs',
                'cjs',  'jsx',
                'ts',   'tsx',
                'json', 'node'
              ],
              moduleNameMapper: [
                [ '^use\\-cases/(.*)$', '<rootDir>/src/use-cases/$1' ],
                [ '^app/(.*)$', '<rootDir>/src/app/$1' ],
                [ '^vtex/(.*)$', '<rootDir>/src/vtex/$1' ],
                [ '^root/(.*)$', '<rootDir>/$1' ]
              ],
              modulePathIgnorePatterns: [],
              modulePaths: [ '<rootDir>/src/src' ],
              prettierPath: 'prettier',
              resetMocks: true,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<rootDir>/src',
              roots: [ '<rootDir>/src' ],
              runner: '<rootDir>/node_modules/jest-runner/build/index.js',
              runtime: undefined,
              sandboxInjectedGlobals: [],
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<rootDir>/node_modules/jest-environment-node/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/app/**/*.spec.ts' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<rootDir>/node_modules/jest-circus/runner.js',
              transform: [ [ '^.+\\.(t|j)s$', '<rootDir>/node_modules/ts-jest/dist/index.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            },
            {
              automock: false,
              cache: true,
              cacheDirectory: '/tmp/jest_rs',
              clearMocks: false,
              coveragePathIgnorePatterns: [ 'testing' ],
              cwd: '<rootDir>',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: { color: 'white', name: 'VTEX' },
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              fakeTimers: { enableGlobally: false },
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: true, throwOnModuleCollision: false },
              id: 'e64266a2bc54c0a21f52898485a7de49',
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [
                'js',   'mjs',
                'cjs',  'jsx',
                'ts',   'tsx',
                'json', 'node'
              ],
              moduleNameMapper: [
                [ '^use\\-cases/(.*)$', '<rootDir>/src/use-cases/$1' ],
                [ '^app/(.*)$', '<rootDir>/src/app/$1' ],
                [ '^vtex/(.*)$', '<rootDir>/src/vtex/$1' ],
                [ '^root/(.*)$', '<rootDir>/$1' ]
              ],
              modulePathIgnorePatterns: [],
              modulePaths: [ '<rootDir>/src/src' ],
              prettierPath: 'prettier',
              resetMocks: true,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<rootDir>/src',
              roots: [ '<rootDir>/src' ],
              runner: '<rootDir>/node_modules/jest-runner/build/index.js',
              runtime: undefined,
              sandboxInjectedGlobals: [],
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<rootDir>/node_modules/jest-environment-node/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/vtex/**/*.spec.ts' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<rootDir>/node_modules/jest-circus/runner.js',
              transform: [ [ '^.+\\.(t|j)s$', '<rootDir>/node_modules/ts-jest/dist/index.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            },
            {
              automock: false,
              cache: true,
              cacheDirectory: '/tmp/jest_rs',
              clearMocks: false,
              coveragePathIgnorePatterns: [ 'testing' ],
              cwd: '<rootDir>',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: { color: 'white', name: 'AppE2E' },
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              fakeTimers: { enableGlobally: false },
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: true, throwOnModuleCollision: false },
              id: 'a6f2e2bf348894f20c9bcd5e3db73e17',
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [
                'js',   'mjs',
                'cjs',  'jsx',
                'ts',   'tsx',
                'json', 'node'
              ],
              moduleNameMapper: [
                [ '^use\\-cases/(.*)$', '<rootDir>/src/use-cases/$1' ],
                [ '^app/(.*)$', '<rootDir>/src/app/$1' ],
                [ '^vtex/(.*)$', '<rootDir>/src/vtex/$1' ],
                [ '^root/(.*)$', '<rootDir>/$1' ]
              ],
              modulePathIgnorePatterns: [],
              modulePaths: [ '<rootDir>/src/src' ],
              prettierPath: 'prettier',
              resetMocks: true,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<rootDir>/src',
              roots: [ '<rootDir>/src' ],
              runner: '<rootDir>/node_modules/jest-runner/build/index.js',
              runtime: undefined,
              sandboxInjectedGlobals: [],
              setupFiles: [],
              setupFilesAfterEnv: [ '<rootDir>/setup-database-jest.ts' ],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<rootDir>/node_modules/jest-environment-node/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/app/**/*.test.ts' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<rootDir>/node_modules/jest-circus/runner.js',
              transform: [ [ '^.+\\.(t|j)s$', '<rootDir>/node_modules/ts-jest/dist/index.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            ci: false,
            collectCoverage: true,
            collectCoverageFrom: [],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<rootDir>/coverage',
            coverageProvider: 'v8',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 17,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [
              {
                coveragePathIgnorePatterns: [ 'testing' ],
                transform: { '^.+\\.(t|j)s$': 'ts-jest' },
                modulePaths: [ './src/' ],
                moduleNameMapper: { '^use\\-cases/(.*)$': '<rootDir>/use-cases/$1', '^app/(.*)$': '<rootDir>/app/$1', '^vtex/(.*)$': '<rootDir>/vtex/$1', '^root/(.*)$': '<rootDir>/../$1' },
                resetMocks: true,
                displayName: 'Use Cases',
                rootDir: '<rootDir>/src',
                testMatch: [ '**/use-cases/**/*.spec.ts' ]
              },
              {
                coveragePathIgnorePatterns: [ 'testing' ],
                transform: { '^.+\\.(t|j)s$': 'ts-jest' },
                modulePaths: [ './src/' ],
                moduleNameMapper: { '^use\\-cases/(.*)$': '<rootDir>/use-cases/$1', '^app/(.*)$': '<rootDir>/app/$1', '^vtex/(.*)$': '<rootDir>/vtex/$1', '^root/(.*)$': '<rootDir>/../$1' },
                resetMocks: true,
                displayName: 'App',
                rootDir: '<rootDir>/src',
                testMatch: [ '**/app/**/*.spec.ts' ]
              },
              {
                coveragePathIgnorePatterns: [ 'testing' ],
                transform: { '^.+\\.(t|j)s$': 'ts-jest' },
                modulePaths: [ './src/' ],
                moduleNameMapper: { '^use\\-cases/(.*)$': '<rootDir>/use-cases/$1', '^app/(.*)$': '<rootDir>/app/$1', '^vtex/(.*)$': '<rootDir>/vtex/$1', '^root/(.*)$': '<rootDir>/../$1' },
                resetMocks: true,
                displayName: 'VTEX',
                rootDir: '<rootDir>/src',
                testMatch: [ '**/vtex/**/*.spec.ts' ]
              },
              {
                coveragePathIgnorePatterns: [ 'testing' ],
                transform: { '^.+\\.(t|j)s$': 'ts-jest' },
                modulePaths: [ './src/' ],
                moduleNameMapper: { '^use\\-cases/(.*)$': '<rootDir>/use-cases/$1', '^app/(.*)$': '<rootDir>/app/$1', '^vtex/(.*)$': '<rootDir>/vtex/$1', '^root/(.*)$': '<rootDir>/../$1' },
                resetMocks: true,
                displayName: 'AppE2E',
                rootDir: '<rootDir>/src',
                setupFilesAfterEnv: [ '<rootDir>/../setup-database-jest.ts' ],
                testMatch: [ '**/app/**/*.test.ts' ]
              }
            ],
            replname: undefined,
            reporters: undefined,
            rootDir: '<rootDir>',
            runTestsByPath: false,
            shard: undefined,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: undefined,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<rootDir>/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [ 'src' ],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/tmp/jest_rs', '\\./coverage' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/tmp/jest_rs', '\\./coverage' ],
            testMatch: [ '**/use-cases/**/*.spec.ts', '**/app/**/*.spec.ts', '**/vtex/**/*.spec.ts', '**/app/**/*.test.ts' ],
            testRegex: []
          }
        }
      }
    },
    filesWithCoverageCalculated: [],
    globalSetup: false,
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    dot: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, file: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        file: true
      },
      { pattern: '/tmp/jest_rs', regexp: /\/tmp\/jest_rs/, ignore: true, trigger: true, load: true, file: true },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**', ignore: false, trigger: true, load: true, order: 2 },
      { pattern: 'src/**/*.spec.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/**/*.test.ts', ignore: true, trigger: true, load: true, file: true }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '/usr/local/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    configCode: 'module.exports = function () {\n' +
      '  return {\n' +
      '    autoDetect: true,\n' +
      "    name: 'ONStores Backend',\n" +
      "    tests: ['src/**/*.spec.ts', 'src/**/*.test.ts'],\n" +
      '    workers: {\n' +
      '      initial: 1,\n' +
      '      regular: 1,\n' +
      '      restart: false,\n' +
      '    },\n' +
      "    filesWithNoCoverageCalculated: ['src/**/testing/**.ts'],\n" +
      '    runAllTestsWhenNoAffectedTests: true,\n' +
      '    trace: true,\n' +
      '  };\n' +
      '};\n'
  },
  packageJSON: {
    dependencies: {
      '@nestjs/axios': '^1.0.1',
      '@nestjs/bull': '^0.6.2',
      '@nestjs/common': '^9.0.0',
      '@nestjs/core': '^9.0.0',
      '@nestjs/event-emitter': '^1.3.1',
      '@nestjs/platform-express': '^9.0.0',
      bull: '^4.10.2',
      'class-transformer': '^0.5.1',
      'class-validator': '^0.14.0',
      knex: '^2.3.0',
      pg: '^8.8.0',
      'reflect-metadata': '^0.1.13',
      rxjs: '^7.5.5',
      zod: '^3.19.1'
    },
    devDependencies: {
      '@commitlint/cli': '^17.3.0',
      '@commitlint/config-conventional': '^17.3.0',
      '@golevelup/ts-jest': '^0.3.4',
      '@nestjs/cli': '^9.0.0',
      '@nestjs/schematics': '^9.0.0',
      '@nestjs/testing': '^9.0.0',
      '@types/bull': '^4.10.0',
      '@types/express': '^4.17.13',
      '@types/jest': '^28.1.4',
      '@types/node': '^18.0.3',
      '@types/supertest': '^2.0.12',
      '@typescript-eslint/eslint-plugin': '^5.30.5',
      '@typescript-eslint/parser': '^5.30.5',
      eslint: '^8.19.0',
      'eslint-config-prettier': '^8.5.0',
      'eslint-plugin-prettier': '^4.2.1',
      husky: '^8.0.2',
      jest: '^28.1.2',
      nock: '^13.3.0',
      prettier: '^2.7.1',
      'source-map-support': '^0.5.21',
      sqlite3: '^5.1.2',
      supertest: '^6.2.4',
      'ts-jest': '^28.0.5',
      'ts-loader': '^9.3.1',
      'ts-node': '^10.8.2',
      'tsconfig-paths': '^4.0.0',
      typescript: '^4.7.4'
    }
  },
  fs: { numberOfFiles: 194 },
  debug: [
    '2023-01-17T22:30:23.691Z config Attempting automatic configuration for angular\n',
    '2023-01-17T22:30:23.694Z angular/cli config Angular CLI not found.\n',
    '2023-01-17T22:30:23.694Z config Finished attempting automatic configuration for angular (3ms)\n',
    '2023-01-17T22:30:23.694Z config Attempting automatic configuration for jest\n',
    '2023-01-17T22:30:25.088Z jest/config Detected Jest.\n',
    '2023-01-17T22:30:25.089Z jest/config Configured Jest.\n',
    '2023-01-17T22:30:25.089Z config Finished attempting automatic configuration for jest (1395ms)\n',
    '2023-01-17T22:30:25.091Z project Wallaby Node version: v18.12.1\n',
    '2023-01-17T22:30:25.091Z project Wallaby config: <rootDir>/wallaby.conf.js\n',
    '2023-01-17T22:30:25.107Z fs File system starting\n',
    '2023-01-17T22:30:27.091Z fs File system scan completed\n',
    '2023-01-17T22:30:27.104Z project File cache: <homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.348/projects/3b11c41d7d4abb02\n',
    '2023-01-17T22:30:27.156Z uiService Listening port 51235\n',
    '2023-01-17T22:30:27.182Z workers Parallelism for initial run: 1, for regular run: 1\n',
    '2023-01-17T22:30:27.182Z workers Starting run worker instance #0\n',
    '2023-01-17T22:30:27.184Z workers Web server is listening at 38037\n',
    '2023-01-17T22:30:27.210Z project Stopping process pool\n',
    '2023-01-17T22:30:27.210Z project File cache is up-to-date, starting full test run\n',
    '2023-01-17T22:30:27.212Z project Test run started; run priority: 3\n',
    '2023-01-17T22:30:27.213Z project Running all tests\n',
    '2023-01-17T22:30:27.218Z workers Starting test run, priority: 3\n',
    '2023-01-17T22:30:27.218Z nodeRunner Starting sandbox [worker #0, session #juags]\n',
    '2023-01-17T22:30:27.218Z nodeRunner Preparing sandbox [worker #0, session #juags]\n',
    '2023-01-17T22:30:27.324Z workers Started run worker instance (delayed) #0\n',
    '2023-01-17T22:30:27.325Z nodeRunner Prepared sandbox [worker #0, session #juags]\n',
    '2023-01-17T22:30:27.325Z workers [worker #0, session #juags] Running tests in sandbox\n',
    '2023-01-17T22:30:28.992Z workers Sandbox (active) [juags] error: Failed to initialize wallaby jest.\n' +
      "Cannot read properties of undefined (reading 'context')\n" +
      "TypeError: Cannot read properties of undefined (reading 'context')\n" +
      '    at Array.map (<anonymous>)\n',
    '2023-01-17T22:30:29.094Z workers [juags] Run 0 test(s), skipped 0 test(s)\n',
    '2023-01-17T22:30:29.099Z workers [juags] Sandbox is responsive, closing it\n',
    '2023-01-17T22:30:29.100Z workers Failed to map the stack to user code, entry message: Failed to initialize wallaby jest.\n' +
      "Cannot read properties of undefined (reading 'context')\n" +
      "TypeError: Cannot read properties of undefined (reading 'context'), stack: Failed to initialize wallaby jest.\n" +
      "Cannot read properties of undefined (reading 'context')\n" +
      "TypeError: Cannot read properties of undefined (reading 'context')\n" +
      '    at <homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby87cc08/runners/node/jest@24.8.0/initializer.js:14:27394\n' +
      '    at Array.map (<anonymous>)\n' +
      '    at getTestData (<homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby87cc08/runners/node/jest@24.8.0/initializer.js:14:26940)\n' +
      '    at <homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby87cc08/runners/node/jest@24.8.0/initializer.js:14:29489\n' +
      '    at r (<homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby87cc08/runners/node/jest@24.8.0/initializer.js:14:1390)\n' +
      '    at Object.next (<homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby87cc08/runners/node/jest@24.8.0/initializer.js:14:685)\n' +
      '    at o (<homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby87cc08/runners/node\n',
    '2023-01-17T22:30:29.101Z project Test run finished\n',
    '2023-01-17T22:30:29.101Z project Processed console.log entries\n',
    '2023-01-17T22:30:29.101Z project Processed loading sequences\n',
    '2023-01-17T22:30:29.101Z project Processed executed tests\n',
    '2023-01-17T22:30:29.102Z project Processed code coverage\n',
    '2023-01-17T22:30:29.109Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem. We found and fixed the cause so it shouldn't affect anyone else in future (from Wallaby core `v1.0.1371`+).
