### ISSUE TITLE
Error: Wallaby is not compatible with current version of Vitest

### ISSUE THREAD

**Issue by bhvngt** [wallabyjs/public#3154]
### Issue description or question
While running wallaby against `vitest` I end up getting following error

```
Runtime error: Error executing tests in vitest:
Transform (./node_modules/.pnpm/vitest@0.27.3/node_modules/vitest/dist/chunk-runtime-setup.8ca273cd.js): Wallaby is not compatible with current version of Vitest.
Error: Transform (./node_modules/.pnpm/vitest@0.27.3/node_modules/vitest/dist/chunk-runtime-setup.8ca273cd.js): Wallaby is not compatible with current version of Vitest.
    at Object.transform (file://./node_modules/.pnpm/vite@4.0.4_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41506:44)
    at async loadAndTransform (file://./node_modules/.pnpm/vite@4.0.4_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39313:29)
```

Here's the [repo](https://github.com/bhvngt/wallabyjs-pnpm-workspace-vitest) that you can use for the purpose of reproduction.

### Wallaby diagnostics report

```
{
  editorVersion: 'IntelliJ IDEA 2022.3.1',
  pluginVersion: '1.0.257',
  editorType: 'IntelliJ',
  osVersion: 'darwin 22.2.0',
  nodeVersion: 'v18.13.0',
  coreVersion: '1.0.1375',
  checksum: 'YWY0MmM4MWJmNWE2MGFiNzAxYzhkNTgzMDc4NmU5YjEsMTcwMTEyOTYwMDAwMCww',
  config: {
    diagnostics: {
      vitest: {
        file: {
          config: "import {defineConfig} from 'vitest/config'\n" +
            'import {loadEnv} from "vite";\n' +
            '\n' +
            'export default defineConfig(({mode}) => {\n' +
            '    Object.assign(process.env, loadEnv("development", "./", ""));\n' +
            '    return {\n' +
            '        mode: "development",\n' +
            '        test: {\n' +
            '            globalSetup: ["./libs/foo/test/globalSetup.ts"],\n' +
            '            setupFiles: ["./libs/foo/test/setupTest.ts"],\n' +
            '            include: ["./libs/**/*.test.ts"],\n' +
            '            exclude: ["**/node_modules/**", "./libs/bar/**"]\n' +
            '        }\n' +
            '    };\n' +
            '})\n'
        },
        config: {
          allowOnly: true,
          watch: true,
          globals: false,
          environment: 'node',
          threads: true,
          clearMocks: false,
          restoreMocks: false,
          mockReset: false,
          include: [ './libs/**/*.test.ts' ],
          exclude: [ '**/node_modules/**', './libs/bar/**' ],
          testTimeout: 5000,
          hookTimeout: 10000,
          teardownTimeout: 10000,
          isolate: true,
          watchExclude: [ '**/node_modules/**', '**/dist/**' ],
          forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**', '<homeDir>/Projects/lab/wallabyjs-pnpm-workspace-vitest/libs/foo/test/setupTest.ts' ],
          update: false,
          reporters: [ 'default' ],
          silent: false,
          ui: false,
          uiBase: '/__vitest__/',
          open: true,
          css: { include: [], modules: { classNameStrategy: 'stable' } },
          coverage: {
            provider: 'c8',
            enabled: false,
            clean: true,
            cleanOnRerun: true,
            reportsDirectory: './coverage',
            exclude: [
              'coverage/**',
              'dist/**',
              'packages/*/test{,s}/**',
              '**/*.d.ts',
              'cypress/**',
              'test{,s}/**',
              'test{,-*}.{js,cjs,mjs,ts,tsx,jsx}',
              '**/*{.,-}test.{js,cjs,mjs,ts,tsx,jsx}',
              '**/*{.,-}spec.{js,cjs,mjs,ts,tsx,jsx}',
              '**/__tests__/**',
              '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*',
              '**/.{eslint,mocha,prettier}rc.{js,cjs,yml}',
              'libs/foo/test/setupTest.ts'
            ],
            reporter: [ 'text', 'html', 'clover', 'json' ],
            extension: [
              '.js',  '.cjs',
              '.mjs', '.ts',
              '.mts', '.cts',
              '.tsx', '.jsx',
              '.vue', '.svelte'
            ]
          },
          fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
          maxConcurrency: 5,
          dangerouslyIgnoreUnhandledErrors: false,
          typecheck: {
            checker: 'tsc',
            include: [ '**/*.{test,spec}-d.{ts,js}' ],
            exclude: [
              '**/node_modules/**',
              '**/dist/**',
              '**/cypress/**',
              '**/.{idea,git,cache,output,temp}/**',
              '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*'
            ]
          },
          slowTestThreshold: 300,
          globalSetup: [ './libs/foo/test/globalSetup.ts' ],
          setupFiles: [ '<homeDir>/Projects/lab/wallabyjs-pnpm-workspace-vitest/libs/foo/test/setupTest.ts' ],
          defines: {},
          root: '<homeDir>/Projects/lab/wallabyjs-pnpm-workspace-vitest',
          mode: [],
          deps: { inline: [ {}, {}, {}, {}, {}, {}, '@nuxt/test-utils' ], registerNodeLoader: false },
          snapshotOptions: { snapshotFormat: {}, updateSnapshot: 'new' },
          cache: { dir: '<homeDir>/Projects/lab/wallabyjs-pnpm-workspace-vitest/node_modules/.vitest' },
          sequence: { hooks: 'parallel' },
          environmentMatchGlobs: [],
          package: {
            version: '0.27.3',
            urls: { hooks: 'file://<homeDir>/Library/Caches/JetBrains/IntelliJIdea2022.3/wallaby/wallaby/runners/node/hooks.mjs' },
            paths: {
              root: '<homeDir>/Projects/lab/wallabyjs-pnpm-workspace-vitest/node_modules/.pnpm/vitest@0.27.3/node_modules/vitest',
              dist: '<homeDir>/Projects/lab/wallabyjs-pnpm-workspace-vitest/node_modules/.pnpm/vitest@0.27.3/node_modules/vitest/dist'
            }
          }
        }
      }
    },
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0', autoDetected: true },
    preserveComments: false,
    extractComments: true,
    files: [
      { pattern: 'libs/**/*.test.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: 'libs/bar/**', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'libs/foo/test/globalSetup.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/*.*', ignore: false, trigger: true, load: true, order: 1 }
    ],
    tests: [
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'libs/bar/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'libs/foo/test/globalSetup.ts', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'libs/**/*.test.ts', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    workers: { initial: 1, regular: 1, recycle: false },
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: {
      type: 'node',
      params: { runner: '--experimental-loader=file://<homeDir>/Library/Caches/JetBrains/IntelliJIdea2022.3/wallaby/wallaby/runners/node/hooks.mjs' },
      runner: '<homeDir>/Library/pnpm/nodejs/18.13.0/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: true,
    symlinkNodeModules: true,
    configCode: 'auto.detect#-1529498823'
  },
  packageJSON: { dependencies: undefined, devDependencies: { '@libs/bar': 'workspace:1.0.0', '@libs/foo': 'workspace:1.0.0', typescript: '^4.9.4', vite: '^4.0.4', vitest: '^0.27.3' } },
  fs: { numberOfFiles: 24 },
  debug: []
}
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This has been fixed in the latest version of Wallaby core, `v1.0.1376`.

After updating to use the latest version, we received another error in Wallaby that we weren't getting from the command-line, 

```
 Cannot find module 'ajv-formats/dist/formats' 
    Require stack: 
    -  
      ​​​​​at ​​​​​​libs/foo/test/SchemaValidator.test.ts:22:9
```

Right now, your project is set up as a `mono-repo` with nested `node_modules` for your libs. Wallaby does not support mono-repos in `vitest` at this point in time, we are waiting for [this issue](https://github.com/vitest-dev/vitest/issues/256) to be closed before we can guarantee Wallaby runs with `vitest` monorepos.

There's something strange going on with the `require` function when using the `requireFromString`. In both Wallaby and `vitest` case, the `requireFromString` package is being resolved from your mono-repo root (`<projectRoot>/node_modules/.pnpm/require-from-string@2.0.2/node_modules/require-from-string/index.js`), not your project's version. In **Wallaby's** context, it tries to load `ajv-formats/dist/formats` from the JavaScript code generated from `SchemaValidatorGenerator` and looks in the root `node_modules` and fails to load. For some reason this is working from the CLI but we're not sure why. Wallaby correctly resolves this if you `require` the module from your code, for example:

```javascript
    it("validate schema with date format", async () => {
        let schema = {"type": "object", properties: {foo: {type: "string", format: "date"}}};
        const validatorCode = SchemaValidatorGenerator(schema, false)

        // This eval correctly resolves the ajv dependency
        eval(`const formats0 = require("ajv-formats/dist/formats").fullFormats.date;`);
    })
```

The `requireFromString` function is creating a new Module and for some reason it's not inheriting the proper ambient node_modules resolution when Wallaby is running. You can fix this by changing your test as shown below (which works in both Wallaby and the CLI):

```javascript
import * as url from 'url';
...
    it("validate schema with date format", async () => {
        let schema = {"type": "object", properties: {foo: {type: "string", format: "date"}}};
        const validatorCode = SchemaValidatorGenerator(schema, false)
        eval(`const formats0 = require("ajv-formats/dist/formats").fullFormats.date;`);
        const validator = requireFromString(validatorCode, url.fileURLToPath(import.meta.url), { });
        expect(validator({foo: "2010-10-10"})).toBeTruthy(); 
    })
```

**Comment by bhvngt** [comment]
Thanks @smcenlly. I did a fresh clone of my repo. Added `ajv-formats` as a root workspace dependency and updated `wallabyjs` plugin. 

Everything seems to be working fine. Thanks for your always prompt and accurate support.
