### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by msorens** [wallabyjs/public#3155]
### Issue description or question

In a react project, all of our JS files used a `.js` extension, whether containing react code or not. WallabyJS was working fine with this arrangement.

We just renamed all the react-containing files to end in `.jsx`; those not containing react code still end in `.js`. This applies to both code-under-test as well as test files themselves.
Now wallabyJS balks with this...
```
[Error] Runtime error: {"message":"Cannot use import statement outside a module"...
```
...even though from the command line `npm run test` (which uses mocha) still works just fine.

Web search suggested a couple things I have tried:
- adding "type": "module" to package.json; this did not seem promising...
- adding "@babel/plugin-transform-modules-commonjs" to the babel plugin (one of your previously solved issues mentioned this); this made no difference.

### Wallaby diagnostics report

```
{
  editorVersion: '1.74.3',
  pluginVersion: '1.0.348',
  editorType: 'VSCode',
  osVersion: 'darwin 21.6.0',
  nodeVersion: 'v18.6.0',
  coreVersion: '1.0.1375',
  checksum: 'ZGNlOGM2N2ZmNWYwM2UzYTFlNmViMGQwMTRiY2I5OGUsMTY5OTA1NjAwMDAwMCww',
  config: {
    files: [
      { pattern: 'src/**/*.*', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: 'test/**/*.*', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: 'test/**/*.test.js', ignore: true, trigger: true, load: true, instrument: true, file: true }
    ],
    filesWithNoCoverageCalculated: [ 'test/**/*.*' ],
    tests: [ { pattern: 'test/**/*.test.js', ignore: false, trigger: true, load: true, test: true, order: 3 } ],
    testFramework: { version: 'mocha@2.1.0', configurator: 'mocha@2.1.0', reporter: 'mocha@2.1.0', starter: 'mocha@2.1.0' },
    env: { type: 'node', params: {}, runner: '/opt/homebrew/Cellar/node/18.6.0/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    compilers: { '**/*.js': [Function (anonymous)], '**/*.?(lit)coffee?(.md)': [Function (anonymous)] },
    workers: { restart: true, initial: 0, regular: 0, recycle: true },
    diagnostics: {},
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: true,
    symlinkNodeModules: undefined,
    configCode: 'module.exports = function (wallaby) {\n' +
      '  return {\n' +
      '    files: [\n' +
      '      // just the src dir...\n' +
      "      'src/**/*.*',\n" +
      '      // ... but need a few key files under the test tree, too\n' +
      "      'test/**/*.*',\n" +
      "      '!test/**/*.test.js',\n" +
      '    ],\n' +
      "    filesWithNoCoverageCalculated: ['test/**/*.*'],\n" +
      '    tests: [\n' +
      '      // Include tests\n' +
      "      'test/**/*.test.js'\n" +
      '    ],\n' +
      "    testFramework: 'mocha',\n" +
      '    env: {\n' +
      "      type: 'node'\n" +
      '    },\n' +
      '    compilers: {\n' +
      '      // If you have a .babelrc or babel.config.js file:\n' +
      "      '**/*.js': wallaby.compilers.babel(),\n" +
      '    },\n' +
      '    setup: function (_w) {\n' +
      "      require('./test/setup')\n" +
      '\n' +
      '      // Require polyfill and register as per mocha run script\n' +
      "      require('@babel/polyfill')\n" +
      "      require('@babel/register')\n" +
      '    },\n' +
      '    workers: {\n' +
      '      restart: true\n' +
      '    }\n' +
      '  }\n' +
      '}\n' +
      '\n'
  },
  packageJSON: {
    dependencies: {
      '@blueprintjs/core': '^3.52.0',
      '@blueprintjs/select': '^3.15.4',
      '@blueprintjs/table': '^3.8.13',
      '@codemirror/lang-json': '^6.0.1',
      '@codemirror/theme-one-dark': '^6.1.0',
      ajv: '^8.1.0',
      'autobind-decorator': '^2.4.0',
      classnames: '^2.2.6',
      codemirror: '^5.55.0',
      codemirror6: 'npm:codemirror@^6.0.1',
      'content-type': '^1.0.4',
      'diff-match-patch': '^1.0.5',
      esm: '^3.2.25',
      'find-my-way': '^2.2.5',
      formik: '^2.2.5',
      history: '^4.10.1',
      'js-yaml': '^3.14.1',
      koa: '^2.13.0',
      'koa-send': '^5.0.1',
      moment: '^2.29.4',
      pondjs: '^0.8.10',
      'prop-types': '^15.6.2',
      'query-string': '^5.1.1',
      'rc-scrollbars': '^1.0.3',
      react: '^16.13.1',
      'react-beautiful-dnd': '^13.1.0',
      'react-dom': '^16.13.1',
      'react-google-recaptcha': '^2.1.0',
      'react-redux': '^7.2.0',
      'react-router-dom': '^5.2.0',
      'react-timeseries-charts': '^0.16.1',
      recharts: '^2.1.9',
      redux: '^4.0.5',
      'redux-saga': '^1.1.3',
      'server-destroy': '^1.0.1',
      'stringifiable-error': '0.0.2',
      'whatwg-fetch': '^3.2.0'
    },
    devDependencies: {
      '@babel/core': '^7.12.9',
      '@babel/eslint-parser': '^7.15.7',
      '@babel/eslint-plugin': '^7.14.5',
      '@babel/plugin-proposal-decorators': '^7.12.1',
      '@babel/plugin-transform-react-jsx': '^7.12.7',
      '@babel/plugin-transform-regenerator': '^7.12.1',
      '@babel/preset-env': '^7.12.7',
      '@babel/register': '^7.12.1',
      '@rollup/plugin-babel': '^5.3.1',
      '@rollup/plugin-commonjs': '^22.0.0',
      '@rollup/plugin-json': '^4.1.0',
      '@rollup/plugin-node-resolve': '^13.3.0',
      '@rollup/plugin-replace': '^4.0.0',
      '@testing-library/react': '^11.2.6',
      '@testing-library/user-event': '^8.1.3',
      chai: '^4.3.6',
      'chai-dom': '^1.8.2',
      chokidar: '^3.4.3',
      enzyme: '^3.11.0',
      'enzyme-adapter-react-16': '^1.15.5',
      eslint: '^7.32.0',
      'eslint-plugin-cypress': '^2.12.1',
      'eslint-plugin-import': '^2.24.2',
      'eslint-plugin-react': '^7.26.0',
      'eslint-plugin-react-hooks': '^4.2.0',
      'eslint-plugin-sort-imports-es6-autofix': '^0.6.0',
      'eslint-plugin-sort-requires': '^2.1.0',
      'esm-wallaby': '^3.2.26',
      inflation: '^2.0.0',
      jsdom: '^20.0.0',
      'jsdom-global': '^3.0.2',
      less: '^3.12.2',
      marked: '^4.0.10',
      mocha: '^9.1.3',
      'mutationobserver-shim': '^0.3.7',
      'node-fetch': '^3.2.10',
      pegjs: '^0.10.0',
      'raw-body': '^2.4.1',
      'redux-mock-store': '^1.5.4',
      rollup: '^2.70.2',
      'rollup-plugin-postcss': '^4.0.2',
      'rollup-plugin-terser': '^7.0.2',
      sinon: '^8.1.1',
      'source-map-support': '^0.5.21',
      tmp: '^0.2.1',
      yargs: '^16.2.0'
    }
  },
  fs: { numberOfFiles: 814 },
  debug: [
    '2023-01-28T02:38:13.561Z project Wallaby Node version: v18.6.0\n',
    '2023-01-28T02:38:13.561Z project Wallaby config: <homeDir>/github/projects/ui/wallaby.js\n',
    '2023-01-28T02:38:13.566Z fs File system starting\n',
    '2023-01-28T02:38:13.640Z fs File system scan completed\n',
    '2023-01-28T02:38:13.660Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/projects/86a810363b26297e\n',
    '2023-01-28T02:38:13.663Z uiService Listening port 51236\n',
    '2023-01-28T02:38:13.664Z project package.json file change detected, invalidating local cache\n',
    '2023-01-28T02:38:13.762Z workers Parallelism for initial run: 8, for regular run: 4\n',
    '2023-01-28T02:38:13.762Z workers Starting run worker instance #0\n',
    '2023-01-28T02:38:13.762Z workers Starting run worker instance #1\n',
    '2023-01-28T02:38:13.762Z workers Starting run worker instance #2\n',
    '2023-01-28T02:38:13.762Z workers Starting run worker instance #3\n',
    '2023-01-28T02:38:13.762Z workers Starting run worker instance #4\n',
    '2023-01-28T02:38:13.762Z workers Starting run worker instance #5\n',
    '2023-01-28T02:38:13.762Z workers Starting run worker instance #6\n',
    '2023-01-28T02:38:13.762Z workers Starting run worker instance #7\n',
    '2023-01-28T02:38:13.762Z workers Web server is listening at 56087\n',
    '2023-01-28T02:38:13.762Z project File cache requires some updates, waiting required files from IDE\n',
    '2023-01-28T02:38:14.185Z workers Started run worker instance (delayed) #6\n',
    '2023-01-28T02:38:14.185Z workers Started run worker instance (delayed) #0\n',
    '2023-01-28T02:38:14.185Z workers Started run worker instance (delayed) #2\n',
    '2023-01-28T02:38:14.186Z workers Started run worker instance (delayed) #4\n',
    '2023-01-28T02:38:14.186Z workers Started run worker instance (delayed) #1\n',
    '2023-01-28T02:38:14.186Z workers Started run worker instance (delayed) #3\n',
    '2023-01-28T02:38:14.186Z workers Started run worker instance (delayed) #5\n',
    '2023-01-28T02:38:14.186Z workers Started run worker instance (delayed) #7\n',
    '2023-01-28T02:38:16.263Z project Compiler did not set ranges for file [src/lib/prop-types.js]\n',
    '2023-01-28T02:38:16.273Z project Compiler did not set ranges for file [src/lib/storage.js]\n',
    '2023-01-28T02:38:16.385Z project Compiler did not set ranges for file [src/lib/store/types.js]\n',
    '2023-01-28T02:38:16.739Z project Compiler did not set ranges for file [src/lib/policy/snippet.js]\n',
    '2023-01-28T02:38:16.769Z project Compiler did not set ranges for file [src/lib/policy/aux-container/panel-types.js]\n',
    '2023-01-28T02:38:16.803Z project Compiler did not set ranges for file [src/lib/json-schema/name-set-of-numbers-parameter.js]\n',
    '2023-01-28T02:38:16.806Z project Compiler did not set ranges for file [src/lib/json-schema/name-string-parameter.js]\n',
    '2023-01-28T02:38:16.808Z project Compiler did not set ranges for file [src/lib/json-schema/name-set-of-strings-parameter.js]\n',
    '2023-01-28T02:38:16.811Z project Compiler did not set ranges for file [src/lib/json-schema/set-of-strings-multi-select-parameter.js]\n',
    '2023-01-28T02:38:16.814Z project Compiler did not set ranges for file [src/lib/json-schema/set-of-strings-parameter.js]\n',
    '2023-01-28T02:38:16.833Z project Compiler did not set ranges for file [src/lib/json-schema/number-parameter.js]\n',
    '2023-01-28T02:38:16.836Z project Compiler did not set ranges for file [src/lib/json-schema/string-enum-parameter.js]\n',
    '2023-01-28T02:38:16.851Z project Compiler did not set ranges for file [src/lib/getting-started/page-type.js]\n',
    '2023-01-28T02:38:16.857Z project Compiler did not set ranges for file [src/lib/events/keyboard-event.js]\n',
    '2023-01-28T02:38:16.860Z project Compiler did not set ranges for file [src/lib/edition/edition-types.js]\n',
    '2023-01-28T02:38:16.871Z project Compiler did not set ranges for file [src/lib/json-schema/string-parameter.js]\n',
    '2023-01-28T02:38:16.884Z project Compiler did not set ranges for file [src/lib/docs/paths.js]\n',
    '2023-01-28T02:38:16.888Z project Compiler did not set ranges for file [src/lib/datasource/datasource-types.js]\n',
    '2023-01-28T02:38:16.894Z project Compiler did not set ranges for file [src/components/auth-router.js]\n',
    '2023-01-28T02:38:16.916Z project Compiler did not set ranges for file [src/components/sign-up/sign-up-support.url.js]\n',
    '2023-01-28T02:38:19.997Z project Stopping process pool\n',
    '2023-01-28T02:38:19.998Z project Running postprocessor\n',
    '2023-01-28T02:38:20.019Z postprocessor New TypeScript language service is required\n',
    "2023-01-28T02:38:20.029Z postprocessor TypeScript postprocessor will be removed because in 814 project files none were found by patterns: [ '**/*.ts?(x)' ]\n",
    '2023-01-28T02:38:20.031Z project Postprocessor execution finished\n',
    '2023-01-28T02:38:20.031Z project Postprocessor is removed as requested by itself\n',
    '2023-01-28T02:38:20.031Z project Test run started; run priority: 3\n',
    '2023-01-28T02:38:20.031Z project Running all tests\n',
    '2023-01-28T02:38:20.039Z workers Starting test run, priority: 3\n',
    '2023-01-28T02:38:20.039Z workers Distributing tests between 8 workers\n',
    '2023-01-28T02:38:20.041Z workers Running tests in parallel\n',
    '2023-01-28T02:38:20.042Z nodeRunner Starting sandbox [worker #0, session #cno03]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Starting sandbox [worker #1, session #iepcn]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Starting sandbox [worker #2, session #okkio]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Starting sandbox [worker #3, session #8g5r0]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Starting sandbox [worker #4, session #bof4o]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Starting sandbox [worker #5, session #iheyf]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Starting sandbox [worker #6, session #aqjnc]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Starting sandbox [worker #7, session #2iajc]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Preparing sandbox [worker #0, session #cno03]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Preparing sandbox [worker #1, session #iepcn]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Preparing sandbox [worker #2, session #okkio]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Preparing sandbox [worker #3, session #8g5r0]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Preparing sandbox [worker #4, session #bof4o]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Preparing sandbox [worker #5, session #iheyf]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Preparing sandbox [worker #6, session #aqjnc]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Preparing sandbox [worker #7, session #2iajc]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Prepared sandbox [worker #0, session #cno03]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Prepared sandbox [worker #1, session #iepcn]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Prepared sandbox [worker #2, session #okkio]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Prepared sandbox [worker #3, session #8g5r0]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Prepared sandbox [worker #4, session #bof4o]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Prepared sandbox [worker #5, session #iheyf]\n',
    '2023-01-28T02:38:20.042Z nodeRunner Prepared sandbox [worker #6, session #aqjnc]\n',
    '2023-01-28T02:38:20.043Z nodeRunner Prepared sandbox [worker #7, session #2iajc]\n',
    '2023-01-28T02:38:20.043Z workers [worker #0, session #cno03] Running tests in sandbox\n',
    '2023-01-28T02:38:20.045Z workers [worker #1, session #iepcn] Running tests in sandbox\n',
    '2023-01-28T02:38:20.045Z workers [worker #2, session #okkio] Running tests in sandbox\n',
    '2023-01-28T02:38:20.046Z workers [worker #3, session #8g5r0] Running tests in sandbox\n',
    '2023-01-28T02:38:20.046Z workers [worker #4, session #bof4o] Running tests in sandbox\n',
    '2023-01-28T02:38:20.046Z workers [worker #5, session #iheyf] Running tests in sandbox\n',
    '2023-01-28T02:38:20.047Z workers [worker #6, session #aqjnc] Running tests in sandbox\n',
    '2023-01-28T02:38:20.048Z workers [worker #7, session #2iajc] Running tests in sandbox\n',
    `2023-01-28T02:38:21.114Z workers Sandbox (active) [2iajc] error: {"message":"Cannot use import statement outside a module","stack":"./src/lib/datasource/datasource-config.jsx:2\\nimport React from 'react';\\n^^^^^^\\n\\nSyntaxError: Cannot use import statement outside a module\\n    at Object.compileFunction (node:vm:360:18)\\n    at wrapSafe (node:internal/modules/cjs/loader:1049:15)\\n    at Module._compile (node:internal/modules/cjs/loader:1084:27)\\n    at _0x36d4d9._compile (eval at <anonymous> ([wallaby core]/node_modules/q/q.js:2075:6), <anonymous>:1:1102327)\\n    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)\\n    at Module.load (node:internal/modules/cjs/loader:998:32)\\n    at Module._load (node:internal/modules/cjs/loader:839:12)\\n    at Module.require (node:internal/modules/cjs/loader:1022:19)\\n    at n.require ([wallaby core]/server.js:31:20482)\\n    at r.require ([wallaby core]/server.js:31:18958)\\n    at r.require ([wallaby core]/server.js:31:18958)\\n    at require (node:internal/modules/cjs/helpers:102:18)\\n    at Object.<anonymous> (./src/store/datasources.js:16:46)\\n    at Module._compile (node:internal/modules/cjs/loader:1120:14)\\n    at _0x36d4d9._compile (eval at <anonymous> ([wallaby core]/node_modules/q/q.js:2075:6), <anonymous>:1:1102327)\\n    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)\\n    at Module.load (node:internal/modules/cjs/loader:998:32)\\n    at Module._load (node:internal/modules/cjs/loader:839:12)\\n    at Module.require (node:internal/modules/cjs/loader:1022:19)\\n    at n.require ([wallaby core]/server.js:31:20482)\\n    at r.require ([wallaby core]/server.js:31:18958)\\n    at r.require ([wallaby core]/server.js:31:18958)\\n    at require (node:internal/modules/cjs/helpers:102:18)\\n    at Object.<anonymous> (./src/store/systems.js:21:41)\\n    at Module._compile (node:internal/modules/cjs/loader:1120:14)\\n    at _0x36d4d9._compile (eval at <anonymous> ([wallaby core]/node_modules/q/q.js:2075:6), <anonymous>:1:1102327)\\n    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)\\n    at Module.load (node:internal/modules/cjs/loader:998:32)\\n    at Module._load (node:internal/modules/cjs/loader:839:12)\\n    at Module.require (node:internal/modules/cjs/loader:1022:19)\\n    at n.require ([wallaby core]/server.js:31:20482)\\n    at r.require ([wallaby core]/server.js:31:18958)\\n    at r.require ([wallaby core]/server.js:31:18958)\\n    at require (node:internal/modules/cjs/helpers:102:18)\\n    at Object.<anonymous> (./src/store/blueprints.js:21:37)\\n    at Module._compile (node:internal/modules/cjs/loader:1120:14)\\n    at _0x36d4d9._compile (eval at <anonymous> ([wallaby core]/node_modules/q/q.js:2075:6), <anonymous>:1:1102327)\\n    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)\\n    at Module.load (node:internal/modules/cjs/loader:998:32)\\n    at Module._load (node:internal/modules/cjs/loader:839:12)\\n    at Module.require (node:internal/modules/cjs/loader:1022:19)\\n    at n.require ([wallaby core]/server.js:31:20482)\\n    at r.require ([wallaby core]/server.js:31:18958)\\n    at r.require ([wallaby core]/server.js:31:18958)\\n    at require (node:internal/modules/cjs/helpers:102:18)\\n    at Object.<anonymous> (./src/store.js:10:63)\\n    at Module._compile (node:internal/modules/cjs/loader:1120:14)\\n    at _0x36d4d9._compile (eval at <anonymous> ([wallaby core]/node_modules/q/q.js:2075:6), <anonymous>:1:1102327)\\n    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)\\n    at Module.load (node:internal/modules/cjs/loader:998:32)\\n    at Module._load (node:internal/modules/cjs/loader:839:12)\\n    at Module.require (node:internal/modules/cjs/loader:1022:19)\\n    at n.require ([wallaby core]/server.js:31:20482)\\n    at r.require ([wallaby core]/server.js:31:18958)\\n    at r.require ([wallaby core]/server.js:31:18958)\\n    at require (node:internal/modules/cjs/helpers:102:18)\\n    at Object.<anonymous> (./test/setup.js:12:20)\\n    at Module._compile (node:internal/modules/cjs/loader:1120:14)\\n    at _0x36d4d9._compile (eval at <anonymous> ([wallaby core]/node_modules/q/q.js:2075:6), <anonymous>:1:1102327)\\n    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)\\n    at Module.load (node:internal/modules/cjs/loader:998:32)\\n    at Module._load (node:internal/modules/cjs/loader:839:12)\\n    at Module.require (node:internal/modules/cjs/loader:1022:19)\\n    at n.require ([wallaby core]/server.js:31:20482)\\n    at r.require ([wallaby core]/server.js:31:18958)\\n    at r.require ([wallaby core]/server.js:31:18958)\\n    at require (node:internal/modules/cjs/helpers:102:18)\\n    at eval (eval at module.exports ([wallaby core]/runners/node/bootstrap.js:14:44), <anonymous>:2:7)\\n    at eval (eval at module.exports ([wallaby core]/runners/node/bootstrap.js:14:44), <anonymous>:7:7)\\n    at module.exports ([wallaby core]/runners/node/bootstrap.js:14:44)\\n    at in:run ([wallaby core]/server.js:22:29750)\\n    at WebSocket.<anonymous> ([wallaby core]/server.js:22:26851)\\n    at WebSocket.emit (node:events:513:28)\\n    at Receiver.ontext ([wallaby core]/node_modules/ws/lib/WebSocket.js:841:10)\\n    at [wallaby core]/node_modules/ws/lib/Receiver.js:536:18\\n    at [wallaby core]/node_modules/ws/lib/Receiver.js:368:7\\n    at [wallaby core]/node_modules/ws/lib/PerMessageDeflate.js:249:5\\n    at afterWrite (node:internal/streams/writable:500:5)\\n   \n`,
. . .
    '2023-01-28T02:38:21.135Z nodeRunner Error while processing STDERR message: Unexpected token a in JSON at position 1\n',
    '2023-01-28T02:38:21.135Z nodeRunner Error while processing STDERR message: Unexpected token a in JSON at position 1\n',
    '2023-01-28T02:38:21.135Z nodeRunner Error while processing STDERR message: Unexpected token a in JSON at position 1\n',
    '2023-01-28T02:38:21.216Z workers [2iajc] Run 0 test(s), skipped 0 test(s)\n',
    '2023-01-28T02:38:21.217Z workers [2iajc] Sandbox is responsive, closing it\n',
    '2023-01-28T02:38:21.217Z workers Recyling run worker instance #7\n',
    '2023-01-28T02:38:21.217Z workers Starting run worker instance #7\n',
    '2023-01-28T02:38:21.219Z workers [aqjnc] Run 0 test(s), skipped 0 test(s)\n',
    '2023-01-28T02:38:21.221Z workers [okkio] Run 0 test(s), skipped 0 test(s)\n',
    '2023-01-28T02:38:21.222Z workers [aqjnc] Sandbox is responsive, closing it\n',
    '2023-01-28T02:38:21.222Z workers Recyling run worker instance #6\n',
    '2023-01-28T02:38:21.222Z workers Starting run worker instance #6\n',
    '2023-01-28T02:38:21.222Z workers [cno03] Run 0 test(s), skipped 0 test(s)\n',
    '2023-01-28T02:38:21.223Z workers [okkio] Sandbox is responsive, closing it\n',
    '2023-01-28T02:38:21.223Z workers Recyling run worker instance #2\n',
    '2023-01-28T02:38:21.223Z workers Starting run worker instance #2\n',
    '2023-01-28T02:38:21.225Z workers [cno03] Sandbox is responsive, closing it\n',
    '2023-01-28T02:38:21.225Z workers Recyling run worker instance #0\n',
    '2023-01-28T02:38:21.225Z workers Starting run worker instance #0\n',
    '2023-01-28T02:38:21.230Z workers [bof4o] Run 0 test(s), skipped 0 test(s)\n',
    '2023-01-28T02:38:21.230Z workers [8g5r0] Run 0 test(s), skipped 0 test(s)\n',
    '2023-01-28T02:38:21.232Z workers [8g5r0] Sandbox is responsive, closing it\n',
    '2023-01-28T02:38:21.232Z workers Recyling run worker instance #3\n',
    '2023-01-28T02:38:21.232Z workers Starting run worker instance #3\n',
    '2023-01-28T02:38:21.233Z workers [iheyf] Run 0 test(s), skipped 0 test(s)\n',
    '2023-01-28T02:38:21.233Z workers [iepcn] Run 0 test(s), skipped 0 test(s)\n',
    '2023-01-28T02:38:21.233Z workers [bof4o] Sandbox is responsive, closing it\n',
    '2023-01-28T02:38:21.233Z workers Recyling run worker instance #4\n',
    '2023-01-28T02:38:21.234Z workers Starting run worker instance #4\n',
    '2023-01-28T02:38:21.236Z workers [iheyf] Sandbox is responsive, closing it\n',
    '2023-01-28T02:38:21.236Z workers Recyling run worker instance #5\n',
    '2023-01-28T02:38:21.237Z workers Starting run worker instance #5\n',
    '2023-01-28T02:38:21.238Z workers [iepcn] Sandbox is responsive, closing it\n',
    '2023-01-28T02:38:21.238Z workers Recyling run worker instance #1\n',
    '2023-01-28T02:38:21.238Z workers Starting run worker instance #1\n',
    '2023-01-28T02:38:21.238Z workers Merging parallel test run results\n',
    '2023-01-28T02:38:21.238Z project Test run finished\n',
    '2023-01-28T02:38:21.238Z project Processed console.log entries\n',
    '2023-01-28T02:38:21.238Z project Processed loading sequences\n',
    '2023-01-28T02:38:21.238Z project Processed executed tests\n',
    '2023-01-28T02:38:21.304Z project Processed code coverage\n',
    '2023-01-28T02:38:21.470Z project Test run result processed and sent to IDE\n',
    '2023-01-28T02:38:21.477Z workers Started run worker instance (delayed) #2\n',
    '2023-01-28T02:38:21.477Z workers Started run worker instance (delayed) #7\n',
    '2023-01-28T02:38:21.477Z workers Started run worker instance (delayed) #0\n',
    '2023-01-28T02:38:21.477Z workers Started run worker instance (delayed) #6\n',
    '2023-01-28T02:38:21.477Z workers Started run worker instance (delayed) #4\n',
    '2023-01-28T02:38:21.478Z workers Started run worker instance (delayed) #5\n',
    '2023-01-28T02:38:21.478Z workers Started run worker instance (delayed) #3\n',
    '2023-01-28T02:38:21.623Z workers Started run worker instance (delayed) #1\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
Your Wallaby config file specifies the pattern for files being compiled with Babel and it needs to be updated to include `.jsx` files:
```diff
compilers: {
   // If you have a .babelrc or babel.config.js file:
-  '**/*.js': wallaby.compilers.babel(),
+  '**/*.js?(x)': wallaby.compilers.babel(),
}
```
Making the change and restarting Wallaby should make it work, please let us know if the change doesn't help and we'll keep looking into it then.

**Comment by msorens** [comment]
That got me most of the way there, @ArtemGovorov . 
Also had to update the `files` and `tests` lists with jsx as shown: once I did that, I got the full set of tests being executed.

Thank you for your prompt response and fix!

```
    files: [
      // just the src dir...
      'src/**/*.*',
      // ... but need a few key files under the test tree, too
      'test/**/*.*',
      '!test/**/*.test.js',
      '!test/**/*.test.jsx'
    ],
    filesWithNoCoverageCalculated: ['test/**/*.*'],
    tests: [
      // Include tests
      'test/**/*.test.js',
      'test/**/*.test.jsx'
    ],
```
