### ISSUE TITLE
​[Info]​ console.error: TypeError: Cannot read properties of undefined (reading 'changedFiles')

### ISSUE THREAD

**Issue by nabaisu** [wallabyjs/public#3167]
Hello! I am finding issues with configuring wallaby in my project. I'm using the automatic configuration:

This is what is showing in my VSCode output console:

```
[Info]​ Started Wallaby.js Core v1.0.1220
​[Info]​ Wallaby App (realtime reports) is available at: http://localhost:51245
​[Info]​ console.warn: Can not find Jest run global hook module
​[Info]​ console.warn: Can not find Jest run global hook module
​[Info]​ console.error: TypeError: Cannot read properties of undefined (reading 'changedFiles')
​[Info]​     at /Users/io/Documents/GitHub/my-repo/node_modules/@jest/core/build/TestScheduler.js:271:41
​[Info]​     at async Promise.all (index 0)
​[Info]​     at async TestScheduler.scheduleTests (/Users/io/Documents/GitHub/my-repo/node_modules/@jest/core/build/TestScheduler.js:259:5)
​[Info]​ console.error: TypeError: Cannot read properties of undefined (reading 'changedFiles')
​[Info]​     at /Users/io/Documents/GitHub/my-repo/node_modules/@jest/core/build/TestScheduler.js:271:41
​[Info]​     at async Promise.all (index 0)
​[Info]​     at async TestScheduler.scheduleTests (/Users/io/Documents/GitHub/my-repo/node_modules/@jest/core/build/TestScheduler.js:259:5)
```

### Wallaby diagnostics report

```
{
  editorVersion: '1.75.1',
  pluginVersion: '1.0.327',
  editorType: 'VSCode',
  osVersion: 'darwin 21.6.0',
  nodeVersion: 'v16.17.1',
  coreVersion: '1.0.1220',
  checksum: 'MWI3NTJkYjU1NDY3ODVhOTZmZGVjMDJhNDk1NmM4ZjIsMTY0NDQ1MTIwMDAwMCww',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/private/var/folders/20/h5zr69z11mx2zjmww2gp68440000gn/T/jest_dx',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/Documents/GitHub/my-repo',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: undefined,
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              fakeTimers: { enableGlobally: false },
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: true, throwOnModuleCollision: false },
              id: '72c070ab07220f602856c3dcd217a961',
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [
                'js',   'mjs',
                'cjs',  'jsx',
                'ts',   'tsx',
                'json', 'node'
              ],
              moduleNameMapper: [ [ '.+\\.(css|styl|less|sass|scss|png|jpg|jpeg|ttf|woff|woff2|wav)$', 'identity-obj-proxy' ] ],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/Documents/GitHub/my-repo',
              roots: [ '<homeDir>/Documents/GitHub/my-repo' ],
              runner: '<homeDir>/Documents/GitHub/my-repo/node_modules/jest-runner/build/index.js',
              runtime: undefined,
              sandboxInjectedGlobals: [],
              setupFiles: [],
              setupFilesAfterEnv: [ '<homeDir>/Documents/GitHub/my-repo/src/setupTests.js' ],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/Documents/GitHub/my-repo/node_modules/jest-environment-jsdom/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
              testPathIgnorePatterns: [ '<homeDir>/Documents/GitHub/my-repo/tests-e2e/' ],
              testRegex: [],
              testRunner: '<homeDir>/Documents/GitHub/my-repo/node_modules/jest-circus/runner.js',
              transform: [ [ '\\.[jt]sx?$', '<homeDir>/Documents/GitHub/my-repo/node_modules/esbuild-jest/esbuild-jest.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            ci: false,
            collectCoverage: false,
            collectCoverageFrom: [ './src/**/*.{js,jsx}', '!**/node_modules/**', '!**/vendor/**' ],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<homeDir>/Documents/GitHub/my-repo/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 7,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/Documents/GitHub/my-repo',
            runTestsByPath: false,
            shard: undefined,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: undefined,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/Documents/GitHub/my-repo/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/20/h5zr69z11mx2zjmww2gp68440000gn/T/jest_dx', '\\./tests-e2e/', '\\./coverage' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/20/h5zr69z11mx2zjmww2gp68440000gn/T/jest_dx', '\\./tests-e2e/', '\\./coverage' ],
            testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    filesWithCoverageCalculated: [ './src/**/*.{js,jsx}', '!**/node_modules/**', '!**/vendor/**' ],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    micromatch: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
      { pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//, ignore: true, trigger: true, load: true },
      {
        pattern: '/private/var/folders/20/h5zr69z11mx2zjmww2gp68440000gn/T/jest_dx',
        regexp: /\/private\/var\/folders\/20\/h5zr69z11mx2zjmww2gp68440000gn\/T\/jest_dx/,
        ignore: true,
        trigger: true,
        load: true
      },
      { pattern: '\\./tests-e2e/', regexp: /\.\/tests-e2e\//, ignore: true, trigger: true, load: true },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      {
        pattern: '/private/var/folders/20/h5zr69z11mx2zjmww2gp68440000gn/T/jest_dx',
        regexp: /\/private\/var\/folders\/20\/h5zr69z11mx2zjmww2gp68440000gn\/T\/jest_dx/,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      { pattern: '\\./tests-e2e/', regexp: /\.\/tests-e2e\//, ignore: true, trigger: true, load: true, test: true },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, test: true },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    addModifiedTestFileToExclusiveTestRun: true,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '<homeDir>/.asdf/installs/nodejs/16.17.1/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'module.exports = function (wallaby) {\n  return {\n    autoDetect: true,\n  }\n}\n'
  },
  packageJSON: {
    dependencies: {
      '@headlessui/react': '^1.6.6',
      '@tanstack/react-table': '^8.7.0',
      '@tauri-apps/api': '^1.0.2',
      classnames: '^2.3.2',
      howler: '^2.2.3',
      i18next: '^21.8.14',
      'i18next-browser-languagedetector': '^6.1.4',
      lodash: '^4.17.21',
      mathjs: '^11.0.1',
      'random-useragent': '^0.5.0',
      react: '^18.2.0',
      'react-contexify': '^5.0.0',
      'react-debounce-input': '^3.3.0',
      'react-dom': '^18.2.0',
      'react-draggable': '^4.4.5',
      'react-error-boundary': '^3.1.4',
      'react-ga': '^3.3.1',
      'react-i18next': '^11.18.2',
      'react-icons': '^4.4.0',
      'react-multi-split-pane': '^0.3.3',
      'react-router-dom': '^6.3.0',
      'react-table': '^7.8.0',
      'react-toastify': '^9.0.7',
      'react-usestateref': '^1.0.8',
      'react-virtual': '^2.10.4',
      'react-virtualized-auto-sizer': '^1.0.6',
      'react-window': '^1.8.7',
      recharts: '^2.1.16',
      'string-similarity': '^4.0.4',
      'use-color-change': '^1.0.2',
      uuid: '^8.3.2'
    },
    devDependencies: {
      '@playwright/test': '^1.25.0',
      '@tauri-apps/cli': '^1.2.3',
      '@testing-library/jest-dom': '^5.16.5',
      '@testing-library/react': '^13.3.0',
      '@testing-library/user-event': '^14.4.3',
      '@types/react': '^18.0.15',
      '@types/react-dom': '^18.0.6',
      '@vitejs/plugin-react': '^2.0.0',
      autoprefixer: '^10.4.7',
      axios: '^0.27.2',
      'cross-env': '^7.0.3',
      esbuild: '^0.15.5',
      'esbuild-jest': '^0.5.0',
      'eslint-config-kentcdodds': '^20.3.1',
      'identity-obj-proxy': '^3.0.0',
      jest: '^28.1.3',
      'jest-environment-jsdom': '^28.1.3',
      msw: '^0.47.3',
      postcss: '^8.4.14',
      tailwindcss: '^3.1.6',
      vite: '^3.0.0'
    }
  },
  fs: { numberOfFiles: 15292 },
  debug: [
    '2023-02-18T21:36:44.392Z angular/cli config Angular CLI not found.\n',
    '2023-02-18T21:36:44.468Z jest/config Detected Jest.\n',
    '2023-02-18T21:36:44.468Z jest/config Configured Jest.\n',
    '2023-02-18T21:36:44.469Z project Wallaby Node version: v16.17.1\n',
    '2023-02-18T21:36:44.469Z project Wallaby config: <homeDir>/Documents/GitHub/my-repo/wallaby.cjs\n',
    '2023-02-18T21:36:45.319Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.327/projects/a5dd567924ecba74\n',
    '2023-02-18T21:36:45.366Z uiService Listening port 51235\n',
    '2023-02-18T21:36:45.376Z project Config file change detected, invalidating local cache\n',
    '2023-02-18T21:36:45.807Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2023-02-18T21:36:45.807Z workers Starting run worker instance #0\n',
    '2023-02-18T21:36:45.807Z workers Starting run worker instance #1\n',
    '2023-02-18T21:36:45.807Z workers Starting run worker instance #2\n',
    '2023-02-18T21:36:45.807Z workers Starting run worker instance #3\n',
    '2023-02-18T21:36:45.807Z workers Starting run worker instance #4\n',
    '2023-02-18T21:36:45.807Z workers Starting run worker instance #5\n',
    '2023-02-18T21:36:45.808Z workers Web server is listening at 56364\n',
    '2023-02-18T21:36:45.808Z project File cache requires some updates, waiting required files from IDE\n',
    '2023-02-18T21:36:45.867Z project Stopping process pool\n',
    '2023-02-18T21:36:45.868Z project Promoting test run to full run because of test selection changes\n',
    '2023-02-18T21:36:45.868Z project Test run started; run priority: 3\n',
    '2023-02-18T21:36:45.905Z project Running all tests\n',
    '2023-02-18T21:36:46.054Z workers Starting test run, priority: 3\n',
    '2023-02-18T21:36:46.054Z workers Distributing tests between 6 workers\n',
    '2023-02-18T21:36:46.055Z workers Running tests in parallel\n',
    '2023-02-18T21:36:46.055Z nodeRunner Starting sandbox [worker #0, session #ikczs]\n',
    '2023-02-18T21:36:46.055Z nodeRunner Starting sandbox [worker #1, session #m450g]\n',
    '2023-02-18T21:36:46.055Z nodeRunner Preparing sandbox [worker #0, session #ikczs]\n',
    '2023-02-18T21:36:46.055Z nodeRunner Preparing sandbox [worker #1, session #m450g]\n',
    '2023-02-18T21:36:46.060Z workers Started run worker instance (delayed) #1\n',
    '2023-02-18T21:36:46.061Z nodeRunner Prepared sandbox [worker #1, session #m450g]\n',
    '2023-02-18T21:36:46.061Z workers [worker #1, session #m450g] Running tests in sandbox\n',
    '2023-02-18T21:36:46.075Z workers Started run worker instance (delayed) #0\n',
    '2023-02-18T21:36:46.075Z nodeRunner Prepared sandbox [worker #0, session #ikczs]\n',
    '2023-02-18T21:36:46.075Z workers [worker #0, session #ikczs] Running tests in sandbox\n',
    '2023-02-18T21:36:46.095Z workers Started run worker instance (delayed) #2\n',
    '2023-02-18T21:36:46.098Z workers Started run worker instance (delayed) #4\n',
    '2023-02-18T21:36:46.098Z workers Started run worker instance (delayed) #3\n',
    '2023-02-18T21:36:46.098Z workers Started run worker instance (delayed) #5\n',
    '2023-02-18T21:36:46.520Z workers Scheduling Jest Test Run (m450g): 2023-02-18T21:36:46.509Z\n',
    '2023-02-18T21:36:46.521Z workers Jest Test Error: 2023-02-18T21:36:46.518Z\n',
    '2023-02-18T21:36:46.521Z workers Jest Test Run Complete (m450g): 2023-02-18T21:36:46.519Z\n',
    '2023-02-18T21:36:46.522Z workers [m450g] Run 0 test(s), skipped 0 test(s)\n',
    '2023-02-18T21:36:46.522Z workers [m450g] Sandbox is responsive, closing it\n',
    '2023-02-18T21:36:46.574Z workers Scheduling Jest Test Run (ikczs): 2023-02-18T21:36:46.568Z\n',
    '2023-02-18T21:36:46.574Z workers Jest Test Error: 2023-02-18T21:36:46.573Z\n',
    '2023-02-18T21:36:46.575Z workers Jest Test Run Complete (ikczs): 2023-02-18T21:36:46.573Z\n',
    '2023-02-18T21:36:46.575Z workers [ikczs] Run 0 test(s), skipped 0 test(s)\n',
    '2023-02-18T21:36:46.575Z workers [ikczs] Sandbox is responsive, closing it\n',
    '2023-02-18T21:36:46.575Z workers Merging parallel test run results\n',
    '2023-02-18T21:36:46.576Z project Test run finished\n',
    '2023-02-18T21:36:46.576Z project Processed console.log entries\n',
    '2023-02-18T21:36:46.576Z project Processed loading sequences\n',
    '2023-02-18T21:36:46.576Z project Processed executed tests\n',
    '2023-02-18T21:36:46.586Z project Processed code coverage\n',
    '2023-02-18T21:36:47.053Z project Test run result processed and sent to IDE\n',
    '2023-02-18T21:36:51.637Z uiService UI client connected\n',
    '2023-02-18T21:36:51.638Z uiService Outgoing message ui:handshake\n',
    '2023-02-18T21:36:51.643Z uiService Incoming message ui:tests:resultsRequested\n',
    '2023-02-18T21:36:51.649Z uiService Outgoing message ui:tests:allResultsUpdated\n',
    '2023-02-18T21:36:51.649Z uiService Incoming message ui:start\n',
    '2023-02-18T21:36:51.658Z uiService Outgoing message ui:summary\n',
    '2023-02-18T21:36:51.673Z uiService Outgoing message ui:files\n'
  ]
}
```

**Comment by smcenlly** [comment]
The version of Wallaby that you are using `v1.0.1220` was released on **Feb 8, 2022**.  Since then, there have been a number of breaking changes made to the latest versions of Jest that Wallaby has been updated to support.

Please update to the latest version of Wallaby, it should fix your problem. If your license has expired and you would like to use the latest version, you may [request a 15-day trial](https://wallabyjs.com/download/#try-it-free) to confirm the issue is fixed for you. You may renew your license via [our website](https://wallabyjs.com/purchase/#select-wallaby) (select to Claim your existing user discount), or else email us: hello@wallabyjs.com.

If you're still having problems after updating to the latest version of Wallaby, please provide us with an updated diagnostics report.
