### ISSUE TITLE
Wallaby with Jest does not correctly output `assert` expectations

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/public#3170]
From discord:

Take the following simple test using `jest`:

```javascript
const assert = require('assert');

it('should work', () => {
  console.log('foo');
  assert.equal(1, 2);
});
```

The CLI correctly outputs the diff:

```shell
> npx jest 
  console.log
    foo

      at Object.log (src/a.spec.js:4:11)

 FAIL  src/a.spec.js
  ✕ should work (13 ms)

  ● should work

    assert.equal(received, expected)

    Expected value to be equal to:
      2
    Received:
      1

      3 | it('should work', () => {
      4 |   console.log('foo');
    > 5 |   assert.equal(1, 2);
        |          ^
      6 | });

      at Object.equal (src/a.spec.js:5:10)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.157 s, estimated 1 s
Ran all test suites.
```

Wallaby output looks like this (note missing diff and bad stack trace):

<img width="710" alt="image" src="https://user-images.githubusercontent.com/2074089/220469447-d21d9664-bc36-4daf-934f-d32b42fd5e07.png">

**Comment by smcenlly** [comment]
This has been fixed in the latest version of Wallaby core `v1.0.1384`.

The correct stack trace, error, and diff now display:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/2074089/220493713-74fc8c7b-db2e-4a09-a04f-db6e92e4123a.png">
