### ISSUE TITLE
latest vscode extension importing wrong vitest file

### ISSUE THREAD

**Issue by tsirlucas** [wallabyjs/public#3171]
### Wallaby diagnostics report

```
{
  editorVersion: '1.75.0',
  pluginVersion: '1.0.349',
  editorType: 'VSCode',
  osVersion: 'darwin 21.0.1',
  nodeVersion: 'v16.14.2 - Electron',
  coreVersion: '1.0.1385',
  checksum: 'ZTRkZWY1MTYzMjgzYWUwZTQ5ZTFiYzQwOTUxMmZhNTUsMTcwODY0NjQwMDAwMCww',
  config: {
    files: [ { pattern: 'test/setupTests.ts', ignore: false, trigger: true, load: true, instrument: true, order: 1 } ],
    tests: [ { pattern: 'src/**/*.test.ts?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 } ],
    env: {
      type: 'node',
      kind: 'electron',
      params: {},
      runner: '/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0' },
    trace: true,
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: { '**/*.?(lit)coffee?(.md)': [Function (anonymous)] },
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: true,
    symlinkNodeModules: undefined,
    configCode: 'module.exports = function () {\n' +
      '  return {\n' +
      "    files: ['test/setupTests.ts'],\n" +
      "    tests: ['src/**/*.test.ts?(x)'],\n" +
      '    env: {\n' +
      "      type: 'node',\n" +
      "      kind: 'electron',\n" +
      '    },\n' +
      "    testFramework: 'vitest',\n" +
      '    trace: true,\n' +
      '  }\n' +
      '}\n'
  },
  packageJSON: {
    dependencies: {
      '@rollup/plugin-replace': '5.0.2',
      lodash: '4.17.21',
      postcss: '8.4.21',
      react: '18.2.0',
      'react-query': '3.39.3'
    },
    devDependencies: {
      '@storybook/react': '6.5.15',
      '@storybook/testing-library': '0.0.13',
      '@storybook/testing-react': '1.3.0',
      '@testing-library/jest-dom': '5.16.5',
      '@testing-library/react': '13.4.0',
      '@testing-library/react-hooks': '8.0.1',
      '@testing-library/user-event': '14.4.3',
      '@types/react': '18.0.27',
      '@vitejs/plugin-react': '3.1.0',
      '@vitest/coverage-c8': '0.28.5',
      'cross-env': '7.0.3',
      'dependency-cruiser': '12.6.0',
      electron: '^23.1.1',
      eslint: '8.32.0',
      'msw-storybook-addon': '1.6.3',
      'resize-observer-polyfill': '1.5.1',
      rimraf: '4.1.2',
      'rollup-plugin-external-globals': '0.7.1',
      typescript: '4.9.4',
      vite: '3.2.5',
      'vite-plugin-css-injected-by-js': '2.4.0',
      vitest: '0.28.5',
      'vitest-preview': '0.0.1',
      'whatwg-fetch': '3.6.2'
    }
  },
  fs: { numberOfFiles: 3 },
  debug: [
    '2023-02-23T22:38:40.175Z project Wallaby Node version: v16.14.2\n',
    '2023-02-23T22:38:40.176Z project Wallaby config: <homeDir>/Documents/workspace/chilipiper/frontend/apps/admin-chilical/wallaby.cjs\n',
    '2023-02-23T22:38:40.181Z fs File system starting\n',
    '2023-02-23T22:38:40.198Z fs File system scan completed\n',
    '2023-02-23T22:38:40.202Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.349/projects/5054540eb5f99426\n',
    '2023-02-23T22:38:40.253Z uiService Listening port 51235\n',
    '2023-02-23T22:38:40.257Z project Config file change detected, invalidating local cache\n',
    '2023-02-23T22:38:40.260Z workers Parallelism for initial run: 8, for regular run: 4\n',
    '2023-02-23T22:38:40.260Z workers Starting run worker instance #0\n',
    '2023-02-23T22:38:40.260Z workers Starting run worker instance #1\n',
    '2023-02-23T22:38:40.260Z workers Starting run worker instance #2\n',
    '2023-02-23T22:38:40.260Z workers Starting run worker instance #3\n',
    '2023-02-23T22:38:40.260Z workers Starting run worker instance #4\n',
    '2023-02-23T22:38:40.260Z workers Starting run worker instance #5\n',
    '2023-02-23T22:38:40.260Z workers Starting run worker instance #6\n',
    '2023-02-23T22:38:40.260Z workers Starting run worker instance #7\n',
    '2023-02-23T22:38:40.261Z workers Web server is listening at 51968\n',
    '2023-02-23T22:38:40.261Z project File cache requires some updates, waiting required files from IDE\n',
    '2023-02-23T22:38:40.506Z workers Started run worker instance (delayed) #5\n',
    '2023-02-23T22:38:40.515Z workers Started run worker instance (delayed) #6\n',
    '2023-02-23T22:38:40.522Z workers Started run worker instance (delayed) #4\n',
    '2023-02-23T22:38:40.533Z workers Started run worker instance (delayed) #3\n',
    '2023-02-23T22:38:40.545Z workers Started run worker instance (delayed) #0\n',
    '2023-02-23T22:38:40.569Z workers Started run worker instance (delayed) #2\n',
    '2023-02-23T22:38:40.580Z workers Started run worker instance (delayed) #1\n',
    '2023-02-23T22:38:40.591Z workers Started run worker instance (delayed) #7\n',
    '2023-02-23T22:38:40.739Z project Stopping process pool\n',
    '2023-02-23T22:38:40.741Z project Running postprocessor\n',
    '2023-02-23T22:38:40.747Z postprocessor New TypeScript language service is required\n',
    '2023-02-23T22:38:40.880Z project Postprocessor execution finished\n',
    '2023-02-23T22:38:40.880Z project Test run started; run priority: 3\n',
    '2023-02-23T22:38:40.880Z project Running all tests\n',
    '2023-02-23T22:38:40.880Z workers Starting test run, priority: 3\n',
    '2023-02-23T22:38:40.881Z workers Distributing tests between 8 workers\n',
    '2023-02-23T22:38:40.881Z workers Running tests in parallel\n',
    '2023-02-23T22:38:40.881Z nodeRunner Starting sandbox [worker #0, session #w5tq1]\n',
    '2023-02-23T22:38:40.881Z nodeRunner Starting sandbox [worker #1, session #mjtn6]\n',
    '2023-02-23T22:38:40.881Z nodeRunner Preparing sandbox [worker #0, session #w5tq1]\n',
    '2023-02-23T22:38:40.881Z nodeRunner Preparing sandbox [worker #1, session #mjtn6]\n',
    '2023-02-23T22:38:40.881Z nodeRunner Prepared sandbox [worker #0, session #w5tq1]\n',
    '2023-02-23T22:38:40.881Z nodeRunner Prepared sandbox [worker #1, session #mjtn6]\n',
    '2023-02-23T22:38:40.881Z workers [worker #0, session #w5tq1] Running tests in sandbox\n',
    '2023-02-23T22:38:40.881Z workers [worker #1, session #mjtn6] Running tests in sandbox\n',
    '2023-02-23T22:38:41.036Z workers Sandbox (active) [w5tq1] error: Failed to initialize wallaby vitest.\n' +
      'dependency.startVitest is not a function\n' +
      'TypeError: dependency.startVitest is not a function\n',
    '2023-02-23T22:38:41.037Z workers Failed to map the stack to user code, entry message: Failed to initialize wallaby vitest.\n' +
      'dependency.startVitest is not a function\n' +
      'TypeError: dependency.startVitest is not a function, stack: Failed to initialize wallaby vitest.\n' +
      'dependency.startVitest is not a function\n' +
      'TypeError: dependency.startVitest is not a function\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.349/wallabye337c1/runners/node/vitest@0.14.0/initializer.js:14:8566\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.349/wallabye337c1/runners/node/vitest@0.14.0/initializer.js:14:10373)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.349/wallabye337c1/runners/node/vitest@0.14.0/initializer.js:14:9668)\n' +
      '    at o (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.349/wallabye337c1/runners/node/vitest@0.14.0/initializer.js:14:9417)\n',
    '2023-02-23T22:38:41.037Z workers Sandbox (active) [mjtn6] error: Failed to initialize wallaby vitest.\n' +
      'dependency.startVitest is not a function\n' +
      'TypeError: dependency.startVitest is not a function\n',
    '2023-02-23T22:38:41.037Z workers Failed to map the stack to user code, entry message: Failed to initialize wallaby vitest.\n' +
      'dependency.startVitest is not a function\n' +
      'TypeError: dependency.startVitest is not a function, stack: Failed to initialize wallaby vitest.\n' +
      'dependency.startVitest is not a function\n' +
      'TypeError: dependency.startVitest is not a function\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.349/wallabye337c1/runners/node/vitest@0.14.0/initializer.js:14:8566\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.349/wallabye337c1/runners/node/vitest@0.14.0/initializer.js:14:10373)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.349/wallabye337c1/runners/node/vitest@0.14.0/initializer.js:14:9668)\n' +
      '    at o (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.349/wallabye337c1/runners/node/vitest@0.14.0/initializer.js:14:9417)\n',
    '2023-02-23T22:38:41.138Z workers [w5tq1] Run 0 test(s), skipped 0 test(s)\n',
    '2023-02-23T22:38:41.139Z workers [mjtn6] Run 0 test(s), skipped 0 test(s)\n',
    '2023-02-23T22:38:41.140Z workers [w5tq1] Sandbox is responsive, closing it\n',
    '2023-02-23T22:38:41.141Z workers [mjtn6] Sandbox is responsive, closing it\n',
    '2023-02-23T22:38:41.141Z workers Merging parallel test run results\n',
    '2023-02-23T22:38:41.141Z project Test run finished\n',
    '2023-02-23T22:38:41.141Z project Processed console.log entries\n',
    '2023-02-23T22:38:41.141Z project Processed loading sequences\n',
    '2023-02-23T22:38:41.141Z project Processed executed tests\n',
    '2023-02-23T22:38:41.142Z project Processed code coverage\n',
    '2023-02-23T22:38:41.146Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by tsirlucas** [comment]
It seems like when initializer imports vitest, it imports the chunk instead of the index node.js file

node.js does the following when exporting

```ts
export { B as BaseSequencer, V as VitestPlugin, c as createVitest, s as startVitest } from './chunk-node-pkg.9a107dfb.js';
```

but vscode extension is importing `./chunk-node-pkg.9a107dfb.js` which exports things as

```ts
export { BaseSequencer as B, VitestPlugin as V, createVitest as c, divider as d, onetime$1 as o, startVitest as s, version$1 as v };
```

and then initializer tries to call `.startVitest` which doesnt exist. I hardcoded the `.startVitest` call to `.s` instead and got a few different errors but that one worked.

**Comment by smcenlly** [comment]
The `wallaby.js` configuration that you created (reported in your diagnostics report) is not valid, which is why you're having a problem.

The best way to use Wallaby with `vitest` is to ensure that `vitest` runs from the command-line and then use automatic configuration (do not create a config file at all). Run the VS Code command `Wallaby.js: Select Configuration` and select `Automatic Configuration <project directory>`.

With your configuration file, providing `env` and providing `testFramework` is also not valid and is causing problems.

**wallaby.js configuration file**
```javascript
module.exports = function () {
  return {
    files: ['test/setupTests.ts'],
    tests: ['src/**/*.test.ts?(x)'],
    env: {
      type: 'node',
      kind: 'electron',
    },
    testFramework: 'vitest',
    trace: true,
  }
}
```

You may replace your configuration file with:

```javascript
module.exports = function () {
  return {
    autoDetect: true,
    files: ['test/setupTests.ts'],
    tests: ['src/**/*.test.ts?(x)'],
    trace: true,
  }
}
```

---

This will solve your problem so I'm going to close the issue. If you're having other problems and need a custom Wallaby configuration for some reason, please let us know and we'll re-open the issue.

**Comment by tsirlucas** [comment]
issue is that the project im attempting to use wallaby lives in a monorepo which contains other projects that are using jest. so when i set `autoDetect` to true it picks jest as testFramework.

Is there a way I can manually tell wallaby to use vitest and not autoDetect?

**Comment by smcenlly** [comment]
Instead of `autoDetect: true`, you can use `autoDetect: ['vitest']`. This makes Wallaby **only** try and auto detect configuration for vitest.

It's also worth noting that vitest does not yet have first class support for mono-repos ([see here](https://github.com/vitest-dev/vitest/issues/256)). Until that's added we won't be able to ensure that Wallaby works with vitest monorepos. If `vitest` works from your project root though, Wallaby should too.

**Comment by tsirlucas** [comment]
That worked like a charm. Thank you!
