### ISSUE TITLE
Wallaby not working after upgrading to Jest 29

### ISSUE THREAD

**Issue by mmazur122** [wallabyjs/public#3174]
### Issue description or question

I'm having issues with Wallaby after upgrading to Jest 29. This error comes up every time I try to run tests with Wallaby: 

<img width="2056" alt="Screenshot 2023-02-26 at 12 25 35 PM" src="https://user-images.githubusercontent.com/11011670/221407619-484cf28c-4dc1-4567-a468-5f29dec0e133.png">

It works fine with Jest 28.1.3. 

I prepared a [tiny repo](https://github.com/mmazur122/wallaby-issue-reproduction) to check if it's just my laptop. I was able to reproduce the same issue on my other Mac. 

### Wallaby diagnostics report

```
{
  editorVersion: 'WebStorm 2022.2.3',
  pluginVersion: '1.0.261',
  editorType: 'IntelliJ',
  osVersion: 'darwin 22.3.0',
  nodeVersion: 'v18.12.1',
  coreVersion: '1.0.1328',
  checksum: 'N2M1YjE2NzA2ZTM4Y2Q4ZGJjZDdjOTI1NjlhMWJiZmYsMTY2MjQyMjQwMDAwMCww',
  config: {
    trace: true,
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/private/var/folders/9j/_kkh8f6x1png7hhtw04xp0rr0000gp/T/jest_dy',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/projects/wallaby-issue-reproduction',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: undefined,
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [ '.ts' ],
              fakeTimers: { enableGlobally: false },
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: true, throwOnModuleCollision: false },
              id: '5c07f724696870e5f35fec58e440d363',
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [
                'js',   'mjs',
                'cjs',  'jsx',
                'ts',   'tsx',
                'json', 'node'
              ],
              moduleNameMapper: [],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/projects/wallaby-issue-reproduction',
              roots: [ '<homeDir>/projects/wallaby-issue-reproduction' ],
              runner: '<homeDir>/projects/wallaby-issue-reproduction/node_modules/jest-runner/build/index.js',
              runtime: undefined,
              sandboxInjectedGlobals: [],
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: { escapeString: false, printBasicPrototype: false },
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/projects/wallaby-issue-reproduction/node_modules/jest-environment-node/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '<homeDir>/projects/wallaby-issue-reproduction/src/**/__tests__/**/*.[jt]s?(x)' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<homeDir>/projects/wallaby-issue-reproduction/node_modules/jest-circus/runner.js',
              transform: [ [ '^.+\\.tsx?$', '<homeDir>/projects/wallaby-issue-reproduction/node_modules/ts-jest/dist/index.js', { useESM: true } ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            ci: false,
            collectCoverage: false,
            collectCoverageFrom: [],
            coverageDirectory: '<homeDir>/projects/wallaby-issue-reproduction/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 9,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/projects/wallaby-issue-reproduction',
            runTestsByPath: false,
            seed: -255792723,
            shard: undefined,
            showSeed: undefined,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: { escapeString: false, printBasicPrototype: false },
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/projects/wallaby-issue-reproduction/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true,
            workerIdleMemoryLimit: undefined
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/9j/_kkh8f6x1png7hhtw04xp0rr0000gp/T/jest_dy', '\\./coverage' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/9j/_kkh8f6x1png7hhtw04xp0rr0000gp/T/jest_dy', '\\./coverage' ],
            testMatch: [ 'src/**/__tests__/**/*.[jt]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    dot: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, file: true, test: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        file: true,
        test: true
      },
      {
        pattern: '/private/var/folders/9j/_kkh8f6x1png7hhtw04xp0rr0000gp/T/jest_dy',
        regexp: /\/private\/var\/folders\/9j\/_kkh8f6x1png7hhtw04xp0rr0000gp\/T\/jest_dy/,
        ignore: true,
        trigger: true,
        load: true,
        file: true,
        test: true
      },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true, file: true }
    ],
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true, file: false },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true,
        file: false
      },
      {
        pattern: '/private/var/folders/9j/_kkh8f6x1png7hhtw04xp0rr0000gp/T/jest_dy',
        regexp: /\/private\/var\/folders\/9j\/_kkh8f6x1png7hhtw04xp0rr0000gp\/T\/jest_dy/,
        ignore: true,
        trigger: true,
        load: true,
        test: true,
        file: false
      },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'src/**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '<homeDir>/.nvm/versions/node/v18.12.1/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#1438136455'
  },
  packageJSON: { dependencies: {}, devDependencies: { '@types/jest': '~29.4.0', jest: '~29.0.0', 'ts-jest': '~29.0.5', 'ts-node': '~10.9.1', typescript: '~4.7.2' } },
  fs: { numberOfFiles: 7 },
  debug: [
    '2023-02-26T11:20:03.332Z config Attempting automatic configuration for angular\n',
    '2023-02-26T11:20:03.334Z angular/cli config Angular CLI not found.\n',
    '2023-02-26T11:20:03.334Z config Finished attempting automatic configuration for angular (2ms)\n',
    '2023-02-26T11:20:03.334Z config Attempting automatic configuration for jest\n',
    '2023-02-26T11:20:03.975Z jest/config Detected Jest.\n',
    '2023-02-26T11:20:03.975Z jest/config Configured Jest.\n',
    '2023-02-26T11:20:03.975Z config Finished attempting automatic configuration for jest (641ms)\n',
    '2023-02-26T11:20:03.976Z project Wallaby Node version: v18.12.1\n',
    '2023-02-26T11:20:03.976Z project Wallaby config: <homeDir>/projects/wallaby-issue-reproduction/auto.detect\n',
    '2023-02-26T11:20:03.983Z fs File system starting\n',
    '2023-02-26T11:20:03.997Z fs File system scan completed\n',
    '2023-02-26T11:20:03.999Z project File cache: <homeDir>/Library/Caches/JetBrains/WebStorm2022.2/wallaby/projects/c2a452667d052689\n',
    '2023-02-26T11:20:04.030Z uiService Listening port 51235\n',
    '2023-02-26T11:20:04.034Z project package.json file change detected, invalidating local cache\n',
    '2023-02-26T11:20:04.036Z workers Parallelism for initial run: 8, for regular run: 4\n',
    '2023-02-26T11:20:04.036Z workers Starting run worker instance #0\n',
    '2023-02-26T11:20:04.037Z workers Starting run worker instance #1\n',
    '2023-02-26T11:20:04.037Z workers Starting run worker instance #2\n',
    '2023-02-26T11:20:04.037Z workers Starting run worker instance #3\n',
    '2023-02-26T11:20:04.037Z workers Starting run worker instance #4\n',
    '2023-02-26T11:20:04.037Z workers Starting run worker instance #5\n',
    '2023-02-26T11:20:04.037Z workers Starting run worker instance #6\n',
    '2023-02-26T11:20:04.037Z workers Starting run worker instance #7\n',
    '2023-02-26T11:20:04.037Z workers Web server is listening at 63510\n',
    '2023-02-26T11:20:04.037Z project File cache requires some updates, waiting required files from IDE\n',
    '2023-02-26T11:20:04.078Z project Stopping process pool\n',
    '2023-02-26T11:20:04.081Z project Test run started; run priority: 3\n',
    '2023-02-26T11:20:04.082Z project Running all tests\n',
    '2023-02-26T11:20:04.083Z workers Starting test run, priority: 3\n',
    '2023-02-26T11:20:04.083Z nodeRunner Starting sandbox [worker #0, session #c6izy]\n',
    '2023-02-26T11:20:04.083Z nodeRunner Preparing sandbox [worker #0, session #c6izy]\n',
    '2023-02-26T11:20:04.157Z workers Started run worker instance (delayed) #2\n',
    '2023-02-26T11:20:04.159Z workers Started run worker instance (delayed) #1\n',
    '2023-02-26T11:20:04.159Z workers Started run worker instance (delayed) #0\n',
    '2023-02-26T11:20:04.159Z nodeRunner Prepared sandbox [worker #0, session #c6izy]\n',
    '2023-02-26T11:20:04.159Z workers [worker #0, session #c6izy] Running tests in sandbox\n',
    '2023-02-26T11:20:04.163Z workers Started run worker instance (delayed) #4\n',
    '2023-02-26T11:20:04.164Z workers Started run worker instance (delayed) #3\n',
    '2023-02-26T11:20:04.167Z workers Started run worker instance (delayed) #6\n',
    '2023-02-26T11:20:04.169Z workers Started run worker instance (delayed) #5\n',
    '2023-02-26T11:20:04.174Z workers Started run worker instance (delayed) #7\n',
    '2023-02-26T11:20:05.272Z workers Scheduling Jest Test Run (c6izy): 2023-02-26T11:20:04.836Z\n',
    "2023-02-26T11:20:05.273Z workers Sandbox (active) [c6izy] error: ENOENT: no such file or directory, open '/private/var/folders/9j/_kkh8f6x1png7hhtw04xp0rr0000gp/T/jest_dy/jest-transform-cache-5c07f724696870e5f35fec58e440d363-abc22ad5e77a7416ef9c18e131733e53/b8/sumtest_b82ebc2301f36e262d8fd4e8f6c3fa8e.wallaby.718304486'\n" +
      '    at Object.openSync (node:fs:600:3)\n' +
      '    at ScriptTransformer.transformSource (./node_modules/@jest/transform/build/ScriptTransformer.js:542:31)\n' +
      '    at ScriptTransformer._transformAndBuildScript (./node_modules/@jest/transform/build/ScriptTransformer.js:671:40)\n' +
      '    at ScriptTransformer.transform (./node_modules/@jest/transform/build/ScriptTransformer.js:723:19)\n' +
      '    at Runtime.transformFile (./node_modules/jest-runtime/build/index.js:1455:53)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1387:34)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:1012:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:872:12)\n' +
      '    at jestAdapter (./node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:77:13)\n' +
      '    at async runTestInternal (./node_modules/jest-runner/build/runTest.js:367:16)\n' +
      '    at async runTest (./node_modules/jest-runner/build/runTest.js:444:34)\n',
    '2023-02-26T11:20:05.274Z workers [c6izy] Run 0 test(s), skipped 0 test(s)\n',
    '2023-02-26T11:20:05.274Z workers Jest Test Run Complete (c6izy): 2023-02-26T11:20:05.271Z\n',
    '2023-02-26T11:20:05.275Z workers [c6izy] Sandbox is responsive, closing it\n',
    "2023-02-26T11:20:05.275Z workers Failed to map the stack to user code, entry message: ENOENT: no such file or directory, open '/private/var/folders/9j/_kkh8f6x1png7hhtw04xp0rr0000gp/T/jest_dy/jest-transform-cache-5c07f724696870e5f35fec58e440d363-abc22ad5e77a7416ef9c18e131733e53/b8/sumtest_b82ebc2301f36e262d8fd4e8f6c3fa8e.wallaby.718304486', stack: Error: ENOENT: no such file or directory, open '/private/var/folders/9j/_kkh8f6x1png7hhtw04xp0rr0000gp/T/jest_dy/jest-transform-cache-5c07f724696870e5f35fec58e440d363-abc22ad5e77a7416ef9c18e131733e53/b8/sumtest_b82ebc2301f36e262d8fd4e8f6c3fa8e.wallaby.718304486'\n" +
      '    at Object.openSync (node:fs:600:3)\n' +
      '    at writeFileSync (<homeDir>/Library/Caches/JetBrains/WebStorm2022.2/wallaby/wallaby/node_modules/write-file-atomic/lib/index.js:209:13)\n' +
      '    at s (<homeDir>/Library/Caches/JetBrains/WebStorm2022.2/wallaby/wallaby/runners/node/jest@24.8.0/initializer.js:15:3306)\n' +
      '    at TsJestTransformer.e.process (<homeDir>/Library/Caches/JetBrains/WebStorm2022.2/wallaby/wallaby/runners/node/jest@24.8.0/initializer.js:15:6257)\n' +
      '    at ScriptTransformer.transformSource (<homeDir>/projects/wallaby-issue-reproduction/node_modules/@jest/transform/build/ScriptTransformer.js:542:31)\n' +
      '    at ScriptTransformer._transformAndBuildScript (<homeDir>/projects/wallaby-issue-reproduction/node_modules/@jest/transform/build/Sc\n',
    '2023-02-26T11:20:05.276Z project Test run finished\n',
    '2023-02-26T11:20:05.276Z project Processed console.log entries\n',
    '2023-02-26T11:20:05.276Z project Processed loading sequences\n',
    '2023-02-26T11:20:05.276Z project Processed executed tests\n',
    '2023-02-26T11:20:05.276Z project Processed code coverage\n',
    '2023-02-26T11:20:05.279Z project Test run result processed and sent to IDE\n',
    '2023-02-26T11:20:35.871Z fs No metadata for added file found: .idea/workspace.xml\n',
    '2023-02-26T11:20:35.871Z fs File changed: .idea/workspace.xml\n',
    '2023-02-26T11:20:35.871Z fs No metadata for changed file found: .idea/workspace.xml\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
Thanks for providing the diagnostics report and the repo. Can you please try a couple of things:
- try stopping Wallaby, running `yarn run jest --clearCache` command in your repo, and starting Wallaby.
- if the previous suggestion doesn't work, the issue may be related to your expired license and outdated Wallaby Core (v`1.0.1328`). The current version is `1.0.1386`, your version is 6 months old and there may have been some Jest breaking changes that were fixed in the latest version of Wallaby. Please try [installing trial of the latest Wallaby version](https://wallabyjs.com/download/) to see if it fixes the issue for you.

**Comment by mmazur122** [comment]
Thanks for the suggestions. Clearing Jest cache didn't work and I was already running the most recent plugin version for Webstorm which was updated 4 days ago. However, resetting Wallaby cache did the trick. Thanks for help!
