### ISSUE TITLE
React native expo project not allowing for the import keyword 

### ISSUE THREAD

**Issue by bj97301** [wallabyjs/public#3194]
### Issue description or question

React native expo project not allowing for the import keyword

### Wallaby diagnostics report
I am using the auto-config. 

```
{
  editorVersion: '1.76.2',
  pluginVersion: '1.0.351',
  editorType: 'VSCode',
  osVersion: 'darwin 22.3.0',
  nodeVersion: 'v16.19.1',
  coreVersion: '1.0.1403',
  checksum: 'NGMxZjc4ZmM5N2JjMGEyNDVhZGU0ZDFhZGE0MjkyMzEsMTcxMTQ5NzYwMDAwMCww',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/private/var/folders/1w/74gf8glj0tj1t5nblsx800nc0000gs/T/jest_e1',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/code/AwesomeProject',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: undefined,
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              fakeTimers: { enableGlobally: false },
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { defaultPlatform: 'ios', platforms: [ 'android', 'ios', 'native' ] },
              id: '89606061999bcc03d5a06a9b6959b1f9',
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [
                'js',   'mjs',
                'cjs',  'jsx',
                'ts',   'tsx',
                'json', 'node'
              ],
              moduleNameMapper: [],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              openHandlesTimeout: 1000,
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/code/AwesomeProject',
              roots: [ '<homeDir>/code/AwesomeProject' ],
              runner: '<homeDir>/code/AwesomeProject/node_modules/jest-runner/build/index.js',
              runtime: undefined,
              sandboxInjectedGlobals: [],
              setupFiles: [ '<homeDir>/code/AwesomeProject/node_modules/react-native/jest/setup.js', '<homeDir>/code/AwesomeProject/node_modules/jest-expo/src/preset/setup.js' ],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: { escapeString: false, printBasicPrototype: false },
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/code/AwesomeProject/node_modules/react-native/jest/react-native-env.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<homeDir>/code/AwesomeProject/node_modules/jest-circus/runner.js',
              transform: [
                [ '^.+\\.(js|ts|tsx)$', '<homeDir>/code/AwesomeProject/node_modules/babel-jest/build/index.js', {} ],
                [
                  '^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp|ttf|otf|m4v|mov|mp4|mpeg|mpg|webm|aac|aiff|caf|m4a|mp3|wav|html|pdf|obj)$',
                  '<homeDir>/code/AwesomeProject/node_modules/jest-expo/src/preset/assetFileTransformer.js',
                  {}
                ]
              ],
              transformIgnorePatterns: [
                'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)'
              ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            ci: false,
            collectCoverage: false,
            collectCoverageFrom: [],
            coverageDirectory: '<homeDir>/code/AwesomeProject/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 9,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            openHandlesTimeout: 1000,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [],
            randomize: undefined,
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/code/AwesomeProject',
            runTestsByPath: false,
            seed: -1513708735,
            shard: undefined,
            showSeed: undefined,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: { escapeString: false, printBasicPrototype: false },
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/code/AwesomeProject/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true,
            workerIdleMemoryLimit: undefined,
            workerThreads: false
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/|android/|ios/', '/private/var/folders/1w/74gf8glj0tj1t5nblsx800nc0000gs/T/jest_e1', '\\./coverage' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/|android/|ios/', '/private/var/folders/1w/74gf8glj0tj1t5nblsx800nc0000gs/T/jest_e1', '\\./coverage' ],
            testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    dot: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, file: true, test: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/|android/|ios/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\/|android\/|ios\//,
        ignore: true,
        trigger: true,
        load: true,
        file: true,
        test: true
      },
      {
        pattern: '/private/var/folders/1w/74gf8glj0tj1t5nblsx800nc0000gs/T/jest_e1',
        regexp: /\/private\/var\/folders\/1w\/74gf8glj0tj1t5nblsx800nc0000gs\/T\/jest_e1/,
        ignore: true,
        trigger: true,
        load: true,
        file: true,
        test: true
      },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true, file: true }
    ],
    captureConsoleLog: true,
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true, file: false },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/|android/|ios/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\/|android\/|ios\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true,
        file: false
      },
      {
        pattern: '/private/var/folders/1w/74gf8glj0tj1t5nblsx800nc0000gs/T/jest_e1',
        regexp: /\/private\/var\/folders\/1w\/74gf8glj0tj1t5nblsx800nc0000gs\/T\/jest_e1/,
        ignore: true,
        trigger: true,
        load: true,
        test: true,
        file: false
      },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '<homeDir>/.nvm/versions/node/v16.19.1/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: false,
    configCode: 'auto.detect#2033992156'
  },
  packageJSON: {
    dependencies: {
      '@expo/webpack-config': '^18.0.1',
      '@types/react': '~18.0.27',
      expo: '~48.0.9',
      'expo-status-bar': '~1.4.4',
      jest: '^29.2.1',
      'jest-expo': '^48.0.2',
      react: '18.2.0',
      'react-dom': '18.2.0',
      'react-native': '0.71.4',
      'react-native-web': '~0.18.10',
      typescript: '^4.9.4'
    },
    devDependencies: { '@babel/core': '^7.20.0', '@types/jest': '^29.5.0' }
  },
  fs: { numberOfFiles: 15 },
  debug: [
    '2023-03-29T18:25:08.322Z config Attempting automatic configuration for angular\n',
    '2023-03-29T18:25:08.328Z angular/cli config Angular CLI not found.\n',
    '2023-03-29T18:25:08.328Z config Finished attempting automatic configuration for angular (6ms)\n',
    '2023-03-29T18:25:08.329Z config Attempting automatic configuration for jest\n',
    '2023-03-29T18:25:08.577Z jest/config Detected Jest.\n',
    '2023-03-29T18:25:08.577Z jest/config Configured Jest.\n',
    '2023-03-29T18:25:08.577Z config Finished attempting automatic configuration for jest (248ms)\n',
    '2023-03-29T18:25:08.579Z project Wallaby Node version: v16.19.1\n',
    '2023-03-29T18:25:08.580Z project Wallaby config: <homeDir>/code/AwesomeProject/auto.detect\n',
    '2023-03-29T18:25:08.596Z fs File system starting\n',
    '2023-03-29T18:25:08.644Z fs File system scan completed\n',
    '2023-03-29T18:25:08.655Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.351/projects/73ef1adc9f669159\n',
    '2023-03-29T18:25:08.664Z uiService Listening port 51236\n',
    '2023-03-29T18:25:08.671Z project package.json file change detected, invalidating local cache\n',
    '2023-03-29T18:25:08.680Z workers Parallelism for initial run: 8, for regular run: 4\n',
    '2023-03-29T18:25:08.681Z workers Starting run worker instance #0\n',
    '2023-03-29T18:25:08.681Z workers Starting run worker instance #1\n',
    '2023-03-29T18:25:08.681Z workers Starting run worker instance #2\n',
    '2023-03-29T18:25:08.681Z workers Starting run worker instance #3\n',
    '2023-03-29T18:25:08.681Z workers Starting run worker instance #4\n',
    '2023-03-29T18:25:08.681Z workers Starting run worker instance #5\n',
    '2023-03-29T18:25:08.681Z workers Starting run worker instance #6\n',
    '2023-03-29T18:25:08.681Z workers Starting run worker instance #7\n',
    '2023-03-29T18:25:08.683Z workers Web server is listening at 57213\n',
    '2023-03-29T18:25:08.683Z project File cache requires some updates, waiting required files from IDE\n',
    '2023-03-29T18:25:08.791Z extended-core New file or complex file change\n',
    '2023-03-29T18:25:08.815Z project Stopping process pool\n',
    '2023-03-29T18:25:08.818Z project Test run started; run priority: 3\n',
    '2023-03-29T18:25:08.822Z project Running all tests\n',
    '2023-03-29T18:25:08.824Z workers Starting test run, priority: 3\n',
    '2023-03-29T18:25:08.824Z nodeRunner Starting sandbox [worker #0, session #c18vs]\n',
    '2023-03-29T18:25:08.825Z nodeRunner Preparing sandbox [worker #0, session #c18vs]\n',
    '2023-03-29T18:25:09.005Z workers Started run worker instance (delayed) #0\n',
    '2023-03-29T18:25:09.006Z nodeRunner Prepared sandbox [worker #0, session #c18vs]\n',
    '2023-03-29T18:25:09.007Z workers [worker #0, session #c18vs] Running tests in sandbox\n',
    '2023-03-29T18:25:09.015Z workers Started run worker instance (delayed) #2\n',
    '2023-03-29T18:25:09.016Z workers Started run worker instance (delayed) #1\n',
    '2023-03-29T18:25:09.052Z workers Started run worker instance (delayed) #3\n',
    '2023-03-29T18:25:09.053Z workers Started run worker instance (delayed) #4\n',
    '2023-03-29T18:25:09.072Z workers Started run worker instance (delayed) #5\n',
    '2023-03-29T18:25:09.095Z workers Started run worker instance (delayed) #7\n',
    '2023-03-29T18:25:09.097Z workers Started run worker instance (delayed) #6\n',
    '2023-03-29T18:25:11.730Z workers Scheduling Jest Test Run (c18vs): 2023-03-29T18:25:09.894Z\n',
    '2023-03-29T18:25:11.744Z workers Sandbox (active) [c18vs] error: Jest encountered an unexpected token\n' +
      '\n' +
      'Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.\n' +
      '\n' +
      'Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.\n' +
      '\n' +
      'By default "node_modules" folder is ignored by transformers.\n' +
      '\n' +
      "Here's what you can do:\n" +
      ' ‚Ä¢ If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.\n' +
      ' ‚Ä¢ If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript\n' +
      ' ‚Ä¢ To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.\n' +
      ' ‚Ä¢ If you need a custom transformation specify a "transform" option in your config.\n' +
      ' ‚Ä¢ If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.\n' +
      '\n' +
      "You'll find more details and examples of these config options in the docs:\n" +
      'https://jestjs.io/docs/configuration\n' +
      'For information about custom transformations, see:\n' +
      'https://jestjs.io/docs/code-transformation\n' +
      '\n' +
      'Details:\n' +
      '\n' +
      './App.jsx:2\n' +
      "import { StatusBar } from 'expo-status-bar';\n" +
      '^^^^^^\n' +
      '\n' +
      'SyntaxError: Cannot use import statement outside a module\n' +
      '    at new Script (node:vm:100:7)\n' +
      '    at Runtime.createScriptFromCode (./node_modules/jest-runtime/build/index.js:1495:14)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1389:25)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:1013:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:873:12)\n' +
      '    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:1039:21)\n' +
      '    at Object.<anonymous> (./__tests__/App-test.tsx:5:55)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1429:24)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:1013:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:873:12)\n' +
      '    at jestAdapter (./node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:77:13)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at runTestInternal (./node_modules/jest-runner/build/runTest.js:367:16)\n' +
      '    at runTest (./node_modules/jest-runner/build/runTest.js:444:34)\n',
    '2023-03-29T18:25:11.748Z workers [c18vs] Run 0 test(s), skipped 0 test(s)\n',
    '2023-03-29T18:25:11.749Z workers Jest Test Run Complete (c18vs): 2023-03-29T18:25:11.722Z\n',
    '2023-03-29T18:25:11.757Z workers [c18vs] Sandbox is responsive, closing it\n',
    '2023-03-29T18:25:11.760Z project Test run finished\n',
    '2023-03-29T18:25:11.760Z project Processed console.log entries\n',
    '2023-03-29T18:25:11.760Z project Processed loading sequences\n',
    '2023-03-29T18:25:11.760Z project Processed executed tests\n',
    '2023-03-29T18:25:11.761Z project Processed code coverage\n',
    '2023-03-29T18:25:11.771Z project Test run result processed and sent to IDE\n',
    '2023-03-29T18:25:14.409Z fs No metadata for added file found: .git/FETCH_HEAD\n',
    '2023-03-29T18:28:26.816Z fs File changed: .git/FETCH_HEAD\n',
    '2023-03-29T18:28:26.817Z fs No metadata for changed file found: .git/FETCH_HEAD\n'
  ]
}
```

when I start wallaby I get this error:

```
‌0 failing tests, 0 passing  ​Launch Coverage & Test Explorer​ | ​Search Tests​

Cannot use import statement outside a module 
  ​​​​​at ​​​​​​App.jsx:1​
  ​​​​​at Object.<anonymous> ​​​​​​__tests__/App-test.tsx:7:1​



```

**Comment by smcenlly** [comment]
Do your tests run when using the command-line? i.e. `npx jest`?

We tried creating a new `expo` project with `jest` tests, and it is working for us (please see [here](https://github.com/wallabyjs/wallaby-3194)).

Could you please try cloning the repo and see if it works for you? If it does, can you please compare against your project configuration and see if you can update the repo to break in the same way?

**Comment by bj97301** [comment]
@smcenlly thank you for the quick and excellent reply.  Your repo works.  Let me try and figure out what went wrong with mine.  I ran this command `npx create-expo-app AwesomeProject` and then added some jest dependencies but otherwise, it's untouched.  

I was wondering why line 4 in your repo was orange:
<img width="900" alt="Screenshot 2023-03-29 at 5 12 51 PM" src="https://user-images.githubusercontent.com/1450431/228696100-5fa5dcac-9dd3-4612-84dd-a1378f57b41f.png">

This would be the exact line that is giving me issues(the import).

**Comment by smcenlly** [comment]
> I was wondering why line 4 in your repo was orange:

You may see this from time to time in Wallaby code, depending on what your development tools are doing. It's not uncommon to see this for imports, depending on what your compiler is doing.

As your code gets transformed by your compiler, your import can be changed. For example, in the screenshot above, the `import` is changed to a `require` statement. Sometimes the declaration is split into multiple parts. Again, for the above example, the import is changed from:


```javascript
import { MonoText } from '../StyledText';
```

to

```javascript
var _StyledText = require("../StyledText");
```

But you will noticed that `MonoText` is no longer included. This is likely why it's showing as partially covered in the example above.

**Comment by bj97301** [comment]
ahhhh.  This makes a lot of sense.  Thank you 😊.  I gotta say I always receive top notch help from wallaby.  I really appreciate it ♥️.

**Comment by bj97301** [comment]
ok i figured it out.  Looks like my file was a jsx file and yours is a tsx file.  When I convert yours to jsx I get the same error.  I will probably just use typescript(I am trying not to be old and stuck in my ways) but at the same time I am wondering why the jsx file isn't working:

<img width="1728" alt="Screenshot 2023-03-29 at 6 34 31 PM" src="https://user-images.githubusercontent.com/1450431/228705456-0d6c86b8-2bd6-4c4e-af07-8e45d80f7245.png">

**Comment by smcenlly** [comment]
What you'll probably find is that in this case, the `.jsx` file `imports` statements are not being processed / compiled to `require` statements. Glad you've figured it out. I'll close the issue.

**Comment by bj97301** [comment]
Let me know if I should ask somewhere else but do you know why they are not being processed correctly?

**Comment by smcenlly** [comment]
Not sure off the top of my head but you get the same result using the `jest` CLI. I assume some missing babel import transforms when using `jsx` files instead of `tsx`.

**Comment by bj97301** [comment]
Got it. Yes. I will check this out. Thank you.

**Comment by bj97301** [comment]
This did the trick: 
https://forums.expo.dev/t/jest-expo-cannot-use-import-statement-outside-a-module/53525/2

```

"jest": {
    "preset": "jest-expo",
    "transform": {"\\.[jt]sx?$": "babel-jest"},
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*)"
    ]
  },

```
<img width="1728" alt="Screenshot 2023-03-29 at 8 39 12 PM" src="https://user-images.githubusercontent.com/1450431/228722599-493b2b80-dc33-4426-be03-97a37fe99a9b.png">
