### ISSUE TITLE
Broken config while migrating to newer react(native) 

### ISSUE THREAD

**Issue by ProLoser** [wallabyjs/public#3195]
### Broken config while migrating to newer react(native) 

<img width="766" alt="image" src="https://user-images.githubusercontent.com/67395/228687191-9308cbc4-aee2-4904-a70c-2a467e0b6eaa.png">
 This is the configuration I'm using and the errors I've been seeing

Previously I was using wallaby with great success on react 16 but we are migrating to react 18 and now I'm seeing lots of failures. I'm a little confused what's going on. We do have some custom babel presets due to a custom react native environment but I'm not sure where or how to use them appropriately in this config.

### Wallaby diagnostics report

```
{
  editorVersion: '1.76.2',
  pluginVersion: '1.0.351',
  editorType: 'VSCode',
  osVersion: 'darwin 22.3.0',
  nodeVersion: 'v12.22.12',
  coreVersion: '1.0.1403',
  checksum: 'OWQwZWViNTRlYWZjYzM2MWE4ODAyYzBhZTdiNGMzMzAsMTY4MTI1NzYwMDAwMCwx',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/private/var/folders/g6/cmpq70p17b7_dlp5w2s_1l3dwskktw/T/jest_xqm730',
              clearMocks: true,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/Sites/my-project',
              dependencyExtractor: undefined,
              detectLeaks: undefined,
              detectOpenHandles: undefined,
              displayName: undefined,
              errorOnDeprecated: false,
              extraGlobals: [],
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { defaultPlatform: 'custom', platforms: [ 'custom' ] },
              injectGlobals: true,
              moduleDirectories: [ 'node_modules', 'packages/*/node_modules' ],
              moduleFileExtensions: [ 'js', 'json', 'jsx', 'ts', 'tsx', 'node' ],
              moduleLoader: undefined,
              moduleNameMapper: [],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              name: '2b3e50592ae2ad3e81c5696d026c98b2',
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: '<homeDir>/Sites/my-project/node_modules/react-native-custom/jest/resolver.custom.js',
              restoreMocks: false,
              rootDir: '<homeDir>/Sites/my-project',
              roots: [ '<homeDir>/Sites/my-project' ],
              runner: 'jest-runner',
              setupFiles: [ '<homeDir>/Sites/my-project/node_modules/react-native-custom/jest/setup.custom.js', '<homeDir>/Sites/my-project/scripts/jest-setup.js' ],
              setupFilesAfterEnv: [ '<homeDir>/Sites/my-project/node_modules/@testing-library/jest-native/extend-expect.js' ],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/Sites/my-project/node_modules/jest-environment-jsdom/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '<homeDir>/Sites/my-project/packages/*/src/**/__tests__/**/*test.[jt]s?(x)' ],
              testPathIgnorePatterns: [],
              testRegex: [],
              testRunner: '<homeDir>/Sites/my-project/node_modules/jest-jasmine2/build/index.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [
                [ '^.+\\.[jt]sx?$', '<homeDir>/Sites/my-project/node_modules/babel-jest/build/index.js', {} ],
                [
                  '.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga|dds|ogg|json.resource)$',
                  '<homeDir>/Sites/my-project/node_modules/react-native-custom/jest/assetFileTransformer.js',
                  {}
                ],
                [ '^.+\\.(js|ts|tsx)$', '<homeDir>/Sites/my-project/node_modules/babel-jest/build/index.js', {} ],
                [ '^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$', '<homeDir>/Sites/my-project/node_modules/react-native-custom/jest/assetFileTransformer.js', {} ]
              ],
              transformIgnorePatterns: [
                'node_modules/@testing-library/jest-native/',
                'node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native|@react-native-community|@my-org)'
              ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: [],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<homeDir>/Sites/my-project/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: undefined,
            detectOpenHandles: undefined,
            enabledTestsMap: undefined,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: undefined,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 11,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: undefined,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/Sites/my-project',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/Sites/my-project/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/g6/cmpq70p17b7_dlp5w2s_1l3dwskktw/T/jest_xqm730', '\\./coverage' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/g6/cmpq70p17b7_dlp5w2s_1l3dwskktw/T/jest_xqm730', '\\./coverage' ],
            testMatch: [ 'packages/*/src/**/__tests__/**/*test.[jt]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    dot: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, file: true, test: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        file: true,
        test: true
      },
      {
        pattern: '/private/var/folders/g6/cmpq70p17b7_dlp5w2s_1l3dwskktw/T/jest_xqm730',
        regexp: /\/private\/var\/folders\/g6\/cmpq70p17b7_dlp5w2s_1l3dwskktw\/T\/jest_xqm730/,
        ignore: true,
        trigger: true,
        load: true,
        file: true,
        test: true
      },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'packages/*/src/**/__tests__/**/*test.[jt]s?(x)', ignore: true, trigger: true, load: true, file: true }
    ],
    captureConsoleLog: true,
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true, file: false },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true,
        file: false
      },
      {
        pattern: '/private/var/folders/g6/cmpq70p17b7_dlp5w2s_1l3dwskktw/T/jest_xqm730',
        regexp: /\/private\/var\/folders\/g6\/cmpq70p17b7_dlp5w2s_1l3dwskktw\/T\/jest_xqm730/,
        ignore: true,
        trigger: true,
        load: true,
        test: true,
        file: false
      },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'packages/*/src/**/__tests__/**/*test.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    smartStart: [ { test: true, source: false, pattern: '**/*', startMode: 'open' }, { test: false, source: true, pattern: '**/*', startMode: 'edit' } ],
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: true,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '<homeDir>/.local/share/nvm/v12.22.12/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: false,
    configCode: 'auto.detect#-1976378613',
    testLocations: [ 'packages/core/src/Video/__tests__/NativeVideo-test.js' ]
  },
  packageJSON: {
    dependencies: undefined,
    devDependencies: {
      react: '18.1.0',
      'react-native-custom': '^0.70.6-0.8',
      '@babel/core': '^7.20.12',
      '@babel/preset-typescript': '^7.14.5',
      '@babel/runtime': '^7.4.4',
      '@my-org/eslint-config-react-native-app': '^5.0.0',
      '@my-org/babel-preset-reactnativecustom': '^3.0.0',
      '@testing-library/react-native': '^12.0.0',
      '@testing-library/jest-native': '^5.4.1',
      'react-test-renderer': '^18.0.0',
      '@types/jest': '^25.2.3',
      '@types/react': '^18.0.26',
      '@types/react-native': '^0.70.6',
      '@types/react-test-renderer': '^18.0.0',
      '@typescript-eslint/eslint-plugin': '^4.16.1',
      '@typescript-eslint/parser': '^4.16.1',
      chalk: '^2.4.2',
      eslint: '^6.6.0',
      'fs-extra': '^7.0.1',
      gulp: '^4.0.0',
      'gulp-footer': '^2.0.2',
      'gulp-header': '^2.0.9',
      'gulp-rename': '^2.0.0',
      'gulp-string-replace': '^1.1.2',
      husky: '^3.0.5',
      jest: '^26.6.3',
      jsdom: '^16.2.0',
      lolex: '^5.1.1',
      prettier: '^2.3.1',
      rimraf: '^3.0.2',
      'rmrf-promise': '^1.1.0',
      rollup: '^2.22.2',
      'rollup-plugin-babel': '^4.3.2',
      'rollup-plugin-json': '^4.0.0',
      'rollup-plugin-node-resolve': '^5.0.1',
      'rollup-plugin-terser': '^6.0.0',
      'simple-git': '^1.126.0',
      typescript: '4.9.5',
      'write-json-file': '^4.2.0'
    }
  },
  fs: { numberOfFiles: 1317 },
  debug: [
    '2023-03-29T23:13:21.917Z config Attempting automatic configuration for angular\n',
    '2023-03-29T23:13:21.921Z angular/cli config Angular CLI not found.\n',
    '2023-03-29T23:13:21.921Z config Finished attempting automatic configuration for angular (4ms)\n',
    '2023-03-29T23:13:21.921Z config Attempting automatic configuration for jest\n',
    '2023-03-29T23:13:22.075Z jest/config Detected Jest.\n',
    '2023-03-29T23:13:22.075Z jest/config Configured Jest.\n',
    '2023-03-29T23:13:22.075Z config Finished attempting automatic configuration for jest (154ms)\n',
    '2023-03-29T23:13:22.077Z project Wallaby Node version: v12.22.12\n',
    '2023-03-29T23:13:22.077Z project Wallaby config: <homeDir>/Sites/my-project/auto.detect\n',
    '2023-03-29T23:13:22.090Z fs File system starting\n',
    '2023-03-29T23:13:22.352Z fs File system scan completed\n',
    '2023-03-29T23:13:22.367Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.351/projects/33ecdab4dddc52b6\n',
    '2023-03-29T23:13:22.483Z uiService Listening port 51235\n',
    '2023-03-29T23:13:22.522Z workers Parallelism for initial run: 10, for regular run: 5\n',
    '2023-03-29T23:13:22.522Z workers Starting run worker instance #0\n',
    '2023-03-29T23:13:22.522Z workers Starting run worker instance #1\n',
    '2023-03-29T23:13:22.522Z workers Starting run worker instance #2\n',
    '2023-03-29T23:13:22.522Z workers Starting run worker instance #3\n',
    '2023-03-29T23:13:22.522Z workers Starting run worker instance #4\n',
    '2023-03-29T23:13:22.522Z workers Starting run worker instance #5\n',
    '2023-03-29T23:13:22.522Z workers Starting run worker instance #6\n',
    '2023-03-29T23:13:22.522Z workers Starting run worker instance #7\n',
    '2023-03-29T23:13:22.522Z workers Starting run worker instance #8\n',
    '2023-03-29T23:13:22.522Z workers Starting run worker instance #9\n',
    '2023-03-29T23:13:22.524Z workers Web server is listening at 64424\n',
    '2023-03-29T23:13:22.560Z project Stopping process pool\n',
    '2023-03-29T23:13:22.560Z project File cache is up-to-date, starting full test run\n',
    '2023-03-29T23:13:22.561Z project Test run started; run priority: 3\n',
    '2023-03-29T23:13:22.565Z project Running all tests\n',
    '2023-03-29T23:13:22.607Z project Test run finished\n',
    '2023-03-29T23:13:22.607Z project Test run data re-queued\n',
    '2023-03-29T23:13:22.855Z workers Started run worker instance (delayed) #5\n',
    '2023-03-29T23:13:22.856Z workers Started run worker instance (delayed) #7\n',
    '2023-03-29T23:13:22.890Z workers Started run worker instance (delayed) #3\n',
    '2023-03-29T23:13:22.893Z workers Started run worker instance (delayed) #4\n',
    '2023-03-29T23:13:22.900Z project Requested to run all tests\n',
    '2023-03-29T23:13:22.901Z project Test run started; run priority: 3\n',
    '2023-03-29T23:13:22.901Z project Running all tests\n',
    '2023-03-29T23:13:22.918Z workers Starting test run, priority: 3\n',
    '2023-03-29T23:13:22.918Z nodeRunner Starting sandbox [worker #0, session #djog9]\n',
    '2023-03-29T23:13:22.918Z nodeRunner Preparing sandbox [worker #0, session #djog9]\n',
    '2023-03-29T23:13:22.924Z workers Started run worker instance (delayed) #2\n',
    '2023-03-29T23:13:22.925Z workers Started run worker instance (delayed) #0\n',
    '2023-03-29T23:13:22.925Z nodeRunner Prepared sandbox [worker #0, session #djog9]\n',
    '2023-03-29T23:13:22.925Z workers [worker #0, session #djog9] Running tests in sandbox\n',
    '2023-03-29T23:13:22.929Z workers Started run worker instance (delayed) #1\n',
    '2023-03-29T23:13:22.930Z workers Started run worker instance (delayed) #8\n',
    '2023-03-29T23:13:22.933Z workers Started run worker instance (delayed) #6\n',
    '2023-03-29T23:13:22.978Z workers Started run worker instance (delayed) #9\n',
    '2023-03-29T23:13:27.696Z workers Scheduling Jest Test Run (djog9): 2023-03-29T23:13:23.942Z\n',
    '2023-03-29T23:13:27.698Z workers Sandbox (active) [djog9] error: Jest encountered an unexpected token\n' +
      '\n' +
      "This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.\n" +
      '\n' +
      'By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".\n' +
      '\n' +
      "Here's what you can do:\n" +
      ' • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.\n' +
      ' • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.\n' +
      ' • If you need a custom transformation specify a "transform" option in your config.\n' +
      ' • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.\n' +
      '\n' +
      "You'll find more details and examples of these config options in the docs:\n" +
      'https://jestjs.io/docs/en/configuration.html\n' +
      '\n' +
      'Details:\n' +
      '\n' +
      './node_modules/@testing-library/jest-native/dist/to-be-disabled.js:21\n' +
      "    if ((0, utils_1.getType)(element) === 'TextInput' && element?.props?.editable === false) {\n" +
      '                                                                 ^\n' +
      '\n' +
      "SyntaxError: Unexpected token '.'\n" +
      '    at new Script (vm.js:88:7)\n' +
      '    at Runtime.createScriptFromCode (./node_modules/jest-runtime/build/index.js:1350:14)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1245:25)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:898:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:746:10)\n' +
      '    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:919:21)\n' +
      '    at Object.<anonymous> (./node_modules/@testing-library/jest-native/dist/extend-expect.js:3:26)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1299:24)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:898:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:746:10)\n' +
      '    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:919:21)\n' +
      '    at Object.<anonymous> (./node_modules/@testing-library/jest-native/extend-expect.js:1:90)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1299:24)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:898:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:746:10)\n' +
      '    at jasmine2 (./node_modules/jest-jasmine2/build/index.js:204:15)\n' +
      '    at runTestInternal (./node_modules/jest-runner/build/runTest.js:380:22)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n' +
      '    at runTest (./node_modules/jest-runner/build/runTest.js:472:34)\n',
    '2023-03-29T23:13:27.699Z workers [djog9] Run 0 test(s), skipped 0 test(s)\n',
    '2023-03-29T23:13:27.699Z workers Jest Test Run Complete (djog9): 2023-03-29T23:13:27.691Z\n',
    '2023-03-29T23:13:27.700Z workers [djog9] Sandbox is responsive, closing it\n',
    "2023-03-29T23:13:27.702Z workers Failed to map the stack to user code, entry message: Unexpected token '.', stack: Jest encountered an unexpected token\n" +
      '\n' +
      "This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.\n" +
      '\n' +
      'By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".\n' +
      '\n' +
      "Here's what you can do:\n" +
      ' • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.\n' +
      ' • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.\n' +
      ' • If you need a custom transformation specify a "transform" option in your config.\n' +
      ' • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.\n' +
      '\n' +
      "You'll find more details and examples of these config options in the docs:\n" +
      'https://jestjs.io/docs/en/configuration.html\n' +
      '\n' +
      'Details:\n' +
      '\n' +
      '<homeDir>/Sites/my-project/node_modules/@testing-library/jest-native/dist/to-be-disabled.js:21\n' +
      '    if ((0, utils_1.getType)(element) ===\n',
    '2023-03-29T23:13:27.702Z project Test run finished\n',
    '2023-03-29T23:13:27.703Z project Processed console.log entries\n',
    '2023-03-29T23:13:27.703Z project Processed loading sequences\n',
    '2023-03-29T23:13:27.703Z project Processed executed tests\n',
    '2023-03-29T23:13:27.706Z project Processed code coverage\n',
    '2023-03-29T23:13:27.726Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by smcenlly** [comment]
Is `jest` working from the CLI when you run `npx jest`? If not, you'll want to get this working first.

> We do have some custom babel presets due to a custom react native environment but I'm not sure where or how to use them appropriately in this config.

Are you able to share a couple of sample repos working with `react 16` and failing with `react 18` so we can see for ourselves what is going on?

**Comment by ProLoser** [comment]
Yes `jest` works when run from command line. I will have to get back to you about the sample repos, it's a very complicated unfortunately.

**Comment by ProLoser** [comment]
This was the config on the previous configuration. Am I correct in understanding that the `files` need to be in reverse order with earlier imports at the end of the array?

```
module.exports = function(wallaby) {
  return {
    files: [
      'packages/*/src/**/*.js',
      '!packages/*/src/**/__tests__/**/*.js',
      'scripts/jest-setup.js',
      { pattern: 'packages/*/package.json', instrument: false, load: true },
      { pattern: 'babel.config.js', instrument: false, load: true },
    ],
    tests: ['packages/*/src/**/__tests__/**/*.js'],
    testFramework: 'jest',
    env: {
      type: 'node',
      runner: 'node',
    },
    compilers: {
      '**/*.js': wallaby.compilers.babel(),
    },
  };
};
```

Some notes I've been wondering about:
- We don't use `.babelrc` we use `babel.config.js`, does this get automatically detected or do I need to just include it in my `files` array?
- `jest-setup.js` is used as `setupFiles: ['./scripts/jest-setup.js'],` in our `jest.config.js` of which we have one sitting at the project root
- We mock JSDom for a subset of tests that run in a WebView

**Comment by ProLoser** [comment]
Thank you for this feedback! 

I use fish and NVM to handle node versions. What would be the best way to configure vscode wallaby to use the appropriate nvm version?

**Comment by smcenlly** [comment]
The previous issue response from https://github.com/wallabyjs/public/issues/1116#issuecomment-1245361991 should help, setting up a [Wallaby.js configuration file](https://wallabyjs.com/docs/intro/config.html#configuration-file) (see below).

We're not familiar with `fish` but you could extend the script below as you need.

> People who want to use the node version based on their local `.nvmrc` file can use this:
> 
> ```js
> const path = require('path');
> const fs = require('fs');
> const { execSync } = require('child_process');
> 
> const nvmrcPath = path.join(__dirname, '.nvmrc');
> 
> function getNodePathFromNvm() {
> 	let nvmrcVersion;
> 	try {
> 		nvmrcVersion = fs.readFileSync(nvmrcPath, 'utf8').toString();
> 	} catch (e) {
> 		console.error('Failed to read .nvmrc file', e);
> 
> 		throw new Error('Failed to read .nvmrc file');
> 	}
> 
> 	const loadNvmScriptPath = path.join(process.env.NVM_DIR, 'nvm.sh');
> 
> 	// Will equal /Users/<user>/.nvm/versions/node/<version>/bin/node on Mac for example
> 	return execSync(`source ${loadNvmScriptPath} && nvm which ${nvmrcVersion}`).toString().trim();
> }
> 
> function getNodeFromNvmrcOrNone() {
> 	// Meaning that no nvm exists
> 	if (!process.env.NVM_DIR) {
> 		return undefined;
> 	}
> 
> 	if (!fs.existsSync(nvmrcPath)) {
> 		return undefined;
> 	}
> 
> 	return getNodePathFromNvm();
> }
> 
> module.exports = function () {
> 	const config = {
> 		autoDetect: true,
> 		smartStart: [{ startMode: 'edit' }],
> 		instrument: false
> 	};
> 
> 	const nodeVersionPath = getNodeFromNvmrcOrNone();
> 	if (nodeVersionPath) {
> 		config.env = {
> 			type: 'node',
> 			runner: nodeVersionPath
> 		};
> 	}
> 
> 	return config;
> };
> 
> ```
