### ISSUE TITLE
Jest + @swc/jest tests fail in Wallaby, work in terminal

### ISSUE THREAD

**Issue by milang** [wallabyjs/public#3198]
### Issue description or question
We have been using Wallaby to run Jest tests with `@swc/jest` runner for a long time, without any issues. However, today the tests started failing with:

```
‍​[Info]​ Started Wallaby.js Core v1.0.1407
​[Info]​ Wallaby App (realtime reports) is available at: http://localhost:51245
​[Info]​ console.log: Jest: FAIL src/utils/fileExtension.test.ts
​[Info]​ console.log: Jest:   ● Test suite failed to run
​[Info]​     Failed to deserialize buffer as swc::config::Options
​[Info]​     JSON: {"jsc":{"target":"es2023","transform":{"hidden":{"jest":true}}},"sourceMaps":"inline","module":{"type":"commonjs"},"filename":"C:\\Users\\milang\\dev\\MobileWebApp\\src\\utils\\fileExtension.test.ts"}
​[Info]​     Caused by:
​[Info]​         unknown variant `es2023`, expected one of `es3`, `es5`, `es2015`, `es2016`, `es2017`, `es2018`, `es2019`, `es2020`, `es2021`, `es2022`, `esnext` at line 1 column 200
​[Info]​       at Compiler.transformSync (node_modules/@swc/core/index.js:241:29)
​[Info]​       at transformSync (node_modules/@swc/core/index.js:348:21)
​[Info]​       at Object.process (node_modules/@swc/jest/index.js:73:45)
​[Info]​       at Object.e.process (../../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.351/wallaby100696/runners/node/jest@24.8.0/initializer.js:15:8115)
​[Info]​       at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:542:31)
​[Info]​       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:671:40)
​[Info]​       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:723:19)
```

Our `.swcrc` file specifies `es2021` as the target, so I do not understand why is Wallaby trying to use the unsupported `es2023` variant:

```jsonc
{
    "$schema": "https://json.schemastore.org/swcrc",
    "jsc": {
        "target": "es2021",
        "parser": {
            "syntax": "typescript",
            "tsx": true
        },
        // ...
    }
}
```

Please note that running tests in the terminal works without issues.

**Comment by milang** [comment]
Actually, `@swc/jest` just published a new version, `0.2.26`, and Wallaby works again. It seems the failure was caused by `@swc/jest@0.2.25`, not Wallaby.
