### ISSUE TITLE
How to completely remove partially installed Wallaby in webstorm

### ISSUE THREAD

**Issue by sheltonial** [wallabyjs/public#32]
Due to some proxy issues we have a machine where Wallaby has been partially installed (I suspect). When running wallaby in webstorm the run window does not appear but there is a spinner in the bottom right hand corner of webstorm that does not stop.

What files need to be removed in order to get the machine back to a state where wallaby is completely removed, so we can try a fresh re-install of the plugin?

**Comment by ArtemGovorov** [comment]
On Mac OSX delete ~/Library/Caches/WebStorm9/wallaby folder. 
On Windows delete <SYSTEM DRIVE>\Users\<USER ACCOUNT NAME>\.<PRODUCT><VERSION>\system\wallaby folder.

**Comment by ArtemGovorov** [comment]
If it doesn't help, please attach the end of the idea.log file (in IDE menu Help - Show Log).

**Comment by sheltonial** [comment]
Has not worked unfortunately. The OS is Windows too. Here is the log:

```
015-03-05 16:47:49,250 [ 239757] ERROR - til.concurrency.QueueProcessor - org/java_websocket/client/WebSocketClient 
java.lang.NoClassDefFoundError: org/java_websocket/client/WebSocketClient
  at com.wallaby.javascript.WallabyController.a(Unknown Source)
  at com.wallaby.javascript.execution.g.execute(Unknown Source)
  at com.wallaby.javascript.execution.WallabyProgramRunner.doExecute(Unknown Source)
  at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
  at com.intellij.execution.RunProfileStarter.execute(RunProfileStarter.java:39)
  at com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java:203)
  at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:131)
  at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:243)
  at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:40)
  at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:64)
  at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
  at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:53)
  at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
  at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:94)
  at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:375)
  at com.intellij.execution.impl.ExecutionManagerImpl.access$400(ExecutionManagerImpl.java:60)
  at com.intellij.execution.impl.ExecutionManagerImpl$4.run(ExecutionManagerImpl.java:368)
  at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
  at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
  at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:318)
  at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
  at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
  at java.awt.EventQueue.access$400(EventQueue.java:97)
  at java.awt.EventQueue$3.run(EventQueue.java:697)
  at java.awt.EventQueue$3.run(EventQueue.java:691)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
  at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
  at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
  at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
  at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
  at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
  at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.java_websocket.client.WebSocketClient PluginClassLoader[wallaby.js, 1.0.1]
  at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 37 more
2015-03-05 16:47:49,257 [ 239764] ERROR - til.concurrency.QueueProcessor - WebStorm 9.0.3 Build #WS-139.
```

**Comment by ArtemGovorov** [comment]
Could you please try downloading and installing this version http://update.wallabyjs.com/wallaby-intellij-v1.0.2.zip on that machine?

**Comment by sheltonial** [comment]
All working now. The wallaby plugin was first unzipped and installed from that folder. Apparently Webstorm happily allows you to do this but doesn't copy the jar files it requires.

**Comment by ArtemGovorov** [comment]
Awesome, so the issue was that the downloaded zip was unzipped before installing? I should probably make it clear in the readme file that unzipping is not required.

**Comment by sheltonial** [comment]
Correct. Thanks for your help.

**Comment by sheltonial** [comment]
I see that webstorm allows JAR or ZIP files when installing a plugin from disk. Perhaps if the file was a JAR instead people would be less inclined to "unzip"

**Comment by ArtemGovorov** [comment]
You are right, I will have a look if I can just rename it.
