### ISSUE TITLE
Wallaby not working in Nx based react app

### ISSUE THREAD

**Issue by Animesh-Maji** [wallabyjs/public#3200]
### Issue description or question

I am using Nx in my react app. I want to integrate wallaby for testing, everytime I start wallaby it fails to run tests.

### Wallaby diagnostics report

```
{
  editorVersion: '1.77.3',
  pluginVersion: '1.0.351',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.23430',
  nodeVersion: 'v18.14.0',
  coreVersion: '1.0.1179',
  checksum: 'YzQxZDUxOGU0YWNiMjkzOGZhMzk4NDc0NDBlODkxOGEsMTYzNzk3MTIwMDAwMCww',
  config: {
    diagnostics: {
      angular: {
        workspace: {
          '$schema': './node_modules/nx/schemas/workspace-schema.json',
          version: 2,
          projects: {
            '.-data-access-rtk': 'libs/data-access/rtk',
            '.-features-feature-primary-filters': 'libs/features/feature-primary-filters',
            '.-ui-breadcrumb': 'libs/ui/breadcrumb',
            '.-ui-ui-side-drawer': 'libs/ui/ui-side-drawer',
            '.-utils-helpers': 'libs/utils/helpers',
            '.-utils-root-props': 'libs/utils/root-props',
            '.-utils-util-form-wrapper': 'libs/utils/util-form-wrapper',
            api: 'apps/api',
            iconic: 'apps/iconic',
            utilities: 'libs/utilities'
          }
        }
      },
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: 'C:\\Users\\anime\\AppData\\Local\\Temp\\jest',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '\\\\node_modules\\\\' ],
              cwd: 'D:\\Internship\\web\\DPR\\apps\\iconic',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: { color: 'white', name: 'iconic' },
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [ '.ts', '.tsx' ],
              fakeTimers: { enableGlobally: false },
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: true, throwOnModuleCollision: false },
              id: 'a7a94e39e2dfc2c77f203cf46dbe0207',
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [ 'ts', 'tsx', 'js', 'jsx' ],
              moduleNameMapper: [],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: 'D:\\Internship\\web\\DPR\\node_modules\\@nrwl\\jest\\plugins\\resolver.js',
              restoreMocks: false,
              rootDir: 'D:\\Internship\\web\\DPR\\apps\\iconic',
              roots: [ 'D:\\Internship\\web\\DPR\\apps\\iconic' ],
              runner: 'D:\\Internship\\web\\DPR\\node_modules\\jest-runner\\build\\index.js',
              runtime: undefined,
              sandboxInjectedGlobals: [],
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: 'D:\\Internship\\web\\DPR\\node_modules\\jest-environment-jsdom\\build\\index.js',
              testEnvironmentOptions: { customExportConditions: [ 'node', 'require', 'default' ] },
              testLocationInResults: false,
              testMatch: [ '**/?(*.)+(spec|test).[jt]s?(x)' ],
              testPathIgnorePatterns: [ '\\\\node_modules\\\\' ],
              testRegex: [],
              testRunner: 'D:\\Internship\\web\\DPR\\node_modules\\jest-circus\\runner.js',
              transform: [
                [ '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)', 'D:\\Internship\\web\\DPR\\node_modules\\@nrwl\\react\\plugins\\jest.js', {} ],
                [ '^.+\\.[tj]sx?$', 'D:\\Internship\\web\\DPR\\node_modules\\jest-cli\\node_modules\\babel-jest\\build\\index.js', { presets: [ '@nrwl/react/babel' ] } ],
                [ '^.+\\.(ts|js|html)$', 'D:\\Internship\\web\\DPR\\node_modules\\ts-jest\\dist\\index.js', {} ]
              ],
              transformIgnorePatterns: [ '\\\\node_modules\\\\(?!@sabide\\\\ui-comps)' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            ci: false,
            collectCoverage: false,
            collectCoverageFrom: [],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: 'D:\\Internship\\web\\DPR\\coverage\\apps\\iconic',
            coverageProvider: 'babel',
            coverageReporters: [ 'lcov', 'json' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 5,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [],
            replname: undefined,
            reporters: [ [ 'default', {} ], [ 'D:\\Internship\\web\\DPR\\node_modules\\jest-junit\\index.js', {} ] ],
            rootDir: 'D:\\Internship\\web\\DPR\\apps\\iconic',
            runTestsByPath: false,
            shard: undefined,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: undefined,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: 'D:\\Internship\\web\\DPR\\node_modules\\@jest\\test-sequencer\\build\\index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '\\\\node_modules\\\\', '\\.\\\\dist\\\\|\\.\\\\build\\\\|\\.\\\\coverage\\\\|\\.\\\\git\\\\|\\\\\\..+\\\\' ],
            testPathIgnorePatterns: [ '\\\\node_modules\\\\', '\\.\\\\dist\\\\|\\.\\\\build\\\\|\\.\\\\coverage\\\\|\\.\\\\git\\\\|\\\\\\..+\\\\' ],
            testMatch: [ '**/?(*.)+(spec|test).[jt]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    micromatch: true,
    files: [
      { pattern: '\\\\node_modules\\\\', regexp: /\\node_modules\\/, ignore: true, trigger: true, load: true },
      {
        pattern: '\\.\\\\dist\\\\|\\.\\\\build\\\\|\\.\\\\coverage\\\\|\\.\\\\git\\\\|\\\\\\..+\\\\',
        regexp: /\.\\dist\\|\.\\build\\|\.\\coverage\\|\.\\git\\|\\\..+\\/,
        ignore: true,
        trigger: true,
        load: true
      },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '**/?(*.)+(spec|test).[jt]s?(x)', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '\\\\node_modules\\\\', regexp: /\\node_modules\\/, ignore: true, trigger: true, load: true, test: true },
      {
        pattern: '\\.\\\\dist\\\\|\\.\\\\build\\\\|\\.\\\\coverage\\\\|\\.\\\\git\\\\|\\\\\\..+\\\\',
        regexp: /\.\\dist\\|\.\\build\\|\.\\coverage\\|\.\\git\\|\\\..+\\/,
        ignore: true,
        trigger: true,
        load: true,
        test: true
      },
      { pattern: '**/?(*.)+(spec|test).[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    addModifiedTestFileToExclusiveTestRun: true,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: 'C:\\Program Files\\nodejs\\node.exe', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#-394811061'
  },
  fs: { numberOfFiles: 346 },
  debug: [
    '2023-04-16T06:06:44.547Z angular/cli config Detected Angular CLI.\n',
    '2023-04-16T06:06:44.551Z angular/cli config TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined\n' +
      '    at new NodeError (node:internal/errors:399:5)\n' +
      '    at validateString (node:internal/validators:163:11)\n' +
      '    at Object.join (node:path:429:7)\n' +
      '    at c:\\Users\\anime\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.351\\wallaby09ea3c\\server.js:16:15764\n' +
      '    at Array.find (<anonymous>)\n' +
      '    at c:\\Users\\anime\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.351\\wallaby09ea3c\\server.js:16:15728\n' +
      '    at n (c:\\Users\\anime\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.351\\wallaby09ea3c\\server.js:16:18628)\n' +
      '    at Object.next (c:\\Users\\anime\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.351\\wallaby09ea3c\\server.js:16:17923)\n' +
      '    at o (c:\\Users\\anime\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.351\\wallaby09ea3c\\server.js:16:17682)\n',
    '2023-04-16T06:06:44.553Z angular/cli config Angular.json: \n' +
      ' {\n' +
      "  '$schema': './node_modules/nx/schemas/workspace-schema.json',\n" +
      '  version: 2,\n' +
      '  projects: {\n' +
      "    '.-data-access-rtk': 'libs/data-access/rtk',\n" +
      "    '.-features-feature-primary-filters': 'libs/features/feature-primary-filters',\n" +
      "    '.-ui-breadcrumb': 'libs/ui/breadcrumb',\n" +
      "    '.-ui-ui-side-drawer': 'libs/ui/ui-side-drawer',\n" +
      "    '.-utils-helpers': 'libs/utils/helpers',\n" +
      "    '.-utils-root-props': 'libs/utils/root-props',\n" +
      "    '.-utils-util-form-wrapper': 'libs/utils/util-form-wrapper',\n" +
      "    api: 'apps/api',\n" +
      "    iconic: 'apps/iconic',\n" +
      "    utilities: 'libs/utilities'\n" +
      '  }\n' +
      '}\n',
    '2023-04-16T06:06:44.553Z angular/cli config TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined\n' +
      '    at new NodeError (node:internal/errors:399:5)\n' +
      '    at validateString (node:internal/validators:163:11)\n' +
      '    at Object.join (node:path:429:7)\n' +
      '    at c:\\Users\\anime\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.351\\wallaby09ea3c\\server.js:16:15764\n' +
      '    at Array.find (<anonymous>)\n' +
      '    at c:\\Users\\anime\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.351\\wallaby09ea3c\\server.js:16:15728\n' +
      '    at n (c:\\Users\\anime\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.351\\wallaby09ea3c\\server.js:16:18628)\n' +
      '    at Object.next (c:\\Users\\anime\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.351\\wallaby09ea3c\\server.js:16:17923)\n' +
      '    at o (c:\\Users\\anime\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.351\\wallaby09ea3c\\server.js:16:17682)\n',
    '2023-04-16T06:06:46.614Z jest/config Detected Jest.\n',
    '2023-04-16T06:06:46.614Z jest/config Configured Jest.\n',
    '2023-04-16T06:06:46.616Z project Wallaby Node version: v18.14.0\n',
    '2023-04-16T06:06:46.616Z project Wallaby config: D:\\Internship\\web\\DPR\\apps\\iconic\\auto.detect\n',
    '2023-04-16T06:06:47.013Z project File cache: C:\\Users\\anime\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.351\\projects\\28e3bc54f70c0a5c\n',
    '2023-04-16T06:06:47.179Z uiService Listening port 51235\n',
    '2023-04-16T06:06:47.215Z workers Parallelism for initial run: 4, for regular run: 2\n',
    '2023-04-16T06:06:47.215Z workers Starting run worker instance #0\n',
    '2023-04-16T06:06:47.215Z workers Starting run worker instance #1\n',
    '2023-04-16T06:06:47.215Z workers Starting run worker instance #2\n',
    '2023-04-16T06:06:47.215Z workers Starting run worker instance #3\n',
    '2023-04-16T06:06:47.216Z workers Web server is listening at 51305\n',
    '2023-04-16T06:06:47.216Z project File cache requires some updates, waiting required files from IDE\n',
    '2023-04-16T06:06:47.333Z project Stopping process pool\n',
    '2023-04-16T06:06:47.336Z project Test run started; run priority: 3\n',
    '2023-04-16T06:06:47.337Z project Running all tests\n',
    '2023-04-16T06:06:47.344Z workers Starting test run, priority: 3\n',
    '2023-04-16T06:06:47.344Z workers Distributing tests between 4 workers\n',
    '2023-04-16T06:06:47.346Z workers Running tests in parallel\n',
    '2023-04-16T06:06:47.347Z nodeRunner Starting sandbox [worker #0, session #6zslz]\n',
    '2023-04-16T06:06:47.347Z nodeRunner Starting sandbox [worker #1, session #tpj0x]\n',
    '2023-04-16T06:06:47.347Z nodeRunner Starting sandbox [worker #2, session #b51cj]\n',
    '2023-04-16T06:06:47.347Z nodeRunner Starting sandbox [worker #3, session #28pav]\n',
    '2023-04-16T06:06:47.347Z nodeRunner Preparing sandbox [worker #0, session #6zslz]\n',
    '2023-04-16T06:06:47.347Z nodeRunner Preparing sandbox [worker #1, session #tpj0x]\n',
    '2023-04-16T06:06:47.347Z nodeRunner Preparing sandbox [worker #2, session #b51cj]\n',
    '2023-04-16T06:06:47.347Z nodeRunner Preparing sandbox [worker #3, session #28pav]\n',
    '2023-04-16T06:06:47.406Z workers Started run worker instance (delayed) #1\n',
    '2023-04-16T06:06:47.407Z nodeRunner Prepared sandbox [worker #1, session #tpj0x]\n',
    '2023-04-16T06:06:47.407Z workers [worker #1, session #tpj0x] Running tests in sandbox\n',
    '2023-04-16T06:06:47.411Z workers Started run worker instance (delayed) #0\n',
    '2023-04-16T06:06:47.411Z nodeRunner Prepared sandbox [worker #0, session #6zslz]\n',
    '2023-04-16T06:06:47.411Z workers [worker #0, session #6zslz] Running tests in sandbox\n',
    '2023-04-16T06:06:47.423Z workers Started run worker instance (delayed) #2\n',
    '2023-04-16T06:06:47.424Z nodeRunner Prepared sandbox [worker #2, session #b51cj]\n',
    '2023-04-16T06:06:47.424Z workers [worker #2, session #b51cj] Running tests in sandbox\n',
    '2023-04-16T06:06:47.448Z workers Started run worker instance (delayed) #3\n',
    '2023-04-16T06:06:47.448Z nodeRunner Prepared sandbox [worker #3, session #28pav]\n',
    '2023-04-16T06:06:47.448Z workers [worker #3, session #28pav] Running tests in sandbox\n',
    '2023-04-16T06:06:51.541Z workers Scheduling Jest Test Run (6zslz): 2023-04-16T06:06:50.997Z\n',
    '2023-04-16T06:06:51.542Z workers Jest Test Error: 2023-04-16T06:06:51.536Z\n',
    '2023-04-16T06:06:51.543Z workers Jest Test Run Complete (6zslz): 2023-04-16T06:06:51.538Z\n',
    '2023-04-16T06:06:51.543Z workers [6zslz] Run 0 test(s), skipped 0 test(s)\n',
    '2023-04-16T06:06:51.545Z workers [6zslz] Sandbox is responsive, closing it\n',
    '2023-04-16T06:06:51.587Z workers Scheduling Jest Test Run (28pav): 2023-04-16T06:06:51.079Z\n',
    '2023-04-16T06:06:51.588Z workers Jest Test Error: 2023-04-16T06:06:51.581Z\n',
    '2023-04-16T06:06:51.588Z workers Jest Test Run Complete (28pav): 2023-04-16T06:06:51.582Z\n',
    '2023-04-16T06:06:51.588Z workers [28pav] Run 0 test(s), skipped 0 test(s)\n',
    '2023-04-16T06:06:51.590Z workers [28pav] Sandbox is responsive, closing it\n',
    '2023-04-16T06:06:51.602Z workers Scheduling Jest Test Run (b51cj): 2023-04-16T06:06:51.092Z\n',
    '2023-04-16T06:06:51.603Z workers Jest Test Error: 2023-04-16T06:06:51.596Z\n',
    '2023-04-16T06:06:51.603Z workers Jest Test Run Complete (b51cj): 2023-04-16T06:06:51.598Z\n',
    '2023-04-16T06:06:51.604Z workers [b51cj] Run 0 test(s), skipped 0 test(s)\n',
    '2023-04-16T06:06:51.605Z workers [b51cj] Sandbox is responsive, closing it\n',
    '2023-04-16T06:06:51.680Z workers Scheduling Jest Test Run (tpj0x): 2023-04-16T06:06:51.168Z\n',
    '2023-04-16T06:06:51.680Z workers Jest Test Error: 2023-04-16T06:06:51.674Z\n',
    '2023-04-16T06:06:51.680Z workers Jest Test Run Complete (tpj0x): 2023-04-16T06:06:51.676Z\n',
    '2023-04-16T06:06:51.681Z workers [tpj0x] Run 0 test(s), skipped 0 test(s)\n',
    '2023-04-16T06:06:51.683Z workers [tpj0x] Sandbox is responsive, closing it\n',
    '2023-04-16T06:06:51.683Z workers Merging parallel test run results\n',
    '2023-04-16T06:06:51.684Z project Test run finished\n',
    '2023-04-16T06:06:51.685Z project Processed console.log entries\n',
    '2023-04-16T06:06:51.685Z project Processed loading sequences\n',
    '2023-04-16T06:06:51.685Z project Processed executed tests\n',
    '2023-04-16T06:06:51.686Z project Processed code coverage\n',
    '2023-04-16T06:06:51.690Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
Your Wallaby Core version is very outdated because your license has expired ~18 months ago, and it may not be compatible with the current version of your dependencies, so you may need to renew your license. 

Please try getting our trial license to update to the [latest Wallaby Core](https://wallabyjs.com/download/) to see if it fixes the issue.

**Comment by smcenlly** [comment]
I'm going to assume that the latest version of Wallaby fixed the problem and close this issue. If you're still having problems using the latest version, please provide an updated Wallaby Diagnostics report and we will re-open this issue.
