### ISSUE TITLE
Smart Configuration fails on Nx 16

### ISSUE THREAD

**Issue by wescopeland** [wallabyjs/public#3214]
### Issue description or question

After upgrading to Nx 16 and Next.js 13.3, Wallaby.js smart configuration no longer works.

I have confirmed that all my local testing commands, **including npx jest** are still successful.

---

### Video recording

https://github.com/wallabyjs/public/assets/3984985/0c718061-822f-4989-b93b-8a49f7ada92c

---

### Wallaby diagnostics report

As shown in the video, there does not seem to be a command available in the VSCode Command Palette for copying a diagnostics report.

Here is the output in "Wallaby.js Tests":

```
‌[Error] Automatic Angular CLI configuration error: Failed to read Jest configuration from '.': Error: Jest: Failed to parse the TypeScript config file ./apps/home-web/jest.config.ts 
[Error]   TypeError: Cannot read properties of undefined (reading 'data') 
[Error]     at readConfigFileAndSetRootDir (./node_modules/jest-config/build/readConfigFileAndSetRootDir.js:116:13) 
[Error]     at processTicksAndRejections (node:internal/process/task_queues:96:5) 
[Error]     at async readInitialOptions (./node_modules/jest-config/build/index.js:400:13) 
[Error]     at async readConfig (./node_modules/jest-config/build/index.js:147:48) 
[Error]     at async Promise.all (index 17) 
[Error]     at async Object.readConfigs (./node_modules/jest-config/build/index.js:440:27) 
[Error]  
[Error] We've also tried to automatically configure Wallaby.js for other frameworks 
[Error] Automatic Jest configuration error: Failed to read Jest configuration from '.': Error: Jest: Failed to parse the TypeScript config file ./apps/home-web/jest.config.ts 
[Error]   TypeError: Cannot read properties of undefined (reading 'data') 
[Error]     at readConfigFileAndSetRootDir (./node_modules/jest-config/build/readConfigFileAndSetRootDir.js:116:13) 
[Error]     at processTicksAndRejections (node:internal/process/task_queues:96:5) 
[Error]     at async readInitialOptions (./node_modules/jest-config/build/index.js:400:13) 
[Error]     at async readConfig (./node_modules/jest-config/build/index.js:147:48) 
[Error]     at async Promise.all (index 17) 
[Error]     at async Object.readConfigs (./node_modules/jest-config/build/index.js:440:27) 
[Error] Automatic Vitest configuration error: Vitest dependency not found. 
[Error]     at processTicksAndRejections (node:internal/process/task_queues:96:5) 
```

Here is the output in "Wallaby.js Console":

```
‍​[Info]​ Started Wallaby.js Core v1.0.1420
​[Info]​ info  - Loaded env from /Users/wescopeland/Documents/GitHub/advisor-site/advisor-node/apps/home-web/.env.local
​[Info]​ info  - Loaded env from /Users/wescopeland/Documents/GitHub/advisor-site/advisor-node/apps/home-web/.env.production
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/shared-data-access-property-managers-api" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/shared-data-access-geolocation-api" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/shared-data-access-search-api" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/shared-feature-standard-leads" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/shared-feature-user-favorites" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/shared-feature-verified-leads" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/utils-split-testing-engine" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/shared-feature-cms-slots" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/ui-content-components" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/shared-feature-auth" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/ui-core-components" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/ui-react-obfuscate" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/ui-design-system" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/ui-analytics" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/utils-common" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/utils-photos" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/ui-layouts" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/shared-data-access-property-managers-api" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/shared-data-access-geolocation-api" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/shared-data-access-search-api" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/shared-feature-standard-leads" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/shared-feature-user-favorites" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/shared-feature-verified-leads" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/utils-split-testing-engine" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/shared-feature-cms-slots" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/ui-content-components" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/shared-feature-auth" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/ui-core-components" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/ui-react-obfuscate" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/ui-design-system" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/ui-analytics" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/utils-common" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/utils-photos" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] ● Validation Warning:​​
​​[Error]   Unknown option "coverageDirectory" with value "../../coverage/libs/ui-layouts" was found.​​
​​[Error]   This is probably a typing mistake. Fixing it will remove this message.​​
​​[Error]   Configuration Documentation:​​
​​[Error]   https://jestjs.io/docs/configuration​​
​​[Error] Failed to load configuration file: Automatic Angular CLI configuration error: Failed to read Jest configuration from '.': Error: Jest: Failed to parse the TypeScript config file ./apps/home-web/jest.config.ts​​
​​[Error]   TypeError: Cannot read properties of undefined (reading 'data')​​
​​[Error]     at readConfigFileAndSetRootDir (./node_modules/jest-config/build/readConfigFileAndSetRootDir.js:116:13)​​
​​[Error]     at processTicksAndRejections (node:internal/process/task_queues:96:5)​​
​​[Error]     at async readInitialOptions (./node_modules/jest-config/build/index.js:400:13)​​
​​[Error]     at async readConfig (./node_modules/jest-config/build/index.js:147:48)​​
​​[Error]     at async Promise.all (index 17)​​
​​[Error]     at async Object.readConfigs (./node_modules/jest-config/build/index.js:440:27)​​
​​[Error] We've also tried to automatically configure Wallaby.js for other frameworks​​
​​[Error] Automatic Jest configuration error: Failed to read Jest configuration from '.': Error: Jest: Failed to parse the TypeScript config file ./apps/home-web/jest.config.ts​​
​​[Error]   TypeError: Cannot read properties of undefined (reading 'data')​​
​​[Error]     at readConfigFileAndSetRootDir (./node_modules/jest-config/build/readConfigFileAndSetRootDir.js:116:13)​​
​​[Error]     at processTicksAndRejections (node:internal/process/task_queues:96:5)​​
​​[Error]     at async readInitialOptions (./node_modules/jest-config/build/index.js:400:13)​​
​​[Error]     at async readConfig (./node_modules/jest-config/build/index.js:147:48)​​
​​[Error]     at async Promise.all (index 17)​​
​​[Error]     at async Object.readConfigs (./node_modules/jest-config/build/index.js:440:27)​​
​​[Error] Automatic Vitest configuration error: Vitest dependency not found.​​
​​[Error]     at processTicksAndRejections (node:internal/process/task_queues:96:5)​​
​​[Error] Please refer to our docs: https://wallabyjs.com/docs/config/overview.html ​​
```

**Comment by ArtemGovorov** [comment]
We have generated a new NX + Next workspace via `npx create-nx-workspace@latest --preset=next`, then generated a library into it via `nx g @nx/next:lib my-new-lib`, and then updated Jest configs in the root and in the lib project with your Jest configs. The sample repo is available here: https://github.com/wallabyjs/wallaby-3214.

When we run `npx jest` from the repo's root, we get the exact same error from Jest CLI without Wallaby:
<img width="1342" alt="Screen Shot 2023-05-15 at 1 11 27 pm" src="https://github.com/wallabyjs/public/assets/979966/0f408843-f295-4615-b24e-0b5f95a8fc4c">

Quick investigation points to what's possibly a compatibility issue in your library Jest config: https://github.com/wallabyjs/wallaby-3214/blob/main/libs/my-new-lib/jest.config.ts#L4-L8, because if you comment out lines 4-6 and uncomment line 8, then `npx jest` starts working as expected.

Can you please clone the sample repo, run `npm i` and verify that it's not working for you with your current lib config and is working with commenting out the `nextJest` call?

> I have confirmed that all my local testing commands, including npx jest are still successful.

As the issue doesn't seem to be related to Wallaby and is easily reproduced outside Wallaby via Jest CLI, I'm not sure how `npx jest` is working in your current repo. Maybe it is still working because your update to nx 16/next 13.3 is not complete and some older dependencies are still around. If you can create a sample repo (or update our sample repo) where `npx jest` is working, but Wallaby is failing with that specific error, we are happy to investigate.

**Comment by wescopeland** [comment]
No worries!

I can confirm most tests are pasing with the commented out `nextJest` call. I can also confirm most tests pass when using Wallaby.js under this circumstance.

The only issue is now any test using experimental decorators fails, even after setting `experimentalDecorators` and `emitDecoratorMetadata` to true in all tsconfig*.json files. I suspect this is because some config is lost when `nextJest` is omitted.

**Comment by ArtemGovorov** [comment]
@wescopeland Is `npx jest` failing too for the decorators use or it's just Wallaby? If it's Wallaby specific, can you please add an example to the https://github.com/wallabyjs/wallaby-3214 sample repo?
