### ISSUE TITLE
Wallabyjs stopped working - File missing from TS compilation

### ISSUE THREAD

**Issue by jasonhick** [wallabyjs/public#3232]
### Issue description or question
Help! WallbyJs has stopped working in VS Code. What do I need to do to fix this?

The error below keeps getting thrown:
[Error] Error: /Users/HNFS/Sites/gfdtv-ui-portal-staff/src/app/app.component.spec.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property. 

### Wallaby diagnostics report
```
{
  editorVersion: '1.78.2',
  pluginVersion: '1.0.356',
  editorType: 'VSCode',
  osVersion: 'darwin 22.3.0',
  nodeVersion: 'v14.20.1',
  coreVersion: '1.0.1427',
  checksum: 'NGFiZTViOWU1Y2IxOGI0ZWQxNDEyMjU1ODM2ZWJlYmYsMTcwNjA1NDQwMDAwMCww',
  config: {
    diagnostics: {
      angular: {
        workspace: {
          '$schema': './node_modules/@angular/cli/lib/config/schema.json',
          version: 1,
          newProjectRoot: 'projects',
          projects: {
            'gfdtv-ui-portal-staff': {
              root: '',
              sourceRoot: 'src',
              projectType: 'application',
              prefix: 'app',
              schematics: { '@schematics/angular:component': { styleext: 'scss' } },
              architect: {
                build: {
                  builder: '@angular-devkit/build-angular:browser',
                  options: {
                    outputPath: 'dist/',
                    index: 'src/index.html',
                    main: 'src/main.ts',
                    polyfills: 'src/polyfills.ts',
                    tsConfig: 'src/tsconfig.app.json',
                    assets: [
                      { glob: 'favicon.ico', input: 'src/', output: '/' },
                      { glob: '**/*', input: 'src/assets/', ignore: [ '**/*.scss' ], output: '/assets/' },
                      { glob: '**/*', input: 'node_modules/gfdtv-ui-module-data-contracts-validator/dist/data-contracts-validator/assets', output: 'assets/' }
                    ],
                    styles: [ 'src/assets/scss/main.scss' ],
                    stylePreprocessorOptions: { includePaths: [ 'node_modules/gfdtv-ui-module-portal/dist', 'src/assets/scss' ] },
                    scripts: [
                      'node_modules/gfdtv-ui-module-analytics/dist/analytics-lib/bundles/gfdtv-analytics.min.js',
                      { bundleName: 'amazon-connect-streams', inject: true, input: './node_modules/amazon-connect-streams/release/connect-streams-min.js' }
                    ]
                  },
                  configurations: {
                    wiremock: {
                      fileReplacements: [
                        { replace: 'src/assets/config/config.json', with: 'src/environments/wiremock/config/local.config.json' },
                        { replace: 'src/assets/data/roles.data.json', with: 'src/environments/wiremock/data/roles.data.json' }
                      ]
                    },
                    wiremockRemote: {
                      fileReplacements: [
                        { replace: 'src/assets/config/config.json', with: 'src/environments/wiremock/config/remote.config.json' },
                        { replace: 'src/assets/data/roles.data.json', with: 'src/environments/wiremock/data/roles.data.json' }
                      ]
                    },
                    si: {
                      fileReplacements: [
                        { replace: 'src/assets/config/config.json', with: 'src/environments/si/config/config.json' },
                        { replace: 'src/assets/data/roles.data.json', with: 'src/environments/si/data/roles.data.json' }
                      ]
                    },
                    dev: {
                      fileReplacements: [
                        { replace: 'src/assets/config/config.json', with: 'src/environments/dev/config/config.json' },
                        { replace: 'src/assets/data/roles.data.json', with: 'src/environments/dev/data/roles.data.json' }
                      ]
                    },
                    qa: {
                      fileReplacements: [
                        { replace: 'src/assets/config/config.json', with: 'src/environments/qa/config/config.json' },
                        { replace: 'src/assets/data/roles.data.json', with: 'src/environments/qa/data/roles.data.json' }
                      ]
                    },
                    uat: {
                      fileReplacements: [
                        { replace: 'src/assets/config/config.json', with: 'src/environments/uat/config/config.json' },
                        { replace: 'src/assets/data/roles.data.json', with: 'src/environments/uat/data/roles.data.json' }
                      ]
                    },
                    uat2: {
                      fileReplacements: [
                        { replace: 'src/assets/config/config.json', with: 'src/environments/uat2/config/config.json' },
                        { replace: 'src/assets/data/roles.data.json', with: 'src/environments/uat2/data/roles.data.json' }
                      ]
                    },
                    training: {
                      fileReplacements: [
                        { replace: 'src/assets/config/config.json', with: 'src/environments/training/config/config.json' },
                        { replace: 'src/assets/data/roles.data.json', with: 'src/environments/training/data/roles.data.json' }
                      ]
                    },
                    production: {
                      fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.prod.ts' } ],
                      optimization: true,
                      outputHashing: 'all',
                      sourceMap: false,
                      extractCss: false,
                      namedChunks: false,
                      aot: true,
                      extractLicenses: true,
                      vendorChunk: false,
                      buildOptimizer: true,
                      budgets: [ { type: 'initial', maximumWarning: '2mb', maximumError: '5mb' } ]
                    }
                  }
                },
                serve: {
                  builder: '@angular-devkit/build-angular:dev-server',
                  options: { browserTarget: 'gfdtv-ui-portal-staff:build' },
                  configurations: {
                    wiremock: { browserTarget: 'gfdtv-ui-portal-staff:build:wiremock' },
                    wiremockRemote: { browserTarget: 'gfdtv-ui-portal-staff:build:wiremockRemote' },
                    si: { browserTarget: 'gfdtv-ui-portal-staff:build:si' },
                    dev: { browserTarget: 'gfdtv-ui-portal-staff:build:dev' },
                    qa: { browserTarget: 'gfdtv-ui-portal-staff:build:qa' },
                    uat: { browserTarget: 'gfdtv-ui-portal-staff:build:uat' },
                    uat2: { browserTarget: 'gfdtv-ui-portal-staff:build:uat2' },
                    training: { browserTarget: 'gfdtv-ui-portal-staff:build:training' },
                    production: { browserTarget: 'gfdtv-ui-portal-staff:build:production' }
                  }
                },
                'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: 'gfdtv-ui-portal-staff:build' } },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    main: 'src/test.ts',
                    polyfills: 'src/polyfills.ts',
                    tsConfig: 'src/tsconfig.spec.json',
                    karmaConfig: 'src/karma.conf.js',
                    styles: [ 'src/assets/scss/main.scss' ],
                    stylePreprocessorOptions: { includePaths: [ 'node_modules/gfdtv-ui-module-portal/dist', 'src/assets/scss' ] },
                    scripts: [
                      'src/assets/scripts/segment.js',
                      'node_modules/gfdtv-ui-module-analytics/dist/analytics-lib/bundles/gfdtv-analytics.min.js',
                      { bundleName: 'amazon-connect-streams', inject: true, input: './node_modules/amazon-connect-streams/release/connect-streams-min.js' }
                    ],
                    assets: [ 'src/favicon.ico', 'src/assets' ],
                    codeCoverageExclude: [ 'src/app/**/*.module.ts', '**/*.mock.ts' ]
                  }
                },
                lint: { builder: '@angular-devkit/build-angular:tslint', options: { tsConfig: [ 'src/tsconfig.app.json', 'src/tsconfig.spec.json' ], exclude: [ '**/node_modules/**' ] } }
              }
            }
          },
          defaultProject: 'gfdtv-ui-portal-staff'
        },
        main: '// This file is required by karma.conf.js and loads recursively all the .spec and framework files\n' +
          '// `zone.js` must be imported first: https://github.com/angular/angular/issues/18033\n' +
          "import 'zone.js/dist/zone-testing';\n" +
          '// tslint:disable-next-line:ordered-imports\n' +
          "import { getTestBed } from '@angular/core/testing';\n" +
          "import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';\n" +
          '\n' +
          "import 'hammerjs';\n" +
          '\n' +
          'declare const require: any;\n' +
          '\n' +
          '// First, initialize the Angular testing environment.\n' +
          'getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());\n' +
          '// Then we find all the tests.\n' +
          '\n' +
          '// And load the modules.\n' +
          '\n' +
          '\n' +
          '/**\n' +
          ' * Hacky speed fix\n' +
          ' *\n' +
          ' * Angular appends the styles for each element each time it is displayed, but\n' +
          ' * does not remove them when the test ends. This means that the browser has to\n' +
          ' * keep all the stylesheets in memory and work out if they should apply after\n' +
          ' * every dom update in every test.\n' +
          ' *\n' +
          ' * This snippet removes all <style> elements from the <head> after each test.\n' +
          ' * At time of writing, this resulted in a speed improvement from 2m40 to 1m30;\n' +
          ' * or roughly 40% faster for a full run.\n' +
          ' *\n' +
          ' * The DomSharedStylesHost alternative suggested in the link did not speed up\n' +
          ' * the suite. It might be worth revisiting after upgrading to a newer version\n' +
          " * of Angular. Note the prefix ('…µ') is a barred-o symbol, not a lowercase E.\n" +
          ' *\n' +
          ' * @link https://www.luminis.eu/blog/development-en/speed-up-angular-unit-test-duration/\n' +
          ' */\n' +
          'jasmine.getEnv().afterEach(() => {\n' +
          "    const head = document.getElementsByTagName('head')[0];\n" +
          "    const styles = head.getElementsByTagName('style');\n" +
          '\n' +
          '    Array.from(styles).forEach((style) => head.removeChild(style));\n' +
          '});\n'
      }
    },
    testFramework: { version: 'jasmine@3.10.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3', autoDetected: true },
    env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    files: [
      { pattern: 'src/**/*.spec.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/polyfills.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/test.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/main.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/index.html', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/test.base.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/test.wallaby.ts', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/assets/scripts/segment.js', instrument: false, load: true, ignore: false, trigger: true, order: 2 },
      { pattern: 'node_modules/gfdtv-ui-module-analytics/dist/analytics-lib/bundles/gfdtv-analytics.min.js', instrument: false, load: true, ignore: false, trigger: true, order: 3 },
      { pattern: 'src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 4 },
      { pattern: 'src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 5 }
    ],
    tests: [ { pattern: 'src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 6 } ],
    captureConsoleLog: true,
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: false,
    configCode: 'auto.detect#-409921241'
  },
  packageJSON: {
    dependencies: {
      '@angular/animations': '^8.2.14',
      '@angular/cdk': '^8.2.3',
      '@angular/common': '~8.2.14',
      '@angular/compiler': '~8.2.14',
      '@angular/core': '~8.2.14',
      '@angular/forms': '~8.2.14',
      '@angular/material': '^8.2.3',
      '@angular/platform-browser': '~8.2.14',
      '@angular/platform-browser-dynamic': '~8.2.14',
      '@angular/router': '~8.2.14',
      '@types/chai': '^4.1.7',
      '@types/cucumber': '^4.0.4',
      'amazon-connect-streams': '^1.6.6',
      'angular2-template-loader': '^0.6.2',
      chai: '^4.2.0',
      'core-js': '^2.5.4',
      'crypto-js': '^3.1.9-1',
      cucumber: '^5.1.0',
      'cucumber-html-report': '^0.6.5',
      dayjs: '^1.11.0',
      'gfdtv-ui-module-analytics': '^0.0.14',
      'gfdtv-ui-module-apm': '^2.0.0',
      'gfdtv-ui-module-config-service': '^1.2.1',
      'gfdtv-ui-module-data-contracts-store': '^1.8.0',
      'gfdtv-ui-module-data-contracts-validator': '^1.8.0',
      'gfdtv-ui-module-form-validators': '^2.3.7',
      'gfdtv-ui-module-idle-timeout': '^1.0.3',
      'gfdtv-ui-module-portal': '^2.4.2',
      'gfdtv-ui-module-storage': '^2.3.0',
      'gfdtv-ui-module-stripe-payments': '^1.2.1',
      glob: '^7.1.6',
      hammerjs: '^2.0.8',
      'jasmine-marbles': '^0.8.1',
      json2csv: '^5.0.6',
      moment: '^2.24.0',
      'multiple-cucumber-html-reporter': '^1.13.1',
      'ng-bullet': '^1.0.3',
      rxjs: '^6.5.5',
      'swagger-typescript-api': '^9.2.0',
      tslib: '^1.9.0',
      'wallaby-webpack': '^3.9.14',
      'zone.js': '~0.9.1'
    },
    devDependencies: {
      '@angular-devkit/build-angular': '~0.803.25',
      '@angular/cli': '^8.3.25',
      '@angular/compiler-cli': '^8.2.14',
      '@angular/language-service': '~8.2.14',
      '@cypress/webpack-preprocessor': '^5.1.2',
      '@types/cypress-cucumber-preprocessor': '^1.14.1',
      '@types/googlemaps': '^3.36.2',
      '@types/jasmine': '~2.8.8',
      '@types/jasminewd2': '~2.0.3',
      '@types/node': '^8.9.5',
      btoa: '^1.2.1',
      codelyzer: '^5.0.1',
      'cucumber-pretty': '^1.5.2',
      cypress: '^9.6.0',
      'cypress-cucumber-preprocessor': '^2.3.1',
      'cypress-terminal-report': '^3.3.4',
      'fs-extra': '^8.1.0',
      'gfdtv-ui-cli': '^1.3.0',
      'jasmine-core': '~2.99.1',
      'jasmine-spec-reporter': '~4.2.1',
      karma: '^4.1.0',
      'karma-chrome-launcher': '~3.1.0',
      'karma-coverage': '^1.1.2',
      'karma-coverage-istanbul-reporter': '~2.0.1',
      'karma-jasmine': '~1.1.2',
      'karma-jasmine-html-reporter': '^0.2.2',
      'karma-mocha-reporter': '^2.2.5',
      prettier: '^2.0.5',
      'remark-cli': '^10.0.1',
      'remark-lint': '^9.1.1',
      'remark-normalize-headings': '^3.0.1',
      'remark-preset-lint-recommended': '^6.1.2',
      'remark-toc': '^8.0.1',
      'request-promise': '^4.2.4',
      'sass-lint': '^1.12.1',
      'start-server-and-test': '^1.11.2',
      'ts-loader': '^7.0.1',
      'ts-node': '^7.0.1',
      tslint: '^5.14.0',
      'tslint-config-prettier': '^1.18.0',
      typescript: '~3.5.3',
      'typescript-strict-plugin': '^1.1.1',
      yargs: '^13.3.0'
    }
  },
  fs: { numberOfFiles: 1839 },
  debug: [
    '2023-06-07T09:23:38.836Z config Attempting automatic configuration for angular\n',
    '2023-06-07T09:23:38.840Z angular/cli config Detected Angular CLI.\n',
    '2023-06-07T09:23:38.842Z angular/cli config Angular currentDirPath: "<homeDir>/sites/gfdtv-ui-portal-staff", workspaceDirPath: "<homeDir>/sites/gfdtv-ui-portal-staff"\n',
    '2023-06-07T09:23:41.797Z angular/cli karma project config Using virtual <homeDir>/sites/gfdtv-ui-portal-staff/src/test.ts.\n',
    '2023-06-07T09:23:41.811Z config Finished attempting automatic configuration for angular (2975ms)\n',
    '2023-06-07T09:23:41.813Z project Wallaby Node version: v14.20.1\n',
    '2023-06-07T09:23:41.813Z project Wallaby config: <homeDir>/sites/gfdtv-ui-portal-staff/auto.detect\n',
    '2023-06-07T09:23:41.830Z fs File system starting\n',
    '2023-06-07T09:23:42.177Z fs File system scan completed\n',
    '2023-06-07T09:23:42.196Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.356/projects/a5bc63f9d78ea721_1\n',
    '2023-06-07T09:23:42.204Z uiService Listening port 51236\n',
    '2023-06-07T09:23:42.205Z project package.json file change detected, invalidating local cache\n',
    '2023-06-07T09:23:42.317Z chromeRunner launch new instance (path: <default>, flags: --headless --disable-gpu --deterministic-fetch)\n',
    '2023-06-07T09:23:42.341Z workers Parallelism for initial run: 10, for regular run: 5\n',
    '2023-06-07T09:23:42.341Z workers Starting run worker instance #0\n',
    '2023-06-07T09:23:42.341Z workers Starting run worker instance #1\n',
    '2023-06-07T09:23:42.341Z workers Starting run worker instance #2\n',
    '2023-06-07T09:23:42.341Z workers Starting run worker instance #3\n',
    '2023-06-07T09:23:42.341Z workers Starting run worker instance #4\n',
    '2023-06-07T09:23:42.341Z workers Starting run worker instance #5\n',
    '2023-06-07T09:23:42.341Z workers Starting run worker instance #6\n',
    '2023-06-07T09:23:42.342Z workers Starting run worker instance #7\n',
    '2023-06-07T09:23:42.342Z workers Starting run worker instance #8\n',
    '2023-06-07T09:23:42.342Z workers Starting run worker instance #9\n',
    '2023-06-07T09:23:42.345Z workers Web server is listening at 53069\n',
    '2023-06-07T09:23:42.352Z project Stopping process pool\n',
    '2023-06-07T09:23:42.352Z project File cache is up-to-date, starting full test run\n',
    '2023-06-07T09:23:42.353Z chromeRunner Connection to Chrome Debugger Protocol on 127.0.0.1:53068 failed: Error: connect ECONNREFUSED 127.0.0.1:53068\n',
    '2023-06-07T09:23:42.354Z project Running postprocessor\n',
    '2023-06-07T09:23:42.373Z postprocessor Processing started.\n',
    '2023-06-07T09:23:42.373Z postprocessor Initializing.\n',
    '2023-06-07T09:23:42.375Z postprocessor Initializing entry.\n',
    '2023-06-07T09:23:42.376Z postprocessor Sanitizing configuration.\n',
    '2023-06-07T09:23:42.376Z postprocessor Adjusting configuration.\n',
    '2023-06-07T09:23:42.377Z postprocessor Creating compiler.\n',
    '2023-06-07T09:23:42.455Z postprocessor Customizing compiler.\n',
    '2023-06-07T09:23:42.455Z postprocessor Compilation started.\n',
    '2023-06-07T09:24:00.505Z chromeRunner Connection to Chrome Debugger Protocol on 127.0.0.1:53068 succeeded\n',
    '2023-06-07T09:24:00.506Z workers Started run worker instance (immediate) #0\n',
    '2023-06-07T09:24:00.506Z workers Started run worker instance (immediate) #1\n',
    '2023-06-07T09:24:00.506Z workers Started run worker instance (immediate) #2\n',
    '2023-06-07T09:24:00.506Z workers Started run worker instance (immediate) #3\n',
    '2023-06-07T09:24:00.506Z workers Started run worker instance (immediate) #4\n',
    '2023-06-07T09:24:00.506Z workers Started run worker instance (immediate) #5\n',
    '2023-06-07T09:24:00.506Z workers Started run worker instance (immediate) #6\n',
    '2023-06-07T09:24:00.506Z workers Started run worker instance (immediate) #7\n',
    '2023-06-07T09:24:00.506Z workers Started run worker instance (immediate) #8\n',
    '2023-06-07T09:24:00.506Z workers Started run worker instance (immediate) #9\n',
    '2023-06-07T09:24:04.549Z project Error: <homeDir>/Sites/gfdtv-ui-portal-staff/src/app/app.component.spec.ts\n' +
      'Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):\n' +
      "Error: <homeDir>/Sites/gfdtv-ui-portal-staff/src/app/app.component.spec.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.\n" +
      '    at AngularCompilerPlugin.getCompiledFile (<homeDir>/sites/gfdtv-ui-portal-staff/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:913:23)\n' +
      '    at <homeDir>/sites/gfdtv-ui-portal-staff/node_modules/@ngtools/webpack/src/loader.js:41:31\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
      ' @ <homeDir>/Sites/gfdtv-ui-portal-staff/wallaby-webpack-entry.js 4:0-42\n' +
      '    at t.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.356/wallaby388d1e/server.js:23:20085)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.356/wallaby388d1e/server.js:23:16312)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.356/wallaby388d1e/server.js:23:15607)\n' +
      '    at o (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.356/wallaby388d1e/server.js:23:15366)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n',
    '2023-06-07T09:24:04.550Z project Test run finished\n',
    '2023-06-07T09:24:04.550Z project Test run data re-queued\n'
  ]
}
```

**Comment by jasonhick** [comment]
Hi @NikGovorov  Yes, the tests run perfectly outside of Wallaby. The site also compiles and serves as expected.

I've also tried uninstalling Wallaby in VSCode, clearing cache, updating VS Code, reboot! Lol!

### tsconfig.spec.json below

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "types": [
      "jasmine",
      "node",
      "googlemaps",
      "amazon-connect-streams"
    ]
  },
  "files": ["test.ts", "polyfills.ts"],
  "include": [
    "src/app/app.component.spec.ts",
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}

```

**Comment by jasonhick** [comment]
Apologies! I added `app.component.spec.ts` to the config to see if helped. Normally that line is not there, and this file definitely exists within the project at: `src/app/app.component.spec.ts`

I will clone the repo and try running it.

**Comment by jasonhick** [comment]
Ok, thanks for clearing that up. I have tried your repo and Wallaby works in there. I've also re-cloned my own repo (it's a large repo worked on by several devs) and am still unable to run Wallaby. I've copied over the config json files from your repo and get the same result.

I've also noticed that VS Code is also throwing an error in the notification bar:

<img width="474" alt="A case sensitive file rename has been detected. Close the renamed file and restart VS Code to continue using Wallaby." src="https://github.com/wallabyjs/public/assets/1746397/57d31c58-929c-4b8f-97bb-dfec82b60b4b">

Could this be related? I'm unable to find out what file it's referring to.

**Comment by jasonhick** [comment]
Here are a few scenarios I've tried:

> Open VS Code, no files open, run Smart Start
-- no errors, 0 failing tests, 0 passing

> As above, then open a .ts or .spec.ts file... 
-- "Case sensitive" notification appears,
-- Error in the console saying "[file_that_was_opened].spec.ts is missing from the TypeScript compilation.

> Open VS Code with a previously opened file
-- Same errors as above

> Stop Wallaby, delete `app.component.spec.ts`, start Wallaby
-- Wallaby complains that the next spec file is missing.

**Comment by jasonhick** [comment]
Thanks for investigating this.

I'm on a Macbook Pro running Ventura 13.2.1.
I only have 1 ~/Sites folder
There is no ~/sites folder, and I am unable to create one
I usually start VSCode using Spotlight search (CMD + Space > type Code > hit Enter  or by running `code .` from the terminal

I DO have an alias for my local repo which is all lowercase:
`alias staff="cd ~/sites/gfdtv-ui-portal-staff"`

Let me fix this and see what happens...
