### ISSUE TITLE
Automatic configuration is not working with Nx Monorepo Yarn 3 PnP and jest 

### ISSUE THREAD

**Issue by pavel-shermayster-sage** [wallabyjs/public#3235]
### Issue description or question

Monorepo project that uses Nx, yarn 3, typescript and jest. Automatic configuration is not working. 

### Wallaby diagnostics report
```
{
  editorVersion: '1.79.2',
  pluginVersion: '1.0.360',
  editorType: 'VSCode',
  osVersion: 'darwin 22.5.0',
  nodeVersion: 'v18.12.1',
  coreVersion: '1.0.1433',
  checksum: 'NjRjZTZlN2Y5N2FjMWNiNGQzZGIzOTk1NjI3ZDVjZDgsMTcxNTIxMjgwMDAwMCww',
  config: { tests: [], files: [] },
  packageJSON: {
    dependencies: {
      '@dagrejs/graphlib': '^2.1.13',
      '@mui/material': '^5.13.5',
      '@mui/styled-engine-sc': '^5.12.0',
      '@mui/system': '^5.13.5',
      '@shared/db': '*',
      '@shared/event-registry': '*',
      '@shared/mocks': '*',
      '@shared/utils': '*',
      '@ui/styles': '*',
      'ag-grid-enterprise': '^29.3.5',
      'ag-grid-react': '^29.3.5',
      dayjs: '^1.11.8',
      dexie: '^3.2.4',
      react: '~18.2.0',
      'react-dom': '~18.2.0',
      'react-router-dom': '^6.13.0',
      redux: '^4.2.1',
      'redux-logger': '^3.0.6',
      'redux-saga': '^1.2.3',
      'styled-components': '^5.3.11',
      'typed-redux-saga': '^1.5.0'
    },
    devDependencies: {
      '@babel/core': '^7.22.5',
      '@babel/plugin-transform-runtime': '^7.22.5',
      '@babel/preset-env': '^7.22.5',
      '@babel/preset-react': '^7.22.5',
      '@babel/preset-typescript': '^7.22.5',
      '@babel/runtime': '^7.22.5',
      '@faker-js/faker': '^8.0.2',
      '@juggle/resize-observer': '^3.4.0',
      '@mui/styled-engine': '^5.13.2',
      '@reduxjs/toolkit': '^1.9.5',
      '@shared/types': '*',
      '@svgr/webpack': '^8.0.1',
      '@testing-library/dom': '^9.3.1',
      '@testing-library/jest-dom': '^5.16.5',
      '@testing-library/react': '^14.0.0',
      '@testing-library/user-event': '^14.4.3',
      '@types/jest': '^29.5.2',
      '@types/node': '^20.3.1',
      '@types/react': '^18.2.12',
      '@types/react-dom': '^18.2.5',
      '@types/react-redux': '^7.1.25',
      '@types/redux-logger': '^3.0.9',
      '@types/styled-components': '^5.1.26',
      '@types/testing-library__jest-dom': '^5.14.6',
      '@types/webpack-env': '^1.18.1',
      'ag-grid-community': '^29.3.5',
      'babel-loader': '^9.1.2',
      'css-loader': '^6.8.1',
      'css-minimizer-webpack-plugin': '^5.0.1',
      'fake-indexeddb': '^4.0.1',
      'fork-ts-checker-webpack-plugin': '^8.0.0',
      'html-webpack-plugin': '^5.5.3',
      jest: '^29.5.0',
      'jest-environment-jsdom': '^29.5.0',
      'mini-css-extract-plugin': '^2.7.6',
      msw: '^1.2.2',
      'react-is': '^18.2.0',
      'react-redux': '^8.1.0',
      sass: '^1.63.4',
      'sass-loader': '^13.3.2',
      'style-loader': '^3.3.3',
      typescript: '^5.1.3',
      webpack: '^5.87.0',
      'webpack-cli': '^5.1.4',
      'webpack-dev-server': '^4.15.1',
      'webpack-merge': '^5.9.0',
      'whatwg-fetch': '^3.6.2'
    }
  },
  fs: { numberOfFiles: 0 },
  debug: [
    '2023-06-22T10:40:13.398Z config Attempting automatic configuration for angular\n',
    '2023-06-22T10:40:13.402Z angular/cli config Detected Angular CLI.\n',
    "2023-06-22T10:40:13.402Z angular/cli config Error: '<homeDir>/code/xPnA/nx.json' is not a valid Angular CLI file.\n" +
      '    at Object.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:16:12274)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:16:19443)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:16:18738)\n' +
      '    at o (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:16:18497)\n',
    '2023-06-22T10:40:13.403Z angular/cli config Angular.json: \n' +
      ' {\n' +
      '  tasksRunnerOptions: {\n' +
      "    default: { runner: 'nx-cloud', options: { cacheableOperations: [ 'build', 'test', 'ci', 'plan' ], accessToken: 'YTAzYWRmYzAtZDVkMC00NWYxLWEyMmUtYmNlNDI5ZGE4MjU0fHJlYWQtd3JpdGU=' } }\n" +
      '  },\n' +
      "  pluginsConfig: { '@nx/js': { analyzeSourceFiles: false } },\n" +
      '  targetDefaults: {\n' +
      "    build: { dependsOn: [ '^build' ] },\n" +
      "    test: { executor: '@nx/jest:jest', options: { jestConfig: '{projectRoot}/jest.config.ts' }, outputs: [ '{projectRoot}/coverage' ], configurations: { ci: { ci: true } } }\n" +
      '  },\n' +
      "  namedInputs: { default: [ '{projectRoot}/**/*', 'sharedGlobals' ], sharedGlobals: [], production: [ 'default' ] }\n" +
      '}\n',
    "2023-06-22T10:40:13.403Z angular/cli config Error: '<homeDir>/code/xPnA/nx.json' is not a valid Angular CLI file.\n" +
      '    at Object.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:16:12274)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:16:19443)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:16:18738)\n' +
      '    at o (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:16:18497)\n',
    '2023-06-22T10:40:13.403Z config Finished attempting automatic configuration for angular (5ms)\n',
    '2023-06-22T10:40:13.403Z config Attempting automatic configuration for jest\n',
    "2023-06-22T10:40:13.404Z jest/config Error: Module jest-cli is not found in '<homeDir>/code/xPnA/frontend/app1'.\n" +
      '    at Object.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:32:5011)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:31:20108)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:31:19403)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:31:19312\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at s (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:31:19106)\n' +
      '    at Object.loadJest (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:32:2609)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:19:30281\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:20:2986)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:20:2281)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:20:2190\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at s (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:20:1984)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:19:29969)\n' +
      '    at Object.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:20:1661)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:20:2986)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:20:2281)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:20:2190\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at s (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:20:1984)\n' +
      '    at Object.n [as configure] (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:20:1542)\n' +
      '    at Config.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:15:24267)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:15:15488)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:15:14783)\n' +
      '    at o (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:15:14532)\n',
    '2023-06-22T10:40:13.404Z config Finished attempting automatic configuration for jest (1ms)\n',
    '2023-06-22T10:40:13.404Z config Attempting automatic configuration for vitest\n',
    '2023-06-22T10:40:13.405Z vitest/config Error: Vitest dependency not found.\n' +
      '    at Object.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:20:5203)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:20:8459)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:20:7754)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:20:7663\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at n (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:20:7457)\n' +
      '    at Object.r [as configure] (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:20:4454)\n' +
      '    at Config.<anonymous> (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:15:24267)\n' +
      '    at r (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:15:15488)\n' +
      '    at Object.next (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:15:14783)\n' +
      '    at o (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.360/wallabye49e76/server.js:15:14532)\n',
    '2023-06-22T10:40:13.405Z config Finished attempting automatic configuration for vitest (1ms)\n'
  ]
}
```
## Nx Config
```
{
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx-cloud",
      "options": {
        "cacheableOperations": [
          "build",
          "test",
          "ci",
          "plan"
        ],
      }
    }
  },
  "pluginsConfig": {
    "@nx/js": {
      "analyzeSourceFiles": false
    }
  },
  "targetDefaults": {
    "build": {
      "dependsOn": [
        "^build"
      ]
    },
    "test": {
      "executor": "@nx/jest:jest",
      "options": {
        "jestConfig": "{projectRoot}/jest.config.ts"
      },
      "outputs": [
        "{projectRoot}/coverage"
      ],
      "configurations": {
        "ci": {
          "ci": true
        }
      }
    }
  },
  "namedInputs": {
    "default": [
      "{projectRoot}/**/*",
      "sharedGlobals"
    ],
    "sharedGlobals": [],
    "production": [
      "default"
    ]
  }
}
```
## Yarn configs:
```
npmScopes:

packageExtensions:
  "@mui/system@*":
    dependencies:
      "@mui/styled-engine-sc": "*"
      react-dom: "*"
      react-is: "*"
      styled-components: "*"
  "@nx/jest@*":
    peerDependenciesMeta:
      nx:
        optional: true
  "@nx/js@*":
    peerDependenciesMeta:
      nx:
        optional: true
  "@phenomnomnominal/tsquery@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  ag-grid-enterprise@*:
    dependencies:
      ag-grid-community: ^29
  eslint-config-react-app@*:
    peerDependenciesMeta:
      "@babel/plugin-syntax-flow":
        optional: true
      "@babel/plugin-transform-react-jsx":
        optional: true
  jest-config@*:
    dependencies:
      ts-node: "*"
    peerDependenciesMeta:
      typescript:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
```

**Comment by smcenlly** [comment]
We have tried creating an NX mono-repo with Yarn 3 and Jest, and everything is working for us.

We suspect that your issue may be related to an older version of NX or else some configuration errors as a result of an upgrade in NX version (or other dependencies) at some point in time.

We created a [sample repo](https://github.com/wallabyjs/wallaby-3235) that we used to try and reproduce your problem.

Can you please compare your project configuration to our sample repo? It should help you identify why it's not working in your local project and why it is working on a fresh project.

If you're still having problems, can you please update our sample repo so that it has the same problem as your project? Alternatively, you may provide us with another repo that has the same problem.

**Comment by pavel-shermayster-sage** [comment]
We're not using nx-schema json and project json. Instead, each project has each own package json file.

**Comment by smcenlly** [comment]
If you are not using `nx` schema to describe your repo, then you will need to make sure that `jest` runs from the command-line with `yarn jest` in order for Wallaby to work.

As you are using Yarn2, once you have `jest` working from the CLI, you may find that Wallaby needs some additional dependencies. These should be reported in Wallaby's output window. You can refer to [our Yarn2 docs](https://wallabyjs.com/docs/integration/yarn2.html) on how to fix these. By default, the following `.yarnrc.yml` is required:

```yml
yarnPath: ".yarn/releases/yarn-berry.cjs"
...
packageExtensions:
  jest-config@*:
    dependencies:
      jest-runtime: "*"
  jest-cli@*:
    dependencies:
      "@jest/reporters": "*"
      "@jest/console": "*"
```

If you're still having problems, can you please update our sample repo (or else provide a separate sample) so that we can see your exact setup / configuration; this should allow us to solve your problem once we can see/confirm that your tests are running from the command-line.

**Comment by pavel-shermayster-sage** [comment]
I've created minimal configuration. Running `yarn test` from root and project works 
https://github.com/pavel-shermayster-sage/wallaby-config

**Comment by smcenlly** [comment]
Thanks for the sample repo.

The `jest` command is actually failing from the command-line with `yarn jest` in the project root, which you'll need to fix. Once you've fixed this, Wallaby will work for you.

To fix the problem, you'll need to install `jest` in the project root and then update your `.yarnrc.yml` to fix some dependency issues. You will need to make the following changes:

**rootDir/package.json**
```diff
{
  "name": "wallaby-config",
  "packageManager": "yarn@3.6.0",
  "workspaces": [
    "frontend/*"
  ],
  "scripts": {
    "start:dev": "nx run-many --target=start:dev --parallel=999",
    "test": "nx run-many --target=test"
  },
  "devDependencies": {
    "@nx/jest": "^16.4.0",
    "@types/node": "^20.3.1",
+   "jest": "^29.5.0",
    "nx": "^16.4.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.1.3"
  }
}
```

**rootdir/.yarnrc.yml**
```diff
yarnPath: .yarn/releases/yarn-3.6.0.cjs
packageExtensions:
  "@nx/jest@*":
    peerDependenciesMeta:
      nx:
        optional: true
  jest-config@*:
    dependencies:
      ts-node: "*"
    peerDependenciesMeta:
      typescript:
        optional: true
+ jest-config@*:
+   dependencies:
+     jest-runtime: "*"
+ jest-cli@*:
+   dependencies:
+     "@jest/reporters": "*"
+     "@jest/console": "*"
```

_**Note: be sure to run `yarn install` after making the changes.**_

**Comment by pavel-shermayster-sage** [comment]
It worked. Thanks @smcenlly.
