### ISSUE TITLE
not working with nextjs

### ISSUE THREAD

**Issue by heysanyam** [wallabyjs/public#3239]
### Issue description or question

not working with nextjs/jest
[example config](https://raw.githubusercontent.com/vercel/next.js/canary/examples/with-jest/jest.config.js)

### Wallaby diagnostics report

```
‌[Error] Automatic Jest configuration error: Failed to read Jest configuration from '.': Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:stream/web 
[Error]     at new NodeError (internal/errors.js:322:7) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:781:13) 
[Error]     at Module.require (internal/modules/cjs/loader.js:1003:19) 
[Error]     at require (internal/modules/cjs/helpers.js:107:18) 
[Error]     at Object.<anonymous> (./node_modules/next/dist/lib/download-wasm-swc.js:63:29) 
[Error]     at Module._compile (internal/modules/cjs/loader.js:1114:14) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:979:32) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:819:12) 
[Error]     at Module.require (internal/modules/cjs/loader.js:1003:19) 
[Error]     at require (internal/modules/cjs/helpers.js:107:18) 
[Error]     at Object.<anonymous> (./node_modules/next/dist/build/swc/index.js:83:26) 
[Error]     at Module._compile (internal/modules/cjs/loader.js:1114:14) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:979:32) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:819:12) 
[Error]     at Module.require (internal/modules/cjs/loader.js:1003:19) 
[Error]     at require (internal/modules/cjs/helpers.js:107:18) 
[Error]     at Object.<anonymous> (./node_modules/next/dist/build/jest/jest.js:32:14) 
[Error]     at Module._compile (internal/modules/cjs/loader.js:1114:14) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:979:32) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:819:12) 
[Error]     at Module.require (internal/modules/cjs/loader.js:1003:19) 
[Error]     at require (internal/modules/cjs/helpers.js:107:18) 
[Error]     at Object.<anonymous> (./node_modules/next/jest.js:1:18) 
[Error]     at Module._compile (internal/modules/cjs/loader.js:1114:14) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:979:32) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:819:12) 
[Error]     at Module.require (internal/modules/cjs/loader.js:1003:19) 
[Error]     at require (internal/modules/cjs/helpers.js:107:18) 
[Error]     at Object.<anonymous> (./jest.config.js:1:18) 
[Error]     at Module._compile (internal/modules/cjs/loader.js:1114:14) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:979:32) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:819:12) 
[Error]     at Module.require (internal/modules/cjs/loader.js:1003:19) 
[Error]     at require (internal/modules/cjs/helpers.js:107:18) 
[Error]     at requireOrImportModule (./node_modules/jest-util/build/requireOrImportModule.js:44:28) 
[Error]     at readConfigFileAndSetRootDir (./node_modules/jest-config/build/readConfigFileAndSetRootDir.js:112:66) 
[Error]     at readInitialOptions (./node_modules/jest-config/build/index.js:400:60) 
[Error]     at readConfig (./node_modules/jest-config/build/index.js:147:54) 
[Error]     at Object.readConfigs (./node_modules/jest-config/build/index.js:421:32) 
[Error]     at new Promise (<anonymous>) 
[Error]     at new Promise (<anonymous>) 
[Error]     at new Promise (<anonymous>) 
[Error]  
[Error] We've also tried to automatically configure Wallaby.js for other frameworks 
[Error] Automatic Vitest configuration error: Vitest dependency not found. 
```

**Comment by thedaviddias** [comment]
Wallaby works perfectly fine with a NextJS project. I can see 2 issues you could investigate:
- `Failed to read Jest configuration from '.'`
- `Automatic Vitest configuration error: Vitest dependency not found.`

**Comment by smcenlly** [comment]
Your diagnostic report indicates that Wallaby is trying to run your project using a version of `node.js` that is not supported by your project dependencies.

We were able to reproduce the same error running Wallaby on the `with-jest` example with `node.js@v14`. The same project works for us when using `node.js@v18.16.0`.

If you are using VS Code, you can explicitly set the version of `node.js` using the `wallaby.node` VS Code setting. If you are using a JetBrains editor, you can set the node version to use in your Wallaby.js Run Configuration.
