### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by hellboy81** [wallabyjs/public#324]
In some cases after some code changed unexpected error can be throwed:

`test/myMod/spec.js`:
```sh
var sinon = require('sinon'),
   ....
   fakes = require('./fakes') // Path to fakes module is specified in tests array of wallaby.js configuration
```

`test/myMod/fakes/index.js`:
```
'use strict';

var jsf = require('json-schema-faker'), // May be exception is throwed here 
   ....
```

```sh
Runtime error: TypeError: Cannot read property '0' of undefined
    at Object.<anonymous> (./test/unit/myMod/fakes/index.js:3:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/home/local/.../.WebStorm10/system/wallaby/projects/c71567ea4cd5d8f4/instrumented/test/unit/myMod/spec.js:3:173)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
```

Restart wallaby.js process can help.

core v1.0.142, also early versions are

**Comment by ArtemGovorov** [comment]
> Path to fakes module is specified in tests array of wallaby.js configuration

Try moving the path to `files` list in your wallaby config file. `tests` list should only contain files with tests in them.

**Comment by hellboy81** [comment]
OK, works4me
