### ISSUE TITLE
IntelliJ infinite loading - Connection refused/Operation timed out

### ISSUE THREAD

**Issue by filipw01** [wallabyjs/public#3240]
### Issue description or question

Wallaby extension in IntelliJ stopped working. There's no output only and infinite spinner and I encountered these 2 errors. 

I used one of the sample projects to test if this is some kind of breaking change using automatic configuration or something with my project, but it's still failing.

I would love to debug more, but I'm not where it's best to start

```
java.net.ConnectException: Operation timed out
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:473)
	at com.wallaby.javascript.extendedCore.Client.q(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
```
java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:473)
	at com.wallaby.javascript.extendedCore.Client.q(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Wallaby diagnostics report

I don't have any because it is in infinite loading state

I'm using M1 Mac with PyCharm 231.9161.41

**Comment by ArtemGovorov** [comment]
It looks like there's been some change in your environment that is causing network issue when the plugin is trying to connect to locally running Wallaby Core via localhost websocket.

We have seen the issue once, was related to `hosts` file: https://github.com/wallabyjs/public/issues/668#issuecomment-228311759. If checking/fixing the file doesn't help, try the following:

- Disable your firewall/antivirus software to see if it helps.
- Does you WebStorm have any proxy settings (Settings | Appearance & Behavior | System Settings | HTTP Proxy)?
- Does your system have any proxy settings?

**Comment by filipw01** [comment]
I started experiencing other network related issues which in the end I resolved by flushing DNS, removing some docker/k8s stuff from /etc/hosts and possibly some other generic networking restarts. Thank you for the hint

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
