### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by PavelA85** [wallabyjs/public#3244]
### Issue description or question

I am getting very strange error: Unexpected token 'export'
```
Unexpected token 'export'
	at Object.<anonymous> src/components/home/patientdetails/tabscontent/backgroundTab/PatientDetailsBackgroundSubTabs/Tabs/riskTab/riskScoresView.tsx:28:1
	at Object.<anonymous> src/components/home/patientdetails/tabscontent/backgroundTab/PatientDetailsBackgroundSubTabs/Tabs/riskTab/riskTab.tsx:7:1
	at Object.<anonymous> src/components/home/patientdetails/tabscontent/backgroundTab/PatientDetailsBackgroundSubTabs/Tabs/riskTab/index.tsx:1:1
	at Object.<anonymous> src/components/home/patientdetails/tabscontent/backgroundTab/PatientDetailsBackgroundSubTabs/index.tsx:10:1
	at Object.<anonymous> src/components/home/patientdetails/tabscontent/backgroundTab/BackgroundTab.tsx:3:1
	at Object.<anonymous> src/components/home/patientdetails/tabscontent/backgroundTab/index.ts:1:1
	at Object.<anonymous> src/components/home/patientdetails/DialogBody.tsx:4:1
	at Object.<anonymous> src/components/home/patientdetails/Tabs.tsx:3:1
	at Object.<anonymous> src/components/home/patientdetails/index.tsx:7:1
	at Object.<anonymous> src/components/home/patientdetails/index.test.tsx:1:1
```
![image](https://github.com/wallabyjs/public/assets/2944514/b7a8a7cf-86c7-4b94-8f5a-cb2f01ad81c2)

I was unable to paste all diagnostic data here, so I created a gist: https://gist.github.com/PavelA85/4c3575e8c745ee8dc4d429de09898d62

**Comment by PavelA85** [comment]
The only error I get is 
```
  Invalid testPattern --config=jest.config.js|--maxWorkers=1|--testResultsProcessor|.\\node_modules\\jest-junit|--coverage|--coverageDirectory=coverage|--watch|--config|{"roots":["<rootDir>\\src"],"collectCoverageFrom":["src\\**\\*.{js,jsx,ts,tsx}","!src\\**\\*.d.ts"],"setupFiles":["C:\\Projects\\sproj-ui\\node_modules\\react-app-polyfill\\jsdom.js"],"setupFilesAfterEnv":["<rootDir>\\src\\setupTests.ts"],"testMatch":["<rootDir>\\src\\**\\__tests__\\**\\*.{js,jsx,ts,tsx}","<rootDir>\\src\\**\\*.{spec,test}.{js,jsx,ts,tsx}"],"testEnvironment":"jsdom","transform":{"^.+\\.(js|jsx|mjs|cjs|ts|tsx)$":"C:\\Projects\\sproj-ui\\node_modules\\react-scripts\\config\\jest\\babelTransform.js","^.+\\.css$":"C:\\Projects\\sproj-ui\\node_modules\\react-scripts\\config\\jest\\cssTransform.js","^(?!.*\\.(js|jsx|mjs|cjs|ts|tsx|css|json)$)":"C:\\Projects\\sproj-ui\\node_modules\\react-scripts\\config\\jest\\fileTransform.js"},"transformIgnorePatterns":["[\\\\\\]node_modules[\\\\\\].+\\.(js|jsx|mjs|cjs|ts|tsx)$","^.+\\.module\\.(css|sass|scss)$"],"modulePaths":["C:\\Projects\\sproj-ui\\src"],"moduleNameMapper":{"^react-native$":"react-native-web","^.+\\.module\\.(css|sass|scss)$":"identity-obj-proxy"},"moduleFileExtensions":["web.js","js","web.ts","ts","web.tsx","tsx","json","web.jsx","jsx","node"],"watchPlugins":["jest-watch-typeahead\\filename","jest-watch-typeahead\\testname"],"resetMocks":true,"rootDir":"C:\\Projects\\sproj-ui"}|--env|C:\Projects\sproj-ui\node_modules\jest-environment-jsdom\build\index.js supplied. Running all tests instead.
```
Jest discovers:
Test Suites: 203 passed, 203 total
Tests:       756 passed, 756 total

while Wallaby `0 failing tests, 335 passing  Launch Coverage/Test Explorer`

**Comment by ArtemGovorov** [comment]
Thanks for providing your config files. 

> The only error I get is
> Invalid testPattern

It looks like your scripts `test` command is invalid, because it's trying to use `react-scripts` (that automatically [creates Jest config](https://github.com/facebook/create-react-app/blob/0a827f69ab0d2ee3871ba9b71350031d8a81b7ae/packages/react-scripts/scripts/test.js#L61)) and at the same time pass your own Jest config file.

In order to make your setup work you may create the following Wallaby config file:

```
module.exports = () => {
  return {
    testFramework: {
      configFile: './jest.config.js'
    }
  }
};
```
and modify your Wallaby Run Configuration in WebStorm to point to the config file by changing the `Configuration Type` setting.

**Comment by PavelA85** [comment]
Thanks, Your fix helped!
