### ISSUE TITLE
Failed to run vitest

### ISSUE THREAD

**Issue by atako** [wallabyjs/public#3245]
### Wallaby diagnostic report

```
{
  editorVersion: '1.80.1',
  pluginVersion: '1.0.364',
  editorType: 'VSCode',
  osVersion: 'darwin 21.6.0',
  nodeVersion: 'v18.17.0',
  coreVersion: '1.0.1446',
  checksum: 'YTVmMzFkYmFjNmY0MGQ1MjNkNzIyZDJhMjQxOTg4MzIsMTY5NjU1MDQwMDAwMCww',
  config: {
    files: [
      { pattern: 'src/**/*.ts', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: '__test__/utils/*.ts', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: '__mocks__/**/*.ts', ignore: false, trigger: true, load: true, instrument: true, order: 3 },
      { pattern: '__fixtures__/**/*.ts', ignore: false, trigger: true, load: true, instrument: true, order: 4 }
    ],
    tests: [ { pattern: '__test__/**/*.spec.ts', ignore: false, trigger: true, load: true, test: true, order: 5 } ],
    compilers: { '**/*.ts?(x)': [Function (anonymous)], '**/*.?(lit)coffee?(.md)': [Function (anonymous)] },
    env: { type: 'node', runner: 'node', params: { env: 'test=test' }, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    workers: { restart: true, initial: 0, regular: 0, recycle: true },
    debug: true,
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0' },
    runMode: 'onsave',
    diagnostics: {},
    captureConsoleLog: true,
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: true,
    symlinkNodeModules: undefined,
    configCode: 'module.exports = (wallaby) => {\n' +
      '  return {\n' +
      '    files: [\n' +
      "      './src/**/*.ts',\n" +
      "      './__test__/utils/*.ts',\n" +
      "      './__mocks__/**/*.ts',\n" +
      "      './__fixtures__/**/*.ts',\n" +
      '    ],\n' +
      "    tests: ['/__test__/**/*.spec.ts'],\n" +
      '\n' +
      '    compilers: {\n' +
      "      '**/*.ts?(x)': wallaby.compilers.typeScript({\n" +
      "        module: 'commonjs',\n" +
      '        isolatedModules: true,\n' +
      '      }),\n' +
      '    },\n' +
      '\n' +
      '    env: {\n' +
      "      type: 'node',\n" +
      "      runner: 'node',\n" +
      '      params: {\n' +
      "        env: 'test=test',\n" +
      '      },\n' +
      "      // runner: '<homeDir>/.nvm/versions/node/v16.18.0/bin/node',\n" +
      '    },\n' +
      '\n' +
      '    workers: {\n' +
      '      restart: true,\n' +
      '    },\n' +
      '\n' +
      '    debug: true,\n' +
      "    testFramework: 'vitest',\n" +
      "    runMode: 'onsave',\n" +
      '  }\n' +
      '}\n'
  },
  packageJSON: {
    dependencies: {
      '@aws-sdk/client-eventbridge': '^3.370.0',
      '@aws-sdk/client-sesv2': '^3.370.0',
      '@prisma/client': '^5.0.0',
      '@typescript-eslint/eslint-plugin': '^5.57.0',
      'aws-sdk': '^2.1351.0',
      nanoid: '^4.0.2',
      npm: '^9.6.2'
    },
    devDependencies: { '@types/aws-lambda': '^8.10.107', prisma: '^5.0.0', '@vitest/runner': '^0.28.1', vitest: '^0.28.1' }
  },
  fs: { numberOfFiles: 4 },
  debug: [
    '2023-07-22T10:20:53.018Z project Wallaby Node version: v18.17.0\n',
    '2023-07-22T10:20:53.018Z project Wallaby config: <homeDir>/code/my/telewatcher/backend/services/wallaby.js\n',
    '2023-07-22T10:20:53.066Z fs File system starting\n',
    '2023-07-22T10:20:54.089Z fs File system scan has finished by timeout\n',
    '2023-07-22T10:20:54.094Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.364/projects/4440be8155c1d03c\n',
    '2023-07-22T10:20:54.190Z uiService Listening port 51235\n',
    '2023-07-22T10:20:54.198Z project package.json file change detected, invalidating local cache\n',
    '2023-07-22T10:20:54.203Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2023-07-22T10:20:54.203Z workers Starting run worker instance #0\n',
    '2023-07-22T10:20:54.203Z workers Starting run worker instance #1\n',
    '2023-07-22T10:20:54.203Z workers Starting run worker instance #2\n',
    '2023-07-22T10:20:54.203Z workers Starting run worker instance #3\n',
    '2023-07-22T10:20:54.203Z workers Starting run worker instance #4\n',
    '2023-07-22T10:20:54.203Z workers Starting run worker instance #5\n',
    '2023-07-22T10:20:54.204Z workers Web server is listening at 55784\n',
    '2023-07-22T10:20:54.204Z project File cache requires some updates, waiting required files from IDE\n',
    '2023-07-22T10:20:54.617Z workers Started run worker instance (delayed) #2\n',
    '2023-07-22T10:20:54.620Z workers Started run worker instance (delayed) #0\n',
    '2023-07-22T10:20:54.623Z workers Started run worker instance (delayed) #3\n',
    '2023-07-22T10:20:54.628Z workers Started run worker instance (delayed) #4\n',
    '2023-07-22T10:20:54.628Z workers Started run worker instance (delayed) #5\n',
    '2023-07-22T10:20:54.629Z workers Started run worker instance (delayed) #1\n',
    '2023-07-22T10:20:55.275Z project Stopping process pool\n',
    '2023-07-22T10:20:55.277Z project Test run started; run priority: 3\n',
    '2023-07-22T10:20:55.279Z project Running all tests\n',
    '2023-07-22T10:20:55.281Z workers Starting test run, priority: 3\n',
    '2023-07-22T10:20:55.281Z nodeRunner Starting sandbox [worker #0, session #jmzzc]\n',
    '2023-07-22T10:20:55.282Z nodeRunner Preparing sandbox [worker #0, session #jmzzc]\n',
    '2023-07-22T10:20:55.282Z nodeRunner Prepared sandbox [worker #0, session #jmzzc]\n',
    '2023-07-22T10:20:55.282Z workers [worker #0, session #jmzzc] Running tests in sandbox\n',
    '2023-07-22T10:20:55.832Z workers Sandbox (active) [jmzzc] error: Failed to initialize wallaby vitest.\n' +
      'dependency.startVitest is not a function\n' +
      'TypeError: dependency.startVitest is not a function\n',
    '2023-07-22T10:20:55.833Z workers Failed to map the stack to user code, entry message: Failed to initialize wallaby vitest.\n' +
      'dependency.startVitest is not a function\n' +
      'TypeError: dependency.startVitest is not a function, stack: Failed to initialize wallaby vitest.\n' +
      'dependency.startVitest is not a function\n' +
      'TypeError: dependency.startVitest is not a function\n' +
      '    at initializeVitest (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.364/wallaby375de6/runners/node/vitest@0.14.0/initializer.js:14:12085)\n' +
      '    at async v._onStart (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.364/wallaby375de6/runners/node/vitest@0.14.0/initializer.js:14:21264)\n',
    '2023-07-22T10:20:55.934Z workers [jmzzc] Run 0 test(s), skipped 0 test(s)\n',
    '2023-07-22T10:20:55.937Z workers [jmzzc] Sandbox is responsive, closing it\n',
    '2023-07-22T10:20:55.937Z workers Recyling run worker instance #0\n',
    '2023-07-22T10:20:55.938Z workers Starting run worker instance #0\n',
    '2023-07-22T10:20:55.939Z project Test run finished\n',
    '2023-07-22T10:20:55.939Z project Processed console.log entries\n',
    '2023-07-22T10:20:55.939Z project Processed loading sequences\n',
    '2023-07-22T10:20:55.939Z project Processed executed tests\n',
    '2023-07-22T10:20:55.940Z project Processed code coverage\n',
    '2023-07-22T10:20:55.948Z project Test run result processed and sent to IDE\n',
    '2023-07-22T10:20:56.107Z workers Started run worker instance (delayed) #0\n'
  ]
}
```

**Comment by mburnell** [comment]
Thanks for reporting the issue. We've used your config to identify and fix a problem in Wallaby, and have some other information for you regarding configuring Wallaby to run with vitest. Details are as follows:

- There was an issue in Wallaby's vitest integration logic that caused problems when env.params.env property was specified (as in your config). This has been corrected in Wallaby core version `1.0.1447`.
- Support for vitest relies on Wallaby's `autoDetect` behaviour. This behaviour is on by default when `files` and `tests` are not specified in Wallaby config. Modifying your vitest config is the recommended way to manage these values, but if you do find it necessary to specify or override them in the Wallaby config, you'll need to also specify `autoDetect: true`.
- Specifying `compilers` is not relevant for vitest, as vitest uses vite for compilation
- Specifying `workers` settings is not required for vitest (which will use your vitest configuration)
- `testFramework: vitest` is not valid Wallaby configuration; autoDetect must be used when working with vitest

If not specifying `file` and `test` patterns, your config should look something like this:
```javascript
module.exports = (wallaby) => {
  return {
    env: {
      runner: 'node',
      params: {
        env: 'test=test',
      },
    },
    runMode: 'onsave',
  }
}
```

With your `file` and `test` patterns, it will also need the `autoDetect` flag set:
```javascript
module.exports = (wallaby) => {
  return {
    files: [
      './src/**/*.ts',
      './__test__/utils/*.ts',
      './__mocks__/**/*.ts',
      './__fixtures__/**/*.ts',
    ],
    tests: ['/test/**/*.test.ts'],
    env: {
      runner: 'node',
      params: {
        env: 'test=test',
      },
    },
    runMode: 'onsave',
    autoDetect: true
  }
}
```

We're assuming this will fix your problem, and we'll close the issue. If you're still having problems, please reply and we'll reopen the issue.

**Comment by atako** [comment]
Thank you.
I changed the config and get the new error.
This is diagnostic report: 

```
{
  editorVersion: '1.80.1',
  pluginVersion: '1.0.364',
  editorType: 'VSCode',
  osVersion: 'darwin 21.6.0',
  nodeVersion: 'v18.17.0',
  coreVersion: '1.0.1447',
  checksum: 'YTVmMzFkYmFjNmY0MGQ1MjNkNzIyZDJhMjQxOTg4MzIsMTY5NjU1MDQwMDAwMCww',
  config: {
    files: [
      { pattern: 'src/**/*.ts', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '__test__/utils/*.ts', ignore: false, trigger: true, load: true, order: 2 },
      { pattern: '__mocks__/**/*.ts', ignore: false, trigger: true, load: true, order: 3 },
      { pattern: '__fixtures__/**/*.ts', ignore: false, trigger: true, load: true, order: 4 }
    ],
    tests: [ { pattern: '__test__/**/*.test.ts', ignore: false, trigger: true, load: true, test: true, order: 5 } ],
    env: { runner: 'node', params: { env: 'test=test' }, type: 'node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    runMode: 'onsave',
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/private/var/folders/t1/lxpjbnzs4gq6xc_sjj6c0n1w0000gn/T/jest_dx',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/code/my/telewatcher/backend/services',
              dependencyExtractor: undefined,
              detectLeaks: undefined,
              detectOpenHandles: undefined,
              displayName: undefined,
              errorOnDeprecated: false,
              extraGlobals: [],
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, throwOnModuleCollision: false },
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [ 'js', 'json', 'jsx', 'ts', 'tsx', 'node' ],
              moduleLoader: undefined,
              moduleNameMapper: [],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              name: '4945762be0a140479ce176d3c8ee1202',
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/code/my/telewatcher/backend/services',
              roots: [ '<homeDir>/code/my/telewatcher/backend/services' ],
              runner: 'jest-runner',
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/code/my/telewatcher/backend/node_modules/jest-environment-jsdom/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<homeDir>/code/my/telewatcher/backend/node_modules/jest-jasmine2/build/index.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [ [ '\\.[jt]sx?$', '<homeDir>/code/my/telewatcher/backend/node_modules/babel-jest/build/index.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: [],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<homeDir>/code/my/telewatcher/backend/services/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: undefined,
            detectOpenHandles: undefined,
            enabledTestsMap: undefined,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: undefined,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 7,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: undefined,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/code/my/telewatcher/backend/services',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/code/my/telewatcher/backend/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/t1/lxpjbnzs4gq6xc_sjj6c0n1w0000gn/T/jest_dx', '\\./coverage' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/t1/lxpjbnzs4gq6xc_sjj6c0n1w0000gn/T/jest_dx', '\\./coverage' ],
            testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    filesWithCoverageCalculated: [],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    dot: true,
    captureConsoleLog: true,
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: false,
    configCode: 'module.exports = (wallaby) => {\n' +
      '  return {\n' +
      '    files: [\n' +
      "      './src/**/*.ts',\n" +
      "      './__test__/utils/*.ts',\n" +
      "      './__mocks__/**/*.ts',\n" +
      "      './__fixtures__/**/*.ts',\n" +
      '    ],\n' +
      "    tests: ['/__test__/**/*.test.ts'],\n" +
      '    env: {\n' +
      "      runner: 'node',\n" +
      '      params: {\n' +
      "        env: 'test=test',\n" +
      '      },\n' +
      '    },\n' +
      "    runMode: 'onsave',\n" +
      '    autoDetect: true,\n' +
      '  }\n' +
      '}\n'
  },
  packageJSON: {
    dependencies: {
      '@aws-sdk/client-eventbridge': '^3.370.0',
      '@aws-sdk/client-sesv2': '^3.370.0',
      '@prisma/client': '^5.0.0',
      '@typescript-eslint/eslint-plugin': '^5.57.0',
      'aws-sdk': '^2.1351.0',
      nanoid: '^4.0.2',
      npm: '^9.6.2'
    },
    devDependencies: { '@types/aws-lambda': '^8.10.107', prisma: '^5.0.0', '@vitest/runner': '^0.28.1', vitest: '^0.28.1' }
  },
  fs: { numberOfFiles: 5 },
  debug: [
    '2023-07-24T05:02:09.792Z config Attempting automatic configuration for angular\n',
    '2023-07-24T05:02:09.796Z angular/cli config Angular CLI not found.\n',
    '2023-07-24T05:02:09.796Z config Finished attempting automatic configuration for angular (4ms)\n',
    '2023-07-24T05:02:09.796Z config Attempting automatic configuration for jest\n',
    '2023-07-24T05:02:09.957Z jest/config Detected Jest.\n',
    '2023-07-24T05:02:09.958Z jest/config Configured Jest.\n',
    '2023-07-24T05:02:09.958Z config Finished attempting automatic configuration for jest (162ms)\n',
    '2023-07-24T05:02:09.959Z project Wallaby Node version: v18.17.0\n',
    '2023-07-24T05:02:09.959Z project Wallaby config: <homeDir>/code/my/telewatcher/backend/services/wallaby.js\n',
    '2023-07-24T05:02:10.002Z fs File system starting\n',
    '2023-07-24T05:02:11.017Z fs File system scan has finished by timeout\n',
    '2023-07-24T05:02:11.023Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.364/projects/4440be8155c1d03c\n',
    '2023-07-24T05:02:11.139Z uiService Listening port 51235\n',
    '2023-07-24T05:02:11.149Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2023-07-24T05:02:11.149Z workers Starting run worker instance #0\n',
    '2023-07-24T05:02:11.149Z workers Starting run worker instance #1\n',
    '2023-07-24T05:02:11.149Z workers Starting run worker instance #2\n',
    '2023-07-24T05:02:11.149Z workers Starting run worker instance #3\n',
    '2023-07-24T05:02:11.149Z workers Starting run worker instance #4\n',
    '2023-07-24T05:02:11.149Z workers Starting run worker instance #5\n',
    '2023-07-24T05:02:11.149Z workers Web server is listening at 49465\n',
    '2023-07-24T05:02:11.150Z project File cache requires some updates, waiting required files from IDE\n',
    '2023-07-24T05:02:11.166Z project Stopping process pool\n',
    '2023-07-24T05:02:11.167Z project Test run started; run priority: 3\n',
    '2023-07-24T05:02:11.168Z project Running all tests\n',
    '2023-07-24T05:02:11.170Z workers Starting test run, priority: 3\n',
    '2023-07-24T05:02:11.170Z nodeRunner Starting sandbox [worker #0, session #gfshf]\n',
    '2023-07-24T05:02:11.170Z nodeRunner Preparing sandbox [worker #0, session #gfshf]\n',
    '2023-07-24T05:02:11.366Z workers Started run worker instance (delayed) #3\n',
    '2023-07-24T05:02:11.366Z workers Started run worker instance (delayed) #2\n',
    '2023-07-24T05:02:11.370Z workers Started run worker instance (delayed) #0\n',
    '2023-07-24T05:02:11.370Z nodeRunner Prepared sandbox [worker #0, session #gfshf]\n',
    '2023-07-24T05:02:11.371Z workers [worker #0, session #gfshf] Running tests in sandbox\n',
    '2023-07-24T05:02:11.373Z workers Started run worker instance (delayed) #4\n',
    '2023-07-24T05:02:11.375Z workers Started run worker instance (delayed) #1\n',
    '2023-07-24T05:02:11.376Z workers Started run worker instance (delayed) #5\n',
    '2023-07-24T05:02:13.279Z workers Scheduling Jest Test Run (gfshf): 2023-07-24T05:02:11.916Z\n',
    '2023-07-24T05:02:13.281Z workers Sandbox (active) [gfshf] error: Jest encountered an unexpected token\n' +
      '\n' +
      "This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.\n" +
      '\n' +
      'By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".\n' +
      '\n' +
      "Here's what you can do:\n" +
      ' ‚Ä¢ If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.\n' +
      ' ‚Ä¢ To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.\n' +
      ' ‚Ä¢ If you need a custom transformation specify a "transform" option in your config.\n' +
      ' ‚Ä¢ If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.\n' +
      '\n' +
      "You'll find more details and examples of these config options in the docs:\n" +
      'https://jestjs.io/docs/en/configuration.html\n' +
      '\n' +
      'Details:\n' +
      '\n' +
      './__test__/init.test.ts:2\n' +
      "import { handler as prepareHandler } from '../src/_prepareCaptureService/index';\n" +
      '^^^^^^\n' +
      '\n' +
      'SyntaxError: Cannot use import statement outside a module\n' +
      '    at new Script (node:vm:94:7)\n' +
      '    at Runtime.createScriptFromCode (<homeDir>/code/my/telewatcher/backend/node_modules/jest-runtime/build/index.js:1350:14)\n' +
      '    at Runtime._execModule (<homeDir>/code/my/telewatcher/backend/node_modules/jest-runtime/build/index.js:1245:25)\n' +
      '    at Runtime._loadModule (<homeDir>/code/my/telewatcher/backend/node_modules/jest-runtime/build/index.js:898:12)\n' +
      '    at Runtime.requireModule (<homeDir>/code/my/telewatcher/backend/node_modules/jest-runtime/build/index.js:746:10)\n' +
      '    at jasmine2 (<homeDir>/code/my/telewatcher/backend/node_modules/jest-jasmine2/build/index.js:230:13)\n' +
      '    at runTestInternal (<homeDir>/code/my/telewatcher/backend/node_modules/jest-runner/build/runTest.js:380:22)\n' +
      '    at runTest (<homeDir>/code/my/telewatcher/backend/node_modules/jest-runner/build/runTest.js:472:34)\n',
    '2023-07-24T05:02:13.282Z workers [gfshf] Run 0 test(s), skipped 0 test(s)\n',
    '2023-07-24T05:02:13.283Z workers Jest Test Run Complete (gfshf): 2023-07-24T05:02:13.277Z\n',
    '2023-07-24T05:02:13.284Z workers [gfshf] Sandbox is responsive, closing it\n',
    '2023-07-24T05:02:13.285Z project Test run finished\n',
    '2023-07-24T05:02:13.286Z project Processed console.log entries\n',
    '2023-07-24T05:02:13.286Z project Processed loading sequences\n',
    '2023-07-24T05:02:13.286Z project Processed executed tests\n',
    '2023-07-24T05:02:13.286Z project Processed code coverage\n',
    '2023-07-24T05:02:13.291Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by mburnell** [comment]
It looks like you may have out of date dependencies. Please delete your `package-lock.json` or `yarn.lock` file, and also your `node_modules` folder and reinstall.

**Comment by atako** [comment]
> It looks like you may have out of date dependencies. Please delete your `package-lock.json` or `yarn.lock` file, and also your `node_modules` folder and reinstall.

I tried but it did't help.

**Comment by mburnell** [comment]
Ok, thanks for trying that. I'm not sure why Jest is being detected. Could you please try replacing `autoDetect: true` with `autoDetect: ['vitest']`?

**Comment by atako** [comment]
> Ok, thanks for trying that. I'm not sure why Jest is being detected. Could you please try replacing `autoDetect: true` with `autoDetect: ['vitest']`?

Yes, this helped.
Thank you.
