### ISSUE TITLE
SyntaxError: Unexpected token ?​​ 

### ISSUE THREAD

**Issue by Jorriss** [wallabyjs/public#3250]
I've been upgrading an app to v3 of the AWS SDK. Wallby stopped working with the error
```​
[Error] Runtime error: ./node_modules/@aws-sdk/client-s3/dist-cjs/endpoint/EndpointParameters.js:7​​
​​[Error]         useFipsEndpoint: options.useFipsEndpoint ?? false,​​
​​[Error]                                                   ^​​
​​[Error] SyntaxError: Unexpected token ?​​
​​[Error]     at Module._compile (internal/modules/cjs/loader.js:723:23)​​
​​[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)​​
​​[Error]     at Module.load (internal/modules/cjs/loader.js:653:32)​​
​​[Error]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)​​
​​[Error]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)​​
​​[Error]     at Module.require (internal/modules/cjs/loader.js:692:17)​​
​​[Error]     at require (internal/modules/cjs/helpers.js:25:18)​​
​​[Error]     at Object.<anonymous> (./node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js:18:30)​​
​​[Error]     at Module._compile (internal/modules/cjs/loader.js:778:30)​​
​​[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)​​
​​[Error]     at Module.load (internal/modules/cjs/loader.js:653:32)​​
​​[Error]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)​​
​​[Error]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)​​
​​[Error]     at Module.require (internal/modules/cjs/loader.js:692:17)​​
​​[Error]     at require (internal/modules/cjs/helpers.js:25:18)​​
​​[Error]     at Object.<anonymous> (./node_modules/@aws-sdk/client-s3/dist-cjs/index.js:5:22)​​
​​[Error]     at Module._compile (internal/modules/cjs/loader.js:778:30)​​
​​[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)​​
​​[Error]     at Module.load (internal/modules/cjs/loader.js:653:32)​​
​​[Error]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)​​
​​[Error]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)​​
​​[Error]     at Module.require (internal/modules/cjs/loader.js:692:17)​​
​​[Error]     at require (internal/modules/cjs/helpers.js:25:18)​​
​​[Error]     at Object.<anonymous> (./common/lib/CloudStorage.js:3:178)​​
​​[Error]     at Module._compile (internal/modules/cjs/loader.js:778:30)​​
​​[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)​​
​​[Error]     at Module.load (internal/modules/cjs/loader.js:653:32)​​
​​[Error]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)​​
​​[Error]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)​​
​​[Error]     at Module.require (internal/modules/cjs/loader.js:692:17)​​
​​[Error]     at require (internal/modules/cjs/helpers.js:25:18)​​
​​[Error]     at Object.<anonymous> (./common/test/CloudStorage-test.js:7:39)​​
​​[Error]     at Module._compile (internal/modules/cjs/loader.js:778:30)​​
​​[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)​​
​​[Error]     at Module.load (internal/modules/cjs/loader.js:653:32)​​
​​[Error]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)​​
​​[Error]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)​​
​​[Error]     at Module.require (internal/modules/cjs/loader.js:692:17)​​
​​[Error]     at require (internal/modules/cjs/helpers.js:25:18)​​
​​[Error]     at Array.forEach (<anonymous>)​​
​​[Error]     at WebSocket.emit (events.js:198:13)​​
​​[Error]     at afterWrite (_stream_writable.js:485:3)​​
​​[Error]     at onwrite (_stream_writable.js:476:7)​​
​​[Error]     at InflateRaw.afterTransform (_stream_transform.js:94:3)​​
​​[Error]     at Zlib.processCallback (zlib.js:557:8)​​
```

### Wallaby diagnostics report
```
{ editorVersion: '1.80.1',
  pluginVersion: '1.0.364',
  editorType: 'VSCode',
  osVersion: 'darwin 22.5.0',
  nodeVersion: 'v10.18.1',
  coreVersion: '1.0.1451',
  checksum: 'MWM3OGM1MjdlODJhZDI1MGRhYmVkYmUxOGMzN2JhZmEsMTcwNjY1OTIwMDAwMCww',
  config:
   { files:
      [ { pattern: 'node_modules/**/*.js', ignore: true, trigger: true, load: true, instrument: true, file: true },
        { pattern: 'common/lib/CloudStorage.js', instrument: true, ignore: false, trigger: true, load: true, order: 1 } ],
     tests: [ { pattern: 'common/test/CloudStorage-test.js', ignore: false, trigger: true, load: true, test: true, order: 2 } ],
     env: { type: 'node', params: {}, runner: '<homeDir>/.nvm/versions/node/v10.18.1/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
     hints:
      { ignoreCoverage: '__REGEXP /ignore coverage/',
        ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
        commentAutoLog: '?',
        testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' } },
     diagnostics: {},
     captureConsoleLog: true,
     filesWithNoCoverageCalculated: [],
     runAllTestsInAffectedTestFile: false,
     updateNoMoreThanOneSnapshotPerTestFileRun: false,
     compilers: { '**/*.?(lit)coffee?(.md)': [Function] },
     logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
     preprocessors: {},
     maxConsoleMessagesPerTest: 100,
     autoConsoleLog: true,
     delays: { run: 0, edit: 100, update: 0 },
     workers: { initial: 0, regular: 0, recycle: false },
     teardown: undefined,
     automaticTestFileSelection: true,
     runSelectedTestsOnly: false,
     mapConsoleMessagesStackTrace: false,
     extensions: {},
     reportUnhandledPromises: true,
     testFramework: { version: 'mocha@2.1.0', configurator: 'mocha@2.1.0', reporter: 'mocha@2.1.0', starter: 'mocha@2.1.0' },
     slowTestThreshold: 75,
     lowCoverageThreshold: 80,
     runAllTestsWhenNoAffectedTests: true,
     symlinkNodeModules: undefined,
     configCode:
      'module.exports = function () {\n    return {\n        files: [\n            // \'**/lib/*.js\',\n            \'!node_modules/**/*.js\',\n            { pattern: \'common/lib/CloudStorage.js\', instrument: true } ,\n        ] ,\n\n        tests: [\n            \'common/test/CloudStorage-test.js\',\n        ],\n\n        setup: function (wallaby) {\n            global.expect = require(\'chai\').expect;\n            var mocha = wallaby.testFramework;\n            mocha.ui(\'tdd\');\n        } ,\n\n        env: {\n            type: \'node\'\n            // More options are described here\n            // http://wallabyjs.com/docs/integration/node.html\n        } ,\n\n        hints: {\n            ignoreCoverage: /ignore coverage/ \n        } ,\n    };\n};\n' },
  packageJSON:
   { dependencies: { '@aws-sdk/client-kms': '^3.370.0', '@aws-sdk/client-s3': '^3.373.0', '@aws-sdk/util-stream-node': '^3.374.0', jszip: '^3.2.2' },
     devDependencies:
      { '@types/node': '^18.16.19',
        'aws-sdk': '^2.1326.0',
        'aws-sdk-client-mock': '^3.0.0',
        chai: '^4.3.7',
        'chai-as-promised': '^7.1.1',
        del: '^6.1.1',
        dotenv: '^16.0.3',
        eslint: '^8.35.0',
        'eslint-plugin-import': '^2.27.5',
        'eslint-plugin-node': '^11.1.0',
        'eslint-plugin-promise': '^6.1.1',
        'eslint-plugin-standard': '^5.0.0',
        gulp: '^4.0.2',
        'gulp-clean': '^0.4.0',
        'gulp-ext-replace': '^0.3.0',
        ioredis: '^5.3.1',
        jsonpath: '^1.1.1',
        'mock-aws-s3': '^4.0.2',
        moment: '^2.29.4',
        'moment-timezone': '^0.5.41',
        mute: '^2.0.6',
        pg: '^8.10.0',
        sinon: '^15.0.1',
        uuid: '^9.0.0' } },
  fs: { numberOfFiles: 2 },
  debug:
   [ '2023-07-27T16:41:29.759Z project Wallaby Node version: v10.18.1\n',
     '2023-07-27T16:41:29.759Z project Wallaby config: <homeDir>/Brent Ozar Unlimited/Code/BlitzService/BlitzServerless/wallaby.js\n',
     '2023-07-27T16:41:29.796Z fs File system starting\n',
     '2023-07-27T16:41:29.838Z fs File system scan completed\n',
     '2023-07-27T16:41:29.845Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.364/projects/f921184a76355772\n',
     '2023-07-27T16:41:29.955Z uiService Listening port 51235\n',
     '2023-07-27T16:41:29.973Z workers Parallelism for initial run: 14, for regular run: 7\n',
     '2023-07-27T16:41:29.973Z workers Starting run worker instance #0\n',
     '2023-07-27T16:41:29.974Z workers Starting run worker instance #1\n',
     '2023-07-27T16:41:29.974Z workers Starting run worker instance #2\n',
     '2023-07-27T16:41:29.974Z workers Starting run worker instance #3\n',
     '2023-07-27T16:41:29.974Z workers Starting run worker instance #4\n',
     '2023-07-27T16:41:29.974Z workers Starting run worker instance #5\n',
     '2023-07-27T16:41:29.974Z workers Starting run worker instance #6\n',
     '2023-07-27T16:41:29.974Z workers Starting run worker instance #7\n',
     '2023-07-27T16:41:29.974Z workers Starting run worker instance #8\n',
     '2023-07-27T16:41:29.974Z workers Starting run worker instance #9\n',
     '2023-07-27T16:41:29.974Z workers Starting run worker instance #10\n',
     '2023-07-27T16:41:29.974Z workers Starting run worker instance #11\n',
     '2023-07-27T16:41:29.974Z workers Starting run worker instance #12\n',
     '2023-07-27T16:41:29.974Z workers Starting run worker instance #13\n',
     '2023-07-27T16:41:29.975Z workers Web server is listening at 51592\n',
     '2023-07-27T16:41:30.942Z workers Started run worker instance (delayed) #0\n',
     '2023-07-27T16:41:30.954Z workers Started run worker instance (delayed) #3\n',
     '2023-07-27T16:41:30.956Z workers Started run worker instance (delayed) #1\n',
     '2023-07-27T16:41:30.961Z workers Started run worker instance (delayed) #4\n',
     '2023-07-27T16:41:30.970Z workers Started run worker instance (delayed) #6\n',
     '2023-07-27T16:41:30.972Z workers Started run worker instance (delayed) #2\n',
     '2023-07-27T16:41:30.978Z workers Started run worker instance (delayed) #5\n',
     '2023-07-27T16:41:30.980Z workers Started run worker instance (delayed) #7\n',
     '2023-07-27T16:41:30.981Z workers Started run worker instance (delayed) #8\n',
     '2023-07-27T16:41:30.996Z workers Started run worker instance (delayed) #9\n',
     '2023-07-27T16:41:30.999Z workers Started run worker instance (delayed) #10\n',
     '2023-07-27T16:41:31.006Z workers Started run worker instance (delayed) #11\n',
     '2023-07-27T16:41:31.012Z workers Started run worker instance (delayed) #13\n',
     '2023-07-27T16:41:31.013Z workers Started run worker instance (delayed) #12\n',
     '2023-07-27T16:41:33.149Z project Stopping process pool\n',
     '2023-07-27T16:41:33.150Z project File cache is up-to-date, starting full test run\n',
     '2023-07-27T16:41:33.153Z project Running postprocessor\n',
     '2023-07-27T16:41:33.160Z postprocessor New TypeScript language service is required\n',
     '2023-07-27T16:41:33.161Z postprocessor TypeScript postprocessor will be removed because in 2 project files none were found by patterns: **/*.ts?(x)\n',
     '2023-07-27T16:41:33.161Z project Postprocessor execution finished\n',
     '2023-07-27T16:41:33.161Z project Postprocessor is removed as requested by itself\n',
     '2023-07-27T16:41:33.162Z project Test run started; run priority: 3\n',
     '2023-07-27T16:41:33.162Z project Running all tests\n',
     '2023-07-27T16:41:33.164Z workers Starting test run, priority: 3\n',
     '2023-07-27T16:41:33.165Z nodeRunner Starting sandbox [worker #0, session #sulbg]\n',
     '2023-07-27T16:41:33.165Z nodeRunner Preparing sandbox [worker #0, session #sulbg]\n',
     '2023-07-27T16:41:33.165Z nodeRunner Prepared sandbox [worker #0, session #sulbg]\n',
     '2023-07-27T16:41:33.166Z workers [worker #0, session #sulbg] Running tests in sandbox\n',
     '2023-07-27T16:41:33.541Z workers Sandbox (active) [sulbg] error: ./node_modules/@aws-sdk/client-s3/dist-cjs/endpoint/EndpointParameters.js:7\n        useFipsEndpoint: options.useFipsEndpoint ?? false,\n                                                  ^\n\nSyntaxError: Unexpected token ?\n    at Module._compile (internal/modules/cjs/loader.js:723:23)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (./node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js:18:30)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (./node_modules/@aws-sdk/client-s3/dist-cjs/index.js:5:22)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (./common/lib/CloudStorage.js:3:178)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (./common/test/CloudStorage-test.js:7:39)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Array.forEach (<anonymous>)\n    at WebSocket.emit (events.js:198:13)\n    at afterWrite (_stream_writable.js:485:3)\n    at onwrite (_stream_writable.js:476:7)\n    at InflateRaw.afterTransform (_stream_transform.js:94:3)\n    at Zlib.processCallback (zlib.js:557:8)\n',
     '2023-07-27T16:41:33.643Z workers [sulbg] Run 0 test(s), skipped 0 test(s)\n',
     '2023-07-27T16:41:33.646Z workers [sulbg] Sandbox is responsive, closing it\n',
     '2023-07-27T16:41:33.647Z project Test run finished\n',
     '2023-07-27T16:41:33.648Z project Processed console.log entries\n',
     '2023-07-27T16:41:33.648Z project Processed loading sequences\n',
     '2023-07-27T16:41:33.648Z project Processed executed tests\n',
     '2023-07-27T16:41:33.653Z project Processed code coverage\n',
     '2023-07-27T16:41:33.729Z project Test run result processed and sent to IDE\n' ] }
```

**Comment by ArtemGovorov** [comment]
Thanks for providing the diagnostics report.

According to the log, Wallaby is using `nodeVersion: 'v10.18.1',` that doesn't support nullish coalescing operator (`??`).

By default Wallaby uses node path from your system's `PATH`, and in your case the resolved version is too old to run the required code. Yo may either update your system's default node version or point Wallaby to use any installed node version via the [VS Code Wallaby setting](https://wallabyjs.com/docs/intro/install.html):

```
{
    ...
    "wallaby.node": "/Users/user/.nvm/versions/node/v20.0.0/bin/node"
}
```

**Comment by smcenlly** [comment]
Your problem is a result of using an incompatible version of node with the `@aws-sdk/client-s3` library. The `@aws-sdk/client-s3` package uses the [Nullish coalescing operator (??)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) that was not supported until `node@14.0.0`. 

For the version of `@aws-sdk/client-s3` that you are using, the [`package.json`](https://github.com/aws/aws-sdk-js-v3/blob/7ce1427b24a96e4006e4a10e80339a7df52101d1/clients/client-s3/package.json#L93) specifies a node version of `"node": ">=14.0.0"`.

Your diagnostic report shows that you are using `node@10.18.1`. This version of node is quite old and has been end of life since April, 2021.

By default, Wallaby uses your your system default `node` version. If you want to keep `node@10.18.1` as your system version, you can provide a different version to Wallaby in your configuration file with the [`env.runner` property](https://wallabyjs.com/docs/integration/node.html#node-version).

---

Please update your node version, it will fix your problem.

**Comment by Jorriss** [comment]
I assumed that it would use the nvm version but that makes sense. I pointed it to use a more current javascript version and it worked. Thanks for the quick response.
