### ISSUE TITLE
"Unexpected token '.'" Wallaby, Remix, TypeScript, jest, ts-jest.

### ISSUE THREAD

**Issue by slackermorris** [wallabyjs/public#3266]
### Issue description or question

Firstly, thanks a bunch for this tool.

Quick notes:

1. I'm making use of the automatic configuration.
2. I am working on a Remix project.

I have a Remix project that I am attempting to run Wallaby on but am running into an issue with a library import from [`@remix-run/node`](https://remix.run/docs/en/main/other-api/node). I get the error:

```cli
Unexpected token '.' 
  ​​​​​at Object.<anonymous> ​​​​​​test/setup-test-env.ts:1:1
```

With the `setup-test-env.ts` file being:

```typescript
import { installGlobals } from "@remix-run/node";
import "@testing-library/jest-dom/extend-expect";

installGlobals();
```

<img width="1109" alt="Screen Shot 2023-09-01 at 12 26 55 PM" src="https://github.com/wallabyjs/public/assets/35620369/55e62e38-d412-4c7a-a964-4481c500ec17">

I feel rotten raising an issue because it feels to me because, through my researching this, you have already fielded a tonne of "issues" that are less about Wallaby and more about gaps in peoples understanding of JS module standards (Common, ES) and the relevance of this to transpilers, compilers, and test frameworks. So, I apologise in advance because I know the problem here is a similar gap in my understanding and no fault of Wallaby.

But, alas, here I am. And any help would greatly be appreciated.

```json
// package.json

"jest": "^27.5.1",
"ts-jest": "^27.1.4",
"typescript": "^4.6.3"
```

```typescript
// jest.config.ts

export default {
  preset: "ts-jest/presets/default-esm",
  testEnvironment: "jsdom",

  globals: {
    "ts-jest": {
      tsconfig: "<rootDir>/tsconfig.json",
      diagnostics: {
        pathRegex: /\.(spec|test)\.ts$/,
        warnOnly: true,
      },
    },
  },

  testPathIgnorePatterns: ["<rootDir>/node_modules/", "<rootDir>/.next/"],

  /* <!--  📥 TS Support (jest code transformations/ ts-jest transpiler) --> */
  transform: {
    "^.+\\.tsx?$": "ts-jest",
  },
  transformIgnorePatterns: ["/node_modules/"],

  // Runs special logic, such as cleaning up components
  // when using React Testing Library and adds special
  // extended assertions to Jest
  setupFilesAfterEnv: ["<rootDir>/test/setup-test-env.ts"],
  moduleDirectories: ["node_modules", "app"],
  moduleNameMapper: {
    "~/(.*)": "<rootDir>/app/$1",
  },
  // /* <!--  📥 Test Spec File Resolution Pattern (parent folder `__tests__`; filename to contain `test` or `spec`) --> */
  testRegex: "(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$",

  // Module file extensions for importing
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
};
```

```typescript
// tsconfig.json
{
  "exclude": ["./cypress"],
  "include": ["remix.env.d.ts", "*.d.ts", "app/*.ts", "/*.tsx"],
  "compilerOptions": {
    "lib": ["DOM", "DOM.Iterable", "ES2019"],
    "types": ["node", "jest"],
    "isolatedModules": true,
    "esModuleInterop": true,
    "jsx": "react-jsx",
    "module": "CommonJS",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "target": "ES2019",
    "strict": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./app/*"],
      "fuzzy-scrawl-styles": ["./node_modules/fuzzy-scrawl/build/index.css"],
      "animejs": ["animejs/lib/anime.es.js"]
    },
    "skipLibCheck": true,
    "noEmit": true,
    "forceConsistentCasingInFileNames": true,
    "allowJs": true
  }
}
```

### Wallaby diagnostics report

```
{
  editorVersion: '1.81.1',
  pluginVersion: '1.0.365',
  editorType: 'VSCode',
  osVersion: 'darwin 21.4.0',
  nodeVersion: 'v12.14.1',
  coreVersion: '1.0.1465',
  checksum: 'ODQ1MzQ3Yjc2OGQ5MmVjMDc0NWMwOWIxZWMyYTc0N2UsMTY5NDEzMTIwMDAwMCwx',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/private/var/folders/g6/jvn206x501z9_fqzl7ph6p8r0000gn/T/jest_dx',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/Code/better-brain-blogging',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: undefined,
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [ '.ts', '.tsx' ],
              extraGlobals: [],
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: { 'ts-jest': { tsconfig: '<rootDir>/tsconfig.json', diagnostics: { pathRegex: /\.(spec|test)\.ts$/, warnOnly: true } } },
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: false, throwOnModuleCollision: false },
              injectGlobals: true,
              moduleDirectories: [ 'node_modules', 'app' ],
              moduleFileExtensions: [ 'ts', 'tsx', 'js', 'jsx', 'json', 'node' ],
              moduleLoader: undefined,
              moduleNameMapper: [ [ '~/(.*)', '<homeDir>/Code/better-brain-blogging/app/$1' ] ],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              name: '5ae5fbffae2515d0b85f3ecd32596731',
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/Code/better-brain-blogging',
              roots: [ '<homeDir>/Code/better-brain-blogging' ],
              runner: '<homeDir>/Code/better-brain-blogging/node_modules/jest-runner/build/index.js',
              setupFiles: [],
              setupFilesAfterEnv: [ '<homeDir>/Code/better-brain-blogging/test/setup-test-env.ts' ],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/Code/better-brain-blogging/node_modules/jest-environment-jsdom/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [],
              testPathIgnorePatterns: [ '<homeDir>/Code/better-brain-blogging/node_modules/', '<homeDir>/Code/better-brain-blogging/.next/' ],
              testRegex: [ '(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$' ],
              testRunner: '<homeDir>/Code/better-brain-blogging/node_modules/jest-circus/runner.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [ [ '^.+\\.tsx?$', '<homeDir>/Code/better-brain-blogging/node_modules/ts-jest/dist/index.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: [],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<homeDir>/Code/better-brain-blogging/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 7,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/Code/better-brain-blogging',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: undefined,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/Code/better-brain-blogging/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [
              '/node_modules/',
              '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
              '/private/var/folders/g6/jvn206x501z9_fqzl7ph6p8r0000gn/T/jest_dx',
              '\\./node_modules/',
              '\\./.next/',
              '\\./coverage'
            ],
            testPathIgnorePatterns: [
              '/node_modules/',
              '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
              '/private/var/folders/g6/jvn206x501z9_fqzl7ph6p8r0000gn/T/jest_dx',
              '\\./node_modules/',
              '\\./.next/',
              '\\./coverage'
            ],
            testMatch: [],
            testRegex: [ '(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$' ]
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    dot: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, file: true, test: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        file: true,
        test: true
      },
      {
        pattern: '/private/var/folders/g6/jvn206x501z9_fqzl7ph6p8r0000gn/T/jest_dx',
        regexp: /\/private\/var\/folders\/g6\/jvn206x501z9_fqzl7ph6p8r0000gn\/T\/jest_dx/,
        ignore: true,
        trigger: true,
        load: true,
        file: true,
        test: true
      },
      { pattern: '\\./node_modules/', regexp: /\.\/node_modules\//, ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '\\./.next/', regexp: /\.\/.next\//, ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$', regexp: /(\/__tests__\/.*|(\.|\/)(test|spec))\.tsx?$/, ignore: true, trigger: true, load: true, file: true }
    ],
    captureConsoleLog: true,
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true, file: false },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true,
        file: false
      },
      {
        pattern: '/private/var/folders/g6/jvn206x501z9_fqzl7ph6p8r0000gn/T/jest_dx',
        regexp: /\/private\/var\/folders\/g6\/jvn206x501z9_fqzl7ph6p8r0000gn\/T\/jest_dx/,
        ignore: true,
        trigger: true,
        load: true,
        test: true,
        file: false
      },
      { pattern: '\\./node_modules/', regexp: /\.\/node_modules\//, ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '\\./.next/', regexp: /\.\/.next\//, ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$', regexp: /(\/__tests__\/.*|(\.|\/)(test|spec))\.tsx?$/, ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: {
      type: 'node',
      params: {},
      runner: '<homeDir>/.nvm/versions/node/v12.14.1/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: false,
    configCode: 'auto.detect#-237178725'
  },
  packageJSON: {
    dependencies: {
      '@architect/architect': '^10.2.1',
      '@architect/functions': '^5.0.4',
      '@happy-dom/jest-environment': '^3.1.0',
      '@notionhq/client': '^1.0.4',
      '@remix-run/architect': '^1.7.2',
      '@remix-run/node': '^1.7.2',
      '@remix-run/react': '^1.7.2',
      '@remix-run/server-runtime': '^1.7.2',
      animejs: '^3.2.1',
      bcryptjs: '2.4.3',
      'bostock-metaball-animation': '^1.0.0',
      classnames: '^2.3.1',
      cuid: '^2.1.8',
      'fuzzy-scrawl': '^1.0.4',
      'highlight.js': '^11.5.1',
      react: '^18.2.0',
      'react-dom': '^18.2.0',
      'tiny-invariant': '^1.2.0'
    },
    devDependencies: {
      '@remix-run/dev': '^1.7.2',
      '@remix-run/eslint-config': '^1.7.2',
      '@testing-library/cypress': '^8.0.7',
      '@testing-library/jest-dom': '^5.16.3',
      '@testing-library/react': '^12.1.4',
      '@testing-library/user-event': '^14.0.4',
      '@types/architect__functions': '^3.13.6',
      '@types/bcryptjs': '2.4.2',
      '@types/eslint': '^8.4.1',
      '@types/jest': '^27.4.1',
      '@types/react': '^18.0.21',
      '@types/react-dom': '^18.0.6',
      c8: '^7.11.0',
      'cross-env': '^7.0.3',
      cypress: '^12.0.2',
      esbuild: '^0.14.29',
      eslint: '^8.12.0',
      'eslint-config-prettier': '^8.5.0',
      'eslint-plugin-cypress': '^2.12.1',
      'happy-dom': '^2.55.0',
      jest: '^27.5.1',
      'mock-aws-s3': '^4.0.2',
      msw: '^0.39.2',
      'notion-api-types': '^1.0.0',
      'npm-run-all': '^4.1.5',
      prettier: '^2.6.1',
      'prettier-plugin-tailwindcss': '^0.1.8',
      'start-server-and-test': '^1.14.0',
      tailwindcss: '^3.0.23',
      'ts-jest': '^27.1.4',
      'ts-node': '^10.7.0',
      typescript: '^4.6.3'
    }
  },
  fs: { numberOfFiles: 7014 },
  debug: [
    '2023-09-01T00:11:38.111Z config Attempting automatic configuration for angular\n',
    '2023-09-01T00:11:38.114Z angular/cli config Angular CLI not found.\n',
    '2023-09-01T00:11:38.114Z config Finished attempting automatic configuration for angular (3ms)\n',
    '2023-09-01T00:11:38.115Z config Attempting automatic configuration for jest\n',
    '2023-09-01T00:11:40.379Z jest/config Detected Jest.\n',
    '2023-09-01T00:11:40.380Z jest/config Configured Jest.\n',
    '2023-09-01T00:11:40.380Z config Finished attempting automatic configuration for jest (2265ms)\n',
    '2023-09-01T00:11:40.381Z project Wallaby Node version: v12.14.1\n',
    '2023-09-01T00:11:40.381Z project Wallaby config: <homeDir>/Code/better-brain-blogging/auto.detect\n',
    '2023-09-01T00:11:40.418Z fs File system starting\n',
    '2023-09-01T00:11:40.846Z fs File system scan completed\n',
    '2023-09-01T00:11:40.885Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.365/projects/fc30b7b41b28916c\n',
    '2023-09-01T00:11:40.942Z uiService Listening port 51235\n',
    '2023-09-01T00:11:41.051Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2023-09-01T00:11:41.052Z workers Starting run worker instance #0\n',
    '2023-09-01T00:11:41.052Z workers Starting run worker instance #1\n',
    '2023-09-01T00:11:41.052Z workers Starting run worker instance #2\n',
    '2023-09-01T00:11:41.052Z workers Starting run worker instance #3\n',
    '2023-09-01T00:11:41.052Z workers Starting run worker instance #4\n',
    '2023-09-01T00:11:41.052Z workers Starting run worker instance #5\n',
    '2023-09-01T00:11:41.052Z workers Web server is listening at 53491\n',
    '2023-09-01T00:11:41.212Z project Stopping process pool\n',
    '2023-09-01T00:11:41.212Z project File cache is up-to-date, starting full test run\n',
    '2023-09-01T00:11:41.215Z project Test run started; run priority: 3\n',
    '2023-09-01T00:11:41.233Z project Running all tests\n',
    '2023-09-01T00:11:41.334Z workers Starting test run, priority: 3\n',
    '2023-09-01T00:11:41.334Z workers Distributing tests between 6 workers\n',
    '2023-09-01T00:11:41.337Z workers Running tests in parallel\n',
    '2023-09-01T00:11:41.337Z nodeRunner Starting sandbox [worker #0, session #p39tw]\n',
    '2023-09-01T00:11:41.337Z nodeRunner Starting sandbox [worker #1, session #13st5]\n',
    '2023-09-01T00:11:41.337Z nodeRunner Preparing sandbox [worker #0, session #p39tw]\n',
    '2023-09-01T00:11:41.337Z nodeRunner Preparing sandbox [worker #1, session #13st5]\n',
    '2023-09-01T00:11:41.347Z workers Started run worker instance (delayed) #1\n',
    '2023-09-01T00:11:41.348Z nodeRunner Prepared sandbox [worker #1, session #13st5]\n',
    '2023-09-01T00:11:41.348Z workers [worker #1, session #13st5] Running tests in sandbox\n',
    '2023-09-01T00:11:41.357Z workers Started run worker instance (delayed) #0\n',
    '2023-09-01T00:11:41.357Z nodeRunner Prepared sandbox [worker #0, session #p39tw]\n',
    '2023-09-01T00:11:41.357Z workers [worker #0, session #p39tw] Running tests in sandbox\n',
    '2023-09-01T00:11:41.368Z workers Started run worker instance (delayed) #2\n',
    '2023-09-01T00:11:41.374Z workers Started run worker instance (delayed) #3\n',
    '2023-09-01T00:11:41.397Z workers Started run worker instance (delayed) #4\n',
    '2023-09-01T00:11:41.404Z workers Started run worker instance (delayed) #5\n',
    '2023-09-01T00:11:49.979Z workers Scheduling Jest Test Run (13st5): 2023-09-01T00:11:44.578Z\n',
    '2023-09-01T00:11:49.985Z workers Sandbox (active) [13st5] error: Jest encountered an unexpected token\n' +
      '\n' +
      'Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.\n' +
      '\n' +
      'Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.\n' +
      '\n' +
      'By default "node_modules" folder is ignored by transformers.\n' +
      '\n' +
      "Here's what you can do:\n" +
      ' ‚Ä¢ If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.\n' +
      ' ‚Ä¢ If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript\n' +
      ' ‚Ä¢ To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.\n' +
      ' ‚Ä¢ If you need a custom transformation specify a "transform" option in your config.\n' +
      ' ‚Ä¢ If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.\n' +
      '\n' +
      "You'll find more details and examples of these config options in the docs:\n" +
      'https://jestjs.io/docs/configuration\n' +
      'For information about custom transformations, see:\n' +
      'https://jestjs.io/docs/code-transformation\n' +
      '\n' +
      'Details:\n' +
      '\n' +
      './node_modules/@remix-run/web-fetch/dist/lib.node.cjs:278\n' +
      "  const contentType = headers?.get('Content-Type') || '';\n" +
      '                              ^\n' +
      '\n' +
      "SyntaxError: Unexpected token '.'\n" +
      '    at new Script (vm.js:84:7)\n' +
      '    at Runtime.createScriptFromCode (./node_modules/jest-runtime/build/index.js:1728:14)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1596:25)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:1185:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:1009:12)\n' +
      '    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:1210:21)\n' +
      '    at Object.<anonymous> (./node_modules/@remix-run/node/dist/fetch.js:15:16)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1646:24)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:1185:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:1009:12)\n' +
      '    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:1210:21)\n' +
      '    at Object.<anonymous> (./node_modules/@remix-run/node/dist/index.js:17:13)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1646:24)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:1185:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:1009:12)\n' +
      '    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:1210:21)\n' +
      '    at Object.<anonymous> (./test/setup-test-env.ts:4:36)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1646:24)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:1185:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:1009:12)\n' +
      '    at jestAdapter (./node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:70:15)\n' +
      '    at async runTestInternal (./node_modules/jest-runner/build/runTest.js:389:16)\n' +
      '    at async runTest (./node_modules/jest-runner/build/runTest.js:475:34)\n' +
      '    at async TestRunner.runTests (./node_modules/jest-runner/build/index.js:101:12)\n' +
      '    at async TestScheduler.scheduleTests (./node_modules/@jest/core/build/TestScheduler.js:333:13)\n',
    '2023-09-01T00:11:49.987Z workers [13st5] Run 0 test(s), skipped 0 test(s)\n',
    '2023-09-01T00:11:49.987Z workers Jest Test Run Complete (13st5): 2023-09-01T00:11:49.977Z\n',
    '2023-09-01T00:11:49.988Z workers [13st5] Sandbox is responsive, closing it\n',
    '2023-09-01T00:11:50.000Z workers Scheduling Jest Test Run (p39tw): 2023-09-01T00:11:44.578Z\n',
    '2023-09-01T00:11:50.003Z workers Sandbox (active) [p39tw] error: Jest encountered an unexpected token\n' +
      '\n' +
      'Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.\n' +
      '\n' +
      'Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.\n' +
      '\n' +
      'By default "node_modules" folder is ignored by transformers.\n' +
      '\n' +
      "Here's what you can do:\n" +
      ' ‚Ä¢ If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.\n' +
      ' ‚Ä¢ If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript\n' +
      ' ‚Ä¢ To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.\n' +
      ' ‚Ä¢ If you need a custom transformation specify a "transform" option in your config.\n' +
      ' ‚Ä¢ If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.\n' +
      '\n' +
      "You'll find more details and examples of these config options in the docs:\n" +
      'https://jestjs.io/docs/configuration\n' +
      'For information about custom transformations, see:\n' +
      'https://jestjs.io/docs/code-transformation\n' +
      '\n' +
      'Details:\n' +
      '\n' +
      './node_modules/@remix-run/web-fetch/dist/lib.node.cjs:278\n' +
      "  const contentType = headers?.get('Content-Type') || '';\n" +
      '                              ^\n' +
      '\n' +
      "SyntaxError: Unexpected token '.'\n" +
      '    at new Script (vm.js:84:7)\n' +
      '    at Runtime.createScriptFromCode (./node_modules/jest-runtime/build/index.js:1728:14)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1596:25)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:1185:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:1009:12)\n' +
      '    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:1210:21)\n' +
      '    at Object.<anonymous> (./node_modules/@remix-run/node/dist/fetch.js:15:16)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1646:24)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:1185:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:1009:12)\n' +
      '    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:1210:21)\n' +
      '    at Object.<anonymous> (./node_modules/@remix-run/node/dist/index.js:17:13)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1646:24)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:1185:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:1009:12)\n' +
      '    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:1210:21)\n' +
      '    at Object.<anonymous> (./test/setup-test-env.ts:4:36)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1646:24)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:1185:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:1009:12)\n' +
      '    at jestAdapter (./node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:70:15)\n' +
      '    at async runTestInternal (./node_modules/jest-runner/build/runTest.js:389:16)\n' +
      '    at async runTest (./node_modules/jest-runner/build/runTest.js:475:34)\n' +
      '    at async TestRunner.runTests (./node_modules/jest-runner/build/index.js:101:12)\n' +
      '    at async TestScheduler.scheduleTests (./node_modules/@jest/core/build/TestScheduler.js:333:13)\n',
    '2023-09-01T00:11:50.004Z workers [p39tw] Run 0 test(s), skipped 0 test(s)\n',
    '2023-09-01T00:11:50.004Z workers Jest Test Run Complete (p39tw): 2023-09-01T00:11:49.998Z\n',
    '2023-09-01T00:11:50.004Z workers [p39tw] Sandbox is responsive, closing it\n',
    '2023-09-01T00:11:50.005Z workers Merging parallel test run results\n',
    '2023-09-01T00:11:50.006Z project Test run finished\n',
    '2023-09-01T00:11:50.006Z project Processed console.log entries\n',
    '2023-09-01T00:11:50.006Z project Processed loading sequences\n',
    '2023-09-01T00:11:50.006Z project Processed executed tests\n',
    '2023-09-01T00:11:50.029Z project Processed code coverage\n',
    '2023-09-01T00:11:50.095Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by smcenlly** [comment]
Your diagnostics report shows that you are using `node@12.14.1`. The compiled modules for remix are using the optional chaining operator (`?.`) which was not supported until `node@14.0.0`.

You will need to update your node version to fix the problem.

By default, Wallaby will use your system's node version (found in your system PATH). You can explicitly provide the node path with the `wallaby.node` setting:

<img width="1062" alt="image" src="https://github.com/wallabyjs/public/assets/2074089/4334dee6-bcc3-4100-b9ed-a5f3fab833bc">

---

We also noticed conflicts in your dependencies. If you delete your `yarn.lock`, `package-lock.json` files and `node_modules` folder, and reinstall with `npm install`, you will be able to identify the conflicts that you need to fix.

**Comment by slackermorris** [comment]
Ahhhh. That makes sense @smcenlly. Yeah, I use `nvm` so silly-ey made an assumption that the node version would be picked up. I went back to the Wallaby docs and found this:

>If you have multiple versions of node.js installed or don’t have node path in your PATH, and you would like wallaby.js to run with a specific version (for example if you are using nvm), you may use wallaby.node setting in your settings.json file to specify the full path to node.js executable file.

And that recommends to do:

```
// Place your settings in this file to overwrite the default settings
{
    ...
    "wallaby.node": "/Users/user/.nvm/versions/node/v4.1.1/bin/node"
}
```

So, I tried that.

```
// my own settings.json
{
    ...
    "wallaby.node": "/Users/jackwilliammorris/.nvm/versions/node/v14.8.1/bin/node"
}
```

But I get the following error:

```
Can not start node.js process (/Users/jackwilliammorris/.nvm/versions/node/v12.8.1/bin/node), make sure your system has node.js installed
```

Which is weird given that that version of node is present under `nvm`.

<img width="573" alt="Screen Shot 2023-09-01 at 5 32 49 PM" src="https://github.com/wallabyjs/public/assets/35620369/8f638cab-2499-42c5-9281-c597edd002d2">

**Comment by ArtemGovorov** [comment]
> Can not start node.js process (/Users/jackwilliammorris/.nvm/versions/node/v12.8.1/bin/node), make sure your system has node.js installed

The error typically means that Wallaby can't locate the file by the provided path.
Can you please double check that the file exists (by pasting the path in your terminal to try to run it with `-v` flag fro example)? I have noticed that your error message mentions `v12.8.1` while your setting has `v14.8.1`.

**Comment by slackermorris** [comment]
Man, I'm sorry for wasting your time. I had:

```json
"wallaby.node": "/Users/jackwilliammorris/.nvm/versions/node/v14.8.1/bin/node"
```

And not:

```json
"wallaby.node": "/Users/jackwilliammorris/.nvm/versions/node/v14.18.1/bin/node"
```

`v14.8.1` and not `v14.18.1`. I'm a goon. Thanks for all the help.
