### ISSUE TITLE
Doesn't show some errors from vitest

### ISSUE THREAD

**Issue by polRk** [wallabyjs/public#3273]
### Issue description or question

Wallaby show success test result, but vitest show an error.

<img width="749" alt="SCR-20230918-kkex" src="https://github.com/wallabyjs/public/assets/39828645/a6ddbdfb-6d8d-4016-bc8b-4736a4564203">

### Wallaby diagnostics report

```js
{
  editorVersion: '1.82.0',
  pluginVersion: '1.0.367',
  editorType: 'VSCode',
  osVersion: 'linux 4.18.0-477.13.1.el8_8.x86_64',
  nodeVersion: 'v20.4.0',
  coreVersion: '1.0.1467',
  checksum: 'YzhmY2QyYTM2OTZiNWU5ZTlmYWI1YzI3NTg1ODhmNzYsMTcwMzM3NjAwMDAwMCww',
  config: {
    diagnostics: {
      vitest: {
        file: {
          config: 'import { dirname } from "node:path";\n' +
            'import { fileURLToPath } from "node:url";\n' +
            '\n' +
            'import { defineProject } from "vitest/config";\n' +
            'import pkg from "./package.json" assert { type: "json" };\n' +
            '\n' +
            'export default defineProject({\n' +
            '  test: {\n' +
            '    name: pkg.name,\n' +
            '    root: dirname(fileURLToPath(import.meta.url)),\n' +
            '  },\n' +
            '});\n'
        },
        config: {
          allowOnly: true,
          watch: true,
          globals: false,
          environment: 'node',
          threads: true,
          clearMocks: false,
          restoreMocks: false,
          mockReset: false,
          include: [ '**/*.{test,spec}.?(c|m)[jt]s?(x)' ],
          exclude: [
            '**/node_modules/**',
            '**/dist/**',
            '**/cypress/**',
            '**/.{idea,git,cache,output,temp}/**',
            '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*'
          ],
          testTimeout: 5000,
          hookTimeout: 10000,
          teardownTimeout: 10000,
          isolate: true,
          watchExclude: [ '**/node_modules/**', '**/dist/**' ],
          forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**' ],
          update: false,
          reporters: [ 'default' ],
          silent: false,
          hideSkippedTests: false,
          ui: false,
          uiBase: '/__vitest__/',
          open: true,
          css: { include: [], modules: { classNameStrategy: 'stable' } },
          coverage: {
            provider: 'v8',
            enabled: false,
            clean: true,
            cleanOnRerun: true,
            reportsDirectory: './coverage',
            exclude: [
              'coverage/**',
              'dist/**',
              'packages/*/test?(s)/**',
              '**/*.d.ts',
              '**/virtual:*',
              '**/__x00__*',
              '**/\x00*',
              'cypress/**',
              'test?(s)/**',
              'test?(-*).?(c|m)[jt]s?(x)',
              '**/*{.,-}{test,spec}.?(c|m)[jt]s?(x)',
              '**/__tests__/**',
              '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*',
              '**/vitest.{workspace,projects}.[jt]s?(on)',
              '**/.{eslint,mocha,prettier}rc.{?(c|m)js,yml}'
            ],
            reportOnFailure: false,
            reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
            extension: [
              '.js',  '.cjs',
              '.mjs', '.ts',
              '.mts', '.cts',
              '.tsx', '.jsx',
              '.vue', '.svelte'
            ],
            allowExternal: false
          },
          fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
          maxConcurrency: 5,
          dangerouslyIgnoreUnhandledErrors: false,
          typecheck: {
            checker: 'tsc',
            include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
            exclude: [
              '**/node_modules/**',
              '**/dist/**',
              '**/cypress/**',
              '**/.{idea,git,cache,output,temp}/**',
              '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*'
            ]
          },
          slowTestThreshold: 300,
          name: '@monorepo/graphql',
          root: '<homeDir>/monorepo/apps/graphql',
          config: '<homeDir>/monorepo/apps/graphql/vitest.config.ts',
          defines: {},
          mode: [],
          inspect: false,
          inspectBrk: false,
          singleThread: false,
          deps: {
            moduleDirectories: [ '/node_modules/' ],
            optimizer: { ssr: { enabled: true }, web: { enabled: true } },
            web: { transformAssets: true, transformCss: true, transformGlobPattern: [] }
          },
          server: { deps: { inline: [ {}, {}, {}, '@nuxt/test-utils' ], moduleDirectories: [ '/node_modules/' ], cacheDir: 'node_modules/.vitest' } },
          snapshotOptions: { snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
          experimentalVmWorkerMemoryLimit: 4179631616,
          setupFiles: [],
          cache: { dir: '<homeDir>/monorepo/apps/graphql/node_modules/.vitest' },
          sequence: { hooks: 'parallel' },
          environmentMatchGlobs: [],
          browser: { enabled: false, headless: false, slowHijackESM: true, api: { port: 63315 } },
          testTransformMode: {},
          package: {
            version: '0.34.3',
            urls: { hooks: 'file://<homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.367/wallaby/runners/node/hooks.mjs' },
            paths: { root: '<homeDir>/monorepo/node_modules/vitest', dist: '<homeDir>/monorepo/node_modules/vitest/dist' }
          }
        }
      }
    },
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0', autoDetected: true },
    preserveComments: false,
    extractComments: true,
    files: [
      { pattern: '**/*.{test,spec}.?(c|m)[jt]s?(x)', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/*.*', ignore: false, trigger: true, load: true, order: 1 }
    ],
    tests: [
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/*.{test,spec}.?(c|m)[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    workers: { initial: 1, regular: 1, recycle: false },
    captureConsoleLog: true,
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    smartStart: [
      { test: true, source: false, path: 'src/resolvers/areaResolver.test.ts', startMode: 'always' },
      { test: true, source: false, pattern: '**/*', startMode: 'open' },
      { test: false, source: true, pattern: '**/*', startMode: 'edit' }
    ],
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: true,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: {
      type: 'node',
      params: { runner: '--experimental-loader=file://<homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.367/wallaby/runners/node/hooks.mjs' },
      runner: '/usr/local/lib/nodejs/node-v20.4.0-linux-x64/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: true,
    symlinkNodeModules: true,
    configCode: 'auto.detect#2145583041',
    testLocations: [ 'src/resolvers/areaResolver.test.ts' ]
  },
  packageJSON: {
    dependencies: {
      '@envelop/core': '^4.0.0',
      '@gquittet/graceful-server': '^4.0.8',
      '@graphql-tools/executor-http': '^1.0.2',
      '@graphql-tools/schema': '^10.0.0',
      '@graphql-yoga/render-graphiql': '^3.9.1',
      '@grpc/grpc-js': '^1.9.0',
      '@opentelemetry/api': '^1.4.1',
      '@opentelemetry/semantic-conventions': '^1.15.2',
      '@tinkoff/utils': '^2.6.2',
      '@monorepo/certs': '*',
      '@monorepo/config': '*',
      '@monorepo/constants': '*',
      '@monorepo/polyfills': '*',
      '@monorepo/server': '*',
      '@monorepo/telemetry': '*',
      '@monorepo/tracing': '*',
      '@monorepo/utils': '*',
      dataloader: '^2.2.2',
      'fp-ts': '^2.16.1',
      'ts-toolbelt': '^9.6.0',
      undici: '^5.23.0'
    },
    devDependencies: {
      '@faker-js/faker': '^8.0.0',
      '@graphql-codegen/cli': '^5.0.0',
      '@graphql-codegen/introspection': '^4.0.0',
      '@graphql-codegen/typescript': '^4.0.0',
      '@graphql-codegen/typescript-resolvers': '^4.0.0',
      '@grpc/proto-loader': '^0.7.8',
      '@types/glob': '^8.1.0',
      '@types/ws': '^8.5.5',
      glob: '^10.3.3',
      'quicktype-core': '^23.0.12',
      yaml: '^2.3.1'
    }
  },
  fs: { numberOfFiles: 1372 },
  debug: [
    '2023-09-18T08:32:08.761Z config Attempting automatic configuration for angular\n',
    '2023-09-18T08:32:08.764Z angular/cli config Angular CLI not found.\n',
    '2023-09-18T08:32:08.764Z config Finished attempting automatic configuration for angular (3ms)\n',
    '2023-09-18T08:32:08.764Z config Attempting automatic configuration for jest\n',
    "2023-09-18T08:32:08.765Z jest/config Error: Module jest-cli is not found in '<homeDir>/monorepo/apps/graphql'.\n" +
      '    at Object.loadJest (<homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.367/wallaby/server.js:496:1070)\n' +
      '    at n (<homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.367/wallaby/server.js:184:23339)\n' +
      '    at Object.configure (<homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.367/wallaby/server.js:184:26449)\n' +
      '    at automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.367/wallaby/server.js:132:12015)\n' +
      '    at async automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.367/wallaby/server.js:132:11892)\n' +
      '    at async Config.load (<homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.367/wallaby/server.js:132:11832)\n',
    '2023-09-18T08:32:08.765Z config Finished attempting automatic configuration for jest (1ms)\n',
    '2023-09-18T08:32:08.765Z config Attempting automatic configuration for vitest\n',
    '2023-09-18T08:32:08.768Z vitest/config Detected Vitest (0.34.3).\n',
    '2023-09-18T08:32:09.291Z config Finished attempting automatic configuration for vitest (526ms)\n',
    '2023-09-18T08:32:09.293Z project Wallaby Node version: v20.4.0\n',
    '2023-09-18T08:32:09.293Z project Wallaby config: <homeDir>/monorepo/apps/graphql/auto.detect\n',
    '2023-09-18T08:32:09.339Z fs File system starting\n',
    '2023-09-18T08:32:09.776Z fs File system scan completed\n',
    '2023-09-18T08:32:09.787Z project File cache: <homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.367/projects/dd5d1a72a91e99f7\n',
    '2023-09-18T08:32:09.829Z uiService Listening port 38187\n',
    '2023-09-18T08:32:09.843Z project package.json file change detected, invalidating local cache\n',
    '2023-09-18T08:32:09.871Z workers Parallelism for initial run: 1, for regular run: 1\n',
    '2023-09-18T08:32:09.872Z workers Starting run worker instance #0\n',
    '2023-09-18T08:32:09.874Z workers Web server is listening at 35689\n',
    '2023-09-18T08:32:09.874Z project File cache requires some updates, waiting required files from IDE\n',
    '2023-09-18T08:32:10.422Z workers Started run worker instance (delayed) #0\n',
    '2023-09-18T08:32:10.653Z project Stopping process pool\n',
    '2023-09-18T08:32:10.663Z project Test run started; run priority: 3\n',
    '2023-09-18T08:32:10.666Z project Running all tests\n',
    '2023-09-18T08:32:10.687Z workers Starting test run, priority: 3\n',
    '2023-09-18T08:32:10.687Z nodeRunner Starting sandbox [worker #0, session #xvjqn]\n',
    '2023-09-18T08:32:10.687Z nodeRunner Preparing sandbox [worker #0, session #xvjqn]\n',
    '2023-09-18T08:32:10.687Z nodeRunner Prepared sandbox [worker #0, session #xvjqn]\n',
    '2023-09-18T08:32:10.688Z workers [worker #0, session #xvjqn] Running tests in sandbox\n',
    '2023-09-18T08:32:11.173Z workers Scheduling Vitest Run (xvjqn): 2023-09-18T08:32:11.160Z\n',
    '2023-09-18T08:32:12.443Z workers [xvjqn.1] Loaded unknown number of test(s)\n',
    '2023-09-18T08:32:12.462Z workers [xvjqn.1] Test executed: should return resolved area object\n',
    '2023-09-18T08:32:12.463Z workers [xvjqn.1] Test executed: should return an error\n',
    '2023-09-18T08:32:12.488Z workers Sandbox (active) [xvjqn] error: AssertionError: expected GraphQLError{ …(10) } to be an instance of AsyncLocalStorage\n' +
      '    at Assertion.<anonymous> (file://<homeDir>/monorepo/node_modules/vitest/node_modules/@vitest/expect/dist/index.js:908:17)\n' +
      '    at Assertion.<anonymous> (file://<homeDir>/monorepo/node_modules/vitest/node_modules/@vitest/expect/dist/index.js:649:17)\n' +
      '    at Assertion.methodWrapper (<homeDir>/monorepo/node_modules/vitest/node_modules/chai/lib/chai/utils/addMethod.js:57:25)\n' +
      '    at file://<homeDir>/monorepo/node_modules/vitest/node_modules/@vitest/expect/dist/index.js:1304:29\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n',
    '2023-09-18T08:32:12.494Z workers Vitest Run Complete (xvjqn): 2023-09-18T08:32:12.487Z\n',
    '2023-09-18T08:32:12.495Z workers [xvjqn] Run 2 test(s), skipped 0 test(s)\n',
    '2023-09-18T08:32:12.496Z workers [xvjqn] Sandbox is responsive, closing it\n',
    '2023-09-18T08:32:12.497Z workers Failed to map the stack to user code, entry message: AssertionError: expected GraphQLError{ …(10) } to be an instance of AsyncLocalStorage, stack: AssertionError: expected GraphQLError{ …(10) } to be an instance of AsyncLocalStorage\n' +
      '    at Assertion.<anonymous> (file://<homeDir>/monorepo/node_modules/vitest/node_modules/@vitest/expect/dist/index.js:908:17)\n' +
      '    at Assertion.<anonymous> (file://<homeDir>/monorepo/node_modules/vitest/node_modules/@vitest/expect/dist/index.js:649:17)\n' +
      '    at Assertion.methodWrapper (<homeDir>/monorepo/node_modules/vitest/node_modules/chai/lib/chai/utils/addMethod.js:57:25)\n' +
      '    at file://<homeDir>/monorepo/node_modules/vitest/node_modules/@vitest/expect/dist/index.js:1304:29\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n',
    '2023-09-18T08:32:12.498Z project Test run finished\n',
    '2023-09-18T08:32:12.499Z project Processed console.log entries\n',
    '2023-09-18T08:32:12.499Z project Processed loading sequences\n',
    '2023-09-18T08:32:12.499Z project Processed executed tests\n',
    '2023-09-18T08:32:12.503Z project Processed code coverage\n',
    '2023-09-18T08:32:12.523Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
> vitest show an error.

We have tried your assertion in a simple test, but it looks like both Wallaby and Vitest are displaying the test as passed in this case (green tick next to the test):
<img width="1076" alt="Screen Shot 2023-09-19 at 9 45 30 am" src="https://github.com/wallabyjs/public/assets/979966/c668d218-7276-4bf5-bbc1-06f58250511b">

Also both Wallaby and Vitest are displaying the uncaught execution error in the output.

Since your test is asserting [asynchronous code result via `rejects`](https://vitest.dev/api/expect.html#rejects), it looks like you are missing `await` (and possibly `async` too if you don't have it yet in your test function definition). So if you make the following change to the test:

```diff
-test('should return an error', async () => {
+test('should return an error', async () => {
...
-expect(result).rejects.toBeInstanceOf(AsyncLocalStorage)
+await expect(result).rejects.toBeInstanceOf(AsyncLocalStorage)
})
```

the both Wallaby and Vitest will start reporting the test as failing as opposed to an uncaught error as now.

**Comment by polRk** [comment]
No, it doesn't works

<img width="1070" alt="image" src="https://github.com/wallabyjs/public/assets/39828645/eb6e3167-1cdf-4954-92e7-87d88bf52051">

**Comment by polRk** [comment]
And

<img width="956" alt="image" src="https://github.com/wallabyjs/public/assets/39828645/579196d5-449e-4442-a52b-4e597161035e">

**Comment by ArtemGovorov** [comment]
Can you please provide a small sample repo where the issue can be reproduced? We are happy to take a look and investigate.

**Comment by polRk** [comment]
Ok, really, I have to write await everywhere if I want to see errors from wallaby.

**Comment by ArtemGovorov** [comment]
Yes, those [async rejects](https://vitest.dev/api/expect.html#rejects) can not be attributed to any test if the promise is not handled in test, neither by Wallaby nor by Vitest CLI runner. Having `await` for those will improve reporting for both.
