### ISSUE TITLE
PhpStorm 2023.2.2 error after installing wallaby plugin update 1.0.277

### ISSUE THREAD

**Issue by DontRepeatYourself** [wallabyjs/public#3281]
### Issue description or question

com.intellij.diagnostic.PluginException: Cannot create extension (class=com.wallaby.javascript.WallabyStatusBarWidgetFactory) [Plugin: wallaby.js]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:1067)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:69)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:30)
	at com.intellij.openapi.extensions.ExtensionPointNameKt.createOrError(ExtensionPointName.kt:290)
	at com.intellij.openapi.extensions.ExtensionPointName$LazyExtensionSequence$iterator$1$next$1.getInstance(ExtensionPointName.kt:250)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager$init$availableFactories$2.invoke(StatusBarWidgetsManager.kt:177)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager$init$availableFactories$2.invoke(StatusBarWidgetsManager.kt:177)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager.init$intellij_platform_ide_impl(StatusBarWidgetsManager.kt:179)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl$init$items$1$1.invoke(IdeStatusBarImpl.kt:285)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl$init$items$1$1.invoke(IdeStatusBarImpl.kt:284)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:199)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.init$intellij_platform_ide_impl(IdeStatusBarImpl.kt:284)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.init$intellij_platform_ide_impl$default(IdeStatusBarImpl.kt:281)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper.installDefaultProjectStatusBarWidgets$suspendImpl(ProjectFrameHelper.kt:345)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper.installDefaultProjectStatusBarWidgets(ProjectFrameHelper.kt)
	at com.intellij.openapi.project.impl.ProjectFrameAllocatorKt$scheduleInitFrame$1$1$1.invokeSuspend(ProjectFrameAllocator.kt:341)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.ClassNotFoundException: com.wallaby.javascript.WallabyStatusBarWidgetFactory PluginClassLoader(plugin=PluginDescriptor(name=Wallaby, id=wallaby.js, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PhpStorm2023.2\plugins\wallaby-intellij, version=1.0.277, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1607)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:947)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.kt:24)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:48)
	... 29 more

### Wallaby diagnostics report

Not available

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This has been fixed in Wallaby for IntelliJ `v1.0.278`. Please update to the latest version, it will fix your issue.
