### ISSUE TITLE
`ReferenceError: document is not defined` for SvelteKit + Vitest + `@testing-library/svelte` test

### ISSUE THREAD

**Issue by node-ex** [wallabyjs/public#3283]
### Issue description or question

Hello, I would like to use Wallby.js with Vitest and `@testing-library/svelte` to test SvelteKit components. Vitest tests run successfully in a console, but Wallaby.js displays `ReferenceError: document is not defined` when I call `render()` function from `@testing-library/svelte`.

Here is an example repository: https://github.com/node-ex/sveltekit-vitest-wallaby-example

![image](https://github.com/wallabyjs/public/assets/8402099/5b971148-ed8c-4f53-afdb-ffa9e40efad3)

### Wallaby diagnostics report

<details>
<summary>Wallaby Diagnostics Report</summary>

```
{
  editorVersion: '1.81.1',
  pluginVersion: '1.0.371',
  editorType: 'VSCode',
  osVersion: 'linux 5.4.0-163-generic',
  nodeVersion: 'v18.14.2',
  coreVersion: '1.0.1481',
  checksum: 'NjU0ZjZhMmY2NWM4ZWExMGIyZDYyMmIxYWQxNDVmMDgsMTcwMDc4NDAwMDAwMCww',
  config: {
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0', configFile: './vitest.dom.config.ts', autoDetected: true },
    hints: {
      ignoreCoverageForFile: '__REGEXP /Wallaby ignore file coverage/',
      ignoreCoverage: '__REGEXP /Wallaby ignore coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    trace: true,
    diagnostics: {
      vitest: {
        file: {
          config: <Buffer 2f 2a 2a 0a 20 2a 20 55 73 65 64 20 66 6f 72 20 61 70 70 27 73 20 75 6e 69 74 20 74 65 73 74 73 20 6f 66 20 63 6c 69 65 6e 74 20 63 6f 64 65 20 75 73 ... 396 more bytes>
        },
        config: {
          config: {
            allowOnly: true,
            watch: true,
            globals: false,
            environment: 'jsdom',
            threads: true,
            clearMocks: false,
            restoreMocks: false,
            mockReset: false,
            include: [ 'src/**/*.dom-test.{js,ts}' ],
            exclude: [
              '**/node_modules/**',
              '**/dist/**',
              '**/cypress/**',
              '**/.{idea,git,cache,output,temp}/**',
              '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*'
            ],
            testTimeout: 5000,
            hookTimeout: 10000,
            teardownTimeout: 10000,
            isolate: true,
            watchExclude: [ '**/node_modules/**', '**/dist/**' ],
            forceRerunTriggers: [
              '**/package.json/**',
              '**/{vitest,vite}.config.*/**',
              '<homeDir>/Documents/sveltekit-vitest-wallaby-example/vitest.dom.setup.ts'
            ],
            update: false,
            reporters: [ 'default' ],
            silent: false,
            hideSkippedTests: false,
            api: { middlewareMode: true },
            ui: false,
            uiBase: '/__vitest__/',
            open: true,
            css: { include: [], modules: { classNameStrategy: 'stable' } },
            coverage: {
              provider: 'v8',
              enabled: false,
              clean: true,
              cleanOnRerun: true,
              reportsDirectory: './coverage',
              exclude: [
                'coverage/**',
                'dist/**',
                'packages/*/test?(s)/**',
                '**/*.d.ts',
                '**/virtual:*',
                '**/__x00__*',
                '**/\x00*',
                'cypress/**',
                'test?(s)/**',
                'test?(-*).?(c|m)[jt]s?(x)',
                '**/*{.,-}{test,spec}.?(c|m)[jt]s?(x)',
                '**/__tests__/**',
                '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*',
                '**/vitest.{workspace,projects}.[jt]s?(on)',
                '**/.{eslint,mocha,prettier}rc.{?(c|m)js,yml}',
                'vitest.dom.setup.ts'
              ],
              reportOnFailure: false,
              reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
              extension: [
                '.js',  '.cjs',
                '.mjs', '.ts',
                '.mts', '.cts',
                '.tsx', '.jsx',
                '.vue', '.svelte'
              ],
              allowExternal: false
            },
            fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
            maxConcurrency: 5,
            dangerouslyIgnoreUnhandledErrors: false,
            typecheck: {
              checker: 'tsc',
              include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
              exclude: [
                '**/node_modules/**',
                '**/dist/**',
                '**/cypress/**',
                '**/.{idea,git,cache,output,temp}/**',
                '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*'
              ]
            },
            slowTestThreshold: 300,
            setupFiles: [ '<homeDir>/Documents/sveltekit-vitest-wallaby-example/vitest.dom.setup.ts' ],
            config: '<homeDir>/Documents/sveltekit-vitest-wallaby-example/vitest.dom.config.ts',
            defines: {},
            root: '<homeDir>/Documents/sveltekit-vitest-wallaby-example',
            mode: [],
            inspect: false,
            inspectBrk: false,
            singleThread: false,
            deps: {
              moduleDirectories: [ '/node_modules/' ],
              optimizer: { ssr: { enabled: true }, web: { enabled: true } },
              web: { transformAssets: true, transformCss: true, transformGlobPattern: [] }
            },
            server: {
              deps: {
                inline: [ {}, {}, {}, '@nuxt/test-utils', 'svelte', {}, '@testing-library/svelte', 'esm-env', '@sveltejs/kit' ],
                moduleDirectories: [ '/node_modules/' ],
                cacheDir: 'node_modules/.vitest'
              }
            },
            snapshotOptions: { snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
            experimentalVmWorkerMemoryLimit: 2047151616,
            cache: { dir: '<homeDir>/Documents/sveltekit-vitest-wallaby-example/node_modules/.vitest' },
            sequence: { hooks: 'parallel' },
            environmentMatchGlobs: [],
            browser: { enabled: false, headless: false, slowHijackESM: true, api: { middlewareMode: true } },
            testTransformMode: {}
          },
          projects: [
            {
              path: '<homeDir>/Documents/sveltekit-vitest-wallaby-example',
              config: {
                allowOnly: true,
                watch: true,
                globals: false,
                environment: 'jsdom',
                threads: true,
                clearMocks: false,
                restoreMocks: false,
                mockReset: false,
                include: [ 'src/**/*.dom-test.{js,ts}' ],
                exclude: [
                  '**/node_modules/**',
                  '**/dist/**',
                  '**/cypress/**',
                  '**/.{idea,git,cache,output,temp}/**',
                  '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*'
                ],
                testTimeout: 5000,
                hookTimeout: 10000,
                teardownTimeout: 10000,
                isolate: true,
                watchExclude: [ '**/node_modules/**', '**/dist/**' ],
                forceRerunTriggers: [
                  '**/package.json/**',
                  '**/{vitest,vite}.config.*/**',
                  '<homeDir>/Documents/sveltekit-vitest-wallaby-example/vitest.dom.setup.ts'
                ],
                update: false,
                reporters: [ 'default' ],
                silent: false,
                hideSkippedTests: false,
                api: { middlewareMode: true },
                ui: false,
                uiBase: '/__vitest__/',
                open: true,
                css: { include: [], modules: { classNameStrategy: 'stable' } },
                coverage: {
                  provider: 'v8',
                  enabled: false,
                  clean: true,
                  cleanOnRerun: true,
                  reportsDirectory: './coverage',
                  exclude: [
                    'coverage/**',
                    'dist/**',
                    'packages/*/test?(s)/**',
                    '**/*.d.ts',
                    '**/virtual:*',
                    '**/__x00__*',
                    '**/\x00*',
                    'cypress/**',
                    'test?(s)/**',
                    'test?(-*).?(c|m)[jt]s?(x)',
                    '**/*{.,-}{test,spec}.?(c|m)[jt]s?(x)',
                    '**/__tests__/**',
                    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*',
                    '**/vitest.{workspace,projects}.[jt]s?(on)',
                    '**/.{eslint,mocha,prettier}rc.{?(c|m)js,yml}',
                    'vitest.dom.setup.ts'
                  ],
                  reportOnFailure: false,
                  reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
                  extension: [
                    '.js',  '.cjs',
                    '.mjs', '.ts',
                    '.mts', '.cts',
                    '.tsx', '.jsx',
                    '.vue', '.svelte'
                  ],
                  allowExternal: false
                },
                fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
                maxConcurrency: 5,
                dangerouslyIgnoreUnhandledErrors: false,
                typecheck: {
                  checker: 'tsc',
                  include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
                  exclude: [
                    '**/node_modules/**',
                    '**/dist/**',
                    '**/cypress/**',
                    '**/.{idea,git,cache,output,temp}/**',
                    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*'
                  ]
                },
                slowTestThreshold: 300,
                setupFiles: [ '<homeDir>/Documents/sveltekit-vitest-wallaby-example/vitest.dom.setup.ts' ],
                config: '<homeDir>/Documents/sveltekit-vitest-wallaby-example/vitest.dom.config.ts',
                defines: {},
                root: '<homeDir>/Documents/sveltekit-vitest-wallaby-example',
                mode: [],
                inspect: false,
                inspectBrk: false,
                singleThread: false,
                deps: {
                  moduleDirectories: [ '/node_modules/' ],
                  optimizer: { ssr: { enabled: true }, web: { enabled: true } },
                  web: { transformAssets: true, transformCss: true, transformGlobPattern: [] }
                },
                server: {
                  deps: {
                    inline: [ {}, {}, {}, '@nuxt/test-utils', 'svelte', {}, '@testing-library/svelte', 'esm-env', '@sveltejs/kit' ],
                    moduleDirectories: [ '/node_modules/' ],
                    cacheDir: 'node_modules/.vitest'
                  }
                },
                snapshotOptions: { snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
                experimentalVmWorkerMemoryLimit: 2047151616,
                cache: { dir: '<homeDir>/Documents/sveltekit-vitest-wallaby-example/node_modules/.vitest' },
                sequence: { hooks: 'parallel' },
                environmentMatchGlobs: [],
                browser: { enabled: false, headless: false, slowHijackESM: true, api: { middlewareMode: true } },
                testTransformMode: {}
              }
            }
          ],
          package: {
            version: '0.34.6',
            urls: { hooks: 'file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.371/wallabydd8d50/runners/node/hooks.mjs' },
            paths: {
              root: '<homeDir>/Documents/sveltekit-vitest-wallaby-example/node_modules/vitest',
              dist: '<homeDir>/Documents/sveltekit-vitest-wallaby-example/node_modules/vitest/dist'
            }
          }
        }
      }
    },
    preserveComments: false,
    extractComments: true,
    files: [
      { pattern: 'src/**/*.dom-test.{js,ts}', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/*.*', ignore: false, trigger: true, load: true, order: 1 }
    ],
    tests: [
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'src/**/*.dom-test.{js,ts}', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    workers: { initial: 1, regular: 1, recycle: false },
    dot: true,
    captureConsoleLog: true,
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: {
      type: 'node',
      params: { runner: '--experimental-loader=file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.371/wallabydd8d50/runners/node/hooks.mjs' },
      runner: '<homeDir>/.asdf/installs/nodejs/18.14.2/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: true,
    symlinkNodeModules: true,
    configCode: 'module.exports = function () {\n' +
      '  return {\n' +
      '    testFramework: {\n' +
      "      configFile: './vitest.dom.config.ts',\n" +
      '    },\n' +
      '    hints: {\n' +
      '      ignoreCoverageForFile: /Wallaby ignore file coverage/,\n' +
      '      ignoreCoverage: /Wallaby ignore coverage/,\n' +
      '    },\n' +
      '    trace: true,\n' +
      '  };\n' +
      '};\n'
  },
  packageJSON: {
    dependencies: undefined,
    devDependencies: {
      '@sveltejs/adapter-auto': '2.1.0',
      '@sveltejs/adapter-node': '1.3.1',
      '@sveltejs/kit': '1.25.2',
      '@testing-library/dom': '9.3.3',
      '@testing-library/jest-dom': '6.1.4',
      '@testing-library/svelte': '4.0.4',
      '@testing-library/user-event': '14.5.1',
      '@types/estree': '1.0.1',
      '@types/jsdom': '21.1.4',
      '@types/node': '18.16.0',
      autoprefixer: '10.4.14',
      jsdom: '22.1.0',
      postcss: '8.4.23',
      'pretty-format': '29.7.0',
      svelte: '4.2.1',
      'svelte-check': '3.5.2',
      tslib: '2.5.0',
      tsx: '3.12.7',
      typescript: '5.2.2',
      vite: '4.4.11',
      vitest: '0.34.6'
    }
  },
  fs: { numberOfFiles: 29 },
  debug: [
    '2023-10-21T13:42:00.461Z project waiting for initial run signal\n',
    '2023-10-21T13:42:00.471Z config Attempting automatic configuration for angular\n',
    '2023-10-21T13:42:00.474Z angular/cli config Angular CLI not found.\n',
    '2023-10-21T13:42:00.474Z config Finished attempting automatic configuration for angular (3ms)\n',
    '2023-10-21T13:42:00.474Z config Attempting automatic configuration for jest\n',
    "2023-10-21T13:42:00.476Z jest/config Error: Module jest-cli is not found in '<homeDir>/Documents/sveltekit-vitest-wallaby-example'.\n" +
      '    at Object.loadJest (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.371/wallabydd8d50/server.js:496:1070)\n' +
      '    at n (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.371/wallabydd8d50/server.js:184:23339)\n' +
      '    at Object.configure (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.371/wallabydd8d50/server.js:184:26449)\n' +
      '    at automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.371/wallabydd8d50/server.js:132:12015)\n' +
      '    at async automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.371/wallabydd8d50/server.js:132:11892)\n' +
      '    at async Config.load (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.371/wallabydd8d50/server.js:132:11832)\n',
    '2023-10-21T13:42:00.476Z config Finished attempting automatic configuration for jest (2ms)\n',
    '2023-10-21T13:42:00.476Z config Attempting automatic configuration for vitest\n',
    '2023-10-21T13:42:00.478Z vitest/config Detected Vitest (0.34.6).\n',
    '2023-10-21T13:42:02.204Z config Finished attempting automatic configuration for vitest (1728ms)\n',
    '2023-10-21T13:42:02.207Z project Wallaby Node version: v18.14.2\n',
    '2023-10-21T13:42:02.207Z project Wallaby config: <homeDir>/Documents/sveltekit-vitest-wallaby-example/wallaby.cjs\n',
    '2023-10-21T13:42:02.269Z fs File system starting\n',
    '2023-10-21T13:42:02.352Z fs File system scan completed\n',
    '2023-10-21T13:42:02.362Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.371/projects/42c26b48588ceed4_1\n',
    '2023-10-21T13:42:02.370Z uiService Listening port 51237\n',
    '2023-10-21T13:42:02.375Z project package.json file change detected, invalidating local cache\n',
    '2023-10-21T13:42:02.423Z workers Parallelism for initial run: 1, for regular run: 1\n',
    '2023-10-21T13:42:02.424Z workers Starting run worker instance #0\n',
    '2023-10-21T13:42:02.424Z workers Web server is listening at 44081\n',
    '2023-10-21T13:42:02.425Z project File cache requires some updates, waiting required files from IDE\n',
    '2023-10-21T13:42:02.469Z project Stopping process pool\n',
    '2023-10-21T13:42:02.470Z project Test run started; run priority: 3\n',
    '2023-10-21T13:42:02.471Z project Running all tests\n',
    '2023-10-21T13:42:02.473Z workers Starting test run, priority: 3\n',
    '2023-10-21T13:42:02.473Z nodeRunner Starting sandbox [worker #0, session #swnls]\n',
    '2023-10-21T13:42:02.473Z nodeRunner Preparing sandbox [worker #0, session #swnls]\n',
    '2023-10-21T13:42:02.694Z workers Started run worker instance (delayed) #0\n',
    '2023-10-21T13:42:02.694Z nodeRunner Prepared sandbox [worker #0, session #swnls]\n',
    '2023-10-21T13:42:02.694Z workers [worker #0, session #swnls] Running tests in sandbox\n',
    '2023-10-21T13:42:04.146Z fs File changed: .svelte-kit/tsconfig.json\n',
    '2023-10-21T13:42:04.147Z fs File changed: .svelte-kit/ambient.d.ts\n',
    '2023-10-21T13:42:04.148Z fs File changed: .svelte-kit/types/route_meta_data.json\n',
    '2023-10-21T13:42:04.148Z fs File changed: .svelte-kit/generated/root.svelte\n',
    '2023-10-21T13:42:04.149Z project Test run is not cancelled because cancel requester does not have enough priority to cancel the run\n',
    '2023-10-21T13:42:04.153Z project Test run is not cancelled because cancel requester does not have enough priority to cancel the run\n',
    '2023-10-21T13:42:04.153Z project Test run is not cancelled because cancel requester does not have enough priority to cancel the run\n',
    '2023-10-21T13:42:04.154Z fs No changes detected for .svelte-kit/generated/root.svelte\n',
    '2023-10-21T13:42:04.154Z extended-core File was not changed, but file markers may need to be synced\n',
    '2023-10-21T13:42:04.154Z fs File changed: .svelte-kit/generated/client/app.js\n',
    '2023-10-21T13:42:04.154Z fs File changed: .svelte-kit/generated/client/nodes/0.js\n',
    '2023-10-21T13:42:04.155Z fs File changed: .svelte-kit/generated/client/matchers.js\n',
    '2023-10-21T13:42:04.155Z fs File changed: .svelte-kit/types/src/routes/$types.d.ts\n',
    '2023-10-21T13:42:04.155Z fs File changed: .svelte-kit/generated/server/internal.js\n',
    '2023-10-21T13:42:04.160Z fs File changed: .svelte-kit/generated/client/nodes/1.js\n',
    '2023-10-21T13:42:04.160Z fs File changed: .svelte-kit/generated/client/nodes/2.js\n',
    '2023-10-21T13:42:04.162Z fs No changes detected for .svelte-kit/generated/client/app.js\n',
    '2023-10-21T13:42:04.162Z extended-core File was not changed, but file markers may need to be synced\n',
    '2023-10-21T13:42:04.162Z fs No changes detected for .svelte-kit/generated/client/matchers.js\n',
    '2023-10-21T13:42:04.162Z extended-core File was not changed, but file markers may need to be synced\n',
    '2023-10-21T13:42:04.162Z fs No changes detected for .svelte-kit/types/src/routes/$types.d.ts\n',
    '2023-10-21T13:42:04.162Z extended-core File was not changed, but file markers may need to be synced\n',
    '2023-10-21T13:42:04.163Z project Test run is not cancelled because cancel requester does not have enough priority to cancel the run\n',
    '2023-10-21T13:42:04.163Z fs No changes detected for .svelte-kit/generated/client/nodes/1.js\n',
    '2023-10-21T13:42:04.163Z extended-core File was not changed, but file markers may need to be synced\n',
    '2023-10-21T13:42:04.164Z fs No changes detected for .svelte-kit/generated/client/nodes/2.js\n',
    '2023-10-21T13:42:04.164Z extended-core File was not changed, but file markers may need to be synced\n',
    '2023-10-21T13:42:04.164Z fs No changes detected for .svelte-kit/generated/client/nodes/0.js\n',
    '2023-10-21T13:42:04.164Z extended-core File was not changed, but file markers may need to be synced\n',
    '2023-10-21T13:42:04.393Z workers Scheduling Vitest Run (swnls): 2023-10-21T13:42:04.350Z\n',
    "2023-10-21T13:42:04.400Z workers Did not find project to provide to 'vitest' for file: <homeDir>/Documents/sveltekit-vitest-wallaby-example/src/routes/page.svelte.dom-test.ts\n",
    '2023-10-21T13:42:05.585Z workers [swnls.1] Loaded unknown number of test(s)\n',
    '2023-10-21T13:42:05.596Z workers [swnls.1] Test executed: should render the component\n',
    '2023-10-21T13:42:05.620Z workers Vitest Run Complete (swnls): 2023-10-21T13:42:05.613Z\n',
    '2023-10-21T13:42:05.621Z workers [swnls] Run 1 test(s), skipped 0 test(s)\n',
    '2023-10-21T13:42:05.623Z workers [swnls] Sandbox is responsive, closing it\n',
    '2023-10-21T13:42:05.624Z project Test run finished\n',
    '2023-10-21T13:42:05.625Z project Processed console.log entries\n',
    '2023-10-21T13:42:05.625Z project Processed loading sequences\n',
    '2023-10-21T13:42:05.626Z project Processed executed tests\n',
    '2023-10-21T13:42:05.627Z project Processed code coverage\n',
    '2023-10-21T13:42:05.644Z project Test run result processed and sent to IDE\n',
    '2023-10-21T13:42:05.655Z project Test run started; run priority: 2\n',
    '2023-10-21T13:42:05.656Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2023-10-21T13:42:05.658Z project Test task priority upgraded to full run\n',
    '2023-10-21T13:42:05.658Z workers Starting test run, priority: 3\n',
    '2023-10-21T13:42:05.658Z nodeRunner Starting sandbox [worker #0, session #u92vb]\n',
    '2023-10-21T13:42:05.659Z nodeRunner Preparing sandbox [worker #0, session #u92vb]\n',
    '2023-10-21T13:42:05.659Z nodeRunner Prepared sandbox [worker #0, session #u92vb]\n',
    '2023-10-21T13:42:05.659Z workers [worker #0, session #u92vb] Running tests in sandbox\n',
    '2023-10-21T13:42:05.664Z workers Scheduling Vitest Run (u92vb): 2023-10-21T13:42:05.662Z\n',
    "2023-10-21T13:42:05.665Z workers Did not find project to provide to 'vitest' for file: <homeDir>/Documents/sveltekit-vitest-wallaby-example/src/routes/page.svelte.dom-test.ts\n",
    '2023-10-21T13:42:06.156Z workers [u92vb.1] Loaded unknown number of test(s)\n',
    '2023-10-21T13:42:06.157Z workers [u92vb.1] Test executed: should render the component\n',
    '2023-10-21T13:42:06.168Z workers Vitest Run Complete (u92vb): 2023-10-21T13:42:06.164Z\n',
    '2023-10-21T13:42:06.168Z workers [u92vb] Run 1 test(s), skipped 0 test(s)\n',
    '2023-10-21T13:42:06.170Z workers [u92vb] Sandbox is responsive, closing it\n',
    '2023-10-21T13:42:06.170Z project Test run finished\n',
    '2023-10-21T13:42:06.170Z project Processed console.log entries\n',
    '2023-10-21T13:42:06.170Z project Processed loading sequences\n',
    '2023-10-21T13:42:06.170Z project Processed executed tests\n',
    '2023-10-21T13:42:06.171Z project Processed code coverage\n',
    '2023-10-21T13:42:06.173Z project Test run result processed and sent to IDE\n'
  ]
}
```

</details>

**Comment by smcenlly** [comment]
Thanks for reporting your problem and for the detailed issue report + sample repo, it was a big help.

There was a change to vitest internal API a while back that had broken the use of custom vitest configuration files.

This is fixed in the latest version of Wallaby core, `v1.0.1482`. Wallaby should update automatically with the latest version for you. Alternatively, you can run the command `Wallaby.js: Force Core Update`.

**Comment by node-ex** [comment]
@smcenlly Thank you for the fix, everything works after updating to the mentioned version of Wallaby code
