### ISSUE TITLE
AlreadyDisposedException: Cannot create light service com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager because container is already disposed

### ISSUE THREAD

**Issue by tomsquest** [wallabyjs/public#3285]
### Issue description or question

Hi,

I am having the following error since a couple days ago, when switching between projects.

Here is the full stack trace:

```java
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager because container is already disposed (container=Project(name=.dotfiles, containerState=DISPOSE_COMPLETED, componentStore=/home/tom/.dotfiles) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkThatCreatingOfLightServiceIsAllowed(ComponentManagerImpl.kt:752)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:732)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:688)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
	at com.wallaby.javascript.WallabyController.ae(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### Intellij Config

Automatic config, no wallabyjs.

![image](https://github.com/wallabyjs/public/assets/365778/1142fa3c-1ba8-43b1-a168-665bc79a3cb6)

### Wallaby diagnostics report

```
{
  editorVersion: 'IntelliJ IDEA 2023.2.3',
  pluginVersion: '1.0.278',
  editorType: 'IntelliJ',
  osVersion: 'linux 6.2.0-35-generic',
  nodeVersion: 'v18.16.0',
  coreVersion: '1.0.1482',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '<homeDir>/Dev/adeo/opus-search/.cache/jest',
              clearMocks: false,
              collectCoverageFrom: [],
              coverageDirectory: '<homeDir>/Dev/adeo/opus-search/.coverage',
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/Dev/adeo/opus-search',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: undefined,
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              fakeTimers: { enableGlobally: false },
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: true, throwOnModuleCollision: false },
              id: 'bcd920175a9b6041dfa7f619d40ac8fe',
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [
                'js',   'mjs',
                'cjs',  'jsx',
                'ts',   'tsx',
                'json', 'node'
              ],
              moduleNameMapper: [ [ '^@opus-search/(.*)$', '<homeDir>/Dev/adeo/opus-search/libs/$1/src' ] ],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              openHandlesTimeout: 1000,
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/Dev/adeo/opus-search',
              roots: [ '<homeDir>/Dev/adeo/opus-search/libs', '<homeDir>/Dev/adeo/opus-search/apps' ],
              runner: '<homeDir>/Dev/adeo/opus-search/node_modules/jest-runner/build/index.js',
              runtime: undefined,
              sandboxInjectedGlobals: [],
              setupFiles: [ '<homeDir>/Dev/adeo/opus-search/node_modules/reflect-metadata/Reflect.js' ],
              setupFilesAfterEnv: [ '<homeDir>/Dev/adeo/opus-search/jest-setup.ts' ],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: { escapeString: false, printBasicPrototype: false },
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/Dev/adeo/opus-search/node_modules/jest-environment-node/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<homeDir>/Dev/adeo/opus-search/node_modules/jest-circus/runner.js',
              transform: [ [ '^.+\\.tsx?$', '<homeDir>/Dev/adeo/opus-search/node_modules/ts-jest/dist/index.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            ci: false,
            collectCoverage: false,
            collectCoverageFrom: [],
            coverageDirectory: '<homeDir>/Dev/adeo/opus-search/.coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'lcov' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 6,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            openHandlesTimeout: 1000,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [],
            randomize: undefined,
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/Dev/adeo/opus-search',
            runInBand: undefined,
            runTestsByPath: false,
            seed: -1961096371,
            shard: undefined,
            showSeed: undefined,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: { escapeString: false, printBasicPrototype: false },
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/Dev/adeo/opus-search/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: 60000,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true,
            workerIdleMemoryLimit: undefined,
            workerThreads: false
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [ 'libs', 'apps' ],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '\\./.cache/jest', '\\./.coverage' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '\\./.cache/jest', '\\./.coverage' ],
            testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    dot: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, file: true, test: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        file: true,
        test: true
      },
      { pattern: '\\./.cache/jest', regexp: /\.\/.cache\/jest/, ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '\\./.coverage', regexp: /\.\/.coverage/, ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'libs/**', ignore: false, trigger: true, load: true, order: 2 },
      { pattern: 'apps/**', ignore: false, trigger: true, load: true, order: 3 },
      { pattern: 'libs/**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'libs/**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'apps/**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true, file: true }
    ],
    captureConsoleLog: true,
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true, file: false },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true,
        file: false
      },
      { pattern: '\\./.cache/jest', regexp: /\.\/.cache\/jest/, ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '\\./.coverage', regexp: /\.\/.coverage/, ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'libs/**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 4 },
      { pattern: 'libs/**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 5 },
      { pattern: 'apps/**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 6 },
      { pattern: 'apps/**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 7 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    smartStart: [ { test: true, source: false, pattern: '**/*', startMode: 'open' }, { test: false, source: true, pattern: '**/*', startMode: 'edit' } ],
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: true,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '<homeDir>/.asdf/installs/nodejs/18.16.0/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: false,
    configCode: 'auto.detect#-277251592',
    testLocations: []
  },
  packageJSON: {
    dependencies: {
      '@adeo/opus-healthcheck': '1.0.8',
      '@adeo/opus-nest-authentication': '2.0.4',
      '@elastic/elasticsearch': '8.9.0',
      '@fastify/static': '6.10.2',
      '@fastify/view': '7.4.1',
      '@google-cloud/bigquery': '7.2.0',
      '@google-cloud/logging-winston': '6.0.0',
      '@google-cloud/pubsub': '4.0.2',
      '@google-cloud/tasks': '4.0.0',
      '@nestjs/common': '9.4.2',
      '@nestjs/core': '9.4.2',
      '@nestjs/platform-fastify': '9.4.2',
      '@nestjs/swagger': '6.3.0',
      axios: '1.5.0',
      'class-transformer': '0.5.1',
      'class-validator': '0.14.0',
      cors: '2.8.5',
      'dd-trace': '4.14.0',
      dotenv: '16.3.1',
      ejs: '3.1.9',
      'env-var': '7.4.1',
      'fold-to-ascii': '5.0.1',
      helmet: '7.0.0',
      jsonwebtoken: '9.0.2',
      lodash: '4.17.21',
      'lru-cache': '10.0.1',
      nocache: '4.0.0',
      'p-limit': '3.1.0',
      'reflect-metadata': '0.1.13',
      rxjs: '7.8.1',
      tslib: '2.6.2',
      uuid: '^9.0.0',
      winston: '3.10.0'
    },
    devDependencies: {
      '@nestjs/cli': '9.5.0',
      '@nestjs/schematics': '9.2.0',
      '@nestjs/testing': '9.4.2',
      '@tsconfig/node18': '18.2.1',
      '@types/cors': '2.8.13',
      '@types/ejs': '3.1.2',
      '@types/fold-to-ascii': '5.0.0',
      '@types/jest': '29.5.4',
      '@types/jest-when': '3.5.2',
      '@types/jsonwebtoken': '9.0.2',
      '@types/lodash': '4.14.197',
      '@types/node': '20.5.7',
      '@types/prompts': '2.4.4',
      '@types/uuid': '9.0.3',
      '@typescript-eslint/eslint-plugin': '6.5.0',
      '@typescript-eslint/parser': '6.5.0',
      conf: '10.2.0',
      cpx2: '5.0.0',
      eslint: '8.48.0',
      'eslint-config-prettier': '9.0.0',
      'eslint-plugin-deprecation': '1.5.0',
      'eslint-plugin-functional': '6.0.0',
      'eslint-plugin-import': '2.28.1',
      'eslint-plugin-jest': '27.2.3',
      'eslint-plugin-jest-formatting': '3.1.0',
      'eslint-plugin-no-secrets': '0.8.9',
      'eslint-plugin-only-error': '1.0.2',
      'eslint-plugin-regexp': '1.15.0',
      'eslint-plugin-simple-import-sort': '10.0.0',
      'eslint-plugin-sonarjs': '0.21.0',
      'eslint-plugin-unused-imports': '3.0.0',
      husky: '8.0.3',
      jest: '29.6.4',
      'jest-when': '3.6.0',
      'lint-staged': '14.0.1',
      nock: '13.3.3',
      'npm-run-all': '4.1.5',
      prettier: '3.0.3',
      prompts: '2.4.2',
      qqd: '1.6.0',
      rimraf: '5.0.1',
      'ts-jest': '29.1.1',
      'ts-loader': '9.4.4',
      'ts-node': '10.9.1',
      'ts-prune': '0.10.3',
      'tsc-alias': '1.8.7',
      typescript: '5.2.2',
      webpack: '5.88.2'
    }
  },
  fs: { numberOfFiles: 1280 },
  debug: [
    '2023-10-25T13:10:38.025Z project waiting for initial run signal\n',
    '2023-10-25T13:10:38.029Z config Attempting automatic configuration for angular\n',
    '2023-10-25T13:10:38.030Z angular/cli config Angular CLI not found.\n',
    '2023-10-25T13:10:38.030Z config Finished attempting automatic configuration for angular (1ms)\n',
    '2023-10-25T13:10:38.030Z config Attempting automatic configuration for jest\n',
    '2023-10-25T13:10:38.118Z jest/config Detected Jest.\n',
    '2023-10-25T13:10:38.119Z jest/config Configured Jest.\n',
    '2023-10-25T13:10:38.119Z config Finished attempting automatic configuration for jest (89ms)\n',
    '2023-10-25T13:10:38.119Z project Wallaby Node version: v18.16.0\n',
    '2023-10-25T13:10:38.120Z project Wallaby config: <homeDir>/Dev/adeo/opus-search/auto.detect\n',
    '2023-10-25T13:10:38.141Z fs File system starting\n',
    '2023-10-25T13:10:38.265Z fs File system scan completed\n',
    '2023-10-25T13:10:38.269Z project File cache: <homeDir>/.cache/JetBrains/IntelliJIdea2023.2/wallaby/projects/4e6c3ea8fde55710\n',
    '2023-10-25T13:10:38.323Z uiService Listening port 51235\n',
    '2023-10-25T13:10:38.358Z workers Parallelism for initial run: 30, for regular run: 15\n',
    '2023-10-25T13:10:38.358Z workers Starting run worker instance #0\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #1\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #2\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #3\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #4\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #5\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #6\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #7\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #8\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #9\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #10\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #11\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #12\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #13\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #14\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #15\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #16\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #17\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #18\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #19\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #20\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #21\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #22\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #23\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #24\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #25\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #26\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #27\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #28\n',
    '2023-10-25T13:10:38.359Z workers Starting run worker instance #29\n',
    '2023-10-25T13:10:38.361Z workers Web server is listening at 34753\n',
    '2023-10-25T13:10:38.546Z project File cache requires some updates, waiting required files from IDE\n',
    '2023-10-25T13:10:38.573Z workers Started run worker instance (delayed) #0\n',
    '2023-10-25T13:10:38.573Z workers Started run worker instance (delayed) #1\n',
    '2023-10-25T13:10:38.573Z workers Started run worker instance (delayed) #2\n',
    '2023-10-25T13:10:38.573Z workers Started run worker instance (delayed) #3\n',
    '2023-10-25T13:10:38.573Z workers Started run worker instance (delayed) #4\n',
    '2023-10-25T13:10:38.574Z workers Started run worker instance (delayed) #6\n',
    '2023-10-25T13:10:38.574Z workers Started run worker instance (delayed) #7\n',
    '2023-10-25T13:10:38.574Z workers Started run worker instance (delayed) #5\n',
    '2023-10-25T13:10:38.574Z workers Started run worker instance (delayed) #8\n',
    '2023-10-25T13:10:38.574Z workers Started run worker instance (delayed) #9\n',
    '2023-10-25T13:10:38.574Z workers Started run worker instance (delayed) #10\n',
    '2023-10-25T13:10:38.574Z workers Started run worker instance (delayed) #11\n',
    '2023-10-25T13:10:38.574Z workers Started run worker instance (delayed) #13\n',
    '2023-10-25T13:10:38.575Z workers Started run worker instance (delayed) #14\n',
    '2023-10-25T13:10:38.575Z workers Started run worker instance (delayed) #15\n',
    '2023-10-25T13:10:38.575Z workers Started run worker instance (delayed) #17\n',
    '2023-10-25T13:10:38.575Z workers Started run worker instance (delayed) #12\n',
    '2023-10-25T13:10:38.577Z workers Started run worker instance (delayed) #16\n',
    '2023-10-25T13:10:38.578Z workers Started run worker instance (delayed) #19\n',
    '2023-10-25T13:10:38.578Z project Stopping process pool\n',
    '2023-10-25T13:10:38.578Z workers Started run worker instance (delayed) #18\n',
    '2023-10-25T13:10:38.579Z project Test run started; run priority: 3\n',
    '2023-10-25T13:10:38.581Z project Running all tests\n',
    '2023-10-25T13:10:38.589Z project Test run finished\n',
    '2023-10-25T13:10:38.589Z project Test run data re-queued\n',
    '2023-10-25T13:10:38.594Z workers Started run worker instance (delayed) #22\n',
    '2023-10-25T13:10:38.594Z workers Started run worker instance (delayed) #20\n',
    '2023-10-25T13:10:38.594Z workers Started run worker instance (delayed) #24\n',
    '2023-10-25T13:10:38.595Z workers Started run worker instance (delayed) #21\n',
    '2023-10-25T13:10:38.597Z workers Started run worker instance (delayed) #23\n',
    '2023-10-25T13:10:38.598Z workers Started run worker instance (delayed) #25\n',
    '2023-10-25T13:10:38.607Z workers Started run worker instance (delayed) #26\n',
    '2023-10-25T13:10:38.609Z workers Started run worker instance (delayed) #28\n',
    '2023-10-25T13:10:38.614Z workers Started run worker instance (delayed) #27\n',
    '2023-10-25T13:10:38.621Z workers Started run worker instance (delayed) #29\n'
  ]
}
```

**Comment by smcenlly** [comment]
Thank you for reporting the issue.

This has been fixed in the latest version of the JetBrains Wallaby Plugin, `v1.0.279`.
