### ISSUE TITLE
Exception NoSuchMethodError: XBreakpointManager.addBreakpointListener

### ISSUE THREAD

**Issue by rparree** [wallabyjs/public#3288]
I am getting the stacktrace below on WebStorm 2023.3 EAP

on version 1.0.403 (and versions before)

```
java.lang.NoSuchMethodError: 'void com.intellij.xdebugger.breakpoints.XBreakpointManager.addBreakpointListener(com.intellij.xdebugger.breakpoints.XBreakpointListener)'
	at com.quokka.javascript.j.a(Unknown Source)
	at com.quokka.javascript.j.a(Unknown Source)
	at com.quokka.javascript.session.QuokkaSession.<init>(Unknown Source)
	at com.quokka.javascript.session.QuokkaSession.a(Unknown Source)
	at com.quokka.javascript.QuokkaController$d.a(Unknown Source)
	at com.quokka.javascript.QuokkaController$d.a(Unknown Source)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:253)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:373)
	at com.intellij.util.Alarm$Request.run(Alarm.java:356)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:857)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:477)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1444)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:862)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

WebStorm 2023.3 EAP
Build #WS-233.10527.23, built on October 23, 2023
Licensed to WebStorm EAP user: Raphael Parree
Expiration date: November 22, 2023
Runtime version: 17.0.8.1+7-b1072.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.7-200.fc38.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 3964M
Cores: 16
Registry:
  suggest.all.run.configurations.from.context=true
  ide.experimental.ui=true
  ide.balloon.shadow.size=0
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (233.10527.23)
  Dummy Text Generator (1.2.0)
  com.intellij.datagen (233.10527.7)
  com.github.lppedd.idea-conventional-commit (0.22.0)
  in.thekalinga.snippet.intellij (6.1.0)
  net.sjrx.intellij.plugins.systemdunitfiles (223.230322.126)
  biz.elfuego.idea.issues.gitea (1.6)
  org.toml.lang (233.10527.14)
  wallaby.js (1.0.280)
  com.jinsihou.react.snippets (1.1.1)
  org.nik.presentation-assistant (1.0.10)
  quokka.js (1.0.403)
  io.aesy.yamllint (0.3)
  com.sburlyaev.terminal.plugin (0.6.0)
  name.kropp.intellij.makefile (233.10527.14)
  String Manipulation (9.11.3)
  ir.msdehghan.plugins.ansible (0.92)
  dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
  com.intellij.grazie.pro (0.3.259)
  com.intellij.ml.llm (233.10527.14)
  com.intellij.database (233.10527.23)
  com.suming.react.PropTypes (1.1.5)
  com.ppolivka.plugin.gitcleaner (1.1.4)
  de.sist.gitlab (2.14.2)
  com.mallowigi (94.1.0)
  com.github.blarc.gitlab-template-lint-plugin (1.13.2)
  izhangzhihao.rainbow.brackets (2023.3.6)
Current Desktop: KDE

**Comment by mburnell** [comment]
Thank you for reporting this. It looks like this API has finally been removed; we'll need to update to work with the newer API when running on newer JetBrians editor versions.

**Comment by mburnell** [comment]
This issue has now been fixed; updating your Wallaby plugin to version `1.0.281` should now work properly in 2023.3 EAP.
