### ISSUE TITLE
Failed to open file in coverage / test explorer

### ISSUE THREAD

**Issue by DontRepeatYourself** [wallabyjs/public#3308]
### Issue description or question

Running tests in PhpStorm 2023.3.1 with Wallaby.js App v1.0.86, Core v1.0.1511.
Launching coverage / test explorer -> selecting "FILES" and clicking on file to open it.
Content of file won't show in coverage / test explorer and selected file didn't open in PhpStorm.

Output from Wallaby console in PhpStorm after clicking:

```
Finished executing 1896 affected test(s) in 5.45 minute(s)
TypeError: _0x55e15c is not a constructor
    at WebSocket.emit (node:events:514:28)
    at afterWrite (node:internal/streams/writable:693:5)
    at onwrite (node:internal/streams/writable:671:7)
    at Zlib.cb (node:internal/streams/transform:195:7)
    at Zlib.processCallback (node:zlib:613:8)
```

### Wallaby diagnostics report
```
{
  editorVersion: 'PhpStorm 2023.3.1',
  pluginVersion: '1.0.284',
  editorType: 'IntelliJ',
  osVersion: 'win32 10.0.19045',
  nodeVersion: 'v20.10.0',
  coreVersion: '1.0.1511',
  checksum: 'NGFjMDcwZjAzMTdmZWZhZTVlZDIxMmZmOTA5M2IwNGIsMTcyOTgxNDQwMDAwMCww',
  config: {
    diagnostics: {
      vitest: {
        file: {
          config: '// noinspection JSUnusedGlobalSymbols,NpmUsedModulesInstalled\r\n' +
            '\r\n' +
            "import { configDefaults, defineConfig } from 'vitest/config'\r\n" +
            "import vue from '@vitejs/plugin-vue'\r\n" +
            "import { quasar, transformAssetUrls } from '@quasar/vite-plugin'\r\n" +
            "import jsconfigPaths from 'vite-jsconfig-paths'\r\n" +
            '\r\n' +
            '// https://vitejs.dev/config/\r\n' +
            'export default defineConfig({\r\n' +
            '  test: {\r\n' +
            "    environment: 'happy-dom',\r\n" +
            "    setupFiles: 'test/vitest/setup-file.js',\r\n" +
            '    testTimeout: 10000,\r\n' +
            '    coverage: {\r\n' +
            "      provider: 'istanbul',\r\n" +
            "      reporters: ['text', 'json', 'html'],\r\n" +
            '      exclude: [\r\n' +
            '        ...configDefaults.exclude,\r\n' +
            "        'test/vitest/fixtures/*.*',\r\n" +
            "        'test/vitest/helper/*.*',\r\n" +
            "        'src/stores/*.*',\r\n" +
            "        'src/utils/{authentication,excel,notifier,pdf}.js'\r\n" +
            '      ]\r\n' +
            '    },\r\n' +
            '    include: [\r\n' +
            "      // Matches vitest tests in any sub folder of 'src' or into 'test/vitest/__tests__'\r\n" +
            "      // Matches all files with extension 'js', 'jsx', 'ts' and 'tsx'\r\n" +
            "      // 'src/**/*.vitest.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}',\r\n" +
            "      'test/vitest/__tests__/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'\r\n" +
            '    ],\r\n' +
            '    exclude: [\r\n' +
            '      ...configDefaults.exclude,\r\n' +
            "      'test/vitest/fixtures/*.*',\r\n" +
            "      'test/vitest/helper/*.*',\r\n" +
            "      'src/stores/*.*',\r\n" +
            "      'src/utils/{authentication,excel,notifier,pdf}.js'\r\n" +
            '    ]\r\n' +
            '  },\r\n' +
            '  plugins: [\r\n' +
            '    vue({\r\n' +
            '      template: { transformAssetUrls }\r\n' +
            '    }),\r\n' +
            '    quasar({\r\n' +
            "      sassVariables: 'src/quasar-variables.sass'\r\n" +
            '    }),\r\n' +
            '    jsconfigPaths()\r\n' +
            '  ]\r\n' +
            '})\r\n'
        },
        config: {
          config: {
            allowOnly: true,
            watch: true,
            globals: false,
            environment: 'happy-dom',
            pool: 'threads',
            clearMocks: false,
            restoreMocks: false,
            mockReset: false,
            include: [ 'test/vitest/__tests__/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}' ],
            exclude: [
              '**/node_modules/**',
              '**/dist/**',
              '**/cypress/**',
              '**/.{idea,git,cache,output,temp}/**',
              '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
              'test/vitest/fixtures/*.*',
              'test/vitest/helper/*.*',
              'src/stores/*.*',
              'src/utils/{authentication,excel,notifier,pdf}.js'
            ],
            testTimeout: 10000,
            hookTimeout: 10000,
            teardownTimeout: 10000,
            watchExclude: [ '**/node_modules/**', '**/dist/**' ],
            forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**', 'C:/Users/xxx/code/quasar/minds/test/vitest/setup-file.js' ],
            update: false,
            reporters: [ 'default' ],
            silent: false,
            hideSkippedTests: false,
            api: { middlewareMode: true },
            ui: false,
            uiBase: '/__vitest__/',
            open: true,
            css: { include: [], modules: { classNameStrategy: 'stable' } },
            coverage: {
              provider: 'istanbul',
              enabled: false,
              all: true,
              clean: true,
              cleanOnRerun: true,
              reportsDirectory: './coverage',
              exclude: [
                '**/node_modules/**',
                '**/dist/**',
                '**/cypress/**',
                '**/.{idea,git,cache,output,temp}/**',
                '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
                'test/vitest/fixtures/*.*',
                'test/vitest/helper/*.*',
                'src/stores/*.*',
                'src/utils/{authentication,excel,notifier,pdf}.js',
                'test/vitest/setup-file.js'
              ],
              reportOnFailure: false,
              reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
              extension: [
                '.js',    '.cjs',
                '.mjs',   '.ts',
                '.mts',   '.cts',
                '.tsx',   '.jsx',
                '.vue',   '.svelte',
                '.marko'
              ],
              allowExternal: false,
              processingConcurrency: 8,
              reporters: [ 'text', 'json', 'html' ]
            },
            fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
            maxConcurrency: 5,
            dangerouslyIgnoreUnhandledErrors: false,
            typecheck: {
              checker: 'tsc',
              include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
              exclude: [
                '**/node_modules/**',
                '**/dist/**',
                '**/cypress/**',
                '**/.{idea,git,cache,output,temp}/**',
                '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
              ],
              enabled: false
            },
            slowTestThreshold: 300,
            setupFiles: [ 'C:/Users/xxx/code/quasar/minds/test/vitest/setup-file.js' ],
            config: 'C:\\Users\\xxx\\code\\quasar\\minds\\vitest.config.js',
            defines: {},
            root: 'C:/Users/xxx/code/quasar/minds',
            mode: [],
            inspect: false,
            inspectBrk: false,
            deps: {
              moduleDirectories: [ '/node_modules/' ],
              optimizer: { ssr: { enabled: true }, web: { enabled: true } },
              web: { transformAssets: true, transformCss: true, transformGlobPattern: [] }
            },
            server: { deps: { inline: [ {}, {}, {}, '@nuxt/test-utils' ], moduleDirectories: [ '/node_modules/' ], cacheDir: 'node_modules/.vitest' } },
            snapshotOptions: { expand: false, snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
            poolMatchGlobs: [],
            globalSetup: [],
            cache: { dir: 'C:/Users/xxx/code/quasar/minds/node_modules/.vitest' },
            sequence: { hooks: 'parallel' },
            environmentMatchGlobs: [],
            browser: { enabled: false, headless: false, slowHijackESM: false, isolate: true, api: { middlewareMode: true } },
            testTransformMode: {}
          },
          projects: [
            {
              path: 'C:/Users/xxx/code/quasar/minds',
              config: {
                allowOnly: true,
                watch: true,
                globals: false,
                environment: 'happy-dom',
                pool: 'threads',
                clearMocks: false,
                restoreMocks: false,
                mockReset: false,
                include: [ 'test\\vitest\\__tests__\\**\\*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}' ],
                exclude: [
                  '**\\node_modules\\**',
                  '**\\dist\\**',
                  '**\\cypress\\**',
                  '**\\.{idea,git,cache,output,temp}\\**',
                  '**\\{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
                  'test\\vitest\\fixtures\\*.*',
                  'test\\vitest\\helper\\*.*',
                  'src\\stores\\*.*',
                  'src\\utils\\{authentication,excel,notifier,pdf}.js'
                ],
                testTimeout: 10000,
                hookTimeout: 10000,
                teardownTimeout: 10000,
                watchExclude: [ '**/node_modules/**', '**/dist/**' ],
                forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**', 'C:/Users/xxx/code/quasar/minds/test/vitest/setup-file.js' ],
                update: false,
                reporters: [ 'default' ],
                silent: false,
                hideSkippedTests: false,
                api: { middlewareMode: true },
                ui: false,
                uiBase: '/__vitest__/',
                open: true,
                css: { include: [], modules: { classNameStrategy: 'stable' } },
                coverage: {
                  provider: 'istanbul',
                  enabled: false,
                  all: true,
                  clean: true,
                  cleanOnRerun: true,
                  reportsDirectory: './coverage',
                  exclude: [
                    '**/node_modules/**',
                    '**/dist/**',
                    '**/cypress/**',
                    '**/.{idea,git,cache,output,temp}/**',
                    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
                    'test/vitest/fixtures/*.*',
                    'test/vitest/helper/*.*',
                    'src/stores/*.*',
                    'src/utils/{authentication,excel,notifier,pdf}.js',
                    'test/vitest/setup-file.js'
                  ],
                  reportOnFailure: false,
                  reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
                  extension: [
                    '.js',    '.cjs',
                    '.mjs',   '.ts',
                    '.mts',   '.cts',
                    '.tsx',   '.jsx',
                    '.vue',   '.svelte',
                    '.marko'
                  ],
                  allowExternal: false,
                  processingConcurrency: 8,
                  reporters: [ 'text', 'json', 'html' ]
                },
                fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
                maxConcurrency: 5,
                dangerouslyIgnoreUnhandledErrors: false,
                typecheck: {
                  checker: 'tsc',
                  include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
                  exclude: [
                    '**/node_modules/**',
                    '**/dist/**',
                    '**/cypress/**',
                    '**/.{idea,git,cache,output,temp}/**',
                    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
                  ],
                  enabled: false
                },
                slowTestThreshold: 300,
                setupFiles: [ 'C:/Users/xxx/code/quasar/minds/test/vitest/setup-file.js' ],
                config: 'C:\\Users\\xxx\\code\\quasar\\minds\\vitest.config.js',
                defines: {},
                root: 'C:/Users/xxx/code/quasar/minds',
                mode: [],
                inspect: false,
                inspectBrk: false,
                deps: {
                  moduleDirectories: [ '/node_modules/' ],
                  optimizer: { ssr: { enabled: true }, web: { enabled: true } },
                  web: { transformAssets: true, transformCss: true, transformGlobPattern: [] }
                },
                server: { deps: { inline: [ {}, {}, {}, '@nuxt/test-utils' ], moduleDirectories: [ '/node_modules/' ], cacheDir: 'node_modules/.vitest' } },
                snapshotOptions: { expand: false, snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
                poolMatchGlobs: [],
                globalSetup: [],
                cache: { dir: 'C:/Users/xxx/code/quasar/minds/node_modules/.vitest' },
                sequence: { hooks: 'parallel' },
                environmentMatchGlobs: [],
                browser: { enabled: false, headless: false, slowHijackESM: false, isolate: true, api: { middlewareMode: true } },
                testTransformMode: {}
              }
            }
          ],
          package: {
            version: '1.0.4',
            urls: { hooks: 'file:///C:/Users/xxx/AppData/Local/JetBrains/PhpStorm2023.3/wallaby/wallaby/runners/node/hooks.mjs' },
            paths: { root: 'C:\\Users\\xxx\\code\\quasar\\minds\\node_modules\\vitest', dist: 'C:\\Users\\xxx\\code\\quasar\\minds\\node_modules\\vitest\\dist' }
          }
        }
      }
    },
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0', autoDetected: true },
    preserveComments: false,
    extractComments: true,
    files: [
      { pattern: 'test/vitest/__tests__/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'test\\vitest\\__tests__\\**\\*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: 'test/vitest/fixtures/*.*', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'test/vitest/helper/*.*', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/stores/*.*', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/utils/{authentication,excel,notifier,pdf}.js', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**\\node_modules\\**', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**\\dist\\**', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**\\cypress\\**', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**\\.{idea,git,cache,output,temp}\\**', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**\\{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'test\\vitest\\fixtures\\*.*', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'test\\vitest\\helper\\*.*', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src\\stores\\*.*', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src\\utils\\{authentication,excel,notifier,pdf}.js', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/*.*', ignore: false, trigger: true, load: true, order: 1 }
    ],
    tests: [
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'test/vitest/fixtures/*.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'test/vitest/helper/*.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'src/stores/*.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'src/utils/{authentication,excel,notifier,pdf}.js', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**\\node_modules\\**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**\\dist\\**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**\\cypress\\**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**\\.{idea,git,cache,output,temp}\\**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**\\{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'test\\vitest\\fixtures\\*.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'test\\vitest\\helper\\*.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'src\\stores\\*.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'src\\utils\\{authentication,excel,notifier,pdf}.js', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'test/vitest/__tests__/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: 'test\\vitest\\__tests__\\**\\*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}', ignore: false, trigger: true, load: true, test: true, order: 3 }
    ],
    workers: { initial: 1, regular: 1, recycle: false },
    dot: true,
    captureConsoleLog: true,
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: 'C:\\Program Files\\nodejs\\node.exe', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: true,
    symlinkNodeModules: undefined,
    configCode: 'auto.detect#147180772'
  },
  packageJSON: {
    dependencies: {
      '@apollo/client': '^3.6.8',
      '@casl/ability': '^6.0.0',
      '@casl/vue': '^2.1.2',
      '@chenfengyuan/vue-qrcode': '^2.0.0',
      '@quasar/extras': '^1.10.7',
      '@vue/apollo-composable': '^4.0.0-beta.4',
      axios: '^1.1.2',
      'commons-math-interpolation': '^2.2.3',
      'core-js': '^3.8.2',
      'crypto-js': '^4.1.1',
      'deep-diff': '^1.0.2',
      graphql: '^16.8.0',
      'graphql-tag': '^2.12.6',
      'graphql-ws': '^5.6.2',
      highcharts: '^11.0.0',
      'highcharts-vue': '^1.4.3',
      'image-to-base64': '^2.2.0',
      jspdf: '^2.2.0',
      liquidjs: '^10.0.0',
      'object-hash': '^3.0.0',
      pinia: '^2.0.22',
      qrcode: '^1.4.4',
      quasar: '^2.6.0',
      uuid: '^9.0.0',
      vue: '^3.2.47',
      'vue-router': '^4.0.0',
      xlsx: '^0.18.0'
    },
    devDependencies: {
      '@pinia/testing': '^0.1.0',
      '@quasar/app-vite': '^1.0.6',
      '@quasar/quasar-app-extension-testing-unit-vitest': '^0.4.0',
      '@vitest/coverage-istanbul': '^1.0.0',
      '@vitest/ui': '^1.0.0',
      '@vue/test-utils': '^2.0.0',
      autoprefixer: '^10.4.2',
      eslint: '^8.23.1',
      'eslint-config-standard': '^17.0.0',
      'eslint-plugin-import': '^2.22.1',
      'eslint-plugin-n': '^16.0.0',
      'eslint-plugin-promise': '^6.0.0',
      'eslint-plugin-quasar': '^1.0.0',
      'eslint-plugin-vue': '^9.0.1',
      vitest: '^1.0.0',
      ws: '^8.9.0'
    }
  },
  fs: { numberOfFiles: 920 },
  debug: [
    '2023-12-14T13:05:38.547Z project waiting for initial run signal\n',
    '2023-12-14T13:05:38.561Z config Attempting automatic configuration for angular\n',
    '2023-12-14T13:05:38.565Z angular/cli config Angular CLI not found.\n',
    '2023-12-14T13:05:38.565Z config Finished attempting automatic configuration for angular (4ms)\n',
    '2023-12-14T13:05:38.565Z config Attempting automatic configuration for jest\n',
    "2023-12-14T13:05:38.570Z jest/config Error: Module jest-cli is not found in 'C:\\Users\\xxx\\code\\quasar\\minds'.\n" +
      '    at Object.loadJest (C:\\Users\\xxx\\AppData\\Local\\JetBrains\\PhpStorm2023.3\\wallaby\\wallaby\\server.js:508:1070)\n' +
      '    at n (C:\\Users\\xxx\\AppData\\Local\\JetBrains\\PhpStorm2023.3\\wallaby\\wallaby\\server.js:196:23421)\n' +
      '    at Object.configure (C:\\Users\\xxx\\AppData\\Local\\JetBrains\\PhpStorm2023.3\\wallaby\\wallaby\\server.js:196:26531)\n' +
      '    at automaticConfigurationProviders.reduce.Promise.resolve.success (C:\\Users\\xxx\\AppData\\Local\\JetBrains\\PhpStorm2023.3\\wallaby\\wallaby\\server.js:144:12207)\n' +
      '    at async automaticConfigurationProviders.reduce.Promise.resolve.success (C:\\Users\\xxx\\AppData\\Local\\JetBrains\\PhpStorm2023.3\\wallaby\\wallaby\\server.js:144:12084)\n' +
      '    at async Config.load (C:\\Users\\xxx\\AppData\\Local\\JetBrains\\PhpStorm2023.3\\wallaby\\wallaby\\server.js:144:12024)\n',
    '2023-12-14T13:05:38.570Z config Finished attempting automatic configuration for jest (5ms)\n',
    '2023-12-14T13:05:38.570Z config Attempting automatic configuration for vitest\n',
    '2023-12-14T13:05:38.573Z vitest/config Detected Vitest (1.0.4).\n',
    '2023-12-14T13:05:41.434Z config Finished attempting automatic configuration for vitest (2864ms)\n',
    '2023-12-14T13:05:41.436Z project Wallaby Node version: v20.10.0\n',
    '2023-12-14T13:05:41.436Z project Wallaby config: C:\\Users\\xxx\\code\\quasar\\minds\\auto.detect\n',
    '2023-12-14T13:05:41.491Z fs File system starting\n',
    '2023-12-14T13:05:42.412Z fs File system scan completed\n',
    '2023-12-14T13:05:42.426Z project File cache: C:\\Users\\xxx\\AppData\\Local\\JetBrains\\PhpStorm2023.3\\wallaby\\projects\\3e70228aec54a4a8\n',
    '2023-12-14T13:05:42.741Z uiService Listening port 51235\n',
    '2023-12-14T13:05:42.753Z project package.json file change detected, invalidating local cache\n',
    '2023-12-14T13:05:42.782Z workers Parallelism for initial run: 1, for regular run: 1\n',
    '2023-12-14T13:05:42.783Z workers Starting run worker instance #0\n',
    '2023-12-14T13:05:42.785Z workers Web server is listening at 63672\n',
    '2023-12-14T13:05:42.785Z project File cache requires some updates, waiting required files from IDE\n',
    '2023-12-14T13:05:44.310Z workers Started run worker instance (delayed) #0\n',
    '2023-12-14T13:05:45.107Z project Stopping process pool\n',
    '2023-12-14T13:05:45.110Z project Test run started; run priority: 3\n',
    '2023-12-14T13:05:45.114Z project Running all tests\n',
    '2023-12-14T13:05:45.132Z workers Starting test run, priority: 3\n',
    '2023-12-14T13:05:45.133Z nodeRunner Starting sandbox [worker #0, session #3e4sx]\n',
    '2023-12-14T13:05:45.133Z nodeRunner Preparing sandbox [worker #0, session #3e4sx]\n',
    '2023-12-14T13:05:45.133Z nodeRunner Prepared sandbox [worker #0, session #3e4sx]\n',
    '2023-12-14T13:05:45.133Z workers [worker #0, session #3e4sx] Running tests in sandbox\n',
    "2023-12-14T13:05:47.502Z workers 'Scheduling Vitest Run (3e4sx): 2023-12-14T13:05:47.421Z'\n",
    '2023-12-14T13:05:56.755Z workers Some long running code has been detected: one of your files is taking more than 5000ms to execute.\n' +
      'Execution of the following files has started but has not finished:\n' +
      '- test/vitest/__tests__/components/servicing/ServicingFormItems.test.js\n' +
      'Try commenting out the test or excluding the test file from the `tests` list in your wallaby config,\n' +
      'and restarting wallaby to make sure that it is this test/file causing the issue and not something else.\n' +
      'Pinging test runner sandbox...\n',
    '2023-12-14T13:05:56.755Z workers Some long running code has been detected: one of your files is taking more than 5000ms to execute.\n' +
      'Execution of the following files has started but has not finished:\n' +
      '- test/vitest/__tests__/components/building/BuildingFormItems.test.js\n' +
      'Try commenting out the test or excluding the test file from the `tests` list in your wallaby config,\n' +
      'and restarting wallaby to make sure that it is this test/file causing the issue and not something else.\n' +
      'Pinging test runner sandbox...\n',
    '2023-12-14T13:05:56.755Z workers Some long running code has been detected: one of your files is taking more than 5000ms to execute.\n' +
      'Execution of the following files has started but has not finished:\n' +
      '- test/vitest/__tests__/components/order/OrderFormItems.test.js\n' +
      'Try commenting out the test or excluding the test file from the `tests` list in your wallaby config,\n' +
      'and restarting wallaby to make sure that it is this test/file causing the issue and not something else.\n' +
      'Pinging test runner sandbox...\n',

...

    '2023-12-14T13:11:12.094Z project Test name duplicate: should return "false" if not all necessary "formData" is set\n',
    '2023-12-14T13:11:12.094Z project Test name duplicate: should return "true" if all necessary "formData" is set\n',
    '2023-12-14T13:11:12.101Z project Processed executed tests\n',
    '2023-12-14T13:11:12.228Z project Processed code coverage\n',
    '2023-12-14T13:11:12.529Z project Test run result processed and sent to IDE\n',
    '2023-12-14T13:11:47.145Z uiService UI client connected\n',
    '2023-12-14T13:11:47.145Z uiService Outgoing message ui:handshake\n',
    '2023-12-14T13:11:47.182Z uiService Incoming message ui:start\n',
    '2023-12-14T13:11:47.184Z uiService Outgoing message ui:summary\n',
    '2023-12-14T13:11:47.193Z uiService Outgoing message ui:files\n',
    '2023-12-14T13:11:47.195Z uiService Incoming message ui:tests:resultsRequested\n',
    '2023-12-14T13:11:47.339Z uiService Outgoing message ui:tests:allResultsUpdated\n',
    '2023-12-14T13:11:58.756Z uiService Incoming message ui:tests:resultsAbandoned\n',
    '2023-12-14T13:12:58.224Z uiService Incoming message ui:codeRequested\n',
    '2023-12-14T13:14:27.656Z uiService UI client disconnected\n',
    '2023-12-14T13:14:41.296Z uiService UI client connected\n',
    '2023-12-14T13:14:41.296Z uiService Outgoing message ui:handshake\n',
    '2023-12-14T13:14:41.328Z uiService Incoming message ui:start\n',
    '2023-12-14T13:14:41.330Z uiService Outgoing message ui:summary\n',
    '2023-12-14T13:14:41.335Z uiService Outgoing message ui:files\n',
    '2023-12-14T13:14:41.336Z uiService Incoming message ui:tests:resultsRequested\n',
    '2023-12-14T13:14:41.420Z uiService Outgoing message ui:tests:allResultsUpdated\n',
    '2023-12-14T13:14:46.123Z uiService Incoming message ui:tests:resultsAbandoned\n',
    '2023-12-14T13:14:58.987Z uiService Incoming message ui:codeRequested\n',
    '2023-12-14T13:15:34.514Z uiService UI client disconnected\n',
    '2023-12-14T13:15:42.959Z uiService UI client connected\n',
    '2023-12-14T13:15:42.959Z uiService Outgoing message ui:handshake\n',
    '2023-12-14T13:15:42.995Z uiService Incoming message ui:start\n',
    '2023-12-14T13:15:42.996Z uiService Outgoing message ui:summary\n',
    '2023-12-14T13:15:43.000Z uiService Outgoing message ui:files\n',
    '2023-12-14T13:15:43.002Z uiService Incoming message ui:tests:resultsRequested\n',
    '2023-12-14T13:15:43.047Z uiService Outgoing message ui:tests:allResultsUpdated\n',
    '2023-12-14T13:15:47.305Z uiService Incoming message ui:tests:resultsAbandoned\n',
    '2023-12-14T13:15:55.520Z uiService Incoming message ui:codeRequested\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
Thanks for reporting the issue. It's now fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) v1.0.1512.
