### ISSUE TITLE
Automatic Angular CLI configuration error: Unable to load webpack module.

### ISSUE THREAD

**Issue by azaeng04** [wallabyjs/public#3309]
### Issue description or question
Similar to issue #2737, but I am getting the error in VS Code:

```
‌[Error] Automatic Angular CLI configuration error: Unable to load webpack module. 
[Error]  
[Error] We've also tried to automatically configure Wallaby.js for other frameworks 
[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'. 
[Error] Automatic Vitest configuration error: Vitest dependency not found. 
```

### Wallaby diagnostics report
Unable to get the diagnostic report since Wallaby fails before it can even start

![image](https://github.com/wallabyjs/public/assets/13921692/779cbd8a-8655-44cb-b436-f7dc9e43d1bc)

**Comment by ArtemGovorov** [comment]
Can you please share the content of your `package.json` and `angular.json` files?

**Comment by azaeng04** [comment]
`packag.json`
```
{
  "name": "my-app",
  "description": "My App",
  "version": "1.0.0-beta",
  "private": true,
  "scripts": {
    "postinstall": "ngcc",
    "build": "ng build",
    "watch": "ng build --watch",
    "start": "ng serve",
    "test": "ng test",
    "lint": "ng lint",
    "gqlgen": ".\\node_modules\\.bin\\graphql-codegen --config codegen.yml"
  },
  "dependencies": {
    "@angular/core": "15.2.0",
    "@angular/common": "15.2.0",
    "@angular/compiler": "15.2.0",
    "@angular/platform-browser": "15.2.0",
    "@angular/platform-browser-dynamic": "15.2.0",
    "@angular/router": "15.2.0",
    "@angular/forms": "15.2.0",
    "@angular/animations": "15.2.0",
    "@angular/localize": "15.2.0",
    "@angular/cdk": "14.2.7",
    "@angular/material": "14.2.7",
    "@ngneat/until-destroy": "9.2.0",
    "@boldbi/boldbi-embedded-sdk": "6.3.3",
    "@microsoft/signalr": "7.0.3",
    "@azure/msal-browser": "3.1.0",
    "@azure/msal-angular": "3.0.4",
    "zone.js": "0.11.8",
    "rxjs": "7.8.0",
    "tslib": "2.5.0",
    "util": "0.12.4",
    "ngx-resize-observer": "2.4.0",
    "text-encoding-shim": "1.0.4",
    "ngx-cookie-service": "15.0.0",
    "fast-sha256": "1.3.0",
    "date-fns": "2.16.1",
    "date-fns-tz": "1.1.6",
    "dock-spawn-ts": "2.403.x",
    "lodash": "4.17.21",
    "pluralize": "8.0.0",
    "papaparse": "4.6.3",
    "file-saver": "2.0.2",
    "leader-line-new": "1.1.9",
    "ol": "6.14.x",
    "@fortawesome/fontawesome-free": "5.15.4",
    "vis-data": "7.1.6",
    "vis-network": "9.1.6",
    "vis-timeline": "7.7.2",
    "vis-util": "5.0.3",
    "xlsx": "0.16.x",
    "@techiediaries/ngx-qrcode": "9.1.0",
    "@zip.js/zip.js": "2.3.24",
    "xml-js": "1.6.11",
    "stream": "0.0.2",
    "ngx-markdown": "15.1.1",
    "dat.gui": "0.7.7",
    "three": "0.148.0",
    "ngx-monaco-editor-v2": "15.0.1"
  },
  "devDependencies": {
    "@angular/cli": "15.2.0",
    "@angular/compiler-cli": "15.2.0",
    "@angular/language-service": "15.2.0",
    "@angular-devkit/build-angular": "15.2.0",
    "@angular-eslint/builder": "15.2.1",
    "@angular-eslint/eslint-plugin": "15.2.1",
    "@angular-eslint/eslint-plugin-template": "15.2.1",
    "@angular-eslint/schematics": "15.2.1",
    "@angular-eslint/template-parser": "15.2.1",
    "@typescript-eslint/eslint-plugin": "5.54.0",
    "@typescript-eslint/parser": "5.54.0",
    "typescript": "4.9.5",
    "eslint": "7.26.x",
    "raw-loader": "4.0.2",
    "url-loader": "4.1.1",
    "graphql": "14.5.8",
    "@graphql-codegen/cli": "1.8.3",
    "@graphql-codegen/add": "1.8.3",
    "@graphql-codegen/typescript": "1.8.3",
    "@graphql-codegen/typescript-operations": "1.8.3",
    "jasmine-auto-spies": "^8.0.1",
    "ts-node": "10.9.1",
    "msw": "1.3.0",
    "marked": "4.0.17",
    "@babel/preset-typescript": "7.22.15",
    "@babel/preset-env": "7.22.15",
    "babel-plugin-transform-import-meta": "2.2.1",
    "@types/papaparse": "4.5.9",
    "@types/file-saver": "2.0.1",
    "@types/node": "18.17.14",
    "@types/ws": "8.5.4",
    "@types/pluralize": "0.0.29",
    "@types/ol": "6.5.x",
    "@types/pdfmake": "0.1.17",
    "@types/lodash": "4.14.191",
    "@types/dat.gui": "0.7.7",
    "@types/three": "0.148.1",
    "@types/marked": "4.0.3",
    "@types/jasmine": "~5.1.0",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "@angular-builders/custom-webpack": "15.0.0",
    "stream-http": "3.2.0",
    "https-browserify": "1.0.0",
    "timers-browserify": "2.0.12",
    "browserify-zlib": "0.2.0",
    "assert": "2.1.0",
    "url": "0.11.3"
  }
}
```

`angular.json`

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "projects": {
    "my-app": {
      "projectType": "application",
      "schematics": {},
      "root": "",
      "sourceRoot": "./",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "tsConfig": "./tsconfig.json",
            "index": "./MyApp/index.html",
            "main": "./MyApp/boot.ts",
            "assets": [ "./assets" ],
            "scripts": [
              "node_modules/marked/marked.min.js"
            ],
            "styles": [
              "./assets/styles/app.scss",
              "./assets/styles/themes/_core-theme.scss",
              {
                "input": "./assets/styles/themes/default-theme.scss",
                "bundleName": "default-theme-v2",
                "inject": false
              },
              {
                "input": "./assets/styles/themes/dhl-theme.scss",
                "bundleName": "dhl-theme-v2",
                "inject": false
              },
              {
                "input": "./assets/styles/themes/vital-theme.scss",
                "bundleName": "vital-theme-v2",
                "inject": false
              },
              "node_modules/dock-spawn-ts/lib/css/dock-manager.css",
              "node_modules/dock-spawn-ts/lib/css/dock-manager-style.css",
              "node_modules/@fortawesome/fontawesome-free/css/all.min.css",
              "node_modules/vis-timeline/styles/vis-timeline-graph2d.min.css",
              "MyApp/flex/assets/css/flex.scss",
              "MyApp/travel-gantt/assets/css/base-styles.scss",
              "MyApp/travel-gantt/assets/css/theme.scss"
            ],
            "sourceMap": true,
            "outputPath": "./MyAppServer/wwwroot"
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "./environments/working.env.ts",
                  "with": "./environments/prod.env.ts"
                }
              ],
              "outputHashing": "all",
              "sourceMap": {
                "hidden": true,
                "scripts": true
              },
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "aot": false,
              "buildOptimizer": false,
              "optimization": false,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "20mb",
                  "maximumError": "25mb"
                }
              ]
            },
            "development": {
              "namedChunks": true,
              "vendorChunk": true,
              "aot": false,
              "buildOptimizer": false,
              "optimization": false,
              "extractLicenses": false
            }
          },
          "defaultConfiguration": "development"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "my-app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "my-app:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "angular.io-example:build"
          }
        },
        "test": {
          "builder": "@angular-builders/custom-webpack:karma",
          "options": {              
            "customWebpackConfig": {
              "path": "./webpack.test.config.js"
            },
            "polyfills": [
              "zone.js",
              "zone.js/testing"
            ],
            "tsConfig": "tsconfig.spec.json",
            "inlineStyleLanguage": "scss",
            "assets": [ "./assets" ],
            "scripts": [
              "node_modules/marked/marked.min.js"
            ],
            
            "styles": [
              "./assets/styles/app.scss",
              "./assets/styles/themes/_core-theme.scss",
              {
                "input": "./assets/styles/themes/default-theme.scss",
                "bundleName": "default-theme-v2",
                "inject": false
              },
              {
                "input": "./assets/styles/themes/dhl-theme.scss",
                "bundleName": "dhl-theme-v2",
                "inject": false
              },
              {
                "input": "./assets/styles/themes/vital-theme.scss",
                "bundleName": "vital-theme-v2",
                "inject": false
              },
              "node_modules/dock-spawn-ts/lib/css/dock-manager.css",
              "node_modules/dock-spawn-ts/lib/css/dock-manager-style.css",
              "node_modules/@fortawesome/fontawesome-free/css/all.min.css",
              "node_modules/vis-timeline/styles/vis-timeline-graph2d.min.css",
              "MyApp/flex/assets/css/flex.scss",
              "MyApp/travel-gantt/assets/css/base-styles.scss",
              "MyApp/travel-gantt/assets/css/theme.scss"
            ],
            "karmaConfig": "karma.conf.js"
          }
        },
        "lint": {
          "builder": "@angular-eslint/builder:lint",
          "options": {
            "lintFilePatterns": [
              "**/**/*.ts",
              "**/**/*.html"
            ]
          }
        }
      }
    }
  },
  "schematics": {
    "@schematics/angular:component": {
      "style": "scss"
    }
  },
  "cli": {
    "analytics": false,
    "schematicCollections": [
      "@angular-eslint/schematics"
    ]
  }
}
```

**Comment by azaeng04** [comment]
It works when I run it with `ng test`

**Comment by azaeng04** [comment]
```

module.exports = {
  resolve: {
    fallback: {
      http: require.resolve("stream-http"),
      https: require.resolve("https-browserify"),
      timers: require.resolve("timers-browserify"),
      zlib: require.resolve("browserify-zlib"),
      assert: require.resolve("assert"),
      url: require.resolve("url")
    }
  }
};
```

**Comment by smcenlly** [comment]
Can you please run the following command from the CLI from your project root and provide us with the output?

```bash
npm ls webpack
```

You may also try to delete your `node_modules` folder, and reinstall your project dependencies with `npm install`; it may fix the problem for you.

**Comment by azaeng04** [comment]
![image](https://github.com/wallabyjs/public/assets/13921692/4cc6df55-6d4b-4116-9d14-72b43c75e761)

@smcenlly I did that and a normal `npm install`. I then get this message:
![image](https://github.com/wallabyjs/public/assets/13921692/68f321fe-e1dc-4d2c-8139-abc1faf34188)

But `ng test` works just fine and picks up all tests.

**Comment by azaeng04** [comment]
Diagnostic Report
```
{
  editorVersion: '1.85.0',
  pluginVersion: '1.0.371',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.22631',
  nodeVersion: 'v18.18.2',
  coreVersion: '1.0.1513',
  checksum: 'NDg2ZGU1MzUyMTNiZTU2MDczN2MxZGUyOTEzNWM0NDIsMTcxMTY3MDQwMDAwMCww',
  config: {
    diagnostics: {
      angular: {
        workspace: {
          '$schema': './node_modules/@angular/cli/lib/config/schema.json',
          version: 1,
          projects: {
            'my-app': {
              projectType: 'application',
              schematics: {},
              root: '',
              sourceRoot: './',
              prefix: 'app',
              architect: {
                build: {
                  builder: '@angular-devkit/build-angular:browser',
                  options: {
                    tsConfig: './tsconfig.json',
                    index: './My.App/index.html',
                    main: './My.App/boot.ts',
                    assets: [ './assets' ],
                    scripts: [ 'node_modules/marked/marked.min.js' ],
                    styles: [
                      './assets/styles/app.scss',
                      './assets/styles/themes/_core-theme.scss',
                      { input: './assets/styles/themes/default-theme.scss', bundleName: 'default-theme-v2', inject: false },
                      { input: './assets/styles/themes/dhl-theme.scss', bundleName: 'dhl-theme-v2', inject: false },
                      { input: './assets/styles/themes/vital-theme.scss', bundleName: 'vital-theme-v2', inject: false },
                      'node_modules/dock-spawn-ts/lib/css/dock-manager.css',
                      'node_modules/dock-spawn-ts/lib/css/dock-manager-style.css',
                      'node_modules/@fortawesome/fontawesome-free/css/all.min.css',
                      'node_modules/vis-timeline/styles/vis-timeline-graph2d.min.css',
                      'My.App/flex/assets/css/flex.scss',
                      'My.App/travel-gantt/assets/css/base-styles.scss',
                      'My.App/travel-gantt/assets/css/theme.scss'
                    ],
                    sourceMap: true,
                    outputPath: './My.App.Server/wwwroot'
                  },
                  configurations: {
                    production: {
                      fileReplacements: [ { replace: './environments/working.env.ts', with: './environments/prod.env.ts' } ],
                      outputHashing: 'all',
                      sourceMap: { hidden: true, scripts: true },
                      namedChunks: false,
                      extractLicenses: true,
                      vendorChunk: false,
                      aot: false,
                      buildOptimizer: false,
                      optimization: false,
                      budgets: [ { type: 'initial', maximumWarning: '20mb', maximumError: '25mb' } ]
                    },
                    development: { namedChunks: true, vendorChunk: true, aot: false, buildOptimizer: false, optimization: false, extractLicenses: false }
                  },
                  defaultConfiguration: 'development'
                },
                serve: {
                  builder: '@angular-devkit/build-angular:dev-server',
                  options: { browserTarget: 'my-app:build' },
                  configurations: { production: { browserTarget: 'my-app:build:production' } }
                },
                'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: 'angular.io-example:build' } },
                test: {
                  builder: '@angular-builders/custom-webpack:karma',
                  options: {
                    customWebpackConfig: { path: './webpack.test.config.js' },
                    polyfills: [ 'zone.js', 'zone.js/testing' ],
                    tsConfig: 'tsconfig.spec.json',
                    inlineStyleLanguage: 'scss',
                    assets: [ './assets' ],
                    scripts: [ 'node_modules/marked/marked.min.js' ],
                    styles: [
                      './assets/styles/app.scss',
                      './assets/styles/themes/_core-theme.scss',
                      { input: './assets/styles/themes/default-theme.scss', bundleName: 'default-theme-v2', inject: false },
                      { input: './assets/styles/themes/dhl-theme.scss', bundleName: 'dhl-theme-v2', inject: false },
                      { input: './assets/styles/themes/vital-theme.scss', bundleName: 'vital-theme-v2', inject: false },
                      'node_modules/dock-spawn-ts/lib/css/dock-manager.css',
                      'node_modules/dock-spawn-ts/lib/css/dock-manager-style.css',
                      'node_modules/@fortawesome/fontawesome-free/css/all.min.css',
                      'node_modules/vis-timeline/styles/vis-timeline-graph2d.min.css',
                      'My.App/flex/assets/css/flex.scss',
                      'My.App/travel-gantt/assets/css/base-styles.scss',
                      'My.App/travel-gantt/assets/css/theme.scss'
                    ],
                    karmaConfig: 'karma.conf.js'
                  }
                },
                lint: { builder: '@angular-eslint/builder:lint', options: { lintFilePatterns: [ '**/**/*.ts', '**/**/*.html' ] } }
              }
            }
          },
          schematics: { '@schematics/angular:component': { style: 'scss' } },
          cli: { analytics: false, schematicCollections: [ '@angular-eslint/schematics' ] }
        },
        main: '\n' +
          '  \n' +
          "  import 'zone.js/testing';\n" +
          "  import { getTestBed } from '@angular/core/testing';\n" +
          '  import {\n' +
          '    BrowserDynamicTestingModule,\n' +
          '    platformBrowserDynamicTesting,\n' +
          "   } from '@angular/platform-browser-dynamic/testing';\n" +
          '   \n' +
          '  // Initialize the Angular testing environment.\n' +
          '  getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting(), {\n' +
          '    errorOnUnknownElements: true,\n' +
          '    errorOnUnknownProperties: true\n' +
          '  });'
      }
    },
    testFramework: { version: 'jasmine@5.1.1', configurator: 'jasmine@4.6.0', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3', autoDetected: true },
    env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    files: [
      { pattern: '**/*.spec.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'My.App/boot.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'My.App/index.html', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'test.base.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'test.wallaby.ts', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'node_modules/marked/marked.min.js', instrument: false, load: true, ignore: false, trigger: true, order: 2 },
      { pattern: '**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 3 },
      { pattern: '**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 4 }
    ],
    tests: [ { pattern: '**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 5 } ],
    captureConsoleLog: true,
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: false,
    configCode: 'auto.detect#1401795509'
  },
  packageJSON: {
    dependencies: {
      '@angular/core': '15.2.0',
      '@angular/common': '15.2.0',
      '@angular/compiler': '15.2.0',
      '@angular/platform-browser': '15.2.0',
      '@angular/platform-browser-dynamic': '15.2.0',
      '@angular/router': '15.2.0',
      '@angular/forms': '15.2.0',
      '@angular/animations': '15.2.0',
      '@angular/localize': '15.2.0',
      '@angular/cdk': '14.2.7',
      '@angular/material': '14.2.7',
      '@ngneat/until-destroy': '9.2.0',
      '@boldbi/boldbi-embedded-sdk': '6.3.3',
      '@microsoft/signalr': '7.0.3',
      '@azure/msal-browser': '3.1.0',
      '@azure/msal-angular': '3.0.4',
      'zone.js': '0.11.8',
      rxjs: '7.8.0',
      tslib: '2.5.0',
      util: '0.12.4',
      'ngx-resize-observer': '2.4.0',
      'text-encoding-shim': '1.0.4',
      'ngx-cookie-service': '15.0.0',
      'fast-sha256': '1.3.0',
      'date-fns': '2.16.1',
      'date-fns-tz': '1.1.6',
      'dock-spawn-ts': '2.403.x',
      lodash: '4.17.21',
      pluralize: '8.0.0',
      papaparse: '4.6.3',
      'file-saver': '2.0.2',
      'leader-line-new': '1.1.9',
      ol: '6.14.x',
      '@fortawesome/fontawesome-free': '5.15.4',
      'vis-data': '7.1.6',
      'vis-network': '9.1.6',
      'vis-timeline': '7.7.2',
      'vis-util': '5.0.3',
      xlsx: '0.16.x',
      '@techiediaries/ngx-qrcode': '9.1.0',
      '@zip.js/zip.js': '2.3.24',
      'xml-js': '1.6.11',
      stream: '0.0.2',
      'ngx-markdown': '15.1.1',
      'dat.gui': '0.7.7',
      three: '0.148.0',
      'ngx-monaco-editor-v2': '15.0.1'
    },
    devDependencies: {
      '@angular/cli': '15.2.0',
      '@angular/compiler-cli': '15.2.0',
      '@angular/language-service': '15.2.0',
      '@angular-devkit/build-angular': '15.2.0',
      '@angular-eslint/builder': '15.2.1',
      '@angular-eslint/eslint-plugin': '15.2.1',
      '@angular-eslint/eslint-plugin-template': '15.2.1',
      '@angular-eslint/schematics': '15.2.1',
      '@angular-eslint/template-parser': '15.2.1',
      '@typescript-eslint/eslint-plugin': '5.54.0',
      '@typescript-eslint/parser': '5.54.0',
      typescript: '4.9.5',
      eslint: '7.26.x',
      'raw-loader': '4.0.2',
      'url-loader': '4.1.1',
      graphql: '14.5.8',
      '@graphql-codegen/cli': '1.8.3',
      '@graphql-codegen/add': '1.8.3',
      '@graphql-codegen/typescript': '1.8.3',
      '@graphql-codegen/typescript-operations': '1.8.3',
      'jasmine-auto-spies': '^8.0.1',
      'ts-node': '10.9.1',
      msw: '1.3.0',
      marked: '4.0.17',
      '@babel/preset-typescript': '7.22.15',
      '@babel/preset-env': '7.22.15',
      'babel-plugin-transform-import-meta': '2.2.1',
      '@types/papaparse': '4.5.9',
      '@types/file-saver': '2.0.1',
      '@types/node': '18.17.14',
      '@types/ws': '8.5.4',
      '@types/pluralize': '0.0.29',
      '@types/ol': '6.5.x',
      '@types/pdfmake': '0.1.17',
      '@types/lodash': '4.14.191',
      '@types/dat.gui': '0.7.7',
      '@types/three': '0.148.1',
      '@types/marked': '4.0.3',
      '@types/jasmine': '~5.1.0',
      'jasmine-core': '~5.1.0',
      karma: '~6.4.0',
      'karma-chrome-launcher': '~3.2.0',
      'karma-coverage': '~2.2.0',
      'karma-jasmine': '~5.1.0',
      'karma-jasmine-html-reporter': '~2.1.0',
      '@angular-builders/custom-webpack': '15.0.0',
      'stream-http': '3.2.0',
      'https-browserify': '1.0.0',
      'timers-browserify': '2.0.12',
      'browserify-zlib': '0.2.0',
      assert: '2.1.0',
      url: '0.11.3'
    }
  },
  fs: { numberOfFiles: 76043 },
  debug: [
    '2023-12-18T08:50:54.009Z project waiting for initial run signal\n',
    '2023-12-18T08:50:54.030Z config Attempting automatic configuration for angular\n',
    '2023-12-18T08:50:54.036Z angular/cli config Detected Angular CLI.\n',
    '2023-12-18T08:50:54.040Z angular/cli config Angular currentDirPath: "C:\\Users\\Azariah\\project\\My_App\\main\\WebApps", workspaceDirPath: "C:\\Users\\Azariah\\project\\My_App\\main\\WebApps"\n',
    '2023-12-18T08:50:57.892Z angular/cli karma project config Using builtin C:/Users/Azariah/project/My_App/main/WebApps/test.js.\n',
    '2023-12-18T08:50:57.929Z config Finished attempting automatic configuration for angular (3899ms)\n',
    '2023-12-18T08:50:57.930Z project Wallaby Node version: v18.18.2\n',
    '2023-12-18T08:50:57.930Z project Wallaby config: C:\\Users\\Azariah\\project\\My_App\\main\\WebApps\\auto.detect\n',
    '2023-12-18T08:50:57.994Z fs File system starting\n',
    '2023-12-18T08:50:58.041Z fs File system scan completed\n',
    '2023-12-18T08:50:58.050Z project File cache: C:\\Users\\Azariah\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.371\\projects\\420754480ff6a0b6\n',
    '2023-12-18T08:50:58.287Z uiService Listening port 51235\n',
    '2023-12-18T08:50:58.323Z project package.json file change detected, invalidating local cache\n',
    '2023-12-18T08:51:11.719Z chromeRunner launch new instance (path: <default>, flags: --headless --disable-gpu --deterministic-fetch)\n',
    '2023-12-18T08:51:11.724Z workers Parallelism for initial run: 10, for regular run: 5\n',
    '2023-12-18T08:51:11.724Z workers Starting run worker instance #0\n',
    '2023-12-18T08:51:11.725Z workers Starting run worker instance #1\n',
    '2023-12-18T08:51:11.725Z workers Starting run worker instance #2\n',
    '2023-12-18T08:51:11.725Z workers Starting run worker instance #3\n',
    '2023-12-18T08:51:11.725Z workers Starting run worker instance #4\n',
    '2023-12-18T08:51:11.725Z workers Starting run worker instance #5\n',
    '2023-12-18T08:51:11.725Z workers Starting run worker instance #6\n',
    '2023-12-18T08:51:11.725Z workers Starting run worker instance #7\n',
    '2023-12-18T08:51:11.725Z workers Starting run worker instance #8\n',
    '2023-12-18T08:51:11.725Z workers Starting run worker instance #9\n',
    '2023-12-18T08:51:11.728Z workers Web server is listening at 55282\n',
    '2023-12-18T08:51:11.740Z project Stopping process pool\n',
    '2023-12-18T08:51:11.740Z project File cache is up-to-date, starting full test run\n',
    '2023-12-18T08:51:12.871Z chromeRunner Connection to Chrome Debugger Protocol on 127.0.0.1:55281 failed: Error: connect ECONNREFUSED 127.0.0.1:55281\n',
    '2023-12-18T08:51:14.095Z chromeRunner Connection to Chrome Debugger Protocol on 127.0.0.1:55281 succeeded\n',
    '2023-12-18T08:51:14.096Z workers Started run worker instance (immediate) #0\n',
    '2023-12-18T08:51:14.096Z workers Started run worker instance (immediate) #1\n',
    '2023-12-18T08:51:14.096Z workers Started run worker instance (immediate) #2\n',
    '2023-12-18T08:51:14.096Z workers Started run worker instance (immediate) #3\n',
    '2023-12-18T08:51:14.096Z workers Started run worker instance (immediate) #4\n',
    '2023-12-18T08:51:14.096Z workers Started run worker instance (immediate) #5\n',
    '2023-12-18T08:51:14.096Z workers Started run worker instance (immediate) #6\n',
    '2023-12-18T08:51:14.096Z workers Started run worker instance (immediate) #7\n',
    '2023-12-18T08:51:14.096Z workers Started run worker instance (immediate) #8\n',
    '2023-12-18T08:51:14.096Z workers Started run worker instance (immediate) #9\n',
    '2023-12-18T08:51:37.847Z project Running postprocessor\n',
    '2023-12-18T08:51:37.887Z postprocessor Processing started.\n',
    '2023-12-18T08:51:37.887Z postprocessor Initializing.\n',
    '2023-12-18T08:51:37.889Z postprocessor Initializing entry.\n',
    '2023-12-18T08:51:37.889Z postprocessor Sanitizing configuration.\n',
    '2023-12-18T08:51:37.889Z postprocessor Adjusting configuration.\n',
    '2023-12-18T08:51:37.959Z postprocessor Creating compiler.\n',
    '2023-12-18T08:51:41.520Z postprocessor Customizing compiler.\n',
    '2023-12-18T08:51:41.520Z postprocessor Compilation started.\n',
    '2023-12-18T08:54:29.703Z project Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):\n' +
      "Error: EMFILE: too many open files, open 'C:\\Users\\Azariah\\project\\My_App\\main\\WebApps\\node_modules\\@angular\\compiler-cli\\bundles\\chunk-2PLRZDNU.js'\n" +
      '@ ./node_modules/css-loader/dist/runtime/api.js,\n' +
      '@ ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!wallaby-pre-loader!./node_modules/dock-spawn-ts/lib/css/dock-manager-style.css?ngGlobalStyle\n' +
      '    at i.process (c:\\Users\\Azariah\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.371\\wallaby5ac778\\server.js:197:109865)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n',
    '2023-12-18T08:54:29.706Z project Test run finished\n',
    '2023-12-18T08:54:29.706Z project Test run data re-queued\n',
    '2023-12-18T08:59:12.362Z project Running postprocessor\n',
    '2023-12-18T08:59:13.094Z postprocessor Processing started.\n',
    '2023-12-18T08:59:13.094Z postprocessor Initializing entry.\n',
    '2023-12-18T08:59:15.246Z postprocessor Compilation started (incremental).\n',
    '2023-12-18T08:59:18.771Z project Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):\n' +
      "Error: EMFILE: too many open files, open 'C:\\Users\\Azariah\\project\\My_App\\main\\WebApps\\node_modules\\@angular\\compiler-cli\\bundles\\chunk-2PLRZDNU.js'\n" +
      '@ ./node_modules/css-loader/dist/runtime/api.js,\n' +
      '@ ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!wallaby-pre-loader!./node_modules/dock-spawn-ts/lib/css/dock-manager.css?ngGlobalStyle\n' +
      '    at i.process (c:\\Users\\Azariah\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.371\\wallaby5ac778\\server.js:197:109865)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n',
    '2023-12-18T08:59:18.773Z project Test run finished\n',
    '2023-12-18T08:59:18.773Z project Test run data re-queued\n'
  ]
}
```

**Comment by smcenlly** [comment]
Thanks for providing your diagnostics report.

Your project configuration as a little non-standard and your project `"sourceRoot": "./",` was causing Wallaby to watch all files in your `node_modules` directory.

We have updated Wallaby to handle your specific project configuration. Can you please update to Wallaby core `v1.0.1514+`. You can do this with the `Wallaby.js: Force Core Update` VS Code command.

If you're still having problems after trying this, please let us know.

**Comment by azaeng04** [comment]
It's working! Thank you @smcenlly

**Comment by smcenlly** [comment]
That's great to hear. For posterity, just documenting that there were two issues:

1. There was something wrong with your project dependencies (fixed by `npm install`), and
2. Wallaby didn't support non-nested `sourceRoot`

I'll close the issue now.
