### ISSUE TITLE
Can't use import statement outside a module

### ISSUE THREAD

**Issue by chancesmith** [wallabyjs/public#3317]
### Issue description or question

I'm getting an error setting up wallaby in a yarn workspace project. I've put the config file in `<repo-root>/frontend/apps/mobile/wallaby.config.js`. When I start with this configuration with `Smart Start`, I get an error:

`Can't use import statement outside a module`

screenshot
![Screenshot 2024-01-10 at 10 41 04 AM](https://github.com/wallabyjs/public/assets/4466585/eae8f875-d691-4b12-80f2-8bdabf69379e)

with this config
```
module.exports = function (w) {
  return {
    files: ["src/**/*.ts?(x)", "!src/**/*.spec.ts?(x)"],
    tests: ["src/**/*.spec.ts?(x)"],

    runAllTestsWhenNoAffectedTests: true,

    env: {
      type: "node",
    },

    testFramework: "ts-jest",

    compilers: {
      "**/*.ts?(x)": w.compilers.typeScript({ isolatedModules: true }),
    },

    setup: function (wallaby) {
      const jestConfig = require("./.jest/config.ts")
      wallaby.testFramework.configure(jestConfig)
    },
  }
}
```

### Wallaby diagnostics report

```
{
  editorVersion: '1.85.1',
  pluginVersion: '1.0.371',
  editorType: 'VSCode',
  osVersion: 'darwin 23.2.0',
  nodeVersion: 'v18.15.0',
  coreVersion: '1.0.1517',
  checksum: 'ZTE3NDlkNThhODgwNmNiZDVlN2JiYzU4NThlMjBkOWEsMTcwNzM1MDQwMDAwMCww',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/private/var/folders/l2/l72h9v351k709j9ljtcj6b9m0000gq/T/jest_dz',
              clearMocks: false,
              collectCoverageFrom: [],
              coverageDirectory: '<homeDir>/wip/lifeway-discipleship/frontend/apps/mobile/coverage',
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/wip/lifeway-discipleship/frontend/apps/mobile',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: undefined,
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              fakeTimers: { enableGlobally: false },
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: true, throwOnModuleCollision: false },
              id: '4b5211e56b9c90949009a67e00478a1a',
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [
                'js',   'mjs',
                'cjs',  'jsx',
                'ts',   'tsx',
                'json', 'node'
              ],
              moduleNameMapper: [],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              openHandlesTimeout: 1000,
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/wip/lifeway-discipleship/frontend/apps/mobile',
              roots: [ '<homeDir>/wip/lifeway-discipleship/frontend/apps/mobile' ],
              runner: '<homeDir>/wip/lifeway-discipleship/frontend/apps/mobile/node_modules/jest-runner/build/index.js',
              runtime: undefined,
              sandboxInjectedGlobals: [],
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: { escapeString: false, printBasicPrototype: false },
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/wip/lifeway-discipleship/frontend/apps/mobile/node_modules/jest-environment-node/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<homeDir>/wip/lifeway-discipleship/frontend/apps/mobile/node_modules/jest-circus/runner.js',
              transform: [ [ '\\.[jt]sx?$', '<homeDir>/wip/lifeway-discipleship/frontend/apps/mobile/node_modules/jest-config/node_modules/babel-jest/build/index.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            ci: false,
            collectCoverage: false,
            collectCoverageFrom: [],
            coverageDirectory: '<homeDir>/wip/lifeway-discipleship/frontend/apps/mobile/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 9,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            openHandlesTimeout: 1000,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [],
            randomize: undefined,
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/wip/lifeway-discipleship/frontend/apps/mobile',
            runInBand: undefined,
            runTestsByPath: false,
            seed: -1325434057,
            shard: undefined,
            showSeed: undefined,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: { escapeString: false, printBasicPrototype: false },
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/wip/lifeway-discipleship/frontend/apps/mobile/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true,
            workerIdleMemoryLimit: undefined,
            workerThreads: false
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/|android/|ios/', '/private/var/folders/l2/l72h9v351k709j9ljtcj6b9m0000gq/T/jest_dz', '\\./coverage' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/|android/|ios/', '/private/var/folders/l2/l72h9v351k709j9ljtcj6b9m0000gq/T/jest_dz', '\\./coverage' ],
            testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    dot: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, file: true, test: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/|android/|ios/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\/|android\/|ios\//,
        ignore: true,
        trigger: true,
        load: true,
        file: true,
        test: true
      },
      {
        pattern: '/private/var/folders/l2/l72h9v351k709j9ljtcj6b9m0000gq/T/jest_dz',
        regexp: /\/private\/var\/folders\/l2\/l72h9v351k709j9ljtcj6b9m0000gq\/T\/jest_dz/,
        ignore: true,
        trigger: true,
        load: true,
        file: true,
        test: true
      },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true, file: true }
    ],
    captureConsoleLog: true,
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true, file: false },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/|android/|ios/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\/|android\/|ios\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true,
        file: false
      },
      {
        pattern: '/private/var/folders/l2/l72h9v351k709j9ljtcj6b9m0000gq/T/jest_dz',
        regexp: /\/private\/var\/folders\/l2\/l72h9v351k709j9ljtcj6b9m0000gq\/T\/jest_dz/,
        ignore: true,
        trigger: true,
        load: true,
        test: true,
        file: false
      },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    smartStart: [ { test: true, source: false, pattern: '**/*', startMode: 'open' }, { test: false, source: true, pattern: '**/*', startMode: 'edit' } ],
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: true,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '/usr/local/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: false,
    configCode: 'auto.detect#-99745358',
    testLocations: [ 'src/context/__tests__/useSessionDownload.spec.tsx' ]
  },
  packageJSON: {
    dependencies: {
      '@apollo/client': '^3.6.9',
      '@babel/plugin-proposal-nullish-coalescing-operator': '^7.18.6',
      '@babel/plugin-proposal-optional-chaining': '^7.21.0',
      '@babel/plugin-transform-arrow-functions': '^7.22.5',
      '@babel/plugin-transform-shorthand-properties': '^7.22.5',
      '@babel/plugin-transform-template-literals': '^7.22.5',
      '@config-plugins/react-native-google-cast': '^6.0.0',
      '@expo/dev-server': '^0.5.5',
      '@fullstory/react-native': '^1.3.0',
      '@gorhom/portal': '^1.0.14',
      '@lifeway/expo-brightcove-player': '*',
      '@lifeway/ui': '*',
      '@react-native-async-storage/async-storage': '1.18.2',
      '@react-native-community/netinfo': '9.3.10',
      '@react-navigation/bottom-tabs': '^6.5.5',
      '@react-navigation/native': '^6.1.4',
      '@react-navigation/native-stack': '^6.9.10',
      'aws-appsync-auth-link': '^3.0.7',
      'aws-appsync-subscription-link': '^3.0.11',
      dotenv: '16.0.3',
      expo: '~49.0.20',
      'expo-application': '~5.3.0',
      'expo-auth-session': '~5.0.2',
      'expo-build-properties': '~0.8.3',
      'expo-dev-client': '~2.4.11',
      'expo-device': '~5.4.0',
      'expo-font': '~11.4.0',
      'expo-haptics': '~12.4.0',
      'expo-navigation-bar': '~2.3.0',
      'expo-random': '~13.2.0',
      'expo-screen-orientation': '~6.0.6',
      'expo-secure-store': '~12.3.1',
      'expo-splash-screen': '~0.20.5',
      'expo-status-bar': '~1.6.0',
      'expo-updates': '~0.18.17',
      'expo-web-browser': '~12.3.2',
      graphql: '^16.5.0',
      'graphql-request': '^4.3.0',
      'jwt-decode': '^3.1.2',
      'lottie-react': '^2.4.0',
      'lottie-react-native': '5.1.6',
      react: '18.2.0',
      'react-airplay': '^1.2.0',
      'react-dom': '18.2.0',
      'react-native': '~0.72.6',
      'react-native-dotenv': '^3.4.8',
      'react-native-error-boundary': '^1.2.1',
      'react-native-gesture-handler': '~2.12.0',
      'react-native-google-cast': '^4.6.2',
      'react-native-media-controls': '^2.3.0',
      'react-native-pager-view': '6.2.0',
      'react-native-reanimated': '~3.3.0',
      'react-native-safe-area-context': '4.6.3',
      'react-native-screens': '~3.22.0',
      'react-native-svg': '13.9.0',
      'react-native-toast-message': '^2.1.6',
      'react-native-web': '~0.19.6',
      'sentry-expo': '~7.0.0',
      uuid: '^8.3.2'
    },
    devDependencies: {
      '@babel/core': '^7.23.2',
      '@babel/plugin-proposal-export-namespace-from': '^7.18.9',
      '@lifeway/graphql-schema': '*',
      '@testing-library/jest-native': '^5.0.0',
      '@testing-library/react-native': '^11.2.0',
      '@types/eslint': '^8.4.6',
      '@types/jest': '^29.1.1',
      '@types/node': '^18.11.18',
      '@types/react': '~18.2.14',
      '@types/react-native-dotenv': '^0.2.0',
      '@typescript-eslint/eslint-plugin': '^5.62.0',
      '@typescript-eslint/parser': '^5.62.0',
      eslint: '^8.17.0',
      'eslint-config-prettier': '^8.5.0',
      'eslint-plugin-import': '^2.26.0',
      'eslint-plugin-jest': '^27.1.0',
      'eslint-plugin-prettier': '^4.2.1',
      'eslint-plugin-react': '^7.31.8',
      'eslint-plugin-react-hooks': '^4.6.0',
      'eslint-plugin-react-native': '^4.0.0',
      'eslint-plugin-react-native-a11y': '^3.2.1',
      'eslint-plugin-testing-library': '^5.7.2',
      'is-ci-cli': '^2.2.0',
      jest: '^29.1.2',
      'jest-expo': '^49.0.0',
      'jest-watch-typeahead': '^2.2.0',
      msw: '^0.47.4',
      prettier: '^2.7.1',
      'ts-node': '^10.9.1',
      typescript: '^5.1.3'
    }
  },
  fs: { numberOfFiles: 257 },
  debug: [
    '2024-01-10T16:07:26.180Z project waiting for initial run signal\n',
    '2024-01-10T16:07:26.189Z config Attempting automatic configuration for angular\n',
    '2024-01-10T16:07:26.190Z angular/cli config Angular CLI not found.\n',
    '2024-01-10T16:07:26.190Z config Finished attempting automatic configuration for angular (1ms)\n',
    '2024-01-10T16:07:26.191Z config Attempting automatic configuration for jest\n',
    '2024-01-10T16:07:26.328Z jest/config Detected Jest.\n',
    '2024-01-10T16:07:26.328Z jest/config Configured Jest.\n',
    '2024-01-10T16:07:26.328Z config Finished attempting automatic configuration for jest (137ms)\n',
    '2024-01-10T16:07:26.329Z project Wallaby Node version: v18.15.0\n',
    '2024-01-10T16:07:26.329Z project Wallaby config: <homeDir>/wip/lifeway-discipleship/frontend/apps/mobile/auto.detect\n',
    '2024-01-10T16:07:26.355Z fs File system starting\n',
    '2024-01-10T16:07:26.395Z fs File system scan completed\n',
    '2024-01-10T16:07:26.399Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.371/projects/0340616f4e5c063b\n',
    '2024-01-10T16:07:26.460Z uiService Listening port 51235\n',
    '2024-01-10T16:07:26.473Z workers Parallelism for initial run: 8, for regular run: 4\n',
    '2024-01-10T16:07:26.473Z workers Starting run worker instance #0\n',
    '2024-01-10T16:07:26.473Z workers Starting run worker instance #1\n',
    '2024-01-10T16:07:26.473Z workers Starting run worker instance #2\n',
    '2024-01-10T16:07:26.473Z workers Starting run worker instance #3\n',
    '2024-01-10T16:07:26.473Z workers Starting run worker instance #4\n',
    '2024-01-10T16:07:26.473Z workers Starting run worker instance #5\n',
    '2024-01-10T16:07:26.473Z workers Starting run worker instance #6\n',
    '2024-01-10T16:07:26.473Z workers Starting run worker instance #7\n',
    '2024-01-10T16:07:26.473Z workers Web server is listening at 65510\n',
    '2024-01-10T16:07:26.478Z project Stopping process pool\n',
    '2024-01-10T16:07:26.478Z project File cache is up-to-date, starting full test run\n',
    '2024-01-10T16:07:26.480Z project Test run started; run priority: 3\n',
    '2024-01-10T16:07:26.480Z project Running all tests\n',
    '2024-01-10T16:07:26.483Z project Test run finished\n',
    '2024-01-10T16:07:26.483Z project Test run data re-queued\n',
    '2024-01-10T16:07:26.588Z workers Started run worker instance (delayed) #0\n',
    '2024-01-10T16:07:26.592Z workers Started run worker instance (delayed) #1\n',
    '2024-01-10T16:07:26.594Z workers Started run worker instance (delayed) #3\n',
    '2024-01-10T16:07:26.599Z workers Started run worker instance (delayed) #6\n',
    '2024-01-10T16:07:26.600Z workers Started run worker instance (delayed) #4\n',
    '2024-01-10T16:07:26.605Z workers Started run worker instance (delayed) #5\n',
    '2024-01-10T16:07:26.606Z workers Started run worker instance (delayed) #7\n',
    '2024-01-10T16:07:26.611Z workers Started run worker instance (delayed) #2\n',
    '2024-01-10T16:07:38.227Z project Requested to run all tests\n',
    '2024-01-10T16:07:38.228Z project Test run started; run priority: 3\n',
    '2024-01-10T16:07:38.228Z project Running all tests\n',
    '2024-01-10T16:07:38.231Z workers Starting test run, priority: 3\n',
    '2024-01-10T16:07:38.231Z nodeRunner Starting sandbox [worker #0, session #8ogek]\n',
    '2024-01-10T16:07:38.231Z nodeRunner Preparing sandbox [worker #0, session #8ogek]\n',
    '2024-01-10T16:07:38.231Z nodeRunner Prepared sandbox [worker #0, session #8ogek]\n',
    '2024-01-10T16:07:38.232Z workers [worker #0, session #8ogek] Running tests in sandbox\n',
    "2024-01-10T16:07:39.398Z workers 'Scheduling Jest Test Run (8ogek): 2024-01-10T16:07:38.432Z'\n",
    '2024-01-10T16:07:39.406Z workers Sandbox (active) [8ogek] error: Jest encountered an unexpected token\n' +
      '\n' +
      'Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.\n' +
      '\n' +
      'Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.\n' +
      '\n' +
      'By default "node_modules" folder is ignored by transformers.\n' +
      '\n' +
      "Here's what you can do:\n" +
      ' ‚Ä¢ If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.\n' +
      ' ‚Ä¢ If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript\n' +
      ' ‚Ä¢ To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.\n' +
      ' ‚Ä¢ If you need a custom transformation specify a "transform" option in your config.\n' +
      ' ‚Ä¢ If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.\n' +
      '\n' +
      "You'll find more details and examples of these config options in the docs:\n" +
      'https://jestjs.io/docs/configuration\n' +
      'For information about custom transformations, see:\n' +
      'https://jestjs.io/docs/code-transformation\n' +
      '\n' +
      'Details:\n' +
      '\n' +
      './node_modules/react-native/index.js:14\n' +
      "import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';\n" +
      '^^^^^^\n' +
      '\n' +
      'SyntaxError: Cannot use import statement outside a module\n' +
      '    at new Script (node:vm:100:7)\n' +
      '    at Runtime.createScriptFromCode (./node_modules/jest-runtime/build/index.js:1505:14)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1399:25)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:1022:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:882:12)\n' +
      '    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:1048:21)\n' +
      '    at Object.require (./node_modules/@testing-library/react-native/src/fireEvent.ts:2:1)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1439:24)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:1022:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:882:12)\n' +
      '    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:1048:21)\n' +
      '    at Object.require (./node_modules/@testing-library/react-native/src/pure.ts:3:1)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1439:24)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:1022:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:882:12)\n' +
      '    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:1048:21)\n' +
      '    at Object.require (./node_modules/@testing-library/react-native/src/index.ts:1:1)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1439:24)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:1022:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:882:12)\n' +
      '    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:1048:21)\n' +
      '    at Object.<anonymous> (./src/context/__tests__/useSessionDownload.spec.tsx:29:42)\n' +
      '    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1439:24)\n' +
      '    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:1022:12)\n' +
      '    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:882:12)\n' +
      '    at jestAdapter (./node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:77:13)\n' +
      '    at runTestInternal (./node_modules/jest-runner/build/runTest.js:367:16)\n' +
      '    at runTest (./node_modules/jest-runner/build/runTest.js:444:34)\n',
    '2024-01-10T16:07:39.407Z workers [8ogek] Run 0 test(s), skipped 0 test(s)\n',
    "2024-01-10T16:07:39.407Z workers 'Jest Test Run Complete (8ogek): 2024-01-10T16:07:39.395Z'\n",
    '2024-01-10T16:07:39.408Z workers [8ogek] Sandbox is responsive, closing it\n',
    '2024-01-10T16:07:39.409Z project Test run finished\n',
    '2024-01-10T16:07:39.409Z project Processed console.log entries\n',
    '2024-01-10T16:07:39.409Z project Processed loading sequences\n',
    '2024-01-10T16:07:39.409Z project Processed executed tests\n',
    '2024-01-10T16:07:39.411Z project Processed code coverage\n',
    '2024-01-10T16:07:39.422Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by ArtemGovorov** [comment]
Hi,

there are a couple of different issues with your configuration.

- your Wallaby config file has an incorrect (legacy) format, but it's not even relevant because according to the supplied log it is not even being used at all (to select an active config you need to use `Wallaby.js: Select Configuration` command).
- the `Can't use import statement outside a module` error occurs because Wallaby uses default Jest config and correct `transformIgnorePatterns` value is missing to load some of ESM node modules (`react-native` in case of this error). In order to make Wallaby automatic config work, you'll need to let it know where your Jest config is located. 
-  
As I can see from your Wallaby config file, you are trying to load it from `<homeDir>/wip/lifeway-discipleship/frontend/apps/mobile/.jest/config.ts`. If your Jest config is indeed there, then all you need to do is to modify your Wallaby config as follows to [override automatic configuration](https://wallabyjs.com/docs/integration/jest.html#overriding-automatic-configuration):

**wallaby.config.js**
```
module.exports = () => {
  return {
    testFramework: {
      // the jest configuration file path
      // (relative to project root)
      configFile: './.jest/config.ts'
    }
  }
};
```

and run Wallaby `Select Configuration` command in VS Code to select the config file. After this, all tests in the project should run. You may then stop Wallaby at any time and start it with `Smart Start` to only run opened/selected test files.

Please let us know if the above provided solution addresses the issue. If it doesn't, please share:
- an updated Diagnostics report, 
- your Jest config with its location relative to the project's root,
- command/script that you are using to run tests in the project without Wallaby.

**Comment by chancesmith** [comment]
Yes, that worked great. I copied your much simpler config, and I am ashamed to say I didn't have the right path to my config (`<homeDir>/wip/lifeway-discipleship/frontend/apps/mobile/.jest/spec👈/config.ts`), but _then_ it worked.

No more wobbly Wallaby.

Thank you @ArtemGovorov. I'm up and running, thanks to you.
