### ISSUE TITLE
Automatic Vitest configuration error: Vitest dependency not found.

### ISSUE THREAD

**Issue by phenry20** [wallabyjs/public#3322]
### Issue description or question

I'm trying to get vitest to work, but I keep getting the error:

```
wallaby.js started
2024-01-19T19:47:27.217Z project waiting for initial run signal
2024-01-19T19:47:27.226Z config Attempting automatic configuration for vitest
core v1.0.1520
2024-01-19T19:47:27.227Z vitest/config Error: Vitest dependency not found.
    at Object.r.configure (/Users/peterhenry/Library/Caches/JetBrains/WebStorm2023.2/wallaby/wallaby/server.js:197:1603)
    at automaticConfigurationProviders.reduce.Promise.resolve.success (/Users/peterhenry/Library/Caches/JetBrains/WebStorm2023.2/wallaby/wallaby/server.js:144:12277)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Config.load (/Users/peterhenry/Library/Caches/JetBrains/WebStorm2023.2/wallaby/wallaby/server.js:144:12094)
2024-01-19T19:47:27.228Z config Finished attempting automatic configuration for vitest (2ms)
Failed to load configuration file: Automatic Vitest configuration error: Vitest dependency not found.
Please refer to our docs: https://wallabyjs.com/docs/config/overview.html 
```

I'm using the latest version of Webstorm and on the latest version of vitest and Wallaby. 

wallaby.cjs
```
module.exports = () => ({
    autoDetect: ['vitest'],
    debug: true,
});
```

vitest.config.ts
```
import { defineConfig } from "vitest/config";
export default defineConfig({
    test: {
        include: ["**/*.test.ts", "**/*.test.tsx"],
    },
});
```

I also tested my files using the command line and it runs fine. It just fails to run on Wallaby.

**Comment by smcenlly** [comment]
Wallaby with Vitest is working for us; we think there might be something specific to your project that's causing a problem.

Can you please try using [this sample repository](https://github.com/wallabyjs/wallaby-3322) that we created for you and see if it works for you? After cloning the repo, you'll need to install dependencies with `npm install`.

If the sample project works for you, please compare it against your project, that might help you determine why your project is not working.

If the sample project does not work for you, please check that you are using `Node >=v18.00`.

If you're still having problems, can you please update the sample project so that it breaks in the same way, or else provide us with another repo that has the same problem that you're experiencing?

**Comment by phenry20** [comment]
For some reason my system default node version was set to version 14. I upgraded to v20 and all is well. Thanks for the support
