### ISSUE TITLE
Failed to work with vitest workspace in a mix jest/vitest yarn workspaces project

### ISSUE THREAD

**Issue by tzafrir-benami-sage** [wallabyjs/public#3346]
### Issue description or question

We have a yarn workspaces project, where some workspaces tests are written with jest and some workspaces tests are written with vitest (React frontend app).

Wallaby plugin is working as expected with the `Jest` workspaces, but fail to load with `Vitest` workspaces. 

Attached is our diagnostics report. Note that we have no Angular in our project also report does indicate angular for some reason

**Comment by tzafrir-benami-sage** [comment]
Our diagnostics report:

```
{
  editorVersion: '1.87.2',
  pluginVersion: '1.0.374',
  editorType: 'VSCode',
  osVersion: 'darwin 23.3.0',
  nodeVersion: 'v20.11.0',
  coreVersion: '1.0.1544',
  checksum: 'YzEzODJiMDU5MWI4MDNiZjA3ZmFkMGZkOGI5NjIzMWEsMTcyNDgwMzIwMDAwMCww',
  config: { tests: [], files: [] },
  packageJSON: {
    dependencies: {
      '@ag-grid-community/client-side-row-model': '31.1.1',
      '@ag-grid-community/core': '31.1.1',
      '@ag-grid-community/react': '31.1.1',
      '@ag-grid-community/styles': '31.1.1',
      '@ag-grid-enterprise/clipboard': '31.1.1',
      '@ag-grid-enterprise/menu': '31.1.1',
      '@ag-grid-enterprise/range-selection': '31.1.1',
      '@ag-grid-enterprise/row-grouping': '31.1.1',
      '@ag-grid-enterprise/server-side-row-model': '31.1.1',
      '@dagrejs/graphlib': '^2.1.13',
      '@hookform/error-message': '^2.0.1',
      '@lexical/react': '^0.13.1',
      '@mui/icons-material': '^5.15.13',
      '@mui/material': '^5.15.13',
      '@mui/styled-engine-sc': '^6.0.0-alpha.17',
      '@mui/system': '^5.15.13',
      '@mui/utils': '^5.15.13',
      '@mui/x-date-pickers': '^6.19.6',
      '@radix-ui/react-slot': '^1.0.2',
      '@sage/design-tokens': '^4.34.0',
      'autosuggest-highlight': '^3.3.4',
      clsx: '^2.1.0',
      dayjs: '^1.11.10',
      dexie: '^3.2.6',
      'dexie-react-hooks': '^1.1.7',
      'js-md5': '^0.7.3',
      lexical: '^0.13.1',
      'material-ui-popup-state': '^5.0.10',
      'ohm-js': '^17.1.0',
      react: '~18.2.0',
      'react-dom': '~18.2.0',
      'react-hook-form': '^7.51.0',
      'react-router-dom': '^6.22.3',
      'react-toastify': '^10.0.4',
      rxdb: '^15.11.1',
      rxjs: '^7.8.1',
      sass: '^1.72.0',
      'styled-components': '^6.1.8',
      'tailwind-merge': '^2.2.1',
      'vite-plugin-svgr': '^4.2.0',
      'vite-tsconfig-paths': '^4.3.2'
    },
    devDependencies: {
      '@babel/core': '^7.24.0',
      '@babel/preset-env': '^7.24.0',
      '@babel/preset-react': '^7.23.3',
      '@babel/preset-typescript': '^7.23.3',
      '@emotion/react': '^11.11.4',
      '@emotion/styled': '^11.11.0',
      '@faker-js/faker': '^8.4.1',
      '@juggle/resize-observer': '^3.4.0',
      '@mui/styled-engine': '^5.15.11',
      '@nx/vite': '18.0.8',
      '@playwright/test': '1.39.0',
      '@remix-run/router': '^1.15.3',
      '@shared/types': '*',
      '@storybook/addon-essentials': '^8.0.0',
      '@storybook/addon-interactions': '^8.0.0',
      '@storybook/react': '^8.0.0',
      '@storybook/react-vite': '^8.0.0',
      '@tailwindcss/nesting': '^0.0.0-insiders.565cd3e',
      '@testing-library/dom': '^9.3.4',
      '@testing-library/react': '^14.2.1',
      '@testing-library/user-event': '^14.5.2',
      '@types/autosuggest-highlight': '^3.2.3',
      '@types/eslint': '^8.56.5',
      '@types/js-md5': '^0.7.2',
      '@types/node': '^20.11.27',
      '@types/react': '^18.2.65',
      '@types/react-dom': '^18.2.22',
      '@types/react-refresh': '^0.14.5',
      '@types/styled-components': '^5.1.34',
      '@vitejs/plugin-react': '^4.2.1',
      '@vitest/coverage-v8': '^1.2.0',
      autoprefixer: '^10.4.18',
      'babel-plugin-transform-vite-meta-env': '^1.0.3',
      eslint: '^8.55.0',
      'eslint-plugin-react-refresh': '^0.4.4',
      'identity-obj-proxy': '^3.0.0',
      jsdom: '^23.0.1',
      msw: '^2.2.3',
      postcss: '^8.4.35',
      'postcss-import': '^16.0.1',
      'postcss-scss': '^4.0.9',
      'react-is': '^18.2.0',
      'react-refresh': '^0.14.0',
      'tailwind-config-viewer': '^1.7.3',
      tailwindcss: '^3.4.1',
      typescript: '^5.1.6',
      vite: '^5.1.6',
      'vite-node': '1.3.1',
      'vite-plugin-eslint': '^1.8.1',
      'vite-raw-plugin': '^1.0.2',
      vitest: '^1.3.1',
      'vitest-dom': '^0.1.1'
    }
  },
  fs: { numberOfFiles: 0 },
  debug: [
    '2024-03-19T04:25:44.061Z project waiting for initial run signal\n',
    '2024-03-19T04:25:44.068Z config Attempting automatic configuration for angular\n',
    '2024-03-19T04:25:44.223Z angular/cli config Detected Angular CLI.\n',
    '2024-03-19T04:25:44.223Z angular/cli config Error: Cannot detect @nx/workspace package version, is the package installed?\n' +
      '    at t.configure (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:156:16856)\n' +
      '    at async automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:144:12269)\n' +
      '    at async automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:144:12154)\n' +
      '    at async automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:144:12154)\n' +
      '    at async Config.load (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:144:12094)\n',
    '2024-03-19T04:25:44.227Z angular/cli config Angular.json: \n' +
      ' {\n' +
      '  projects: {\n' +
      "    'xpna-proxy-extension': {\n" +
      "      root: 'devops/dev-experience/xpna-proxy-extension',\n" +
      '      targets: {\n' +
      "        build: { executor: 'nx:run-script', dependsOn: [ '^build' ], cache: true, options: { script: 'build' }, configurations: {} },\n" +
      "        start: { executor: 'nx:run-script', options: { script: 'start' }, configurations: {} },\n" +
      "        eject: { executor: 'nx:run-script', options: { script: 'eject' }, configurations: {} },\n" +
      "        'nx-release-publish': { dependsOn: [ '^nx-release-publish' ], executor: '@nx/js:release-publish', options: {}, configurations: {} }\n" +
      '      },\n' +
      "      sourceRoot: 'devops/dev-experience/xpna-proxy-extension',\n" +
      "      name: 'xpna-proxy-extension',\n" +
      "      projectType: 'library',\n" +
      '      implicitDependencies: [],\n' +
      '      tags: []\n' +
      '    },\n' +
      "    '@sibp/xpna-budget-generator': {\n" +
      "      root: 'services/apps/xpna-budget-generator',\n" +
      "      name: '@sibp/xpna-budget-generator',\n" +
      '      targets: {\n' +
      "        build: { executor: 'nx:run-script', dependsOn: [ '^build' ], cache: true, options: { script: 'build' }, configurations: {} },\n" +
      "        clean: { executor: 'nx:run-script', options: { script: 'clean' }, configurations: {} },\n" +
      "        test: { executor: 'nx:run-script', options: { script: 'test' }, configurations: {}, builder: 'nx:run-script' },\n" +
      "        'test:unit': { executor: 'nx:run-script', options: { script: 'test:unit' }, configurations: {} },\n" +
      "        'test:unit:ci': { executor: 'nx:run-script', options: { script: 'test:unit:ci' }, configurations: {} },\n" +
      "        start: { executor: 'nx:run-script', options: { script: 'start' }, configurations: {} },\n" +
      "        'start:server': { executor: 'nx:run-script', options: { script: 'start:server' }, configurations: {} },\n" +
      "        'publish:setCurrentVersion': { executor: 'nx:run-script', options: { script: 'publish:setCurrentVersion' }, configurations: {} },\n" +
      "        'publish:setReleaseVersion': { executor: 'nx:run-script', options: { script: 'publish:setReleaseVersion' }, configurations: {} },\n" +
      "        'publish:publish': { executor: 'nx:run-script', options: { script: 'publish:publish' }, configurations: {} },\n" +
      "        'nx-release-publish': { dependsOn: [ '^nx-release-publish' ], executor: '@nx/js:release-publish', options: {}, configurations: {} }\n" +
      '      },\n' +
      "      sourceRoot: 'services/apps/xpna-budget-generator',\n" +
      "      projectType: 'library',\n" +
      "      implicitDependencies: [ '@sibp/devops-resources' ],\n" +
      '      tags: [],\n' +
      '      architect: {\n' +
      "        build: { executor: 'nx:run-script', dependsOn: [ '^build' ], cache: true, options: { script: 'build' }, configurations: {} },\n" +
      "        clean: { executor: 'nx:run-script', options: { script: 'clean' }, configurations: {} },\n" +
      "        test: { executor: 'nx:run-script', options: { script: 'test' }, configurations: {}, builder: 'nx:run-script' },\n" +
      "        'test:unit': { executor: 'nx:run-script', options: { script: 'test:unit' }, configurations: {} },\n" +
      "        'test:unit:ci': { executor: 'nx:run-script', options: { script: 'test:unit:ci' }, configurations: {} },\n" +
      "        start: { executor: 'nx:run-script', options: { script: 'start' }, configurations: {} },\n" +
      "        'start:server': { executor: 'nx:run-script', options: { script: 'start:server' }, configurations: {} },\n" +
      "        'publish:setCurrentVersion': { executor: 'nx:run-script', options: { script: 'publish:setCurrentVersion' }, configurations: {} },\n" +
      "        'publish:setReleaseVersion': { executor: 'nx:run-script', options: { script: 'publish:setReleaseVersion' }, configurations: {} },\n" +
      "        'publish:publish': { executor: 'nx:run-script', options: { script: 'publish:publish' }, configurations: {} },\n" +
      "        'nx-release-publish': { dependsOn: [ '^nx-release-publish' ], executor: '@nx/js:release-publish', options: {}, configurations: {} }\n" +
      '      }\n' +
      '    },\n' +
      "    '@sibp/generate-xpna-budget': {\n" +
      "      root: 'services/apps/generate-xpna-budget',\n" +
      "      name: '@sibp/generate-xpna-budget',\n" +
      '      targets: {\n' +
      "        build: { executor: 'nx:run-script', dependsOn: [ '^build' ], cache: true, options: { script: 'build' }, configurations: {} },\n" +
      "        clean: { executor: 'nx:run-script', options: { script: 'clean' }, configurations: {} },\n" +
      "        test: { executor: 'nx:run-script', options: { script: 'test' }, configurations: {}, builder: 'nx:run-script' },\n" +
      "        'test:unit': { executor: 'nx:run-script', options: { script: 'test:unit' }, configurations: {} },\n" +
      "        'test:unit:ci': { executor: 'nx:run-script', options: { script: 'test:unit:ci' }, configurations: {} },\n" +
      "        start: { executor: 'nx:run-script', options: { script: 'start' }, configurations: {} },\n" +
      "        'start:server': { executor: 'nx:run-script', options: { script: 'start:server' }, configurations: {} },\n" +
      "        'publish:setCurrentVersion': { executor: 'nx:run-script', options: { script: 'publish:setCurrentVersion' }, configurations: {} },\n" +
      "        'publish:setReleaseVersion': { executor: 'nx:run-script', options: { script: 'publish:setReleaseVersion' }, configurations: {} },\n" +
      "        'publish:publish': { executor: 'nx:run-script', options: { script: 'publish:publish' }, configurations: {} },\n" +
      "        'nx-release-publish': { dependsOn: [ '^nx-release-publish' ], executor: '@nx/js:release-publish', options: {}, configurations: {} }\n" +
      '      },\n' +
      "      sourceRoot: 'services/apps/generate-xpna-budget',\n" +
      "      projectType: 'library',\n" +
      "      implicitDependencies: [ '@sibp/devops-resources' ],\n" +
      '      tags: [],\n' +
      '      architect: {\n' +
      "        build: { executor: 'nx:run-script', dependsOn: [ '^build' ], cache: true, options: { script: 'build' }, configurations: {} },\n" +
      "        clean: { executor: 'nx:run-script', options: { script: 'clean' }, configurations: {} },\n" +
      "        test: { executor: 'nx:run-script', options: { script: 'test' }, configurations: {}, builder: 'nx:run-script' },\n" +
      "        'test:unit': { executor: 'nx:run-script', options: { script: 'test:unit' }, configurations: {} },\n" +
      "        'test:unit:ci': { executor: 'nx:run-script', options: { script: 'test:unit:ci' }, configurations: {} },\n" +
      "        start: { executor: 'nx:run-script', options: { script: 'start' }, configurations: {} },\n" +
      "        'start:server': { executor: 'nx:run-script', options: { script: 'start:server' }, configurations: {} },\n" +
      "        'publish:setCurrentVersion': { executor: 'nx:run-script', options: { script: 'publish:setCurrentVersion' }, configurations: {} },\n" +
      "        'publish:setReleaseVersion': { executor: 'nx:run-script', options: { script: 'publish:setReleaseVersion' }, configurations: {} },\n" +
      "        'publish:publish': { executor: 'nx:run-script', options: { script: 'publish:publish' }, configurations: {} },\n" +
      "        'nx-release-publish': { dependsOn: [ '^nx-release-publish' ], executor: '@nx/js:release-publish', options: {}, configurations: {} }\n" +
      '      }\n' +
      '    },\n' +
      "    '@sibp/plans-down-stream': {\n" +
      "      root: 'services/apps/plans-down-stream',\n" +
      "      name: '@sibp/plans-down-stream',\n" +
      '      targets: {\n' +
      "        build: { executor: 'nx:run-script', dependsOn: [ '^build' ], cache: true, options: { script: 'build' }, configurations: {} },\n" +
      "        clean: { executor: 'nx:run-script', options: { script: 'clean' }, configurations: {} },\n" +
      "        start: { executor: 'nx:run-script', options: { script: 'start' }, configurations: {} },\n" +
      "        test: { executor: 'nx:run-script', options: { script: 'test' }, configurations: {}, builder: 'nx:run-script' },\n" +
      "        'test:unit': { executor: 'nx:run-script', options: { script: 'test:unit' }, configurations: {} },\n" +
      "        'test:unit:ci': { executor: 'nx:run-script', options: { script: 'test:unit:ci' }, configurations: {} },\n" +
      "        'start:server': { executor: 'nx:run-script', options: { script: 'start:server' }, configurations: {} },\n" +
      "        'publish:setCurrentVersion': { executor: 'nx:run-script', options: { script: 'publish:setCurrentVersion' }, configurations: {} },\n" +
      "        'publish:setReleaseVersion': { executor: 'nx:run-script', options: { script: 'publish:setReleaseVersion' }, configurations: {} },\n" +
      "        'publish:publish': { executor: 'nx:run-script', options: { script: 'publish:publish' }, configurations: {} },\n" +
      "        'nx-release-publish': { dependsOn: [ '^nx-release-publish' ], executor: '@nx/js:release-publish', options: {}, configurations: {} }\n" +
      '      },\n' +
      "      sourceRoot: 'services/apps/plans-down-stream',\n" +
      "      projectType: 'library',\n" +
      "      implicitDependencies: [ '@sibp/devops-resources' ],\n" +
      '      tags: [],\n' +
      '      architect: {\n' +
      "        build: { executor: 'nx:run-script', dependsOn: [ '^build' ], cache: true, options: { script: 'build' }, configurations: {} },\n" +
      "        clean: { executor: 'nx:run-script', options: { script: 'clean' }, configurations: {} },\n" +
      "        start: { executor: 'nx:run-script', options: { script: 'start' }, configurations: {} },\n" +
      "        test: { executor: 'nx:run-script', options: { script: 'test' }, configurations: {}, builder: 'nx:run-script' },\n" +
      "        'test:unit': { executor: 'nx:run-script', options: { script: 'test:unit' }, configurations: {} },\n" +
      "        'test:unit:ci': { executor: 'nx:run-script', options: { script: 'test:unit:ci' }, configurations: {} },\n" +
      "        'start:server': { executor: 'nx:run-script', options: { script: 'start:server' }, configurations: {} },\n" +
      "        'publish:setCurrentVersion': { executor: 'nx:run-script', options: { script: 'publish:setCurrentVersion' }, configurations: {} },\n" +
      "        'publish:setReleaseVersion': { executor: 'nx:run-script', options: { script: 'publish:setReleaseVersion' }, configurations: {} },\n" +
      "        'publish:publish': { executor: 'nx:run-script', options: { script: 'publish:publish' }, configurations: {} },\n" +
      "        'nx-release-publish': { dependsOn: [ '^nx-release-publish' ], executor: '@nx/js:release-publish', options: {}, configurations: {} }\n" +
      '      }\n' +
      '    },\n' +
      "    '@sibp/import-sif-data': {\n" +
      "      root: 'services/apps/import-sif-data',\n" +
      "      name: '@sibp/import-sif-data',\n" +
      '      targets: {\n' +
      "        build: { executor: 'nx:run-script', dependsOn: [ '^build' ], cache: true, options: { script: 'build' }, configurations: {} },\n"... 42952 more characters,
    '2024-03-19T04:25:44.227Z angular/cli config Error: Cannot detect @nx/workspace package version, is the package installed?\n' +
      '    at t.configure (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:156:16856)\n' +
      '    at async automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:144:12269)\n' +
      '    at async automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:144:12154)\n' +
      '    at async automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:144:12154)\n' +
      '    at async Config.load (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:144:12094)\n',
    '2024-03-19T04:25:44.227Z config Finished attempting automatic configuration for angular (159ms)\n',
    '2024-03-19T04:25:44.227Z config Attempting automatic configuration for jest\n',
    "2024-03-19T04:25:44.228Z jest/config Error: Module jest-cli is not found in '<homeDir>/Documents/work/xPnA/frontend/app'.\n" +
      '    at Object.loadJest (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:508:1070)\n' +
      '    at i (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:196:24792)\n' +
      '    at r.configure (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:196:28093)\n' +
      '    at automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:144:12277)\n' +
      '    at async automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:144:12154)\n' +
      '    at async Config.load (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:144:12094)\n',
    '2024-03-19T04:25:44.228Z config Finished attempting automatic configuration for jest (1ms)\n',
    '2024-03-19T04:25:44.228Z config Attempting automatic configuration for vitest\n',
    '2024-03-19T04:25:44.231Z vitest/config Detected Vitest (1.3.1).\n',
    "2024-03-19T04:25:44.423Z vitest/config Error: Cannot find module '<homeDir>/Documents/work/xPnA/.yarn/__virtual__/vitest-virtual-edbceba055/0/cache/vitest-npm-1.3.1-f654c79bcc-41a8405d65.zip/node_modules/vitest/dist/vendor/cac.wWT9ELdg.js' imported from <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js\n" +
      'Did you mean to import <homeDir>/Documents/work/xPnA/.yarn/__virtual__/vitest-virtual-edbceba055/0/cache/vitest-npm-1.3.1-f654c79bcc-41a8405d65.zip/node_modules/vitest/dist/vendor/cac.wWT9ELdg.js?\n' +
      '    at r.configure (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:197:3160)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:144:12269)\n' +
      '    at async Config.load (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.374/wallabybb1443/server.js:144:12094)\n',
    '2024-03-19T04:25:44.423Z config Finished attempting automatic configuration for vitest (195ms)\n'
  ]
}
```

**Comment by smcenlly** [comment]
> Note that we have no Angular in our project also report does indicate angular for some reason

Wallaby has detected `nx` workspace artefacts in your project and is attempting to configure your NX project tests. NX workspaces actually started as a special type of Angular-schema projects, which is why Wallaby is reporting Angular, but it's really NX.

> Wallaby plugin is working as expected with the Jest workspaces, but fail to load with Vitest workspaces.

Am I right in saying that you are using the `Wallaby.js: Select Configuration` option and selecting a specific project to run on? And in this case, `jest` is working, but `vitest` is not?

From your diagnostics report, it looks like Wallaby is running on `<homeDir>/Documents/work/xPnA/frontend/app` while your workspace root is `<homeDir>/Documents/work/xPnA/`. Is that correct?

**Comment by smcenlly** [comment]
We've set up a sample project with the structure that we suggested you had and it's not working for us.

We're investigating and will let you know when we have an update.

**Comment by smcenlly** [comment]
We've identified and fixed a problem with Wallaby when using vitest in nested yarn2 mono-repos.

Please update to Wallaby core `v1.0.1545`, it should fix your problem.
