### ISSUE TITLE
An error occurred while processing Wallaby output

### ISSUE THREAD

**Issue by EdwardSalter** [wallabyjs/public#3382]
### Issue description or question

When attempting to start Wallaby in any project within Webstorm, I am receiving an error popup in Webstorm stating that An error occurred while processing Wallaby output.
The Wallaby console only has the following output when run with no tracing enabled and automatic configuration enabled:
```
wallaby.js started
core v1.0.1575
```

and with a config file that turns on debug and tracing:
```
wallaby.js started
2024-07-01T21:54:12.673Z project waiting for initial run signal
2024-07-01T21:54:12.678Z model Initialization Completed: 229ms
2024-07-01T21:54:12.683Z config Attempting automatic configuration for angular
core v1.0.1575
2024-07-01T21:54:12.683Z angular/cli config Detecting Angular CLI.
2024-07-01T21:54:12.685Z angular/cli config Angular CLI not found.
2024-07-01T21:54:12.685Z config Finished attempting automatic configuration for angular (2ms)
2024-07-01T21:54:12.685Z config Attempting automatic configuration for jest
2024-07-01T21:54:12.685Z jest/config Detecting Jest.
2024-07-01T21:54:12.786Z jest/config Detected Jest.
2024-07-01T21:54:12.786Z jest/config Configured Jest.
2024-07-01T21:54:12.787Z config Finished attempting automatic configuration for jest (102ms)
2024-07-01T21:54:12.788Z project Wallaby Node version: v20.12.2
2024-07-01T21:54:12.788Z project Wallaby config: W:\git\Automation.UI - Copy\wallaby.config.js
2024-07-01T21:54:12.825Z fs File system starting
2024-07-01T21:54:12.839Z fs File added: .gitignore
2024-07-01T21:54:12.840Z fs File added: codealike.json
2024-07-01T21:54:12.840Z fs File added: package.json
2024-07-01T21:54:12.840Z fs File added: vite.config.ts
2024-07-01T21:54:12.841Z fs File added: wallaby.config.js
2024-07-01T21:54:12.841Z fs File added: yarn.lock
2024-07-01T21:54:12.843Z fs File added: src/App.test.tsx
2024-07-01T21:54:12.844Z fs File added: src/App.tsx
2024-07-01T21:54:12.844Z fs File added: src/vite-env.d.ts
2024-07-01T21:54:12.858Z fs File system scan completed
2024-07-01T21:54:12.865Z project File cache: C:\Users\Edwar\AppData\Local\JetBrains\WebStorm2024.1\wallaby\projects\f583899a96bf4c08
2024-07-01T21:54:12.966Z ui.service.legacy Listening port 51235
2024-07-01T21:54:12.969Z project package.json file change detected, invalidating local cache
```

I have tried with both vitest and jest with the same results - I get the error in the IDE and then nothing further seems to occur within Wallaby itself.

I have found the following error in the IDE log file which could possibly be the cause of this issue:
```
2024-07-01 22:43:56,016 [  22726]   INFO - Wallaby - Connecting to Wallaby Runtime (1): [ws://localhost:59440]
2024-07-01 22:43:56,021 [  22731]   INFO - STDERR - SLF4J: A SLF4J service provider failed to instantiate:
2024-07-01 22:43:56,021 [  22731]   INFO - STDERR - org.slf4j.spi.SLF4JServiceProvider: org.slf4j.jul.JULServiceProvider not a subtype
2024-07-01 22:43:56,829 [  23539]   WARN - Wallaby - 'other' has different root
java.lang.IllegalArgumentException: 'other' has different root
	at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:404)
	at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:42)
	at com.wallaby.javascript.b.a.a(Unknown Source)
	at com.wallaby.javascript.WallabyController.a(Unknown Source)
	at com.wallaby.javascript.i.a(Unknown Source)
	at com.wallaby.javascript.i.b(Unknown Source)
	at com.wallaby.javascript.WallabyController.a(Unknown Source)
	at com.wallaby.javascript.extendedCore.Client$d.a(Unknown Source)
	at com.wallaby.javascript.extendedCore.Client$d.a(Unknown Source)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:302)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:299)
	at com.intellij.util.concurrency.QueueProcessor.lambda$wrappingProcessor$0(QueueProcessor.java:84)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:253)
	at com.intellij.util.concurrency.QueueProcessor.lambda$wrappingProcessor$1(QueueProcessor.java:84)
	at com.intellij.util.concurrency.QueueProcessor.lambda$startProcessing$3(QueueProcessor.java:227)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:253)
	at com.intellij.util.concurrency.QueueProcessor.lambda$startProcessing$4(QueueProcessor.java:227)
	at com.intellij.util.concurrency.AppJavaExecutorUtil$executeOnPooledIoThread$1$1.invoke(executor.kt:23)
	at com.intellij.util.concurrency.AppJavaExecutorUtil$executeOnPooledIoThread$1$1.invoke(executor.kt:23)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:320)
	at com.intellij.openapi.progress.CoroutinesKt.access$blockingContextInner(coroutines.kt:1)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:197)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:196)
	at com.intellij.util.concurrency.AppJavaExecutorUtil$executeOnPooledIoThread$1.invokeSuspend(executor.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

A quick Google of this error hints that the relativize function is being called with paths that are on different disks which could potentially the issue in my particular use-case.
My machine is setup to use a [Windows Dev Drive](https://learn.microsoft.com/en-us/windows/dev-drive/) where all of my repositories are located including my yarn/npm package cache directories. This is a different drive to my Webstorm installation directory.

Notes:
This is occurring in WebStorm 2024.1.5 using Wallaby Plugin 1.0.290 and Wallaby Core 1.0.1575. I have also tried downgrading to Wallaby Plugin 1.0.285 with the same results.

Edit:
I have also just trialled moving my minimal project from my dev drive on to my system drive. This seems to stop the above error occurring.

### Wallaby diagnostics report
Unable to generate one since the server fails to start.

**Comment by smcenlly** [comment]
We believe we have found and fixed the problem that was causing this error. Unfortunately we don't have a Windows environment with a a separate drive to easily test this.

Could you please update to the latest version of the Wallaby Plugin for IntelliJ, `v1.0.291`? It should work for you.

**Comment by EdwardSalter** [comment]
Hi @smcenlly,
I have updated the plugin this morning and can confirm that the issue is indeed fixed; many thanks.

I believe that you found, fixed and released the issue in less time than it took me to actually dig into the issue to figure out what exactly was causing it 🥇
