### ISSUE TITLE
Wallaby.js won't report on tests with vitest@2.0.4

### ISSUE THREAD

**Issue by holvi-sebastian** [wallabyjs/public#3385]
### Issue description or question

Using `vitest@2.0.4`, `wallaby` in `vscode` runs, but doesn't report on tests correctly.

In Output for `Wallaby.js Tests` the following error is reported:
```
Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match. 
```

Running `vitest --run` passes the tests without problem.

### Wallaby diagnostics report

```
{
  editorVersion: '1.91.1',
  pluginVersion: '1.0.379',
  editorType: 'VSCode',
  osVersion: 'darwin 23.5.0',
  nodeVersion: 'v20.11.0',
  coreVersion: '1.0.1586',
  pnp: '<not set>',
  pnpEsm: '<not set>',
  checksum: 'YmY0OTlmNzc1YmQ4MmQzYzA3ZjkzODU2YWIxODVjN2IsMTc0MzQ2NTYwMDAwMCww',
  config: {
    diagnostics: {
      vitest: {
        config: {
          config: {
            allowOnly: true,
            isolate: true,
            watch: true,
            globals: false,
            environment: 'node',
            pool: 'forks',
            clearMocks: false,
            restoreMocks: false,
            mockReset: false,
            include: [ '**/*.{test,spec}.?(c|m)[jt]s?(x)' ],
            exclude: [
              '**/node_modules/**',
              '**/dist/**',
              '**/cypress/**',
              '**/.{idea,git,cache,output,temp}/**',
              '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
            ],
            teardownTimeout: 10000,
            forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**' ],
            update: false,
            reporters: [ [ 'default', {} ] ],
            silent: false,
            hideSkippedTests: false,
            api: { middlewareMode: true },
            ui: false,
            uiBase: '/__vitest__/',
            open: true,
            css: { include: [], modules: { classNameStrategy: 'stable' } },
            coverage: {
              provider: 'v8',
              enabled: false,
              all: true,
              clean: true,
              cleanOnRerun: true,
              reportsDirectory: './coverage',
              exclude: [
                'coverage/**',
                'dist/**',
                '**/node_modules/**',
                '**/[.]**',
                'packages/*/test?(s)/**',
                '**/*.d.ts',
                '**/virtual:*',
                '**/__x00__*',
                '**/\x00*',
                'cypress/**',
                'test?(s)/**',
                'test?(-*).?(c|m)[jt]s?(x)',
                '**/*{.,-}{test,spec,bench,benchmark}?(-d).?(c|m)[jt]s?(x)',
                '**/__tests__/**',
                '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
                '**/vitest.{workspace,projects}.[jt]s?(on)',
                '**/.{eslint,mocha,prettier}rc.{?(c|m)js,yml}'
              ],
              reportOnFailure: false,
              reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
              extension: [
                '.js',     '.cjs',
                '.mjs',    '.ts',
                '.mts',    '.tsx',
                '.jsx',    '.vue',
                '.svelte', '.marko'
              ],
              allowExternal: false,
              ignoreEmptyLines: true,
              processingConcurrency: 12
            },
            fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
            maxConcurrency: 5,
            dangerouslyIgnoreUnhandledErrors: false,
            typecheck: {
              checker: 'tsc',
              include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
              exclude: [
                '**/node_modules/**',
                '**/dist/**',
                '**/cypress/**',
                '**/.{idea,git,cache,output,temp}/**',
                '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
              ],
              enabled: false
            },
            slowTestThreshold: 300,
            disableConsoleIntercept: false,
            poolOptions: { threads: {}, forks: {} },
            defines: {},
            root: '<homeDir>/holvi/dev-env/libs/e2e',
            mode: 'test',
            inspector: { enabled: false, waitForDebugger: false },
            clearScreen: true,
            browser: { enabled: false, headless: false, isolate: true, fileParallelism: true, ui: true, screenshotFailures: false, viewport: { width: 414, height: 896 }, api: { port: 63315 } },
            fileParallelism: true,
            expect: {},
            deps: {
              moduleDirectories: [ '/node_modules/' ],
              optimizer: { ssr: { enabled: true }, web: { enabled: true } },
              web: { transformAssets: true, transformCss: true, transformGlobPattern: [] }
            },
            server: { deps: { inline: [ {}, {}, {}, '@nuxt/test-utils' ], moduleDirectories: [ '/node_modules/' ], cacheDir: 'node_modules/.vite' } },
            snapshotOptions: { expand: false, snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
            snapshotSerializers: [],
            poolMatchGlobs: [],
            setupFiles: [],
            globalSetup: [],
            cache: { dir: '<homeDir>/holvi/dev-env/libs/e2e/node_modules/.vite/vitest' },
            sequence: { hooks: 'stack' },
            environmentMatchGlobs: [],
            testTransformMode: {},
            testTimeout: 5000,
            hookTimeout: 10000
          },
          projects: [
            {
              path: '<homeDir>/holvi/dev-env/libs/e2e',
              config: {
                allowOnly: true,
                isolate: true,
                watch: true,
                globals: false,
                environment: 'node',
                pool: 'forks',
                clearMocks: false,
                restoreMocks: false,
                mockReset: false,
                include: [ '**/*.{test,spec}.?(c|m)[jt]s?(x)' ],
                exclude: [
                  '**/node_modules/**',
                  '**/dist/**',
                  '**/cypress/**',
                  '**/.{idea,git,cache,output,temp}/**',
                  '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
                ],
                teardownTimeout: 10000,
                forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**' ],
                update: false,
                reporters: [ [ 'default', {} ] ],
                silent: false,
                hideSkippedTests: false,
                api: { middlewareMode: true },
                ui: false,
                uiBase: '/__vitest__/',
                open: true,
                css: { include: [], modules: { classNameStrategy: 'stable' } },
                coverage: {
                  provider: 'v8',
                  enabled: false,
                  all: true,
                  clean: true,
                  cleanOnRerun: true,
                  reportsDirectory: './coverage',
                  exclude: [
                    'coverage/**',
                    'dist/**',
                    '**/node_modules/**',
                    '**/[.]**',
                    'packages/*/test?(s)/**',
                    '**/*.d.ts',
                    '**/virtual:*',
                    '**/__x00__*',
                    '**/\x00*',
                    'cypress/**',
                    'test?(s)/**',
                    'test?(-*).?(c|m)[jt]s?(x)',
                    '**/*{.,-}{test,spec,bench,benchmark}?(-d).?(c|m)[jt]s?(x)',
                    '**/__tests__/**',
                    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
                    '**/vitest.{workspace,projects}.[jt]s?(on)',
                    '**/.{eslint,mocha,prettier}rc.{?(c|m)js,yml}'
                  ],
                  reportOnFailure: false,
                  reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
                  extension: [
                    '.js',     '.cjs',
                    '.mjs',    '.ts',
                    '.mts',    '.tsx',
                    '.jsx',    '.vue',
                    '.svelte', '.marko'
                  ],
                  allowExternal: false,
                  ignoreEmptyLines: true,
                  processingConcurrency: 12
                },
                fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
                maxConcurrency: 5,
                dangerouslyIgnoreUnhandledErrors: false,
                typecheck: {
                  checker: 'tsc',
                  include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
                  exclude: [
                    '**/node_modules/**',
                    '**/dist/**',
                    '**/cypress/**',
                    '**/.{idea,git,cache,output,temp}/**',
                    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
                  ],
                  enabled: false
                },
                slowTestThreshold: 300,
                disableConsoleIntercept: false,
                poolOptions: { threads: {}, forks: {} },
                defines: {},
                root: '<homeDir>/holvi/dev-env/libs/e2e',
                mode: 'test',
                inspector: { enabled: false, waitForDebugger: false },
                clearScreen: true,
                browser: { enabled: false, headless: false, isolate: true, fileParallelism: true, ui: true, screenshotFailures: false, viewport: { width: 414, height: 896 }, api: { port: 63315 } },
                fileParallelism: true,
                expect: {},
                deps: {
                  moduleDirectories: [ '/node_modules/' ],
                  optimizer: { ssr: { enabled: true }, web: { enabled: true } },
                  web: { transformAssets: true, transformCss: true, transformGlobPattern: [] }
                },
                server: { deps: { inline: [ {}, {}, {}, '@nuxt/test-utils' ], moduleDirectories: [ '/node_modules/' ], cacheDir: 'node_modules/.vite' } },
                snapshotOptions: { expand: false, snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
                snapshotSerializers: [],
                poolMatchGlobs: [],
                setupFiles: [],
                globalSetup: [],
                cache: { dir: '<homeDir>/holvi/dev-env/libs/e2e/node_modules/.vite/vitest' },
                sequence: { hooks: 'stack' },
                environmentMatchGlobs: [],
                testTransformMode: {},
                testTimeout: 5000,
                hookTimeout: 10000
              }
            }
          ],
          package: {
            version: '2.0.4',
            urls: { hooks: 'file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/runners/node/hooks.mjs' },
            paths: {
              root: '<homeDir>/holvi/dev-env/node_modules/.pnpm/vitest@2.0.4_@types+node@20.11.16/node_modules/vitest',
              dist: '<homeDir>/holvi/dev-env/node_modules/.pnpm/vitest@2.0.4_@types+node@20.11.16/node_modules/vitest/dist'
            }
          }
        }
      }
    },
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0', autoDetected: true },
    preserveComments: false,
    extractComments: true,
    files: [
      { pattern: '**/*.{test,spec}.?(c|m)[jt]s?(x)', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/*.timestamp-*', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/*.*', ignore: false, trigger: true, load: true, order: 1 }
    ],
    tests: [
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/*.{test,spec}.?(c|m)[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    workers: { initial: 1, regular: 1, recycle: false },
    dot: true,
    captureConsoleLog: true,
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 8192 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    maxTraceSteps: 999999,
    maxTraceStepsForWatchExpressionPrefetch: 0,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: {
      type: 'node',
      params: {},
      runner: '<homeDir>/.nvm/versions/node/v20.11.0/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: true,
    symlinkNodeModules: true,
    configCode: 'auto.detect#-1486913993'
  },
  packageJSON: {
    dependencies: { '@holvi/common': 'workspace:*', '@holvi/data-generation': 'workspace:*', remeda: '^1.61.0', 'type-fest': '^4.18.2' },
    devDependencies: { '@holvi/config': 'workspace:*', '@holvi/testing': 'workspace:*', '@sinclair/typebox': '^0.32.20', playwright: '^1.44.0' }
  },
  fs: { numberOfFiles: 57 },
  debug: [
    '2024-07-27T19:35:51.660Z project waiting for initial run signal\n',
    '2024-07-27T19:35:51.664Z model Initialization Completed: 152ms\n',
    '2024-07-27T19:35:51.666Z config Attempting automatic configuration for angular\n',
    '2024-07-27T19:35:51.668Z angular/cli config Angular CLI not found.\n',
    '2024-07-27T19:35:51.668Z config Finished attempting automatic configuration for angular (2ms)\n',
    '2024-07-27T19:35:51.668Z config Attempting automatic configuration for jest\n',
    "2024-07-27T19:35:51.668Z jest/config Error: Module jest-cli is not found in '<homeDir>/holvi/dev-env/libs/e2e'.\n" +
      '    at Object.loadJest (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/server.js:497:1080)\n' +
      '    at i (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/server.js:184:24825)\n' +
      '    at s.configure (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/server.js:184:28164)\n' +
      '    at automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/server.js:132:13094)\n' +
      '    at async automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/server.js:132:12971)\n' +
      '    at async automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/server.js:132:12971)\n' +
      '    at async Config.load (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/server.js:132:12911)\n' +
      '    at async Project.configure (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/server.js:484:2644)\n',
    '2024-07-27T19:35:51.668Z config Finished attempting automatic configuration for jest (0ms)\n',
    '2024-07-27T19:35:51.668Z config Attempting automatic configuration for vitest\n',
    '2024-07-27T19:35:51.670Z vitest/config Detected Vitest (2.0.4).\n',
    '2024-07-27T19:35:51.975Z config Finished attempting automatic configuration for vitest (307ms)\n',
    '2024-07-27T19:35:51.976Z project Wallaby Node version: v20.11.0\n',
    '2024-07-27T19:35:51.976Z project Wallaby config: <homeDir>/holvi/dev-env/libs/e2e/auto.detect\n',
    '2024-07-27T19:35:51.999Z fs File system starting\n',
    '2024-07-27T19:35:52.018Z fs File system scan completed\n',
    '2024-07-27T19:35:52.022Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/projects/bbf6c181b0d20719\n',
    '2024-07-27T19:35:52.088Z ui.service.legacy Listening port 51235\n',
    '2024-07-27T19:35:52.092Z workers Parallelism for initial run: 1, for regular run: 1\n',
    '2024-07-27T19:35:52.092Z workers Starting run worker instance #0\n',
    '2024-07-27T19:35:52.092Z workers Web server is listening at 51244\n',
    '2024-07-27T19:35:52.093Z project Stopping process pool\n',
    '2024-07-27T19:35:52.093Z project File cache is up-to-date, starting full test run\n',
    '2024-07-27T19:35:52.095Z project Test run started; run priority: 3\n',
    '2024-07-27T19:35:52.095Z project Running all tests\n',
    '2024-07-27T19:35:52.102Z workers Starting test run, priority: 3\n',
    '2024-07-27T19:35:52.102Z nodeRunner Starting sandbox [worker #0, session #i5lds]\n',
    '2024-07-27T19:35:52.103Z nodeRunner Preparing sandbox [worker #0, session #i5lds]\n',
    '2024-07-27T19:35:52.182Z workers Started run worker instance (delayed) #0\n',
    '2024-07-27T19:35:52.182Z nodeRunner Prepared sandbox [worker #0, session #i5lds]\n',
    '2024-07-27T19:35:52.182Z workers [worker #0, session #i5lds] Running tests in sandbox\n',
    "2024-07-27T19:35:52.572Z workers 'Scheduling Vitest Run (i5lds): 2024-07-27T19:35:52.570Z'\n",
    '2024-07-27T19:35:53.540Z workers Sandbox (active) [i5lds] error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.\n' +
      '    at onMessage (file://<homeDir>/holvi/dev-env/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)\n',
    '2024-07-27T19:35:53.552Z workers Sandbox (active) [i5lds] error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.\n' +
      '    at onMessage (file://<homeDir>/holvi/dev-env/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)\n',
    '2024-07-27T19:35:53.653Z workers [i5lds] Run 0 test(s), skipped 0 test(s)\n',
    '2024-07-27T19:35:53.654Z workers [i5lds] Sandbox is responsive, closing it\n',
    '2024-07-27T19:35:53.654Z workers Failed to map the stack to user code, entry message: Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match., stack: Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.\n' +
      '    at complete (file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/runners/node/vitest@0.14.0/shared.mjs:1:5211)\n' +
      '    at run (file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/runners/node/vitest@0.14.0/worker.mjs:1:341)\n' +
      '    at onMessage (file://<homeDir>/holvi/dev-env/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)\n',
    '2024-07-27T19:35:53.654Z workers Failed to map the stack to user code, entry message: Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match., stack: Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.\n' +
      '    at complete (file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/runners/node/vitest@0.14.0/shared.mjs:1:5211)\n' +
      '    at run (file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/runners/node/vitest@0.14.0/worker.mjs:1:341)\n' +
      '    at onMessage (file://<homeDir>/holvi/dev-env/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)\n',
    '2024-07-27T19:35:53.655Z project Test run finished\n',
    '2024-07-27T19:35:53.655Z project Processed console.log entries\n',
    '2024-07-27T19:35:53.655Z project Processed loading sequences\n',
    '2024-07-27T19:35:53.655Z project Processed executed tests\n',
    '2024-07-27T19:35:53.657Z project Processed code coverage\n',
    '2024-07-27T19:35:53.667Z project Test run result processed and sent to IDE\n',
    '2024-07-27T19:35:54.171Z fs No metadata for added file found: node_modules/.vite/vitest/results.json\n',
    '2024-07-27T19:35:55.265Z fs File changed in editor: src/states/State.spec.ts\n',
    '2024-07-27T19:35:55.272Z project Test run started; run priority: 2\n',
    '2024-07-27T19:35:55.272Z testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2024-07-27T19:35:55.273Z workers Starting test run, priority: 2\n',
    '2024-07-27T19:35:55.273Z nodeRunner Starting sandbox [worker #0, session #igvxm]\n',
    '2024-07-27T19:35:55.273Z nodeRunner Preparing sandbox [worker #0, session #igvxm]\n',
    '2024-07-27T19:35:55.273Z nodeRunner Prepared sandbox [worker #0, session #igvxm]\n',
    '2024-07-27T19:35:55.273Z workers [worker #0, session #igvxm] Running tests in sandbox\n',
    "2024-07-27T19:35:55.275Z workers 'Scheduling Vitest Run (igvxm): 2024-07-27T19:35:55.274Z'\n",
    "2024-07-27T19:35:55.417Z workers 'Range mismatch (fileId: 32, calculated: 0, actual: 45)'\n",
    '2024-07-27T19:35:55.520Z workers Sandbox (active) [igvxm] error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.\n' +
      '    at onMessage (file://<homeDir>/holvi/dev-env/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)\n',
    "2024-07-27T19:35:55.528Z workers 'Vitest Run Complete (igvxm): 2024-07-27T19:35:55.528Z'\n",
    '2024-07-27T19:35:55.529Z workers [igvxm] Run 0 test(s), skipped 0 test(s)\n',
    '2024-07-27T19:35:55.529Z workers [igvxm] Sandbox is responsive, closing it\n',
    '2024-07-27T19:35:55.529Z workers Failed to map the stack to user code, entry message: Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match., stack: Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.\n' +
      '    at complete (file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/runners/node/vitest@0.14.0/shared.mjs:1:5211)\n' +
      '    at run (file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/runners/node/vitest@0.14.0/worker.mjs:1:341)\n' +
      '    at onMessage (file://<homeDir>/holvi/dev-env/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)\n',
    '2024-07-27T19:35:55.530Z project Test run finished\n',
    '2024-07-27T19:35:55.530Z project Processed console.log entries\n',
    '2024-07-27T19:35:55.530Z project Processed loading sequences\n',
    '2024-07-27T19:35:55.530Z project Processed executed tests\n',
    '2024-07-27T19:35:55.531Z project Processed code coverage\n',
    '2024-07-27T19:35:55.532Z project Test run result processed and sent to IDE\n',
    '2024-07-27T19:35:55.547Z fs File changed: node_modules/.vite/vitest/results.json\n',
    '2024-07-27T19:35:55.547Z fs No metadata for changed file found: node_modules/.vite/vitest/results.json\n',
    '2024-07-27T19:35:55.726Z fs File changed: src/states/State.spec.ts\n',
    '2024-07-27T19:35:55.726Z fs No changes detected for src/states/State.spec.ts\n',
    '2024-07-27T19:35:55.727Z extended-core File was not changed, but file markers may need to be synced\n',
    '2024-07-27T19:35:56.997Z fs File changed in editor: src/states/State.spec.ts\n',
    '2024-07-27T19:35:57.001Z project Test run started; run priority: 2\n',
    '2024-07-27T19:35:57.001Z testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2024-07-27T19:35:57.002Z workers Starting test run, priority: 2\n',
    '2024-07-27T19:35:57.002Z nodeRunner Starting sandbox [worker #0, session #7b7s5]\n',
    '2024-07-27T19:35:57.002Z nodeRunner Preparing sandbox [worker #0, session #7b7s5]\n',
    '2024-07-27T19:35:57.002Z nodeRunner Prepared sandbox [worker #0, session #7b7s5]\n',
    '2024-07-27T19:35:57.002Z workers [worker #0, session #7b7s5] Running tests in sandbox\n',
    "2024-07-27T19:35:57.002Z workers 'Scheduling Vitest Run (7b7s5): 2024-07-27T19:35:57.002Z'\n",
    "2024-07-27T19:35:57.139Z workers 'Range mismatch (fileId: 32, calculated: 0, actual: 45)'\n",
    '2024-07-27T19:35:57.259Z workers Sandbox (active) [7b7s5] error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.\n' +
      '    at onMessage (file://<homeDir>/holvi/dev-env/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)\n',
    "2024-07-27T19:35:57.263Z workers 'Vitest Run Complete (7b7s5): 2024-07-27T19:35:57.263Z'\n",
    '2024-07-27T19:35:57.264Z workers [7b7s5] Run 0 test(s), skipped 0 test(s)\n',
    '2024-07-27T19:35:57.264Z workers [7b7s5] Sandbox is responsive, closing it\n',
    '2024-07-27T19:35:57.264Z workers Failed to map the stack to user code, entry message: Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match., stack: Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.\n' +
      '    at complete (file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/runners/node/vitest@0.14.0/shared.mjs:1:5211)\n' +
      '    at run (file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.379/wallaby226ca6/runners/node/vitest@0.14.0/worker.mjs:1:341)\n' +
      '    at onMessage (file://<homeDir>/holvi/dev-env/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)\n',
    '2024-07-27T19:35:57.264Z project Test run finished\n',
    '2024-07-27T19:35:57.264Z project Processed console.log entries\n',
    '2024-07-27T19:35:57.264Z project Processed loading sequences\n',
    '2024-07-27T19:35:57.264Z project Processed executed tests\n',
    '2024-07-27T19:35:57.264Z project Processed code coverage\n',
    '2024-07-27T19:35:57.266Z project Test run result processed and sent to IDE\n',
    '2024-07-27T19:35:57.312Z fs File changed: src/states/State.spec.ts\n',
    '2024-07-27T19:35:57.312Z fs File changed: node_modules/.vite/vitest/results.json\n',
    '2024-07-27T19:35:57.312Z fs No metadata for changed file found: node_modules/.vite/vitest/results.json\n',
    '2024-07-27T19:35:57.312Z fs No changes detected for src/states/State.spec.ts\n',
    '2024-07-27T19:35:57.313Z extended-core File was not changed, but file markers may need to be synced\n'
  ]
}
```

**Comment by smcenlly** [comment]
Vitest@2.0.4 is working for us. Your diagnostics report shows your package.json dependencies for your project root do not include vitest.

```
{
  "dependencies": {
    "@holvi/common": "workspace:*",
    "@holvi/data-generation": "workspace:*",
    "remeda": "^1.61.0",
    "type-fest": "^4.18.2"
  },
  "devDependencies": {
    "@holvi/config": "workspace:*",
    "@holvi/testing": "workspace:*",
    "@sinclair/typebox": "^0.32.20",
    "playwright": "^1.44.0"
  }
}
```

Could you please try installing `vitest@2.0.4` in your project root, and also ensure that this version aligns with any workspace project dependencies so that they are all the same?

**Comment by holvi-sebastian** [comment]
My VSCode Wallaby extension got two core updates, and now it seems to work fine! I'll re-open if I see the problem again. Thanks for your response!
