### ISSUE TITLE
Running with vitest@2.0.5 gives error: "Wallaby did not detect that any vitest tasks were executed."

### ISSUE THREAD

**Issue by jrutila** [wallabyjs/public#3388]
### Issue description or question

Running with vitest@2.0.5 and pnpm mono-repo I got following error. Wallaby worked at some point!

```
​​[Error] Runtime error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.​​
​​[Error]     at complete (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/shared.mjs:1:5211)​​
​​[Error]     at run (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/worker.mjs:1:341)​​
​​[Error]     at onMessage (file:///C:/Users/user/devel/ngh/proj/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)​​
```

I tried adding this `.npmrc` in the pnpm workspace root:
```
public-hoist-pattern[]=*vitest*
public-hoist-pattern[]=vite-node
```

### Wallaby diagnostics report

```
{
  editorVersion: '1.92.0',
  pluginVersion: '1.0.381',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.22631',
  nodeVersion: 'v18.20.4',
  coreVersion: '1.0.1591',
  pnp: '<not set>',
  pnpEsm: '<not set>',
  checksum: 'OTJkYzg2NDkxOTQ3MTM0ZThiZWI0MWQ4ZTE0OTIzZjYsMTc1NDQzODQwMDAwMCww',
  config: {
    diagnostics: {
      vitest: {
        config: {
          config: {
            allowOnly: true,
            isolate: true,
            watch: true,
            globals: false,
            environment: 'node',
            pool: 'forks',
            clearMocks: false,
            restoreMocks: false,
            mockReset: false,
            unstubGlobals: false,
            unstubEnvs: false,
            include: [ '**/*.{test,spec}.?(c|m)[jt]s?(x)' ],
            exclude: [
              '**/node_modules/**',
              '**/dist/**',
              '**/cypress/**',
              '**/.{idea,git,cache,output,temp}/**',
              '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
            ],
            teardownTimeout: 10000,
            forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**' ],
            update: false,
            reporters: [ [ 'default', {} ] ],
            silent: false,
            hideSkippedTests: false,
            api: { middlewareMode: true },
            ui: false,
            uiBase: '/__vitest__/',
            open: true,
            css: { include: [], modules: { classNameStrategy: 'stable' } },
            coverage: {
              provider: 'v8',
              enabled: false,
              all: true,
              clean: true,
              cleanOnRerun: true,
              reportsDirectory: './coverage',
              exclude: [
                'coverage/**',
                'dist/**',
                '**/node_modules/**',
                '**/[.]**',
                'packages/*/test?(s)/**',
                '**/*.d.ts',
                '**/virtual:*',
                '**/__x00__*',
                '**/\x00*',
                'cypress/**',
                'test?(s)/**',
                'test?(-*).?(c|m)[jt]s?(x)',
                '**/*{.,-}{test,spec,bench,benchmark}?(-d).?(c|m)[jt]s?(x)',
                '**/__tests__/**',
                '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
                '**/vitest.{workspace,projects}.[jt]s?(on)',
                '**/.{eslint,mocha,prettier}rc.{?(c|m)js,yml}'
              ],
              reportOnFailure: false,
              reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
              extension: [
                '.js',     '.cjs',
                '.mjs',    '.ts',
                '.mts',    '.tsx',
                '.jsx',    '.vue',
                '.svelte', '.marko'
              ],
              allowExternal: false,
              ignoreEmptyLines: true,
              processingConcurrency: 14
            },
            fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
            maxConcurrency: 5,
            dangerouslyIgnoreUnhandledErrors: false,
            typecheck: {
              checker: 'tsc',
              include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
              exclude: [
                '**/node_modules/**',
                '**/dist/**',
                '**/cypress/**',
                '**/.{idea,git,cache,output,temp}/**',
                '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
              ],
              enabled: false
            },
            slowTestThreshold: 300,
            disableConsoleIntercept: false,
            poolOptions: { threads: {}, forks: {} },
            defines: {},
            root: 'C:/Users/user/devel/ngh/proj/libraries/ngh',
            mode: 'test',
            inspector: { enabled: false, waitForDebugger: false },
            clearScreen: true,
            browser: { enabled: false, headless: false, isolate: true, fileParallelism: true, ui: true, screenshotFailures: false, viewport: { width: 414, height: 896 }, api: { port: 63315 } },
            fileParallelism: true,
            expect: {},
            deps: {
              moduleDirectories: [ '/node_modules/' ],
              optimizer: { ssr: { enabled: true }, web: { enabled: true } },
              web: { transformAssets: true, transformCss: true, transformGlobPattern: [] }
            },
            server: { deps: { inline: [ {}, {}, {} ], moduleDirectories: [ '/node_modules/' ], cacheDir: 'node_modules/.vite' } },
            snapshotOptions: { expand: false, snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
            snapshotSerializers: [],
            poolMatchGlobs: [],
            setupFiles: [],
            globalSetup: [],
            cache: { dir: 'C:/Users/user/devel/ngh/proj/libraries/ngh/node_modules/.vite/vitest' },
            sequence: { hooks: 'stack' },
            environmentMatchGlobs: [],
            testTransformMode: {},
            testTimeout: 5000,
            hookTimeout: 10000
          },
          projects: [
            {
              path: 'C:/Users/user/devel/ngh/proj/libraries/ngh',
              config: {
                allowOnly: true,
                isolate: true,
                watch: true,
                globals: false,
                environment: 'node',
                pool: 'forks',
                clearMocks: false,
                restoreMocks: false,
                mockReset: false,
                unstubGlobals: false,
                unstubEnvs: false,
                include: [ '**\\*.{test,spec}.?(c|m)[jt]s?(x)' ],
                exclude: [
                  '**\\node_modules\\**',
                  '**\\dist\\**',
                  '**\\cypress\\**',
                  '**\\.{idea,git,cache,output,temp}\\**',
                  '**\\{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
                ],
                teardownTimeout: 10000,
                forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**' ],
                update: false,
                reporters: [ [ 'default', {} ] ],
                silent: false,
                hideSkippedTests: false,
                api: { middlewareMode: true },
                ui: false,
                uiBase: '/__vitest__/',
                open: true,
                css: { include: [], modules: { classNameStrategy: 'stable' } },
                coverage: {
                  provider: 'v8',
                  enabled: false,
                  all: true,
                  clean: true,
                  cleanOnRerun: true,
                  reportsDirectory: './coverage',
                  exclude: [
                    'coverage/**',
                    'dist/**',
                    '**/node_modules/**',
                    '**/[.]**',
                    'packages/*/test?(s)/**',
                    '**/*.d.ts',
                    '**/virtual:*',
                    '**/__x00__*',
                    '**/\x00*',
                    'cypress/**',
                    'test?(s)/**',
                    'test?(-*).?(c|m)[jt]s?(x)',
                    '**/*{.,-}{test,spec,bench,benchmark}?(-d).?(c|m)[jt]s?(x)',
                    '**/__tests__/**',
                    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
                    '**/vitest.{workspace,projects}.[jt]s?(on)',
                    '**/.{eslint,mocha,prettier}rc.{?(c|m)js,yml}'
                  ],
                  reportOnFailure: false,
                  reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
                  extension: [
                    '.js',     '.cjs',
                    '.mjs',    '.ts',
                    '.mts',    '.tsx',
                    '.jsx',    '.vue',
                    '.svelte', '.marko'
                  ],
                  allowExternal: false,
                  ignoreEmptyLines: true,
                  processingConcurrency: 14
                },
                fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
                maxConcurrency: 5,
                dangerouslyIgnoreUnhandledErrors: false,
                typecheck: {
                  checker: 'tsc',
                  include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
                  exclude: [
                    '**/node_modules/**',
                    '**/dist/**',
                    '**/cypress/**',
                    '**/.{idea,git,cache,output,temp}/**',
                    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
                  ],
                  enabled: false
                },
                slowTestThreshold: 300,
                disableConsoleIntercept: false,
                poolOptions: { threads: {}, forks: {} },
                defines: {},
                root: 'C:/Users/user/devel/ngh/proj/libraries/ngh',
                mode: 'test',
                inspector: { enabled: false, waitForDebugger: false },
                clearScreen: true,
                browser: { enabled: false, headless: false, isolate: true, fileParallelism: true, ui: true, screenshotFailures: false, viewport: { width: 414, height: 896 }, api: { port: 63315 } },
                fileParallelism: true,
                expect: {},
                deps: {
                  moduleDirectories: [ '/node_modules/' ],
                  optimizer: { ssr: { enabled: true }, web: { enabled: true } },
                  web: { transformAssets: true, transformCss: true, transformGlobPattern: [] }
                },
                server: { deps: { inline: [ {}, {}, {} ], moduleDirectories: [ '/node_modules/' ], cacheDir: 'node_modules/.vite' } },
                snapshotOptions: { expand: false, snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
                snapshotSerializers: [],
                poolMatchGlobs: [],
                setupFiles: [],
                globalSetup: [],
                cache: { dir: 'C:/Users/user/devel/ngh/proj/libraries/ngh/node_modules/.vite/vitest' },
                sequence: { hooks: 'stack' },
                environmentMatchGlobs: [],
                testTransformMode: {},
                testTimeout: 5000,
                hookTimeout: 10000
              }
            }
          ],
          package: {
            version: '2.0.5',
            urls: { hooks: 'file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/hooks.mjs' },
            paths: {
              root: 'C:\\Users\\user\\devel\\ngh\\proj\\node_modules\\.pnpm\\vitest@2.0.5_@types+node@20.14.14_happy-dom@14.12.3_terser@5.31.3\\node_modules\\vitest',
              dist: 'C:\\Users\\user\\devel\\ngh\\proj\\node_modules\\.pnpm\\vitest@2.0.5_@types+node@20.14.14_happy-dom@14.12.3_terser@5.31.3\\node_modules\\vitest\\dist'
            }
          }
        }
      }
    },
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0', autoDetected: true },
    preserveComments: false,
    extractComments: true,
    files: [
      { pattern: '**/*.{test,spec}.?(c|m)[jt]s?(x)', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**\\*.{test,spec}.?(c|m)[jt]s?(x)', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**\\node_modules\\**', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**\\dist\\**', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**\\cypress\\**', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**\\.{idea,git,cache,output,temp}\\**', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**\\{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/*.timestamp-*', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/*.*', ignore: false, trigger: true, load: true, order: 1 }
    ],
    tests: [
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**\\node_modules\\**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**\\dist\\**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**\\cypress\\**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**\\.{idea,git,cache,output,temp}\\**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**\\{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/*.{test,spec}.?(c|m)[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: '**\\*.{test,spec}.?(c|m)[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 }
    ],
    workers: { initial: 1, regular: 1, recycle: false },
    dot: true,
    captureConsoleLog: true,
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 8192 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    maxTraceSteps: 999999,
    maxTraceStepsForWatchExpressionPrefetch: 0,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: 'C:\\Program Files\\nodejs\\node.exe', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: true,
    symlinkNodeModules: true,
    configCode: 'auto.detect#1734400718'
  },
  packageJSON: {
    dependencies: { consola: '^3.2.3', 'js-yaml': '^4.1.0', ofetch: '^1.0.1', txml: '^5.1.1' },
    devDependencies: {
      '@babel/cli': '^7.23.0',
      '@babel/core': '^7.23.2',
      '@types/js-yaml': '^4.0.8',
      'babel-plugin-add-import-extension': '^1.6.0',
      typescript: '^5.0.4',
      vite: '^5.3.4',
      vitest: '^2.0.5',
      'xml-js': '^1.6.11'
    }
  },
  fs: { numberOfFiles: 105 },
  debug: [
    '2024-08-07T06:04:09.435Z project waiting for initial run signal\n',
    '2024-08-07T06:04:09.449Z model Initialization Completed: 551ms\n',
    '2024-08-07T06:04:09.464Z config Attempting automatic configuration for vitest\n',
    '2024-08-07T06:04:09.473Z vitest/config Detected Vitest (2.0.5).\n',
    '2024-08-07T06:04:11.715Z config Finished attempting automatic configuration for vitest (2251ms)\n',
    '2024-08-07T06:04:11.718Z project Wallaby Node version: v18.20.4\n',
    '2024-08-07T06:04:11.718Z project Wallaby config: C:\\Users\\user\\devel\\ngh\\proj\\libraries\\ngh\\auto.detect\n',
    '2024-08-07T06:04:11.799Z fs File system starting\n',
    '2024-08-07T06:04:12.085Z fs File system scan completed\n',
    '2024-08-07T06:04:12.099Z project File cache: C:\\Users\\user\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.381\\projects\\f714a56d9e304793\n',
    '2024-08-07T06:04:12.288Z ui.service.legacy Listening port 51235\n',
    '2024-08-07T06:04:12.303Z project package.json file change detected, invalidating local cache\n',
    '2024-08-07T06:04:12.327Z workers Parallelism for initial run: 1, for regular run: 1\n',
    '2024-08-07T06:04:12.327Z workers Starting run worker instance #0\n',
    '2024-08-07T06:04:12.329Z workers Web server is listening at 64121\n',
    '2024-08-07T06:04:12.330Z project File cache requires some updates, waiting required files from IDE\n',
    '2024-08-07T06:04:12.489Z project Stopping process pool\n',
    '2024-08-07T06:04:12.511Z project Test run started; run priority: 3\n',
    '2024-08-07T06:04:12.518Z project Running all tests\n',
    '2024-08-07T06:04:12.570Z workers Starting test run, priority: 3\n',
    '2024-08-07T06:04:12.571Z nodeRunner Starting sandbox [worker #0, session #ki1nb]\n',
    '2024-08-07T06:04:12.571Z nodeRunner Preparing sandbox [worker #0, session #ki1nb]\n',
    '2024-08-07T06:04:12.752Z workers Started run worker instance (delayed) #0\n',
    '2024-08-07T06:04:12.753Z nodeRunner Prepared sandbox [worker #0, session #ki1nb]\n',
    '2024-08-07T06:04:12.753Z workers [worker #0, session #ki1nb] Running tests in sandbox\n',
    "2024-08-07T06:04:13.991Z workers 'Scheduling Vitest Run (ki1nb): 2024-08-07T06:04:13.990Z'\n",
    '2024-08-07T06:04:15.935Z workers Sandbox (active) [ki1nb] error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.\n' +
      '    at complete (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/shared.mjs:1:5211)\n' +
      '    at run (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/worker.mjs:1:341)\n' +
      '    at onMessage (file:///C:/Users/user/devel/ngh/proj/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)\n',
    '2024-08-07T06:04:15.961Z workers Sandbox (active) [ki1nb] error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.\n' +
      '    at complete (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/shared.mjs:1:5211)\n' +
      '    at run (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/worker.mjs:1:341)\n' +
      '    at onMessage (file:///C:/Users/user/devel/ngh/proj/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)\n',
    '2024-08-07T06:04:15.982Z workers Sandbox (active) [ki1nb] error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.\n' +
      '    at complete (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/shared.mjs:1:5211)\n' +
      '    at run (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/worker.mjs:1:341)\n' +
      '    at onMessage (file:///C:/Users/user/devel/ngh/proj/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)\n',
    '2024-08-07T06:04:15.984Z workers Sandbox (active) [ki1nb] error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.\n' +
      '    at complete (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/shared.mjs:1:5211)\n' +
      '    at run (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/worker.mjs:1:341)\n' +
      '    at onMessage (file:///C:/Users/user/devel/ngh/proj/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)\n',
    '2024-08-07T06:04:16.095Z workers [ki1nb] Run 0 test(s), skipped 0 test(s)\n',
    '2024-08-07T06:04:16.101Z workers [ki1nb] Sandbox is responsive, closing it\n',
    '2024-08-07T06:04:16.103Z workers Failed to map the stack to user code, entry message: Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match., stack: Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.\n' +
      '    at complete (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/shared.mjs:1:5211)\n' +
      '    at run (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/worker.mjs:1:341)\n' +
      '    at onMessage (file:///C:/Users/user/devel/ngh/proj/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)\n',
    '2024-08-07T06:04:16.103Z workers Failed to map the stack to user code, entry message: Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match., stack: Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.\n' +
      '    at complete (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/shared.mjs:1:5211)\n' +
      '    at run (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/worker.mjs:1:341)\n' +
      '    at onMessage (file:///C:/Users/user/devel/ngh/proj/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)\n',
    '2024-08-07T06:04:16.103Z workers Failed to map the stack to user code, entry message: Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match., stack: Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.\n' +
      '    at complete (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/shared.mjs:1:5211)\n' +
      '    at run (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/worker.mjs:1:341)\n' +
      '    at onMessage (file:///C:/Users/user/devel/ngh/proj/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)\n',
    '2024-08-07T06:04:16.103Z workers Failed to map the stack to user code, entry message: Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match., stack: Error: Wallaby did not detect that any vitest tasks were executed. This may indicate a problem with vitest dependency conflicts. Please ensure your vitest dependency versions match.\n' +
      '    at complete (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/shared.mjs:1:5211)\n' +
      '    at run (file:///c:/Users/user/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyfc1091/runners/node/vitest@0.14.0/worker.mjs:1:341)\n' +
      '    at onMessage (file:///C:/Users/user/devel/ngh/proj/node_modules/.pnpm/tinypool@1.0.0/node_modules/tinypool/dist/entry/process.js:54:20)\n',
    '2024-08-07T06:04:16.105Z project Test run finished\n',
    '2024-08-07T06:04:16.106Z project Processed console.log entries\n',
    '2024-08-07T06:04:16.106Z project Processed loading sequences\n',
    '2024-08-07T06:04:16.106Z project Processed executed tests\n',
    '2024-08-07T06:04:16.114Z project Processed code coverage\n',
    '2024-08-07T06:04:16.143Z project Test run result processed and sent to IDE\n',
    '2024-08-07T06:04:21.105Z workers Some long running code has been detected: one of your files is taking more than 5000ms to execute.\n' +
      'Execution of the following files has started but has not finished:\n' +
      '- src/FetchGuideMd.ts\n' +
      '- src/GuideParser.ts\n' +
      '- src/index.ts\n' +
      '- test/GuideParser.spec.ts\n' +
      'Try commenting out the test or excluding the test file from the `tests` list in your wallaby config,\n' +
      'and restarting wallaby to make sure that it is this test/file causing the issue and not something else.\n' +
      'Pinging test runner sandbox...\n',
    '2024-08-07T06:04:21.107Z workers Sandbox is responsive. The issue may be asynchronous in nature (for example, a missing callback).\n',
    '2024-08-07T06:04:21.631Z ui.service.legacy UI client connected\n',
    '2024-08-07T06:04:21.632Z ui.service.legacy Outgoing message ui:handshake\n',
    '2024-08-07T06:04:21.660Z ui.service.legacy Incoming message ui:start\n',
    '2024-08-07T06:04:21.662Z ui.service.legacy Outgoing message ui:summary\n',
    '2024-08-07T06:04:21.664Z ui.service.legacy Outgoing message ui:files\n',
    '2024-08-07T06:04:21.665Z ui.service.legacy Incoming message ui:tests:resultsRequested\n',
    '2024-08-07T06:04:21.667Z ui.service.legacy Outgoing message ui:tests:allResultsUpdated\n',
    '2024-08-07T06:04:25.737Z ui.service.legacy UI client disconnected\n'
  ]
}
```

**Comment by mburnell** [comment]
Thanks for reporting the error. There are a couple of different ways we think you could encounter this issue. We were able to reproduce it by installing dependencies using both npm and pnpm (one after another, on the same project), resulting in a node_modules folder that contained multiple instances of some dependencies. Given you mentioned this used to work for your project, this might be the problem. If it is, deleting your node_modules folder and reinstalling your dependencies using pnpm should fix things.

You also mentioned you're in a monorepo. If the above wipe/reinstall of node_modules doesn't fix your problem, it's possible there are conflicting vitest versions you'll need to align in order to fix the issue.

Please let us know whether either of these potential solutions fixes the error.

**Comment by jrutila** [comment]
Yes, I had a project inside the mono-repo that was referencing to vitest `^1.0.4` and others were for `^2.0.5`. After streamlining all projects to the same vitest version it started working. Thank you!
