### ISSUE TITLE
Question: setting up wallaby.js config to specify specific jest configuration

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#3389]
### Issue description or question

I'm trying to setup wallaby.js with jest configuration does not lives under project root.

For some reason, I'm not able to make wallaby.js runs either with auto configuration or manually specifying wallaby.js config and would like to get some help to resolve.

Ideally, I'd like to make autoconfig works, or make wallaby.js to specify jest config correctly.

Reproducible repo is at https://github.com/kwonoj/jest-config-path-setup, `npm test` works but wallaby does not picks up config correctly somehow.

### Wallaby diagnostics report

```
{
  editorVersion: '1.92.0',
  pluginVersion: '1.0.381',
  editorType: 'VSCode',
  osVersion: 'darwin 23.5.0',
  nodeVersion: 'v20.15.1',
  coreVersion: '1.0.1591',
  pnp: '<not set>',
  pnpEsm: '<not set>',
  checksum: 'M2E1MjY5NDcyNmRkZDRjOTc1MTc5N2ZkNjhmNzNhYzUsMTc3NzkzOTIwMDAwMCww',
  config: {
    tests: [ { pattern: 'src/**/*.unit.ts?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 } ],
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true, toolVersion: '27.5.1' },
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/private/var/folders/5m/1m5fnhvd763_srt0st0dn9s00000gp/T/jest_dy',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/github/jest-config-path-setup',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: undefined,
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              extraGlobals: [],
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: false, throwOnModuleCollision: false },
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [ 'js', 'jsx', 'ts', 'tsx', 'json', 'node' ],
              moduleLoader: undefined,
              moduleNameMapper: [],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              name: '9c3fa86695e277d6f7a1fb3aebeb9c85',
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/github/jest-config-path-setup',
              roots: [ '<homeDir>/github/jest-config-path-setup' ],
              runner: '<homeDir>/github/jest-config-path-setup/node_modules/jest-runner/build/index.js',
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: undefined,
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/github/jest-config-path-setup/node_modules/jest-environment-node/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<homeDir>/github/jest-config-path-setup/node_modules/jest-circus/runner.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [ [ '\\.[jt]sx?$', '<homeDir>/github/jest-config-path-setup/node_modules/babel-jest/build/index.js', {} ] ],
              transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: [],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<homeDir>/github/jest-config-path-setup/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 11,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/github/jest-config-path-setup',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: undefined,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/github/jest-config-path-setup/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/5m/1m5fnhvd763_srt0st0dn9s00000gp/T/jest_dy', '\\./coverage' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/5m/1m5fnhvd763_srt0st0dn9s00000gp/T/jest_dy', '\\./coverage' ],
            testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    filesWithCoverageCalculated: [],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    dot: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, file: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        file: true
      },
      {
        pattern: '/private/var/folders/5m/1m5fnhvd763_srt0st0dn9s00000gp/T/jest_dy',
        regexp: /\/private\/var\/folders\/5m\/1m5fnhvd763_srt0st0dn9s00000gp\/T\/jest_dy/,
        ignore: true,
        trigger: true,
        load: true,
        file: true
      },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**/*.unit.ts?(x)', ignore: true, trigger: true, load: true, file: true }
    ],
    captureConsoleLog: true,
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 8192 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    maxTraceSteps: 999999,
    maxTraceStepsForWatchExpressionPrefetch: 0,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: {
      type: 'node',
      params: {},
      runner: '<homeDir>/.local/share/fnm/node-versions/v20.15.1/installation/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: false,
    configCode: 'module.exports = function (w) {\n' +
      '  return {\n' +
      '    //files: [\n' +
      "    //  'src/**/*.{ts,tsx,js,jsx}',\n" +
      "    //  { pattern: 'src/**/*.unit.*', ignore: true },\n" +
      "    //  { pattern: 'src/**/*.d.ts', ignore: true },\n" +
      '    //],\n' +
      "    //files: [{ pattern: 'src/**/*.unit.*', ignore: true }],\n" +
      "    tests: ['src/**/*.unit.ts?(x)'],\n" +
      '    //trace: true,\n' +
      "    testFramework: 'jest',\n" +
      "    autoDetect: ['jest'],\n" +
      '    //compilers: {\n' +
      "    //  '**/*.{ts,tsx}': w.compilers.typeScript({\n" +
      '    //    esModuleInterop: true,\n' +
      '    //  }),\n' +
      '    //},\n' +
      '\n' +
      '    setup(wallaby) {\n' +
      "      const jestConfig = require('./tests/framework/jest/jest.config.js');\n" +
      '      //jestConfig.transform = undefined;\n' +
      '      //jestConfig.cache = false;\n' +
      '      //console.log(jestConfig.transform);\n' +
      '      wallaby.testFramework.configure(jestConfig);\n' +
      '    },\n' +
      '  };\n' +
      '};\n'
  },
  packageJSON: { dependencies: undefined, devDependencies: { '@types/jest': '^27.5.2', jest: '^27.5.1', 'ts-jest': '^27.1.5', typescript: '^4.9.5', undici: '^4.16.0' } },
  fs: { numberOfFiles: 11 },
  debug: [
    '2024-08-07T21:00:38.709Z project waiting for initial run signal\n',
    '2024-08-07T21:00:38.712Z model Initialization Completed: 112ms\n',
    '2024-08-07T21:00:38.715Z config Attempting automatic configuration for jest\n',
    '2024-08-07T21:00:38.750Z jest/config Detected Jest.\n',
    '2024-08-07T21:00:38.750Z jest/config Configured Jest.\n',
    '2024-08-07T21:00:38.750Z config Finished attempting automatic configuration for jest (35ms)\n',
    '2024-08-07T21:00:38.751Z project Wallaby Node version: v20.15.1\n',
    '2024-08-07T21:00:38.751Z project Wallaby config: <homeDir>/github/jest-config-path-setup/wallaby.js\n',
    '2024-08-07T21:00:38.772Z fs File system starting\n',
    '2024-08-07T21:00:39.925Z fs File system scan has finished by timeout\n',
    '2024-08-07T21:00:39.935Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/projects/2d7c67d4ecd5c4e4\n',
    '2024-08-07T21:00:39.970Z ui.service.legacy Listening port 51236\n',
    '2024-08-07T21:00:39.971Z project package.json file change detected, invalidating local cache\n',
    '2024-08-07T21:00:39.976Z workers Parallelism for initial run: 10, for regular run: 5\n',
    '2024-08-07T21:00:39.976Z workers Starting run worker instance #0\n',
    '2024-08-07T21:00:39.976Z workers Starting run worker instance #1\n',
    '2024-08-07T21:00:39.976Z workers Starting run worker instance #2\n',
    '2024-08-07T21:00:39.976Z workers Starting run worker instance #3\n',
    '2024-08-07T21:00:39.976Z workers Starting run worker instance #4\n',
    '2024-08-07T21:00:39.976Z workers Starting run worker instance #5\n',
    '2024-08-07T21:00:39.976Z workers Starting run worker instance #6\n',
    '2024-08-07T21:00:39.976Z workers Starting run worker instance #7\n',
    '2024-08-07T21:00:39.976Z workers Starting run worker instance #8\n',
    '2024-08-07T21:00:39.976Z workers Starting run worker instance #9\n',
    '2024-08-07T21:00:39.976Z workers Web server is listening at 49169\n',
    '2024-08-07T21:00:39.976Z project File cache requires some updates, waiting required files from IDE\n',
    '2024-08-07T21:00:39.991Z project Stopping process pool\n',
    '2024-08-07T21:00:39.994Z project Test run started; run priority: 3\n',
    '2024-08-07T21:00:39.996Z project Running all tests\n',
    '2024-08-07T21:00:39.997Z workers Starting test run, priority: 3\n',
    '2024-08-07T21:00:39.997Z nodeRunner Starting sandbox [worker #0, session #zqtwo]\n',
    '2024-08-07T21:00:39.997Z nodeRunner Preparing sandbox [worker #0, session #zqtwo]\n',
    '2024-08-07T21:00:40.122Z workers Started run worker instance (delayed) #6\n',
    '2024-08-07T21:00:40.125Z workers Started run worker instance (delayed) #5\n',
    '2024-08-07T21:00:40.125Z workers Started run worker instance (delayed) #0\n',
    '2024-08-07T21:00:40.125Z nodeRunner Prepared sandbox [worker #0, session #zqtwo]\n',
    '2024-08-07T21:00:40.125Z workers [worker #0, session #zqtwo] Running tests in sandbox\n',
    '2024-08-07T21:00:40.126Z workers Started run worker instance (delayed) #7\n',
    '2024-08-07T21:00:40.126Z workers Started run worker instance (delayed) #4\n',
    '2024-08-07T21:00:40.127Z workers Started run worker instance (delayed) #1\n',
    '2024-08-07T21:00:40.128Z workers Started run worker instance (delayed) #3\n',
    '2024-08-07T21:00:40.128Z workers Started run worker instance (delayed) #8\n',
    '2024-08-07T21:00:40.130Z workers Started run worker instance (delayed) #2\n',
    '2024-08-07T21:00:40.140Z workers Started run worker instance (delayed) #9\n',
    "2024-08-07T21:00:40.343Z workers 'Scheduling Jest Test Run (zqtwo): 2024-08-07T21:00:40.342Z'\n",
    "2024-08-07T21:00:40.345Z workers 'Jest Test Error: 2024-08-07T21:00:40.345Z'\n",
    '2024-08-07T21:00:40.346Z workers Sandbox (active) [zqtwo] error: TypeError: this._config.transform.map is not a function\n' +
      '    at ScriptTransformer.loadTransformers (<rootDir>/node_modules/@jest/transform/build/ScriptTransformer.js:380:30)\n' +
      '    at createScriptTransformer (<rootDir>/node_modules/@jest/transform/build/ScriptTransformer.js:1113:21)\n' +
      '    at <rootDir>/node_modules/@jest/core/build/TestScheduler.js:269:78\n' +
      '    at Array.map (<anonymous>)\n' +
      '    at TestScheduler.scheduleTests (<rootDir>/node_modules/@jest/core/build/TestScheduler.js:263:28)\n',
    "2024-08-07T21:00:40.346Z workers 'Jest Test Run Complete (zqtwo): 2024-08-07T21:00:40.345Z'\n",
    '2024-08-07T21:00:40.346Z workers [zqtwo] Run 0 test(s), skipped 0 test(s)\n',
    '2024-08-07T21:00:40.346Z workers [zqtwo] Sandbox is responsive, closing it\n',
    '2024-08-07T21:00:40.347Z workers Failed to map the stack to user code, entry message: this._config.transform.map is not a function, stack: TypeError: this._config.transform.map is not a function\n' +
      '    at ScriptTransformer.loadTransformers (<homeDir>/github/jest-config-path-setup/node_modules/@jest/transform/build/ScriptTransformer.js:380:30)\n' +
      '    at createScriptTransformer (<homeDir>/github/jest-config-path-setup/node_modules/@jest/transform/build/ScriptTransformer.js:1113:21)\n' +
      '    at <homeDir>/github/jest-config-path-setup/node_modules/@jest/core/build/TestScheduler.js:269:78\n' +
      '    at Array.map (<anonymous>)\n' +
      '    at TestScheduler.scheduleTests (<homeDir>/github/jest-config-path-setup/node_modules/@jest/core/build/TestScheduler.js:263:28)\n' +
      '    at async a._onStart (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyf0113f/runners/node/jest@24.8.0/initializer.js:35:11295)\n',
    '2024-08-07T21:00:40.347Z project Test run finished\n',
    '2024-08-07T21:00:40.347Z project Processed console.log entries\n',
    '2024-08-07T21:00:40.347Z project Processed loading sequences\n',
    '2024-08-07T21:00:40.347Z project Processed executed tests\n',
    '2024-08-07T21:00:40.347Z project Processed code coverage\n',
    '2024-08-07T21:00:40.349Z project Test run result processed and sent to IDE\n',
    '2024-08-07T21:00:40.354Z fs No metadata for added file found: <rootDir>/.cache/unit/haste-map-9c3fa86695e277d6f7a1fb3aebeb9c85-7bd914840e119a3240ff1c8682b5c75d-475fe4928e45e6abcf7b9571bb228a44\n'
  ]
}
```

**Comment by smcenlly** [comment]
Thanks for providing the sample repo. Your configuration looks like it is bit of a combination of our automatic configuration and our legacy jest support (from 2019). For your reference, [this page in our docs](https://wallabyjs.com/docs/integration/jest.html#overriding-automatic-configuration) describes how to specify a custom configuration file.

If you update your configuration file, it should work for you:

**wallaby.js**
```javascript
module.exports = {
  testFramework: {
    // the jest configuration file path (relative to project root)
    configFile: "./tests/framework/jest/jest.config.js",
  },
};
```
