### ISSUE TITLE
Required dependency '@vitest/runner' not found, trying to use vitest with yarn 4.4.0 in VSCode

### ISSUE THREAD

**Issue by lachlanhunt** [wallabyjs/public#3393]
### Issue description or question

Using yarn 4.4.0, I set up a repo using `yarn create vite --template react-swc-ts`, added vitest (with `"test": "vitest"` added to package.json scripts) and created some sample tests for both both JS and TS.  The tests successfully pass when running with `yarn test`, but when I attempt to run WallabyJS in VSCode, I get this error:

```
Failed to initialize wallaby vitest. 
Required dependency '@vitest/runner' not found. If you are using pnpm, please refer to our docs: (https://wallabyjs.com/docs/integration/vitest.html#using-pnpm) 
Error: Required dependency '@vitest/runner' not found. If you are using pnpm, please refer to our docs: (https://wallabyjs.com/docs/integration/vitest.html#using-pnpm) 
```

I looked at the Wallaby docs, but the page for Yarn only mentions additional config for Jest, and the page for VItest only mentions additional config for pnpm. Does vitest require additional config for yarn 2 or later?

I also noticed that if there's no node_modules folder at all (since yarn doesn't create one itself), then attempting to run WallabyJS creates a `node_modules` symlink that is pointing to itself.

```
$ ls -l node_modules 
lrwxr-xr-x  1 lachlanhunt  staff  45 24 Aug 13:36 node_modules -> /Users/lachlanhunt/Sites/sandbox/node_modules
```

 Subsequently running `yarn test` gives an error.

```
Error: ELOOP: too many symbolic links encountered, mkdir '/Users/lachlanhunt/Sites/sandbox/node_modules/.vite/vitest'
```

Deleting the node_modules symlink fixes that. Creating an empty `node_modules` folder prevents Wallaby creating a symlink in its place.

### Wallaby diagnostics report

```
{
  editorVersion: '1.92.2',
  pluginVersion: '1.0.381',
  editorType: 'VSCode',
  osVersion: 'darwin 24.0.0',
  nodeVersion: 'v21.7.1',
  coreVersion: '1.0.1594',
  pnp: '--require <homeDir>/Sites/sandbox/.pnp.cjs',
  pnpEsm: '--experimental-loader <homeDir>/Sites/sandbox/.pnp.loader.mjs',
  checksum: 'NThkYTlmNzAyMDMwZjY3OTBhMmMzZWI4ZDNlYjZkMTcsMTc0MjE2OTYwMDAwMCww',
  config: {
    diagnostics: {
      vitest: {
        file: {
          config: "import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react-swc'\n\n// https://vitejs.dev/config/\nexport default defineConfig({\n  plugins: [react()],\n})\n"
        },
        config: {
          config: {
            allowOnly: true,
            isolate: true,
            watch: true,
            globals: false,
            environment: 'node',
            pool: 'forks',
            clearMocks: false,
            restoreMocks: false,
            mockReset: false,
            unstubGlobals: false,
            unstubEnvs: false,
            include: [ '**/*.{test,spec}.?(c|m)[jt]s?(x)' ],
            exclude: [
              '**/node_modules/**',
              '**/dist/**',
              '**/cypress/**',
              '**/.{idea,git,cache,output,temp}/**',
              '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
            ],
            teardownTimeout: 10000,
            forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**' ],
            update: false,
            reporters: [ [ 'default', {} ] ],
            silent: false,
            hideSkippedTests: false,
            api: { middlewareMode: true },
            ui: false,
            uiBase: '/__vitest__/',
            open: true,
            css: { include: [], modules: { classNameStrategy: 'stable' } },
            coverage: {
              provider: 'v8',
              enabled: false,
              all: true,
              clean: true,
              cleanOnRerun: true,
              reportsDirectory: './coverage',
              exclude: [
                'coverage/**',
                'dist/**',
                '**/node_modules/**',
                '**/[.]**',
                'packages/*/test?(s)/**',
                '**/*.d.ts',
                '**/virtual:*',
                '**/__x00__*',
                '**/\x00*',
                'cypress/**',
                'test?(s)/**',
                'test?(-*).?(c|m)[jt]s?(x)',
                '**/*{.,-}{test,spec,bench,benchmark}?(-d).?(c|m)[jt]s?(x)',
                '**/__tests__/**',
                '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
                '**/vitest.{workspace,projects}.[jt]s?(on)',
                '**/.{eslint,mocha,prettier}rc.{?(c|m)js,yml}'
              ],
              reportOnFailure: false,
              reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
              extension: [
                '.js',     '.cjs',
                '.mjs',    '.ts',
                '.mts',    '.tsx',
                '.jsx',    '.vue',
                '.svelte', '.marko'
              ],
              allowExternal: false,
              ignoreEmptyLines: true,
              processingConcurrency: 12
            },
            fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
            maxConcurrency: 5,
            dangerouslyIgnoreUnhandledErrors: false,
            typecheck: {
              checker: 'tsc',
              include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
              exclude: [
                '**/node_modules/**',
                '**/dist/**',
                '**/cypress/**',
                '**/.{idea,git,cache,output,temp}/**',
                '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
              ],
              enabled: false
            },
            slowTestThreshold: 300,
            disableConsoleIntercept: false,
            poolOptions: { threads: {}, forks: {} },
            config: '<homeDir>/Sites/sandbox/vite.config.ts',
            defines: {},
            root: '<homeDir>/Sites/sandbox',
            mode: 'test',
            inspector: { enabled: false, waitForDebugger: false },
            clearScreen: true,
            browser: { enabled: false, headless: false, isolate: true, fileParallelism: true, ui: true, screenshotFailures: false, viewport: { width: 414, height: 896 }, api: { port: 63315 } },
            fileParallelism: true,
            expect: {},
            deps: {
              moduleDirectories: [ '/node_modules/' ],
              optimizer: { ssr: { enabled: true }, web: { enabled: true } },
              web: { transformAssets: true, transformCss: true, transformGlobPattern: [] }
            },
            server: { deps: { inline: [ {}, {}, {} ], moduleDirectories: [ '/node_modules/' ], cacheDir: 'node_modules/.vite' } },
            snapshotOptions: { expand: false, snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
            snapshotSerializers: [],
            poolMatchGlobs: [],
            setupFiles: [],
            globalSetup: [],
            cache: { dir: '<homeDir>/Sites/sandbox/node_modules/.vite/vitest' },
            sequence: { hooks: 'stack' },
            environmentMatchGlobs: [],
            testTransformMode: {},
            testTimeout: 5000,
            hookTimeout: 10000
          },
          projects: [
            {
              path: '<homeDir>/Sites/sandbox',
              config: {
                allowOnly: true,
                isolate: true,
                watch: true,
                globals: false,
                environment: 'node',
                pool: 'forks',
                clearMocks: false,
                restoreMocks: false,
                mockReset: false,
                unstubGlobals: false,
                unstubEnvs: false,
                include: [ '**/*.{test,spec}.?(c|m)[jt]s?(x)' ],
                exclude: [
                  '**/node_modules/**',
                  '**/dist/**',
                  '**/cypress/**',
                  '**/.{idea,git,cache,output,temp}/**',
                  '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
                ],
                teardownTimeout: 10000,
                forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**' ],
                update: false,
                reporters: [ [ 'default', {} ] ],
                silent: false,
                hideSkippedTests: false,
                api: { middlewareMode: true },
                ui: false,
                uiBase: '/__vitest__/',
                open: true,
                css: { include: [], modules: { classNameStrategy: 'stable' } },
                coverage: {
                  provider: 'v8',
                  enabled: false,
                  all: true,
                  clean: true,
                  cleanOnRerun: true,
                  reportsDirectory: './coverage',
                  exclude: [
                    'coverage/**',
                    'dist/**',
                    '**/node_modules/**',
                    '**/[.]**',
                    'packages/*/test?(s)/**',
                    '**/*.d.ts',
                    '**/virtual:*',
                    '**/__x00__*',
                    '**/\x00*',
                    'cypress/**',
                    'test?(s)/**',
                    'test?(-*).?(c|m)[jt]s?(x)',
                    '**/*{.,-}{test,spec,bench,benchmark}?(-d).?(c|m)[jt]s?(x)',
                    '**/__tests__/**',
                    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
                    '**/vitest.{workspace,projects}.[jt]s?(on)',
                    '**/.{eslint,mocha,prettier}rc.{?(c|m)js,yml}'
                  ],
                  reportOnFailure: false,
                  reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
                  extension: [
                    '.js',     '.cjs',
                    '.mjs',    '.ts',
                    '.mts',    '.tsx',
                    '.jsx',    '.vue',
                    '.svelte', '.marko'
                  ],
                  allowExternal: false,
                  ignoreEmptyLines: true,
                  processingConcurrency: 12
                },
                fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
                maxConcurrency: 5,
                dangerouslyIgnoreUnhandledErrors: false,
                typecheck: {
                  checker: 'tsc',
                  include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
                  exclude: [
                    '**/node_modules/**',
                    '**/dist/**',
                    '**/cypress/**',
                    '**/.{idea,git,cache,output,temp}/**',
                    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
                  ],
                  enabled: false
                },
                slowTestThreshold: 300,
                disableConsoleIntercept: false,
                poolOptions: { threads: {}, forks: {} },
                config: '<homeDir>/Sites/sandbox/vite.config.ts',
                defines: {},
                root: '<homeDir>/Sites/sandbox',
                mode: 'test',
                inspector: { enabled: false, waitForDebugger: false },
                clearScreen: true,
                browser: { enabled: false, headless: false, isolate: true, fileParallelism: true, ui: true, screenshotFailures: false, viewport: { width: 414, height: 896 }, api: { port: 63315 } },
                fileParallelism: true,
                expect: {},
                deps: {
                  moduleDirectories: [ '/node_modules/' ],
                  optimizer: { ssr: { enabled: true }, web: { enabled: true } },
                  web: { transformAssets: true, transformCss: true, transformGlobPattern: [] }
                },
                server: { deps: { inline: [ {}, {}, {} ], moduleDirectories: [ '/node_modules/' ], cacheDir: 'node_modules/.vite' } },
                snapshotOptions: { expand: false, snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
                snapshotSerializers: [],
                poolMatchGlobs: [],
                setupFiles: [],
                globalSetup: [],
                cache: { dir: '<homeDir>/Sites/sandbox/node_modules/.vite/vitest' },
                sequence: { hooks: 'stack' },
                environmentMatchGlobs: [],
                testTransformMode: {},
                testTimeout: 5000,
                hookTimeout: 10000
              }
            }
          ],
          package: {
            version: '2.0.5',
            urls: { hooks: 'file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyb9c27a/runners/node/hooks.mjs' },
            paths: {
              root: '<homeDir>/Sites/sandbox/.yarn/__virtual__/vitest-virtual-e78256417d/3/.yarn/berry/cache/vitest-npm-2.0.5-3ee23fccc7-10c0.zip/node_modules/vitest',
              dist: '<homeDir>/Sites/sandbox/.yarn/__virtual__/vitest-virtual-e78256417d/3/.yarn/berry/cache/vitest-npm-2.0.5-3ee23fccc7-10c0.zip/node_modules/vitest/dist'
            }
          }
        }
      }
    },
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0', autoDetected: true },
    preserveComments: false,
    extractComments: true,
    files: [
      { pattern: '**/*.{test,spec}.?(c|m)[jt]s?(x)', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/*.timestamp-*', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/*.*', ignore: false, trigger: true, load: true, order: 1 }
    ],
    tests: [
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/*.{test,spec}.?(c|m)[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    workers: { initial: 1, regular: 1, recycle: false },
    dot: true,
    captureConsoleLog: true,
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 8192 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    maxTraceSteps: 999999,
    maxTraceStepsForWatchExpressionPrefetch: 0,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: {
      type: 'node',
      params: {},
      runner: '<homeDir>/Library/Application Support/fnm/node-versions/v21.7.1/installation/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: true,
    symlinkNodeModules: true,
    configCode: 'auto.detect#-1486913993'
  },
  packageJSON: {
    dependencies: { react: '^18.3.1', 'react-dom': '^18.3.1' },
    devDependencies: {
      '@eslint/js': '^9.9.0',
      '@types/react': '^18.3.3',
      '@types/react-dom': '^18.3.0',
      '@vitejs/plugin-react-swc': '^3.5.0',
      eslint: '^9.9.0',
      'eslint-plugin-react-hooks': '^5.1.0-rc.0',
      'eslint-plugin-react-refresh': '^0.4.9',
      globals: '^15.9.0',
      typescript: '^5.5.3',
      'typescript-eslint': '^8.0.1',
      vite: '^5.4.1',
      vitest: '^2.0.5'
    }
  },
  fs: { numberOfFiles: 34 },
  debug: [
    '2024-08-24T03:13:45.001Z project waiting for initial run signal\n',
    '2024-08-24T03:13:45.008Z model Initialization Completed: 272ms\n',
    '2024-08-24T03:13:45.013Z config Attempting automatic configuration for vitest\n',
    '2024-08-24T03:13:45.030Z vitest/config Detected Vitest (2.0.5).\n',
    '2024-08-24T03:13:46.874Z config Finished attempting automatic configuration for vitest (1861ms)\n',
    '2024-08-24T03:13:46.876Z project Wallaby Node version: v21.7.1\n',
    '2024-08-24T03:13:46.876Z project Wallaby config: <homeDir>/Sites/sandbox/auto.detect\n',
    '2024-08-24T03:13:46.938Z fs File system starting\n',
    '2024-08-24T03:13:46.977Z fs File system scan completed\n',
    '2024-08-24T03:13:46.984Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/projects/285085d58a626d48\n',
    '2024-08-24T03:13:47.122Z ui.service.legacy Listening port 51237\n',
    '2024-08-24T03:13:47.125Z project package.json file change detected, invalidating local cache\n',
    '2024-08-24T03:13:47.138Z workers Parallelism for initial run: 1, for regular run: 1\n',
    '2024-08-24T03:13:47.138Z workers Starting run worker instance #0\n',
    '2024-08-24T03:13:47.138Z workers Web server is listening at 64015\n',
    '2024-08-24T03:13:47.139Z project File cache requires some updates, waiting required files from IDE\n',
    '2024-08-24T03:13:47.211Z project Stopping process pool\n',
    '2024-08-24T03:13:47.213Z project Test run started; run priority: 3\n',
    '2024-08-24T03:13:47.214Z project Running all tests\n',
    '2024-08-24T03:13:47.227Z workers Starting test run, priority: 3\n',
    '2024-08-24T03:13:47.228Z nodeRunner Starting sandbox [worker #0, session #44c3k]\n',
    '2024-08-24T03:13:47.228Z nodeRunner Preparing sandbox [worker #0, session #44c3k]\n',
    '2024-08-24T03:13:47.517Z workers Started run worker instance (delayed) #0\n',
    '2024-08-24T03:13:47.517Z nodeRunner Prepared sandbox [worker #0, session #44c3k]\n',
    '2024-08-24T03:13:47.517Z workers [worker #0, session #44c3k] Running tests in sandbox\n',
    '2024-08-24T03:13:47.555Z workers Sandbox (active) [44c3k] error: Failed to initialize wallaby vitest.\n' +
      "Required dependency '@vitest/runner' not found. If you are using pnpm, please refer to our docs: (https://wallabyjs.com/docs/integration/vitest.html#using-pnpm)\n" +
      "Error: Required dependency '@vitest/runner' not found. If you are using pnpm, please refer to our docs: (https://wallabyjs.com/docs/integration/vitest.html#using-pnpm)\n",
    '2024-08-24T03:13:47.657Z workers [44c3k] Run 0 test(s), skipped 0 test(s)\n',
    '2024-08-24T03:13:47.658Z workers [44c3k] Sandbox is responsive, closing it\n',
    '2024-08-24T03:13:47.659Z workers Failed to map the stack to user code, entry message: Failed to initialize wallaby vitest.\n' +
      "Required dependency '@vitest/runner' not found. If you are using pnpm, please refer to our docs: (https://wallabyjs.com/docs/integration/vitest.html#using-pnpm)\n" +
      "Error: Required dependency '@vitest/runner' not found. If you are using pnpm, please refer to our docs: (https://wallabyjs.com/docs/integration/vitest.html#using-pnpm), stack: Failed to initialize wallaby vitest.\n" +
      "Required dependency '@vitest/runner' not found. If you are using pnpm, please refer to our docs: (https://wallabyjs.com/docs/integration/vitest.html#using-pnpm)\n" +
      "Error: Required dependency '@vitest/runner' not found. If you are using pnpm, please refer to our docs: (https://wallabyjs.com/docs/integration/vitest.html#using-pnpm)\n" +
      '    at initializeVitest (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyb9c27a/runners/node/vitest@0.14.0/initializer.js:14:6240)\n' +
      '    at async a._onStart (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.381/wallabyb9c27a/runners/node/vitest@0.14.0/initializer.js:14:43160)\n',
    '2024-08-24T03:13:47.660Z project Test run finished\n',
    '2024-08-24T03:13:47.661Z project Processed console.log entries\n',
    '2024-08-24T03:13:47.661Z project Processed loading sequences\n',
    '2024-08-24T03:13:47.661Z project Processed executed tests\n',
    '2024-08-24T03:13:47.661Z project Processed code coverage\n',
    '2024-08-24T03:13:47.667Z project Test run result processed and sent to IDE\n',
    '2024-08-24T03:18:19.755Z fs No metadata for added file found: vite.config.ts.timestamp-1724469499462-f01433c0a8435.mjs\n',
    '2024-08-24T03:18:20.858Z fs No metadata for deleted file found: vite.config.ts.timestamp-1724469499462-f01433c0a8435.mjs\n',
    '2024-08-24T03:18:21.810Z fs No metadata for added file found: node_modules/.vite/vitest/results.json\n'
  ]
}
```

**Comment by lachlanhunt** [comment]
I created a sample repo to reproduce the issue.

https://github.com/lachlanhunt/sandbox/tree/wallabyjs-issue-3393
