### ISSUE TITLE
Wallaby.js auto-detects jest even though there’s no Jest configuration

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/public#3404]
Wallaby.js auto-detects jest even though there’s no Jest configuration or direct dependency in my project. The only way I got it to work was by manually creating a wallaby.js file:
```js
module.exports = () => ({
  autoDetect: true,

  // specify non-standard vitest configuration file path
  testFramework: {
    configFile: "./vitest.workspace.ts",
  },
})
```

In my [Vitest configuration](https://vitest.dev/guide/workspace) (vitest.workspace.ts), I defined the workspace like this:
```typescript
import { defineWorkspace } from 'vitest/config'

export default defineWorkspace([
  "apps/app", //"packages/*", "libs/*"
])
```

However, after setting this up, I encountered the following error:

```
console.error: 'failed to load config from {PATH TO}/vitest.workspace.ts'
​​[Error] Runtime error: Failed to initialize wallaby vitest.​​
​​[Error] config must export or return an object.​​
​​[Error] Error: config must export or return an object.​​
​​[Error]     at loadConfigFromFile (file://<rootDir>/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:66483:13)​​
​​[Error]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)​​
​​[Error]     at async resolveConfig (file://<rootDir>/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:66083:24)​​
​​[Error]     at async _createServer (file://<rootDir>/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:62701:18)​​
​​[Error]     at async createViteServer (file://<rootDir>/node_modules/vitest/dist/chunks/cli-api.CHxC4-U8.js:9345:18)​​
​​[Error]     at async createVitest (file://<rootDir>/node_modules/vitest/dist/chunks/cli-api.CHxC4-U8.js:11201:18)​​
​​[Error]     at async prepareVitest (file://<rootDir>/node_modules/vitest/dist/chunks/cli-api.CHxC4-U8.js:11615:15)​​
​​[Error]     at async Module.startVitest (file://<rootDir>/node_modules/vitest/dist/chunks/cli-api.CHxC4-U8.js:11541:15)​​

_Originally posted by @stijnvanderlaan in https://github.com/wallabyjs/public/issues/3402#issuecomment-2402384164_

**Comment by smcenlly** [comment]
By default Wallaby's `autoDetect` feature tries to detect frameworks in the following order:

```javascript
module.exports = function (wallaby) {
  return {
    // Default `true` setting will detect and configure
    // in the following order: ['angular', 'jest', 'vitest', 'node:test']
  };
};
```

If you have `vitest` as a direct dependency of your project, the order is changed to:

```javascript
module.exports = function (wallaby) {
  return {
    // Default `true` setting will detect and configure
    // in the following order: ['vitest', 'angular', 'jest', 'node:test']
  };
};
```

---

Jest and vitest also allow you to specify a `testFramework.configFile`. Without your [diagnostic report](https://wallabyjs.com/docs/intro/troubleshooting.html#diagnostics-report), we can't confirm, but in your case, it looks like the testFramework order is our default (`['angular', 'jest', 'vitest', 'node:test']`) and jest is installed as a transitive dependency. When you define a configFile `vitest.workspace.ts`, this is actually making jest fail to load, and then vitest succeeds.

While your current configuration may work for you, it would be better to change your configuration to:

```javascript
// Note: you may also provide this configuration via your `package.json`
module.exports = () => ({
  autoDetect: ['vitest']
})
```

**Comment by stijnvanderlaan** [comment]
Right, thnx for clearing that up!
