### ISSUE TITLE
Wallaby V.2x Angular 18.2 Jasmine

### ISSUE THREAD

**Issue by alexander-kastil** [wallabyjs/public#3413]
### Issue description or question

After forcing the Update to Wallaby 2.0 and setting configuration to automatic, an existing Angular project that has been tested before using Wallaby 1.x does nothing when "wallaby start" has been executed. Stuck on post precessing files in wallaby console

### Wallaby diagnostics report

```
{
  editorVersion: '1.94.2',
  pluginVersion: '1.0.389',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.22631',
  nodeVersion: 'v22.3.0',
  coreVersion: '1.0.1615',
  pnp: '<not set>',
  pnpEsm: '<not set>',
  checksum: 'ZDQyM2Q0ZWE2ZTUwN2YwNjg2ZmIwYjRmZTQxMTA0NTEsMTc1NzYzNTIwMDAwMCww',
  config: {
    diagnostics: {
      angular: {
        workspace: {
          '$schema': './node_modules/@angular/cli/lib/config/schema.json',
          version: 1,
          newProjectRoot: 'projects',
          projects: {
            'jasmine-testing': {
              projectType: 'application',
              schematics: { '@schematics/angular:component': { style: 'scss' } },
              root: '',
              sourceRoot: 'src',
              prefix: 'app',
              architect: {
                build: {
                  builder: '@angular-devkit/build-angular:browser-esbuild',
                  options: {
                    outputPath: 'dist/jasmine-testing',
                    index: 'src/index.html',
                    main: 'src/main.ts',
                    polyfills: 'src/polyfills.ts',
                    tsConfig: 'tsconfig.app.json',
                    inlineStyleLanguage: 'scss',
                    assets: [ 'src/favicon.ico', 'src/assets' ],
                    styles: [ 'src/styles.scss', 'node_modules/prismjs/themes/prism-okaidia.min.css', 'node_modules/prismjs/plugins/line-highlight/prism-line-highlight.min.css' ],
                    stylePreprocessorOptions: { includePaths: [ 'src/theme' ] },
                    scripts: [
                      'node_modules/marked/marked.min.js',
                      'node_modules/prismjs/prism.js',
                      'node_modules/prismjs/components/prism-csharp.min.js',
                      'node_modules/prismjs/components/prism-typescript.min.js',
                      'node_modules/prismjs/components/prism-css.min.js',
                      'node_modules/prismjs/plugins/line-highlight/prism-line-highlight.min.js'
                    ]
                  },
                  configurations: {
                    production: {
                      budgets: [ { type: 'initial', maximumWarning: '500kb', maximumError: '1mb' }, { type: 'anyComponentStyle', maximumWarning: '2kb', maximumError: '4kb' } ],
                      fileReplacements: [ { replace: 'src/environments/environment.ts', with: 'src/environments/environment.prod.ts' } ],
                      outputHashing: 'all'
                    },
                    development: { buildOptimizer: false, optimization: false, vendorChunk: true, extractLicenses: false, sourceMap: true, namedChunks: true }
                  },
                  defaultConfiguration: 'production'
                },
                serve: {
                  builder: '@angular-devkit/build-angular:dev-server',
                  configurations: { production: { buildTarget: 'jasmine-testing:build:production' }, development: { buildTarget: 'jasmine-testing:build:development' } },
                  defaultConfiguration: 'development'
                },
                'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { buildTarget: 'jasmine-testing:build' } },
                test: {
                  builder: '@angular-devkit/build-angular:karma',
                  options: {
                    main: 'src/test.ts',
                    polyfills: 'src/polyfills.ts',
                    tsConfig: 'tsconfig.spec.json',
                    karmaConfig: 'karma.conf.js',
                    inlineStyleLanguage: 'scss',
                    assets: [ 'src/favicon.ico', 'src/assets' ],
                    styles: [ 'src/styles.scss', 'node_modules/prismjs/themes/prism-okaidia.min.css', 'node_modules/prismjs/plugins/line-highlight/prism-line-highlight.min.css' ],
                    stylePreprocessorOptions: { includePaths: [ 'src/theme' ] },
                    scripts: [
                      'node_modules/marked/marked.min.js',
                      'node_modules/prismjs/prism.js',
                      'node_modules/prismjs/components/prism-csharp.min.js',
                      'node_modules/prismjs/components/prism-typescript.min.js',
                      'node_modules/prismjs/components/prism-css.min.js',
                      'node_modules/prismjs/plugins/line-highlight/prism-line-highlight.min.js'
                    ]
                  }
                }
              }
            }
          },
          cli: { analytics: '9c057ce0-a02e-414c-b3c0-f33f626d3b71', cache: { enabled: false } }
        },
        main: '// This file is required by karma.conf.js and loads recursively all the .spec and framework files\r\n' +
          '\r\n' +
          "import 'zone.js/testing';\r\n" +
          "import { getTestBed } from '@angular/core/testing';\r\n" +
          'import {\r\n' +
          '  BrowserDynamicTestingModule,\r\n' +
          '  platformBrowserDynamicTesting\r\n' +
          "} from '@angular/platform-browser-dynamic/testing';\r\n" +
          '\r\n' +
          '// First, initialize the Angular testing environment.\r\n' +
          'getTestBed().initTestEnvironment(\r\n' +
          '  BrowserDynamicTestingModule,\r\n' +
          '  platformBrowserDynamicTesting(),\r\n' +
          ');\r\n'
      }
    },
    testFramework: { version: 'jasmine@4.6.0', configurator: 'jasmine@4.6.0', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3', autoDetected: true },
    env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    files: [
      { pattern: 'src/**/*.spec.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/polyfills.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/test.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/main.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/index.html', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/test.base.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: 'src/test.wallaby.ts', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'node_modules/marked/marked.min.js', instrument: false, load: true, ignore: false, trigger: true, order: 2 },
      { pattern: 'node_modules/prismjs/prism.js', instrument: false, load: true, ignore: false, trigger: true, order: 3 },
      { pattern: 'node_modules/prismjs/components/prism-csharp.min.js', instrument: false, load: true, ignore: false, trigger: true, order: 4 },
      { pattern: 'node_modules/prismjs/components/prism-typescript.min.js', instrument: false, load: true, ignore: false, trigger: true, order: 5 },
      { pattern: 'node_modules/prismjs/components/prism-css.min.js', instrument: false, load: true, ignore: false, trigger: true, order: 6 },
      { pattern: 'node_modules/prismjs/plugins/line-highlight/prism-line-highlight.min.js', instrument: false, load: true, ignore: false, trigger: true, order: 7 },
      { pattern: 'src/**/*.+(ts|js)', load: false, ignore: false, trigger: true, order: 8 },
      { pattern: 'src/**/*.+(css|less|scss|sass|styl|html|json|svg)', instrument: false, load: false, ignore: false, trigger: true, order: 9 }
    ],
    tests: [ { pattern: 'src/**/*.spec.ts', load: false, ignore: false, trigger: true, test: true, order: 10 } ],
    captureConsoleLog: true,
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 8192 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    maxTraceSteps: 999999,
    maxTraceStepsForWatchExpressionPrefetch: 10,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: false,
    configCode: 'auto.detect#1467677587'
  },
  packageJSON: {
    dependencies: {
      '@angular/animations': '^18.2.3',
      '@angular/cdk': '^18.2.3',
      '@angular/common': '^18.2.3',
      '@angular/compiler': '^18.2.3',
      '@angular/core': '^18.2.3',
      '@angular/fire': '^18.0.1',
      '@angular/forms': '^18.2.3',
      '@angular/material': '^18.2.3',
      '@angular/platform-browser': '^18.2.3',
      '@angular/platform-browser-dynamic': '^18.2.3',
      '@angular/router': '^18.2.3',
      '@ngrx/data': '^18.0.2',
      '@ngrx/effects': '^18.0.2',
      '@ngrx/entity': '^18.0.2',
      '@ngrx/operators': '^18.0.0',
      '@ngrx/store': '^18.0.2',
      cypress: '^13.14.2',
      firebase: '^10.13.1',
      lodash: '^4.17.21',
      marked: '9.1.6',
      'ngx-markdown': '^18.0.0',
      prismjs: '^1.29.0',
      rxjs: '~7.8.0',
      tslib: '^2.3.0',
      'zone.js': '~0.14.10'
    },
    devDependencies: {
      '@angular-devkit/build-angular': '^18.2.3',
      '@angular/cli': '~18.2.3',
      '@angular/compiler-cli': '^18.2.3',
      '@ngrx/schematics': '^18.0.2',
      '@ngrx/store-devtools': '^18.0.2',
      '@types/jasmine': '~4.3.0',
      '@types/lodash': '^4.14.182',
      'jasmine-core': '~4.5.0',
      karma: '~6.4.0',
      'karma-chrome-launcher': '~3.1.0',
      'karma-coverage': '~2.2.0',
      'karma-jasmine': '~5.1.0',
      'karma-jasmine-html-reporter': '~2.0.0',
      typescript: '~5.5.4'
    }
  },
  fs: { numberOfFiles: 270 },
  debug: [
    '2024-10-27T08:01:04.020Z project waiting for initial run signal\n',
    '2024-10-27T08:01:04.023Z model Initialization Completed: 145ms\n',
    '2024-10-27T08:01:04.080Z config Attempting automatic configuration for angular\n',
    '2024-10-27T08:01:04.085Z angular/cli config Detected Angular CLI.\n',
    '2024-10-27T08:01:04.087Z angular/cli config Angular currentDirPath: "D:\\git-classes\\ng-adv-17\\demos\\06-testing\\jasmine-testing", workspaceDirPath: "D:\\git-classes\\ng-adv-17\\demos\\06-testing\\jasmine-testing"\n',
    '2024-10-27T08:01:04.720Z ui.service Starting UI service on port: 55000\n',
    '2024-10-27T08:01:04.721Z ui.service UI service started on port: 55000\n',
    '2024-10-27T08:01:04.883Z websocket received message ui.trackOverviewTestList\n',
    '2024-10-27T08:01:04.883Z websocket received method call: trackOverviewTestList\n',
    '2024-10-27T08:01:04.883Z websocket received message ui.trackAllLogsAndErrors\n',
    '2024-10-27T08:01:04.883Z websocket received method call: trackAllLogsAndErrors\n',
    '2024-10-27T08:01:04.884Z websocket received message ui.trackStatus\n',
    '2024-10-27T08:01:04.884Z websocket received method call: trackStatus\n',
    '2024-10-27T08:01:04.884Z websocket received message ui.trackTestRun\n',
    '2024-10-27T08:01:04.884Z websocket received method call: trackTestRun\n',
    '2024-10-27T08:01:04.884Z websocket received message ui.trackStartupEvents\n',
    '2024-10-27T08:01:04.884Z websocket received method call: trackStartupEvents\n',
    '2024-10-27T08:01:04.885Z websocket received message ui.trackStats\n',
    '2024-10-27T08:01:04.885Z websocket received method call: trackStats\n',
    '2024-10-27T08:01:04.885Z websocket received message ui.trackStatus\n',
    '2024-10-27T08:01:04.885Z websocket received method call: trackStatus\n',
    '2024-10-27T08:01:04.885Z websocket received message ui.trackTestRun\n',
    '2024-10-27T08:01:04.885Z websocket received method call: trackTestRun\n',
    '2024-10-27T08:01:04.885Z websocket received message ui.handshake\n',
    '2024-10-27T08:01:04.885Z websocket received method call: handshake\n',
    '2024-10-27T08:01:04.885Z websocket received message ui.trackEditorCursor\n',
    '2024-10-27T08:01:04.885Z websocket received method call: trackEditorCursor\n',
    '2024-10-27T08:01:04.885Z websocket received message ui.trackStatus\n',
    '2024-10-27T08:01:04.885Z websocket received method call: trackStatus\n',
    '2024-10-27T08:01:05.137Z angular/cli karma project config Using virtual D:/git-classes/ng-adv-17/demos/06-testing/jasmine-testing/src/test.ts.\n',
    '2024-10-27T08:01:05.154Z config Finished attempting automatic configuration for angular (1074ms)\n',
    '2024-10-27T08:01:05.154Z project Wallaby Node version: v22.3.0\n',
    '2024-10-27T08:01:05.154Z project Wallaby config: D:\\git-classes\\ng-adv-17\\demos\\06-testing\\jasmine-testing\\auto.detect\n',
    '2024-10-27T08:01:05.179Z fs File system starting\n',
    '2024-10-27T08:01:05.299Z fs File system scan completed\n',
    '2024-10-27T08:01:05.301Z project File cache: C:\\Users\\AlexanderKastil\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.389\\projects\\2891cbaab7532b9c\n',
    '2024-10-27T08:01:05.321Z chromeRunner launch new instance (path: <default>, flags: --headless=old --disable-gpu --deterministic-fetch)\n',
    '2024-10-27T08:01:05.323Z workers Parallelism for initial run: 30, for regular run: 15\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #0\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #1\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #2\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #3\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #4\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #5\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #6\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #7\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #8\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #9\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #10\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #11\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #12\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #13\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #14\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #15\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #16\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #17\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #18\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #19\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #20\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #21\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #22\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #23\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #24\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #25\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #26\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #27\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #28\n',
    '2024-10-27T08:01:05.323Z workers Starting run worker instance #29\n',
    '2024-10-27T08:01:05.325Z workers Web server is listening at 65502\n',
    '2024-10-27T08:01:05.334Z project Stopping process pool\n',
    '2024-10-27T08:01:05.334Z project File cache is up-to-date, starting full test run\n',
    '2024-10-27T08:01:05.335Z project Running postprocessor\n',
    '2024-10-27T08:01:05.337Z postprocessor Processing started.\n',
    '2024-10-27T08:01:05.337Z postprocessor Initializing.\n',
    '2024-10-27T08:01:05.337Z postprocessor Initializing entry.\n',
    '2024-10-27T08:01:05.337Z postprocessor Sanitizing configuration.\n',
    '2024-10-27T08:01:05.337Z postprocessor Adjusting configuration.\n',
    '2024-10-27T08:01:05.339Z postprocessor Creating compiler.\n',
    '2024-10-27T08:01:05.458Z postprocessor Customizing compiler.\n',
    '2024-10-27T08:01:05.458Z postprocessor Compilation started.\n',
    '2024-10-27T08:01:06.733Z chromeRunner Connection to Chrome Debugger Protocol on 127.0.0.1:65501 failed: Error: connect ECONNREFUSED 127.0.0.1:65501\n',
    '2024-10-27T08:01:07.493Z chromeRunner Connection to Chrome Debugger Protocol on 127.0.0.1:65501 succeeded\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #0\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #1\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #2\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #3\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #4\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #5\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #6\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #7\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #8\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #9\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #10\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #11\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #12\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #13\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #14\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #15\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #16\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #17\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #18\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #19\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #20\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #21\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #22\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #23\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #24\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #25\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #26\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #27\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #28\n',
    '2024-10-27T08:01:07.494Z workers Started run worker instance (immediate) #29\n',
    "2024-10-27T08:01:11.609Z project Error: Module not found: Error: Can't resolve './form-control.component' in 'D:\\git-classes\\ng-adv-17\\demos\\06-testing\\jasmine-testing\\src\\app\\demos\\samples\\component-class'\n" +
      '@ ./src/app/demos/samples/component-class/form-control.component.spec.ts\n' +
      '    at n.process (c:\\Users\\AlexanderKastil\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.389\\wallabya829f1\\server.js:192:120803)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async Project._performPostProcessing (c:\\Users\\AlexanderKastil\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.389\\wallabya829f1\\server.js:498:30944)\n' +
      '    at async Timeout._onTimeout (c:\\Users\\AlexanderKastil\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.389\\wallabya829f1\\server.js:498:33137)\n',
    '2024-10-27T08:01:11.610Z project Test run finished\n',
    '2024-10-27T08:01:11.610Z project Test run data re-queued\n'
  ]
}
```

**Comment by smcenlly** [comment]
Thanks for reporting the issue.

The new Wallaby UI was not correctly reporting errors that occurred when your files couldn't be bundled during startup. This has been fixed in the latest version of Wallaby core, `v1.0.1617`.

In your case, it looks like you have an error in your source code that you will need to fix:

```
Module not found: Error: Can't resolve './form-control.component' in 
       D:\\git-classes\\ng-adv-17\\demos\\06-testing\\jasmine-testing\\src\\app\\demos\\samples\\component-class
       @ ./src/app/demos/samples/component-class/form-control.component.spec.ts
```

**Comment by alexander-kastil** [comment]
> Thanks for reporting the issue.
> 
> The new Wallaby UI was not correctly reporting errors that occurred when your files couldn't be bundled during startup. This has been fixed in the latest version of Wallaby core, `v1.0.1617`.
> 
> In your case, it looks like you have an error in your source code that you will need to fix:
> 
> ```
> Module not found: Error: Can't resolve './form-control.component' in 
>        D:\\git-classes\\ng-adv-17\\demos\\06-testing\\jasmine-testing\\src\\app\\demos\\samples\\component-class
>        @ ./src/app/demos/samples/component-class/form-control.component.spec.ts
> ```

Thanks ... found it out that there was a build error for the tests, but as you said it was not reported properly
