### ISSUE TITLE
Vitest 2.1.4 is broken

### ISSUE THREAD

**Issue by jgoz** [wallabyjs/public#3416]
### Issue description or question

I happened to upgrade to vitest 2.1.4 and saw this.

```
Failed to initialize wallaby vitest.
Initialization: Wallaby is not compatible with current version of Vitest.
Could not find GlobalSetupPlugin in entry point for file file:///path/to/repo/node_modules/.pnpm/vitest@2.1.4_@types+node@22.8.1_jsdom@25.0.1/node_modules/vitest/dist/chunks/cli-api.CKrRYkw8.js.
```

It must have been a very recent change because 2.1.3 works fine.

### Wallaby diagnostics report

```
{
  editorVersion: '1.94.2',
  pluginVersion: '1.0.389',
  editorType: 'VSCode',
  osVersion: 'darwin 23.6.0',
  nodeVersion: 'v20.13.1',
  coreVersion: '1.0.1616',
  pnp: '<not set>',
  pnpEsm: '<not set>',
  checksum: 'OGI1Yjg0OWVmMmQwNWM4NGU5OWYzYzcyNmY1YzM0NTAsMTc0NzUyNjQwMDAwMCww',
  config: {
    diagnostics: {
      vitest: {
        config: {
          config: {
            allowOnly: true,
            isolate: true,
            watch: true,
            globals: false,
            environment: 'node',
            pool: 'forks',
            clearMocks: false,
            restoreMocks: false,
            mockReset: false,
            unstubGlobals: false,
            unstubEnvs: false,
            include: [ '**/*.{test,spec}.?(c|m)[jt]s?(x)' ],
            exclude: [
              '**/node_modules/**',
              '**/dist/**',
              '**/cypress/**',
              '**/.{idea,git,cache,output,temp}/**',
              '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
            ],
            teardownTimeout: 10000,
            forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**' ],
            update: false,
            reporters: [ [ 'default', {} ] ],
            silent: false,
            hideSkippedTests: false,
            api: { middlewareMode: true },
            ui: false,
            uiBase: '/__vitest__/',
            open: true,
            css: { include: [], modules: { classNameStrategy: 'stable' } },
            coverage: {
              provider: 'v8',
              enabled: false,
              all: true,
              clean: true,
              cleanOnRerun: true,
              reportsDirectory: './coverage',
              exclude: [
                'coverage/**',
                'dist/**',
                '**/node_modules/**',
                '**/[.]**',
                'packages/*/test?(s)/**',
                '**/*.d.ts',
                '**/virtual:*',
                '**/__x00__*',
                '**/\x00*',
                'cypress/**',
                'test?(s)/**',
                'test?(-*).?(c|m)[jt]s?(x)',
                '**/*{.,-}{test,spec,bench,benchmark}?(-d).?(c|m)[jt]s?(x)',
                '**/__tests__/**',
                '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
                '**/vitest.{workspace,projects}.[jt]s?(on)',
                '**/.{eslint,mocha,prettier}rc.{?(c|m)js,yml}'
              ],
              reportOnFailure: false,
              reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
              extension: [
                '.js',     '.cjs',
                '.mjs',    '.ts',
                '.mts',    '.tsx',
                '.jsx',    '.vue',
                '.svelte', '.marko',
                '.astro'
              ],
              allowExternal: false,
              excludeAfterRemap: false,
              ignoreEmptyLines: true,
              processingConcurrency: 12
            },
            fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
            maxConcurrency: 5,
            dangerouslyIgnoreUnhandledErrors: false,
            typecheck: {
              checker: 'tsc',
              include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
              exclude: [
                '**/node_modules/**',
                '**/dist/**',
                '**/cypress/**',
                '**/.{idea,git,cache,output,temp}/**',
                '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
              ],
              enabled: false
            },
            slowTestThreshold: 300,
            disableConsoleIntercept: false,
            poolOptions: { threads: {}, forks: {} },
            defines: {},
            root: '<homeDir>/dev/repo/packages/myproj',
            mode: 'test',
            provide: {},
            inspector: { enabled: false, waitForDebugger: false },
            clearScreen: true,
            browser: {
              enabled: false,
              headless: false,
              isolate: true,
              fileParallelism: true,
              ui: true,
              screenshotFailures: false,
              viewport: { width: 414, height: 896 },
              locators: { testIdAttribute: 'data-testid' },
              api: { port: 63315 }
            },
            fileParallelism: true,
            expect: {},
            deps: {
              moduleDirectories: [ '/node_modules/' ],
              optimizer: { ssr: { enabled: true }, web: { enabled: true } },
              web: { transformAssets: true, transformCss: true, transformGlobPattern: [] }
            },
            setupFiles: [],
            globalSetup: [],
            server: { deps: { inline: [ {}, {}, {} ], inlineFiles: [], moduleDirectories: [ '/node_modules/' ], cacheDir: 'node_modules/.vite' } },
            snapshotOptions: { expand: false, snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
            snapshotSerializers: [],
            poolMatchGlobs: [],
            cache: { dir: '<homeDir>/dev/repo/packages/myproj/node_modules/.vite/vitest' },
            sequence: { hooks: 'stack' },
            environmentMatchGlobs: [],
            testTransformMode: {},
            testTimeout: 5000,
            hookTimeout: 10000
          },
          projects: [
            {
              path: '<homeDir>/dev/repo/packages/myproj',
              config: {
                allowOnly: true,
                isolate: true,
                watch: true,
                globals: false,
                environment: 'node',
                pool: 'forks',
                clearMocks: false,
                restoreMocks: false,
                mockReset: false,
                unstubGlobals: false,
                unstubEnvs: false,
                include: [ '**/*.{test,spec}.?(c|m)[jt]s?(x)' ],
                exclude: [
                  '**/node_modules/**',
                  '**/dist/**',
                  '**/cypress/**',
                  '**/.{idea,git,cache,output,temp}/**',
                  '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
                ],
                teardownTimeout: 10000,
                forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**' ],
                update: false,
                reporters: [ [ 'default', {} ] ],
                silent: false,
                hideSkippedTests: false,
                api: { middlewareMode: true },
                ui: false,
                uiBase: '/__vitest__/',
                open: true,
                css: { include: [], modules: { classNameStrategy: 'stable' } },
                coverage: {
                  provider: 'v8',
                  enabled: false,
                  all: true,
                  clean: true,
                  cleanOnRerun: true,
                  reportsDirectory: './coverage',
                  exclude: [
                    'coverage/**',
                    'dist/**',
                    '**/node_modules/**',
                    '**/[.]**',
                    'packages/*/test?(s)/**',
                    '**/*.d.ts',
                    '**/virtual:*',
                    '**/__x00__*',
                    '**/\x00*',
                    'cypress/**',
                    'test?(s)/**',
                    'test?(-*).?(c|m)[jt]s?(x)',
                    '**/*{.,-}{test,spec,bench,benchmark}?(-d).?(c|m)[jt]s?(x)',
                    '**/__tests__/**',
                    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
                    '**/vitest.{workspace,projects}.[jt]s?(on)',
                    '**/.{eslint,mocha,prettier}rc.{?(c|m)js,yml}'
                  ],
                  reportOnFailure: false,
                  reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
                  extension: [
                    '.js',     '.cjs',
                    '.mjs',    '.ts',
                    '.mts',    '.tsx',
                    '.jsx',    '.vue',
                    '.svelte', '.marko',
                    '.astro'
                  ],
                  allowExternal: false,
                  excludeAfterRemap: false,
                  ignoreEmptyLines: true,
                  processingConcurrency: 12
                },
                fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
                maxConcurrency: 5,
                dangerouslyIgnoreUnhandledErrors: false,
                typecheck: {
                  checker: 'tsc',
                  include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
                  exclude: [
                    '**/node_modules/**',
                    '**/dist/**',
                    '**/cypress/**',
                    '**/.{idea,git,cache,output,temp}/**',
                    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
                  ],
                  enabled: false
                },
                slowTestThreshold: 300,
                disableConsoleIntercept: false,
                poolOptions: { threads: {}, forks: {} },
                defines: {},
                root: '<homeDir>/dev/repo/packages/myproj',
                mode: 'test',
                provide: {},
                inspector: { enabled: false, waitForDebugger: false },
                clearScreen: true,
                browser: {
                  enabled: false,
                  headless: false,
                  isolate: true,
                  fileParallelism: true,
                  ui: true,
                  screenshotFailures: false,
                  viewport: { width: 414, height: 896 },
                  locators: { testIdAttribute: 'data-testid' },
                  api: { port: 63315 }
                },
                fileParallelism: true,
                expect: {},
                deps: {
                  moduleDirectories: [ '/node_modules/' ],
                  optimizer: { ssr: { enabled: true }, web: { enabled: true } },
                  web: { transformAssets: true, transformCss: true, transformGlobPattern: [] }
                },
                setupFiles: [],
                globalSetup: [],
                server: { deps: { inline: [ {}, {}, {} ], inlineFiles: [], moduleDirectories: [ '/node_modules/' ], cacheDir: 'node_modules/.vite' } },
                snapshotOptions: { expand: false, snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
                snapshotSerializers: [],
                poolMatchGlobs: [],
                cache: { dir: '<homeDir>/dev/repo/packages/myproj/node_modules/.vite/vitest' },
                sequence: { hooks: 'stack' },
                environmentMatchGlobs: [],
                testTransformMode: {},
                testTimeout: 5000,
                hookTimeout: 10000
              }
            }
          ],
          package: {
            version: '2.1.4',
            urls: { hooks: 'file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.389/wallaby65cbc5/runners/node/hooks.mjs' },
            paths: {
              root: '<homeDir>/dev/repo/node_modules/.pnpm/vitest@2.1.4_@types+node@22.8.1_jsdom@25.0.1/node_modules/vitest',
              dist: '<homeDir>/dev/repo/node_modules/.pnpm/vitest@2.1.4_@types+node@22.8.1_jsdom@25.0.1/node_modules/vitest/dist'
            }
          }
        }
      }
    },
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0', autoDetected: true },
    preserveComments: false,
    extractComments: true,
    files: [
      { pattern: '**/*.{test,spec}.?(c|m)[jt]s?(x)', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/*.timestamp-*', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/*.*', ignore: false, trigger: true, load: true, order: 1 }
    ],
    tests: [
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/*.{test,spec}.?(c|m)[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    workers: { initial: 1, regular: 1, recycle: false },
    dot: true,
    captureConsoleLog: true,
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    smartStart: [ { test: true, source: false, pattern: '**/*', startMode: 'open' }, { test: false, source: true, pattern: '**/*', startMode: 'edit' } ],
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 8192 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    maxTraceSteps: 999999,
    maxTraceStepsForWatchExpressionPrefetch: 10,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: true,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '<homeDir>/.volta/tools/image/node/20.13.1/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: true,
    symlinkNodeModules: undefined,
    configCode: 'auto.detect#-1486913993',
    testLocations: [ 'src/general/general.spec.ts' ]
  },
  packageJSON: {
    dependencies: { 'axios-retry': '^3.1.1', 'has-own-prop': '^2.0.0', jssha: '^3.3.1', 'resize-observer-polyfill': '^1.5.1', tslib: '^2.8.0', uuid: '^11.0.2' },
    devDependencies: {
      '@myorg/config': 'workspace:*',
      '@myorg/tsconfig': 'workspace:*',
      '@testing-library/dom': 'catalog:',
      '@testing-library/react': 'catalog:',
      '@testing-library/user-event': '^14.5.2',
      '@types/node': 'catalog:',
      '@types/react': 'catalog:'
    }
  },
  fs: { numberOfFiles: 62 },
  debug: [
    '2024-10-28T21:52:29.571Z project waiting for initial run signal\n',
    '2024-10-28T21:52:29.574Z model Initialization Completed: 109ms\n',
    '2024-10-28T21:52:29.597Z config Attempting automatic configuration for angular\n',
    '2024-10-28T21:52:29.599Z angular/cli config Angular CLI not found.\n',
    '2024-10-28T21:52:29.599Z config Finished attempting automatic configuration for angular (2ms)\n',
    '2024-10-28T21:52:29.599Z config Attempting automatic configuration for jest\n',
    "2024-10-28T21:52:29.600Z jest/config Error: Module jest-cli is not found in '<homeDir>/dev/repo/packages/myproj'.\n" +
      '    at Object.loadJest (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.389/wallaby65cbc5/server.js:503:1080)\n' +
      '    at i (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.389/wallaby65cbc5/server.js:190:24826)\n' +
      '    at s.configure (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.389/wallaby65cbc5/server.js:190:28165)\n' +
      '    at automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.389/wallaby65cbc5/server.js:138:13141)\n' +
      '    at async automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.389/wallaby65cbc5/server.js:138:13018)\n' +
      '    at async automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.389/wallaby65cbc5/server.js:138:13018)\n' +
      '    at async Config.load (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.389/wallaby65cbc5/server.js:138:12958)\n' +
      '    at async Project.configure (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.389/wallaby65cbc5/server.js:490:2644)\n',
    '2024-10-28T21:52:29.600Z config Finished attempting automatic configuration for jest (1ms)\n',
    '2024-10-28T21:52:29.600Z config Attempting automatic configuration for vitest\n',
    '2024-10-28T21:52:29.601Z vitest/config Detected Vitest (2.1.4).\n',
    '2024-10-28T21:52:29.604Z ui.service Starting UI service on port: 55000\n',
    '2024-10-28T21:52:29.605Z ui.service UI service started on port: 55000\n',
    '2024-10-28T21:52:29.708Z websocket received message ui.trackOverviewTestList\n',
    '2024-10-28T21:52:29.708Z websocket received method call: trackOverviewTestList\n',
    '2024-10-28T21:52:29.709Z websocket received message ui.trackAllLogsAndErrors\n',
    '2024-10-28T21:52:29.709Z websocket received method call: trackAllLogsAndErrors\n',
    '2024-10-28T21:52:29.710Z websocket received message ui.trackStatus\n',
    '2024-10-28T21:52:29.710Z websocket received method call: trackStatus\n',
    '2024-10-28T21:52:29.710Z websocket received message ui.trackTestRun\n',
    '2024-10-28T21:52:29.710Z websocket received method call: trackTestRun\n',
    '2024-10-28T21:52:29.710Z websocket received message ui.trackStartupEvents\n',
    '2024-10-28T21:52:29.710Z websocket received method call: trackStartupEvents\n',
    '2024-10-28T21:52:29.710Z websocket received message ui.trackStats\n',
    '2024-10-28T21:52:29.710Z websocket received method call: trackStats\n',
    '2024-10-28T21:52:29.710Z websocket received message ui.trackStatus\n',
    '2024-10-28T21:52:29.710Z websocket received method call: trackStatus\n',
    '2024-10-28T21:52:29.711Z websocket received message ui.trackTestRun\n',
    '2024-10-28T21:52:29.711Z websocket received method call: trackTestRun\n',
    '2024-10-28T21:52:29.711Z websocket received message ui.handshake\n',
    '2024-10-28T21:52:29.711Z websocket received method call: handshake\n',
    '2024-10-28T21:52:29.711Z websocket received message ui.trackEditorCursor\n',
    '2024-10-28T21:52:29.711Z websocket received method call: trackEditorCursor\n',
    '2024-10-28T21:52:29.711Z websocket received message ui.trackStatus\n',
    '2024-10-28T21:52:29.711Z websocket received method call: trackStatus\n',
    '2024-10-28T21:52:29.839Z config Finished attempting automatic configuration for vitest (239ms)\n',
    '2024-10-28T21:52:29.840Z project Wallaby Node version: v20.13.1\n',
    '2024-10-28T21:52:29.840Z project Wallaby config: <homeDir>/dev/repo/packages/myproj/auto.detect\n',
    '2024-10-28T21:52:29.864Z fs File system starting\n',
    '2024-10-28T21:52:29.884Z fs File system scan completed\n',
    '2024-10-28T21:52:29.885Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.389/projects/1a04103d1c11ee41\n',
    '2024-10-28T21:52:29.890Z workers Parallelism for initial run: 1, for regular run: 1\n',
    '2024-10-28T21:52:29.890Z workers Starting run worker instance #0\n',
    '2024-10-28T21:52:29.890Z workers Web server is listening at 52816\n',
    '2024-10-28T21:52:29.891Z project Stopping process pool\n',
    '2024-10-28T21:52:29.891Z project File cache is up-to-date, starting full test run\n',
    '2024-10-28T21:52:29.893Z project Test run started; run priority: 3\n',
    '2024-10-28T21:52:29.893Z project Running all tests\n',
    '2024-10-28T21:52:29.894Z project Test run finished\n',
    '2024-10-28T21:52:29.894Z project Test run data re-queued\n',
    '2024-10-28T21:52:29.972Z workers Started run worker instance (delayed) #0\n',
    '2024-10-28T21:52:29.993Z project Requested to run all tests\n',
    '2024-10-28T21:52:29.994Z project Test run started; run priority: 3\n',
    '2024-10-28T21:52:29.994Z project Running all tests\n',
    '2024-10-28T21:52:29.995Z workers Starting test run, priority: 3\n',
    '2024-10-28T21:52:29.995Z nodeRunner Starting sandbox [worker #0, session #ipq1f]\n',
    '2024-10-28T21:52:29.995Z nodeRunner Preparing sandbox [worker #0, session #ipq1f]\n',
    '2024-10-28T21:52:29.995Z nodeRunner Prepared sandbox [worker #0, session #ipq1f]\n',
    '2024-10-28T21:52:29.995Z workers [worker #0, session #ipq1f] Running tests in sandbox\n',
    '2024-10-28T21:52:30.062Z workers Sandbox (active) [ipq1f] error: Failed to initialize wallaby vitest.\n' +
      'Initialization: Wallaby is not compatible with current version of Vitest.\n' +
      'Could not find GlobalSetupPlugin in entry point for file file://<homeDir>/dev/repo/node_modules/.pnpm/vitest@2.1.4_@types+node@22.8.1_jsdom@25.0.1/node_modules/vitest/dist/chunks/cli-api.CKrRYkw8.js.\n' +
      'Error: Initialization: Wallaby is not compatible with current version of Vitest.\n' +
      'Could not find GlobalSetupPlugin in entry point for file file://<homeDir>/dev/repo/node_modules/.pnpm/vitest@2.1.4_@types+node@22.8.1_jsdom@25.0.1/node_modules/vitest/dist/chunks/cli-api.CKrRYkw8.js.\n' +
      '    at file://<homeDir>/dev/repo/node_modules/.pnpm/vitest@2.1.4_@types+node@22.8.1_jsdom@25.0.1/node_modules/vitest/dist/chunks/cli-api.CKrRYkw8.js:1:7\n' +
      '    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)\n' +
      '    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)\n',
    '2024-10-28T21:52:30.164Z workers [ipq1f] Run 0 test(s), skipped 0 test(s)\n',
    '2024-10-28T21:52:30.165Z workers [ipq1f] Sandbox is responsive, closing it\n',
    '2024-10-28T21:52:30.165Z workers Failed to map the stack to user code, entry message: Failed to initialize wallaby vitest.\n' +
      'Initialization: Wallaby is not compatible with current version of Vitest.\n' +
      'Could not find GlobalSetupPlugin in entry point for file file://<homeDir>/dev/repo/node_modules/.pnpm/vitest@2.1.4_@types+node@22.8.1_jsdom@25.0.1/node_modules/vitest/dist/chunks/cli-api.CKrRYkw8.js.\n' +
      'Error: Initialization: Wallaby is not compatible with current version of Vitest.\n' +
      'Could not find GlobalSetupPlugin in entry point for file file://<homeDir>/dev/repo/node_modules/.pnpm/vitest@2.1.4_@types+node@22.8.1_jsdom@25.0.1/node_modules/vitest/dist/chunks/cli-api.CKrRYkw8.js., stack: Failed to initialize wallaby vitest.\n' +
      'Initialization: Wallaby is not compatible with current version of Vitest.\n' +
      'Could not find GlobalSetupPlugin in entry point for file file://<homeDir>/dev/repo/node_modules/.pnpm/vitest@2.1.4_@types+node@22.8.1_jsdom@25.0.1/node_modules/vitest/dist/chunks/cli-api.CKrRYkw8.js.\n' +
      'Error: Initialization: Wallaby is not compatible with current version of Vitest.\n' +
      'Could not find GlobalSetupPlugin in entry point for file file://<homeDir>/dev/repo/node_modules/.pnpm/vitest@2.1.4_@types+node@22.8.1_jsdom@25.0.1/node_modules/vitest/dist/chunks/cli-api.CKrRYkw8.js.\n' +
      '    at file://<homeDir>/dev/repo/node_modules/.pnpm/vitest@2.1.4_@types+node@22.8.1_jsdom@25.0.1/node_modules/vitest/dist/chunks/cli-api.CKrRYkw8.js:1:7\n' +
      '    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)\n' +
      '    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)\n' +
      '    at async initializeVitest (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.389/wallaby65cbc5/runn\n',
    '2024-10-28T21:52:30.166Z project Test run finished\n',
    '2024-10-28T21:52:30.166Z project Processed console.log entries\n',
    '2024-10-28T21:52:30.166Z project Processed loading sequences\n',
    '2024-10-28T21:52:30.166Z project Processed executed tests\n',
    '2024-10-28T21:52:30.166Z project Processed code coverage\n',
    '2024-10-28T21:52:30.172Z project Test run result processed and sent to IDE\n',
    '2024-10-28T21:52:30.172Z websocket received message ui.untrackStats\n',
    '2024-10-28T21:52:30.172Z websocket received method call: untrackStats\n',
    '2024-10-28T21:52:30.172Z websocket received message ui.untrackStartupEvents\n',
    '2024-10-28T21:52:30.172Z websocket received method call: untrackStartupEvents\n',
    '2024-10-28T21:52:30.172Z websocket received message ui.untrackStatus\n',
    '2024-10-28T21:52:30.172Z websocket received method call: untrackStatus\n',
    '2024-10-28T21:52:30.172Z websocket received message ui.untrackTestRun\n',
    '2024-10-28T21:52:30.172Z websocket received method call: untrackTestRun\n',
    '2024-10-28T21:52:30.174Z websocket received message ui.trackStats\n',
    '2024-10-28T21:52:30.174Z websocket received method call: trackStats\n',
    '2024-10-28T21:52:30.175Z websocket received message ui.trackStatus\n',
    '2024-10-28T21:52:30.175Z websocket received method call: trackStatus\n',
    '2024-10-28T21:52:30.175Z websocket received message ui.trackTestRun\n',
    '2024-10-28T21:52:30.175Z websocket received method call: trackTestRun\n'
  ]
}
```

**Comment by smcenlly** [comment]
Thanks for reporting your problem. 

As you are probably aware, Vitest 2.1.4 was released very recently (~12 hours ago). There were breaking changes that required updates to Wallaby. This version is now supported from Wallaby core `v1.0.1618+`.
