### ISSUE TITLE
NestJS, Vitest, SWC - js syntax error

### ISSUE THREAD

**Issue by Kinkanp** [wallabyjs/public#3427]
### Issue description or question

**Test**:
```
describe('demo', () => {
  it('should calculate 1 + 1', () => {
    const a: number = 1;
    const b = 1;

    expect(a + b).toEqual(2);
  })
})
```

**Result**:
`Error:   x 'const' declarations must be initialized`

---
Wallaby cannot compile typescript. If i remove type `:number` , or remove `swc` plugin from vitest - test will run sucessfully.

tsconfig.json, package.json are in diagnostics report

P.S I saw extremely similar issue: https://github.com/wallabyjs/public/issues/3329, but it was marked as resolved. I've updated webstorm & wallaby to the latest - but the issue still exists. Please let me know if my configuration is incorrect.

Best regards

### Wallaby diagnostics report

```
{
  editorVersion: 'WebStorm 2024.3',
  pluginVersion: '1.0.311',
  editorType: 'IntelliJ',
  osVersion: 'darwin 23.2.0',
  nodeVersion: 'v18.19.1',
  coreVersion: '1.0.1650',
  pnp: '<not set>',
  pnpEsm: '<not set>',
  checksum: 'OTY3NTc3MDYzODk3YTVlYjZmMjM3Y2QyOGUwMGMwYmMsMTc2NDExNTIwMDAwMCww',
  config: {
    compilers: {},
    env: {
      type: 'node',
      params: {},
      runner: '<homeDir>/.nvm/versions/node/v18.19.1/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0', configFile: './vitest.config.ts', autoDetected: true },
    diagnostics: {
      vitest: {
        file: {
          config: "import swc from 'unplugin-swc';\n" +
            "import { defineConfig } from 'vitest/config';\n" +
            '\n' +
            'export default defineConfig({\n' +
            '  test: {\n' +
            '    globals: true,\n' +
            "    root: './',\n" +
            "    include: ['src/test.spec.ts'],\n" +
            "    // include: ['src/**/**.spec.ts'],\n" +
            '  },\n' +
            '  plugins: [\n' +
            '    // This is required to build the test files with SWC\n' +
            '    swc.vite({\n' +
            '      // Explicitly set the module type to avoid inheriting this value from a `.swcrc` config file\n' +
            "      module: { type: 'es6' },\n" +
            '    }),\n' +
            '  ],\n' +
            '});\n' +
            '\n'
        },
        config: {
          config: {
            allowOnly: true,
            isolate: true,
            watch: true,
            globals: true,
            environment: 'node',
            pool: 'forks',
            clearMocks: false,
            restoreMocks: false,
            mockReset: false,
            unstubGlobals: false,
            unstubEnvs: false,
            include: [ 'src/test.spec.ts' ],
            exclude: [
              '**/node_modules/**',
              '**/dist/**',
              '**/cypress/**',
              '**/.{idea,git,cache,output,temp}/**',
              '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
            ],
            teardownTimeout: 10000,
            forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**' ],
            update: false,
            reporters: [ [ 'default', {} ] ],
            silent: false,
            hideSkippedTests: false,
            api: { middlewareMode: true },
            ui: false,
            uiBase: '/__vitest__/',
            open: true,
            css: { include: [], modules: { classNameStrategy: 'stable' } },
            coverage: {
              provider: 'v8',
              enabled: false,
              all: true,
              clean: true,
              cleanOnRerun: true,
              reportsDirectory: './coverage',
              exclude: [
                'coverage/**',
                'dist/**',
                '**/node_modules/**',
                '**/[.]**',
                'packages/*/test?(s)/**',
                '**/*.d.ts',
                '**/virtual:*',
                '**/__x00__*',
                '**/\x00*',
                'cypress/**',
                'test?(s)/**',
                'test?(-*).?(c|m)[jt]s?(x)',
                '**/*{.,-}{test,spec,bench,benchmark}?(-d).?(c|m)[jt]s?(x)',
                '**/__tests__/**',
                '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
                '**/vitest.{workspace,projects}.[jt]s?(on)',
                '**/.{eslint,mocha,prettier}rc.{?(c|m)js,yml}'
              ],
              reportOnFailure: false,
              reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
              extension: [
                '.js',     '.cjs',
                '.mjs',    '.ts',
                '.mts',    '.tsx',
                '.jsx',    '.vue',
                '.svelte', '.marko',
                '.astro'
              ],
              allowExternal: false,
              excludeAfterRemap: false,
              ignoreEmptyLines: true,
              processingConcurrency: 12
            },
            fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
            maxConcurrency: 5,
            dangerouslyIgnoreUnhandledErrors: false,
            typecheck: {
              checker: 'tsc',
              include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
              exclude: [
                '**/node_modules/**',
                '**/dist/**',
                '**/cypress/**',
                '**/.{idea,git,cache,output,temp}/**',
                '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
              ],
              enabled: false
            },
            slowTestThreshold: 300,
            disableConsoleIntercept: false,
            root: '<homeDir>/Documents/projects/notes-book/notes-book-server',
            poolOptions: { threads: {}, forks: {} },
            config: '<homeDir>/Documents/projects/notes-book/notes-book-server/vitest.config.ts',
            defines: {},
            mode: 'test',
            provide: {},
            inspector: { enabled: false, waitForDebugger: false },
            clearScreen: true,
            browser: {
              enabled: false,
              headless: false,
              isolate: true,
              fileParallelism: true,
              ui: true,
              screenshotFailures: false,
              viewport: { width: 414, height: 896 },
              locators: { testIdAttribute: 'data-testid' },
              api: { port: 63315 }
            },
            fileParallelism: true,
            expect: {},
            deps: {
              moduleDirectories: [ '/node_modules/' ],
              optimizer: { ssr: { enabled: true }, web: { enabled: true } },
              web: { transformAssets: true, transformCss: true, transformGlobPattern: [] }
            },
            setupFiles: [],
            globalSetup: [],
            server: { deps: { inline: [ {}, {}, {} ], inlineFiles: [], moduleDirectories: [ '/node_modules/' ], cacheDir: 'node_modules/.vite' } },
            snapshotOptions: { expand: false, snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
            snapshotSerializers: [],
            poolMatchGlobs: [],
            cache: { dir: '<homeDir>/Documents/projects/notes-book/notes-book-server/node_modules/.vite/vitest' },
            sequence: { hooks: 'stack' },
            environmentMatchGlobs: [],
            testTransformMode: {},
            testTimeout: 5000,
            hookTimeout: 10000
          },
          projects: [
            {
              path: '<homeDir>/Documents/projects/notes-book/notes-book-server',
              config: {
                allowOnly: true,
                isolate: true,
                watch: true,
                globals: true,
                environment: 'node',
                pool: 'forks',
                clearMocks: false,
                restoreMocks: false,
                mockReset: false,
                unstubGlobals: false,
                unstubEnvs: false,
                include: [ 'src/test.spec.ts' ],
                exclude: [
                  '**/node_modules/**',
                  '**/dist/**',
                  '**/cypress/**',
                  '**/.{idea,git,cache,output,temp}/**',
                  '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
                ],
                teardownTimeout: 10000,
                forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**' ],
                update: false,
                reporters: [ [ 'default', {} ] ],
                silent: false,
                hideSkippedTests: false,
                api: { middlewareMode: true },
                ui: false,
                uiBase: '/__vitest__/',
                open: true,
                css: { include: [], modules: { classNameStrategy: 'stable' } },
                coverage: {
                  provider: 'v8',
                  enabled: false,
                  all: true,
                  clean: true,
                  cleanOnRerun: true,
                  reportsDirectory: './coverage',
                  exclude: [
                    'coverage/**',
                    'dist/**',
                    '**/node_modules/**',
                    '**/[.]**',
                    'packages/*/test?(s)/**',
                    '**/*.d.ts',
                    '**/virtual:*',
                    '**/__x00__*',
                    '**/\x00*',
                    'cypress/**',
                    'test?(s)/**',
                    'test?(-*).?(c|m)[jt]s?(x)',
                    '**/*{.,-}{test,spec,bench,benchmark}?(-d).?(c|m)[jt]s?(x)',
                    '**/__tests__/**',
                    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
                    '**/vitest.{workspace,projects}.[jt]s?(on)',
                    '**/.{eslint,mocha,prettier}rc.{?(c|m)js,yml}'
                  ],
                  reportOnFailure: false,
                  reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
                  extension: [
                    '.js',     '.cjs',
                    '.mjs',    '.ts',
                    '.mts',    '.tsx',
                    '.jsx',    '.vue',
                    '.svelte', '.marko',
                    '.astro'
                  ],
                  allowExternal: false,
                  excludeAfterRemap: false,
                  ignoreEmptyLines: true,
                  processingConcurrency: 12
                },
                fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
                maxConcurrency: 5,
                dangerouslyIgnoreUnhandledErrors: false,
                typecheck: {
                  checker: 'tsc',
                  include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
                  exclude: [
                    '**/node_modules/**',
                    '**/dist/**',
                    '**/cypress/**',
                    '**/.{idea,git,cache,output,temp}/**',
                    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*'
                  ],
                  enabled: false
                },
                slowTestThreshold: 300,
                disableConsoleIntercept: false,
                root: '<homeDir>/Documents/projects/notes-book/notes-book-server',
                poolOptions: { threads: {}, forks: {} },
                config: '<homeDir>/Documents/projects/notes-book/notes-book-server/vitest.config.ts',
                defines: {},
                mode: 'test',
                provide: {},
                inspector: { enabled: false, waitForDebugger: false },
                clearScreen: true,
                browser: {
                  enabled: false,
                  headless: false,
                  isolate: true,
                  fileParallelism: true,
                  ui: true,
                  screenshotFailures: false,
                  viewport: { width: 414, height: 896 },
                  locators: { testIdAttribute: 'data-testid' },
                  api: { port: 63315 }
                },
                fileParallelism: true,
                expect: {},
                deps: {
                  moduleDirectories: [ '/node_modules/' ],
                  optimizer: { ssr: { enabled: true }, web: { enabled: true } },
                  web: { transformAssets: true, transformCss: true, transformGlobPattern: [] }
                },
                setupFiles: [],
                globalSetup: [],
                server: { deps: { inline: [ {}, {}, {} ], inlineFiles: [], moduleDirectories: [ '/node_modules/' ], cacheDir: 'node_modules/.vite' } },
                snapshotOptions: { expand: false, snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
                snapshotSerializers: [],
                poolMatchGlobs: [],
                cache: { dir: '<homeDir>/Documents/projects/notes-book/notes-book-server/node_modules/.vite/vitest' },
                sequence: { hooks: 'stack' },
                environmentMatchGlobs: [],
                testTransformMode: {},
                testTimeout: 5000,
                hookTimeout: 10000
              }
            }
          ],
          package: {
            version: '2.1.6',
            urls: { hooks: 'file://<homeDir>/Library/Caches/JetBrains/WebStorm2024.3/wallaby/wallaby/runners/node/hooks.mjs' },
            paths: {
              root: '<homeDir>/Documents/projects/notes-book/notes-book-server/node_modules/vitest',
              dist: '<homeDir>/Documents/projects/notes-book/notes-book-server/node_modules/vitest/dist'
            }
          }
        }
      }
    },
    preserveComments: false,
    extractComments: true,
    files: [
      { pattern: 'src/test.spec.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/*.timestamp-*', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/*.*', ignore: false, trigger: true, load: true, order: 1 }
    ],
    tests: [
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'src/test.spec.ts', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    workers: { initial: 1, regular: 1, recycle: false },
    dot: true,
    captureConsoleLog: true,
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 8192 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    maxTraceSteps: 999999,
    maxTraceStepsForWatchExpressionPrefetch: 10,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: false,
    symlinkNodeModules: undefined,
    configCode: 'module.exports = (wallaby) => ({\n' +
      '  autoDetect: true,\n' +
      '\n' +
      '  // modify `files` automatic configuration settings\n' +
      '  // files: {\n' +
      '  //   override: (filePatterns) => {\n' +
      "  //     console.log('[LOG]', filePatterns);\n" +
      '  //     // TODO: modify `filePatterns` array as required\n' +
      "  //     return ['src/**/*.ts'];\n" +
      '  //   }\n' +
      '  // },\n' +
      '  //\n' +
      '  // tests: {\n' +
      '  //   override: (testPatterns) => {\n' +
      '  //     // TODO: modify `testPatterns` array as required\n' +
      "  //     return ['src/**/*.spec.ts'];\n" +
      '  //   }\n' +
      '  // },\n' +
      '  compilers: {\n' +
      "    // '**/*.ts': wallaby.compilers.typeScript({\n" +
      "      // module: 'commonjs',\n" +
      "      // moduleResolution: 'node'\n" +
      '    // })\n' +
      '  },\n' +
      '  env: {\n' +
      "    type: 'node'\n" +
      '  },\n' +
      '  testFramework: {\n' +
      "    configFile: './vitest.config.ts'\n" +
      '  }\n' +
      '});\n'
  },
  packageJSON: {
    dependencies: {
      '@dotenvx/dotenvx': '1.25.1',
      '@nestjs/platform-express': '10.4.9',
      '@prisma/client': '5.22.0',
      dotenv: '16.4.5',
      googleapis: '144.0.0',
      jsonwebtoken: '9.0.2',
      lodash: '4.17.21',
      'reflect-metadata': '^0.2.2',
      rimraf: '^6.0.1',
      rxjs: '^7.8.1'
    },
    devDependencies: {
      '@nestjs/cli': '^10.4.8',
      '@nestjs/schematics': '^10.2.3',
      '@nestjs/testing': '^10.4.9',
      '@swc/core': '1.9.3',
      '@types/express': '^5.0.0',
      '@types/jsonwebtoken': '9.0.7',
      '@types/lodash': '4.17.13',
      '@types/node': '^22.10.0',
      '@types/supertest': '^6.0.2',
      '@typescript-eslint/eslint-plugin': '^8.16.0',
      '@typescript-eslint/parser': '^8.16.0',
      '@vitest/coverage-v8': '2.1.6',
      eslint: '^9.15.0',
      'eslint-config-prettier': '^9.1.0',
      'eslint-plugin-prettier': '^5.2.1',
      prettier: '^3.4.1',
      prisma: '5.22.0',
      supertest: '^7.0.0',
      'ts-loader': '^9.5.1',
      'ts-node': '^10.9.2',
      'tsconfig-paths': '^4.2.0',
      typescript: '5.6.3',
      'unplugin-swc': '1.5.1',
      vitest: '2.1.6',
      'vitest-mock-extended': '2.0.2'
    }
  },
  fs: { numberOfFiles: 71 },
  debug: [
    '2024-11-26T21:58:51.234Z project waiting for initial run signal\n',
    '2024-11-26T21:58:51.244Z model Initialization Completed: 341ms\n',
    '2024-11-26T21:58:51.376Z config Attempting automatic configuration for vitest\n',
    '2024-11-26T21:58:51.378Z vitest/config Detected Vitest (2.1.6).\n',
    '2024-11-26T21:58:52.295Z config Finished attempting automatic configuration for vitest (919ms)\n',
    '2024-11-26T21:58:52.297Z project Wallaby Node version: v18.19.1\n',
    '2024-11-26T21:58:52.297Z project Wallaby config: <homeDir>/Documents/projects/notes-book/notes-book-server/wallaby.conf.js\n',
    '2024-11-26T21:58:52.354Z fs File system starting\n',
    '2024-11-26T21:58:52.715Z fs File system scan completed\n',
    '2024-11-26T21:58:52.718Z project File cache: <homeDir>/Library/Caches/JetBrains/WebStorm2024.3/wallaby/projects/91b0fae86f096f75\n',
    '2024-11-26T21:58:52.720Z project package.json file change detected, invalidating local cache\n',
    '2024-11-26T21:58:52.740Z workers Parallelism for initial run: 1, for regular run: 1\n',
    '2024-11-26T21:58:52.740Z workers Starting run worker instance #0\n',
    '2024-11-26T21:58:52.740Z workers Web server is listening at 60398\n',
    '2024-11-26T21:58:52.741Z project File cache requires some updates, waiting required files from IDE\n',
    '2024-11-26T21:58:52.820Z project Stopping process pool\n',
    '2024-11-26T21:58:52.823Z project Test run started; run priority: 3\n',
    '2024-11-26T21:58:52.863Z project Running all tests\n',
    '2024-11-26T21:58:52.869Z workers Starting test run, priority: 3\n',
    '2024-11-26T21:58:52.871Z nodeRunner Starting sandbox [worker #0, session #qv0v6]\n',
    '2024-11-26T21:58:52.871Z nodeRunner Preparing sandbox [worker #0, session #qv0v6]\n',
    '2024-11-26T21:58:52.875Z ui.service Starting UI service on port: 55000\n',
    '2024-11-26T21:58:52.877Z ui.service UI service started on port: 55000\n',
    '2024-11-26T21:58:53.086Z websocket received message ui.trackOverviewTestList\n',
    '2024-11-26T21:58:53.086Z websocket received method call: trackOverviewTestList\n',
    '2024-11-26T21:58:53.087Z websocket received message ui.trackAllLogsAndErrors\n',
    '2024-11-26T21:58:53.087Z websocket received method call: trackAllLogsAndErrors\n',
    '2024-11-26T21:58:53.087Z websocket received message ui.trackStatus\n',
    '2024-11-26T21:58:53.087Z websocket received method call: trackStatus\n',
    '2024-11-26T21:58:53.088Z websocket received message ui.trackTestRun\n',
    '2024-11-26T21:58:53.088Z websocket received method call: trackTestRun\n',
    '2024-11-26T21:58:53.088Z websocket received message ui.trackStartupEvents\n',
    '2024-11-26T21:58:53.088Z websocket received method call: trackStartupEvents\n',
    '2024-11-26T21:58:53.088Z websocket received message ui.trackStats\n',
    '2024-11-26T21:58:53.088Z websocket received method call: trackStats\n',
    '2024-11-26T21:58:53.089Z websocket received message ui.trackStatus\n',
    '2024-11-26T21:58:53.089Z websocket received method call: trackStatus\n',
    '2024-11-26T21:58:53.089Z websocket received message ui.trackTestRun\n',
    '2024-11-26T21:58:53.089Z websocket received method call: trackTestRun\n',
    '2024-11-26T21:58:53.089Z websocket received message ui.handshake\n',
    '2024-11-26T21:58:53.089Z websocket received method call: handshake\n',
    '2024-11-26T21:58:53.090Z websocket received message ui.trackEditorCursor\n',
    '2024-11-26T21:58:53.090Z websocket received method call: trackEditorCursor\n',
    '2024-11-26T21:58:53.090Z websocket received message ui.trackStatus\n',
    '2024-11-26T21:58:53.090Z websocket received method call: trackStatus\n',
    '2024-11-26T21:58:53.200Z workers Started run worker instance (delayed) #0\n',
    '2024-11-26T21:58:53.200Z nodeRunner Prepared sandbox [worker #0, session #qv0v6]\n',
    '2024-11-26T21:58:53.200Z workers [worker #0, session #qv0v6] Running tests in sandbox\n',
    "2024-11-26T21:58:53.880Z workers 'Scheduling Vitest Run (qv0v6): 2024-11-26T21:58:53.879Z'\n",
    "2024-11-26T21:58:54.339Z workers Sandbox (active) [qv0v6] error:   \x1B[31mx\x1B[0m 'const' declarations must be initialized\n" +
      '   ,-[\x1B[36;1;4m<rootDir>/src/test.spec.ts?wallaby=1732658332770\x1B[0m:3:1]\n' +
      " \x1B[2m1\x1B[0m | describe('demo', () => {\n" +
      " \x1B[2m2\x1B[0m |   it('should calculate 1 + 1', () => {\n" +
      ' \x1B[2m3\x1B[0m |     const a: number = 1;\n' +
      '   : \x1B[35;1m          ^\x1B[0m\n' +
      ' \x1B[2m4\x1B[0m |     const b = 1;\n' +
      ' \x1B[2m5\x1B[0m | \n' +
      ' \x1B[2m6\x1B[0m |     expect(a + b).toEqual(2);\n' +
      '   `----\n' +
      '  \x1B[31mx\x1B[0m Expected a semicolon\n' +
      '   ,-[\x1B[36;1;4m<rootDir>/src/test.spec.ts?wallaby=1732658332770\x1B[0m:3:1]\n' +
      " \x1B[2m1\x1B[0m | describe('demo', () => {\n" +
      " \x1B[2m2\x1B[0m |   it('should calculate 1 + 1', () => {\n" +
      ' \x1B[2m3\x1B[0m |     const a: number = 1;\n' +
      '   : \x1B[35;1m           ^\x1B[0m\n' +
      ' \x1B[2m4\x1B[0m |     const b = 1;\n' +
      ' \x1B[2m5\x1B[0m | \n' +
      ' \x1B[2m6\x1B[0m |     expect(a + b).toEqual(2);\n' +
      '   `----\n' +
      '\n' +
      '\n' +
      'Caused by:\n' +
      '    Syntax Error\n' +
      '    at <rootDir>/src/test.spec.ts:1:1453\n' +
      '    at VitestExecutor.runModule (file://<rootDir>/node_modules/vite-node/dist/client.mjs:399:11)\n' +
      '    at VitestExecutor.runModule (file://<rootDir>/node_modules/vitest/dist/chunks/execute.2pr0rHgK.js:766:20)\n' +
      '    at VitestExecutor.directRequest (file://<rootDir>/node_modules/vite-node/dist/client.mjs:381:16)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at VitestExecutor.cachedRequest (file://<rootDir>/node_modules/vite-node/dist/client.mjs:206:14)\n' +
      '    at VitestExecutor.executeId (file://<rootDir>/node_modules/vite-node/dist/client.mjs:173:12)\n' +
      '    at collectTestsPatched (file://<rootDir>/node_modules/@vitest/runner/dist/index.js:851:7)\n' +
      '    at collectTests (file://<rootDir>/node_modules/@vitest/runner/dist/index.js:832:61)\n' +
      '    at startTests (file://<rootDir>/node_modules/@vitest/runner/dist/index.js:1268:17)\n' +
      '    at file://<rootDir>/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:126:11\n' +
      '    at withEnv (file://<rootDir>/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:90:5)\n' +
      '    at run (file://<rootDir>/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:112:3)\n' +
      '    at runBaseTests (file://<rootDir>/node_modules/vitest/dist/chunks/base.BZZh4cSm.js:29:3)\n' +
      '    at ForksBaseWorker.executeTests (file://<rootDir>/node_modules/vitest/dist/workers/forks.js:27:7)\n' +
      '    at execute (file://<rootDir>/node_modules/vitest/dist/worker.js:127:5)\n' +
      '    at onMessage (file://<rootDir>/node_modules/tinypool/dist/entry/process.js:55:20)\n',
    '2024-11-26T21:58:54.340Z workers [qv0v6.1] Loaded unknown number of test(s)\n',
    "2024-11-26T21:58:54.360Z workers Sandbox (active) [qv0v6] error:   \x1B[31mx\x1B[0m 'const' declarations must be initialized\n" +
      '   ,-[\x1B[36;1;4m<rootDir>/src/test.spec.ts?wallaby=1732658332770\x1B[0m:3:1]\n' +
      " \x1B[2m1\x1B[0m | describe('demo', () => {\n" +
      " \x1B[2m2\x1B[0m |   it('should calculate 1 + 1', () => {\n" +
      ' \x1B[2m3\x1B[0m |     const a: number = 1;\n' +
      '   : \x1B[35;1m          ^\x1B[0m\n' +
      ' \x1B[2m4\x1B[0m |     const b = 1;\n' +
      ' \x1B[2m5\x1B[0m | \n' +
      ' \x1B[2m6\x1B[0m |     expect(a + b).toEqual(2);\n' +
      '   `----\n' +
      '  \x1B[31mx\x1B[0m Expected a semicolon\n' +
      '   ,-[\x1B[36;1;4m<rootDir>/src/test.spec.ts?wallaby=1732658332770\x1B[0m:3:1]\n' +
      " \x1B[2m1\x1B[0m | describe('demo', () => {\n" +
      " \x1B[2m2\x1B[0m |   it('should calculate 1 + 1', () => {\n" +
      ' \x1B[2m3\x1B[0m |     const a: number = 1;\n' +
      '   : \x1B[35;1m           ^\x1B[0m\n' +
      ' \x1B[2m4\x1B[0m |     const b = 1;\n' +
      ' \x1B[2m5\x1B[0m | \n' +
      ' \x1B[2m6\x1B[0m |     expect(a + b).toEqual(2);\n' +
      '   `----\n' +
      '\n' +
      '\n' +
      'Caused by:\n' +
      '    Syntax Error\n' +
      '    at <rootDir>/src/test.spec.ts:1:1453\n' +
      '    at VitestExecutor.runModule (file://<rootDir>/node_modules/vite-node/dist/client.mjs:399:11)\n' +
      '    at VitestExecutor.runModule (file://<rootDir>/node_modules/vitest/dist/chunks/execute.2pr0rHgK.js:766:20)\n' +
      '    at VitestExecutor.directRequest (file://<rootDir>/node_modules/vite-node/dist/client.mjs:381:16)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at VitestExecutor.cachedRequest (file://<rootDir>/node_modules/vite-node/dist/client.mjs:206:14)\n' +
      '    at VitestExecutor.executeId (file://<rootDir>/node_modules/vite-node/dist/client.mjs:173:12)\n' +
      '    at collectTestsPatched (file://<rootDir>/node_modules/@vitest/runner/dist/index.js:851:7)\n' +
      '    at collectTests (file://<rootDir>/node_modules/@vitest/runner/dist/index.js:832:61)\n' +
      '    at startTests (file://<rootDir>/node_modules/@vitest/runner/dist/index.js:1268:17)\n' +
      '    at file://<rootDir>/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:126:11\n' +
      '    at withEnv (file://<rootDir>/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:90:5)\n' +
      '    at run (file://<rootDir>/node_modules/vitest/dist/chunks/runBaseTests.3qpJUEJM.js:112:3)\n' +
      '    at runBaseTests (file://<rootDir>/node_modules/vitest/dist/chunks/base.BZZh4cSm.js:29:3)\n' +
      '    at ForksBaseWorker.executeTests (file://<rootDir>/node_modules/vitest/dist/workers/forks.js:27:7)\n' +
      '    at execute (file://<rootDir>/node_modules/vitest/dist/worker.js:127:5)\n' +
      '    at onMessage (file://<rootDir>/node_modules/tinypool/dist/entry/process.js:55:20)\n',
    "2024-11-26T21:58:54.361Z workers 'Vitest Run Complete (qv0v6): 2024-11-26T21:58:54.361Z'\n",
    '2024-11-26T21:58:54.362Z workers [qv0v6] Run 0 test(s), skipped 0 test(s)\n',
    '2024-11-26T21:58:54.362Z workers [qv0v6] Sandbox is responsive, closing it\n',
    '2024-11-26T21:58:54.365Z project Test run finished\n',
    '2024-11-26T21:58:54.366Z project Processed console.log entries\n',
    '2024-11-26T21:58:54.366Z project Processed loading sequences\n',
    '2024-11-26T21:58:54.366Z project Processed executed tests\n',
    '2024-11-26T21:58:54.367Z project Processed code coverage\n',
    '2024-11-26T21:58:54.374Z project Test run result processed and sent to IDE\n',
    '2024-11-26T21:58:54.375Z websocket received message ui.untrackStats\n',
    '2024-11-26T21:58:54.375Z websocket received method call: untrackStats\n',
    '2024-11-26T21:58:54.375Z websocket received message ui.untrackStartupEvents\n',
    '2024-11-26T21:58:54.375Z websocket received method call: untrackStartupEvents\n',
    '2024-11-26T21:58:54.375Z websocket received message ui.untrackStatus\n',
    '2024-11-26T21:58:54.375Z websocket received method call: untrackStatus\n',
    '2024-11-26T21:58:54.375Z websocket received message ui.untrackTestRun\n',
    '2024-11-26T21:58:54.375Z websocket received method call: untrackTestRun\n',
    '2024-11-26T21:58:54.376Z fs No metadata for added file found: node_modules/.vite/vitest/results.json\n',
    '2024-11-26T21:58:54.389Z websocket received message ui.trackStats\n',
    '2024-11-26T21:58:54.389Z websocket received method call: trackStats\n',
    '2024-11-26T21:58:54.390Z websocket received message ui.trackStatus\n',
    '2024-11-26T21:58:54.390Z websocket received method call: trackStatus\n',
    '2024-11-26T21:58:54.390Z websocket received message ui.trackTestRun\n',
    '2024-11-26T21:58:54.390Z websocket received method call: trackTestRun\n'
  ]
}
```

**Comment by mburnell** [comment]
Thank you for reporting the issue, and for the diagnostic information. We were able to reproduce the issue, and identify a change to unplugin-swc that broke our integration with it (`1.4.4` worked, `1.5.1` did not). We've updated our integration and released core `1.0.1561`; updating core (you can use the `Force Core Update` action in WebStorm) should fix things for you.
