### ISSUE TITLE
autodetection of node:test and vitest breaking on example code

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#3430]
Hi,

I have a repo in which some of the workspaces use Mocha, and others use `node:test`.  I'd like to create a Wallaby configuration for _just_ the `node:test` ones, but autodetection fails when it encounters an `example` directory I have:

![image](https://github.com/user-attachments/assets/ff14c8e4-7113-4452-bd41-af4dd5bf5f58)

```
"Automatic node:test configuration error: ENOENT: no such file or directory, stat
'<rootDir>/example/plugin-reporter/node_modules/plugin-reporter-fail'\n",
```

There's nothing in `example/plugin-reporter/` that implies `./fixture/plugin-reporter-fail` is a dependency -- nor a workspace.

This same error happens during autodetection of vitest, fwiw.  Seems weird that the autodetection would fully crap out instead of warning and moving on?

Try as I might, I haven't been able to coerce Wallaby into ignoring this directory, and there are no instructions for a _non_-automatic configuration of `node:test` (that I saw, anyway).

And as I paste this diagnostic, I don't even see the contents of my selected Wallaby config.  Something is weird.

Here's the config I am trying to use (which does not ignore `example/**/*`, unfortunately). Using the `files: {override: () => {...}` syntax mentioned in the docs makes no difference.

```js
module.exports = {
  autoDetect: ['node:test'],
  files: [
    '!example/**/*',
    'packages/pkg-manager/src/**/*.ts',
    'packages/pkg-manager/test/debug.ts',
    'packages/pkg-manager/test/unit/fixture.ts',
    'packages/tarball-installer/src/**/*.ts',
    'packages/tarball-installer/test/debug.ts',
    'packages/tarball-installer/test/unit/fixture.ts',
  ],
  tests: [
    '!example/**/*',
    'packages/pkg-manager/test/**/*.test.ts',
    'packages/tarball-installer/test/**/*.test.ts',
  ],
  trace: true,
};
```

### Wallaby diagnostics report

```
{
  editorVersion: '1.95.3',
  pluginVersion: '1.0.396',
  editorType: 'VSCode',
  osVersion: 'darwin 24.1.0',
  nodeVersion: 'v22.10.0',
  coreVersion: '1.0.1656',
  pnp: '<not set>',
  pnpEsm: '<not set>',
  checksum: 'YjA3ZjFlOGJkYTMwYWFkNzdiMzA5MjQ0YmVjM2NmYTMsMTc3OTIzNTIwMDAwMCww',
  config: { tests: [], files: [] },
  packageJSON: {
    dependencies: undefined,
    devDependencies: {
      '@commitlint/cli': '17.8.1',
      '@commitlint/config-conventional': '17.8.1',
      '@stylistic/eslint-plugin-js': '2.1.0',
      '@stylistic/eslint-plugin-ts': '2.1.0',
      '@swc/core': '1.3.107',
      '@tsconfig/node18': '18.2.4',
      '@types/mocha': '10.0.6',
      '@types/node': '20.14.11',
      '@types/sinon': '17.0.2',
      '@types/source-map-support': '0.5.10',
      '@types/wallabyjs': '0.0.15',
      '@typescript-eslint/eslint-plugin': '6.14.0',
      '@typescript-eslint/parser': '6.14.0',
      c8: '10.1.2',
      'cross-env': '7.0.3',
      'dependency-cruiser': '15.5.0',
      eslint: '8.56.0',
      'eslint-plugin-jsonc': '2.13.0',
      'eslint-plugin-mocha': '10.5.0',
      'eslint-plugin-n': '15.7.0',
      'eslint-plugin-perfectionist': '3.0.0',
      glob: '10.3.10',
      husky: '8.0.3',
      impvol: '0.1.7',
      knip: '5.16.0',
      'lint-staged': '15.2.10',
      'markdownlint-cli2': '0.14.0',
      'markdownlint-cli2-formatter-pretty': '0.0.5',
      minimatch: '9.0.4',
      mocha: '10.2.0',
      'npm-run-all2': '6.2.2',
      prettier: '3.1.1',
      'prettier-plugin-astro': '0.12.3',
      'prettier-plugin-jsdoc': '1.1.1',
      'prettier-plugin-organize-imports': '3.2.4',
      'prettier-plugin-pkg': '0.18.0',
      shx: '0.3.4',
      sinon: '16.1.3',
      'snap-shot-it': '7.9.10',
      'source-map-support': '0.5.21',
      tsd: '0.31.0',
      tsx: '4.17.0',
      'type-fest': '4.19.0',
      typescript: '5.6.2',
      unexpected: '13.2.1',
      'unexpected-sinon': '11.1.0',
      xstate: '5.19.0',
      'xstate-audition': '3.0.1'
    }
  },
  fs: { numberOfFiles: 0 },
  debug: [
    '2024-12-01T06:54:49.718Z project waiting for initial run signal\n',
    '2024-12-01T06:54:49.721Z model Initialization Completed: 121ms\n',
    '2024-12-01T06:54:49.761Z config Attempting automatic configuration for node:test\n',
    "2024-12-01T06:54:49.889Z vitest/config Error: ENOENT: no such file or directory, stat '<homeDir>/projects/boneskull/midnight-smoker/example/plugin-reporter/node_modules/plugin-reporter-fail'\n" +
      '    at realpathSync (node:fs:2729:17)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.396/wallaby655b7e/server.js:191:1210\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at s (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.396/wallaby655b7e/server.js:191:1156)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.396/wallaby655b7e/server.js:191:1302\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at s (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.396/wallaby655b7e/server.js:191:1156)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.396/wallaby655b7e/server.js:191:1302\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at s (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.396/wallaby655b7e/server.js:191:1156)\n' +
      '    at <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.396/wallaby655b7e/server.js:191:1302\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at s (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.396/wallaby655b7e/server.js:191:1156)\n' +
      '    at s.configure (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.396/wallaby655b7e/server.js:191:1326)\n' +
      '    at automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.396/wallaby655b7e/server.js:138:13141)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
      '    at async Config.load (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.396/wallaby655b7e/server.js:138:12958)\n' +
      '    at async Project.configure (<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.396/wallaby655b7e/server.js:490:2644)\n',
    '2024-12-01T06:54:49.889Z config Finished attempting automatic configuration for node:test (128ms)\n',
    "2024-12-01T06:54:49.890Z project Failed to load configuration file: Automatic node:test configuration error: ENOENT: no such file or directory, stat '<rootDir>/example/plugin-reporter/node_modules/plugin-reporter-fail'\n",
    '2024-12-01T06:54:49.895Z ui.service Starting UI service on port: 55001\n',
    '2024-12-01T06:54:49.896Z ui.service UI service started on port: 55001\n',
    '2024-12-01T06:54:49.994Z websocket received message ui.trackOverviewTestList\n',
    '2024-12-01T06:54:49.994Z websocket received method call: trackOverviewTestList\n',
    '2024-12-01T06:54:49.995Z websocket received message ui.trackAllLogsAndErrors\n',
    '2024-12-01T06:54:49.995Z websocket received method call: trackAllLogsAndErrors\n',
    '2024-12-01T06:54:49.995Z websocket received message ui.trackStatus\n',
    '2024-12-01T06:54:49.995Z websocket received method call: trackStatus\n',
    '2024-12-01T06:54:49.995Z websocket received message ui.trackTestRun\n',
    '2024-12-01T06:54:49.995Z websocket received method call: trackTestRun\n',
    '2024-12-01T06:54:49.996Z websocket received message ui.trackStartupEvents\n',
    '2024-12-01T06:54:49.996Z websocket received method call: trackStartupEvents\n',
    '2024-12-01T06:54:49.996Z websocket received message ui.trackStats\n',
    '2024-12-01T06:54:49.996Z websocket received method call: trackStats\n',
    '2024-12-01T06:54:49.996Z websocket received message ui.trackStatus\n',
    '2024-12-01T06:54:49.996Z websocket received method call: trackStatus\n',
    '2024-12-01T06:54:49.997Z websocket received message ui.trackTestRun\n',
    '2024-12-01T06:54:49.997Z websocket received method call: trackTestRun\n',
    '2024-12-01T06:54:49.997Z websocket received message ui.handshake\n',
    '2024-12-01T06:54:49.997Z websocket received method call: handshake\n',
    '2024-12-01T06:54:49.997Z websocket received message ui.trackEditorCursor\n',
    '2024-12-01T06:54:49.997Z websocket received method call: trackEditorCursor\n',
    '2024-12-01T06:54:49.997Z websocket received message ui.trackStatus\n',
    '2024-12-01T06:54:49.997Z websocket received method call: trackStatus\n',
    '2024-12-01T06:54:49.997Z websocket received message ui.untrackStats\n',
    '2024-12-01T06:54:49.997Z websocket received method call: untrackStats\n',
    '2024-12-01T06:54:49.997Z websocket received message ui.untrackStartupEvents\n',
    '2024-12-01T06:54:49.997Z websocket received method call: untrackStartupEvents\n',
    '2024-12-01T06:54:49.997Z websocket received message ui.untrackTestRun\n',
    '2024-12-01T06:54:49.997Z websocket received method call: untrackTestRun\n',
    '2024-12-01T06:54:50.069Z websocket received message ui.trackDiagnosticMessages\n',
    '2024-12-01T06:54:50.069Z websocket received method call: trackDiagnosticMessages\n'
  ]
}
```

**Comment by smcenlly** [comment]
We haven't seen this problem before.

From your diagnostic report it look like (as you say) something's going catastrophically wrong when trying to detect node native in your files.

This shouldn't be happening. We've updated our integration to ignore file scan errors on startup, but we'd really like to be able to reproduce your problem, both with node native and with vitest. Please update to Wallaby core `v1.0.1657`, it should fix your node native problem.

Are you able to provide us with sample repos that break (both the node native one, and vitest)?

**Comment by boneskull** [comment]
Well, the update eliminated that error, and things are mostly working now with the following configuration:

```js
module.exports = {
  autoDetect: ['node:test'],
  files: [
    // midnight-smoker is a peer dep for the other two
    'packages/{pkg-manager,tarball-installer,midnight-smoker}/**/*.ts',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/*.{test,spec}.?(c|m)[jt]s?(x)',
  ],
  preloadModules: ['tsx/cjs'],
  tests: [
    '!**/node_modules/**',
    'packages/pkg-manager/test/**/*.test.ts',
    'packages/tarball-installer/test/**/*.test.ts',
  ],
  trace: true,
};

```

A note:

- `ts-node` was throwing exceptions when compiling, so I needed to remove it from `preloadModules` to get it to work. I wanted to use `tsx` anyhow. `ts-node` is present in my `node_modules`, _but_ it is not a direct dependency of my project. Maybe that should inform the choice of hooks?

- And what looks like a bug:
- Wallaby seemingly has trouble with [`describe.only`](https://nodejs.org/api/test.html#describeonlyname-options-fn): [gist](https://gist.github.com/boneskull/e60696197b701db760d11e021726fa1a)
    This is not a `tsx`-related problem, as running the tests outside of Wallaby works fine (e.g., `node --import tsx --test-only my-tests/*.test.ts`)

**Comment by smcenlly** [comment]
Thanks for reporting your problems.

#### RE: `ts-node` vs. `tsx`
We've updated Wallaby to prioritize direct dependencies for your project before attempting to use transitive dependencies. If you explicitly have `tsx` installed, and `ts-node` is transitive, then Wallaby should now attempt to use `tsx` before `ts-node`

#### Describe.only bug
Thanks for reporting the issue. There were a few issues we uncovered with the describe blocks (`.only`, `.skip`, and `.todo` weren't working).

These problems have now been fixed.

---

These updates are available in the latest version of Wallaby core, `v1.0.1658`.

---

When using Wallaby with Node's native testing framework, `.only` behaves slightly differently compared to other testing frameworks. We've updated [our docs](https://wallabyjs.com/docs/integration/node-test/) to note this.

By default, when you run tests using Node's test runner, all tests will execute, including those marked with `.only`. If you want to run only `.only` tests, you need to start the Node test runner CLI with the `--test-only` option. Wallaby leverages this option internally to run only the tests you've changed while working in a test file. 

This behavior arises because Node processes tests in a single pass, making it challenging for Wallaby to detect `.only` tests before execution has started. Given these limitations and differences in behavior, Wallaby currently follows the default Node test runner behavior, where all tests (both `.only` and others) are executed. We do not support running with `--test-only`.

We're interested to get your feedback on this behavior, whether the differences impact you, and how differences in execution would impact your workflow if/when you switch from Wallaby to the CLI.

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. If you're still having problems, or would like to share your feedback on `.only` behavior differences, feel free to reply to this issue.
