### ISSUE TITLE
Struggling to get Wallaby running

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#347]
I seem to be getting several errors when attempting to run wallaby.js. I'm using VS2015. If I attempt to start wallaby.js I get the following output:

This is the line it seems to be complaining at:

`var start = new Date(2015, 07, 13, 09, 19, 16);`

````
wallaby.js started
core v1.0.144
Failed to execute start operation, Error: Failed to parse Scripts/Tests/spec/FilterObjectSpec.js, SyntaxError: Invalid number (15:43)
  at emitTwo (events.js:87:13)
  at process.emit (events.js:169:7)
  at handleMessage (child_process.js:306:10)
  at Pipe.channel.onread (child_process.js:334:11)
From previous event:
  at EventEmitter._.extend.start (C:\Users\ian.wright\.wallaby\core\server.js:16:2722)
  at Object.i.receive (C:\Users\ian.wright\.wallaby\core\server.js:14:1177)
  at WebSocket.<anonymous> (C:\Users\ian.wright\.wallaby\core\server.js:18:10320)
  at emitTwo (events.js:87:13)
  at WebSocket.emit (events.js:169:7)
  at Receiver.self._receiver.ontext (C:\Users\ian.wright\.wallaby\core\node_modules\ws\lib\WebSocket.js:682:10)
  at Receiver.opcodes.1.finish (C:\Users\ian.wright\.wallaby\core\node_modules\ws\lib\Receiver.js:391:14)
  at Receiver.expectHandler (C:\Users\ian.wright\.wallaby\core\node_modules\ws\lib\Receiver.js:372:33)
  at Receiver.add (C:\Users\ian.wright\.wallaby\core\node_modules\ws\lib\Receiver.js:87:24)
  at Socket.firstHandler (C:\Users\ian.wright\.wallaby\core\node_modules\ws\lib\WebSocket.js:663:22)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)
Error: write EPIPE
  at exports._errnoException (util.js:749:11)
  at ChildProcess.target._send (child_process.js:466:28)
  at ChildProcess.target.send (child_process.js:398:12)
  at i.send (C:\Users\ian.wright\.wallaby\core\server.js:15:23923)
  at n._run (C:\Users\ian.wright\.wallaby\core\server.js:15:24339)
  at emitOne (events.js:77:13)
  at i.emit (events.js:166:7)
  at i.onMessage (C:\Users\ian.wright\.wallaby\core\server.js:15:23755)
  at ChildProcess.g (events.js:257:16)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at handleMessage (child_process.js:306:10)
  at Pipe.channel.onread (child_process.js:334:11)

Error: write EPIPE
  at exports._errnoException (util.js:749:11)
  at ChildProcess.target._send (child_process.js:466:28)
  at ChildProcess.target.send (child_process.js:398:12)
  at i.send (C:\Users\ian.wright\.wallaby\core\server.js:15:23923)
  at n._run (C:\Users\ian.wright\.wallaby\core\server.js:15:24339)
  at emitOne (events.js:77:13)
  at i.emit (events.js:166:7)
  at i.onMessage (C:\Users\ian.wright\.wallaby\core\server.js:15:23755)
  at ChildProcess.g (events.js:257:16)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at handleMessage (child_process.js:306:10)
  at Pipe.channel.onread (child_process.js:334:11)

Error: write EPIPE
  at exports._errnoException (util.js:749:11)
  at ChildProcess.target._send (child_process.js:466:28)
  at ChildProcess.target.send (child_process.js:398:12)
  at i.send (C:\Users\ian.wright\.wallaby\core\server.js:15:23923)
  at n._run (C:\Users\ian.wright\.wallaby\core\server.js:15:24339)
  at emitOne (events.js:77:13)
  at i.emit (events.js:166:7)
  at i.onMessage (C:\Users\ian.wright\.wallaby\core\server.js:15:23755)
  at ChildProcess.g (events.js:257:16)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at handleMessage (child_process.js:306:10)
  at Pipe.channel.onread (child_process.js:334:11)

Error: write EPIPE
  at exports._errnoException (util.js:749:11)
  at ChildProcess.target._send (child_process.js:466:28)
  at ChildProcess.target.send (child_process.js:398:12)
  at i.send (C:\Users\ian.wright\.wallaby\core\server.js:15:23923)
  at n._run (C:\Users\ian.wright\.wallaby\core\server.js:15:24339)
  at emitOne (events.js:77:13)
  at i.emit (events.js:166:7)
  at i.onMessage (C:\Users\ian.wright\.wallaby\core\server.js:15:23755)
  at ChildProcess.g (events.js:257:16)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at handleMessage (child_process.js:306:10)
  at Pipe.channel.onread (child_process.js:334:11)

Error: write EPIPE
  at exports._errnoException (util.js:749:11)
  at ChildProcess.target._send (child_process.js:466:28)
  at ChildProcess.target.send (child_process.js:398:12)
  at i.send (C:\Users\ian.wright\.wallaby\core\server.js:15:23923)
  at n._run (C:\Users\ian.wright\.wallaby\core\server.js:15:24339)
  at emitOne (events.js:77:13)
  at i.emit (events.js:166:7)
  at i.onMessage (C:\Users\ian.wright\.wallaby\core\server.js:15:23755)
  at ChildProcess.g (events.js:257:16)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at handleMessage (child_process.js:306:10)
  at Pipe.channel.onread (child_process.js:334:11)
````

If I attempt to `Run Project Tests` I get the following error, but I guess at it seemed to fail to start that's to be expected

````
​​​​​Test run failure: file Scripts/underscore-min.js has invalid syntax
````

**Comment by ArtemGovorov** [comment]
This line is not a valid JavaScript:
``` JavaScript
var start = new Date(2015, 07, 13, 09, 19, 16);
```
and that's what it's complaining about: `SyntaxError: Invalid number`.
`07` and `09` are not valid numbers. There're only few scenarios when a number literal can start with `0` and your case is not one of them. In ES5 standard only hex number can start with `0`, but `x` or `X` should follow it, for example `0x1`. In ES6 standard there're also [octal and binary literals](http://www.2ality.com/2015/04/numbers-math-es6.html), but they should start with `0o`/`0O` and `0b`/`0B` respectively.

Some engines/browsers may still accept and execute the code, but wallaby.js needs to parse your code before execution and its parser doesn't accept invalid JavaScript, [neither does babel](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=true&code=var%20start%20%3D%20new%20Date(2015%2C%2007%2C%2013%2C%2009%2C%2019%2C%2016)%3B).
So you if mean to use `7` and `9`, then you should change the line to
``` JavaScript
var start = new Date(2015, 7, 13, 9, 19, 16);
```
and it should work for you.

**Comment by IPWright83** [comment]
Thanks @ArtemGovorov - I'd not had any problems running that line but I can see your point. Just knowing that Wallaby enforces stricter rules than some of the browsers is enough to massively help, because at least then I'll immediately jump to the ES5 spec to verify issues.
