### ISSUE TITLE
Cannot read property 'sections' of undefined

### ISSUE THREAD

**Issue by TylerGarlick** [wallabyjs/public#377]
I'm getting a weird error when I try to run wallaby.  In the failing tests pane, I get the message: 'Cannot read property 'sections' of undefined'.  

Let me know if you need additional details.

**Wallaby Console Output**
----
```js
wallaby.js started
core v1.0.152
Failed to execute start operation, TypeError: Cannot read property 'sections' of undefined
From previous event:
  at EventEmitter._.extend.start (/Users/tylergarlick/Library/Caches/WebStorm11/wallaby/wallaby/server.js:16:2722)
  at Object.i.receive (/Users/tylergarlick/Library/Caches/WebStorm11/wallaby/wallaby/server.js:14:1177)
  at WebSocket.<anonymous> (/Users/tylergarlick/Library/Caches/WebStorm11/wallaby/wallaby/server.js:18:10358)
  at emitTwo (events.js:87:13)
  at WebSocket.emit (events.js:172:7)
  at Receiver.self._receiver.ontext (/Users/tylergarlick/Library/Caches/WebStorm11/wallaby/wallaby/node_modules/ws/lib/WebSocket.js:682:10)
  at Receiver.opcodes.1.finish (/Users/tylergarlick/Library/Caches/WebStorm11/wallaby/wallaby/node_modules/ws/lib/Receiver.js:391:14)
  at Receiver.expectHandler (/Users/tylergarlick/Library/Caches/WebStorm11/wallaby/wallaby/node_modules/ws/lib/Receiver.js:372:33)
  at Receiver.add (/Users/tylergarlick/Library/Caches/WebStorm11/wallaby/wallaby/node_modules/ws/lib/Receiver.js:87:24)
  at Socket.firstHandler (/Users/tylergarlick/Library/Caches/WebStorm11/wallaby/wallaby/node_modules/ws/lib/WebSocket.js:663:22)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)
```
----

**Wallaby Configuration**
```js
'use strict';

const Fs = require('fs');
const Path = require('path');

const babelConfiguration = JSON.parse(Fs.readFileSync(Path.join(__dirname, '.babelrc')));
babelConfiguration.babel = require('babel-core');

module.exports = (wallaby) => {
  return {
    files: [
      'plugins/**/*',
      { pattern: '**/*.tests.js', ignore: true }
    ],
    tests: [
      '**/*.test.js'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    compilers: {
      '**/*.js': wallaby.compilers.babel(babelConfiguration)
    }
  }
};
```

Project folder structure:
```
plugins
  |- hooks
    |- test
     |- hooks.tests.js (plugin specific test)
    |- index.js
  |- notifier
    |- test
      |- notifier.tests.js
```

**Comment by TylerGarlick** [comment]
I should also clarify this is in webstorm.

**Comment by ArtemGovorov** [comment]
The error reason is most likely an incorrect/unexpected source map generated for one of the babel compiled files. You may add [`debug: true`](http://wallabyjs.com/docs/config/overview.html#debug-setting) to your config to see what file it stops processing on.

My suspicion is that wallaby/babel fails to generate correct source map for one of the files in your node modules, so the first thing to try is to change your tests scope to be more specific - like `'plugins/**/*.test.js'`. It's better for performance reasons as well, otherwise all of your files, including `node_modules` are scanned for `'**/*.tests.js'` and some of the node modules may actually contain files satisfying the pattern. Further compilation of these files with babel and processing in wallaby.js, may be the reason for the `Cannot read property 'sections' of undefined` error that you're getting.

Anyway, I can't reproduce the issue, here is the repository with your structure and config - https://github.com/ArtemGovorov/wallaby-377, please have a look what's different between it and your repo where the issue is reproduced.

One thing I had to change was your `tests` pattern from `'**/*.test.js'` to `'**/*.tests.js'`, otherwise I was getting an expected `No files with tests found, check your tests list patterns.` error.

**Comment by TylerGarlick** [comment]
Thanks for your feedback, I think it was a combination of wrong glob for testing and babel, either way it's now working.   :+1: 

Keep up the good work!
