### ISSUE TITLE
Receiving error in node module: 'multiply is not defined'

### ISSUE THREAD

**Issue by kutenai** [wallabyjs/public#394]
This error does not make a lot of sense. The error is in a library file =>

`node_modules/package.json/lib/advanced_math.js`. 

I've included that file in this gist: https://gist.github.com/kutenai/a6b3a5d69b4fe8670b66

The error is on line 38, and the error reads:

`Runtime error: ReferenceError: multiply is not defined`

Here is a block of text from the debug log

```
Mon, 11 Jan 2016 17:46:03 GMT wallaby:project Running all tests
Mon, 11 Jan 2016 17:46:03 GMT wallaby:workers Starting test run, priority: 3
Mon, 11 Jan 2016 17:46:03 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #5ly1r]
Mon, 11 Jan 2016 17:46:03 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #5ly1r]
Mon, 11 Jan 2016 17:46:03 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #5ly1r]
Mon, 11 Jan 2016 17:46:03 GMT wallaby:workers Running tests in sandbox [worker #0, session #5ly1r]
Runtime error: ReferenceError: multiply is not defined
Mon, 11 Jan 2016 17:46:03 GMT wallaby:workers Sandbox (active) [5ly1r] error: ReferenceError: multiply is not defined
Mon, 11 Jan 2016 17:46:03 GMT wallaby:workers Failed to map the stack to user code, entry message: ReferenceError: multiply is not defined, stack: ReferenceError: multiply is not defined
    at Object.<anonymous> (/Volumes/bnpraid/Users/kutenai/node_modules/package.json/lib/advanced_math.js:38:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Object.<anonymous> (/Volumes/bnpraid/Users/kutenai/node_modules/package.json/lib/advanced_math.js:38:18)
    at Function.Module._load (module.js:311:12)
    at Module._compile (module.js:435:26)
    at Module.require (module.js:366:17)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.s.require (/Volumes/bnpraid/Users/kutenai/Library/Caches/PyCharm50/wallaby/wallaby/server.js:18:9557)
    at Module.load (module.js:356:32)
    at require (module.js:385:17)
    at Function.Module._load (module.js:311:12)
    at Object.<anonymous> (/Volumes/bnpraid/Users/kutenai/node_modules/package.json/bin/main.js:5:16)
    at Module.require (module.js:366:17)
    at Module._compile (module.js:435:26)
    at require (module.js:385:17)
    at Object.<anonymous> (/Volumes/bnpraid/Users/kutenai/node_modules/package.json/bin/main.js:5:16)
    at Module._compile (module.js:435:26)
Mon, 11 Jan 2016 17:46:03 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
Mon, 11 Jan 2016 17:46:03 GMT wallaby:workers Sandbox [5ly1r] is responsive, closing it
Mon, 11 Jan 2016 17:46:03 GMT wallaby:project Test run finished
```

Wallaby is running, no other errors, but not finding my test (just have one for now.. keeping it simple.) - but I don't want to debug that while this big red error is starting at me.

**Comment by kutenai** [comment]
It seems I had an old node_modules directory in my home path.. that was causing some issues. Not sure how it found it..

**Comment by ArtemGovorov** [comment]
Thanks for the update. From the error stack it looks like it was trying to load the package.json module from `/Volumes/bnpraid/Users/kutenai/node_modules`. It normally happens when it can't find the module locally in the project (so it starts looking for the module in parent folders) and in your case it has found one. Perhaps the module wasn't installed locally?
