### ISSUE TITLE
Angular 2: "moduleId: module.id" causes "Potentially unhandled rejection"

### ISSUE THREAD

**Issue by yanglee** [wallabyjs/public#421]
Hello,

Environment:
* Wallaby 1.0.46
* Node.js 5.5.0 (32bit)
* WebStorm 11.0.3 (32bit)
* Windows 10 (64bit)

At [this repository](https://github.com/duncanhunter/angular2-jspm) (referenced by [official docs](http://wallabyjs.com/docs/integration/systemjs.html)).

In the [app.ts](https://github.com/duncanhunter/angular2-jspm/blob/master/app/components/app/app.ts) file, add

```javascript
moduleId: module.id
```

so it looks like:

```javascript
@Component({
    directives: [Typeahead],
    moduleId: module.id,
    selector: 'my-app',
    template: template
})
export class AppComponent {
    public plop(s:string) {
        console.log(s)
    }

    testFunction(){
        return 2;
    }
}
```

Wallaby immediately throws:
```
wallaby.js started
core v1.0.165
console.error: Potentially unhandled rejection [3] 	at http://localhost:21961/wallaby_sandbox0.html:70:41
	at execute (http://localhost:21961/wallaby_sandbox0.html:77:14)
	at u (http://localhost:21961/jspm_packages/system.js?1453811534538&wallabyFileId=3:5:2942)
	at u (http://localhost:21961/jspm_packages/system.js?1453811534538&wallabyFileId=3:5:2874)
	at execute (http://localhost:21961/jspm_packages/system.js?1453811534538&wallabyFileId=3:5:5939)
	at b (http://localhost:21961/jspm_packages/system.js?1453811534538&wallabyFileId=3:4:15663)
	at x (http://localhost:21961/jspm_packages/system.js?1453811534538&wallabyFileId=3:4:16036)
	at p (http://localhost:21961/jspm_packages/system.js?1453811534538&wallabyFileId=3:4:13914)
	at h (http://localhost:21961/jspm_packages/system.js?1453811534538&wallabyFileId=3:4:14299)
	at http://localhost:21961/jspm_packages/system.js?1453811534538&wallabyFileId=3:4:18729
	at M (http://localhost:21961/jspm_packages/system-polyfills.js:4:16072)
	at H (http://localhost:21961/jspm_packages/system-polyfills.js:4:15701)
	at when (http://localhost:21961/jspm_packages/system-polyfills.js:4:19375)
	at run (http://localhost:21961/jspm_packages/system-polyfills.js:4:18414)
	at _drain (http://localhost:21961/jspm_packages/system-polyfills.js:4:7105)
	at drain (http://localhost:21961/jspm_packages/system-polyfills.js:4:4237)
```

Setting ```moduleId``` in Angular 2 allows relative paths for templateUrl ([see official docs](https://angular.io/docs/js/latest/api/core/ComponentMetadata-class.html)), a quite important feature.

Any idea how to fix this? Thanks in advance.

**Comment by ArtemGovorov** [comment]
@yanglee The docs says 

>  In CommonJS, this can always be set to module.id

However the sample is for SystemJS, there's no such thing as `module` there as opposed to CommonJS, hence the error. I'm not yet very familiar with angular2, so not sure if/when/how it's supposed to work with SystemJS. If you could point me to a working karma configuration for some code using `module.id` with SystemJS, then I'm happy to investigate it.

**Comment by ArtemGovorov** [comment]
According to the [SystemJS docs](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md), module.id is only available for CommonJs format.

If you'd like to use in your app, you need to change 2 things in the sample:
- Change TypeScript compilation from `module: 4` (SystemJs) to `module: 1` here https://github.com/duncanhunter/angular2-jspm/blob/master/wallaby.js#L26
- Comment out this line: https://github.com/duncanhunter/angular2-jspm/blob/master/wallaby.js#L51, because when using CommonJs format, systemJs can not load files via `script` tags.

After you do these 2 things, you may use `module.id` without any issues:
```
@Component({
    directives: [Typeahead],
    selector: 'my-app',
    template: template,
    moduleId: module.id
})
```

Please let me know if it helps, happy to answer any of your questions.

**Comment by yanglee** [comment]
Thanks, your solution works perfectly!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for checking.
Please note that I have sent the pull request to wallaby.js config file in the sample ng2 + SystemJS project, you may change it in your project as well to get better error reporting: https://github.com/duncanhunter/angular2-jspm/pull/2/files
