### ISSUE TITLE
SyntaxError: Parse error without any details

### ISSUE THREAD

**Issue by mrasoahaingo** [wallabyjs/public#432]
Hi,

When I run wallabyjs I got this same many error message:
```
SyntaxError: Parse error
at http://localhost:60946/__modules/1059.js?1453973032855:2
```
This js file look like this:
```javascript
window.__moduleBundler.cache[1059] = [function(__webpack_require__, module, exports) {"use strict";
const internalQuerySelector = __webpack_require__(1060).querySelector;
const internalGetAttr = __webpack_require__(897).getAttributeValue;
const URL = __webpack_require__(430).URL;

exports.documentBaseURL = function (document) {
  // https://html.spec.whatwg.org/multipage/infrastructure.html#document-base-url

  const firstBase = internalQuerySelector(document, "base[href]");
  const fallbackBaseURL = exports.fallbackBaseURL(document);

  if (firstBase === null) {
    return fallbackBaseURL;
  }

  return exports.frozenBaseURL(firstBase, fallbackBaseURL);
};

exports.fallbackBaseURL = function (document) {
  // https://html.spec.whatwg.org/multipage/infrastructure.html#fallback-base-url

  // Unimplemented: <iframe srcdoc>

  if (document._URL === "about:blank" && document._defaultView &&
      document._defaultView._parent !== document._defaultView) {
    return module.exports.documentBaseURL(document._defaultView._parent._document);
  }

  return document._URL;
};

exports.frozenBaseURL = function (baseElement, fallbackBaseURL) {
  // https://html.spec.whatwg.org/multipage/semantics.html#frozen-base-url
  // The spec is eager (setting the frozen base URL when things change); we are lazy (getting it when we need to)

  const baseHrefAttribute = internalGetAttr(baseElement, "href");

  try {
    return new URL(baseHrefAttribute, fallbackBaseURL).href;
  } catch (e) {
    return fallbackBaseURL;
  }
};

}, window.__moduleBundler.deps];
```
This is my wallaby.js file:
```javascript
var wallabyWebpack = require('wallaby-webpack');
var babel = require('babel-core');

var babelConfig = JSON.parse(require('fs').readFileSync(require('path').join(__dirname, '.babelrc')));
babelConfig.babel = babel;

var webpackConfig = require('./.js-tasks/webpack.config')

module.exports = function (wallaby) {

    var babelCompiler = wallaby.compilers.babel(babelConfig);

    var webpackPostprocessor = wallabyWebpack(webpackConfig);

    return {
        files: [
            {pattern: 'app/Resources/js/**/*.js*', load: false}
        ],

        tests: [
            {pattern: 'app/Resources/tests/mocha/**/*Test.js*', load: false}
        ],

        compilers: {
            '**/*.js*': babelCompiler
        },

        postprocessor: webpackPostprocessor,

        testFramework: 'mocha',

        debug: true
    };
};
```
For instance I run my tests via a npm scripts like this:
```
mocha --compilers js:babel-core/register --require app/Resources/tests/helpers/*.js --recursive app/Resources/tests/mocha/
```
I need to require helpers to define global.window, and global.document from jsdom for some tests that need these

Do you see where am I doing wrong? 

Thanks

**Comment by ArtemGovorov** [comment]
@mrasoahaingo So you run your tests in mocha in node.js without webpack? Any reason then why are you then trying to run tests with webpack in wallaby? Perhaps you should try doing the same with wallaby then and [use node.js to run your tests](http://wallabyjs.com/docs/integration/node.html):

```
var babel = require('babel-core');
var babelConfig = JSON.parse(require('fs')
     .readFileSync(require('path').join(__dirname, '.babelrc')));

module.exports = function (wallaby) {

    var babelCompiler = wallaby.compilers.babel(babelConfig);

    return {
        files: [
            {pattern: 'app/Resources/js/**/*.js*'}
        ],

        tests: [
            {pattern: 'app/Resources/tests/mocha/**/*Test.js*'}
        ],

        env: {
           type: 'node'
        },

        compilers: {
            '**/*.js*': babelCompiler
        },

        bootstrap: function() {
            // you may require your helpers here
        },

        testFramework: 'mocha',

        debug: true
    };
};
```

You may `require` your helpers in [the `bootstrap` function](http://wallabyjs.com/docs/config/bootstrap.html).

**Comment by mrasoahaingo** [comment]
You're right, there's no need to use webpack as on my npm script runner. So, I removed it and required helper files into bootstrap. 

```javascript
var babel = require('babel-core');

var babelConfig = JSON.parse(require('fs')
    .readFileSync(require('path').join(__dirname, '.babelrc')));

babelConfig.babel = babel;

module.exports = function (wallaby) {

    var babelCompiler = wallaby.compilers.babel(babelConfig);

    return {
        files: [
            {pattern: 'app/Resources/js/**/*.js*'}
        ],

        tests: [
            {pattern: 'app/Resources/tests/mocha/**/*Test.js*'}
        ],

        env: {
            type: 'node',
            runner: 'node'
        },

        compilers: {
            '**/*.js*': babelCompiler
        },

        bootstrap: function bootstrap(wallaby) {
            var path = require('path');
            require(path.join(wallaby.localProjectDir, 'app/Resources/tests/helpers/chai'));
            require(path.join(wallaby.localProjectDir, 'app/Resources/tests/helpers/jsdom'));
        },

        testFramework: 'mocha',

        debug: true
    };
};
```
Now I got this error, may be I must load these helper files with babel compiler?
```
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

My helper files:
```
import chai from 'chai'
import chaiSpies from 'chai-spies'
import chaiEnzyme from 'chai-enzyme'

chai.use(chaiEnzyme());
chai.use(chaiSpies);
```
```
import jsdom from 'jsdom'

const sandbox = '<div id="sandbox"></div>'

global.window = jsdom.jsdom(sandbox).defaultView
global.document = window.document

```

**Comment by ArtemGovorov** [comment]
> may be I must load these helper files with babel compiler

Correct, because node.js doesn't support ES6 imports. Just add them to your `files` list:
```
        files: [
            {pattern: 'app/Resources/js/**/*.js*'},
            {pattern: 'app/Resources/tests/helpers/chai.js'},
            {pattern: 'app/Resources/tests/helpers/jsdom.js'},
        ],
```
so they'll be compiled by wallaby babel compiler and then you may require them from your `bootstrap` function just like:
```
     bootstrap: function bootstrap(wallaby) {
            require('./app/Resources/tests/helpers/chai');
            require('./app/Resources/tests/helpers/jsdom');
        },
```

**Comment by mrasoahaingo** [comment]
Great! it works now!

Thank you

**Comment by ArtemGovorov** [comment]
@mrasoahaingo Awesome, thanks for the update!
