### ISSUE TITLE
Wallaby seems to be calling babel incorrectly.

### ISSUE THREAD

**Issue by gatorcse** [wallabyjs/public#440]
I'm trying to get wallaby to process my babel files, and after fighting my config for hours, I think I may have found an issue with wallaby, how wallaby.compiler.babel calls babel-core. [I have my example repo here](https://github.com/gatorcse/wallaby-babel-boilerplate). I have one test file at client/components/Footer/footer_spec.js.

The error that wallaby gives when I try to start it is:
```
Failed to run compilers on client/components/Footer/footer_spec.js, Error: unknown: Cannot find module '/Users/tlohman/src/boilerplate/frontend-boilerplate-master/style.css'
  at require (internal/module.js:16:19)
  at PluginPass.CallExpression (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-plugin-css-modules-transform/build/index.js:129:36)
  at newFn (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/visitors.js:293:19)
  at NodePath._call (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/path/context.js:74:18)
  at NodePath.call (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/path/context.js:46:17)
  at NodePath.visit (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/path/context.js:104:12)
  at TraversalContext.visitQueue (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/context.js:153:16)
  at TraversalContext.visitSingle (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/context.js:113:19)
  at TraversalContext.visit (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/context.js:197:19)
  at Function.traverse.node (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/index.js:139:17)
  at NodePath.visit (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/path/context.js:114:22)
  at TraversalContext.visitQueue (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/context.js:153:16)
  at TraversalContext.visitMultiple (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/context.js:108:17)
  at TraversalContext.visit (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/context.js:195:19)
  at Function.traverse.node (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/index.js:139:17)
  at NodePath.visit (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/path/context.js:114:22)
  at TraversalContext.visitQueue (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/context.js:153:16)
  at TraversalContext.visitSingle (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/context.js:113:19)
  at TraversalContext.visit (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/context.js:197:19)
  at Function.traverse.node (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/index.js:139:17)
  at Object.traverse [as default] (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-traverse/lib/index.js:61:12)
  at File.transform (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-core/lib/transformation/file/index.js:507:31)
  at /Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-core/lib/transformation/pipeline.js:49:19
  at File.wrap (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-core/lib/transformation/file/index.js:520:16)
  at Pipeline.transform (/Users/tlohman/src/boilerplate/frontend-boilerplate-master/node_modules/babel-core/lib/transformation/pipeline.js:46:17)
  at Array.forEach (native)
  at emitTwo (events.js:100:13)
  at process.emit (events.js:185:7)
  at handleMessage (internal/child_process.js:689:10)
  at Pipe.channel.onread (internal/child_process.js:440:11)
```
I'm using the atom plugin, but the same thing happens in IntelliJ as well. As you can see, it is trying to locate the required file at the root of the project, rather than relative to the source file. I confirmed that when I imported the required css files relative to project root (`import style from './client/components/Footer/style.css'`) it works.

I added some console output to the problematic line in babel-plugin-css-modules-transform, outputting file.opts. Atom's console gives (for each file):
```
Wallaby Console: Mon, 01 Feb 2016 06:04:00 GMT wallaby:processor Running 1 processor(s) for client/components/Footer/footer_spec.js
Wallaby Console: ===============
Wallaby Console: { filename: 'unknown',
Wallaby Console:   filenameRelative: 'unknown',
Wallaby Console:   inputSourceMap: undefined,
Wallaby Console:   env: {},
Wallaby Console:   mode: undefined,
Wallaby Console:   retainLines: false,
Wallaby Console:   highlightCode: true,
Wallaby Console:   suppressDeprecationMessages: false,
...
...
...
```
I truncated the output, but you can see that filename and filenameRelative are both unknown, and most of the other output is all unknown or undefined as well. When I run my tests with Mocha (also compiling with babel with `--compilers js:babel-core/register`) the the logged output for each file is:
```
{ filename: '/Users/tlohman/src/boilerplate/frontend-boilerplate-master/client/components/Footer/footer_spec.js',
  filenameRelative: '/Users/tlohman/src/boilerplate/frontend-boilerplate-master/client/components/Footer/footer_spec.js',
  inputSourceMap: undefined,
  env: {},
  mode: undefined,
  retainLines: false,
  highlightCode: true,
```
Mocha correctly sets the filename and filenameRelative.

Suspecting that babel wasn't being called correctly, I added output to the first function called by Wallaby, just before line 46 in pipeline.js in babel-core. Running wallaby outputs (for each file):
```
Wallaby Console: { presets: [ 'es2015', 'stage-0', 'react' ],
Wallaby Console:   plugins: 
Wallaby Console:    [ { visitor: [Object] },
Wallaby Console:      'css-modules-transform',
Wallaby Console:      'transform-runtime' ],
Wallaby Console:   sourceMap: true,
Wallaby Console:   comments: false }
```
It seems like wallaby is just passing along the options given to its babel compiler.

Running with mocha gives:
```
{ filename: '/Users/tlohman/src/boilerplate/frontend-boilerplate-master/client/components/Footer/footer_spec.js',
  filenameRelative: undefined,
  inputSourceMap: undefined,
  env: {},
  mode: undefined,
  retainLines: false,
  highlightCode: true,
  suppressDeprecationMessages: false,
  presets: [],
  plugins:
   [ [ [Object], undefined ],
     [ [Object], undefined ],
     [ [Object], undefined ],
...
...
...
```
I also checked what was output when webpack built the bundle:
```
{ inputSourceMap: undefined,
  sourceRoot: '/Users/tlohman/src/boilerplate/frontend-boilerplate-master',
  filename: '/Users/tlohman/src/boilerplate/frontend-boilerplate-master/client/components/Footer/index.js',
  sourceMap: false,
  sourceFileName: 'client/components/Footer/index.js' }
```
Where wallaby seems to just pass in the babel configuration object, webpack and mocha send in information about the file. The properties that they send are also in the file.opts object from the earlier round of output.

Am I missing something sublte in my config? Or is wallaby calling babel incorrectly?

**Comment by ArtemGovorov** [comment]
Thanks for the report and the investigation! The issue is fixed the latest wallaby core v1.0.169. The core should be updated automatically next time you restart wallaby in WebStorm or within few minutes after next wallaby (re)start in Atom (you may also [force the update in Atom](https://github.com/wallabyjs/public/issues/413#issuecomment-173174486) if you prefer to get it immediately).

**Comment by ArtemGovorov** [comment]
If you're interested, the issue was that we were not setting the `filename` property for babel transformations. It's totally optional in babel-core (only used for some reporting) and apparently the majority of babel plugins are not using it, but `babel-plugin-css-modules-transform` is.

**Comment by gatorcse** [comment]
Thank you for your prompt response and fix! I had to do the force update for Atom, but I can confirm the fix works in both IntelliJ and Atom.

**Comment by ArtemGovorov** [comment]
@gatorcse Awesome, thanks for checking!
