### ISSUE TITLE
Error on Wallaby Start using SublimeText on Fedora

### ISSUE THREAD

**Issue by Hyzual** [wallabyjs/public#450]
Hi ! I've been anticipating WallabyJS on SublimeText for a long time. Thanks a lot for making it !

I recently installed it on my local SublimeText on Fedora 22, but always got stuck on the following error when running the Wallaby - Start command.
It displays in the bottom bar "installing/updating wallaby.js core" and then stops and logs the following error in the console:

```
Exception in thread Thread-14:
Traceback (most recent call last):
  File "./tarfile.py", line 1656, in bz2open
  File "./bz2.py", line 21, in <module>
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "<string>", line 582, in start
  File "<string>", line 603, in checkForUpdates
  File "<string>", line 634, in updatePhantom
  File "<string>", line 29, in extract_file
  File "./tarfile.py", line 1584, in open
  File "./tarfile.py", line 1658, in bz2open
tarfile.CompressionError: bz2 module is not available
```

I've found that it seems to be distribution-specific (see http://forums.fedoraforum.org/showthread.php?t=258694).
The workaround explained in the link works: 

```bash
sudo ln -s /lib64/libbz2.so.1.6 /lib64/libbz2.so.1.1
```

After that, it installs correctly. I hope you can add some kind of test for this library, in any case others encountering this problem won't waste more time :).

**Comment by ArtemGovorov** [comment]
Hi,
thanks a lot for posting the workaround! We will have a look if we can add some checks to load the correct version of the lib.

**Comment by ArtemGovorov** [comment]
In the latest v1.0.14 (published and should be available in a hour), we have added an additional check and the attempt to unzip using `tar` command if the original unzipping attempt had failed.
