### ISSUE TITLE
Wallaby not starting in ST3

### ISSUE THREAD

**Issue by creeonix** [wallabyjs/public#469]
I am having trouble starting wallaby in Sublime Text 3
Using Electron + React + Babel + Webpack

Error:
```
[Error]: Runtime error: ReferenceError: window is not defined​​
​​​​​[Info]: Sun, 21 Feb 2016 13:30:07 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #354g3]​​​​​
​​[Error]:     at emitTwo (events.js:87:13)​​
​​​​​[Info]: Sun, 21 Feb 2016 13:30:07 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #354g3]​​​​​
​​[Error]:     at WebSocket.emit (events.js:172:7)​​
​​​​​[Info]: Sun, 21 Feb 2016 13:30:07 GMT wallaby:workers Running tests in sandbox [worker #0, session #354g3]​​​​​
​​​​​[Info]: Sun, 21 Feb 2016 13:30:07 GMT wallaby:workers Sandbox (active) [354g3] error: ReferenceError: window is not defined​​​​​
​​​​​[Info]: Sun, 21 Feb 2016 13:30:07 GMT wallaby:workers Failed to map the stack to user code, entry message: ReferenceError: window is not defined, stack: ReferenceError: window is not defined​​​​​
​​​​​[Info]:     at eval (eval at <anonymous> (.../Sublime Text 3/Packages/Wallaby/wallaby/runners/node/bootstrap.js:14:848), <anonymous>:2:7)​​​​​
​​​​​[Info]:     at eval (eval at <anonymous> (.../Sublime Text 3/Packages/Wallaby/wallaby/runners/node/bootstrap.js:14:848), <anonymous>:4:7)​​​​​
​​​​​[Info]:     at module.exports (.../Sublime Text 3/Packages/Wallaby/wallaby/runners/node/bootstrap.js:14:44)​​​​​
​​​​​[Info]:     at Object._.in:run (.../Sublime Text 3/Packages/Wallaby/wallaby/server.js:15:16926)​​​​​
​​​​​[Info]:     at WebSocket.<anonymous> (.../Sublime Text 3/Packages/Wallaby/wallaby/server.js:15:16001)​​​​​
​​​​​[Info]:     at emitTwo (events.js:87:13)​​​​​
​​​​​[Info]:     at WebSocket.emit (events.js:172:7)​​​​​
​​​​​[Info]:     at Receiver.self._receiver.ontext (.../Sublime Text 3/Packages/Wallaby/wallaby/node_modules/ws/lib/WebSocket.js:682:10)​​​​​
​​​​​[Info]:     at ​​​​​
```

wallaby.js
```js
var wallabyWebpack = require('wallaby-webpack');
var wallabyPostprocessor = wallabyWebpack({
    resolve: {
      extensions: ['', '.js', '.jsx'],
    },
  }
);

module.exports = function (wallaby) {
  return {
    debug: true,

    files: [
      { pattern: 'app/actions/**/*.js*', load: false },
      { pattern: 'app/reducers/**/*.js*', load: false },
      { pattern: 'app/components/**/*.js*', load: false }
    ],

    postprocessor: wallabyPostprocessor,

    tests: [
      { pattern: 'test/components/**/*.spec.js*', load: false }
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    env: {
      type: 'node'
    },

    testFramework: 'mocha',

    setup: function () {
      window.expect = chai.expect;
      window.__moduleBundler.loadTests();
    }
  };
};
```

**Comment by ArtemGovorov** [comment]
It looks like you are using node environment:
```
env: {
      type: 'node'
    },
```
and webpack at the same time, and this scenario is not supported in wallaby.

Depending on on whether or not your tests run in pure node.js environment, you may either remove webpack from your config, so it looks like:

```javascript
module.exports = function (wallaby) {
  return {
    debug: true,

    files: [
      { pattern: 'app/actions/**/*.js*', load: false },
      { pattern: 'app/reducers/**/*.js*', load: false },
      { pattern: 'app/components/**/*.js*', load: false }
    ],

    tests: [
      { pattern: 'test/components/**/*.spec.js*', load: false }
    ],

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel()
    },

    env: {
      type: 'node'
    },

    testFramework: 'mocha',

    setup: function () {
      global.expect = require('chai').expect;
    }
  };
};
```

or make it run in browser environment (PhantomJs) by removing env.type setting: 
```javascript
var wallabyWebpack = require('wallaby-webpack');
var wallabyPostprocessor = wallabyWebpack({
    resolve: {
      extensions: ['', '.js', '.jsx'],
    },
  }
);

module.exports = function (wallaby) {
  return {
    debug: true,

    files: [
      { pattern: 'app/actions/**/*.js*', load: false },
      { pattern: 'app/reducers/**/*.js*', load: false },
      { pattern: 'app/components/**/*.js*', load: false }
    ],

    postprocessor: wallabyPostprocessor,

    tests: [
      { pattern: 'test/components/**/*.spec.js*', load: false }
    ],

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel()
    },

    testFramework: 'mocha',

    setup: function () {
      window.expect = chai.expect;
      window.__moduleBundler.loadTests();
    }
  };
};
```

(note that for both examples I have changed your compiler pattern to include .jsx files).

**Comment by creeonix** [comment]
Thanks. One question, why it cannot map test to code? (I see white squares everywhere)

**Comment by ArtemGovorov** [comment]
> Thanks. One question, why it cannot map test to code? (I see white squares everywhere)

It's hard to tell, does it say that some tests passed/failed? Are there any errors in [Wallaby Console](http://wallabyjs.com/docs/intro/get-started-sublime.html#troubleshooting)?

**Comment by ArtemGovorov** [comment]
If there's nothing helpful in Wallaby Console and your tests are passing, but you still see white squares everywhere, perhaps you could create and share a small sample GH repo reproducing the issue, I'm happy to have a look and find out what's wrong.

**Comment by creeonix** [comment]
No errors at all. Basically I took this boilerplate and I am building small app on top of it: https://github.com/chentsulin/electron-react-boilerplate 
Then I decided to try out wallaby there.
with config: 
```
module.exports = function (wallaby) {
  return {
    debug: true,

    files: [
      { pattern: 'app/actions/**/*.js*', load: false },
      { pattern: 'app/reducers/**/*.js*', load: false },
      { pattern: 'app/components/**/*.js*', load: false }
    ],

    tests: [
      { pattern: 'test/actions/**/*.js*', load: false },
      { pattern: 'test/reducers/**/*.js*', load: false },
      { pattern: 'test/components/**/*.js*', load: false }
    ],

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel()
    },

    env: {
      type: 'node'
    },

    testFramework: 'mocha',

    setup: function () {
      global.expect = require('chai').expect;
    }
  };
};
```

That boilerplate has same structure and some tests for counter app. The only difference is I updated `react-router` to 2.0, but that does not matter.

**Comment by ArtemGovorov** [comment]
Thanks for the repo link. it wasn't working because for node.js you need to remove `load: false` from your files and tests patterns (sorry for providing a bad sample). But anyway, after looking into it, I have realised that you can't use pure node because the code imports css, so needs webpack loaders. 

Here is the config that should work for you:

```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpack = require('webpack');
var wallabyPostprocessor = wallabyWebpack({
    resolve: {
      extensions: ['', '.js', '.jsx']
    },
    externals: {
      'sinon': 'sinon'
    },
    module: {
      loaders: [ {
        test: /\.module\.css$/,
        loaders: [
          'style-loader',
          'css-loader?modules&sourceMap&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!'
        ]
      }]
    }
  }
);

module.exports = function (wallaby) {

  process.env.BABEL_ENV = 'test';

  return {
    debug: true,

    files: [
      {pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false},
      {pattern: 'node_modules/sinon/pkg/sinon.js', instrument: false},
      {pattern: 'app/actions/**/*.js*', load: false},
      {pattern: 'app/reducers/**/*.js*', load: false},
      {pattern: 'app/components/**/*.js*', load: false},
      {pattern: 'app/components/**/*.css', load: false}
    ],

    postprocessor: wallabyPostprocessor,

    tests: [
      {pattern: 'test/components/**/*.spec.js*', load: false}
    ],

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel()
    },

    testFramework: 'mocha',

    setup: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

I have added back the webpack postprocessor, have set [babel env to `test`](http://wallabyjs.com/docs/integration/es-next.html#babel-environment), added the pattern ti icnlude css files: `{pattern: 'app/components/**/*.css', load: false}` as they are used by components being tested.

Also, because for browser environment wallaby.js is using PhantomJs to run tests, I have added `phantomjs-polyfill` to the files list (it polyfills `Function.prototype.bind` missing in PhantomJs 1.9.x), so you also need to run:
```
 npm install --save-dev phantomjs-polyfill
```
Note that you don't need this if you switch from the default version of PhantomJs (that needs the polyfill) to [PhantomJs 2](http://wallabyjs.com/docs/integration/phantomjs2.html) (that doesn't need it).

I have also made `sinon` to be an external lib by loading it in the files list (globally) and telling webpack that it is external. You may do the same for `react` and other libs if you like. It's optional, just faster when you run your tests to provide ready libs rather than making webpack to compile them every time.

**Comment by creeonix** [comment]
Still don't get what am I doing wrong. It just does not work for me (just checked out fresh repo from my link above, added this config). Installled phantomjs-polyfill.

I am using node 5.0 if it matters
```
[Error]: ModuleBuildError: Module build failed: ReferenceError: Promise is not defined​​
​​​​​[Info]: Mon, 22 Feb 2016 19:43:19 GMT wallaby:processor Finished running one processor for app/components/Counter.js​​​​​
​​[Error]:     at LazyResult.async (<path>/electron-react-boilerplate/node_modules/postcss/lib/lazy-result.js:157:31)​​
​​[Error]:     at LazyResult.then (<path>/electron-react-boilerplate/node_modules/postcss/lib/lazy-result.js:79:21)​​
​​[Error]:     at processCss (<path>/electron-react-boilerplate/node_modules/css-loader/lib/processCss.js:198:5)​​
​​[Error]:     at Object.module.exports (<path>/electron-react-boilerplate/node_modules/css-loader/lib/loader.js:24:2)​​
​​[Error]:     at DependenciesBlock.onModuleBuildFailed (<path>/electron-react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)​​
​​[Error]:     at nextLoader (<path>/electron-react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)​​
​​[Error]:     at <path>/electron-react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15​​
​​[Error]:     at runSyncOrAsync (<path>/electron-react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)​​
​​[Error]:     at nextLoader (<path>/electron-react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)​​
​​[Error]:     at <path>/electron-react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5​​
​​[Error]:     at Storage.finished (<path>/electron-react-boilerplate/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)​​
​​[Error]:     at <path>/electron-react-boilerplate/node_modules/webpack/node_modules/graceful-fs/graceful-fs.js:78:16​​
​​[Error]:     at fs.js:272:14​​
​​[Error]:     at <path>/electron-react-boilerplate/node_modules/webpack/node_modules/graceful-fs/graceful-fs.js:43:10​​
​​[Error]:     at Object.oncomplete (fs.js:108:15)​​
​​[Error]: ModuleBuildError: Module build failed: ReferenceError: Promise is not defined​​
​​[Error]:     at LazyResult.async (<path>/electron-react-boilerplate/node_modules/postcss/lib/lazy-result.js:157:31)​​
​​[Error]:     at LazyResult.then (<path>/electron-react-boilerplate/node_modules/postcss/lib/lazy-result.js:79:21)​​
​​[Error]:     at processCss (<path>/electron-react-boilerplate/node_modules/css-loader/lib/processCss.js:198:5)​​
​​[Error]:     at Object.module.exports (<path>/electron-react-boilerplate/node_modules/css-loader/lib/loader.js:24:2)​​
​​[Error]:     at DependenciesBlock.onModuleBuildFailed (<path>/electron-react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)​​
​​[Error]:     at nextLoader (<path>/electron-react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)​​
​​[Error]:     at <path>/electron-react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15​​
​​[Error]:     at runSyncOrAsync (<path>/electron-react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)​​
​​[Error]:     at nextLoader (<path>/electron-react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)​​
​​[Error]:     at <path>/electron-react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5​​
​​[Error]:     at Storage.finished (<path>/electron-react-boilerplate/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)​​
​​[Error]:     at <path>/electron-react-boilerplate/node_modules/webpack/node_modules/graceful-fs/graceful-fs.js:78:16​​
​​[Error]:     at fs.js:272:14​​
​​[Error]:     at <path>/electron-react-boilerplate/node_modules/webpack/node_modules/graceful-fs/graceful-fs.js:43:10​​
​​[Error]:     at Object.oncomplete (fs.js:108:15)​​
```

**Comment by ArtemGovorov** [comment]
It is webpack build error, seems like your version of node doesn't support promises. Which is strange, because node v5 should support them. What's your exact node version (`node -v`), is it `5.0.0`? Do you have it installed for your system or using nvm? Does just building the project with webpack work for you (without wallaby)?

**Comment by creeonix** [comment]
Node version is 5.4.0, `node_path` is set in `Wallaby.subl-settings`. Also, 5.4.0 is aliased as default version.

**Comment by ArtemGovorov** [comment]
Could you try adding this:
```javascript
console.log('Node version used by wallaby', process.version);
console.log(typeof global.Promise);

var wallabyWebpack = require('wallaby-webpack');
var webpack = require('webpack');
...
```
at the very beginning of your config and checking what's printed in Wallaby Console?

**Comment by creeonix** [comment]
```
​​​​​[Info]: wallaby.js stopped​​​​​
​​​​​[Info]: wallaby.js started​​​​​
​​​​​[Info]: Node version used by wallaby v5.4.0​​​​​
​​​​​[Info]: function​​​​​
​​​​​```

also, I have noticed that it does not like `'use strict';` in `webpack.config.development.js`

**Comment by ArtemGovorov** [comment]
> also, I have noticed that it does not like 'use strict'; in webpack.config.development.js

Hmm, are you loading the `webpack.config.development.js` file from your wallaby config? Because it's not something I have been trying, I have only been trying the config I shared here - https://github.com/wallabyjs/public/issues/469#issuecomment-186994362.

**Comment by ArtemGovorov** [comment]
So what I'm trying:
- this exact config: https://github.com/wallabyjs/public/issues/469#issuecomment-186994362
- in this project: https://github.com/chentsulin/electron-react-boilerplate
- node 5.4.0
and it works for me:

<img width="605" alt="screen shot 2016-02-23 at 6 47 01 pm" src="https://cloud.githubusercontent.com/assets/979966/13246216/ebf108aa-da5d-11e5-8494-d9a603938a70.png">

Perhaps it's better if you create a repo if you've changed something or doing something differently so I may have a look.

**Comment by creeonix** [comment]
I am doing exactly same thing. In exactly same project and it does not work.
`npm test` works just fine for me.
I am using nvm 
```
[creeonix@iMac.local 11:29:02] ⟩ nvm ls
       v0.10.41
        v0.12.9
         v4.2.4
->       v5.4.0
         system
default -> 5.4.0 (-> v5.4.0)
node -> stable (-> v5.4.0) (default)
stable -> 5.4 (-> v5.4.0) (default)
iojs -> N/A (default)
```

this is my `npm ll --dev=trye --depth=0`: https://gist.github.com/creeonix/bb61f904869159223566

**Comment by creeonix** [comment]
I don't know why it is trying to load `webpack.config.development.js`

**Comment by creeonix** [comment]
Here is log:
```
[Info]: Tue, 23 Feb 2016 09:34:44 GMT wallaby:project Writing to disk and caching processed file app/reducers/index.js​​​​​
​​[Error]: ​​
​​[Error]: <path>/electron-react-boilerplate/webpack.config.development.js:4​​
​​[Error]: const webpack = require('webpack');​​
​​[Error]: ^^^^^​​
​​[Error]: SyntaxError: Use of const in strict mode.​​
​​​​​[Info]: Tue, 23 Feb 2016 09:34:44 GMT wallaby:processor Finished running one processor for app/components/Home.js​​​​​
​​[Error]:     at Module._compile (module.js:439:25)​​
​​[Error]:     at Object.Module._extensions..js (module.js:474:10)​​
​​[Error]:     at Module.load (module.js:356:32)​​
​​[Error]:     at Function.Module._load (module.js:312:12)​​
​​[Error]:     at Module.require (module.js:364:17)​​
​​[Error]:     at require (module.js:380:17)​​
​​[Error]:     at Object.<anonymous> (<path>/electron-react-boilerplate/webpack.config.node.js:2:20)​​
​​[Error]:     at Module._compile (module.js:456:26)​​
​​[Error]:     at Object.Module._extensions..js (module.js:474:10)​​
​​[Error]:     at Module.load (module.js:356:32)​​
​​​​​[Info]: Tue, 23 Feb 2016 09:34:44 GMT wallaby:project Stopping process pool​​​​​
```

**Comment by ArtemGovorov** [comment]
Ok, let's try to resolve one issue at a time (perhaps they are related).

So it looks like `webpack.config.development.js` is loaded from `webpack.config.node.js` and the latter is defined in `.babelrc`, for `test` environment. Webpack-loaders are not required for wallaby (as it has its own compilers), so try to replace 

```
process.env.BABEL_ENV = 'test';
```
with 
```
process.env.BABEL_ENV = 'wallaby'; // or anything, but not 'test'
```
in your wallaby config.

**Comment by creeonix** [comment]
Ha! `process.env.BABEL_ENV = 'wallaby'` this worked. Very interesting. Why it works so differently for us on same code base.

**Comment by ArtemGovorov** [comment]
So everything worked and the error with `Promise` had gone as well?

It is interesting indeed, because it works for me with `'test'` as well: `webpack.config.node.js` and files it requires are loaded ok, etc. It looks like node is started in some way without ES6 support in your case. I have no idea how it's possible, but I have no other explanation for `SyntaxError: Use of const in strict mode.​​` and the absence of `Promise`.

**Comment by creeonix** [comment]
It seems it loads `webpack.config.node.js` from `.babelrc`

**Comment by ArtemGovorov** [comment]
@creeonix yes, I have mentioned it - https://github.com/wallabyjs/public/issues/469#issuecomment-187628914. By setting `process.env.BABEL_ENV` to anything but `test` we are making it not to load at all.

**Comment by creeonix** [comment]
Now it works as I want :) *Thanks*!
ok, I added `babelrc: false` and some configuration from `.babelrc`, so my final config is:
```js
var wallabyWebpack = require('wallaby-webpack');
var webpack = require('webpack');
var wallabyPostprocessor = wallabyWebpack({
    resolve: {
      extensions: ['', '.js', '.jsx']
    },
    externals: {
      'sinon': 'sinon'
    },
    module: {
      loaders: [ {
        test: /\.module\.css$/,
        loaders: [
          'style-loader',
          'css-loader?modules&sourceMap&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!'
        ]
      }]
    }
  }
);

module.exports = function (wallaby) {

  process.env.BABEL_ENV = 'wallaby';

  return {
    // debug: true,

    files: [
      {pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false},
      {pattern: 'node_modules/sinon/pkg/sinon.js', instrument: false},
      {pattern: 'app/*.js*', load: false},
      {pattern: 'app/utils/**/*.js*', load: false},
      {pattern: 'app/store/**/*.js*', load: false},
      {pattern: 'app/actions/**/*.js*', load: false},
      {pattern: 'app/containers/**/*.js*', load: false},
      {pattern: 'app/reducers/**/*.js*', load: false},
      {pattern: 'app/components/**/*.js*', load: false},
      {pattern: 'app/components/**/*.css', load: false}
    ],

    postprocessor: wallabyPostprocessor,

    tests: [
      {pattern: 'test/**/*.spec.js*', load: false}
    ],

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({
        babelrc: false,
        "presets": ["es2015", "stage-0", "stage-2", "react"],
        "plugins": ["add-module-exports"]
      })
    },

    testFramework: 'mocha',

    setup: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

**Comment by ArtemGovorov** [comment]
@creeonix Awesome, thanks for the update!

P.S. As you're not using `.babelrc` now, I think you may remove the `process.env.BABEL_ENV = 'wallaby';` statement as well.
