### ISSUE TITLE
TypeError: 'undefined' is not an object (evaluating 'window.__moduleBundler.loadTests')

### ISSUE THREAD

**Issue by xavierhaurie** [wallabyjs/public#499]
### Issue description or question
I am 99% sure this issue has been solved before, but I just can't find the solution after hours or searching. In fact I am totally lost right now :-)

I get errors like this:

Postprocessor run failure: Cannot find module '../../main/webapp/jsx/normalizers/DetailsNormalizer' from './src/test/karma'

Note that in the Wallaby console the error message refers to a cached file:

```
Mon, 07 Mar 2016 20:19:55 GMT wallaby:project Error: Cannot find module '../../main/webapp/jsx/normalizers/DetailsNormalizer' from '/Users/xavier/Library/Caches/IntelliJIdea15/wallaby/projects/2632598fefbb29ec/instrumented/src/test/karma'
  at /Users/xavier/IdeaProjects/protocol-review/web/node_modules/resolve/lib/async.js:55:21
  at load (/Users/xavier/IdeaProjects/protocol-review/web/node_modules/resolve/lib/async.js:69:43)
  at onex (/Users/xavier/IdeaProjects/protocol-review/web/node_modules/resolve/lib/async.js:92:31)
  at /Users/xavier/IdeaProjects/protocol-review/web/node_modules/resolve/lib/async.js:22:47
  at FSReqWrap.oncomplete (fs.js:82:15)

```

*If I comment out the postProcessor setting in the config, then I get this error instead:*

`TypeError: 'undefined' is not an object (evaluating 'window.__moduleBundler.loadTests')`

I imagine that the postProcessor errors are masking the latter error.. 

What to do?

Thank you in advance!

### Wallaby.js configuration file

```
var wallabify = require('wallabify');
var wallabyPostprocessor = wallabify({
        // browserify options, such as
        // insertGlobals: false
    }
    // you may also pass an initializer function to chain other
    // browserify options, such as transformers
    // , b => b.exclude('mkdirp').transform(require('babelify'))
);

module.exports = function (wallaby) {
    return {
        "files": [
            {pattern: 'src/main/webapp/jsx/**/*.js', load: false},
            {pattern: 'src/main/webapp/jsx/**/*.jsx', load: false}
        ],

        "tests": [
            {pattern: "src/test/karma/**/*.js", load: false},
            {pattern: "src/test/karma/**/*.jsx", load: false}
        ],

        "testFramework": "jasmine",

        "compilers": {
            "**/*.js": wallaby.compilers.babel({
                presets: ['es2015', 'react', "stage-0"]
            }),
            "**/*.jsx": wallaby.compilers.babel({
                presets: ['es2015', 'react', "stage-0"]
            })
        },

        bootstrap: function () {
            // required to trigger tests loading
            window.__moduleBundler.loadTests();
        },

        postprocessor: wallabyPostprocessor,

        "debug": true
    };
};
```

### Code editor or IDE name and version

IntelliJ IDEA v15

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
If you remove `postprocessor` setting, then the `TypeError: 'undefined' is not an object (evaluating 'window.__moduleBundler.loadTests')` is expected, because the code that sets `window.__moduleBundler` is generated by postprocessor.

So the real issue here is that browserify fails to compile the project because it can't find one of the referenced files in wallaby cache.

Is the `src/main/webapp/jsx/normalizers/DetailsNormalizer` covered by one of your `files` patterns?
Could you make sure the file is in this folder when you start wallaby: 
`/Users/xavier/Library/Caches/IntelliJIdea15/wallaby/projects/2632598fefbb29ec/instrumented/src//main/webapp/jsx/normalizers/`?

Another important thing to check is that these patterns [only contain actual test files](http://wallabyjs.com/docs/config/files.html#tests) (files with `describe`/`it` in them)
```javascript
{pattern: "src/test/karma/**/*.js", load: false},
{pattern: "src/test/karma/**/*.jsx", load: false}
```
If you have anything else there, like test helpers there, they should be listed in the `files` list.

**Comment by xavierhaurie** [comment]
I checked that my pattern matches only test files, and I added missing describe/it calls to a test file that had only commented out code in it.

I then checked whether the modules that were not found were or were not in the cache, and they are in the cache. So I fixed my import statements to include the file extensions (.js, .jsx) because that was what was breaking the imports.

But, I still get a whole bunch of these:

ReferenceError: Can't find variable: require
	at src/main/webapp/jsx/actions/__tests__/testAppActions.jsx:3

ReferenceError: Can't find variable: exports
	at src/main/webapp/jsx/actions/appActions.jsx:3

I'll try and reduce this issue to its simplest possible form. In the meantime if you have any other idea please let me know :-)

**Comment by xavierhaurie** [comment]
I am down to this:

```
var wallabify = require('wallabify');
var wallabyPostprocessor = wallabify({});

module.exports = function (wallaby) {
    return {
        "files": [
            {pattern: 'src/main/webapp/jsx/**/*.js', load: false},
            {pattern: 'src/main/webapp/jsx/**/*.jsx', load: false}
        ],

        "tests": [
            {pattern: "src/test/karma/**/test*.js", load: false},
            {pattern: "src/test/karma/**/test*.jsx", load: false}
        ],

        "testFramework": "jasmine",

        "compilers": {
            "**/*.js": wallaby.compilers.babel({
                presets: ['es2015', 'react', "stage-0"]
            }),
            "**/*.jsx": wallaby.compilers.babel({
                presets: ['es2015', 'react', "stage-0"]
            })
        },

        bootstrap: function () {
            "use strict";
            window.__moduleBundler.loadTests();
        },

        postprocessor: wallabyPostprocessor,

        "debug": true
    };
};
```

and I get this at the end of my Wallaby console:

```
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Test executed: should pass
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Test executed: should pass too
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Run 2 test(s), skipped 0 test(s)
Runtime error: TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
at http://localhost:58152/__modules/HTMLDOMPropertyConfig.bba13ee00fdb9f8294526aa66a23557e.js?1457473692764:32
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Sandbox (active) [qay31] error: TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Failed to map the stack to user code, entry message: TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)'), stack: TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
at http://localhost:58152/__modules/HTMLDOMPropertyConfig.bba13ee00fdb9f8294526aa66a23557e.js?1457473692764:32
Runtime error: TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Sandbox (active) [qay31] error: TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Loaded 0 test(s)
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
Tue, 08 Mar 2016 21:48:15 GMT wallaby:middleware Preparing to serve /src/test/karma/testSimpleApplicationModules.jsx.bro.js
Tue, 08 Mar 2016 21:48:15 GMT wallaby:middleware Serving /src/test/karma/testSimpleApplicationModules.jsx.bro.js from cache
Runtime error: TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
Runtime error: TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
at http://localhost:58152/__modules/HTMLDOMPropertyConfig.bba13ee00fdb9f8294526aa66a23557e.js?1457473692764:32
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Sandbox (active) [opao8] error: TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Sandbox (active) [opao8] error: TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Failed to map the stack to user code, entry message: TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)'), stack: TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
at http://localhost:58152/__modules/HTMLDOMPropertyConfig.bba13ee00fdb9f8294526aa66a23557e.js?1457473692764:32
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Sandbox [34ron] is responsive, closing it
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Sandbox [y9scl] is responsive, closing it
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Sandbox [qay31] is responsive, closing it
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Sandbox [opao8] is responsive, closing it
Tue, 08 Mar 2016 21:48:15 GMT wallaby:workers Merging parallel test run results
Finished executing 3 affected test(s)
Tue, 08 Mar 2016 21:48:15 GMT wallaby:project Test run finished
Tue, 08 Mar 2016 21:48:15 GMT wallaby:project Processed console.log entries
Tue, 08 Mar 2016 21:48:15 GMT wallaby:project Processed loading sequences
Tue, 08 Mar 2016 21:48:15 GMT wallaby:project Processed executed tests
Tue, 08 Mar 2016 21:48:15 GMT wallaby:project Processed code coverage
Tue, 08 Mar 2016 21:48:15 GMT wallaby:project Test run result processed and sent to IDE
```

with matching errors in the main Wallaby window:

```
TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
at http://localhost:58152/__modules/HTMLDOMPropertyConfig.bba13ee00fdb9f8294526aa66a23557e.js?1457473692764:32


TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
	at src/test/karma/testNavBar.jsx:3

TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
	at src/main/webapp/jsx/reduxApp.jsx:7
	at src/test/karma/testSimpleApplicationModules.jsx:5

TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
at http://localhost:58152/__modules/HTMLDOMPropertyConfig.bba13ee00fdb9f8294526aa66a23557e.js?1457473692764:32
```

**Comment by ArtemGovorov** [comment]
> `TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind`

@xavierhaurie This one should be [easy to fix](http://wallabyjs.com/docs/intro/troubleshooting.html#undefined-is-not-a-function-evaluating-reactelementvalidatorcreateelementbind-or-typeerror-undefined-is-not-a-function-evaluating-regexpprototypetestbinddataaria-a-za-zd-)

**Comment by ArtemGovorov** [comment]
@xavierhaurie Here is the [solution we recommend](http://wallabyjs.com/docs/integration/react-jsx.html#phantomjs-shim).

**Comment by xavierhaurie** [comment]
If am using Phantom-prebuilt v2.1.5 so should not have needed the polyfill. But I did. I tried with phantomjs 1.9.19, phantomjs-prebuilt 2.1.5, and phantomjs2 2.2.0. In all cases I needed the polyfill. I must still be doing something wrong.

The nice thing is that it did work. :-) Thank you for that!

**Comment by ArtemGovorov** [comment]
> If am using Phantom-prebuilt v2.1.5 so should not have needed the polyfill.

I don't see it configured in the wallaby config that you have shared. Did you [specify it in your `env` setting like described here](http://wallabyjs.com/docs/integration/phantomjs2.html)?

**Comment by hellboy81** [comment]
Have the same issue
