### ISSUE TITLE
module path error if require related module in env:type=node

### ISSUE THREAD

**Issue by TerenceZ** [wallabyjs/public#50]
System: Windows 7 x64
Node version: node v0.12.0
WebStorm Version: 9.0.3

The errors raise up 'Cannot find module `../some_path` if I require some related path module.
For example,
```js
// config/index.js
'use strict';
const info = require('../package.json');
```

The wallaby console will report `Runtime error: Error: Cannot find module '../package.json'`, detailed as follows:

```error
Runtime error: Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (module.js:322:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.<anonymous> (C:\Users\username\.WebStorm9\system\wallaby\projects\projectname_wallaby.conf\instrumented\config\index.js:8:35)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
```

Here is my config.

```json
{
  "files": [
    "config/index.js"
  ],
  "tests": [
    "test/config.test.js"
  ],
  "workers": {
    "recycle": true
  },
  "env": {
    "type": "node",
    "params": {
      "runner": "--harmony"
    }
  }
}
```

**Comment by ArtemGovorov** [comment]
Try
```
"files": [
    "config/index.js",
    "package.json"
  ],
```

it should fix the issue. Wallaby uses its own cache for files, so all the files that you use have to be in the files list. Let me know if it helps.

**Comment by TerenceZ** [comment]
Yes, this works for just including the `package.json`, but it raised up another problem, which I have opened another issue#52.
