### ISSUE TITLE
Getting error when defining a testHelper.js as browserify module

### ISSUE THREAD

**Issue by ftom2** [wallabyjs/public#507]
### As the title states, I defined testHelpers file that requires an object and wallaby fails to identify it as a module.

here is the full stack:

```javascript

Error: Cannot find module '.\public\angular-client\test\mockPriceFactorsService.js'
at http://localhost:60291/wallabify.js?1457631588805:1​​ 

​​Error: Cannot find module 'C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\Wallaby\projects\40733ca41b8476b7\instrumented\public\angular-client\test\mockPriceFactorsService.js'​​ 
  at ​public/angular-client/test/testHelpers.js:1:1​ 
  at ​public/angular-client/app/scripts/controllers/discounts/ctrlPrograms.spec.js:4:1​ 

​​TypeError: undefined is not a constructor (evaluating 'jasmineRequire.html(jasmine)')​​ 
  at ​public/angular-client/test/lib/jasmine-2.3.4/boot.js:23:3​ 

​​ReferenceError: Can't find variable: require​​ 
  at ​public/angular-client/test/testHelpers.js:1:1​ 

```

### Wallaby.js configuration file

```javascript
// Wallaby.js configuration

var wallabify = require('wallabify');
var wallabyPostprocessor = wallabify({
    debug: true,
    entryPatterns: [
        'public/angular-client/app/scripts/app.js',
        'public/angular-client/app/scripts/**/*.spec.js',
        'public/angular-client/test/testHelpers.js'
    ]
});

module.exports = function() {
    return {
        // set `load: false` to all of the browserified source files and tests,
        // as they should not be loaded in browser,
        // their browserified versions will be loaded instead
        "files": [
            { pattern: "public/angular-client/app/scripts/routeParams.js", instrument: false },
            { pattern: "node_modules/jquery/dist/jquery.js", instrument: false },
            { pattern: "public/angular-client/app/bower_components/lodash/lodash.js", instrument: false },
            { pattern: "public/angular-client/app/bower_components/angular/angular.js", instrument: false },
            { pattern: "node_modules/sinon/pkg/sinon.js", instrument: false },
            { pattern: "node_modules/bardjs/dist/bard.js", instrument: false },
            { pattern: "public/angular-client/app/bower_components/angular-sanitize/angular-sanitize.js", instrument: false },
            { pattern: "public/angular-client/app/bower_components/angular-cookies/angular-cookies.js", instrument: false },
            { pattern: "public/angular-client/app/bower_components/angular-route/angular-route.js", instrument: false },
            { pattern: "node_modules/angular-nvd3/dist/angular-nvd3.js", instrument: false },
            { pattern: "node_modules/angular-ui-bootstrap/ui-bootstrap-tpls.js", instrument: false },
            { pattern: "node_modules/angular-ui-sortable/dist/sortable.js", instrument: false },
            { pattern: "public/angular-client/app/translation/angular-translate.js", instrument: false },
            { pattern: "public/angular-client/app/uploader/angular-file-upload.js", instrument: false },
            { pattern: "public/angular-client/app/bower_components/line-chart-master/dist/line-chart.js", instrument: false },
            { pattern: "public/angular-client/app/bower_components/angular-ui-grid/ui-grid.js", instrument: false },
            { pattern: "public/angular-client/app/bower_components/angular-ui-ng-grid/build/ng-grid.js", instrument: false },
            { pattern: "public/angular-client/app/bower_components/ui-grid-draggable-rows/js/draggable-rows.js", instrument: false },
            { pattern: "public/angular-client/app/bower_components/ng-slider/src/ng-slider.js", instrument: false },
            { pattern: "public/angular-client/app/bower_components/ng-slider/dist/ng-slider.tmpl.js", instrument: false },
            { pattern: "node_modules/angular-smart-table/dist/smart-table.js", instrument: false },
            { pattern: "public/angular-client/app/bower_components/angular-mocks/angular-mocks.js", instrument: false },
            { pattern: 'public/angular-client/app/bundle.js', instrument: false },
            { pattern: "public/angular-client/app/scripts/**/*.js", load: false },
            { pattern: 'public/angular-client/app/scripts/**/*.spec.js', ignore: true }

        ],
        "tests": [
            { pattern: "public/angular-client/app/scripts/**/*.spec.js", load: false },
            { pattern: "public/angular-client/test/**/*.js", instrument: false},

        ],
        debug: false,
        env: {
            runner: 'C:/phantomjs-2.1.1/bin/phantomjs',
            params: { runner: '--web-security=false' }
        },

        postprocessor: wallabyPostprocessor,

        bootstrap: function() {
            // required to trigger tests loading
            window.__moduleBundler.loadTests();
        }
    };
};

```

#### testHelpers.js:

```javascript
var mockPriceFactorsService = require('./mockPriceFactorsService.js');

var TestHelpers = {
    
    mockPriceFactorsService: mockPriceFactorsService
};

modules.exports = TestHelpers;
```

#### mockPriceFactorsService

```javascript
'use strict';

module.exports = {
    getPrograms: function() {
        return{};
    }
};
```

### Code editor or IDE name and version
Sublime Text v3

### OS name and version
Windows 7

**Comment by ArtemGovorov** [comment]
Thanks for providing the details.

In wallaby config `tests` section, [only files with actual tests](http://wallabyjs.com/docs/config/files.html#tests) in them should be listed. It looks like this pattern: `{ pattern: "public/angular-client/test/**/*.js", instrument: false}` in you `tests` includes the `testHelpers`, which is not a file with tests. 

Try moving the line  `{ pattern: "public/angular-client/test/**/*.js", instrument: false}` to the `files` list and also add `load: false` to it (because you're loading the file via entry patterns).

Let me know if it helps.

**Comment by ftom2** [comment]
Thank you for the quick response.

I tried what you said and now i get this:

```javascript
  ReferenceError: Can't find variable: modules​​ 
    at ​public/angular-client/test/testHelpers.js:72​ 
```

**Comment by ArtemGovorov** [comment]
I think `modules.exports` needs to be fixed to `module.exports`.

**Comment by ftom2** [comment]
How embarrassing :( now it works, thanks a lot for your help

**Comment by ArtemGovorov** [comment]
Awesome, no worries, thanks for the update!
