### ISSUE TITLE
Syntax Error:  Unexpected Token !

### ISSUE THREAD

**Issue by mwq27** [wallabyjs/public#541]
### Issue description or question
I am using TypeScript with Webpack, and when I startup wallaby, I immediately get this error:
```
SyntaxError: Unexpected token !
    at Object.parse (native)
    at new SourceMapConsumer (/Users/###/Projects/Uptake/claymore/node_modules/source-map/lib/source-map/source-map-consumer.js:50:24)
    at mapSourcePosition (/Users/###/Projects/Uptake/claymore/node_modules/source-map-support/source-map-support.js:164:14)
    at wrapCallSite (/Users/###/Projects/Uptake/claymore/node_modules/source-map-support/source-map-support.js:323:20)
    at /Users/###/Projects/Uptake/claymore/node_modules/source-map-support/source-map-support.js:358:26
    at Array.map (native)
    at Function.prepareStackTrace (/Users/###/Projects/Uptake/claymore/node_modules/source-map-support/source-map-support.js:357:24)
    at Object.i.receive (/Users/###/Library/Caches/WebStorm2016.1/wallaby/wallaby/server.js:14:1373)
    at WebSocket.<anonymous> (/Users/###/Library/Caches/WebStorm2016.1/wallaby/wallaby/server.js:18:24046)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.self._receiver.ontext (/Users/###/Library/Caches/WebStorm2016.1/wallaby/wallaby/node_modules/ws/lib/WebSocket.js:682:10)
    at Receiver.opcodes.1.finish (/Users/###/Library/Caches/WebStorm2016.1/wallaby/wallaby/node_modules/ws/lib/Receiver.js:391:14)
    at Receiver.expectHandler (/Users/###/Library/Caches/WebStorm2016.1/wallaby/wallaby/node_modules/ws/lib/Receiver.js:372:33)
    at Receiver.add (/Users/###/Library/Caches/WebStorm2016.1/wallaby/wallaby/node_modules/ws/lib/Receiver.js:87:24)
    at Socket.firstHandler (/Users/###/Library/Caches/WebStorm2016.1/wallaby/wallaby/node_modules/ws/lib/WebSocket.js:663:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:521:20)
```
### Wallaby.js configuration file

```javascript
'use strict';
var webpackConfig = require('./webpack.config');
var wallabyWebpack = require('wallaby-webpack');
webpackConfig.output = {};
delete webpackConfig.module.preLoaders;
delete webpackConfig.module.loaders;
webpackConfig.debug = false;
delete webpackConfig.devtool;
var webpackPostprocessor = wallabyWebpack(webpackConfig);

module.exports = function (wallaby) {

	return {
		files: [
			{ pattern: 'src/**/!(*.spec|*.e2e).ts', load: false }
		],

		tests: [
			{ pattern: 'src/**/*.spec.ts', load: false }
		],

		postprocessor: webpackPostprocessor,

		bootstrap: function () {
			window.__moduleBundler.loadTests();
		}
	};
};

```

### Code editor or IDE name and version

WebStorm 2016.1

### OS name and version
OSX

**Comment by mwq27** [comment]
This turned out to be a loader in my webpack config, the `awesome-typescript-loader` plugin.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update! Was just going to ask you to provide the `./webpack.config.js` to see if any loaders were interfering with wallaby TypeScript compiler :)
