### ISSUE TITLE
wallaby:nodeRunner Error in worker: ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by dingziran** [wallabyjs/public#57]
I suddenly met this error in the afternoon. I didn't change anything. 

Mon, 30 Mar 2015 07:50:39 GMT wallaby:workers Worker is not created in time, recycling it
Mon, 30 Mar 2015 07:50:39 GMT wallaby:project Test run cancelled, re-queueing run data, tests (may have duplicates): 0
Mon, 30 Mar 2015 07:50:39 GMT wallaby:project Test run finished
Mon, 30 Mar 2015 07:50:39 GMT wallaby:project Test run data re-queued, tests (may have duplicates): 0
Mon, 30 Mar 2015 07:50:39 GMT wallaby:project Test run started; run priority: 3, tests (may have duplicates): 0
Mon, 30 Mar 2015 07:50:39 GMT wallaby:project Running all tests
Mon, 30 Mar 2015 07:50:39 GMT wallaby:workers Starting test run, priority: 3
Mon, 30 Mar 2015 07:50:39 GMT wallaby:workers Distributing tests between 2 workers
Mon, 30 Mar 2015 07:50:39 GMT wallaby:workers Running tests in parallel
Mon, 30 Mar 2015 07:50:39 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #74f75]
Mon, 30 Mar 2015 07:50:39 GMT wallaby:nodeRunner Starting sandbox [worker #1, session #audpy]
Mon, 30 Mar 2015 07:50:39 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #74f75]
Mon, 30 Mar 2015 07:50:39 GMT wallaby:workers Starting run worker instance #0
Mon, 30 Mar 2015 07:50:39 GMT wallaby:nodeRunner Preparing sandbox [worker #1, session #audpy]
Mon, 30 Mar 2015 07:50:39 GMT wallaby:workers Worker is not created in time, recycling it
Mon, 30 Mar 2015 07:50:39 GMT wallaby:project Test run cancelled, re-queueing run data, tests (may have duplicates): 0
Mon, 30 Mar 2015 07:50:39 GMT wallaby:project Test run finished
Mon, 30 Mar 2015 07:50:39 GMT wallaby:project Test run data re-queued, tests (may have duplicates): 0
Mon, 30 Mar 2015 07:50:39 GMT wallaby:project Test run started; run priority: 3, tests (may have duplicates): 0
Mon, 30 Mar 2015 07:50:39 GMT wallaby:project Running all tests
Mon, 30 Mar 2015 07:50:39 GMT wallaby:workers Starting test run, priority: 3
Mon, 30 Mar 2015 07:50:39 GMT wallaby:workers Distributing tests between 2 workers
Mon, 30 Mar 2015 07:50:39 GMT wallaby:workers Running tests in parallel
Mon, 30 Mar 2015 07:50:39 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #udcaj]
Mon, 30 Mar 2015 07:50:39 GMT wallaby:nodeRunner Starting sandbox [worker #1, session #f3fv6]
Mon, 30 Mar 2015 07:50:39 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #udcaj]
Mon, 30 Mar 2015 07:50:39 GMT wallaby:nodeRunner Preparing sandbox [worker #1, session #f3fv6]
Mon, 30 Mar 2015 07:50:39 GMT wallaby:workers Starting run worker instance #1
Mon, 30 Mar 2015 07:50:39 GMT wallaby:nodeRunner Error in worker: ReferenceError: XMLHttpRequest is not defined
    at Object.e (C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:10:22883)
    at C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:10:31749
    at Object.15 (C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:11:151)
    at e (C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:8:254)
    at C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:8:305
    at Object.j (C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:9:5245)
    at b.exports (C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:9:6483)
    at Object.17../lib/app (C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:11:2832)
    at e (C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:8:254)
    at a (C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:8:421)
Mon, 30 Mar 2015 07:50:39 GMT wallaby:nodeRunner Error in worker: ReferenceError: XMLHttpRequest is not defined
    at Object.e (C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:10:22883)
    at C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:10:31749
    at Object.15 (C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:11:151)
    at e (C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:8:254)
    at C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:8:305
    at Object.j (C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:9:5245)
    at b.exports (C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:9:6483)
    at Object.17../lib/app (C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:11:2832)
    at e (C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:8:254)
    at a (C:\Users\dingziran\.WebStorm9\system\wallaby\wallaby\server.js:8:421)

**Comment by dingziran** [comment]
webstorm 9.0.3
windows 8.1
node v0.10.34
mocha

**Comment by ArtemGovorov** [comment]
Hi, 
fixed. Restart your WebStorm, then start wallaby.js to force the update.

**Comment by ArtemGovorov** [comment]
And thanks for noticing and reporting it so fast! :) The broken build with the issue has only been available for an hour or so.
