### ISSUE TITLE
Jest seems to fail after the update

### ISSUE THREAD

**Issue by andrew-w-ross** [wallabyjs/public#581]
### Jest and wallaby don't seem to work after the update

My configuration was working but now seems to fail after the update.

The error I get is 
```
[Error] Runtime error: TypeError: Path must be a string. Received null
[Error]     at assertPath (path.js:7:11)
[Error]     at Object.dirname (path.js:1324:5)
[Error]     at Runtime._resolveNodeModule (/Users/ross/Projects/ksysUDM/udm_deploy/node_modules/jest-cli/src/Runtime/Runtime.js:427:26)
[Error]     at Runtime._resolveModuleName (/Users/ross/Projects/ksysUDM/udm_deploy/node_modules/jest-cli/src/Runtime/Runtime.js:419:33)
[Error]     at Runtime._getNormalizedModuleID (/Users/ross/Projects/ksysUDM/udm_deploy/node_modules/jest-cli/src/Runtime/Runtime.js:489:29)
[Error]     at Runtime.requireModule (/Users/ross/Projects/ksysUDM/udm_deploy/node_modules/jest-cli/src/Runtime/Runtime.js:102:27)
[Error]     at environment.fakeTimers.runWithRealTimers (/Users/ross/Projects/ksysUDM/udm_deploy/node_modules/jest-jasmine2/src/index.js:69:20)
[Error]     at FakeTimers.runWithRealTimers (/Users/ross/Projects/ksysUDM/udm_deploy/node_modules/jest-util/lib/FakeTimers.js:260:7)
[Error]     at jasmine2 (/Users/ross/Projects/ksysUDM/udm_deploy/node_modules/jest-jasmine2/src/index.js:37:26)
[Error]     at Test.run (/Users/ross/Projects/ksysUDM/udm_deploy/node_modules/jest-cli/src/Test.js:42:12)
```

### Wallaby.js configuration file

```javascript
var babelCore = require("babel-core");

module.exports = function (wallaby) {

	return {		
		files: [
			'src/**/*.ts',
			'!src/**/*.spec.ts'
		],
		tests: [
			'src/**/*.spec.ts'
		],
		compilers: {
			'**/*.ts': wallaby.compilers.typeScript()
		},
		workers: {
			initial: 1,
			regular: 1
		},
		testFramework: 'jest',
		preprocessors: {
			'**/*.js': function (file) {
				return babelCore.transform(file.content, {					
					sourceMap: true,
					compact: false,
					presets: ["es2015", "stage-2", "jest"]
				});
			}
		},
		env: {
			type: 'node',
			runner: 'node'
		},
		setup: function (wallaby) {
			require("babel-polyfill");
			wallaby.testFramework.configure({
				automock: false,
				testEnvironment:"node",
				globals: {
					regeneratorRuntime: global.regeneratorRuntime,
					jasmine: {
						DEFAULT_TIMEOUT_INTERVAL: 20000
					}
                }
			});
		}
	};
};
```

### Code editor or IDE name and version

Visual Studio Code v1.0.0

### OS name and version

OSX 10.11.4

**Comment by andrew-w-ross** [comment]
I've cleared everything and updated to the latest version of jest and the error has changed to the following

```
[Info] Started Wallaby.js Core v1.0.223
[Info] src/utils/any.js
[Info] src/utils/any.spec.js
[Error] Runtime error: TypeError: Data must be a string or a buffer
[Error]     at TypeError (native)
[Error]     at Hash.update (crypto.js:67:16)
[Error]     at Array.from.slice.forEach.arg (/Users/ross/Projects/ksysUDM/udm_deploy/node_modules/jest-haste-map/src/index.js:148:56)
[Error]     at Array.forEach (native)
[Error]     at Function.getCacheFilePath (/Users/ross/Projects/ksysUDM/udm_deploy/node_modules/jest-haste-map/src/index.js:148:36)
[Error]     at new HasteMap (/Users/ross/Projects/ksysUDM/udm_deploy/node_modules/jest-haste-map/src/index.js:132:32)
[Error]     at createHasteMap (/Users/ross/Projects/ksysUDM/udm_deploy/node_modules/jest-cli/src/lib/createHasteMap.js:21:10)
[Error]     at new TestRunner (/Users/ross/Projects/ksysUDM/udm_deploy/node_modules/jest-cli/src/TestRunner.js:60:22)
```

**Comment by ArtemGovorov** [comment]
Added the support for jest-cli v12.0.2 in the latest wallaby core v1.0.224. The core should be updated automatically, to force the update, please [follow these instructions](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by Fresheyeball** [comment]
@ArtemGovorov what was the issue? I'm getting the same error but not with your project.

**Comment by ArtemGovorov** [comment]
> I'm getting the same error but not with your project.

@Fresheyeball You mean not with wallaby sample project for jest or just not with wallaby.js at all?

The issue was that jest had added a new config parameter (`name`) that doesn't have a default value (when using their API externally, internally jest-cli does pass a value, so does wallaby now). 

So `undefined` was passed through and at some point jest creates md5 hash for cache path where it uses some config properties to create the hash and when doing `hash.update(...)` it fails if the property is not a string.
