### ISSUE TITLE
TypeError: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by vjau** [wallabyjs/public#588]
### Issue description or question

I have this error reported frequently.
When i restart Wallaby, it disappears. 
When i was writing my tests in ES6 it was working flawlessly.
I think i have this problem since i switched to Typescript

### Wallaby.js configuration file

```javascript
  files: [
      { pattern: 'client/**/tests/*.js', ignore: true },
      { pattern: 'server/**/tests/*.js', ignore: true },
      { pattern: 'imports/**/tests/*.js', ignore: true },
      { pattern: 'client/**/tests/*.ts', ignore: true },
      { pattern: 'imports/**/tests/*.ts', ignore: true },
      'client/imports/**/*.js',
      'client/imports/**/*.jsx',
      'imports/**/*.js',
      'client/imports/**/*.ts',
      'client/imports/**/*.tsx',
      'imports/**/*.ts'
    ],
    tests: [
      'client/**/tests/*.ts',
      'imports/**/tests/*.ts'
    ],
    compilers: {
      '**/*.ts*': wallaby.compilers.typeScript({module: 'es6'}),
      '**/*.js*': wallaby.compilers.babel()
    },
    preprocessors: {
      '**/*.js*': file => require('babel-core').transform(
        file.content,
        {sourceMap: true, presets: ["es2015", "stage-2","react"]})
    },
    env: {
      type: 'node'
    },
    testFramework: 'mocha',
    setup: function() {
      global.React = require('react');
    }
  };
```

### Code editor or IDE name and version

WebStorm 2016.1
### OS name and version

Linux Ubuntu 15.10

**Comment by ArtemGovorov** [comment]
I have a suspicion it may be related to some node modules you're using, specifically some state they cache and the fact that wallaby [reuses node processes by default](https://wallabyjs.com/docs/integration/node.html#node-process-reuse). Let's try something to see if that's the case and we'll take it from there. Try adding `workers.recycle` setting:
```javascript
module.exports = function () {
  return {
     ...
    workers: {
      recycle: true
    }
  };
};
```

If it helps, try resetting some/all used modules cache like described in the docs I referenced.
If it doesn't help, please [add the `debug: true`](more-debug-information) setting in your config, and when the error occurs next time, go to Wallaby Console tab and get the full error stack to paste here.

Either way, let me know how it goes.

**Comment by vjau** [comment]
Thank you for your help.
It seems to work with recycle:true, i don't see the problem anymore. 
The problem is that most of my tested code & test are pure, how to figure which could be the culprit ?

**Comment by ArtemGovorov** [comment]
The issue may not be with your code, but with node modules that your code is using.
Try resetting the state set by some of the node modules by resetting node modules cache in your setup function. If it works, it will be faster than recycling workers, especially if you find out specific modules to reset the cache for and only delete those from the cache.
```javascript
module.exports = wallaby => {
  return {
    ...
    setup: function (w) {
      Object.keys(require.cache)
              // you may try only resetting cache for specific modules
              // by filtering them by name
              .filter(function (k) { return ~k.indexOf(w.localProjectDir); }) // && ~k.indexOf('module_with_state')
              .forEach(function (k)  { delete require.cache[k]; });
    }
  };
};
```
I'd start with resetting the cache for all modules, and if it helps, would try to bisect and find out which module is causing the issue and would only reset the cache for it.

**Comment by vjau** [comment]
It seems the problem is not fixed by recycle:true since it is coming back.
Here is part of the debug trace. 
```
Sat, 14 May 2016 17:17:30 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
Sat, 14 May 2016 17:17:30 GMT wallaby:workers Sandbox [8l4kq] is responsive, closing it
Sat, 14 May 2016 17:17:30 GMT wallaby:workers Starting run worker instance #0
Sat, 14 May 2016 17:17:30 GMT wallaby:project Test run finished
Sat, 14 May 2016 17:17:30 GMT wallaby:project Processed console.log entries
Sat, 14 May 2016 17:17:30 GMT wallaby:project Processed loading sequences
Sat, 14 May 2016 17:17:30 GMT wallaby:project Processed executed tests
Sat, 14 May 2016 17:17:30 GMT wallaby:project Processed code coverage
Sat, 14 May 2016 17:17:30 GMT wallaby:project Test run result processed and sent to IDE
Sat, 14 May 2016 17:17:30 GMT wallaby:project File client/imports/modules/rdvs/validators/tests/validRdv.ts changes are patches only: true
Sat, 14 May 2016 17:17:30 GMT wallaby:project Returning previously cached file [254] from memory
Sat, 14 May 2016 17:17:30 GMT wallaby:project Preparing to process client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:30 GMT wallaby:project No compilers configured for client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:30 GMT wallaby:project File client/imports/modules/rdvs/validators/tests/validRdv.ts is not instrumented by core
Sat, 14 May 2016 17:17:30 GMT wallaby:project No preprocessors configured for client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:30 GMT wallaby:project Writing to disk and caching processed file client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:30 GMT wallaby:project File client/imports/modules/rdvs/validators/tests/validRdv.ts changes saved, store ts: 1462742489396, change ts: 1463246250274
Sat, 14 May 2016 17:17:30 GMT wallaby:project Running postprocessor
Sat, 14 May 2016 17:17:30 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Sat, 14 May 2016 17:17:30 GMT wallaby:project Preparing to process client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:30 GMT wallaby:project Processing compiled client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:30 GMT wallaby:project Instrumenting client/imports/modules/rdvs/validators/tests/validRdv.js, via process pool: false
Sat, 14 May 2016 17:17:30 GMT wallaby:project Error: Failed to parse client/imports/modules/rdvs/validators/tests/validRdv.js, SyntaxError: Unexpected token (59:38)
  at /home/vincent/.WebStorm2016.1/system/wallaby/wallaby/server.js:17:2824
From previous event:
  at Object._.extend.createFile (/home/vincent/.WebStorm2016.1/system/wallaby/wallaby/server.js:16:26540)
  at /home/vincent/.WebStorm2016.1/system/wallaby/wallaby/server.js:18:16531
  at baseFor (/home/vincent/.WebStorm2016.1/system/wallaby/wallaby/node_modules/lodash/index.js:1971:13)
  at baseForOwn (/home/vincent/.WebStorm2016.1/system/wallaby/wallaby/node_modules/lodash/index.js:2025:14)
  at baseEach (/home/vincent/.WebStorm2016.1/system/wallaby/wallaby/node_modules/lodash/index.js:1814:16)
  at Function.forEach (/home/vincent/.WebStorm2016.1/system/wallaby/wallaby/node_modules/lodash/index.js:5701:11)
  at Object.postprocessor (/home/vincent/.WebStorm2016.1/system/wallaby/wallaby/server.js:18:15543)
  at /home/vincent/.WebStorm2016.1/system/wallaby/wallaby/server.js:16:20919
  at [object Object]._onTimeout (/home/vincent/.WebStorm2016.1/system/wallaby/wallaby/server.js:16:20521)
  at Timer.listOnTimeout (timers.js:92:15)
Sat, 14 May 2016 17:17:30 GMT wallaby:project Test run finished
Sat, 14 May 2016 17:17:30 GMT wallaby:project Test run data re-queued
Sat, 14 May 2016 17:17:30 GMT wallaby:workers Started run worker instance (delayed) #0
Sat, 14 May 2016 17:17:30 GMT wallaby:project File client/imports/modules/rdvs/validators/tests/validRdv.ts changes are patches only: true
Sat, 14 May 2016 17:17:30 GMT wallaby:project Returning previously cached file [254] from memory
Sat, 14 May 2016 17:17:30 GMT wallaby:project Preparing to process client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:30 GMT wallaby:project No compilers configured for client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:30 GMT wallaby:project File client/imports/modules/rdvs/validators/tests/validRdv.ts is not instrumented by core
Sat, 14 May 2016 17:17:30 GMT wallaby:project No preprocessors configured for client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:30 GMT wallaby:project Writing to disk and caching processed file client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:30 GMT wallaby:project File client/imports/modules/rdvs/validators/tests/validRdv.ts changes saved, store ts: 1462742489396, change ts: 1463246250554
Sat, 14 May 2016 17:17:30 GMT wallaby:project Running postprocessor
Sat, 14 May 2016 17:17:30 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Sat, 14 May 2016 17:17:30 GMT wallaby:project Preparing to process client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:30 GMT wallaby:project Processing compiled client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:30 GMT wallaby:project Instrumenting client/imports/modules/rdvs/validators/tests/validRdv.js, via process pool: false
Sat, 14 May 2016 17:17:30 GMT wallaby:project Detected single test [accepts rdv with upercase id] change
Sat, 14 May 2016 17:17:30 GMT wallaby:processor Running 1 processor(s) for client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:30 GMT wallaby:processor Finished running one processor for client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:30 GMT wallaby:project Writing to disk and caching processed file client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:30 GMT wallaby:project Postprocessor execution finished
Sat, 14 May 2016 17:17:30 GMT wallaby:project Test run started; run priority: 2
Sat, 14 May 2016 17:17:30 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Sat, 14 May 2016 17:17:30 GMT wallaby:workers Starting test run, priority: 2
Sat, 14 May 2016 17:17:30 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #6y2ir]
Sat, 14 May 2016 17:17:30 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #6y2ir]
Sat, 14 May 2016 17:17:30 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #6y2ir]
Sat, 14 May 2016 17:17:30 GMT wallaby:workers Running tests in sandbox [worker #0, session #6y2ir]
Sat, 14 May 2016 17:17:30 GMT wallaby:workers Cancelling test run, cancel requester priority: 2, current run priority: 2
Sat, 14 May 2016 17:17:30 GMT wallaby:project Test run was cancelled
Sat, 14 May 2016 17:17:30 GMT wallaby:workers Sandbox (inactive) [6y2ir] error: TypeError: Cannot set property '0' of undefined
Sat, 14 May 2016 17:17:30 GMT wallaby:workers Sandbox [6y2ir] is responsive, closing it
Sat, 14 May 2016 17:17:30 GMT wallaby:workers Starting run worker instance #0
Sat, 14 May 2016 17:17:30 GMT wallaby:project Test run cancelled, re-queueing run data
Runtime error: TypeError: Cannot set property '0' of undefined
    at Object.<anonymous> (./client/imports/modules/rdvs/validators/validRdv.js:88:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
Sat, 14 May 2016 17:17:30 GMT wallaby:project Test run finished
Sat, 14 May 2016 17:17:30 GMT wallaby:project Test run data re-queued
Sat, 14 May 2016 17:17:30 GMT wallaby:project File client/imports/modules/rdvs/validators/tests/validRdv.ts changes are patches only: true
Sat, 14 May 2016 17:17:30 GMT wallaby:project Returning previously cached file [254] from memory
Sat, 14 May 2016 17:17:30 GMT wallaby:project Preparing to process client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:30 GMT wallaby:project No compilers configured for client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:30 GMT wallaby:project File client/imports/modules/rdvs/validators/tests/validRdv.ts is not instrumented by core
Sat, 14 May 2016 17:17:30 GMT wallaby:project No preprocessors configured for client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:30 GMT wallaby:project Writing to disk and caching processed file client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:30 GMT wallaby:project File client/imports/modules/rdvs/validators/tests/validRdv.ts changes saved, store ts: 1462742489396, change ts: 1463246250764
Sat, 14 May 2016 17:17:30 GMT wallaby:project Running postprocessor
Sat, 14 May 2016 17:17:30 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Sat, 14 May 2016 17:17:30 GMT wallaby:project Preparing to process client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:30 GMT wallaby:project Processing compiled client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:30 GMT wallaby:project Instrumenting client/imports/modules/rdvs/validators/tests/validRdv.js, via process pool: false
Sat, 14 May 2016 17:17:30 GMT wallaby:project Detected single test [accepts rdv with upercase id] change
Sat, 14 May 2016 17:17:30 GMT wallaby:processor Running 1 processor(s) for client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:30 GMT wallaby:processor Finished running one processor for client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:30 GMT wallaby:project Writing to disk and caching processed file client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:30 GMT wallaby:project Postprocessor execution finished
Sat, 14 May 2016 17:17:30 GMT wallaby:project Test run started; run priority: 2
Sat, 14 May 2016 17:17:30 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Sat, 14 May 2016 17:17:30 GMT wallaby:workers Starting test run, priority: 2
Sat, 14 May 2016 17:17:30 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #9aqfq]
Sat, 14 May 2016 17:17:30 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #9aqfq]
Sat, 14 May 2016 17:17:30 GMT wallaby:workers Started run worker instance (delayed) #0
Sat, 14 May 2016 17:17:30 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #9aqfq]
Sat, 14 May 2016 17:17:30 GMT wallaby:workers Running tests in sandbox [worker #0, session #9aqfq]
Runtime error: TypeError: Cannot set property '0' of undefined
    at Object.<anonymous> (./client/imports/modules/rdvs/validators/validRdv.js:88:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
Sat, 14 May 2016 17:17:31 GMT wallaby:workers Sandbox (active) [9aqfq] error: TypeError: Cannot set property '0' of undefined
Sat, 14 May 2016 17:17:31 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
Sat, 14 May 2016 17:17:31 GMT wallaby:workers Sandbox [9aqfq] is responsive, closing it
Sat, 14 May 2016 17:17:31 GMT wallaby:workers Starting run worker instance #0
Sat, 14 May 2016 17:17:31 GMT wallaby:project Test run finished
Sat, 14 May 2016 17:17:31 GMT wallaby:project Processed console.log entries
Sat, 14 May 2016 17:17:31 GMT wallaby:project Processed loading sequences
Sat, 14 May 2016 17:17:31 GMT wallaby:project Processed executed tests
Sat, 14 May 2016 17:17:31 GMT wallaby:project Processed code coverage
Sat, 14 May 2016 17:17:31 GMT wallaby:project Test run result processed and sent to IDE
Sat, 14 May 2016 17:17:31 GMT wallaby:project File client/imports/modules/rdvs/validators/tests/validRdv.ts changes are patches only: true
Sat, 14 May 2016 17:17:31 GMT wallaby:project Returning previously cached file [254] from memory
Sat, 14 May 2016 17:17:31 GMT wallaby:project Preparing to process client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:31 GMT wallaby:project No compilers configured for client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:31 GMT wallaby:project File client/imports/modules/rdvs/validators/tests/validRdv.ts is not instrumented by core
Sat, 14 May 2016 17:17:31 GMT wallaby:project No preprocessors configured for client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:31 GMT wallaby:project Writing to disk and caching processed file client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:31 GMT wallaby:project File client/imports/modules/rdvs/validators/tests/validRdv.ts changes saved, store ts: 1462742489396, change ts: 1463246251182
Sat, 14 May 2016 17:17:31 GMT wallaby:project Running postprocessor
Sat, 14 May 2016 17:17:31 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Sat, 14 May 2016 17:17:31 GMT wallaby:project Preparing to process client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:31 GMT wallaby:project Processing compiled client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:31 GMT wallaby:project Instrumenting client/imports/modules/rdvs/validators/tests/validRdv.js, via process pool: false
Sat, 14 May 2016 17:17:31 GMT wallaby:project Detected single test [accepts rdv with upercase id] change
Sat, 14 May 2016 17:17:31 GMT wallaby:processor Running 1 processor(s) for client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:31 GMT wallaby:processor Finished running one processor for client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:31 GMT wallaby:project Writing to disk and caching processed file client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:31 GMT wallaby:project Postprocessor execution finished
Sat, 14 May 2016 17:17:31 GMT wallaby:project Test run started; run priority: 2
Sat, 14 May 2016 17:17:31 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Sat, 14 May 2016 17:17:31 GMT wallaby:workers Starting test run, priority: 2
Sat, 14 May 2016 17:17:31 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #rgkg7]
Sat, 14 May 2016 17:17:31 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #rgkg7]
Sat, 14 May 2016 17:17:31 GMT wallaby:workers Started run worker instance (delayed) #0
Sat, 14 May 2016 17:17:31 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #rgkg7]
Sat, 14 May 2016 17:17:31 GMT wallaby:workers Running tests in sandbox [worker #0, session #rgkg7]
Runtime error: TypeError: Cannot set property '0' of undefined
    at Object.<anonymous> (./client/imports/modules/rdvs/validators/validRdv.js:88:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
Sat, 14 May 2016 17:17:31 GMT wallaby:workers Sandbox (active) [rgkg7] error: TypeError: Cannot set property '0' of undefined
Sat, 14 May 2016 17:17:31 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
Sat, 14 May 2016 17:17:31 GMT wallaby:workers Sandbox [rgkg7] is responsive, closing it
Sat, 14 May 2016 17:17:31 GMT wallaby:workers Starting run worker instance #0
Sat, 14 May 2016 17:17:31 GMT wallaby:project Test run finished
Sat, 14 May 2016 17:17:31 GMT wallaby:project Processed console.log entries
Sat, 14 May 2016 17:17:31 GMT wallaby:project Processed loading sequences
Sat, 14 May 2016 17:17:31 GMT wallaby:project Processed executed tests
Sat, 14 May 2016 17:17:31 GMT wallaby:project Processed code coverage
Sat, 14 May 2016 17:17:31 GMT wallaby:project Test run result processed and sent to IDE
Sat, 14 May 2016 17:17:31 GMT wallaby:project File client/imports/modules/rdvs/validators/tests/validRdv.ts changes are patches only: true
Sat, 14 May 2016 17:17:31 GMT wallaby:project Returning previously cached file [254] from memory
Sat, 14 May 2016 17:17:31 GMT wallaby:project Preparing to process client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:31 GMT wallaby:project No compilers configured for client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:31 GMT wallaby:project File client/imports/modules/rdvs/validators/tests/validRdv.ts is not instrumented by core
Sat, 14 May 2016 17:17:31 GMT wallaby:project No preprocessors configured for client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:31 GMT wallaby:project Writing to disk and caching processed file client/imports/modules/rdvs/validators/tests/validRdv.ts
Sat, 14 May 2016 17:17:31 GMT wallaby:project File client/imports/modules/rdvs/validators/tests/validRdv.ts changes saved, store ts: 1462742489396, change ts: 1463246251656
Sat, 14 May 2016 17:17:31 GMT wallaby:project Running postprocessor
Sat, 14 May 2016 17:17:31 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Sat, 14 May 2016 17:17:31 GMT wallaby:project Preparing to process client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:31 GMT wallaby:project Processing compiled client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:31 GMT wallaby:project Instrumenting client/imports/modules/rdvs/validators/tests/validRdv.js, via process pool: false
Sat, 14 May 2016 17:17:31 GMT wallaby:project Detected single test [accepts rdv with upercase id] change
Sat, 14 May 2016 17:17:31 GMT wallaby:processor Running 1 processor(s) for client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:31 GMT wallaby:processor Finished running one processor for client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:31 GMT wallaby:project Writing to disk and caching processed file client/imports/modules/rdvs/validators/tests/validRdv.js
Sat, 14 May 2016 17:17:31 GMT wallaby:project Postprocessor execution finished
Sat, 14 May 2016 17:17:31 GMT wallaby:project Test run started; run priority: 2
Sat, 14 May 2016 17:17:31 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Sat, 14 May 2016 17:17:31 GMT wallaby:workers Starting test run, priority: 2
Sat, 14 May 2016 17:17:31 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #gv9iv]
Sat, 14 May 2016 17:17:31 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #gv9iv]
Sat, 14 May 2016 17:17:31 GMT wallaby:workers Started run worker instance (delayed) #0
Sat, 14 May 2016 17:17:31 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #gv9iv]
Sat, 14 May 2016 17:17:31 GMT wallaby:workers Running tests in sandbox [worker #0, session #gv9iv]
Sat, 14 May 2016 17:17:31 GMT wallaby:workers Sandbox (active) [gv9iv] error: TypeError: Cannot set property '0' of undefined
Runtime error: TypeError: Cannot set property '0' of undefined
    at Object.<anonymous> (./client/imports/modules/rdvs/validators/validRdv.js:88:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
Sat, 14 May 2016 17:17:31 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
Sat, 14 May 2016 17:17:32 GMT wallaby:workers Sandbox [gv9iv] is responsive, closing it
Sat, 14 May 2016 17:17:32 GMT wallaby:workers Starting run worker instance #0
Sat, 14 May 2016 17:17:32 GMT wallaby:project Test run finished
Sat, 14 May 2016 17:17:32 GMT wallaby:project Processed console.log entries
Sat, 14 May 2016 17:17:32 GMT wallaby:project Processed loading sequences
Sat, 14 May 2016 17:17:32 GMT wallaby:project Processed executed tests
Sat, 14 May 2016 17:17:32 GMT wallaby:project Processed code coverage
Sat, 14 May 2016 17:17:32 GMT wallaby:project Test run result processed and sent to IDE
Sat, 14 May 2016 17:17:32 GMT wallaby:workers Started run worker instance (delayed) #0
```

**Comment by ArtemGovorov** [comment]
Not really sure what's going on here, I may need a sample where I could reproduce the issue. Is it possible to isolate the issue in a separate repo?

Without a way to reproduce it, my only suggestion would be to open wallaby cache folder (the path displayed as one of the first few lines of the debug output when you start wallaby), open `instrumented` folder there, open the `./client/imports/modules/rdvs/validators/validRdv.js` file and check what's in the line 88 there that could be causing the issue.

**Comment by vjau** [comment]
The problem is that i can't for now reproduce the bug predictably.
What i know is that the files are sometimes incorrectly transpiled.

Here is what is produced when the problem appears :

```
'use strict';

$_$wp(243);
$_$w(243, 0), Object.defineProperty(exports, '__esModule', { value: true });
$_$w(243, 1), exports.getDuréeMiniRdv = exports.getFinHeureAffichage = exports.getDebutHeureAffichage = undefined;
var _underscore = ($_$w(243, 2), require('underscore'));
var _underscore2 = ($_$w(243, 3), _interopRequireDefault(_underscore));
function _interopRequireDefault(obj) {
    $_$wf(243);
    return $_$w(243, 4), ($_$w(243, 7), obj) && ($_$w(243, 8), obj.__esModule) ? ($_$w(243, 5), obj) : ($_$w(243, 6), { default: obj });
}
var getPrefs = ($_$w(243, 9), function getPrefs(state) {
    $_$wf(243);
    return $_$w(243, 10), ($_$w(243, 11), state.preferences) && ($_$w(243, 12), state.preferences[state.preferences.length - 1]);
});
var getDebutHeure = ($_$w(243, 13), function getDebutHeure(prefs) {
    $_$wf(243);
    return $_$w(243, 14), prefs.débutHeureAffichage;
});
var getFinHeure = ($_$w(243, 15), function getFinHeure(prefs) {
    $_$wf(243);
    return $_$w(243, 16), prefs.finHeureAffichage;
});
var getDuréeMini = ($_$w(243, 17), function getDuréeMini(prefs) {
    $_$wf(243);
    return $_$w(243, 18), prefs.duréeMinRdv;
});
var getDebutHeureAffichage = ($_$w(243, 19), _underscore2.default.compose(getDebutHeure, getPrefs));
var getFinHeureAffichage = ($_$w(243, 20), _underscore2.default.compose(getFinHeure, getPrefs));
var getDuréeMiniRdv = ($_$w(243, 21), _underscore2.default.compose(getDuréeMini, getPrefs));
$_$w(243, 22), exports.getDebutHeureAffichage = getDebutHeureAffichage;
$_$w(243, 23), exports.getFinHeureAffichage = getFinHeureAffichage;
$_$w(243, 24), exports.getDuréeMiniRdv = getDuréeMiniRdv;
$_$wpe(243);
```

Now here is what is produced when i restart wallaby :

```
'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.getDuréeMiniRdv = exports.getFinHeureAffichage = exports.getDebutHeureAffichage = undefined;

var _underscore = require('underscore');

var _underscore2 = _interopRequireDefault(_underscore);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

$_$wp(243);

var getPrefs = ($_$w(243, 0), function (state) {
    $_$wf(243);
    return $_$w(243, 1), ($_$w(243, 2), state.preferences) && ($_$w(243, 3), state.preferences[state.preferences.length - 1]);
});
var getDebutHeure = ($_$w(243, 4), function (prefs) {
    $_$wf(243);
    return $_$w(243, 5), prefs.débutHeureAffichage;
});
var getFinHeure = ($_$w(243, 6), function (prefs) {
    $_$wf(243);
    return $_$w(243, 7), prefs.finHeureAffichage;
});
var getDuréeMini = ($_$w(243, 8), function (prefs) {
    $_$wf(243);
    return $_$w(243, 9), prefs.duréeMinRdv;
});
var getDebutHeureAffichage = ($_$w(243, 10), _underscore2.default.compose(getDebutHeure, getPrefs));
var getFinHeureAffichage = ($_$w(243, 11), _underscore2.default.compose(getFinHeure, getPrefs));
var getDuréeMiniRdv = ($_$w(243, 12), _underscore2.default.compose(getDuréeMini, getPrefs));
exports.getDebutHeureAffichage = getDebutHeureAffichage;
exports.getFinHeureAffichage = getFinHeureAffichage;
exports.getDuréeMiniRdv = getDuréeMiniRdv;

$_$wpe(243);
```

The problem seems to be related to source file transpilation, but it only happens when i'm fiddling with the tests (and since i write them in Typescript).

**Comment by ArtemGovorov** [comment]
Is the file in your example originally `.ts` file or `.js` file? It's not the `./client/imports/modules/rdvs/validators/validRdv` file, is it? Because the error was on the line 88 and your example file has less than 88 lines.

**Comment by ArtemGovorov** [comment]
Another question, do you have a WebStorm built-in TypeScript compiler producing `.js` files for you `.ts` files? Because in your example above, the correctly instrumented fie looks like the one being transpiled from TS to JS, but the one resulting in error looks like the one being transpiled from JS to JS. Perhaps with your mixed js/ts file patterns locally compiled JS files may get copied to wallaby cache and somehow conflict with compiled wallaby files? Wallaby renames files from TS to JS when compiling them in its cache. So what may happen is your locally compiled JS file gets copied to the cache (because it satisfies `files` pattern) and replace a file compiled by wallaby.

**Comment by vjau** [comment]
Yes indeed the original file is ts, and webstorm is compiling file on the fly.
Does it mean i should try to remove all js and jsx files from wallaby and only import ts and tsx ?

**Comment by ArtemGovorov** [comment]
> Does it mean i should try to remove all js and jsx files from wallaby and only import ts and tsx ?

Yes, this may help if that's the issue. Wallaby doesn't need those locally compiled JS files as it compiles the files itself (with instrumentation).

**Comment by vjau** [comment]
This seems to do the trick.
Thank you for your help, and incredible support.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
