### ISSUE TITLE
Cannot read property '0' of undefined - on module require

### ISSUE THREAD

**Issue by DinisCruz** [wallabyjs/public#607]
### Issue description or question

This is something that I have seen many times before, but was not able to reproduce as cleanly as I have now

When I have the require I get the error

![image](https://cloud.githubusercontent.com/assets/656739/15456639/397e51a8-206e-11e6-8839-9a7655e087cb.png)

without it, it works ok

![image](https://cloud.githubusercontent.com/assets/656739/15456641/45fbfc78-206e-11e6-9522-21c07daca0fa.png)

What is weird is that it works once ok, but after making a code change and the test re-running, the prob happens again

![image](https://cloud.githubusercontent.com/assets/656739/15456645/72a50eae-206e-11e6-8e6a-1b66241bc1ae.png)

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    wallaby
    return {
        files: [
            { pattern: 'test-spectron/src/**/*.coffee'},
            { pattern: 'test-spectron/electron-apps/** /*.*', instrument: false},
        ],

        tests: [
            'test-spectron/test/**/*.coffee'
        ],

        //testFramework: 'mocha',

        env: {
            type: 'node'//,
        },
    };
};
```

### Code editor or IDE name and version

WebStorm v11

### OS name and version
OSX

**Comment by DinisCruz** [comment]
ok I was able to replicate it with just these files

![image](https://cloud.githubusercontent.com/assets/656739/15456686/8accc1c4-206f-11e6-9940-7fda31d97c0c.png)

![image](https://cloud.githubusercontent.com/assets/656739/15456687/902a76f2-206f-11e6-8bfa-2d8541e18b1d.png)

![image](https://cloud.githubusercontent.com/assets/656739/15456688/94fbbf6a-206f-11e6-9ff8-0fe4832f942f.png)

![image](https://cloud.githubusercontent.com/assets/656739/15456689/9a9f49c8-206f-11e6-8866-94e5ee982d2c.png)

**Comment by DinisCruz** [comment]
I just run it with the debug flag set to true, and here are the logs (in case it helps)

```
wallaby.js started
core v1.0.232
Sun, 22 May 2016 21:58:41 GMT wallaby:project File cache: /Users/diniscruz/Library/Caches/WebStorm2016.1/wallaby/projects/fd2247435bc67e38
Sun, 22 May 2016 21:58:41 GMT wallaby:project Config file change detected, invalidating local cache
Sun, 22 May 2016 21:58:41 GMT wallaby:workers Parallelism for initial run: 2, for regular run: 2
Sun, 22 May 2016 21:58:41 GMT wallaby:workers Starting run worker instance #0
Sun, 22 May 2016 21:58:41 GMT wallaby:workers Starting run worker instance #1
Sun, 22 May 2016 21:58:41 GMT wallaby:workers Web server is listening at 55226
Sun, 22 May 2016 21:58:41 GMT wallaby:project File cache requires some updates, waiting required files from IDE
Sun, 22 May 2016 21:58:41 GMT wallaby:project File test/abc.coffee changes are patches only: false
Sun, 22 May 2016 21:58:41 GMT wallaby:project File test/start-test.coffee changes are patches only: false
Sun, 22 May 2016 21:58:41 GMT wallaby:project Preparing to process test/abc.coffee
Sun, 22 May 2016 21:58:41 GMT wallaby:project Starting processor pool (if not yet started)
Sun, 22 May 2016 21:58:41 GMT wallaby:project Preparing to process test/start-test.coffee
Sun, 22 May 2016 21:58:41 GMT wallaby:project Starting processor pool (if not yet started)
Sun, 22 May 2016 21:58:42 GMT wallaby:workers Started run worker instance (delayed) #1
Sun, 22 May 2016 21:58:42 GMT wallaby:workers Started run worker instance (delayed) #0
Sun, 22 May 2016 21:58:42 GMT wallaby:processor Running 1 processor(s) for test/start-test.coffee
Sun, 22 May 2016 21:58:42 GMT wallaby:processor Running 1 processor(s) for test/abc.coffee
Sun, 22 May 2016 21:58:42 GMT wallaby:processor Finished running one processor for test/start-test.coffee
Sun, 22 May 2016 21:58:42 GMT wallaby:project Processing compiled test/start-test.coffee
Sun, 22 May 2016 21:58:42 GMT wallaby:project Instrumenting test/start-test.coffee, via process pool: true
Sun, 22 May 2016 21:58:42 GMT wallaby:processor Finished running one processor for test/abc.coffee
Sun, 22 May 2016 21:58:42 GMT wallaby:project Processing compiled test/abc.coffee
Sun, 22 May 2016 21:58:42 GMT wallaby:project Instrumenting test/abc.coffee, via process pool: true
Sun, 22 May 2016 21:58:42 GMT wallaby:project No preprocessors configured for test/start-test.coffee
Sun, 22 May 2016 21:58:42 GMT wallaby:project Writing to disk and caching processed file test/start-test.coffee
Sun, 22 May 2016 21:58:42 GMT wallaby:project No preprocessors configured for test/abc.coffee
Sun, 22 May 2016 21:58:42 GMT wallaby:project Writing to disk and caching processed file test/abc.coffee
Sun, 22 May 2016 21:58:42 GMT wallaby:project File test/start-test.coffee changes saved, store ts: 1463953732000, change ts: 1463954321400
Sun, 22 May 2016 21:58:42 GMT wallaby:project File test/abc.coffee changes saved, store ts: 1463953749000, change ts: 1463954321384
Sun, 22 May 2016 21:58:42 GMT wallaby:project Stopping process pool
Sun, 22 May 2016 21:58:42 GMT wallaby:project Running postprocessor
Sun, 22 May 2016 21:58:42 GMT wallaby:postprocessor New TypeScript language service is required
Sun, 22 May 2016 21:58:42 GMT wallaby:postprocessor TypeScript postprocessor will be removed because in 2 project files none were found by patterns: **/*.ts?(x)
Sun, 22 May 2016 21:58:42 GMT wallaby:project Postprocessor execution finished
Sun, 22 May 2016 21:58:42 GMT wallaby:project Postprocessor is removed as requested by itself
Sun, 22 May 2016 21:58:42 GMT wallaby:project Test run started; run priority: 3
Sun, 22 May 2016 21:58:42 GMT wallaby:project Running all tests
Sun, 22 May 2016 21:58:42 GMT wallaby:workers Starting test run, priority: 3
Sun, 22 May 2016 21:58:42 GMT wallaby:workers Distributing tests between 2 workers
Sun, 22 May 2016 21:58:42 GMT wallaby:workers Running tests in parallel
Sun, 22 May 2016 21:58:42 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #nbvil]
Sun, 22 May 2016 21:58:42 GMT wallaby:nodeRunner Starting sandbox [worker #1, session #b8e6z]
Sun, 22 May 2016 21:58:42 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #nbvil]
Sun, 22 May 2016 21:58:42 GMT wallaby:nodeRunner Preparing sandbox [worker #1, session #b8e6z]
Sun, 22 May 2016 21:58:42 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #nbvil]
Sun, 22 May 2016 21:58:42 GMT wallaby:nodeRunner Prepared sandbox [worker #1, session #b8e6z]
Sun, 22 May 2016 21:58:42 GMT wallaby:workers Running tests in sandbox [worker #0, session #nbvil]
Sun, 22 May 2016 21:58:42 GMT wallaby:workers Running tests in sandbox [worker #1, session #b8e6z]
console.log: in abc.coffee..
console.log: in abc.coffee..
Sun, 22 May 2016 21:58:42 GMT wallaby:workers Loaded 0 test(s)
Sun, 22 May 2016 21:58:42 GMT wallaby:workers Loaded 1 test(s)
Sun, 22 May 2016 21:58:42 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
Sun, 22 May 2016 21:58:42 GMT wallaby:workers Sandbox [nbvil] is responsive, closing it
Sun, 22 May 2016 21:58:42 GMT wallaby:workers Test executed: happpens with require
Sun, 22 May 2016 21:58:42 GMT wallaby:workers Run 1 test(s), skipped 0 test(s)
Sun, 22 May 2016 21:58:42 GMT wallaby:workers Sandbox [b8e6z] is responsive, closing it
Sun, 22 May 2016 21:58:42 GMT wallaby:workers Merging parallel test run results
Finished executing 1 affected test(s)
Sun, 22 May 2016 21:58:42 GMT wallaby:project Test run finished
Sun, 22 May 2016 21:58:42 GMT wallaby:project Processed console.log entries
Sun, 22 May 2016 21:58:42 GMT wallaby:project Processed loading sequences
Sun, 22 May 2016 21:58:42 GMT wallaby:project Processed executed tests
Sun, 22 May 2016 21:58:42 GMT wallaby:project Processed code coverage
Sun, 22 May 2016 21:58:42 GMT wallaby:project Test run result processed and sent to IDE
Sun, 22 May 2016 21:58:50 GMT wallaby:project File test/start-test.coffee changes are patches only: true
Sun, 22 May 2016 21:58:50 GMT wallaby:project Caching file [2] in memory
Sun, 22 May 2016 21:58:50 GMT wallaby:project Preparing to process test/start-test.coffee
Sun, 22 May 2016 21:58:50 GMT wallaby:processor Running 1 processor(s) for test/start-test.coffee
Sun, 22 May 2016 21:58:50 GMT wallaby:processor Finished running one processor for test/start-test.coffee
Sun, 22 May 2016 21:58:50 GMT wallaby:project Processing compiled test/start-test.coffee
Sun, 22 May 2016 21:58:50 GMT wallaby:project Instrumenting test/start-test.coffee, via process pool: false
Sun, 22 May 2016 21:58:50 GMT wallaby:project No preprocessors configured for test/start-test.coffee
Sun, 22 May 2016 21:58:50 GMT wallaby:project Writing to disk and caching processed file test/start-test.coffee
Sun, 22 May 2016 21:58:50 GMT wallaby:project File test/start-test.coffee changes saved, store ts: 1463953732000, change ts: 1463954330186
Sun, 22 May 2016 21:58:50 GMT wallaby:project Test run started; run priority: 2
Sun, 22 May 2016 21:58:50 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Sun, 22 May 2016 21:58:50 GMT wallaby:workers Starting test run, priority: 2
Sun, 22 May 2016 21:58:50 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #2d3v8]
Sun, 22 May 2016 21:58:50 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #2d3v8]
Sun, 22 May 2016 21:58:50 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #2d3v8]
Sun, 22 May 2016 21:58:50 GMT wallaby:workers Running tests in sandbox [worker #0, session #2d3v8]
Sun, 22 May 2016 21:58:50 GMT wallaby:workers Sandbox (active) [2d3v8] error: TypeError: Cannot read property '0' of undefined
Runtime error: TypeError: Cannot read property '0' of undefined
    at Object.<anonymous> (./test/abc.js:2:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
Sun, 22 May 2016 21:58:50 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
Sun, 22 May 2016 21:58:50 GMT wallaby:workers Sandbox [2d3v8] is responsive, closing it
Sun, 22 May 2016 21:58:50 GMT wallaby:project Test run finished
Sun, 22 May 2016 21:58:50 GMT wallaby:project Processed console.log entries
Sun, 22 May 2016 21:58:50 GMT wallaby:project Processed loading sequences
Sun, 22 May 2016 21:58:50 GMT wallaby:project Processed executed tests
Sun, 22 May 2016 21:58:50 GMT wallaby:project Processed code coverage
Sun, 22 May 2016 21:58:50 GMT wallaby:project Test run result processed and sent to IDE
```

**Comment by DinisCruz** [comment]
btw, the issue doesn't happen when the require is in the ```src``` folder

![image](https://cloud.githubusercontent.com/assets/656739/15456726/50174372-2071-11e6-9582-cbe7cd2f768d.png)

**Comment by ArtemGovorov** [comment]
Thanks for providing the details.

As [specified in the docs](https://wallabyjs.com/docs/config/files.html#tests), only actual test files should be specified in the tests list, i.e. the files with specs/tests (for example with describe/it for mocha/jasmine). Any test helpers or testing frameworks extensions should be specified in the files list.

So in your case, if there are some files in the tests folder that are not tests, the config may look like this:
```javascript
module.exports = function (wallaby) {
    wallaby
    return {
        files: [
            { pattern: 'test-spectron/src/**/*.coffee'},
            { pattern: 'test-spectron/electron-apps/** /*.*', instrument: false},
            { pattern: ''test-spectron/test/**/*.coffee'' },
            { pattern: ''test-spectron/test/**/*-test.coffee'', ignore: true },
        ],

        tests: [
            'test-spectron/test/**/*-test.coffee'
        ],

        //testFramework: 'mocha',

        env: {
            type: 'node'//,
        },
    };
};
```

**Comment by DinisCruz** [comment]
ok, thx
