### ISSUE TITLE
Cannot read Cache and module not found react/lib/ExecutionEnvironment by enzyme

### ISSUE THREAD

**Issue by maitriyogin** [wallabyjs/public#642]
### Module not found react/lib/ExecutionEnvironment by enzyme
Hi,
having a bit of bother with setting up wallaby in our react application.
The error I'm getting is this in the wallaby console
```
Runtime error: TypeError: Cannot read property 'cache' of undefined
    at Object.<anonymous> (./src/adapters/__test__/aggregation_adapter.spec.js.wbp.js:1:85)

```

And then this in Failing tests 
```
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'react/lib/ExecutionEnvironment' in ****/node_modules/enzyme/build

TypeError: Cannot read property 'cache' of undefined
	at src/adapters/__test__/aggregation_adapter.spec.js:1
```
This is happening for a bunch of tests but actually not all.

If I open a file and then it's test file in web storm I can see the grey squares both in the test and implementation.  Although in the test file the tooltip says that the code is uncovered ... Thought this was a bit strange as it's the test code..

Our file structure is 
```
src/**/*.js
src/**/__tests__/*.spec.js
```
So all our test files are postfixed with .spec and live in a __tests__

As you can see from the wallaby config I'v had to fiddle to get web pack section to look like our own webpack.config.
### Wallaby.js configuration file

```
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');
// Remove this when aws-sdk support webpack //
const awsPath = path.join('aws-sdk', 'dist', 'aws-sdk');

var wallabyPostprocessor = wallabyWebpack({
  // webpack options, such as
  // module: {
  //   loaders: [...]
  // },
  // externals: { jquery: "jQuery" }
  module: {
    loaders: [
      {
        test: /\.jsx?$/, exclude: /(node_modules|vendor|spec)/, loaders: ['babel']
      },
      {test: /\.scss$/, loaders: ['style', 'css', 'autoprefixer', 'sass']},
      {
        test: /\.css$/,
        loader: 'style!css?modules',
        exclude: /(node_modules\/(c3|mapbox\.js|leaflet\.markercluster))/
      },
      {test: /\.css$/, loaders: ['style', 'css'], include: /(node_modules\/(c3|mapbox\.js|leaflet\.markercluster))/},
      {test: /\.(woff|woff2|eot|ttf|svg|png|jpg)$/, loader: 'file?name=dist/assets/[hash].[ext]'},
      {test: /\.json$/, loader: 'json'},
      {test: require.resolve(awsPath), loader: 'exports?AWS'}
    ],
    noParse: /aws-sdk/
  },
  resolve: {
    modulesDirectories: [
      path.join(__dirname, 'node_modules'),
      'node_modules', 'src'],
    alias: {'aws-sdk': awsPath}
  }
});


module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false},
      "src/**/*.js",
      "src/**/*.scss",
      "src/assets/**/*.*",
      {pattern: 'src/**/*.spec.js', ignore: true},
      'test/unit/test_helper.js'
    ],
    tests: [
      "src/**/*.spec.js"
    ],
    postprocessor: wallabyPostprocessor,
    compilers: {
      'src/**/*.js': wallaby.compilers.babel(),
      'test/unit/test_helper.js': wallaby.compilers.babel()
    },
    workers: {
      initial: 6,
      regular: 2
    },

    env: {
      type: 'node', runner: 'node'
    },

    testFramework: 'mocha',

    bootstrap: function bootstrap() {
      require('./test/unit/test_helper'); // <-- it's in the `files` list, so you may just do that
    },

    setup: function () {
      // required to trigger test loading
      window.__moduleBundler.loadTests();
    }
  };
};


```

### Code editor or IDE name and version

WebStorm v16

### OS name and version
OSX 10.11.4

### Node Version
v6.0.2

**Comment by ArtemGovorov** [comment]
Not sure what exactly is causing the issue, but I have spotted a few things in your config that may be causing it:

- You can not use webpack in node environment with wallaby.js, so I have removed the `env` setting.
- When using webpack, you need to set [`load: false` to your files and tests](https://wallabyjs.com/docs/integration/webpack.html), otherwise by default they'll be loaded via `script` tags instead of being loaded via webpack when you call the `window.__moduleBundler.loadTests();` in your `setup` function. So I have set the `load: false` to everything, except `babel-polyfill`, which I'm assuming you do want to just load via `script` into the sandbox.
- We recommend to use wallaby built-in babel compiler instead of the `babel-loader`, so I removed the `babel-loader` and extended your `compilers` pattern to include `jsx` (because your babel loader config includes it, your `files` patterns don't seem to include any `jsx` files though).
- [`setup` and `bootstrap` are alias](https://wallabyjs.com/docs/config/bootstrap.html) of the same thing, so no need to specify both.
- To `require` the `test_helper` via webpack, you need to [use `entryPatterns`](https://wallabyjs.com/docs/integration/webpack.html#entry-patterns). So I have added the file and your tests pattern to the `entryPatterns` of your webpack config.

Here is the config after the mentioned changes. Please try it and let me know how it goes.

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');
// Remove this when aws-sdk support webpack //
const awsPath = path.join('aws-sdk', 'dist', 'aws-sdk');

var wallabyPostprocessor = wallabyWebpack({
  entryPatterns: [ 'test/unit/test_helper.js', 'src/**/*.spec.js' ],
  module: {
    loaders: [
      {test: /\.scss$/, loaders: ['style', 'css', 'autoprefixer', 'sass']},
      {
        test: /\.css$/,
        loader: 'style!css?modules',
        exclude: /(node_modules\/(c3|mapbox\.js|leaflet\.markercluster))/
      },
      {test: /\.css$/, loaders: ['style', 'css'], include: /(node_modules\/(c3|mapbox\.js|leaflet\.markercluster))/},
      {test: /\.(woff|woff2|eot|ttf|svg|png|jpg)$/, loader: 'file?name=dist/assets/[hash].[ext]'},
      {test: /\.json$/, loader: 'json'},
      {test: require.resolve(awsPath), loader: 'exports?AWS'}
    ],
    noParse: /aws-sdk/
  },
  resolve: {
    modulesDirectories: [
      path.join(__dirname, 'node_modules'),
      'node_modules', 'src'],
    alias: {'aws-sdk': awsPath}
  }
});


module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false},
      {pattern: "src/**/*.js", load: false},
      {pattern: "src/**/*.scss", load: false},
      {pattern: "src/assets/**/*.*", load: false},
      {pattern: 'src/**/*.spec.js', ignore: true},
      {pattern: 'test/unit/test_helper.js', load: false}
    ],
    tests: [
      {pattern: "src/**/*.spec.js", load: false}
    ],
    postprocessor: wallabyPostprocessor,
    compilers: {
      'src/**/*.js?(x)': wallaby.compilers.babel(),
      'test/unit/test_helper.js': wallaby.compilers.babel()
    },
    workers: {
      initial: 6,
      regular: 2
    },

    testFramework: 'mocha',

    setup: function () {
      // required to trigger test loading
      window.__moduleBundler.loadTests();
    }
  };
};

```

**Comment by maitriyogin** [comment]
Hi Artem,thanks for the fast reply!
ok I tried it and got the following errors 
lots of these 
```
SyntaxError: Parse error
at http://localhost:64653/__modules/1224.js?1465552416259:2
```

then
```
ModuleNotFoundError: Module not found: Error: Cannot resolve module **'fs'** in /project/node_modules/jsdom/lib
  at /project/node_modules/webpack/lib/Compilation.js:229:38

ModuleNotFoundError: Module not found: Error: Cannot resolve module **'fs'** in /project/node_modules/jsdom/lib/jsdom/browser
  at /project/node_modules/webpack/lib/Compilation.js:229:38

ModuleNotFoundError: Module not found: Error: Cannot resolve module **'net'** in /project/node_modules/tough-cookie/lib
  at /project/node_modules/webpack/lib/Compilation.js:229:38

ModuleNotFoundError: Module not found: Error: Cannot resolve module 'child_process' in /project/node_modules/jsdom/lib/jsdom/living
  at 

/project/node_modules/webpack/lib/Compilation.js:229:38

ModuleNotFoundError: Module not found: Error: Cannot resolve module 'react/lib/ReactContext' in /project/node_modules/enzyme/build
  at /project/node_modules/webpack/lib/Compilation.js:229:38

ModuleNotFoundError: Module not found: Error: Cannot resolve module 'react/lib/ExecutionEnvironment' in /project/node_modules/enzyme/build
  at /project/node_modules/webpack/lib/Compilation.js:229:38


ModuleNotFoundError: Module not found: Error: Cannot resolve module **'fs'** in /project/node_modules/cssstyle/lib
  at /project/node_modules/webpack/lib/Compilation.js:229:38

ModuleNotFoundError: Module not found: Error: Cannot resolve module **'net'** in /project/node_modules/forever-agent
  at /project/node_modules/webpack/lib/Compilation.js:229:38

ModuleNotFoundError: Module not found: Error: Cannot resolve module **'tbs'** in /project/node_modules/forever-agent
  at /project/node_modules/webpack/lib/Compilation.js:229:38

```
looks like fs, net and tls are missing ... I switched to the node v4.2.2 that you ship and got exactly the same error...
the tests run fine when running npm run test, heres the command in our package.json
```
"test": "NODE_ENV=testing NODE_PATH=$(pwd)/src mocha --compilers js:babel-register,.:./test/unit/test_compiler.js --require ./test/unit/test_helper.js --recursive ./test/unit --recursive ./src/**/*.spec.js",
```

and heres our test helper
```
import chai from 'chai';
import sinonChai from 'sinon-chai';
import chaiEnzyme from 'chai-enzyme';
import chaiImmutable from 'chai-immutable';

chai.use(sinonChai);
chai.use(chaiEnzyme());
chai.use(chaiImmutable);

var jsdom = require('jsdom').jsdom;

var exposedProperties = ['window', 'navigator', 'document'];

global.document = jsdom('');
global.window = document.defaultView;
Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    exposedProperties.push(property);
    global[property] = document.defaultView[property];
  }
});

global.navigator = {
  userAgent: 'node.js'
};
```

test compiler ( maybe this is missing from wallaby ?)
```
// The purpose of this file is to support webpack loaders in mocha

const loader = (module, filename) =>
  module._compile(`module.exports = '${filename.replace(__dirname, '')}'`, filename);

[
  '.png',
  '.jpg',
  '.gif',
  '.svg',
  '.css',
  '.scss'
].forEach(extension => require.extensions[extension] = loader);

```

Cheers,
Stephen.

**Comment by ArtemGovorov** [comment]
Ok, thanks for sharing your `npm run test` command, it looks like you are not using webpack for testing and are testing in [node environment](https://wallabyjs.com/docs/integration/node.html). In this case you need to get rid of the webpack stuff from your config, and need just few things:

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      "src/**/*.js",
      "src/**/*.scss",
      "src/assets/**/*.*",
      'test/unit/test_helper.js',
      'test/unit/test_compiler.js',
      {pattern: 'src/**/*.spec.js', ignore: true},
    ],

    tests: [
      'src/**/*.spec.js'
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    env: {
      type: 'node', runner: 'node'
    },

    setup: function () {
      require('babel-polyfill');
      require('./test/unit/test_compiler.js'); 
      require('./test/unit/test_helper'); 
    }
  };
};
```

**Comment by ArtemGovorov** [comment]
Also forgot to suggest to set the envronment variables from your command:
```javascript
    setup: function (w) {
      process.env.NODE_ENV = 'testing';
      process.env.NODE_PATH = './src'; // or, if the relative path doesn't work, then try the absolute one: require('path').join(w.projectCacheDir, 'src');

      require('babel-polyfill');
      require('./test/unit/test_compiler.js'); 
      require('./test/unit/test_helper'); 
    }
```

**Comment by maitriyogin** [comment]
Hi Artem,
that's working better if not perfect although ...
In our webpack config we had a 
```
resolve: {
  modulesDirectories: ['node_modules', 'src']
}
```
I'v got lots of module not found exceptions because I'm lacking a modulesDirectory ...
How do I do this with wallaby config?
I kind of thought that 
```
process.env.NODE_PATH = require('path').join(w.projectCacheDir, 'src');
```
Cheers,
/Stephen.

**Comment by ArtemGovorov** [comment]
> `process.env.NODE_PATH = require('path').join(w.projectCacheDir, 'src');`

I thought this should do the trick. You may try to move it to the main function, perhaps it's too late to set it in the test runner process, and setting it in the main process that will pass it to test runner processes anyway, may help (I also added the `path.delimiter` just in case):

```javascript
module.exports = function (wallaby) {
  process.env.NODE_PATH += require('path').delimiter 
    + require('path').join(wallaby.projectCacheDir, 'src');

  return {
    ...
  }
}
```

Works for me in a similar setup. If it doesn't help, please create a sample repo demonstrating the issue, happy to have a look.

**Comment by ArtemGovorov** [comment]
Re-reading my message, perhaps I should've been more clear: the `setup` function gets executed in a test runner process, so setting some env variables at that stage may be too late. On the other hand, setting some env variables in outside the function will set them in the main wallaby process env, which gets passed when forking test runner processes, so may help. Hope it makes sense.

**Comment by maitriyogin** [comment]
Hi, yes that made sense.
I had to include both
```
process.env.NODE_ENV = 'testing';
  process.env.NODE_PATH += require('path').delimiter
    + require('path').join(wallaby.projectCacheDir, 'src');
```
at the top of the function.
Works great!
Huge thanks for your help.
/Stephen.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
