### ISSUE TITLE
​Error: Cannot find module './test/ClientInfoSpec.js'

### ISSUE THREAD

**Issue by thomas-jeepe** [wallabyjs/public#645]
### ​Error: Cannot find module './test/ClientInfoSpec.js'

So currently, I am trying to set up a typescript/webpack/react app with wallaby, and I didn't get very much progress. No matter what I do I seem to get this error.

```
​0 failing tests, 0 passing
​
​SyntaxError: Parse error
​ /Users/PenguinSoccer/Documents/projects/ecolo/test/ClientInfoSpec.tsx:6:0
​Error: Cannot find module './test/ClientInfoSpec.js'
​at http://localhost:53389/wallaby-webpack.js?1465679241262:1
​Error: Cannot find module '/Users/PenguinSoccer/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.15/projects/e3774cd2e1ae07db/instrumented/test/ClientInfoSpec.js'
```

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack')
var webpackPostprocessor = wallabyWebpack({})
var config = require('./webpack.config.js')

config.module.loaders = config.module.loaders.filter(function(l) {
  return l.loader !== 'awesome-typescript-loader' 
})

module.exports = function () {

  return {
    files: [
      { pattern: 'src/**/*.ts', load: false },
      { pattern: 'src/**/*.tsx', load: false }
    ],

    tests: [
      { pattern: 'test/**/*Spec.ts', load: false },
      { pattern: 'test/**/*Spec.tsx', load: false }
    ],

    testRunner: 'mocha',

    postprocessor: webpackPostprocessor,

    bootstrap: function () {
      window.__moduleBundler.loadTests()
    }
  }
}
```

### webpack.config.js
```javascript
var path = require('path')
var webpack = require('webpack')
var ExtractTextPlugin = require('extract-text-webpack-plugin')

module.exports = {
  devtool: 'source-map',
  entry: [
    'webpack-hot-middleware/client',
    './src/app/Index.tsx'
  ],
  output: {
    path: __dirname + '/src/endpoint/static',
    filename: 'app.js',
    publicPath: '/static/'

  },
  plugins: [
    new ExtractTextPlugin('style.css', { allChunks: true }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ],
  resolve: {
    extensions: ['', '.ts', '.tsx', '.js']
  },
  module: {
    loaders: [{
      test: /\.ts$/,
      loader: 'awesome-typescript-loader'
    },{
      test: /\.tsx$/,
      loader: 'awesome-typescript-loader'
    },{
      test: /\.js$/,
      loader: 'awesome-typescript-loader',
      exclude: /node_modules/
    },{ 
      test: /\.css$/, 
      loader: 'style!css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]' 
    }]
  }
}
```

### File structure

```
project/
  test/
    ClientInfoSpec.tsx
  src/
    app/
      (otherdirs)
      Index.js
    endpoint/
      css/
      images/
  wallaby.js
  webpack.config.json
  tsconfig.json
  typings.json
  package.json
  server.js
```

### Contents of test file

```javascript
/// <reference path="../typings/globals/mocha/index.d.ts" />
// import { mount } from 'enzyme'
import { expect } from 'chai'

describe('ClientInfo', () => {
  it('should render', () => {
    // const wrapper = mount(<ClientInfo/>, { attachTo: document.body })
    
    // expect(wrapper.find('h2').length).toBe(1)
    expect(1).to.equal(1)
  })
})
```

### Code editor or IDE name and version
Visual Studio Code v1.2.0

### OS name and version

OSX El Capitan 10.11.3

**Comment by ArtemGovorov** [comment]
Thanks for the file structure and the files.

I have created [this repo](https://github.com/wallabyjs/wallaby-645) with your file structure and files content and it works for me. Could you please clone it to see if it works for you, and if so, suggest the changes to reproduce the issue?

Note that you are not really using your webpack config in your wallaby config, because you are passing an empty object:
```javascript
var webpackPostprocessor = wallabyWebpack({})
```
and not the imported `config`. Either way, if I change it to use your config, it still works for me (but `new webpack.HotModuleReplacementPlugin()` needs to be removed in wallaby config).

Also note that you may need to add your `tsconfig.json` in order for the TSX syntax to be correctly compiled (your provided sample works as is though).

**Comment by thomas-jeepe** [comment]
Awesome! that almost works for me now :D

So the problem on my side was that my tsconfig target was set ES6 and not ES5.

Now I got it largely working on my main project, with two expections.

#### 1.

In the test file, importing from the source files fails.

Adding this LOC to a test file:

```javascript
import api from '../src/app/bundles/api'
```

Causes this failure

```
​Error: Cannot find module "../src/app/bundles/api"
​ /Users/PenguinSoccer/Documents/projects/ecolo/test/ClientInfoSpec.tsx:4
​ /Users/PenguinSoccer/Documents/projects/ecolo/test/ClientInfoSpec.tsx:4
​ModuleParseError: Module parse failed: ./src/app/bundles/api.ts Unexpected token (7:7)
​You may need an appropriate loader to handle this file type.
​SyntaxError: Unexpected token (7:7)
​  at Parser.pp.raise (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:920:13)
​  at Parser.pp.unexpected (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:1483:8)
​  at Parser.pp.expect (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:1477:26)
​  at Parser.pp.parseExportSpecifiers (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:2211:8)
​  at Parser.pp.parseExport (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:2183:28)
​  at Parser.pp.parseStatement (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:1744:85)
​  at Parser.pp.parseTopLevel (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:1648:21)
​  at Parser.parse (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:1616:17)
​  at Object.parse (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:882:44)
​  at Parser.parse (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/lib/Parser.js:902:15)
​  at DependenciesBlock.<anonymous> (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/lib/NormalModule.js:104:16)
​  at DependenciesBlock.onModuleBuild (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
​  at nextLoader (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
​  at /Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
​  at /Users/PenguinSoccer/Documents/projects/ecolo/node_modules/graceful-fs/graceful-fs.js:78:16
​  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
​
​  at DependenciesBlock.<anonymous> (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/lib/NormalModule.js:113:20)
​  at DependenciesBlock.onModuleBuild (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
​  at nextLoader (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
​  at /Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
​  at /Users/PenguinSoccer/Documents/projects/ecolo/node_modules/graceful-fs/graceful-fs.js:78:16
​  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

That seems to be a problem with webpack.

### 2.

Trying to use enzyme causes parsing failures.

If I import enzyme and use it in a test, it will cause a ModuleParseError.

```javascript
/// <reference path="../typings/globals/mocha/index.d.ts" />
import * as React from 'react'
import * as ReactDOM from 'react-dom'
// import api from '../src/app/bundles/api'
import { mount } from 'enzyme'
import { expect } from 'chai'

describe('ClientInfo', () => {
  it('should render', () => {
    // console.log(<ClientInfo header='hi' />)
    const wrapper = mount(<h1>hi</h1>, { attachTo: document.body })
    // ReactDOM.render(<h1>hi</h1>, document.body)
    // expect(wrapper.find('h2').length).to.equal('hi')
    expect(1).to.equal(1)
  })
})
```

Fails with 

```
​ModuleParseError: Module parse failed: /Users/PenguinSoccer/Documents/projects/ecolo/node_modules/entities/maps/decode.json Unexpected token (1:4)
​You may need an appropriate loader to handle this file type.
​SyntaxError: Unexpected token (1:4)
​  at Parser.pp.raise (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:920:13)
​  at Parser.pp.unexpected (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:1483:8)
​  at Parser.pp.semicolon (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:1462:73)
​  at Parser.pp.parseExpressionStatement (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:1976:8)
​  at Parser.pp.parseStatement (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:1754:188)
​  at Parser.pp.parseBlock (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:1991:21)
​  at Parser.pp.parseStatement (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:1735:19)
​  at Parser.pp.parseTopLevel (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:1648:21)
​  at Parser.parse (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:1616:17)
​  at Object.parse (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/node_modules/acorn/dist/acorn.js:882:44)
​  at Parser.parse (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/lib/Parser.js:902:15)
​  at DependenciesBlock.<anonymous> (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/lib/NormalModule.js:104:16)
​  at DependenciesBlock.onModuleBuild (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
​  at nextLoader (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
​  at /Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
​  at /Users/PenguinSoccer/Documents/projects/ecolo/node_modules/graceful-fs/graceful-fs.js:78:16
​  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
​
​  at DependenciesBlock.<anonymous> (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack/lib/NormalModule.js:113:20)
​  at DependenciesBlock.onModuleBuild (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
​  at nextLoader (/Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
​  at /Users/PenguinSoccer/Documents/projects/ecolo/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
​  at /Users/PenguinSoccer/Documents/projects/ecolo/node_modules/graceful-fs/graceful-fs.js:78:16
​  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

It seems like using enzyme is causing the need to read a json file.

The problem is specific to enzyme because this:

```javascript
/// <reference path="../typings/globals/mocha/index.d.ts" />
import * as React from 'react'
import * as ReactDOM from 'react-dom'
// import api from '../src/app/bundles/api'
import { mount } from 'enzyme'
import { expect } from 'chai'

describe('ClientInfo', () => {
  it('should render', () => {
    // console.log(<ClientInfo header='hi' />)
    // const wrapper = mount(<h1>hi</h1>, { attachTo: document.body })
    ReactDOM.render(<h1>hi</h1>, document.body)
    // expect(wrapper.find('h2').length).to.equal('hi')
    expect(1).to.equal(1)
  })
})
```

works perfectly, screenshots work and everything else.


Anyways a big thank you for replying and helping so fast :)

**Comment by thomas-jeepe** [comment]
Quick note:

Changing the import statement to 

```javascript
import api from '../src/app/bundles/api'
```

Causes the failure to come from an import inside the api file rather than from the test file.

So it looks like webpack is trying to resolve with a .js file ending.

**Comment by thomas-jeepe** [comment]
I made a repo which reproduces those 

https://github.com/thomas-jeepe/wallaby-645

**Comment by ArtemGovorov** [comment]
Thanks for the repo.

> `import api from '../src/app/bundles/api'`

It fails for me because there's no `api.ts` file in your repo. I added one and managed to reproduce teh issue. Because wallaby stores both `ts` and compiled `js` files in its cache, you need to change the priority of the `js` extension in your webpack config, may just do it for wallaby in wallaby config by removing the resolve property completely to make webpack use defaults:

```javascript
var config = require('./webpack.config.js')

config.module.loaders = config.module.loaders.filter(function(l) {
  return l.loader !== 'awesome-typescript-loader'
})
delete config.resolve; // <--
```

I was also getting some `Module not found` issues for your css files, because the pattern for css files is missing in your `files` section:
```
    files: [
      ...
      { pattern: 'src/**/*.css', load: false }
    ],
```

Then I got the second issue you've mentioned.

> `​ModuleParseError: Module parse failed: /Users/PenguinSoccer/Documents/projects/ecolo/node_modules/entities/maps/decode.json Unexpected token (1:4)
​You may need an appropriate loader to handle this file type.`

It's pretty clear about what it needs though (and doesn't look like wallaby specific). I did:
```
npm i json-loader --save-dev
```
+
```
config.module.loaders.push({
  test: /\.json$/,
  loader: 'json-loader'
})
```

Then it started to complain about missing `react-addons-test-utils`, so I did
```
npm i react-addons-test-utils --save-dev
```

Now the test using `enzyme` is passing. There're few webpack `ModuleNotFoundError` errors still being reported from `enzyme` (they're not affecting tests). But it looks like its enzyme + webpack specific issue. Do you have any other test runner (karma?) set up? Does it display the same error?

**Comment by ArtemGovorov** [comment]
I'll close the issue for now as there's been no activity on it for a while. If the issue is still valid for you, please try my suggestions above and let me know how it goes.

**Comment by ArtemGovorov** [comment]
BTW, regarding the `enzyme` related `ModuleNotFoundError`, here is the related issue https://github.com/airbnb/enzyme/issues/47. The current solution is to specify some externals for enzyme:

```javascript
var config = require('./webpack.config.js')
...
config.externals = config.externals || {};
config.externals['react/lib/ExecutionEnvironment'] = true;
config.externals['react/lib/ReactContext'] = true;
config.externals['react/addons'] = true;
```

**Comment by thomas-jeepe** [comment]
Sorry about the non response.

I got it working with everything except CSS modules which didn't come up in the sandbox/snapshot.

I will post my wallaby config file in a bit.
