### ISSUE TITLE
error when using React and Enzyme

### ISSUE THREAD

**Issue by yanivefraim** [wallabyjs/public#666]
### Issue description or question
I have a (working) Reactjs + Wallaby setup. I tried to add Enzyme to my tests, and I am getting the following error: 
`Error: Cannot find module "../maps/decode.json"`

I guess it is somehow related to enzyme internal relative path?
I tried to add Enzyme to my files, but it did not help

### Wallaby.js configuration file

```javascript
const wallabyWebpack = require('wallaby-webpack');
const webpackConfig = require('my-web-build/config/webpack.config');
module.exports = function (wallaby) {

  const webpackPostprocessor = wallabyWebpack(webpackConfig);

  return {
    files: [
      {pattern: 'app/**/*.spec.[t|j]s*', load: false, ignore: true},

      {pattern: 'app/**/*.[t|j]s*', load: false},
      {pattern: 'node_modules/enzyme', load: false}, //This is an experiment I did adding enzyme to files
      {pattern: 'node_modules/react', load: false} //This is an experiment I did adding react to files
    ],

    tests: [
      {pattern: 'app/**/*.spec.[t|j]s*', load: false}
    ],

    compilers: {
      '**/*.[t|j]s*': wallaby.compilers.babel({babel: require('my-web-build/node_modules/babel-core')})
    },

    postprocessor: webpackPostprocessor,
    /*global window*/
    bootstrap() {
      window.__moduleBundler.loadTests();
    },
    debug: true
  };
};

```

### Code editor or IDE name and version

Atom v1.x

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
`enzyme` `require`-s JSON files, so webpack needs to know how to `require` JSON. Does your `wix-web-build/config/webpack.config` have `json-loader` added? If not you'll need to add it:
```javascript
const webpackConfig = require('wix-web-build/config/webpack.config');
webpackConfig.module.loaders.push({
  test: /\.json$/,
  loader: 'json-loader'
});
```
+
```
npm i json-loader --save-dev
```

**Comment by yanivefraim** [comment]
Ok, I added `json-loader` in my web-build. Now I get:

```shell
Error: Cannot find module "./package"
at http://localhost:62828/__modules/182.js?1466668646607:14
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'react/lib/ReactContext' in /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/enzyme/build
  at /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/webpack/lib/Compilation.js:229:38
  at onDoneResolving (/Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
  at /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/webpack/lib/NormalModuleFactory.js:85:20
  at /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/async/lib/async.js:726:13
  at /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/async/lib/async.js:52:16
  at done (/Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/async/lib/async.js:241:17)
  at /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/async/lib/async.js:44:16
  at /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/async/lib/async.js:723:17
  at /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/async/lib/async.js:167:37
  at /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
  at onResolved (/Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
  at innerCallback (/Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/enhanced-resolve/lib/Resolver.js:94:11)
  at loggingCallbackWrapper (/Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
  at /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/tapable/lib/Tapable.js:134:6
  at /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
  at /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/enhanced-resolve/lib/Resolver.js:191:15
  at /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:45:26
  at loggingCallbackWrapper (/Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
  at /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/tapable/lib/Tapable.js:134:6
  at /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/enhanced-resolve/lib/Resolver.js:122:33
  at /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/enhanced-resolve/lib/Resolver.js:191:15
  at applyPluginsParallelBailResult.createInnerCallback.log (/Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
  at loggingCallbackWrapper (/Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
  at /Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/tapable/lib/Tapable.js:134:6
  at Tapable.<anonymous> (/Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
  at Storage.finished (/Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
  at ReadFileContext.callback (/Users/yanivef/Documents/wix/wix-js-stack/examples/react-js/node_modules/graceful-fs/graceful-fs.js:78:16)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
```

**Comment by ArtemGovorov** [comment]
It looks like its enzyme + webpack specific issue.

BTW, regarding the `enzyme` related `ModuleNotFoundError`, here is the related issue https://github.com/airbnb/enzyme/issues/47 from the `enzyme` repo. From what I read there, the current solution is to specify some externals for enzyme:

```javascript
const webpackConfig = require('my-web-build/config/webpack.config');
...
webpackConfig.externals = config.externals || {};
webpackConfig.externals['react/lib/ExecutionEnvironment'] = true;
webpackConfig.externals['react/lib/ReactContext'] = true;
webpackConfig.externals['react/addons'] = true;
```

Let me know if it fixes the issue for you.

**Comment by yanivefraim** [comment]
I will try this solution. This error os only happening when using Wallaby (if I use `npm test` it works). So I guess it is somehow related to Wallaby

**Comment by ArtemGovorov** [comment]
Could you please share your `npm test` command and your other test runner config file?

**Comment by yanivefraim** [comment]
Ok, after playing with settings, the solution you suggested worked well for me (adding this to webpack configurations):

```js
externals: {
    jsdom: 'window',
    cheerio: 'window',
    'react/lib/ExecutionEnvironment': true,
    'react/lib/ReactContext': 'window'
  }
```

Thanks!

**Comment by stkrzysiak** [comment]
FWIW, this worked for me when I put it in the wallaby.js config file, like so:
`    externals: [
      { jsdom: 'window' },
      {cheerio: 'window'},
      {'react/lib/ExecutionEnvironment': true},
      {'react/lib/ReactContext': 'window'}
    ],`

**Comment by yanivefraim** [comment]
@stkrzysiak - isn't it the same as what I did?

**Comment by stkrzysiak** [comment]
@yanivefraim It must be now that I think about it, when I saw you write:
> adding this to webpack configurations
I thought you meant you added it to the webpack config file, not the wallabyjs file.

**Comment by yanivefraim** [comment]
@stkrzysiak - I did add this to my webpack configurations inside wallabyjs.. Something like:

```js
webpackConfig.externals = webpackConfig.externals || {};
webpackConfig.externals.jsdom = 'window';
webpackConfig.externals.cheerio = 'window';
webpackConfig.externals['react/lib/ExecutionEnvironment'] = true;
webpackConfig.externals['react/lib/ReactContext'] = 'window';

  const webpackPostprocessor = wallabyWebpack(webpackConfig);

```

**Comment by stkrzysiak** [comment]
Ah yes, then my mistake!  It looks like we're going through the same things lately @yanivefraim , i came across another one of your issues when trying to get my wallaby working.

**Comment by yanivefraim** [comment]
@stkrzysiak - (: Please fill free to contact if you have questions.. I have my Wallaby env setup working for client & server (Node and React)
