### ISSUE TITLE
"RangeError: out of range index" issue after upgrading to node 6.3

### ISSUE THREAD

**Issue by ArtemGovorov** [wallabyjs/public#686]
Node 6.3 has introduced some changes that [broke the websocket package](https://github.com/websockets/ws/issues/778) wallaby.js using. While we are investigating the issue, you may downgrade to node 6.2.2 (or use `nvm` to install it side by side and [configure wallaby.js to use the 6.2.2 version](https://wallabyjs.com/docs/intro/install.html)).

```
 RangeError: out of range index
   at RangeError (native)
   at fastCopy (/Users/mv/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.19/wallaby/node_modules/ws/lib/Receiver.js:317:24)
   at Receiver.add (/Users/mv/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.19/wallaby/node_modules/ws/lib/Receiver.js:78:3)
   at Socket.firstHandler (/Users/mv/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.19/wallaby/node_modules/ws/lib/WebSocket.js:663:22)
   at emitOne (events.js:96:13)
   at Socket.emit (events.js:188:7)
   at readableAddChunk (_stream_readable.js:177:18)
   at Socket.Readable.push (_stream_readable.js:135:10)
   at TCP.onread (net.js:542:20)
```

**Comment by ArtemGovorov** [comment]
The issue is fixed in core v1.0.259.
