### ISSUE TITLE
Error: payload cannot exceed 104857600 bytes

### ISSUE THREAD

**Issue by arg20** [wallabyjs/public#689]
### Issue description or question
I can't run wallaby.js on my project
### Wallaby.js configuration file

```javascript
"use strict";

module.exports = function(wallaby) {
  return {
    files: [
      '!node_modules/**/*.js',
      '!**/*.test.js',
      '.env',
      'api/**/*.js',
      'server.js',
      'mocha.conf.js',
      {pattern: 'config/**/*.js', instrument: false, load: true},
      {pattern: 'data-model/**/*.js', instrument: false, load: true},
      {pattern: 'config/**/*.json', instrument: false, load: true},
      {pattern: 'log/*.log', instrument: false, load: false}
    ],
    env: {
      type: 'node',
      runner: 'node',
      params: {
        env: 'DB_NAME=billboarder-test;NODE_ENV=test'
      }
    },
    tests: [
      'api/**/*.test.js'
    ],
    testFramework: 'mocha',
    bootstrap: function(wallaby) {
      require('dotenv').config({silent: true});
      var config = require('./config');
      var mocha = wallaby.testFramework;
      config.nodePort = 0;
      config.passwords.defaultNumberOfHashIterations = 2;
      config.database.database = config.database.database + '-' + wallaby.workerId;
      var setUpTeardown = require('./api/core/tests/setup.teardown');
      setUpTeardown.initializeAndSeedDatabase = setUpTeardown.seed;
      console.log(`Worker: ${wallaby.workerId} using Database: ${config.database.database}`);
      mocha.timeout(10000);
    },
    teardown: function(wallaby) {
      var knex = require('./api/core/models/base.model').knex;
      knex.destroy();
    }
  };
};
```

### Code editor or IDE name and version

WebStorm v11

### OS name and version

OSX

I'm getting this stack trace: 
```
Error: payload cannot exceed 104857600 bytes
    at Receiver.error (/Users/gabriel/Library/Caches/WebStorm2016.2/wallaby/wallaby/node_modules/ws/lib/Receiver.js:321:18)
    at Receiver.maxPayloadExceeded (/Users/gabriel/Library/Caches/WebStorm2016.2/wallaby/wallaby/node_modules/ws/lib/Receiver.js:389:8)
    at Receiver.<anonymous> (/Users/gabriel/Library/Caches/WebStorm2016.2/wallaby/wallaby/node_modules/ws/lib/Receiver.js:479:20)
    at Receiver.add (/Users/gabriel/Library/Caches/WebStorm2016.2/wallaby/wallaby/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/Users/gabriel/Library/Caches/WebStorm2016.2/wallaby/wallaby/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
```

The wallaby.js config file hasn't been changed for a while, it was working before, it just suddenly stopped working (I'm guessing a file is causing this? but I can't know which one).

**Comment by arg20** [comment]
Ok so it turns out that one of the log files that I need every time I run my process exceeded 104mb (it was 105mb) so I deleted that log file and it started working again but it's a really obscure error. Any way you can somehow handle it better?

**Comment by ArtemGovorov** [comment]
Thanks for the update. I'll double check the websocket library limits and add a more descriptive error message (will try to display the offending  file name).
