### ISSUE TITLE
ReactJs + Redux + Webpack.  Trying to run browser and node tests.

### ISSUE THREAD

**Issue by oshalygin** [wallabyjs/public#719]
### Issue description or question
Hey Artem, trying really hard here to get my tests to run in node as well as a jsdom(browser) environment.  Is there any possible way to include both browser and node as env?

Here is my github repo with the source code and project.  Any help is appreciated!~
https://github.com/oshalygin/ReactReduxRecipes

So with the following configuration I get the following errors:
```
[Error] Runtime error: ReferenceError: window is not defined
[Error]     at emitTwo (events.js:106:13)
[Error]     at WebSocket.emit (events.js:191:7)
````
### Wallaby.js configuration file

```javascript
const wallabyWebpack = require("wallaby-webpack");

module.exports = function (wallaby) {

    const webpackPostprocessor = wallabyWebpack({
        externals: {
            // Use external version of React instead of rebuilding it
            "react": "React" //eslint-disable-line
        },
        resolve: {
            extensions: ["", ".js", ".jsx"]
        }
    });

    return {
        files: [
            { pattern: "node_modules/babel-polyfill/dist/polyfill.min.js", instrument: false },
            { pattern: "node_modules/phantomjs-polyfill/bind-polyfill.js", instrument: false },
            { pattern: "node_modules/react/dist/react-with-addons.js", instrument: false },

            { pattern: "client/**/*.js*", load: false },
            { pattern: "!client/**/*.spec.js*", load: false }
        ],

        tests: [
            { pattern: "client/**/*.spec.js*", load: false }
        ],

        compilers: {
            "**/*.js*": wallaby.compilers.babel()
        },

        postprocessor: webpackPostprocessor,
        env: {

        }

        bootstrap: function () {
            window.__moduleBundler.loadTests(); //eslint-disable-line
        }
    };
};
```

### Code editor or IDE name and version
Visual Studio Code v0.10.x
### OS name and version
Windows

### Webpack configuration:
```
/* eslint-disable max-len */
import webpack from "webpack";
import path from "path";

export default {
  debug: true,
  devtool: "cheap-module-eval-source-map",
  noInfo: true,
  entry: [
    "eventsource-polyfill", // necessary for hot reloading with IE
    "webpack-hot-middleware/client?reload=true",
    "./client/index"
  ],
  target: "web",
  output: {
    path: __dirname + "/dist", // Note: Physical files are only output by the production build task `npm run build`.
    publicPath: "/",
    filename: "bundle.js"
  },
  devServer: {
    contentBase: "./client"
  },
  plugins: [
    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      "windows.jQuery": "jquery",
      "window.$": "jquery"
    }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ],
  module: {
    loaders: [
      { test: /\.js$/, include: path.join(__dirname, "server"), loaders: ["babel"] },
      { test: /\.js$/, include: path.join(__dirname, "client"), loaders: ["babel"] },
      { test: /\.jsx$/, include: path.join(__dirname, "client"), loader: "babel", query: { presets: ["es2015", "react"] } },
      { test: /(\.css)$/, loaders: ["style", "css"] },
      { test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: "file" },
      {
        test: /\.woff(\?v=\d+\.\d+\.\d+)?$/,
        loader: "url?limit=10000&mimetype=application/font-woff"
      }, {
        test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/,
        loader: "url?limit=10000&mimetype=application/font-woff"
      },
      { test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=application/octet-stream" },
      { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=image/svg+xml" },
      {test: /\.ico$/, loader: "file-loader?name=[name].[ext]"},
      {
        test: /\.(jpe?g|png|gif|svg)$/i,
        loaders: [
          "file?hash=sha512&digest=hex&name=[hash].[ext]",
          "image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false"
        ]
      }
    ]
  }
};
```

###Then I modified the code to go ahead and include some jsdom configuration and then I get the following errors!

```
 Started Wallaby.js Core v1.0.269
[Error] Runtime error: TypeError: Cannot read property 'cache' of undefined
[Error]     at Object.<anonymous> (./client/clientSanityCheck.spec.js.wbp.js:1:85)
[Error]     at Module._compile (module.js:541:32)
[Error]     at Object.Module._extensions..js (module.js:550:10)
[Error]     at Module.load (module.js:458:32)
[Error]     at tryModuleLoad (module.js:417:12)
[Error]     at Function.Module._load (module.js:409:3)
[Error]     at Module.require (module.js:468:17)
[Error]     at require (internal/module.js:20:19)
```

###Modified wallaby.js with jsdom configuration
```
const wallabyWebpack = require("wallaby-webpack");

module.exports = function (wallaby) {

    const webpackPostprocessor = wallabyWebpack({
        externals: {
            // Use external version of React instead of rebuilding it
            "react": "React" //eslint-disable-line
        },
        resolve: {
            extensions: ["", ".js", ".jsx"]
        }
    });

    return {
        files: [
            { pattern: "node_modules/babel-polyfill/dist/polyfill.min.js", instrument: false },
            { pattern: "node_modules/phantomjs-polyfill/bind-polyfill.js", instrument: false },
            { pattern: "node_modules/react/dist/react-with-addons.js", instrument: false },

            { pattern: "client/**/*.js*", load: false },
            { pattern: "!client/**/*.spec.js*", load: false },
            { pattern: "!/**/*.json", load: false }
        ],

        tests: [
            { pattern: "client/**/*.spec.js*", load: false }
        ],
        env: {
            type: "node"
        },
        compilers: {
            "**/*.js*": wallaby.compilers.babel()
        },

        postprocessor: webpackPostprocessor,

        bootstrap: function () {

            var jsdom = require("jsdom").jsdom;
            var exposedProperties = ["window", "navigator", "document"];

            global.document = jsdom("");
            global.window = document.defaultView;
            Object.keys(document.defaultView).forEach((property) => {
                if (typeof global[property] === "undefined") {
                    exposedProperties.push(property);
                    global[property] = document.defaultView[property];
                }
            });

            global.navigator = {
                userAgent: "node.js"
            };

            documentRef = document; //eslint-disable-line no-undef
            // window.__moduleBundler.loadTests(); //eslint-disable-line
        }
    };
};
```

###Note everything runs fine with command line mocha.  Would love to get wallaby going but I've been battling the configuration for awhile and I'm lost.  I tried to trace down the logs but with no luck.

Attached is a snippet of the debug:

```
[Info] Tue, 02 Aug 2016 02:11:29 GMT wallaby:workers Running tests in sandbox [worker #2, session #kuz5l]
[Info] Tue, 02 Aug 2016 02:11:29 GMT wallaby:workers Running tests in sandbox [worker #3, session #fp18k]
[Info] Tue, 02 Aug 2016 02:11:29 GMT wallaby:workers Running tests in sandbox [worker #4, session #ezezt]
[Info] Tue, 02 Aug 2016 02:11:29 GMT wallaby:workers Running tests in sandbox [worker #5, session #pkj0b]
[Info] Tue, 02 Aug 2016 02:11:30 GMT wallaby:workers Sandbox (active) [ezezt] error: TypeError: Cannot read property 'cache' of undefined
[Error] Runtime error: TypeError: Cannot read property 'cache' of undefined
[Error]     at Object.<anonymous> (./client/components/common/header.spec.js.wbp.js:1:85)
[Error]     at Module._compile (module.js:541:32)
[Error]     at Object.Module._extensions..js (module.js:550:10)
[Error]     at Module.load (module.js:458:32)
[Error]     at tryModuleLoad (module.js:417:12)
[Error]     at Function.Module._load (module.js:409:3)
[Error]     at Module.require (module.js:468:17)
[Error]     at require (internal/module.js:20:19)
[Info] Tue, 02 Aug 2016 02:11:30 GMT wallaby:workers Sandbox (active) [do0nq] error: TypeError: Cannot read property 'cache' of undefined
[Error] Runtime error: TypeError: Cannot read property 'cache' of undefined
[Error]     at Object.<anonymous> (./client/actions/xhrStatusActions.spec.js.wbp.js:1:85)
```

**Comment by ArtemGovorov** [comment]
Wallaby doesn't support both webpack and node environment in a single config (it's either webpack in browser environment or node environment, possibly with `jsdom`). In your case it should be possible, because:

> Note everything runs fine with command line mocha.

Try this:

```javascript
module.exports = function (wallaby) {

    return {
        files: [
            "client/**/*.js*"
            "!client/**/*.spec.js*"
        ],

        tests: [
            "client/**/*.spec.js*"
        ],
        env: {
            type: "node"
        },
        compilers: {
            "**/*.js*": wallaby.compilers.babel()
        },

        setup: function () {

            var jsdom = require("jsdom").jsdom;
            var exposedProperties = ["window", "navigator", "document"];

            global.document = jsdom("");
            global.window = document.defaultView;
            Object.keys(document.defaultView).forEach((property) => {
                if (typeof global[property] === "undefined") {
                    exposedProperties.push(property);
                    global[property] = document.defaultView[property];
                }
            });

            global.navigator = {
                userAgent: "node.js"
            };

            documentRef = document; //eslint-disable-line no-undef
        }
    };
};
```

In the `setup` (alias of `bootstrap`) function I have just pasted your `jsdom` setup. You need to do the same here as what you're doing in your plain mocha command line. You probably `--require` some helpers in your mocha command line (to initialize `jsdom`, etc.), so may need to require those files in the `setup` function as well (don't forget to include those files in the `files` list).

**Comment by oshalygin** [comment]
Artem,
As always thanks man!  I am 99% there, but I'm struggling to connect the last piece which is not instrumenting the image files.  

I've read the docs you posted here:
https://wallabyjs.com/docs/integration/webpack.html#webpack-options
But this seems like its configuration only for webpack, and since I'm not using webpack with your response(which nearly completely works for my solution), I'm not quite sure where I can add the node-noop plugin.   

This is the error I see
```
[Error] Runtime error: ./client/images/noResult.png:1
[Error] (function (exports, require, module, __filename, __dirname) { �PNG
[Error]                                                               ^
[Error] SyntaxError: Unexpected token ILLEGAL
[Error]     at Object.exports.runInThisContext (vm.js:53:16)
[Error]     at Module._compile (module.js:513:28)
[Error]     at Object.Module._extensions..js (module.js:550:10)
[Error]     at Module.load (module.js:458:32)
[Error]     at tryModuleLoad (module.js:417:12)
[Error]     at Function.Module._load (module.js:409:3)
[Error]     at Module.require (module.js:468:17)
[Error]     at require (internal/module.js:20:19)
[Error]     at Object.<anonymous> (/Users/Admin/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/projects/ffb120093528d7b1/instrumented/client/components/common/notFound.jsx:6:31)
```

The component basically looks like this:
```
const NotFound = ({message}) => {
    return (
        <div className="mdl-cell mdl-cell--12-col mdl-typography--text-center">
            <img src={require("../../images/noResult.png") } alt={"Not found Image"} />
            <br />
            <br />
            <p className="mdl-color-text--grey mdl-typography--headline">{message}</p>
        </div>
    );
};
```

Notice in the above example where I require the image in the middle of the code.  Probably better to pull it out as a variable but that doesn't help solve the problem anyways.

This is what my wallaby.js config looks like:
```
module.exports = function (wallaby) {

    return {
        files: [
            "client/**/*.js*",
            "!client/**/*.json",
            "!client/**/*.spec.js*",
            { pattern: "/**/*.png", instrument: false }
        ],

        tests: [
            "client/**/*.spec.js*"

        ],
        env: {
            type: "node"
        },
        compilers: {
            "**/*.js*": wallaby.compilers.babel()
        },

        // loaders: [
        //     {test: /\.(png)$/, loader: 'null'}
        // ],

        setup: function () {

            var jsdom = require("jsdom").jsdom;
            var exposedProperties = ["window", "navigator", "document"];

            global.document = jsdom("");
            global.window = document.defaultView;
            Object.keys(document.defaultView).forEach((property) => {
                if (typeof global[property] === "undefined") {
                    exposedProperties.push(property);
                    global[property] = document.defaultView[property];
                }
            });

            global.navigator = {
                userAgent: "node.js"
            };

            documentRef = document; //eslint-disable-line no-undef
        }
    };
};
```

Note I commented out the loaders part, I had no hope in that working anyways because it's not a wallabywebpack config.

Let me know if you have any ideas :)

Also for reference here is my mocha command line that works!
`NODE_ENV=test babel-node ./node_modules/.bin/isparta cover --include 'server/**/*.js*' --include 'client/**/*.js*' _mocha`

**Comment by oshalygin** [comment]
After some legit sleuthing around and reading the wallaby docs up and down(pretty damn solid docs man good job!), I got it working.  Obviously you helped as well!

Here is the working config file.  Working like a charm.  Note I had to pull in some of the babel configs into the wallabyjs config because I was getting complaints about my hmr in the .babelrc file. 

```
module.exports = function (wallaby) {

    return {
        files: [
            "client/**/*.js*",
            "server/**/*.js",
            "!client/**/*.json",
            "!client/**/*.spec.js*",
            "!server/**/*.spec.js*",
            { pattern: "/**/*.png", load: "null" }
        ],

        tests: [
            "client/**/*.spec.js",
            "server/**/*.spec.js"

        ],
        env: {
            type: "node",
            params: {
                env: "NODE_ENV=test"
            }
        },
        compilers: {
            "**/*.js*": wallaby.compilers.babel({
                presets: ["react", "es2015"],
                plugins: ["transform-object-rest-spread"]
            })
        },

        setup: function () {

            const noop = () => { };

            require.extensions[".css"] = noop;
            require.extensions[".ico"] = noop;
            require.extensions[".png"] = noop;
            require.extensions[".svg"] = noop;

            let jsdom = require("jsdom").jsdom;
            let exposedProperties = ["window", "navigator", "document"];

            global.document = jsdom("");
            global.window = document.defaultView;
            Object.keys(document.defaultView).forEach((property) => {
                if (typeof global[property] === "undefined") {
                    exposedProperties.push(property);
                    global[property] = document.defaultView[property];
                }
            });

            global.navigator = {
                userAgent: "node.js"
            };

            documentRef = document; //eslint-disable-line no-undef
        }
    };
};
```

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update. Just was typing my response to try setting `require.extensions[".png"]` to a noOp function.
