### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by vjau** [wallabyjs/public#739]
### Issue description or question
Wallaby runs with following error :
Postprocessor run failure: Failed to run preprocessors on client/imports/modules/ficheAppel/actionsCreators/dejaVenu.js, TypeError: Path must be a string. Received undefined
  at assertPath (path.js:7:11)
  at Object.dirname (path.js:1326:5)
  at /home/vincent/dev/Cadendar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:353:36
  at /home/vincent/dev/Cadendar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:375:22
  at Array.map (native)
  at OptionManager.resolvePresets (/home/vincent/dev/Cadendar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
  at OptionManager.mergePresets (/home/vincent/dev/Cadendar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
  at OptionManager.mergeOptions (/home/vincent/dev/Cadendar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
  at /home/vincent/dev/Cadendar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14
  at /home/vincent/dev/Cadendar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24
  at Array.map (native)
  at OptionManager.resolvePresets (/home/vincent/dev/Cadendar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
  at OptionManager.mergePresets (/home/vincent/dev/Cadendar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
  at OptionManager.mergeOptions (/home/vincent/dev/Cadendar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
  at OptionManager.init (/home/vincent/dev/Cadendar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
  at File.initOptions (/home/vincent/dev/Cadendar/node_modules/babel-core/lib/transformation/file/index.js:194:75)
  at new File (/home/vincent/dev/Cadendar/node_modules/babel-core/lib/transformation/file/index.js:123:22)
  at Pipeline.transform (/home/vincent/dev/Cadendar/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
  at **/*.js* (/home/vincent/dev/Cadendar/wallaby.plouf:32:49)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)

The file mentionned contains nothing special
### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  // There is a weird error with the mui and mantra.
  // See: https://goo.gl/cLH8ib
  // Using require here seems to be the error.
  // Renaming it into `load` just fixed the issue.
  var load = require;

  return {
    files: [
      { pattern: 'client/**/tests/*.js', ignore: true },
      { pattern: 'server/**/tests/*.js', ignore: true },
      { pattern: 'imports/**/tests/*.js', ignore: true },
      { pattern: 'client/**/tests/*.ts', ignore: true },
      { pattern: 'client/**/tests/*.tsx', ignore: true },
      { pattern: 'imports/**/tests/*.ts', ignore: true },
      { pattern: 'server/**/tests/*.ts', ignore: true },
      'client/imports/**/*.ts',
      'client/imports/**/*.tsx',
      'imports/**/*.ts',
      'server/**/*.ts'
    ],
    tests: [
      'client/**/tests/*.ts*',
      'imports/**/tests/*.ts',
      'server/**/tests/*.ts'
    ],
    compilers: {
      '**/*.ts*': wallaby.compilers.typeScript({module: 'es6'}),
      '**/*.js*': wallaby.compilers.babel()
    },
    preprocessors: {
      '**/*.js*': file => require('babel-core').transform(
        file.content,
        {sourceMap: true, presets: ["es2015", "stage-2","react"]})
    },
    env: {
      type: 'node'
    },
    testFramework: 'mocha',
    setup: function() {
      global.React = require('react');
    },
     workers: {
           recycle: true
         },
         debug : true
  };
};
```

### Code editor or IDE name and version

WebStorm 2016.2.1
node v6.3.1

### OS name and version

Ubuntu 16.04

**Comment by ArtemGovorov** [comment]
Did it start happening just recently and was ok before? Any recent changes in your environment (lile babel or node update)?

Try this:
```javascript
preprocessors: {
      '**/*.js*': file => require('babel-core').transform(
        file.content,
        {sourceMap: true, filename: file.path, presets: ["es2015", "stage-2","react"]})
    },
```

**Comment by vjau** [comment]
This was a working config, but i havn't been using it for perhaps one month.
Major change in my environnment was a changre from node 0.12 to node 6
Sadly your configuration change didn't fix the problem.

**Comment by ArtemGovorov** [comment]
What is your current `babel-core` version?

**Comment by ArtemGovorov** [comment]
Perhaps some presets from your `.baberc` get mixed into the wallaby babel config for preprocessors. You may try this:
```javascript
preprocessors: {
      '**/*.js*': file => require('babel-core').transform(
        file.content,
        {sourceMap: true, babelrc: false, filename: file.path, presets: ["es2015", "stage-2","react"]})
    },
```

**Comment by vjau** [comment]
Updating babel-core to latest version solved the problem.
Thank you for your help.
