### ISSUE TITLE
[Question] - Wallaby's Jest implementation and typescript decorators.

### ISSUE THREAD

**Issue by dsifford** [wallabyjs/public#765]
### Issue description or question

Your implementation of Jest works better than Jest by itself with typescript decorators. Is there some trickery happening behind the scenes that allows yours to handle decorators without any issues? If so, how can I get Jest to handle in a similar manner? 

Here's the context:

**Works perfect with Wallaby**
![image](https://cloud.githubusercontent.com/assets/5240018/18030904/988d9e4a-6c97-11e6-8510-a6382657ccfc.png)

**Errors out with jest-cli**

```
      ✓ should allow non-existing CSL to be set (1ms)

 FAIL  src/lib/js/reference-list/__tests__/Store-test.ts
  ● Reflist Store › should return citedIDs

    Error: [mobx] Invariant failed: @computed can only be used on getter functions, like: '@computed get myProps() { return ...; }'. It looks like it was used on a property.

      at invariant (node_modules/mobx/lib/mobx.js:2432:15)
      at /home/dsifford/repos/academic-bloggers-toolkit/development/node_modules/mobx/lib/mobx.js:224:5
      at typescriptInitializeProperty (node_modules/mobx/lib/mobx.js:2326:5)
      at Store.newDescriptor.get (node_modules/mobx/lib/mobx.js:2272:25)
      at Object.<anonymous> (src/lib/js/reference-list/__tests__/Store-test.ts:51:21)

  ● Reflist Store › should return uncited CSL

    Error: [mobx] Invariant failed: @computed can only be used on getter functions, like: '@computed get myProps() { return ...; }'. It looks like it was used on a property.

      at invariant (node_modules/mobx/lib/mobx.js:2432:15)
      at /home/dsifford/repos/academic-bloggers-toolkit/development/node_modules/mobx/lib/mobx.js:224:5
      at typescriptInitializeProperty (node_modules/mobx/lib/mobx.js:2326:5)
      at Store.newDescriptor.get (node_modules/mobx/lib/mobx.js:2272:25)
      at Object.<anonymous> (src/lib/js/reference-list/__tests__/Store-test.ts:54:21)

  ● Reflist Store › should return cited CSL

    Error: [mobx] Invariant failed: @computed can only be used on getter functions, like: '@computed get myProps() { return ...; }'. It looks like it was used on a property.

      at invariant (node_modules/mobx/lib/mobx.js:2432:15)
      at /home/dsifford/repos/academic-bloggers-toolkit/development/node_modules/mobx/lib/mobx.js:224:5
      at typescriptInitializeProperty (node_modules/mobx/lib/mobx.js:2326:5)
      at Store.newDescriptor.get (node_modules/mobx/lib/mobx.js:2272:25)
      at Object.<anonymous> (src/lib/js/reference-list/__tests__/Store-test.ts:59:21)

  ● Reflist Store › should return persistent

    Error: [mobx] Invariant failed: @computed can only be used on getter functions, like: '@computed get myProps() { return ...; }'. It looks like it was used on a property.

      at invariant (node_modules/mobx/lib/mobx.js:2432:15)
      at /home/dsifford/repos/academic-bloggers-toolkit/development/node_modules/mobx/lib/mobx.js:224:5
      at typescriptInitializeProperty (node_modules/mobx/lib/mobx.js:2326:5)
      at Store.newDescriptor.get (node_modules/mobx/lib/mobx.js:2272:25)
      at Object.<anonymous> (src/lib/js/reference-list/__tests__/Store-test.ts:62:32)
```

I'm assuming this has to do with the postprocessed code being served into Jest.

Thanks for the help, as always 😄

**Comment by ArtemGovorov** [comment]
Wallaby just uses the TypeScript version from your node modules and the `tsconfig.json` file from your project root to compile the code, there's no decorators related trickery.

The issue seems to be mobx specific, and I'm not sure why Jest itself doesn't work in your case. Perhaps whatever compiles your TypeScript for Jest has a different config? If you share a sample  project, I could have a look and try to find the difference.

**Comment by dsifford** [comment]
@ArtemGovorov Sure thing. The project in question is here: https://github.com/dsifford/academic-bloggers-toolkit

**Comment by ArtemGovorov** [comment]
As I was suggesting:

> Perhaps whatever compiles your TypeScript for Jest is using a different TypeScript config (different from tsconfig.json)?

your `scripts/jestPreprocessor.js` does:

```javascript
tsc.transpile(
                src, {
                    module: tsc.ModuleKind.CommonJS,
                    jsx: tsc.JsxEmit.React,
                },
                path, []
            )
```
however, your `tsconfig.json` contains much more settings, including
```
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
```

If I change your jestPreprocessor to use your `tsconfig.json`:
```javascript
            tsc.transpile(
                src, require('../tsconfig.json').compilerOptions,
                path, []
            )
```
and make any change to the `src/lib/js/reference-list/Store.ts` file (to clear the jest cache), then plain jest starts working ok.

**Comment by dsifford** [comment]
Ah, well that makes sense.

Thanks for the kind support (as usual). 👍
