### ISSUE TITLE
angular2 node unit test with zone-node

### ISSUE THREAD

**Issue by tamascsaba** [wallabyjs/public#814]
When I import zone-node in my node based ng2 test environment, i got the following error, without
zone-node plain unit tests runs, but angular2 has depend on global.Zone. 

The issue affected up zone.js v0.6.17 version.

```
Runtime error: TypeError: Cannot read property 'on' of undefined
    at dispatch (/home/dev/projects/foo/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2042:28)
Wed, 05 Oct 2016 08:45:52 GMT wallaby:workers Failed to map the stack to user code, entry message: TypeError: Cannot read property 'on' of undefined, stack: TypeError: Cannot read property 'on' of undefined
    at PerMessageDeflate.compress (/home/dev/.WebStorm2016.2/system/wallaby/wallaby/node_modules/ws/lib/PerMessageDeflate.js:305:37)
    at Sender.applyExtensions (/home/deb/.WebStorm2016.2/system/wallaby/wallaby/node_modules/ws/lib/Sender.js:285:54)
    at /home/dev/.WebStorm2016.2/system/wallaby/wallaby/node_modules/ws/lib/Sender.js:120:10
    at Sender.flush (/home/dev/.WebStorm2016.2/system/wallaby/wallaby/node_modules/ws/lib/Sender.js:268:3)
    at Sender.send (/home/dev/.WebStorm2016.2/system/wallaby/wallaby/node_modules/ws/lib/Sender.js:130:8)
    at WebSocket.send (/home/dev/.WebStorm2016.2/system/wallaby/wallaby/node_modules/ws/lib/WebSocket.js:267:18)
    at Object.s._send (/home/dev/.WebStorm2016.2/system/wallaby/wallaby/server.js:18:7383)
    at Object.s.started (/home/dev/.WebStorm2016.2/system/wallaby/wallaby/server.js:18:2354)
    at jasmineStarted (/home/tonyo/.WebStorm2016.2/system/wallaby/wallaby/runners/node/jasmine@2.3.4/ini

```

### Wallaby.js configuration file

```javascript
module.exports = function () {
   return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*test.ts', ignore: true}
    ],
    tests: [
      {pattern: 'src/**/*.test.ts', load: true}
    ],
    bootstrap: function (w) {
       require(w.projectCacheDir + '/src/testing/setup.js');
    },
    testFramework: 'jasmine',
    env: {
      type: 'node'
    },
    debug: true
  };
};
```

### Setup file
```typescript
import 'ts-helpers';
import 'reflect-metadata';
import 'zone.js/dist/zone-node';
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';

import {TestBed} from '@angular/core/testing';

import {
  ServerTestingModule,
  platformServerTesting
} from '@angular/platform-server/testing';

TestBed.initTestEnvironment(
  ServerTestingModule,
  platformServerTesting()
);

```

### Code editor or IDE name and version
WebStorm 2016.2.3

### OS name and version
Linux

**Comment by ArtemGovorov** [comment]
Wallaby uses websockets to communicate with test workers, websockets library is using streams, and the current version of zone.js breaks streams interface because it incorrectly patches EvenEmitter. 

Here's the issue for this in the [zone.js repo](https://github.com/angular/zone.js/issues/470), looks like the issue is being fixed so as soon as the fixed version published, it should work for you. Feel free to subscribe to the related issue. Let me know if there's still an issue after you try the zone.js version with the fix.

**Comment by ArtemGovorov** [comment]
In a meantime, you may try using a previous version of zone.js before it was broken by [this PR](https://github.com/angular/zone.js/pull/430)  or [the branch with the fix PR](https://github.com/angular/zone.js/pull/475/commits/292558f1ae1df88dd6aee2e1165e92cc8ddc471c) as your git npm dependency for zone.js.

**Comment by tamascsaba** [comment]
thx :+1:

**Comment by vespertilian** [comment]
@ArtemGovorov 

Still having a little trouble with my exact setup 58 / 140 tests passing (they all pass with Karma). I use sass which seems to work unless you compile your components in your unit tests with the Angular2 TestBed. I also use jade but this does not seem to be a problem. 

I updated the repository with sample failures:
https://github.com/Benefex/angular2-webpack-starter/tree/wallaby_failure


```javascript
describe('Card with heading', () => {
	beforeEach(() => {
		TestBed.configureTestingModule({
			declarations: [CardWithHeading],
		})
	});

    beforeEach(async(() => {
      TestBed.compileComponents();
    }));

	it('should display leftHeading and rightLinkText', () => {
		let fixture = TestBed.createComponent(CardWithHeading);
		fixture.componentInstance.leftHeading = 'awesome left heading';
		fixture.componentInstance.rightLinkText = 'right link text';
		fixture.detectChanges();
		let compiled = fixture.debugElement.nativeElement;
		expect(compiled.querySelector('span')).toHaveText('awesome left heading');
		expect(compiled.querySelector('button')).toHaveText('right link text');
	});

	it('should fire a click event', () => {
		let fixture = TestBed.createComponent(CardWithHeading);
		fixture.componentInstance.rightLinkText = 'right link text';
		fixture.detectChanges();

		let compiled = fixture.debugElement.nativeElement;
		let button = compiled.querySelector('button');

		let counter = 0;
		fixture.componentInstance.rightLinkAction.subscribe($event => {
			counter++;
		});
		button.click();
		expect((counter)).toBe(1);
	})

});
``` 

wallaby.js console 
```
src/app/card-with-heading/card-with-heading.spec.ts Card with heading should display leftHeading and rightLinkText [189 ms]

	Failed: Expected 'styles' to be an array of strings.
		at src/app/card-with-heading/card-with-heading.spec.ts:12
```

I tried adding a pre-loader but I was just getting other errors. 

Also, I think my custom marchers are not loading correctly, and I am not sure where to put them.  They are just in my src folder as matchers.spec.ts at the moment. (Not in the sample app)

```js
// this will get run before every single spec.
// use the .spec filename so karma will load this along with the other specs.
declare module jasmine {
	interface Matchers {
		toHaveText(expecteText: string): void;
		toContainText(expecteText: string): void;
		toBeDisabled(): void;
		toBeEnabled(): void;
	}
}
beforeEach(() => {
	jasmine.addMatchers({

		toHaveText: function() {
			return {
				compare: function(actual, expectedText) {
					var actualText = actual.textContent;
					return {
						pass: actualText == expectedText,
						get message() { return 'Expected ' + actualText + ' to equal ' + expectedText; }
					};
				}
			};
		},

		toContainText: function() {
			return {
				compare: function(actual, expectedText) {
					var actualText = actual.textContent;
					return {
						pass: actualText.indexOf(expectedText) > -1,
						get message() { return 'Expected ' + actualText + ' to contain text' + expectedText; }
					};
				}
			};
		},

		toBeDisabled: function () {
			return {
				compare: function(domElement) {
					var disabled = domElement.disabled;
					return {
						pass: disabled,
						get message() { return 'Expected element: ' + domElement + ' to be disabled' }
					};
				}
			};
		},

		toBeEnabled: function () {
			return {
				compare: function(domElement) {
					var enabled = !domElement.disabled;
					return {
						pass: enabled,
						get message() { return 'Expected element: ' + domElement + ' to be enabled' }
					};
				}
			};
		}
	});
});

```

**Comment by ArtemGovorov** [comment]
@vespertilian You've probably posted here by mistake, I have replied in the original issue you've raised: https://github.com/wallabyjs/public/issues/812#issuecomment-251840162
