### ISSUE TITLE
Wallaby stopped running tests in Visual Studio 2015

### ISSUE THREAD

**Issue by kasperoo** [wallabyjs/public#824]
For about 2 weeks now, my wallaby at work machine stopped working in VS2015. I've got the exact same setup at home and it works like a charm! -same code base etc.). It happened suddenly, before I even upgraded to latest wallaby plugin (which is installed now - 1.0.25, with core version v1.0.305). When I start the wallaby task, the console outputs:

    wallaby.js started
    core v1.0.305
    Wed, 12 Oct 2016 08:31:28 GMT wallaby:project Wallaby config:     C:\Git\Software\PB_Website\wallaby.conf.js

usually would load all of my tests after 5-6 seconds, but now hangs for eternity. The icon in lower right corner is spinning constantly. Debug information only returns the date.  The log file always have this error:

    2016-10-12 08:31:28Z [74] Error Wallaby.RemoteSession 0: Error caught from stderr.
    WebSocketSharp.WebSocketException: The header part of a frame cannot be read from the data source.
           at WebSocketSharp.WebSocketFrame.<>c__DisplayClass7.<ReadAsync>b__6(Byte[] header)
           at WebSocketSharp.Ext.<>c__DisplayClass6.<ReadBytesAsync>b__5(IAsyncResult ar)

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        debug: true,
        files: [
            'scripts/tests/globalSetup.js',
            "scripts/jquery-1.10.1.js",
            //... some more js files etc.
            "src/ts/viewModels/Charter.ts",
            "src/ts/tests/TestHelpers.ts"
        ],

        tests: [
           "scripts/Tests/**/*Tests.js",
           "src/ts/Tests/**/*Tests.ts"
        ],
        testFramework: "jasmine"
    };
};
```

### Code editor or IDE name and version

Visual Studio 2015

### OS name and version

Windows 10 64bit

**Comment by ArtemGovorov** [comment]
Thanks for providing the log. Could you provide a list of other extensions you have installed in your VS at work? Are there any extensions you have installed on the work machine but not on the home machine?

**Comment by kasperoo** [comment]
Sure, I have:

Code Maid (v. 1.0.50619.2)
End of the Line (v. 1.4)
File Nesting (v. 2.5.63)
Indent Guides (v. 15.0.0.0)
Web Analyzer (v. 1.7.77)
Web Essentials 2015.3 (v. 3.0.235)

There might be a difference in extensions, but nothing major, might be missing analyzer at home, will need to check later

**Comment by ArtemGovorov** [comment]
Just to confirm, you also have `Windows 10 64bit` at home?

**Comment by kasperoo** [comment]
yes, I do

**Comment by ArtemGovorov** [comment]
Could you please do this:
- open ` c:\Users\%username%\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\` folder and search for `Wallaby.config` in its subfolders (there'll be some subfolders with names like `quwo133h.t2r`, the file is in one of them),
- change the `Wallaby.config` file and replace `<add key="Wallaby.LogLevel" value="Warning"/>` with `<add key="Wallaby.LogLevel" value="All"/>`,
- restart VS, start wallaby.js,
- paste the latest (by date) log file content from `c:\%username%\Nikita Govorov\AppData\Local\Temp\.wallaby\`.

**Comment by kasperoo** [comment]
```
2016-10-12 13:29:17Z [8] Verbose Wallaby.VisualStudio.Vsix.WallabyPackage 0: Package - initialising.
2016-10-12 13:29:17Z [9] Verbose Wallaby.VsGlobalEventsListener 0: Initialising.
2016-10-12 13:29:17Z [8] Verbose Wallaby.VsGlobalEventsListener 0: Initialised.
2016-10-12 13:29:17Z [8] Verbose Wallaby.VsGlobalEventsListener 0: Listen is callled.
2016-10-12 13:29:17Z [30] Verbose Wallaby.VisualStudio.Vsix.WallabyPackage 0: Package - initialised.
2016-10-12 13:29:23Z [30] Verbose Wallaby.FailingTestsClassifierProvider 0: Initialising.
2016-10-12 13:29:23Z [31] Verbose Wallaby.FailingTestsClassifierProvider 0: Initialised.
2016-10-12 13:29:23Z [30] Verbose Wallaby.FailingTestsClassifierProvider 0: GetClassifier is calling.
2016-10-12 13:29:47Z [32] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:47Z [9] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:47Z [30] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:47Z [8] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:47Z [30] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:47Z [7] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:47Z [32] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:47Z [30] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:53Z [34] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:53Z [57] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:53Z [7] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:53Z [32] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:53Z [33] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:53Z [33] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:53Z [33] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:53Z [9] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:55Z [31] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:29:56Z [57] Verbose Wallaby.TextBufferFileBinder 0: Initialising.
2016-10-12 13:29:56Z [34] Verbose Wallaby.TextBufferFileBinder 0: Initialised.
2016-10-12 13:29:56Z [31] Verbose Wallaby.TextBufferFileBinder 0: TextViewCreated is calling.
2016-10-12 13:29:56Z [6] Verbose Wallaby.BufferBinder 0: Initialising.
2016-10-12 13:29:56Z [57] Verbose Wallaby.BufferBinder 0: Initialize is calling.
2016-10-12 13:29:56Z [34] Verbose Wallaby.BufferBinder 0: Initialisation is postponed, because runner is not active.
2016-10-12 13:29:56Z [7] Verbose Wallaby.BufferBinder 0: Initialised.
2016-10-12 13:29:56Z [9] Verbose Wallaby.TextBufferChangeListener 0: Initialising.
2016-10-12 13:29:56Z [57] Verbose Wallaby.TextBufferChangeListener 0: Initialised.
2016-10-12 13:29:56Z [7] Verbose Wallaby.TextBufferChangeListener 0: TextViewCreated is calling.
2016-10-12 13:29:56Z [9] Verbose Wallaby.BufferListener 0: Initialising.
2016-10-12 13:29:56Z [34] Verbose Wallaby.BufferListener 0: Initialisation is postponed because runner is not active or file is ignored.
2016-10-12 13:29:56Z [57] Verbose Wallaby.BufferListener 0: Initialised.
2016-10-12 13:29:56Z [9] Verbose Wallaby.IntraLineMessageTagger 0: Initialising.
2016-10-12 13:29:56Z [9] Verbose Wallaby.IntraLineMessageTagger 0: Initialised
2016-10-12 13:29:56Z [34] Verbose Wallaby.LastRunScreenshotAdornment 0: Initialising.
2016-10-12 13:29:56Z [6] Verbose Wallaby.LastRunScreenshotAdornment 0: Initialised.
2016-10-12 13:29:56Z [6] Verbose Wallaby.CoverageTaggerProvider 0: Initialising.
2016-10-12 13:29:56Z [31] Verbose Wallaby.CoverageTaggerProvider 0: Initilised.
2016-10-12 13:29:56Z [57] Verbose Wallaby.CoverageTaggerProvider 0: CreateTagger is calling.
2016-10-12 13:29:56Z [34] Verbose Wallaby.EditorCommandBinder 0: Initialising.
2016-10-12 13:29:56Z [6] Verbose Wallaby.EditorCommandBinder 0: VsTextViewCreated is calling.
2016-10-12 13:29:56Z [9] Verbose Wallaby.TextBufferFileBinder 0: TextViewCreated is calling.
2016-10-12 13:29:56Z [9] Verbose Wallaby.BufferBinder 0: Initialising.
2016-10-12 13:29:56Z [9] Verbose Wallaby.BufferBinder 0: Initialize is calling.
2016-10-12 13:29:56Z [6] Verbose Wallaby.BufferBinder 0: Initialisation is postponed, because runner is not active.
2016-10-12 13:29:56Z [6] Verbose Wallaby.BufferBinder 0: Initialised.
2016-10-12 13:29:56Z [31] Verbose Wallaby.TextBufferChangeListener 0: TextViewCreated is calling.
2016-10-12 13:29:56Z [9] Verbose Wallaby.BufferListener 0: Initialising.
2016-10-12 13:29:56Z [6] Verbose Wallaby.BufferListener 0: Initialisation is postponed because runner is not active or file is ignored.
2016-10-12 13:29:56Z [7] Verbose Wallaby.BufferListener 0: Initialised.
2016-10-12 13:29:56Z [6] Verbose Wallaby.IntraLineMessageTagger 0: Initialising.
2016-10-12 13:29:56Z [34] Verbose Wallaby.IntraLineMessageTagger 0: Initialised
2016-10-12 13:29:56Z [31] Verbose Wallaby.LastRunScreenshotAdornment 0: Initialising.
2016-10-12 13:29:56Z [31] Verbose Wallaby.LastRunScreenshotAdornment 0: Initialised.
2016-10-12 13:29:56Z [9] Verbose Wallaby.CoverageTaggerProvider 0: CreateTagger is calling.
2016-10-12 13:29:56Z [7] Verbose Wallaby.EditorCommandBinder 0: VsTextViewCreated is calling.
2016-10-12 13:29:58Z [57] Verbose Wallaby.FailingTestsClassifierProvider 0: GetClassifier is calling.
2016-10-12 13:29:58Z [75] Verbose Wallaby.SmartTaggerProvider 0: Initialising.
2016-10-12 13:29:58Z [76] Verbose Wallaby.SmartTaggerProvider 0: Initilised.
2016-10-12 13:29:58Z [73] Verbose Wallaby.SmartTaggerProvider 0: CreateTagger is calling.
2016-10-12 13:29:58Z [6] Verbose Wallaby.SmartTagger 0: Initialising.
2016-10-12 13:29:58Z [77] Verbose Wallaby.SmartTagger 0: Initialised.
2016-10-12 13:29:58Z [6] Verbose Wallaby.SmartTaggerProvider 0: CreateTagger is calling.
2016-10-12 13:29:58Z [81] Verbose Wallaby.SmartTagger 0: Initialising.
2016-10-12 13:29:58Z [81] Verbose Wallaby.SmartTagger 0: Initialised.
2016-10-12 13:30:05Z [89] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:05Z [89] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:05Z [72] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:05Z [33] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:05Z [72] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:05Z [73] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:05Z [81] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:06Z [81] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:06Z [33] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:06Z [9] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:06Z [82] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:06Z [82] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:06Z [89] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:06Z [82] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:26Z [81] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:27Z [86] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:27Z [82] Verbose Wallaby.VsSolutionEventsListener 0: OnAfterOpenProject is called.
2016-10-12 13:30:35Z [34] Verbose Wallaby.Runner 0: Start is called.
2016-10-12 13:30:35Z [72] Verbose Wallaby.StatusIndicatorLifetime 0: RunnerStarting handler is called.
2016-10-12 13:30:35Z [84] Verbose Wallaby.StatusIndicator 0: Initialising.
2016-10-12 13:30:35Z [34] Verbose Wallaby.StatusIndicator 0: Initialised.
2016-10-12 13:30:35Z [77] Verbose Wallaby.StatusIndicatorLifetime 0: StatusIndicator is inserted to visual tree.
2016-10-12 13:30:35Z [7] Verbose Wallaby.NotificationsAreaLifetime 0: RunnerStarting handler is called.
2016-10-12 13:30:35Z [34] Verbose Wallaby.AutoUpdater 0: Update is calling.
2016-10-12 13:30:35Z [30] Verbose Wallaby.RootFolderInstaller 0: Install is calling.
2016-10-12 13:30:35Z [80] Verbose Wallaby.RootFolderInstaller 0: Checking: 'C:\Users\PB-Dev4\.wallaby'.
2016-10-12 13:30:35Z [8] Verbose Wallaby.RootFolderInstaller 0: Checking: 'C:\Users\PB-Dev4\.wallaby\core'.
2016-10-12 13:30:35Z [8] Verbose Wallaby.RootFolderInstaller 0: Checking: 'C:\Users\PB-Dev4\.wallaby\dependencies'.
2016-10-12 13:30:35Z [30] Verbose Wallaby.NodeJsInstaller 0: Install is calling.
2016-10-12 13:30:35Z [77] Verbose Wallaby.NodeJsInstaller 0: Checking: 'C:\Users\PB-Dev4\.wallaby\dependencies\nodejs'.
2016-10-12 13:30:35Z [34] Verbose Wallaby.NodeJsInstaller 0: Checking: 'C:\Users\PB-Dev4\.wallaby\dependencies\nodejs\4.2.2'.
2016-10-12 13:30:35Z [78] Verbose Wallaby.NodeJsInstaller 0: Checking: 'C:\Users\PB-Dev4\.wallaby\dependencies\nodejs\4.2.2\node.exe'.
2016-10-12 13:30:35Z [80] Verbose Wallaby.PhantomJsInstaller 0: Install is calling.
2016-10-12 13:30:35Z [78] Verbose Wallaby.PhantomJsInstaller 0: Checking: 'C:\Users\PB-Dev4\.wallaby\dependencies\phantomjs'.
2016-10-12 13:30:35Z [8] Verbose Wallaby.PhantomJsInstaller 0: Checking: 'C:\Users\PB-Dev4\.wallaby\dependencies\phantomjs\2.1.1\bin\phantomjs.exe'.
2016-10-12 13:30:35Z [72] Verbose Wallaby.VersionMetadataInstaller 0: Install is calling.
2016-10-12 13:30:35Z [82] Verbose Wallaby.FileDownloader 0: Download is calling.
2016-10-12 13:30:35Z [8] Verbose Wallaby.FileDownloader 0: Download will use: 'http://update.wallabyjs.com/wallaby.json?licensed=True&expiry=07-04-2017' and 'https://s3.amazonaws.com/wallaby-downloads/wallaby.json?licensed=True&expiry=07-04-2017'.
2016-10-12 13:30:36Z [82] Verbose Wallaby.VersionMetadataResolver 0: SetMetadata is calling: '{"latestServer":["1.0.305","0.9.10"],"latestIntelliJPlugin":"1.0.76","latestVisualStudioPlugin-12":"1.0.25","latestVisualStudioPlugin-14":"1.0.25","latestAtomPlugin":"1.0.28"}'.
2016-10-12 13:30:36Z [34] Verbose Wallaby.VersionMetadataResolver 0: Plugin version is extracted: '1.0.25'.
2016-10-12 13:30:36Z [75] Verbose Wallaby.VersionMetadataResolver 0: Core versions are extracted: '1.0.305;0.9.10;'.
2016-10-12 13:30:36Z [78] Verbose Wallaby.VersionMetadataResolver 0: VersionMetadata is set.
2016-10-12 13:30:36Z [82] Verbose Wallaby.CoreInstaller 0: Install is calling.
2016-10-12 13:30:36Z [86] Verbose Wallaby.CoreInstaller 0: Resolved current plugin version: '1.0.25.0'.
2016-10-12 13:30:36Z [78] Verbose Wallaby.CoreInstaller 0: Checking: 'C:\Users\PB-Dev4\.wallaby\core' and 'C:\Users\PB-Dev4\.wallaby\core\package.json'.
2016-10-12 13:30:36Z [82] Verbose Wallaby.CoreInstaller 0: Resolved current core version: '1.0.305'.
2016-10-12 13:30:36Z [7] Verbose Wallaby.CoreInstaller 0: Resolved remote compatible core version: '1.0.305'.
2016-10-12 13:30:36Z [7] Verbose Wallaby.CoreInstaller 0: Update is not required.
2016-10-12 13:30:36Z [72] Verbose Wallaby.ExtensionInstaller 0: Install is calling.
2016-10-12 13:30:36Z [30] Verbose Wallaby.AutoUpdater 0: Update is finished.
2016-10-12 13:30:36Z [84] Verbose Wallaby.CoreProcess 0: Initialising.
2016-10-12 13:30:36Z [30] Verbose Wallaby.CoreProcess 0: Initialised: configurationPath - 'C:\Git\Software\PB_Website\wallaby.conf.js', projectCachePath - 'C:\Users\PB-Dev4\AppData\Local\Temp\.wallaby\projects\Pen0JJ780yJGi9+fkNXcBSsBYNI=\cache'.
2016-10-12 13:30:36Z [80] Verbose Wallaby.CoreProcess 0: Start is called.
2016-10-12 13:30:36Z [7] Verbose Wallaby.CoreProcess 0: Checking projectCachePath.
2016-10-12 13:30:36Z [7] Verbose Wallaby.CoreProcess 0: Searching for free port.
2016-10-12 13:30:36Z [30] Verbose Wallaby.CoreProcess 0: Free port is found: 61532.
2016-10-12 13:30:36Z [8] Verbose Wallaby.CoreProcess 0: Process is created.
2016-10-12 13:30:36Z [82] Verbose Wallaby.FailingTestsClassifierProvider 0: GetClassifier is calling.
2016-10-12 13:30:36Z [75] Verbose Wallaby.CoreProcess 0: Process is started.
2016-10-12 13:30:36Z [8] Verbose Wallaby.CoreProcess 0: Process Job is started.
2016-10-12 13:30:36Z [34] Verbose Wallaby.CoreProcess 0: Waiting for magic output.
2016-10-12 13:30:36Z [75] Verbose Wallaby.CoreProcess 0: OnOutputDataReceived is called
2016-10-12 13:30:36Z [82] Verbose Wallaby.CoreProcess 0: Receiving output data from the process: 'wallaby.js started'.
2016-10-12 13:30:36Z [78] Verbose Wallaby.CoreProcess 0: Magic output is captured.
2016-10-12 13:30:36Z [34] Verbose Wallaby.CoreProcess 0: Start is finished.
2016-10-12 13:30:36Z [30] Verbose Wallaby.CoreProcess 0: OnOutputDataReceived is called
2016-10-12 13:30:36Z [78] Verbose Wallaby.CoreProcess 0: Receiving output data from the process: 'core v1.0.305'.
2016-10-12 13:30:36Z [30] Verbose Wallaby.RemoteSession 0: Initialising: port '61532'.
2016-10-12 13:30:36Z [78] Verbose Wallaby.RemoteSession 0: Initialised.
2016-10-12 13:30:36Z [82] Verbose Wallaby.RemoteSession 0: Connect is called.
2016-10-12 13:30:36Z [30] Verbose Wallaby.RemoteSession 0: Socket is created.
2016-10-12 13:30:38Z [78] Verbose Wallaby.RemoteSession 0: Socket is connected.
2016-10-12 13:30:38Z [80] Verbose Wallaby.RemoteSession 0: Connected.
2016-10-12 13:30:38Z [80] Verbose Wallaby.Runner 0: Waiting for configuration.
2016-10-12 13:30:38Z [30] Verbose Wallaby.CoreProcess 0: OnOutputDataReceived is called
2016-10-12 13:30:38Z [75] Verbose Wallaby.CoreProcess 0: Receiving output data from the process: 'Wed, 12 Oct 2016 13:30:38 GMT wallaby:project Wallaby config: C:\Git\Software\PB_Website\wallaby.conf.js'.
2016-10-12 13:30:38Z [78] Verbose Wallaby.RemoteSession 0: OnError is called.
2016-10-12 13:30:38Z [82] Error Wallaby.RemoteSession 0: Error caught from stderr.
WebSocketSharp.WebSocketException: The header part of a frame cannot be read from the data source.
   at WebSocketSharp.WebSocketFrame.<>c__DisplayClass7.<ReadAsync>b__6(Byte[] header)
   at WebSocketSharp.Ext.<>c__DisplayClass6.<ReadBytesAsync>b__5(IAsyncResult ar)
2016-10-12 13:30:38Z [30] Verbose Wallaby.RemoteSession 0: OnClose is called.
```

**Comment by ArtemGovorov** [comment]
@kasperoo Thanks! Could you please try turning off firewall on your work machine?

**Comment by kasperoo** [comment]
@ArtemGovorov yes, that's it!! But it wasn't the Windows firewall, it's the sily antivirus called Kaseya. When I disabled it, wallaby was running like a dream. Does it need a specific port opened to work? 

Cheers

**Comment by ArtemGovorov** [comment]
@kasperoo Awesome thanks for the update! Wallaby opens a free random port every time it starts, so unfortunately there's no static port to whitelist. Wallaby core is a node.js app, so you may whitelist node.exe app to open/connect ports.

We will also investigate the option of improving the UX in cases like this.
