### ISSUE TITLE
[TypeScript, Jest] - Wallaby stopped working suddenly (ostensibly after Jest 16 update)

### ISSUE THREAD

**Issue by dsifford** [wallabyjs/public#828]
### Issue description or question

Hi there. I recently noticed that wallaby stopped working at some point in the last 7-14 days in one of my repos. I'm not sure if there were changes in the wallaby config API or if Jest 16 screwed something up (from looking at other issues it looks like the latter is not the case).

Here's the repo if you'd like to see what I have going on: https://github.com/dsifford/academic-bloggers-toolkit

### Wallaby.js configuration file

```javascript
module.exports = {
    files: [
        'src/**/*.{tsx,ts}',
        'types/**/*.d.ts',
        './package.json',
        {
            pattern: 'scripts/*.js',
            instrument: false,
        },
        '!src/lib/js/utils/Externals.ts',
        '!src/**/__tests__/*',
        '!src/**/index.{ts,tsx}',
        '!src/lib/js/Frontend.ts',
        '!src/lib/js/utils/TinymceFunctions.ts',
    ],
    tests: [
        'src/**/__tests__/*-test.{ts,tsx}',
    ],
    env: {
        type: 'node',
        runner: 'node',
    },
    testFramework: 'jest',
    setup(wallaby) {
        wallaby.testFramework.configure(require('./package.json').jest); // eslint-disable-line
    },
};
```

### Code editor or IDE name and version

Atom...

```sh
$ atom --version
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

### OS name and version

Arch Linux

-----

Thanks so much in advance for the help. 😄

**Comment by ArtemGovorov** [comment]
I have sent you 2 PRs: https://github.com/dsifford/academic-bloggers-toolkit/pull/190 and https://github.com/dsifford/academic-bloggers-toolkit/pull/191. For some reason some source files were excluded in your wallaby config, causing module not find errors. After removing the exclusions, I found another issue with 
```javascript
jest.unmock('../ReferenceList.tsx');
jest.unmock('../../Store.ts');
```
Using file extensions is not required and breaks wallaby jest integration (you're not using file extensions anywhere else anyway).

P.S. I have also seen a transient issue with API tests (something about bad network request), but the issue shows up when running jest from CLI.

**Comment by dsifford** [comment]
@ArtemGovorov Wow thanks so much! You went above and beyond, as usual 😄 

Good to know Re: file extensions issue. Those unmocks were probably added using code completion or something because I've never added extensions purposefully!

Thanks again!

**Comment by dsifford** [comment]
Actually -- I'm working on a feature branch which is a bit different than the master branch right now. I made the necessary changes to that feature branch described in the pull requests and it's still saying `0 failing tests, 0 passing` in the panel in atom. 

Any ideas?

Here's that branch: https://github.com/dsifford/academic-bloggers-toolkit/tree/next

(I'm pushing the changes now so the branch will be caught up to this exact moment on github).

Thanks so much.

**Comment by ArtemGovorov** [comment]
Got the branch, did `npm install` and everything seems to be working for me (`0 failing tests, 144 passing`):
<img width="792" alt="screen shot 2016-10-15 at 10 00 23 am" src="https://cloud.githubusercontent.com/assets/979966/19405711/3d37cea6-92be-11e6-9447-c1d2395faceb.png">

**Comment by dsifford** [comment]
Super strange! Possibly a conflict with another package?

Here's my list:

```
Community Packages (79) /home/dsifford/.atom/packages
├── Stylus@3.1.0
├── Sublime-Style-Column-Selection@1.7.2
├── advanced-open-file@0.16.4
├── atom-alignment@0.12.1
├── atom-beautify@0.29.13
├── atom-typescript@10.1.9
├── atom-wallaby@1.0.11
├── autocomplete-clang@0.10.0
├── autocomplete-go@1.3.0
├── autocomplete-paths@1.0.2
├── builder-go@1.0.1
├── code-peek@1.4.11
├── docblockr@0.8.7
├── editorconfig@1.4.1
├── emmet@2.4.3
├── environment@1.2.0
├── exception-reporting@0.40.0
├── git-time-machine@1.5.3
├── go-config@1.2.4
├── go-debug@0.1.22
├── go-get@2.1.1
├── go-plus@4.3.2
├── godoc@1.1.1
├── gofmt@1.2.0
├── gometalinter-linter@1.2.2
├── gorename@1.1.0
├── gpp-compiler@3.0.7
├── highlight-selected@0.11.2
├── hyperclick@0.0.39
├── hyperclick-php@0.2.1
├── increment-me@0.4.1
├── js-hyperclick@1.9.0
├── language-babel@2.44.1
├── language-docker@1.1.7
├── language-jade@0.7.2
├── language-nginx@0.6.2
├── language-rust@0.4.7
├── linter@1.11.18
├── linter-clang@3.4.4
├── linter-eslint@8.0.0
├── linter-golinter@1.2.1
├── linter-js-yaml@1.2.5
├── linter-jsonlint@1.3.0
├── linter-php@1.3.1
├── linter-phpmd@1.5.2
├── linter-pylama@0.7.6
├── linter-rust@0.6.0
├── linter-shellcheck@1.4.1
├── linter-stylint@2.2.5
├── linter-tslint@0.11.1
├── markdown-scroll-sync@2.1.2
├── merge-conflicts@1.4.4
├── metrics@1.0.0
├── minimap@4.25.0
├── minimap-bookmarks@0.4.2
├── minimap-cursorline@0.2.0
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.4.0
├── minimap-linter@1.6.0
├── minimap-split-diff@0.3.2
├── navigator-go@1.1.3
├── nerd-treeview@0.4.2
├── package-sync@1.1.0
├── pdf-view@0.50.0
├── pigments@0.37.0
├── project-plus@0.9.0
├── qolor@0.4.0
├── racer@0.20.0
├── script@3.10.1
├── set-syntax@0.3.2
├── sort-lines@0.14.0
├── split-diff@1.0.5
├── sync-settings@0.7.2
├── tester-go@2.0.2
├── todo@0.6.0
├── tree-view-autoresize@1.2.0
├── turbo-javascript@1.4.0
├── vim-mode-plus@0.60.0
└── vim-mode-plus-move-selected-text@0.6.1
```

**Comment by ArtemGovorov** [comment]
It's very unlikely, the issue seems to be in the core, not the editor integration.
Is wallaby.js in the `master` branch currently working for you? Try doing a clean `npm install` in the `next` branch, perhaps there's some issue with installed packages. if it doesn't help, try [setting `debug: true`](https://wallabyjs.com/docs/intro/get-started-atom.html#troubleshooting) and paste the output from the Wallaby Console in Atom dev tools.

**Comment by dsifford** [comment]
Will do. Thanks so much again. Seriously, can't stress how grateful I am for your help.

Give me a few and I'll report back.

**Comment by dsifford** [comment]
@ArtemGovorov Sorry for the delay. Still no luck after a clean install of my node modules.

There's thousands and thousands of lines of debug messages, but I think these are probably the one's you'll be interested in:

```
Wallaby Console: Sat, 15 Oct 2016 01:24:30 GMT wallaby:nodeRunner Preparing sandbox [worker #5, session #tl2md]
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:30 GMT wallaby:workers Starting run worker instance #5
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:31 GMT wallaby:nodeRunner Error in worker: Error: Cannot find module 'Q'
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Function.Module._resolveFilename (module.js:440:15)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Function.Module._load (module.js:388:25)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.require (module.js:468:17)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.s.require (/home/dsifford/.atom/packages/atom-wallaby/wallaby/server.js:18:27449)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at require (internal/module.js:20:19)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Object.<anonymous> (/home/dsifford/.atom/packages/atom-wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:54)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module._compile (module.js:541:32)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Object.Module._extensions..js (module.js:550:10)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.load (module.js:458:32)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at tryModuleLoad (module.js:417:12)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:31 GMT wallaby:nodeRunner Error in worker: Error: Cannot find module 'Q'
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Function.Module._resolveFilename (module.js:440:15)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Function.Module._load (module.js:388:25)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.require (module.js:468:17)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.s.require (/home/dsifford/.atom/packages/atom-wallaby/wallaby/server.js:18:27449)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at require (internal/module.js:20:19)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Object.<anonymous> (/home/dsifford/.atom/packages/atom-wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:54)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module._compile (module.js:541:32)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Object.Module._extensions..js (module.js:550:10)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.load (module.js:458:32)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at tryModuleLoad (module.js:417:12)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:31 GMT wallaby:nodeRunner Error in worker: Error: Cannot find module 'Q'
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Function.Module._resolveFilename (module.js:440:15)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Function.Module._load (module.js:388:25)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.require (module.js:468:17)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.s.require (/home/dsifford/.atom/packages/atom-wallaby/wallaby/server.js:18:27449)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at require (internal/module.js:20:19)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Object.<anonymous> (/home/dsifford/.atom/packages/atom-wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:54)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module._compile (module.js:541:32)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Object.Module._extensions..js (module.js:550:10)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.load (module.js:458:32)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at tryModuleLoad (module.js:417:12)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:31 GMT wallaby:nodeRunner Error in worker: Error: Cannot find module 'Q'
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Function.Module._resolveFilename (module.js:440:15)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Function.Module._load (module.js:388:25)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.require (module.js:468:17)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.s.require (/home/dsifford/.atom/packages/atom-wallaby/wallaby/server.js:18:27449)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at require (internal/module.js:20:19)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Object.<anonymous> (/home/dsifford/.atom/packages/atom-wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:54)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module._compile (module.js:541:32)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Object.Module._extensions..js (module.js:550:10)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.load (module.js:458:32)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at tryModuleLoad (module.js:417:12)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:31 GMT wallaby:nodeRunner Error in worker: Error: Cannot find module 'Q'
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Function.Module._resolveFilename (module.js:440:15)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Function.Module._load (module.js:388:25)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.require (module.js:468:17)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.s.require (/home/dsifford/.atom/packages/atom-wallaby/wallaby/server.js:18:27449)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at require (internal/module.js:20:19)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Object.<anonymous> (/home/dsifford/.atom/packages/atom-wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:54)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module._compile (module.js:541:32)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Object.Module._extensions..js (module.js:550:10)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.load (module.js:458:32)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at tryModuleLoad (module.js:417:12)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:31 GMT wallaby:nodeRunner Error in worker: Error: Cannot find module 'Q'
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Function.Module._resolveFilename (module.js:440:15)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Function.Module._load (module.js:388:25)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.require (module.js:468:17)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.s.require (/home/dsifford/.atom/packages/atom-wallaby/wallaby/server.js:18:27449)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at require (internal/module.js:20:19)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Object.<anonymous> (/home/dsifford/.atom/packages/atom-wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:54)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module._compile (module.js:541:32)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Object.Module._extensions..js (module.js:550:10)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at Module.load (module.js:458:32)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:     at tryModuleLoad (module.js:417:12)
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:40 GMT wallaby:workers Worker is not created in time, recycling it
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:40 GMT wallaby:project Test run cancelled, re-queueing run data
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:40 GMT wallaby:project Test run finished
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:40 GMT wallaby:project Test run data re-queued
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:40 GMT wallaby:project Running postprocessor
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:40 GMT wallaby:postprocessor TypeScript language service re-created because some tracked files were added or deleted
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/Frontend.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/components/Spinner.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/components/ToggleSwitch.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/reference-list/API.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/reference-list/Store.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/reference-list/components/Card.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/reference-list/components/ItemList.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/reference-list/components/Menu.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/reference-list/components/PanelButton.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/reference-list/components/ReferenceList.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/reference-list/index.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/tinymce/components/import-window/ImportWindow.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/tinymce/components/import-window/index.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/tinymce/components/pubmed-window/Paginate.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/tinymce/components/pubmed-window/PubmedWindow.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/tinymce/components/pubmed-window/ResultList.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/tinymce/components/pubmed-window/index.js
/home/dsifford/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console: Sat, 15 Oct 2016 01:24:41 GMT wallaby:project Preparing to process src/lib/js/tinymce/components/reference-window/components/Butto
```

Let me know if there's anything else I might be able to help with.

**Comment by ArtemGovorov** [comment]
@dsifford Awesome, thanks for the log, it's very helpful. I believe I fixed the issue in core v1.0.306. You may wait for an automatic update or [force the update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
Please let me know if it fixes the issue for you.

**Comment by dsifford** [comment]
@ArtemGovorov Sorry for the delay. Yep, the issue is all fixed!

I noticed a completely different issue now though related to coverage reporting. Let me know if you'd like me to create a separate issue and I will.

In the meantime: The gist of the issue is, `instrument: false` isn't working. Coverage for the files is still being reported in wallabyjs.com/app

**Comment by ArtemGovorov** [comment]
@dsifford Awesome, thanks for checking. Yes, please create a new issue for the coverage problem, share the repo (if it's different from the one in this issue), the branch to look at and the file with `instrument: false` and reported coverage.
