### ISSUE TITLE
SyntaxError: Unexpected token )​

### ISSUE THREAD

**Issue by baldore** [wallabyjs/public#862]
### Issue description or question

Hi! I'm using https://github.com/mxstbr/react-boilerplate and I would like to add wallaby.config.js to it, but I can't even pass the simple configuration since I'm receiving a syntax error in Lodash (No idea why.)

### Error

```
[Error] ​​/home/baldore/own-projects/video-repeater-react/node_modules/wallaby-webpack/node_modules/lodash/index.js:3818​​
[Error] ​​});​​
[Error] ​​ ^​​
[Error] ​​SyntaxError: Unexpected token )​​
[Error] ​​  at Object.exports.runInThisContext (vm.js:76:16)​​
[Error] ​​  at Module.n._compile (/home/baldore/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.30/wallaby/server.js:15:9700)​​
[Error] ​​  at Module.s.require (/home/baldore/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.30/wallaby/server.js:18:29197)​​
[Error] ​​  at require (internal/module.js:20:19)​​
[Error] ​​  at Object.<anonymous> (/home/baldore/own-projects/video-repeater-react/node_modules/wallaby-webpack/index.js:4:9)​​
[Error] ​​  at Module.n._compile (/home/baldore/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.30/wallaby/server.js:15:9700)​​
[Error] ​​  at Module.s.require (/home/baldore/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.30/wallaby/server.js:18:29197)​​
[Error] ​​  at require (internal/module.js:20:19)​​
[Error] ​​  at Object.<anonymous> (/home/baldore/own-projects/video-repeater-react/wallaby.config.js:3:24)​
```

### Wallaby.js configuration file

```javascript
'use strict'; //eslint-disable-line

const wallabyWebpack = require('wallaby-webpack');
const webpackConfig = require('./internals/webpack/webpack.test.babel');
const webpackPostprocessor = wallabyWebpack(webpackConfig);

module.exports = (wallaby) => ({
  files: [
    { pattern: 'app/**/*.js', load: false },
  ],

  tests: [
    { pattern: 'app/**/*.test.js', load: false },
  ],

  env: {
    kind: 'electron',
  },

  compilers: {
    'app/**/*.js': wallaby.compilers.babel(),
  },

  postprocessor: webpackPostprocessor,

  setup() {
    window.__moduleBundler.loadTests(); // eslint-disable-line
  },
});
```

### Webpack Configuration

Using the one defined in the boilerplate for tests.

```javascript
/**
 * TEST WEBPACK CONFIGURATION
 */

const webpack = require('webpack');
const modules = [
  'app',
  'node_modules',
];

module.exports = {
  devtool: 'inline-source-map',
  module: {
    // Some libraries don't like being run through babel.
    // If they gripe, put them here.
    noParse: [
      /node_modules(\\|\/)sinon/,
      /node_modules(\\|\/)acorn/,
    ],
    loaders: [
      { test: /\.json$/, loader: 'json-loader' },
      { test: /\.css$/, loader: 'null-loader' },

      // sinon.js--aliased for enzyme--expects/requires global vars.
      // imports-loader allows for global vars to be injected into the module.
      // See https://github.com/webpack/webpack/issues/304
      { test: /sinon(\\|\/)pkg(\\|\/)sinon\.js/,
        loader: 'imports?define=>false,require=>false',
      },
      { test: /\.js$/,
        loader: 'babel',
        exclude: [/node_modules/],
      },
      { test: /\.jpe?g$|\.gif$|\.png$|\.svg$/i,
        loader: 'null-loader',
      },
    ],
  },

  plugins: [

    // Always expose NODE_ENV to webpack, in order to use `process.env.NODE_ENV`
    // inside your code for any environment checks; UglifyJS will automatically
    // drop any unreachable code.
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV),
      },
    })],

  // Some node_modules pull in Node-specific dependencies.
  // Since we're running in a browser we have to stub them out. See:
  // https://webpack.github.io/docs/configuration.html#node
  // https://github.com/webpack/node-libs-browser/tree/master/mock
  // https://github.com/webpack/jade-loader/issues/8#issuecomment-55568520
  node: {
    fs: 'empty',
    child_process: 'empty',
    net: 'empty',
    tls: 'empty',
  },

  // required for enzyme to work properly
  externals: {
    jsdom: 'window',
    'react/addons': true,
    'react/lib/ExecutionEnvironment': true,
    'react/lib/ReactContext': 'window',
  },
  resolve: {
    modules,
    alias: {
      // required for enzyme to work properly
      sinon: 'sinon/pkg/sinon',
    },
  },
};
```

### Code editor or IDE name and version
Webstorm and Visual Studio Code

### OS name and version

Linux

**Comment by baldore** [comment]
Sorry, looks like it was a problem with the package installation.

**Comment by ArtemGovorov** [comment]
No worries, thanks for the update!
