### ISSUE TITLE
SyntaxError: Unexpected token ! in JSON at position 0

### ISSUE THREAD

**Issue by jbrey** [wallabyjs/public#863]
### Issue description or question

Because I wasn't able to use wallaby waiting for #124 to be fixed, I wanted to upgrade and see if it works better now with my env. but I have another issue which prevents wallaby to start.

Here are the different tests I made so far:

1. install last IntelliJ plugin version (**1.0.78**)
2. upgrade nodeJS path to v6.9.0 in wallaby runner configuration
3. apply workaround and configs given in #726 & #541 
4. test with different wallaby versions

Each time, wallaby throws a syntax error when starting, here are the detailed results:

**Wallaby error until 1.0.78 – – with default node (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\node_v4.2.2\node.exe):**
```
wallaby.js started
core v1.0.319
SyntaxError: Unexpected token !
    at Object.parse (native)
    at new SourceMapConsumer (C:\Data\git\gitlab\tnt\tnt-ui-frontend\node_modules\source-map\lib\source-map-consumer.js:17:22)
    at mapSourcePosition (C:\Data\git\gitlab\tnt\tnt-ui-frontend\node_modules\source-map-support\source-map-support.js:164:14)
    at wrapCallSite (C:\Data\git\gitlab\tnt\tnt-ui-frontend\node_modules\source-map-support\source-map-support.js:331:20)
    at C:\Data\git\gitlab\tnt\tnt-ui-frontend\node_modules\source-map-support\source-map-support.js:366:26
    at Array.map (native)
    at Function.prepareStackTrace (C:\Data\git\gitlab\tnt\tnt-ui-frontend\node_modules\source-map-support\source-map-support.js:365:24)
    at Object.i.receive (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\server.js:14:1565)
    at WebSocket.<anonymous> (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\server.js:19:65)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\WebSocket.js:841:10)
    at C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:536:18
    at Receiver.applyExtensions (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:371:5)
    at C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:508:14
    at Receiver.flush (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:347:3)
    at Receiver.opcodes.1.finish (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:541:12)
    at Receiver.expectHandler (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:493:33)
    at Receiver.add (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:103:24)
    at Socket.realHandler (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\WebSocket.js:825:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Wallaby error until 1.0.58 – with node v6.9.0:**

```
D:\Program Files\nodejs\node.exe: bad option: --harmony_arrow_functions

Process finished with exit code 9
```

**Wallaby error 1.0.59->1.0.78 – with node V6.9.0:**

```
wallaby.js started
core v1.0.319
SyntaxError: Unexpected token ! in JSON at position 0
    at Object.parse (native)
    at new SourceMapConsumer (C:\Data\git\gitlab\tnt\tnt-ui-frontend\node_modules\source-map\lib\source-map-consumer.js:17:22)
    at mapSourcePosition (C:\Data\git\gitlab\tnt\tnt-ui-frontend\node_modules\source-map-support\source-map-support.js:164:14)
    at wrapCallSite (C:\Data\git\gitlab\tnt\tnt-ui-frontend\node_modules\source-map-support\source-map-support.js:331:20)
    at C:\Data\git\gitlab\tnt\tnt-ui-frontend\node_modules\source-map-support\source-map-support.js:366:26
    at Array.map (native)
    at Function.prepareStackTrace (C:\Data\git\gitlab\tnt\tnt-ui-frontend\node_modules\source-map-support\source-map-support.js:365:24)
    at SyntaxError.get stack [as stack] (native)
    at Object.i.receive (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\server.js:14:1565)
    at WebSocket.<anonymous> (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\server.js:19:65)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\WebSocket.js:841:10)
    at C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:536:18
    at Receiver.applyExtensions (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:371:5)
    at C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:508:14
    at Receiver.flush (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:347:3)
    at Receiver.finish (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:541:12)
    at Receiver.expectHandler (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:493:33)
    at Receiver.add (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\Receiver.js:103:24)
    at Socket.realHandler (C:\Users\jbrey\.IntelliJIdea2016.1\system\wallaby\wallaby\node_modules\ws\lib\WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TCP.onread (net.js:548:20)
```

### Wallaby.js configuration file

```javascript
import paths from './paths';
import wallabyWebpack from 'wallaby-webpack';

// https://github.com/wallabyjs/public/issues/726
var Module              = require( 'module' ).Module;
var modulePrototype     = Module.prototype;
var originalRequire     = modulePrototype.require;
modulePrototype.require = function ( filePath ) {
	if ( filePath === 'source-map-support' ) {
		return { install: () => {} };
	}
	return originalRequire.call( this, filePath );
};

const getWebpackConfig = require( './webpack/webpack.config' );
const webpackConfig = getWebpackConfig( false, true, false );
delete webpackConfig.devtool;
delete webpackConfig.output;
webpackConfig.module.loaders = webpackConfig.module.loaders.filter( ( l ) => {
	return l.loader !== 'babel';
} );

// delete webpackConfig.module.preLoaders;
// delete webpackConfig.module.loaders;

modulePrototype.require = originalRequire;
// ------

const config               = {
	...webpackConfig,
	debug:         false,
	// devtool:       undefined,
	output:        {},
	entryPatterns: [
		`${paths.unitSpecsSrc}/jasmine-init.js`,
		`${paths.unitSpecsSrc}/**/*.spec.js`
		`${paths.unitSpecsSrc}/**/*.spec.jsx`
	]
};
const wallabyPostprocessor = wallabyWebpack( config );

export default module.exports = ( wallaby ) => {
	return {
		files: [
			{ pattern: 'node_modules/sinon/pkg/sinon.js', instrument: false },
			{ pattern: 'node_modules/jasmine-sinon/lib/jasmine-sinon.js', instrument: false, load: true },
			// polyfills
			{ pattern: 'node_modules/babel-polyfill/browser.js', instrument: false },

			{ pattern: `${paths.root}/**/*.scss`, load: false, instrument: false },
			{ pattern: `${paths.root}/**/*.js`, load: false },
			{ pattern: `${paths.root}/**/*.jsx`, load: false },
			{ pattern: `${paths.unitSpecsSrc}/test-utils/**/*.js`, load: false, instrument: false }, // utils
			{ pattern: `${paths.unitSpecsSrc}/test-utils/**/*.jsx`, load: false, instrument: false } // utils
		],

		tests: [
			{ pattern: 'init.js', load: true },
			{ pattern: `${paths.unitSpecsSrc}/**/*.spec.js`, load: false },
			{ pattern: `${paths.unitSpecsSrc}/**/*.spec.jsx`, load: false }
		],

		compilers: {
			'**/*.js':  wallaby.compilers.babel( { babel: require( 'babel-core' ), babelrc: true } ),
			'**/*.jsx': wallaby.compilers.babel( { babel: require( 'babel-core' ), babelrc: true } )
		},

		postprocessor: wallabyPostprocessor,

		testFramework: 'jasmine',

		setup: () => {
			window.__moduleBundler.loadTests();
		}
	};
};
```

I've tried also different alternatives with loaders, delete it from original webpack config or filter babel loader, ...

Note that this conf is loaded from:

```javascript
require( 'babel-core/register' );
process.env.NODE_ENV = 'test';
module.exports = require( './build/wallaby.conf.js' );
```

### Code editor or IDE name and version

IntelliJ IDEA 2016.1

### OS name and version

Windows 7 enterprise sp 1

### App & wallaby env

- node v6.9.0
- es6/7 + react + redux
- jasmine / sinon / enzyme
- webpack
- sass
- some lazy loaded files

**Comment by ArtemGovorov** [comment]
This looks like the exact same issue as in https://github.com/wallabyjs/public/issues/726.

The `source-map-support` module is used in one of the packages that is used in `./webpack/webpack.config` or `./paths` and loading it breaks wallaby, it doesn't even start.

The workaround you have in place (with patching the package `install` function) should help. Perhaps the problematic module gets loaded before the workaround is applied, maybe from `./paths` file that gets imported before the workaround? 

Try moving the workaround code to the root config file:
```javascript
require( 'babel-core/register' );
process.env.NODE_ENV = 'test';

// https://github.com/wallabyjs/public/issues/726
var Module              = require( 'module' ).Module;
var modulePrototype     = Module.prototype;
var originalRequire     = modulePrototype.require;
modulePrototype.require = function ( filePath ) {
	if ( filePath === 'source-map-support' ) {
		return { install: () => {} };
	}
	return originalRequire.call( this, filePath );
};

module.exports = require( './build/wallaby.conf.js' );
```

If it doesn't help, try editing the `./node_modules/source-map-support/source-map-support.js` file and adding:
```javascript
exports.install = function(options) {
  throw new Error('Who is calling it');
  ...
}
```
to see the error stack of what module is calling it and why does it happen before the monkey-patch for the `require` is applied.

Unrelated note, this: 
```
{ pattern: 'init.js', load: true },
```
in your `tests` list is probably not going to work if it's some setup code for your tests. The `tests` list should only contain files with tests, so you'll need to move the file to the `files` list, and if there's some code in there that webpack should handle (like imports of other files/modules, etc.) then it should also have the `load: false` set and [be listed in the `entryPatterns`](https://wallabyjs.com/docs/integration/webpack.html#entry-patterns).

**Comment by jbrey** [comment]
Thanks for the quick answer.

I found the problem with your install patch advice ... it was because of the babel-core/register.

The fix is therefore, in my root file:
```javascript
// https://github.com/wallabyjs/public/issues/726
var Module              = require( 'module' ).Module;
var modulePrototype     = Module.prototype;
var originalRequire     = modulePrototype.require;
modulePrototype.require = function ( filePath ) {
	if ( filePath === 'source-map-support' ) {
		return { install: () => {} };
	}
	return originalRequire.call( this, filePath );
};

require( 'babel-core/register' );

modulePrototype.require = originalRequire;

process.env.NODE_ENV = 'test';
module.exports = require( './build/wallaby.conf.js' );
```
I have other problems now to run my tests but I'll open other issues after more investigation if necessary, you can close the issue. Thanks

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
