### ISSUE TITLE
ENOENT: no such file or directory, unlink (WebStrom)

### ISSUE THREAD

**Issue by narthollis** [wallabyjs/public#873]
### Issue description or question

I am seeing `ENOENT: no such file or directory, unlink` in my Failing Tests console, and when I enable debug to determine what is happening, my Wallaby Console is being spammed with

This is an issue I have been experiencing on and off for the past week.

```
Thu, 17 Nov 2016 05:40:27 GMT wallaby:project Preparing to process src/utilities/AuthObject.jsx
Thu, 17 Nov 2016 05:40:27 GMT wallaby:processor Running 1 processor(s) for src/utilities/AuthObject.jsx
Thu, 17 Nov 2016 05:40:27 GMT wallaby:processor Finished running one processor for src/utilities/AuthObject.jsx
Thu, 17 Nov 2016 05:40:27 GMT wallaby:project Processing compiled src/utilities/AuthObject.jsx
Thu, 17 Nov 2016 05:40:27 GMT wallaby:project Instrumenting src/utilities/AuthObject.jsx, via process pool: false
Thu, 17 Nov 2016 05:40:27 GMT wallaby:project No preprocessors configured for src/utilities/AuthObject.jsx
Thu, 17 Nov 2016 05:40:27 GMT wallaby:project Writing to disk and caching processed file src/utilities/AuthObject.jsx
Thu, 17 Nov 2016 05:40:27 GMT wallaby:project File src/utilities/AuthObject.jsx changes saved, store ts: 1479342615950, change ts: 1479361227388
Thu, 17 Nov 2016 05:40:27 GMT wallaby:project File src/utilities/AuthObject.jsx changes are patches only: false
```

During the initial startup I see the following error in the debuging output

```
Thu, 17 Nov 2016 05:42:37 GMT wallaby:project Error: ENOENT: no such file or directory, unlink 'C:\Users\narthollis\.WebStorm2016.3\system\wallaby\projects\c94ac82c79b5dfe6\instrumented\src\utilities\AuthObject.jsx'
  at Error (native)
From previous event:
  at EventEmitter.h.unlinkFilePromise [as _unlinkFilePromise] (C:\Users\narthollis\.WebStorm2016.3\system\wallaby\wallaby\server.js:19:346)
  at C:\Users\narthollis\.WebStorm2016.3\system\wallaby\wallaby\server.js:16:29174
  at baseFor (C:\Users\narthollis\.WebStorm2016.3\system\wallaby\wallaby\node_modules\lodash\index.js:1971:13)
  at baseForOwn (C:\Users\narthollis\.WebStorm2016.3\system\wallaby\wallaby\node_modules\lodash\index.js:2025:14)
  at baseEach (C:\Users\narthollis\.WebStorm2016.3\system\wallaby\wallaby\node_modules\lodash\index.js:1814:16)
  at Function.forEach (C:\Users\narthollis\.WebStorm2016.3\system\wallaby\wallaby\node_modules\lodash\index.js:5701:11)
  at EventEmitter._.extend._processChangedQueue (C:\Users\narthollis\.WebStorm2016.3\system\wallaby\wallaby\server.js:16:28468)
  at [object Object]._onTimeout (C:\Users\narthollis\.WebStorm2016.3\system\wallaby\wallaby\server.js:16:23712)
  at Timer.listOnTimeout (timers.js:92:15)
```

### Wallaby.js configuration file

```javascript
process.env.NODE_ENV = 'test';


// eslint-disable-next-line func-names
module.exports = function (wallaby) {
    return {
        files: [
            { pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false },
            'defaultData/**/*.json',
            'src/**/*.js*',
            '!src/**/*.test.js*',
            '!src/**/*.fixture.js',

            { pattern: 'test/*.js', instrument: false },
        ],

        tests: [
            'src/**/*.test.js',
            'src/**/*.test.jsx',
        ],

        compilers: {
            '**/*.js': wallaby.compilers.babel(),
            '**/*.jsx': wallaby.compilers.babel(),
        },

        env: {
            type: 'node',
            runner: 'node',
            params: {
                runner: '--harmony',
            },
        },

        testFramework: 'jest',

        setup: (w) => {
            w.testFramework.configure({
                setupTestFrameworkScriptFile: '<rootDir>/test/setup-before-after.js',
                moduleFileExtensions: ['js', 'json', 'jsx', 'node'],
                moduleNameMapper: {
                    '^.+\\.(css|scss|sass)$': '<rootDir>/test/styleMock.js',
                    '^.+\\.(gif|ttf|eot|svg)$': '<rootDir>/test/fileMock.js',
                },
                // testRegex: '/__tests__/.*|\\.(test|spec)\\.(js|jsx)$',
            });
        },

        debug: true,
    };
};
```

### Code editor or IDE name and version

WebStorm 2016.3

### OS name and version

Windows 7

**Comment by ArtemGovorov** [comment]
Hmm, interesting one.
- Does it only report `src\utilities\AuthObject.jsx` or different files?
- How frequently does the issue show up? Like almost every time, once an hour/once a day?
- Are you just editing the `src/utilities/AuthObject.jsx` file and the issue `ENOENT: no such file or directory, unlink` starts to show up or it only shows up during the initial start up?
- Are you able to reproduce it [on this project of yours](https://github.com/narthollis/minimal_jest_mock)?

**Comment by narthollis** [comment]
The same project works properly when Wallaby is run from Atom

**Comment by narthollis** [comment]
* It mostly remember it reporting AuthObject.jsx.
* It feels like it is more normal to get this error than not - though as I haven't been working on as much tested code as I would like I haven't been starting Wallaby that much. 
* It tends to happen on startup before I begin editing any files.
* I am yet to see this issue happen in that test repo.

On the note of if it happens after editing, I cut all of the content in AuthObject.jsx, saved the file, then pasted the content back in and saved again. This appears to have fixed the problem currently.
