### ISSUE TITLE
Typescript & webpack compile importing modules

### ISSUE THREAD

**Issue by risonipli** [wallabyjs/public#891]
### Issue description or question
Hi again! Is it possible to make wallby's typescript compiler to compile typescript file marked as main in package.json? It works fine with webpack's ts-loader.

```json
{
  "name": "u-workflow.utils",
  "main": "src/index.ts"
}
```

components/src/index.ts file
```typescript
import * as angular from 'angular';

import 'u-workflow.utils';

//...
```

Got error message:
```
​​SyntaxError: Use of reserved word 'import'​​
​​at http://localhost:62628/__modules/10.js?1480695948823:1​​
​​Error​​
​​  at /Users/artem/code/ui-modules/node_modules/webpack/lib/Compilation.js:229:38​​
​​  at onDoneResolving (/Users/artem/code/ui-modules/node_modules/webpack/lib/NormalModuleFactory.js:29:20)​​
​​  at /Users/artem/code/ui-modules/node_modules/webpack/lib/NormalModuleFactory.js:85:20​​
​​  at /Users/artem/code/ui-modules/node_modules/webpack/node_modules/async/lib/async.js:726:13​​
​​  at /Users/artem/code/ui-modules/node_modules/webpack/node_modules/async/lib/async.js:52:16​​
​​  at done (/Users/artem/code/ui-modules/node_modules/webpack/node_modules/async/lib/async.js:241:17)​​
​​  at /Users/artem/code/ui-modules/node_modules/webpack/node_modules/async/lib/async.js:44:16​​
​​  at /Users/artem/code/ui-modules/node_modules/webpack/node_modules/async/lib/async.js:723:17​​
​​  at /Users/artem/code/ui-modules/node_modules/webpack/node_modules/async/lib/async.js:167:37​​
​​  at /Users/artem/code/ui-modules/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19​​
​​  at onResolved (/Users/artem/code/ui-modules/node_modules/enhanced-resolve/lib/Resolver.js:38:18)​​
​​  at /Users/artem/code/ui-modules/node_modules/enhanced-resolve/lib/Resolver.js:127:10​​
​​  at /Users/artem/code/ui-modules/node_modules/enhanced-resolve/lib/Resolver.js:191:15​​
​​  at applyPluginsParallelBailResult.createInnerCallback.log (/Users/artem/code/ui-modules/node_modules/enhanced-resolve/lib/Resolver.js:110:4)​​
​​  at loggingCallbackWrapper (/Users/artem/code/ui-modules/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)​​
​​  at /Users/artem/code/ui-modules/node_modules/tapable/lib/Tapable.js:134:6​​
​​  at Resolver.<anonymous> (/Users/artem/code/ui-modules/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)​​
​​  at Storage.finished (/Users/artem/code/ui-modules/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)​​
​​  at ReadFileContext.callback (/Users/artem/code/ui-modules/node_modules/graceful-fs/graceful-fs.js:78:16)​​
​​  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:335:13)​​
```

And if open 'http://localhost:62628/__modules/10.js?1480695948823:1​​'
```typescript
window.__moduleBundler.cache[10] = [function(__webpack_require__, module, exports) {import * as angular from 'angular';
import 'angular-translate';

let localeConfig = __webpack_require__(11);
import { EarlyExitDecoratorConfig } from './decorators/EarlyExitDecoratorConfig';
//...
let uuid = __webpack_require__(23);

angular.module('u-workflow.utils', ['pascalprecht.translate'])
    .config(EarlyExitDecoratorConfig)
    .factory('UUID', uuid.UUIDService);

}, window.__moduleBundler.deps];
```
Looks like I need to put info about not compiled modules to 'files' property of wallaby config, but not sure how.
### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    var wallabyWebpack = require('wallaby-webpack');
    var webpackConfig = require('./webpack.conf.js');
    webpackConfig.module.loaders.shift();
    webpackConfig.resolve.root = wallaby.projectCacheDir;
    webpackConfig.resolve.extensions = ['', '.js'];
    webpackConfig.entryPatterns = [
        'packages/components/**/test.js',
        'packages/components/**/*.spec.js'];

    var webpackPostprocessor = wallabyWebpack(webpackConfig);

    return {
        files: [
            {pattern: 'packages/components/**/src/**/*.html', load: false},
            {pattern: 'packages/components/**/src/**/*.css', load: false},
            {pattern: 'packages/components/**/src/**/*.js', load: false},
            {pattern: 'packages/components/**/src/**/*.ts', load: false},
            {pattern: 'packages/components/**/helper/**/*.html', load: false},
            {pattern: 'packages/components/**/helper/**/*.js', load: false},
            {pattern: 'packages/components/**/*.spec.js', ignore: true},
            {pattern: 'packages/components/**/*.spec.ts', ignore: true}
        ],

        tests: [
            {pattern: 'packages/components/**/*.spec.ts', load: false},
            {pattern: 'packages/components/**/*.spec.js', load: false}
        ],

        testFramework: 'jasmine',
        postprocessor: webpackPostprocessor,
        bootstrap: function () {
            window.__moduleBundler.loadTests();
        }
    };
};
```

My tsconfig.json
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "sourceMap": false,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "moduleResolution": "node",
        "isolatedModules": false,
        "declaration": false,
        "noImplicitAny": true,
        "noLib": false,
        "removeComments": true
    }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.7.2

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Hi,

Could you please update the sample repo https://github.com/risonipli/wallaby-webpack-typescript-issue, so I could reproduce the issue and have a look?

**Comment by ArtemGovorov** [comment]
Without the sample my guess would be that you need to include `package.json`files to your `files` list, as wallaby runs TS compiler on its cache (where all the listed files are copied to), so perhaps it's just missing that bit of data. Try this:

```javascript
...
files: [
            {pattern: 'packages/components/**/*.json', load: false},
             ...
]
```

**Comment by risonipli** [comment]
Hi, 

tried your suggestion, but no luck. Updated https://github.com/risonipli/wallaby-webpack-typescript-issue. Please run 'npm install' or 'yarn' first in order to allow 'postinstall.sh' script to create symbolic link.

**Comment by ArtemGovorov** [comment]
Thanks for updating the repo! Now I much better understand your setup. 

Got to say it's pretty unusual setup. I have never seen the mapping of a local folder with modules to `node_modules`, so that webpack can handle it as a module. Normally I see people adding their project folder's [to the `modulesDirectories`](https://webpack.github.io/docs/configuration.html#resolve-modulesdirectories) so that webpack looks up for the modules in the local project. But perhaps you have some other reasons for not using `modulesDirectories`, so I'm going to suggest two ways of making wallaby.js work.

Regardless of the way, `package.json` files have to be included into the `files` list, and you already know, wallaby runs TS compiler on its cache and renames `.ts` -> `.js` after the compilation, so a [small `preprocessor`](https://wallabyjs.com/docs/config/preprocessors.html) is required to modify the `package.json` files on the fly.

So the issue is that the module is in `node_modules` and wallaby doesn't process/compile/instrument the code in `node_modules`, basically expecting the code there to be ready for the production consumption (ie to contain compiled JS code, not TS code).

**The first way** to make it work is to just let webpack know that it should look up for modules in your `packages`  folder (in wallaby cache). The drawback of this way is that you'll need to also specify aliases for the modules, because you're importing `u-workflow.utils` and not just `utils` as in the folder structure.

```javascript
module.exports = function (wallaby) {
    var path = require('path');
    var wallabyWebpack = require('wallaby-webpack');
    var webpackConfig = require('./webpack.conf.js');
    webpackConfig.module.loaders.shift();
    webpackConfig.resolve.root = wallaby.projectCacheDir;
    // webpack will look up for modules in the wallaby cache 
    // (instrumented mirror of your local folder)
    webpackConfig.resolve.modulesDirectories = [
      path.join(wallaby.projectCacheDir, 'packages'), 'node_modules'
    ];
    // because you import a different (from a folder) name, the alias is required
    webpackConfig.resolve.alias = {
        'u-workflow.utils': 'utils'
    };
    webpackConfig.entryPatterns = [
        'packages/**/test.js',
        'packages/**/tests/unit/**/*.spec.js'];

    var webpackPostprocessor = wallabyWebpack(webpackConfig);

    return {
        files: [
            {pattern: 'packages/**/*.json', load: false}, // mentioned above
            {pattern: 'packages/**/src/**/*.html', load: false},
            {pattern: 'packages/**/src/**/*.css', load: false},
            {pattern: 'packages/**/src/**/*.js', load: false},
            {pattern: 'packages/**/src/**/*.ts', load: false}
        ],

        tests: [
            {pattern: 'packages/**/tests/unit/**/*.spec.ts', load: false},
            {pattern: 'packages/**/tests/unit/**/*.spec.js', load: false}
        ],

        testFramework: 'jasmine',
        // mentioned above
        preprocessors: {
            '**/*.json': file => file.content.replace('index.ts', 'index.js')
        },
        postprocessor: webpackPostprocessor,
        bootstrap: function () {
            window.__moduleBundler.loadTests();
        }
    };
};
```

**The second way** to make it work is to let wallaby know that some of your `node_modules` have to be processed/compiled/instrumented by adding them to the `files` list. The drawback of this way is that all files the `files` list are copied to the wallaby cache, so wallaby will be copying/compiling/instrumenting module files twice: from the `packages/utils` and from the `node_modules/u-workflow.utils`. Also, similar to specifying the aliases in the first approach, you'll obviously need to list modules in the `files` list.

```javascript
module.exports = function (wallaby) {
    var path = require('path');
    var wallabyWebpack = require('wallaby-webpack');
    var webpackConfig = require('./webpack.conf.js');
    webpackConfig.module.loaders.shift();
    webpackConfig.resolve.root = wallaby.projectCacheDir;
    // webpack will look up for modules in the wallaby cache 
    // (instrumented mirror of your local folder)
    webpackConfig.resolve.modulesDirectories = [
      path.join(wallaby.projectCacheDir, 'node_modules'), 'node_modules'
    ];
    webpackConfig.entryPatterns = [
        'packages/**/test.js',
        'packages/**/tests/unit/**/*.spec.js'];

    var webpackPostprocessor = wallabyWebpack(webpackConfig);

    return {
        files: [
            // copying the files to wallaby cache (so that wallaby can instrument them)
            {pattern: 'node_modules/u-workflow.utils/**', load: false},
            {pattern: 'packages/**/*.json', load: false},  // mentioned above
            {pattern: 'packages/**/src/**/*.html', load: false},
            {pattern: 'packages/**/src/**/*.css', load: false},
            {pattern: 'packages/**/src/**/*.js', load: false},
            {pattern: 'packages/**/src/**/*.ts', load: false}
        ],

        tests: [
            {pattern: 'packages/**/tests/unit/**/*.spec.ts', load: false},
            {pattern: 'packages/**/tests/unit/**/*.spec.js', load: false}
        ],

        testFramework: 'jasmine',
        // mentioned above
        preprocessors: {
            '**/*.json': file => file.content.replace('index.ts', 'index.js')
        },
        postprocessor: webpackPostprocessor,
        bootstrap: function () {
            window.__moduleBundler.loadTests();
        }
    };
};
```

Given the advantages/drawbacks of the approaches, I'd recommend to use the approach number one, if you can.

Hope it makes sense.

**Comment by risonipli** [comment]
Thanks again, Artem! Works like a charm!
