### ISSUE TITLE
Cannot Start Wallaby in VS2015

### ISSUE THREAD

**Issue by dapple16** [wallabyjs/public#912]
I downloaded Wallaby for Visual Studio 2015, and created the simple configuration file.  However, when clicked on the 'Start Wallaby.js'  I get a message at the bottom of the VS2015 is

'Wallaby.js: Failed to start runner, see the output window or log file for more details :('

And the output windows states:
'wallaby.js stopped'

The jasmine tests run fine.
It is not clear what is going wrong with starting wallaby, can you help?

(The PC that the VS2015 is running does not have the privilege to download anything from internet.)

**Comment by ArtemGovorov** [comment]
> (The PC that the VS2015 is running does not have the privilege to download anything from internet.)

This is an issue. Wallaby.js needs to download a few dependencies before it starts. Try connecting the machine to internet and do one wallaby.js run. After one run you may disconnect it. Alternatively, try following tis offline installation procedure: https://github.com/wallabyjs/public/issues/504#issuecomment-195117961

**Comment by dapple16** [comment]
This PC does not have privilege to connect to the internet, I followed your instruction as on #504 (comment) by downloading the zip files and copy/paste them in the .wallaby folder but it made no difference.

**Comment by ArtemGovorov** [comment]
> should I remove the 2.1.1 from this folder?

No, actually you'll need to download PhantomJs 2.1.1. I have update the comment to reflect it: https://github.com/wallabyjs/public/issues/504#issuecomment-195117961.

Try installing PhantomJs 2.1.1 (similar way you did for 1.9.8), and starting wallaby again. If it doesn't help, please attach the latest log file from `drive:\Users\%username%\AppData\Local\Temp\.wallaby\`.

**Comment by dapple16** [comment]
2016-12-21 15:11:11Z [1] Error Wallaby.Menu.StartRunnerCommand 0: Error occurred during selecting configuration project item.
System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.PlatformUI.UIHierarchyDTEHelpers.NodeFromName(IEnumerable`1 childNodes, String name, Boolean ignoreCase)
   at Microsoft.VisualStudio.PlatformUI.UIHierarchyMarshaler.UIHierarchy.GetItem(String Names)
   at Microsoft.VisualStudio.PlatformUI.UIHierarchyMarshaler.<>c__DisplayClass6_0.<GetItem>b__0()
   at Microsoft.VisualStudio.Shell.ThreadHelper.Invoke[TResult](Func`1 method)
   at Microsoft.VisualStudio.PlatformUI.UIHierarchyMarshaler.GetItem(String Names)
   at ‮‭‌⁯‬⁫⁯⁬​‪⁫‎⁮⁫​⁯⁬‬​⁭‌‍⁮​‬⁬‎⁮‍​⁬‏‏⁮⁯‏⁬‎⁬‮.Yv=qx(\*F0')^njN)(U\&\[2(FX.MoveNext()
2016-12-21 15:11:13Z [69] Error Wallaby.CoreProcess 0: Failed to start node process.
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at ‮⁬⁪⁯‫‎‎‎⁫‎‎‌‭​⁫‪⁮⁫⁪​‌‎‎​‪‫‬⁭‍‌⁬⁭‎‭‌​‮‎‌‮.‏‪‫‏​‌⁪⁫‎‎‭‌‭‪‏‌⁬⁯⁭⁭​‫‌⁬‬‌‭‍⁯⁫‌⁬​‪⁫‪⁬‪‌‮()
2016-12-21 15:11:13Z [1] Error Wallaby.Runner 0: Failed to start Runner.
System.Exception: Port must be greater than zero.
   at ⁯⁯⁭‭‎‏⁪‎‪‏‭‪⁫‏‫‪⁭‎⁮‪⁬‭‭‬​‪​⁫⁫⁯⁭⁬‎⁭⁮‎⁮⁯‫‮.odN}zH"Hs!L=_YM\&rAamI^n.MoveNext()
2016-12-21 15:11:13Z [104] Error Wallaby.CoreProcess 0: Error stopping core process.
System.InvalidOperationException: No async read operation is in progress on the stream.
   at System.Diagnostics.Process.CancelErrorRead()
   at ‮⁬⁪⁯‫‎‎‎⁫‎‎‌‭​⁫‪⁮⁫⁪​‌‎‎​‪‫‬⁭‍‌⁬⁭‎‭‌​‮‎‌‮.‌⁯⁪⁭⁬⁫‮⁬⁬‬‭‫⁯‌⁪‬⁫‌‮‍‮⁯‪‮‎⁯⁯‎⁯‪‎⁬‎‭‬‍⁭⁮‏‮()

**Comment by ArtemGovorov** [comment]
Thanks. It looks like the downloaded version of node.js is either not correct or not located correctly. 

Could you please make sure that you have downloaded the correct node.js version for your system (32 bit version vs 64 bit) and also check that you've placed it where the comment says: https://github.com/wallabyjs/public/issues/504#issuecomment-195117961. 

Could you please also attach a screenshot of your fully expanded `drive:\Users\%username%\.wallaby` folder?

**Comment by dapple16** [comment]
I have:

'C:\Users\jt176\.wallaby\core'
'C:\Users\jt176\.wallaby\dependencies\nodejs\4.2.2'
'C:\Users\jt176\.wallaby\dependencies\phantomjs\2.1.1'

**Comment by ArtemGovorov** [comment]
Can you successfully run `C:\Users\jt176.wallaby\dependencies\nodejs\4.2.2\node.exe` file from your command line?

**Comment by dapple16** [comment]
Nop! cannot start or run due to incompatibility with 64 bit version of Windows.

**Comment by ArtemGovorov** [comment]
Ok, we're getting somewhere. As I have been asking, could you please make sure that you have downloaded the correct node.js version for your system (32 bit version vs 64 bit version). The https://github.com/wallabyjs/public/issues/504#issuecomment-195117961 comment specifies where to download the correct version (32 bit version vs 64 bit version).

**Comment by dapple16** [comment]
thanks, x64 bit node.exe fixed the problem, much appreciated.
