### ISSUE TITLE
ReactNative+jest without .babelrc file errors

### ISSUE THREAD

**Issue by DanielZlotin** [wallabyjs/public#914]
Errors when running wallaby using jest **without** a `.babelrc` file in the project root.

Everything works when having a `.babelrc` file in the project root. 
Using the jest CLI in node works with or without the `.babelrc` file.

### Issue description or question

Because of the way the react-native packager works with babel, we can't add a `.babelrc` file to the project root if we want to avoid serious runtime issues in our apps. 

The way we are still able to use babel is by adding the `babel` config into package.json and specifying the env `BABEL_ENV` before running jest.
For example:
### package.json:
```javascript
  "babel": {
    "env": {
      "test": {
        "presets": [
          "react-native"
        ]
      }
    }
  },
  "scripts": {
    "test": "BABEL_ENV=test jest"
  }
```

### Wallaby Console:
```
wallaby.js started
core v1.0.334
Wallaby App available at: http://wallabyjs.com/app/#/files
console.log:  PASS  ../../Library/Caches/WebStorm2016.3/wallaby/projects/ad67258db0f4fcee/instrumented/src2/containers/ContainerStore.test.js

console.log: 

console.log:  PASS  ../../Library/Caches/WebStorm2016.3/wallaby/projects/ad67258db0f4fcee/instrumented/src2/env.test.js

console.log: 

Runtime error: TypeError: Assignment to constant variable.
    at Object.setGlobalHandler (/Users/danielzl/dev/react-native-navigation/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/error-guard.js:31:20)
    at Object.<anonymous> (/Users/danielzl/dev/react-native-navigation/node_modules/react-native/Libraries/Core/InitializeCore.js:118:12)
    at Runtime._execModule (/Users/danielzl/dev/react-native-navigation/node_modules/jest-runtime/build/index.js:441:13)
    at Runtime.requireModule (/Users/danielzl/dev/react-native-navigation/node_modules/jest-runtime/build/index.js:297:14)
    at Runtime.requireModuleOrMock (/Users/danielzl/dev/react-native-navigation/node_modules/jest-runtime/build/index.js:366:19)
    at Object.<anonymous> (/Users/danielzl/dev/react-native-navigation/node_modules/react-native/Libraries/Renderer/src/renderers/native/ReactNativeDefaultInjection.js:20:1)
    at Runtime._execModule (/Users/danielzl/dev/react-native-navigation/node_modules/jest-runtime/build/index.js:441:13)
    at Runtime.requireModule (/Users/danielzl/dev/react-native-navigation/node_modules/jest-runtime/build/index.js:297:14)
    at Runtime._generateMock (/Users/danielzl/dev/react-native-navigation/node_modules/jest-runtime/build/index.js:510:34)
    at Runtime.requireMock (/Users/danielzl/dev/react-native-navigation/node_modules/jest-runtime/build/index.js:356:43)
console.log:  FAIL  ../../Library/Caches/WebStorm2016.3/wallaby/projects/ad67258db0f4fcee/instrumented/src2/containers/ContainerRegistry.test.js

console.log:   ● Test suite failed to run

    TypeError: Assignment to constant variable.
      
      at Object.setGlobalHandler (node_modules/react-native/packager/react-packager/src/Resolver/polyfills/error-guard.js:31:20)
      at Object.<anonymous> (node_modules/react-native/Libraries/Core/InitializeCore.js:118:12)
      at Object.<anonymous> (node_modules/react-native/Libraries/Renderer/src/renderers/native/ReactNativeDefaultInjection.js:20:1)


console.log:  PASS  ../../Library/Caches/WebStorm2016.3/wallaby/projects/ad67258db0f4fcee/instrumented/src2/commands/Commands.test.js

console.log: 

console.log:  PASS  ../../Library/Caches/WebStorm2016.3/wallaby/projects/ad67258db0f4fcee/instrumented/src2/containers/PropsStore.test.js

console.log: 

console.log:  FAIL  ../../Library/Caches/WebStorm2016.3/wallaby/projects/ad67258db0f4fcee/instrumented/src2/Navigation.test.js

console.log:   ● Navigation › exposes static commands

    TypeError: Assignment to constant variable.
      
      at Object.setGlobalHandler (node_modules/react-native/packager/react-packager/src/Resolver/polyfills/error-guard.js:31:20)
      at Object.<anonymous> (node_modules/react-native/Libraries/Core/InitializeCore.js:118:12)
      at Object.<anonymous> (node_modules/react-native/Libraries/Renderer/src/renderers/native/ReactNativeDefaultInjection.js:20:1)

  ● Navigation › exposes static commands

    TypeError: Cannot read property 'registerContainer' of undefined
      
      at Object.<anonymous> (../../Library/Caches/WebStorm2016.3/wallaby/projects/ad67258db0f4fcee/instrumented/src2/Navigation.test.js:23:19)
      at Object.e.length.arguments.(anonymous function) (../../Library/Caches/WebStorm2016.3/wallaby/wallaby/runners/node/jest@0.4.3/jasmine2Initializer.js:14:2015)

  ● Navigation › delegates register container to container registry

    expect(jest.fn())[.not].toHaveBeenCalled()
    
    jest.fn() value must be a mock function or spy.
    Received: undefined
      
      at Object.<anonymous> (../../Library/Caches/WebStorm2016.3/wallaby/projects/ad67258db0f4fcee/instrumented/src2/Navigation.test.js:43:70)
      at Object.e.length.arguments.(anonymous function) (../../Library/Caches/WebStorm2016.3/wallaby/wallaby/runners/node/jest@0.4.3/jasmine2Initializer.js:14:2015)


Finished executing 10 affected test(s)

```

### Wallaby.js configuration file

```javascript
/*eslint-disable*/
'use strict';
const babelOptions = require('./package.json').babel.env.test;
module.exports = function(wallaby) {
  return {
    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    files: [
      'package.json',
      'src2/**/*.js',
      '!src2/**/*.test.js'
    ],

    tests: [
      'src2/**/*.test.js'
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel(babelOptions)
    },

    setup: function(w) {
      require('babel-polyfill');
      w.testFramework.configure(require('./package.json').jest);
    }
  };
};

```

### Code editor or IDE name and version

WebStorm 2016.3

### OS name and version

OSX Sierra 10.12.2

**Comment by ArtemGovorov** [comment]
> The way we are still able to use babel is by adding the babel config into package.json and specifying the env BABEL_ENV before running jest.

You'll need to do the [same in wallaby config](https://wallabyjs.com/docs/integration/es-next.html#babel-environment).

```javascript
/*eslint-disable*/
'use strict';
...
process.env.BABEL_ENV = 'test'; // <---
module.exports = function(wallaby) {
  ...
};
```

If the issue persists after changing the config, try clearing `jest` cache by deleting the `jest` folder in your tmp folder:
```
node
> process.env.TMPDIR
```

**Comment by DanielZlotin** [comment]
Works! thanks!
