### ISSUE TITLE
Cannot compile when code includes optional parameters with "= value"

### ISSUE THREAD

**Issue by mvonballmo** [wallabyjs/public#920]
### Issue description or question

When I changed the optional-parameter syntax from using a ? to using "= value", Wallaby failed to compile the TypeScript whereas PHPStorm was able to do so. 

This works fine for both PHPStorm and Wallaby.

`private createFinalErrorToken(errorMessage: string, useLastToken?: boolean)`

This works only for PHPStorm (I'm not sure with which version of TypeScript this syntax is supported...):

`private createFinalErrorToken(errorMessage: string, useLastToken = false)`

Instead, for the above version, Wallaby shows this error message in the "Failing Tests" console:

`SyntaxError: Unexpected token =
	at Object.<anonymous> test/LowLevelTokenizerTests.ts:6`

In the "Wallaby Console", I found the following:

```
wallaby.js started
core v1.0.335
Execution progress: 50 tests
Finished executing 64 affected test(s)
Execution progress: 50 tests
Execution progress: 50 tests
Finished executing 64 affected test(s)
Runtime error: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (./test/LowLevelTokenizerTests.js:6:43)
    at Module._compile (module.js:435:26)
Runtime error: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (./test/LowLevelTokenizerTests.js:6:43)
    at Module._compile (module.js:435:26)
Runtime error: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (./test/LowLevelTokenizerTests.js:6:43)
    at Module._compile (module.js:435:26)
Runtime error: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (./test/LowLevelTokenizerTests.js:6:43)
    at Module._compile (module.js:435:26)
Runtime error: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (./test/LowLevelTokenizerTests.js:6:43)
    at Module._compile (module.js:435:26)
Runtime error: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (./test/LowLevelTokenizerTests.js:6:43)
    at Module._compile (module.js:435:26)
Execution progress: 50 tests
Finished executing 64 affected test(s)
Runtime error: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (./test/LowLevelTokenizerTests.js:6:43)
    at Module._compile (module.js:435:26)
Runtime error: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (./test/LowLevelTokenizerTests.js:6:43)
    at Module._compile (module.js:435:26)
Runtime error: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (./test/LowLevelTokenizerTests.js:6:43)
    at Module._compile (module.js:435:26)
```

I was under the impression that Wallaby used the TypeScript compiler under node_modules, as the JetBrains tools now do, as well? The full source of my project is available on [GitHub](https://github.com/mvonballmo/ts-earthli-markup-language).

### Wallaby.js configuration file

```javascript
    "files": [
        "lib/**/*.ts"
    ],
    "tests": [
        "test/**/*Tests.ts"
    ],
    "testFramework": "mocha",
    "env": {
        "type": "node"
    }
```

### Code editor or IDE name and version

PHPStorm 2016.3.2

### OS name and version

MacOS Sierra 10.12.1

**Comment by ArtemGovorov** [comment]
> I was under the impression that Wallaby used the TypeScript compiler under node_modules

It is correct.

I think the issue is not with the TypeScript version, but with the [node.js version used by default by wallaby.js in PhpStorm](https://wallabyjs.com/docs/integration/node.html#node-version). Your `tsconfig.json` compiles the code to ES6 and node 4.x doesn't fully support ES6. 

Adding the `runner` config value that runs your system default node should fix it for you:

```
    "files": [
        "lib/**/*.ts"
    ],
    "tests": [
        "test/**/*Tests.ts"
    ],
    "testFramework": "mocha",
    "env": {
        "type": "node",
        "runner": "node"
    }
```

**Comment by mvonballmo** [comment]
Thank you! That did the trick. Now that you mention it, I remember reading in the documentation that Wallaby uses the IntelliJ Node.js version and that most installations won't need to change it. Thanks for the quick answer and for the excellent product.
