### ISSUE TITLE
Wallaby with TS on multiple **/*.ts loophole...

### ISSUE THREAD

**Issue by Mech45** [wallabyjs/public#927]
### Issue description or question
Hi,
I discovered wallaby today, and i tried it on a simple base project TS based.
When I launch it for the first time, it takes several seconds to fall on timeout statement.

`​​​​​[Info]​​​​​   at /Users/stevenleclerc/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.37/wallaby/server.js:16:26973
​​​​​[Info]​​​​​   at Timeout._onTimeout (/Users/----/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.37/wallaby/server.js:16:26575)
​​​​​[Info]​​​​​   at ontimeout (timers.js:365:14)
​​​​​[Info]​​​​​   at tryOnTimeout (timers.js:237:5)
​​​​​[Info]​​​​​   at Timer.listOnTimeout (timers.js:207:5)
​​​​​[Info]​​​​​ From previous event:
​​​​​[Info]​​​​​   at Timeout._onTimeout `

And when i try the second time, he never stops (until I kill vscode...).
On the console we can see repeatedly this :

`[Info]​​​​​   at getTypeAtFlowNode (/Users/-----/Documents/Dev-Projects/projectTest/node_modules/typescript/lib/typescript.js:32839:32)
​​​​​[Info]​​​​​   at getTypeAtFlowLoopLabel (/Users/-----/Documents/Dev-Projects/projectTest/node_modules/typescript/lib/typescript.js:33050:36)
​​​​​[Info]​​​​​   at getTypeAtFlowNode (/Users/-----/Documents/Dev-Projects/projectTest/node_modules/typescript/lib/typescript.js:32858:29)
​​​​​[Info]​​​​​   at getFlowTypeOfReference (/Users/-----/Documents/Dev-Projects/projectTest/node_modules/typescript/lib/typescript.js:32814:51)
​​​​​[Info]​​​​​   at checkIdentifier (/Users/-----/Documents/Dev-Projects/projectTest/node_modules/typescript/lib/typescript.js:33538:28)
​​​​​[Info]​​​​​   at checkExpressionWorker (/Users/-----/Documents/Dev-Projects/projectTest/node_modules/typescript/lib/typescript.js:37914:28)
​​​​​[Info]​​​​​   at checkExpression (/Users/-----/Documents/Dev-Projects/projectTest/node_modules/typescript/lib/typescript.js:37894:42)
​​​​​[Info]​​​​​   at checkExpressionCached (/Users/-----/Documents/Dev-Projects/projectTest/node_modules/typescript/lib/typescript.js:37793:38)
​​​​​[Info]​​​​​   at checkSpreadExpression (/Users/-----/Documents/Dev-Projects/projectTest/node_modules/typescript/lib/typescript.js:34449:39)
​​​​​[Info]​​​​​   at checkExpressionWorker (/Users/-----/Documents/Dev-Projects/projectTest/node_modules/typescript/lib/typescript.js:37974:28)
​​​​​[Info]​​​​​   at checkExpression `

When I tried to set my transcripted .js file all seems good... ! my typescript compilator fall in the loop and I don't know why...

### Wallaby.js configuration file

I put this little base project here : https://github.com/Mech45/loopHole-wallaby.git

### Code editor or IDE name and version

Visual Studio Code  1.8.1 (1.8.1)

### OS name and version

OSX 10.12

I really want to use your product, its seems to be excellent, maybe I've made some mistakes...

Thanks a lot, and sorry for my english :s

**Comment by Mech45** [comment]
Great ! thanks for the help ;)
