### ISSUE TITLE
Wallaby will not start, "Unexpected token ! in JSON at position 0"

### ISSUE THREAD

**Issue by grantbowering** [wallabyjs/public#954]
### Issue description or question
After a prompt to install an upgrade to wallaby core last week (which may or may not be related, but nothing else has changed as far as I can see), it now displays the following: 

```
​​[Error] SyntaxError: Unexpected token ! in JSON at position 0​​
​​[Error]     at JSON.parse (<anonymous>)​​
​​[Error]     at new SourceMapConsumer (c:\projectbuildpath\node_modules\source-map\lib\source-map-consumer.js:17:22)​​
​​[Error]     at mapSourcePosition (c:\projectbuildpath\node_modules\source-map-support\source-map-support.js:163:14)​​
​​[Error]     at wrapCallSite (c:\projectbuildpath\node_modules\source-map-support\source-map-support.js:330:20)​​
​​[Error]     at c:\projectbuildpath\node_modules\source-map-support\source-map-support.js:365:26​​
​​[Error]     at Array.map (native)​​
​​[Error]     at Function.prepareStackTrace (c:\projectbuildpath\node_modules\source-map-support\source-map-support.js:364:24)​​
​​[Error]     at trackRejection (C:\Users\myprofilepath\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.30\wallaby\node_modules\q\q.js:988:32)​​
​​[Error]     at reject (C:\Users\myprofilepath\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.30\wallaby\node_modules\q\q.js:1044:5)​​
​​[Error]     at self.promiseDispatch.done (C:\Users\myprofilepath\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.30\wallaby\node_modules\q\q.js:816:30)​​
​​[Error]     at Promise.promise.promiseDispatch (C:\Users\myprofilepath\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.30\wallaby\node_modules\q\q.js:749:13)​​
​​[Error]     at C:\Users\myprofilepath\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.30\wallaby\node_modules\q\q.js:509:49​​
​​[Error]     at flush (C:\Users\myprofilepath\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.30\wallaby\node_modules\q\q.js:108:17)​​
​​[Error]     at _combinedTickCallback (internal/process/next_tick.js:67:7)​​
​​[Error]     at process._tickCallback (internal/process/next_tick.js:98:9)​​
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.343
```
It does not proceed further.

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackConfig = require('./webpack.config');
var path = require('path');

webpackConfig.module.loaders = [];
webpackConfig.resolve.extensions = ['', '.js', '.jsx'];
webpackConfig.entry = {};
delete webpackConfig.output;
delete webpackConfig.devServer;

// To support Enzyme
webpackConfig.module.loaders.push({
	test: /\.json$/,
	loader: 'json-loader'
});

webpackConfig.externals = webpackConfig.externals || {};
webpackConfig.externals.jsdom = 'window';
webpackConfig.externals.cheerio = 'window';
webpackConfig.externals['react/addons'] = true;
webpackConfig.externals['react/lib/ExecutionEnvironment'] = true;
webpackConfig.externals['react/lib/ReactContext'] = true;

// Per: https://github.com/davezuko/react-redux-starter-kit/issues/327
webpackConfig.node = webpackConfig.node || {};
webpackConfig.node.fs = 'empty';

module.exports = function (wallaby) {
	// Per https://wallabyjs.com/docs/integration/webpack.html#absolute-paths-for-wallaby-cache-folder
	webpackConfig.resolve.root = [path.join(wallaby.projectCacheDir, 'App')];

	var webpackPostprocessor = wallabyWebpack(webpackConfig);

	return {

		files: [
			{ pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false },
			{ pattern: 'node_modules/json.date-extensions/json.date-extensions.js', instrument: false },
			{ pattern: 'Scripts/testSetup.js', instrument: false },
			{ pattern: 'App/**/*.ts?(x)', load: false },
			{ pattern: 'App/**/*.spec.ts?(x)', ignore: true }
		],

		tests: [
			{ pattern: 'App/**/*.spec.ts?(x)', load: false }
		],

		testFramework: 'mocha',

		compilers: {
			'App/**/*.ts*': wallaby.compilers.typeScript({
				module: 'es6'
			})
		},

		preprocessors: {
			'App/**/*.js': function (file) {
				return require('babel-core').transform(
					file.content, { sourceMap: true, presets: ['es2015', 'react'] });
			}
		},

		postprocessor: webpackPostprocessor,

		setup: function () {
			window.__moduleBundler.loadTests();
		},

		debug: false,
		hints: {
			ignoreCoverage: / coverage ignore next /
		}
	};
};
```

### tsconfig.json
```javascript
{
	"compilerOptions": {
		"moduleResolution": "node",
		"target": "es6",
		"jsx": "preserve",
		"experimentalDecorators": true,
		"sourceMap": true,
		"skipDefaultLibCheck": true,
		"allowSyntheticDefaultImports": true,
		"noImplicitAny": true,
		"baseUrl": ".",
		"paths": {
			"*": [
				"App/*",
				"node_modules/*",
				"App/typeOverrides/*"
			]
		},
		"typeRoots": [ "./node_modules/@types" ]
	},
	"awesomeTypescriptLoaderOptions": {
		"useBabel": true,
		"useCache": true
	},
	"exclude": [
		"node_modules"
	]
}
```

### webpack.config.js 
```javascript
/* eslint-disable no-var, strict, prefer-arrow-callback */
'use strict';

var path = require('path');
var webpack = require('webpack');
var progressPlugin = require('webpack/lib/ProgressPlugin');
var checkerPlugin = require('awesome-typescript-loader').CheckerPlugin;

function progressHandler(percentage, msg) {

	if (percentage < 1) {
		percentage = Math.floor(percentage * 100);
		msg = percentage + '% ' + msg;
		if (percentage < 100) {
			msg = ' ' + msg;
		}
		if (percentage < 10) {
			msg = ' ' + msg;
		}
	}

	process.stdout.write('                                              \r' + msg + '\r');
}

module.exports = {
	cache: true,
	entry: {
		main: './App/main.tsx',
		vendor: [
			'isomorphic-fetch',
			'babel-polyfill',
			'bootstrap',
			'react',
			'react-bootstrap',
			'react-bootstrap-table',
			'react-datepicker',
			'react-dom',
			'react-measure',
			'react-router',
			'react-router-bootstrap',
			'redux',
			'redux-thunk',
			'react-router-redux',
			'moment',
			'moment-business',
			'seamless-immutable',
			'classnames',
            'json.date-extensions'
		]
	},
	output: {
		path: path.resolve(__dirname, './dist/scripts'),
		filename: '[name].js',
		chunkFilename: '[chunkhash].js'
	},
	module: {
		loaders: [
			{
				test: /\.ts(x?)$/,
				exclude: /node_modules/,
				loader: 'babel-loader?presets[]=es2015&presets[]=react!awesome-typescript-loader'
			},
			{
				test: /\.js$/,
				exclude: /node_modules/,
				loader: 'babel',
				query: {
					presets: ['es2015', 'react']
				}
			},
			{ test: /\.css$/, loader: 'style!css' }
		]
	},
	plugins: [
		// Maps these identifiers to the jQuery package (because Bootstrap expects it to be a global variable)
		new webpack.ProvidePlugin({ $: 'jquery', jQuery: 'jquery' }),
		new progressPlugin(progressHandler),
        new checkerPlugin()
	],
	resolve: {
		// Add `.ts` and `.tsx` as a resolvable extension.
		extensions: ['', '.webpack.js', '.web.js', '.ts', '.tsx', '.js'],
		root: [
			path.resolve('./App'),
			path.resolve('./node_modules')
		]
	},
	devServer: {
		contentBase: '.',
		host: 'localhost',
		port: 9000
	}
};
```

### Code editor or IDE name and version

Visual Studio 2015 u3
Visual Studio Code v1.8.1

### OS name and version

Windows 8.1
Windows 10

**Comment by ArtemGovorov** [comment]
It's a known issue with source-map and some webpack loaders:
https://github.com/wallabyjs/public/issues/863
https://github.com/wallabyjs/public/issues/726#issuecomment-237760537
(I think `awesome-typescript-loader` in your case).
This should fix it for you:

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var Module = require('module').Module;
var modulePrototype = Module.prototype;
var originalRequire = modulePrototype.require;
modulePrototype.require = function (filePath) {
  if (filePath === 'source-map-support') {
    return {install: () => {}};
  }
  return originalRequire.call(this, filePath);
};

var webpackConfig = require('./webpack.config');

modulePrototype.require = originalRequire;

// the rest of your config
```

**Comment by grantbowering** [comment]
...yep, confirm fix.  
Sorry Artem, I'm not sure how I missed the previous issues!  My search-fu is usually stronger ;)  
Thanks for the fix!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
