### ISSUE TITLE
Upgrading angularCli stops wallaby from running.

### ISSUE THREAD

**Issue by masimplo** [wallabyjs/public#981]
### Issue description or question
Using angular-cli 1.0.0-beta.22 tests run fine
Upgrading from angular-cli-1.0.0-beta.22 to angular-cli 1.0.0-beta.24 and above results to ` Can't resolve 'angular2-template-loader` error:

> 0 failing tests, 0 passing​​​​​
> Error: Cannot find module 'undefined'​​
> ​​Entry module not found: Error: Can't resolve 'angular2-template-loader' in '/Users/michael/Repos/'EntryModuleNotFoundError: Entry module not found: Error: Can't resolve 'angular2-template-loader' in '/Users/michael/Repos'​​
> ​​  at Compilation.<anonymous> (/Users/michael/Repos/node_modules/webpack/lib/Compilation.js:366:28)​​
> ​​  at /Users/michael/Repos/node_modules/webpack/lib/NormalModuleFactory.js:235:19​​
> ​​  at onDoneResolving
### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/wallaby-test.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      { test: /\.css$/, loader: 'raw-loader' },
      { test: /\.html$/, loader: 'raw-loader' },
      { test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/ },
      { test: /\.json$/, loader: 'json-loader' },
      { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
      { test: /\.less$/, loaders: ['raw-loader', 'less-loader'] },
      { test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader'] },
      { test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000' }
    ]
  }
});

var compilerOptions = require('./src/tsconfig.test.json').compilerOptions;

module.exports = function (wallaby) {

  return {
    files: [
      { pattern: 'package.json', load: false },
      { pattern: 'src/**/*.ts', load: false },
      { pattern: 'src/**/*.d.ts', ignore: true },
      { pattern: 'src/**/*.css', load: false },
      { pattern: 'src/**/*.less', load: false },
      { pattern: 'src/**/*.sass', load: false },
      { pattern: 'src/**/*.scss', load: false },
      { pattern: 'src/**/*.html', load: false },
      { pattern: 'src/**/*spec.ts', ignore: true }
    ],

    tests: [
      { pattern: 'src/**/*spec.ts', load: false }
    ],

    testFramework: 'jasmine',

    env: {
      //kind: 'electron',
      runner: require('phantomjs-prebuilt').path,
      params: { runner: '--web-security=false' }
    },

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.8.1

### OS name and version
OSX 10.12.2

**Comment by ArtemGovorov** [comment]
There was a change in the angular-cli that requires one more configuration step. As specified in [the repo readme](https://github.com/wallabyjs/ngCliWebpackSample/#wallabyjs), you need to:
```
npm install angular2-template-loader --save-dev
```
