### ISSUE TITLE
Unexpected token on import(); in react-boilerplate

### ISSUE THREAD

**Issue by joshmeads** [wallabyjs/public#997]
I'm trying to add a wallaby config for [react-boilerplate](https://github.com/mxstbr/react-boilerplate). However, they're using dynamic import() statements. Webpack & babel handle them fine, but wallaby seems to be failing on them.

Any insights? Thanks

Error message:
```
Failed to parse app/app.js, SyntaxError: Unexpected token (97:12)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

The section where it is failing:
```javascript
if (!window.Intl) {
  (new Promise((resolve) => {
    resolve(import('intl')); // line 97
  }))
    .then(() => Promise.all([
      import('intl/locale-data/jsonp/en.js'),
    ]))
    .then(() => render(translationMessages))
    .catch((err) => {
      throw err;
    });
} else {
  render(translationMessages);
}
```

### Wallaby.js configuration file

```javascript
const wallabyWebpack = require('wallaby-webpack');
const webpackConfig = require('./internals/webpack/webpack.dev.babel');
const webpackPostprocessor = wallabyWebpack(webpackConfig);

module.exports = (wallaby) => ({
  files: [
    { pattern: 'app/**/*.js', load: false },
  ],

  tests: [
    { pattern: 'app/**/__tests__/*.test.js', load: false },
  ],

  env: {
    type: 'node',
    runner: 'node',
  },

  testFramework: 'jest',

  compilers: {
    '**/*.js': wallaby.compilers.babel(require('./package.json').babel), // eslint-disable-line global-require
  },

  postprocessor: webpackPostprocessor,

  setup() {
    const jestConfig = require('./package.json').jest; // eslint-disable-line global-require
    jestConfig.rootDir = wallaby.projectCacheDir;
    wallaby.testFramework.configure(jestConfig);
    window.__moduleBundler.loadTests(); // eslint-disable-line
  },

});

```

# IDE and OS
Atom v1.12.6
OSX Sierra

# Jest Config
```json
"jest": {
    "collectCoverageFrom": [
      "app/**/*.{js,jsx}",
      "!app/**/*.test.{js,jsx}",
      "!app/*/RbGenerated*/*.{js,jsx}",
      "!app/app.js",
      "!app/routes.js"
    ],
    "coverageThreshold": {
      "global": {
        "statements": 98,
        "branches": 91,
        "functions": 98,
        "lines": 98
      }
    },
    "moduleDirectories": [
      "node_modules",
      "app"
    ],
    "moduleNameMapper": {
      ".*\\.(css|less|styl|scss|sass)$": "<rootDir>/internals/mocks/cssModule.js",
      ".*\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/internals/mocks/image.js"
    },
    "setupTestFrameworkScriptFile": "<rootDir>/internals/testing/test-bundler.js",
    "testRegex": "__tests__/.*\\.test\\.js$"
  },
```

# Babel Config
```json
"babel": {
    "presets": [
      [
        "latest",
        {
          "es2015": {
            "modules": false
          }
        }
      ],
      "react",
      "stage-0"
    ],
    "env": {
      "production": {
        "only": [
          "app"
        ],
        "plugins": [
          "transform-react-remove-prop-types",
          "transform-react-constant-elements",
          "transform-react-inline-elements"
        ]
      },
      "test": {
        "plugins": [
          "transform-es2015-modules-commonjs",
          "dynamic-import-node"
        ]
      }
    }
  },
```

**Comment by ArtemGovorov** [comment]
First of all, you don't need webpack, Jest (and wallaby running Jest) doesn't need it, so I got rid of it.

I've also cleaned up the files/tests patterns to reflect the repo structure (there're no `__tests__` folders there). 

And finally [added the setting to let babel know that the `test` environment](https://wallabyjs.com/docs/integration/es-next.html#babel-environment) should be used (the fist line of the config below). It was causing the error that you've been observing and have reported.

Here's the working config for the react-boilerplate repo:

```javascript
process.env.BABEL_ENV = 'test';

module.exports = (wallaby) => ({
  files: [
    'app/**/*.js',
    'app/**/*.json',
    'package.json',
    '!app/**/*.test.js'
  ],

  tests: [
    'app/**/*.test.js'
  ],

  env: {
    type: 'node',
    runner: 'node',
  },

  testFramework: 'jest',

  compilers: {
    '**/*.js': wallaby.compilers.babel(require('./package.json').babel), // eslint-disable-line global-require
  },

  setup() {
    const jestConfig = require('./package.json').jest; // eslint-disable-line global-require
    wallaby.testFramework.configure(jestConfig);
  },

});
```

Let me know if the config is working for you.

**Comment by joshmeads** [comment]
Thank you very much Artem, that works great!

The __tests__ was my own preference.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

> The tests was my own preference.

I thought so, but just in case :)
